### ISSUE TITLE
Sample User error

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1000]
Trying to ingest the sample users ends up being unable to ingest anything without proper logging.

There are some topics that might need fixing:
- Should we use the proper generated `User` model instead of a custom model in ingestion/models? That might get harder to maintain if we update the endpoint info.
- in `sink/metadata_rest` at `write_users` we have an `except: pass`, which silently covers issues. This should log the proper information.

With a fresh branch from `main`, we get the following error:

```
Unrecognized field "isbot" (class org.openmetadata.catalog.api.teams.CreateUser), not marked as ignorable (9 known properties: "isAdmin", "teams", "timezone", "name", "description", "displayName", "profile", "email", "isBot"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 6, column: 19] (through reference chain: org.openmetadata.catalog.api.teams.CreateUser["isbot"])
```

Thanks

**Comment by harshach** [comment]
Thanks for filing this. we should be using CreateUserEntityRequest and CreateTeamEntityRequest. 
@ayush-shah can you take this up.
