### ISSUE TITLE
Duplicate glossaries

### ISSUE THREAD

**Issue by knoerregaard** [open-metadata/OpenMetadata#10008]
At the moment I am not able to duplicate glossaries

I would like to be able to duplicate glossaries and their children. Mark the new glossary with "- copy"

**Comment by harshach** [comment]
@knoerregaard you can export a glossary and change the name and import as a new one. Will that work?

**Comment by sureshms** [comment]
Glossary CSV import and export is the best way to do this. Marking this as resolved.
