### ISSUE TITLE
Mark glossary and terms as "Abstract"

### ISSUE THREAD

**Issue by knoerregaard** [open-metadata/OpenMetadata#10006]
** Problem statement **
I am relying on ISA88 standard that determines som meta classes for my data objects. ISA 88 describes Enterprise, Site, Area, Process, Unit, Equipment Modul and Control Module. There is a certain relationship between these classes. There is May and Must relationsship depending of the class. These meta classes could be regarded as Abstract types. They describe rules. Other standard could be important to describe as well.

** Solution **
I would like to have the opportunity to define Meta classes that act as abstract types. Then have a glossery and terms that inherits from these abstract "classes" / glossary and terms.
The abstract types only live inside the glossary. It should not be possible to define columns with abstract type.

The relationship between terms in an abstract glossary should be marked with Must Have or May have (maybe other relationtypes as weel). This should reflect the concrete glossary in a way that reflects the rules of the abstract Glossary.

At the moment I have the opportunity to use the Related Terms feature. But it does not add the constrain that I would like to give the users. The constrains should be inherited from the "abstract" glossary. 

An example could be that a Site may contain Areas. Another example could be that a ProcessCell MUST have one or more Units.

On the following picture you will see an example of a glossary that contains concrete classes and a glossary that contains abstract classes. ISA 88 glossary is the abstract and Company A standard is the concrete class

![image](https://user-images.githubusercontent.com/4918661/215484282-00efa3bf-f48d-46c4-bfe6-d213c8398144.png)

Thanks

**Comment by harshach** [comment]
@sureshms thoughts?
