### ISSUE TITLE
Usage Ingestion not showing all pulled usage data in the UI

### ISSUE THREAD

**Issue by NoelAramis** [open-metadata/OpenMetadata#10016]
**Affected module**
The bug affects the UI.

**Describe the bug**
When running the Usage Ingestion (for PostgreSQL), sometimes not all queries will show in the UI under Queries tab, despite the fact that they were ran on the database. Also, query count at the top is wrong (it seems to multiply with the number of ingestion runs).
![image](https://user-images.githubusercontent.com/6871756/215541020-a14bee22-9890-45f2-ba5b-91e15dc00367.png)
![image](https://user-images.githubusercontent.com/6871756/215541884-5fff8870-5f0d-49c3-8529-729d08fa6273.png)
![image](https://user-images.githubusercontent.com/6871756/215541605-2dba6714-38f1-4edd-88a6-879a6d9dc5dd.png)

**To Reproduce**

- Create a test Postgres DB using a docker compose, adding: `command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200` in the .yml file
- Create a new database, and enable pg_stat_statements using `CREATE EXTENSION pg_stat_statements`
- Create some tables, insert some data so that the tables are not empty
- Call Metadata ingestion to pull database and table metadata into OM
- Call several different SELECT statements on the existing tables
- Call Usage ingestion with increased Result limit to 1.000.000.

**Expected behavior**
The expected behavior is seeing all Usage data (all queries ran on the DB) in the UI.
In this case, Usage data was complete for all tables except for a table named `roles` for which only partial query data was shown (see above in the **Describe the bug** section).
The log for Usage Ingestion with DEBUG mode on shows several instances of `DEBUG - Lineage with SqlFluff failed for the [postgres] query` error for many queries, including those that were shown in the UI and those that were not.
Also, query count at the top of the UI is expected to be the same as the number of queries displayed, but is instead the number of queries times number of usage ingestions ran.

**Version:**
 - OS: CentOS 7
 - Python version: Python 3.9.7
 - OpenMetadata version: 0.13.2-beta
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==0.13.2-beta

**Additional context**
Enclosing a debug file from the Usage Ingestion.
[debug.txt](https://github.com/open-metadata/OpenMetadata/files/10538020/debug.txt)

**Comment by ulixius9** [comment]
Upon investigation we found that the query `select * from roles where role_id=$1` and `select role_name from roles where role_id=$1` is not visible on the UI because the sqlfluff parser is not able to parse these queries because of the intermediate  literal `$1` and hence it gets passed to the sqlparse parser and even the sqlparse parser is not able to parse this I'm assuming because it considers the roles as reserved keyword because when the query is  `select * from "roles" where role_id=$1` it's able to parse that


ideally we should depend on the sqlfluff parser so we will raise a pr on sqlflull to fix this

**Comment by ulixius9** [comment]
closing by https://github.com/sqlfluff/sqlfluff/pull/4883
