### ISSUE TITLE
Most Active Users section not working

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#10018]
**Affected module**
UI

**Describe the bug**
It currently only displays 2 records, which is impossible.

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/215550869-6256ca1c-ea2b-46d8-a4b7-f06b96404dda.png)

**Expected behavior**
We have XX daily active users. This is plainly wrong.

**Version:**
 - OS: Chrome
 - OpenMetadata version: 0.13.1

**Comment by harshach** [comment]
@TeddyCr can you look into this. Looks more of an operational issue than a bug

**Comment by TeddyCr** [comment]
@trillhaa thank you for opening this issue. Are you able to share the logs from the workflow? Feel free to DM them directly to me on slack if there are any privacy concerns.

**Comment by abcabhishek** [comment]
Hi @TeddyCr 

Following is a snippet from the Warning portion of the Data Insights workflows:

```
[2023-01-31 12:42:36] WARNING {DataInsight:web_analytic_report_data_processor:256} - Could not get user details - 7 validation errors for User
--
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image24
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image32
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image48
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image72
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image192
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  | 2023-01-31T18:12:36.217+05:30 | profile -> images -> image512
  | 2023-01-31T18:12:36.217+05:30 | ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
```

Although this shows up as a warning, I believe it is actually an error that is being caught.

Could you kindly verify and let me know?

**Comment by TeddyCr** [comment]
Thanks @abcabhishek for sharing, let me take a look.

**Comment by TeddyCr** [comment]
@abcabhishek we have a PR open that should fix your issue. We'll do a minor release of the 0.13.2 python package early next with the fix.

Also could you share the response you get from sending a GET request to this endpoint `http://localhost:8585/api/v1/users/name/{userName}?fields=profile,roles,teams` where `{userName}` is a username that does not show up in the data insight report.
