### ISSUE TITLE
Search for lineage edges based on timestamp and method of creation

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#10057]
**Is your feature request related to a problem? Please describe.**
Need to be able to find "old" lineage edges that were not created by a user. This could aid in automated cleansing of stale lineage.

**Describe the solution you'd like**
It would be nice if... each lineage edge has it's own ID (to reference in deletion). It would be nice to be able to search for lineage edges by created_or_updated_timestamp and created service (e.g. ingestion, api, user, ...)

https://openmetadata.slack.com/archives/C02B6955S4S/p1675265747829059?thread_ts=1675265082.472359&cid=C02B6955S4S

**Comment by gavin-denyse** [comment]
Please prioritize this enhancement.
Thank you!
