### ISSUE TITLE
Reevaluate fpath.open from the FileSink class

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10054]
**Context**
In `/profiler/sink/file.py` and `ingestion/sink/file.py`, pylint error for `self.file = fpath.open("w", encoding=UTF_8)` (line 50) has been silenced with `# pylint: disable=consider-using-with` as a quick fix. Pylint recommendation of using a context manager should be followed and implemented

**A.C.**
- [ ] Context manager as been implemented to handle file read/write
- [ ] Pylint comment has been removed and no new linting error is reported

**Comment by pmbrull** [comment]
@TeddyCr would you have some more details on this? Moving it to the backlog for now. Not sure if this could be a candidate for a `good-first-issue`

**Comment by TeddyCr** [comment]
@pmbrull just updated the description.

**Comment by shivamshrey** [comment]
Hi @TeddyCr, I'd like to have a go at this. Could you assign this to me?

**Comment by haquem1** [comment]
@TeddyCr  @shivamshrey I was actually already working on this earlier this week (mentioned on Slack channel). Happy to consolidate efforts

**Comment by TeddyCr** [comment]
Hey @shivamshrey, apologies this was indeed already assigned. We have quite a few others [good first issue](https://github.com/open-metadata/OpenMetadata/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue). Feel free to reach out if you have questions on any of these.

@haquem1 yep make sense. I assigned it to you 🙂

**Comment by shivamshrey** [comment]
@TeddyCr @haquem1 no worries. I'll find something else. :)
