### ISSUE TITLE
UI Improvements 

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#10052]
- [x] Dropdown Styling isn't consistent  - @Ashish8689 
<img width="738" alt="Screenshot 2023-02-01 at 8 15 40 PM" src="https://user-images.githubusercontent.com/103238069/216074798-4c304b6a-2f0c-44d5-beb7-420fccd7b69a.png">

- [x] table bottom corners don't have curved corners
<img width="1137" alt="Screenshot 2023-02-01 at 8 16 49 PM" src="https://user-images.githubusercontent.com/103238069/216075099-0ab0cb39-f424-4ce9-b684-c2df6e8a532f.png">

**Comment by devyani-kaushik** [comment]
- [ ] Switch not aligned 

<img width="602" alt="Screenshot 2023-02-02 at 4 52 56 PM" src="https://user-images.githubusercontent.com/103238069/216311865-b533baed-ea3a-4b9e-809f-844ead43dd86.png">

**Comment by devyani-kaushik** [comment]
- [ ] breadcrumb padding not consistent to other pages
<img width="1436" alt="Screenshot 2023-02-02 at 4 54 26 PM" src="https://user-images.githubusercontent.com/103238069/216312187-70210ee1-b264-4909-9d66-435c3282e1f1.png">

**Comment by devyani-kaushik** [comment]
- [ ] Buttons are not aligned properly 
<img width="1440" alt="Screenshot 2023-02-02 at 4 57 13 PM" src="https://user-images.githubusercontent.com/103238069/216312837-f3d90d06-6b0f-43bf-a12a-2f873894b420.png">

**Comment by devyani-kaushik** [comment]
- [ ] More icon isn't right
<img width="276" alt="Screenshot 2023-02-06 at 12 02 04 PM" src="https://user-images.githubusercontent.com/103238069/216899513-16fbbb0a-1b3c-416d-9b9b-468311b3eaa8.png">

**Comment by devyani-kaushik** [comment]
- [ ] Remove the description on hover send button
<img width="1002" alt="Screenshot 2023-02-06 at 12 25 14 PM" src="https://user-images.githubusercontent.com/103238069/216903409-d46c49ee-f9ce-4220-9aff-12811e9dfcfc.png">

**Comment by devyani-kaushik** [comment]
- [ ] on expanding a node other node's shouldn't be overlapping it
<img width="1440" alt="Screenshot 2023-02-07 at 5 51 21 PM" src="https://user-images.githubusercontent.com/103238069/217243580-6381be0c-4768-4f27-8fc7-3536a45ed630.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Make the label in the capitalized format
- [ ] Replace the native select with Antd Select Component
![image](https://user-images.githubusercontent.com/59080942/221103059-798ffdce-6272-44fc-9a5d-e13acabe9733.png)

**Comment by Ashish8689** [comment]
@chirag-madlani  Marking this issue done and closing it as every improvement has been fixed.
