### ISSUE TITLE
Bug on updating column or struct field which has duplicate name among TableEntity

### ISSUE THREAD

**Issue by nuang-ee** [open-metadata/OpenMetadata#10067]
**Affected module**

Table UI

**Describe the bug**

For hive tables, it is possible that name of struct field is identical among different columns,

For example, consider table `chat` that has `user`, and `target_user` as its column,
And type of `user` and `target_user` is: `struct<_id:int, ...>`

The problem is, in this case, if you update the description of a struct field: `user._id`, description of `target_user._id`  field also gets updated with same value.

Problematic code location is right here:
https://github.com/open-metadata/OpenMetadata/blob/58052695069c9685fc74f02804d45003c0ab12f6/openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx#L169-L186

As you can see, column or struct field's tag or description are updated by their name, not their fullyQualifiedName.

**To Reproduce**

You can reproduce this bug by updating description or tag of any table, which contains duplicate names within all struct field / columns.

**Expected behavior**

Update on a description of column / struct field should be applied to only desired one.

This can be easily fixed by using column / field's fullyQualifiedName (which contains full path of the field) instead of name on update methods.

**Version:**
 - OpenMetadata version: 0.13.2 (present on latest version)

**Comment by nuang-ee** [comment]
I think I already know how to fix this problem and able to make related PR. I'll post it soon :)

**Comment by sureshms** [comment]
@nuang-ee assigned this issue to you. Looking forward to the PR.

**Comment by Sachin-chaurasiya** [comment]
Fixed with #10340
