### ISSUE TITLE
MySQL Environment Variables: DB_SCHEME='mysql' twice

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10099]
**Is some content missing, wrong or not clear?**
In the MySQL Environment Variables, DB_SCHEME='mysql'  is listed twice twice.

**Describe the solution you'd like**
This seems to be an error as YML files have it only ones. For some this might be obvious, but if someone is just trying - it might be confusing. 

**Additional context**
![image](https://user-images.githubusercontent.com/26750060/216568628-7ea332bb-1645-44b6-9f42-52d5229ed224.png)

**Comment by harshach** [comment]
@joeshajan assigned to you.
