### ISSUE TITLE
Add JSON schema visualisation

### ISSUE THREAD

**Issue by tomtor** [open-metadata/OpenMetadata#1011]
Would it be possible to add eg

https://github.com/jlblcc/json-schema-viewer

to visualize JSON schemas:

![afbeelding](https://user-images.githubusercontent.com/1104260/139654333-aea5617c-a4b7-4dd6-94bc-79ed18c9f6a7.png)

**Comment by harshach** [comment]
This will be cool to have along with docs and APIs
