### ISSUE TITLE
Version history page not highlighting changes

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#10135]
**Affected module**
UI

**Describe the bug**
When the datatype of my column changed from `string` to `float` in the version history page it seems like I've two columns named `timestamp`

![image (2)](https://user-images.githubusercontent.com/39544459/217314679-38872de0-0a1d-492e-8936-61a28871c269.png)

**Comment by ulixius9** [comment]
Got it thanks @Sachin-chaurasiya, also it will not be possible to have two columns of same name!

**Comment by Sachin-chaurasiya** [comment]
Happy to help @ulixius9, so, closing this.
