### ISSUE TITLE
Support cursor based pagination for Bots entity

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1014]
This requires adding before, after, and limit in the list operation in `BotsResource.java` similar to `TableResource.java` list method. Make sure you copy all the annotation and description from TableResource.java to BotsResource.java and make suitable edits to change from table to metrics.

**Comment by ReyhanPatria** [comment]
Hi! This seems simple enough, I'd be modifying the list function in `BotsResource.java` to be similar to list function in `TableResource.java` correct? I'd like to work on this if you would assign it to me, thanks!
