### ISSUE TITLE
Propagate Tags from Parent to Child Containers

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#10147]
**Is your feature request related to a problem? Please describe.**
There should be way to allow users to set tags to child once it is applied to the parent.
Eg tags applied to database , if choosen should be propagated to databaseSchema and Tables

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sureshms** [comment]
Propagating ownership from parent to child is already done in https://github.com/open-metadata/OpenMetadata/pull/8824
