### ISSUE TITLE
[feature-request] - Problem with update descriptions and tags in OM tables

### ISSUE THREAD

**Issue by BessonEduardo** [open-metadata/OpenMetadata#10158]
Hi OM Team!

I'm trying to run some metadata descriptions from BigQuery to Open Metadata without sucess. When the descriptions in OM are blank, it's work, but when I update something at BigQuery, don't work anymore bacause it's wont override. Same case at tags and schema descriptions.

It's very important update in all tools same time to not do rework or doing the manual job.

Sorry if I'm saying no sense things. But, it can be something about changing the method? Maybe we're in GET or POST scenary and we need something like PUT or PATCH to update or insert a new id.

I have tested this scenarys at Glue, Redshift and GCP. All cases with same problem.

My post at community support.
https://openmetadata.slack.com/archives/C02B6955S4S/p1675728257778779

Thanks in advance.

**Comment by pmbrull** [comment]
Hi, with PUT you can update the description when its empty. Once defined, this can only be done with PATCH. The idea is that we dont want to update descriptions manually added by users. This behavior is intended
