### ISSUE TITLE
failed to ingestion dbt 1.4 

### ISSUE THREAD

**Issue by Karl-Wu** [open-metadata/OpenMetadata#10156]
**Affected module**
dbt ingestion 

**Describe the bug**
Unable to ingestion dbt 1.4 

**To Reproduce**
Upgrade jaffle_shop project  to dbt 1.4 and run dbt ingestion on OpenMetadata

Screenshots or steps to reproduce
[2023-02-09 15:24:33] INFO     {Ingestion:dbt:326} - Processing DBT node: customers
[2023-02-09 15:24:33] WARNING  {Ingestion:dbt:383} - Unexpected exception parsing DBT node:customers - 'root_path'

**Expected behavior**

**Version:**
 - OS:  MacOS
 - Python version:  3.9.16
 - OpenMetadata version:  0.13.1
 - OpenMetadata Ingestion package version: 

**Additional context**
root_path: Absolute file path of this resource's package. This is removed in dbt Core v1.4 / manifest v8 to reduce duplicative information across nodes.
https://docs.getdbt.com/reference/artifacts/manifest-json

**Comment by harshach** [comment]
with the new dbt parser this is resolved and confirmed in the community
