### ISSUE TITLE
dot (.) is not allowed in the Glossary Term Name on the UI, but can be uploaded  via CSV and no error is give.

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10164]
**Affected module**
Govern. Glossary.

**Describe the bug**
dot (.) is not allowed in the Glossary Term Name on the UI, but can be uploaded  via CSV and no error is given.

**To Reproduce**
![image](https://user-images.githubusercontent.com/26750060/217863261-85a5af1e-dbbf-43bd-b9b5-dd6510cc1005.png)

but all allowed during the upload
![image](https://user-images.githubusercontent.com/26750060/217863767-920ad642-aa8f-4229-bc28-3d17ee2672a1.png)

Then one gets strange bahaviour
![image](https://user-images.githubusercontent.com/26750060/217864116-f10dcc5d-c907-454a-a97b-80ae5feb61d1.png)

**Expected behavior**
Error is given on the upload and terms with dots not allowed as per UI constraints

**Comment by sureshms** [comment]
@chirag-madlani Glossary Term indeed allows `.` in the name. UI has it's own regex restrictions that don't match with restrictions defined in JSON schemas. We should remove restricting `.` in the UI when users enter Glossary and Glossary Term names.

**Comment by Ashish8689** [comment]
@harshach  and @sureshms  ->  Allowing `.`  in Glossary will leads to some issues like:
In UI we are splitting Glossary from `.` to extract Glossary and terms but it will be false if it has `.`  within the name
Since API for getting `glossary` and `glossaryTerm` is different we need to identify it in frontend and make appropriate calls
Can we avoid `.`  in names or can we have a generic API to resolve the glossary?

**Comment by sureshms** [comment]
@Ashish8689 this is where fully qualified names have quoted string. The glossary term FQN would be "glossary.name".term1.term2. This is handled using ANTLR for FQNs of all the entities where it automatically takes care of splitting correctly. @Sachin-chaurasiya maybe able to provide context here.

**Comment by Sachin-chaurasiya** [comment]
> @Ashish8689 this is where fully qualified names have quoted string. The glossary term FQN would be "glossary.name".term1.term2. This is handled using ANTLR for FQNs of all the entities where it automatically takes care of splitting correctly. @Sachin-chaurasiya maybe able to provide context here.

Yes, we have ANTLR for splitting and quoting the FQNS, @Ashish8689 will be trying out the same.

**Comment by Ashish8689** [comment]
@sureshms  Glossary terms are  coming empty `[ ]` when trying to fetch. Only for Glossary having  `.` in it.  Data can be seen while listing all GlossaryTerm.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/66266464/224337845-4e45c5c4-509b-4901-a2ac-600962c8a4a3.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/66266464/224338216-439d028e-6805-418b-9951-e3e554049696.png">

**Comment by chirag-madlani** [comment]
@harshach @sureshms Any update here?

**Comment by harshach** [comment]
@chirag-madlani as I said, it will be part of fqnHash fix.

**Comment by harshach** [comment]
looks like we are allowing entity name to valid during the upload from backend 
<img width="1579" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/a6dc1ac5-0d8e-4996-a0b2-8c05a658fb89">
and UI is restricting while adding the term
@karanh37 can you take a look

**Comment by harshach** [comment]
@DovileKr "/" not allowed in GlossaryTerm, we enabled dry run validations for entity names as well. This will fix the inconsistencies
