### ISSUE TITLE
[feature-request] - Creating Domain Glossary

### ISSUE THREAD

**Issue by BessonEduardo** [open-metadata/OpenMetadata#10160]
Hi OM Team!

Good day!

"...creating domain glossary that includes all the conceptual definitions and terms related to the domain. Then have a classification tag for defining data product with it's hierarchy. Use the glossary terms  to label the data assets and tags to classify the data assets. It could be used in access control policies, such as, only people in a domain can view the data other than data product..."

Mr. Suresh comment in the community
https://app.slack.com/client/T02BVTLN3G8/C02DZK3QH8Q/thread/C02DZK3QH8Q-1673954038.726129

It's exactly what I need.
I know this conversation of Mr. Suresh wasn't with me but, I'm here to confirm it's will help me too.

Thanks in advance.

**Comment by sureshms** [comment]
@BessonEduardo, please see the new feature we are working on #12142. I think it addresses all the requirements of this issue. If not please do comment on that issue. I am closing this.
