### ISSUE TITLE
Handle Redshift `SUPER` data type

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10171]
- https://openmetadata.slack.com/archives/C02B6955S4S/p1675891156606479

**Comment by osocron** [comment]
Piggy backing on this. We have the same issue but for the `GEOMETRY` and `GEOGRAPHY` data types. We make heavy use of these data types and currently we are unable to run profilers for most of our tables.

**Comment by harshach** [comment]
@sushi30 assigning this to you

**Comment by sushi30** [comment]
@osocron I cannot find docs for `GEOMERTY` or `GEOGREAPHY` type. Canyou please provide a sample DDL and some data so I can test on my end?

**Comment by sushi30** [comment]
# Steps to reproduce

create table and insert data

```sql
-- Create the landmarks table with GEOMETRY, GEOGRAPHY, and SUPER columns
CREATE TABLE landmarks (
    landmark_id INT,
    location_geometry GEOMETRY,
    location_geography GEOGRAPHY,
    tags SUPER
);
   
-- Insert sample data with tags using JSON_PARSE
INSERT INTO landmarks (landmark_id, location_geometry, location_geography, tags)
VALUES
    (1, ST_GeomFromText('POINT(13.404954 52.520008)'), ST_GeomFromText('POINT(-122.419418 37.774929)'), JSON_PARSE('{"country": "Germany", "city": "Berlin", "rating": 4.5}')),
    (2, ST_GeomFromText('POINT(13.377704 52.516275)'), ST_GeomFromText('POINT(-122.431297 37.807617)'), JSON_PARSE('{"country": "Germany", "city": "Berlin", "rating": 4.2}')),
    (3, ST_GeomFromText('POINT(13.390327 52.518611)'), ST_GeomFromText('POINT(-122.408227 37.771469)'), JSON_PARSE('{"country": "Germany", "city": "Berlin", "rating": 4.8}')),
    (4, ST_GeomFromText('POINT(13.373611 52.507222)'), ST_GeomFromText('POINT(-122.453056 37.720000)'), JSON_PARSE('{"country": "Germany", "city": "Berlin", "rating": 4.0}')),
    (5, ST_GeomFromText('POINT(13.412778 52.520833)'), ST_GeomFromText('POINT(-122.387500 37.774722)'), JSON_PARSE('{"country": "Germany", "city": "Berlin", "rating": 4.6}'));
```

Run profiler. No results for super, geography and geometry columns:

![image](https://github.com/open-metadata/OpenMetadata/assets/26347589/468703b6-05d1-438f-afd2-1a79eb9b329c)

**Comment by sushi30** [comment]
1. There appears to be no issue when running the profiler on Redshift tables with complex data types.
2. Generally, there is [set of types (`NOT_COMPUTE`)](https://github.com/open-metadata/OpenMetadata/blob/1bb7d893ac74a5d6a0730fb51eebb6236973dc6a/ingestion/src/metadata/profiler/orm/registry.py#L86) that OM currently does not process.
3. This is a more general issue than Redshift (as we can see in https://github.com/open-metadata/OpenMetadata/issues/12127)

I will close this issue in favor of https://github.com/open-metadata/OpenMetadata/issues/15627
