### ISSUE TITLE
add ctas parsing from query log for oracle to OM oracle connector

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#10175]
log_mgr.db_repo_ddl

https://openmetadata.slack.com/archives/C02B6955S4S/p1676019067769739?thread_ts=1675790396.879999&cid=C02B6955S4S

**Comment by ulixius9** [comment]
closing this ticket by #11005 we are now using the method `DBMS_METADATA.GET_DDL` to get the full create view definition

**Comment by pmbrull** [comment]
This requires creating the Usage & Lineage connector for Oracle

**Comment by pmbrull** [comment]
a bunch of the tables where useful information might live is behind paywall, e.g. `DBA_HIST_ACTIVE_SESS_HISTORY` requires the diagnostics pack licence. We might need to stick to less info but have it more available for all users
