### ISSUE TITLE
Dot character in service names cause issues when running the ingestion

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#10181]
**Affected module**
UI and backend

**Describe the bug**
OM API lets us build service names with dots on them and our code treats all names as `fqn`. When a service is created with name `sevice.name` our code will translate it into its `fqn` which is `"sevice.name"` which causes errors when searching entities by name. 

**To Reproduce**

- Create a service with a dot on it using the API.
- Try to ingest from the service.

**Expected behavior**
We should ingest without any error, but we get:

```
metadata.ingestion.api.topology_runner.MissingExpectedEntityAckException: Missing ack back from [DatabaseService: __root__='local_my.sql'] - Possible causes are changes in the server Fernet key or mismatched JSON Schemas for the service connection.
```

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Approaches to fix it:**

1. Use `fqn` for the entity name

This option would imply changes in the DB schema and many parts of the code.

2. Stop using `fqn` to refer to service names

We must check when we use the `fqn` to refer to the service names and change it.

3. Stop using `.` char in the service entity names

We have to check current service names in DB and change them.

CC @sureshms

**Comment by sureshms** [comment]
@nahuelverdugo option 3 is not a choice. I am still not clear on what the issue is. It is most likely that we are setting the FQN for service name in JSON without quotes because ServiceEntityRepository does not override EntityRepository::setFullyQualifiedName method.

**Comment by sureshms** [comment]
@harshach need to validate if this issue is no longer relevant with fqnHash.

**Comment by harshach** [comment]
<img width="1867" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/f58a08c9-8b9d-483e-8ebf-26a2ac0494d8">
<img width="1869" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/c323c73a-1e7a-4030-823b-666687825d12">

**Comment by harshach** [comment]
its resolved now 
<img width="1654" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/08537754-4631-4950-8d3f-aebcd17697ec">
<img width="1663" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/277e8754-8e07-4e26-b361-b63251a50f97">
![Uploading image.png…]()
