### ISSUE TITLE
Add custom timestamps selection using a calendar to get a custom period or a specific day

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#10187]
**Feature**
Currently, we only allow users to select the last 3 days or 7 days. We should allow users to select a specific window

**Describe the task**

**Comment by ShaileshParmar11** [comment]
Hello @devyani-kaushik I need your help to show the custom time range in UI
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/71748675/223721087-3ff4e589-fb1f-4d5c-b748-57704d40a326.png">

**Comment by TeddyCr** [comment]
@JahJajaka you can follow progress of this feature request here. 🙂
