### ISSUE TITLE
Glossary Term Search not returning terms from a deep term structure

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10188]
**Affected module** UI

**Describe the bug**
Search for Glossary Term is not working as expected. It doesn't return the term if the Nested Glossary Term is more than 2 levels. 

**To Reproduce** 

**I have  created a deep glossary structure , 6 layers**
![image](https://user-images.githubusercontent.com/26750060/218130291-3f99ab61-5014-405a-a329-e9d8aa0933c8.png)

**I am trying to use search for a term "Palace"** and it works ok, if I have FIRST expanded all levels
![image](https://user-images.githubusercontent.com/26750060/218131057-0b600bb7-2264-4f7a-8a45-4e409af52ff1.png)

**However, the term is shown as "non existing" if I just do a search and glossary is not expanded.**
![image](https://user-images.githubusercontent.com/26750060/218131214-f8968967-b0a3-4f16-842d-3108562f7d9e.png)
![image](https://user-images.githubusercontent.com/26750060/218131301-721b757d-6bfe-42f7-94d8-aa3594fe0f3f.png)

**I have to be in the T+2 hierarchy, to finally for the search to work.**  And it doesn't even show me term (T), but the parent  Term (T+1)
![image](https://user-images.githubusercontent.com/26750060/218131443-f97e0caa-8c53-4f4d-897b-322d1d44a547.png)

Expected behavior
1) I can search for the term from any layer (and ideally across the glossaries)
2) The search brings me to the term directly.  If I filter for "palace" I should only see it:
![image](https://user-images.githubusercontent.com/26750060/218152323-c75c60af-e9ad-445c-8547-bcf11fd58aac.png)

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.13.2]

**Additional context**

**Comment by DovileKr** [comment]
I want to add additional examples. If I search within a glossary - it shows me a parent term, when expanded it gives me a correct suggestions, but then as soon as I click the mouse - all terms are being shown.
1. Search
![image](https://user-images.githubusercontent.com/26750060/226908559-9072eb73-161c-4993-9cbe-7d3adf687312.png)

2. Expand
![image](https://user-images.githubusercontent.com/26750060/226908791-5fa1afb4-41ce-40d2-81e0-71fd84a78bc9.png)

3. Click
![image](https://user-images.githubusercontent.com/26750060/226908888-dcdb7073-2e59-455b-87ae-e0daceea718d.png)

**Comment by harshach** [comment]
@DovileKr here are the changes we are doing https://github.com/open-metadata/OpenMetadata/pull/10677 . Please give us some feedback
