### ISSUE TITLE
Support cursor based pagination for Pipeline Service entity

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1018]
This requires adding before, after, and limit in the list operation in `PipelineServiceResource.java` similar to `TableResource.java` list method. Make sure you copy all the annotation and description from TableResource.java to PipelineServiceResource.java and make suitable edits to change from table to metrics.

**Comment by dec0deit** [comment]
Hi @sureshms Please assign this to me. Thanks

**Comment by sureshms** [comment]
Done

**Comment by sureshms** [comment]
This issue has been fixed recently by #1325
