### ISSUE TITLE
Filterning annoucements doesn't work in Entity page

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#10185]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/38649/218136481-23c758c1-994b-4784-836f-06b07b12f170.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Closing this, as it's fixed.

https://user-images.githubusercontent.com/59080942/228333646-d8c38c96-62df-4b5b-94c6-f5e1b53d7975.mov
