### ISSUE TITLE
Azure blob storage support in database service DBT ingestion

### ISSUE THREAD

**Issue by ph-eip** [open-metadata/OpenMetadata#10184]
I would like to see Azure blob storage support in the database service DBT ingestion.

In the current version, only GCP and S3 appear to be available:

![image](https://user-images.githubusercontent.com/85677784/218119810-cefa9c21-49a1-4744-9f90-4e18aed2da21.png)

**Comment by chirag-madlani** [comment]
UI changes are pending

**Comment by harshach** [comment]
@chirag-madlani lets finish the UI changes

**Comment by chirag-madlani** [comment]
cc: @ShaileshParmar11

**Comment by ShaileshParmar11** [comment]
The feature delivers in #12594
