### ISSUE TITLE
Allow user to disable system tags

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10198]
**Context**
In previous version system tags could be deleted from the platform. In the recent release we added system tags back into the platform and removed the ability to delete them. We should allow users to disable system tags if they do not want to use them.

**Comment by chirag-madlani** [comment]
Hi @TeddyCr 
I feel this requires backend support as well. 
We can have it in UI as an option or as a config while bootstrapping the server
cc: @open-metadata/backend

**Comment by sureshms** [comment]
@TeddyCr and @chirag-madlani, all the system-provided entities already come with `disabled` property. You can use that to disable the system entities.

**Comment by chirag-madlani** [comment]
@devyani-kaushik need your help in make classification looks like disabled while viewing

**Comment by chirag-madlani** [comment]
@harshach we need ES support to disable tags and don't show it in the UI anywhere
