### ISSUE TITLE
The security support of python 3.7 will be ended in June, 2023

### ISSUE THREAD

**Issue by yu-iskw** [open-metadata/OpenMetadata#10197]
**Is your feature request related to a problem? Please describe.**
According to the python community, the security support of python 3.7 will be ended on 27 June, 2023. So, it would be better to stop supporting python 3.7 in OpenMetadata, because we won't guarantee updates in python 3.7 if vulnerabilities are found. Let's discuss the plan to stop supporting python 3.7.

![image](https://user-images.githubusercontent.com/1523515/218373081-01df58e8-cba9-407c-8340-f32d7f5eacd5.png)

https://devguide.python.org/versions/

**Describe the solution you'd like**
We will support python 3.8 or later. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TeddyCr** [comment]
Hey @yu-iskw thank you for opening thi issue. We won't stop support for Python 3.7 as some critical cloud infrastructure that clients may use still have requirements around this version (i.e. AWS MWAA https://github.com/open-metadata/OpenMetadata/issues/8359). By support here we mean adding logic in the code that is only supported from python 3.8+.

We do have an open issue arounding adding tests for Python 3.10/3.11 https://github.com/open-metadata/OpenMetadata/issues/8359. We'll also be adding messaging around the recommended Python version to use.

**Comment by yu-iskw** [comment]
@TeddyCr Alright. I close the issue.
