### ISSUE TITLE
Timestamp field label not quoted

### ISSUE THREAD

**Issue by Tarasshetman** [open-metadata/OpenMetadata#10200]
**Affected module**
It depends on beckend and Ingestion Framework

**Describe the bug**
When the timestamp is not being quoted we have an error ORA-01843: not a valid month.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OS: [Debian GBU/Linux 11]
 - Python version: 3.9
 - OpenMetadata version: [0.13.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
@Tarasshetman could you let us know if this is still an issue?

**Comment by Tarasshetman** [comment]
No, it has not.

пт, 6 жовт. 2023, 15:58 користувач Teddy ***@***.***> пише:
