### ISSUE TITLE
Add click event web analytic

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10208]
**Context**
Currently we are passing page view events from openmetadata. We should add the possibility to track clicks.

A.C.
**Backend**
- [ ] Add event event type for web analytics

**Frontend**
- [ ] send click event to collect endpoint. `sessionId` should match that of the `pageViewEvent`

**Comment by pmbrull** [comment]
Pending on some changes on the backend to add the new events support

**Comment by TeddyCr** [comment]
PR for the backend part https://github.com/open-metadata/OpenMetadata/pull/10554

**Comment by TeddyCr** [comment]
@Sachin-chaurasiya this is good to go on the UI side.
