### ISSUE TITLE
Lineage arrangement state lost when entering edit mode

### ISSUE THREAD

**Issue by NithinKumaraNT** [open-metadata/OpenMetadata#10219]
**Affected module**
Impacts the UI - Lineage

**Describe the bug**
1. Read-mode (tables are arranged and column level is expanded = everything is ready to draw the data lineage).
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/42895864/219091241-9cfa27dd-fc1f-4cba-803e-2d9e4413964c.png">

2. Now when I enter the edit mode: The state of my arrangement is lost
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/42895864/219091644-0b20f8e8-f17b-41ea-8563-4fba379fdb3b.png">

As you can see from the above image from step 2, the user has to rearrange the blocks and expand the table again and setup new lineage through the UI.

**To Reproduce**

The above can be reproduced in the sandbox environment (0.13.2)
https://sandbox.open-metadata.org/lineage-view/table/redshift.dev.public.category

**Expected behavior**
The linage arrangement state is the same when the edit mode is entered.

**Version:**
 - OpenMetadata version: 0.13.2
 - Environment : Sandbox

**Comment by harshach** [comment]
Fixed in the latest release
