### ISSUE TITLE
Table search box/widget on Explore page

### ISSUE THREAD

**Issue by focagrande** [open-metadata/OpenMetadata#10216]
**Describe the solution you'd like**
(We are using OM 0.13.0). On "Explore" page we would like to have "Table" box/widget apart from existing "Column" and "Schema" for searching tables by name.

It does not exist also on the list after clicking on "funnel" icon (at the moment present additionally "database", "owner", "tag", "service")

BTW. It is possible to use "table" in "Advance Search"

**Comment by sureshms** [comment]
@focagrande can you please add more details with screenshots for this issue?
