### ISSUE TITLE
Create config options to filter metrics 

### ISSUE THREAD

**Issue by pieroTrobatty** [open-metadata/OpenMetadata#10210]
OpenMetadata is generating massive prometheus output.
`curl http://localhost:8586/prometheus -o prometheus.out` is 260MB with 1.4 million lines.
Our Prometheus scraper is understandably struggling with it.

99% of the log histograms:
```
http_server_requests_seconds_bucket{method="GET",status="404",uri="/v1/tables/name/tab.col",le="0.001",} 0.0
http_server_requests_seconds_bucket{method="GET",status="404",uri="/v1/tables/name/tab.col",le="0.002",} 0.0
http_server_requests_seconds_bucket{method="GET",status="404",uri="/v1/tables/name/tab.col",le="0.003",} 1.0
http_server_requests_seconds_bucket{method="GET",status="404",uri="/v1/tables/name/tab.col",le="0.004",} 1.0
...
```

Can we have a config on yaml file where we can actually chose what to scrap?
Something along the line of:
[Druid Operator Metric Scraper](https://github.com/druid-io/druid-operator/blob/master/examples/tiny-cluster.yaml#L86-L247)
The option to not have the Histograms would also be helpful, this will at least filter 90% of logs.

**Comment by ynaguib** [comment]
Also, an option to disable histograms would do the trick.

**Comment by gnomolio** [comment]
It's really crucial to launch OM as a production solution
