### ISSUE TITLE
Inability to delete default tags

### ISSUE THREAD

**Issue by mhornst** [open-metadata/OpenMetadata#10217]
**Affected module**
Impact is mostly on the UI

**Describe the bug**
We cannot delete default Tags (`PersonalData`, `PII`, `Tier`) on OpenMetadata anymore and they reappear with new versions. Since we have a more Compliance / Legal-related use case, we defined our own set of tags within the Glossary around these categories, and it caused confusion and incorrect tagging on the UI during the first trial already. Could there be an option to disable default tags completely or delete these?

An image why it is confusing from a tagging perspective (an end user will find it harder to distinguish the tag categories):
![image](https://user-images.githubusercontent.com/70534496/219006544-e90a8f04-057f-4d77-aa2e-f89e7a1044f1.png)

**To Reproduce**

These default tag categories cannot be removed (option is greyed out):
![image](https://user-images.githubusercontent.com/70534496/219003810-5854447a-990e-4b56-adee-67efd80f42f7.png)

**Expected behavior**
We would expect the ability to delete / disable completely default tags so they don't show up when searching for tags to be applied.

**Version:**
 - OpenMetadata version: 0.13.1

**Additional context**
This is causing major confusion across our first users, and it is harder to increase adoption for the tool if we cannot configure it completely to support our use case. It is also related to my other ticket ([#8080](https://github.com/open-metadata/OpenMetadata/issues/8080)) as our main justification for OpenMetadata is to be able to tag entities and track ownership across these, and we'll need to be able to have a scalable follow-up mechanism on the tags applied.

**Comment by mhornst** [comment]
This will be solved in: https://github.com/open-metadata/OpenMetadata/issues/10198

**Comment by sureshms** [comment]
Release 1.1 supports disabling the tags. Closing this issue.
