### ISSUE TITLE
UI: Teams drag and drop functionality not working properly

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#10229]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Drag and drop functionality on teams page is not working properly

**To Reproduce**

Screenshots or steps to reproduce

https://user-images.githubusercontent.com/51777795/219634745-1f438357-913e-48a9-b114-ad152729fcd4.mov

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97 any update on this?
@chirag-madlani this is a customer issue, lets fix it and patch it for 0.13.2 and do a in-place release cc @akash-jain-10
