### ISSUE TITLE
[feature-resquest] OM - Create label for Schemas

### ISSUE THREAD

**Issue by BessonEduardo** [open-metadata/OpenMetadata#10220]
Hi OM Team!

Good day!

It's will be very interesting to have a label for schemas, with that, we can control the access from users, not just controlling by tables.

**Comment by sureshms** [comment]
@BessonEduardo, do you mean ability to add tag labels to Schema? If that is the case, it has been added by https://github.com/open-metadata/OpenMetadata/pull/10381. Marking this as resolved. Feel free to open it with clarifying comments.
