### ISSUE TITLE
Role not appearing against the user after tagging, also same user is not appearing under the team structure

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10227]
**Affected module**
UI

**Describe the bug**
No role is appearing against the user, though role is already tagged.
Because of this issue, the user is also not appearing against the team, though already joined 

**To Reproduce**

Screenshots 

role not appearing against the user
![image](https://user-images.githubusercontent.com/110607559/219564165-8930c9e5-ce19-4dba-8d39-0404c01abca5.png)

role already appearing if we go inside
![image](https://user-images.githubusercontent.com/110607559/219564380-d174cebc-fa92-409e-bf8b-2339f1bb1e04.png)

the below screen shows 3 users
![image](https://user-images.githubusercontent.com/110607559/219564500-17c2e2d7-0a47-4ece-9b4b-3374ff14a254.png)

but inside, it doesnot show any user
![image](https://user-images.githubusercontent.com/110607559/219564549-7e6da1eb-63b2-4784-9076-846a59c9bfcc.png)

**Expected behavior**

 - OpenMetadata version: [e.g. 13.2
 

**Additional context**

**Comment by sureshms** [comment]
@lailapatel is this still an issue?

**Comment by lailapatel** [comment]
@sureshms this one got resolved when we added all teams in the hierarchy against the user (like Department, Division, Group )

e.g. if User A is a part of Group c, then we added 4 teams in the hierarchy against the user, like Business Unit A-> Department A-> Division A -> Group C

Need your assistance for the other issue related to Data Steward Role for deleting and editing test - Ticket 10859

**Comment by chirag-madlani** [comment]
Thanks, @lailapatel 
Closing this.
