### ISSUE TITLE
[Feature-Resquest] OM - Lineage - Table field

### ISSUE THREAD

**Issue by BessonEduardo** [open-metadata/OpenMetadata#10225]
Hi OM Team!

Good day!

We had some problems about tests in the Lineage.
In the origin (GCP), we had erased a specific field of a table and after the update we have observed that OM lost the conection and the same field still there (OM).

Thanks in advance.

**Comment by sureshms** [comment]
@BessonEduardo can you please provide more details on what field you erased and details of what you observed on OM?
