### ISSUE TITLE
Integration tests for Ldap is broken

### ISSUE THREAD

**Issue by vijaypm** [open-metadata/OpenMetadata#1023]
Sub-issue of #798
When following the instructions on this page https://docs.open-metadata.org/open-source-community/developer/run-integration-tests for Hive Integration tests, you get errors:
`FAILED tests/integration/mysql/test_mysql_crud.py::test_read_schema - sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
`

**Comment by vijaypm** [comment]
@harshach please assign this to me. I'll start working on fixing this test.

**Comment by harshach** [comment]
Thanks @vijaypm

**Comment by vijaypm** [comment]
Root cause of issue seems to be that the json serialization python code is converting property names like 'isBot' to 'isbot' and being rejected by the catalog-rest-service with a deserialization exception like:
`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isbot" (class org.openmetadata.catalog.api.teams.CreateUser), not marked as ignorable (9 known properties: "isAdmin", "teams", "timezone", "name", "description", "displayName", "profile", "email", "isBot"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 6, column: 19] (through reference chain: org.openmetadata.catalog.api.teams.CreateUser["isbot"])
`
