### ISSUE TITLE
Upper filter between data assets

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#10236]
**Affected module**
UI

**Describe the bug**
When selecting specific owner for tables for example, it shows the number other data assets have for this owner (e.g. 200 tables, 400 dashboards). When selecting dashboards, the owner filter restart, so you must select it again. 

**To Reproduce**

<img width="790" alt="image" src="https://user-images.githubusercontent.com/87426120/220101495-376d2171-4337-4265-ab78-ccd48ca1c4f5.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/87426120/220101564-6eb80d9a-4d24-4bc5-9db4-ad045699d896.png">

**Expected behavior**
When moving to another asset with same filters option, the filter should be saved.

**Version:**
latest OMD version on MAC

**Additional context**

**Comment by chirag-madlani** [comment]
Hi @sapirhi 
We are tracking same [here](https://github.com/open-metadata/OpenMetadata/issues/9665)
Duplicate hence closing
