### ISSUE TITLE
When changing GlossaryTerm displayName in the UI, name changes as well.

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10237]
**Affected module**
UI ==> Govern ==> Glossary

**Describe the bug**
When changing GlossaryTerm displayName in the UI, name changes as well.

**To Reproduce**
**I have loaded (via Bulk Upload) this** 
![image](https://user-images.githubusercontent.com/26750060/220105601-e63f2478-e29f-46f6-80cd-e4fca7a080df.png)

**As expected, UI shows:**
![image](https://user-images.githubusercontent.com/26750060/220105869-3cc9d5d1-a35e-4bb3-9fe8-5befb87458cb.png)

**However, if I now change the display name, to Partner Display v2, I get**
![image](https://user-images.githubusercontent.com/26750060/220106113-c0f678a3-2d86-47e3-a671-793b66889194.png)

**and if I now download the Glossary, I have that both Display Name and Name changed**
![image](https://user-images.githubusercontent.com/26750060/220106552-cba28bc5-06ec-4d32-a3be-85bd1c2994a4.png)

**Expected behavior**
My understanding is that Name should not change if we change just the Display Name. 

**Version:**
 - OpenMetadata version: [e.g. 13.2]

**Additional context**

**Comment by ayush-shah** [comment]
please check if it's related to UI cc: @open-metadata/ui

**Comment by harshach** [comment]
@chirag-madlani this should be solved in the new Glossary Implementation right?

**Comment by chirag-madlani** [comment]
Yes we have separate fields now so this is fixed
