### ISSUE TITLE
Filter data assets

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#10235]
**Affected module**
UI

**Describe the bug**
When selecting few options in the **upper** filter section the behavior is 'OR'

When selecting few options in the **left** filter section the behavior is 'AND'

**To Reproduce**

<img width="763" alt="image" src="https://user-images.githubusercontent.com/87426120/220100551-0d4c7af9-60a0-4fb1-adea-f9037c838d4a.png">

<img width="245" alt="image" src="https://user-images.githubusercontent.com/87426120/220100670-b9d13263-a08e-46f3-

**Expected behavior**
This is very confusing for to user, which actually expect to see AND behavior in order to filter a group of relevant assets. 

**Version:**
latest OMD version on mac

**Additional context**

**Comment by nahuelverdugo** [comment]
@chirag-madlani I am assigning it to you so from UI team can prioritize it
