### ISSUE TITLE
GEOMETRY data-type incorrectly ingested

### ISSUE THREAD

**Issue by osocron** [open-metadata/OpenMetadata#10242]
**Affected module**
Ingestion Framework

**Describe the bug**
Using the Redshift connector, when a table containing a `GEOMETRY` data-type is ingested, OM fails to recognize the data-type and defaults to `VARCHAR`.

**To Reproduce**
<img width="650" alt="geom_varchar" src="https://user-images.githubusercontent.com/6936336/220150188-f51b2151-ab92-48fb-9552-05a9747bd375.png">

**Expected behavior**
The data-type of the column in the schema should be `GEOMETRY`.

**Version:**
 - OS: Linux
 - Python version: 3.10
 - OpenMetadata version: 13.2
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[redshift]==0.13.2.4`

**Comment by TeddyCr** [comment]
We should check the list of datatype [here](https://docs.aws.amazon.com/redshift/latest/dg/c_Supported_data_types.html). From a small test I can see we are ingesting the following types `GEOMETRY`, `GEOGRAPHY `, `HLLSKETCH ` as `VARCHAR`.

**Comment by harshach** [comment]
@MilanBariya any updates here?

**Comment by MilanBariya** [comment]
@harshach Not started yet.

**Comment by pmbrull** [comment]
@ulixius9 is this fixed from the column type updates?

**Comment by ulixius9** [comment]
yes closing this ticket by #10563
