### ISSUE TITLE
Add GlossaryTerm status attribute creation and update options in the UI and Bulk Upload

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10240]
**Is your feature request related to a problem? Please describe.**
I don't have option to update [glossaryTerm ](https://github.com/open-metadata/OpenMetadata/blob/afad0a476919e8123de06fb6db42718b01840182/openmetadata-spec/src/main/resources/json/schema/entity/data/glossaryTerm.json)status attribute via UI or Bulk Upload

**Describe the solution you'd like**
Being able to specify glossaryTerm status attribute upon glossaryTerm creation or update

**Describe alternatives you've considered**
Update via ingestion / API, however this doesn't work for users like Business Data Stewards

**Additional context**

**Comment by sureshms** [comment]
This is already available in release 1.0. Closing the issue.
