### ISSUE TITLE
Possibility to modify base url of OM server

### ISSUE THREAD

**Issue by Sudokamikaze** [open-metadata/OpenMetadata#10253]
**Is your feature request related to a problem? Please describe.**
Not problem related, more approach related.

**Describe the solution you'd like**
I'd like to have same variable as `rootPath` which is designed for the same purpose but currently only for API, end user could modify base_url to have his OM instance responding on different URL path instead of `/`, for example: `localhost/openmetadata`

Airflow has the same feature defined https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#base-url

**Describe alternatives you've considered**
We considered other solutions like hosting OM behind reverse proxy, official Helm charts include that, but to me, I'd reduce moving parts in our infrastructure, thus requesting this feature.

**Additional context**
Currently, there's no way to modify base url of OM server, we use Service mesh and Envoy proxy to route the requests directly to the pod endpoint having much more performance. Due to some design decisions & limitations of our architecture, we reuse single internal domain and splitting it to other deployments by different URL path

**Comment by harshach** [comment]
@Sudokamikaze can you describe the use case. Generally /api/v1/ path is to describe the URL for the apis. Changing something like that will require you to change the ingestion configs on where the api is. Don't think this is a good idea, would like to know what you are trying to accomplish

**Comment by Sudokamikaze** [comment]
Hi @harshach,
This is needed for such cases where NGINX/other reverse proxies are not involved in Deployment chain, in our case we'd need that because of our architecure, we don't use reverse proxies in deployments, instead we have Envoy Proxy with the UI which generates needed configs and routes traffic to the pods

**Comment by Sudokamikaze** [comment]
Hey @harshach
Will this feature be ever reviewed and possibly implemented? Thanks in advance

**Comment by harshach** [comment]
<img width="723" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/994b26fd-c1f7-4482-876c-45c49a8fd86c">
