### ISSUE TITLE
Additional Data Management Roles

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#10258]
**Is your feature request related to a problem? Please describe.**
Data governance implies several roles and funcionts, not only data owner. 

**Describe the solution you'd like**
Provide additonal persona roles in openmetadata in addition to "data owner":

- Data steward
- Data quality responsible
- Technical Data owner

Integrated with active directory / SSO.

**Describe alternatives you've considered**
Custom properties to define text free persona roles

**Additional context**
Provide better identification of data roles involved in organization data life cycle to user.

**Comment by sureshms** [comment]
@jromandv I am not sure I understand the issue. Currently, you can define any role you want. Is your requirement being able to use those roles in writing policies?

**Comment by jromandv** [comment]
This issue is about people involved in data management, not technical roles/permissions. As well as you can see and assign an "Owner" in the UI, it would be great to assign other people. In our use case these will be: Data Quality Analyst (DQ) and Technical Data Producer (IT). I see this like splitting current Owner or considering additional people in the tool. As well as we can use the Owner in policy definition (isowner()), these people could be involved in policies too. The rationale is that Data Owner is a very generic and high level concept (sometimes bussines), in big organizations doesn't do all data management tasks because there are several departaments involved. With current policies you can manage metadata, but when accessing the table details you can not quick identify who is in charge of certains task. Some times these people should be identified quick to ask questions or details about data.

**Comment by harshach** [comment]
we are adding extended custom properties that will allow you to define your own roles like this per entity and will be able to assign users or teams
