### ISSUE TITLE
The hierarchy of the glossary (bulk upload) is not appearing in the left pane.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10257]
**Affected module**
UI

**Describe the bug**
1. Glossary hierarchy not appearing in left pane.

The hierarchy of the glossary (bulk upload) is not appearing in the left pane. Since the input for parent vs. nested term is already available in the loading file and same is appearing by clicking nested terms. However, same should also be available in left pane, else the users wont be able to explore the glossary based on the relationship exist between terms (parent vs. nested - 1st level to nth level).

**To Reproduce**

Screenshots 

![image](https://user-images.githubusercontent.com/110607559/220367048-3a577873-29bf-4925-be27-c73bcff6690a.png)

![image](https://user-images.githubusercontent.com/110607559/220367970-5693762b-36a1-4dfc-a0db-3643bb8c905e.png)

**Expected behavior**

**Version:**
13.2

**Comment by harshach** [comment]
@lailapatel, this works as expected. Side bar is only for showing the Glossaries and GlossaryTerm hierarchy will appear on the right panel
