### ISSUE TITLE
Can't save changes for OpenMetadata Client security configuration

### ISSUE THREAD

**Issue by khalepski** [open-metadata/OpenMetadata#10251]
**Affected module**
It impact the UI

**Describe the bug**
We can't save the changes when trying to change OpenMetadata Client security configuration from GoogleSSO to CustomOIDC. 

**To Reproduce**
Try to change OpenMetadata Client security configuration from GoogleSSO to CustomOIDC and save.

![image](https://user-images.githubusercontent.com/6360074/220309710-5dec9de4-ca1f-4355-90d3-788371e49c99.png)
![image](https://user-images.githubusercontent.com/6360074/220309779-e1176b9a-eceb-4b71-a0de-21efbc13a060.png)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 0.13.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
we will not support editing the configuration from the ui.
@chirag-madlani as discussed we shouldn't show Openmetadata service (system created) in metadata services. 
users should use the server config to update any such configs
