### ISSUE TITLE
OM ingestion workflows running endlessly

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#10275]
**Affected module**
Ingestion

**Describe the bug**
The lineage and dbt workflows are running endlessly and not stopping the execution automatically
ref lineage workflow: https://openmetadata.slack.com/archives/C02B6955S4S/p1676966084576559
ref dbt workflow: https://openmetadata.slack.com/archives/C02B6955S4S/p1675706216500849

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Workflows should stop automatically after execution

**Comment by harshach** [comment]
@OnkarVO7 any updates on this ticket?

**Comment by OnkarVO7** [comment]
@harshach tried to reproduce this couple of times unable to do so. Will try out a few more things and provide an update

**Comment by nahuelverdugo** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/10474. The latest [release](https://pypi.org/project/openmetadata-ingestion/0.13.2.6/) contains a patch for fixing this issue.
