### ISSUE TITLE
Bulk upload API is not allowing to pass nth level nested terms.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10272]
**Affected module**
API
**Describe the bug**
Bulk upload API is not allowing to pass nth level nested terms. like a Parent term can be linked to Nth level terms. 
The API is reducing the relationship to 2nd level term only. The input passed in API contains 5 to 6 level nested terms and it was successful. However, the output only shows 2 level nested relationship.

parent - > nested term 1 - > nested term 2 -> nested term nth...

**To Reproduce**

Screenshots 

1. it was successful through manual approach

![image](https://user-images.githubusercontent.com/110607559/220556554-0a937afb-d13a-493c-841e-5c3e063a8ff1.png)

2. relationship was reduced to 2 level nested terms after loading through API. There were two more terms between individual party and Aadhaar card

![image](https://user-images.githubusercontent.com/110607559/220557061-e25b90f3-76db-44bc-b156-9d8877b7fdb6.png)

sample 
[party testing - Sheet1 (1).csv](https://github.com/open-metadata/OpenMetadata/files/10801330/party.testing.-.Sheet1.1.csv)
file is attached

**Version:**
OM -13.2

**Comment by harshach** [comment]
@lailapatel need details on how are you using API and what data are you sending and what response are you getting for us to reproduce.

**Comment by lailapatel** [comment]
The sample file is attached above. Will share inputs for :

**Comment by lailapatel** [comment]
The issue got fixed, a parameter was missing from the API script.

Therefore, we can close this ticket.

Now the only issue left is about unsuccessful bulk upload through UI of the terms in file, though same is successful through API.
@TeddyCr is investigating this issue separately.
