### ISSUE TITLE
UI - Object Storage Service

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10271]
[ObjectStorageServices.pdf](https://github.com/open-metadata/OpenMetadata/files/10801148/ObjectStorageServices.pdf)

We need to prepare the UI for the new Object Storage Service. In the mocks above, there's the page to explore the "Containers" (entities that will live inside the service).

cc @harshach @chirag-madlani

**Comment by pmbrull** [comment]
we can proceed here once the APIs and sample data are finished

**Comment by cristiancalugaru** [comment]
Initial PR created for the Object Storage Service:
https://github.com/open-metadata/OpenMetadata/pull/10283

**Comment by pmbrull** [comment]
Let's add a BETA tag here
