### ISSUE TITLE
ui: improvement in data-quality component

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#10285]
- [ ] Remove the name and description from the right side of the graph as it is repetitive
- [ ] More space to graph horizontally as well as vertically, like what we do in data insight
- [ ] Show parameters in a bit cleaner way -> suggested way was to show param in one row and graph in the next row

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/71748675/220648020-620fb90e-f0af-44cb-9882-d640ff685f1d.png">

**Comment by ShaileshParmar11** [comment]
@devyani-kaushik will propose the mock, and will make changes accordingly

**Comment by harshach** [comment]
@devyani-kaushik where we show the test configuration needs to be aligned properly and more emphasis as this is the test configuration showing the conditions of the test.
Also there will be tests with SQL queries we need to show better details there. 
Abiltiy to pop up the chart that we drawn

cc @ShaileshParmar11 @TeddyCr 

All of our time series should have custom start and end date to be selected not just last N no.of days
