### ISSUE TITLE
Add support for col-level lineage between table and dashboard

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#10291]
**Feature**
We can get the select queries used to create the dashboards from the dashboard APIs (e.g Tableau Metadata API).
Parse the queries and add support for col-level lineage between `table<->dashboard`

ref: https://openmetadata.slack.com/archives/C02DZK3QH8Q/p1677010164137989

**Comment by pmbrull** [comment]
Closing this one, as it will be handled via the introduction of the Dashboard Model Entity
