### ISSUE TITLE
[UI] Links in the markdown should open in a new tab in the browser

### ISSUE THREAD

**Issue by NithinKumaraNT** [open-metadata/OpenMetadata#10296]
**Is your feature request related to a problem? Please describe.**
Many users are frustrated that links in the markdown are not opened in a new tab. It would be nice if the markdown links are opened in a new tab.

**Describe the solution you'd like**
Links in the markdown content open in a new tab.

**Comment by chirag-madlani** [comment]
Hi, @NithinKumaraNT Can you give us some examples of where exactly you are facing this?
We are using markdown extensively in our application so found this very open-ended, Some example will be helpful to narrow down use cases

**Comment by chirag-madlani** [comment]
Thanks, @NithinKumaraNT
@Ashish8689 let's fix this
