### ISSUE TITLE
Display of sample data is hiding non-NULL data

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [open-metadata/OpenMetadata#10306]
**Affected module**
Possibly Ingestion Framework: https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/orm_profiler/profiler/sampler.py
But most likely UI.

**Describe the bug**
I'm using a table with 14670 rows of data.  The field `parent_lei` is 89% NULL, meaning 11% non-NULL.  When I sample at 4%, the sample data produces 586 rows of sample data, of which 120 rows are displayed in my browser.  I'd expect to see 13 rows of Non-NULL data in that column, but all 120 rows are NULL.  When I change the sample rate to 5%, I see one single non-NULL row.

I don't know how to query all the sample data to know whether I was so unlucky that zero of the rows have a non-NULL `parent_lei` field.  But the fact that the first (alphanumerically sorted) 120 rows all have a non-NULL `parent_lei` is extremely misleading.

**To Reproduce**
Attached is the CSV file I loaded into a Trino database, but the sampling code appears to be database independent, so you should be able to reproduce with most any database.  This file is 11.4MB: https://www.dropbox.com/s/cfw7v4m37e0h7j6/utility_state_map_2023.csv?dl=0

**Expected behavior**
I'd expect that the statistics of the file would be reflected somewhat within the sample data.  As a first step to remediate, when sample rows are returned, there should be some effort to select rows for display that match the overall NULL/non-NULL statistics.  Beyond that, would be great to match other statistics.  One way to do this would be to sort the data by percentage of NULL fields and then choose random rows from the piles that tend toward the statistics.  At first you can choose from random piles (and even favor choosing from larger piles rather than smaller piles).  But If the rows are getting too NULL-rich, select from non-NULL rich piles, and vice-versa.

If the problem is purely a UI problem (i.e., the statistics of the 586 rows are on point, it's just the 120 rows that are bonkers), then use the above method to display 120 "random" rows to use humans who are trying to see what data looks like when we can only inspect 1% of it.

**Version:**
 - Red Hat Enterprise Linux 8
 - Python version: 3.9.x
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: unknown exactly (can ask if really needed)

**Additional context**

Here's a screenshot of a lot of NULL rows.

<img width="1312" alt="Screenshot 2023-02-23 at 1 30 57 PM" src="https://user-images.githubusercontent.com/72577720/220998415-ea5c3cf4-d47c-4599-b524-64d690db434f.png">

**Comment by TeddyCr** [comment]
Hey @MichaelTiemannOSC thank you for suggesting this. As you might have seen, we just take a random sample of the sample (if there is sampling set). Each row has an equal probability to be part of the sample data. While I understand the need there might exist to apply a weighted probability based on the profiler statistics we will not implement the feature at this time.

If this is something you are interested to contribute to we would be more than happy to guide you through the process and review your PR. 🙂
