### ISSUE TITLE
Number of Glossary Reviewers

### ISSUE THREAD

**Issue by victorrichart** [open-metadata/OpenMetadata#10302]
**Affected module**
Glossary

**Describe the bug**
There are multiple users created but when clicking in Add Reviewer in the Glossary tab only a list of 10 users is displayed. In addition, we can only search within this ten users, not anyone outside this list.

**Expected behavior**
I expect all users should appear to be added as a reviewer.

**Version:**
 - OpenMetadata version: 0.12.2

**Comment by harshach** [comment]
For showing Users list, we should use the same component as the rest of the places where we show the owners for entity pages
cc @Sachin-chaurasiya
