### ISSUE TITLE
Restore Backup Bug

### ISSUE THREAD

**Issue by FelipeArruda** [open-metadata/OpenMetadata#10311]
**Affected module**
Backend

**Describe the bug**
When restore the backup from another environment, I'm facing some problem with openmetadata_server, only still starting.
No error occur when restoring, just when start up the openmetadata_server.
I did it with openmetadata_server off

**To Reproduce**

Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/5818475/221050811-8471df06-8537-4335-9622-31927d932d2a.png)

**Expected behavior**

**Version:**
 - OS: Ubuntu
 - Python version: 3.10
 - OpenMetadata version: Backup from 0.13.1 to restore 0.13.2
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==0.13.2

**Additional context**

**Comment by FelipeArruda** [comment]
Hey @harshach. 

I was looking for a solution and found out why I couldn't restore to a newer version.

I did backup from 0.13.1 to restore on 0.13.2 and got error.

So, I created a new environment with 0.13.1 version and restore successfully then upgraded to 0.13.2.

May I close this issue, or not?

Thanks.

**Comment by nahuelverdugo** [comment]
Hi @FelipeArruda, thank you for the update. I will close this issue since the error only happens when we try to restore a backup from an older version to a newer version which is not supported.
