### ISSUE TITLE
Creation of Domain umbrella to tag assets and Glossaries to a higher level grouping

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10328]
**Is your feature request related to a problem? Please describe.**
Currently, in the OMD explore tab, all search functionality is related to technical metadata (what's my service, what's my application, what's my table) and it is lacking a Business Context, higher level grouping. 
For example, I might want to have all my Product related assets under one logical, easily findable umbrella (my Product systems, my product pipelines, my product related glossaries, my product related tables in the data platform).

**Describe the solution you'd like**
Creation of Domains tag, but which is more exposed to the end-users.  Provides "I know where to click straight away" to the user.
**So by clicking on the domain, I am taken to the explore tab, but everything I see is already pre-filtered by the chosen domain.** This would really improve user experience as they are exposed to assets that is relevant to them. Especially good for business side users of specific function.

**Describe alternatives you've considered**
Using tags, however tags are not very "in you face" obvious, and we have a lot of tags and using them for initial search is not convenient. 

**Additional context**

**Comment by sureshms** [comment]
@DovileKr please see a more comprehensive implementation of Domains that adds domain as a first-class entity instead of depending on Tags or Glossaries in #12142. Please provide feedback on that issue. I am closing this issue for now.

**Comment by DovileKr** [comment]
**Feedback** 
Domains and Glossaries to be  provided together "For example, I might want to have all my Product related assets under one logical, easily findable umbrella (my Product systems, my product pipelines, my product related glossaries, my product related tables in the data platform)."

Domain examples that we have provided based on datahub features:  https://github.com/open-metadata/OpenMetadata/issues/10327
