### ISSUE TITLE
Tag asset from Glossary Term. Specify "Golden Source". Filter by Asset Type.

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10332]
**Is your feature request related to a problem? Please describe.**
1. Currently I can only added glossary term (as tag) from Tables and Columns. However, I might want to do it from Glossary Term. 
For example, Data Steward just added a description for a term and  wants to specify that this column, in this table is the golden source for this glossary term.  It would not be user friendly for them to have to go and navigate to that table and add a tag. 
2. Also, same term might tagged to many different assets. However, not all assets are the same. Some of them are the golden source for the term (for example customer master table in CRM or official Customer Master Datamart in DWH). They should be highlighted, ranked hire.
3. Important terms like Product, will have many asserts tagged to them - tables, reports, dashboards. View from Business glossary will be very messy and that tab will be difficult to use with no filter
 
**Describe the solution you'd like**
1. Being able to tag assets from Glossary - to facilitate data stewards. 
2. Being able to specify if tagged asset is special. At least marking a golden source, but it also can be: Origin Source, Golden Source.  to facilitate data stewards. 
3. Being able to filter Glossary term assets by type (tables, reports, dashboards or so on). To make Business Glossary an easy entry point for discovering data assets. 

**Describe alternatives you've considered**
Nothing available.

**Additional context**
Example. just by adding 6 asset tags, it become difficult to interpret the results:
![image](https://user-images.githubusercontent.com/26750060/221196557-0fcc9047-135a-431e-bd55-ed814370d34d.png)

Inspiration from DataHub project
![image](https://user-images.githubusercontent.com/26750060/221198625-4e805254-6e88-454d-8551-35080abe5833.png)
https://demo.datahubproject.io/glossaryTerm/urn:li:glossaryTerm:77fabc0a-b223-448c-a995-ee85887c334a/Related%20Entities?is_lineage_mode=false

**Comment by sureshms** [comment]
@DovileKr, assets can now be added on the Glossary page (except you can't tag a column but only at the asset level). You can also filter the assets by asset type on that page.

I am going to mark it as (mostly) completed. Can you please create a separate issue for pending issues?
