### ISSUE TITLE
Being able to link Issue Tickets to Data Assets: for example for tracking  DQ issues

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10333]
**Is your feature request related to a problem? Please describe.**
Data assets experience data quality issues. Source tables, DW tables, Reports. People raise Service Desk Tickets and Change Request on the data assets:
- Service Desk Tickets - data incorrect, data not updated, data  doesn't match
- Change Request  - need a new column, 

**Describe the solution you'd like**
We would like to be able to link these requests from Service systems (like Jira or Service now) so that:
a) Assets users could see all open issues and request relating to the data asset. 
b) Data Governance users, Data Stewards, could track how many issues or request there is on the assets and how it tracks over time.

**Describe alternatives you've considered**

- Using announcements and pasting urls of related issues and requests there. While it is great notify users, the data can't be used for data quality reporting. 
- Getting Jira Webhook to post in comments, but again this not helping with tracking DQ issues metrics

**Additional context**

**Comment by harshach** [comment]
we shipped incident manager for this to manage via OpenMetadata itself.
