### ISSUE TITLE
 searching for an ingestion pipeline is limited to the current page

### ISSUE THREAD

**Issue by itaise** [open-metadata/OpenMetadata#10345]
**Affected module**
UI

**Describe the bug**
We have 40 pages of ingestion pipelines for one database service. 
When searching for an ingestion pipeline which is on a different page, it does not find it - it looks only on the current page. 

**To Reproduce**
Go to Database service Ingestions tab, and search for Ingestion pipeline name which is not on the same page, it will not be found. 

**Version:**
 - OpenMetadata version: 0.13.12

**Comment by chirag-madlani** [comment]
Already taken care here: https://github.com/open-metadata/OpenMetadata/issues/16585
We moved to ES search from local search which should address the issue here
