### ISSUE TITLE
Add method to update GlossaryTerm in Python SDK

### ISSUE THREAD

**Issue by JonathanBonnaud** [open-metadata/OpenMetadata#10343]
**Is your feature request related to a problem? Please describe.**
When creating Glossaries from SDK, I'm using `CreateGlossaryTermRequest`  with `create_glossary_term` method, but it can only create new term and it will not update existing terms.

**For example:**
We have this as a first pass:
`Parent A > Child 1`
`Parent B > Child 2`
Then on second pass we want to change Child 2's parent to Parent A, then we get:
`Parent A > Child 1`
`Parent A > Child 2`
`Parent B > Child 2`
`Child 2` is created as a new term, and not updated the existing term.

**Describe the solution you'd like**
We could have a simple method `create_or_update_glosary_term` using the API endpoint [PUT /v1/glossaryTerms](https://docs.open-metadata.org/swagger.html#operation/createOrUpdateGlossaryTerm)
 
As discussed on Slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1677233629287539?thread_ts=1677228836.335459&cid=C02B6955S4S

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pmbrull** [comment]
Thanks @schlameel , appreciate the effort in bringing all these methods to the sdk

**Comment by schlameel** [comment]
This will be the third mixin that will use a protected method called `_fetch_entity_if_exists` which originated in [patch_mixin.py](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py). I am moving this method to a super class which the three classes using the method will inherit. I am proposing to put the super class into `/ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin_utils.py`.

With #3809 I moved a bunch of PATCH mixin specific constants to `ingestion/src/metadata/ingestion/ometa/patch.py`. The constants were all strings and were grouped into enums.  Should these enums be moved to the same file? Some of the methods using the enums accept them as parameters so the user will need access to them if that sways the decision.

As a matter of process, does the team prefer one commit with a description that covers all changes or a commit for each file (or logical groups of files or similar)?

**Comment by pmbrull** [comment]
hi, sounds good, we can move these to `patch_mixin_utils`.

Regarding the commits, whatever works best for you. We will squash merge the PR, so as long as the name references the issue and the description works, we're good to go
