### ISSUE TITLE
Filter test suites by owner / name

### ISSUE THREAD

**Issue by itaise** [open-metadata/OpenMetadata#10354]
Hi, 
We have many test suites in openmetadata quality section, and would like to filter these test suites by owner. 
We would like to have a drop down menu with owners list (teams list) so that each team can see their tests among the hundreads of test suites that we have. 

Alternatively, a search bar to look for suites with a specific name will also be useful. If you will implement this option, we will add the owner name as a part of the test suite name. 

Thanks a lot in advance!

**Comment by harshach** [comment]
@ShaileshParmar11 this and filter by status and other options should be available in data quality page.

**Comment by harshach** [comment]
@chirag-madlani @ShaileshParmar11 we haven't made any progress on this, it was discussed to be part of 1.4.0

**Comment by ShaileshParmar11** [comment]
Re-opening as UI side changes still left
