### ISSUE TITLE
Save OM DAGs to github

### ISSUE THREAD

**Issue by khalepski** [open-metadata/OpenMetadata#10375]
**Is your feature request related to a problem? Please describe.**
The OM saves new created DAGs in OS which is requires Airflow to have the same storage as open metadata server.
As we are running OM in k8s it requires to create shared storage between OM and Airflow, which is not so good solution for production environment.

**Describe the solution you'd like**
We would like to create Airflow cluster to support big load and high availability. It would be great to have an ability for OM to save their DAGs to github and we will sync them using https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html#mounting-dags-using-git-sync-sidecar-with-persistence-enabled

**Describe alternatives you've considered**

**Additional context**

**Comment by hsnprsd** [comment]
I think currently the synchronization of DAGs between OM and Airflow is not so good. The OM should try to sync DAGs periodically in a persistence storage and Airflow should read DAGs from the persistence storage as @khalepski said.

**Comment by harshach** [comment]
one can create the DAGs manually or set the Airflow to sync back to github
