### ISSUE TITLE
Error when ingesting metadata from Databricks SQL if column of type Array is present

### ISSUE THREAD

**Issue by felipecgonc** [open-metadata/OpenMetadata#10404]
**Affected module**
Ingestion Framework

**Describe the bug**
We are currently trying to add OpenMetadata to our Lakehouse stack which centers around Databricks SQL. Some of our ingestions are presenting errors when trying to fetch metadata, and we have found the error occurs specifically for tables which contain one or more columns with the type _Array_.

Here is an example of what logs show when this error occurs:

```
[2023-03-02, 00:02:35 UTC] {common_db_source.py:359} WARNING - Unexpected exception to yield table [profiles]: (databricks.sql.exc.OperationalError) Query execution failed. State: ERROR_STATE; Error code: 0; SQLSTATE: None; Error message: org.apache.hive.service.cli.HiveSQLException: Error running query: [_LEGACY_ERROR_TEMP_1117] org.apache.spark.sql.AnalysisException: spark_catalog requires a single-part namespace, but got [].
```

Further down, we see that the following query is being ran on Databricks SQL:

`DESCRIBE hive_metastore.profiles events`, where `hive_metastore` is a custom catalog name defined in the Databricks SQL connection.

We have investigated the source code, and found the following snippet in the file `ingestion/src/metadata/ingestion/source/database/databricks/metadata.py` around line 126:

```
        if col_type in {"array", "struct", "map"}:
            if db_name is not None:
                rows = dict(
                    connection.execute(
                        f"DESCRIBE {db_name}.{table_name} {col_name}"
                    ).fetchall()
                )
            else:
                rows = dict(
                    connection.execute(f"DESCRIBE {table_name} {col_name}").fetchall()
                )
```

We believe the bug is located right around this part. We have tested both queries used for Array/Struct/Map types manually on Databricks SQL, and got the following results:

- `DESCRIBE {db_name}.{table_name} {col_name}` results in the same error observed in the log snippet above
- `DESCRIBE {table_name} {col_name}` results in the following error: `[TABLE_OR_VIEW_NOT_FOUND] The table or view {table_name} cannot be found. Verify the spelling and correctness of the schema and catalog.`

We think something like `DESCRIBE {db_name}.{schema_name}.{table_name} {column_name}` would work, but are unsure of the logic behind why this was written the way it is now, so we would like more opinions before opening a PR.

**To Reproduce**

Connect OpenMetadata to Databricks SQL and try to run a normal ingestion on any table with at least one column of type Array (possibly the same occurs for Struct and Map types).

**Expected behavior**
We expected the ingestion to run successfully and the `DESCRIBE` query used for Array columns to yield the corresponding metadata correctly.

**Version:**
 - OpenMetadata deployed on Kubernetes using Helm Chart version 0.0.50 and Docker images on version 0.13.1
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: `openmetadata-ingestion==0.13.1.8`

**Comment by MilanBariya** [comment]
Hello @felipecgonc ,
This is the same issue(#10420). 
And this #10469 PR will fix that.
To avoid the duplicate issue closing this one.

-Thanks
