### ISSUE TITLE
Table level tags does not show the terms which are at the beginning of the hierarchy for tagging at table level

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10413]
**Affected module**
UI

Issue : 
The tags option at the table level is not allowing to mark the terms which are at the beginning of the hierarchy. Though the terms at the end of the hierarchy can be marked.

It should pick all the terms regardless of their hierarchy level.

table view 

![image](https://user-images.githubusercontent.com/110607559/222661031-246544b2-72e4-40cd-adcf-2a03de564698.png)

term not appearing

![image](https://user-images.githubusercontent.com/110607559/222661105-aa0d1a6e-a2d1-49cb-81a0-ab405e4711f5.png)

term appearing

![image](https://user-images.githubusercontent.com/110607559/222661163-9462240e-aeac-46f6-bae7-aa904823fa50.png)

**Comment by harshach** [comment]
This issues is fixed
