### ISSUE TITLE
Glossary Bulk Upload Failure

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10414]
**Affected module**
UI

**Describe the bug**
Glossary Bulk Upload through UI is not getting passed. Sample File is attached. The format is same as advised.
Also have tried in both ways, with and without * in column names where required (format is taken by exporting the csv).

[party testing - Sheet1 (3).csv](https://github.com/open-metadata/OpenMetadata/files/10880816/party.testing.-.Sheet1.3.csv)
[party testing - Sheet1 (4).csv](https://github.com/open-metadata/OpenMetadata/files/10880826/party.testing.-.Sheet1.4.csv)

screenshot

![image](https://user-images.githubusercontent.com/110607559/222692767-041cf43b-64e9-4096-bba6-fad972d18be0.png)

![image](https://user-images.githubusercontent.com/110607559/222693214-8dbbbaf1-700a-4633-8843-59e8f52ddc2f.png)

**Version:**
 OM-13.2

**Additional context**

**Comment by ShaileshParmar11** [comment]
Have you tried exporting 1st? looks like your template is old! please export the glossary 1st to get a fresh template, also parent name should be a full hierarchy starting from glossary name 
here is example CSV file for your reference
[100DataSuccess.csv](https://github.com/open-metadata/OpenMetadata/files/10880928/100DataSuccess.csv)

**Comment by ShaileshParmar11** [comment]
Hi @lailapatel can you please confirm if it worked for you or not?

**Comment by harshach** [comment]
@lailapatel isn't that error is clear ? it does say invalid header. Did you try fixing and trying out?
