### ISSUE TITLE
Entity Type: Description Request | Comment

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#10428]
**Is your feature request related to a problem? Please describe.**
Today, I can only create an alert when table is getting updated: Event Type = Entity Updated.
However, we are not able to configure alerts when there is a `Comment` or `Description request` on a table, which is what we want to send alerts for. Right now we can only send alerts when a table is being updated (which we don't need to send alerts for).

![image](https://user-images.githubusercontent.com/102999683/222842006-08aebe19-caee-4422-85e5-772f3ebee038.png)

**Describe the solution you'd like**
Configure event types for alerts to `Comments` and `Description request`.

**Comment by harshach** [comment]
@mohityadav766 this should happen by default throw email/slack.

**Comment by harshach** [comment]
we will addressing this as part of https://github.com/open-metadata/OpenMetadata/issues/10757
