### ISSUE TITLE
Profiler :: passing avg,max,mean for non-numerics data type 

### ISSUE THREAD

**Issue by SandipDogra** [open-metadata/OpenMetadata#10432]
Hey team, please check profiler is generating  mathematical sql syntax's for non-numerical data type field's/column 

Database Redshift

Sample SQL - here brand_id is a text like '123455gjbghj89u9'

below is the sample generated code
/* {"app": "OpenMetadata", "version": "0.13.2.4"} */
WITH zoho_bills_rnd AS (
  SELECT
    zoho_bills.bill_date AS bill_date,
    zoho_bills.transaction_posting_date AS transaction_posting_date,
    zoho_bills.due_date AS due_date,
    zoho_bills.bill_id AS bill_id,
    zoho_bills.vendor_name AS vendor_name,
    zoho_bills.entity_discount_percent AS entity_discount_percent,
    zoho_bills.payment_terms AS payment_terms,
    zoho_bills.payment_terms_label AS payment_terms_label,
    zoho_bills.bill_number AS bill_number,
    zoho_bills.purchaseorder AS purchaseorder,
    zoho_bills.currency_code AS currency_code,
    zoho_bills.exchange_rate AS exchange_rate,
    zoho_bills.balance AS balance
    
  FROM
    zoho_bills_rnd
  WHERE
    zoho_bills_rnd.random <= 100.0
)
SELECT
  avg(branch_id) AS mean,
  count(branch_id) AS "valuesCount",
  count(DISTINCT branch_id) AS "distinctCount",
  min(branch_id) AS min,
  NULL AS anon_1,
  max(branch_id) AS max,
  NULL AS anon__1,
  SUM(
    CAST(
      CASE
        WHEN (branch_id IS NULL) THEN 1
        ELSE 0
      END AS BIGINT
    )
  ) AS "nullCount",
  STDDEV_POP(branch_id) AS stddev,
  SUM(CAST(branch_id AS BIGINT)) AS sum
FROM
  zoho_bills_sample
LIMIT
  1

**Comment by harshach** [comment]
@SandipDogra can you let us know what the data type in OpenMetadata table's schema here.

**Comment by SandipDogra** [comment]
in Openmetadata it is BIGINT 

and please find the code run error
<img width="638" alt="image" src="https://user-images.githubusercontent.com/113590544/222928273-4ec43cc4-5c7d-48f4-b29d-cf094c4ebc5d.png">

**Comment by harshach** [comment]
@SandipDogra whats the type in your redshift db? its weird that its getting translated to BIGINT

**Comment by TeddyCr** [comment]
To add a bit more context here, we won't compute `MIN`/`MAX` for non numerical data type -- see below.
https://github.com/open-metadata/OpenMetadata/blob/df2001418e536f11962a3acdeaa79b651328aef2/ingestion/src/metadata/profiler/metrics/static/min.py#L37-L41

We do compute the `MEAN` for some non numerical value as the average length of the string. 

Type is determined by OM type. @SandipDogra if you could confirm the tyoe of your field in redshift that would be great. 
![Screenshot 2023-03-06 at 8 24 25 AM](https://user-images.githubusercontent.com/13626425/223044645-5190350d-b3ab-48f5-98f0-98e1d73500b2.png).

You can also exclude ID columns from the profiler. More info [here](https://docs.open-metadata.org/connectors/ingestion/workflows/profiler#profiler-options-1) on how to do it.

**Comment by pmbrull** [comment]
@TeddyCr I believe this should be sorted already, correct? cc @ulixius9

**Comment by TeddyCr** [comment]
@pmbrull correct.
