### ISSUE TITLE
Adding support for GCP secret manager integration

### ISSUE THREAD

**Issue by masterlittle** [open-metadata/OpenMetadata#10431]
**Is your feature request related to a problem? Please describe.**
There is no support to integrate with GCP Secret Maanger

**Describe the solution you'd like**
Similar to Aws secret manager integration, it would be great if we can have a gcs secret integration

**Describe alternatives you've considered**
None

I'm open to working on this. Looked through the code and saw that there is both a python implementaion and java implementation of AWS currently. Are both needed initially? If someone can guide me on the files to touch, would be helpful

**Comment by harshach** [comment]
duplicate of #9875
