### ISSUE TITLE
UI - Error when showing Policy Tags

### ISSUE THREAD

**Issue by FelipeArruda** [open-metadata/OpenMetadata#10446]
**Affected module**
UI

**Describe the bug**
When move 3 time using Next Button, an error occur on the screen.

I have 49 policies tags ingested from biquery

**To Reproduce**
Go to Govern -> Tags and move 3 time using the Next Button

- Button
![image (2)](https://user-images.githubusercontent.com/5818475/223106862-c79fa45f-b4a9-424c-aa49-d6a25762ae10.png)
- Error - after click 3 times
![image (3)](https://user-images.githubusercontent.com/5818475/223106919-1418db0b-9e5b-40a6-a059-38133d21331d.png)

**Expected behavior**
Show all policy tags

**Version:**
 - OS: Ubuntu
 - Python version: 3.10
 - OpenMetadata version: 0.13.2
 - OpenMetadata Ingestion package version:

**Comment by harshach** [comment]
@chirag-madlani @ShaileshParmar11 lets fix this and add a cypress test for this pagination behavior.
