### ISSUE TITLE
update translation with latest changes

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#10453]
- [ ] @mark800 Can you help us in updating zh-cn again with the latest changes?
- [ ] @TeddyCr Can you update fr-fr  again
- [ ] @pmbrull Need help in Spanish and Catalan

**Comment by chirag-madlani** [comment]
Refer steps to add new localisation file here: https://github.com/open-metadata/OpenMetadata/tree/main/openmetadata-ui/src/main/resources/ui#steps-to-run-openmetadata-ui

**Comment by pmbrull** [comment]
Spanish done
