### ISSUE TITLE
To show more records on one page upon quering the tables

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10459]
**Is your feature request related to a problem? Please describe.**
UI

**Describe the solution you'd like**
To show more than 10 records or may be all on one page upon querying a search term in the table search option. Currently, it only gives 10 records, so many pages for the users to check for the relevant one.

![image](https://user-images.githubusercontent.com/110607559/223430689-829f7949-1da9-4cde-84e6-3ca84f06af06.png)

**Comment by sureshms** [comment]
This issue has already been fixed.
