### ISSUE TITLE
Some Column Attributes aren't being displayed, even if populated

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10451]
**Affected module**
UI. Highlighted in yellow are attributes that are not visible anywhere on UI. 

**Describe the bug**
I have populated precision, scale, ordinal position, display name, dataLegth column attributes. they have been consumed successfully (I can retrieve them via API), but they are not shown anywhere on the UI.

**To Reproduce**
Populate a few columns for a table (char and decimal) with all attributes populated.
![image](https://user-images.githubusercontent.com/26750060/223254480-6e64b797-284b-42f2-a4d5-dca7c390befd.png)
![image](https://user-images.githubusercontent.com/26750060/223254622-f8099aa2-9d96-41b5-8810-4203f2140e0b.png)
Screenshots or steps to reproduce

**Expected behavior**
I would expect this information is being collected to display to OMD data catalog users. 

**Version:**
 - OS: [e.g. iOS]. Docker Deployment
 - Python version:
 - OpenMetadata version: [e.g. 13.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Hello @DovileKr, We are planning to remove the column of precision and scale, as we are already showing it with dataType, please find the below screenshot for the same, and let us know if its works for you or not!
![image](https://user-images.githubusercontent.com/71748675/232232793-9fac5566-b258-4e5f-9ead-8c8b3b65b5d0.png)
