### ISSUE TITLE
To have glossary tagging seperate then the tags tagging at table level

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10461]
**Is your feature request related to a problem? Please describe.**
UI

**Describe the solution you'd like**
Currently, the glossary terms are getting tagged at table level with the help of ' tags' option. Which means tags and terms are getting tagged using the same option and are appearing in an overlapping way.

We can have two options here at table level , one to add glossary term and other to add/show tags.

![image](https://user-images.githubusercontent.com/110607559/223438578-12d6544f-2cb5-489d-b39b-944ca3c619b8.png)

**Comment by harshach** [comment]
@lailapatel closing this in favor of this ticket https://github.com/open-metadata/OpenMetadata/issues/10330 . both are talking about the same feature. Please add your thoughts in that ticket
