### ISSUE TITLE
To have assigning task option for Glossary.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10460]
**Is your feature request related to a problem? Please describe.**
UI

**Describe the solution you'd like**
Currently, tasks can be assigned at table level. Since we also need to collaborate around glossary, therefore, we need an option for assigning tasks at glossary level other than the reviewer option.

available option at table level only.
![image](https://user-images.githubusercontent.com/110607559/223436127-df11eecf-4cba-4e39-a94e-f8350bc40247.png)

**Comment by sureshms** [comment]
Duplicated of #12166
