### ISSUE TITLE
Tableau Dashboard Lineage Drawn to Table in Different Schema

### ISSUE THREAD

**Issue by joal-zb** [open-metadata/OpenMetadata#10483]
**Affected module**
Ingestion - Tableau

**Describe the Bug**
We have a Snowflake database service with ingestion configured to consume all schemas from our production database. In this database, we have a public schema that holds a number of dimension and fact tables. This same production database also holds snapshots of the public schema (named public_yyyy_mm_dd based on the date the snapshot was taken). The snapshot schemas basically hold copies of the tables from the public schema, which share names. 

When we ran our Tableau ingestion, it seems to have drawn lineage from many dashboards to one of these snapshot schemas, rather than the actual public schema where the dashboards are sourcing their data from. I confirmed that the Tableau metadata API is returning the correct schema, and not the snapshots. 

We were able to temporarily fix this on our end by filtering the snapshot schemas from ingestion and removing the previously ingested metadata from our instance of Open Metadata. However, I assume that there could be a case in the future where table names are legitimately shared across schemas (in this case we couldn't just filter our the 'duplicates') and we'd need lineage to be drawn correctly between dashboards. 

**To Reproduce**

1. Set up a Snowflake database service
2. Configure ingestion against a Snowflake database with multiple schemas containing identical tables (same column schema, and same name) 
3. In tableau, create a data source that references one of these tables that are identical across these schemas
4. Create a dashboard that uses the data source created in step 3
5. Run Open Metadata Tableau ingestion

**Expected behavior**
Dashboard lineage is drawn to the correct source table in Snowflake

**Version:**
 - OS: debian
 - Python version: 3.9
 - OpenMetadata version: 0.13.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[tableau]==0.13.2`]

**Additional context**

**Comment by pmbrull** [comment]
let's handle this after adding the dataModel changes

**Comment by nahuelverdugo** [comment]
This should be fixed by this [PR](https://github.com/open-metadata/OpenMetadata/pull/10923). 

@joal-zb could you confirm once the `1.0` version is released? Otherwise, feel free to reopen it. Thank you.
