### ISSUE TITLE
Add system identifier for the tags

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#10487]
Whichever classification is of type system should have an identifier. 
<img width="433" alt="Screenshot 2023-03-09 at 8 44 40 AM" src="https://user-images.githubusercontent.com/40225091/223907353-5b24f4b2-3677-4fa0-8560-82a6aab8a267.png">

**Comment by harshach** [comment]
@devyani-kaushik lets use a better styling for this. We can use badge styling

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=18582%3A22371&t=ZtvaH5N1wXZ11X9z-1
<img width="223" alt="Screenshot 2023-03-15 at 2 54 42 PM" src="https://user-images.githubusercontent.com/103238069/225265741-6bcbf761-4194-49e2-ab0b-08be998b6c4f.png">

@chirag-madlani
