### ISSUE TITLE
High-level API - Add Versioning Mixin

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1048]
Prepare a new mixin with the new versioning functionalities:
- GET specific version
- List versions -> here we should parse the response and convert it to a List[T] directly

In `metadata/ingestion/ometa/ometa_api.py` we have defined the new client interface `OpenMetadata`, which helps us make calls to the REST endpoints in a safe and comfortable way.

For this issue, you'll need to review the API documentation and prepare:
- if needed, a new `suffix` in `OpenMetadata.get_suffix` to handle versioning
- a new mixin in the `mixins` module to handle version-specific operations.

You can review the current implementations to see how to work with `TypeVar`s  to have a dynamic definition of our methods.

The Acceptance Criteria here is:
- There is a new mixin that handles versioning
- There is a new test that covers all the defined methods with any pydantic model as an example.

**Comment by TeddyCr** [comment]
@pmbrull I'd love to take this one if it is good w/ you.

**Comment by pmbrull** [comment]
> @pmbrull I'd love to take this one if it is good w/ you.

That would be awesome @TeddyCr, just assigned you the issue 🎉 

To get you started I'd recommend having a look at the API definitions: https://sandbox.open-metadata.org/docs#operation/listVersions_3

For this issue, we need to revisit the versioning of the Entities as well as the ChangeEvents.

Let me know if there is anything I can help you with!

Thanks 🙏

**Comment by TeddyCr** [comment]
Thanks @pmbrull, I think it'd be super helpful to have a quick syncup to get more background on this. 🙂

**Comment by TeddyCr** [comment]
Hey @pmbrull merry Christmas 🎅🎄. 

I was working on this and I was wondering after calling the endpoint what base model is it supposed to instantiate:
- the entity model
- the entity versioning model

or is it supposed to simply return the response?

```python
resp = self.client.get(<entity>/<entity_id>/versions/<version>)
...
```

**Comment by pmbrull** [comment]
Hi @TeddyCr, merry christmas, nice hearing from you 🎉 

I would say, that after requesting a specific version, we should get back the Entity itself at that point in time. So from `v1/tables/{id}/versions/{version}` we should expect a `Table` model.

WDYT?

**Comment by TeddyCr** [comment]
(Apologies for the delay on that, I did not time it well as I went from on duty to vacation) 😕

Yes, that makes a lot of sense.

**Comment by pmbrull** [comment]
Thanks, @TeddyCr! And do not worry at all, we're just happy you are willing to handle this. It is not a blocker, so feel free to take as much time as needed.

Let me know if you have any questions 🤗

**Comment by pmbrull** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/2018
