### ISSUE TITLE
Show dbt node fields in the UI

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#10502]
**Feature**
Below mentioned fields are captured on the ingestion side but not displayed on the UI for dbt:

- rawSql (Display this field if the sql field is empty)
- path

<img width="416" alt="image" src="https://user-images.githubusercontent.com/28966081/224237227-9b522079-db0d-462e-98a3-7b1d7994f678.png">

**Comment by chirag-madlani** [comment]
@devyani-kaushik Can you help us to show path field in the UI?
