### ISSUE TITLE
Tasks assigned to Team owner doesn't have any options to update/close

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#10505]
**Affected module**
UI

**Describe the bug**
Create a task "request description" and assign it to the Team.
Now log in as a member of that team. 
UI shows it as a pending task, and going to the task will present this UI

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/38649/224254917-64087053-036d-4350-b476-5f833f0806b5.png">

As the team member of this task, I can't do any operation on this page
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/224254952-ebf6fd58-337a-4345-a197-23f9882543db.png">

Other issues, clicking on the Team name takes us to the users/cloud_infra instead of the team's page.

If the task is assigned to the individual the UI shows "Close With Comment", "Add Description," etc..

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani any updates on this?

**Comment by chirag-madlani** [comment]
@harshach will wrap this in 1.0

**Comment by karanh37** [comment]
@harshach @sureshms - we need backend support for this.
Have added support from UI. Members of team will now be shown the buttons.

![Screenshot 2023-04-03 at 10 33 20 AM](https://user-images.githubusercontent.com/33024356/229416183-3092dad5-f324-4bdd-b0ad-edda1f85f5b0.png)
![Screenshot 2023-04-03 at 10 33 49 AM](https://user-images.githubusercontent.com/33024356/229416191-6d0a3cbb-47a3-4ed0-9352-d6d1afa0ea57.png)
![Screenshot 2023-04-03 at 10 34 18 AM](https://user-images.githubusercontent.com/33024356/229416197-4b044b10-dddc-4fbd-9caa-8bfb5803eae8.png)
