### ISSUE TITLE
Glossary - Assigning owners doesn't work for non-admin users

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#10504]
**Affected module**
UI
**Describe the bug**
Login as admin user

Try to change the owner of a term. Here we do not show any teams or users if the logged-in user is not an admin.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/224248395-ad959ee8-6545-4202-8128-c9937571c667.png">

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/38649/224248606-bc414407-1c9f-4651-af29-7f52df0cc350.png">

 We shouldn't be allowing the user to change the owner of the glossary term since the logged-in user is a non-admin user and is not the owner of the Glossary or the glossary term. If the user has the necessary permissions, they should get all the results here.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
As discussed we will be showing the teams and users list based on permissions users have.
