### ISSUE TITLE
Glossary Related terms overflows

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#10503]
**Affected module**
UI

**Describe the bug**
Glossary Related terms overflow the page and don't show all the related terms in some cases.

1. We do not have to cancel to remove the terms 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/38649/224245696-e6977323-b113-4481-bfb6-109f63b41f53.png">

2.  There are many more, we need to wrap the content around to show a better view of it.
![image](https://user-images.githubusercontent.com/38649/224245995-f3ddf642-6e26-4632-9419-3b8bbd90da53.png)

3. child terms appear at the same level in the hierarchy display as the parent  
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/38649/224246354-95e69209-0545-4427-b458-28ec7ce60b6b.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/38649/224246423-b61fdaa0-2f31-4811-a6ac-3b245d79e870.png">

4. same level terms appear to be indented due to the > mark. This should be more elegant here 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/38649/224246846-0c62e22e-4ae5-4356-a22e-037adec19727.png">
we do this well on Teams page 
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/38649/224246957-62e47ed0-2e42-4ecf-8239-783abc52cf0c.png">
but it needs to be added on the Glossary side.
also may be using + sign will look better than the > mark cc @devyani-kaushik 

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
@karanh37 Did we fix word-break in Teams page as well, or it's still pending
