### ISSUE TITLE
Align import strategy

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1050]
In the `ingestion` module we sometimes make the imports with relative paths and others from the installed `metadata` package.

We need to define a cohesive strategy here.

Example: `metadata.py`

```python
from metadata.config.common import ConfigModel
from metadata.ingestion.api.common import Record, WorkflowContext
from metadata.ingestion.api.source import Source, SourceStatus
from metadata.ingestion.ometa.ometa_api import OpenMetadata

from ...generated.schema.entity.data.dashboard import Dashboard
from ...generated.schema.entity.data.table import Table
from ...generated.schema.entity.data.topic import Topic
from ..ometa.openmetadata_rest import MetadataServerConfig
```

**Comment by harshach** [comment]
Thanks for raising this. We should always use absolute paths.

**Comment by pmbrull** [comment]
Thanks, @harshach, should those be from the installed `metadata` module or absolute paths from `ingestion.src`?

**Comment by harshach** [comment]
I think its good to use metadata. In case in future if we want to make that as a common package we can move it out

**Comment by pmbrull** [comment]
I think we are good on this now
