### ISSUE TITLE
Refactor ldap_rest_users User Entity

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1051]
Refactor `ingestion/src/metadata/ingestion/sink/ldap_rest_users.py` to work with the proper `User` Entity from `pydantic` models, instead of relying on a custom-defined `MetadataUser`.

EDIT: I actually think that this class is not being used at all. Double-check and remove it if necessary!

**Comment by omriAl** [comment]
@pmbrull I will take this one (my first issue, just to get my hands dirty)

**Comment by pmbrull** [comment]
Thanks, @omriAl!

Please, let me know if you have any questions or issues while working on this. Basically, the point of the task at hand is to have you prepare the local instances of the metadata server and get a bit familiar with the code.

Thanks

**Comment by omriAl** [comment]
@pmbrull Thanks, As mentioned, I will also deprecate MetadataUser class.
It's used only on tests, which should be modified anyways after this change.

**Comment by omriAl** [comment]
@pmbrull Hi.
currently, org.openmetadata.catalog.api.teams.CreateUser schema does not match the User class.
As I see this, we have 2 options - either changing the User class to have the same attributes as the schema, or changing the org.openmetadata.catalog.api.teams.CreateUser schema, which I'm guessing will affect other places as well.

what do you think is the better approach here?
seems like option a is preferable, but just wanted to make sure.
Thanks!

**Comment by pmbrull** [comment]
Hi, @omriAl, sorry what do you mean by `CreateUser` not matching the `User` class?

In the JSON schemas, we have a couple of definitions for each Entity. The entity itself, which describes the properties that define an Entity (in this case [user](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/teams/user.json)), and then the Create Entity (in this case [CreateUser](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/api/teams/createUser.json). They are a bit different from the Create, for example, does not require the `id` field, which is automatically generated when running the `POST` operation to the backend, and it takes the definitions from the Entity schema.

Is this what you are referring to? Sorry if I misunderstood! Or is there some field not properly defined?

Thanks!

**Comment by omriAl** [comment]
There are some discrepancies between the User class and user.json schema.
for example first_name & last_name doesn't appear in user.json but are attributes of the User class.
and the other way around - user.json has description, but User class does not.

It seems like the best way here is to modify the user class to match the user.json schema.
I just want to verify that there is no objection to that.

**Comment by pmbrull** [comment]
> @pmbrull There are some discrepancies between the User class and user.json schema. for example first_name & last_name doesn't appear in user.json but are attributes of the User class. and the other way around - user.json has description, but User class does not.
> 
> It seems like the best way here is to modify the user class to match the user.json schema. I just want to verify that there is no objection to that.

Aaaah sorry I completely misunderstood. What User class are you taking? We should be working with the one under `metadata/generated`, which id automatically creared based on the JSON schemad

**Comment by pmbrull** [comment]
Closed with https://github.com/open-metadata/OpenMetadata/pull/1473
