### ISSUE TITLE
Mark Deleted Tables must be clear on the behaviour

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#10514]
**Affected module**
Ingestion Framework

**Describe the bug**
When running an ingestion workflow with the `Mark Deleted Tables` option enabled, it deletes all the tables not present in the source. But when a filter in the table name is set, it deletes all the tables that have been filtered out.

**To Reproduce**
1. Ingest data source
2. Edit ingestion with Mark delete table enabled and with a table filter.
3. Tables filtered out will be deleted.

**Expected behavior**
It depends on what we want to do here:
1. Remove only tables when they have been deleted in the data source, regardless of the table filter applied. 
2. Determine what will be deleted when `Mark Deleted Tables` is enabled. For example, will the filter be considered?

<img width="678" alt="image" src="https://user-images.githubusercontent.com/11074908/224300771-8d476489-4f7c-4074-8b00-6417f0a11ce5.png">

**Version:**
 - OpenMetadata version: 0.13.2

**Additional question**

In addition, @pmbrull, should we remove the schemas when `Mark All Deleted Tables` instead of leaving the schemas empty?

**Comment by pmbrull** [comment]
we could clean up the schema, yes
