### ISSUE TITLE
Feature Request : Polish Ingestion UI

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#10510]
For this release, we are targeting two things
- [All ingestion connector form should display relevant docs](https://github.com/open-metadata/OpenMetadata/issues/6981)
- Make test connection flow more intuitive by providing message feedback ( like what metadata can be extracted, what cannot be extracted, etc.)

**Comment by pmbrull** [comment]
## Test Connection Flow

1. You can get the steps' names and descriptions of each step by calling `http://localhost:8585/api/v1/services/testConnectionDefinition/name/{name}`.
2. The `name` parameter will be the name of the source CONNECTION (not the service name). E.g., a MySQL connection will be `mysql`, and a Tableau one, `tableau`.
3. To trigger a test connection, you'll need to:
    1. Create a workflow with POST/PUT `/v1/automations/workflow/` passing the payload of [createWorkflow](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/api/automations/createWorkflow.json).
    2. This create workflow `request` will be the current `TestServiceConnectionRequest`.
    3. This will return you a [Workflow](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/automations/workflow.json). In the `response`, the Ingestion Framework will keep sending the updated test connection results.
    4. Now, you won't get all the data in a batch. You'll need to keep polling by Workflow ID until the workflow status is either `Successful` or `Pending`.
    5. When the workflow is finished, you are good to stop.

**Comment by pmbrull** [comment]
Marking this as blocked, we have some pending work on the ingestion side cc @ulixius9

**Comment by pmbrull** [comment]
We should be good to go. To the `/v1/automations/workflow/` endpoint you can send a payload like:

```json
{
  "name": "test-connection-mysql",
  "description": "description",
  "workflowType": "TEST_CONNECTION",
  "request": {
    "connection": {
      "config": {
        "type": "Mysql",
        "scheme": "mysql+pymysql",
        "username": "openmetadata_user",
        "password": "**********",
        "hostPort": "localhost:3306"
      }
    },
    "serviceType": "Database",
    "connectionType": "Mysql",
    "serviceName": null,
    "secretsManagerProvider": "noop"
  }
}
```

Then, keep fetching the workflow by name until you got it finished
