### ISSUE TITLE
Mask PII sample data and don't return column metrics

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10542]
If a column is flagged as `PII.Sensitive` and the user does not have permissions, we should not show the sample data for that column (maybe show ***) and we should not return the column metrics as well.

Otherwise, a sensitive column could be semi-inferred just by seeing the min/max values, for example.

cc @harshach @TeddyCr

**Comment by nahuelverdugo** [comment]
Created this ticket https://github.com/open-metadata/OpenMetadata/issues/10830 to separate masking sample data of the rest of things we can hide of a given column.
