### ISSUE TITLE
Entity metadata versioning does not follow major.minor standard

### ISSUE THREAD

**Issue by osocron** [open-metadata/OpenMetadata#10545]
**Affected module**
UI, backend

**Describe the bug**
According to the [documentation](https://docs.open-metadata.org/connectors/ingestion/versioning), metadata versioning increases the minor version for backward **compatible** changes and major versions are used for backward **incompatible** changes. However, when adding column descriptions to an entity, if the minor version reaches 9, instead of going to 10 it instead bumps to the next major version even though the changes are backwards compatible.

<img width="306" alt="versioning" src="https://user-images.githubusercontent.com/6936336/224656705-92cf79ae-2318-40d1-9823-e7f5d1694046.png">

**To Reproduce**

Use the patch endpoint for adding column descriptions at least 10 times.

```
url = f"{om_host}/v1/tables/{table_entity_id}"
payload = [
                {
                    "op": "add", "path": f"/columns/{column_index}/description",
                    "value": column_description
                }
            ]
response = req.patch(url, headers=headers, json=payload)
```

<img width="306" alt="version2" src="https://user-images.githubusercontent.com/6936336/224658063-20e7c94c-7e41-4b21-8b98-b885dee429c8.png">

**Expected behavior**
No major version bump should happen when adding column descriptions as this is not a backward incompatible change.

**Version:**
 - OS: Linux
 - Python version: 3.10
 - OpenMetadata version: 13.2
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[redshift]==0.13.2.4`

**Additional context**

**Comment by sureshms** [comment]
@osocron, the documentation states this:
`Backward incompatible changes result in a Major version change. For example, when a column in a table is deleted, the version increases by 1.0 (e.g., from 0.2 to 1.2).`

So the entire version is increased by 1.0. In case of minor changes, the version number increases by 0.1. Perhaps we can explain this in the documentation better.
