### ISSUE TITLE
Ingested Materalized View Also 

### ISSUE THREAD

**Issue by SaadAmien20** [open-metadata/OpenMetadata#10550]
To enrich data governance and to track most thing in our data system.
I think to add view and Materialized View , it will be great

**Comment by harshach** [comment]
@OnkarVO7 can we double check if we are not ingesting materialized views?

**Comment by pmbrull** [comment]
@SaadAmien20 on which connector is this happening? We should be picking things up by default

**Comment by OnkarVO7** [comment]
This has been handled with below PR
https://github.com/open-metadata/OpenMetadata/pull/11005
