### ISSUE TITLE
Different samples for different purposes

### ISSUE THREAD

**Issue by ayeremeeva** [open-metadata/OpenMetadata#10556]
**Is your feature request related to a problem? Please describe.**
Having the same settings for samples and profiling as for number of rows (or percentage) we cannot provide the whole profiling without demonstrating the full table/schema as samples. We don't need to see a table with 1 mln rows (100 rows would be enough) but profiling should be done for the whole table. Or sometimes we don't need profiling at all but samples are important

**Describe the solution you'd like**
We'd like to have different sample %/rows' number for sample demonstrated and profiling

Here is the slack link: ttps://openmetadata.slack.com/archives/C02DZK3QH8Q/p1678205790829219

**Comment by harshach** [comment]
@ayeremeeva sampling is for profile only. For sample data we consider all of the profile sample % but only capture 100 rows. Just because you mentioned 100% and there are 1M rows we won't ingest all of that data into OpenMetadata as sample.
