### ISSUE TITLE
OpenMetadata Server: Fetch Environment Variables from Secret Store for Server Configurations

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#10566]
**Is your feature request related to a problem? Please describe.**
Ability for OpenMetadata Server to fetch secrets at runtime for Server Configurations rather than hardcoding them as environment variable or local files.

**Comment by pmbrull** [comment]
the server should be agnostic on where the secrets live. We'll keep picking up env vars as we are doing
