### ISSUE TITLE
Tableau Online - Individual Tab Hyperlinks Do Not Work

### ISSUE THREAD

**Issue by zyst1988** [open-metadata/OpenMetadata#10572]
**Affected module**
Tableau Dashboard Metadata 

**Describe the bug**
Hyperlinks to individual tabs appear to be missing 'Site Name' and don't work.

**To Reproduce**

Ingest Tableau Online / Cloud Metadata and try using the hyperlink to any sheet

![image](https://user-images.githubusercontent.com/86759835/224954625-6737ccc7-ccd9-4cf8-8814-9019821614f9.png)

![image](https://user-images.githubusercontent.com/86759835/225067771-80ce76dc-68af-4f10-95e1-e0b238e58187.png)

**Expected behavior**
Hyperlink should work

**Version:**
Latest Docker Image (as at 20230314)

**Additional context**
Please can this be fixed?

**Comment by pmbrull** [comment]
fixed by https://github.com/open-metadata/OpenMetadata/pull/10605
