### ISSUE TITLE
Storage Service Manifest handling

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10587]
Instead of having a manifest in each bucket, we can make it easier for some users by handling the manifest in the same way that we handle them in dbt.

Let's update the S3 connection ([link](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/objectstore/s3ObjectStoreConnection.json)) to add a `manifestPath` in the same fashion that we support dbt manifest & catalog (local, s3, gcs, HTTP). We can make assumptions on the name and location of the file.

We can also have a separate property to Ingest All Buckets.

The manifest should be versioned (a la dbt) and defined in the JSON Schema

**Comment by cristiancalugaru** [comment]
I can pick this up.
