### ISSUE TITLE
Add test option is only available with the user having Admin role.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10609]
**Affected module**
UI

**Describe the bug**
Add test option is only available with the user having Admin role.
We tried different combination of rights to test if adding test is allowed against those rights.

1. Having 'All' operation rights
2. Having Create , Delete, Edit All and View All rights
3. Having Create, Delete, Specific Edits , View All rights
4. Having specific Edits and View All rights

For all 4 cases the add test option at table level remain restricted.

Screenshot

![image](https://user-images.githubusercontent.com/110607559/225419160-b7e39e7b-c7cc-408a-a16f-ec355e76bc54.png)
![image](https://user-images.githubusercontent.com/110607559/225419222-aabe6538-b79a-4718-ba0a-5f82b7d706df.png)
![image](https://user-images.githubusercontent.com/110607559/225419313-b0abe344-cc6f-4a89-bbac-5aec9124f1b7.png)
![image](https://user-images.githubusercontent.com/110607559/225419373-ecc0941c-9b0f-457b-a1ef-ea90dd1c3cf8.png)
![image](https://user-images.githubusercontent.com/110607559/225420192-8aabd37b-82d1-4147-ae90-2bc87396f8bb.png)

Adding test rights should to be allowed based on roles other than Admin role.

**Version:**
 13.2

**Comment by harshach** [comment]
There is EditTests/ViewTests option in policies. You can restrict or allow based on those operations
