### ISSUE TITLE
[java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size

### ISSUE THREAD

**Issue by SandipDogra** [open-metadata/OpenMetadata#10629]
**Affected module**
User creation

**Describe the bug**
An exception with message [java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size [statement:“/* UserDAO.listAfter */ SELECT ue.json FROM user_entity ue LEFT JOIN entity_relationship er on ue.id = er.toId LEFT JOIN team_entity te on te.id = er.fromId and er.relation = :relation WHERE ue.deleted = FALSE AND (JSON_EXTRACT(ue.json, ‘$.isBot’) IS NULL OR JSON_EXTRACT(ue.json, ‘$.isBot’) = FALSE ) AND (:team IS NULL OR te.name = :team) AND ue.name > :after GROUP BY ue.name, ue.json ORDER BY ue.name LIMIT :limit”, arguments:{positional:{4:null,5:16,6:,7:10}, named:{limit:16,team:null,after:,relation:10}, finder:[]}]] was thrown while processing request.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
follow the docs here https://docs.open-metadata.org/v1.1.0/deployment/upgrade#update-sortbuffersize-mysql-or-workmem-postgres
