### ISSUE TITLE
Pluggable Email Template Styling

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#10638]
**Is your feature request related to a problem? Please describe.**
Currently, the problem is that we cannot have a different implementation depending on the use case for OSS and Collate, need to have a generic interface and concrete implementation in OSS and Collate.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Siddhanttimeline** [comment]
Completed here: https://github.com/open-metadata/OpenMetadata/pull/17015
