### ISSUE TITLE
Data discrepancy in profiler

### ISSUE THREAD

**Issue by itaise** [open-metadata/OpenMetadata#10633]
**Affected module**
UI

**Describe the bug**
We are using table profiler, with a sample of 5%. 
In the Profiler we saw that for many tables, the values count for a **column** is larger than the row count of the **table**, this does not make sense..
here is a slack discussion about it, where @TeddyCr suggested to open an issue: 
https://openmetadata.slack.com/archives/C02B6955S4S/p1678977269442909

Can you please check? thanks a lot!

**To Reproduce**
Screenshot in the slack thread

**Expected behavior**
The row count should be larger or equal to the column value count

**Version:**
 - OpenMetadata version: 0.13.2

**Comment by itaise** [comment]
https://files.slack.com/files-tmb/T02BVTLN3G8-F04TVJG0EQ7-f9bd3b5bc2/image_720.png

**Comment by TeddyCr** [comment]
Currently, the sampling size is computed for each categories of metrics therefore it might show this small variation. We hold the same sample in memory to process all the categories of metrics.

**Comment by TeddyCr** [comment]
@itaise we started a discussion https://github.com/open-metadata/OpenMetadata/discussions/11864 regarding this ticket to get feedback from the community on the most acceptable approach. We'll put this one on hold until we come to a resolution. If you have any comments to add on the discussion we would love to hear it. 🙂
