### ISSUE TITLE
Glossary Import & Export validation

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10644]
We have encountered the following scenario:

1. We have a glossary X with some terms & nested terms
1. We export from X
1. We create a glossary Y
1. Then, import the values from X into Y -> The validation is flagged as :white_check_mark: , but when the terms are imported, the nested ones do not appear.

I believe that this is due to the FQN or something internally still pointing to the glossary X. The questions are:

- If this is intended, then the validation at the import should fail. The preview does not match reality
- If it is not intended, then it needs a fix

**Comment by harshach** [comment]
solving as part of fqnHash
