### ISSUE TITLE
Typo in Kubernetes Deployment documentation

### ISSUE THREAD

**Issue by aprabhat** [open-metadata/OpenMetadata#10652]
"I have noticed a typo in the heading of this https://docs.open-metadata.org/deployment/kubernetes#1-create-a-dockerfile-based-on-openmetadataingestion.

The heading should be 
"**Create a Dockerfile based on openmetadata/ingestion**" 

instead of

"**Create aDockerfilebased onopenmetadata/ingestion**".

![image](https://user-images.githubusercontent.com/5886356/226112802-0ed459b9-9dd8-47b9-92e8-c88315b0b47d.png)

**Comment by MihirR123** [comment]
<img width="523" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/136401045/7cea19c2-492d-4f8e-b3e9-5eb46946565b">
The documentation has a space, but there is a problem with the rendering. @harshach I need help with fixing this in docs rendering. Can you please assign this to someone else.

**Comment by harshach** [comment]
hey @aniketkatkar97 can you take a look
