### ISSUE TITLE
Snowflake schemas do not show under a team's assets

### ISSUE THREAD

**Issue by Alina-Valea-Forter** [open-metadata/OpenMetadata#10670]
I am running OpenMetadata version 0.13.0. I am trying to assign a Snowflake schema to a team. I have navigated to the schema itself and have assigned the owner there, however, when I navigate back to the Teams view Openmetadata still shows 0 assets. 
<img width="744" alt="snowflake_schema_owners" src="https://user-images.githubusercontent.com/110388428/226338499-2f8cdf2f-5d30-4e0c-8c3c-397faf68dec6.png">
<img width="466" alt="team_asset_view" src="https://user-images.githubusercontent.com/110388428/226338519-1b68f1a7-0f03-4911-802d-0ee48dd1f484.png">

**Comment by harshach** [comment]
Thanks @Alina-Valea-Forter for reporting the issue.
@chirag-madlani @shahsank3t we do have the data coming back from the backend, but we are not showing the entity
<img width="2207" alt="image" src="https://user-images.githubusercontent.com/38649/226454398-a00af7e2-93c1-4f70-836e-360ec69499df.png">

**Comment by Sachin-chaurasiya** [comment]
@harshach, the `owns` field returns entity references, however in the assets tab we want to show assets as we have on explore page, and for that, we need more information, so we are using the search API to get the assets owned by the team.

In search API, we only have an index for top-level entities like `table`, `topic`, etc, that's why the schemas owned by team a are not listed there.

**Comment by chirag-madlani** [comment]
@CheyenneRobinson Yes it will be resolved for all the services once we fixed it

**Comment by harshach** [comment]
@07Himank lets add support for database , databaseSchema as separate docs and that will allow us to list it in Assets tab

**Comment by harshach** [comment]
@07Himank we should create an alias for searching across all the entities. So that we can show it as part of the assets with one call to the backend search apis

**Comment by harshach** [comment]
@chirag-madlani we need to show assets on Team page similar to Glossary 
<img width="994" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/9eadfab4-5424-4f94-b6c5-aea53e72ee06">

**Comment by harshach** [comment]
@07Himank lets follow-up on this and close it out

**Comment by chirag-madlani** [comment]
cc: @Ashish8689 @ShaileshParmar11 can you confirm this?

**Comment by harshach** [comment]
@07Himank @Ashish8689 @ShaileshParmar11 can someone confirm and close it out
We need to show services/databases/databaseSchemas as well

**Comment by Ashish8689** [comment]
@harshach yes, I have raised the [PR](https://github.com/open-metadata/OpenMetadata/pull/13372) for that, will close it once got merged!

**Comment by harshach** [comment]
@Ashish8689 I still see this in the user profile in sandbox-beta
![Uploading image.png…]()

**Comment by Ashish8689** [comment]
@harshach the images is broken, can you re-share what you are pointing out!

**Comment by harshach** [comment]
@Ashish8689 @chirag-madlani this needs to be fixed, lets add Assets tab similar to glossary term 
<img width="1921" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/d87bc220-bfd2-47d0-94db-0c85237c718e">
and ability to bulk add asses to the team page

**Comment by harshach** [comment]
same thing should be available at Users level as well

**Comment by chirag-madlani** [comment]
> [@Harsha](https://collate-inc.slack.com/team/URD58MSM9) Needed API support for the following:
> 
> Teams : Bulk add and remove asset for `Entities` for Team, currently in Team we only support bulk add for `User` . Users : Same bulk add and remove asset for adding user as `owner and following` for the entities.

@Ashish8689 Let's have readonly for assets until we do not have above APIs

**Comment by Ashish8689** [comment]
Closing this as we have already covered this case in Automation.
