### ISSUE TITLE
[Ingestion] Power BI Datasets and SSAS / AAS 

### ISSUE THREAD

**Issue by Daandamhuis** [open-metadata/OpenMetadata#10689]
**Describe the solution you'd like**
Since I'm working a lot with the Microsoft Stack, integrating the Power BI dataset metadata would be helpful. In terms of the metadata, this would be relatable to Looker and Tableau. There are two options, at least that's what I think. 
1. Use the Power BI Admin Scanner API to read out the datasets.
2. Use **PyTabular** with Microsoft's dlls to read out the Tabular Object Model (TOM). 

The attributes that can be retrieved are plenty, but this is a High-Level Overview;
- Measures (Expressions, Names, Descriptions, DataTypes and Translations)
- Columns  (Expressions, Dataset Column Name, Source Column Name, Descriptions, DataTypes and Translations)
- Tables (Partitions, Names, Descriptions and Translations)
- Relationships within the dataset. (From Column & Table  -> To Column and Table)

**Downsides**
Option 1 is that it can only work for Power BI Dasets (afaik) 
Option 2 is that the package only runs in Windows environments (afaik). [PyTabular Issue](https://github.com/Curts0/PyTabular/issues/36)

**Upside**
- Option two would also make it possible to read out the metadata from SQL / Azure Server Analysis Services.
- And it would also be able to excecute DAX queries to the dataset which could be used for profiling.

**Example based on Adventure Works**
I've implemented PyTabular with Docusaurus for my personal [website](https://www.daandamhuis.nl/docs/adventure-works), so you can see what can be extracted. 

**Additional context**
Measure Example
![image](https://user-images.githubusercontent.com/3600611/226601101-79ec53e7-69f4-47e1-9337-d9d5fb28dfc2.png)

Table Example
![image](https://user-images.githubusercontent.com/3600611/226601152-8d4320c2-d961-4058-8040-9bcff4cf7378.png)

Column Example
![image](https://user-images.githubusercontent.com/3600611/226601238-5db0f089-4d86-49b0-b41b-ac0024528217.png)

**Comment by Daandamhuis** [comment]
Updated the base request

**Comment by Daandamhuis** [comment]
Yes, correct 👍

**Comment by pmbrull** [comment]
Thanks, since this has some more details, I'll close the other and mark as duplicate
