### ISSUE TITLE
Biq Query role for bigquery.jobs.listAll  has changed

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10690]
**Is some content missing, wrong or not clear?**
Hi, bigquery.jobs.listAll is no longer part of BigQuery Job User, but as part of roles/bigquery.resourceViewer.

**Describe the solution you'd like**
Update documentation on docs.open-metadata.org/connectors/database/bigquery#requirements

**Additional context**

**Comment by ulixius9** [comment]
done by #10692
