### ISSUE TITLE
Fix API tags for ModelResource

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1069]
ModelResource has two methods that have `tags = "model"` instead of `tags = "models"`. This causes our API documentation to have two sections - one for model and another one for models, as show below:

![image](https://user-images.githubusercontent.com/1417689/140533534-f47542a0-0ab3-4bf4-9a1b-ebef11d0979d.png)

**Comment by pmbrull** [comment]
Yep sorry @sureshms, noticed that a while ago and still need to jump into it. I had reported it here: https://github.com/open-metadata/OpenMetadata/issues/871

**Comment by pmbrull** [comment]
Fixing this as a part of https://github.com/open-metadata/OpenMetadata/issues/801

**Comment by pmbrull** [comment]
closed with https://github.com/open-metadata/OpenMetadata/pull/1071
