### ISSUE TITLE
Alert when entity version change

### ISSUE THREAD

**Issue by zuzuviewer** [open-metadata/OpenMetadata#10701]
**Is your feature request related to a problem? Please describe.**
I want to get notification when version change, e.x table entity

**Describe the solution you'd like**
notification when version change

**Describe alternatives you've considered**

**Additional context**

**Comment by sureshms** [comment]
This is nothing but `EntityUpdated` event for an entity as shown below (choose instead of `All` the entity you are interested in):
<img width="906" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/f6a76ee4-29ec-4fb7-aa10-9a6a9187da6d">
