### ISSUE TITLE
Team page does not paginate API request

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10702]
**Affected module**
[UI]

**Describe the bug**
When navigating to the teams page of the UI, the request to fetch the team is not paginated properly (i.e. `limit=100000`) which in certain scenario will cause the request to timeout.

**To Reproduce**
Create a large number of teams and navigate to the teams page

Screenshots or steps to reproduce
Here is a sample request

`http://localhost:8585/api/v1/teams?fields=defaultRoles%2CuserCount%2CchildrenCount%2Cowns%2Cparents&limit=100000&parentTeam=Organization&include=all`

**Expected behavior**
Similar to how roles, users, policies and admins have a pagination set to 15, teams page should have a similar behavior.

**Version:**
 - OpenMetadata version: 0.13.2

**Additional context**
Slack thread 👉 https://openmetadata.slack.com/archives/C02B6955S4S/p1679470435365239

**Comment by chirag-madlani** [comment]
We have separated heavy fields from the list API and made a separate API call for the same.
While fetching additional details we have added a loader to specific for those details in this [chore(ui): teams page improvements](https://github.com/open-metadata/OpenMetadata/pull/12603#top)
