### ISSUE TITLE
Create URLs for all Data Assets

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#10713]
**Is your feature request related to a problem? Please describe.**
Today, I'm unable to share a link to the "Asset" page of a Glossary term. I can only share with another user a link to a glossary page and give him the hint to navigate to the Asset section, which is a bit hard to find.

**Describe the solution you'd like**
Provide a dedicated URL for "Assets", similar how we have it for "Sample Data", "Custom Properties" etc. on Table asset page.

![image](https://user-images.githubusercontent.com/102999683/227025585-ec257f1a-e45f-4f7c-b0fd-9d20cdcdae3b.png)

**Comment by chirag-madlani** [comment]
@karanh37 Let's have deep links for internal tabs

**Comment by trillhaa** [comment]
That's great!
