### ISSUE TITLE
Data Glossary Tags: order Tag suggestions by Level and Alphabet

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10724]
**Is your feature request related to a problem? Please describe.**
**Example**. I have a Data Glossary Term Earth. It has 7 Children (continents) and each of them have Country children.
Use cases:
1. I only want to tag continent Europe to a table. I type in Europe. I get the list of 45 suggestions. As Europe is part of FQN name for Continent and Countries. And it doesn't seem that is ordered in any specific order.

 This is a real case example, where I need to tag a parent term, but suggestion lists all the children, and children of children. And I have maybe 50 of them.  What's worse - I only see the beginning of FQN, but I think there is a bug for that already.

![image](https://user-images.githubusercontent.com/26750060/227191921-0d0f5733-f631-42d1-b92d-61ddaa181a02.png)

**Describe the solution you'd like**
If I type Europe in the Tag, I first get parent terms that contain Europe. And only then Children Terms.  

**Describe alternatives you've considered**
I tried typing in Geo.Continent.Europe but it didn't work. 

**Additional context**

**Comment by sureshms** [comment]
@harshach and @chirag-madlani, we should have tag suggestions that include the hierarchy as we do in the `Add User` page as shown below:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1417689/227220945-dbcc103b-c3c4-4b53-8918-46e41d6e652f.png">

**Comment by DovileKr** [comment]
Yes. the tree hierarchy - would make the discovery of tags so much easier!

**Comment by DovileKr** [comment]
hello, do we have any plans for this enhancement?

**Comment by pmbrull** [comment]
> hello, do we have any plans for this enhancement?

We'll handle for 1.4

**Comment by chirag-madlani** [comment]
Hi @pmbrull @DovileKr 

Can you confirm if current design for Tag Selection will be good here? I will add Alphabet sorting to this.
My view for not going to hiearachy approach is:
1. It will add indentation which will consume some space and we are already at crunch of space there
2. To avoid long fqn as a line, We separate actual term and FQN with two different lines
3. Search results will be more clear instead it will be hard in case of hierarchy view (May have horizontal scroll in case of n level of nesting)

_**Hierarchy view fits better if we have full width to use**_

cc: @sureshms @harshach 

<img width="694" alt="Screenshot 2024-04-03 at 6 55 19 PM" src="https://github.com/open-metadata/OpenMetadata/assets/12962843/8f26e003-d3d4-46a5-b936-6dd7ff84412e">

**Comment by harshach** [comment]
@chirag-madlani we don't need to expand by default right? only when the user searches for it the term needs to be expanded. 
The goal here is to make it easy for users to understand the hierarchy and making sure the term is selected from the right glossary.
