### ISSUE TITLE
Page browsing improvements

### ISSUE THREAD

**Issue by JonathanBonnaud** [open-metadata/OpenMetadata#10726]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to browse my tables or ingestion pipelines with more than one page and I need to click `next` repeatedly.

**Describe the solution you'd like**
1. Add `first` and `last` buttons to be able to go to first or last page. 
2. Add option to change the number of results displayed on one page.
3. Allow to click on the page "tracker" (`1/4`) to be able to edit the current page number to jump to it

**Describe alternatives you've considered**
Described above

**Additional context**
-

**Comment by harshach** [comment]
@chirag-madlani we should use UX similar to this 

![Image](https://user-images.githubusercontent.com/38649/227336073-b3b1afab-7d50-490d-8c34-4998fe1592d3.png)

where we can allow users to enter custom page by clicking ...

**Comment by chirag-madlani** [comment]
@harshach I will check on this

**Comment by chirag-madlani** [comment]
@harshach Do we also want to support variable PAGE_SIZE here? Something like below or just page numbers will be fine?
<img width="856" alt="Screenshot 2023-03-24 at 11 51 02 AM" src="https://user-images.githubusercontent.com/12962843/227441380-6171a564-996c-45e3-a737-6900d4329fc6.png">


https://4x.ant.design/components/pagination/

**Comment by harshach** [comment]
variable paze size sounds good to me

**Comment by chirag-madlani** [comment]
Will add Pagination on Explore page

**Comment by JonathanBonnaud** [comment]
Hi @chirag-madlani, thanks for resolving this last month, but I thought the change would be applied to all pages in the UI, unfortunately I can only see this in the `Explore` page. It would still be good to have the same to move between pages in the Schema page of a Database Service, or in the Ingestion Pipelines page.

**Comment by chirag-madlani** [comment]
Re-opening for cases where pagination is missing

**Comment by ShaileshParmar11** [comment]
We can only add number-based pagination in the ES-based pages but if we wanted to support number-based pagination everywhere we need backend support cc @harshach  @chirag-madlani
