### ISSUE TITLE
Prepare REST Client for Metabase

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#10721]
**Affected module**
Ingestion Framework

**Describe the bug**
Currently the API of metabase are called within the `metadata.py` ([ex](https://github.com/open-metadata/OpenMetadata/blob/c9feba826f98a2e4d5e21b5457b521f9f0854068/ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py#L283)) we should create a separate `client.py`  file and define all the REST calls over there.

**Comment by pmbrull** [comment]
Let's follow the same approach we have in other connectors, for example Tableau or Nifi, where we are defining a separate client, a file with pydantic models, and we validate the data early before processing
