### ISSUE TITLE
[Feature Request] New JSON Patch Endpoint and Display Path field for sources

### ISSUE THREAD

**Issue by tjpegram** [open-metadata/OpenMetadata#10731]
In some situations especially related to Oracle databases (and possibly others), the architechture may be such that there is a single top level database, which is divided up into schemas. In some situations this top level database may not have been renamed when created and will come across to openmetadata as "default". This makes all paths for tables, views, and other data for that database service take on the path (from the database FQN) databaseService.default.resource. 

When using the JSON patch API to add the displayName field to the database entity, the name shown in the UI can be easily updated. However this displayed name does not propagate down the tree, and so when a user then views a table under the database, the path shown is relative to the FQN and does not include the new displayed name. 

The request here being an API that allows for updating all tables entities under a database, etc to take on this new "displayPath" so that the naming is homogenous across all data related to the database service. 

More information found in the slack thread related to this discussion. https://openmetadata.slack.com/archives/C02B6955S4S/p1679408558419819

**Comment by chirag-madlani** [comment]
@harshach @sureshms As per the discussion we will need `fullyQualifiedDisplayName ` from the backend to show `displayName` in the breadcrumbs

**Comment by sureshms** [comment]
@chirag-madlani, let's not mark this as a blocker for release 1.0. We will get to it if possible in 1.0. Otherwise, move it out.

**Comment by harshach** [comment]
@sureshms when we call out blocker, its not a blocker for the release but the blocker on someone from backend to ship it before the UI can work on it.

**Comment by tjpegram** [comment]
@chirag-madlani Just so I can update folks on my end. Is this completed and included in 1.0?

**Comment by harshach** [comment]
@tjpegram not yet, especially for breadcrumbs to show the DisplayName. We are adding at each entity level whats the display name going to be

**Comment by chirag-madlani** [comment]
@harshach we have fixed this for Explore page cards will fix it for details pages in 1.1
