### ISSUE TITLE
Add Warnings (on top of Success / Failed) for DQ

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#10739]
**Is your feature request related to a problem? Please describe.**
tableCustomSQLQuery parameters.

Currently the test will fail if the query result return more than 0 rows. 
This is ok in most cases, however sometimes, especially for already known issues every fail would be quite noisy and not productive and might mask more important issues.

**A use case example**:
I am tracking master data inconsistencies between two datasets. The query is a simple left anti join. It returns a large number of mismatches, but it is a known issue and is being addressed. So while I don't want  to be notified about it on every run, we still want to track it.

On the same table I have other checks where I don't expect any errors, and I would like to be notified on those fails. 

So if I chose to notify table owners and table followers and use webhooks - this issue will be always trigger notification. And then people might pay less attention or even "mute" it.

**Describe the solution you'd like**
Couple of ideas:
1. For tableCustomSQLQuery be able to set a parameter, so Fail Status if query result return more rows than Parameter.
2. For tableCustomSQLQuery be able to set not only Failed and Success for tests, but also Amber. Then one could set different alerts: Amber - notify A, Fail - notify B. 

**Describe alternatives you've considered**
Assigning the rule to a dummy owner and excluding them from notifications by 
![image](https://user-images.githubusercontent.com/26750060/227336400-67171cb6-2282-428c-8f5c-6e41ba866606.png)

**Additional context**

**Comment by TeddyCr** [comment]
Thank you @DovileKr for open this issue. Would you be able to give more details around what you mean by "Amber"?

**Comment by DovileKr** [comment]
@TeddyCr sure.

For example
**Transactional Data:**
I am validating a sales data ingestion pipeline. I expect 100k a day, but sales fluctuate and I set 
1. a range 90k to 110k a day  for **Green = Pass/Success**
2. a range 50k to 150k a day for **Yellow = Warning**, most likely correct, but worth checking. So I might just inform owner and data providers to check, just in case.
3. anything outside this range, meaning below 50k and above 150k **Red = Sure Fail.** I would be notifying people who provide data and who use data., Owners and Followers.

Master Data
I am validating a customer master ingestion pipeline. I expect X number of records (based on a reference data sets). Ideally, I would get a 100% match, but missing a few customer records is considered to be ok. So I set
1. 100% match **Green = Pass/Success**
2. 95% **Yellow = Warning**. This is our bad master data acceptance level.  Missing a few hundred customer records not great, but we wouldn't act on it and would just hope that it would fix itself of the next load. I just inform owner and data providers to keep this in mind and check tomorrow. For dataset followers - they would see the warning on the dataset, but they wouldn't get an email , or notification.
3. anything below 95% match would be  **Red = Sure Fail.** I would be notifying people who provide data and who use data and Owners and Followers. Basically everyone, as it is a critical error.

I had a "pleasure" monitoring Data Quality rules and there is a grey zone between Green and Red, or I should say - Yellow :).  And you don't notify or want to be notified or  minor issues, even if they are an issues. 
And depending on the number of daily issues - different actions are taken. But you still want to take note of them.

- green = use data set with no concern
- yellow = data is ok to use, but do not expect perfect results, so be careful
- red = data is not ok and should not be used until fixed

It is also important for tracking DQ KPIs. How many days minor issues and how many  - major issues. 


let me know if this helps.

**Comment by TeddyCr** [comment]
Make sense. Thank you for the details. 🙂
