### ISSUE TITLE
Profiler option to scan only tables or only views

### ISSUE THREAD

**Issue by JonathanBonnaud** [open-metadata/OpenMetadata#10747]
**Is your feature request related to a problem? Please describe.**
When creating a profiler ingestion pipeline, I cannot set an option to only scan tables or views

**Describe the solution you'd like**
It would be nice to have a toggle button `only_views` and one `only_tables` or something similar.

**Describe alternatives you've considered**
-

**Additional context**
CC: @chirag-madlani for context

**Comment by TeddyCr** [comment]
@JonathanBonnaud we have an issue open for this already https://github.com/open-metadata/OpenMetadata/issues/8429. You can follow the progression there. 🙂
