### ISSUE TITLE
Parent Owner for Database is cascading to all schemas and tables, even those assets have separately been assigned ownership.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10744]
**Affected module**
UI

**Describe the bug**
Parent Owner for Database is cascading to schemas and tables.

Steps:
1. We initially marked owners against all the schemas.
2. Later we marked the Owner for our DB (which has those schemas)
3. Upon marking owner at DB level, the parent owner cascaded to all  schemas and all tables.

Screenshots 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/110607559/227430630-c627679a-34f7-4692-8b52-2c17ef568c1e.png">

**Expected behavior**
It should be propagated only to those schemas or tables that don't already have an ownership.

**Version:**
OM 13.2

**Comment by sureshms** [comment]
@lailapatel, this issue has already been fixed. Reopen if you can reproduce the issue in 1.x release.
