### ISSUE TITLE
Filter by ingestion pipeline type

### ISSUE THREAD

**Issue by JonathanBonnaud** [open-metadata/OpenMetadata#10750]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I am on the ingestion pipelines page and I see all the pipeline types, but I would like to see only profiler pipelines.

**Describe the solution you'd like**
A filter to select the ingestion pipelines to display. It could be multi select as I could want to see only lineage and profiler, but not metadata.

**Describe alternatives you've considered**
-

**Additional context**
I tried using the search bar on top of the ingestion pipelines list, but it doesn't allow me to display all the pipelines matching the search and clicking on next page removes the search.

[screen-capture-openmetadata-issue-search.webm](https://user-images.githubusercontent.com/23031977/227525652-bc0374f0-9ab1-402a-9c96-681d70f70e73.webm)

**Comment by harshach** [comment]
Services are currently displayed in card-type UI, we should show the listing in a table format, and each service section should also have a list of pipelines across multiple services in that section. For example, Database Services must have two tabs, one to list the services and another to list the pipelines. In pipelines tabs, users should have the ability to select the pipelines based on the type of those pipelines.

**Comment by chirag-madlani** [comment]
- [ ] Support toggle between card view and table view for service page
