### ISSUE TITLE
Add Google Data Studio / Looker Studio support

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1075]
Add connector for Data Studio and ingest dashboard metadata from it

**Comment by sisir-umich** [comment]
Hi, this is Sisir and Yong (@show981111). Can we have this issue assigned to us? Thanks!

**Comment by show981111** [comment]
Hello, this is Yong. It would be great if Sisir and I can work on this together.

**Comment by ayush-shah** [comment]
Assigned you guys.
Do let us know if you get blocked.
Happy Coding!!

**Comment by sisir-umich** [comment]
Thank you!

**Comment by pmbrull** [comment]
hi @show981111 @sisir-umich , any updates on this? Let us know if you have any questions. Thanks

**Comment by sisir-umich** [comment]
Hi @pmbrull , we actually selected a different open source project for our assignment - apologies for not unassigning myself sooner

**Comment by harshach** [comment]
@pmbrull lets address this for 1.3

**Comment by SumanMaharana** [comment]
Ill be working on the issue

**Comment by Bmpsilva** [comment]
Hello, Is there any news about this topic?

**Comment by claudiazi** [comment]
Hello! Im also wondering when we will have this connector live? many thanks!
