### ISSUE TITLE
Broken link to tableau url on lineage screen

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#10751]
On press Tableau URL on the lineage screen page reloads instead of loading Tableau page
https://openmetadata.slack.com/archives/C02B6955S4S/p1679647365110299

OM 0.13.1

**Comment by harshach** [comment]
@OnkarVO7 can you look into this

**Comment by OnkarVO7** [comment]
This has been fixed with the `1.0` release.
![ezgif-2-82028a5c5f](https://user-images.githubusercontent.com/28966081/234494683-7f65ceea-81c7-487c-b45d-1147568d836c.gif)
