### ISSUE TITLE
Flag not to ingest Tableau tags and owners 

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#10776]
**Is your feature request related to a problem? Please describe.**
Tags and owners are always ingested from Tableau. In some cases tags and owners are not necessary  

**Describe the solution you'd like**
A boolean flag in ingestion config not to ingest tags and owners. 

**Describe alternatives you've considered**
We regularly remove tags and owners via API

**Additional context**
None

**Comment by sureshms** [comment]
@gnomolio you don't want owners and tags from Tableau because they are not valid?

**Comment by ulixius9** [comment]
closing this ticket as already done with #10695
