### ISSUE TITLE
percentage of table description is not getting updated in insights

### ISSUE THREAD

**Issue by KMoove** [open-metadata/OpenMetadata#10773]
**Affected module**
UI

**Describe the bug**
percentage of table description is not getting updated in insights. 
we have updated the descriptions for a number of tables but upon running the metadata ingestion, the table descriptions do not get updated in the graph ( "Percentage of Data Assets with Description" ) under Insights tab. 

**To Reproduce**

Screenshots 
![IMG_3889](https://user-images.githubusercontent.com/129042584/227875406-6197a859-93d4-4dcd-9060-3830607d3694.jpg)
![IMG_3891](https://user-images.githubusercontent.com/129042584/227875456-938c41ee-de87-4de4-a83c-6dded3f6dc05.jpg)

**Expected behavior**
Table description percentage should be updated. 

**Version:**
OM 13.2

**Comment by TeddyCr** [comment]
@KMoove can you confirm that you have updated the 1) **table description** as well as 2) **columns description** https://docs.open-metadata.org/openmetadata/data-insight.

As mentioned in the documentation

> For Table asset type, this condition [description completed] is true only if the table and column description are filed. It allows you to quickly view the description coverage for your data assets in OpenMetadata.

**Comment by ShaileshParmar11** [comment]
@KMoove are you still facing the issue?

**Comment by KMoove** [comment]
no, the issue has been resolved and it can be closed.
Thanks a lot for your assistance.

**Comment by ShaileshParmar11** [comment]
You're Welcome!, closing the ticket as its resolved!
