### ISSUE TITLE
Add support for Teradata

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1077]
Add teradata connection and support metadata ingestion

**Comment by parthiv11** [comment]
@harshach Can i work on this.

Also provide me some guidance

**Comment by harshach** [comment]
@parthiv11 definitely, can you join our slack https://slack.open-metadata.org

**Comment by pmbrull** [comment]
hi @parthiv11 any updates here? let us know if you need any help

**Comment by TeddyCr** [comment]
fixed in https://github.com/open-metadata/OpenMetadata/pull/16373
