### ISSUE TITLE
Limiting workflow paths for cypress-integration

### ISSUE THREAD

**Issue by Anuj359** [open-metadata/OpenMetadata#10794]
**Is your feature request related to a problem? Please describe.**
To reduce the footprints of workflows in cypress by limiting it to the UI changes

**Describe the solution you'd like**
Updating the path to trigger workflows

**Describe alternatives you've considered**
Else, adding all the directories which we want to ignore.

**Comment by Sachin-chaurasiya** [comment]
Fixed with #10796
