### ISSUE TITLE
Object Store services metadata ingestion filters

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10801]
The ingestion pipeline JSON Schema has a `containerFilterPattern` we need to surface in the UI https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/metadataIngestion/objectstoreServiceMetadataPipeline.json

**Comment by Ashish8689** [comment]
Duplicate issue : https://github.com/open-metadata/OpenMetadata/issues/10828
