### ISSUE TITLE
UI Ingestion Polish improvements

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10805]
- [x] Connection options and connection arguments should appear in a hidden pannel "Advanced Configuration", not there by default. #11910 
- [x] The `scheme` should also be part of this Advanced Configuration #11910 
- [x] We need to have the same behavior in the Ingestion Pipelines
- [x] 1.2 (If there is any advanced config then we can handle it) Advanced Configuration should also be available when configuring a workflow so that we can hide some of the options
- [ ] 1.2 - table-like component to show the available features for each component, similar to what we show in the top of the docs. Let's align with @aniketkatkar97 to have the same component in both places, if possible
- [ ] 1.2 - If a connector does not have some workflows enabled (e.g., only supports metadata, but not profiler, etc.) We should still show up the option in the UI but disable it.
  - There we should have some short explanation, e.g., "The Profiler Workflow is not yet implemented for DynamoDB. You can find more information about this connector in the docs (link)".
---

In terms of pending documentation of the sources as markdown:

@harshach 
- [x] PinotDB
- [x] Airflow

@pmbrull 
- [x] Lineage / Usage Workflow
- [x] Custom database, dashboard, pipeline, messaging, mlmodel
- [x] Looker
- [x] Athena
- [x] Glue
- [x] Glue Pipeline
- [x] Deltalake
- [x] Vertica
- [x] S3 Object Store
- [x] Impala

@NiharDoshi99 
- [x] Domo Dashboard, Pipeline & Database
- [x] Druid
- [x] Amundsen
- [x] Atlas
- [x] SQLite

@ulixius9 
- [x] Metabase
- [x] Ingestion Workflow
- [x] Superset
- [x] Azure SQL
- [x] Snowflake
- [x] BigQuery
- [x] Salesforce

@TeddyCr 
- [x] Profiler Workflow
- [x] MlFlow
- [x] Nifi
- [x] Presto & Trino
- [x] Redshift
- [x] Hive
- [x] Singlestore, MariaDB & MySQL

@ayush-shah 

- [x] Quicksight -> https://github.com/open-metadata/OpenMetadata/pull/11179
- [x] Datalake -> #11175 
- [x] Clickhouse -> https://github.com/open-metadata/OpenMetadata/pull/11182
- [x] Dagster -> #11198 
- [x] Oracle -> #11193 
- [x] MSSQL -> #11196 

@OnkarVO7 

- [x] dbt workflow
- [x] Sagemaker
- [x] Mode
- [x] PowerBI
- [x] DB2
- [x] Dynamo
- [x] Kinesis
- [x] Fivetran

@nahuelverdugo 

- [x] Data Insight Workflow https://github.com/open-metadata/OpenMetadata/pull/11201
- [x] ES Reindex Workflow https://github.com/open-metadata/OpenMetadata/pull/11201
- [x] Kafka https://github.com/open-metadata/OpenMetadata/pull/11171
- [x] Redpanda https://github.com/open-metadata/OpenMetadata/pull/11171
- [x] Tableau https://github.com/open-metadata/OpenMetadata/pull/11165
- [x] Redash https://github.com/open-metadata/OpenMetadata/pull/11165

@MilanBariya 

- [x] Airbyte
- [x] Databricks
- [x] Databricks Pipeline

**Comment by pmbrull** [comment]
cc @chirag-madlani

**Comment by Sachin-chaurasiya** [comment]
- [ ] Screen flickers after selecting a field the first time we arrive at the connection details screen

https://user-images.githubusercontent.com/59080942/228779358-6ca20057-df4b-419d-ac98-457721ba1322.mov

**Comment by ulixius9** [comment]
- [ ] size changes on scroll for service configure page 

https://user-images.githubusercontent.com/39544459/228805432-06c0a0d0-f013-4aa9-8387-33f7f76cee46.mov

**Comment by pmbrull** [comment]
Based on our recent discussion, some updates on the documentation section of the connectors:
1. The UI should clearly show which connector is being created. We lose the information if we are creating a Redshift, Athena, BigQuery,... after the first step
2. Instead of having the Requirements as a second step, have a right side panel with all the necessary info when adding the Connection Details
3. We need to improve on the markdown styling
4. All the forms should follow the format of:
    - Small description
    - Example values
5. If we click to any field in the connection details, the doc should scroll automatically to that point

<img width="263" alt="image" src="https://user-images.githubusercontent.com/35870520/229419882-24c81d2f-ee86-4e92-95fd-ac0d8a83664c.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Add md files for workflows as well. @open-metadata/ingestion

**Comment by pmbrull** [comment]
cc @mohityadav766 we should improve the docs here https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/public/locales/en-US/OpenMetadata/EmailConfiguration.md
