### ISSUE TITLE
Add a flag to renew descriptions from data sources

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#10818]
**Is your feature request related to a problem? Please describe.**
There are many cases when data owners store and update table and column descriptions in data sources. Now Open Metadata won't renew descriptions, if any description in OM already exists. It makes to manually sync descriptions between data sources and Open Metadata manually. 

**Describe the solution you'd like**
Add a flag to ingestion configs to renew descriptions from the data source. It will let OM user to rule, what will be the source of the truth about descriptions: data source or Open Metadata itself.  

**Describe alternatives you've considered**
Manually compare descriptions between data source and OM and update obsolete descriptions (it's painfull)

**Additional context**
-

**Comment by pmbrull** [comment]
Hi @gnomolio, we've added the `Override Metadata` flag https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json#L99 for the ingestion process.

It'll update every piece coming from the source if specified in the metadata ingestion.

Thanks
