### ISSUE TITLE
ESLint issue, relating to the no-irregular-whitespace rule.

### ISSUE THREAD

**Issue by TeodorLungu** [open-metadata/OpenMetadata#10849]
**Affected module**
ESLint issue, relating to the no-irregular-whitespace rule.

**Describe the bug**
Discovered this when trying to open a PR from a branch to fix an unrelated issue. There seems to be an error in the way the pt-br.json file is created, specifically at line 1178:72, indicating an irregular whitespace.

**To Reproduce**
The error occurs after running the git commit -m "Issue-000" command, and can be seen in the following screenshot:

<img width="566" alt="Screenshot 2023-03-30 at 16 26 35" src="https://user-images.githubusercontent.com/64256672/228869652-743990ae-51cd-4335-be11-ea639dabb5c8.png">

This is easily fixable using an extension of VSCode, Fix Irregular Whitespace, as per this StackOverflow thread. 
https://stackoverflow.com/questions/34186283/eslint-fast-way-to-solve-irregular-whitespace-not-allowed

I am willing to fix this if I get assigned to it

**Expected behavior**
I would espect this issue to not appear, as this seems to prevent opening a PR, without first fixing the issue (not necessarily commiting it)

**Version:**
 - OS: MacOS
 - Python version: Python 3.10.6
 - OpenMetadata version: 1.0.0-alpha
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
@TeodorLungu assigning this issue to you. Thank you for reporting and helping in fixing this issue.

**Comment by TeddyCr** [comment]
Fixed in https://github.com/open-metadata/OpenMetadata/pull/10841
