### ISSUE TITLE
Create/Update Chart Not working as Expected

### ISSUE THREAD

**Issue by parthasarathy93** [open-metadata/OpenMetadata#10854]
Updating the chartUrl from the old one to different one , it is not updating 

The put request:
{"chartUrl":"/question/6379","description":"","name":"QTD Net Margin Points","displayName":"QTD Net Margin Points","service":{"id":"dce3fb52-0b1d-4925-bea3-5803c14dc672","type":"dashboardService"}}

Output of Put request:

{
  "id": "0207ff8c-b727-41d0-a785-524751e2f9d0",
  "name": "QTD Net Margin Points",
  "displayName": "QTD Net Margin Points",
  "fullyQualifiedName": "Metabase.QTD Net Margin Points",
  "description": "",
  "version": 0.1,
  "updatedAt": 1680085355821,
  "updatedBy": "ingestion-bot",
  "chartUrl": "/question/6379",
  "href": "http://openmetadata.agoda.local/api/v1/charts/0207ff8c-b727-41d0-a785-524751e2f9d0",
  "service": {
    "id": "dce3fb52-0b1d-4925-bea3-5803c14dc672",
    "type": "dashboardService",
    "name": "Metabase",
    "fullyQualifiedName": "Metabase",
    "description": "",
    "deleted": false,
    "href": "http://openmetadata.agoda.local/api/v1/services/dashboardServices/dce3fb52-0b1d-4925-bea3-5803c14dc672"
  },
  "serviceType": "Metabase",
  "changeDescription": {
    "fieldsAdded": [],
    "fieldsUpdated": [],
    "fieldsDeleted": [],
    "previousVersion": 0.1
  },
  "deleted": false
}

output from db even after update:
{"id": "0207ff8c-b727-41d0-a785-524751e2f9d0", "name": "QTD Net Margin Points", "deleted": false, "version": 0.1, "chartUrl": "https://metabase.agodadev.io/question/6379", "updatedAt": 1680085355821, "updatedBy": "ingestion-bot", "description": "", "displayName": "QTD Net Margin Points", "serviceType": "Metabase", "fullyQualifiedName": "Metabase.QTD Net Margin Points"}

Slack:  https://openmetadata.slack.com/archives/C02B6955S4S/p1680201145907729

CC: @ulixius9

**Comment by sureshms** [comment]
@parthasarathy93 looks like `ChartRepository.java` is missing implementation of `ChartUpdater`. Do you want to take a stab at fixing this and contributing code? For an example of how an updater works, please see `TableUpdater` in `TableRepository.java`.

**Comment by pdeeparao** [comment]
I would like to work on this.

**Comment by parthasarathy93** [comment]
Please go ahead
