### ISSUE TITLE
The count of service on first page after login appears 3. However, only one service is connected.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#10857]
**Affected module**
UI

**Describe the bug**
The count of service on first page after login appears 3. However, only one service is connected.

**To Reproduce**
<img width="165" alt="image" src="https://user-images.githubusercontent.com/110607559/229040859-5f4a14d5-c441-473e-82b4-614cfbe9581c.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/110607559/229040919-55f6497e-9024-484a-874e-162b04a4542a.png">

**Version:**
 OM -13.2.5

**Comment by Sachin-chaurasiya** [comment]
@lailapatel, it's a total service that you have in OM. so its a composition of all service types.

**Comment by lailapatel** [comment]
so far only one service is connected i.e. Redshift. Would it be counting Dashboard service too? that is QuickSight for us. In that case we got 2 services.

Can you share breakup / logics it is using behind the services count?

**Comment by Sachin-chaurasiya** [comment]
> so far only one service is connected i.e. Redshift. Would it be counting Dashboard service too? that is QuickSight for us. In that case we got 2 services.
> 
> Can you share breakup / logics it is using behind the services count?

@lailapatel , The counts that you are seeing on the landing page are to give a gist of metadata you have in OM.

**Comment by sureshms** [comment]
@lailapatel it is better to confirm that the issue you are seeing is indeed a bug on Slack channel before creating an issue. This is a count of all the services. In this case - Redshift, QuickSight, and a metadata service.
