### ISSUE TITLE
ingest issues for kafka messaging 

### ISSUE THREAD

**Issue by chethan-bs** [open-metadata/OpenMetadata#10867]
**Affected module**
Ingestion Framework

**Describe the bug**
we have kafka ingest in airflow and data sync every 1h but on any config changes in the topic data is not getting updated into openmetadata automatically.

**To Reproduce**

<img width="930" alt="image" src="https://user-images.githubusercontent.com/110088247/229115725-c192ae0e-3f92-4906-8681-9f19b8f212ac.png">

**Expected behavior**
on any changes data has to be patched automatically from the Ingestion

**Version:**
 - OS: openmetadata docker image for k8s
 - Python version: openmetadata docker image for k8s
 - OpenMetadata version: 13.2 latest
 - OpenMetadata Ingestion package version: 

**Additional context**
API works fine to use update or patch and i am asking from the airflow ingest scheduler its not updated on changes in the server config of it. ex: when  Partitions change to 5 from server data is not updating in OM until we delete topic name or service itself.

**Comment by chethan-bs** [comment]
Also with reference to the document https://docs.open-metadata.org/connectors/messaging/kafka/cli  markDeletedTopics not working as well. 

i am using python to run directly from the airflow pod which is deployed from the OM image itself to run ingest .. 

airflow@openmetadata-dependencies-web-64749b789f-v6r99:/opt/airflow$ which python3
/usr/local/bin/python3


airflow@openmetadata-dependencies-web-64749b789f-v6r99:/opt/airflow$ metadata ingest -c pp.yaml
[2023-04-04 02:29:33] INFO     {metadata.Utils:logger:165} - Error loading INGEST configuration: We encountered an error parsing the configuration of your MessagingServiceMetadataPipeline.
You might need to review your config based on the original cause of this failure:
         **- Extra parameter 'markDeletedTopics'**
[2023-04-04 02:29:33] INFO     {metadata.Utils:logger:165} - 
Make sure you are following the following format e.g. 'kafka':
[2023-04-04 02:29:33] INFO     {metadata.Utils:logger:165} - ------------
[2023-04-04 02:29:33] INFO     {metadata.Utils:logger:165} - source:
  type: kafka
  serviceName: local_kafka
  serviceConnection:
    config:
      type: Kafka
      bootstrapServers: localhost:9092
      schemaRegistryURL: http://localhost:8081
      consumerConfig: {}
      schemaRegistryConfig: {}
  sourceConfig:
    config:
      type: MessagingMetadata
      topicFilterPattern:
        excludes:
        - _confluent.*
      generateSampleData: true
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: openmetadata
    securityConfig:
      "jwtToken": "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzQm90IjpmYWxzZSwiaXNzIjoib3Blbi1tZXRhZGF0YS5vcmciLCJpYXQiOjE2NjM5Mzg0NjIsImVtYWlsIjoiYWRtaW5Ab3Blbm1ldGFkYXRhLm9yZyJ9.tS8um_5DKu7HgzGBzS1VTA5uUjKWOCU0B_j08WXBiEC0mr0zNREkqVfwFDD-d24HlNEbrqioLsBuFRiwIWKc1m_ZlVQbG7P36RUxhuv2vbSp80FKyNM-Tj93FDzq91jsyNmsQhyNv_fNr3TXfzzSPjHt8Go0FMMP66weoKMgW2PbXlhVKwEuXUHyakLLzewm9UMeQaEiRzhiTMU3UkLXcKbYEJJvfNFcLwSl9W8JCO_l0Yj3ud-qt_nQYEZwqW6u5nfdQllN133iikV4fM5QZsMCnm8Rq1mvLR0y9bmJiD7fwM1tmJ791TUWqmKaTnP49U493VanKpUAfzIiOiIbhg"

[2023-04-04 02:29:33] INFO     {metadata.Utils:logger:165} - ------------
[2023-04-04 02:29:33] INFO     {metadata.Utils:logger:165} - 
For more information, please visit: https://docs.open-metadata.org/connectors/ingestion/workflows/metadata
Or join us in Slack: https://slack.open-metadata.org/
airflow@openmetadata-dependencies-web-64749b789f-v6r99:/opt/airflow$

**Comment by chethan-bs** [comment]
any updates ?

**Comment by harshach** [comment]
markDeletedTopics works as expected 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/233821453-302da773-7c86-4269-ac38-27b92a450a9a.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/38649/233821474-13e84ee3-e85d-4fe4-806e-17dddd5f0679.png">

**Comment by harshach** [comment]
topicConfig is now supported in UI. All of your topicConfigs are visible including updated ones in 1.0
markDeletedTopics works as expected in my testing 
cc @chethan-bs
