### ISSUE TITLE
App Analytics: Show "Yesterday" as option for analysis period

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#10878]
**Is your feature request related to a problem? Please describe.**
Current analysis period filter option don't allow me to look at yesterday's data, or even T90days (also common).

**Describe the solution you'd like**
I'd like to have additional filter options.
- Yesterday
- Last 90 days

![image](https://user-images.githubusercontent.com/102999683/229301067-2efb4de3-d4a6-46ba-bf61-e977b8da4b8a.png)

**Comment by ShaileshParmar11** [comment]
similer issue [#10187](https://github.com/open-metadata/OpenMetadata/issues/10187)

**Comment by ShaileshParmar11** [comment]
yesterday will be default selected @aniketkatkar97
