### ISSUE TITLE
backend: aggregate and suggest APIs not working properly

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#10888]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**
1. A clear and concise description of what the bug is.
Both the `aggregate` and `suggest` APIs are not working for the container entity when trying to search through the `columns` field.

https://user-images.githubusercontent.com/51777795/229433682-54b0964a-bd83-44f2-bf66-eda35f63df03.mov

- Aggregate:
Request URL: `/api/v1/search/aggregate?index=container_search_index&field=dataModel.columns.name`

- Suggest:
Request URL: `/api/v1/search/suggest?index=container_search_index&field=column_suggest&q=d`

2. `Suggest` API is not working properly for the `Dashboard` entity for the `chart_suggest` field. As shown in the video, the dashboard `FCC New Coder Survey 2018` should return two charts in suggestion when searched with the query `bo`(i.e. `Box Plot` and `Boy Name Cloud`), but the response object contains only one option, although the length of results in the object is `2`.

https://user-images.githubusercontent.com/51777795/229471413-c8e2f52a-fdb9-473b-b148-207fd8deb4cf.mov

Request URL: `/api/v1/search/suggest?index=dashboard_search_index&field=chart_suggest&q=bo`
Response: 
```
{
    "text": "bo",
    "offset": 0,
    "length": 2,
    "options": [
        {
            "text": "Box plot",
            "_index": "dashboard_search_index",
            "_type": "_doc",
            "_id": "0021151a-65bd-4638-8717-86546cfd9bab",
            "_score": 10,
            "_source": {
                "id": "0021151a-65bd-4638-8717-86546cfd9bab",
                "name": "FCC New Coder Survey 2018",
                "displayName": "FCC New Coder Survey 2018",
                "fullyQualifiedName": "sample_superset.11",
                "description": "",
                "version": 0.1,
                "updatedAt": 1680252275906,
                "updatedBy": "admin",
                "dashboardUrl": "http://localhost:808/superset/dashboard/7/",
                "charts": [
                    {
                        "id": "3194d51e-b75e-4062-901f-20047982d13e",
                        "type": "chart",
                        "name": "170",
                        "fullyQualifiedName": "sample_superset.170",
                        "description": "",
                        "displayName": "Box plot",
                        "deleted": false
                    },
                    {
                        "id": "648d9946-1c7b-4dd0-ad5e-fdfdd1c389e1",
                        "type": "chart",
                        "name": "180",
                        "fullyQualifiedName": "sample_superset.180",
                        "description": "",
                        "displayName": "Boy Name Cloud",
                        "deleted": false
                    },
                    {
                        "id": "074dff51-2310-4030-b70c-41c9720faa30",
                        "type": "chart",
                        "name": "183",
                        "fullyQualifiedName": "sample_superset.183",
                        "description": "",
                        "displayName": "Average and Sum Trends",
                        "deleted": false
                    },
                    {
                        "id": "6b4a27bc-ea81-445c-b3b1-da7ddf2923c1",
                        "type": "chart",
                        "name": "197",
                        "fullyQualifiedName": "sample_superset.197",
                        "description": "",
                        "displayName": "Arcs",
                        "deleted": false
                    }
                ],
                "dataModels": [],
                "href": "http://localhost:8585/api/v1/dashboards/0021151a-65bd-4638-8717-86546cfd9bab",
                "followers": [],
                "tags": [],
                "service": {
                    "id": "6a375a27-0a10-4661-8636-ea29bc254d1f",
                    "type": "dashboardService",
                    "name": "sample_superset",
                    "fullyQualifiedName": "sample_superset",
                    "deleted": false
                },
                "serviceType": "Superset",
                "usageSummary": {
                    "dailyStats": {
                        "count": 0,
                        "percentileRank": 0
                    },
                    "weeklyStats": {
                        "count": 0,
                        "percentileRank": 0
                    },
                    "monthlyStats": {
                        "count": 0,
                        "percentileRank": 0
                    },
                    "date": "2023-04-03"
                },
                "deleted": false,
                "tier": null,
                "suggest": [
                    {
                        "input": "sample_superset.11",
                        "weight": 5
                    },
                    {
                        "input": "FCC New Coder Survey 2018",
                        "weight": 10
                    }
                ],
                "chart_suggest": [
                    {
                        "input": "Box plot",
                        "weight": 5
                    },
                    {
                        "input": "Boy Name Cloud",
                        "weight": 5
                    },
                    {
                        "input": "Average and Sum Trends",
                        "weight": 5
                    },
                    {
                        "input": "Arcs",
                        "weight": 5
                    }
                ],
                "service_suggest": [
                    {
                        "input": "sample_superset",
                        "weight": 5
                    }
                ],
                "entityType": "dashboard"
            }
        }
    ]
}
```

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97 always .keyword for a filed at the end. 
cc @chirag-madlani 
http://localhost:8585/api/v1/search/aggregate?index=container_search_index&field=dataModel.columns.name.keyword

```{
    "took": 14,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 7,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "sterms#dataModel.columns.name.keyword": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "approved",
                    "doc_count": 1
                },
                {
                    "key": "budget_executor",
                    "doc_count": 1
                },
                {
                    "key": "budget_total_value",
                    "doc_count": 1
                },
                {
                    "key": "department_id",
                    "doc_count": 2
                },
                {
                    "key": "fraudulent_claims",
                    "doc_count": 1
                },
                {
                    "key": "merchant",
                    "doc_count": 1
                },
                {
                    "key": "notes",
                    "doc_count": 1
                },
                {
                    "key": "total_value_for_current_month",
                    "doc_count": 1
                },
                {
                    "key": "transaction_id",
                    "doc_count": 1
                },
                {
                    "key": "transaction_time",
                    "doc_count": 1
                }
            ]
        }
    }
}```

**Comment by harshach** [comment]
suggest
```
http://localhost:8585/api/v1/search/suggest?index=container_search_index&field=column_suggest&q=d ```

Response

```
{
    "suggest": {
        "metadata-suggest": [
            {
                "text": "d",
                "offset": 0,
                "length": 1,
                "options": [
                    {
                        "text": "department_id",
                        "_index": "container_search_index",
                        "_type": "_doc",
                        "_id": "fbb18d09-b4d9-455b-8186-e5132ebe2e18",
                        "_score": 5.0,
                        "_source": {
                            "id": "fbb18d09-b4d9-455b-8186-e5132ebe2e18",
                            "name": "finance",
                            "fullyQualifiedName": "s3_object_store_sample.departments.finance",
                            "displayName": "Finance department",
                            "description": "Bucket containing finance department information",
                            "version": 0.1,
                            "updatedAt": 1680504511774,
                            "updatedBy": "admin",
                            "href": "http://localhost:8585/api/v1/containers/fbb18d09-b4d9-455b-8186-e5132ebe2e18",
                            "service": {
                                "id": "d448d780-52ab-4254-bc85-061ecb0040c1",
                                "type": "objectStoreService",
                                "name": "s3_object_store_sample",
                                "fullyQualifiedName": "s3_object_store_sample",
                                "deleted": false,
                                "href": "http://localhost:8585/api/v1/services/objectStoreServices/d448d780-52ab-4254-bc85-061ecb0040c1"
                            },
                            "parent": {
                                "id": "c9624db8-06d4-44e4-8bd7-89cda9d19b20",
                                "type": "container",
                                "name": "departments",
                                "fullyQualifiedName": "s3_object_store_sample.departments",
                                "description": "Bucket containing company department information",
                                "displayName": "Company departments",
                                "deleted": false,
                                "href": "http://localhost:8585/api/v1/containers/c9624db8-06d4-44e4-8bd7-89cda9d19b20"
                            },
                            "dataModel": {
                                "isPartitioned": false,
                                "columns": [
                                    {
                                        "name": "department_id",
                                        "dataType": "NUMERIC",
                                        "dataTypeDisplay": "numeric",
                                        "description": "The ID of the department. This column is the primary key for this table.",
                                        "fullyQualifiedName": "s3_object_store_sample.departments.finance.department_id",
                                        "tags": [],
                                        "constraint": "PRIMARY_KEY",
                                        "ordinalPosition": 1
                                    },
                                    {
                                        "name": "budget_total_value",
                                        "dataType": "NUMERIC",
                                        "dataTypeDisplay": "numeric",
                                        "description": "The department's budget for the current year.",
                                        "fullyQualifiedName": "s3_object_store_sample.departments.finance.budget_total_value",
                                        "tags": [],
                                        "ordinalPosition": 2
                                    },
                                    {
                                        "name": "notes",
                                        "dataType": "VARCHAR",
                                        "dataLength": 100,
                                        "dataTypeDisplay": "varchar",
                                        "description": "Notes concerning sustainability for the budget.",
                                        "fullyQualifiedName": "s3_object_store_sample.departments.finance.notes",
                                        "tags": [],
                                        "ordinalPosition": 3
                                    },
                                    {
                                        "name": "budget_executor",
                                        "dataType": "VARCHAR",
                                        "dataTypeDisplay": "varchar",
                                        "description": "The responsible finance lead for the budget execution",
                                        "fullyQualifiedName": "s3_object_store_sample.departments.finance.budget_executor",
                                        "tags": [],
                                        "ordinalPosition": 4
                                    }
                                ]
                            },
                            "prefix": "/departments/finance/",
                            "numberOfObjects": 75.0,
                            "size": 286720.0,
                            "fileFormats": [
                                "zip",
                                "csv"
                            ],
                            "serviceType": "S3",
                            "deleted": false,
                            "tags": [],
                            "tier": null,
                            "followers": [],
                            "suggest": [
                                {
                                    "input": "s3_object_store_sample.departments.finance",
                                    "weight": 5
                                },
                                {
                                    "input": "finance",
                                    "weight": 10
                                }
                            ],
                            "service_suggest": [
                                {
                                    "input": "s3_object_store_sample",
                                    "weight": 5
                                }
                            ],
                            "column_suggest": [
                                {
                                    "input": "department_id",
                                    "weight": 5
                                },
                                {
                                    "input": "budget_total_value",
                                    "weight": 5
                                },
                                {
                                    "input": "notes",
                                    "weight": 5
                                },
                                {
                                    "input": "budget_executor",
                                    "weight": 5
                                }
                            ],
                            "entityType": "container"
                        }
                    }
                ]
            }
        ]
    }
}
```

**Comment by harshach** [comment]
@aniketkatkar97 the suggest keywords are used to retrieve a document that matches the keywords in suggest. It won't give you 2 different documents as the Box Chart, Boy Name Cloud belongs to the same document. So either you search with "Box" or "Boy" they hit one source document which is the dashboard doc that contains both these charts. The response you are getting is correct.
