### ISSUE TITLE
Review ALTER table name in db usage to update new table metadata

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10930]
From https://openmetadata.slack.com/archives/C02AZGN0WKY/p1680671001230059

Consider the following scenario:
1. We have a table A with metadata
2. We run `ALTER TABLE A RENAME TO B`
3. In the next ingestion, Table `A` will be deleted and Table `B` ingested without `A`'s metadata

In the query Usage we can identify these statements, and update `B`'s metadata from `A`

**Comment by nuang-ee** [comment]
Thanks for fast feedbacks!

In addition, I think it will be cool if `B` contains `A`'s change event histories in above case,
(or it will be sufficient to leave any record in `B`'s history, that tells renamed from `A`)
