### ISSUE TITLE
Update workflow config

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1095]
We are currently defining our workflows as simple static JSON files.

It would be interesting to allow more complete integration of these files into our systems. Having the possibility of using Jinja syntax on top would benefit us even if it is just for security reasons. Instead of managing the user & pwd of the systems directly into the files, we could have a dynamic rendering of custom functions to help us push these configurations to Github or any other versioning system without security risks.

Having a greater level of dynamism would also help us ingest data from the different environments within a single file.

Moreover, data validation on top of the configurations would help us detect possible issues as early as possible during the rendering step.

---

Example:

Instead of having our `superset.json` workflow as

```
{
  "source": {
    "type": "superset",
    "config": {
      "url": "http://localhost:8088",
      "username": "admin",
      "password": "admin",
      "service_name": "local_superset"
    }
  },
  "sink": {
    "type": "metadata-rest",
    "config": {
    }
  },
  "metadata_server": {
    "type": "metadata-server",
    "config": {
      "api_endpoint": "http://localhost:8585/api",
      "auth_provider_type": "no-auth"
    }
  }
}
```

We could aim for:

```
{
  "source": {
    "type": "superset",
    "config": {
      "url": "${env('SUPERSET_SERVER')}",
      "username":"${env('SUPERSET_USER')}"
      "password": "${env('SUPERSET_PWD')}"
      "service_name": "local_superset"
    }
  },
  "sink": {
    "type": "metadata-rest",
    "config": {
    }
  },
  "metadata_server": {
    "type": "metadata-server",
    "config": {
      "api_endpoint": "${env('API_ENDPOINT')}",
      "auth_provider_type": "no-auth"
    }
  }
}
```

Where the `env` function retrieves environment variables at render-time.

I had developed a small library that adds these kind of security and dynamism: https://pmbrull.github.io/levy/.

I'll review if/how this could be integrated.

Thanks

**Comment by pmbrull** [comment]
I see that we are already using `expandvars`, which is great for environment variables. However, we would still miss on other needs for retrieval of information, such as Vault, Azure KeyVault or any other method to store sensitive information

**Comment by harshach** [comment]
@pmbrull this is a good idea. wondering how would you fetch there username and password.
Our goal always has been that user first goes to services section
1. Define a service 
2. Add a connection
3. Setup Ingestion through the UI itself -> pending for 0.6 release

One option, I was thinking is all user(admin) can pass is the service.name and the ingestion makes a call to fetch the connection details like username, password etc..
1. we already have admin, bot concept. We guard such sensitive details to be retrieved by admin and bot
2. OpenMetadata can be setup using ssl. Hence the wire transfer such sensitive details are protected

IMO, convenient tooling such metadata ingest more of a user-friendly way of installing. Anyone who is going to run OpenMetadata in production should use Airflow to schedule the ingestion pipelines.
I am curious to understand how can jinja templates can be used here.
Btw Levy is pretty cool :) . I may use in another projects too . But we can definitely move the json to jinja based templates.

**Comment by pmbrull** [comment]
Hi @harshach 🤗 thanks for your input!!

Good point about configuring the ingestions through airflow. This would leave all configs self contained and secure.

What I was also trying to solve is providing all necessary information as infrastructure as code. While having the possibility of figuring the whole workflow out from the UI, if we can just provide new files directly in git and push the changes, that would make the service more maintainable.

Thanks for your comments on Lévy! Feel free to open any issues there in case there's something you would need. Happy to make any adjustments!

**Comment by pmbrull** [comment]
In terms of retrieving user & pwd, that could be an env var or any specific function to get it from other services. We could update Lévy's registry at runtime to have custom functionalities.

However, in terms of IaC it might be easier to directly create de Airflow DAGs 🤔 then the workflow parser would not need these additions.

**Comment by pmbrull** [comment]
I was giving this another read. Agree on:
- `metadata ingest` makes sense for a nice-to-have CLI to play around
- PROD scenarios, which are the ones that are going to need further security and improved setup must be in Airflow. The engineers can then parse the config file as they see fit.

Let's close this! Thanks
