### ISSUE TITLE
need API support to improve search behaviour on teams page

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#10954]
Currently, on the team's page we have a hierarchical view, and to get full hierarchical view we are making teams call with 1000 limit, and also maintaining search on the UI side. so the problem with this is we can only search for the team which is present on UI side.
-> One solution could be to implement team hierarchical API but the challenge is we don't have the option to fetch hierarchical for a particular parent team and also we don't have a count for assets and users for the team in the API response, which we currently show in teams page

![image](https://user-images.githubusercontent.com/71748675/230372619-9db252dc-cb01-4911-a708-f02d9340e822.png)

**Comment by harshach** [comment]
@ShaileshParmar11 is this still an issue?
