### ISSUE TITLE
Extend Tableau connector to ingest databases, data sources, workbook sheets, extracts and calculated terms

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#10952]
**Is your feature request related to a problem? Please describe.**
Tableau is a complex BI platform that can serve for visualization, business metrics calculation, data processing, data pipeline management. So, if we consider Tableau only as a dashboarding tool, we miss a lot of useful metadata for various data management cases. That’s why it’s critical to have full and high-quality metadata ingestion from Tableau.

**Describe the solution you'd like**
There is a paper with detailed solution in attachment
[How to collect metadata from Tableau.pdf](https://github.com/open-metadata/OpenMetadata/files/11168039/How.to.collect.metadata.from.Tableau.pdf)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pmbrull** [comment]
hi @gnomolio, it would be great if you could check out the 1.0 release, where we added already the data source extraction from Tableau.

Let us know if you have any feedback. We still need to work on col-level lineage and other elements you mention in your doc, such as freshness or business metrics, but we have a big foundation already.
