### ISSUE TITLE
Ingestion bot overwrites the table descriptions

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#10964]
**Affected module**
backend

**Describe the bug**
To reproduce did the following steps:
- create a table with comment and ingest it to openmetadata
- from the UI update the description 
- run the ingestion once again and you will find that the updated description is lost as ingestion-bot will overwrite it

support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1680705080670079

**Comment by gnomolio** [comment]
overriding is a feature when data owners document tables and columns in RDBMS itself (via sql migration files). 
it seems the flag "override descriptions from data source" will be useful.

**Comment by harshach** [comment]
@ulixius9 is this reproducible?

**Comment by ulixius9** [comment]
Tested this out, not reproducible. closing the ticket. 

the issue on the ingestion side related to oracle table comments has already been fixed
