### ISSUE TITLE
In Lineage view, Airflow URL in `PopOverCard` is broken.

### ISSUE THREAD

**Issue by nuang-ee** [open-metadata/OpenMetadata#10993]
**Affected module**
- Impacts on UI.

**Describe the bug**

<img width="794" alt="image" src="https://user-images.githubusercontent.com/50770626/231049292-f42d027c-008c-439f-9ee5-3e4b7d37a828.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/50770626/231049460-f10b5f4f-f63f-47b3-87b1-68a3042a0ae9.png">

- In lineage view, in the `PopOverCard` (I think this is the component shown in above, sorry if wrong), "airflow URL" href is referencing to relative path, which is eventually pointing to broken URL in OpenMetadata.

**Expected behavior**
- Airflow URL link should be built with actual airflow service's URL + `PipelineEntity.pipelineUrl`, instead of just the relative path of the pipeline.

**Version:**
 - OpenMetadata version: latest (0.13.3)
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==0.13.3`]

**Additional context**
- `pipelineUrl` of `PipelineEntity` seems to be determined in here: https://github.com/open-metadata/OpenMetadata/blob/0bbcfc5b3dbc314da0e0936d25626e24fef6835e/ingestion/src/airflow_provider_openmetadata/lineage/runner.py#L148-L164

**Comment by ulixius9** [comment]
closing this ticket as this is already fixed by #10957
