### ISSUE TITLE
UI: provide and improve the 'Deleted Entity' switch

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#11003]
**Affected module**
UI

**Describe the bug**
Currently, the `Deleted Entity` switch is not being used in all the required places where the user should be able to see the soft deleted entities. Also, the switch provided in some places, e.g. database schema details page, is not upfront and it's hard to know for the user about the existing functionality as the switch is inside a manage button actions dropdown.

**Expected behavior**

- [ ] Improve existing user experience with the provided switch in the database schema details page where it is not upfront
<img width="460" alt="Screenshot 2023-04-11 at 7 10 48 PM" src="https://user-images.githubusercontent.com/51777795/231185373-a4af4a85-b352-43ef-8708-23b2a72dfa5c.png">

- [ ] Provide a `Deleted Entity` switch in all the required places:
- Database Details Page
- Database Schema Page
- Service Details page for Topics, Pipeline, Dashboard, MlModel, and Containers
<img width="1440" alt="Screenshot 2023-04-11 at 7 10 18 PM" src="https://user-images.githubusercontent.com/51777795/231184815-302ffc12-d21b-4522-ab69-c53329311bab.png">
<img width="1440" alt="Screenshot 2023-04-11 at 7 10 27 PM" src="https://user-images.githubusercontent.com/51777795/231184842-205c9e49-8ae1-4f57-953b-1001314b23e8.png">
<img width="1121" alt="Screenshot 2023-04-11 at 7 15 53 PM" src="https://user-images.githubusercontent.com/51777795/231184848-afd13903-6a4f-4255-8738-4afa3f43b46c.png">

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
@devyani-kaushik we need updated mocks here to show deleted assets
Text for the switch will be "Show deleted <Entity>"

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?type=design&node-id=19271%3A22973&t=CyY32Bu2zRl8g0O3-1
