### ISSUE TITLE
UI Improvements Backlog

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#11029]
- [ ] Glossary - Give max width to term name in the table where the name gets wrapped
- [ ] Reduce the character limit for glossary name

- [ ] Use full width for the description in entity tables
<img width="430" alt="Screenshot 2023-04-12 at 3 24 52 PM" src="https://user-images.githubusercontent.com/103238069/231517473-87fcb3a2-1748-4006-921b-debca6e86784.png">

- [ ] Placeholders on explore are touching the boundaries

Uploading Screen Recording 2023-04-27 at 11.15.17 AM.mov…

**Comment by OnkarVO7** [comment]
- [ ] Incorrect pagination number is getting displayed on the users page
Proposed Solution: Disable the `next` button till the next API results are in
<img width="909" alt="Screenshot 2023-04-27 at 11 18 13 AM" src="https://user-images.githubusercontent.com/28966081/234779873-cf6f95e0-661d-4df0-a9e6-077ea64a7b4b.png">
