### ISSUE TITLE
Glossary term with long FQN can be used for tagging but fails in the client

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11032]
If we keep creating terms with long names as children, we can end up with a rather long glossary term.

The issue is:
- `tagLabel` is 128 characters https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/type/tagLabel.json#L11
- We can tag from the UI with terms with FQN longer than 128
- The validation only happens when picking up the data from the client, which fails

```
>>> metadata.get_by_name(entity=Table, fqn="sample_data.ecommerce_db.shopify.raw_customer",fields=["tags"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 590, in get_by_name
    return self._get(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 623, in _get
    return entity(**resp)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Table
columns -> 0 -> tags -> 0 -> tagFQN -> __root__
  ensure this value has at most 128 characters (type=value_error.any_str.max_length; limit_value=128)
```

The backend/UI should verify if we are using a tag that follows the spec

**Comment by pmbrull** [comment]
from https://openmetadata.slack.com/archives/C02B6955S4S/p1681307084042099

**Comment by harshach** [comment]
yes this will work in fqnHash

**Comment by sureshms** [comment]
@harshach to be closed along with size increases for names and fqnHash.
