### ISSUE TITLE
UI : The column lineage is not displayed  correctly

### ISSUE THREAD

**Issue by gzusgw** [open-metadata/OpenMetadata#11038]
**Affected module**
 UI

**Describe the bug**
The UI does not display the column lineage correctly

example：
a pg sql : insert into tb_2 select * from tb_source,the ui lineage is ：
![image](https://user-images.githubusercontent.com/37568108/231682310-69ce6f78-45df-4c20-96ca-c510aa714a86.png)

version:1.0.0-alpha

**Comment by ulixius9** [comment]
closing ticket by https://github.com/open-metadata/OpenMetadata/pull/11250
