### ISSUE TITLE
Add ZH index mapping configurations

### ISSUE THREAD

**Issue by heroWang** [open-metadata/OpenMetadata#11035]
**Is your feature request related to a problem? Please describe.**
When I search for Chinese text, I can only find complete short phrases separated by spaces, but cannot find individual Chinese words.

**Describe the solution you'd like**
Add Chinese tokenizer for ElasticSearch, for example : IK

**Describe alternatives you've considered**
No

**Additional context**
https://openmetadata.slack.com/archives/C02B6955S4S/p1680855759965709

**Comment by harshach** [comment]
ZH index mappings are already supported https://github.com/open-metadata/OpenMetadata/tree/main/openmetadata-service/src/main/resources/elasticsearch/zh
