### ISSUE TITLE
Feature request: Register web APIs as metadata for data products

### ISSUE THREAD

**Issue by ruial** [open-metadata/OpenMetadata#11046]
**Is your feature request related to a problem? Please describe.**
Data products can currently be registered as services in the form of tables, queues, dashboards, pipelines and ML models.

However, it would be awesome to have another Service, for **web APIs**. For example, some data products are exposed as REST or gRPC APIs instead of tables/queues. ChatGPT comes to mind as an example. Companies may develop many data/ML-related APIs they could register on the catalog so other teams can find them more easily.

**Describe alternatives you've considered**
Use another service catalog tool to register APIs like Backstage.

**Comment by DovileKr** [comment]
Support the idea. Similar to one raised by me: https://github.com/open-metadata/OpenMetadata/issues/10933

**Comment by harshach** [comment]
closing this in favor #10933
