### ISSUE TITLE
Non-admin user can't join open teams

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#11057]
**Affected module**
backend

**Describe the bug**
Users with DataConsumer role or any role without EditAll operation cannot join the open team
<img width="591" alt="image" src="https://user-images.githubusercontent.com/38649/231925305-2d57cbf4-5f8b-42ec-bfce-5f1bcec36f71.png">
We are already validating the PATCH method in UserResource, however, we are getting the EditAll operation check in patchInternal .

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
Currently joining a team is becoming an EditAll operation. And only users that have EditAll on User entity can join a team. Changing the authorization mechanism as follows:
- For a user entity set the owner as the user himself
- The isOwner() policy will kick in and allow all the operations for a user on the entity corresponding to him
- Changing isBot and isAdmin is still only allowed for the admin

cc @harshach

**Comment by harshach** [comment]
@sureshms sounds good to me.
