### ISSUE TITLE
Add customizable link under help menu

### ISSUE THREAD

**Issue by LKMcGrath** [open-metadata/OpenMetadata#11077]
Looking to add a customizable link in the help menu that can be used to send users to internal documentation.
![image](https://user-images.githubusercontent.com/108548597/232140028-14e42969-aec4-48d0-bd7c-eee2f569287e.png)

Thanks!

**Comment by harshach** [comment]
we added knowledge center to add quick links and articles to address this. We will not be customizing the menu.
