### ISSUE TITLE
Make entire item clickable within UI dropdown for Settings

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#1109]
User cannot click on the highlighted item for Tags in the screenshot below 

![Screen Shot 2021-11-08 at 9 30 32 PM](https://user-images.githubusercontent.com/5906984/140868054-b0551dad-aa93-49f8-97bc-0890c57bdc93.png)

User has to click specifically on the Tags text 

![Screen Shot 2021-11-08 at 9 30 38 PM](https://user-images.githubusercontent.com/5906984/140868038-b3df2454-9613-4c17-9031-9bdf5d1f6b96.png)

(This is from Sandbox environment)

**Comment by mithmatt** [comment]
@shahsank3t @darth-coder00 @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
@mithmatt thanks for filing the ticket.

**Comment by ShaileshParmar11** [comment]
assign this to me

**Comment by Sachin-chaurasiya** [comment]
> assign this to me

@ShaileshParmar11 assigned to you.
