### ISSUE TITLE
Cannot delete message as an admin

### ISSUE THREAD

**Issue by ichbinangela** [open-metadata/OpenMetadata#11103]
**Affected module**
UI

**Describe the bug**
Delete message button is covered by a gray layer and users won't be able to click on it.

<img width="1436" alt="截圖 2023-04-13 11 54 50" src="https://user-images.githubusercontent.com/9590974/232716416-25722b1c-222f-4615-bd6a-db8b3d79eb38.png">

**To Reproduce**

Login as admin, table -> conversation -> delete conversation

**Expected behavior**

delete message button can be clicked.

**Version:**

 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/11163
