### ISSUE TITLE
React state is not getting clear on Explore page

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#1110]
If we click on explore page, and switch to another tab and change the filter like click on `Tier1` then if we click on explore again, it calls api with filters (`Tier1`).

![image](https://user-images.githubusercontent.com/71748675/140869328-a1c89c70-0048-41f0-b48d-5e41e479ec35.png)
![image](https://user-images.githubusercontent.com/71748675/140869352-ba23d80d-0347-4c68-a428-e55341881398.png)

**Comment by darth-coder00** [comment]
Fixed by #1115
