### ISSUE TITLE
Data observability capabilities

### ISSUE THREAD

**Issue by seckindinc** [open-metadata/OpenMetadata#11110]
**Is your feature request related to a problem? Please describe.**
On the official website, the tool describes itself as an observability solution. Unfortunately, the core functionalities of an observability tool are not handled in the tool.

**Describe the solution you'd like**
I would like to have automated anomaly detection capabilities that distinguish the normal and outlier behaviors from each other to notify the users.

**Describe alternatives you've considered**
Soda Core has observability capabilities built on the Prophet algorithm. As the Prophet algorithm is not a trustworthy solution in the data science community, another approach can be followed by you.

**Additional context**

**Comment by TeddyCr** [comment]
@seckindinc this will be part of the SaaS solution. Closing this issue from the OS board
