### ISSUE TITLE
Automated - Data Quality Certification process 

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#11136]
**Is your feature request related to a problem? Please describe.**
Problem Statement: For data consumers, the most important question is whether they can trust an information asset or not. The consumer can't determine the trustworthiness of the data until they can some sort of verification badge that confirms the particular table/dashboard is certified and good to use

**Describe the solution you'd like**
Solution: There could be a verification process based on data quality coverage at the table/dashboard level. This certification can have different levels like Gold, Silver, Bronze or non-verified. The entire verification process can be automated with the least manual intervention and should also be customizable. For example, if a table has 90% of columns with data quality test then should be at Gold level, if between 50% to 90% then Silver and if between 30% to 50% then Bronze otherwise non-verified.

Now this % should be customizable 

Once certification calculation is done for each table then that must be reflect in OpenMetadata for the table , one badge for each table

**Comment by FelipeArruda** [comment]
@17rahulsharma nice ideia.

@harshach and @pmbrull look this idea.

**Comment by pmbrull** [comment]
Hi @17rahulsharma, thanks for popping the issue.

We have similar ideas in mind about adding a certification process to give a stamp to an asset based on a set of rules. We still need to land things, and this issue will def help.

We'll be preparing the roadmap for OM and Collate after 1.0 is out, and we'll be able to give you all some more visibility and open the conversation on what we will be cooking in the following months.

Thanks!

**Comment by 17rahulsharma** [comment]
Thanks @pmbrull looking forward for this!

**Comment by 17rahulsharma** [comment]
@pmbrull - this is how we do it now at my organisation. (adding images for the ideation process)

![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/80594da2-3151-4496-9dd1-b82fd261e332)
![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/55464c31-cd83-4133-bb3c-e12be272fa1f)

**Comment by harshach** [comment]
Available in Collate SaaS
