### ISSUE TITLE
Table PUT API fails when child column contains `.` in name

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#11142]
**Affected module**
Backend

**Describe the bug**
When creating a table with put api with example request as follows 

```
{
  "columns": [
    {
      "children": [
        {
            "dataType": "NUMBER",
            "name": "child.test.hello"
        }
      ],
      "dataType": "NUMBER",
      "name": "parent"
    }
  ],
  "databaseSchema": "local_mysql.default.openmetadata_db",
  "name": "test_ss_s",
  "tableType": "Regular"
}
``` 

if table did not exist it gets created successfully but when trying to hit the same api again (basically trying to update the table)

```
{
  "code": 400,
  "message": "Invalid name parent.\"child.test.hello\""
}
```

**Comment by harshach** [comment]
@ulixius9 you need to escape the quotes just like we are doing it for the table names

**Comment by ulixius9** [comment]
@harshach I'm not sure if I follow that, I'm not passing quotes in the name instead passing `.` in the name 

and this only happens when there is a `.` in name of child column and works if there is a `.` in the name of parent or top column 


https://user-images.githubusercontent.com/39544459/233543183-4e4d2f79-a185-4308-aff9-3e3c443a119b.mov
