### ISSUE TITLE
Add URL as default entity field schema definition

### ISSUE THREAD

**Issue by stephanesol** [open-metadata/OpenMetadata#11178]
**Is your feature request related to a problem? Please describe.**

The dashboard entity in OMD has a [dashboardUrl](https://github.com/open-metadata/OpenMetadata/blob/9acf45cd1b3e9c055121feee3fcd82a716502bd3/openmetadata-spec/src/main/resources/json/schema/entity/data/dashboard.json#L43) .  If populated this URL is exposed to end users via the UI and enables them to continue their data exploration journey.   I think this url field should be made available many more if not all entity types.   

For my use case, i'd like to be able to populate a URL for snowflake tables so users can go from discovering data in OpenMetadata to directly querying/engaging with the data source in another tool.

The UI for the dashboard entity does this well and i think it could be extended to other services like databases.

**Describe the solution you'd like**

Allow some kind of url on the database table/view entity that could be populated via ingestion or api.
Allow this to be exposed, if available, in the UI similar to how it is done for dashboards.

**Describe alternatives you've considered**

Right now the alternative i'm using is using custom properties, which i understand can be populated with anything i want 🙇  but i think it can be buried in the UI.  This requested change, I believe,  would provide users with a clearer call to action to further explore data.

**Additional context**

cc @harshach from community office hours 🙇

**Comment by harshach** [comment]
@ulixius9 sourceURL is added as part of this PR https://github.com/open-metadata/OpenMetadata/commit/c3cec54be926dd511087af689798ddc3fc91d0ba
but we missed adding it for Topic, Database, DatabaseSchema, MLModel, Container. Let's make sure we add it everywhere.

@07Himank can you take this up
