### ISSUE TITLE
UI: Show consistent add and edit tags button on columns

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#1117]
Here we are showing a button like this to add tags
![image](https://user-images.githubusercontent.com/59080942/140945613-6c71f042-2826-483d-b9f6-223baaad07fb.png)

But in the dashboard charts table, we are not showing any button
![image](https://user-images.githubusercontent.com/59080942/140945741-9f841c32-e887-49a3-9176-c02e6bc0b1f0.png)

**Comment by darth-coder00** [comment]
Related issue: #852
