### ISSUE TITLE
Kafka connection SASL Mechanism

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11216]
Should be an enum instead of a basic string

`GSSAPI`, `PLAIN`, `SCRAM-SHA-256`, `SCRAM-SHA-512`, `OAUTHBEARER`.

**Comment by nahuelverdugo** [comment]
@pmbrull 
- What should be the default value? 
- For migration, should we remove the current SASL Mechanism in case it is set?

**Comment by pmbrull** [comment]
- not sure about the default, we might to get whatever is the most common. Not sure if there is a `NOSASL` method there that disables this.
- For migration we can remove the current SASL if it is not in the supported enum

**Comment by harshach** [comment]
@nahuelverdugo default will be PLAIN
