### ISSUE TITLE
Dashboard - Metabase

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#1122]
Hi,

Metabase is an open-source popular BI solution.
As Apache superset, integration Metabase would be a nice feature.

**Comment by harshach** [comment]
@haithem-souala Thanks a lot for opening this issue. Let us know if you are interested in contributing . We can help with the code base.

**Comment by harshach** [comment]
Api details https://www.metabase.com/docs/latest/api-documentation.html
Lets collect
1. Dashboard
2. Metric , it will be chart on OM side
3. what queries each Metric is using

**Comment by haithem-souala** [comment]
You rock guys!!
