### ISSUE TITLE
[UI] Data Insights UI does not show scheduling options

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#11254]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
![image](https://user-images.githubusercontent.com/15995028/234215271-0b8b723b-b8e3-467e-99ea-dad2c6302e4e.png)

**To Reproduce**
Navigate to settings > Insights edit the existing insights available or create new. Proceed to the last screen where you can configure scheduling activity.

**Expected behavior**
Possible option is to disable the cron scheduling if this is intended to run everyday!

**Version:**
 - OpenMetadata version: 1.0.0-beta

**Comment by pmbrull** [comment]
we should not allow people to change the day
