### ISSUE TITLE
GX results not shown on OpenMetadata per expectation

### ISSUE THREAD

**Issue by fionachowps** [open-metadata/OpenMetadata#11275]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
1. GX results populated on OM does not match the actual GX result

  On GX Data Docs, observed value shows `≈21.846% unexpected`
  On OM Test Case Chart, observed value shows `0`
  
  GX validation output
  `
  {
        "result": {
          "element_count": 15179,
          "missing_count": 0,
          "missing_percent": 0.0,
          "unexpected_count": 3316,
          "unexpected_percent": 21.84597140786613,
          "unexpected_percent_nonmissing": 21.84597140786613,
          "unexpected_percent_total": 21.84597140786613
          }
  }
  `
  
  OM screenshot
  ![image](https://user-images.githubusercontent.com/121575191/234346330-ed72c18e-b78c-4f1c-8d0b-38c68b601968.png)

2. Data Quality Summary for Success, Aborted, Failed shows 0

  This table contains 12 tests: 1 built from OM, 11 written in from GX
  
  Expected
  The summary above to show: Success 2; Aborted 0; Failed 9
  
  OM screenshot
  ![image](https://user-images.githubusercontent.com/121575191/234348851-d5abf92a-8bd7-4e1d-a587-e9e906a1ce28.png)

**Version:**
 - OS: linux
 - Python version: 3.10.7
 - OpenMetadata version: 0.13.3
 - OpenMetadata Ingestion package version: openmetadata-ingestion[great-expectations]==0.13.3.1

**Comment by TeddyCr** [comment]
@fionachowps Regarding the second point, the screenshot you shared shows the table-level tests. If you have column levels tests the summary of success/abort/failure will show up in the column section -- see screenshot. 

![Screenshot 2023-04-26 at 8 12 35 AM](https://user-images.githubusercontent.com/13626425/234485180-e620b79e-2e4d-4fc3-9eda-25cedb838b6f.png)

**Comment by fionachowps** [comment]
@TeddyCr Heyya - I had double checked - here's what my column profile view looks like.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/121575191/234587183-881e4984-02ce-403f-8063-1be917da7b34.png">


How is the Success; Aborted; Failed count derived? 

I thought Success would be the sum of all successful tests ran, but your screenshot only shows a count of 1 for success?

**Comment by TeddyCr** [comment]
@fionachowps it will show you the status of the last run for each column. For example, the column below has 5 tests out of which 3 failed and 2 were successful. 

![Screenshot 2023-04-27 at 8 11 50 AM](https://user-images.githubusercontent.com/13626425/234774760-7df33cba-ff64-4051-b7f9-b498c9955355.png)

Were you expecting to view it differently?

**Comment by fionachowps** [comment]
@TeddyCr  - apologies let me clarify:

1. For individual column status
Agreed - that's what I've expected from this screenshot
![image](https://user-images.githubusercontent.com/121575191/234917678-f2c8c0b7-0688-4e0a-9b4c-3af92aec4eba.png)

2. For the summary card on Column Profile, i've drawn on the screenshot what I was expecting

That the top summary stats would reflect the total successful, aborted and failed tests
![image](https://user-images.githubusercontent.com/121575191/234919056-a37efbd2-8a2f-4824-981e-b5128bd69acb.png)
