### ISSUE TITLE
Terms in descriptions for fields of struct column not searchable

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#1127]
Steps to reproduce. 
1. Visit this table in the sandbox beta: https://sandbox-beta.open-metadata.org/dataset/aws_redshift.demo.customer_order_nested_json
2. Edit the customer.name field. I added the word "oranges"
3. Search for "oranges" -- no results found.

This behavior is different than what I see for columns that are not structs. For example, adding the term, "oranges" to the description for the comments column of customer_order_nested_json does make this table findable using "oranges" as a query.

This is a bit of a blocker for me because I would like to show adding descriptions and finding tables based on those changes in the feature gif I'm trying to create for the features docs page.

**Comment by harshach** [comment]
Thanks for reporting this @shannonbradshaw
