### ISSUE TITLE
Search Indexing page takes long time to load

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#11282]
**Affected module**
UI

**Describe the bug**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/234424043-c5da5877-1903-4b35-9107-58a5b4e67d06.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Ashish8689 check this on sandbox. It takes forever to load that. We need to identify where the issue is

**Comment by Ashish8689** [comment]
@harshach  Have verified it on Sandbox and the reindex API `https://sandbox.open-metadata.org/api/v1/search/reindex/latest` is taking time to complete that's why we are seeing loading on card!

https://user-images.githubusercontent.com/66266464/234762218-68b455bd-e241-4744-b456-54794dbdb66f.mov

**Comment by harshach** [comment]
new refresh looks like fixed it. Not sure whats the root cause for it. we will re-open if it happens again
