### ISSUE TITLE
Make custom properties available across all levels of Databases

### ISSUE THREAD

**Issue by mhornst** [open-metadata/OpenMetadata#11287]
**Is your feature request related to a problem? Please describe.**
We are unable to add custom properties at the database / schema level which would come handy in many situations. We would like to add `Last reviewed date` to schema level, and `Retention period` & `environment` etc. to db level as a custom property.

**Describe the solution you'd like**
It would be great if custom properties:
1. Extended to schemas and databases as well (not only tables)
2. Had additional types e.g. date

**Describe alternatives you've considered**
Adding `Retention period`, `environment`, and `Last reviewed date` to table level, however, as most of our users are doing the tagging on the UI (and not via the API), it is not a reasonable request for them to update properties at a table level (and it does not make sense either).

**Additional context**
Adding `Last reviewed date` is connected to another ticket (#8080) I logged earlier as our use case is Data Protection-related where all users would need to periodically review metadata tagging and information in OpenMetadata.

**Comment by sureshms** [comment]
This issue covers multiple unrelated issues. Splitting them into the following tasks:

- [ ] Add support for custom properties to database and databaseSchema
- [ ] Add UI support for custom properties to database and databaseSchema
- [ ] Add additional `date` type to type system to be used for custom properites.

**Comment by mhornst** [comment]
Hi @chirag-madlani , thanks very much for the help on this! I saw the videos on the PR and they look brilliant! I have one question that's marked as done on this ticket, will we be able to set the custom property type to date as well? Thanks!
>  Add additional date type to type system to be used for custom properites.

**Comment by chirag-madlani** [comment]
Hi @mhornst 
No that's pending, we already have one more similar request [here](https://github.com/open-metadata/OpenMetadata/issues/8898)
Can you post it there we can take care of it while doing it

**Comment by mhornst** [comment]
Thanks @chirag-madlani ! I commented on that request now. :)
