### ISSUE TITLE
Error while connect SMTP-server with SMTPS Transportation Strategy

### ISSUE THREAD

**Issue by Artemnest** [open-metadata/OpenMetadata#11306]
Notifications do not work if 465/SMTPS is selected, everything is okay with 25/SMTP. The email provider supports both ports.
when i make a curl sendmail. it work with--url ‘smtps://smtp.gmail.com:465’ \ Where smTPs (not smPTs).

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/121867854/234672111-991281e3-ee59-4066-a29b-239ec35e8f8f.png">

API request confrim this typo 
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/121867854/234672408-3cb72c5b-2244-4206-a6df-ff799c4b994e.png">

 - OS: Mac
 - Python version: 3.11.3
 - OpenMetadata version: 1.0
 - OpenMetadata Ingestion package version: 1.0

**Comment by mohityadav766** [comment]
@Artemnest can you confirm that APP/Server supports SMTP over SSL?

**Comment by harshach** [comment]
@Artemnest can you please address the above question. Without that we won't be able to make progress on this ticket. thanks

**Comment by Artemnest** [comment]
It works! Thanks for the fix, closing the ticket)
