### ISSUE TITLE
Add DAG schedule_interval and last run in the DAG lineage

### ISSUE THREAD

**Issue by dafuallah96** [open-metadata/OpenMetadata#11310]
**Is your feature request related to a problem? Please describe.**
As a data analyst, it is not possible to view the DAG refresh intervals and last runs directly in the lineage. This requires navigating back and forth to the execution tab to access information on the last or successful runs. Additionally, there is no visibility into the DAG's `schedule_interval`.

**Describe the solution you'd like**
- The ingestion pipeline can be modified to capture the `schedule_interval`. This information can then be displayed on the lineage.
- The lineage can also be updated to show the details of the most recent run.

**Additional context**
- Example of how it can look like in the lineage
![image](https://user-images.githubusercontent.com/32087554/234757111-b2fbae4b-1143-4408-a8cd-59737a67d273.png)

**Comment by harshach** [comment]
@dafuallah96 we will addressing this as part of this ticket https://github.com/open-metadata/OpenMetadata/issues/11661
