### ISSUE TITLE
Include IBM dependency for i Series

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11311]
From support https://openmetadata.slack.com/archives/C02B6955S4S/p1682541086282089?thread_ts=1680811338.848789&cid=C02B6955S4S

We can include this dependency and add a new scheme in the DB2 connection https://github.com/IBM/sqlalchemy-ibmi

**Comment by dkalisch** [comment]
That's great. Let me know if we can be of any help

**Comment by nahuelverdugo** [comment]
@dkalisch This will be part of version `1.0.1` which will be released at the beginning of next week. It would be great if you can test it and let us know if it works.

**Comment by dkalisch** [comment]
DB2 for I connector unfortunately doesn't work in the current version....

**Comment by ayush-shah** [comment]
we have an open ticket for the same with more context: https://github.com/open-metadata/OpenMetadata/issues/11556

**Comment by dkalisch** [comment]
Ok. sounds good
