### ISSUE TITLE
UI not masking fields flagged as password

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11336]
![image](https://user-images.githubusercontent.com/35870520/234875907-64f6e775-c4e0-429f-ab00-ea19d512789c.png)

![image](https://user-images.githubusercontent.com/35870520/234876013-e45b5ae3-89aa-428f-9006-52be4f352460.png)

GitHub creds have the token marked as `password`, but the UI keeps it in clear text https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/security/credentials/githubCredentials.json#L23

Looks like an issue with the `oneOf` field in looker credentials https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/dashboard/lookerConnection.json#L47

**Comment by OnkarVO7** [comment]
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/28966081/235924763-c51bc051-69c1-45bf-969d-961f61d73879.png">

Passowrd fields are also not getting masked for tableau on sandbox
