### ISSUE TITLE
Databases create API documentation has no information about the valid service type

### ISSUE THREAD

**Issue by eliseealex** [open-metadata/OpenMetadata#1133]
Example of a valid request for (https://sandbox.open-metadata.org/docs#operation/create_3):
```
{
"description": "DB for test purposes",
"name": "TestDB",
"service": {
  "id": serviceId,
  "type": "databaseService"
}
```

Example of an invalid request, that seems intuitive based on API:
```
{
"description": "DB for test purposes",
"name": "TestDB",
"service": {
  "id": serviceId,
  "type": "database"
}
```

Error in case of this request:
```
'{"code":400,"message":"Invalid service type database for the database"}'
```

**Comment by sureshms** [comment]
@eliseealex, unfortunately the API documentation generated is not carrying for the documentation from schemas (we should find a way to fix this). CreateDatabase request is derived from this JSON schema:
https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/api/data/createDatabase.json

The entityReference that it uses a type to point to the database service where the database is from is derived from:
https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/type/entityReference.json

So the `type` in the entityReference should be the type of entity the `id` is pointing to. That is  `databaseService`. Perhaps we should the error message to - `serviceId` does not refer to an entity of type `database`. Wdyt?

**Comment by harshach** [comment]
@eliseealex can you give us some update on the above comment. We can update the docs accordingly. Thanks

**Comment by amiorin** [comment]
JSONSchema allows [extensions](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.5). We could create a custom field `toEntities` and customize the tool generating the API documentation.

```json
{
  "$id": "https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/api/data/createDatabase.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Create Database entity request",
  "description": "Create Database entity request",
  "type": "object",

  "properties" : {
    "name": {
      "description": "Name that identifies this database instance uniquely.",
      "$ref": "../../entity/data/database.json#/definitions/databaseName"
    },
    "description": {
      "description": "Description of the database instance. What it has and how to use it.",
      "type": "string"
    },
    "owner": {
      "description": "Owner of this database",
      "$ref": "../../type/entityReference.json",
      "toEntities": ["user", "team"]
    },
    "service" : {
      "description": "Link to the database service where this database is hosted in",
      "$ref" : "../../type/entityReference.json",
      "toEntities": ["databaseService"]
    }
  },
  "required": ["name", "service"]
}
```

**Comment by sureshms** [comment]
Changing the error returned to be more clear when service type is not correct for all the different entities as shown below:
```
Invalid service type `invalid` for database. Expected [BigQuery, MySQL, Redshift, Snowflake, Postgres, MSSQL, Oracle, Athena, Hive, Presto, Trino, Vertica, Glue, MariaDB, Druid, Db2].
```
