### ISSUE TITLE
Mutually Exclusive option for Classifications and Glossaries not displayed in UI

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#11344]
**Improvement**
When creating a Glossary or a Classification, we show the "Mutually Exclusive" toggle.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/11074908/234903429-0ee1e600-cef5-47fa-8432-035c31023050.png">

In the UI, we are not showing anywhere it has been activated, so the user does not know which of them are mutually exclusive or not. 

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/11074908/234904307-add63809-23d3-43cc-9665-6bbde66e4195.png">

**Comment by jromandv** [comment]
This information is useful at UI level when dealing with many classifications and also complex glossaries.

**Comment by sureshms** [comment]
This is fixed in 1.1
