### ISSUE TITLE
Add UI Support to Add Custom Profiler Metrics

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#11346]
**Feature**
Profiler supports the execution of custom profiler metrics using a SQL expression. We should add support to implement/add custom metrics through the UI and display these metrics.

Users will be able to add custom metrics through the `add` dropdown button on either the table or column level. `add test` will become `add` and the drop down will offer 2 choices `add [column|table] test` and `add [column|table] metric`. Clicking on either of the button will open a new page to configure either the test or the metric. The right side bar will be the same for test or metric only the config will change.

To display custom metrics we'll add 1 graph per custom metric. three dots on the right upper corner of the custom graph will allow to delete or edit the custom metric. Editing a custom metric should open a pop up and allow users to edit the configuration of the metric

**Technical Details**
For all the below endpoints `id` corresponds to the table ID

- Create or edit a Custom metric endpoint: PUT `/api/v1/tables/{id}/customMetric`. If `columnName` is omitted from the payload then the metric will be attached at the table level.

https://github.com/open-metadata/OpenMetadata/blob/c7e758eccc322e957cc4b72f119d0d27fca9e0c4/openmetadata-spec/src/main/resources/json/schema/api/tests/createCustomMetric.json#L1-L40

Delete a custom metric endpoints
- table: DELETE `/api/v1/tables//{id}/customMetric/{customMetricName}`
- column: DELETE `/api/v1/tables/{id}/customMetric/{columnName}/{customMetricName}`

Get custom metrics
GET requests against tables resources accept a `customMetrics` field in the `fields` parameter. If **only** `customMetrics` field is passed **ONLY** table custom metrics will be returned (array of custom metrics definition)

https://github.com/open-metadata/OpenMetadata/blob/c7e758eccc322e957cc4b72f119d0d27fca9e0c4/openmetadata-spec/src/main/resources/json/schema/entity/data/table.json#L1009-L1015

if `customMetrics` and `columns` fields are passed then table and column custom metrics definition will be returned

https://github.com/open-metadata/OpenMetadata/blob/c7e758eccc322e957cc4b72f119d0d27fca9e0c4/openmetadata-spec/src/main/resources/json/schema/entity/data/table.json#L318-L324

**Comment by ShaileshParmar11** [comment]
UI will be pickup once Ingestion side work is done cc @TeddyCr

**Comment by ShaileshParmar11** [comment]
This has been completed in [PR](https://github.com/open-metadata/OpenMetadata/pull/14132)
