### ISSUE TITLE
TagLabels in Tables and MlModels are stored as part of the entity

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#11342]
**Affected module**
Backend

**Describe the bug**

When we store MlModels and Tables, we keep the TagLabel object instead of a reference to it. This can cause issues when we change the TagLabel JSON schema, as in #10486. 

**To Reproduce**

1. Start OM
2. Create a Table with a DataModel containing a column with a tag.
3. Stop OM
4. Update the values of any enum in the TagLabel JSON schema.
5. Build and start OM.

An error like this appears:

![image](https://user-images.githubusercontent.com/11074908/234899576-f614a93a-5d6f-4cdc-a56e-8898f0c8d81e.png)

**Expected behavior**
It should display the table without any errors.

**Version:**
 - OpenMetadata version: 1.0.0

**Additional context**
N/A

**Comment by harshach** [comment]
cannot reproduce
