### ISSUE TITLE
Add the information about required fields for table creation to the API documentation

### ISSUE THREAD

**Issue by eliseealex** [open-metadata/OpenMetadata#1134]
`description` is required when the table is created. If the description is not specified, the web page crashes when I open a table.

`dataTypeDisplay` is required for structs and nested fields (it's not stated in the documentation).
1. Struct should have `dataTypeDisplay` with the format like (not sure about real regexp/validation): `struct<.*>`. If it's not specified, there is an error during the insert.
2. If there is no `dataTypeDisplay` for any of the inner columns of a struct, the web page crashes whenever I try to expand the struct.

I'm not sure, whether they should be required or not, maybe it's better to fix these crashes and leave them as not required in API.

**Comment by sureshms** [comment]
@eliseealex, sorry for the late reply.

`description` should not be a required fields. If the web page crashes, then it is a bug. @darth-coder00, can you confirm that UI does not make any assumptions about `description` being required.

`dataTypeDisplay` should be a required field that is used for displaying in the UI. We should not mark it as required. cc @harshach and @darth-coder00 for confirmation. @eliseealex, if you want to fix this issue, you are welcome :).
