### ISSUE TITLE
Add Lineage support for Kafka Connect

### ISSUE THREAD

**Issue by pieroTrobatty** [open-metadata/OpenMetadata#11351]
**Is your feature request related to a problem? Please describe.**
While working with Kafka Topics, we use Kafka Connect to transport data from different sources and sinks such as S3, Hive, and others.

**Describe the solution you'd like**
We would love the possibility to register our Kafka Connect processes to Open Metadata in order to show them on Lineage.
This solution would be a sort of Messaging Service lineage.

**Describe alternatives you've considered**
Metadata could be fed using an API or an ingestion pipeline

**Comment by SumanMaharana** [comment]
Ill be working on this
