### ISSUE TITLE
MSSQL RegEx not executed

### ISSUE THREAD

**Issue by dkalisch** [open-metadata/OpenMetadata#11361]
**Affected module**
Testing on Columns on MSSQL using mssql+pytds connection: Insights -> Test Cases -> columnValuesToMatchRegex

**Describe the bug**
The RegEx is not executed. The error states:
[2023-04-27 19:51:20,663] {sqa_test_suite_interface.py:179} ERROR - Error executing columnValuesToMatchRegex - mssql dialect does not support regular expressions.

The database can, however, execute the following command correctly:

`SELECT * FROM tablename
WHERE field LIKE '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]';`

**To Reproduce**
Set up MSSQL Database with sample data. Create test case columnValuesToMatchRegex with RegEx value [0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9] ('[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]' will also not work)

**Expected behavior**
A correct executed SQL statement

**Version:**
 - DockerSetup
 - OpenMetadata version: 1.0.0
 - OpenMetadata Ingestion package version: 1.0.0

**Comment by TeddyCr** [comment]
Hey @dkalisch thank you for reporting this. We opened a PR [here](https://github.com/open-metadata/OpenMetadata/pull/11366/files) that will be part of the patch release. 

It looks like MSSQL dialect trow a generic SQA error (we are looking at compilation error to fall back to the like method for dialect that have not implemented the logic for regex).
