### ISSUE TITLE
Activity feeds are not recorded for actions against creation of sub-terms in glossary

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#11368]
**Affected module**
UI

**Describe the bug**
Activity feeds should show all the creation, maintenance,  deletion activities in OpenMetadata as performed by the user in the UI.

In the below user case, DG policy term was created , along with a few subterms. 

Only creation of parent term is visible. Creation of sub-terms is not appearing in the activity feed.
Later, the desc of one of the sub-term was edited and same is appearing in the activity feed i.e. apparently maintenance activity is recorded but not the creation of sub-terms.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/110607559/235370127-19c26c3c-b914-48a3-b862-8ddd4274a390.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/110607559/235370139-8f610f10-4640-410a-950c-c7a768e52d6b.png">

use case 2: Policy is created, but same is not appearing in activity feed.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/110607559/235370295-1eaea505-100f-4f2a-b315-5a8ae01e0f04.png">

**
<img width="666" alt="image" src="https://user-images.githubusercontent.com/110607559/235370337-ed5ac84a-b8c1-494f-aa55-2af854fcc78a.png">

use case 3 : role updation against user is not being captured in activity feed.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/110607559/235370385-a9444e18-d627-4f02-a19c-26410b901dfe.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/110607559/235370402-e566f698-035b-43b9-8066-3d6c1c9acc43.png">

**
version 
13.3

**Comment by harshach** [comment]
@lailapatel this is intentional, policy action should be minimal and only limited to admins. Activity feed goal is to show the changes that entity is going through and facilitate collaboration among data consumers/producers. Policies and Roles should be rarely changing , even if they change its admin only operation there isn't any benefit or collaboration aspects to policies & roles.

Do you mind explaining how are you using activity feed and why you would like to see roles and policies changes in activity feed.

**Comment by lailapatel** [comment]
yes, policy and role actions were performed by Admin User only in the above case. We were considering the activity feed for  Audit log purpose. However, if the purpose is only collaboration then its okay to leave this.

then this is only required for the glossary part.

**Comment by harshach** [comment]
@mohityadav766 glossary term addition works but deletion is not showing up
