### ISSUE TITLE
Improve suggestions for explore quick dropdown filters

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#11375]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI, backend

**Describe the bug**

- [ ] Use only aggregate API for showing the suggestion options for explore page quick dropdown filters. ( Currently, 2 APIs are being used for fetching the options, `Aggregates` API for getting options without any search text and `Suggest` API for with search text)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by aniketkatkar97** [comment]
Blocked due to test failing because of elastic search indexing issue for 
1. `Schema Fields` in topics
2. `Data Models` in dashboards
3. `columns` in containers
cc. @mohityadav766

**Comment by aniketkatkar97** [comment]
@harshach, With the `Aggregate API approach, there will be a limitation on the number of results we show. We need to think of a better way here.

**Comment by harshach** [comment]
I believe this is fixed by @karanh37 @07Himank , re-open if necessary

**Comment by aniketkatkar97** [comment]
hey @sapirhi, that will be resolved in our next patch release

**Comment by 07Himank** [comment]
> I believe this is fixed by @karanh37 @07Himank , re-open if necessary

Yes, its fixed
