### ISSUE TITLE
Add support for metadata change events and APIs

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1138]
# Eventing
State of metadata in OpenMetadata changes due to user activity, such as updating the description of a dataset, changing ownership, or adding new tags. Metadata also changes due to activities at the metadata sources, such as a new dataset was created, a dataset was deleted, or the schema of a dataset is modified, which is ingested using Ingestion bot. When the state of metadata changes, an event is produced. These events can be used to build apps and bots that respond to the change from activities. 

An event must provide the following information in order write bots/applications around it:

1. The entity that changed
2. Type of change - a new entity is created, an entity is deleted, or an entity is modified.
3. User/bot that made the change.
4. Activity that caused the change as a result of API operation on an entity.
5. The time when the change occurred
6. Value of entity before and after the change. A way to easily determine the fields of the entity (attributes and relationships) that changed.

Changes/operations can be categorized into two broad categories:

- **Operations that change the version of an entity** - Some API operations change the metadata version of an entity, such as updating an entity description, adding new tags to an entity, some changes as a schema for a table was updated or a query was updated for a report, etc.
- **Operations that don’t change the version of an entity** - Some API operations change the metadata associated with an entity that are not core attributes of an entity. Such changes do not result in a version change, such as an entity was followed/unfollowed, usage details or data profiler information for an entity is updated.

Additionally, a change event might apply to a single entity, such as description of a table changed or multiple entities, such as a user followed a table, where the event is attributed to two entities - table and user. 

## AuditLog vs. Change Events
AuditLog logs the details of an operation - what operation was performed, who performed it, when was it performed, what was the result of an operation (success or failure). Audit logs capture operations, whether they resulted in a change or not. Audit logs also capture other operations, such as user logged in and logged out that are relevant for auditing.

Change events are the result of successful operation and do not track failed operations as they don’t result in any change. Even a successful operation that did not result in a change is not relevant for change events. For example a PUT operation that made no change is still relevant to AuditLog but may not result in any change events).

## Change event schema
Eventing functionality is heavily based on the entity versioning work that was done earlier in #736. Changes made to an entity during PUT, PATCH are captured as `changeDescription` from [entityHistory.json](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/type/entityHistory.json).

Following changes will be captured:
All events will include the following common information - user who made the change, entity type (table, dashboard etc.), entityId (UUID of the entity), current version of the entity after the change, pervious version of the entity before the change, and change details.

- **entityCreated** - this event includes the entity that was created in the event itself. This can be used by applications getting the events to initialize the state about an entity from the change event itself.
- **entityUpdated** - these events captures details of what fields were added and the new value of the field, what fields were updated with old and new value of the field, and finally what fields were deleted and old value of the field.
- **entityDeleted** - this event just informations the the entity is deleted (with all the common event details).

changeEvent schema is as follows:
```
{
  "$id": "https://open-metadata.org/schema/type/auditLog.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ChangeEvent",
  "description": "This schema defines the change event type to capture the changes to entities. Entities change due to user activity, such as updating description of a dataset, changing ownership, or adding new tags. Entity also changes due to activities at the metadata sources, such as a new dataset was created, a datasets was deleted, or schema of a dataset is modified. When state of entity changes, an event is produced. These events can be used to build apps and bots that respond to the change from activities.",
  "type": "object",
  "javaType": "org.openmetadata.catalog.type.ChangeEvent",

  "definitions": {
    "eventType" :{
      "javaType": "org.openmetadata.catalog.type.EventType",
      "description": "Type of event",
      "type": "string",
      "enum": [
        "entityCreated",
        "entityUpdated",
        "entityDeleted"
      ]
    },
    "eventFilter": {
      "type": "object",
      "javaType": "org.openmetadata.catalog.type.EventFilter",
      "properties": {
        "eventType": {
          "description": "Event type that is being requested.",
          "$ref": "#/definitions/eventType"
        },
        "entities": {
          "description": "Entities for which the events are needed. Example - `table`, `topic`, etc. **When not set, events for all the entities will be provided.**",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["eventType"]
    }
  },
  "properties" : {
    "eventType" : {
      "$ref": "#/definitions/eventType"
    },
    "entityType" : {
      "description": "Entity type that changed. Use the schema of this entity to process the entity attribute.",
      "type": "string"
    },
    "entityId": {
      "description": "Identifier of entity that was modified by the operation.",
      "$ref": "basic.json#/definitions/uuid"
    },
    "previousVersion" : {
      "description" : "Version of the entity before this change. Note that not all changes result in entity version change. When entity version is not changed, `previousVersion` is same as `currentVersion`",
      "$ref" : "entityHistory.json#/definitions/entityVersion"
    },
    "currentVersion" : {
      "description" : "Current version of the entity after this change. Note that not all changes result in entity version change. When entity version is not changed, `previousVersion` is same as `currentVersion`",
      "$ref" : "entityHistory.json#/definitions/entityVersion"
    },
    "userName": {
      "description": "Name of the user whose activity resulted in the change.",
      "type": "string"
    },
    "dateTime": {
      "description": "Date and time when the change was made.",
      "$ref": "basic.json#/definitions/dateTime"
    },
    "changeDescription" : {
      "description": "For `eventType` `entityUpdated` this field captures details about what fields were added/updated/deleted. For `eventType` `entityCreated` or `entityDeleted` this field is null.",
      "$ref" : "entityHistory.json#/definitions/changeDescription"
    },
    "entity" : {
      "description": "For `eventType` `entityCreated`, this field captures JSON coded string of the entity using the schema corresponding to `entityType`"
    }
  },
  "required": ["eventType", "entityType", "entityId", "dateTime"],
  "additionalProperties": false
}
```
## Generating change events

1. POST API requests - POST requests create an entity.  The `entityCreated` event is generated with entity JSON as the payload.
2. PUT API requests - PUT requests can create an entity when it does not exists or update an existing entity. When entity is created, `entityCreated` event is generated as done in POST. When an entity is updated, `entityUpdated` event is generated with `changeDescription` that includes field change information.
3. PATCH API requests - PATCH updates an existing entity. As with PUT requests during updated, `entityUpdated` event is generated during PATCH.
4. DELETE API requests - DELETE deletes an entity. The event `entityDeleted` is generated that identify entityType, and entityID, and entityVersion.

## Storing change events
Change events are stored so that other applications can **pull** the change events to get the changes and react to them. They events are stored in the following table:
```
CREATE TABLE IF NOT EXISTS change_event (
    eventType VARCHAR(36) GENERATED ALWAYS AS (json ->> '$.eventType') NOT NULL,
    entityType VARCHAR(36) GENERATED ALWAYS AS (json ->> '$.entityType') NOT NULL,
    userName VARCHAR(256) GENERATED ALWAYS AS (json ->> '$.userName') NOT NULL,
    dateTime TIMESTAMP GENERATED ALWAYS AS (TIMESTAMP(STR_TO_DATE(json ->> '$.dateTime', '%Y-%m-%dT%T.%fZ'))) NOT NULL,
    json JSON NOT NULL,
    INDEX (dateTime),
    INDEX (eventType),
    INDEX (entityType)
);
```

## APIs are change events
Following API is supported for pulling change events:
```
GET .../events?entityCreated=<entities>&entitiesModified=<entities>&entitiesDeleted=<entities>&date=<eventTime to get change events since>
```
An application can use the above API to get specific eventTypes for the entities they are interested in and catch up by pulling the events since they left off.

## Future work

1. Add support for push based events where an application can register a webhook using `event subscription` api to be notified of change events.
2. Use change events to create notification and alerts to the users using `feeds` API.
3. Add support for Kafka sink for change events for deployments that need such a setup.

**Comment by sureshms** [comment]
Issue breakdown:

**Comment by mithmatt** [comment]
```
GET .../events?entityCreated=<entities>&entitiesModified=<entities>&entitiesDeleted=<entities>&date=<eventTime to get change events since>
```

Would it be better to support `fromTimestamp` and `toTimestamp` (instead of since `date`), with `toTimestamp` being optional?

**Comment by sureshms** [comment]
Marking this issue as closed
