### ISSUE TITLE
Lineage of BQ tables is not visible

### ISSUE THREAD

**Issue by raghav-khatoria-5000254** [open-metadata/OpenMetadata#11398]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
The lineage of tables is not visible

**To Reproduce**

Screenshots or steps to reproduce
SQL Query for creating table:
CREATE TABLE `open_metadata.Demo Table 1`AS
SELECT o.order_id, o.order_date, o.customer_id, c.first_name, c.email, c.phone,
      o.product_name, o.product_price, o.quantity
FROM `open_metadata.Demo Table 2` o
INNER JOIN `open_metadata.Demo Table 3` c ON o.customer_id = c.customer_id;

**Expected behavior**
Able to see from where we are getting the data

**Version:**
 - OS: MacOS
 - Python version:  3.9.13
 - OpenMetadata version: 13.3
 - OpenMetadata Ingestion package version: 1.0.0.1
**Additional context**

**Comment by DovileKr** [comment]
Same noted on my side as well.

**Comment by ulixius9** [comment]
Hey @DovileKr & @raghav-khatoria-5000254, with OpenMetadata version 1.1.0 we have made a lot of improvements with lineage, I tested it with the latest version and I was able to get the lineage out of same query available in the ticket. Please re-open the if you are still facing the same issue with some more context.
