### ISSUE TITLE
docs header link doesn't go to the exact header content

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#11393]
**Affected module**
Docs

**Describe the bug**
We allow users to copy specific section in the docs page but the link doesn't take us to the exact content in the page . Example
https://docs.open-metadata.org/v1.0.0/connectors/database/snowflake/cli#1.-define-the-yaml-config

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by aniketkatkar97** [comment]
Re-opening the ticket as the issue has arrived again due to some changes in other PRs
