### ISSUE TITLE
hasAny*** condition error

### ISSUE THREAD

**Issue by LeeHomeen** [open-metadata/OpenMetadata#11397]
**Affected module**
Policies setting

**Describe the bug**
Error occurred when creating hasanyrole, hasanyteam of Condition

**To Reproduce**

![image](https://user-images.githubusercontent.com/124124085/235821482-5effb848-fd39-4a87-b906-be18d06d17e2.png)

**Expected behavior**
normal operation of condition

**Version:**
 - OS: Windows 11
 - Python version: - 
 - OpenMetadata version: 1.0.0
 - OpenMetadata Ingestion package version: -just wep console-

**Additional context**
none

**Comment by ShaileshParmar11** [comment]
Hello @harshach @sureshms, I have checked from UI side we are just making an API request, it seems like a backend issue to me.
