### ISSUE TITLE
Feat: add update displayName support for all entity

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#11399]
Currently, we do not have support to add/update display name of any entity. we should add the support for the same.

**Comment by harshach** [comment]
@ShaileshParmar11 this should only be adding or editing display name

**Comment by ShaileshParmar11** [comment]
Thanks @harshach for confirming!

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=19271%3A22329&t=pi28c4n2gUgXJems-1

**Comment by ShaileshParmar11** [comment]
![Image](https://github.com/open-metadata/OpenMetadata/assets/71748675/c974744d-a5e6-4abf-bac7-ee3e39a58669)

need to take care of the above bug with this ticket, one should be name and another should be displayname, currently we are showing both as displayName

**Comment by ShaileshParmar11** [comment]
List of component where we need to provide edit/update displayName

- [ ] Service ?
- [ ] database details page
- [ ] schema details page
- [ ] Table details page
- [ ] Topic details page
- [ ] dashboard details page
- [ ] pipeline details page
- [ ] mlmoadel details page
- [ ] container details page

**Comment by ShaileshParmar11** [comment]
organize the menu items at all placeses

1. Announcements
2. Rename
4. Delete
