### ISSUE TITLE
UI Improvements 1.0.1

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#11407]
- [x] fields are overlapping  -> @Ashish8689 
- [x] After saving, While loading we show "Add New" placeholder, maybe we should show simple skeleton loader 

https://user-images.githubusercontent.com/103238069/235849253-0a695bb3-9065-4ca2-8c9b-a636f17bc163.mov

- [x]  Tags are misaligned  -> @Ashish8689 
<img width="193" alt="Screenshot 2023-05-03 at 4 59 24 PM" src="https://user-images.githubusercontent.com/103238069/235903879-87176ba9-d4cc-4d7e-8c3d-d2bb0f82cefc.png">

- [ ] icons are moving to 3rd line
<img width="224" alt="Screenshot 2023-05-03 at 5 02 43 PM" src="https://user-images.githubusercontent.com/103238069/235904581-1eb31e8c-0068-4bae-b7b1-d89c51081051.png">

- [x] Icon collars are not right -> @Ashish8689 
<img width="705" alt="Screenshot 2023-05-03 at 5 09 59 PM" src="https://user-images.githubusercontent.com/103238069/235905954-b6e223db-958b-4e20-9858-d430c3925335.png">
<img width="352" alt="Screenshot 2023-05-03 at 5 10 34 PM" src="https://user-images.githubusercontent.com/103238069/235906036-4b44d07f-15c1-4043-b347-65ebd9b320a7.png">

- [x] inconsistent icon color -> @Ashish8689 
<img width="237" alt="Screenshot 2023-05-03 at 5 31 11 PM" src="https://user-images.githubusercontent.com/103238069/235910078-e3cdf3d7-49a4-4620-bbcf-d64309f0b501.png">

- [x] can we update the top padding to following ( div class="h-full flex-center mt-8" data-testid="search-error-placeholder" ) -> @Ashish8689 
- [x] Illustration size to 86px -> @Ashish8689 
<img width="1252" alt="Screenshot 2023-05-03 at 5 47 36 PM" src="https://user-images.githubusercontent.com/103238069/235913225-7696e5e3-fcf7-41b6-95ea-9b118ae90c3f.png">

- [x] Remove the card  -> @Ashish8689 
<img width="1440" alt="Screenshot 2023-05-03 at 5 57 04 PM" src="https://user-images.githubusercontent.com/103238069/235915285-3471c0c6-cb41-4fb0-860d-3694ceca1385.png">

- [x] Table border is missing -> @Ashish8689 
- [x] Below tab background is inconsistent with entity page
<img width="1440" alt="Screenshot 2023-05-03 at 6 16 21 PM" src="https://user-images.githubusercontent.com/103238069/235920017-ed636ef6-7898-4215-89a2-544ed4a57190.png">

- [x] Right panel title alignment is not right.  -> @Ashish8689 
<img width="1149" alt="Screenshot 2023-05-03 at 6 23 58 PM" src="https://user-images.githubusercontent.com/103238069/235921847-046b5e77-4201-4701-8068-b4e50bef33bf.png">

- [x] wrong user/team count -> https://github.com/open-metadata/OpenMetadata/pull/11482
<img width="449" alt="Screenshot 2023-05-04 at 10 37 53 AM" src="https://user-images.githubusercontent.com/103238069/236116752-782780a9-4d4a-415a-8b9c-b5872a5b2f98.png">

- [x] Border in mai card is missing - @ShaileshParmar11 -> https://github.com/open-metadata/OpenMetadata/pull/11452
- [x] Remove the store outside "Edit tier" please refer the styling from  - @ShaileshParmar11 -> https://github.com/open-metadata/OpenMetadata/pull/11452 https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=10679%3A10799&t=CWQB0AyslGyQBFnX-1

<img width="805" alt="Screenshot 2023-05-04 at 10 40 03 AM" src="https://user-images.githubusercontent.com/103238069/236117024-afe29897-7ea5-4bed-9085-68838a073e11.png"> - @ShaileshParmar11  -> https://github.com/open-metadata/OpenMetadata/pull/11452

- [x] Here the icon isn't collapsing the tier (this UX makes it look like a bug), make it collapsable - @ShaileshParmar11 -> https://github.com/open-metadata/OpenMetadata/pull/11452
<img width="150" alt="Screenshot 2023-05-04 at 10 46 41 AM" src="https://user-images.githubusercontent.com/103238069/236117734-fd3d8bca-1e73-456c-81d0-05024cf39885.png">

- [x] Table content needs to be top aligned. - @ShaileshParmar11 -> https://github.com/open-metadata/OpenMetadata/pull/11452
<img width="1392" alt="Screenshot 2023-05-04 at 4 16 53 PM" src="https://user-images.githubusercontent.com/103238069/236182840-87b45479-dd1c-408b-9b2b-39382c81cf44.png">

**Comment by harshach** [comment]
- [ ] on the side panel for Glossaries we should show the display name 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/38649/236104891-7e5fc01d-d7aa-43f6-8a09-824ea1f2d094.png">

**Comment by aniketkatkar97** [comment]
- [ ] Redirection links in the breadcrumb are incorrect

https://user-images.githubusercontent.com/51777795/236148003-55886f3f-79f5-4663-b09a-4c0a79fe3659.mov

**Comment by aniketkatkar97** [comment]
- [ ] Pagination is missing in the `Data Model` tab in the `Dashboard Service` details page
<img width="1439" alt="Screenshot 2023-05-04 at 1 48 27 PM" src="https://user-images.githubusercontent.com/51777795/236148916-9d5b4cb7-8d7d-4485-839d-36e9ec3bab14.png">

**Comment by harshach** [comment]
- [ ] this field should use the same type of owner field where we show users and teams separately. Here we are putting them together 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/38649/236557262-264f8d4f-20f9-404f-a564-3ec826884180.png">

**Comment by harshach** [comment]
- [ ] same here typing @ should open the same panel as entity owner panel
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/38649/236557802-cfadd1c7-85df-4f8c-ae0c-9cb59e76833f.png">

**Comment by ShaileshParmar11** [comment]
move pending issue here -> https://github.com/open-metadata/OpenMetadata/issues/11154#issuecomment-1539410669
