### ISSUE TITLE
backend: not getting Edit operation details for testSuite

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#11404]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Not getting edit operation details from permission 

**To Reproduce**

Screenshots or steps to reproduce
path:  https://sandbox-beta.open-metadata.org/test-suites/critical_metrics_suite
API: https://sandbox-beta.open-metadata.org/api/v1/permissions/testSuite/name/critical_metrics_suite
Response: 
```
{"resource":"testSuite","permissions":[{"operation":"Create","access":"allow"},{"operation":"Delete","access":"allow"},{"operation":"ViewAll","access":"allow"}]}
```

**Expected behavior**
We should get information for editOwner, editDescription & editAll.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Ok, earlier we decided to allow only admin to edit the test suite! if we want to continue with the same we can close this.

**Comment by sureshms** [comment]
@ShaileshParmar11 per our discussion yesterday, we should depend on only permissions and not have a separate check for admin.
