### ISSUE TITLE
UI Lineage: Add via search not working

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#11412]
**Affected module**
UI, Lineage

**Describe the bug**
I want to add a new table to the lineage using visual UI. I have a table called **_someting_loyalty_something_**.
I enter loyalty in the search bar and nothing.

**To Reproduce**
![image](https://user-images.githubusercontent.com/26750060/235926518-652d4060-1dab-43cd-a0eb-c6237cec8c9a.png)
![image](https://user-images.githubusercontent.com/26750060/235927365-f39d2566-2a57-47f1-af40-3dd99b3a0de6.png)

Screenshots or steps to reproduce
Example I can see "loyalty" table, but if I type loyalty - I get nothing.

**Expected behavior**
Working Search

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 1.0]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@karanh37 lets use search api here instead of suggest.
