### ISSUE TITLE
[Serach Indexing] Allow app to have cleanup option for orphaned/ irrelevant entities.

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#11416]
**Is your feature request related to a problem? Please describe.**
A Database may run into inconsistent state , where we can have missing relationship, we should have be able to cleanup those using the search indexing app , especially the databaseService -> database -> databaseSchema -> table 
- We can also add that in bootstrap via searchindxing 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 lets ship this as another option in tablesInitializer
