### ISSUE TITLE
Impala connection missing from https://docs.open-metadata.org/v1.0.0/connectors page

### ISSUE THREAD

**Issue by ksirmons** [open-metadata/OpenMetadata#11417]
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.
Impala connection missing from https://docs.open-metadata.org/v1.0.0/connectors page

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

**Comment by pmbrull** [comment]
this has been added, thanks for reporting
