### ISSUE TITLE
DataLake - Support Manifest file similar to Storage Connectors

### ISSUE THREAD

**Issue by dkalisch** [open-metadata/OpenMetadata#11421]
**Is your feature request related to a problem? Please describe.**
When setting up ingestion in OM for AWS datalake, the ingestion jobs don't function as expected. The problem is that glue does not write file extensions to the files saved in S3, so that the ingestion job states:
`[2023-05-03 17:02:05,258] {metadata.py:366} DEBUG - Object filtered due to unsupported file type: run-1679417237460-part-r-00000`
on each job and therefor does not ingest metadata or profiling data into OM

**Describe the solution you'd like**
Add fields to the ingestion forms stating wich file format the bucket holds etc. and ingest the bucket data accordingly.

**Describe alternatives you've considered**
Renaming the files does not work due to workload, doubling the storage space and inferring with spark. The proposed solution in slack using a manifest.json to define the metadata in the S3 bucket is also not optimal, since this will infer with the spark behavior that the AWS datalake runs on.

**Comment by pmbrull** [comment]
hi @dkalisch , thanks for reaching out. Thinking out loud if using Storage Services for these cases might be helpful: https://docs.open-metadata.org/v1.0.0/connectors/storage.

For the Datalake connector, we rely directly on the data files we find on the bucket. Also, not sure how safe of an assumption can be to have a single "default" format for files without extension. Would that format always be the same in the buckets being ingested?

In this case where specific formats/business logic might come in re your bucket structure, the Storage Service with the manifest definition might help state how to get the metadata out

**Comment by dkalisch** [comment]
@pmbrull The problem is, that Glue jobs write data into the s3 buckets and they don't have a file extension and no way to add one... This leads to the problem, that OM can't ingest the data since there is no file extension...
