### ISSUE TITLE
 Explore UI - Incorrect url

### ISSUE THREAD

**Issue by min772a** [open-metadata/OpenMetadata#11431]
**Affected module**
UI

**Describe the bug**
When I click Explore -> Topics or Dashboards or Pipelines -> result title,
URL is incorrect.

**To Reproduce**

Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/115981844/236181918-d189c177-4fe4-4d19-ac67-dbf78d2a92f9.png)

**Expected behavior**
URL is should be correct URL

not messagingService, messagingServices is correct. s is missing.
(dashboardService, pipelineService is same problems. But Tables url is correct.)

**Version:**
 - Python version:
 - OpenMetadata version: 1.0.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by aniketkatkar97** [comment]
Duplicate issue, already being tracked [here](https://github.com/open-metadata/OpenMetadata/issues/11407#issuecomment-1534273840)
