### ISSUE TITLE
Data profiler - row count of sample data

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#11430]
**Affected module**
UI

**Describe the bug**
When looking on the rows number, it show how much rows are injected to the sample, but it very misleading to the user that think it's the amount of rows in the table.

**To Reproduce**

<img width="828" alt="image" src="https://user-images.githubusercontent.com/87426120/236179524-e428c501-c9e5-4a81-bd68-574d17230787.png">

**Expected behavior**
The rows amount should be the total rows in the table 

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
Hey @sapirhi. Thank you for reporting this. We have this ticket open [here](https://github.com/open-metadata/OpenMetadata/issues/4565) you can follow. I'll be closing this one as duplicate. 🙂
