### ISSUE TITLE
Document how to use SAML in Docker deployment

### ISSUE THREAD

**Issue by uhcl-lund** [open-metadata/OpenMetadata#11445]
**Is some content missing, wrong, or not clear?**
Current documentation shows how to edit a config file to implement SAML.  Please provide instructions on doing the same for the Docker deployment

**Describe the solution you'd like**
How to implement in Docker deployment without extending the container.

**Additional context**
Good documentation otherwise.

**Comment by harshach** [comment]
@mohityadav766 @akash-jain-10 lets add the DOCKER, Baremetal, K8s section for SAML docs like other SSOs https://docs.open-metadata.org/v1.1.0/deployment/security/saml

**Comment by harshach** [comment]
@Prajwal214 can you take this up and work with @mohityadav766 to document it
