### ISSUE TITLE
Add webhook based API for receiving events

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1145]
### API
A new entity called **webhook** will be added to the system to track webhook-based subscriptions for events.

Following APIs will be provided related to webhook:
`POST .../webhook` to create a webhook subscription
`PUT .../webhook` to update a webhook subscription
`GET .../webhook` to list all the webhook subscriptions
`GET .../webhook/{id}` to get a specific webhook subscription
`DELETE .../webhook/{id}` to delete a webhook subscription

### Webhook
Webhook schema is as shown below (versioning, change descriptions are excluded in the schema below):
```
{
  "$id": "https://open-metadata.org/schema/type/webhook.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ChangeEvent",
  "description": "This schema defines webhook for receiving events from OpenMetadata",
  "type": "object",
  "javaType": "org.openmetadata.catalog.type.Webhook",
  "properties": {
    "id": {
      "description": "Unique ID associated with a webhook subscription.",
      "$ref": "../../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Unique name of the application receiving webhook events.",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "description": {
      "description": "Description of the application",
      "type": "string"
    },
    "endPoint": {
      "description": "Endpoint to receive the webhook events over POST requests.",
      "type": "string",
      "format": "uri"
    },
    "eventFilters": {
      "description": "Endpoint to receive the webhook events over POST requests.",
      "type": "array",
      "items": {
        "$ref": "../../type/changeEvent.json#/definitions/eventFilter"
      }
    },
    "batchSize": {
      "description": "Maximum number of events sent in a batch (Default 10).",
      "type": "integer",
      "default": 10
    },
    "timeout": {
      "description": "Connection timeout in seconds. (Default 10s)",
      "type": "integer",
      "default": 10
    },
    "enabled": {
      "description": "When set to `true`, the webhook event notification is enabled. Set it to `false` to disable the subscription. (Default `true`)",
      "type": "boolean",
      "default": true
    }
}
```

An application created a webhook subscription and receives events that match `eventFilters` at the `endPoint` over POST requests.

### Error handling
OpenMetadata server sends events to the `endPoint` registered by an application and handles the errors as follows:
1. If the `endPoint` URL is malformed or not reachable because of unknown host, the webhook subscription is marked as in `error` and no further attempts are made to deliver events.
2. If the `endPoint` returns `3xx` response, since webhook does not accept redirection, the webhook subscription is marked as in `error` and no further attempts are made to deliver events.
3. If the `endPoint` returns `4xx`, `5xx`, or fails to respond, the webhook moves to `awaitingRetry` state and retries delivering events with the following backoff - 3 seconds, 30 seconds, 5 minutes, 1 hour, and 24 hours. If no response was received, the endpoint is marked as `retryLimitReached` and no further attempts are made to deliver events.

Webhook subscription can be reenabled by fixing `endPoint` URL or by reenabling the webhook using PUT request.

### Internal mechanism
We will use[ LMAX Disruptor](https://lmax-exchange.github.io/disruptor/) Concurrency framework to manage subscription and deliver events as shown below:
![image](https://user-images.githubusercontent.com/1417689/147272306-3172e445-02d0-4813-91b6-c5aadd5ec46a.png)

Publishers publish change events to a `ringbuffer`. Consumers are registered as `EventHandlers` and are reading the change events from the ringbuffer. `WebhookPublisher` is an event handler that reads from ringbuffer and publishes the event to webhook endpoint over `POST` request. `ElasticSearch` event handler reads the change events from ringbuffer and updates the ElasticSearch index. Many other types of event handlers can be added to this framework in the future.

LMAX Disruptor provides several advantages:
1. Allows multiple publisher threads and consumer threads to concurrently work on a single copy of change events in the Distruptor ring buffer.
2. Different webhook publishers can work independently of each other and can work at different speeds, given the webhook endpoints are going to have different response times and failure characteristics.
3. Adding and removing webhooks in a running a system is super simple using Distruptor without disrupting the existing publishers and event handler.

WIP

**Comment by sureshms** [comment]
@avignd please take look

**Comment by pulkitbhanot** [comment]
@sureshms I have started looking into this. Can you please assign me this to me.

**Comment by avignd** [comment]
thanks @sureshms

**Comment by sureshms** [comment]
I am assigning it both @avignd and @pulkitbhanot   you guys can collaborate together on this work. Thank you both.

**Comment by amiorin** [comment]
I was thinking that this article could be useful.
[Using SKIP LOCK For Queue Processing in MySQL
](https://www.percona.com/blog/2020/08/03/using-skip-lock-for-queue-processing-in-mysql/)

**Comment by avignd** [comment]
@pulkitbhanot let's chat

**Comment by sureshms** [comment]
Task breakdown:
- [] #1900

**Comment by sureshms** [comment]
@avignd and @pulkitbhanot, please take a look.

**Comment by sureshms** [comment]
@darth-coder00, can you please add links to webhook UI work as a task to this issue?

**Comment by sureshms** [comment]
Marking this issue as closed
