### ISSUE TITLE
Sample Data change UX for horizontal scrolling (and vertical)

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#11490]
**Is your feature request related to a problem? Please describe.**
I have a table with 142 columns. However there are no vertical or horizontal scrolls bars. For vertical scrolling I can use the mouse, but for the horizontal scrolling - I have to use the mouse pad and two touch points or arrows on my keyboard.
I have tested it withy couple users and none of them realized that they should do a horizontal scrolling. The arrows right ONLY appears after using left arrow or mouse pad.

![image](https://user-images.githubusercontent.com/26750060/236867114-77fcf3c9-7ef9-44cd-913d-ed2b0d975686.png)

**Describe the solution you'd like**
A horizontal scroll pad on screen (rather than having to use the mouse pad or arrows).
like 
![image](https://user-images.githubusercontent.com/26750060/236867052-d6968dc0-ece5-4f61-9767-6fca1898ee0b.png)

**Describe alternatives you've considered**
teaching users that there is possibility to scroll, but I can't teach every user,..

**Additional context**
1.0. UI, Sample Data

**Comment by Ashish8689** [comment]
#harsha will be picking this one once finished with the separate column issue!

**Comment by DovileKr** [comment]
@Ashish8689  hello, was this addressed in 1.0.2 still same inconvenience with Horizontal Scrolling:

https://sandbox.open-metadata.org/table/sample_data.ecommerce_db.shopify.dim_customer/sample_data.

try scrolling horizontally, so seeing all 29 columns just using a standard mouse.

**Comment by chirag-madlani** [comment]
@DovileKr You can use the `shift` key with Mouse to perform a horizontal scroll, Don't need a mouse pad or arrow keys, Give it a try and let me know if that's works
