### ISSUE TITLE
Azure blob storage connection

### ISSUE THREAD

**Issue by LPontes** [open-metadata/OpenMetadata#11494]
I'm looking to implement openmetadata in the company where I work, but we use azure's data lake gen 2.
I would like to see Azure blob storage connector implelmented on OM.
Meanwhile I'm trying to use Databricks connector however It relies on a dedicated cluster

**Comment by tomtom215** [comment]
We'd love this as well as we are only using Azure Blob and Azure File without the option of using S3 or MinIO

**Comment by pmbrull** [comment]
hi @LPontes, @tomtom215, you should be able to already use the Datalake connector [docs](https://docs.open-metadata.org/v1.1.0/connectors/database/datalake) to ingest individual files as tables from ADLS.

We'll use this ticket to implement ADLS as a Storage Service [docs](https://docs.open-metadata.org/v1.1.0/connectors/storage)

Thanks
