### ISSUE TITLE
Search engine doesn't work correctly for some cases

### ISSUE THREAD

**Issue by kirillbartosh** [open-metadata/OpenMetadata#11517]
It impacts UI search bar of OpenMetadata released version 1.0.0

It reproduces while searching on keywords with "-" symbol. The system trim only first part of the request which cause significally more results of search. Example : when i try to search text "CR-11662" the system trims "-11662" and output all results which start from "CR"

**Expected behavior**
I expect that system filters values on my exact input and not to return similar values (eg. on the screenshot wrong value CR-13794)

**Version:**
 - OS: windows 10
 - Python version: NA
 - OpenMetadata version: 1.0.0
 - OpenMetadata Ingestion package version: NA

**Additional context**
![scr2023-05-09 124219](https://github.com/open-metadata/OpenMetadata/assets/26789033/6b8ffdf4-e98f-4af9-a94a-1785864590bb)

**Comment by kirillbartosh** [comment]
The problem here is not in the yellow highlighter of the results. But in the relevancy of the results. As you can see there are no matches on the first page with my key word "CR-11662" and there is 18 pages which i should review to distinct all matches which I need. 
![image](https://github.com/open-metadata/OpenMetadata/assets/26789033/78efb976-2e96-4ee4-bf02-2385978068d1)

**Comment by harshach** [comment]
This is fixed in main and will be part of 1.2
