### ISSUE TITLE
Search lineage Using Column of the table

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#11515]
Problem:
As a user of data lineage, the user would like to see lineage specific to one particular column of the table. The problem is that tracing a single column (upstream or downstream) is very difficult especially if the lineage is complex.

Solution:
Provide filter with columns at lineage diagram. The expectation from a user is to select a column of a table from the filter (same as the table filter) at the lineage diagram and see only related tables/columns which are part of the lineage for the column. This can help the user to see only relevant lineage (related to the column), which can help in understanding the dependency  (upstream or downstream) for the column.

Slack discussion link:
https://openmetadata.slack.com/archives/C02B6955S4S/p1684313995693519

here is a snapshot of **column as filter** at lineage diagram
![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/56bcf1a7-558d-4769-b414-2a36e873d3e3)

**Comment by heroWang** [comment]
Basically same as what I thought. However, like the dbt documentation service, we can give more choices to users. For example: upstream or downstream. Limiting tags, schema, etc.
![image](https://github.com/open-metadata/OpenMetadata/assets/1209358/93d0324b-296d-475a-836b-e4c06828afe6)

**Comment by 17rahulsharma** [comment]
@sureshms - more ideas added 

So here you can see downstream tables dependent on fact_booking_all_product_all table
![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/a8910829-881e-48d2-b10e-823848399785)


Now from left filter user select column called airline_id of fact_booking_all_product_all table and based on the column airline_id the lineage filter down to only two tables , see below

![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/d4527d27-8413-4861-a3d5-3a47784a8dfa)

**Comment by hoangdh5** [comment]
Hi, @17rahulsharma , that is what I expect. But, can we have one more Filter for Table.  And These filter should be multi select not single select.
Thanks alot

**Comment by mantasmy** [comment]
Hello,
This is a cool feature and really needed one. In addition to that if we would have filters applied in "dynamic manner" when clicking on a specific column in table lineage (graph) view... that would be amazing. IMO there is no point to filter columns in any other way just clicking in that view would do the trick, but maybe there are other use cases which I can't think of right now.
