### ISSUE TITLE
Glossary Term. Description in Edit: window too small: 4 lines at a time only

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#11521]
**Is your feature request related to a problem? Please describe.**
I am editing Glossary Term. Description in Edit and I find window way too small. Having to scroll is not convenient especially if I want to make changes in different places of a large text.

only 4 lines at a time. If I have text of 30 lines, it makes it very tricky to edit,
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/7c79d32a-61ea-44ac-93a2-bfdd3a13dfa2)

**Describe the solution you'd like**
Having a pop up window just for Description edit, where I could see more than 4 lines at a time.

**Describe alternatives you've considered**
Just live with it.

**Additional context**

**Comment by harshach** [comment]
@karanh37 the text area size still remains the same. Lets make it larger
