### ISSUE TITLE
Salesforce connection, additional parameters for domain & sf_version

### ISSUE THREAD

**Issue by wwittenborn** [open-metadata/OpenMetadata#11540]
**Affected module**
Ingestion framework

**Describe the bug**
When configuring a Salesforce resource the GUI provides the ability to specify username, password, & security_token.  It does not provide the ability to specify domain or sf_version.  This limits the target URL to the default "login.salesforce.com" and the version to the current default "42.0".   I need to pass "test" as the domain to create a target URL of "test.salesforce.com" 

**To Reproduce**
Create a new resource for Salesforce.  The screen doesn't provide affordances for domain or sf_version.

**Expected behavior**
Add optional input fields to the Salesforce resource configuration screen which would allow specification of domain and sf_version.

**Version:**
 - OS: OSX
 - Python version:  3.9.13
 - OpenMetadata version: 1.0
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==1.0.0

**Additional context**

**Comment by harshach** [comment]
@ulixius9 @OnkarVO7 can we push this in 1.0.2?
