### ISSUE TITLE
Allow parenthesis as allowed characters in entity name

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#11579]
This is split into three tasks:
- [x] Change schema regex to allow parenthesis in the entity name #11580
- [x] Update sample data and ingestion to include entity name with parenthesis - cc @pmbrull  https://github.com/open-metadata/OpenMetadata/pull/11591
- [ ] Ensure UI allows parenthesis in the entity names - cc @chirag-madlani

**Comment by pmbrull** [comment]
checking the UI on `main` noticed the following forms we need to update where currently () are not allowed:
- Service creation
- Team creation
- Classification & Tag creation
- Glossary & Glossary term creation

**Comment by Sachin-chaurasiya** [comment]
From The UI side, we will handle it as part of https://github.com/open-metadata/OpenMetadata/issues/11358

**Comment by chirag-madlani** [comment]
UI side changes will be handled with #11358 hence closing it out
