### ISSUE TITLE
DateTimeRange in Postgres not supported

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#11586]
**Affected module**
Ingestion Framework

**Describe the bug**
DateTimeRange type of Postgres is not ingested but fails instead with:  

```
Object of type 'DateTimeRange' is not JSON serializable
Error fetching sample data: 'DataType' object has no attribute 'dialect_impl'
```

**To Reproduce**

create a table with a column of type `DateTimeRange` and try to run the Postgres profiler on it

**Expected behavior**
it should work/profile

**Version:**
 - OpenMetadata version: 1.0.1
 - OpenMetadata Ingestion package version: 1.0.1.3

**Additional context**

**Comment by ayush-shah** [comment]
fixed in https://github.com/open-metadata/OpenMetadata/pull/12583
