### ISSUE TITLE
Japanese/Chinese language support in Custom Property Name

### ISSUE THREAD

**Issue by quguangyu0321** [open-metadata/OpenMetadata#11589]
It is seems that Custom Property Name only support english now. 
is it any plan to support japanese or chinese in the future?
![image](https://github.com/open-metadata/OpenMetadata/assets/61673226/8b7631db-a4c9-4466-bb07-9d472c4bca32)

**Comment by sureshms** [comment]
@chirag-madlani this looks like a UI validation issue. The backend support all Unicode characters for the name. Also when fixing this, can you also change the title to "Add Customer Property" with *P*roperty capitalized. In i.0, it is not.
