### ISSUE TITLE
Owner as a team and a user

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#11606]
Currently there is ability to add to entity owner as a team OR as a user. 
Many times, there is owner as a team, but inside the team there is specific user the is responsible for the entity.
So a good solution will be to enable both options on the same entity (and probably in this case, the user can be selected only from the team members). 
<img width="258" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/51fe585e-80e7-4d56-952d-e778bd657504">

**Comment by JahJajaka** [comment]
Apparently such functionality exists:
<img width="348" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/54989457/e19df5f6-dbaf-402e-9328-ade87cd65128">
But currently it works incorrectly. It doesn't display user who is a team owner. I don't understand how it defines a person for a team.

**Comment by sapirhi** [comment]
It happens only when you are part of to a team, and then you see yourself as the owner of your assets.
But each user see only it's connected assets on it's OMD view...
