### ISSUE TITLE
Implement Teradata connector for Ingestion

### ISSUE THREAD

**Issue by rich-clarke** [open-metadata/OpenMetadata#11611]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for Teradata but having recently moved to SQLFluff as a parser for SQLLineage(which supports Teradata), I think supporting Teradata would make sense. Teradata does currently not have any out of the box lineage tools available and requires manual development, OMD would solve a large gap in the Teradata community. 

**Describe the solution you'd like**
Support a Teradata connector

**Describe alternatives you've considered**
- Using the OpenMetadata Ingestion API to manually push Teradata tables/columns and lineage into OpenMetadata.

**Comment by harshach** [comment]
duplicate of #1077
