### ISSUE TITLE
Filter Staging/Temp tables out of search

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#11632]
Problem Statement: 
For our metadata systems, we have a lot of staging tables which are part of the lineage for Tier tables. So, these staging tables also need to be uploaded to OM in order to show accurate lineage, but the problem is that we don't want these tables to show as part of the search, because the OM portal shows the count of tables very high and it is information overload.

Possible Solution: 
Whitelisting of tables (or blacklisting) to show only some tables as part of global search not all tables like staging or intermediate.

Alternative:
Tagging blacklisted tables and creating a policy/rule not to show such tagged tables. However, did not try this whether it works or not.

Slack thread:
https://openmetadata.slack.com/archives/C02B6955S4S/p1684207468227369

**Comment by 17rahulsharma** [comment]
@ShaileshParmar11 - added feature request. Thank you for your support.

**Comment by harshach** [comment]
@ulixius9 are ingesting the table type as staging , temporary?

**Comment by harshach** [comment]
table type added as filter and one can use advanced search and add not equal to table type to exclude searches around temp tables
