### ISSUE TITLE
Profiler - Sample Data Percentage Value 

### ISSUE THREAD

**Issue by berogu** [open-metadata/OpenMetadata#11634]
Hi, although I updated the sample data percentage value in the profiler, only 100 data are listed on the sample data tab.
For example i select sample data percentage 5% in the profiler, but on the sample data tab I see 100 data instead of 51 data.

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/26457591/eddc93d6-d631-45ce-ac70-e2e839469479)

**Version:**
 - OpenMetadata version: [1.0.0]

**Comment by harshach** [comment]
@berogu we at minimum try to get 100 rows in sample data. Not more than and not less than that.
@TeddyCr maybe worth adding what no.of rows users want to collect as a sample with max limit as 100

**Comment by TeddyCr** [comment]
This is already supported. We need to make it clearer in the config.
