### ISSUE TITLE
Tableau AccessToken is flagging filed out fields as required

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#11637]
**Affected module**
UI

**Describe the bug**
Tableau access token is flagging filed out fields as required
![Screenshot 2023-05-17 at 11 28 27 AM](https://github.com/open-metadata/OpenMetadata/assets/13626425/75d45942-4ada-4c03-9197-688ff2cdb39f)

**To Reproduce**
Create a tableau connection with `AccessToken ` type.

**Expected behavior**
Should allow user to go to the next step

**Version:**
 - OS: Linux/MacOS
 - OpenMetadata version: 1.0.1

**Comment by OnkarVO7** [comment]
Clicking on the tableau test connection button redirects back to the connection details page

https://github.com/open-metadata/OpenMetadata/assets/28966081/f7dba862-efed-42b0-94e1-ef2c9144b502
