### ISSUE TITLE
problem in install open metadata on debian 11

### ISSUE THREAD

**Issue by alitehranim** [open-metadata/OpenMetadata#11636]
hi
when i try to install open meta data on debian 11 , at this level
" 6. Ensure the module is installed and ready for use "
this error apear : 
" global flags not at the start of the expression at position 1
"
please help !

**Comment by sylthiel** [comment]
Just for the sake of anyone looking this up on Google -- I joined the Open metadata Slack to find the answer. According to the developers, 
>hi, we don't have support yet for python 3.11. I'd recommend using 3.9
