### ISSUE TITLE
Removing all tags from Entity does not reflect changes in Elasticsearch results

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1165]
Try adding `User.Address` to any dim_address, check it on explore
It shows 3 tags added in the table card
Now try removing all tags from dim_address, check it again on explore
Tags are still there

Changes reflect if we remove `n-1` tags, i.e. do not remove all the tags from entity details page

P.S. @parthp2107 please attach video for more details

**Comment by parthp2107** [comment]
@darth-coder00 @harshach adding the link for the screen recording: https://app.replay.io/recording/33244264-46d6-44d4-8cf8-83bb413a02a0
