### ISSUE TITLE
Lineage UI - Circular dependency visualization

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11658]
# Scenario 1: Lineage A -> A

If we have a circular dependency of a table with itself, for example:

```
{'fromEntity': '6cc76cc3-eea0-477a-b574-1c69b5b68492',
   'toEntity': '6cc76cc3-eea0-477a-b574-1c69b5b68492',
   'lineageDetails': {'columnsLineage': [],
    'pipeline': {'id': 'ab6a47f9-f5d5-4084-a3b4-66ef685b9ace',
     'type': 'pipeline',
     'name': 'test_circular_lineage',
     'fullyQualifiedName': 'airflow_source2.test_circular_lineage',
     'description': 'An example DAG which runs a a task group lineage test',
     'deleted': False}}}
```
Then the Lineage UI from the table view is quite small and you cannot really see it if there are other upstream nodes

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/dba1be1b-4e8f-4c21-bb80-bda7bd7af742)

And the Lineage UI from the pipeline view only shows the node at the downstream:

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/d5c76c18-562b-4444-8ce4-84ff283d19c5)

# Scenario 2: Lineage A -> B and B -> A

In the default Lineage view, we'll only see:

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/db6c2fc0-2e84-49e5-89c3-36d09e544aa2)

Then, if we expand the right lineage of `dim.product`, we should see how `dim.product` -> `raw_order` and `raw_order` -> `dim.product`. However, only one lineage edge appears

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/f6493289-5602-47ea-a547-630fccc7cd2e)

We should make this easier to identify this.

**Comment by gavin-denyse** [comment]
Please prioritize this bug fix.
Thank you!

**Comment by pmbrull** [comment]
reported as solved in the commity
