### ISSUE TITLE
Term not count assert chart in dashboard

### ISSUE THREAD

**Issue by konnectr** [open-metadata/OpenMetadata#11652]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
I add term in glossary
add link term in dashboard for chart
open window term tab assert and not vision assert to chart in dashboard
and add link to table and them open tab asser and vission assert to table

**To Reproduce**

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/46676677/7f185683-de74-42da-a4ea-d43c7742c852)
![image](https://github.com/open-metadata/OpenMetadata/assets/46676677/8b26c64b-6bc6-4af7-997a-536f2ebba254)

**Expected behavior**
I see assert to dashboard in the tab term

**Version:**
 - OS: [e.g. iOS] linux
 - Python version: 
 - OpenMetadata version: [e.g. 0.8] 0.13.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by konnectr** [comment]
replay 1.0.1
![image](https://github.com/open-metadata/OpenMetadata/assets/46676677/0a341f15-7ff5-413d-8337-98dd8b6eb80d)
![image](https://github.com/open-metadata/OpenMetadata/assets/46676677/adb58e94-bafd-48ee-8be9-fe7765d93f26)

**Comment by sureshms** [comment]
This is more likely to be search indexing issues. This works fine in release 1.0. (Try it on our sandbox).

**Comment by sureshms** [comment]
This appears to be working for entities such as Table but not for Chart.
