### ISSUE TITLE
Show Pipeline last known status and Table's DQ summary as part of the lineage

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#11661]
**Is your feature request related to a problem? Please describe.**
To analyse data lineage, it's crucial to know, is the DAGs are enabled or disabled 

**Describe the solution you'd like**
Collect DAG statutes (enabled / disabled)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by harshach** [comment]
@karanh37  lets work with Rupesh to design the panel for EDGE and Pipeline better.
We should show the last known status of the pipeline while displaying the Lineage view and also in the panel.
@07Himank lets discuss on how can support all of these features using Search indexes rather than APIs

**Comment by harshach** [comment]
@karanh37 we need to build a pipeline knowledge panel to be added to Table entity pages on the right side.
If we have pipeline that is related to the table via lineage we will show its last known status
