### ISSUE TITLE
Backend: suggestion for pipeline is not giving result when we search with term

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#11676]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend: ES - suggest API

**Describe the bug**

I have ingested airflow pipeline service, and after ingestion when i try to search for any of the pipelines its not give me suggestions but when I search with the service name it shows results
**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/71748675/3748a2fb-74e5-4476-ac3b-1ae68091c4f5

**Expected behavior**

it should search and show the result for the pipeline, even if service name is not provided

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@07Himank can you take a look

**Comment by chirag-madlani** [comment]
Tested on sandbox version: 1.1.5

https://github.com/open-metadata/OpenMetadata/assets/12962843/c63e06db-e998-470c-bb95-de379afb3120

<img width="331" alt="Screenshot 2023-09-28 at 8 58 24 PM" src="https://github.com/open-metadata/OpenMetadata/assets/12962843/e9bed43f-ebe8-41b2-a080-2b0867fae39b">
