### ISSUE TITLE
Graph discontinuity where there is no object in the database in DataInsights

### ISSUE THREAD

**Issue by FelipeArruda** [open-metadata/OpenMetadata#11683]
**Affected module**
UI

**Describe the bug**
A graph discontinuity occurs where there is no object in the database.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Generate the graph with zero value.
Video
[screen-capture.webm](https://github.com/open-metadata/OpenMetadata/assets/5818475/a86ac54c-99d5-49b3-9b5e-216bcb3b27d0)

**Version:**
 - OS: Chrome
 - OpenMetadata version: 0.13.2

**Comment by harshach** [comment]
@FelipeArruda can you please check the API response and see if we have datapoints for that missing day?
cc @ShaileshParmar11 @TeddyCr

**Comment by FelipeArruda** [comment]
> @FelipeArruda can you please check the API response and see if we have datapoints for that missing day? cc @ShaileshParmar11 @TeddyCr

I just have access to airflow log. Does it work?
[dag_id=OpenMetadata_dataInsight_run_id=scheduled__2023-05-16T04_00_00+00_00_task_id=data_insight_task_attempt=1.log](https://github.com/open-metadata/OpenMetadata/files/11536845/dag_id.OpenMetadata_dataInsight_run_id.scheduled__2023-05-16T04_00_00%2B00_00_task_id.data_insight_task_attempt.1.log)

I found an error but idk if its the cause.
`ERROR - Error trying to fetch entity -- An exception with message [Entity type table not found] was thrown while processing request.`

**Comment by TeddyCr** [comment]
@FelipeArruda to me, this is the right behavior. If there is no data for a specific day we should break the line of the graph (to indeed signify there is not data).

**Comment by FelipeArruda** [comment]
Hey @TeddyCr . No problem, I thought If no data for the day, set the value for 0 (zero) and there is no discontinuity. Just another option.
