### ISSUE TITLE
Upload owner to airflow pipeline - optional field

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#11686]
**Feature**
Add flag for 'owner' when setting definiiton to airflow pipeline ingestion. 

**Describe the task**
In the latests version, probably there is a new feature that takes from dag properties the user mail and put it as Owner in OMD.
We have actually ownership set in a ‘owner’ field in the dag (it’s our convention to do owners as teams). So what we have so far, is a daily api that goes over all airflow pipelines and set the owner according to our logic.
Since you enter the OMD owner automatically (and there is no way to exclude it in the settings), everyday your pipeline change all owners and then we run it over with our owners couple hours later.
Excluding the resource waist here, it’s very confusing for the users as it changes all the time.

**Comment by pmbrull** [comment]
@ayush-shah could you please handle https://github.com/open-metadata/OpenMetadata/issues/5121 as well when working on this? Should be a simple addition since you are already playing with pipelines.

Thanks!
