### ISSUE TITLE
support DBT 1.5

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#11725]
OM 1.0.1 0.3 does not yet support DBT 1.5

https://openmetadata.slack.com/archives/C02B6955S4S/p1684838276025499

there is a transitive dependency clash

please support sqlfluff 2.1.0 and not only 2.0.2 

it looks like sqllineage needs to be upgraded perhaps?

**Comment by pmbrull** [comment]
sqlfluff has been updated
