### ISSUE TITLE
Add a switch to activate New UI

### ISSUE THREAD

**Issue by louie007** [open-metadata/OpenMetadata#11732]
Can we let the users decide to activate or not the new UI [feat(ui): landing page new design #11630](https://github.com/open-metadata/OpenMetadata/pull/11630), by adding a switch in the user preference page ? Also, we can move the language setting to this preference page.

**Comment by harshach** [comment]
@louie007 we won't be adding any switch for this. Any reason for this?

**Comment by harshach** [comment]
@louie007 if you have any feedback please provide us on the Slack (https://slack.open-metadata.org) but maintaining 2 designs and layouts is just too much work and impossible to get things right.
Based on community feedback we are moving with this design.

**Comment by louie007** [comment]
> @louie007 if you have any feedback please provide us on the Slack (https://slack.open-metadata.org) but maintaining 2 designs and layouts is just too much work and impossible to get things right. Based on community feedback we are moving with this design.

Thanks for your response @harshach, I think some folks will prefer the classic design like me. As your said maintaining 2 designs is difficult, I totally agree, and will check the community feedback soon.
