### ISSUE TITLE
Pipeline Tasks do not have option to add/remove tags

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1174]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/141609126-48310b9a-c882-43bc-a7a7-63c308fe9680.png">

**Comment by ShaileshParmar11** [comment]
Assign to me

**Comment by darth-coder00** [comment]
@harshach I think after #1006 fix, UI is not getting `tags` under `tasks`
@ShaileshParmar11 checked it adding `tags` to a `task`, but api does not provide any tags under task

**Comment by ShaileshParmar11** [comment]
Hi, I did research about this and below is my finding on it:-

1. I am able to add tags in tasks through `/api/v1/pipelines/{id}` API.
2. I am not able to get tags through get request for tasks.

once Backend send the tags in tasks, we can implement add/remove tags feature to pipeline tasks.
@harshach @sureshms

**Comment by Sachin-chaurasiya** [comment]
Not relevant anymore as we have task dags now.
