### ISSUE TITLE
Landing Page Overhaul with new mocks

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11759]
- [ ] Landing page -- @karanh37 
  - [x] Left NavBar
  - [x] Right sidebar
  - [x] Feed widget
  - [x] KPI
  - [x] Total data assets
  - [x] Conversation Panel
  - [x] My data widget
  - [ ] Quick Links -- **Blocked on Backend** @mohityadav766 

- [x] Explore -- @karanh37 
  - [x] Entity Card with new UI
  - [x] Right side panel with new UI

- [ ] Data quality -- @ShaileshParmar11 

- [ ] Entity details -- @chirag-madlani 
  - [ ] the main page where we show the entity, schema etc..
  - [ ] Activity feed & Tasks
  - [ ] Lineage
  - [ ] Queries - Remains the same, should follow the style guide make sure its styling is according to the new design but same layout
  - [ ] Sample Data - remains the same, there was an ask for horizonal scrolling more evident
  - [ ] Profiler & Data Quality  - Remains the same , make it consistent with new style guide
  - [ ] Custom Properties - Remains the same, make it consistent with new style guide

- [ ] Data Insights - Layout remains the same, consistent with new style guide
- [ ] Data Quality - new Designs pending form @rupesh
- [ ] Govern, Tags - same layout, consistent new style guide
- [ ] Settings -> Same layout, consistent with new style guide

- [ ] #11003

**Comment by chirag-madlani** [comment]
Figma link: https://www.figma.com/file/FPpKOFSoVddbtesFCQJVjM/OpenMetadata-Final-Screens?type=design&node-id=22%3A8721&t=P4gSb5D5Ch6xFYoj-1
