### ISSUE TITLE
SQL server error

### ISSUE THREAD

**Issue by AbrahanTorres** [open-metadata/OpenMetadata#11768]
I have an issue when I tried to ingest via SQL server.

The server require an encryption, but there is not option to select this.

(pytds.tds_base.Error) Client does not have encryption enabled but it is required by server, enable encryption and try connecting again )

![image](https://github.com/open-metadata/OpenMetadata/assets/102258512/ffc41ee6-ce51-4c53-8c5f-54333c84aeee)

**Comment by Yashar8991** [comment]
what is it ? SSMS ?

**Comment by AbrahanTorres** [comment]
Hi Yashar.

Yes, it is SSMS.

**Comment by Yashar8991** [comment]
but SSMS have encryption section to make it.  Why is not your tool?

**Comment by AbrahanTorres** [comment]
> but SSMS have encryption section to make it. Why is not your tool?

I installed openMetadata by docker-compose dowloading it using the command:

curl -SL https://github.com/open-metadata/OpenMetadata/releases/download/1.0.2-release/docker-compose.yml -o docker-compose.yml -s

**Comment by Yashar8991** [comment]
docker is shit , bro
