### ISSUE TITLE
HIVE Connector - Execution Time Too Long.

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#11778]
**Affected module**
Ingestion - HIVE

**Describe the bug**
HIVE repositories with a great number of schemas an entities (views/tables) metadata ingestion time exceeds afordable time.

**To Reproduce**
HIVE metastore with 9000 schemas filtered by regex to retrieve metadata of only 450 and 8000 views/tables schemas from total: 19 hrs first exec., 24+ second

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/112470575/4d9ddec1-0ee9-4c51-84fc-71fc4eb237fc)
![image](https://github.com/open-metadata/OpenMetadata/assets/112470575/f2b4648b-62c3-4620-b8ed-705a5a81ac31)

**Expected behavior**

**Version:**
 - OS: REHEL
 - Python version: 3.8
 - OpenMetadata version: 1.0.1
 - OpenMetadata Ingestion package version: 1.0.1

**Additional context**

**Comment by pmbrull** [comment]
@jromandv some data that would help us evaluate this:
- Number of ingested tables in total
- Time that it takes to execute a `DESCRIBE FORMATTED` for a few of these tables

Also, do you have this Hive instance connected to an external Hive Metastore we could try to use?

Thanks

**Comment by pmbrull** [comment]
hi @jromandv we'll need this information to evaluate this further. Thanks

**Comment by jromandv** [comment]
Hi, @TeddyCr 

DESCRIBE FORMATTED query against a few tables and views and SHOW CREATE TABLE {viewName}.

https://openmetadata.slack.com/archives/C02B6955S4S/p1685523570973869?thread_ts=1684924826.031689&cid=C02B6955S4S

https://openmetadata.slack.com/archives/C02B6955S4S/p1685525710488899?thread_ts=1684924826.031689&cid=C02B6955S4S

**Comment by harshach** [comment]
@ulixius9 @ayush-shah you are referencing this ticket in one of the PRs. Can we close this?

**Comment by sonnb270898** [comment]
hi  @ulixius9 @harshach,
I see your code change on commit "Fix #11778: Add support for hive metastore ingestion #12599" but this only support on metastore with mysql or postgres, do you have plan to  support metastore with oracle?
