### ISSUE TITLE
Unable to ingest Kafka Topics  mapping parsing exception

### ISSUE THREAD

**Issue by stephanesol** [open-metadata/OpenMetadata#11771]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Ingestion

**Describe the bug**

from [slack](https://openmetadata.slack.com/archives/C02B6955S4S/p1685023850176139)

> i’m unable to re-index my Topics using the elastic search option in the front end. The UI shows 0 Topics but i can see 100 in the db. And when i try to reindex in the UI i see 100 errors.

**To Reproduce**

Screenshots or steps to reproduce

<img width="1162" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/6843613/44c64cf0-ac47-405e-83c3-753a944bd24f">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] 1.0.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by stephanesol** [comment]
closed by https://github.com/vercel/data-catalog/issues/48

<img width="1102" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/6843613/7004a1c9-2621-4187-a715-f8b9557b0267">

**Comment by pmbrull** [comment]
@stephanesol this has been fixed on 1.0.4 where we changed the type as long. Let us know if that solves your issue. Meanwhile I'll be closing this. Thanks!

https://github.com/open-metadata/OpenMetadata/issues/11869

**Comment by stephanesol** [comment]
It solves the problem. Thank you!
