### ISSUE TITLE
Request for custom pipelines CLI documentation

### ISSUE THREAD

**Issue by mathurk1** [open-metadata/OpenMetadata#11788]
**Is some content missing, wrong or not clear?**
In version v1.0.0, we have capability to create custom pipeline integrations like below - 
<img width="1011" alt="Screenshot 2023-05-28 at 5 02 53 PM" src="https://github.com/open-metadata/OpenMetadata/assets/22126205/0c94f46c-4902-4e8a-a056-a2c79bb47100">

However, I am not able to find the corresponding documentation for custom pipelines here - 
<img width="549" alt="Screenshot 2023-05-28 at 5 03 11 PM" src="https://github.com/open-metadata/OpenMetadata/assets/22126205/b27edded-8d06-453c-999a-87696c1a8eec">

**Describe the solution you'd like**
Can you please add detailed documentation around building custom pipelines or point me to existing ones if they are somewhere else, esp. the cli version?

**Additional context**
The goal is to create custom pipelines using CLI and/or Python SDK.

Thanks!

**Comment by harshach** [comment]
@mathurk1 have you looked at this page https://docs.open-metadata.org/v1.1.0/connectors/custom-connectors
