### ISSUE TITLE
Ability to create pipeline (edges) without Connectors

### ISSUE THREAD

**Issue by mathurk1** [open-metadata/OpenMetadata#11789]
**Is your feature request related to a problem? Please describe.**
There are scenarios where adhoc/manual scripts are run on dataset to create outputs used for very specific reporting etc. in an adhoc manner. Imagine an analyst running a small script locally to update outputs based on monthly changing requirements.

**Describe the solution you'd like**
I would like the ability to capture that manual step in the lineage diagram. Currently, we have the ability to edit lineages, but I can only add pipelines (edges) which has some form of a backend specified [here](https://docs.open-metadata.org/v1.0.0/connectors/pipeline). In this scenario, I do not have the job on any orchestrator and I also do not need the status of the job to be polled by Open Metadata airflow. I just want to add a Pipeline with basically a name, just to indicate that there is a manual process happening to create a dataset.

**Describe alternatives you've considered**
Alternatively, I am trying to create a "dummy" Custom Pipeline, which will not do anything, but just allow me to add that pipeline in the data lineage graphs

**Additional context**
Even with the ever growing push to automate, I think these kinds of manual processes happen a lot in business and this might be a good feature to have.

Thanks!

**Comment by JoeJordan1** [comment]
This is exactly what I need too. For example: to create a static 'dummy' pipeline for an MS Excel Report, which uses data from SQL Server.  I want to be able to show the SQL Server data lineage, with the table illustrating it being linked to various of these types of reports. Would be very helpful in identifying and searching where data is used across the business, helping to avoid replication.
