### ISSUE TITLE
Open up customization for the content on the detail tab page on the right side of the search results page

### ISSUE THREAD

**Issue by heroWang** [open-metadata/OpenMetadata#11796]
**Is your feature request related to a problem? Please describe.**
Hi, team. My colleague proposed a scenario: he wants to batch copy the value of a certain custom attribute from tables of the search results. However, it is annoying to jump from the search results page to the details page and then return to the search page every time. Can we open up customization for the content on the detail tab page on the right side of the search results page? So that, We can show the custom property on the tab page. 
![image](https://github.com/open-metadata/OpenMetadata/assets/1209358/91ef68c6-3959-49fc-bc61-28398886d6af)

The Custom Properties I want to show on the detail tab is:
![image](https://github.com/open-metadata/OpenMetadata/assets/1209358/a288f92c-bf56-4b4b-ae59-fdbcf0eb5439)

**Describe the solution you'd like**
open up customization for the content on the detail tab page on the right side of the search results page, So that, We can show the custom property on the tab page. 

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by harshach** [comment]
custom properties can be searchable from Advanced Search
