### ISSUE TITLE
Profiler Ingestion errors specific to Bigint data type.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#11809]
**Affected module**
Profiler Ingestion

**Describe the bug**
Profiler Ingestion error for data type bigint (in particular)

error 1: `Numeric data overflow 

We found this error in the profiler ingestion logs, upon investigations for the problematic columns we can see that this happening mostly with 'bigint' data type.

<img width="779" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/110607559/b092bd89-7dd0-4cdd-b535-fdbde358cc0c">

error 2: Value out of range for 8 bytes: (Happening while casting as BIGINT when the sum is equal to Infinity `SUM(CAST(cancellationrate AS BIGINT)) AS sum`)

<img width="757" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/110607559/a1119d41-71e9-4a20-be35-d62eea9a928d">

OM version : 1.0 (latest)

**Comment by TeddyCr** [comment]
@lailapatel what database engine are you running the profiler against?
