### ISSUE TITLE
Some Quicksight dashboards are not appearing after release 1.0

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#11806]
**Affected module**
QuickSight Dashboard Ingestion

**Describe the bug**
Some QuickSight dashboards are not appearing after release 1.0. Prior to release deployment there were 61 dashboards and after release deployment, only 54 dashboards are getting ingested.

Debug logs and airflow logs are attached. 

[moovedataquicksightmetadatanyu-5631.txt](https://github.com/open-metadata/OpenMetadata/files/11596510/moovedataquicksightmetadatanyu-5631.txt)
[dag_id=moove-data-quicksight_metadata_nYUNLpcR_run_id=scheduled__2023-05-15T10_00_00+00_00_task_id=ingestion_task_attempt=1.log](https://github.com/open-metadata/OpenMetadata/files/11596512/dag_id.moove-data-quicksight_metadata_nYUNLpcR_run_id.scheduled__2023-05-15T10_00_00%2B00_00_task_id.ingestion_task_attempt.1.log)

[moovedataquicksightmetadatanyu-5631.txt](https://github.com/open-metadata/OpenMetadata/files/11596554/moovedataquicksightmetadatanyu-5631.txt)

**Version:**
 OM 1.0 release

**Comment by ayush-shah** [comment]
Not able to reproduce this error / hard to reproduce.
Dashboards are being ingested as expected. as per the logs, the lineage is not getting generated, but the charts and dashboards are getting ingested.

**Comment by pmbrull** [comment]
@lailapatel we'd need some more information here. If this is still an issue feel free to ping us and reopen this issue. Thanks
