### ISSUE TITLE
Add to docs, what metadata are ingested from Airflow

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#11800]
**Is your feature request related to a problem? Please describe.**
Currently it's not clear what can be ingested from Airflow DAG and now DAG code should be prepared to all metadata being ingested.

**Describe the solution you'd like**
1) Clear table what metadata are ingested from Airflow.
2) Code examples of adding owners, tags, descriptions to DAGs and tasks. 

**Describe alternatives you've considered**
Deep dive into the Airflow connector code and instruct data engineers. 

**Additional context**
None.

**Comment by harshach** [comment]
<img width="1219" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/e1a5fe40-79b8-46d8-bb19-e19c0d9e1715">
