### ISSUE TITLE
Table Queries Often Return Empty Queries

### ISSUE THREAD

**Issue by JoeJordan1** [open-metadata/OpenMetadata#11845]
In the list of table queries, there are lots of empty queries being returned:

![image](https://github.com/open-metadata/OpenMetadata/assets/84777707/9ff817b8-e3cb-421c-8e1e-ccfea30e7570)

They all have the same description and are 1 line, and interestingly are all from 1st Jan at Midnight. It seems like these are false detections.

 - OpenMetadata version: 1.0.2

**Comment by JoeJordan1** [comment]
Although this has been assigned to v1.2, interestingly (since 1.1 update) this issue has stopped occurring. It seems that whatever was done in v1.1 dev has rectified the issue. I will continue monitoring and confirm if it reoccurs.

**Comment by pmbrull** [comment]
cool thanks for the update
