### ISSUE TITLE
Incorrect URL encoding

### ISSUE THREAD

**Issue by DenisKirichenko24** [open-metadata/OpenMetadata#11846]
UI Impact

After the reindexing with Elastic (recreate index is True) we can`t find the tables of some services which have **()** in the name and russian letters in the name. Seems like the problem on url encoding side because we have this tables on **explore** and **search** pages

Teams are also unavailable with () in the name 

Screenshots are presented 

Version:
 - OpenMetadata version: 1.0.2
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.0.2.0
![image (3)](https://github.com/open-metadata/OpenMetadata/assets/81522845/57d874d3-45f2-4748-8320-3e5119e56eb1)
![image (5)](https://github.com/open-metadata/OpenMetadata/assets/81522845/6477a297-fea1-42b6-bc7d-7b42e5dc4626)
![image (4)](https://github.com/open-metadata/OpenMetadata/assets/81522845/3433ecc3-c3e7-40e7-9776-4707d5a5d8b5)

**Comment by Sachin-chaurasiya** [comment]
This is fixed in the main and will be part of 1.1

https://github.com/open-metadata/OpenMetadata/assets/59080942/5295c329-48e2-4875-9410-c2a6e893e5f6
