### ISSUE TITLE
Deleting containers not reflected in counters and search results screen

### ISSUE THREAD

**Issue by wwittenborn** [open-metadata/OpenMetadata#11853]
**Affected module**
API / backend

**Describe the bug**
I've been creating and deleting containers via the APIs. Everything is working fine except the display counter for Service: CustomStorage and my Service Name: FileShare.  Deleting containers in this service / service name have not decremented the counters and deleted containers appear in the main screen area.  Clicking on a deleted container returns an error message "container instance for FileShare.-999999999 not found.

**To Reproduce**
**Create container via API:**
CreateContainer container = new CreateContainer();
container.setService("FileShare");
container.setNumberOfObjects(1d);
container.setSize(0d);
container.setDisplayName("foo");
container.setName("bar");
openMetadataRepository.getContainersApi().createOrUpdateContainer(container);

**Delete container via API:**
openMetadataRepository.getContainersApi().deleteContainer(container.getId(), true);

**Expected behavior**
The counter for containers under "CustomStorage.FileShare" should decrement and the deleted container should not display on the search results screen.

**Version:**
 - OS: [e.g. iOS] iOX
 - Python version:  Java SDK,  Java 19
 - OpenMetadata version: [e.g. 0.8]. 1.0.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]. N.A.

**Additional context**
I understand containers are still beta.

**Comment by harshach** [comment]
@07Himank take a look

**Comment by harshach** [comment]
This is resolved in latest release
