### ISSUE TITLE
lineage - unable to link multiple pipelines to tables in one goal

### ISSUE THREAD

**Issue by CorsettiS** [open-metadata/OpenMetadata#11877]
**Affected module**
UI

**Describe the bug**
Lets say I have a pipeline that is airbyte -> postgres -> airflow. to create the lineage chart, I have to go to the airbyte pipeline & link the table to it and, once again, go to the airflow pipeline and link the table to it, so I will obtain the lineage mentioned. The problem with that is:
1) It damages the user experience to not be able to do everything in one go.
2) It it not that intuitive. For a moment I thought it would not be possible to create the lineage chart properly.
It would be good to have the possibility to do the lineage chart in one go.

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/66136602/9feeb0bf-07b2-4397-be2b-7c22ea6c34cc)

**Expected behavior**

**Version:**
1.0.3

**Additional context**

**Comment by karanh37** [comment]
Done with the new lineage UI changes.
