### ISSUE TITLE
MSSQL Lineage from Stored Procedures

### ISSUE THREAD

**Issue by Ossy81** [open-metadata/OpenMetadata#11918]
**Affected module**
LineAge view

**Describe the bug**
When showing a linage from a table it doesn't show the full lineage, due to Stored Procedures. We use lot's of SPs to loa tables

**Expected behavior**
Show the SP as part of the Lineage

**Version:**
 - OpenMetadata version: 1.0.0.3

**Comment by phalix** [comment]
#9269 duplicate

**Comment by pmbrull** [comment]
duplicate of https://github.com/open-metadata/OpenMetadata/issues/9269
