### ISSUE TITLE
Losing child terms during glossary import

### ISSUE THREAD

**Issue by tm-yegorova** [open-metadata/OpenMetadata#11915]
**Affected module**
backend

**Describe the bug**
I hasve glossary with parent and child terms. When I export them I see information about child and parent terms in csv correctly.
But when I try to import them, Just parent terms are imported. Child terms are desapeared absolutely.

**To Reproduce**

1. Create gloassary with child and parent terms.
2. Export them.
3. Look at the scv file. See the parent and the child terms.
4. Import scv.
5. See the  the parent and the child terms in the interface.
6. Finish import.
7. Look to the glossary. See that there isn't child term.
8. Open parent term. See that there isn't child term.

**Expected behavior**
I expected that child terms would be imported too.
And gloassary after exporting and importing would be just the same as source glossary.

**Version:**
We use container by this way [OpenMetadata Documentation: Get Help Instantly (open-metadata.org)](https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment), so I don't know version of OS: [e.g. iOS], OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] and Python version. Screenshot attached.
 - OpenMetadata version: [e.g. 0.8] 0.13.3

**Additional context**
![glossary import1](https://github.com/open-metadata/OpenMetadata/assets/49267105/f7e820d6-62a0-4612-8451-d004c9ca15e7)
![glossary import2](https://github.com/open-metadata/OpenMetadata/assets/49267105/8cd6341f-0cac-4df0-84da-0d0120cb0ab8)
![glossary import3](https://github.com/open-metadata/OpenMetadata/assets/49267105/70d65c5c-edf5-40ad-ac93-89d174140e31)
[Test glossary_2023-06-07T10_54_43.240.csv](https://github.com/open-metadata/OpenMetadata/files/11674242/Test.glossary_2023-06-07T10_54_43.240.csv)
![965552CE](https://github.com/open-metadata/OpenMetadata/assets/49267105/0e4907e3-d56a-4095-936f-7208e74ee1a3)

**Comment by sureshms** [comment]
@tm-yegorova, can you please try this on release 1.0 and see if you can reproduce this?

**Comment by harshach** [comment]
@tm-yegorova can you please provide an update on this?

**Comment by harshach** [comment]
@tm-yegorova unable to reproduce this with the latest release. If you still see the issue in latest release please re-open
