### ISSUE TITLE
Connect to Airflow in Kubernetes

### ISSUE THREAD

**Issue by stepanurban** [open-metadata/OpenMetadata#11935]
Hi all, 
I've just installed openmetadata in Kubernetes but I can't connect to Airflow. I'm getting message: 
_To set up metadata extraction through UI, you first need to configure and connect to Airflow. For more details
 visit our [documentation](https://docs.open-metadata.org/deployment/airflow)._ But in this doc there is nothing about setting this up in Kubernetes. Can you please document how to do it?

**Comment by akash-jain-10** [comment]
Hello @stepanurban  - Can you confirm if you are using the default namespace as mentioned in the documentation [here](https://docs.open-metadata.org/v1.0.0/deployment/kubernetes#prerequisites) ?
