### ISSUE TITLE
Backend - API support to fetch count for mentions

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#11944]
**No API gives count for mentions threads**

Need an API or filter support for `feed/count` so that we can have count for mentions to show below in UI:

<img width="377" alt="Screenshot 2023-06-09 at 7 25 46 PM" src="https://github.com/open-metadata/OpenMetadata/assets/12962843/1df0621c-a630-4faa-bb3b-63a60a5c8eac">

**Comment by harshach** [comment]
@chirag-madlani you can use mentions api today and get the count. We need this to be added to activityFeed in the landing page and also the entity pages. UI anyway making individual calls today so adding another call with limit set to 0 is fine.

**Comment by harshach** [comment]
we are doing this for tasks already 

![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/e1c57f9e-db29-46ff-8e5c-c9aab62ac552)

For mentions same thing

![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/e8c0de27-aca0-45dd-80f4-913225b5e49a)

**Comment by chirag-madlani** [comment]
@harshach will need count API to return the below data
```js
 openTaskCount -- Represents any open tasks present for the entity
 mentionCount -- Represents count of any mentioned to user whos userID will be present in the API param
 coversationCount -- All the conversation for that Entity
 totalTaskCount -- Total tasks present on that entity including Open / Close
```

API endPoint: `/feed/count?entityLink=%3C%23E%3A%3Atable%3A%3Asample_data.ecommerce_db.shopify.raw_product_catalog%3E`
