### ISSUE TITLE
the AirFlow need to deploy separately

### ISSUE THREAD

**Issue by jackxueman** [open-metadata/OpenMetadata#11942]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

![image](https://github.com/open-metadata/OpenMetadata/assets/11639909/0e34cd89-38f0-498c-aa4a-8f24097dcddb)

THE TEST CONNECTION CAN NOT CLICK; the AirFlow need to deploy separately？

**Comment by Sachin-chaurasiya** [comment]
Hello @jackxueman, to test the connection you will need to have the airflow available, for more info read our deployment doc https://docs.open-metadata.org/v1.0.0/deployment, thanks!
