### ISSUE TITLE
Add a list with all Environment Variables that are used

### ISSUE THREAD

**Issue by PascalStehling** [open-metadata/OpenMetadata#11941]
**Is some content missing, wrong or not clear?**
When setting up OpenMetadata, it can be quite tedious to find all Environment Variables you are using internally. Some are mentioned in the example docker-compose files, others are only found in the scripts itself.

**Describe the solution you'd like**
Just a list for the different services (metadata, ingestion,..) and all Environment variables for them, with their default values and a little explanation or so.

**Comment by akash-jain-10** [comment]
Hello @PascalStehling  - We are doing this as part of sample environment variables file we have in our Github Repository here -
- [env-mysql](https://github.com/open-metadata/OpenMetadata/blob/main/docker/docker-compose-openmetadata/env-mysql)
- [env-postgres](https://github.com/open-metadata/OpenMetadata/blob/main/docker/docker-compose-openmetadata/env-postgres)

Let us know if this helps here! Closing this issue for now. Thanks.
