### ISSUE TITLE
Lineage UI rewamp: column lineage features

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#11949]
**Is your feature request related to a problem? Please describe.**
In addition to other user requests in relation to column lineage ( like https://github.com/open-metadata/OpenMetadata/issues/11515) a few other feature suggestions to improve user experience.  Mainly, to reduce the number of clicks a user needs to make when looking for e2e column lineage. 

**Describe the solution you'd like**
1) Ability to access the column lineage from schema, either by
- a) see the first up-stream level if lineage on schema table
- b) or be able to click on the column and it would bring the e2e lineage, but filtered on that specific column

**Describe alternatives you've considered**
Waiting for the column lineage on the UI, but I believe to it would mean that users will need to duplicate clicks.
For example, a big query user is working with a table and wants to find where specific column comes from. The steps would be:
1. Go to OMD and search for the column
2. Select relevant table
3. Go to lineage tab of the table
4. Use search for the column lineage <= so in effect, searching for the column twice

**Additional context**

**Comment by pmbrull** [comment]
- [ ] https://github.com/open-metadata/OpenMetadata/issues/11661
