### ISSUE TITLE
Column Profiling metrics based on data type (for UI and calculations)

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#11951]
**Is your feature request related to a problem? Please describe.**
Column profiling metrics should only be shown if they are relevant for that data type

**Describe the solution you'd like**
For example, UI should not show SUM profiling fo Dates or for strings. 
Example from SandBox, where for VARCHAR   column, out of 5 graphs, 3 are empty and not relevant, It is confusing to users. 
https://sandbox.open-metadata.org/profiler-dashboard/column/sample_data.ecommerce_db.shopify.dim_address.first_name
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/c829dcd8-94ef-410f-8763-6f4cb9c8d992)

also, the profiling graphs don't resize if screen is minimized. 

calculations should also not happen in these instances

**Describe alternatives you've considered**
nothing

**Additional context**

**Comment by DovileKr** [comment]
hello, do we have any plans for this enhancement?

**Comment by pmbrull** [comment]
aiming at 1.4, informed on the project

**Comment by harshach** [comment]
@pmbrull @TeddyCr @ShaileshParmar11 are we planning to finish this in release 1.4.0

**Comment by ShaileshParmar11** [comment]
re-opening as ui side of changes are still pending
