### ISSUE TITLE
Conversations and Request update description for Glossary Term

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#11950]
**Is your feature request related to a problem? Please describe.**
Request on Glossary terms to have collaboration features

**Describe the solution you'd like**

- Same Conversations and Request update description features as for tables and  columns.
- For glossary, there should also be request to add a term, in addition to update description.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by harshach** [comment]
Closing this as duplicate in favor of https://github.com/open-metadata/OpenMetadata/issues/12166
