### ISSUE TITLE
UI: Diff and Current Tabs Displaying Identical Content

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#11959]
**Affected module**
UI

**Describe the bug**
I think I've discovered a  UI bug. When I create a task to modify a table description, I update the description. However, upon checking the **Diff** and **Current** tabs, both of them display the new text instead of showing a difference between the previous and the updated text.

**To Reproduce**

![Capture d’écran 2023-06-11 à 22 00 14](https://github.com/open-metadata/OpenMetadata/assets/75131226/8fc552a9-252c-4e4e-90b2-12d086b3150b)

**Expected behavior**
The diff tab should highlight the diff between the new and current description, and the Current tab shoud show the current description.

**Version:**
 - Python version:
 - OpenMetadata version: 1.0.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
Hi, @haithem-souala can you share the screenshot for all three tabs, Meanwhile I will check this on my end. But wanted to make sure that we aren't missing any corner cases there

**Comment by haithem-souala** [comment]
![Capture d’écran 2023-06-22 à 11 51 07](https://github.com/open-metadata/OpenMetadata/assets/75131226/e99e530a-ef70-4226-b3ac-700d021b4b34)
![Capture d’écran 2023-06-22 à 11 51 24](https://github.com/open-metadata/OpenMetadata/assets/75131226/eb2b053a-448c-441c-9073-0d32a70ee27c)
![Capture d’écran 2023-06-22 à 11 51 15](https://github.com/open-metadata/OpenMetadata/assets/75131226/dfbd9379-da1f-4f46-8a1e-7c731abd1b61)

**Comment by chirag-madlani** [comment]
Thanks @haithem-souala 
Will fix it in 1.1
