### ISSUE TITLE
DI Web Analytics Filter Should Enforce UTC 

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#11963]
**Affected module**
OpenMetadata Data Insight

**Describe the bug**
When filtering data for web analytics we should force timezone to UTC.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@TeddyCr this looks like an important issue, whats the work required here? only on the UI side?

**Comment by TeddyCr** [comment]
@harshach IMO this is mostly not relevant. As we save the UNIX timestamp value (i.e. Long) and send the UNIX timestamp value when requesting the data everything should be in accordance. Aggregation is performed on the ES data which saves the UNIX timesatamp.
