### ISSUE TITLE
Add Size, Created At, Updated At, Created By to table entity metadata

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#11967]
Pass Size, Created At, Updated At, and Created By values as metadata for connectors where this information is available. A couple of elements:
- timestamp should be in milliseconds for `Created At`, `Updated At`. We'll need to understand how timezone affect the timestamp that is passed (is that timestamp based on the DB engine timezone, if so can it be converted to UTC, etc.)
- size should be passed in bytes. We can then convert it appropriately from the frontend to the most logic unit.

**Comment by harshach** [comment]
created_at, updated_at, accessed_at 3 things should be for all entities. This could be a basic type that can be added to all the entities
