### ISSUE TITLE
Wrong documentation for airflow postgres connector in the UI

### ISSUE THREAD

**Issue by CorsettiS** [open-metadata/OpenMetadata#11978]
**Is some content missing, wrong or not clear?**

Lets say I have an airflow application that uses postgres. OMD allows to connect directly to the postgres schema and fetch data from it. The issue comes from the misleading documentation

This is how it is described that we should connect to airflow postgres in the UI
<img width="1380" alt="Screenshot 2023-06-13 at 17 36 29" src="https://github.com/open-metadata/OpenMetadata/assets/66136602/ea17c22b-692f-4b8a-a3f3-ccd3432dd58b">

However this is wrong, and it should be just like that 
<img width="420" alt="Screenshot 2023-06-13 at 17 36 05" src="https://github.com/open-metadata/OpenMetadata/assets/66136602/2da149eb-6eca-4dd6-9d0d-913ed47e66cd">

**Describe the solution you'd like**
Just remove the http:// part of the documentation that was failing for a long time and can be extremely misleading.

**Comment by pmbrull** [comment]
hi sorry about that, just opened a PR with the right docs fixed for each db connection
