### ISSUE TITLE
matchAnyTag() is case insensitive

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#11979]
**Affected module**
User permission

**Describe the bug**
When we set a rule to matchTag it looks like our tag validation is case insensitive (e.g. `.PERSONAL` tag does not exist) but the permission is case sensitive (i.e. my user can't update the table with tag `.Personal`).

**To Reproduce**
Create a rule with the a `matchAnyTag()` condition with an upper case tag.

Screenshots or steps to reproduce

![Screenshot 2023-06-13 at 6 36 53 PM](https://github.com/open-metadata/OpenMetadata/assets/13626425/fdac8213-3430-4a96-8d46-09905fedee21)
![Screenshot 2023-06-13 at 6 35 00 PM](https://github.com/open-metadata/OpenMetadata/assets/13626425/060efc87-4c82-47f3-9256-035001d12e9f)

**Version:**
 - OpenMetadata version: `main`

**Comment by 07Himank** [comment]
Closing this ticket as it is already fixed fixed.
<img width="1137" alt="Screenshot 2023-08-07 at 6 49 06 PM" src="https://github.com/open-metadata/OpenMetadata/assets/112613760/7b2380d0-24b6-416f-b5ff-69ec39576b83">
<img width="1114" alt="Screenshot 2023-08-07 at 6 48 56 PM" src="https://github.com/open-metadata/OpenMetadata/assets/112613760/97f33e34-7c28-48b2-be76-b7d09424d749">
