### ISSUE TITLE
patch_description not working for test case

### ISSUE THREAD

**Issue by itaise** [open-metadata/OpenMetadata#11973]
**Affected module**
Ingestion FW

**Describe the bug**
Since upgrading to 1.0.3, the patch description method is not working for test cases. 

**To Reproduce**
Try to patch a desc. to a test case: 
```
self.conn.patch_description(TestCase, test_case, description,  force=True)
``` 

pydantic error is raised: 

```
2 validation errors for TestCase
testDefinition
  field required (type=value_error.missing)
testSuite
  field required (type=value_error.missing)
Screenshots or steps to reproduce
```
according to @pmbrull  the right shaped entity is not fetched from the APi by default:. slack thread: 
https://openmetadata.slack.com/archives/C02B6955S4S/p1686647795205529?thread_ts=1686644463.337579&cid=C02B6955S4S

can you please check? 
thanks! 

**Version:**
 - OpenMetadata Ingestion package version: 1.0.3

**Comment by pmbrull** [comment]
Thanks. The `patch_*` methods such as `patch_description` could use an added level of logic to pass the correct `fields` value to the `_fetch_entity_if_exists` [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py#L166).

In case of handling an entity type T that is `TestCase`, we would need to pass `fields=["testDefinition", "testSuite"]`. This should get rid of this issue.

Thanks~
