### ISSUE TITLE
Semantic search in support of genAI

### ISSUE THREAD

**Issue by shachr** [open-metadata/OpenMetadata#11981]
**Is your feature request related to a problem? Please describe.**
With the raise of genAI, data catalog needs to be genAI friendly, allowing a user to describe what they look for and use a genAI copilot to help them discover data assets. However, open metadata and many other catalogs are behind on that front, and doesn't offer much to solve this problem. Leaving the bulk of work for developers.

**Describe the solution you'd like**
My solution is 2 fold:
1. Support OWL to describe ontologies that includes the semantics concepts of data.
2. Support replication of ontology to a semantic vector to support semantic search as means to prompt a LLM given user input.

**Describe alternatives you've considered**
I couldn't find any comprehensive solution.

**Additional context**
None.

**Comment by TeddyCr** [comment]
Thank you @shachr for opening this interesting issue. I would love to get your opinion on the advantage you see to use a LLM as opposed to Guided Natural Language Query in the context of OpenMetadata?
