### ISSUE TITLE
Ingestion filter patterns don't support regex values that contain commas

### ISSUE THREAD

**Issue by cutz** [open-metadata/OpenMetadata#11980]
**Affected module**
UI Add/Edit Metadata Ingestion form.

**Describe the bug**
I'm trying to add metadata ingestion that uses a table exclude filter which contains a comma. The resulting ingestion does not behave as one would expect given the configured value. Closer inspection reveals that the provided regex is being split into two filter patterns by the comma. [I've attempted ](https://openmetadata.slack.com/archives/C02B6955S4S/p1686693783125169)to wrap the regex in `"`,  and `'` characters as well as escaping the `,` with a `\`. The end result is always the same.

**To Reproduce**

Add/edit a metadata ingestion and setup a table exclude filter with a regex of `^.*_[0-9]{4,8}.*$`. Complete the wizard and save the ingestion. Notice the saved table filter pattern has split the regex into two filters.

```json
"tableFilterPattern": {
                "excludes": [
                    "^.*_[0-9]{4",
                    "8}.*$"
                ]
            },
```

**Expected behavior**

The provided regex should not be split, rather a single pattern should be persisted.

```json
"tableFilterPattern": {
                "excludes": [
                    "^.*_[0-9]{4,8}.*$"
                ]
            },
```

It should also be possible to specify additional regular expressions as part of the filter even if one contains a comma. Perhaps some form of quoting or escaping is needed.

**Version:**
OpenMetadata 1.0.2 installed via docker.

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/11849
