### ISSUE TITLE
Without DELETE permission on glossaries users cannot import/export

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#11995]
If we don't grant the DELETE permissions for glossaries, the "three dots" button gets disabled, blocking users from running import/export operations

**Comment by harshach** [comment]
@Sachin-chaurasiya lets address this in 1.1 itself
This will impact the ability to 'Rename" the entity as well if we are only looking at Delete permission to enable that menu cc @chirag-madlani

**Comment by Sachin-chaurasiya** [comment]
Hello @pmbrull , Can you please provide the OM version?

**Comment by pmbrull** [comment]
1.0.4

**Comment by Sachin-chaurasiya** [comment]
It's fixed on Main.

Glossary


https://github.com/open-metadata/OpenMetadata/assets/59080942/6886f365-4276-4761-8a0f-bd22fd05700e

Glossary Term


https://github.com/open-metadata/OpenMetadata/assets/59080942/09a97ee4-41ec-4060-8630-d0dfe5cd10f0
