### ISSUE TITLE
Add CypressTests for deploying DataInsight, Re-Index and deploying a scheduled pipeline

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12016]
**Feature**
We need test coverage from UI side to test critical functionality of

- [x]  Deploying DataInsights pipeline
- [ ]  Deploying a Search re-index pipeline
- [ ]  Triggering search re-index
- [ ]  Cypress for entity summary panel
- [ ]  Refactor AddAndRemoveTierAndOwner spec to remove sample_data dependency to fix the dashboard related test fail

**Describe the task**

**Comment by aniketkatkar97** [comment]
Remaining tests will be tracked in [#12576](https://github.com/open-metadata/OpenMetadata/issues/12452)
