### ISSUE TITLE
Allow Tag Creation on the Fly

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#12033]
**Context**
- As a user I want to be able to create new tag on the fly when trying to add a non existing somewhere in the platform

![Screenshot 2023-06-19 at 2 31 16 PM](https://github.com/open-metadata/OpenMetadata/assets/13626425/96c3bf48-0aa9-4367-8d16-3165596a0899)

**Comment by sureshms** [comment]
@TeddyCr tags are for us controlled vocabulary. That means we can't allow users to add them freely but it has to be done based on governance needs. While this is convenient, it runs counter to curated, reviewed, and controlled vocabulary.
