### ISSUE TITLE
Assess swapping `commonregex` by `commonregex-improved`

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#12047]
https://pypi.org/project/commonregex-improved/

Check what usage we are doing on CommonRegex and see if there are any improvements with the improved version

**Comment by psirenny** [comment]
I just hit an openmetadata install error on Python 3.11 when trying to resolve `commonregex`. Switching to `commonregex-improved` would fix it.

**Comment by pmbrull** [comment]
thanks for the ping @psirenny. Also please note that we don't officially support 3.11 yet, we have a bunch of dependencies we might need to align. We'll be adding 3.10 to our testing soon though

**Comment by pmbrull** [comment]
@ulixius9 if you can please take a look at this. Not even sure if we're actually using this lib anymore so we might be able to remove it
