### ISSUE TITLE
Om support for Airflow 2.6.1

### ISSUE THREAD

**Issue by deepaktripathi1997** [open-metadata/OpenMetadata#12044]
**Is your feature request related to a problem? Please describe.**
Currently We are using custom airflow 2.6.1 with OM but Om managed apis don't support Airflow 2.6.1. The issue is Airflow has deprecated the SchedulerJobRun in their latest version, but OM managed apis is still using the SchedulerJobRun in their latest version.

**Describe the solution you'd like**
I will suggest you to use the correct imports and that will work fine.

**Describe alternatives you've considered**
Till Now I have not moved to any alternative.

**Comment by TeddyCr** [comment]
closing as duplicate [here](https://github.com/open-metadata/OpenMetadata/issues/12190)
