### ISSUE TITLE
Send announcements by email/MS Teams/Slack like alerts/notifications

### ISSUE THREAD

**Issue by kreyes7** [open-metadata/OpenMetadata#12054]
**Is your feature request related to a problem? Please describe.**
When a future change to the tables is announced, followers might not see the announcement in time because they don't have OpenMetadata open all the time.

**Describe the solution you'd like**
A possible solution is that, like alerts and notifications, announcements can be sent by email, MS Teams and/or Slack.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks!

**Comment by mohityadav766** [comment]
closing this , it will be handled in https://github.com/open-metadata/OpenMetadata/pull/14674
