### ISSUE TITLE
Read Me section for Airflow

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#12077]
**Is your feature request related to a problem? Please describe.**
Today our users document their airflow pipeline directly from git (no need to write it twice). They would like to have it in OMD as well. 

**Describe the solution you'd like**
In airflow dag there is 'DAG docs' section  
<img width="591" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/876e6bfc-bf17-49d3-8cb7-c39852a49f95">
The information gets from the code line 
dag.doc_md = get_file((Path(__file__) / "../../README_ORDERS.md").resolve())
So, the idea is to get the exact info to the 'description' part for airflow pipeline automatically (same as you did for owner for example)
<img width="217" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/b782e9f4-f5d5-4f83-9bda-71b31d974b1d">

**Comment by harshach** [comment]
we won't be able to support this.
