### ISSUE TITLE
Parsing aliased tables as sources with sqllineage 

### ISSUE THREAD

**Issue by jetpacula** [open-metadata/OpenMetadata#12074]
**Is your feature request related to a problem? Please describe.**
When parsing query strings containing aliased source tables (`table_name AS alias_name`) with `sqllineage.runner.LineageRunner().source_tables`  no source tables are detected. 
**Describe the solution you'd like**
Functionality to recognise aliased source tables, both with `AS` keyword and with whitespace after original table name
**Describe alternatives you've considered**
Manually modifying original query string with regex `re.sub()` with pattern `\bAS\s+\w+`. However this does not work with implicit aliasing without `AS` keyword.

**Comment by ulixius9** [comment]
@jetpacula can you please share any example query.

**Comment by pmbrull** [comment]
hi @jetpacula please share an example where we can reproduce the error, otherwise it's hard for us to move forward. We'll leave this open a few more days. Thanks
