### ISSUE TITLE
Lineage with 3+ dependencies

### ISSUE THREAD

**Issue by jeremytee97** [open-metadata/OpenMetadata#12085]
**Is your feature request related to a problem? Please describe.**
Currently, the max downstream/upstream depth is 3, and users are not able to view the entire lineage when we retrieve it from dbt
![image](https://github.com/open-metadata/OpenMetadata/assets/37123816/f178b8a3-55fa-4cd1-ac7b-2ad88e0b095c)

**Describe the solution you'd like**
Would love to have an option "3+" as a choice to be able to view all dependencies, such as what is implemented in datahub here 
https://datahubproject.io/docs/lineage/lineage-feature-guide/#editing-from-lineage-tab

**Comment by pmbrull** [comment]
This feature is supported on newer releases of OM. You can explore the lineage view in the sandbox https://sandbox.open-metadata.org/table/sample_data.ecommerce_db.shopify.raw_customer/lineage

Closing it for now since we are already presenting all the information
