### ISSUE TITLE
Providing a connection dedicated for Data Quality 

### ISSUE THREAD

**Issue by isabela-angelo-ze-delivery** [open-metadata/OpenMetadata#12081]
**Is your feature request related to a problem? Please describe.**

Tests suits are dependent on the service metadata connection to be executed.
When using Glue connection to ingest metadata, for example, the OM tests suites are not enabled. 
I would like to use these tests suites because they are very easy to be integrated in Airflow however to use them I would need to change the metadata connector and have extra work to transfer the manually input metadata in the new database.

**Describe the solution you'd like**

I would like a way to have a dedicated connection to run DQ tests, independently of the metadata connection.

**Describe alternatives you've considered**

An alternative could be writing my own tests or changing metadata connector and have some extra work like already mentioned.

**Additional context**

**Comment by TeddyCr** [comment]
Hello @isabela-angelo-ze-delivery thank you for opening this issue. Could share more details as to what you are trying to achieve?
