### ISSUE TITLE
Extract BigQuery Profiler Logic Into its own Interface

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#12103]
**Context**
A few elements have been implemented as part of the base profiler to manage BigQuery specific logic. This logic should be extracted into its own interface to handle big query specific cases

(e.g. https://github.com/open-metadata/OpenMetadata/issues/11803 -> struct of arrays)

**Comment by ayush-shah** [comment]
Already taken care of by @TeddyCr..
if need be, will open it again.
