### ISSUE TITLE
Wrong source url for looker looks

### ISSUE THREAD

**Issue by keatmin** [open-metadata/OpenMetadata#12106]
**Affected module**
UI

**Describe the bug**
When clicking on url source of a look/chart of a Looker Dashboard in UI, it leads to the wrong path because of a wrong source url. It is mainly caused [by this specific line](https://github.com/open-metadata/OpenMetadata/blob/84c2d7c69b76658a5ea74364b35fdc898c68250c/ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py#L612) as `dashboard_elements/chart_id` is not the right path to the specific look. Source url for a dashboard is obtained in different ways depending on the chart, if it's a query it will be under `chart.query.share_url` but if it's a merge_result, there is no `share_url` and good to avoid showing. 

**To Reproduce**
1. Ingest dashboards from Looker to OpenMetadata
2. From the UI, view any dashboard and click on the link of any looks in dashboard 
3. If the url has `dashboard_elements/{chart.id}` it will lead to the wrong url. 

**Expected behavior**
A correct look/chart source url from looker instead of the constructed one with `dashboard_elements/chart_id` as it doesn't exist in Looker

**Version:**
 - OS: MacOS Ventura
 - Python version: 3.9.5 
 - OpenMetadata version: 1.0.5
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[looker]==1.0.5`]

**Additional context**

**Comment by keatmin** [comment]
Initial test of changing the following line to this helped: 

```python
 chartUrl=chart.query.share_url if chart.query is not None else f"{clean_uri(self.service_connection.hostPort)}/merge?mid={chart.merge_result_id}",
```

This was a quick fix on my end but essentially check if chart.merge_result_id is not None, then the url with `merge?mid=chart.merge_result_id. Check if chart.query is not empty then chart.query.share_url

**Comment by pmbrull** [comment]
Thanks @keatmin for filing this and proposing the change. Let me take a quick look on my end as well and we'll bring it for the next release
