### ISSUE TITLE
Add support for Domains and Data As A Product in OpenMetadata

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#12142]
# Datamesh support in OpenMetadata
Datamesh has quickly gained popularity in helping organize data, people, and processes. But Datamesh, as it stands today, is fairly high-level and broad in concepts, with a lot of it left to interpretation by practitioners. OpenMetadata is taking a measured approach to supporting Datamesh concepts for this reason. Additionally, Datamesh may be overkill for most organizations with lesser data and smaller teams. So supporting Datamesh in OpenMetadata must be done in a manner where large organizations can get the full support for functionality they need without adding unneeded complexity to smaller organizations.

This document uses the [reference](https://www.datamesh-architecture.com) for Datamesh architecture and uses the definitions provided in it.

## Datamesh concepts
This section describes the Datamesh concepts relevant to OpenMetadata. Many of the concepts, such as ownership, documentation, data quality, data observability, security policies, and many aspects of organizing data and people, are well supported by OpenMetadata already.

### Domains
A data mesh is a decentralized data architecture that organizes data by a specific business domain following the concepts of domain-oriented design. It
 has the following characteristics:
- Has teams that take ownership of data, both operational and analytical, that belong to the domain.
- Provides Data as a Product to consumers based on Data Contract.
- Is powered by Domain-agnostic self-serve data infrastructure.
- Has Enabling Teams for consulting
- Domain has three types Consumer-aligned, Aggregate, and Source-aligned.

### Federated Governance
Federated governance helps in the interoperability of all data products through standardization, promoted by the governance group by establishing organizational policies. It includes:

- Interoperability policy
- Documentation policy
- Security policy
- Privacy policy
- Compliance policy

### Data as a Product
A data product is an autonomous logical component that contains all data, code, and interfaces to serve the domain team's or other teams' analytical data needs.
- Produces analytical data in different formats - Tables, S3 files, Dashboards, PDF reports, ML model
- Data contract defines the endpoint, syntax, semantics, and quality of data
- Owned by a domain team - ensures data quality, availability, and costs
- Metadata - ownership, schema, semantics, security
- Observability - quality metrics, operational metrics, SLOs
- Who is the consumer
- What use cases can the data be used
- Input ports and Output ports

# Datamesh functionality in OpenMetadata
### Adding entities to a domain
Entities can be tagged as belonging to a domain or sub-domain:
- Data assets, such as Databases, Database Schemas, Tables, Dashboards, Charts, Topics, ML Models, Pipelines, and Containers.
- Services, such as Database Services, Messaging Services, Dashboard Services, ML  Model services, Pipeline Services, and Storage services
- Other entities such as Teams and Glossaries

### Domain inheritance
The domain or sub-domain is inherited from the parent entity to the child entities. The domain can also be automatically propagated in some cases. Here are a few examples:
- If a Database Service belongs to a domain, the children entities such as Database, Database Schema, and Tables automatically inherit the domain from the parent.
- If a Team belongs to a domain, all the children team and users under the team inherit the domain.
- When a team is tagged with a domain, all the assets belonging to the team are also tagged with the domain of the team.

**Note that an entity can belong to only one domain. The children must belong to the same domain or sub-domains as the parent.**

## Data products in OpenMetadata
While Data As A Product generally means building a product using data, such as sentiment analysis, funnel analysis, etc., in OpenMetadata, we use the term Data Product to mean Data As A Product. A Data Product is a collection of the following types of entities - Tables, Charts, Dashboards, and Topics. A data asset can be part of zero or more Data Products.

The data assets that are not part of data products are considered to be **internal data assets** and are not exposed outside the domain.

## Domain APIs
New APIs will be added …/api/v1/domains with Create, Update, Get, List, and Delete operations. Domains are hierarchical and can have sub-domains. The following APIs are supported:
|API endpoint|Description|
|------------|-----------|
|`GET …/api/v1/domains`|List domains with pagination and filters|
|`GET …/api/v1/domains/{id}`|Get a domain by unique Id|
|`GET …/api/v1/domains/{fqn}`|Get a domain by fully qualified name|
|`POST …/api/v1/domains`|Create a new domain|
|`PUT …/api/v1/domains`|Create or update a domain|
|`PATCH …/api/v1/domains/{id}`|Update a domain using patch|
|`DELETE …/api/v1/{id}`|Delete a domain by Id|
|`DELETE …/api/v1/{fqn}`|Delete a domain by fully qualified name|

## Data Product APIs
New APIs will be added …/api/v1/dataProducts with Create, Update, Get, List, and Delete operations. Data Products can belong to either top-level domain or sub-domains. The fully qualified name of the data product is <domain>.<dataProductName> when it belongs to a top-level domain and <sub-domain>.<dataProductName> when it belongs to a sub-domain:

|API endpoint|Description|
|------------|-----------|
|`GET …/api/v1/dataProducts`|List dataProducts with pagination and filters|
|`GET …/api/v1/dataProducts/{id}`|Get a data product by unique Id|
|`GET …/api/v1/dataProducts/{fqn}`|Get a data product by fully qualified name|
|`POST …/api/v1/dataProducts`|Create a new data product|
|`PUT …/api/v1/dataProducts`|Create or update a data product|
|`PATCH …/api/v1/dataProducts/{id}`|Update a data product using patch|
|`DELETE …/api/v1/{id}`|Delete a data product by Id|
|`DELETE …/api/v1/{fqn}`|Delete a data product by fully qualified name|

## Domain page
A new page will be added to OpenMetadata to define domains and organize teams, data assets, and other metadata under it.
- *Defining domains and sub-domains in an organization*: The Domain page is a place to create different Domains and sub-domains in the organization. Domains can be of one of the following types - Consumer Aligned, Aggregate, and Source Aligned. Documentation can be added to describe domains in detail.
- *Domain teams and assets*: The highest hierarchy, such as Business Unit, Division, or Department, can be added to the Domain. All the children teams under this team hierarchy automatically inherit the domain property. All the data assets owned by the domain teams automatically become domain assets.
- *Data as a product*:  Data products of a domain can be defined on the domain page. 
- *Domain vocabulary*: Domains can have their specific glossaries by marking a glossary as belonging to the domain. These glossaries are visible to both the users in the domain and outside the domain to help them understand the concepts and business terminology of the domain.

## Domains and changes to the other pages on OpenMetadata
The domain will have an impact on many of the existing pages in the UI:
- Teams, Glossaries, and data assets pages, such as tables, dashboards, pipelines, etc., will clearly show the Domains they belong to.
- The Data Assets show if they are a Data Product.
- Explore page will allow Domains and/or Data Products to filter search results.
- Roles & Policies functionality will incorporate domain as metadata to define rules to allow or not allow access to domains to the users.

## Domain-only view
OpenMetadata will support a Domain-only view. A user can select this view by selecting a domain he has permission to. By default, the Domain-only view allows a user to select the domain that he belongs to. 

In this view:
- Search Experience: The search gives results with data assets that only belong to the domain (both data products and non-data products). In addition, the data assets that are marked as data products from other domains will be provided.
- The Data Quality page will show the data quality metrics at the domain level.
- The Data Insights page will show the data insights at the domain level.

## Future work
Support for Domains in OpenMetadata is going to be ongoing, and more features will be added based on customer feedback.
- OpenMetadata already covers many aspects of Data Contracts. This will be organized better to mark entities as a Data Product along with metrics to measure how the entity is doing to meet the data contract requirements.
- Data product lineage to show the upstream and downstream data products for a given data product.
- Domain map - Show domains and sub-domains in an organization with a graph of how domains are dependent on each other.

**Comment by sureshms** [comment]
[] Task 1 - Add support for Domains
[] Task 2 - Add support for Data As A Products
[] Task 3 - Add support for setting Data Assets, Teams as part of a Domain
[] Task 4 - Add support for setting Data Assets as Data As A Product
[] Task 5 - Add UI support for Domains
[] Task 6 - Add UI support for Domain-only view

**Comment by harshach** [comment]
@sureshms great write up!! 
question: "entity can belong to only one domain" can an parent entity belong to parent domain and children entities can belong to subdomain under that domain?

**Comment by sureshms** [comment]
> @sureshms great write up!! question: "entity can belong to only one domain" can an parent entity belong to parent domain and children entities can belong to subdomain under that domain?

Children can belong to the sub-domains of the parent entity. Clarified that in the writeup.
