### ISSUE TITLE
Allow stored procedures, user defined functions, user defined table types as table types

### ISSUE THREAD

**Issue by gavindew** [open-metadata/OpenMetadata#12167]
**Is your feature request related to a problem? Please describe.**
We have many stored procedures, user-defined table types and user-defined table functions. We would like to be able to add these to the data catalogue.

**Describe the solution you'd like**
We would like to be able to send via the API the table definition with the TableType being 
- StoredProcedure
- UserDefinedTableType
- TableValuedFunction

We would like to be able to define input parameters. This would be an additional tab on the table page. Input parameters should be able to have tags and glossary items assigned to them, just like columns.

We would like to be able to set the table SQL in the ViewDefinition field.

We would like to be able to view the ViewDefinition on the page.

Making this available only via API (i.e. not needing to update the ingestion adapters) would be a good first start.

**Describe alternatives you've considered**
As an alternative, we will be defining these artefacts as Views, however, this is not ideal.
We will be defining input parameters using a convention that ensures they are always the first columns such as  @ParameterName.

**Comment by pmbrull** [comment]
For Snowflake:
- [Overview](https://docs.snowflake.com/en/sql-reference/stored-procedures-overview)
- [List Procedures](https://docs.snowflake.com/en/sql-reference/sql/show-procedures)
- [Possible solution](https://community.snowflake.com/s/article/Getting-the-execution-details-of-procedure) to getting the procedure lineage based on the procedure execution query ID
