### ISSUE TITLE
Airbyte metadata ingestion fails when source and target in Airbyte match to Opensource database services accordingly.

### ISSUE THREAD

**Issue by zhyzhkea** [open-metadata/OpenMetadata#12165]
**Affected module**
Ingestion Framework

**Describe the bug**
Airbyte metadata ingestion fails when the source and target in Airbyte match to Opensource database services accordingly.

**To Reproduce**

Create Airflow Connectin like this:
![image](https://github.com/open-metadata/OpenMetadata/assets/34140723/67d5b0c4-9bb0-49fa-ac9c-a7fa41eed9f4)

Create OM database services "snowflake" and "mssql":
![image](https://github.com/open-metadata/OpenMetadata/assets/34140723/053837fa-b8b4-4ed7-afa0-464fa024bec5)

Create Airbyte metadata ingestion pipeline:
![image](https://github.com/open-metadata/OpenMetadata/assets/34140723/dbca95b6-3107-44a2-84e9-22bd085fdac7)

**Expected behavior**
The ingestion pipeline was executed successfully and table lineage between MSSQL and Snowflake was created.

Ingestion pipeline log file:
[airbyte-ingestion-source-and-target-match-with-om-services.txt](https://github.com/open-metadata/OpenMetadata/files/11875150/airbyte-ingestion-source-and-target-match-with-om-services.txt)

**Version:**
 - OS: Windows 11/WSL2/Unubtu 22.04
 - Python version: 3.8
 - OpenMetadata version: 1.0.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
@zhyzhkea can you upgrade to the latest stable version and let us know if you are still experiencing this issue.

**Comment by pmbrull** [comment]
we need more information
