### ISSUE TITLE
Glossary Term Collaboration & Tasks

### ISSUE THREAD

**Issue by gavindew** [open-metadata/OpenMetadata#12166]
Currently, there appears to be no way to start a conversation for glossary terms or add tasks, like you can for tables.

We would like reviewers of glosssary terms to be able to converse around the terms, have an activity feed like a table etc and subscribe to the activity feed

**Comment by gavindew** [comment]
There is already such a feature request

**Comment by sureshms** [comment]
@gavindew, this has been addressed in release 1.2.
