### ISSUE TITLE
hive - UI database and schema structure alignment

### ISSUE THREAD

**Issue by magpest** [open-metadata/OpenMetadata#12179]
**Affected module**
UI and Backend

**Describe the bug**
During ingestion of metadata from HIVE, there are created structures in format \<HIVE service name>.\<DB>.\<schema>.\<table> in OM HIVE service. 
For HIVE DB, meaning source, DB and schema are equal/same entity. In OM UI however, for HIVE service, DB and schema are not the same object, not with same name. With many HIVE databases, this creates a problem as real HIVE databases are mapped to either 'default' or cli config specified OM HIVE service DB name as "schema" level objects, not as databases.

This difference creates problem for Atlas connector, which treats OM HIVE service DB and schema as same (correctly) and tries to reach them in format:
\<HIVE service name>.\<DB>.\<schema_same_as_DB>.\<table>, which fails.

**To Reproduce**
HIVE config:

source:
type: hive
  serviceName: ref_hive2
  serviceConnection:
    config:
      type: Hive
      scheme: 'impala'
      auth: LDAP
      username: $MY_USER
      password: $MY_PASS
      hostPort: knox.server:443
      connectionOptions:
        http_path: 'knox/topology/hive'
        use_http_transport: True
        use_ssl: True
  sourceConfig:
    config:
      type: DatabaseMetadata
      markDeletedTables: true
      includeTables: true
      includeViews: true
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: $OM_API_URL
    verifySSL: "ignore"
    authProvider: openmetadata
    securityConfig:
      jwtToken: $OM_API_BOT_TOKEN

metadata ingest -c config.yml

![hive_db_schema_alignment](https://github.com/open-metadata/OpenMetadata/assets/94848436/f9a21a67-0fd0-4d19-b1de-79e70c74f733)

**Expected behavior**
In OM UI, for HIVE service, DB and schema are created as same name objects, with 1 OM HIVE service DB object per each 1 HIVE DB and 1 OM HIVE service DB schema object with same name as DB, corresponding to it.
Alternatively, remove the 'schema' logic if possible and also update Atlas connector to count with this.

**Version:**
 - OS: Centos 7
 - Python version: 3.10
 - OpenMetadata version: 1.0.4
 - OpenMetadata Ingestion package version: openmetadata-ingestion[hive]==1.0.4.4

**Additional context**
https://www.oreilly.com/library/view/apache-hive-cookbook/9781782161080/ch04s07.html

**Comment by geoHeil** [comment]
should be fixed by https://github.com/open-metadata/OpenMetadata/pull/12108

**Comment by geoHeil** [comment]
we will update you once we have tested 1.1.0 release

**Comment by ulixius9** [comment]
closing this for now we can reopen if the issue persists.
