### ISSUE TITLE
openmetadata_managed_apis uses deprecated Airflow class

### ISSUE THREAD

**Issue by arroadie** [open-metadata/OpenMetadata#12190]
**Affected module**
Ingestion

**Describe the bug**
WIth the change added [here](https://github.com/apache/airflow/pull/30255), the SchedulerJob class was renamed to SchedulerJobRunner. That change breaks the interaction between openmetadata and airflow in version 2.6 (haven't pinpointed the exact version)

**To Reproduce**

Fresh installation of airflow running tag 2.6.2 with the latest plugin version added will result in the following

<img width="802" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/3903371/1568ae11-7608-4e3c-a48d-fcde818e625d">

**Expected behavior**
The plugin should reference the proper class or in it's effect limit the compatibility to the latest version in which the SchedulerJob class is available.

**Version:**
 - OS: docker on macos (apache/airflow:2.6.2)
 - Python version: Python 3.7.17
 - OpenMetadata version: [e.g. 0.8]
 openmetadata-airflow-managed-apis        0.11.5.3
openmetadata-managed-apis                1.0.5.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] openmetadata-ingestion                   0.11.5.3

**Additional context**
I'm using my own docker compose setup, so it's using a previously set version of airflow (2.6.2) instead of the baked in setup provided by openmetadata

**Comment by pmbrull** [comment]
Hi, note that we don't support yet Airflow 2.5 or 2.6. The work to do here is to enable a wider version range.

If you want to use our APIs you should stick to 2.3.3 (the one we use in our image) or 2.4 (I think some community users tested that already)

Thanks

**Comment by arroadie** [comment]
Oh, in this case I believe it would be awesome to add a compatibility matrix somewhere in the documentation since in some places where airflow is mentioned it says it's supported on oficial airflow releases (not necessarily for this library, but for the pipeline connector).
Anyways, awesome work with the project. kudos to the team.
Will try later with a different version since I can't downgrade our current airflow runtime just to test openmetadata and there's no sense in adding a new version just for it as well.
Cheers
