### ISSUE TITLE
Filter for lineage workflow in Snowflake

### ISSUE THREAD

**Issue by jeremytee97** [open-metadata/OpenMetadata#12199]
**Is your feature request related to a problem? Please describe.**
Currently upon running the lineage workflow, we are not able to limit which database + schema we want to target. It will pull data of all of the query as long as it falls under this [condition](https://github.com/open-metadata/OpenMetadata/blob/49114cdad4342f9ffa3e22d70925ba998014b26c/ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py#L29)

**Describe the solution you'd like**
Add database and schema regex filter, to limit what to scan. This is possible for snowflake as snowflake.account_usage.query_history do have the necessary columns to be filtered on

**Comment by ulixius9** [comment]
solved with https://github.com/open-metadata/OpenMetadata/pull/12560
