### ISSUE TITLE
Display createdDateTime and sizeInByte profile metrics

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#12196]
**Context**
In 1.1.0 we added `sizeInByte` and `createdDateTime` metrics to the table profile (for most of the engine where this info is available). We should surface this information in the profiler tab (alongside the row and column count).

The size metric should be displayed in the format that makes the most sense (MB, GB, TB, etc.)

```
    "profile": {
        "timestamp": 1687938504,
        "profileSample": 64,
        "profileSampleType": "PERCENTAGE",
        "columnCount": 9,
        "rowCount": 99,
        "sizeInByte": 24,
        "createDateTime": 1684133068987
    },
```

**Comment by pmbrull** [comment]
This we are already doing in the Storage Services, maybe you can reuse the same code cc @Ashish8689
