### ISSUE TITLE
Add `Resolved` tab to the quality page

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#12197]
**Context**
In 1.1 we introduce a resolution workflow allowing users to report resolution information for a failed test case. We should now display this information in the user interface (new `resolved` tab in the under the quality page).

The information should display:
- test case name
- execution date (should be sorted by this filed descending)
- reason
- comments
- who resolved it

**Comment by ShaileshParmar11** [comment]
I think we can close this ticket as we already working on the resolution center feature cc @TeddyCr
