### ISSUE TITLE
Unable to add table tag & description for dashboard charts even after claiming ownership

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#1222]
Unable to change or add new tags and descriptions of the dashboard table even if I have claimed ownership of the dashboard.

response:-
`{"code":403,"message":"Principal: CatalogPrincipal{name='shailesh.parmar'} does not have permissions"}`

![image](https://user-images.githubusercontent.com/71748675/142158705-8adba0e1-9c2c-4ccc-b926-6814019b2a3f.png)
![image](https://user-images.githubusercontent.com/71748675/142157916-fb7b4eb5-7889-49ae-8217-957258a32a45.png)

cc @harshach @sureshms

**Comment by Sachin-chaurasiya** [comment]
@harshach this is the same issue that we were facing for pipeline and task. so after merging task entity with pipeline it got resolved.

**Comment by ShaileshParmar11** [comment]
This is resolved
