### ISSUE TITLE
HIVE - connector with impala driver does not use proper DDL to gather view metadata

### ISSUE THREAD

**Issue by magpest** [open-metadata/OpenMetadata#12242]
### Affected module
Ingestion

### Describe the bug
During ingestion of metadata from HIVE, via Impala driver, there is used DDL statement 'show create view' to gather view metadata.
This however doesn't work with the impala driver used against HIVE (not impala). Hive doesn't support such DDL statement and there can be used 'show create table' or described extended. Show create view works in IMPALA(engine), but the cli is used against HIVE.

### To Reproduce
HIVE config:

source:
type: hive
serviceName: ref_hive2
serviceConnection:
config:
type: Hive
scheme: 'impala'
auth: LDAP
username: $MY_USER
password: $MY_PASS
hostPort: knox.server:443
connectionOptions:
http_path: 'knox/topology/hive'
use_http_transport: True
use_ssl: True
sourceConfig:
config:
type: DatabaseMetadata
markDeletedTables: true
includeTables: true
includeViews: true
sink:
type: metadata-rest
config: {}
workflowConfig:
openMetadataServerConfig:
hostPort: $OM_API_URL
verifySSL: "ignore"
authProvider: openmetadata
securityConfig:
jwtToken: $OM_API_BOT_TOKEN

message (table/db names are redacted):
[2023-06-30 15:10:41] WARNING  {metadata.Ingestion:common_db_source:319} - Failed to fetch view definition for view_name: (impala.error.HiveServer2Error) Error while compiling statement: FAILED: ParseException line 1:12 cannot recognize input near 'VIEW' 'db_name' '.' in show statement
[SQL: SHOW CREATE VIEW `db_name`.`view_name`]
(Background on this error at: https://sqlalche.me/e/14/dbapi)

### Expected behavior
Views are properly ingested from HIVE, when config says so.

### Version:
    OS: Centos 7
    Python version: 3.10
    OpenMetadata version: 1.0.4
    OpenMetadata Ingestion package version: openmetadata-ingestion[hive]==1.0.4.4

### Additional context
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-DescribeTable/View/Column

**Comment by pmbrull** [comment]
We just supported the Impala scheme for Hive as a middle step while we were preparing the Impala Connector.

Hive data should only be ingested with the Hive scheme. We'll be deprecating the impala scheme from hive in 1.1.1.

If you have any issues ingesting Hive data, please open a separate issue explaining those so that we can tackle the root cause.

Thanks!
