### ISSUE TITLE
Support integrated lineage from spark (Spline) to OM entities

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12275]
This request as a suggest from Mayur Singal from conversation in Slack:
https://openmetadata.slack.com/archives/C02B6955S4S/p1688460524480109

**Is your feature request related to a problem? Please describe.**
Currently, we use 2 method to ETL data: 1, using SQL run directly in HIVE, 2. run spark to process. With method 1 I can use query log to create lineage. But with method 2, spark does not have any log on hive so I cannot get lineage from this method. I tried to use Spline to generate lineage from spark code but can not integrated lineage (which data source from HDFS) from Spline to current entities (of Hive) in OM. 

**Describe the solution you'd like**
Get Lineage generate by Spline from Spark and integrated each entities in lineage to currently entities (tables) in OM.
With example attached below:
- Spark job: Spark324
- From sonnb_agg14 and sonnb_aggttt  ---> sonnb_agg16
Expected: the lineage from spark will appear in 
- Database service (Hive table) : sonnb_agg14, sonnb_aggttt , sonnb_agg16 
- Pipeline service (Spline connector): Spark324

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/89b3b64a-e9c8-4bf8-959b-7a9cafd4a112)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/543b6a2e-1593-42df-8037-3035de6b4709)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/37a06f4f-e229-4c3a-8b20-740512226985)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/c9446836-1782-4f0b-9a04-f7e5e60b7aa3)

Thanks Team!

**Comment by ulixius9** [comment]
closing this in favour of https://github.com/open-metadata/OpenMetadata/issues/14362
