### ISSUE TITLE
Update Airflow Docker environment variables

### ISSUE THREAD

**Issue by fredericocotrim** [open-metadata/OpenMetadata#12282]
**Is some content missing, wrong or not clear?**
The environment variable names in the file [env-postgres](https://github.com/open-metadata/OpenMetadata/blob/main/docker/docker-compose-ingestion/env-postgres) of [docker-compose-ingestion](https://github.com/open-metadata/OpenMetadata/tree/main/docker/docker-compose-ingestion) don't match with the environment variable names of [docker-compose-ingestion-postgres.yml](https://github.com/open-metadata/OpenMetadata/blob/main/docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml).

**Describe the solution you'd like**
Rename the variable names:
DB_USER to AIRFLOW_DB_USER
DB_SCHEME to AIRFLOW_DB_SCHEME
DB_PASSWORD to AIRFLOW_DB_PASSWORD

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/42280776/e8ede760-d00f-4854-b794-ca30b773da97)

**Comment by akash-jain-10** [comment]
Hello @fredericocotrim  - This is fixed in the recent versions of Application! Let us know once you validate on your end! Closing this issue ticket!
