### ISSUE TITLE
Glossary Reviewer inheritance issues

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#12286]
we have one py test that does some [patch operations on the reviewers](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/tests/integration/ometa/test_ometa_glossary.py#L334) for glossaries and glossary terms that is picking up something strange.

the flow is:
1. We add a user1 and user2 as reviewers for the Glossary
1. Then we patch user1 as reviewer for the Glossary Term
1. The PATCH call result gives us a total of 3 reviewers:
    1. user1 appears twice (same id)
    1. user2

On this PR https://github.com/open-metadata/OpenMetadata/pull/12285 we are commenting out a test that was failing due to this. We should uncomment it in this same fix to validate the results

---

Another observation is that if I GET the glossary passing the ID, I get the correct reviewers (User1 and User2):

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/8ebfe558-9e11-49e0-ad8d-8e93f7eff459)

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/cc462d47-ad33-4115-8ae6-1a87701dac92)

The impact is that on the UI, reviewers are not appearing

**Comment by sureshms** [comment]
@pmbrull, the patch operation should not be adding a new user1 if done correctly? Is the patch being generated by hand or by using JSON patch diff tool?

**Comment by pmbrull** [comment]
> @pmbrull, the patch operation should not be adding a new user1 if done correctly? Is the patch being generated by hand or by using JSON patch diff tool?

@sureshms we are using the same `jsonpatch` lib that generates the diff itself

**Comment by sureshms** [comment]
@pmbrull is this still and issue?
