### ISSUE TITLE
Show the fully qualified name in the UI

### ISSUE THREAD

**Issue by gavinvx** [open-metadata/OpenMetadata#12284]
**Is your feature request related to a problem? Please describe.**
We use the API to interact with the data-catalog. The API can locate objects using ID or fully qualified name (FQN).
We allow users to upload data in excel spreadsheets and they identify objects using the FQN.
The users need to calculate this and get it wrong.

**Describe the solution you'd like**
Showing the fully qualified name in the UI for each object type would be a great help here.

**Describe alternatives you've considered**
The alternative solution is for the user to work it out using the information they see on the screen.

**Additional context**
No additional context

**Comment by harshach** [comment]
fullyQualifedName is already shown in the UI through the breadcrumbs
<img width="372" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/abb2db02-567c-4580-a8a9-9a4ccf67b81c">
