### ISSUE TITLE
The service password displays in clear text in the "review and deploy" panel of the "add ingestion" flow

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#1229]
Adding this as a blocker because it's preventing me from recording a video and producing gifs for docs on this feature.

**Comment by Sachin-chaurasiya** [comment]
@shannonbradshaw Thank you for filing the ticket.
This issue has been fixed by #1223

**Comment by Sachin-chaurasiya** [comment]
Closing as it's fixed by #1223

**Comment by shannonbradshaw** [comment]
Thanks, @Sachin-chaurasiya. I appreciate the quick response!
