### ISSUE TITLE
MSSQL Profiler `text`, `ntext` and `image` type

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#12329]
**Affected module**
Profiler

**Describe the bug**
`text`, `ntext` and `image` errors out when profiling MsSQL tables.

```
[2023-07-05 14:31:18,057] {profiler_interface.py:455} ERROR - bkp29112022_TBL_Contact.notes metric_type.value: (pytds.tds_base.OperationalError) Argument data type text is invalid for argument 1 of len function.

[2023-07-05 14:31:24,799] {profiler_interface.py:60} WARNING - Error trying to compute profile for bkp29112022_TBL_Contact.notes: (pytds.tds_base.OperationalError) The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator.
```

**To Reproduce**
Create a table with the mentioned data types and profile the table

**Comment by ayush-shah** [comment]
@TeddyCr all the three are going to be deprecated soon..

The ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead.
ref: https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver16

but as it's failing for the current versions, i have found an alternative, i.e. casting them to the said alternatives above, and as expected, they are working.

**Comment by ayush-shah** [comment]
Adding one more issue for mssql profiler as well..
`Argument data type text is invalid for count operator` and `Argument data type ntext is invalid for count operator`

**Comment by Jason-Clark-FG** [comment]
> @TeddyCr all the three are going to be deprecated soon..
> 
> The ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead. ref: https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver16
> 
> but as it's failing for the current versions, i have found an alternative, i.e. casting them to the said alternatives above, and as expected, they are working.

@ayush-shah how did you do this casting? Could you explain please? We are seeing the same errors. We cannot modify our source data currently, so we have to deal with it as it is...

**Comment by ayush-shah** [comment]
Hello @Jason-Clark-FG 
We have added the solution for the same here in https://github.com/open-metadata/OpenMetadata/pull/12490

More info here in the [code](https://github.com/open-metadata/OpenMetadata/pull/12490/files#diff-1737f92ac524dd0a49b2438b9d3ab393059f1fb61a535e370952a47d35b80b2eR39-R46)
      
      @compiles(CountFn, Dialects.MSSQL)
      def _(element, compiler, **kw):
          col_type = element.clauses.clauses[0].type
          if isinstance(col_type, (NVARCHAR, TEXT)):
              return "cast(%s as [nvarchar])" % compiler.process(element.clauses, **kw)
          if isinstance(col_type, CustomImage):
              return "cast(%s as [varbinary])" % compiler.process(element.clauses, **kw)
          return compiler.process(element.clauses, **kw)
