### ISSUE TITLE
Unable to ingest my database service redshift

### ISSUE THREAD

**Issue by neb382** [open-metadata/OpenMetadata#12331]
**Affected module**
Database Service -> Ingestion

**Describe the bug**
Tried different approchaes
a) via CLI, always got the message 
"Error initializing INGEST: Test connection definition for Redshift.testConnectionDefinition not found!"
But the example YAML does not contain any testConnection Definition nor the entire documentaion

so i tried a new approch and deployed the airflow Docker
Docker is running and i can use SSH tunnel to 8080, its up and running and i can login with the credentials from the stdout
admin / <strongpassword> 
I passed it along with the openmetadata.yaml "pipelineServiceClientConfiguration"
Also changed it apiEndpoint to the ip/port of the docker. 
I am not using SSL so the http with username/password should be enough, however in 
Openmetadata -> Settings -> Database Services -> Ingestions 
The error : "Authentication failed for user [admin] trying to access the Airflow APIs."
I changed the password in airflow and also in yaml and restarted everything but the error remains. 
When checking docker logs i can see the requests: 
"GET /api/v1/openmetadata/health-auth HTTP/1.1" 401 187 "-" "Java-http-client/11.0.18"
But when using a browser and pass username/password, than the api health-auth i got the response just fine. 
Something is missing or the password auth not working as intended 

**Expected behavior**
I would expect the ingestion workflow via UI

**Version:**
 - OS: oracle linux 7.9
 - Python version:  python3.9
 - OpenMetadata version: 1.0.5 and just upgraded 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==1.1.0`]

**Additional context**
using latest docker from today

**Comment by harshach** [comment]
@neb382 we have lot users running redshift connector successfully. Based on the errors you pasted here , it looks like you have config error. Please come to support channel and discuss before opening a github issue
