### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rosscdh** [open-metadata/OpenMetadata#12333]
**Affected module**
Ingestion Framework

**Describe the bug**
run:  metadata docker --start

```
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
```

**To Reproduce**

follow getting started instructions as of (9 July, 2023)

**Expected behavior**
metadata starts using docker.

**Version:**
 - osx 13.2 
 - Python version: Python 3.11.2 (venv)
 - whatever is latest (cant run version)
 - whatever is latest (cant run version)

**Additional context**
Would be nice to just have docker-compose.yml without multi step cli application that wraps docker

**Comment by harshach** [comment]
@rosscdh please join our slack to ask any questions around your installation at https://slack.open-metadata.org 
we do not support python 3.10 or 3.11. Please use 3.7 to 3.9
