### ISSUE TITLE
Sorting and ordering of queries

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#12347]
**Is your feature request related to a problem? Please describe.**
 Currently, the queries are sorted in random order. In case of any queries, it is good to sort by likeliness 

![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/89f57300-6788-4d02-98c4-6f6b17f90aa1)

**Describe the solution you'd like**

- Sort the queries by the next score of the likes & dislikes. 
- Or provide the sorting options i.e. By Update date time, By Likeness
- Additional feature best to have to allow the Owner to PIN the query at the top

**Describe alternatives you've considered**
Non-alternative, users have to scroll down even the query that is most liked may end up at the bottom.

**Comment by ShaileshParmar11** [comment]
fixed with https://github.com/open-metadata/OpenMetadata/pull/15591

**Comment by 17rahulsharma** [comment]
thanks for adding feature @ShaileshParmar11 . Filtering and sorting looks great in the video
