### ISSUE TITLE
Allow updating "Query used by other tables:" while editing query

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#12346]
**Affected module**
Impact on UI (maybe to the backend )

**Describe the bug**
Version (1.1.0  Sandbox)
Problem: Editing query allows to edit query however there is NO option to edit associated tables  "Query used by other tables:".

**To Reproduce**
More details at https://openmetadata.slack.com/archives/C02B6955S4S/p1688888141300939

![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/4d7fa97c-0d6f-43c8-8ed6-a854fab662ad)

**Expected behavior**
The expected behaviour is to allow editing of the "Query used by other tables:" while editing the query

**Comment by ShaileshParmar11** [comment]
Re-oping as UI side of changes pending.
