### ISSUE TITLE
Table name match convention

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#12341]
No regex, but generate it through the UI and create REGEX at runtime

**Comment by harshach** [comment]
@TeddyCr can you add more details about this ticket

**Comment by TeddyCr** [comment]
@harshach this is to add a data quality check that confirm a table name follows a specific convention (e.g fact_something,etc)

**Comment by pmbrull** [comment]
discuss if needs to be an app?

**Comment by harshach** [comment]
@TeddyCr @pmbrull this shouldn't be a test case. It should be an external app or a data contract to define the rules/convention etc.. making this a test case requires users to create one per table which doesn't make sense to define a global level configuration

**Comment by TeddyCr** [comment]
Make sense. The data contract approach seems good 😊
