### ISSUE TITLE
 Session Persistence Issue when Multiple Users Access Openmetadata on the Same Tab

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#12357]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ans  : UI

**Describe the bug**
When two users use the same tab to access openmetadata, an issue occurs where the second user sees the same page that the first user left off after logging out. This behavior is unexpected and compromises the privacy and security of user sessions.

**To Reproduce**
step 1 : User A logs into the website on a tab and accesses various pages.
step 2 : User A logs out of the website.
step 3 : User B logs into the website on the same tab without closing or refreshing it.
step 4 : User B observes that they are presented with the same page or content that User A left off.

**Expected behavior**
Each user should have an isolated session experience when accessing the website, regardless of whether they use the same tab. Upon logging out, the session of User A should be terminated, and User B should not have access to any of User A's data or progress.

**Version:**
 - OpenMetadata version: 1.1.0

**Comment by harshach** [comment]
Are we not clearing any local data in the browser? 
I am not able to reproduce this with SSO enabled.

**Comment by harshach** [comment]
@Supan90-Shah3006 can't reproduce this in safari or chrome using SSO or basic auth.

**Comment by Supan90-Shah3006** [comment]
Understood,First i need to enable SSO or basic auth. Can you please give me a steps to enable SSO or basic auth?

**Comment by chirag-madlani** [comment]
@Supan90-Shah3006 you can refer this: https://docs.open-metadata.org/v1.1.0/deployment/security
