### ISSUE TITLE
Add Ingestion Pipeline redeployment as a migration step

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#12366]
This requires to separate the DAO load and the Resource classes. Currently we cannot use the DAOs unless all the resource have been previously loaded.

We should allow using the DAO before having to start the full server.

Then, we can use the IngestionPipeline DAO to pick up all the necessary info from the db.

cc @sureshms @harshach

**Comment by harshach** [comment]
EntityRepository initiates all the repository/dao classes separately. This completes the issue described here
