### ISSUE TITLE
Optional dark mode

### ISSUE THREAD

**Issue by WarrenWittenborn** [open-metadata/OpenMetadata#12367]
Not a problem, just a nice to have.

I'd like an optional dark mode for the UI.   It seems common in the development community, particularly nice when one spends the whole day in front of a monitor.

**Comment by Horizon-cmchugh** [comment]
@WarrenWittenborn, was this ever implemented? Having a hard time finding an actual dark mode option despite the issue being closed.

**Comment by Nicolas-Parot-Alvarez-Paidy** [comment]
I haven't found any dark mode option in the doc.

There is partial customization possible for accent colors, but not the background. https://docs.open-metadata.org/latest/how-to-guides/guide-for-data-users/theme
Even if they add an option to change the background and default text color, I think a good dark theme would need a complete overhaul of the colors that would be complicated to do manually. It needs to be created by a UI designer.

I think it is worth reopening or creating a new issue for it. I guess we need more people expressing their support for it.
