### ISSUE TITLE
hive lineage Is it supported？

### ISSUE THREAD

**Issue by pj001** [open-metadata/OpenMetadata#12376]
Currently, it seems that there is no support for hive data lineage, only manual drawing is supported?

**Comment by hoangdh5** [comment]
I already has post request maybe the same request you propose. You can review here https://github.com/open-metadata/OpenMetadata/issues/12275

I suggest use Spline for get lineage from hive

**Comment by pj001** [comment]
I don't quite understand the meaning, it seems different. What I want to know is whether it supports Hive's data lineage analysis



&nbsp;


彭瘦瘦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月12日(星期三) 晚上7:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-metadata/OpenMetadata] hive lineage Is it supported？ (Issue #12376)





 
I already has post request maybe the same request you propose. You can review here #12275
我已经有职位要求，也许你提出同样的要求。您可以在这里查看#12275
 
I suggest use Spline for get lineage from hive
我建议使用样条函数从hive中获取血统
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
-
 直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by harshach** [comment]
@pj001 how do you run queries on Hive. Where are these queries are stored?
Example are your running CTAS queries on top of Hive and are they running using spark jobs or some other means

**Comment by pmbrull** [comment]
hi @pj001, we have not found any internal hive table/source where we can directly extract query history.

If you happen to have a file with hive queries, you can process them by following this [doc](https://docs.open-metadata.org/v1.1.x/connectors/ingestion/workflows/lineage/lineage-workflow-query-logs).

Thanks
