### ISSUE TITLE
Ingestion Pipeline - Capture deployed status in time series

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#12377]
Right now we have a single boolean property that knows if the pipeline is deployed or not.

We can expand this information and keep track of the status and any errors happening in the PipelineStatus prop.

This will be useful when preparing the more generic main dashboard to control Ingestion Pipelines and their evolution, as right now any deployment issues are not being taken stored

**Comment by harshach** [comment]
we need to store the summary of logs success/failure overall success of the pipeline and include a link to the log

**Comment by pmbrull** [comment]
duplicate of https://github.com/open-metadata/OpenMetadata/issues/11857
