### ISSUE TITLE
OM-1.1 lineage search does not search all visible nodes

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#12374]
**Affected module**
Lineage

**Describe the bug**
OM-1.1 lineage search does not search all visible nodes

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/1cb1f31c-799d-4d02-b81c-347b29ea0c1a)

**Expected behavior**
Able to search for any item currently displayed on screen.

**Version:**
 - OpenMetadata version: 1.1

**Comment by karanh37** [comment]
Fixed from #12257
