### ISSUE TITLE
Issue on the column lineage from SQL Server views

### ISSUE THREAD

**Issue by DykVanDyke** [open-metadata/OpenMetadata#12372]
**SQL Server metadata ingestion module**
The impact is on ingestion of metadata from SQL Server views and the resulting lineage

**Describe the bug**
After some tests with the help of @harshach , it has been understood that the SQL parser used in the metadata ingestion from a SQL Server view definition does not handles correctly the square brackets surrounding the column names.  The issue is reflected on the lineage which does not displays any of the column "level" lineage flows for such columns having square brackets on their names:
![SQLServer_view_Column_lineage_KO](https://github.com/open-metadata/OpenMetadata/assets/613812/02b491f1-db67-4d22-8f15-8143765fe9f8)

Bellow, you'll find an example of the SQL code for a view in SQL Server using the "square brackets" syntax, which causes issues to the parser, as well as a syntax without issues for the parser.

**To Reproduce**

*SQL code not well handled*
`CREATE VIEW [dbo].[vDMPrep]
AS
    SELECT
        pc.[EnglishProductCategoryName]
        ,Coalesce(p.[ModelName], p.[EnglishProductName]) AS [Model]
        ,c.[CustomerKey]
        ,s.[SalesTerritoryGroup] AS [Region]
        ,CASE
            WHEN Month(GetDate()) < Month(c.[BirthDate])
                THEN DateDiff(yy,c.[BirthDate],GetDate()) - 1
            WHEN Month(GetDate()) = Month(c.[BirthDate])
            AND Day(GetDate()) < Day(c.[BirthDate])
                THEN DateDiff(yy,c.[BirthDate],GetDate()) - 1
            ELSE DateDiff(yy,c.[BirthDate],GetDate())
        END AS [Age]
        ,CASE
            WHEN c.[YearlyIncome] < 40000 THEN 'Low'
            WHEN c.[YearlyIncome] > 60000 THEN 'High'
            ELSE 'Moderate'
        END AS [IncomeGroup]
        ,d.[CalendarYear]
        ,d.[FiscalYear]
        ,d.[MonthNumberOfYear] AS [Month]
        ,f.[SalesOrderNumber] AS [OrderNumber]
        ,f.SalesOrderLineNumber AS LineNumber
        ,f.OrderQuantity AS Quantity
        ,f.ExtendedAmount AS Amount  
    FROM
        [dbo].[FactInternetSales] f
    INNER JOIN [dbo].[DimDate] d
        ON f.[OrderDateKey] = d.[DateKey]
    INNER JOIN [dbo].[DimProduct] p
        ON f.[ProductKey] = p.[ProductKey]
    INNER JOIN [dbo].[DimProductSubcategory] psc
        ON p.[ProductSubcategoryKey] = psc.[ProductSubcategoryKey]
    INNER JOIN [dbo].[DimProductCategory] pc
        ON psc.[ProductCategoryKey] = pc.[ProductCategoryKey]
    INNER JOIN [dbo].[DimCustomer] c
        ON f.[CustomerKey] = c.[CustomerKey]
    INNER JOIN [dbo].[DimGeography] g
        ON c.[GeographyKey] = g.[GeographyKey]
    INNER JOIN [dbo].[DimSalesTerritory] s
        ON g.[SalesTerritoryKey] = s.[SalesTerritoryKey] 
;`

*SQL Code correctly handled*

`
CREATE VIEW dbo.vDMPrep
AS
    SELECT
        pc.EnglishProductCategoryName
        ,Coalesce(p.ModelName, p.EnglishProductName) AS Model
        ,c.CustomerKey
        ,s.SalesTerritoryGroup AS Region
        ,CASE
            WHEN Month(GetDate()) < Month(c.BirthDate)
                THEN DateDiff(yy,c.BirthDate,GetDate()) - 1
            WHEN Month(GetDate()) = Month(c.BirthDate)
            AND Day(GetDate()) < Day(c.BirthDate)
                THEN DateDiff(yy,c.BirthDate,GetDate()) - 1
            ELSE DateDiff(yy,c.BirthDate,GetDate())
        END AS Age
        ,CASE
            WHEN c.YearlyIncome < 40000 THEN 'Low'
            WHEN c.YearlyIncome > 60000 THEN 'High'
            ELSE 'Moderate'
        END AS IncomeGroup
        ,d.CalendarYear
        ,d.FiscalYear
        ,d.MonthNumberOfYear AS Month
        ,f.SalesOrderNumber AS OrderNumber
        ,f.SalesOrderLineNumber AS LineNumber
        ,f.OrderQuantity AS Quantity
        ,f.ExtendedAmount AS Amount  
    FROM
        dbo.FactInternetSales f
    INNER JOIN dbo.DimDate d
        ON f.OrderDateKey = d.DateKey
    INNER JOIN dbo.DimProduct p
        ON f.ProductKey = p.ProductKey
    INNER JOIN dbo.DimProductSubcategory psc
        ON p.ProductSubcategoryKey = psc.ProductSubcategoryKey
    INNER JOIN dbo.DimProductCategory pc
        ON psc.ProductCategoryKey = pc.ProductCategoryKey
    INNER JOIN dbo.DimCustomer c
        ON f.CustomerKey = c.CustomerKey
    INNER JOIN dbo.DimGeography g
        ON c.GeographyKey = g.GeographyKey
    INNER JOIN dbo.DimSalesTerritory s
        ON g.SalesTerritoryKey = s.SalesTerritoryKey 
`

**Expected behavior**
The parser from the SQL Server ingestion connector should be able to recognize the square brackets "syntax" and then allow for a column lineage recognition like in the belllow lineage flow:
![SQLServer_view_Column_lineage_OK](https://github.com/open-metadata/OpenMetadata/assets/613812/fac5bbc9-d6e8-4348-9fb7-dc8b81ac2a70)

**Version:**
 - OpenMetadata version: 1.1
 - SQL Server Database Service Metadata Ingestion Pipeline

**Comment by ulixius9** [comment]
similar issue for this query 

```
CREATE VIEW dbo.HIS_PATIENT_OP_DR_PRESC
AS
SELECT        dbo.HIS_PATIENT_INFO_EXT.PATIENT_INFO_PKNO, dbo.HIS_PATIENT_INFO_EXT.CHART_NO, dbo.HIS_PATIENT_INFO_EXT.SEX, dbo.HIS_REGISTRAION.REG_DATE, dbo.HIS_REGISTRAION.REG_TYPE,
                         dbo.HIS_OP_DTL.ICD_CODE, dbo.HIS_OP_DTL.ICD_CODE2, dbo.HIS_DR_PRESC.DELIVER_TIME
FROM            dbo.HIS_PATIENT_INFO_EXT INNER JOIN
                         dbo.HIS_REGISTRAION ON dbo.HIS_PATIENT_INFO_EXT.ID = dbo.HIS_REGISTRAION.ID INNER JOIN
                         dbo.HIS_DR_PRESC INNER JOIN
                         dbo.HIS_OP_DTL ON dbo.HIS_DR_PRESC.OP_DTL_PKNO = dbo.HIS_OP_DTL.OP_DTL_PKNO ON dbo.HIS_REGISTRAION.REGISTRAION_PKNO = dbo.HIS_OP_DTL.REGISTRAION_PKNO
```

**Comment by ulixius9** [comment]
closing this ticket as handled with openmetadata-sqllineage 1.1.2
