### ISSUE TITLE
Ingestions should be present in stats

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1237]
We need to add this only if we are continuing with stats data on Landing page

<img width="1792" alt="Screenshot 2021-11-17 at 10 29 00 PM" src="https://user-images.githubusercontent.com/86726556/142246423-d3940646-d0bb-48c7-b77c-6a236484e770.png">

**Comment by ShaileshParmar11** [comment]
Assign to me

**Comment by Sachin-chaurasiya** [comment]
@ShaileshParmar11 Assigned to you. Happy coding.
