### ISSUE TITLE
use user's displayName for Activity feed

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#12389]
**Affected module**
UI

**Describe the bug**
Currently activity feed uses user's name rather than display name for activity feed.
As for other Entities, it should use displayName if set, if name otherwise.

**To Reproduce**

Create a user with different name and displayName. Do an action. Check activity feed.

**Expected behavior**
As for other Entities, it should use displayName if set, if name otherwise.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 1.1]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Ashish8689** [comment]
@harshach  We will be needing support for `displayName` field form the FeedAPI `api/v1/feed`, currently we don't have it.

<img width="599" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/7e784894-7515-41d3-9265-cdef4a94f31e">

**Comment by harshach** [comment]
@karanh37 since we are building a cache of profile pics etc.. can't we use the same to show here?
