### ISSUE TITLE
Postgresql Profiler does not work with 11.19

### ISSUE THREAD

**Issue by isoctcolo** [open-metadata/OpenMetadata#12388]
**Affected module**
Profiler Ingestion

**Describe the bug**
I get an error like this from the generated Airflow injection job.

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "oid" does not exist
LINE 3: SELECT oid, polname, table_catalog , table_schema ,table_nam...
               ^

[SQL: /* {"app": "OpenMetadata", "version": "1.1.0.3"} */

SELECT oid, polname, table_catalog , table_schema ,table_name  
FROM information_schema.tables AS it
JOIN (SELECT pc.relname, pp.*
      FROM pg_policy AS pp
      JOIN pg_class AS pc ON pp.polrelid = pc.oid
      JOIN pg_namespace as pn ON pc.relnamespace = pn.oid) AS ppr ON it.table_name = ppr.relname
      LIMIT 1
]
(Background on this error at: https://sqlalche.me/e/14/f405)

And a second error for the profiler:
You fixed this in metadata but I think not in the profiler:

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column s.total_exec_time does not exist
LINE 7:         s.total_exec_time/1000 duration
                ^

[SQL: /* {"app": "OpenMetadata", "version": "1.1.0.3"} */

      SELECT
        u.usename,
        d.datname database_name,
        s.query query_text,
        s.total_exec_time/1000 duration
      FROM
        pg_stat_statements s
        JOIN pg_catalog.pg_database d ON s.dbid = d.oid
        JOIN pg_catalog.pg_user u ON s.userid = u.usesysid
        LIMIT 1
    ]
(Background on this error at: https://sqlalche.me/e/14/f405)

**To Reproduce**

Install 1.1.0 quickstart docker environment and connect to a 11.19 Postgresql database. Metadata works fine. Profiler data ingestion causes this error.

**Expected behavior**
Profiler Ingestion without errors.

**Version:**
 - OS: Ubuntu server system - running it in the quickstart docker environment 1.1.0
 - Python version: 3.9 
 - OpenMetadata version: 1.1.0
 - OpenMetadata Ingestion package version: what is included in the docker I would assume 1.1.0

**Additional context**

**Comment by harshach** [comment]
@ayush-shah whats the status? are we pushing this for 1.1.1

**Comment by isoctcolo** [comment]
The column is not missing it was just renamed from total_time to total_exec_time.

From my understanding a select version() to get the database version and then if it is 11.x then use total_time else use total_exec_time.

**Comment by ayush-shah** [comment]
Yes, we have the same implemented on the metadata ingestion side, we will centralize the same so it can be used by profiler as well
