### ISSUE TITLE
Allow passing of querystring to api urls in redoc

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1238]

**Comment by shahsank3t** [comment]
Duplicate of #1243

**Comment by harshach** [comment]
@shahsank3t @darth-coder00 this is not fixed right?
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/38649/143142118-c20dbd26-13f6-4e41-bf07-9cdabaf58fd9.png">
I don't see any options to pass in query params

**Comment by shahsank3t** [comment]
This is a duplicate of #1243 so closed this.
