### ISSUE TITLE
Assets not visible for "Child Columns" (1.1)

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#12399]
**Affected module**
Glossary

**Describe the bug**
1. I have a table. A column of STRUCT type has 2 child columns
2.   I have tagged the table, the primary column and the child columns with Glossary terms

ONLY the Glossary Terms tagging the Table and Primary Column, display Asset Info on the Glossary Term page.

**To Reproduce**

1. Create a table with child columns. 
2.  Tag with Glossary Terms the table, the Parent and the Children
3. Check  which terms display Asset

`        {
            "name": "Parent",
            "dataType": "STRUCT",
            "dataLength": 10,
            "dataTypeDisplay": "struct",
            "description": "Customer Number. Explicit search help attachment to field ",
            "fullyQualifiedName": "testcc.ECC.LO.KNA1.Parent",
            "constraint": "NOT_NULL",
            "ordinalPosition": 3,
            "children": [
                {
                    "name": "Child",
                    "dataType": "CHAR",
                    "dataLength": 10,
                    "description": "child",
                    "fullyQualifiedName": "testcc.ECC.LO.KNA1.Parent.Child",
                    "constraint": "NOT_NULL",
                    "ordinalPosition": 1
                },
                {
                    "name": "GrandChild",
                    "dataType": "CHAR",
                    "dataLength": 10,
                    "description": "grandchild",
                    "fullyQualifiedName": "testcc.ECC.LO.KNA1.Parent.GrandChild",
                    "constraint": "NOT_NULL",
                    "ordinalPosition": 2
                }
            ]
        }`

**Expected behavior**
All terms used for tagging columns / tables should show asset

**Version:**
 - Python version:
 - OpenMetadata version: [e.g.1.0]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by DovileKr** [comment]
Parent term tagged to column = shows asset
GrandParent term tagged to child column, assets 0

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/33ffe600-0fcb-4e3d-8b8e-8cb0cb82c66a)

**Comment by DovileKr** [comment]
still a problem for 1.1

**Comment by DovileKr** [comment]
Hi, do we have a roadmap fix for this bug?

**Comment by DovileKr** [comment]
@harshach still not there for 1.1.3, yes?

Example out of Sandbox: https://sandbox.open-metadata.org/table/BigQueryProd.modified-leaf-330420.sdoh_cms_dual_eligible_enrollment.nested_struct 

tagged struct column with https://sandbox.open-metadata.org/glossary/Lead.lead_address_city, but no assets is shown.

**Comment by 07Himank** [comment]
https://github.com/open-metadata/OpenMetadata/pull/13539 this will fix thie issue
