### ISSUE TITLE
áéíóú ÁÉÍÓÚ characters not allowed in glossary, glossary term, classification and tag names

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#12403]
**Affected module**
UI

**Describe the bug**
In  1.1.0 version á é í ó ú characters are not allowed now in glossary terms name. In spanish lang these characters are common and day to day used. 

**To Reproduce**
Reproduce with the UI for:

- new glossary
- new glossary term
- new classification
- new tag
.

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/112470575/5c826f3c-b7b4-4f03-86b6-db615352abe3)

![image](https://github.com/open-metadata/OpenMetadata/assets/112470575/6e07d944-857c-4643-9e15-930a4ea380aa)

![image](https://github.com/open-metadata/OpenMetadata/assets/112470575/9bf9f2e7-9926-4f0c-88f1-4f267d9ce2d1)

**Expected behavior**
As in previous versions allow latin characters like: á é í ó ú in name, by UI and API

**Version:**
OM 1.1.0
python 3.8

**Additional context**

**Comment by jromandv** [comment]
Hi, capital too. ÁÉÍÓÚ.

**Comment by Sachin-chaurasiya** [comment]
> Hi, capital too. ÁÉÍÓÚ. 

Thanks for filing the issue @jromandv , we are looking into it.
