### ISSUE TITLE
Optimize the way OM capture pipelines from Spline

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12405]
This issue is related to the conversation in Slack here: https://openmetadata.slack.com/archives/C02B6955S4S/p1689158699667649

**Is your feature request related to a problem? Please describe.**
We just create an integrated Spline service to catch the lineage on Hive. Our problem is the number of pipelines is increase each time someone executes in Hive and it means each day may be around 100-200 pipelines was created.
Example: if I execute the query "Insert into table A  from table B" 10 times, then 10 pipelines were created. 

As Mayur Singal said that OM are reflecting what we see in spline so after a long time of operation, the number of pipelines may increase very fast and be hard to manage in OM.

**Describe the solution you'd like**
Should we found a solution to merge these pipelines and show in OM like a history of executed instead of individual pipelines.

![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/cb9e5da4-795b-42c5-97d4-cf7f68688828)

**Comment by hoangdh5** [comment]
Hi Team, 
Could we set a priority or any specific plan for this issue? The number of our pipeline OM capture from Spline was increasing so fast.

**Comment by pmbrull** [comment]
hi @hoangdh5 can you share some more details on your spline configuration? In our setup, we are not getting different pipelines after each run from the API. Would like to understand if this is something that can be fixed on Spline itself (and we can document it) or if it's worth it to handle it on the code.

Thanks

**Comment by hoangdh5** [comment]
As I understand, Spline stores lineage by event each time the spark job executes Spline creates a new pipeline to store lineage information. So the problem is Spline does not merge pipelines that represent the same lineage (or come from the same spark job).
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/92107a0f-943a-44c2-8ca0-90c80b823c26)

**Comment by harshach** [comment]
@ulixius9 @pmbrull lets drop the spline support and directly integrate with spark as we discussed.
