### ISSUE TITLE
Enhancement for Lineage graphs

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#12433]
**Is your feature request related to a problem? Please describe.**
Complex lineage graphs are too dense to derive meaningful information and take too long to load.

![image](https://github.com/open-metadata/OpenMetadata/assets/102999683/fa9e2d9d-69bf-4052-9f17-ee10a9b3896c)

**Describe the solution you'd like**

1. Add two filters for the number of upstream and downstream nodes to be shown. This should improve load time for the graph. We have some tables with 300 direct downstream dependencies that themselves have downstream dependencies and the graph just wouldn't load.
2. Add a noise filter to show the critical downstream dependencies only. Users can move a slider up and down to see more or less information. The importance of a downstream node can be determined based on it's usage, which we already have. This should allow me to derive more insights from the graph vs just being overwhelmed.
3. Show the number of total and direct upstream and downstream nodes. This is powerful information that should already be available. 
4. The edges and nodes should be organized in a compact way so users don't need to scroll a lot over the entire map.

**Comment by harshach** [comment]
@trillhaa take a look at 1.1 releaase where we added pagination support. Let us know if its solves your usecase

**Comment by trillhaa** [comment]
This came out very nicely with the version 1.1. My primary concern is addressed with this.
@harshach - what do you think about request 3 for showing total up-and downstream nodes? It's a nice-to-have add-on features, agree, not impacting the user experience.

**Comment by karanh37** [comment]
Fixed with 1.3 release.
