### ISSUE TITLE
Profiler Idle Database Connections

### ISSUE THREAD

**Issue by joal-zb** [open-metadata/OpenMetadata#12432]
**Affected module**
Profiling

**Describe the bug**
Idle database connections left open by the profiler between runs

**To Reproduce**

It's not clear on how to reliably reproduce this issue, as connections appear to be cleaned up after additional invocations of profiling against the same GCP CloudSQL (postgres) database.

The particular cloud sql instance where we are experiencing this issue hosts many individual databases, and we're allow open metadata to profile each database on the instance.

**Expected behavior**
All open metadata database connections are reliably cleaned up after profiling.

**Version:**
 - OS: CentOS
 - Python version: 3.9
 - OpenMetadata version: 1.0.1.1
 - OpenMetadata Ingestion package version: 1.0.1

**Additional context**
Ive attached a screen shot that shows database connection count metrics over ~1 week between our profiling runs. In our case, we only run the profiler once a week.
![Screen Shot 2023-07-13 at 12 33 14 PM](https://github.com/open-metadata/OpenMetadata/assets/68868373/21c225c5-e5c8-4090-a9e6-85c8a1be6b55)

We verified that the idle connections are coming from open metadata by running the following query on one of our databases being profiled: 
```sql
SELECT *
FROM pg_stat_activity
WHERE datname = 'webservices'
AND usename = 'openmetadata'
LIMIT 50
```

**Comment by pmbrull** [comment]
this should be done in 1.1.1
