### ISSUE TITLE
Members of the group, that owns the object, can't resolve a task

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#12459]
**Affected module**
backend

**Describe the bug**
Members of the group, that owns the object, can't accept tasks to change the description (click on "Accept Suggestion" button, but nothing happens)
Also, they can't close these tasks without edit. (can't see "Close" button, only "Accept Suggestion" and "Edit & Accept Suggestion")

**To Reproduce**
![group_problem](https://github.com/open-metadata/OpenMetadata/assets/61934044/f50ca0e6-5f72-4d8c-9d26-9428581fced7)

1) I have created a "TEST GROUP TWO" group with no associated roles and policies. 
2) Added the user "employee_3" to it. 
3) Assigned this group as the owner of the "ERP_USER" table.
4) Another user "employee_1" created a task to change the description and associating it with a group-owner.
5) (look at record) After that, "employee_3" tries to accept the task, presses the "Accept Suggestion" button, but nothing happens. Also, he does not see a button to close task. Only "Accept Suggestion" and "Edit & Accept Suggestion"

**Expected behavior**
Any user of the group that owns the object, if there is an Organization Policy by default and there are no other restrictive policies, should have the right to accept or reject proposals to change the description of the object. (accept or close task)

**Version:**
OpenMetadata version: 1.1.0

**Comment by harshach** [comment]
@chirag-madlani lets add test coverage around this

**Comment by Sachin-chaurasiya** [comment]
@harshach @mohityadav766 
If a task is given to a team, and a team member who is currently logged in attempts to resolve or close the task, they will encounter a permission error.

```js
{
    "code": 403,
    "message": "Principal: CatalogPrincipal{name='customermail2020'} operations resolveTask not allowed"
}

{
    "code": 403,
    "message": "Principal: CatalogPrincipal{name='customermail2020'} operations closeTask not allowed"
}
```

**Comment by harshach** [comment]
cc @sureshms
