### ISSUE TITLE
Export lists of entities from Open Metadata to a csv file

### ISSUE THREAD

**Issue by LKMcGrath** [open-metadata/OpenMetadata#12467]
**Is your feature request related to a problem? Please describe.**
For example, the boss asks for a list of data matching specific parameters, and we search in Open Metadata.  It would be good to export the results so they can be emailed to the boss.

**Describe the solution you'd like**
I would like a button on the Explore page that exports all the displayed tables to a csv file.  This should include all the main fields for the table.  Something like the image below where clicking the button would export the 13 results: 
![image](https://github.com/open-metadata/OpenMetadata/assets/108548597/a372bf0b-9835-4640-b0b6-eda585b3c757)

**Describe alternatives you've considered**
I tried copy and pasting, but it doesn't work very well, especially for long lists.

**Comment by sureshms** [comment]
@LKMcGrath  At present, you should be able to send the search URL to others. This should present the search results in a user-friendly manner to everyone instead of a hard-to-consume CSV file. Wdyt?

**Comment by harshach** [comment]
import/export APIs are supported for Databases/schemas/tables
