### ISSUE TITLE
[DBT] Bad Naming in case testCases/testSuites coming from dbt

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#12465]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Actaul :- dwh_prod.dwh_prod.dbt_integration_layer.IL_value_prompter_F."Id".unique_IL_value_prompter_F__Id_
Expected :- dwh_prod.dwh_prod.dbt_integration_layer.IL_value_prompter_F.Id.unique_IL_value_prompter_F__Id_

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by OnkarVO7** [comment]
Tested this with the latest main the issue is not appearing there. Test case FQN gets created properly
