### ISSUE TITLE
Case sensitivity of user entity name in Azure SSO

### ISSUE THREAD

**Issue by pinkerltm** [open-metadata/OpenMetadata#12475]
**Affected module**
Azure SSO

**Describe the bug**
After logging in through Azure SSO a new user_entity is created with (basically) my E-Mail address. Because of the ActiveDirectory Toolset which is used to administer the Azure AD, a lot of these E-Mail addesses are written with capital letters (like 'Juergen.Zornig' in my case). In the database the user_entity object is created exactly like this, so the user exists now. But In the App OM tells me 'user instance for "juergen.zornig" not found', therefore I don't have any rights or privileges at all.

**To Reproduce**

1. Login via Azure SSO with a new (not logged in before) user
2. User gets created, Userid is taken from email (cannot be modified)
![grafik](https://github.com/open-metadata/OpenMetadata/assets/6107708/d2554fbf-3c0d-46ea-8cdc-df0136582bc6)

3. Logged in, but without User Profile
![grafik](https://github.com/open-metadata/OpenMetadata/assets/6107708/aceb9710-14a2-428c-8213-70b5836ff47b)

**Expected behavior**
There is a fitting user profile after a (Azure SSO) user is created by OM

**Version:**
 - OS: Docker Host is Ubuntu Server 22.04.1
 - OpenMetadata version: Docker Deployment for OM 1.1
 - OpenMetadata Ingestion package version: Docker Deployment for OM 1.1

**Additional context**
We are using docker compose to directly execute the containers using the downloaded docker-compose-postgres.yml file with the additional --env-file flag as noted in the instructions (so Postgres Backend on Docker) 

After Logout and logging in again, I get back to the "create user" modal which tells me, that the user already exists. So no chance to login again without deleting my userid in the database backend.

**Comment by harshach** [comment]
@mohityadav766 did we address this in reelase 1.1.1?

**Comment by harshach** [comment]
Fixed in 1.1.2 and 1.1.4
