### ISSUE TITLE
Enable pymssql dependency 

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#12480]
pymssql build is failing due to the below issue listed in their repo
https://github.com/pymssql/pymssql/issues/826

Enable back the dependancy once the above issue is fixed

**Comment by harshach** [comment]
@OnkarVO7 @ayush-shah any updates?

**Comment by pmbrull** [comment]
pymssql project needs to publish windows and linux wheels https://pypi.org/project/pymssql/2.2.8/#files. Once that is published, we can bump the version for this specific scheme
