### ISSUE TITLE
MSSLQ handle multiple databases with pyodbc connection

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#12485]
currently for pyodbc connection database field is required so when we pass the database name it only ingests the data for that particular database and not all the databases, so add a flag includeAllDatabases like we do have it for postgres and redshift database.

also clearly specify this behaviour in docs to avoid any confusion. 

also as part of this ticket we can also add the ssl options required for odbc connection i.e the required connection arguments `Encrypt: Yes, TrustServerCertificate: No`

**Comment by vanshika18** [comment]
I will do this task, please assign it to me.
