### ISSUE TITLE
Lineage ingestion not properly setup when service name contains spaces

### ISSUE THREAD

**Issue by rudydel** [open-metadata/OpenMetadata#12523]
**Affected module**
UI (fix could be here), and Ingestion Modules

**Describe the bug**
When a database service name contains space characters, the generated lineage ingestion name keeps those spaces and they appear in the underlying Airflow scripts, provoking errors and impossibility to run and check lineage ingestion DAGs

**To Reproduce**

- Create a database service name containing a space (say "**Servicewith Spacechar**")
- Create a metadate ingestion (ingestion default name is OK, all special chars replaced by _: "**Servicewith_Spacechar_metadata_xxxx**")
- Run it
- Create a lineage ingestion (ingestion name is not editable and will keep the spaces: "**Servicewith Spacechar_lineage**")
![omd_lineage_ingestion_naming](https://github.com/open-metadata/OpenMetadata/assets/29460578/718dea4b-d08a-4527-bd87-951be695fe5f)
- You will not be able to run the lineage ingestion or view logs, etc. due to space chars being carried on to the Airflow API calls.
![openmetadata_airflow_error](https://github.com/open-metadata/OpenMetadata/assets/29460578/e45d48fc-46be-48c2-a725-d5e301b44132)

**Expected behavior**
When creating a lineage ingestion within a database service, the ingestion name should have its special characters replaced.
It works fine when using "_" instead of spaces when creating the service name.

**Version:**
 - OpenMetadata version: 1.1.0

**Fix:**
I initiated #12521

**Comment by harshach** [comment]
Thanks @rudydel the PR is merged in for 1.1.1

**Comment by rudydel** [comment]
> Thanks @rudydel the PR is merged in for 1.1.1

Amazing! My first contrib here. OM is great. Too bad I commited without logging with my GitHub account so I'm still not officially a contributor. Oh well!
Hopefully I'll make other fixes!
