### ISSUE TITLE
SQLite Authentication Issue

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#12522]
**Describe the bug**
While Configuring SQLite Connector, Test Connection is running successful even if we enter any wrong value or leave empty all values of the form

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/41a2ad46-2530-4798-bbe1-0d4b6a26ca65)

**Expected behavior**
Authentication layer has to provide for SQLite connector which authenticate credentials are valid or not. If Credentials are valid test connection should be successfull otherwise it should failed.

**Version:**
 - OpenMetadata version: 1.1.0

**Comment by vanshika18** [comment]
I will take care of this issue.

**Comment by Supan90-Shah3006** [comment]
@pmbrull @vanshika18 , is this issue resolved?
