### ISSUE TITLE
total testcount count doesn't match per table

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#12538]
**Affected module**
Data Quality

**Describe the bug**
On Data Quality pages (per Table), testCase count don't match. 
**By Tables**: top bar "total tests: 242". Sum rows underneath - 8.

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/91419f77-dfde-4108-80cc-2f95fadf844c)

First three tables actually have around 200 tests on them (all column tests):  but when you go into them - the counts don't match.
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/12cfd842-872e-4870-9558-f5f517cff2a1)

also, one table with a lot of tests is not loading results and erroring with 

`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.21.5</center> </body> </html>      
`

**are we excluding custom tests by mistake?**

**Expected behavior**
total counts match individual counts

**Version:**
 - OpenMetadata version: [e.g.1.1]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
@DovileKr thanks for this info. Regarding the timeout issue and the performance we have pushed some improvement in the `main` branch that should be available in a patch release soon. Regarding the count for test summary, were these test cases created using the API?

**Comment by DovileKr** [comment]
@TeddyCr , yes, all those tests were external and results are being created and result send via api:

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/37efb69c-ccc0-4ed4-8da8-6e8f19073854)

**Comment by DovileKr** [comment]
But actually, I looked at custom tests out of omd - they are also not showing results

**Comment by harshach** [comment]
@TeddyCr is this still an issue with recent changes?

**Comment by TeddyCr** [comment]
Good to close
