### ISSUE TITLE
Can not add ingestion pipeline for Testsuite

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12544]
Slack conversation here: https://openmetadata.slack.com/archives/C02B6955S4S/p1689933249988789

**Affected module**
- Ingestion Framework

**Describe the bug**
For a table which does not have any test case, go to pipeline then Add Ingestion then click, OM will move to 404 page.
For a table which has at least one test case, go to pipeline >>Add Ingestion button not appear. I can not create any Pipeline for any Testsuite. 

For Testsuite default for each table, It's not shown on the Data Quality page (test suite tag) so we can not adjust (add or remote) testcase belonging to Testsuite default. If you have some testcase not ready for run, the only way is to delete it then it will not run with other testcase in Testsuite default.

**To Reproduce**
Screenshots or steps to reproduce

![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/12ff6a0b-013f-4f1d-b32e-de248233b5d8)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/f94fc371-a5db-44c2-b6e2-a2ef947f9013)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/c03c55da-d9c4-404c-a03c-54bb39a82ef6)

**Expected behavior**
 - User can select testsuite and add pipeline in Data Quality
 - User can add/remote Testcase in Testsuite default and TestSuite Default should be appear in Dataa Quality Page 
 - Testcase maybe need a flag (Activate/DeActivate) so when Run Test Suite only Active Testcase is run in stead of delete Testcase or remove from Test Suite.

**Version:**
 - Python version:
 - OpenMetadata version: OM 1.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by hoangdh5** [comment]
Hi @ShaileshParmar11, how about this expect behavior: "User can select testsuite and add pipeline in Data Quality
User can add/remote Testcase in Testsuite default and TestSuite Default should be appear in Dataa Quality Page
Testcase maybe need a flag (Activate/DeActivate) so when Run Test Suite only Active Testcase is run in stead of delete Testcase or remove from Test Suite"

#12575 as I understand only fix issues related to redirect 404.

**Comment by ShaileshParmar11** [comment]
ok, the issue got closed by mistake, we need to think about other points, and yes the current solution in #12575 is related to redirection. @hoangdh5

**Comment by harshach** [comment]
@hoangdh5 CustomTestsuites are more like dashboarding. If a test is created, it will execute in the context of Table's test suite itself.
You can create a custom test suite to pick and choose testcase across multiple tables and create a dashboard. If the testcase is already running as part of another table's test suite why do you want to re-run them and add another pipeline to CustomTestsuite

**Comment by hoangdh5** [comment]
@harshach In operation, some case need to execute testcase not in scheduled, like have to check urgent issues or adhoc request from bussiness unit, or sometime I just want to run a newly testcase added, I have to run all other . Or other usecase like you have some different kind of testcase, and these have to run in different schedule ?. That would be bad if i have to deleted some testcase just because I don't need run it adhoc. I see we have only one testsuite for each table and so only one schedule for all of testcase. I think we can use testsuite for more features not only for group of result/ dashboarding.

**Comment by TeddyCr** [comment]
Thank you @hoangdh5 for you suggestion. We value your feedback and the contribution you make to enhance the product. We'll be closing this issue as won't fix.

OpenMetadata used to allow execution of logical testSuite where test could be group logically from different tables and executed. Based on the feedback we gather we found it was not the most optimal approach as it created opportunities to duplicate tests and also required users to think about the table refresh schedule to set up the test case. We believe executing all the test cases linked to a table is the best practice to ensure consistent data quality. 

Thank you for all your contributions and feedback
