### ISSUE TITLE
Container hierarchy for custom storage types

### ISSUE THREAD

**Issue by joshliberty** [open-metadata/OpenMetadata#12549]
**Is your feature request related to a problem? Please describe.**
I use a custom connector to ingest buckets from GCP. I organise them in a container hierarchy, but it's not possible to see that hierarchy in the UI.

**Describe the solution you'd like**
1. The breadcrumbs on a child container should show the parents - on the search page and on the container page
2. Bonus: it would be great to be able to search or filter by parent, or at by hierarchy level (depth)

**Describe alternatives you've considered**
Using the description or a custom property on a child bucket to link to the parent, but that's a hacky workaround.

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/12294

**Comment by joshliberty** [comment]
Reopening - the container page was indeed fixed with #12294, but the search page wasn't:
![image](https://github.com/open-metadata/OpenMetadata/assets/1472923/8af6860c-c840-496d-9570-10cd1d3f7cd7)

**Comment by Sachin-chaurasiya** [comment]
> Reopening - the container page was indeed fixed with #12294, but the search page wasn't: ![image](https://user-images.githubusercontent.com/1472923/255197692-8af6860c-c840-496d-9570-10cd1d3f7cd7.png)

Search page related ticket https://github.com/open-metadata/OpenMetadata/issues/12552
