### ISSUE TITLE
show both table and column information under the asset

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#12540]
**Is your feature request related to a problem? Please describe.**
I did check 1.1. For example term First Name (https://sandbox.open-metadata.org/glossary/Banking.Account) has been tagged to table https://sandbox.open-metadata.org/table/sample_data.ecommerce_db.shopify.raw_customer columns comments and creditcard.
Yes, I can click on the preview, but because the columns in the question have a few tags - I don't see the tagged term just a  +3 more and +4 more https://sandbox.open-metadata.org/glossary/Banking.Account/assets: 

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/92d5e1bb-ae63-4660-9fbb-917f75019c23)

**Describe the solution you'd like**
Ideally, under the asset tab, it would display the column info. Linking the business term to a column (is this what was tagged to) is important for UX. because this is what I am looking for. 

**this would be very useful to see that the same business term is being called differently across the business applications**. for example: customer_id, client_number, consumer_id, partner_number.

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/4477fbba-3392-4c64-b0f2-a4b3f9d20a52)

**Describe alternatives you've considered**
using both tags (for linking the asset) and adding technical name as synonym (for user information).

**Additional context**

**Comment by harshach** [comment]
@karanh37 can you take this up? as part of our ongoing asset page changes
