### ISSUE TITLE
MDM - Capability to identify and highlight external data from business applications

### ISSUE THREAD

**Issue by aitkar** [open-metadata/OpenMetadata#12558]
**Is your feature request related to a problem? Please describe.**
In my organization, we use a central MDM tool as the main data reference for all business applications. When these applications engage with data not already present in our reference, these data points are automatically identified and subsequently added to the reference, post validation by a Data Steward or similar role. This process can be quite manual and time-consuming and we'd like to improve our capacity to control data quality in an automated manner.

**Describe the solution you'd like**
We would like OpenMetadata to provide a feature that can identify and highlight data from business applications that exist outside of our unique reference. We're looking for an automated way to flag these external data points so that they can be more effectively managed. This will streamline our data management process and improve overall data quality.

**Describe alternatives you've considered**
We have considered developing an in-house solution to address this issue but believe that such a feature could be beneficial to all users of OpenMetadata, hence our feature request. We've also thought about manually checking for and managing external data points but this method is not sustainable given the growing volume of data.

**Additional context**
Managing our data effectively is a key priority in our organization and this feature could significantly enhance our ability to do so. We also believe that this functionality could be beneficial to other users of OpenMetadata as it could provide a more robust mechanism for managing data points that exist outside of a central reference. Thank you for considering this feature request.

**Comment by hoangdh5** [comment]
I have the same interest in this issue, but I think I could describe the other way of this feature.
***Describe the solution you'd like
1/ Create a new page like Reference Data Management where the user can create and manage Set of Value:
----- Set of Value information
 - Name of Set
 - Description of set
 - List of Value
 - List of abnormal Value
 - -- Value information---------
 - Name of Value
 - Description of Value
2/ New Field on Schema to tag Column to which set of values based on  business and description of each column
3/ Add new profiler task: Compare the value of the column with the set of values to find out which is an outlier and report to user.

Not sure is same what u want @aitkar, If not let me know and I will ask in other post. Thanks!

**Comment by aitkar** [comment]
Thank you @hoangdh5 for your response.

I understand your preference. I would like OpenMetadata to directly connect to our central MDM tool instead of managing a separate list of values within OpenMetadata. This would allow OpenMetadata to retrieve real-time reference information from our MDM and use it to identify data coming from external business applications that are not part of the reference.

The advantage of this approach would be automatic synchronization with our MDM (which is on a simple SQL Server database), ensuring that the data used in our business applications always matches the current reference values, without the need for manual maintenance of value lists in OpenMetadata.

Moreover, starting with a simple and easy-to-implement solution in OpenMetadata would be a good first step. We can build upon it and gradually enhance the functionality.

Thank you for considering this suggestion. Your feedback and support are appreciated.

**Comment by harshach** [comment]
@aitkar @hoangdh5 any reason for not using a Container entity to denote the data that's coming in externally?

**Comment by aitkar** [comment]
@harshach 
Thank you for your suggestion of using a 'Container' entity to represent the incoming external data. 
This is an approach I haven't considered, and I am interested in learning more about how this could work. Could you provide me with more details on how I might use a 'Container' entity to implement this functionality? For instance, how might the 'Container' entity interact with my central MDM tool to identify and manage data that is not already present in our reference? And how could I use this feature to enhance our data quality in an automated way?
