### ISSUE TITLE
Enhancement the use of Resolution info in DQ

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12559]
This request is a suggestion from a Slack conversation with Suresh
Link here: https://openmetadata.slack.com/archives/C02DZK3QH8Q/p1688694520328999

**Is your feature request related to a problem? Please describe.**
In OM 1.1, we have a new feature Resolution, which use to flag the status of each Testcase result. But I think this feature is still limited
We only can change the status, only Resolved comes with a Comment to note but this info only shows in each test case.
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/f5d6872e-eb85-4593-a9ca-abc6ab6505fb)

**Describe the solution you'd like**
1/ Describe workflow (nice to have)
--> Run test case --> Get status ='**New**' --> Change Status to **Ack** & Tag **Priority** & **people** to handle issues
--> Person in charge update Reason or Solution to solve issue --> tag People to approve or Validate Solution/ Results after Ack
--> Change status to Resolved if pass

Noted: 
- These action should be shown in the tab Action in Schemas, currently only show the reason in each Testcase status.
- Issues should be can not change status after marked Resolved. Currently, we can change back and forth.

2/ New tab on Data Quality page to have a single place to view all issues by Priority, Status, Person in charge, Comment & Reason/ Purpose ... Here user can also change status and note directly without coming to each Table and test case to update.

Here user can view some summary info, how many issue is solve, how mana is pending.... by Schema/ Source/ Owner

![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/a59ebfad-6517-47e0-a331-f766b17943f0)

**Describe alternatives you've considered**

**Additional context**

**Comment by TeddyCr** [comment]
@hoangdh5 you can track the "enhanced" approval workflow implementation here https://github.com/open-metadata/OpenMetadata/issues/13746. As far as "New tab on Data Quality page to have a single place to view all issues" this had been planned as a Collate SaaS feature. 

Thanks for sharing the feedback.
