### ISSUE TITLE
Ingested DB data keeps disappearing

### ISSUE THREAD

**Issue by ds201ues** [open-metadata/OpenMetadata#12573]
**Affected module**
UI, Backend

**Describe the bug**
Data keeps disappearing

**To Reproduce**

<img width="981" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/33284199/2b4ce3fa-8a42-4f74-b3b7-6e6c9d288c7c">
<img width="1365" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/33284199/946d0329-dda9-4978-96dc-edd9d1a3516e">

**Expected behavior**
DB data once ingested should not be deleted

**Version:**
 - OS: [e.g. iOS] - MacOS 13.4.1
 - Python version:
 - OpenMetadata version: 1.1
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by harshach** [comment]
@ds201ues please come to slack https://slack.open-metadata.org and discuss your issue before opening a ticket.
This looks like a configuration issue or installation issue on your side.  We do not have anyone losing any data.
