### ISSUE TITLE
Ingestion workflow changes are not being updated on Airflow

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#1257]
After updating the Ingestion workflow from UI, changes are not reflected on the Airflow.
for e.g, if I update the schedule interval then on our backend it is changing but on airflow, it's not.

**Comment by harshach** [comment]
@Sachin-chaurasiya 
@darth-coder00 can we use put for this instead of patch. I don't want to workflow to be deployed on patch

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya @darth-coder00 can we use put for this instead of patch. I don't want to workflow to be deployed on patch

@harshach yeah we can, would make the changes.
