### ISSUE TITLE
Move child glossary terms back to top-level

### ISSUE THREAD

**Issue by oscarkuovista** [open-metadata/OpenMetadata#12596]
# Problem
On the glossary section, looks like once a term is moved under a parent you can no longer move it back to top-level

# Proposed Solution
A user should be able to drag'n'drop a child term back to the top-level term

# Describe alternatives you've considered
Instead of drag'n'drop, maybe a kebeb menu item to remove parent will work too.

**Comment by Ashish8689** [comment]
@harsha Currently we are not supporting moving of glossary term to the parent glossary or to the glossary child, so we will need BE support for this.

- Moving from glossary Term to Glossary
- Moving the Glossary Term child to the Glossary Term Parent.
