### ISSUE TITLE
Column Filter Pattern Ingestion Profiler Sample Data

### ISSUE THREAD

**Issue by aitanajimenez-facephi** [open-metadata/OpenMetadata#12601]
**Is your feature request related to a problem? Please describe.**
According to 'Profiler Ingestion', when I try to do a sample data, there isn't a way to create a filter by columns.

Nowadays there are three kinds of filters:
- Database Filter Pattern
- Schema Filter Pattern
- Table Filter Pattern

**Describe the solution you'd like**
I want ingest sample data only in the columns that I want in a specific table
Nowadays there are three kinds of filters:
- Database Filter Pattern
- Schema Filter Pattern
- Table Filter Pattern
- _'Column Filter Pattern'_

**Additional context/Example**
I tried this:
1. Exclude record_source column
2. Do a profiler ingestion only with the table that I exclude record_source
3. It ingests this column exclude

![Captura de pantalla 2023-07-25 a las 16 12 28](https://github.com/open-metadata/OpenMetadata/assets/114978003/676b67be-6da1-49b2-9896-c046070fd5ad)
![Captura de pantalla 2023-07-25 a las 16 13 01](https://github.com/open-metadata/OpenMetadata/assets/114978003/158df855-efdd-4e40-a34e-ffa1ebf4a7ce)
![image](https://github.com/open-metadata/OpenMetadata/assets/114978003/611744da-19ef-4c14-b238-06bfa1cc85b7)

I try and it's not work. When I exclude a column and I do a ingestion only in this table, it ingests wherever it wants

**Comment by harshach** [comment]
@aitanajimenez-facephi we have a configuration to exclude which columns you want at each table level 
<img width="1868" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/7b93506d-ba0f-4f6d-b841-b028c39a6824">
give this a try

**Comment by ulixius9** [comment]
@harshach we tried this out with this support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1690283169203589

**Comment by aitanajimenez-facephi** [comment]
@harshach I tried with this configuration to exclude which columns I want, and after I did a 'profiler ingestion' in to view the 'sample data' and the ingestion added sample data in all columns, without excluding the one you indicate in this configuration

**Comment by DovileKr** [comment]
Just to add to an idea, since this is being worked. We have a POS system, it has more than 700 tables. This being a COTS solution, not all tables are in use and some are empty (zero rows). 

No, I of course don't want to ingest all of them... I could either go and ask IT to give me a list of non-empty tables and then have a very detail table name filter pattern (yes, they are all in the same schema). 

Or.. maybe I could have a filter pattern to exclude tables with zero rows :)

**Comment by harshach** [comment]
@pmbrull the above worth looking into during the metadata ingestion process.

**Comment by TeddyCr** [comment]
> Just to add to an idea, since this is being worked. We have a POS system, it has more than 700 tables. This being a COTS solution, not all tables are in use and some are empty (zero rows).
> 
> Now, I of course don't want to ingest all of the empty tables... I could either go and ask IT to give me a list of non-empty tables and then have a very detail table name filter pattern (yes, they are all in the same schema).
> 
> Or.. maybe I could have a filter pattern to exclude tables with zero rows :)

This can be tracked here 👉 https://github.com/open-metadata/OpenMetadata/issues/12842
