### ISSUE TITLE
Lineage & Usage Ingestion for Oracle error 

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12621]
Slack conversation with Onkar Ravgan: https://openmetadata.slack.com/archives/C02B6955S4S/p1690455705752759

**Affected module**
Lineage & Usage Ingestion

**Describe the bug**
1/ Lineage Ingestion: Currently OM using gv$sql then we don't have a schema name when parsing lineage from querylogs. In some cases, if the database has multiple tables that have the same name and are stored in different schema then if query logs do not come with the schema name, every table having the same name will be linked to the same lineage.

2/ Usage Ingestion:  In case user (for connection) not granted to view gv$sql the workflow will get error, but at the end, that workflow still marked "Successfull".

**To Reproduce**
Screenshots or steps to reproduce
1/ 3 table same name stored in different schema
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/d6c92cb9-ee9f-4ddd-86ee-729148363bfd)

2/ error to execute query but still mark successful.
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/72e7e1b9-e4fd-40a4-8cb2-24019813bbbd)

**Expected behavior**
1/ Try some other table to get the schema name  and add some filter.
example:
select SQL_FULLTEXT,PARSING_SCHEMA_NAME
   from v$sqlarea
where PARSING_SCHEMA_NAME <> 'SYS'
and (upper(SQL_FULLTEXT) like '%INSERT %' OR upper(SQL_FULLTEXT) like '%MERGE %'  OR upper(SQL_FULLTEXT) like '%UPDATE %')
and upper(SQL_FULLTEXT) like '%FROM %'

2/Return correct status of a workflow 

**Version:**
OM 1.1

**Additional context**

**Comment by hoangdh5** [comment]
Add noted from our DBA, gv$sql only has when you have multiple nodes on your DB, If you have only one node, only has table v$sql. Another hand, v$sql have all field we need SQL_FULLTEXT,FIRST_LOAD_TIME,ELAPSED_TIME. Hope we can close this issues soon :)

**Comment by hoangdh5** [comment]
Just learn about the difference between gv$ and v$ so we still need to use gv@sql. I see in gv$sql has column PARSED_SCHEMA_NAME, can use this field for schema name?

**Comment by ulixius9** [comment]
Hey @hoangdh5, we actually can not use that `PARSING_SCHEMA_NAME` field to generate the lineage, the description of  `PARSING_SCHEMA_NAME` says that `Schema name that was used to originally build this child cursor` so basically it refers to the schema on which query was executed and not the schema involved within the query so, for example, your default schema is X and you are referring to the table of Y schema in your query then this field would contain `X` value not `Y` and another issue on the same line is if your query refers to tables from multiple schemas then as well it won't work because it contains a single string.

**Comment by hoangdh5** [comment]
Hello @ulixius9, there are 2 issues in my request, could you please re-check  the top thread.
For the usage ingestion, OM should return status Fail when ingestion can not fetch data from gv$sql or any error appear when runing ingestion.
For the use of PARSING_SCHEMA_NAME, we change in our local and see it work for us. The reason that if table in query not come with schema name like schemaX.tableA then it should be refer to Executed Schema.

Example 1:  PARSING_SCHEMA_NAME ='SchemaY'
Insert into Table_target 
select * from SchemaX.table_source
--> In that case: Table_target should be in SchemaY and table_source in SchemaX

Example 2:  PARSING_SCHEMA_NAME ='SchemaY'
Insert into Table_target 
select * from table_source
--> In that case: Table_target should be in SchemaY and table_source in SchemaY too

The main flow is: if table in query code has specific schema then system priority to that schema, if table come alone without schema, then that table should belong to executed schema.

**Comment by hoangdh5** [comment]
Here is our example.
The table 'SI_DAT_CFMAST' on both two schemas. 
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/3e1395b5-9eaa-4a3a-bd8e-eba99adc9ddf)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/fd6368a9-fc0e-4771-a694-254a32de7e7a)
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/421dd0bb-b36a-4515-aebf-5edd47b8fb15)
