### ISSUE TITLE
backend: test suite API pagination issue

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#12628]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**
Passing the `after` or `before` field to the API `/api/v1/dataQuality/testSuites` does not return the next or previous test suites.

Request URL: `/api/v1/dataQuality/testSuites`
Request Method: `GET`

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/51777795/c2404fb3-2e7c-4fcc-9008-59de82e37c82

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 closing this as done with your changes
