### ISSUE TITLE
PinotDB Test Connection Form

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#12645]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
PinoDB Connection form is taking Mysql Connection form. It's taking default form that is mention in DatabaseServiceUtils.tsx file.

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/3236cfff-46e9-4c34-977c-d5e607ef751d)

Screenshots or steps to reproduce

**Expected behavior**
It should generate PinotDB Connection Form that mention in pinotDBConnection.json file.

**Version:**
 - OpenMetadata version: 1.1.0

**Comment by Supan90-Shah3006** [comment]
is it merged & Safe to test on OM 1.1.1? @Sachin-chaurasiya @chirag-madlani

**Comment by Sachin-chaurasiya** [comment]
> is it merged & Safe to test on OM 1.1.1? @Sachin-chaurasiya @chirag-madlani 

Yes @Supan90-Shah3006

**Comment by Supan90-Shah3006** [comment]
No, I couldn't see on newer version. Currently, I'm using OM 1.1.1 version. @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
> No, I couldn't see on newer version. Currently, I'm using OM 1.1.1 version. @Sachin-chaurasiya

It's there @Supan90-Shah3006 , here is the recording

https://github.com/open-metadata/OpenMetadata/assets/59080942/ad50cd1a-ff54-44da-b21d-e14ab6c0ad60

**Comment by Supan90-Shah3006** [comment]
Thanks @Sachin-chaurasiya , I will redeploy it & check it.
