### ISSUE TITLE
Glossary Term Search at the asset level is not accurate

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12653]
**Affected module**
UI & Backend

**Describe the bug**
Glossary Term search at the asset level is not accurate

**To Reproduce**
1. Go to any Asset such as table, topic
2.  Click add Glossary Term
3. Search for "Banking.Account"
4. Expected result is to show all the terms that starts with "Banking.Account" or have Banking Account in the name, description 
<img width="324" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/e61b3d10-4f98-40cf-9c58-3d56f9182d7f">
However we show the tags in random order and some are not relevant
Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by 07Himank** [comment]
This is fixed in latest main. 

https://github.com/open-metadata/OpenMetadata/assets/112613760/5af9d44e-8d23-4ed7-bdd8-c637f1c39fa0


for reference the video is attached.

**Comment by 07Himank** [comment]
This is fixed in latest main.
For reference video is attached.. 

https://github.com/open-metadata/OpenMetadata/assets/112613760/bed14b74-1d1c-44b4-abca-199d48433a18
