### ISSUE TITLE
Add matchFQN filter to Policy setup

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12659]
Refer to a conversation in Slack here: https://openmetadata.slack.com/archives/C02B6955S4S/p1690545625455709

**Is your feature request related to a problem? Please describe.**
Currently, OM 1.1 does not support creating a policy at a table level, in some cases as required business units we need to create a policy for a list of specific table for each data source and service.

**Describe the solution you'd like**
Could we add more types of conditions in Policy setting, for supporting the creation of policy based on name of entities (table name/Database name/ Schema name/service type/....)

**Describe alternatives you've considered**
As a suggestion from @harshach , add matchFQN  to condition option in Policy page could be help here.

**Additional context**

**Comment by sureshms** [comment]
@hoangdh5, one of the approaches we have taken is not to have a policy at the individual resource level. Doing this will cause an explosion in the number of policies. An alternative approach is to identify why you need a specific policy for a resource and, assuming that there are multiple resources that want similar policy, create a tag, apply it to those resources, and use `matchTag` to enforce the policy for all resources in that category.

Can you describe in more detail the FQN matching you mentioned in this issue?

**Comment by hoangdh5** [comment]
Hi @sureshms , I want it too, but our business unit still requests to have a policy at least at table level.
I think creating a tag could support it, but we need to allow tagging assets directly on the Tag definition page  (like Glossary). It would reduce the work of tagging for each table.

**Comment by sureshms** [comment]
#12743 addresses the ask related to tagging assets in classifications page. Closing this as Won't Fix.
