### ISSUE TITLE
UI: Data quality pipeline improvement

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#12664]
Rather than going all the way to pipeline section under the Quality -> Clicking on table under `Data Quality By Table` -> `Pipeline`
to trigger a pipeline, it would be much easier have the pipeline controls in the same page for a better and faster UX for triggering multiple pipelines

https://github.com/open-metadata/OpenMetadata/assets/40225091/5dcf4c7d-54bc-4938-9fb6-563d0b8369d2

**Comment by chirag-madlani** [comment]
cc: @harshach
