### ISSUE TITLE
There are 100 tables but on the home page tables count is 0

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#1266]
Hello Everyone,

There are 100 tables but the home page count shows 0.

Version: 0.6

<img width="1786" alt="Captura de Tela 2021-11-18 às 22 55 10" src="https://user-images.githubusercontent.com/36298331/142551622-ce2bddf3-05a5-4b5c-8755-11ebaebfac26.png">

<img width="1792" alt="Captura de Tela 2021-11-18 às 22 55 51" src="https://user-images.githubusercontent.com/36298331/142551613-7bdcf94d-8533-4ee5-9f89-7b320eb774f2.png">

**Comment by harshach** [comment]
@darth-coder00 I think its related to https://github.com/open-metadata/OpenMetadata/issues/1263

**Comment by harshach** [comment]
Fixed in main
