### ISSUE TITLE
OpenLineage Support

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#1267]
Hello,

Do you have plans to support open lineage?

https://github.com/OpenLineage/OpenLineage

This project has Spark Integration and we use spark for all our pipelines, I think it is a good integration to get lineage data automatically.

Or to be simpler, integration with Marquez
https://github.com/MarquezProject/marquez

**Comment by harshach** [comment]
@rubenssoto would like to get more details on this. We already have lineage APIs and have integration with Airflow. We are going to improve our coverage to other services in the upcoming release. 
It would be great to know if you have this integration already in your infra or are you looking into it.

**Comment by rubenssoto** [comment]
@harshach we don't have integration yet, only looking into it. 

I'm looking for a solution to create lineage of ours pyspark pipelines and it seems a good solution to do an "automatic" lineage creation.

**Comment by harshach** [comment]
@rubenssoto is your pyspark pipelines run on Airflow?
@amiorin can you start looking into what integration we can do here for spark.

**Comment by rubenssoto** [comment]
Yeah, we use pyspark a lot, yeah airflow calls our pyspark jobs and run on kubernetes

**Comment by lihan** [comment]
Would you also consider generate lineage from BigQuery query logs? I believe this is how Monte Carlo Data Observability work.

Related links
* [Data lineage systems for a data warehouse ](https://cloud.google.com/architecture/architecture-concept-data-lineage-systems-in-a-data-warehouse#data_lineage_overview)

**Comment by harshach** [comment]
@lihan we already have BigQuery query log parsing to get the usage metrics and frequently joined with . We are going to update that to gather the lineage as well

**Comment by ricardogaspar2** [comment]
Adding OpenLineage support would be great! Since Spark >= 3.1 has integration with OpenLineage, it would be very helpful to get what transformations are happening and have column-level lineage

**Comment by sureshms** [comment]
OpenMetadata supports lineage beyond collecting run/job status, such as sql query analysis, pipeline service metadata (similar to OpenLineage), DBT, etc. Marking this as resolved.

**Comment by ricardogaspar2** [comment]
@wajda I'm somewhat familiar with that project. Never got to use it though.
An integration with Open Metadata would actually be more valuable then setting up Spline (Server side), and sending the lineage info to OpenLineage.
As Taurus Le is proposing/working on: https://github.com/open-metadata/OpenMetadata/issues/1604#issuecomment-1127144525

**Comment by calvertj** [comment]
@sureshms, I'm not sure I understand why you closed this; you commented that you support more than the open lineage does, that sounds great, how can I get spark to populate the metadata in OpenMetadata?  What connector should I use?

**Comment by harshach** [comment]
@calvertj we support lineage through spline connector. Please look at the docs here https://docs.open-metadata.org/v1.1.2/connectors/pipeline/spline. Do reach us out at https://slack.open-metadata.org for any questions
