### ISSUE TITLE
[Bug] HANA DB Integration Shows Password in Plaintext on the Connection Details Ui

### ISSUE THREAD

**Issue by tomtom215** [open-metadata/OpenMetadata#12678]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

- Ui

**Describe the bug**

- The connection details Ui of the HANA DB integration displays the password unmasked in plain text

**To Reproduce**

Screenshots or steps to reproduce

- Cannot add a screenshot to prove it shows the password. To reproduce, connect to a HANA DB and view connection details in the Ui

**Expected behavior**

- The password would be masked in the connection details Ui

**Version:**
 - OS: [e.g. iOS] Chrome browser/MacOS - OM Deployed on K8s
 - Python version: 3.9
 - OpenMetadata version: [e.g. 0.8] 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.1.0

**Comment by cberge908** [comment]
This is still existing in v1.1.5 - this should be masked.

**Comment by harshach** [comment]
@chirag-madlani @pmbrull double check and close it please

**Comment by pmbrull** [comment]
Thanks, I think this comes from the backend. Checking
