### ISSUE TITLE
[Feature request] Reload database ingestion status dynamically

### ISSUE THREAD

**Issue by cberge908** [open-metadata/OpenMetadata#12675]
**Is your feature request related to a problem? Please describe.**
The recent run status within the database ingestion tab does not seem to update automatically. You need to do a full page reload to see the latest status.

**Describe the solution you'd like**
Dynamic page reload in order to show the most recent status without forcing a full page refresh/ reload.

**Describe alternatives you've considered**
Manually reloading page.

**Additional context**
none

**Comment by cberge908** [comment]
![image](https://github.com/open-metadata/OpenMetadata/assets/42270330/4934087e-e555-4f9a-9226-62fa113743a4)

**Comment by harshach** [comment]
@mohityadav766 lets look at if we can use websockets to do this?
