### ISSUE TITLE
docker Deployment airflow

### ISSUE THREAD

**Issue by yizhuying** [open-metadata/OpenMetadata#12670]
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

`I am using bare-metal deployment and have not seen the documentation for Airflow. I would like to deploy Airflow using Docker. What variables do I need to set and which ports should be exposed? Please provide a complete document.`

**Comment by travis-bickle1985** [comment]
i have the same problem. Bare metal open metadata and docker image of airflow. I'm running this: "sudo docker run openmetadata/ingestion airflow standalone". After loading it waits connection on [INFO] Listening at: http://0.0.0.0:8080 (22)
But i cannot get response using curl localhost:8080

**Comment by travis-bickle1985** [comment]
> i have the same problem. Bare metal open metadata and docker image of airflow. I'm running this: "sudo docker run openmetadata/ingestion airflow standalone". After loading it waits connection on [INFO] Listening at: http://0.0.0.0:8080 (22) But i cannot get response using curl localhost:8080

i've runned it by sudo docker run -p 8080:8080 -d openmetadata/ingestion airflow standalone

**Comment by sdcxzx-tester** [comment]
Resolved, the selected image is incorrect.
