### ISSUE TITLE
Generated Python sources do not match naming for CreateMlModelEntityRequest

### ISSUE THREAD

**Issue by tomtor** [open-metadata/OpenMetadata#1268]
```
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ !py
python tests/integration/ometa/test_ometa_model_api.py
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ (cd ..; make generate > /dev/null)
/home/tom/src/OpenMetadata/env38/lib/python3.8/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'timezone' not understood for 'string' - using default
  warn(
/home/tom/src/OpenMetadata/env38/lib/python3.8/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'utc-millisec' not understood for 'string' - using default
  warn(
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ !py
python tests/integration/ometa/test_ometa_model_api.py
Traceback (most recent call last):
  File "tests/integration/ometa/test_ometa_model_api.py", line 7, in <module>
    from metadata.generated.schema.api.data.createMLModel import CreateMLModelEntityRequest
ImportError: cannot import name 'CreateMLModelEntityRequest' from 'metadata.generated.schema.api.data.createMLModel' (/home/tom/src/OpenMetadata/ingestion/src/metadata/generated/schema/api/data/createMLModel.py)
```

So the generated code has `CreateMlModelEntityRequest` but the calling code (checked in in branch `main`) uses `CreateMLModelEntityRequest` note `Ml` versus `ML`.

```
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ pip list|grep generator
datamodel-code-generator          0.11.14
```

**Comment by pmbrull** [comment]
Thanks, @tomtor 

I'll review the creation process and change the schema names if needed to mitigate this issue. Java's POJO has a slightly better approach unfortunately than codegen tool, so let's take a look!

**Comment by tomtor** [comment]
I wonder if this is related to building on Linux with a case sensitive file naming system?

Windows might hide the issue.

**Comment by pmbrull** [comment]
I built the sources with mac and it kept the cases. But yeah, there is a new github action that is going to prepare the files which will be run on ubuntu, so let's make sure that the results are consistent across OSs

**Comment by harshach** [comment]
@pmbrull this is also causing an issue on my Mac as well. given we are calling the MLModel and some places MlModel in json the classes are generating differently

**Comment by pmbrull** [comment]
Thanks @harshach for the input. I'll make a full review of the models and better standardise the naming to `Ml` to be more consistent with Camel Case convention.

**Comment by tomtor** [comment]
@pmbrull Thanks, your PR fixes the issue.

**Comment by pmbrull** [comment]
Thanks @tomtor, happy to hear that!
