### ISSUE TITLE
Glossary Assets does not list Assets when only a Dashboard Asset exists

### ISSUE THREAD

**Issue by ksirmons** [open-metadata/OpenMetadata#12701]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? UI

**Describe the bug**

We have a glossary term that is associated with a single Tableau Dashboard. 
When looking at the Assets tab in the Glossary for this term, you see the "Add Asset" button, but not the list with the dashboard.
![image](https://github.com/open-metadata/OpenMetadata/assets/3988799/00c61184-9cb2-42b6-afb7-be1a161cda26)

When you add that term to a table, then the Assets tab shows the lists..
![image](https://github.com/open-metadata/OpenMetadata/assets/3988799/e2a1af5e-f377-4a1a-b5ba-5f7716f5935d)

When you remove the term from the table, then the Asses tab goes back to the "Add Asset" button

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 

**Additional context**

**Comment by karanh37** [comment]
Hey, this is fixed with latest version.
Reference tableau dashboard asset of a glossary term - https://sandbox.open-metadata.org/glossary/Banking.Electronic%20funds%20transfer/assets

Closing this.
