### ISSUE TITLE
Add a tab to show All services in services page

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1272]
Currently in Services page, one has to jump from tab to tab to look at services configured in OpenMetadata. It would be great to show all of them in a single page. Here the changes that could make this page easier to consume:

1. Add a tab called `All` and show all the services in a single page. Existing tabs for different services can continue to exist and act as filter to look at specific services.
2. Change `Add new service` to a drop down where a user can choose to pick a service type he wants to add. This will help user avoid having to click the right service tab and then add to add a specific type of service.

@harshach wdyt?

**Comment by harshach** [comment]
+1. I think instead of using tabs we can just display all by default allow users to filter using a drop on top right corner with a modern UX

**Comment by darth-coder00** [comment]
Challenges: 

- To show accumulated list of all services on UI properly, when each Service API has it's own cursor based paginated results

For instance,

- `All` tab will show 40 services or less at a time, ideally 10 from each service type
- Suppose we go to DatabaseServices tab, and hit next,

> 1. Database Services will show results of 11-20 services in it and have before cursor, all other service will have 1-10 results at this time with before cursor
> 2. This will also change list of services in `All` tab
> 3. Now on `All` tab we have `after` cursor for all 4 service types and `before` cursor just for Database services
> 
> How would we handle pagination in this case?
