### ISSUE TITLE
Logs Versioning not show all change when update by API

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12732]
cc @chirag-madlani 

Slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1690968880274419

**Affected module**
Version control backend

**Describe the bug**
Sending update information through API for multiple columns (like update description) but after updated, new version only mark changed for the first column on the list.

**To Reproduce**

Screenshots or steps to reproduce
1/ send update request

![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/a256c4f5-1496-4b89-a2b2-12375370c37e)

2/ View the new version created
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/cb046fce-979c-4238-9d29-3d84010ef95a)

**Expected behavior**
Mark all change!

**Version:**
 - Python version:
 - OpenMetadata version:  1.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by aniketkatkar97** [comment]
For `tables`, adding or updating a `column` with children does not display its `children` as added columns as well. Similar case for adding `columns` in `containers` and  `schemaFields` for `topics`

In the video below, column `customer` with children is deleted and `customerUpdated` with children is added to the table.

https://github.com/open-metadata/OpenMetadata/assets/51777795/819fec32-2953-40d3-8ec6-a0f5026f4a86
