### ISSUE TITLE
showing sub tag of XMLType Record in Schemas

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12733]
Slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1690971849651909
cc @ulixius9 
**Is your feature request related to a problem? Please describe.**
Some system store data in a database with XMLTYPE, all column a store as a tag in XML. Need OM parse this type of record like record Type in kafka .
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/e92b06eb-c283-46a4-8d10-111c51e628d4)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sushi30** [comment]
@hoangdh5 can you provide an example for a specific database and a DDL for a table?
