### ISSUE TITLE
Add Asset page for Classification , Tags

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12743]
**Feature**
Similar to Glossary Term, Add Asset page. We should add an Assets Page and allow users to tag multiple assets from Classificaiton Page.

**Comment by aniketkatkar97** [comment]
@harshach We have a separate page for glossary terms which we don't have for tags. Since we want the Add Asset page for tags, we will have to add a tags details page first to show the assets as well. Is that the idea here?

**Comment by hoangdh5** [comment]
Hi there, is there any update on this issue? I see this feature still not available on the latest release v1.2
