### ISSUE TITLE
[Alerts] Improve Slack formatting 

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#12751]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Currently the Slack Formatting is broken 
Eg. 
![image](https://github.com/open-metadata/OpenMetadata/assets/105265192/7de562ba-3bbc-4497-877f-7112bc07dcd0)

We need to work on the formatting of these messages.

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by osinin** [comment]
I would like to add that formatting is not the only problem with Slack alerting, the links are broken too (404 page not found)

**Comment by mohityadav766** [comment]
This has been fixed , the format will be as below and also the urls will work now
<img width="814" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/105265192/3fc8c425-eaa8-4a41-9cba-c782bca69ad5">
