### ISSUE TITLE
Invalid link to entities in frequent joined column

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#12752]
Slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1691117844397249
CC @chirag-madlani  @ShaileshParmar11 
**Affected module**
backend. Redirect link to other entities

**Describe the bug**
Click on Frequently Joined Columns and get the error 'table instance xxxxx not found '
embedded link like: ... schemaname.tablename.columnname so get error
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/3da62b3b-47d3-49ba-aab7-0cc56f1f837d)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: OM1.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
this has been fixed in https://github.com/open-metadata/OpenMetadata/pull/12749
