### ISSUE TITLE
Add durable queue based off on MySQL or Postgres DB, remove LMAX disruptor

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12764]
OpenMetadata generates a change event for any change external to OpenMetadata, such as a schema change in a table or within the OpenMetadata, such as tags and owners. 
1. We create a version history
2. Alerts and notifications are triggered based on change events
3. Search Indexes are updated 

Although the LMAX disruptor enables the current functionality and is not backed up by persistent storage. 
Which results in stuck queue processing if the search index fails to run 

The goal of this approach is to use
1. Add an offset column to the change_event table
2. offset column BIGINT is with automatically generated on every insert
3. event_subscription_entity or automation as described [here](https://github.com/open-metadata/OpenMetadata/issues/11370)
    will have a unique consumer name
4. consumer name will have offset of change_event table. This is to mark how far from the chagne_event table it has read. Each consumer maintains its offset. In case of restarts or server restarts, it will 
5. In case of errors we will have dead_lettter_queue table to capture the consumer name and offset its unable to process
6. Each consumer retries the failed message configured no.of times, if it failed to deliver it will store the consumer name and offset of the message into dead_letter_queue. Initially, we will use dead_letter_queue for debugging only not replay the messages.

![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/5835be9e-8c34-42db-8716-2847014a5099)

## Merge change_event_subscriptions into automation_workfows

1. More details about proposed automation_workflows is here https://github.com/open-metadata/OpenMetadata/issues/11370
2. Automation workflows can react to the change events at a scheduled time. Example propagation of tags/description for a table or column based on lineage. They can be independent such as garbage collecting or deleting older activity data without the need to depend on the change event table
3. Similary current change_event_subscriptions can easily fit into automation_workflows. An example activity publisher is a live automation that publishes changes into the User's activity feed table, Email reacts to change events in a live fashion as well as a scheduled workflow which sends data insights reports.
4. So instead of having two tables to manage subscriptions and automation we can merge them and mark all of these as automation applications 

## Automation Consumer design

![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/0ae16aa1-220c-43aa-aad3-0dadf8ad44a2)

1. ChangeEventConsumer is abstract class and all the Applications/Workflows will extend this interface
2. Each Application initializes itself with a unique Name , while initializing it will look up the consumer table with the name configured . If there is a row with an offset available it will initiailzes the offset to last known offset. If there is no row offset is set to earliest offset. "Earliest" | "Latest" 2 enums it will point to earliest inserted row in change_event_entity or "latest" last row inserted in change_event_entity
3. Example, a new slack application will always come up with a "latest" as its offset as there is no need for processing historical data , where as search application will always come up with "earliest" if there is no stored offset, historical data processing is important.
4. ChangeEventConsumer starts polling change_event_entity with offset passed , it will read in batches of 100 rows. It will hand over that to consumer's publish method which loops through all the of these rows , if all of them are successful it will update its offset to offset = offset + 100. If at anypoint a row is failed to publish it will write to dead_letter_queue after retires are done. Moves on to processing the next row
5. We can catch all exceptions and move that consumer offset forward by writing to dead_letter_queue. This table should contain the offset it failed, error, name of the consumer. We can get actual error with the offset corresponding to change_event_entity
6. Consumer has a thread that  periodically commits the offset of the consumer into consumer table. We will call this commit method in conumser.close() as well to gracefully shutdown the consumer
8. If the sever restarts unexpectedly, we didn't had a chance to close the consumer gracefully ,upon restart consumer will restart from the last known status. 

## Scheduling consumers across multiple OpenMetadata Server

1. consumer table will record which server its running as part of . We will not be scaling same application across the servers. Instead each server is holding the application its assigned
2. A scheduler thread will be monitoring consumers table and no.of servers available and try to assign them in round-robin fashion
3. Each consumer will have a heartbeat thread that will be updating the consumers table that the application is active
4. When a new OpenMetadata server comes up, scheduler will start the reshuffling process of gracefully closing an application. We can also make a decision on sticky applications such as moving search index application is not necessary while slack or email can move. We can drive this based on configuration. Scheduler looks at 4 applications that are running on OM server 1. , It sees OM server 2 came up and there are no consumers are assigned, takes the 2 applications and assigns the OM server 2. OM server 2 scheduler looks up for its assigned Applications and start running them
5. if a server 2 goes down unexpectedly, server 1 scheduler looks at the heartbeat of assigned applications of server 2 . If its not updated with-in a threshold marks them as dead applications and re-assigns them back to server 1.

**Comment by mohityadav766** [comment]
This is done
