### ISSUE TITLE
UI - Service Page needs pagination - shows only 10 services

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#1277]
> The [services page](http://localhost:8585/services) shows maximum 10 services on UI, need to add pagination.

![image](https://user-images.githubusercontent.com/40225091/142678813-25b4ac53-2386-4076-a4aa-99041b00ae97.png)
> The [service tab on explore page](http://localhost:8585/my-data) shows 10 services

![image](https://user-images.githubusercontent.com/40225091/142654759-334de437-6570-4418-926e-d143428b6c33.png)
> The network tab shows total of 11 services.

![image](https://user-images.githubusercontent.com/40225091/142654706-3d3e68a9-b2c8-4c0f-b43b-4e1859ac04d8.png)

**Comment by ShaileshParmar11** [comment]
Assign to me

**Comment by darth-coder00** [comment]
Need minor changes
