### ISSUE TITLE
no Support greenplum version 6

### ISSUE THREAD

**Issue by sdcxzx-tester** [open-metadata/OpenMetadata#12771]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
[2023-08-07 06:17:24,721] {test_connections.py:194} DEBUG - Traceback (most recent call last): 
 File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context 
 self.dialect.do_execute( 
 File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute 
 cursor.execute(statement, parameters) 
psycopg2.errors.UndefinedColumn: column pp.polrelid does not exist 
LINE 7: JOIN pg_class AS pc ON pp.polrelid = pc.oid 
Take a look at this bug.
greenplum version 6

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[docker]==1.0.3`
 - 

**Additional context**
<img width="1006" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/122763218/c47a9f2b-b745-4b46-bcaa-4668e91cb087">

**Comment by harshach** [comment]
@ayush-shah lets create a separate connector for Greenplum cc @pmbrull

**Comment by T01iK** [comment]
added Greenplum Ingestion Connector, please take a look
