### ISSUE TITLE
Metadata Ingestion is dropping constraints just to add them again afterwards

### ISSUE THREAD

**Issue by pinkerltm** [open-metadata/OpenMetadata#12783]
**Affected module**
 Ingestion Framework - namely Metadata Ingestion (as this is the only one I am running on a daily basis, and the behaviour is showing up in a daily fashion)

**Describe the bug**
In certain cases - not quite sure when - the metadata ingestion is removing all constraint information (like Primary or Foreign Keys) from schema, just to add it again in the same job a while afterwards. This results in a huge count of (unnecessary) versions, which basically makes versioning obsolete on the whole database connection.

**To Reproduce**
![grafik](https://github.com/open-metadata/OpenMetadata/assets/6107708/4bee6c45-86c6-4ed0-99b0-28aab8d01b3b)

I have 3 database connections, one Oracle and two Postgresql. This happens on one Postgres and on the Oracle connection. The other Postgres doesn't show this behaviour, although I don't quite know whats the difference here.

On each database there is running a metadata-ingestion job daily at 2:00 a.m. which runs approximately 2 hours... so according to the screenshot, constraints are removed at the start of the job and added pretty much on the end of the job. 

usage and lineage jobs are also configured, but only on weekends. I am also pausing them right now, so I can be sure that this is not the source of this behaviour.

**Expected behavior**
On the other postgresql, I can spot a normal version history only with relevant changes, although there is running a daily metadata ingestion job there

**Version:**
 - OpenMetadata version: 1.1.0 official Docker Image

**Comment by harshach** [comment]
@pinkerltm Thanks opening this.
@pmbrull we might be doing a PUT early in the workflow without constraints which will end up removing the constraints and later we are doing a PUT again with TableConstraints in them?
