### ISSUE TITLE
ES issue after soft deleting table schema

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#12792]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Backend

**Describe the bug**
When soft deleting a whole schema, then also in Explore section we can able to see the tables of that schema Page.

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/66266464/aa28aa21-519e-4ef5-91d3-e15d4db33e21

**Expected behavior**
It should be shown only when we toggle on the deleted button.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by 07Himank** [comment]
This is fixed
