### ISSUE TITLE
UI shows different name formats for owner for databaseService and other services

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#1279]
> The UI shows different format for Owner under databaseService
![image](https://user-images.githubusercontent.com/40225091/142682810-0ae1a9e6-2d09-43ba-90cb-8ec9d461a1cf.png)
> The UI shows different format for Owner under pipelineService, messagingService and dashboardService
![image](https://user-images.githubusercontent.com/40225091/142682921-db6d9598-bd7a-4e41-bd4a-8985ede79701.png)

**Comment by ShaileshParmar11** [comment]
Assign to me

**Comment by ShaileshParmar11** [comment]
HI, @ayush-shah it seems like it's been resolved. can you re-check and confirm?

![image](https://user-images.githubusercontent.com/71748675/142906182-8f5bdcc5-062e-4178-876f-31f02bf06c00.png)
![image](https://user-images.githubusercontent.com/71748675/142906351-8f4531e1-77aa-4f3e-9735-48b40852307b.png)
![image](https://user-images.githubusercontent.com/71748675/142906417-d064abf9-e719-4862-8161-a8fee08c0106.png)
![image](https://user-images.githubusercontent.com/71748675/142906498-e769b7d4-3fb0-4e07-9e40-97812a816882.png)

**Comment by ayush-shah** [comment]
Yes, the fix has been added for this. Thank you.
