### ISSUE TITLE
Unable to run dags in airflow after deploying on EKS .

### ISSUE THREAD

**Issue by azeemkhanmohammed** [open-metadata/OpenMetadata#12805]
**Affected module**
The ingestion Framework is effected.

**Describe the bug**
Deployed openmetadata through an official helm chart on EKS . When opened the airflow for testing the sample ingestion dags all the dags seems to be failing and doesn't outputs any error.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
I expected the sample dags to be running and the data to be visible in openmetadata . 

**Version:**
 - Helm chart (version: 1.1.5) 
 - Python version: N/A
 - OpenMetadata version: [latest]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==latest`]

**Additional context**
<img width="1697" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/133137968/e0bd9d88-0e62-4e30-9216-d7db6d59169a">
<img width="1665" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/133137968/d03b38b5-99c1-46ff-86f1-c5c1e2d81696">
<img width="1627" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/133137968/0c51c0be-8335-4f4e-8faf-fdbdafab4897">
<img width="1697" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/133137968/b0db0e8b-ce7c-44a0-b4aa-5c41498d6d2f">
<img width="1715" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/133137968/3c3e379d-afab-416b-975a-d9296823493a">

**Comment by harshach** [comment]
Please check in our slack support channel (https://slack.open-metadata.org)
