### ISSUE TITLE
HIVE - problem ingesting tables with partitions

### ISSUE THREAD

**Issue by magpest** [open-metadata/OpenMetadata#12814]
**Affected module**
Ingestion Framework

**Describe the bug**
During ingestion of HIVE tables into OM, ingestion of any partitioned table produces error 'expected string or bytes-like object' and does not ingest anything.
It looks like there is some problem parsing the show create statement.

**To Reproduce**
HIVE table with partition: etl_import_export_mapping
HIVE ingestion with IMPALA scheme
source:
  type: hive
  serviceName: ref_hive
  serviceConnection:
    config:
      type: Hive
      scheme: 'impala'
      auth: LDAP
      username: $MY_AD_USER
      password: $MY_AD_PASS
      hostPort: edge02:8443
      #databaseName: "ref_hive"
      connectionOptions:
        http_path: 'gateway/topology/hive'
        use_http_transport: True
        use_ssl: True
  sourceConfig:
    config:
      type: DatabaseMetadata
      markDeletedTables: true
      includeTables: true
      includeViews: true
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: $OM_API_URL
    verifySSL: "ignore"
    authProvider: openmetadata
    securityConfig:
      jwtToken: $OM_API_BOT_TOKEN

beeline output:
0: jdbc:hive2://master01:2181,maste> describe etl_import_export_mapping;
+--------------------------+------------+----------------------------------------+
|         col_name         | data_type  |                comment                 |
+--------------------------+------------+----------------------------------------+
| execution_time           | timestamp  |                                        |
| workflow_id              | string     |                                        |
| table_name_source        | string     | hive table of related input file       |
| table_name_destination   | string     | export data                            |
| batch_id_insert          | bigint     |                                        |
| cnt_output_records       | bigint     |                                        |
| batch_id_export          | bigint     |                                        |
| status                   | string     |                                        |
| comment                  | string     |                                        |
| dt_pt                    | string     | YYMMDD substring from batch_id_export  |
|                          | NULL       | NULL                                   |
| # Partition Information  | NULL       | NULL                                   |
| # col_name               | data_type  | comment                                |
| dt_pt                    | string     | YYMMDD substring from batch_id_export  |
+--------------------------+------------+----------------------------------------+

impala shell output:
[search01:21000] prc_lookup> describe etl_import_export_mapping;
Query: describe etl_import_export_mapping
+------------------------+-----------+---------------------------------------+
| name                   | type      | comment                               |
+------------------------+-----------+---------------------------------------+
| execution_time         | timestamp |                                       |
| workflow_id            | string    |                                       |
| table_name_source      | string    | hive table of related input file      |
| table_name_destination | string    | export data                           |
| batch_id_insert        | bigint    |                                       |
| cnt_output_records     | bigint    |                                       |
| batch_id_export        | bigint    |                                       |
| status                 | string    |                                       |
| comment                | string    |                                       |
| dt_pt                  | string    | YYMMDD substring from batch_id_export |
+------------------------+-----------+---------------------------------------+

error logged by OM cli:
| Source | etl_import_export_mapping                                          | Unexpected exception to yield table [etl_import_export_mapping]: expected string or bytes-like object                                          | Tracebac
k (most recent call last):                                                                                                                                           |
|        |                                                                    |                                                                                                                                                |   File "
/home/at/user/.conda/envs/omcli/lib/python3.10/site-packages/metadata/ingestion/source/database/common_db_source.py", line 357, in yield_table                   |
|        |                                                                    |                                                                                                                                                |     ) =
self.get_columns_and_constraints(                                                                                                                                    |
|        |                                                                    |                                                                                                                                                |   File "
/home/at/user/.conda/envs/omcli/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 236, in get_columns_and_constraints |
|        |                                                                    |                                                                                                                                                |     colu
mns = inspector.get_columns(table_name, schema_name, db_name=db_name)                                                                                                |
|        |                                                                    |                                                                                                                                                |   File "
/home/at/user/.conda/envs/omcli/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns                                          |
|        |                                                                    |                                                                                                                                                |     col_
defs = self.dialect.get_columns(                                                                                                                                     |
|        |                                                                    |                                                                                                                                                |   File "
/home/at/user/.conda/envs/omcli/lib/python3.10/site-packages/metadata/ingestion/source/database/hive/metadata.py", line 275, in get_impala_columns               |
|        |                                                                    |                                                                                                                                                |     atty
pe = re.sub(r"\(.*\)", "", col[1])                                                                                                                                   |
|        |                                                                    |                                                                                                                                                |   File "
/home/at/user/.conda/envs/omcli/lib/python3.10/re.py", line 209, in sub                                                                                          |
|        |                                                                    |                                                                                                                                                |     retu
rn _compile(pattern, flags).sub(repl, string, count)                                                                                                                 |
|        |                                                                    |                                                                                                                                                | TypeErro
r: expected string or bytes-like object   

Ingest error message:

**Expected behavior**
Metadata is ingested also for partitioned tables

**Version:**
 - OS: Centos 7
 - Python version: 3.10
 - OpenMetadata version: 1.1.0.3
 - OpenMetadata Ingestion package version: openmetadata-ingestion[hive]==1.1.0.3

**Additional context**

**Comment by pmbrull** [comment]
closing for lack of information
