### ISSUE TITLE
Perform sample data ingestion without running data profiler

### ISSUE THREAD

**Issue by ekng94** [open-metadata/OpenMetadata#12816]
**Is your feature request related to a problem? Please describe.**
Data profiler operation is expansive/slow and not relevant to our use case, would like to request the option to perform sample data ingestion without running data profiler.

**Describe the solution you'd like**
Able to perform sample data ingestion without running data profiler (min, max, etc)

**Comment by TeddyCr** [comment]
closed in https://github.com/open-metadata/OpenMetadata/pull/14791
