### ISSUE TITLE
`owner` field missing from `GET` request API responses

### ISSUE THREAD

**Issue by assaadhjb** [open-metadata/OpenMetadata#12826]
In the API Doc, there are several references to getting the `owner` as a field in the response (for getting `tables`, `databases`, `databaseSchema` by id or fqdn), however, it is never returned in the responses from `GET` requests.

![Screenshot 2023-08-09 at 18 20 05](https://github.com/open-metadata/OpenMetadata/assets/12980418/69370b63-14ac-4075-b7a2-55af32655291)

**Comment by harshach** [comment]
@assaadhjb please read the docs clearly before opening a ticket or reach us in https://slack.open-metadata.org.
You need to pass fields=owner to get the owner details.
