### ISSUE TITLE
Backend Performance Improvements - Data Quality & Profiler

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#12828]
We have been reported by different users about performance issues when interacting with the profiler and DQ features, both in the UI and the ingestion. The goal of this epic is to list down a series of actions that we'll be taking in 1.1.2 and 1.2.0 to improve this situation. We are taking the chance to review generic topics in the Server <> DB communication layer.

## [1.2.0] @Transaction vs. @UnitOfWork
- @harshach 

We are passing the `@Transaction` decorator in multiple interactions with the DB, even when a locked table is unnecessary. Moreover, the current `@Transaction` is sometimes unable to roll back queries when issues occur, which leaves us with possible inconsistencies in the data (e.g., when issuing a DELETE request).

We'll be introducing the idea of `@UnitOfWork` to group a series of executions into a single transaction block to ensure consistency. Moreover, we'll be revisiting the `@Transaction` use to only apply it when strictly necessary (POST, PUT & DELETE requests).

## [1.1.2] Change PUT for POST in `/tableProfile` and `/testCaseResults` requests
- @harshach  https://github.com/open-metadata/OpenMetadata/issues/12873

When interacting with the db against the `time_series_extension` table, we are just appending data, never updating any older records when sending `tableProfile` or `testCaseResults`. It does not make sense to have that interaction as PUT, which internally queries the table, just to ignore past records.

We'll clean this up to stick to a real POST experience which will reduce the number of reads.

## [1.1.2] New Summary field in the Test Suites
- @TeddyCr https://github.com/open-metadata/OpenMetadata/issues/12884

Getting the summary data for a Test Suite means getting the test suite, listing all of its test cases, and for each test case get the results and pick up the latest one. This number of calls can exponentially grow with many unnecessary data movements.

We'll introduce a `summary` field in the Test Suite entity to store the latest results of its test cases. When we send a new Test Case result, we'll update the Test Suite summary to speed up the UI load.

## [1.1.2] Synthetic data creation for performance benchmarking
- @pmbrull 

Our last [benchmark](https://medium.com/openmetadata/openmetadata-benchmarking-3120782f8a12) analysis ran quite some time back. Since many internals of the application have evolved, we'll be preparing a module to help us generate synthetic data that we can continuously use to properly monitor the performance changes in the application for different scenarios.

We'll analyse the performance with and without DB compression

## [1.2] Split `time_series_extension` into multiple tables
- profiler, data quality and data insight data -> https://github.com/open-metadata/OpenMetadata/issues/12914

We currently have a single `time_series_extension` for the results of Data Insights, Profiler, Test Case Results, Ingestion Pipeline Status,...

This easily means that assets with many entries can slow down unrelated searches. Having separate tables would help us improve the indexing and overall speed up the querying for each independent entity.

We will as well explore the possibility of splitting the `entity_extension` table for each entity (table, pipeline,...)

## [TBD] Add DB Compression @harshach 
- Backlog for now. Not worth the effort

Investigate compression strategies that we can apply at the DB level and/or in the DAO.

One idea is to compress the JSON payload before sending it to the DB ([docs](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_compress)) and uncompress it in the server after the read to reduce network data movement.

**Comment by CheyenneRobinson** [comment]
We are still experiencing slow ingestions where processed data can be 8K items processed and only 9 synched?  Can this be fixed or is this system resource related?  The ingestion that has the biggest problem is the profiler ingestion.  This is when ingesting from an impala connection resource.

**Comment by harshach** [comment]
@CheyenneRobinson need more details here. can you share some logs and final output from the profiler?
cc @ayush-shah @TeddyCr

**Comment by TeddyCr** [comment]
Could you also share more info regarding the size of the tables you are profiling?

**Comment by CheyenneRobinson** [comment]
I see the below first....

[2023-10-10T11:50:54.409-0500] {warnings.py:109} WARNING - /usr/local/lib/python3.9/site-packages/metadata/profiler/processor/runner.py:118: SAWarning: Dialect impala:impala will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return self._select_from_sample(*entities, **kwargs).first()


Here is a snippet of the Processed and Sink....

[2023-10-10T12:18:25.019-0500] {system.py:88} INFO - System metrics not support for impala. Skipping processing.
[2023-10-10T12:18:52.957-0500] {workflow_reporter.py:34} INFO - Source: Processed 427 records, filtered 0 records, found 0 errors
[2023-10-10T12:18:52.957-0500] {workflow_reporter.py:41} INFO - Sink: Processed 11 records, found 0 errors
[2023-10-10T12:19:52.957-0500] {workflow_reporter.py:34} INFO - Source: Processed 427 records, filtered 0 records, found 0 errors
[2023-10-10T12:19:52.957-0500] {workflow_reporter.py:41} INFO - Sink: Processed 11 records, found 0 errors
[2023-10-10T12:20:25.235-0500] {profiler_interface.py:522} WARNING - Unexpected exception computing metrics: list index out of range
[2023-10-10T12:20:52.957-0500] {workflow_reporter.py:34} INFO - Source: Processed 427 records, filtered 0 records, found 0 errors
[2023-10-10T12:20:52.957-0500] {workflow_reporter.py:41} INFO - Sink: Processed 11 records, found 0 errors




It happening to all but we do have a few that maybe larger.....


totalNumberFiles:5
--
 totalFileSize:13880
 maxFileSize:9692
 minFileSize:304

totalNumberFiles:5
--
 totalFileSize:401655267
 maxFileSize:205894890
 minFileSize:380
 lastAccessTime:0


 partitionColumns:
 totalNumberFiles:5
 totalFileSize:41075
 maxFileSize:28405
 minFileSize:374
 lastAccessTime:0
