### ISSUE TITLE
SageMaker Metadata Ingestion Failed

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#12820]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend, Ingestion Framework

**Describe the bug**
In SageMaker Connector, Metadata Ingestion Pipeline is failing with below error.
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/ddbdd159-91ca-4544-b3ab-7925d1355b43)

**To Reproduce**
Connector your AWS Sagemaker account to Openmetadata Version 1.1.0 or 1.1.1
Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OpenMetadata version: 1.1.1 & 1.1.0

**Comment by Supan90-Shah3006** [comment]
Can I raise a PR for the same?
@harshach

**Comment by harshach** [comment]
@Supan90-Shah3006 yes please, that will be great
