### ISSUE TITLE
Lineage doesn't show any table dependencies

### ISSUE THREAD

**Issue by Eeelijah** [open-metadata/OpenMetadata#12838]
**Affected module**
Lineage Ingestion

**Describe the bug**
After creating BigQuery Database service, I added Metadata ingestion.
After finishing metadata ingestion I created Lineage ingestion.
When Lineage ingestion is finished, I go to any table page and try to see lineage information.
But I can't see any table dependencies.

**Expected behavior**
When I click on Lineage tab, I can see that for example table b is depended on table a.

**Version:**
 - OS: Ubuntu 20.04.6 LT
 - Python version: 3.8.10
 - OpenMetadata version: 1.0.5
 - OpenMetadata Ingestion package version: 1.0.5

**Comment by ayush-shah** [comment]
Hello @Eeelijah we have fixed the issues in the latest releases, can you test those out and let us know here?
closing this ticket till then, if you still face an issue, reopen the ticket.
Thanks
