### ISSUE TITLE
add feature to filter out columns in the search results when column is searched.

### ISSUE THREAD

**Issue by ypanaberdiyev** [open-metadata/OpenMetadata#12845]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I search for a column but it UI returns me a list of tables, then I need to click on every table and search for a particular column in a column list of that table.

**Describe the solution you'd like**
when  someone searching for the column, a list of tables appears, then when you click on that table, on a right side there is a list of the columns from that table and description of that table, solution is that it should be pre-filtered to show only column has a keyword from the search bar.

**Describe alternatives you've considered**
to show a column and description directly in the search results, but it is not a good idea because we could have many such fields.

**Additional context**

**Comment by DovileKr** [comment]
same here. our users also don't like this "two step search".

"they are looking for any column, where there is a description of name mentioning "ISO".
Expectation: he should see the column coutry_code within the customer_master table

Reality: the search results give him only the table, with no mention of the field. Only once he clicks on the table, and searches WITHIN the table, then he finds the field coutry_code."

**Comment by cdhsu** [comment]
I echo the above comments and enhancement request.  The end-user experience for search is not user-friendly for our business users.  We have the same issue noted by DovileKr above.

**Comment by harshach** [comment]
@karanh37 as we discussed, we should show the columns matched in the preview panel. If possible we should show the matched column names in the main search panel as well.

**Comment by karanh37** [comment]
Fixed with #14253
