### ISSUE TITLE
Please verify this SQL.

### ISSUE THREAD

**Issue by sdcx-zx** [open-metadata/OpenMetadata#12853]
**Please verify this SQL.**

`CREATE TABLE "standard"."中药饮片分类编码表2" (
  "顺序号" varchar(255) COLLATE "pg_catalog"."default",
  "品名" varchar(255) COLLATE "pg_catalog"."default",
  "代码" varchar(255) COLLATE "pg_catalog"."default",
  "来源" varchar(255) COLLATE "pg_catalog"."default",
  "药材名" varchar(255) COLLATE "pg_catalog"."default",
  "药用部位" varchar(255) COLLATE "pg_catalog"."default",
  "饮片
规格" varchar(255) COLLATE "pg_catalog"."default",
  "炮制
方法" varchar(255) COLLATE "pg_catalog"."default",
  "别名" varchar(255) COLLATE "pg_catalog"."default",
  "备
注" varchar(255) COLLATE "pg_catalog"."default"
)
;`

**Comment by sureshms** [comment]
@sdcx-zx, not sure what issue you are reporting here. Please use Slack to get help for questions and open issues only for confirmed bugs.
