### ISSUE TITLE
Implement filtering by tags inside the table schema

### ISSUE THREAD

**Issue by KAKuznetsov** [open-metadata/OpenMetadata#12860]
**Is your feature request related to a problem? Please describe.**
Now filtering works only either by field name or by description inside the table schema.
But alternative data-catalogs have such an opportunity, for example, in the DataHub.

Some datamarts contain hundreds of fields and this is inconvenient to use on the page with schema the "Ctrl + F" or advansed Search.
Users right on the page with the table want to limit the number of fields by tags and view them.

**Describe the solution you'd like**
Users want to check if there are any tags right on the table schema page.
That is, when they look at a specific table, and do not look for tags at all.
So it is more convenient for them to immediately see both the fields and their descriptions on the page with the table itself.

**Describe alternatives you've considered**
Filtering by checkbox inside table schema page under column "Tegs"

**Additional context**

Add any other context or screenshots about the feature request [here.](url)

 [Screen1](https://disk.yandex.ru/i/woxdcEykizQojw)

[Screen2](https://disk.yandex.ru/i/f4_0VqaZ1M5ayw)

**Comment by pmbrull** [comment]
cc @harshach if you have any thoughts

**Comment by harshach** [comment]
@chirag-madlani can we do this on the client side? or do you want to use the index, cc @07Himank
