### ISSUE TITLE
Update python CI for integration tests

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1287]
We should replicate how maven tests are able to run against an ephemeral endpoint for testing purposes.

This would allow us to have a proper CI phase running the integration tests

**Comment by harshach** [comment]
@akash-jain-10 can you help us here

**Comment by akash-jain-10** [comment]
Thanks @harshach and @pmbrull for raising this issue.
I will work on this. Please help me with few queries regarding the context of this issue -
- Is this the [documentation link](https://docs.open-metadata.org/open-source-community/developer/run-integration-tests) to follow ?
- When do you want the CI to trigger python integration tests ?

**Comment by pmbrull** [comment]
Thanks, @akash-jain-10 for jumping on this.

While running the whole integration test from the docs you shared would be great, each of them has a specific setup (its own docker spinning up the different services etc.).

IMO we could keep that for a second iteration of the issue.

First of all, I believe that we should at least make sure that the code interacting with the backend is working, i.e. the `OpenMetadata` class, as the ingestions are built on top of that. This means spinning up the `metadata-rest` and a local `mysql` and running the integration tests under `ometa` (https://github.com/open-metadata/OpenMetadata/tree/main/ingestion/tests/integration/ometa)

This would already be an interesting exercise of figuring out the testing structure. Afterwards we can add specific issues for the rest of the tests and a guide to set up the testing for upcoming integrations.

WDYT?

**Comment by akash-jain-10** [comment]
Nice. 

I do follow you @pmbrull.

Additionally, what I plan to setup and configure is to run `pytest` command using `setup.cfg` and just for first iteration, overriding the value to run tests under ometa by adding the following in command - `--override-ini=testpaths=tests/integration/ometa`.

Here is what the workflow will look like -
- checkout branch
- install python, venv and testing dependencies
- run docker compose and setup local env
- run pytest command with above attribute and execute integration tests
- cleanup (docker compose down)

Let me know your thoughts for the same. Thanks!

**Comment by pmbrull** [comment]
Hi, @akash-jain-10,

The strategy LGTM. The only comment might be in terms of configuration. Instead of handling it via setup.cfg, what would you think of preparing a `make` recipe and passing the path there? Might be easier to follow the structure and to execute with somethin like `make run-integration`.

Then we could also have specific recipes to spin up and down the containers so that in the CI it could look like `make docker-up run-integration docker-down`.

This would allow to run the tests locally as well just with the integration recipe if we already have the containers running.

Let me know what you think!

Many thanks

**Comment by akash-jain-10** [comment]
@pmbrull - Thank you for the `make` recipe suggestions. I have a PR open to fix this issue. Please review it.
