### ISSUE TITLE
patch_column_tag Python SDK throws a 500

### ISSUE THREAD

**Issue by nd-siouxfan** [open-metadata/OpenMetadata#12874]
**Affected module**
Ingestion Framework?

**Describe the bug**
When calling the patch_column_tag method, a 500 error is recieved

**To Reproduce**

 metadata.patch_column_tag(
                                entity_id= table.id,
                                column_name= column['name'],
                                tag_fqn=tag,
                                from_glossary=True
                            )

**Expected behavior**
With a valid tag, entity and column the tag is successfully updated

**Version:**
 - OS: MacOS
 - Python version:Python 3.9.12
 - OpenMetadata version: 0.13.2
 - OpenMetadata Ingestion package version: 0.13.2
**Additional context**
NO logs in any container reflecting error

**Comment by harshach** [comment]
column_name should be FQN.
Please check in https://slack.open-metadata.org. before opening a GitHub issue.

**Comment by nd-siouxfan** [comment]
Still occuring..
 
                            metadata.patch_column_tag(
                                entity_id= table.id,
                                column_name= raw_meta['serviceName'] + '.' + raw_meta['database'] + '.' + raw_meta['schema'] + '.' + raw_table['name']+ "." + column['name'],
                                tag_fqn=tag,
                                from_glossary=True
                            )


[2023-08-14 14:13:58] WARNING  {metadata.OMetaAPI:patch_mixin:292} - Cannot find column DWASDev.DWASDIDMART.dbo.Device.ImplantDate in Table.

**Comment by nd-siouxfan** [comment]
Assuming that entity_id is the table GUID and tag is a valid tag...
