### ISSUE TITLE
[feature-request] Collect bigquery tables tags

### ISSUE THREAD

**Issue by FelipeArruda** [open-metadata/OpenMetadata#12879]
**Feature**
BigQuery does not ingest information such as labels from tables

**Describe the task**
Collect the labels from table during metadata ingestion. Its the same way used for datasets.

![image](https://github.com/open-metadata/OpenMetadata/assets/5818475/e034bdef-a412-42fc-b8b1-e657990d54f8)

**Comment by FelipeArruda** [comment]
@harshach, its enabled. It works for dataset, tables don't.

![image](https://github.com/open-metadata/OpenMetadata/assets/5818475/afa78072-fad0-4553-9ea0-62a97efdb666)
![image](https://github.com/open-metadata/OpenMetadata/assets/5818475/0963a8f9-b424-455f-afa9-d6716f67b122)

**Comment by ayush-shah** [comment]
@harshach @FelipeArruda, we currently have an implementation for policytags as tags on the table level..
labels are ingested on the schema level, will have the labels fetched for table level as well. Thanks🙂
