### ISSUE TITLE
Lineage Navigation Results into Error

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#12877]
**Affected module**
It is impact at UI definitely 

**Describe the bug**
While user navigate through the lineage (Specially through column lineage) there is an error "Something Wrong (can't read the properties)"
![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/01cd5eee-31ed-4568-9855-55d49b46d19a)

**To Reproduce**
Please go thought the screen capture video of OM  sandbox instance

**Expected behavior**
[Lineage-Render-Error-2.webm](https://github.com/open-metadata/OpenMetadata/assets/131245764/93538c76-65ae-4b6f-b447-237fd29ab7d9)
[Lineage-Render-Error-1.webm](https://github.com/open-metadata/OpenMetadata/assets/131245764/d832090e-4d63-4053-9d39-79a3d9fe4697)

Expected behavior is NOT to have such error

**Version:**
Version 1.1.0 as well as 1.1.1. I used sandbox instance of the OM https://sandbox.open-metadata.org/table/redshift_dbt.dev.dbt_jaffle.orders

**Additional context**
The issue been raised earlier but was not able to reproduce it. Now we can reproduce with the steps in the video

https://openmetadata.slack.com/archives/C02B6955S4S/p1688624707621659

**Comment by karanh37** [comment]
Fixed with above issue.
