### ISSUE TITLE
Support YellowBrick ingestion (postgresql 9.5.2)

### ISSUE THREAD

**Issue by DevOpsDBAMaverick** [open-metadata/OpenMetadata#12886]
The nature of the problem comes in the form of Postgresql official support is >=v11, whereas YellowBrick is based off 9.5.2.
So, when the test connection functionality, it fails due to "Could not determine version from string 'Yellowbrick Database version 5.2.15-38414'"

Desired outcome: Allow the connection to succeed when the string returned is:  'Yellowbrick Database version x.y.z'

Things I have tried: Editing the SQLAlchemy python library - to add Yellow Brick.  This works and allows the ingestion to happen. Similar "fix" was mentioned here: https://github.com/sqlalchemy/sqlalchemy/issues/4957

Other things I have tried, bypass the "checkaccess" mandatory {true} check - allow an option to bypass the test connection functionality and just ingest the ddl.  The function which performs the test_connection, clearly has access as it has returned the string, its only the string is unexpected and throws an exception - offer some kind of support for connection established but will yield limited (best effort) metadata extraction.
Details here: https://github.com/pgspider/OpenMetadata/blob/33c752d2f5a73d02e758aa87a2e24ae4fe5d8942/openmetadata-service/src/main/resources/json/data/testConnections/database/postgres.json
[YB_error.txt](https://github.com/open-metadata/OpenMetadata/files/12358249/YB_error.txt)

**Comment by harshach** [comment]
@pmbrull is it worth supporting or can we close it?
