### ISSUE TITLE
Ingestion fails from Azure SQL after install of 1.1.1 on kubernetes

### ISSUE THREAD

**Issue by gavindew** [open-metadata/OpenMetadata#12883]
**Affected module**
Ingestion Framework

**Describe the bug**
Since upgrade to 1.1.1, all ingestion from Azure SQL databases fails. Connectivity tests work correctly in open metadata.. When DAG is deployed, it starts, passes the connectivity tests and then all tables fail with the same error. The portion in bold highlights the issue.

The logs from the failed jobs all look like below
{standard_task_runner.py:57} INFO - Started process 111 to run task
{standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'XXX', 'ingestion_task', 'scheduled__2023-08-10T02:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/XXX.py', '--cfg-path', '/tmp/tmpwvenh1_2']
{standard_task_runner.py:85} INFO - Job 252: Subtask ingestion_task
{logging_mixin.py:150} INFO - Changing /opt/airflow/logs/dag_id=XXX/run_id=scheduled__2023-08-10T02:00:00+00:00/task_id=ingestion_task permission to 509
{logging_mixin.py:150} INFO - Failed to change /opt/airflow/logs/dag_id=XXX/run_id=scheduled__2023-08-10T02:00:00+00:00/task_id=ingestion_task permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=XXX/run_id=scheduled__2023-08-10T02:00:00+00:00/task_id=ingestion_task'
{task_command.py:410} INFO - Running <TaskInstance: XXX.ingestion_task scheduled__2023-08-10T02:00:00+00:00 [running]> on host horizon-metadata-ingestion-task-9mmpzvwh
{pod_generator.py:529} WARNING - Model file /opt/airflow/pod_templates/pod_template.yaml does not exist
{taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gavin.deWet' AIRFLOW_CTX_DAG_ID='XXX' AIRFLOW_CTX_TASK_ID='ingestion_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-10T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-10T02:00:00+00:00'
{workflow.py:115} INFO - Service type:ServiceType.Database,azuresql configured
{test_connections.py:215} INFO - Test connection results:
{test_connections.py:216} INFO - failed=[] success=["'CheckAccess': Pass", "'GetSchemas': Pass", "'GetTables': Pass", "'GetViews': Pass"] warning=[]
**{common_db_source.py:419} WARNING - Unexpected exception to yield table [TABLE_TEST]: (pyodbc.ProgrammingError) ('ODBC SQL type -150 is not yet supported.  column-index=16  type=-150', 'HY106')
(Background on this error at: https://sqlalche.me/e/14/f405)**

**To Reproduce**
Ingest from any Azure SQL database

**Expected behavior**
Ingestion succeeds

**Version:**
 - OpenMetadata version: 1.1.1
 - OpenMetadata Ingestion package version: Kubernetes 1.1.1

**Comment by ulixius9** [comment]
issue already fixed with https://github.com/open-metadata/OpenMetadata/pull/12851
