### ISSUE TITLE
UI to use Tier TAG displayName if provided

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#12899]
**Affected module**
UI

**Describe the bug**
OMD Tier vocabulary (Tier or Tier1, Tier2) doesn't fit our language. We have updated the displayName, but it does nothing. 

**To Reproduce**

Screenshots or steps to reproduce
update displayName for the Tier.
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/bea17846-c7bb-4e9d-bbee-3dfc598ccc25)

Search via tier filter, showing name: 
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/5bc11f1c-496c-4223-b33d-78f0839617bc)
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/260bf989-a360-43aa-b210-60a6cb730af8)

**Expected behavior**
ui picks up displayName if such exist, as fo other things

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 1.1]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Hello @open-metadata/backend We need displayName support in tags to show displayName in selected tier


![Image](https://github.com/open-metadata/OpenMetadata/assets/71748675/a31e2f17-6fda-409f-9a23-5112cb819d1f)
