### ISSUE TITLE
customProperties for glossaryTerm

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#12898]
**Is your feature request related to a problem? Please describe.**
To be able to add custom properties (attributes) to glossaryTerm.  Currently only available for tables and so on. https://docs.open-metadata.org/v1.0.0/how-to-guides/how-to-add-custom-property-to-an-entity

**Describe the solution you'd like**
glossaryTerm is entity as others and would benefit of this geature.

add attribute, with different datatypes: boolean, reference value list, numeric, string
for the attribute to be visible on the UI

**Describe alternatives you've considered**
no other options

**Additional context**
UI says Custom Attribute while docs say custom property or extensions

**Comment by harshach** [comment]
@chirag-madlani backend APIs are added to support this. Let's add the UI component.
