### ISSUE TITLE
Pick up postgres table owner

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#12908]
Looks like postgres has the tableowner concept. We can ingest this information during the metadata workflow

**Comment by harshach** [comment]
some details here https://stephencharlesweiss.com/postgres-getting-the-owner-of-tables

**Comment by HarikaB11** [comment]
Hi @pmbrull, I would like to work on this issue

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/14289
