### ISSUE TITLE
Modify default port numbers on local-metadata env

### ISSUE THREAD

**Issue by omriAl** [open-metadata/OpenMetadata#1290]
Currently, the MySQL and ES containers are running with ports 3306 & 9200, which are the default port numbers for these services.
I think it would be a good idea to add a prefix to all of the exposed local ports, by that avoid confusion and potential conflicts between other local services.
For example, the exposed ports would be 53306 & 59200 for the services mentioned above.

**Comment by darth-coder00** [comment]
Moving this out to Milestone-2

**Comment by harshach** [comment]
Given we have environment variables. This should be straightforward now.

**Comment by harshach** [comment]
@akash-jain-10 we should document the environment variables and allow users to override them
