### ISSUE TITLE
Can't use IAM role for AWS Secrets Manager

### ISSUE THREAD

**Issue by Michalosu** [open-metadata/OpenMetadata#12941]
**Affected module**
backend

**Describe the bug**
We are trying to use AWS Secrets Manager as backend for secrects in OpenMetadata, we have chosen type: managed-aws and during the bootrap for the openmetadata pod, it is trying to move all existing secrets from local vault to AWS SM. Unfortunately, we can see error that we don't give enough permissions to put secrets in AWS service. We created special service account that has IAM role associated, but in the logs it looks like that role is not even used and only the role from EC2 instance where pod is running. Anyone has successfully configure openmetadata in k8s with service account + iam role (IIRSA)?

We use the same service account and IAM role for ingesting s3 and it works (proper IAM role is in-use). Moreover, during the bootstrap we exec to the pod and installed aws-cli and with this proper IAM role is used, we checked it by aws sts get-caller-identity It looks like the adoption of AWS SDK is working differently and it doesn't take into account associated IAM role with pod.

Error:
`DEBUG [2023-08-09 09:28:06,776] [main] o.a.h.wire - http-outgoing-1 << "{"__type":"AccessDeniedException","Message":"User: arn:aws:sts::AWS_ACCOUNT_ID:assumed-role/<EC2_ROLE_NAME> is not authorized to perform: secretsmanager:CreateSecret on resource: /openmetadata/database/test/authtype/password because no identity-based policy allows the secretsmanager:CreateSecret action"}"`

Most probably, this is related to this thread: https://github.com/aws/aws-sdk-java-v2/issues/1470 and the solution might be adding dependency to sts library

`		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>sts</artifactId>
		</dependency>
`

**To Reproduce**

1. Setup k8s service account with IAM role annotation
2. Enable managed-aws secrets in Openmetadata

**Expected behavior**
No problems with access to AWS Secrets Manager

**Version:**
 - OpenMetadata version: 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by yuhadooper** [comment]
I am facing same problem, can this be prioritized in the next release?

**Comment by harshach** [comment]
@pmbrull anything we need to do here with recent changes

**Comment by pmbrull** [comment]
@tutte if you can please chip in here

**Comment by tutte** [comment]
@Michalosu @ArtyomyuS can you confirm if you still have this issue?

**Comment by pmbrull** [comment]
Closing this. If you're still facing the issue, feel free to reach out in Slack. Since we use the exact same EKS Secrets Management method, the error might come from the configuration
