### ISSUE TITLE
Databricks with Unity - Profiler and Test Case Failing

### ISSUE THREAD

**Issue by tvamendra** [open-metadata/OpenMetadata#12947]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
The bug is in ingestion service for databrick with unity ingestion.

**Describe the bug**
Profiler ingestion and test suite pipeline failing for databricks with unity

**To Reproduce**
Openmetadata version 1.1.1. While running profiler for Databricks with unity I am getting error. The metadata was ingested successfully but when I am running profiler or test case I am getting same error in both of them.

Screenshots are attached showing the error.

**Expected behavior**
The profile and test cases should run and give results properly for Databricks using Unity.

**Version:**
 - OS: Linux
 - Python version: 3.8
 - OpenMetadata version: 1.1.1
 - OpenMetadata Ingestion package version: 1.0.5.1

**Additional context**
![Screenshot from 2023-08-18 14-16-48](https://github.com/open-metadata/OpenMetadata/assets/54747884/8e5b90b6-a5d6-44ff-9a94-9a4fda9ec072)
![Screenshot from 2023-08-18 14-17-15](https://github.com/open-metadata/OpenMetadata/assets/54747884/0bb2c0a7-345d-4823-a1ea-8f91b34a57c7)
![Screenshot from 2023-08-18 14-16-34](https://github.com/open-metadata/OpenMetadata/assets/54747884/74399ad6-9c97-4cca-a6a5-38480383b26c)
![Screenshot from 2023-08-18 14-17-33](https://github.com/open-metadata/OpenMetadata/assets/54747884/8e95a2d6-c01a-4438-b0ba-9db1b5f98927)

**Comment by xthule** [comment]
I altered the line here in sqa_mixin.py commenting out the entire execute command. It got me past this error, but immediately led to other no attribute errors, seemingly through sql_alchemy.

https://github.com/open-metadata/OpenMetadata/blob/9e6e00caf9c90dd2a1de6f53311058f0fd7445a1/ingestion/src/metadata/mixins/sqalchemy/sqa_mixin.py#L94


![Screenshot from 2023-08-21 16-14-29](https://github.com/open-metadata/OpenMetadata/assets/3150559/e75aec47-6962-4ef9-a9cb-3fc17237b2c5)

![Screenshot from 2023-08-21 16-15-24](https://github.com/open-metadata/OpenMetadata/assets/3150559/e1902b1f-74cb-4109-a6e2-546b373438b6)

**Comment by TeddyCr** [comment]
@xthule thanks for sharing this. Looks like the unity catalog connection returns a `WorkspaceClient` object which is not compatible with SQA Alchemy API -- hence the error you are seeing. 

We'll need to add support on the profiler for this -- cc @ayush-shah

**Comment by ayush-shah** [comment]
Adding to this ticket, we are not able to create Unity Catalog service from UI as it gives
`"InvalidServiceConnectionException for service [UnityCatalog] due to [Failed to encrypt connection instance of UnityCatalog. Did the Fernet Key change?]."`
- [ ] Fix Unity Catalog service
