### ISSUE TITLE
Date Filter & Status Filter Not Working

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#12959]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ans : UI

**Describe the bug**
My data has status "Success, Failed, Pending" but when I filter status = failed, it not working. Also, My data is in range 19th july to 23rd july. when i apply date filter it showing no data available.

**To Reproduce**
Before Status Filter
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/4cff58bd-9bf1-4d16-8519-a39253e5bc4f)
After Status Filter
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/f87946b5-50ba-4ffb-99a2-263a69a79d99)

Before Date Filter
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/8094ec87-f653-4f61-b959-94ca4c3a96e7)
After Date Filter
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/7ef9fba5-2366-4bf2-a752-c0c7780950e3)

**Expected behavior**
It should show data as per status & date filter.

**Version:**
 - OpenMetadata version: 1.1.1

**Additional context**

**Comment by vinaykhanchi712** [comment]
I can work on this,please assign it to me.

**Comment by Supan90-Shah3006** [comment]
Mention your name & add a comment in that issue. "I will take care of this"

**Comment by chirag-madlani** [comment]
@Abhishek332
