### ISSUE TITLE
UI - restrict roles and policy in settings for admins only

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#12954]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
- users can access all the roles and policies

**To Reproduce**

Screenshots or steps to reproduce

- Navigate to settings page
- User can see the Role & Policy option and can access the pages

**Expected behavior**

Only admins can view or modify Roles & Policy sections

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] -- 1.1.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Fixed with #13073
