### ISSUE TITLE
Qlik Sense Exclude the draft dashboards

### ISSUE THREAD

**Issue by aknoda** [open-metadata/OpenMetadata#12964]
When I ingest the Qlik Sense apps, the unpublished apps are coming. I wish there was a way to be able to import only published apps.
Thanks

**Comment by ulixius9** [comment]
Hey @aknoda, We will need your help to fix this issue, can you please help us with the [engine api response ](https://help.qlik.com/en-US/sense-developer/August2023/Subsystems/EngineAPI/Content/Sense_EngineAPI/introducing-engine-API.htm) for any unpublished app.

**Comment by pmbrull** [comment]
add a generic include/exclude drafts and fix similar issues (e.g. superset)
