### ISSUE TITLE
Timestamps in python generated classes make difficult to read commits

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1296]

**Comment by harshach** [comment]
@amiorin The generated removed completely from the repo and it becomes a dev/publish time dependency. 
Here is the PR https://github.com/open-metadata/OpenMetadata/issues/1285
Since we removed the code, having timestamps will help us associating a release tag to it.

**Comment by amiorin** [comment]
I've just seen the PR. Closing.
