### ISSUE TITLE
ADLS Connection Troubleshooting - "ClientSecretCredential.get_token failed"

### ISSUE THREAD

**Issue by JStMorgan** [open-metadata/OpenMetadata#12972]
**Is some content missing, wrong or not clear?**

I'm in the process of testing OpenMetadata for my team, attempting to set up a connection between an Azure Data Lake Gen2 and an OpenMetadata instance deployed locally via Docker Desktop. The connection test passes (I am able to list the resources), but upon trying to read data in, I hit the error in the issue title, which I have been unable to resolve. I suspect the answer is to pass the required `additionally_allowed_tenants=["*"]` as a Connection Option or Argument when configuring the connection, but there is no guidance or previous GH Issues describing how to do this (the closest I found was #12855 ), and the troubleshooting page for the Datalake connector does not mention this issue.

**Describe the solution you'd like**

The [existing documentation](https://docs.open-metadata.org/v1.1.0/connectors/database/datalake/troubleshooting) should include a section on dealing with this error, as I feel that a fair few users will encounter it, including syntax on how to pass the required argument.

**Comment by ayush-shah** [comment]
@JStMorgan which OM version are you on? 
as the issue was fixed by handling the bug in the code around the connection and fetching of data from azure datalake.
- Can you try with the latest version?
- If you are facing the same issue in the latest version, please share the debug logs for the same.

**Comment by ayush-shah** [comment]
Till then, we will consider the issue to be stale and close in a week

**Comment by ayush-shah** [comment]
Closing this, fixed as part of latest 1.1.x release, if reproducible, please open this issue again
