### ISSUE TITLE
Search for airflow job - bug in suggest

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#12979]
**Affected module**
Affect UI

**Describe the bug**
When searching for an Airflow dag name, it never suggest an option. 
After pressing enter to search, it find it. 
Also, if you search for service.dag name it find it as well. 

**To Reproduce**

<img width="840" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/6fcb0d4e-eb26-4889-9348-ee5c1c0ab363">

<img width="1022" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/775fcb42-4c52-43c4-a877-f49bd5c3dec2">

**Expected behavior**
When searching for dag name, a suggestion will appear. 

**Version:**
1.1.1

**Additional context**

**Comment by harshach** [comment]
This is fixed in 1.2.x
