### ISSUE TITLE
Team alphabetical ordering not kept after renaming

### ISSUE THREAD

**Issue by mhornst** [open-metadata/OpenMetadata#12981]
**Affected module**
UI

**Describe the bug**
If you rename a team on the UI, the ordering of teams does not change i.e. it looks like the order is not defined by the display name (but by the original name of the group). If you change the name of a team, the team remains in the same place, so the alphabetical ordering of teams is not respected anymore.

**To Reproduce**

We had these teams with `ConvDataPlatform` originally, and then changed the name to `DataPlatform`. However, in the group ordering it remained in the same place rather than being moved after the letter `C` within the groups.
![image](https://github.com/open-metadata/OpenMetadata/assets/70534496/340086a2-e6f5-4ffa-b5a3-2a21b217bbda)

**Expected behavior**
We would expect DataPlatfrom to be moved after the groups starting with `Conv{...}`

**Version:**
OM version: v1.0.0, but we could reproduce it in v1.1.1 as well (`Data governance` --> `Another Data governance`)
![image](https://github.com/open-metadata/OpenMetadata/assets/70534496/86c22544-a039-4bbb-92ce-b86c5900a66b)

**Additional context**
-

**Comment by harshach** [comment]
@mhornst we are sorting by the name of the team, it looks like you changed the display name is that correct?

**Comment by mhornst** [comment]
Also, when tagging a team in a conversation, the original names are shown (and not the display names) which is a little confusing
![image](https://github.com/open-metadata/OpenMetadata/assets/70534496/1b3425f6-f5d5-47a7-87eb-99ecadc7a8b0)

**Comment by karanh37** [comment]
Team Ordering inconsistency areas

- [ ] In Owner Label component under Teams tab.
- [ ] Mentions list
- [ ] Teams page table

**Comment by mohityadav766** [comment]
@Ashish8689 can you take a look here , you need to take the data from Elastic Search
