### ISSUE TITLE
ES Indexing for very large S3 Storage Service buckets fails

### ISSUE THREAD

**Issue by cristiancalugaru** [open-metadata/OpenMetadata#13007]
Affected module
UI & Ingestion framework

Describe the bug
Containers with a very large size or number of objects  (e.g. 1,037,864,944,958,702 for size in bytes and 21.474.83.647 for no. Objects) are not properly indexed into elasticsearch. Sample exception:

Failed while updating ES. Reason[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [numberOfObjects] of type [integer] in document with id '4fb4835b-88f4-4a26-aca7-cb6e430690ca'. Preview of field's value: '1.7661858297E10']], Cause[ElasticsearchException[Elasticsearch exception [type=input_coercion_exception, reason=Numeric value (1.7661858297E10) out of range of int (-2147483648 - 2147483647)
at [Source: (ByteArrayInputStream); line: 1, column: 638]]]], Stack [ElasticsearchStatusException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [numberOfObjects] of type [integer] in document with id '4fb4835b-88f4-4a26-aca7-cb6e430690ca'. Preview of field's value: '1.7661858297E10']]; nested: ElasticsearchException[Elasticsearch exception [type=input_coercion_exception, reason=Numeric value (1.7661858297E10) out of range of int (-2147483648 - 2147483647)
at [Source: (ByteArrayInputStream); line: 1, column: 638]]];

To Reproduce

Ingest a bucket with a very large number of objects. When indexing, it will fail because of the elasticsearch mapping type for the numberOfObjects field

Expected behavior
The bucket information should be correctly indexes.

OpenMetadata version: 1.1.2

**Comment by cristiancalugaru** [comment]
@harshach any idea if this can make it to 1.2?

**Comment by harshach** [comment]
yes will make it into 1.2, let me add a sample data and see where we are missing

**Comment by harshach** [comment]
@07Himank this doesn't look like fixed, can we just make it as text type in es index

**Comment by 07Himank** [comment]
https://github.com/open-metadata/OpenMetadata/pull/13507 @harshach we fixed this here ...

**Comment by 07Himank** [comment]
It works fine in latest main the error is older when the type was integer ..see if its makes sense or i can just change the type.

**Comment by harshach** [comment]
@cristiancalugaru need exact number you are running into error with for us to reproduce
