### ISSUE TITLE
Refactor UI code to depend on typescript and make the generation of typescript code from JsonSchemas

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1300]
Instead of checking the generated code. Lets do this as part of build process such that during the release the generated code gets packaged but doesn't need to be checked into the repository.
cc @shahsank3t

**Comment by darth-coder00** [comment]
Generated Typescript interface files are empty if,

1. `"$id"` field does not consist of proper path - Refer `ingestion.json` or `filters.json` file
2. `"properties"` field does not exist - Refer `storage.json` or `basic.json`

**Comment by darth-coder00** [comment]
Removed global package installation to generate Typescript code from schema

Need to add it to Pre-build run script

**Comment by Sachin-chaurasiya** [comment]
Moving this to the next release as we have added the root `package.json` to install `quicktype` to generate Typescript interface from JSON schema. Also, we have added documentation for the [same](https://docs.open-metadata.org/open-source-community/developer/generate-typescript-types-from-json-schema)

**Comment by sureshms** [comment]
@vivekratnavel marking this issue as resolved given we already use code generation.
