### ISSUE TITLE
UI: Show children if schema is empty - storage containers

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#13025]
<img width="1040" alt="Screenshot 2023-08-29 at 1 20 54 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/9fd22770-30dd-45dd-a49a-ab7ac0d7ffc7">
<img width="1049" alt="Screenshot 2023-08-29 at 1 20 49 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/aa403518-7896-41ad-b7e7-b7321b5daede">

if schema is empty, we can show children if the children are present and vice versa for storage containers

**Comment by harshach** [comment]
Let's move the Children tab after the Schema. If there is no Schema do not show the schema for that entity
