### ISSUE TITLE
Publish new 0.6 release docker

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1302]
We have fixed few issues our users faced for Glue. Please publish latest changes in 0.6 for docker both for server and ingestion

**Comment by akash-jain-10** [comment]
Hello All,

Docker hub images for openmetadata/server and openmetadata/ingestion has been updated with all the changes from main branch. 
I also did a smoke test for the same and verified the installation. 

Tags updated -
- [_openmetadata/server:0.6.0_
](https://hub.docker.com/layers/openmetadata/server/0.6.0/images/sha256-c6c51d9d77b4826f766d57387ef2417c8e4740cb2d09ecc632cabc93f45b11e9?context=explore)
- [_openmetadata/server:latest_](https://hub.docker.com/layers/openmetadata/server/latest/images/sha256-9793cc9d78d0512d77dee36438faa1451f99294d11abdb4e1c8b7fcfdcd5fc97?context=explore)
- [_openmetadata/ingestion:0.6.0_](https://hub.docker.com/layers/openmetadata/ingestion/0.6.0/images/sha256-f4f2638eb4d2205fddd8e4786a7e9a0e8286d79a68103179fc1c718fd01642e0?context=explore)
- [_openmetadata/ingestion:latest_](https://hub.docker.com/layers/openmetadata/ingestion/latest/images/sha256-f4f2638eb4d2205fddd8e4786a7e9a0e8286d79a68103179fc1c718fd01642e0?context=explore)
