### ISSUE TITLE
Using subpaths

### ISSUE THREAD

**Issue by BladeGTs** [open-metadata/OpenMetadata#13039]
Hi all. The question arose whether openmetadata supports deployment not at the root of the address, but at a subpath
e.g. 
https://somedomen/openmetadata

Tried different options to do it through a proxy. But that did not happen. API and frontend package, manifests.json, images. The code says search from the root.
Is there a way to set root_base_url or similar?
Or is there a solution to the problem?

**Comment by sureshms** [comment]
@BladeGTs, please use the Slack for questions. Creating issue is only for confirmed bugs.
