### ISSUE TITLE
lineage does not work for redshift views defined with "with no schema binding"

### ISSUE THREAD

**Issue by kpallati** [open-metadata/OpenMetadata#13033]
**Feature**
Enhancement to lineage to handle Redshift views defined "with no schema binding"

**Describe the task**
When redshift views are created with "with no schema binding", the view is not bound to its underlying database objects (like tables, views), so there is no dependencies between the view and its underlying db objects. This has many benefits when working with Redshift views. However, in OpenMetadata, the lineage is not captured for these views. Is there a way the lineage can be captured irrespective of whether the view is schema bind or not?

**Comment by harshach** [comment]
@kpallati what are the details in such view to determine the lineage?

**Comment by kpallati** [comment]
Another observation, seems like OpenMetadata extracts the metadata for redshift tables/ views from the redshift system view "svv_table_info". And I observed the views  (that are defined "with no schema binding") don't get listed in the "svv_table_info". May be thats the reason, the lineage is not getting captured as well? Just incase this observation helps..if there is a way to override this and find other means to extract metadata.

**Comment by ulixius9** [comment]
fixed with https://github.com/open-metadata/OpenMetadata/pull/17810
