### ISSUE TITLE
MongoDB connection string showing credentials

### ISSUE THREAD

**Issue by eduardodiazvos** [open-metadata/OpenMetadata#13053]
**Affected module**
UI

**Describe the bug**
When accessing the mongoDB connection settings, the connection string is shown with the credentials in plain text

![mongo_openmetadata_bug](https://github.com/open-metadata/OpenMetadata/assets/124708868/e97a9a78-bd81-4344-8b37-d9b773f21add)

**Expected behavior**
hide credentials

**Version:**
i used docker compose. openmetadata 1.1.1

**Comment by pmbrull** [comment]
@ulixius9 not sure if we can ask for the password separatedly to keep that info masked
