### ISSUE TITLE
Run the ingestion from the OpenMetadata UI

### ISSUE THREAD

**Issue by will0815** [open-metadata/OpenMetadata#13057]
openmetadata/ingestion Docker image ,  have specific documentation?
run  standalone?  

airflow web :
Broken DAG: [/opt/airflow/dags/airflow_lineage_operator.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_lineage_operator.py", line 67, in <module>
    raise RuntimeError(f"Could not fetch {DEFAULT_OM_AIRFLOW_CONNECTION} connection")
RuntimeError: Could not fetch openmetadata_conn_id connection

**Comment by ad-it** [comment]
I'm experiencing the same error in Airflow. Running in Docker.
OM : docker.getcollate.io/openmetadata/server:1.6.6
Ingestion: docker.getcollate.io/openmetadata/ingestion:1.6.6

Appreciate any help.
