### ISSUE TITLE
Evolve Location entity integration

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1306]
Since we have Location integration, we should be using ingestion framework to get the details from Glue to publish external tables information. 
Work with @Sachin-chaurasiya / @darth-coder00 to integrate the location information in the UI along with table entities
Improve any other connectors to get more details for Location

**Comment by amiorin** [comment]
@Sachin-chaurasiya @darth-coder00 I'm starting working on this today.
