### ISSUE TITLE
cypress upgrade test failure

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#13069]
RestoreEntity -> failing on clicking of delete switch, seems like a flaky need to check route cause of flakiness - @ShaileshParmar11 
SearchIndexDetails -> fail on assigning owner - @ShaileshParmar11 
MlFlow -> airflow sends a fail status for ingestion -> seems like an instance issue @ulixius9 
redshiftWithDBT -> different tag name received from DBT @OnkarVO7

**Comment by chirag-madlani** [comment]
@ShaileshParmar11 please update it with latest status. Thanks

**Comment by harshach** [comment]
@ShaileshParmar11 any updates here?

**Comment by ShaileshParmar11** [comment]
Hello @harshach @chirag-madlani i have updated the issue with latest failure.

**Comment by harshach** [comment]
@ShaileshParmar11 need final update here, what are we missing and can we close it.

**Comment by ShaileshParmar11** [comment]
Oh sorry i thought this is already closed with above PR, closing it now, we have taken care of above mention failure.
