### ISSUE TITLE
Where is Ingestion?

### ISSUE THREAD

**Issue by kikuchi-hirot** [open-metadata/OpenMetadata#13070]
**Is some content missing, wrong or not clear?**
How to Access Ingestion Tab?

**Describe the solution you'd like**
I wanna use Ingestions, Because I wanna use workflows of Linage.
But I cannot find Ingestion tab or button.
So please tell me how to access Ingestion tabs, or how to use workflows of Linage without Ingestion

**Additional context**

**Comment by k3agan** [comment]
@kikuchi-hirot Please see the documentation here:

https://docs.open-metadata.org/v1.1.x/how-to-guides/quick-start-guide-for-admins/how-to-ingest-metadata

I think we can close this.

**Comment by sureshms** [comment]
@kikuchi-hirot, if you have questions, then please use the Slack. Creating issues is only for confirmed bugs.
