### ISSUE TITLE
Make Atlas connector generic and configurable. Provide documentation on Atlas connector

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1308]

**Comment by harshach** [comment]
@NiharDoshi99 lets finish this off for 0.13.1. cc @pmbrull

**Comment by pmbrull** [comment]
Hi @NiharDoshi99, thanks for reviewing the implementation. I believe that before we are able to close this we need to give more details on the docs on the actual logic behind the Atlas connector. Just providing the technical details on how to connect etc. won't be enough, as how we are moving the data is not straightforward.

Please update the atlas docs https://docs.open-metadata.org/connectors/metadata/atlas with details on what users can expect when ingesting from Atlas in terms of:
- where will tags be created
- how to find the ingested entities
- etc

Thanks
