### ISSUE TITLE
Search not considering numeric characters

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#13093]
**Affected module**
UI Search

**Describe the bug**
Search only  matches on alphabetical values and ignores numeric values. We have a certain naming convention and our table names start with digits like 0101 or 0053 or 0005.
If I type in 0005 in the search, the table 0005_table_name is on **page 3** of the results and it doesn't indicate the match at all.

**To Reproduce**
Example in the sandbox . Searched for **0010e8b4** (as there is a table this such name), and it only matches (or highlights matches on letters):
Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/9037027c-9212-47b1-a25e-3f5b788e716d)

**Expected behavior**
the search match on alphanumeric values. like in sandbox, if I type in **0010e8b4**, the closest match should be table 
users_0010e8b4 https://sandbox.open-metadata.org/table/local_postgres2.postgres.sample_data.users_0010e8b4, but it is nowhere in the results set.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 1.4]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@07Himank this is because of our ngram is minlength as 1, we need to increase this to avoid single char matching

**Comment by harshach** [comment]
<img width="1666" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/6b3f24c1-ae81-4bff-8a38-65d01b5cbedc">
<img width="1666" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/73c10e60-175f-4edf-b29a-a227294e7d94">

@DovileKr  Highlighter is another issue with ElasticSearch, but the search relevancy will be improved in 1.2 with numeric characters.
If you see any other issues with this let us know.
