### ISSUE TITLE
Disabled classification system tags can still be used to tag resources

### ISSUE THREAD

**Issue by badr-a** [open-metadata/OpenMetadata#13108]
**Affected module**
UI

**Describe the bug**
Even after disabling classification system tags in OpenMetadata UI, they can still be used to tag different resources e.g. columns, tables

**To Reproduce**
Disable Classification system tags: 
![Screenshot 2023-09-06 at 15 12 22](https://github.com/open-metadata/OpenMetadata/assets/100701409/f79a11a4-d6af-4321-ba2e-8630e17f505f)
next you use it to tag a column or a table of a resource ingested via a service
![Screenshot 2023-09-06 at 15 23 07](https://github.com/open-metadata/OpenMetadata/assets/100701409/380852d9-cfaa-4112-9283-8b5ca5c06ac2)

**Expected behavior**
Once classification system tags disabled, we expect it to not appear in the list of tags when assigning tags to resources.

**Version:**
 OpenMetadata version: 1.1.1
 
**Additional context**

**Comment by harshach** [comment]
@07Himank anything we are listing for Tags if the parent classification is disable we should add disabled flag to Tags in index not show in the listing

**Comment by harshach** [comment]
@07Himank we should only allow listing of glossary terms that are approved

**Comment by 07Himank** [comment]
This is fixed [here](https://github.com/open-metadata/OpenMetadata/pull/13532)
