### ISSUE TITLE
Separate Service and Connection Details and Make connection per service with specific configuration

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1310]
Connection for different services cannot be captured as a generic JDBC as we modeled it so far.
A single service can be Pipeline or Database service example Glue
Each service has its own JDBC scheme and there are cases where we need advanced security settings which
differs quite a bit from service to service

**Comment by amiorin** [comment]
JDBC is specific to Java. Before understanding the source code of OM, I was puzzled by the fact the ingestion framework is in Python and there is a mention of JDBC in the entity service. We need to clarify what we mean by JDBC in the context of service if we want to continue to use it IMO.
