### ISSUE TITLE
Alerts - Creation, Updation of Existing alerts is not propogated to all the instances of the server

### ISSUE THREAD

**Issue by parthasarathy93** [open-metadata/OpenMetadata#13112]
Hi, Team
Using  OM1.1.1- I was testing the webhook alerts,  it was working fine, but i find a strange behaviour where in updating an existing webhook alert is not at all taking effect ,
  I created an webhook alert
  Scenario 1: new Alert on entity "Table" and event_type "Entity_updated" and a webhook for it "http://abc/" -> it was giving out correct webhook alerts 
  Scenario 2: Now i modified this existing alert with one more filter as FQN and gave a table name so that i receive webhook alerts for only that name -It did not work
  Scenario 3: I even deleted the alerts, even that is not working.. Alerts are triggered even they are not there

**Comment by parthasarathy93** [comment]
cc: @mohityadav766

**Comment by harshach** [comment]
@parthasarathy93 this is resolved in 1.3.1, please give it a try and let us know
