### ISSUE TITLE
Airflow metadata ingestion on MySQL: No database selected

### ISSUE THREAD

**Issue by anfal-alatawi-ah** [open-metadata/OpenMetadata#13123]
**Affected module**
Ingestion Framework - Metadata ingestion from Airflow

**Describe the bug**
When Airflow is running on a MySQL database, SqlAlchemy throws `(1046, 'No database selected')` meaning it is connected to the database, but the database name is missing.

**To Reproduce**
1. Have an Airflow instance running on a MySQL backend
2. Add an Airflow pipeline service
3. Add a metadata ingestion
4. Run the ingestion

The ingestion will fail with `sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1046, 'No database selected')`

**Expected behavior**
Airflow metadata pulled successfully.

**Version:**
 - Python version: 3.9.6
 - OpenMetadata version: 1.1.2.0 
 - OpenMetadata Ingestion package version: 1.1.2

**Comment by ulixius9** [comment]
@ anfal-alatawi-ah can you confirm if you have provided the airflow database name for your mysql backend configuration?
