### ISSUE TITLE
Ingestion: Multiple Project ID in Datalake GCS not supported

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#13149]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
as we are using gcpValues as part of the datalake gcs json schema, it has an option of single project id and multiple project id
but we don't currently support multiple project ids for datalake.
that's why it throws an error:
<img width="1388" alt="Screenshot 2023-09-12 at 4 49 40 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/6ec2fa47-8153-4857-b38d-8efbf318364b">

**Comment by DHClimber** [comment]
I'm interested in trying to help with this bug and very novice level. Is there any additional information available to help understand which portion of source code handles and how to recreate the failure?

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by harshach** [comment]
@ayush-shah whats remaining here?

**Comment by harshach** [comment]
@vimalJD not sure what you project is ongoing. you can look at the commit history. 
For docs its https://docs.open-metadata.org/v1.1.x and look for contributions https://docs.open-metadata.org/v1.1.x/developers/contribute

**Comment by ayush-shah** [comment]
Currently we only support Bigquery with multiple project ids, as we show same gcp config for both, it shows single project id and multiple project id in the same UI, given we can ingest multiple projects from gcp in bigquery, it's currently not possible from the ingestion side code for datalake gcs
