### ISSUE TITLE
Data product list error

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#13153]
**Describe the bug**
When fetching Data Products using GET API, it doesn't take into consideration value passed in `domain` field.
The API results all the data products, instead it should only provide data products for that domain

**Comment by sureshms** [comment]
@karanh37 , let's use Elastic Search API for getting data products by domain instead of list APIs. CC @harshach

**Comment by sureshms** [comment]
Duplicate of #13255
