### ISSUE TITLE
New User: Email Invitation is Not Sent

### ISSUE THREAD

**Issue by ShilpaVernekar** [open-metadata/OpenMetadata#13166]
**Affected module**
Tried this on Sandbox

**Describe the bug**
When a new user is added to Sandbox. No email invitation is sent. Verified by checking both the Inbox as well as the Spam folder. Also, tested with multiple email IDs.

Also, no email is sent when a user is added to new teams. (Not sure if this is a supported use case.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
not reproducible
