### ISSUE TITLE
Trino ingestion does not build URL correctly when username/password is used

### ISSUE THREAD

**Issue by abrisan** [open-metadata/OpenMetadata#1317]
https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/trino.py#L35

This should append a "@" to the URL.

**Comment by harshach** [comment]
Thanks @abrisan

**Comment by harshach** [comment]
@ayush-shah there are few more issues with Trino connector. Lets fix these.

**Comment by ayush-shah** [comment]
Hello @abrisan, I was looking into the documentation for trino and according to the [Trino JDBC Documentation](https://trino.io/docs/current/installation/jdbc.html), I will be adding the username and password URL formatting accordingly alongwith other options.
`String url = "jdbc:trino://example.net:8080/hive/sales?user=test&password=secret&SSL=true";`

I couldn't find any usage of "@", just wanted to know if we need it for anything specifically? 

![image](https://user-images.githubusercontent.com/40225091/143187999-36e81fc5-3dbb-4827-ba34-b6b7d6d31d05.png)

**Comment by abrisan** [comment]
@ayush-shah that will also work, but the current version (see [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/trino.py#L32)) uses the `"jdbc:trino://user:password@host"` pattern, and that is missing a "@"

**Comment by ayush-shah** [comment]
@abrisan can you give a try, we have fixed it with #1614
