### ISSUE TITLE
Unability to filter or see Data assets tagged using newly created classification tags

### ISSUE THREAD

**Issue by badr-a** [open-metadata/OpenMetadata#13171]
**Affected module**
UI

**Describe the bug**
When adding new tag in Classification, we are able to use it and assign it to different data assets on schema and database levels. If we want to check data assets tagged we can't neither filter by Classification tag on the explore section nor check usage on the classification page.

**To Reproduce**

1.  Create a new Classification tag:
![Screenshot 2023-09-13 at 09 27 55](https://github.com/open-metadata/OpenMetadata/assets/100701409/ebfdbd90-6191-48b6-9552-e5ddf511272e)
2.  Assign it to different data assets on database and schemas levels
3. Go back to Classification page, click on usage to see these data assets
![Screenshot 2023-09-13 at 09 27 55](https://github.com/open-metadata/OpenMetadata/assets/100701409/bc06de73-3467-4b8a-846d-dcd65195ed17)
nothing shows
![Screenshot 2023-09-13 at 09 36 46](https://github.com/open-metadata/OpenMetadata/assets/100701409/4b90f953-b60f-46e2-8e4f-6e5c5891b16e)
4.  Next go to explore and try to filter using your Classification tag:
![Screenshot 2023-09-13 at 09 38 02](https://github.com/open-metadata/OpenMetadata/assets/100701409/ce396563-0fca-4be7-9a87-4b3c4bd6e441)
You get `No data available`.

**Expected behavior**
An expected behaviour is to be able to tag different data assets on a database and schema levels and access it either through usage on the classification page or by going to explore section and filtering using the tag.

**Version:**
 - OpenMetadata version: 1.1.1

**Additional context**

**Comment by harshach** [comment]
Please go to settings -> OpenMetadata -> Search Re-Index all. Please do not file issues without confirming in our slack (https://slack.open-metadata.org)
