### ISSUE TITLE
MlModelResourceTest fails

### ISSUE THREAD

**Issue by tomtor** [open-metadata/OpenMetadata#1318]
3 tests fail due to naming:

```
MLModel instance for 216bda15-8db9-4539-84de-ce554d182f63 not found
```

versus

```
MlModel instance for 216bda15-8db9-4539-84de-ce554d182f63 not found
```

Note `L` versus `l`

**Comment by pmbrull** [comment]
missed that, thanks @tomtor

**Comment by pmbrull** [comment]
Morning @tomtor, could you please provide a bit more info on the issue? I just ran `mvn clean test` in a fresh branch and it is working properly for me.

In this PR https://github.com/open-metadata/OpenMetadata/pull/1288 we changed all the naming and the CI tests ran properly for MlModels

```
2021-11-20T16:03:24.0794439Z [INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.423 s - in org.openmetadata.catalog.resources.mlmodels.MlModelResourceTest
```

Thanks

**Comment by tomtor** [comment]
Morning @pmbrull 
I did a checkout of latest `main` and a clean rebuild and the error is gone now.
So, it's fine. Probably some artifact was not rebuild.
Sorry for the false alarm.

**Comment by pmbrull** [comment]
Hi, @tomtor,

Happy to hear! Please, do not hesitate to report any issues or questions you might have.

Thanks!
