### ISSUE TITLE
Non-admin user can't add term on glossary after policy assigned

### ISSUE THREAD

**Issue by cristianodicrescenzo** [open-metadata/OpenMetadata#13188]
**Affected module**
UI

**Describe the bug**
A non-admin user can't add term on glossary even if he is owner and data consumer policies allow it ("Save" button does not work)
<img width="404" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/141228011/9434f601-b00c-4093-8008-d585816b4594">
![image](https://github.com/open-metadata/OpenMetadata/assets/141228011/4a7d43e1-9fcc-44b2-a8ca-457d98617b5d)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OpenMetadata version: 1.1.4
 - OpenMetadata Ingestion package version: 1.1.4

**Additional context**

**Comment by karanh37** [comment]
@harshach - I performed the same steps mentioned as above. Looks like backend is giving error on creation.

![image](https://github.com/open-metadata/OpenMetadata/assets/33024356/e11c3af0-7e66-4e43-80c6-0d7d62c71c37)

**Comment by harshach** [comment]
@sureshms isOwner() conditional check is not working, if the user is owner of the Glossary they should be able to create terms underneath that glossary.

<img width="1669" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/0e7d65f9-d92e-4a6a-8463-3cc9dc807389">

<img width="1370" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/70d8a60a-d431-4a47-b440-bde8c60f2722">

**Comment by sureshms** [comment]
@harshach, this is a known issue. When you are creating a GlossaryTerm, for the new entity there is no owner set. We are not checking the ownership of the glossary term parent.
