### ISSUE TITLE
Excuse me, why can't several plugins be found in the mvn library when starting the UI according to the readme file in openmetadata-ui? There is an error when running mvn clean install. The tagert folder in openmetadata-dist and the generated in openmetadata-ui fail to be generated.

### ISSUE THREAD

**Issue by Jack-Cai-1998** [open-metadata/OpenMetadata#13186]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
@Jack-Cai-1998, please use the slack channel to ask questions and not create issues for that. Also when creating an issue, add a brief summary and the rest of the details in the description.
