### ISSUE TITLE
Add validation in ingestion pipeline json schema to not include whitespace

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#13190]
**Describe the bug**
Below error gets generated when we have a whitespace in the ingestion pipeline name. The logs do not get displayed.
<img width="1489" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/28966081/5337b4fe-2912-4fee-92db-91c4a45c3d45">

We'll add validation in ingestion pipeline json schema to not include whitespace chars.

**Comment by pmbrull** [comment]
let's fix this by validating how we can clean the API call retrieving the logs

**Comment by chirag-madlani** [comment]
@pmbrull should we restrict space in the ingestion name to fix this?

**Comment by pmbrull** [comment]
hi we should allow spaces here. I'll fix the API to get this working, thanks!
