### ISSUE TITLE
Glossary Term: Added Assets are Not Saved

### ISSUE THREAD

**Issue by ShilpaVernekar** [open-metadata/OpenMetadata#13222]
**Affected module**
https://sandbox.open-metadata.org/

**Describe the bug**
When assets are added to a Glossary Term, they are not saved.

In Glossary, I do not see the saved assets
For example: in Business Terms Glossary > Business.Address has no assets
<img width="694" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/94032785/089b3468-735a-4a95-8f0b-3d89e5042f94">

But when I check some data assets, I see that they have the glossary term Business Terms.Business.Address associated with them
<img width="1219" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/94032785/a43f6ff8-a9f5-4a4c-bf6d-227c20a3e7bc">

**To Reproduce**
Navigate to a glossary term > Add Assets > Select a few > Click Save.
The page shows a loading icon, but not of the assets are associated with the glossary term.
It doesn't save the changes

**Expected behavior**
Add assets to glossary term must work.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@07Himank verify if this is working with new changes and close it out.
We also need to support indexing when glossary import happens.
Right now its triggering entire re-indexing which is overkill cc @mohityadav766

**Comment by 07Himank** [comment]
> @07Himank verify if this is working with new changes and close it out. We also need to support indexing when glossary import happens. Right now its triggering entire re-indexing which is overkill cc @mohityadav766

Let me validate, and will handle it

**Comment by 07Himank** [comment]
> t now its triggering entire re-indexing which is overkill cc @mohityadav766


https://github.com/open-metadata/OpenMetadata/assets/112613760/4741f61d-ab08-4324-9f61-1a274fbc48d3

terms issue is resolved .. bulk import work is in progress it will be merged today
