### ISSUE TITLE
Search Results: Some Glossary Terms Missing

### ISSUE THREAD

**Issue by ShilpaVernekar** [open-metadata/OpenMetadata#13223]
**Affected module**
https://sandbox.open-metadata.org/

**Describe the bug**
There's a glossary term "Address" in the Business terms Glossary. When I search for Address from global search.... it does not display the result for the existing Glossary term "Address", even after filtering by Glossary
![image](https://github.com/open-metadata/OpenMetadata/assets/94032785/94031910-931c-4b8c-ab5b-d86ce983bb8a)

Also, in the actual results that are populated, I do see 2 other glossary terms with "Address"
<img width="820" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/94032785/7bea72a1-6bff-4d45-9d29-c582ee09063f">

**To Reproduce**

Plz check image above. Existing glossary term is not displayed in search results even after filtering by glossary term

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by 07Himank** [comment]
This is even fixed in latest main.
for reference video :-

https://github.com/open-metadata/OpenMetadata/assets/112613760/b1ad8966-4e4d-4630-81cd-84ffa5ebf10b
