### ISSUE TITLE
How to generate src/main/resources/ui/src/generated/*

### ISSUE THREAD

**Issue by tomtor** [open-metadata/OpenMetadata#1324]
@harshach It is not clear from the documentation how the generate these files for new JSON defined Entities

**Comment by shahsank3t** [comment]
@darth-coder00 Please double-check whether we have documented the steps and if not then let's add it.

**Comment by Sachin-chaurasiya** [comment]
@tomtor Thank you for filing the ticket. we will document the steps asap.

**Comment by Sachin-chaurasiya** [comment]
@tomtor Here we have added documentation for the above issue [generate-typescript-types-from-json-schema](https://docs.open-metadata.org/open-source-community/developer/generate-typescript-types-from-json-schema)

Thank you.

**Comment by tomtor** [comment]
@Sachin-chaurasiya Thanks!!
