### ISSUE TITLE
Explore view not showing all tables

### ISSUE THREAD

**Issue by colax94** [open-metadata/OpenMetadata#13258]
**Affected module**
UI

**Describe the bug**
In the Explore View, OpenMetadata displays only 1 table, whereas if I go down in Services > Databases, I can see all the tables in my database that seem to be properly ingested.

Screenshot of the Explore View
<img width="1512" alt="Screenshot 2023-09-19 at 12 01 14" src="https://github.com/open-metadata/OpenMetadata/assets/22587311/0893f0df-bf74-436c-bc68-2c1e18bc2293">

Screenshot of the Services > Databases View (we see all the schemas were properly ingested)
<img width="1512" alt="Screenshot 2023-09-19 at 12 20 08" src="https://github.com/open-metadata/OpenMetadata/assets/22587311/f79771b5-467e-4d86-8447-5d63d78eaa79">

**Expected behavior**
We should see all tables in the "Explore" View

**Version:**
 - OS: MacOS
 - Python version: 3.8
 - OpenMetadata version: 1.1.4

**Comment by colax94** [comment]
No one else is experiencing this ? I am really stuck here, everything seems to work perfectly, I can see the tables being ingested, add tests, etc... But I can't see any tables in the "Explore" view, and searching for any table yields no results...
Any help would be greatly appreciated, we are considering OpenMetadata for our company, but this is completely blocking us...

**Comment by pmbrull** [comment]
hi this does not look like an application issue. Can you please go to Settings > Search > Reindex All

ES might have got stuck. This should update it properly.

Closing this issue now. Thanks
