### ISSUE TITLE
Allow empty username/password in Email settings

### ISSUE THREAD

**Issue by jan-pieter** [open-metadata/OpenMetadata#13261]
**Is your feature request related to a problem? Please describe.**
When configuring the Email settings in the UI the username and password fields are required. In our setup the SMTP server does not require authentication.

**Describe the solution you'd like**
Make the username and password optional and only set them when they are non-empty when sending email.

**Describe alternatives you've considered**
We can add a dummy username and password, but that might not work for everybody.

**Comment by mohityadav766** [comment]
Done
