### ISSUE TITLE
Remove OpenMetadata URL from SMTP/Email settings

### ISSUE THREAD

**Issue by jan-pieter** [open-metadata/OpenMetadata#13260]
**Affected module**
Backend/UI

**Describe the bug**
The SMTP settings (both in the UI and via environment variables) contain a field for setting the `OpenMetadata URL`. However that is not used in the emails that are being sent. Instead the `OM_URI` environment variable is used to build the link in the email notifications (and other notifications). I think that is a good thing since it is not specific to email notifications. But then the `OpenMetadata URL` should be removed from the email configuration to avoid confusion.

**To Reproduce**

Set `OM_URI` to something different than `OPENMETADATA_SERVER_URL` and observe that the `OM_URI` is used in notifications.

**Expected behavior**
Remove the `OPENMETADATA_SERVER_URL` environment variable and entry from the smtp settings.

**Version:**
 - OpenMetadata version: 1.1.4

**Comment by vitaly-zverev** [comment]
JFYI, сan't reproduce described behavior with OPENMETADATA_SERVER_URL/OM_URI in v1.2.0.

For example:
docker compose exec -ti openmetadata-server bash -c set | grep -E 'OM_URI|OPENMETADATA_SERVER_URL'
OM_URI=' "http://localhost:8585"'
OPENMETADATA_SERVER_URL='""'

but, in e-mail message I got the 'reset link', pointing on http://localhost

**Comment by vitaly-zverev** [comment]
https://github.com/open-metadata/OpenMetadata/issues/13930

**Comment by harshach** [comment]
@mohityadav766 this was fixed right?

**Comment by mohityadav766** [comment]
> @mohityadav766 this was fixed right?

Yes
