### ISSUE TITLE
Allow lineage graph edge description field to be edited in UI

### ISSUE THREAD

**Issue by traitortots** [open-metadata/OpenMetadata#13268]
**Is your feature request related to a problem? Please describe.**
We need an easy way to document when a custom script loads data from one database to another in the lineage. For example, we have a custom script (in C++ which runs every day with Windows Scheduler) that extracts data from Salesforce and loads it to our MSSQL database. It isn't a "pipeline" per se, but it is a part of the lineage that we would like to track. 

**Describe the solution you'd like**
An easy solution would be a way within the lineage UI to edit the "Description" property of graph edges, as seen here:
![image](https://github.com/open-metadata/OpenMetadata/assets/88009118/f3d731f9-0d01-4ef8-b64d-f0028cb46049)
Being able to edit this description while editing the lineage graph, combined with some type of visual cue in the graph itself that there is a description for the edge (either a different color or maybe a small box with the first few words in the description), would be sufficient in my opinion. 

**Describe alternatives you've considered**
Another option would be a way to annotate the edge with some other type of entity besides pipelines, or make it easier to create a custom pipeline that documents things like custom scripts or other external services not currently supported as regular pipeline services. 

**Additional context**
n/a

**Comment by harshach** [comment]
supported in release 1.2.3
