### ISSUE TITLE
Sending test email feature on the Email config page

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#13270]
After config the Email sender, we have to wait or trigger some alert to make sure the configuration is success.

I suggest we create a new button on the Email page that allows users can send an email to specific email address to verify the configuration. That email could look like this:

Receiver: testuser@xxx.com
Subject: Testing Email configuration from OM
Body: Email configuration Success full!

**Comment by mohityadav766** [comment]
@chirag-madlani work from backend is done ... PUT api/v1/email/test (request body is a String that is just the mail on which the test email should be sent)-> this is the api needs work from the UI to make a call, this needs to be added on the Email SMTP settings page cc @harshach
