### ISSUE TITLE
Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes

### ISSUE THREAD

**Issue by eeennn** [open-metadata/OpenMetadata#13274]
`[2023-09-20T08:24:14.467+0000] {core.py:33} INFO - Executing test case DeletedNotNull for entity xxx.xxx.xxx.dws_talent_map_patent_inventor
[2023-09-20T08:24:14.480+0000] {sqa_test_suite_interface.py:173} ERROR - Error executing columnValuesToBeNotNull - Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes
[2023-09-20T08:24:14.491+0000] {workflow.py:431} ERROR - Could not run test case DeletedNotNull: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes
[2023-09-20T08:24:14.492+0000] {core.py:33} INFO - Executing test case ColumnValueNotNull for entity xxx.xxx.xxx.dws_talent_map_patent_inventor
[2023-09-20T08:24:14.501+0000] {sqa_test_suite_interface.py:173} ERROR - Error executing columnValuesToBeNotNull - Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes
[2023-09-20T08:24:14.501+0000] {workflow.py:431} ERROR - Could not run test case ColumnValueNotNull: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes
[2023-09-20T08:24:14.544+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/test_suite.py", line 50, in test_suite_workflow
    workflow.raise_from_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/workflow/workflow_status_mixin.py", line 91, in raise_from_status
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/workflow/workflow_status_mixin.py", line 88, in raise_from_status
    self._raise_from_status_internal(raise_warnings)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/api/workflow.py", line 488, in _raise_from_status_internal
    raise WorkflowExecutionError("Processor reported errors", self.status)
metadata.config.common.WorkflowExecutionError: ('Processor reported errors', ProcessorStatus(records=[], warnings=[], failures=[StackTraceError(name='DeletedNotNull', error='Could not run test case DeletedNotNull: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes', stack_trace='Traceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/mixins/sqa_validator_mixin.py", line 75, in run_query_results\n    value = dict(runner.dispatch_query_select_first(metric_fn))  # type: ignore\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/timeout.py", line 54, in inner\n    result = fn(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/runner.py", line 127, in dispatch_query_select_first\n    return self.select_first_from_sample(*entities, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/timeout.py", line 54, in inner\n    result = fn(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/handle_partition.py", line 126, in handle_and_execute\n    return func(_self, *args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/runner.py", line 118, in select_first_from_sample\n    return self._select_from_sample(*entities, **kwargs).first()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2824, in first\n    return self.limit(1)._iter().first()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter\n    result = self.session.execute(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute\n    conn = self._connection_for_bind(bind)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind\n    return self._transaction._connection_for_bind(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind\n    conn = bind.connect()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect\n    return self._connection_cls(self, close_with_result=close_with_result)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__\n    else engine.raw_connection()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection\n    return self._wrap_pool_connect(self.pool.connect, _connection)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect\n    return fn()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect\n    return _ConnectionFairy._checkout(self)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout\n    rec = pool._do_get()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get\n    self._dec_overflow()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__\n    compat.raise_(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_\n    raise exception\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get\n    return self._create_connection()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection\n    return _ConnectionRecord(self)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__\n    self.__connect()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect\n    pool.logger.debug("Error on connect(): %s", e)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__\n    compat.raise_(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_\n    raise exception\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect\n    return dialect.connect(*cargs, **cparams)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 143, in connect\n    return Connection(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 213, in __init__\n    raise ValueError("Password should be set if and only if in LDAP or CUSTOM mode; "\nValueError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py", line 171, in run_test_case\n    return Validator(validator_obj=test_handler).validate()\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/validator.py", line 26, in validate\n    return self.validator_obj.run_validation()\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/column/base/columnValuesToBeNotNull.py", line 48, in run_validation\n    res = self._run_results(Metrics.NULL_COUNT, column)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/column/sqlalchemy/columnValuesToBeNotNull.py", line 55, in _run_results\n    return self.run_query_results(self.runner, metric, column)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/mixins/sqa_validator_mixin.py", line 78, in run_query_results\n    raise SQLAlchemyError(exc)\nsqlalchemy.exc.SQLAlchemyError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/api/workflow.py", line 421, in run_test_suite\n    test_result = test_suite_runner.run_and_handle(test_case)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/runner/core.py", line 37, in run_and_handle\n    test_result = self.test_runner_interace.run_test_case(\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py", line 176, in run_test_case\n    raise RuntimeError(err)\nRuntimeError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n'), StackTraceError(name='ColumnValueNotNull', error='Could not run test case ColumnValueNotNull: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes', stack_trace='Traceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/mixins/sqa_validator_mixin.py", line 75, in run_query_results\n    value = dict(runner.dispatch_query_select_first(metric_fn))  # type: ignore\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/timeout.py", line 54, in inner\n    result = fn(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/runner.py", line 127, in dispatch_query_select_first\n    return self.select_first_from_sample(*entities, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/timeout.py", line 54, in inner\n    result = fn(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/handle_partition.py", line 126, in handle_and_execute\n    return func(_self, *args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/runner.py", line 118, in select_first_from_sample\n    return self._select_from_sample(*entities, **kwargs).first()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2824, in first\n    return self.limit(1)._iter().first()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter\n    result = self.session.execute(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute\n    conn = self._connection_for_bind(bind)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind\n    return self._transaction._connection_for_bind(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind\n    conn = bind.connect()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect\n    return self._connection_cls(self, close_with_result=close_with_result)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__\n    else engine.raw_connection()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection\n    return self._wrap_pool_connect(self.pool.connect, _connection)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect\n    return fn()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect\n    return _ConnectionFairy._checkout(self)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout\n    rec = pool._do_get()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get\n    self._dec_overflow()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__\n    compat.raise_(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_\n    raise exception\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get\n    return self._create_connection()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection\n    return _ConnectionRecord(self)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__\n    self.__connect()\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect\n    pool.logger.debug("Error on connect(): %s", e)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__\n    compat.raise_(\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_\n    raise exception\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect\n    return dialect.connect(*cargs, **cparams)\n  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 143, in connect\n    return Connection(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 213, in __init__\n    raise ValueError("Password should be set if and only if in LDAP or CUSTOM mode; "\nValueError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py", line 171, in run_test_case\n    return Validator(validator_obj=test_handler).validate()\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/validator.py", line 26, in validate\n    return self.validator_obj.run_validation()\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/column/base/columnValuesToBeNotNull.py", line 48, in run_validation\n    res = self._run_results(Metrics.NULL_COUNT, column)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/column/sqlalchemy/columnValuesToBeNotNull.py", line 55, in _run_results\n    return self.run_query_results(self.runner, metric, column)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/validations/mixins/sqa_validator_mixin.py", line 78, in run_query_results\n    raise SQLAlchemyError(exc)\nsqlalchemy.exc.SQLAlchemyError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/api/workflow.py", line 421, in run_test_suite\n    test_result = test_suite_runner.run_and_handle(test_case)\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/runner/core.py", line 37, in run_and_handle\n    test_result = self.test_runner_interace.run_test_case(\n  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py", line 176, in run_test_case\n    raise RuntimeError(err)\nRuntimeError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n')]))
`
i not use LDAP , Where should I remove the password?

**Comment by eeennn** [comment]
i see, just remove hive password from datasource

**Comment by wshilman** [comment]
if using KERBEROS Authentication Mode, the profiler throws the same exception, and in this authentication mode, the password is mandatory to be able to make the connection succesfully

**Comment by wshilman** [comment]
@eeennn were you able to connect to hive using kerberos AND using the profiler ingestion?
