### ISSUE TITLE
Alerts on test cases does not work with "owner" filter

### ISSUE THREAD

**Issue by cristianodicrescenzo** [open-metadata/OpenMetadata#13279]
**Affected module**
backend

**Describe the bug**
setting an alert on a test case result, if a filter on "owner" is set the alert does not work

**To Reproduce**

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/141228011/742fdf5d-1691-4d0a-9c62-930b75da3963)

**Expected behavior**

**Version:**
 - OpenMetadata version: 1.1.5
 - OpenMetadata Ingestion package version:  `openmetadata-ingestion[docker]==1.1.5`]

**Additional context**

**Comment by mohityadav766** [comment]
https://github.com/open-metadata/OpenMetadata/pull/14806 fixes this
