### ISSUE TITLE
Support nested fields DESCRIPTION ingestion using Trino

### ISSUE THREAD

**Issue by eladrus** [open-metadata/OpenMetadata#13298]
**Is your feature request related to a problem? Please describe.**
Many of our tables have nested fields, for example of type `struct<id:varchar,name:varchar,sort_order:bigint>`.
We're using Trino database service with metadata ingestions, our stack includes S3 for storage and Apache Iceberg under the hood.
We saw that for non-nested fields or for the top level of a nested field there is a DESCRIPTION being ingested, however it's not the case for the nested fields themselves.

**Describe the solution you'd like**
We would like that DESCRIPTION for nested fields would be ingested exactly like it is for regular fields, and would be reflected in OMD table schemas, as it's important metadata for our users.

**Describe alternatives you've considered**
An alternative would be to manually update this metadata or to maintain a scheduled job but it will probably be very time consuming to develop and to maintain.

**Additional context**
We're using OMD version 1.1.1, Trino version 409.
You can see in the following pics that description exists in Iceberg metadata files also for the nested fields but actually in OMD it's not reflected.
![image (17)](https://github.com/open-metadata/OpenMetadata/assets/93661167/fca458d5-03e7-45a5-b504-82413f9b9001)
![image (18)](https://github.com/open-metadata/OpenMetadata/assets/93661167/fde49a40-99ec-45aa-b30e-aa2b4cc247e3)

**Comment by ayush-shah** [comment]
@eladrus we are getting the information directly from trino like this:
`row(name varchar, address row(city varchar, state varchar), age bigint)` and it seems related to iceberg metadata file more compared to trino comments.
We already have a iceberg connector in the making which should resolve the issue you are facing, you can track the addition of iceberg from here #14825 and the issue #5448

**Comment by ayush-shah** [comment]
Closing this issue as the nested descriptions can be fetched from the iceberg connector which can be found in #14825
