### ISSUE TITLE
Show Display Name of tags instead of classification.tag

### ISSUE THREAD

**Issue by SiimonHyarm** [open-metadata/OpenMetadata#13295]
**Is your feature request related to a problem? Please describe.**
Whenever I tag entities I see the tag in `classification_name.tag_name` format, but I really would wish to see the tags `Display_Name` because it is clearer and more concise for end user. They are clickable anyway, but at least, it is self-explanatory in the latter case. 

**Describe the solution you'd like**
I really would wish to see the tags `Display_Name` because it is clearer and more concise for end user. They are clickable anyway, but at least, it is self-explanatory in the latter case. 

**Describe alternatives you've considered**
No alternatives available

**Additional context**
For API FQN can stay as name, easier to access tags and classifications.

**Comment by ShaileshParmar11** [comment]
Hello, it's fixed from the backend side but the UI required some changes.
