### ISSUE TITLE
Correction to environment variable

### ISSUE THREAD

**Issue by mmalta96** [open-metadata/OpenMetadata#13302]
Remove ":" in file .env-postgres

OLD: ELASTICSEARCH_INDEX_MAPPING_LANG:="EN"
NEW: ELASTICSEARCH_INDEX_MAPPING_LANG="EN"

**Comment by harshach** [comment]
@akash-jain-10 whats the status on this?

**Comment by akash-jain-10** [comment]
Hello @harshach  - Raised a PR for the fix here! Thanks.
