### ISSUE TITLE
The search Feature

### ISSUE THREAD

**Issue by MTelco** [open-metadata/OpenMetadata#13319]
### Discussed in https://github.com/open-metadata/OpenMetadata/discussions/13311

<div type='discussions-op-text'>

<sup>Originally posted by **MTelco** September 22, 2023</sup>
Hi all
we are exploring the search feature in open metadata.
However i see that we can only search my name of dashboards or table only..
while trying to use description, tags as a search, it doesn't work.

Is this a permanent restriction or something to be changed in next releases?

We are setting up this open source tool as our data catalog. if these features are not planned, we might need to look into other tools.?
Regards,
Shyamal                                                                                                               </div>

**Comment by harshach** [comment]
@MTelco , description, column based, tags matching etc.. being supported from day 1. Please come to our slack https://slack.open-metadata.org before opening a github issue.
Github issues for bugs & features and not for discussions.
