### ISSUE TITLE
backend: provide field selection for `matchAnyFieldChange` condition in alerts

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#13320]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**

The `matchAnyFieldChange` condition currently has  `parameterInputType` as `NotRequired` and hence no `paramAdditionalContext` field values. 
Providing a selection of fields to watch for changes would be helpful in this case.

<img width="1317" alt="Screenshot 2023-09-25 at 9 21 38 AM" src="https://github.com/open-metadata/OpenMetadata/assets/51777795/d0215e61-c70b-4d56-b6a7-ff56399c5c88">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohityadav766** [comment]
hi @aniketkatkar97 , I have added this from the backend , you might need to handle it on the UI

**Comment by mohityadav766** [comment]
we can close this since the model is changed , we are going to have it opinionated on UI for different options
