### ISSUE TITLE
Impove UI of /settings/services/databases and other services

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#13337]
**Is your feature request related to a problem? Please describe.**
Currently we have >130 database services. 

It's hard to navigate through /settings/services/databases page

Example:
<img width="1431" alt="Screenshot 2023-09-26 at 9 48 25 AM" src="https://github.com/open-metadata/OpenMetadata/assets/115643517/27a6714e-6494-40a6-8fb3-bc17e33b74b7">

1. database name is shorten to much 
2. 20 services per page is to little (maybe to choose 10, 20, 50, as in Explore page)
3. service type filter would be usefull (MySQL, BigQUery, etc.)
4. database owners should be showed 
5. database owner filter would be usefull (MySQL, BigQUery, etc.)

**Describe the solution you'd like**
Proposed above

**Describe alternatives you've considered**
Use current page 

**Additional context**
-

**Comment by pmbrull** [comment]
covered in 1.2. @gnomolio feel free to explore the new page and let us know your thoughts
