### ISSUE TITLE
Project file not found

### ISSUE THREAD

**Issue by ImprovementSugar** [open-metadata/OpenMetadata#13355]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
openmetadata-service

**Describe the bug**
can not find some java file

**To Reproduce**
Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/47029292/9de7197c-5d2f-4f8f-867b-48a9dfa309d4)

**Expected behavior**

**Version:**
 - OS: [e.g. iOS]  windows
 - Python version: 3.10.x
 - OpenMetadata version: [e.g. 0.8] 1.1.6
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ayush-shah** [comment]
@ImprovementSugar please run the `mvn clean install` and it should get fixed..
please take a look at the: https://docs.open-metadata.org/v1.1.x/developers/contribute/build-code-and-run-tests
check the intellij IDEA configuration and run the commands, the error should get fixed.
