### ISSUE TITLE
Use PATCH API to update display names of entities

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#13364]
**Describe the task**
Currently we are relying on the PUT API to update the display names of the entities
This update does not happen when using ingestion-bot token for authentication
Instead we will use the PATCH API to updated the display names and use `force override` to update already present display names if any.

**Comment by pmbrull** [comment]
fixed by https://github.com/open-metadata/OpenMetadata/pull/14224
