### ISSUE TITLE
Use PATCH API in bulk

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#13365]
**Describe the task**
Currently the PATCH APIs are called once for each update of the tag and description
Update the ingestion logic so that this PATCH operation can be performed in bulk

**Comment by harshach** [comment]
@OnkarVO7 @pmbrull did we fix this?

**Comment by pmbrull** [comment]
we handled the tag PATCH for the profiler (PII processor), not for the ingestion
