### ISSUE TITLE
Cant find openmetadata metadata connector 

### ISSUE THREAD

**Issue by xaer0resus** [open-metadata/OpenMetadata#13370]
Hello! I have problem with creating the metadata service. In your documentation you show that you have your own built-in OpenMetaData Service, but I cant find it, following the route you've given in documentation. I only got two options: amundsen and atlas. Could you make it clear, please? 

Best regards

https://docs.open-metadata.org/v1.1.x/features/data-insight

![image](https://github.com/open-metadata/OpenMetadata/assets/145779989/36ffa1dc-8724-4144-990b-97a6c187928f)

**Comment by sureshms** [comment]
@xaer0resus. did you have any slack conversation about this? When something can be a question on slack, please don't create an issue.
