### ISSUE TITLE
The UI should always display username instead of userid

### ISSUE THREAD

**Issue by DykVanDyke** [open-metadata/OpenMetadata#13382]
**Describe the solution you'd like**
In the history of a Glossary Term, the OpenMetadata UI shows the UserId instead of showing the User Name which would be much more useful.  See the instance from bellow screen capture, where we should have a user Name like "Joe Kido" instead of his user ID . 

**Additional context**
![history](https://github.com/open-metadata/OpenMetadata/assets/613812/50325769-1b27-4701-9da1-92ec3b17f192)

**Comment by NormanZhang-zzt** [comment]
Hi, I would like to work on this issue.

**Comment by sureshms** [comment]
@NormanZhang-zzt assigned the issue to you
