### ISSUE TITLE
What is the purpose of the Mutually Exclusive button on the creation of a Glossary or a Glossary Term?

### ISSUE THREAD

**Issue by DykVanDyke** [open-metadata/OpenMetadata#13381]
**Is some content missing, wrong or not clear?**
In the form of creation of a Glossary and also for a Glossary Term, we have a slider button with the label "Mutually exclusive"  like shown in the bellow screen-capture. The action of that button is not evident in the resulting Glossary / Term. as nothing different seems to happen according to the enabling or disabling of that button.
The "mutually exclusive" feature for the usage of labels on a Classification is very clear, but here on the creation of a Term or Glossary, not so much. So, could we have some description of its effect on the left setup documentation guide? 

**Describe the solution you'd like**
Could we have some description for the "Mutually Exclusive" slider button on the left setup documentation guide of the Term/Glossary form page ? 

**Additional context**
![Mutually Exclusive - create term or Glossary](https://github.com/open-metadata/OpenMetadata/assets/613812/c1b9538e-0d56-4c89-9c40-053a0d7de075)

**Comment by harshach** [comment]
@DykVanDyke before opening an issue please check in the community .
here are the docs https://docs.open-metadata.org/v1.1.x/how-to-guides/openmetadata/data-governance/glossary-classification/classification#classification-and-categorization-tags
