### ISSUE TITLE
UI - allow user to modify constraint for Schema or Table level

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#13396]
**Is your feature request related to a problem? Please describe.**
Good to have option to modify constraint for Schema or Table from UI

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
closing this as duplicate of this https://github.com/open-metadata/OpenMetadata/issues/13820
