### ISSUE TITLE
Error  400 in add-service

### ISSUE THREAD

**Issue by AdalbertoMJR** [open-metadata/OpenMetadata#13405]
When trying to add a new service, I'm getting the following error:

{"code":400,"message":"test-connection-Mysql-qt0yXvm9 Failed to trigger workflow due to airflow API returned Internal Server Error and response {\"error\": \"Error running automation workflow due to ['NoneType' object is not subscriptable] \"}"}

"POST /api/v1/automations/workflows/trigger/505d76b4-68f7-4977-bf89-5a6f81a1f12b HTTP/1.1" 400 245 "https://openmetadata.servicosesfera.com.br/databaseServices/add-service" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 856

I'm running the openmetada service on kubernetes and this error is only occurring when trying to add the service.

**Comment by sureshms** [comment]
@AdalbertoMJR, is there any slack thread to confirm that this is indeed a bug?
