### ISSUE TITLE
Issue on the versioning of Database assets

### ISSUE THREAD

**Issue by DykVanDyke** [open-metadata/OpenMetadata#13417]
**Affected module**
This is a backend issue

**Describe the bug**
As shown on bellow screen capture,  I have Table assets with several versions created on the same timestamp (at minute precision level at least) . I have even seen assets with more than 20 versions created on the same minute!  After exchanging with support team, this seems to have been originated by the data profiling pipeline. 

**To Reproduce**
Simply launching the data profiling pipeline upon database assets. 

![image](https://github.com/open-metadata/OpenMetadata/assets/613812/499fb251-2615-4075-9038-8248112ccfba)

**Expected behavior**
New versions of assets should only be created when some metadata change occurs.

**Version:**
 - OpenMetadata version: 1.1.5

**Comment by pmbrull** [comment]
fixed in https://github.com/open-metadata/OpenMetadata/pull/13385
