### ISSUE TITLE
Add sort feature for Queries tab

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#13426]
**Is your feature request related to a problem? Please describe.**
With a table having a lot of queries, it's hard to find the most queries useful for users to view. Some frequent queries should be shown at the top of the list to help users easy to find them.

**Describe the solution you'd like**
We should have a sort by some relevant field like top vote, last updated, ....

**Describe alternatives you've considered**

**Additional context**

**Comment by ShaileshParmar11** [comment]
This feature is already available
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/bbf146e4-9a53-418c-a33f-603aafbd7e51">
