### ISSUE TITLE
Glue supports column names with dots

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1343]
I have created a table in Glue/Athena with dots in the name of the columns and it works in Athena.

A solution could be to use an encoding similar to [JSON Pointer](http://jsonpatch.com/#json-pointer) for ```column.nesteColumn```.

```
~0 -> ~
~1 -> /
~2 -> .
~3 -> @
```

![image](https://user-images.githubusercontent.com/32617/143048124-b211c7c9-d83c-418a-bc79-4e1910bd8cdb.png)

**Comment by harshach** [comment]
@amiorin we had previous discussion on dot notation https://github.com/open-metadata/OpenMetadata/issues/981 . we agreed on using DOT as the notation. Given we are using "." as the separator for FQDN.

**Comment by amiorin** [comment]
LGTM. Closing this one.
