### ISSUE TITLE
Allow to disable the pipelineServiceClient

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#13459]
![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/f7191c3e-9322-4903-86f1-8dc4043867d6)

and not show any error messages if there's no intent on using it

**Comment by harshach** [comment]
@pmbrull what is remaining here

**Comment by pmbrull** [comment]
this is done https://github.com/open-metadata/OpenMetadata/blob/main/conf/openmetadata.yaml#L246
