### ISSUE TITLE
Data Retention Policy alerts

### ISSUE THREAD

**Issue by ruth-mills-naimuri** [open-metadata/OpenMetadata#13455]
**Is your feature request related to a problem? Please describe.**
We would like to be able to automate alerts for users to be notified when the age of an entity exceeds a pre-determined value.

**Describe the solution you'd like**
To be able to create an Alert (e.g. sending an email or Slack message) and/or an Activity Feed alert, so the appropriate user(s) are notified when the age of an entity exceeds a pre-determined value, and/or has had no updates after a pre-determined time.

**Describe alternatives you've considered**
We've been informed that OM provides this information via Insights, but this does not allow for the automated triggering of alerts that we would ideally need.

**Comment by harshach** [comment]
@ruth-mills-naimuri we are not going to support all of these specific use case for you.
You need to capture the metadata change events do your own operations on it.
