### ISSUE TITLE
nameHash conflict for users with different mail

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#13470]
if we have
- levy@gmail.com
- levy@yahoo.com

Both users can register to the platform, and their name will in both cases be `levy`, which conflicts with the `nameHash` of `user_entity` being a PK.

This is not a usual scenario since orgs restrict the user registration from their domain, but still we might want to review it

**Comment by aryanVanaik** [comment]
I can work on this issue if possible do you know which folder the hashing is located within
