### ISSUE TITLE
Fixing page switching in the policy section

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#13495]
**Affected module**
UI

**Describe the bug**
Good afternoon!
In the policy view section, when switching from one page to another, the page counter is lost. It is impossible to view the policies on the pages further than the second one.

**To Reproduce**
![policy_page_bug](https://github.com/open-metadata/OpenMetadata/assets/61934044/d0e15bc9-0a37-493a-bc46-1ff58ab825cc)

**Expected behavior**
Switching between pages in the policy section should be fine.

**Version:**
 - OpenMetadata version: 1.1.7

**Comment by chirag-madlani** [comment]
Hi @AlekseevVadim,
We have verified same on our end and not able to reproduce the same. Feel free to re-open with additional info like network or console if you are still facing this issue.
Verified with 1.2 release
