### ISSUE TITLE
Please add an option to explicitly specify the output filename for metadata backup

### ISSUE THREAD

**Issue by Jason-Clark-FG** [open-metadata/OpenMetadata#13517]
**Is your feature request related to a problem? Please describe.**

We are attempting to run the `metadata backup` daily to provide a backup for DR. It would be advantageous if we could explicitly specify the output file name (not just the directory name) which would make the subsequent steps much easier. Currently we need to parse the output name and work from there. With the bash script running from cron we are not able to properly capture the output from the python backup script (not sure exactly why), so we had to use some other methods...

**Describe the solution you'd like**

Add a flag, or expand the current `--output` flag to also include a file specific file name for the output...

**Describe alternatives you've considered**

Since for some reason grabbing the output from the python script run from a bash script run by cron doesn't work properly I'm setting the filename based on the same method being used in the `metadata` python ( `openmetadata_db-$(date +%Y%m%d%H%M)_backup.sql` ) and then checking if that exists after the backup. This mostly works, but can fail if it happens to fall across a minute change. If it doesn't find that file, then we failback to looking for the most recent file with the same naming pattern. It all works okay, but would be more efficient if we could just specify the known name.

**Additional context**

Nothing more really... :) Thanks in advance!

**Comment by k3agan** [comment]
#13661

**Comment by pmbrull** [comment]
closed with https://github.com/open-metadata/OpenMetadata/pull/13661
