### ISSUE TITLE
Add support for setting domain for teams and other entities

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#13551]
The following is needed:
- Show domain for a teams, personas, policy, roles, glossary, and glossary terms and make it editable (similar to data asset)
- Show domain for a user (only domain can be assigned to teams)

**Comment by harsh-vador** [comment]
I will take this up

**Comment by karanh37** [comment]
@sureshms @harshach - backend support is required for personas, policy and roles to support domain.
For other entities we are taking a look.
cc - @harsh-vador

**Comment by harshach** [comment]
@karanh37 we are not going to add domain support for personas, policy and roles  at this point.
