### ISSUE TITLE
Superset ingest: option to exclude drafts

### ISSUE THREAD

**Issue by joegoldbeck** [open-metadata/OpenMetadata#13553]
**Is your feature request related to a problem? Please describe.**
We are using OpenMetadata to ingest Superset dashboards, and we have many dashboards that are in draft stage, and currently, they pollute the catalog and it is hard to find the real published dashboards.

**Describe the solution you'd like**
At the ingest sourceConfig, an `includeDrafts` option. When set to `False` drafts are not ingested.

**Describe alternatives you've considered**
An alternate solution might be to include "draft" vs "published" as a new metadata field, and allow filtering on that field during search. That could be a nice addition, but seems like simple than not ingesting. Drafts are inherently cruft for our use case.

**Comment by joegoldbeck** [comment]
Thanks for adding to the release! Taking a look at OM 1.2 (nice work!), and thinking:

Now that dashboard data models are first class in the UI, it would be ideal if this option could be applied to data models as well. For ex, an option to only ingest data models if they are part of a published dashboard

**Comment by SumanMaharana** [comment]
I will work on this issue
