### ISSUE TITLE
Add links between a Glossary term and Tableau chart / TableauDataModel / TableauDataModel field

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#13564]
I would like to raise a feature request.

**My feature request is related to a problem:**
At the current moment it is possible to see a link only between a Glossary term and Dashboard in the "Assets" tab.
There is no possibility to link fields from TableauDataModel.

**The solution I'd like:**
In the "Assets" tab I would like to see a link between a Glossary term and Tableau chart(not only a whole dashboard), also a link between a Glossary term and a Tableau field in TableauDataModel.
The best example is an existing link to fields from BigQuery tables (screenshot is attached)
![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/5576ae23-6047-4883-917b-72c569defbf6)

**So please add:**
- a possibility to look for TableauDataModel in "Assets" tab of Glossary term
- a possibility to see created links between a Tableau field in TableauDataModel and a Glossary term in "Assets" tab of Glossary term

I mean when I add a Glossary term here (as it is presented on the screenshot), I would like to see this link in "Assets" tab with such detalization as for BigQuery field
![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/9bf6aeab-010d-455f-8c62-afe33b60bfaf)

**Comment by TheShiveshNetwork** [comment]
Assign this to me

**Comment by pmbrull** [comment]
hi @LiubovPasechnik, when adding assets through the glossary view, you will be able to link `Dashboard Data Models` starting from the 1.2.0 release

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/ea14756d-a85b-4598-a97b-071a61efc8ac)


Thanks
