### ISSUE TITLE
Add new entities to ES index from OpenMetadata server

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1356]
Currently, once we run ingestion to fetch data from data sources into OM , user needs to run indexing workflow as well.
If the indexing workflow didn't run then the entities that are ingested in OM will not show up in the UI. This is a bad UX.
This issue is to build indexing directly from OM and we will still keep the metadata indexing workflow to catch any issues and it will provide a way update the index in clean fashion.

**Comment by pmbrull** [comment]
Love this! Will be easier to abstract from the underlying architecture and just focus on usage!
