### ISSUE TITLE
Ingestion api fail having % in ingestion name 

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#13575]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
 create any metadata, usage, etc having `%` in its ingestion, usage name throwing us an error.

- API Query: `http://localhost:8585/api/v1/services/ingestionPipelines/%22redshift%25ashish.12%22.redshift%25ashish_12_lineage_7t0zhJsD/pipelineStatus?startTs=1697350193979&endTs=1697436593983`

- Error: `"Airflow Exception [redshift%ashish_12_lineage_7t0zhJsD] due to [Malformed escape pair at index 64: http://ingestion:8080/api/v1/openmetadata/status?dag_id=redshift%ashish_12_lineage_7t0zhJsD&only_queued=true]."`

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Ashish8689 what is the name of the service you created

**Comment by Ashish8689** [comment]
I have created it for database and it name was like `service%data.12`
