### ISSUE TITLE
Get started button on the documentation page leads to Page not found :(

### ISSUE THREAD

**Issue by sylthiel** [open-metadata/OpenMetadata#13580]
Steps to replicate:
1. Navigate to the [documentation link](https://docs.open-metadata.org/v1.1.x) from the main website
2. Click on Get Started 

Expected: We get brought to a relevant webpage (perhaps this one? https://docs.open-metadata.org/v1.1.x/quick-start)
Actual: Page not found :(

**Comment by pmbrull** [comment]
hi @sylthiel, do you mean this button? 
![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/87d5daad-9c9a-4c42-82e1-9cd367f79806)

Just reviewed it and it redirects fine for me. Marking this as closed. Feel free to reopen if I missed something. Thanks
