### ISSUE TITLE
Configurable Sample Data Rows & Sample Data Stored in S3

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#13603]
1. [ ] OpenMetadata profile upgrade to capture a maximum of 10,000 rows based on configuration
1. [ ] Allow Admin to configure S3 bucket location to write data from sampling to S3 buckets
1. [ ] UI Updates to add Sampling and S3 bucket location

-----
## Proposal

- We can configure the default number of rows to be picked up for sample data in the profiler workflow
  - We can also have a specific number of sample data rows in the table properties (same that we do with the metric sampling % / count) -> [tableProfilerConfig](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/data/table.json#L711C6-L711C25)
- We are going to store the data in the object storage as a blob with `service/database/schema/table/sample.parquet`
  - We can store the data as `sample_001.parquet`, `sample_002.parquet`,... so that we can read the sample data paginated directly. Think about tradeoff of calls vs. one single read and paginate internally
- We can configure the S3 location at the service level to ensure that all profiler pipelines are pointing to the same storage location.
  - We can have that in the Advanced Configuration -> UI will need to update this
- We'll need to update the TableResource to pick up the sample data from S3 using the creds from the service, which should be stored using the Secrets Manager.
- Do we need to paginate the sample data rows if we get +100 rows? (paginate [this](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java#L511) endpoint) -> UI will need to update this
- [P2] Getting the sample data in that case can become more expensive, do we want to cache (?)

**Comment by ulixius9** [comment]
> We can store the data as sample_001.parquet, sample_002.parquet,... so that we can read the sample data paginated directly. Think about the tradeoff of calls vs. one single read and paginate internally

For this approach S3 does not provide a way to batch upload files; we will have to do multiple write operations for each table during the profiler workflow which could be more expensive as the profiler workflow would generally run daily hence we would go with the single file and pagination method
