### ISSUE TITLE
Logo not getting set when env vars are set

### ISSUE THREAD

**Issue by yreddy-CS** [open-metadata/OpenMetadata#13618]
**Affected module**
This impacts UI due to an inconsistency on which endpoint is being used for setting the Logo

**Describe the bug**
When the env vars(OM_CUSTOM_MONOGRAM_URL_PATH and CUSTOM_LOGO_URL_PATH) are set when deploying the helm chart, we do see the correct values reflecting when querying _/api/v1/system/config/applicationConfig_ but the UI is setting the logos querying the  _/api/v1/system/config/customLogoConfiguration_ which are set manually set from the UI

**To Reproduce**
1. Deploy the openmetadata helm chart with the vars OM_CUSTOM_MONOGRAM_URL_PATH and CUSTOM_LOGO_URL_PATH as described in https://docs.open-metadata.org/v1.1.x/how-to-guides/how-to-add-custom-logo 
2. observe that the custom logs do not come up in the UI

Screenshots or steps to reproduce

**Expected behavior**
There should be a single point to set the config 

**Version:**
 - OpenMetadata version: 1.1.14
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/server:1.1.7

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hi @yreddy-CS, we appreciate your report regarding the issue. To assist us in debugging the problem, could you kindly furnish the following information:

1. The ENV values you have set.
2. The API response for the endpoint `api/v1/system/config/customLogoConfiguration`.

Additionally, it would be highly beneficial if you could include some screenshots. Thank you!

**Comment by yreddy-CS** [comment]
The response of the API _api/v1/system/config/applicationConfig_ is 
```
{
"logoConfig": {
"customLogoUrlPath": "https://<redacted>/theme/tecnotree-sensa-logomark.svg",
"customMonogramUrlPath": "https://<redacted>/theme/favicon.svg"
},
"loginConfig": {
"maxLoginFailAttempts": 3,
"accessBlockTime": 600,
"jwtTokenExpiryTime": 3600
}
}
```
and the response of the API _api/v1/system/config/customLogoConfiguration_ is 
``` {
"customLogoUrlPath": "",
"customMonogramUrlPath": ""
} ```

The image URL set is a absolute path(part of the URL is redacted ) with no auth needed

I've gone through the existing bugs and have tried with setting these 4 env vars set and they do not work(give above response)
OM_CUSTOM_MONOGRAM_URL_PATH
OM_CUSTOM_LOGO_URL_PATH
CUSTOM_LOGO_URL_PATH
CUSTOM_MONOGRAM_URL_PATH
<img width="871" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/27280368/cba09290-57a6-4885-9b69-167645e946b3">

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya The response of the API _api/v1/system/config/applicationConfig_ is
> 
> ```
> {
> "logoConfig": {
> "customLogoUrlPath": "https://<redacted>/theme/tecnotree-sensa-logomark.svg",
> "customMonogramUrlPath": "https://<redacted>/theme/favicon.svg"
> },
> "loginConfig": {
> "maxLoginFailAttempts": 3,
> "accessBlockTime": 600,
> "jwtTokenExpiryTime": 3600
> }
> }
> ```
> 
> and the response of the API _api/v1/system/config/customLogoConfiguration_ is
> 
> ```
> "customLogoUrlPath": "",
> "customMonogramUrlPath": ""
> } ```
> 
> The image URL set is a absolute path(part of the URL is redacted ) with no auth needed
> 
> I've gone through the existing bugs and have tried with setting these 4 env vars set and they do not work(give above response)
> OM_CUSTOM_MONOGRAM_URL_PATH
> OM_CUSTOM_LOGO_URL_PATH
> CUSTOM_LOGO_URL_PATH
> CUSTOM_MONOGRAM_URL_PATH
> ```
> 
> <img alt="image" width="871" src="https://user-images.githubusercontent.com/27280368/277675930-cba09290-57a6-4885-9b69-167645e946b3.png">
> I've not attached any screenshots as the UI is same as default with no env vars set(related to the Logo)

@yreddy-CS , you are on OpenMetadata version 1.1.7 right?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya The response of the API _api/v1/system/config/applicationConfig_ is
> 
> ```
> {
> "logoConfig": {
> "customLogoUrlPath": "https://<redacted>/theme/tecnotree-sensa-logomark.svg",
> "customMonogramUrlPath": "https://<redacted>/theme/favicon.svg"
> },
> "loginConfig": {
> "maxLoginFailAttempts": 3,
> "accessBlockTime": 600,
> "jwtTokenExpiryTime": 3600
> }
> }
> ```
> 
> and the response of the API _api/v1/system/config/customLogoConfiguration_ is
> 
> ```
> "customLogoUrlPath": "",
> "customMonogramUrlPath": ""
> } ```
> 
> The image URL set is a absolute path(part of the URL is redacted ) with no auth needed
> 
> I've gone through the existing bugs and have tried with setting these 4 env vars set and they do not work(give above response)
> OM_CUSTOM_MONOGRAM_URL_PATH
> OM_CUSTOM_LOGO_URL_PATH
> CUSTOM_LOGO_URL_PATH
> CUSTOM_MONOGRAM_URL_PATH
> ```
> 
> <img alt="image" width="871" src="https://user-images.githubusercontent.com/27280368/277675930-cba09290-57a6-4885-9b69-167645e946b3.png">
> I've not attached any screenshots as the UI is same as default with no env vars set(related to the Logo)

@mohityadav766 , can you check `api/v1/system/config/customLogoConfiguration` is returning the empty values for the custom logo config?

**Comment by yreddy-CS** [comment]
> > @Sachin-chaurasiya The response of the API _api/v1/system/config/applicationConfig_ is
> > ```
> > {
> > "logoConfig": {
> > "customLogoUrlPath": "https://<redacted>/theme/tecnotree-sensa-logomark.svg",
> > "customMonogramUrlPath": "https://<redacted>/theme/favicon.svg"
> > },
> > "loginConfig": {
> > "maxLoginFailAttempts": 3,
> > "accessBlockTime": 600,
> > "jwtTokenExpiryTime": 3600
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the response of the API _api/v1/system/config/customLogoConfiguration_ is
> > ```
> > "customLogoUrlPath": "",
> > "customMonogramUrlPath": ""
> > } ```
> > 
> > The image URL set is a absolute path(part of the URL is redacted ) with no auth needed
> > 
> > I've gone through the existing bugs and have tried with setting these 4 env vars set and they do not work(give above response)
> > OM_CUSTOM_MONOGRAM_URL_PATH
> > OM_CUSTOM_LOGO_URL_PATH
> > CUSTOM_LOGO_URL_PATH
> > CUSTOM_MONOGRAM_URL_PATH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="871" src="https://user-images.githubusercontent.com/27280368/277675930-cba09290-57a6-4885-9b69-167645e946b3.png">
> > I've not attached any screenshots as the UI is same as default with no env vars set(related to the Logo)
> 
> @yreddy-CS , you are on OpenMetadata version 1.1.7 right?

Yes.. I'm using docker.getcollate.io/openmetadata/server:1.1.7 image

**Comment by mohityadav766** [comment]
@yreddy-CS can you please use the UI to set the CustomLogConfiguration

**Comment by yreddy-CS** [comment]
@mohityadav766  Are you saying until the inconsistency is resolved, we use the UI or that configuring through the UI is the only way we can set this and that this is not a bug?

**Comment by mohityadav766** [comment]
@yreddy-CS configuration of logo from the UI should be the way to go , since the env var configuration is a first time startup config which will be removed in coming versions

**Comment by yreddy-CS** [comment]
Thank you for the clarification @mohityadav766
