### ISSUE TITLE
Mask data in API

### ISSUE THREAD

**Issue by kaivalyapendse** [open-metadata/OpenMetadata#13628]
**Is your feature request related to a problem? Please describe.**
The user database credentials and other sensitive information are being exposed in API which should not be the case

**Describe the solution you'd like**
Mask the credentials in API headers and response. Encrypt the details while sending the details to client, decryption should happen at client end

Attaching the current issue observed.

![Screenshot from 2023-10-18 12-22-11](https://github.com/open-metadata/OpenMetadata/assets/42967267/948d4753-9952-4bd3-82f1-747031f1cad3)

**Comment by pmbrull** [comment]
https://docs.open-metadata.org/v1.1.x/deployment/secrets-manager
