### ISSUE TITLE
Failed to connect to mssql

### ISSUE THREAD

**Issue by cgustavoof** [open-metadata/OpenMetadata#13622]
Affected: Database Services

When server name contains \, for example SERVER\NAME1

Error message:

CheckAccess *
Failed
Failed to connect to mssql, please validate the credentials
Show logs
(pytds.tds_base.LoginError) ("Cannot connect to server 'SERVER': [Errno -5] No address associated with hostname", gaierror(-5, 'No address associated with hostname')) (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by harshach** [comment]
@cgustavoof as the error says "No address associated with hostname" wherever you are running the ingestion is not able to resolve the mssql hostname. Please fix that then it will work.

**Comment by cgustavoof** [comment]
the server is correct, the problem occurs when I have a server where the name contains the backslash, if I change it to a server that doesn't have it, it works.
