### ISSUE TITLE
Limit user to domain access

### ISSUE THREAD

**Issue by kevinl1210** [open-metadata/OpenMetadata#13644]
**Is your feature request related to a problem? Please describe.**
With the latest OMD 1.2.0 beta version, there is a new Domain capability, it works great to separate data assets and products in different domain. However, domains can be accessed by any user in the organization, in current release, user can choose any domains and view any assets.

**Describe the solution you'd like**
We would like to have a feature that can assign users to domain, thus they can only choose the domain that they are assigned and view only restricted assets.

**Describe alternatives you've considered**
No other alternatives.

**Additional context**
N/A

**Comment by forastieri** [comment]
Hey everyone, I'm facing this need, but it's not just about the user viewing their own domain. In this case, the user could view other domains, but this user can only edit the objects in the domain for which they have permission.

**Comment by mohityadav766** [comment]
@forastieri we have domain only access policy try using that , it will restrict domain access only
