### ISSUE TITLE
Airflow task status 'skipped'

### ISSUE THREAD

**Issue by KsM00000** [open-metadata/OpenMetadata#13649]
**Affected module**
UI

**Describe the bug**
I have a dag with three tasks. 
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/9aee61c6-71b4-46ee-af95-b75206eb5c27)

Task1 checks the date. Depending on it either task2 or task3 is chosen to run, another task is skipped. 
I noticed that skipped tasks in OM have a status 'pending'. So now I have a bunch of tasks with the status 'pending' in one dag, despite them being completed with the expected result.
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/97f224b7-f20a-4d4b-a4ca-e553f2fd0bc3)

I think it's kinda misleading, considering, well, everything.
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/218d462f-b6d4-40cd-8678-9cf80a85f65f)
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/a1ed5686-2e35-47fc-b1e9-b96fb7428506)

**Version:**
 - OpenMetadata version: 1.1.6
 - Airflow 2.5.1

**Comment by KsM00000** [comment]
I was asked to add details from airflow backend db about tasks.
So I will try to show different examples of dag runs from table task_instance in db (I hide some data because it is unimportant or sensitive).
1) Dag OIS_KRS_PRS. It is completed, it has two succesfull tasks and one skipped task. 
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/e1d63294-6fc2-4058-8228-9216c402cecc)
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/db9aa0b0-fe25-408c-a22e-1bc8ed2e6824)

2) Dag WI_LOAD_COORDINATES_PARAMETER. It is running. It has two succesfull tasks, one running task and nine tasks with no status who are waiting to run. 
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/14233b5f-9166-4238-95e9-06ed4bdb5369)
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/f27274a9-0ab8-4d81-ad51-c455f14b59f3)

3) Dag example_test. It is stopped. It was running, but then I stopped it before its finished its run, so now it has one successful task, one scheduled task and two tasks with no status.
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/06815703-ec0c-4994-a64d-2de5a9da73ab)
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/69b9fb48-4247-4388-8387-b72bac6bff91)

@ me if you need more data (but I kinda need to know what to look for specifically).

**Comment by pmbrull** [comment]
@chirag-madlani any updates on the icon?
