### ISSUE TITLE
Add Permissions for specific Tier/Tag

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#13657]
**Is your feature request related to a problem? Please describe.**
Our organization use 'Tier 1' to document the most important data assets. 
We have automatic process that put the tag according to standing in the requirements. 
Currently in OMD, anyone can add 'Tier 1' tag on the assets, meaning we cannot control the assets credibility. 

**Describe the solution you'd like**
An option to set permissions per tag, so only specific role can assign specific tag (in our case it will be a bot, but it can be any role).

**Comment by harshach** [comment]
fixed in 1.6.0
