### ISSUE TITLE
Email or Slack Notifications about pending tasks in Glossary Approval Workflow

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#13669]
**Is your feature request related to a problem? **
In OpenMetadata v1.2 it is currently unavailable to send notifications about pending tasks in Glossary Approval Workflow to reviewers both via Slack or e-mail.

**Describe the solution you'd like**
Maybe you will add a new event type (for example "Pending approval task") in order to set settings as it is shown at screenshot:
Trigger: - Data Assets: Glossary, Glossary Term
Filters: Event type (= Entity approval task)

![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/b84477bb-08ea-47d8-8300-a1ffe0440e5c)

And also please add to checkbox "Send to:" value "Reviewers" (not only Admins, Owners, Followers)

**Comment by mohityadav766** [comment]
Closing this 
OM wil support in coming version notification for any task that opens up, or gets updated (the user will be notified).
Getting pending task updates will be a scheduled notification that we will be supporting in future releases.
