### ISSUE TITLE
Opening a large glossary take a long time

### ISSUE THREAD

**Issue by UncleGollum** [open-metadata/OpenMetadata#13679]
Drawing Glossary with 3k of records takes < 20 sec. 

Is it possible to include a split to the multiple pages?

**Comment by pmbrull** [comment]
hi @UncleGollum could you please share some more info on how was this created? When you say 3k records, do you mean linekd assets?

any screenshots would be helpful as well to understand the scenario. Thanks

**Comment by UncleGollum** [comment]
For example, if i load "IATA Passenger Glossary of Terms" (https://www.iata.org/contentassets/04c5400c2dcd4b05a520330672b13ef6/iata-passenger-glossary-of-terms.xlsx), it was a single page with 1k of rows

**Comment by harshach** [comment]
This is fixed in 1.3.0
