### ISSUE TITLE
Database service name special characters breaks dbt on MSSQL

### ISSUE THREAD

**Issue by josephniblo** [open-metadata/OpenMetadata#13674]
**Affected module**
Ingestion (dbt on MSSQL)

**Describe the bug**
When ingesting dbt for a MSSQL database, if the database service was named using special characters, the dbt data is not ingested at all, and warnings are seen in the logs that the object names in the dbt manifest/catalog do not match those in the metadata for the database service in OM.

**To Reproduce**

Create a MSSQL Database service named "(local)"
(It is not known which special characters cause the issues, but a bracket should repro) 

Ingest Metadata

Using a dbt project pre-configured for the ingested database, create a dbt ingestion 

Observe warnings in logs like 
`[2023-10-20T15:20:09.271+0000] {metadata.py:447} WARNING - Unable to find the table ... <MATCHING TABLE NAME>`

Note that the dbt ingestion run may still pass.

**Expected behavior**
Either the matching names should be identified,
or it shouldn't be possible to name the service using special characters which cause issues

**Version:**

 - OpenMetadata version: 1.1.7
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/ingestion:1.1.7

**Additional context**
https://openmetadata.slack.com/archives/C02B6955S4S/p1697800366303799

**Comment by pmbrull** [comment]
hi @josephniblo can you share an example of a MSSQL database name that is not working for you?

**Comment by josephniblo** [comment]
Hi @pmbrull, yes - try "(local)". That is, include the brackets in the name.

**Comment by OnkarVO7** [comment]
@josephniblo tested this with the 1.2 release and it is working.

Please upgrade to the same and try it out. Closing the issue, feel free to re-open it if the issue still persists after upgrading we can take a look then.
