### ISSUE TITLE
how to customize defult profile ingestion  query

### ISSUE THREAD

**Issue by alitehranim** [open-metadata/OpenMetadata#13685]
i want customize defult profile ingestion  query in open metadata 1.1.7 Because defult profile ingestion query >> blocks our databases
Please advise.

**Comment by pmbrull** [comment]
hi @alitehranim can you give us some more details? What do you mean that the profiler queries block the database?

**Comment by alitehranim** [comment]
hi pmbrull ,in my  operational database ,when run profile ingestion ,all task in database slow and It will be disturbed .I want to customize the query related to this case to prevent this problem.
Thankful

**Comment by alitehranim** [comment]
@pmbrull ,
To write a SQL query in an operational database without blocking, you can use the NOLOCK hint. The NOLOCK hint allows a query to read data without acquiring locks on the tables or rows being accessed. This can improve query performance but also introduces the risk of dirty reads, where the data being read might not be consistent or accurate if it is being modified by another transaction at the same time[[8]](https://www.mssqltips.com/sqlservertip/2470/understanding-the-sql-server-nolock-hint/).
SELECT * FROM TableName WITH (NOLOCK) WHERE ...
Replace TableName with the actual name of the table you want to query, and add any necessary conditions in the WHERE clause.

It's important to note that using the NOLOCK hint is not always recommended, as it can lead to inconsistent or inaccurate data. It's advisable to use it only when you understand the potential risks and have determined that the trade-off is acceptable for your specific use case.

**Comment by alitehranim** [comment]
hi @pmbrull <https://github.com/pmbrull> ,in my operational database ,when
run profile ingestion ,all task in database slow and It will be disturbed
.I want to customize the query related to this case to prevent this problem.

To write a SQL query in an operational database without blocking, you can
use the NOLOCK hint. The NOLOCK hint allows a query to read data without
acquiring locks on the tables or rows being accessed. This can improve
query performance but also introduces the risk of dirty reads, where the
data being read might not be consistent or accurate if it is being modified
by another transaction at the same time[8]
<https://www.mssqltips.com/sqlservertip/2470/understanding-the-sql-server-nolock-hint/>
.
SELECT * FROM TableName WITH (NOLOCK) WHERE ...
Replace TableName with the actual name of the table you want to query, and
add any necessary conditions in the WHERE clause.

It's important to note that using the NOLOCK hint is not always
recommended, as it can lead to inconsistent or inaccurate data. It's
advisable to use it only when you understand the potential risks and have
determined that the trade-off is acceptable for your specific use case.
Thankful
