### ISSUE TITLE
metadata command line tool should be in a docker container

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1369]
Some users have problems running ```metadata```. A suggested solution from one of our users is to create a docker container of the command ```metadata``` with all the dependencies like Temporal is also doing.
![image](https://user-images.githubusercontent.com/32617/143256453-6d79731c-e5e1-46a4-b8a7-c6f01e2ea08a.png)

**Comment by harshach** [comment]
metadata docker command is to check for user's environment and make sure they have right settings before we stat the docker containers.
Previously users needs to checkout out the repo of OpenMetadata and run docker-compose up against docker-compose.yml
with metadata docker command we are downloading this file and running it in user's env. It makes it much simpler experience than asking users to do docker-compose

**Comment by sureshms** [comment]
Per discussion with @amiorin this week, current `metadata` docker command is okay. We need to make sure, when users don't follow the documented steps, we are able to catch them and suggest running those steps (or avoid those steps of setting environment altogether). @amiorin, if you agree lets close this issue. @harshach, please do create issues to make the current install process more robust and less error prone.

**Comment by amiorin** [comment]
I agree.
