### ISSUE TITLE
mssql ingestion doesn't work using the UI wizard

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1370]
I was supporting a user and I don't recall the exact error but it was something about encryption. I'll try to reproduce it on my computer later and update the issue.

**Comment by amiorin** [comment]
It could be the TLS support. At the moment with don't include this dependency.
From https://github.com/denisenkom/pytds#installation

![image](https://user-images.githubusercontent.com/32617/143398801-ddf48974-0e57-476f-b1ec-546c075ec29e.png)

**Comment by harshach** [comment]
@amiorin do you have the error stack trace or error message when it happened. 
we don't need to install pyOpenSSL and as the mssql package itself will come up with its own dependencies.
Lets also make sure we include enough information to debug and reproduce. Without logs its hard to understand what exactly is the issue

**Comment by harshach** [comment]
TLS support is added to MSSQL. Closing it as fixed.
