### ISSUE TITLE
Garbage characters appear when import a glossary term CSV file contaning DBCS characters

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#13701]
**Affected module**
Govern->Glossary->Import

**Describe the bug**
I tried to import a glossary term CSV file containing DBCS Chinese characters. The import is successful but all Chinese characters become garbage characters.

**To Reproduce**
The glossary term file:
![圖片](https://github.com/open-metadata/OpenMetadata/assets/85471195/c0a6605a-f221-4e54-a1e6-3fd0500c6bbe)

The import result:
<img width="715" alt="Import glossary terms" src="https://github.com/open-metadata/OpenMetadata/assets/85471195/4e0c5a2f-a9db-41cc-8b11-0f4edceec859">

**Expected behavior**
Since we can enter and display Chinese characters in OM. Importing should work, too.

**Version:**
 - Python version:
 - OpenMetadata version: [1.1]
 - OpenMetadata Ingestion package version: []

**Additional context**
N/A

**Comment by pmbrull** [comment]
hi, we had similar issues where Excel did not properly store special characters.

Can you try a small example editing the file with any other editor that does not update the content?

I have exported a sample glossary from the [Sandbox](https://sandbox.open-metadata.org/glossary/job_data_government) and imported it to a new instance without any issues.

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/b7c16c1d-9a1d-4240-9818-5b7066a4fb1e)

Thanks

**Comment by AntonioChen0206** [comment]
@pmbrull  I use OM 1.2 and your way to rerty and it works. Thanks for help.
