### ISSUE TITLE
Ingest metadata in your local Openmetadata is failing for some users

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1371]
I have tried to support two users and we were not able to get the first ingestion done. Problems found so far:

1. README.md of the project is inconsistent with the online documentation.
2. metadata docker --start doesn't work in Windows.
3. Docker version of Openmetadata is super slow and if fails on my Macbook Silicon.
4. One user wanted to create a "hello world" script in Python to programmatically create assets in OM. There is no guide on how to do that.

**Comment by harshach** [comment]
@amiorin 
3. I ran this multiples times in OSX M1. Can you give us more details what's failing in your setup. Providing debug log would be helpful.
4. Have you looked into this https://docs.open-metadata.org/open-source-community/developer/build-a-connector

**Comment by harshach** [comment]
@amiorin do you want to come up with a doc for 4th item in your list. May be an predefined example would be great that others can copy

**Comment by amiorin** [comment]
I've talked with the user about the 4th item and the suggestion is to have a tutorial on how to create a CLI in python to link two entities with the UPSTREAM relationship for the lineage cross-service (Kafka topic -> Glue table).

**Comment by harshach** [comment]
@amiorin ok why don't you come up with that doc.

**Comment by harshach** [comment]
1. Fixed
2. metadata docker --start does work in windows with WSL 2.
3. docker version on m1 looks good to me, native M1 is supported after the feedback for MySQL and ES
4. Its being addressed here https://github.com/open-metadata/OpenMetadata/issues/1488
