### ISSUE TITLE
Tag search inconistency

### ISSUE THREAD

**Issue by 07Himank** [open-metadata/OpenMetadata#13725]
there is some inconsistency in tag searching .. minor thing looking into it.
1 :- when we search for tags , at end it doesnt show any result
for eg if we search for specailcategory it works till specailcategor after exact match it does not give result.
for refrence video :-

Added two examples in video.

https://github.com/open-metadata/OpenMetadata/assets/112613760/634900ff-3652-4b31-9115-2e50daba2dd8

I am finding the root cause.

**Comment by harshach** [comment]
@07Himank is there anything to do here?  cc @karanh37

**Comment by 07Himank** [comment]
@harshach This is already Fixed
