### ISSUE TITLE
Any user can change an attribute of an object by creating a task

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#13735]
**Affected module**
UI and backend

**Describe the bug**
A user without the rights to edit an object can create a request to edit an attribute and, putting himself in the place of the assignee, make a change.

**To Reproduce**
![22_screen_cast](https://github.com/open-metadata/OpenMetadata/assets/61934044/0be47f74-c30c-49e6-9b09-49152abe7ec0)

**Expected behavior**
Object attributes can be changed as a result of task approval ONLY if the user who approved the change has the rights to edit the attribute.

**Version:**
 - OpenMetadata version: 1.1.7

**Additional context**
Prohibiting the change of the assignee when creating a task would be the wrong decision. Because if I set up the policies in such a way that the owner cannot change the description, he will be able to do this through task approval!!

**Comment by harshach** [comment]
@chirag-madlani let's close this for 1.2.3. 
If there is an owner assigned to a table, we should make them the assignee for the task and do not allow the user who is creating the task to add another assignee or change the assignee.

**Comment by chirag-madlani** [comment]
Hi, @AlekseevVadim Thanks for putting time into validating this. 
I somehow missed 1.2.3, So I have added it to 1.2.4. Here the commit: 2c901309edb0536a59e5494deaf72f79c3fd342b
