### ISSUE TITLE
Improve DQ Resolution Flow

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#13746]
### Context and Abstract
In 1.1.0 we introduce a resolution flow allowing user to understand the status of a data quality failure. In of 1.1.0 and 1.2.0 users are able to set 3 status:
- `New`: denote a newly failed data quality test
- `Ack`: denote an acknowledge failure (i.e. we are working on solving it)
- `Resolved`: denote a solved data quality failure

in 1.3.0 we will introduce an enhanced flow adding 2 additional status:
- `assign`: allows to assign the resolution to someone else
     - assignee
- `review`: we'll be introducing a new policy `tests resolution approval`, users without this policy will not be able to mark issue as resolved. They will need to set a reviewer. It should include the following fields
    -  reviewer
    -  resolution summary

assigning an assignee or a reviewer should open a task for the user of concern. Closing a task for an assignee result in a review or a resolution (depending on the permission). Closing a reviewer task should result in a resolution. When a task is marked as resolved, a user should be able to choose if they want to mark all the previously failed tests as resolved as well.

We will also prevent users from changing the status of a resolved test case failure. 

### User Stories
- As a user I want to be able to track what DQ issues do I need to solve 
- As a user I want to be able to control who can mark a DQ issue as resolved

### Resolution flow approval diagram
![image](https://github.com/open-metadata/OpenMetadata/assets/13626425/62bd8641-d0e6-4780-b843-3702c3e6893a)

Below are the lists of all the permutation for the task status

```
combination ('New', 'Ack')
-------
New -> Ack
Ack -> New

combination ('New', 'Assigned')
-------
New -> Assigned
Assigned -> New

combination ('New', 'InReview')
-------
New -> InReview
InReview -> New

combination ('New', 'Resolved')
-------
New -> Resolved

combination ('Ack', 'Assigned')
-------
Ack -> Assigned
Assigned -> Ack

combination ('Ack', 'InReview')
-------
Ack -> InReview
InReview -> Ack

combination ('Ack', 'Resolved')
-------
Ack  -> Resolved

combination ('Assigned', 'InReview')
-------
Assigned -> InReview
InReview -> Assigned

combination ('Assigned', 'Resolved')
-------
Assigned -> Resolved

combination ('InReview', 'Resolved')
-------
Resolved -> InReview

combination ('New', 'Ack', 'Assigned')
-------
New -> Ack -> Assigned
New -> Assigned -> Ack
Ack -> New -> Assigned
Ack -> Assigned -> New
Assigned -> New -> Ack
Assigned -> Ack -> New

combination ('New', 'Ack', 'InReview')
-------
New -> Ack -> InReview
New -> InReview -> Ack
Ack -> New -> InReview
Ack -> InReview -> New
InReview -> New -> Ack
InReview -> Ack -> New

combination ('New', 'Ack', 'Resolved')
-------
New -> Ack -> Resolved
Ack -> New -> Resolved

combination ('New', 'Assigned', 'InReview')
-------
New -> Assigned -> InReview
New -> InReview -> Assigned
Assigned -> New -> InReview
Assigned -> InReview -> New
InReview -> New -> Assigned
InReview -> Assigned -> New

combination ('New', 'Assigned', 'Resolved')
-------
New -> Assigned -> Resolved
Assigned -> New -> Resolved

combination ('New', 'InReview', 'Resolved')
-------
New -> InReview -> Resolved
InReview -> New -> Resolved

combination ('Ack', 'Assigned', 'InReview')
-------
Ack -> Assigned -> InReview
Ack -> InReview -> Assigned
Assigned -> Ack -> InReview
Assigned -> InReview -> Ack
InReview -> Ack -> Assigned
InReview -> Assigned -> Ack

combination ('Ack', 'Assigned', 'Resolved')
-------
Ack -> Assigned -> Resolved
Assigned -> Ack -> Resolved

combination ('Ack', 'InReview', 'Resolved')
-------
Ack -> InReview -> Resolved
InReview -> Ack -> Resolved

combination ('Assigned', 'InReview', 'Resolved')
-------
Assigned -> InReview -> Resolved
InReview -> Assigned -> Resolved

combination ('New', 'Ack', 'Assigned', 'InReview')
-------
New -> Ack -> Assigned -> InReview
New -> Ack -> InReview -> Assigned
New -> Assigned -> Ack -> InReview
New -> Assigned -> InReview -> Ack
New -> InReview -> Ack -> Assigned
New -> InReview -> Assigned -> Ack
Ack -> New -> Assigned -> InReview
Ack -> New -> InReview -> Assigned
Ack -> Assigned -> New -> InReview
Ack -> Assigned -> InReview -> New
Ack -> InReview -> New -> Assigned
Ack -> InReview -> Assigned -> New
Assigned -> New -> Ack -> InReview
Assigned -> New -> InReview -> Ack
Assigned -> Ack -> New -> InReview
Assigned -> Ack -> InReview -> New
Assigned -> InReview -> New -> Ack
Assigned -> InReview -> Ack -> New
InReview -> New -> Ack -> Assigned
InReview -> New -> Assigned -> Ack
InReview -> Ack -> New -> Assigned
InReview -> Ack -> Assigned -> New
InReview -> Assigned -> New -> Ack
InReview -> Assigned -> Ack -> New

combination ('New', 'Ack', 'Assigned', 'Resolved')
-------
New -> Ack -> Assigned -> Resolved
New -> Assigned -> Ack -> Resolved
Ack -> New -> Assigned -> Resolved
Ack -> Assigned -> New -> Resolved
Assigned -> New -> Ack -> Resolved
Assigned -> Ack -> New -> Resolved

combination ('New', 'Ack', 'InReview', 'Resolved')
-------
New -> Ack -> InReview -> Resolved
New -> InReview -> Ack -> Resolved
Ack -> New -> InReview -> Resolved
Ack -> InReview -> New -> Resolved
InReview -> New -> Ack -> Resolved
InReview -> Ack -> New -> Resolved


combination ('New', 'Assigned', 'InReview', 'Resolved')
-------
New -> Assigned -> InReview -> Resolved
New -> InReview -> Assigned -> Resolved
Assigned -> New -> InReview -> Resolved
Assigned -> InReview -> New -> Resolved
InReview -> New -> Assigned -> Resolved
InReview -> Assigned -> New -> Resolved

combination ('Ack', 'Assigned', 'InReview', 'Resolved')
-------
Ack -> Assigned -> InReview -> Resolved
Ack -> InReview -> Assigned -> Resolved
Assigned -> Ack -> InReview -> Resolved
Assigned -> InReview -> Ack -> Resolved
InReview -> Ack -> Assigned -> Resolved
InReview -> Assigned -> Ack -> Resolved


combination ('New', 'Ack', 'Assigned', 'InReview', 'Resolved')
-------
New -> Ack -> Assigned -> InReview -> Resolved
New -> Ack -> InReview -> Assigned -> Resolved
New -> Assigned -> Ack -> InReview -> Resolved
New -> Assigned -> InReview -> Ack -> Resolved
New -> InReview -> Ack -> Assigned -> Resolved
New -> InReview -> Assigned -> Ack -> Resolved
New -> Resolved -> Ack -> Assigned -> InReview
New -> Resolved -> Ack -> InReview -> Assigned
New -> Resolved -> Assigned -> Ack -> InReview
New -> Resolved -> Assigned -> InReview -> Ack
New -> Resolved -> InReview -> Ack -> Assigned
New -> Resolved -> InReview -> Assigned -> Ack
Ack -> New -> Assigned -> InReview -> Resolved
Ack -> New -> InReview -> Assigned -> Resolved
Ack -> Assigned -> New -> InReview -> Resolved
Ack -> Assigned -> InReview -> New -> Resolved
Ack -> InReview -> New -> Assigned -> Resolved
Ack -> InReview -> Assigned -> New -> Resolved
Ack -> Resolved -> New -> Assigned -> InReview
Ack -> Resolved -> New -> InReview -> Assigned
Ack -> Resolved -> Assigned -> New -> InReview
Ack -> Resolved -> Assigned -> InReview -> New
Ack -> Resolved -> InReview -> New -> Assigned
Ack -> Resolved -> InReview -> Assigned -> New
Assigned -> New -> Ack -> InReview -> Resolved
Assigned -> New -> InReview -> Ack -> Resolved
Assigned -> Ack -> New -> InReview -> Resolved
Assigned -> Ack -> InReview -> New -> Resolved
Assigned -> InReview -> New -> Ack -> Resolved
Assigned -> InReview -> Ack -> New -> Resolved
InReview -> New -> Ack -> Assigned -> Resolved
InReview -> New -> Assigned -> Ack -> Resolved
InReview -> Ack -> New -> Assigned -> Resolved
InReview -> Ack -> Assigned -> New -> Resolved
InReview -> Assigned -> New -> Ack -> Resolved
InReview -> Assigned -> Ack -> New -> Resolved
```

#### Backend
- [x] #14049
- [x] Add `assign` status.
- [ ] ~~Create "resolution approval" permission~~
- [x] #14248
- [x] Make test case resolution status with status "resolved" immutable
- [x] #14331
- [ ] Implement severity failure inference

#### Ingestion
- [ ] ~~Update logic to post in the new flow~~

#### UI
- [ ] Implement Resolution center as per mock

**Comment by pmbrull** [comment]
## Scenario 1 - Incident Details Page
1. Create Test Case
2. Run Test that fails
	1. The backend will automatically a `NEW` incident will be created
3. We can get the `incidentId` from the `testCase`
4. From the DQ page, we see `Incidents` column with `NEW`
5. Clicking on `NEW` will send us to the Incident page
6. We will see `Issues (1 Open)` 
7. We click on `Issues`
8. We add a comment on the issue
9. We click on `Reassign`
	1. The UI will send a `POST` request to `/api/v1/dataQuality/testCases/testCaseIncidentStatus` with the `"testCaseResolutionStatusType": "Assigned"`
	2. The backend will reassign the task under the hood (The UI does not need to "talk" to the task directly)
10. The new user, clicks on `Resolve`
	1. The UI will send a `POST` request to `/api/v1/dataQuality/testCases/testCaseIncidentStatus` with the `"testCaseResolutionStatusType": "Resolved"`
	2. The backend will automatically resolve and close the task. The UI does not need to talk to the task directly
11. We can validate that the incident is indeed `Resolved` and that the task is closed.

## Scenario 2 - Resolving task from the Incident List Page
1. Create Test Case
2. Run Test that fails
	1. The backend will automatically a `NEW` incident will be created
3. We can get the `incidentId` from the `testCase`
4. We go to the Incident Manager list page
5. We see our incident with status `NEW`
6. We click on `Reassign`
	1.  The UI will send a `POST` request to `/api/v1/dataQuality/testCases/testCaseIncidentStatus` with the `"testCaseResolutionStatusType": "Assigned"`
	2. The backend will reassign the task under the hood (The UI does not need to "talk" to the task directly)
7. We click on `Resolve`
	1. The UI will send a `POST` request to `/api/v1/dataQuality/testCases/testCaseIncidentStatus` with the `"testCaseResolutionStatusType": "Resolved"`
	2. The backend will automatically resolve and close the task. The UI does not need to talk to the task directly
8. We can validate that the incident is indeed `Resolved` and that the task is closed.

## Scenario 3 - Resolving & Rerunning
1. Create Test Case
2. Run Test that fails
	1. The backend will automatically a `NEW` incident will be created
3. We can get the `incidentId` from the `testCase`
4. We go to the Incident Manager list page
5. We click on `Resolve`
6. We can validate that the incident is indeed `Resolved` and that the task is closed.
7. We trigger the test failure again
8. A `NEW` task is created
9. We should have 1 open incident
	1. 1 open task
	2. 1 closed task
10. We `Resolve` the open incident
11. It will close the open task

## Scenario 4 - Rerunning an open incident
1. Create Test Case
2. Run Test that fails
	1. The backend will automatically a `NEW` incident will be created
3. We can get the `incidentId` from the `testCase`
4. The DQ page shows a `NEW` incident
5. If we click, we see that we have only 1 ongoing incident and 1 open task
6. Rerunning the test case again to trigger another failure won't open another task

**Comment by pmbrull** [comment]
- NEW
- ACK
	- Open a task with the selected assignee
- ASSIGNED
	- Open a task with the selected assignee if no task was created in ACK
	- If we go from ACK -> ASSIGNED, we update the task
- RESOLVED
	- must be manually closed
	- we won't automatically close after the test passes
	- only one unresolved incident alive at a time per each test case

We'll force the flow:
- NEW -> (ACK | ASSIGNED) -> ASSIGNED -> RESOLVED

**Comment by ShaileshParmar11** [comment]
> * NEW
> * ACK
>   
>   * Open a task with the selected assignee
> * ASSIGNED
>   
>   * Open a task with the selected assignee if no task was created in ACK
>   * If we go from ACK -> ASSIGNED, we update the task
> * RESOLVED
>   
>   * must be manually closed
>   * we won't automatically close after the test passes
>   * only one unresolved incident alive at a time per each test case
> 
> We'll force the flow:
> 
> * NEW -> (ACK | ASSIGNED) -> ASSIGNED -> RESOLVED

Do we need any change from UI side?
