### ISSUE TITLE
Improve pipeline details page as per mocks

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#13756]
#### Revamp Pipeline details page -- Dag view

- Find the mock below and update the design of Task DAG view with show in the mocks

Mocks https://www.figma.com/file/FPpKOFSoVddbtesFCQJVjM/OpenMetadata-Final-Screens?type=design&node-id=1906-26568&mode=design&t=Qfx0fbKHSWAanqBN-0

**Comment by chirag-madlani** [comment]
@ShaileshParmar11 Is there anything pending?
