### ISSUE TITLE
EventResource malformed entity info

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1375]
In [EventResource](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/events/EventResource.java#L102) we have
```java
EntityList entityCreatedList = new EntityList(entityCreated);
EntityList entityUpdatedList = new EntityList(entityCreated);
EntityList entityDeletedList = new EntityList(entityCreated);
```
Where we are always passing `entityCreated`. We should update this and review the tests.

If I try to align the variables and run the `TableResourceTests`, everything fails with

```
org.apache.http.client.HttpResponseException: status code: 400, reason phrase: argument is null or empty; this is forbidden on this call to `bindList`
```

As it then looks like we are trying to create a list from query parameters not being passed.

Thanks

**Comment by sureshms** [comment]
Good find. Both the code and the tests have bugs :). I will fix it.
