### ISSUE TITLE
Bug on JWT token auth docs. 

### ISSUE THREAD

**Issue by joaopedro02** [open-metadata/OpenMetadata#13751]
**Is some content missing, wrong or not clear?**

I think there is an error in the docs on the pages :
https://docs.open-metadata.org/v1.2.x/deployment/security/enable-jwt-tokens
https://docs.open-metadata.org/v1.2.x/deployment/security/jwt-troubleshooting

It's indicated to append a public key uri with `http` (in the format: `http://{your domain}:8585/api/v1/system/config/jwks`) so SSO an JWT token auth can work togheter. But i had to add a uri with `https` to enable SSO and JWT in my kubernets deployment using the helm chart.  The uri format i used was:  `https://{your domain}/api/v1/system/config/jwks`.

**Describe the solution you'd like**
I think it would be nice to change the uri format to something like `https://{your domain}/api/v1/system/config/jwks` 

**Additional context**
When i try to add a uri with `http` the open-metadata server throw the following error:

`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Moved': was expecting (JSON String, Array, Object or token 'null', 'true' or 'false' ...
`

I would be happy to contribute a pull request for this.

**Comment by harshach** [comment]
@joaopedro02 I mean I think its fairly clear right, if you enabled https use https or if not use http. We can't document at that minute level. The default is what we put together.
