### ISSUE TITLE
bug on domains: When the domain is switched, the metadata is not filtered correctly

### ISSUE THREAD

**Issue by gzusgw** [open-metadata/OpenMetadata#13762]
in version 1.2.0. assigned the domain information to the table's metadata, when the domain is switched, the metadata is not filtered correctly
![image](https://github.com/open-metadata/OpenMetadata/assets/37568108/685e878f-a5ad-4ff4-9a3f-789b7ea71e5c)
![image](https://github.com/open-metadata/OpenMetadata/assets/37568108/5fa65f94-a480-4885-a987-e211f81727d8)

**Comment by harshach** [comment]
try re-indexing the data. Again please visit slack and ask the questions before openign a ticket in github
