### ISSUE TITLE
Can't create lineage

### ISSUE THREAD

**Issue by NoStayUpLate** [open-metadata/OpenMetadata#13760]
**Affected module**
UI

**Describe the bug**
When i try to create a upstream lineage , the upstream table's name is too long too make the lineage.

**To Reproduce**
make a upstream lineage, the upstream table's name is more than 20 letters

**Expected behavior**
the upstream table's name support more than 20 letters

**Version:**
 - OS: windows
 - Python version:3.9
 - OpenMetadata version: 1.1
 - OpenMetadata Ingestion package version:

**Comment by TeddyCr** [comment]
@NoStayUpLate it would be great if you could share:
1. the full error logs you get from the application
2. the exact version of OM (we have 1.1.0-1.1.7).

**Comment by harshach** [comment]
@karanh37 can you validate if this bug still exists, if not close it out

**Comment by karanh37** [comment]
Can't reproduce with the latest version.
