### ISSUE TITLE
Expand all descriptions in Glossary terms

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#13775]
**Is your feature request related to a problem? Please describe.**
In the current version of Metadata v1.2 the button "Expand all" in Glossary doesn't allow to see the whole description.

**Describe the solution you'd like**
We decided to use Glossary to govern product event. In our company it is crucial to navigate in them via images, so we would like to see all the glossary term descriptions in their entirety.
I have two ideas how it can be implemented:
1) When user clicks on the button "Expand all" (as it is on screenshot) - all descriptions will be presented (not only the hierarchy of terms will be expanded but also every description of term). So there will be no necessity to click "More" in every description.
2) You can add new button to expand all descriptions of terms at the same time.
![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/ab4338aa-f575-4bb0-869e-19464373dc93)

**Comment by harshach** [comment]
@LiubovPasechnik what happens if the description has 10 lines in each term. That won't be fitting in a row

**Comment by LiubovPasechnik** [comment]
Also we understand that for better display it is also possible to add an option to expand descriptions only for a particular branch of the hierarchy of terms.

**Comment by LiubovPasechnik** [comment]
Dear @chirag-madlani and @karanh37,
I can clarify my request:
1) It is possible to add a button "Expand all descriptions" near the current location of button "Expand all". So there will be two buttons: one to expand all hierarchies of terms and another to expand all descriptions.
2) Also we would like to be able to expand all descriptions only in the particular branch of terms. So for instance it is possible to put such button where the star is located at the screenshot:
![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/27f886eb-8485-4345-84d4-bd1bab9ee8d1)

**Comment by harshach** [comment]
we don't want to add yet another button to do this. @LiubovPasechnik how often this action is performed and are all of your users will do this operation?
