### ISSUE TITLE
Translated deletion dialogs break the confirmation logic

### ISSUE THREAD

**Issue by fw8** [open-metadata/OpenMetadata#13771]
**Affected module**
UI

**Describe the bug**
I switched to german in OMD1.2 and now the DELETE dialog is in german but the logic is still english... means you have to type "DELETE" and not "LÖSCHEN". I'm fine with "DELETE" but this word should then NOT be translated...

**To Reproduce**
Switch to german, delete something (e.g. an ingestion pipeline), try to enter the given confirmation word.

![image](https://github.com/open-metadata/OpenMetadata/assets/10989436/1145c398-4ce8-4d78-b2e2-f45e1a2b1117)

**Expected behavior**
The given confirmation word should be accepted.

**Version:**
 - OpenMetadata version: 1.2.0

**Comment by chirag-madlani** [comment]
Hi @fw8 
Thanks for raising your concern, It's already fixed here: https://github.com/open-metadata/OpenMetadata/pull/14769
It's already available with latest version. Thank you
