### ISSUE TITLE
Immutable column width in Glossary hierachy

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#13776]
**Affected module**
UI (Glossary)

**Describe the bug**
When the name of term is long it takes up too much space in column. Please add an opportunity to change the width of each column because it is inconvenient to navigate in glossary term hierarchy when 1 term has a long name but other don't.

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/1d9aa348-672e-4090-b2e0-ffdd53cd1ecb)

![image](https://github.com/open-metadata/OpenMetadata/assets/132373127/52b9a5c1-13f4-4487-9faf-06c499b04d0d)

**Expected behavior**
It is possible to change the size of column manually and long names can be displayed in several rows.

**Version:**
v 1.2

**Comment by LiubovPasechnik** [comment]
Also please take into account this issue:
https://github.com/open-metadata/OpenMetadata/issues/13798

I suppose we can combine these issues in one.

**Comment by chirag-madlani** [comment]
Fixed with 1.3.0

![Image](https://github.com/open-metadata/OpenMetadata/assets/12962843/ff79344c-1559-45f5-af82-c3e223fdd16a)
