### ISSUE TITLE
New service type: API

### ISSUE THREAD

**Issue by Iture** [open-metadata/OpenMetadata#13780]
**Is your feature request related to a problem? Please describe.**
In my organization, large part of data is accessible through REST or GRAPHQL API. I would like to list such APIs in Data Catalog, to provide users knowledge about these data sources.

**Describe the solution you'd like**
I would like to have a new service type: API. Under it, I'm able to ingest REST or GraphQL endpoint, with automatic description ingested from i.e. Swagger. API of curse can be versioned.

**Comment by harshach** [comment]
@Iture we already have a ticket tracking this feature request https://github.com/open-metadata/OpenMetadata/issues/10933 . Please add your requirements there if its not already captured.
