### ISSUE TITLE
Dependencies between services and ingestions are not clear

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1378]
1. One of our users provided feedback that it was not clear for him that he was supposed to create the service before configuring the ingestion.
![image](https://user-images.githubusercontent.com/32617/143319520-cbf1ba05-f2a2-467c-be79-b6d20fcb7d3a.png)
1. Another feedback was about using the word JDBC even if our ingestion framework is written in Python and SQLAlchemy.
![image](https://user-images.githubusercontent.com/32617/143319689-0695c314-9120-410e-8e8a-3e48585c7d82.png)
1. Another feedback was about the wording "Select Service". He thinks it should be "Select Database Service Type".
![image](https://user-images.githubusercontent.com/32617/143319800-409cef5b-c093-4c83-af5b-ee86e9d752d4.png)

**Comment by harshach** [comment]
Its captured in this ticket https://github.com/open-metadata/OpenMetadata/issues/1310 . Intent is move connection details out of the service and make that connection specific for each connector and capture all the details required.

**Comment by amiorin** [comment]
👍

**Comment by sureshms** [comment]
@amiorin and @harshach, is this issue still relevant? If not, can we close this?

**Comment by amiorin** [comment]
Closing because the issue is captured in #1310
