### ISSUE TITLE
Reinitiate workflow

### ISSUE THREAD

**Issue by gzusgw** [open-metadata/OpenMetadata#13783]
A rejected approval workflow allows the owner to modify it and reinitiate approval

**Comment by harshach** [comment]
@gzusgw there is comments to collaborate around that discussion. They don't need to reject? why we need this option

**Comment by gzusgw** [comment]
@harshach  In my understanding, the mention that collaboration brings to each other is less direct than bringing each other a task. For a user, seeing a task to be processed may be prioritized.
