### ISSUE TITLE
Creating an ingestion job when airflow is down returns 400

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1379]
I was trying to create an ingestion job using the MySQL used by OM without having Airflow running and it returned 400.
![image](https://user-images.githubusercontent.com/32617/143320874-b62ad8e0-b6ac-4c08-a73d-03cc0f646a3c.png)

**Comment by Sachin-chaurasiya** [comment]
@harshach can you please add a documentation step for users if the airflow is not running.
