### ISSUE TITLE
Use Table Name in Advanced search

### ISSUE THREAD

**Issue by k3agan** [open-metadata/OpenMetadata#13805]
**Is your feature request related to a problem? Please describe.**

I would like to include or exclude tables in my search based on a prefix in the `Table Name`  (eg. `tmp_` or `Bkup_`)

**Describe the solution you'd like**
I would like to see the `Table Name` attribute as an option in the advanced search feature.

**Describe alternatives you've considered**

![image (2)](https://github.com/open-metadata/OpenMetadata/assets/56366381/4dc60f47-53fd-42ec-9b25-bf064bdc0386)

**Additional context**

**Comment by aniketkatkar97** [comment]
Added the Display Name filter in #17829
