### ISSUE TITLE
[UI] Data Insight Layout looks broken in case of large number of assets

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#13803]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
Please see the video attached.

https://github.com/open-metadata/OpenMetadata/assets/105265192/0030d260-04ae-489d-8880-ddd1d4d3de7e

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohityadav766** [comment]
Opening this needs work from UI

**Comment by harshach** [comment]
@chirag-madlani @ShaileshParmar11 where are we with this
