### ISSUE TITLE
Out of sort memory, consider increasing server sort buffer size

### ISSUE THREAD

**Issue by jackxueman** [open-metadata/OpenMetadata#13808]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

<img width="1432" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/11639909/af904e63-f24a-4de8-829f-33cad9b19002">

**Expected behavior**

display normally

**Version:**
 - OS: linux
 - Python version: 3.9
 - OpenMetadata version: [1.0.4]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==1.0.4`]

**Additional context**

An exception with message [java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size [statement:"/* UserDAO.listAfter */ SELECT ue.json FROM user_entity ue LEFT JOIN entity_relationship er on ue.id = er.toId LEFT JOIN team_entity te on te.id = er.fromId and er.relation = :relation WHERE ue.deleted = FALSE AND JSON_EXTRACT(ue.json, '$.isAdmin') = TRUE AND (JSON_EXTRACT(ue.json, '$.isBot') IS NULL OR JSON_EXTRACT(ue.json, '$.isBot') = FALSE ) AND (:team IS NULL OR te.name = :team) AND ue.name > :after GROUP BY ue.name, ue.json ORDER BY ue.name LIMIT :limit", arguments:{positional:{4:null,5:16,6:,7:10}, named:{limit:16,team:null,after:,relation:10}, finder:[]}]] was thrown while processing request.

**Comment by harshach** [comment]
please use slack https://slack.open-metadata.org before opening a ticket.
Use latest release and follow the upgrade docs https://docs.open-metadata.org/v1.2.x/deployment/upgrade#update-sortbuffersize-mysql-or-workmem-postgres
