### ISSUE TITLE
In Advanced Search, Unable to choose [Database == ] String that is not in the truncated dropdown list.

### ISSUE THREAD

**Issue by k3agan** [open-metadata/OpenMetadata#13804]
**Affected module**
Advanced Search

**Describe the bug**
I can't search on a selected DB if it isn't in the incomplete Advance Search list.
 
![image](https://github.com/open-metadata/OpenMetadata/assets/56366381/1fe54207-5f09-4c42-b0ab-33fc924e4ed6)

**To Reproduce**

After I hit enter, it reverts to:
 
![image (1)](https://github.com/open-metadata/OpenMetadata/assets/56366381/0dd0df55-102a-43de-a23c-c640cd8edaaa)

**Expected behavior**

The dropdown list for `==` conditions should be complete, not truncated.

(The filtering works fine with the `Contains` condition, but I had to know the exact case sensitive string)

![image (2)](https://github.com/open-metadata/OpenMetadata/assets/56366381/cfe909cb-7712-4b96-97a1-aa3a6b18a0bc)

**Version:**
 - OS: Windows
 - Python version: Chrome
 - OpenMetadata version: **1.1.6**
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by k3agan** [comment]
Thank you @karanh37 👍

**Comment by karanh37** [comment]
@07Himank  - `aggregate` api provides results for fields which are part of the entity. It is not providing results for all fields.

**Comment by ShaileshParmar11** [comment]
since we are not reverting the PR, the issue is fixed
