### ISSUE TITLE
support for most custom properties to right side panel

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#13822]
**Is your feature request related to a problem? Please describe.**

- [ ] It's good to have custom properties listed on Right side panel for Asset details page
- [ ] At most 5 custom properties need to be listed on right side panel (read more will redirect to respective tab)
- [ ] Also good to have right side panel as collapsible 

<img width="1512" alt="Screenshot 2023-11-02 at 11 44 30 AM" src="https://github.com/open-metadata/OpenMetadata/assets/12962843/a08498cd-fec1-41a6-a251-7abe2e066a31">

**Comment by harshach** [comment]
@Sachin-chaurasiya are you working on this?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya are you working on this?

Hi @harshach, I haven't begun working on this yet. Is there anything else I need to consider in addition to the tasks mentioned above?

**Comment by chirag-madlani** [comment]
@harshach @Sachin-chaurasiya Pushing this to 1.4.0
We have more priority tasks to tackle for 1.3
