### ISSUE TITLE
How to upgrade smoothly

### ISSUE THREAD

**Issue by ZeroBugHero** [open-metadata/OpenMetadata#13836]
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

`--------------------------------------------`
1. My version is 1.0.3.
2. The server is deployed on bare metal.
3. openmetadata_ingestion Deploy with Docker.
4. Independent databases and Elasticsearch are used.
**How to upgrade without losing data, hoping for detailed documentation.**

**Comment by akash-jain-10** [comment]
Hello @ZeroBugHero . Please take a look at our Upgrade Docs [here](https://docs.open-metadata.org/v1.2.x/deployment/upgrade/bare-metal) for your above requirements! Let us know if there is anything missing / improvement required in the docs!

**Comment by ZeroBugHero** [comment]
<img width="907" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/122763218/29e6892f-d258-44a1-bba8-31eb9781f36d">
Does it still support es7.X?

**Comment by harshach** [comment]
@ZeroBugHero please use slack to ask questions .Github issues are not for support
we do not support 7.x anymore. Recommended to upgrade to 8.10.2
