### ISSUE TITLE
Organization Brand Color Palette

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#13846]
We allow users to choose ANY color for Styling assets (e.g., Glossary Terms)

We can evolve this and have an org setting to predefined a color palette to allow users to select only from there.

**Comment by Sachin-chaurasiya** [comment]
Hello @harshach, the initial PR from the UI has been merged https://github.com/open-metadata/OpenMetadata/pull/15714. We are now waiting for API changes from the backend. Once they are available, we will integrate them into the UI and mark this feature as complete.
