### ISSUE TITLE
python -m metadata should work

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1385]
To mitigate problems like "Command not found", we should implement this way of running our CLI.
![image](https://user-images.githubusercontent.com/32617/143407258-8aeb4d6a-9c0c-45e0-9713-e1c0bad48fbe.png)

**Comment by harshach** [comment]
@amiorin what are the cases where the metadata command is not found. If the package is installed metadata command is available. 
Please provide the steps where the package is installed but metadata command is not found.
