### ISSUE TITLE
Add additional ENV variable OPENMETADATA_EXTRA_ARGS

### ISSUE THREAD

**Issue by Ludden** [open-metadata/OpenMetadata#13867]
**Is your feature request related to a problem? Please describe.**
I have the need to specify additional JVM parameters which feels awkward to add under the existing `OPENMETADATA_JVM_PERFORMANCE_OPTS` variable. 

**Describe the solution you'd like**
Addition of another ENV variable e.g. `OPENMETADATA_EXTRA_ARGS` would make for a nicer way to separate parameters which are of concerns other than related to JVM performance.

**Describe alternatives you've considered**

**Additional context**
Example of other projects having similar options: https://github.com/apache/kafka/blob/3.6.0/bin/kafka-server-start.sh#L37

**Comment by akash-jain-10** [comment]
Hello @harshach . We do support `OPENMETADATA_OPTS` as per the shell script file [here](https://github.com/open-metadata/OpenMetadata/blob/ae046c502d5013866b8ff3ac0b384944a3df5133/bin/openmetadata-server-start.sh#L115-L120). This should work for above use case, right ?

**Comment by harshach** [comment]
how can they pass for K8s?

**Comment by harshach** [comment]
@akash-jain-10 lets document this for docker and K8s

**Comment by akash-jain-10** [comment]
Will have document this for Docker and K8s under [docker](https://docs.open-metadata.org/latest/deployment/docker#advanced) and [kubernetes faqs section (EKS,GCP,Azure,On-Prem)](https://docs.open-metadata.org/latest/deployment/kubernetes/eks#faqs) 👍🏼

**Comment by akash-jain-10** [comment]
@Ludden  - Kindly refer to the docs [here(docker)](https://docs.open-metadata.org/latest/deployment/docker#java-memory-heap-issue) and [here(kubernetes)](https://docs.open-metadata.org/latest/deployment/kubernetes/eks#java-memory-heap-issue) to add Environment Variables for OpenMetadata Application! Closing this Issue. Thanks.
