### ISSUE TITLE
Add tooltips around Domain Type to explain Domains

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#13879]
Issue from https://github.com/open-metadata/OpenMetadata/issues/13316#issuecomment-1743650290

- Needed some info/description around different domain types on UI 

Screenshots or steps to reproduce

<img width="872" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/d11f081c-f1b2-4c27-a91b-256144b995e7">

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
@Ashish8689 here is some reference for domain types - https://www.datamesh-architecture.com/#mesh

Descriptions should be:
Source-aligned
Domains that are closer to the sources corresponding to the events and data generated from the operational systems.

Aggregate
Domains that aggregate data from multiple source-aligned domains to provide data that can be consumed by many consumer-aligned domains.

Consumer-aligned
Domains that are user-facing where the end product of a combination of data from various domains are available for business users for decision-making.
