### ISSUE TITLE
Restrict Domain Propogation from Database Service

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#13900]
**Describe the bug**
Assigning Domain to Database Service using PATCH request propogates Domain field to children.

**Expected behavior**
Domain field propogation should only be done for Database and Schema. It should not be done for Database Service

**Comment by harshach** [comment]
@karanh37 is this still an issue?

**Comment by harshach** [comment]
tested it doesn't happen anymore
