### ISSUE TITLE
Make custom properties as a dropdown

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#13905]
**Is your feature request related to a problem? Please describe.**
In current version of OM (v 1.2) it is possible to create via API only custom properties with text format.

**Describe the solution you'd like**
 I would like as admin to be able to create custom properties (especially in glossary terms):
- also via UI (not only via API)
- as a dropdown (not only as a text field). 
The reason why we would like to have an option to create a dropdown is that it will reduce the human factor of mistake when user fills the value in the field and will make an advanced search more transparent.
So creating a dropdown means that admin or steward will be able to create a list of values for this dropdown (somewhere in admin panel or if it is difficult to do it in UI - please provide this functionality via API).

**Comment by pmbrull** [comment]
hi @harshach we were aiming for Enums in 1.3 right?

**Comment by harshach** [comment]
Enums are shipped in 1.3.1
