### ISSUE TITLE
support cost analysis re-index in Search indexing Application

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#13912]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

Issue from https://github.com/open-metadata/OpenMetadata/issues/13316#issuecomment-1790862772

**Describe the bug**

- Need to support cost analysis re-index in Search indexing Application for collate

**To Reproduce**

Screenshots or steps to reproduce

<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/0c7de455-6034-4020-a6d6-20fca167259e">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Ashish8689 need this to be cherry-picked
