### ISSUE TITLE
Postgres unclear error message for test connection

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#13934]
Postgres test connection gives below error when postgres is running locally and OM is running on docker
![image](https://github.com/open-metadata/OpenMetadata/assets/28966081/a911f9b0-ad2d-423a-954d-766a74b6c33c)

**Describe the task**
Improve the error message to point exactly what the error is and show the networking issue
The issue is resolved by following the steps [here](https://blog.devgenius.io/connect-locally-hosted-postgresql-from-docker-daffea720af1) and putting the hostport as `ip_address:5432`

**Comment by pmbrull** [comment]
the error is `HTTP/1.1 header parser received no bytes`.

We are getting that in a quite specific scenario:
- we point to a known URL (it does not get raised if we go, for example, to `random:9876`)
- the url does not allow the connection of the driver

For example, in a testing setting in OM, we can reproduce the error if we add the Postgres host as `ingestion:8080` (where Airflow runs), which clearly won't respond properly to the JDCB connection.
