### ISSUE TITLE
Callback URL mismatch in e-mail notifications (port missing)

### ISSUE THREAD

**Issue by vitaly-zverev** [open-metadata/OpenMetadata#13930]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
It impact the UI and backend

**Describe the bug**
E-mail notification has callback URL, derived from backend environment settings (OM_URI). 
Eventually, port number in callback URL lost in templating.

**To Reproduce**

For example:
docker compose exec -ti openmetadata-server bash -c set | grep -E 'OM_URI|OPENMETADATA_SERVER_URL'
OM_URI=' "http://localhost:8585/"'
OPENMETADATA_SERVER_URL='""'

but, in e-mail message I got the 'reset link', pointing on http://localhost/

**Expected behavior**
'reset link' pointing on http://localhost:8585/

**Version:**
 - OS:  Linux 5.15.90.1-microsoft-standard-WSL2
 - Python version: 3.8.10
 - OpenMetadata version: 1.2.0
 - OpenMetadata Ingestion package version:  openmetadata-ingestion==1.2.0

**Comment by vitaly-zverev** [comment]
To reproduce issue step by step:
1) git clone https://github.com/vitaly-zverev/OpenMetadata.git issue_13930 
2) cd issue_13930 && git switch issue_13930_Callback_URL_mismatch 
3) docker compose -f docker/docker-compose-quickstart/docker-compose-postgres-carbonio.yml up -d
4) docker compose -f docker/docker-compose-quickstart/docker-compose-postgres-carbonio.yml exec -ti carbonio /opt/zextras/bin/zmprov createDomain openmetadata.org
5) docker compose -f docker/docker-compose-quickstart/docker-compose-postgres-carbonio.yml exec -ti carbonio /opt/zextras/bin/zmprov createAccount admin@openmetadata.org P@ssw0rd
6) Open http://localhost:8585/forgot-password and submit form for admin@openmetedata.org
7) Open https://localhost/carbonio, login as admin/P@ssw0rd and check mail
8) We can see 'Reset link', pointed on 'http://localhost/users/password/reset?user=admin...'

**Comment by mohityadav766** [comment]
hi @vitaly-zverev this should be fixed in upcoming version, setting openmetadata_url -> this is used to generate the url OM_URI is removed
