### ISSUE TITLE
glossaryTerm: tags lost  if added from the "bulk" screen

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#13958]
**Affected module**
Glossary. Issue noticed in 1.1, still valid in 1.2

**Describe the bug**
glossaryTerm: tags lost  if added from the "bulk" screen

**To Reproduce**
I edit glossaryTerm tags from the Glossary:
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/7078d4e1-1232-4505-bfab-b62fe31afc05)

Even if Client has a tag "tag1"
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/b4f45380-0c64-4110-aaf2-f00ca8009b70)

When editing, from the glossary screen - the tag is not visible and and when I add a new one - the original is lost, as visible from the version history:
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/3f9ff7b7-647d-4ac0-92da-97990025b3da)

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/67ba414c-186f-4159-b01a-b15aad75d5bf)

**Expected behavior**
tags are not deleted

**Additional context**

**Comment by harshach** [comment]
@karanh37 what operation are we doing here, is it PUT or PATCH
