### ISSUE TITLE
Tag numbers on filtration 

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#13957]
**Affected module**
UI

**Describe the bug**
When looking on table number (or any asset), we see the number without the deleted assets. When pressing on deleted, we can that number.
When using the tag filter, we see the full number including deleted, which is confusing. 

**To Reproduce**

<img width="608" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/a31fc7ad-f6d1-41ad-95f3-ec96d30f999f">

<img width="549" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/0ec156e0-ee31-44f7-b23e-442d1bcbccb1">

<img width="1084" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/4595f868-3c3c-4beb-8d29-f0db765a47bb">

**Expected behavior**
I expect to see only the actual number in filters without the deleted. 

**Version:**
 - Python version:
 - OpenMetadata version: 1.1.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sejal-bansal** [comment]
@sapirhi I would like to work on this issue. Can you assign it to me?

**Comment by sapirhi** [comment]
Still can assign here tickets=) @harshach can u help?

**Comment by harshach** [comment]
@07Himank this is fixed right?

**Comment by karanh37** [comment]
This is already fixed.

**Comment by sapirhi** [comment]
Hi guys,

I see the bug is fixed for tags, but still exists for Tier. Can you pls check?

**Comment by sapirhi** [comment]
<img width="761" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/f62cc5dc-b376-422a-949a-4fbd49531bcc">
version 1.3.1
