### ISSUE TITLE
Docker ports available on localhost

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1395]
Sometimes is useful to connect with a SQL client running in the host to the MySQL container started by ```metadata docker --start```.

**Comment by akash-jain-10** [comment]
What is your suggestion on this one @amiorin ?

cc - @harshach @ayush-shah @shahsank3t

**Comment by amiorin** [comment]
Adding ```- ports: ["3306:3306"]``` to the MySQL container.
