### ISSUE TITLE
dbt ingestion details disappear after a metadata run

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#13959]
if we run a dbt workflow followed by a metadata workflow, the `dataModel` and column descriptions disappear.

- we will pick the dataModel during the DBT ingestion in case it exists, to keep it as-is. Would be interesting to have a toggle to let the dataModel source of truth be the manifest as we have the description toggle
- Will review what's going on with column descriptions disappearing so that they behave as any description field (only updated via PATCH)

**Comment by harshach** [comment]
@OnkarVO7 closing this as fixed . Please make sure to test it
