### ISSUE TITLE
Not able to list resources with tag based access control

### ISSUE THREAD

**Issue by kevinl1210** [open-metadata/OpenMetadata#13967]
**Affected module**
Impact UI.

**Describe the bug**
I am setting up role based control access in OMD using the tag mechanism.
Basically, I have an user dt_admin in the group DT Admin, which has a policy and a rule as follows:
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/89df6d50-82b0-4946-81b9-06a54ae6645a)

![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/f1f905f6-d744-4113-befb-9790345d3ebf)

The rule specifically allows the dt_admin user to have access to resources tagged with the DNT tag.
So I tagged databases, database schemas, tables, and the user does have access to view the page, however, found a strange behavior that:
- no database schemas are listed in the database page
- no tables are listed in the database schema page
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/5af47e67-ed77-4446-851a-c0521e233d2f)

![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/4f999ca6-96f9-4976-b107-b5772d3133ab)

Further digging the issue, found 403 forbidden response while requesting tables and database schemas.
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/22b3fe91-1312-4bed-904b-8bf16c4f094b)

![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/420623cf-4f02-48d2-9bbd-b228fdf7e50f)

I thought the rule already allowed dt_admin to have view permission?

**Expected behavior**
Expect:
- database schemas will be shown under database page
- tables will be shown under database schema page

**Version:**
 - OpenMetadata version: OMD 1.2.0

**Additional context**
NA

**Comment by kevinl1210** [comment]
Hi Team, may I know if it is a bug or there is something wrong my policy/rule setting?

**Comment by sureshms** [comment]
@kevinl1210 there might another rule denying this operation. Can you debug which policy is denying this by doing the query as describe in https://www.google.com/search?q=roles+and+policies+webinar+openmetadata&oq=roles+and&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDkyBggCEEUYPdIBCDIxNTFqMGoxqAIAsAIA&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:7e8c02a9,vid:LvDMgElrILE,st:0 at 22 minutes?

**Comment by kevinl1210** [comment]
Hi @sureshms 
I checked the permission with database schema level:
```
requests.get(
    'http://172.23.38.138/api/v1/permissions/databaseSchema/name/omd-athena-service.omd-athena-db.kevin_test?user=thepoint_user',
    headers={
        'Authorization': f'Bearer {ACCESS_TOKEN}'
    }
).json()
```

```
{'resource': 'databaseSchema',
 'permissions': [{'operation': 'Create', 'access': 'notAllow'},
  {'operation': 'Delete', 'access': 'notAllow'},
  {'operation': 'ViewAll',
   'access': 'allow',
   'rule': {'name': 'ViewRestricted-Allow',
    'description': 'Allow The Point users to view restricted resources which are tagged with:\n\n- AthenaTags.The Point\n- TableauTags.The Point',
    'effect': 'allow',
    'operations': ['ViewAll'],
    'resources': ['chart',
     'container',
     'dashboard',
     'dashboardDataModel',
     'database',
     'databaseSchema',
     'dataInsightChart',
     'dataProduct',
     'kpi',
     'metrics',
     'query',
     'report',
     'searchIndex',
     'storedProcedure',
     'table'],
    'condition': "matchAnyTag('AthenaTags.The Point', 'TableauTags.The Point')"},
   'policy': 'The Point User Policy',
   'role': 'The Point User Role'},
  {'operation': 'EditAll', 'access': 'notAllow'},
  {'operation': 'EditCustomFields', 'access': 'notAllow'},
  {'operation': 'EditDescription', 'access': 'notAllow'},
  {'operation': 'EditDisplayName', 'access': 'notAllow'},
  {'operation': 'EditOwner', 'access': 'notAllow'},
  {'operation': 'EditTags', 'access': 'notAllow'},
  {'operation': 'EditUsage', 'access': 'notAllow'}]}
```

And also checked the table level:
```
requests.get(
    'http://172.23.38.138/api/v1/permissions/table/name/omd-athena-service.omd-athena-db.kevin_test.app?user=thepoint_user',
    headers={
        'Authorization': f'Bearer {ACCESS_TOKEN}'
    }
).json()
```

```
{'resource': 'table',
 'permissions': [{'operation': 'Create', 'access': 'notAllow'},
  {'operation': 'Delete', 'access': 'notAllow'},
  {'operation': 'ViewAll',
   'access': 'allow',
   'rule': {'name': 'ViewRestricted-Allow',
    'description': 'Allow The Point users to view restricted resources which are tagged with:\n\n- AthenaTags.The Point\n- TableauTags.The Point',
    'effect': 'allow',
    'operations': ['ViewAll'],
    'resources': ['chart',
     'container',
     'dashboard',
     'dashboardDataModel',
     'database',
     'databaseSchema',
     'dataInsightChart',
     'dataProduct',
     'kpi',
     'metrics',
     'query',
     'report',
     'searchIndex',
     'storedProcedure',
     'table'],
    'condition': "matchAnyTag('AthenaTags.The Point', 'TableauTags.The Point')"},
   'policy': 'The Point User Policy',
   'role': 'The Point User Role'},
  {'operation': 'EditAll', 'access': 'notAllow'},
  {'operation': 'EditCustomFields', 'access': 'notAllow'},
  {'operation': 'EditDataProfile', 'access': 'notAllow'},
  {'operation': 'EditDescription', 'access': 'notAllow'},
  {'operation': 'EditDisplayName', 'access': 'notAllow'},
  {'operation': 'EditLineage', 'access': 'notAllow'},
  {'operation': 'EditOwner', 'access': 'notAllow'},
  {'operation': 'EditQueries', 'access': 'notAllow'},
  {'operation': 'EditSampleData', 'access': 'notAllow'},
  {'operation': 'EditTags', 'access': 'notAllow'},
  {'operation': 'EditTests', 'access': 'notAllow'}]}
```

As shown from the query, the user does have permission to access the database schema and its underlying tables because they are tagged.


As you can see the user can browse each individual table:
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/9fa2bf9b-cba9-46e4-9a91-02bbc46f2ff8)

And he/she can browse the database schema, however, no tables are listed under the schema.
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/64bec216-42a1-4201-863b-c1197577e88b)

And this is the expected database schema view which I used admin to access:
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/815a0454-8904-464a-a183-45d3595b4082)

p.s. I am using another user "thepoint_user" and tag "AthenaTags.The Point" for testing, so you might see different user/tag/policy name with my initial screen capture.

**Comment by pmbrull** [comment]
similar thread here https://openmetadata.slack.com/archives/C02B6955S4S/p1700796362701229

**Comment by sureshms** [comment]
@chirag-madlani, this could be a UI issue? cc @harshach

**Comment by chirag-madlani** [comment]
@sureshms @harshach We investigated this issue. 

The main issue over here is we are using list table API to list the tables for a Schema, which doesn't validate evaluated permission for the entity. It will only check basic User permission.

The user can access schema and table both but the user doesn't have full access to all the tables since table API is throwing 403 

attaching API below which is not covered with evaluated api yet
```
api/v1/tables?databaseSchema=Shopify
```

**Comment by harshach** [comment]
@sureshms this is going to bit more complex as we need to list and apply the permissions checks to get only subset of entities back as part of list APIs. Whole bunch of total count and pagination needs to be taken care of.

@kevinl1210 you don't want to users to look the basic information such as table name, description, tags, owner etc.. if they don't have permission? Wouldn't this cause a bigger issue users not even finding the data if they can't look at the basic information?

Apart from that UX issue here is user will see 10 tables even though they only have access to only 1 which would be confusing

**Comment by kevinl1210** [comment]
> @sureshms this is going to bit more complex as we need to list and apply the permissions checks to get only subset of entities back as part of list APIs. Whole bunch of total count and pagination needs to be taken care of.
> 
> @kevinl1210 you don't want to users to look the basic information such as table name, description, tags, owner etc.. if they don't have permission? Wouldn't this cause a bigger issue users not even finding the data if they can't look at the basic information?
> 
> Apart from that UX issue here is user will see 10 tables even though they only have access to only 1 which would be confusing

Yes, you are right, users should not be able to look the information if they don't have permission.
The issue now is that users cannot view any of the table under the schema view even they have permission to view all 10 out of 10 tables in the schema.

**Comment by harshach** [comment]
@kevinl1210 you need to give viewBasic policy to those users

**Comment by kevinl1210** [comment]
> @kevinl1210 you need to give viewBasic policy to those users

Hi, 
I gave those users ViewAll permission, isn't it already included ViewBasic operation as well?
![image](https://github.com/open-metadata/OpenMetadata/assets/14215103/ab069316-7fac-46b9-8671-4bce80905997)
