### ISSUE TITLE
Add anonymous usage and profiling stats to OpenMetadata using OpenTelemetry

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1396]
To improve OpenMetadata and connector integration it will be important for us to look at connector issues and OpenMetadata issues. 
requirements:

1. Track bugs and fix errors as fast as possible
2. Troubleshoot issues
3. Understand how our users are using OpenMetadata and improve their experience and fix bugs

**### What is private?**
1. All personal identifiable information , names, email addresses, credentials, geolocation, IP, etc.
2. All of users or organization e.g database, tables , all entities etc.. 

### Requirements ###
1. Users should be able to opt-out via config

**Comment by sureshms** [comment]
Data insights work that is being done will address this.
