### ISSUE TITLE
Retroactively add reviewers to existing terms

### ISSUE THREAD

**Issue by Kaushik119** [open-metadata/OpenMetadata#13964]
**Feature**
Approval Workflow

**Describe the task**
Currently, if a glossary term that exists was set to draft through mass import, no task shows up to the reviewer to start the approval workflow for this. This seems to be an edge case, where existing terms are unable to have this flow setup when a change to their status occurs after they have already been created

**Comment by sureshms** [comment]
@Kaushik119, currently, the glossary term approval works only when a term is created and not for the existing terms.
