### ISSUE TITLE
Promote integration with other tools by enabling templated links to other tools

### ISSUE THREAD

**Issue by jochemvangrondelle** [open-metadata/OpenMetadata#13978]
**Is your feature request related to a problem? Please describe.**
Once a user finds the table he needs, he will have to copy/paste the table name and go to other tools to query the data. He will have to copy/paste the relevant column names from his search as well. This creates unnecessary and repetitive work.

**Describe the solution you'd like**
As a OM admin, I would like to being able to configure one or more links to other tools - either per entity or per entity type (templated) - that consist of link text, link, tooltip, and icon. This enables users to jump straight into other tools for the relevant entity.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by harshach** [comment]
@jochemvangrondelle is custom properties not working for your usecase?

**Comment by harshach** [comment]
@jochemvangrondelle custom properties will be widget in the schema (landing page of a table) on the right side. This should bring out custom properties more prominently and should solve your issue.

**Comment by harshach** [comment]
we support sourceUrl as well, along with custom properties prominently displayed in the landing page
