### ISSUE TITLE
Great Expectation action: TestCaseResult timestamp is still in SECONDS instead of MILLISECONDS

### ISSUE THREAD

**Issue by firewall413** [open-metadata/OpenMetadata#13981]
**Affected module**
Ingestion - Great Expectations

**Describe the bug**
TestCaseResult timestamp is still in SECONDS instead of MILLISECONDS

**To Reproduce**

Screenshots or steps to reproduce:
Without fix:
![image](https://github.com/open-metadata/OpenMetadata/assets/60637730/48cfb019-e01a-407b-ab75-5c934987af02)
![image](https://github.com/open-metadata/OpenMetadata/assets/60637730/8db1c98b-545b-4d6c-8c08-7005c99f4218)
With fix (timestamp=datetime.now(timezone.utc).timestamp()*1000) the correct date is displayed on the frontend & saved in the DB

**Expected behavior**
You expect the TestCaseResult timestamp and LAST RUN front-end to be in millisecond accuracy

**Version:**
 - OS: linux/amd64
 - Python version: 3.10
 - OpenMetadata version: 1.2.0.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[all]==1.2.0.1`]

**Comment by harshach** [comment]
@TeddyCr I think this is resolved right , can we close it?
