### ISSUE TITLE
Provide a page in the manual for the Windows users

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1398]
Our Windows users can run ```metadata docker --start``` with Windows, Docker, and WSL 2. We consolidate this information in the manual. It would be interesting to test if it is possible to run OM in Windows Intellij.

**Comment by harshach** [comment]
@amiorin since you are looking at this, please come up with doc page and @shannonbradshaw can help with formalizing it and adding to the docs
