### ISSUE TITLE
@mention absent in the @mention of each user

### ISSUE THREAD

**Issue by AnaMariaChousa** [open-metadata/OpenMetadata#13982]
Hello :)

**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Impact the UI

**Describe the bug**
Hello. We use OpenMetada version 1.1.5. However, we've noticed an issue where the use of the "@" symbol to mention people, so it doesn't properly tag the intended users. Specifically, they are not displayed in the specific mentions section for each user. However, the mention is shown in the conversation in which has been incorporated.

**To Reproduce**
Screenshots or steps to reproduce

![Mention to JoseLuis](https://github.com/open-metadata/OpenMetadata/assets/150909717/fac06dee-1eb7-4b35-bece-b21dee769397)
![UI Mention JoseLuis](https://github.com/open-metadata/OpenMetadata/assets/150909717/54b56890-e935-4f99-b0b0-fdd61199aa0f)

**Expected behavior**

We hope that each user will be able to check the mentions in their mentions section.

**Version:**

 - OpenMetadata version: [1.1.5]
 - OpenMetadata Ingestion package version:  `openmetadata-ingestion[docker]
 
 **Additional context**

We have seen something similar happen to it:

https://openmetadata.slack.com/archives/C02B6955S4S/p1699990790131119

Thanks a lot
Ana
anamaria.chousa@ednon.es

**Comment by harshach** [comment]
@chirag-madlani we are not using the user's or team's fullyQualifiedName while creating the entityLink which is causing the issue in generating the hash . Lets clean it up from the UI side?

**Comment by chirag-madlani** [comment]
Sure @harshach 
Will work on UI changes mentioned here

**Comment by harsh-vador** [comment]
I will take this up
