### ISSUE TITLE
Enable column-only search

### ISSUE THREAD

**Issue by jochemvangrondelle** [open-metadata/OpenMetadata#13995]
**Is your feature request related to a problem? Please describe.**
As we do not know whether the user is searching for a table or a column, the user will often get a mix of table name matches and column name matches. 

**Describe the solution you'd like**
Add 'column' as additional entity to search for in the 'what to search for' dropdown.

**Comment by harshach** [comment]
@jochemvangrondelle this is not going to be possible. Its hard to know the intent of the user if its table or column.
You already have filter based on the column. If user indeed wants to search based on the column then there is that option. 
We are not going to add a switch for users. However there will be search relevancy ranking that can be tuned.
This is out of scope, hence closing the ticket
