### ISSUE TITLE
Scanning has not finished in 5 minutes.

### ISSUE THREAD

**Issue by ZeroBugHero** [open-metadata/OpenMetadata#13997]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version: 
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Scanning has not finished in 5 minutes.**

<img width="1495" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/122763218/3776a051-6091-421b-b34e-9704b5aa504d">
[log.log](https://github.com/open-metadata/OpenMetadata/files/13373662/log.log)

**Comment by harshach** [comment]
how is this a bug? please use https://slack.open-metadata.org before opening github issue
