### ISSUE TITLE
Use search context in table detail view

### ISSUE THREAD

**Issue by jochemvangrondelle** [open-metadata/OpenMetadata#13994]
**Is your feature request related to a problem? Please describe.**
In the table detail view, the context of the original search is not applied when searching within the table. Users have to repeat the search within the table details to identify the reason a table appeared in the search results.

**Describe the solution you'd like**
Maintain the search context when transitioning from search results to the table detail view. It can add a background colour to all search term occurences. In case of column or matches, it could automatically apply the search term to the in-table search.

**Comment by pmbrull** [comment]
we can apply the same highlighting logic with glossary assets: show if there are any columns tagged with the term and show them in a separate section

**Comment by harshach** [comment]
@jochemvangrondelle @pmbrull we won't be addressing this, as users can come into an entity page from multiple venues and search is one of them.
We are going to address what matched in search preview page that should be enough for user recognize why they came onto that particular entity page

**Comment by harshach** [comment]
This ticket should address the requirements expressed here https://github.com/open-metadata/OpenMetadata/issues/13992
