### ISSUE TITLE
Native MySQL container for Apple Silicon

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1400]
```mysql``` doesn't support Apple Silicon while ```mysql/mysql-server``` does.
The latter is officially maintained by Oracle and it has 100M+ downloads. It is legit.
![image](https://user-images.githubusercontent.com/32617/143504697-9d6aaef6-798b-40e3-86d1-da3af7e46ba1.png)

**Comment by akash-jain-10** [comment]
Hello @amiorin ,

It seems we are using `mysql/mysql-server` as our base image for Docker Compose mysql. Are you suggesting we should change it ?

https://github.com/open-metadata/OpenMetadata/blob/bd3beb46049b5216ee575376f656d2bb165e7179/docker/local-metadata/Dockerfile_mysql#L1

**Comment by amiorin** [comment]
Maybe [this](https://github.com/open-metadata/OpenMetadata/blob/bd3beb46049b5216ee575376f656d2bb165e7179/docker/local-metadata/docker-compose-dev.yml#L19-L20) is causing the emulation on Apple Silicon.
![image](https://user-images.githubusercontent.com/32617/143557747-8829e9fa-1f55-4a37-8451-a005a25f37ff.png)

**Comment by akash-jain-10** [comment]
We are using [docker-compose.yaml](https://github.com/open-metadata/OpenMetadata/blob/main/docker/local-metadata/docker-compose.yml). That should take care of the above issue you are experience.

I will confirm and cleanup docker-compose.dev.yaml if that is not required. 
Let me know your thoughts!

**Comment by amiorin** [comment]
We have the image for silicon but somehow ```metadata docker --start``` is starting the amd64. My guess is that the docker-compose.yml file used by our CLI is overriding the platform.
![image](https://user-images.githubusercontent.com/32617/143569536-ad0341b1-8906-4231-b387-f64fa94d7e6a.png)
![image](https://user-images.githubusercontent.com/32617/143569764-af574cbc-ef64-4a5f-bc33-24b93ba899f3.png)

**Comment by amiorin** [comment]
I'm using the latest version of the CLI
![image](https://user-images.githubusercontent.com/32617/143569980-b4be26ef-5cf9-42de-b594-1ef7c3bd660e.png)

**Comment by akash-jain-10** [comment]
let me check this with @ayush-shah  and @harshach !

**Comment by amiorin** [comment]
👍

**Comment by ayush-shah** [comment]
@amiorin @akash-jain-10 @harshach 
Removing platform doesn't show the emulation error.
I will push the changes
![image](https://user-images.githubusercontent.com/40225091/143586638-28270a1b-6b3c-414f-8da7-8c245f159ac6.png)
