### ISSUE TITLE
Add sort option for Test Cases

### ISSUE THREAD

**Issue by Zamily84** [open-metadata/OpenMetadata#14001]
Requesting the ability to sort test cases by name. This functionality will allow for better grouping and quicker navigation to test cases.

**Comment by ShaileshParmar11** [comment]
Hello @Zamily84 will you be able to help us in identifying the screen where you need this feature? screen short will be more helpful.

**Comment by Zamily84** [comment]
On test cases
![image](https://github.com/open-metadata/OpenMetadata/assets/5355545/448f0283-4284-4ee1-9fac-c789375997c3)

**Comment by ShaileshParmar11** [comment]
Thank you @Zamily84 We will look into this :)
