### ISSUE TITLE
Swagger.json has an old version

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1402]
After doing ```metadata docker --start```
It shows 0.3.0 instead of 0.6.0

![image](https://user-images.githubusercontent.com/32617/143562745-1f6c2aa5-8a6b-4ca3-9762-3686d4c9b1c5.png)

**Comment by harshach** [comment]
@amiorin lets make this parameterized with ${project.version} https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/pom.xml#L364
