### ISSUE TITLE
Unable to Zoom on graph view of tasks under airflow dag

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#14023]
**Affected module**
UI

**Describe the bug**
Unable to Zoom on graph view of tasks

**To Reproduce**
Navigate to Tasks view of a Dag in airflow

**Expected behavior**
Zoom in/out on graph view of tasks

**Version:**
 - OpenMetadata version: 1.2.1

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/a1d7ea23-f7e0-4e56-8e44-aa92f3cdbe4a)

**Comment by harshach** [comment]
@chirag-madlani lets handle with the new mocks
