### ISSUE TITLE
Inconsistent search results between auto-suggest box and actual search results

### ISSUE THREAD

**Issue by jochemvangrondelle** [open-metadata/OpenMetadata#14038]
**Affected module**
I don't know

**Describe the bug**
I experience inconsistent search results between the auto-suggest box and actual search results. If I search for fact and press enter, I get the search results as expected, the most relevant table with highest usage (in our case, fact_bookings). However, this top 1 table is not visible in the auto-suggest items.

**Expected behavior**
The top 3-5 items in the auto-suggest box should match the 3-5 items from the final search results.

**To Reproduce**
Add a high number of entities with a common prefix such as thread. Ensure that at least one table has high usage compared to others. Search for the prefix thread!
<img width="880" alt="Screenshot 2023-11-24 at 13 18 05" src="https://github.com/open-metadata/OpenMetadata/assets/7136841/95f86eff-3f08-43fd-bf72-462e452a6e75">
<img width="941" alt="Screenshot 2023-11-24 at 13 21 04" src="https://github.com/open-metadata/OpenMetadata/assets/7136841/008fa8de-234c-4a91-bf94-bd2f84c2af3e">

**Version:**
 - OS: Mac
 - Python version: N/A
 - OpenMetadata version: 1.2
 - OpenMetadata Ingestion package version: N/A

**Additional context**
N/A

**Comment by harshach** [comment]
This is fixed in 1.2.3. @jochemvangrondelle give it a try and let us know if the issue still persists on your side

**Comment by harshach** [comment]
1.2.3
