### ISSUE TITLE
Use our logo for the avatar in PyPI

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1403]
It will help our users to be sure that it's us.

![image](https://user-images.githubusercontent.com/32617/143563184-b9681b3e-ff3a-4b33-99a5-81aa4183e5ca.png)

**Comment by amiorin** [comment]
Same thing in Docker Hub
![image](https://user-images.githubusercontent.com/32617/143563450-1b14f96f-d42b-48bf-8494-f825d9724862.png)

**Comment by akash-jain-10** [comment]
Thanks for bringing in to our attention @amiorin. I will take care of this!

**Comment by amiorin** [comment]
👍

**Comment by akash-jain-10** [comment]
![image](https://user-images.githubusercontent.com/15995028/145002248-8bdf846b-7f79-497a-a977-095a9ecf56fd.png)

**Comment by akash-jain-10** [comment]
![image](https://user-images.githubusercontent.com/15995028/145004050-92e6f147-d3a0-42f1-bd9c-c2d510dab570.png)
