### ISSUE TITLE
Separate status from test case result

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#14049]
### Context
Failure status is currently stored alongside a `testCaseResult`. For each failure a new failure status is created and stored with the `testCaseResult` -- see below.
https://github.com/open-metadata/OpenMetadata/blob/d55100592d250f15a200410ceea91bb91ab13913/openmetadata-spec/src/main/resources/json/schema/tests/basic.json#L89-L150

To prevent re writing the test case failure status to a testCaseResult, we'll be separating failure status as their own entities and link it to a testCaseResult (if status of testCaseResult if different than resolved).

### A.C.
- Separate failure status into its own extension. Should be a time series extension linking failureStatus [Many] <-> [One] testCase
- Create `assign` and `review` statuses
- Enable listing of failure status by:
     - status
     - test case
     - assignee -> this should be an entity reference
     - reviewer -> this should be an entity reference

**Comment by harshach** [comment]
@TeddyCr so there will be global status at test case level. How do we determine a test case is failed or not , if we are not going to use the testcase result a way of checking it?

**Comment by TeddyCr** [comment]
@harshach I was thinking to have a reference to the testCaseFailureStatus in the testCaseResult. Let me know if you are thinking otherwise.

**Comment by harshach** [comment]
@TeddyCr what happens if the test case is failed with false positives or some temporary issue. Lets say after 2 more runs its turned to green automatically without user doing anything, will this handle that case?

Instead of calling testCaseResultFailureStatus -> should we call it as testCaseResultStatus. Why not store the current status?
2.

**Comment by TeddyCr** [comment]
> Why not store the current status?

@harshach what do you mean by this ^? 

> what happens if the test case is failed with false positives or some temporary issue. Lets say after 2 more runs its turned to green automatically without user doing anything, will this handle that case?
We had discussed that we would not close it automatically but that a user should close with a reason to keep an accurate view of the statuses. Let me know if you think we should do it in a different way.
