### ISSUE TITLE
List of blog articles in the landing page is old

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1404]
My guess is that we would like to have the link to 0.6.0 and 0.5.0 instead of 0.5.0 and 0.4.0

![image](https://user-images.githubusercontent.com/32617/143581263-a73d02a4-1bc7-48fe-93b4-53f2e95a6c76.png)

**Comment by shahsank3t** [comment]
Thanks for pointing it out. I'll take care of this.

**Comment by shahsank3t** [comment]
Create an issue here: https://github.com/open-metadata/openmetadata-site/issues/6
Closing this one.

**Comment by amiorin** [comment]
👍
