### ISSUE TITLE
Make the search bar for filters case insensitive

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#14060]
**Is your feature request related to a problem? Please describe.**
It would be convenient if the search bar was case-insensitive on the Explore page when setting up filters.
On the recording from the screen, I gave examples proving case sensitivity.
![explore_filter_case_sensitive](https://github.com/open-metadata/OpenMetadata/assets/61934044/aade1621-998a-4fbf-b8f9-6131e056e739)

**Describe the solution you'd like**
The output of the results for the input "Entity" and "entity" should be the same. For all types of filters on the Explore page.
Thus, users will be able to search for the necessary entries for the filter without fear of making a mistake in the register.

**Comment by pmbrull** [comment]
closing in favor of https://github.com/open-metadata/OpenMetadata/issues/13922
