### ISSUE TITLE
Scale of axis on Data Quality Chart

### ISSUE THREAD

**Issue by hoangdh5** [open-metadata/OpenMetadata#14063]
Friendly tag @ShaileshParmar11  as conversation on Slack.

**Is your feature request related to a problem? Please describe.**
UI: Chart on Data Quality Results not show clearly the change of value due to the scale was to high. 
For example below, the daily row count change around these number
20/NOV : 17028400
21/NOV: 17036474
22/NOV: 17044216
The lowest value shoult be around 17M  the see the change.
![image](https://github.com/open-metadata/OpenMetadata/assets/77825774/abb9ac62-af7d-4484-b613-eb5d9ea0314e)

**Describe the solution you'd like**
Fix the way OM chart set the scale and the lowest value to better visual of DQ chart.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShaileshParmar11** [comment]
Hello @hoangdh5, I've submitted the pull request for this issue. Could you please review it and confirm whether it resolves your problem? The issue number is **#15368**.

**Comment by hoangdh5** [comment]
> Hello @hoangdh5, I've submitted the pull request for this issue. Could you please review it and confirm whether it resolves your problem? The issue number is **#15368**.

Hello, #15368 is resolved my issue. Thanks
