### ISSUE TITLE
DatabaseSchema Restore operation throws error EntityNotFound, if a table that belongs to schema is already restored

### ISSUE THREAD

**Issue by madhav-pw** [open-metadata/OpenMetadata#14067]
**Affected module**
It is impacting Ingestion Framework of public schema

**Describe the bug**
Cant restated the deleted schema of 'public' & also it is showing table instance for 004aa994-6a2b-414d-b093-e84ee6d20022 not found when restore.

**Screenshots**

[
![image](https://github.com/open-metadata/OpenMetadata/assets/151714350/0aeae86c-9485-40e9-8c93-f76ee5f9b3a3)
![image (1)](https://github.com/open-metadata/OpenMetadata/assets/151714350/1bfa853f-3b95-47a9-9499-ff00b2606d95)
![image (2)](https://github.com/open-metadata/OpenMetadata/assets/151714350/dbf5bf54-2206-40c9-ba7f-d8daacc93e0b)
](url)

**Version:**

 - OpenMetadata version: [1.2.2]

**Comment by aniketkatkar97** [comment]
A related bug here
- [ ] Database schema version page doesn't show version details for soft deleted schema
- [ ] Add cypress tests to cover all scenario

**Comment by madhav-pw** [comment]
+Aamir Siddiqui ***@***.***>
