### ISSUE TITLE
Review Task & Mention Notifications

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#14079]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? UI

**Describe the bug**

Mentions and tasks don't highlight the notification bell

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
@akash-jain-10 we can close this?

**Comment by akash-jain-10** [comment]
Yes! Closing it now!
