### ISSUE TITLE
PUT method for service APIs give 405 Method not allowed exception

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1407]

**Comment by sureshms** [comment]
@darth-coder00, can you add more details on how to reproduce this? Currently there are java tests that cover this.

**Comment by ShaileshParmar11** [comment]
We can reproduce by going to services page and try to edit any of the service

![image](https://user-images.githubusercontent.com/71748675/145014967-f637a3dd-9689-4b8c-b6d7-a5fe366282d5.png)
![image](https://user-images.githubusercontent.com/71748675/145015035-9c0d2be1-03e0-47f6-b22d-3b7b15b27461.png)
![image](https://user-images.githubusercontent.com/71748675/145015254-afc726a5-8725-4472-909f-7238536c2394.png)

Response: 
`{"responseMessage":"An exception with message [HTTP 405 Method Not Allowed] was thrown while processing request."}`

**Comment by sureshms** [comment]
This is likely because of backward incompatible change from https://github.com/open-metadata/OpenMetadata/issues/1349

I called out your attention @darth-coder00 and @Sachin-chaurasiya in that issue. Did we make a corresponding change?
You no longer need to pass UUID in the PUT request for service related APIs. This is consistent with PUT APIs for all the other entities.

**Comment by sureshms** [comment]
Also @parthp2107, should this issue be caught by selenium tests? cc @harshach

**Comment by parthp2107** [comment]
> Also @parthp2107, should this issue be caught by selenium tests? cc @harshach

@sureshms , this was caught by selenium tests and was informed to @darth-coder00 so he created the issue for the same.

**Comment by Sachin-chaurasiya** [comment]
@sureshms will make the required changes and also sync up with @parthp2107 to cover this thing in selenium test.

**Comment by parthp2107** [comment]
> @sureshms will make the required changes and also sync up with @parthp2107 to cover this thing in selenium test.

@Sachin-chaurasiya , this is already covered in selenium and because of it, we came across this issue. Right now, I've commented that part since the changes are pending. Once the changes are done, will uncomment the test.
