### ISSUE TITLE
Add Argo Workflows support

### ISSUE THREAD

**Issue by artemklevtsov** [open-metadata/OpenMetadata#14070]
**Is your feature request related to a problem? Please describe.**
Can't use Argo Workflows pipelines with Open Metadata.

**Describe the solution you'd like**
Add support to configure and schedule Argo Workflows metadata and profiler workflows from the OpenMetadata UI.

**Describe alternatives you've considered**
I tried to learn custom connectors without success now.

**Additional context**
Argo Workflows is a Kubernetes-based workflow management tool that allows users to define complex data processing pipelines and workflows using a simple and intuitive UI or YAML files.

Main site: https://argoproj.github.io/workflows/
Documentation: https://argoproj.github.io/argo-workflows/
REST API reference: https://argoproj.github.io/argo-workflows/swagger/

**Comment by harshach** [comment]
we support Argo in Collate SaaS product
