### ISSUE TITLE
https://docs.open-metadata.org/swagger.html is unable to display content

### ISSUE THREAD

**Issue by atiftariq1** [open-metadata/OpenMetadata#14082]
https://docs.open-metadata.org/swagger.html is unable to display content

**Comment by Sachin-chaurasiya** [comment]
Hello @atiftariq1 , thanks for reporting, however, I can see the content, please see the recording for reference.


https://github.com/open-metadata/OpenMetadata/assets/59080942/fc77f9cd-50d0-4f19-8c23-390e448a03c1

**Comment by aniketkatkar97** [comment]
@atiftariq1 can you please post some more details with the description about if you are getting any error or something with some screenshots or recordings? This is not reproducible at my end

**Comment by atiftariq1** [comment]
great able to see on other browser. might be issue with chrome but working with Edge.

Thanks team. really appreciate the support!
