### ISSUE TITLE
Using OpenMetadata for Qlik Cloud

### ISSUE THREAD

**Issue by OliAtDup** [open-metadata/OpenMetadata#14089]
**Feature**
Using OpenMetadata for Qlik Cloud

**Describe the task**
I just want to know if there are plans to integrate Qlik Cloud into the native OpenMetadata connectors? No problem for Qlik Sense, the doc is perfect, but I can't find anything regarding Qlik Cloud...

**Comment by Xceptions** [comment]
Hi @pmbrull is this still available?

**Comment by pmbrull** [comment]
hi @Xceptions, assigned! Thanks for the help

**Comment by Xceptions** [comment]
Hi @pmbrull , apologies for the mix up. I was misled into thinking that the project was in python, only to find out it is in Java. I really apologize for this mix up. Kindly unassign

**Comment by pmbrull** [comment]
hi @Xceptions, main piece of work for the connectors is in Python. You can see an example PR developing a connector here https://github.com/open-metadata/OpenMetadata/pull/13128

**Comment by Xceptions** [comment]
thank you. Will look into it!

**Comment by harshsoni2024** [comment]
We are currently working on qlik cloud connector.
