### ISSUE TITLE
Adding Grafana as an optional dashboard connector

### ISSUE THREAD

**Issue by RoniFridman1** [open-metadata/OpenMetadata#14090]
**Is your feature request related to a problem? Please describe.**
We have a Postgres DB that is connected to the open-metadata application, and to a Grafana application.
We would have wanted to integrate the dashboards we create on Grafana into open-metadata but Grafana is not an available option for a dashboard connector.

**Describe the solution you'd like**
Add Grafana as an option for a dashboard connector.

**Describe alternatives you've considered**
None I can think of, except for us switching to another visualization app.

**Comment by pmbrull** [comment]
this is covered here https://github.com/open-metadata/OpenMetadata/issues/1093

Closing this one, thanks!

**Comment by RoniFridman1** [comment]
Right got it.
That thread is from 2 years ago. Is it in works or it's not a priority?
