### ISSUE TITLE
deletion and role change impossible for 1.2.2 with Helm 1.2.3

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#14104]
https://openmetadata.slack.com/archives/C02B6955S4S/p1700730654920459

I have an issue with openmetadata 1.2.1 to 1.2.3 with LDAP-based authentication: When trying to assign roles to the user these are not stored / committed. However, this is only the case for 1 out of my 2 deployments. I have in fact deleted (elastic, DB state) and re-rolled the helm deployment from scratch. Nonetheless, the issue persists

There seems to be a dependence on how the user was created
If the LDAP login is creating the user - then such issues seem to arise in one environment

if the user is created by hand - then it seems to work fine. However, this only works fine if the roles are assigned during the creation of the user

Interestingly, this also applies to the deletion of users - this also does not work there

**Comment by harshach** [comment]
@chirag-madlani can we test this? doesn't look like a login is impacting it but during the SSO sign-in and user account creation.
@geoHeil the description doesn't give full details, please provide some screenshots and we would like to see what apis calls are being made

**Comment by chirag-madlani** [comment]
@harshach, @mohityadav766 will be taking a look here

**Comment by geoHeil** [comment]
![image](https://github.com/open-metadata/OpenMetadata/assets/1694964/b3a29ca3-b882-4f4a-a734-18ba850da2ab)

I cannot observe PUT / POST requests in the environment that fails.

The environment that works is sending many put / post requests

**Comment by geoHeil** [comment]
Well it is also working for me in 1 out of 2 environments. However, I have already nuked the whole state (persistent volume claims and databae) and re-installed the helm.

And evaluated the debug logs. without any luck. 

Is there any chance we can take a look together?

**Comment by geoHeil** [comment]
turned out to be a firewalll issue where the WAF waas filtering certain requests from the frontend
