### ISSUE TITLE
DBT Models not available in Suggest API

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1410]
DBT Models are indexed in `search` api but are not present in `suggest` api
<img width="1461" alt="Screenshot 2021-11-26 at 9 27 26 PM" src="https://user-images.githubusercontent.com/86726556/143606436-dcd2f51e-bae2-46d4-bf80-f3cd2901faed.png">

**Comment by harshach** [comment]
@darth-coder00 are you adding 'dbt_model_search_index' to the index param

**Comment by Sachin-chaurasiya** [comment]
Closing this as it is fixed after adding `dbt_model_search_index` to the Suggestion API call.
