### ISSUE TITLE
Incorrect aggregation of matches in search results for multiple search terms

### ISSUE THREAD

**Issue by jochemvangrondelle** [open-metadata/OpenMetadata#14102]
**Affected module**
Don't know

**Describe the bug**
The search results show the number of matches in column names and column descriptions. I expect to see the unique number of matched columns, but it seems to count every individual match.

**To Reproduce**
1. Add a column description with multiple words - and repeat it twice, for example: The booking_completed_date shows the data a booking was completed. 
2. Search for "booking completed date".
3. Expected result: 1 matched column description.

**Expected behavior**
I expect to see the unique number of matched columns instead of a count of matched words.

**Version:**
 - OM 1.2

**Additional context**
[Link to slack discussion](https://openmetadata.slack.com/archives/C02B6955S4S/p1700811406511729)
I cannot share screenshots from our instance due to confidentiality, but another bug is blocking me to reproduce this in sandbox. Will add it here later

**Comment by harshach** [comment]
@jochemvangrondelle we switched to count one occurrence of the text in description i.e if there are multiple words that matches search result ,the ranking only influenced as it occurred one time in the description.


![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/ce0421ee-7077-4a11-a9c8-adebf89d91bd)
