### ISSUE TITLE
Search results do not include/highlight partial display name matches

### ISSUE THREAD

**Issue by jochemvangrondelle** [open-metadata/OpenMetadata#14103]
**Affected module**
Search UI

**Describe the bug**
The search results show correctly when there is an exact match on the full display name or on parts separated with underscores. When there is a partial match, the table is shown in search results, but the section with aggregated matches and highlights are not visible. Possibly the scoring is also affected. 

**To Reproduce**
Search for a part of a display name, such as tab or strain and note the difference between full vs partial display name matches in the screenshots. A simple use case would be search for 'order' to find a table called 'orders'.

<img width="848" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/7136841/39ae3e1e-d4d7-4303-b83e-b726f4109b7d">
<img width="856" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/7136841/c7e105e6-d4b6-4ac5-b0ee-8302fbdbcf94">
<img width="917" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/7136841/2a0bce66-9717-499c-978d-56f4272e04f4">

**Expected behavior**
Consistent search result display

**Version:**
OM 1.2

**Additional context**
N/A

**Comment by harshach** [comment]
@chirag-madlani 

![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/d2a7b2c5-8edf-47d8-8868-107d3c30655e)

I am closing this as done, Let me know if anything else is needed
