### ISSUE TITLE
Date updated for table

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#14116]
**Is your feature request related to a problem? Please describe.**

Users want to know when their **table data was last updated**.

Currently the solution we have is use custom properties and add 'date_updated' field to each table, which updated on real time.
The issue is that every day usually this field is changed, which make the table version to keep getting larger and larger without appropriate reason (we have a table with 800 versions!), and these our data base need to save all these versions....
![image](https://github.com/open-metadata/OpenMetadata/assets/87426120/b0f83697-14f0-4419-ad2e-11e2dc549b18)

**Describe the solution you'd like**
A data freshness place to show this value.

**Describe alternatives you've considered**
Add to 'table profile' a new field called 'date updated', same as there is already 'created date'.
![image](https://github.com/open-metadata/OpenMetadata/assets/87426120/05980c77-01b7-4aeb-81c4-81e39cfbb802)

**Comment by harshach** [comment]
@sapirhi we already have metrics of table last updated date. Did you check the profiler metrics? this will give you data in time-series fashion rather than using custom property for this.

**Comment by sapirhi** [comment]
Hi @harshach ,
Do you mean looking on the volume graph?
It show the daily differences which are good to know, but it's depend on when we ingest the data right?
It's important for the users to know on which time exactly the table was updated (and in real time), as they want to see if there are data delays, or checking if the job was failing because it's not refresh etc. 

Also, for our huge tables, it's hard to detect if even there was a change in the data between days (well, there can be no change of course, but I mean the graph is not an straight forward way to see it). 
<img width="1130" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/ecee5e1f-1e74-46ea-8443-ea188cde1dfe">

**Comment by harshach** [comment]
@sapirhi you can use the table updates metrics 
<img width="1317" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/4bfc1de6-b126-470c-9ccc-68380eba459b">
Custom properties are like any other metadata in a data asset, such as description, tags, owner etc.. if you change it daily its going to change the version

**Comment by SHEN282754697** [comment]
I also have the same problem ,and don't know how to solve it. how  to add 'table profile' a new field called 'date updated'?
![1](https://github.com/open-metadata/OpenMetadata/assets/22440528/defd29c5-1671-49ec-98f7-b9a78e819b83)
![2](https://github.com/open-metadata/OpenMetadata/assets/22440528/a7cb0e1f-637d-42cc-a9ca-5221f7f13883)

**Comment by sapirhi** [comment]
Yes I agree, it shouldn't be in custom properties. 
Table update metrics is great, but depend on the hour of the ingestion, it's not give the exact time of table readiness in the day. 
For us it's very important, as we want to set a policy that all important tables must be ready before 7 utc, and OMD can be a good place for people to be aware of this data.

**Comment by harshach** [comment]
@sapirhi but why that time changes every day?, we are also introducing custom metrics where you can report your own metric per table. In this case you can record this as a custom metric , would that work?
cc @TeddyCr

**Comment by sapirhi** [comment]
We have huge data flow of dependencies - one delay can cause all the others a change. So every day the outcome is different. 
Also, it's still more comfortable to see a date value (even if we are not looking at specific time) instead of looking in graphs, faster to the eye. 

I think as long as the custom metric available through a central place it can work.

**Comment by TeddyCr** [comment]
@sapirhi are you looking at some kind of SLA checks done against your table on a daily basis (i.e. does my `updated_at` field is within my accepted SLA)?

**Comment by SHEN282754697** [comment]
May I ask if this is a bug? Will it be fixed in the next version? Is there currently a good solution. Please advise and thank you.

**Comment by sapirhi** [comment]
@TeddyCr 
From governance perspective -  absolutely yes. This is actually part of my job to set the guidelines. 

From users perspective - let's say I'm looking to use another team table, and I found something that looks right, but then I see it wasn't updated from May 23, so I won't use it. But this info should be super easy for me to find. 
(In our case we have 80k tables, and the search is the hard part).

**Comment by TeddyCr** [comment]
That makes a lot of sense. @harshach shared the screenshot below. Is it populated and what data base engines are you using?

![Screenshot 2023-11-28 at 8 55 16 AM](https://github.com/open-metadata/OpenMetadata/assets/13626425/f6c7f582-e74f-4a90-a641-f419be496acc)

**Comment by SHEN282754697** [comment]
> @sapirhi That makes a lot of sense. @harshach shared the screenshot below. Is it populated and what data base engines are you using?
> 
> cc @SHEN282754697 if you could also share this information
> 
> ![Screenshot 2023-11-28 at 8 55 16 AM](https://private-user-images.githubusercontent.com/13626425/286174139-f6c7f582-e74f-4a90-a641-f419be496acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTg0ODcsIm5iZiI6MTcwMTE1ODE4NywicGF0aCI6Ii8xMzYyNjQyNS8yODYxNzQxMzktZjZjN2Y1ODItZTc0Zi00YTkwLWE2NDEtZjQxOWJlNDk2YWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMzBhYmVlM2EzZTMwNzQ5NWZkZDkxYTg0YTg3MWU4N2QxNWMxMmRhNzQ4N2MzMzQ0ZWM1OGRjNDk0YmE1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0CXX6UT53t1tTR6n0Qu9zd8gWr6L3ePU-JGla4RGQx8)

mysql

**Comment by SHEN282754697** [comment]
May I ask if there are any other communication methods, such as WeChat groups or QQ groups, that I can join to make it easier to communicate.

**Comment by TeddyCr** [comment]
Hey @SHEN282754697 we'll try to see how we can support this in upcoming releases for MySQL. @sapirhi what DB do you use?

**Comment by sapirhi** [comment]
using mysql
how you will support it?
