### ISSUE TITLE
Enable User tokens to access APIs

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#14114]
**Feature**
Currently, the only way anyone can access it is through bot tokens. Most of them use ingestion-bot tokens.
However, bot tokens are limited because they can't update existing description tags, etc..
We have a user token option in the backend, and we should enable this in the UI so that one can use their user token
to access APIs.

cc @chirag-madlani @mohityadav766

**Comment by harsh-vador** [comment]
I will take this up
