### ISSUE TITLE
Prepare dev docs for OpenMetadata Python API

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1411]
let's write down a guide on the design and usage of `OpenMetadata` Python API. This should help new developers get started in the community and any end users that need to use the wrapper

**Comment by amiorin** [comment]
👍

**Comment by harshach** [comment]
@pmbrull This is great!! we can add a sample source connector to generate Table, Topic, Dashboard entities so that others can copy to build their own connector

**Comment by pmbrull** [comment]
Yeah, we can give some iterations to have a nice onboarding walkthrough!

**Comment by pmbrull** [comment]
Prepared a first version explaining the API use case and showcasing its usage: https://docs.open-metadata.org/open-source-community/developer/python-api

We can open further tickets for specific followup tutorials.

Thanks!

**Comment by pmbrull** [comment]
I am also working on explaining the Solution Design focusing on the API: https://docs.open-metadata.org/open-source-community/developer/solution-design

Would really appreciate your opinion there as well 🙏
