### ISSUE TITLE
 retention period in UI

### ISSUE THREAD

**Issue by LEEHYUNJI94** [open-metadata/OpenMetadata#14134]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
not showing retention period in the UI when I patch retention period to a table
**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
showing retention period in the UI when I patch retention period to a table

**Version:**
 - Python version: 
 - OpenMetadata version: [e.g. 0.8] 1.2.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
https://openmetadata.slack.com/archives/C02B6955S4S/p1701132502435379

**Comment by harshach** [comment]
@chirag-madlani need to be cherry-picked into 1.2.3
