### ISSUE TITLE
Python integration tests get hung

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1414]
We should take a look at how the python integration tests behave in the github actions.

In this PR https://github.com/open-metadata/OpenMetadata/pull/1409 the tests ran, but I cancelled them at 20min and 1h 20min.

**Comment by harshach** [comment]
@akash-jain-10 ^

**Comment by akash-jain-10** [comment]
I'm looking into this one.

**Comment by ayush-shah** [comment]
The changes in the sample-data.py file for the creation of entity types like database has changed, it takes the service name `bigquery_gcp` as default and doesn't consider the `bigquery` from tables.json where our sample-data is stored.
This issue will affect local-docker, metadata docker command, selenium tests.
Raising a PR for it once I am done testing.
CC: @harshach @pmbrull @akash-jain-10

**Comment by pmbrull** [comment]
hi @ayush-shah, we updated the lineage JSON sample data here: https://github.com/open-metadata/OpenMetadata/pull/1436/files. The sample data ingestion should work no

**Comment by ayush-shah** [comment]
Hey @pmbrull,
Yes, the pipeline is workIng, but the recent changes for the methods used to get or create the database service now takes the service name i.e. `bigquery_gcp` which at first was fetching from tables.json i.e. 'bigquery'.
The Local docker script (run_local_docker.sh), metadata docker command and ingestion docker checks whether the `bigquery.shopify.fact_sale` is ingested or not, if it has, it proceeds further.

**Comment by pmbrull** [comment]
> Hey @pmbrull, Yes, the pipeline is workIng, but the recent changes for the methods used to get or create the database service now takes the service name i.e. `bigquery_gcp` which at first was fetching from tables.json i.e. 'bigquery'. The Local docker script (run_local_docker.sh), metadata docker command and ingestion docker checks whether the `bigquery.shopify.fact_sale` is ingested or not, if it has, it proceeds further.

Got it, thanks @ayush-shah 🙏
