### ISSUE TITLE
Search pull-down menu content does not match with search results

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#14143]
**Affected module**
UI, possibly API

**Describe the bug**
Search pull-down menu content does not match with search results (DBCS)

**To Reproduce**

1. Key in DBCS characters in search bar and a pull-down list shown. 5 items searched.
![Pull-down list](https://github.com/open-metadata/OpenMetadata/assets/85471195/facfc420-f3ff-4f27-8748-d61df7602ad0)

2. Press enter and the search results shown. Only 1 item searched.
![Search Results](https://github.com/open-metadata/OpenMetadata/assets/85471195/746bb1e1-87d9-4889-a6d2-817670d1cffb)

**Expected behavior**
The search results should match with the content in the pull-down list.

**Version:**
  - Docker v23.0.6
  - Docker-compose v2.21.0
  - OpenMetadata version: 1.2

**Additional context**
N/A

**Comment by harshach** [comment]
@AntonioChen0206 search result is more accurate right compared to what we are showing in suggest menu?

**Comment by 07Himank** [comment]
> @07Himank others are reporting the same, lets take a look if something is getting changed during the query

i will check this
