### ISSUE TITLE
Add support for MaxCompute metadata

### ISSUE THREAD

**Issue by songjiankai** [open-metadata/OpenMetadata#14145]
**Feature**
Add feature issue reference
We want to obtain Alibaba MaxCompute metadata information.

**Describe the solution you'd like**
Add a module to connect to MaxCompute and explore metadata.

**Comment by faying** [comment]
we need MaxCompute support

**Comment by harshach** [comment]
@faying are you interested in contributing

**Comment by baronbigghf** [comment]
I  am interesting this issue.

**Comment by YuQi-Hu** [comment]
I noticed this issue was closed, don't you plan to support maxcompute metadata in the near future?

**Comment by allenfu007** [comment]
I am also interesting this issue.

**Comment by okx-xj** [comment]
any hope of supporting this in the near future?

**Comment by liyuntao2032** [comment]
Dear OpenMetadata Team,

We are an LLM-focused team handling large-scale data processing, where ​​MaxCompute​​ plays a critical role in our infrastructure. Its elastic compute resources enable us to efficiently process PB-scale data for tasks like deduplication, which is essential for our AI/ML workflows.

As our data storage grows, we are evaluating ​​OpenMetadata​​ as a unified metadata management solution. However, the lack of native ​​MaxCompute connector support​​ is currently a blocker for adoption. Given the increasing adoption of MaxCompute (especially in data-intensive fields like LLMs), we believe adding this connector would benefit many users in the community.

Would your team consider prioritizing this integration in an upcoming release? We’d be happy to provide use-case details, testing support, or feedback if needed.

Thank you for your time and great work on OpenMetadata! Looking forward to your thoughts.

Best regards

**Comment by gylhaut** [comment]
we need MaxCompute connector  support
