### ISSUE TITLE
DBT & ML Models test naming bug

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1415]
Both in `MlModelResourceTest` & `DbtModelResourceTest` there are issues in the `delete`.

If we set up the `delete` method in the tests properly, e.g.:

```
@Test
  public void delete_nonExistentDbtModel_404() {
    HttpResponseException exception = assertThrows(HttpResponseException.class, () ->
            getDbtModel(NON_EXISTENT_ENTITY, adminAuthHeaders()));
    assertResponse(exception, NOT_FOUND, CatalogExceptionMessage.entityNotFound(Entity.DBTMODEL, NON_EXISTENT_ENTITY));
  }
```

(Note how we are passing the Entity information as `Entity.DBTMODEL`) then we get an error in the assertion:

```
org.opentest4j.AssertionFailedError: 
Expected :Dbtmodel instance for 74cade21-39df-40f9-bbdf-3e3d46102b3b not found
Actual   :DbtModel instance for 74cade21-39df-40f9-bbdf-3e3d46102b3b not found
```

This means that at some point in the test suite, we are picking up wrongly the entity type and showing it inconsistently. The `Entity.DBTMODEL` and `Entity.MLMODEL` are being set now full in minus: `dbtmodel` & `mlmodel`.

However, the suite returns `DbtModel`.

WIth the current code, the DBT models are working by bypassing this inconsistency and using, instead of the `Entity.DBTMODEL` call, the string `"dbtModel"`.

Also affects: get_nonExistentDbtModel_404_notFound

Thanks

**Comment by pmbrull** [comment]
Hi, @harshach, noticed this while working on https://github.com/open-metadata/OpenMetadata/issues/1329. For the first iteration on the issue, I'll follow the same approach as with the DBT Model tests.

We can then fix both suites at the same time with this ticket.

Thanks!

**Comment by harshach** [comment]
@pmbrull this is actually a problem in our naming right now.
Entity we will call it with came case example, dbtModel and CatalogExceptionMapper throws the exception with entityName.Capitalize() this only capitalize the first letter https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java#L60

This is causing the problem with how we are calling the names in Entity vs how the exception is getting thrown

**Comment by sureshms** [comment]
@pmbrull and @harshach , `Entity.java` now has a method for Canonical name support. We could leverage it to convert all the entityNames into the right name as per our JSON schema. We should not be capitalizing the first letter, but should have the right entity name per the schema. Let me work on this.

**Comment by sureshms** [comment]
@pmbrull, a while back, we stopped capitalizing the first letter of the entity name in exceptions and started using as-is. This bug may no longer be relevant. Close this issue?

**Comment by pmbrull** [comment]
Thanks, @sureshms, closing this. I cannot even find the test that was throwing this so it might have been moved away.
