### ISSUE TITLE
Data Insights Ingestion: Better Exception Handling

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#14161]
**Affected module**
Ingestion Framework

**Describe the bug**
In the Data Insights processors if a record fails for any error, the entire processor does not report any data.
Handle the exceptions so that the entire processor does not fail.

**Comment by pmbrull** [comment]
this needs to be fixed in the `list_all_entities` -> add a `skip_on_failure` flag and log the entity breaking the schema
