### ISSUE TITLE
Oracle Ingest: lineage error ingesting an oracle View

### ISSUE THREAD

**Issue by SabineGl** [open-metadata/OpenMetadata#14198]
**Affected module**
Ingestion Framework

**Describe the bug**
Error in ingesting an oracle view: 
`Ingesting lineage failed: An Identifier is expected, got Token[value:]`

**To Reproduce**
see attached file
![ingest-oracle-lineage-error](https://github.com/open-metadata/OpenMetadata/assets/130458131/8535527a-331a-4e62-8b2e-10e6eda3b372)

**Expected behavior**
lineage information for view is working. in case it does not work because a missing permission. pls. adapt the error message 

**Version:**
 - Python version: 3.10
 - OpenMetadata version: 1.2.2
 - OpenMetadata Ingestion package version: openmetadata-ingestion == 1.2.2.0

**Additional context**

**Comment by ulixius9** [comment]
Hey @SabineGl, can you please share the entire query here for me to test it out, a masked version of query would also work

**Comment by pmbrull** [comment]
hi @SabineGl let us know ifyou can help us with the comment above. If so, we can reopen the issue. Thanks

**Comment by SabineGl** [comment]
Im sorry. I already copied the query but forgot to send it :-(

`WITH
SAWITH0 AS (select distinct T122752.EXTERNAL_ID as c1,
     T118369.CUSTOMER_ACCOUNT_NO as c2,
     T118385.SET_DATE as c3,
     case  when T118369.CUSTOMER_ACCOUNT_NO is null then 'Kunde nicht in O' when T122752.EXTERNAL_ID is null then 'Kunde nicht in D' else 'OK' end  as c4
from
          OUR_SCHEMA.ODIE_VW_ON_HOLD_CUSTOMERS T122752 /* Dim - Arbor aktuell */  full outer join (
          (
               OUR_SCHEMA.ODIE_T_CUSTOMER T118353 /* Fact - Odie Interactions */  left outer join
               OUR_SCHEMA.ODIE_T_CUSTOMER T118369 /* Dim - Customer */  On T118353.ID = T118369.ID) left outer join
               OUR_SCHEMA.ODIE_T_CUSTOMER T118385 /* Dim - Interactions */  On T118353.ID = T118385.ID) On T122752.EXTERNAL_ID = concat(concat(cast(T118353.CUSTOMER_ACCOUNT_NO as  VARCHAR ( 30 ) ), '-'), cast(T118353.SCHEDULE_ID as  VARCHAR ( 2 ) ))
where  ( (T118385.AUTOMATIC_REVERSAL in (0) or T118385.AUTOMATIC_REVERSAL is null) and (T118385.CANCELLED in (0) or T118385.CANCELLED is null) and (T118385.RA_CANCELLED in (0) or T118385.RA_CANCELLED is null) and T118385.REVERSAL_DATE is null ) ),
SAWITH1 AS (select D1.c1 as c1,
     D1.c2 as c2,
     D1.c3 as c3,
     D1.c4 as c4,
     D1.c5 as c5
from
     (select 0 as c1,
               D1.c1 as c2,
               D1.c2 as c3,
               D1.c3 as c4,
               D1.c4 as c5,
               ROW_NUMBER() OVER (PARTITION BY D1.c1, D1.c2, D1.c3 ORDER BY D1.c1 ASC, D1.c2 ASC, D1.c3 ASC) as c6
          from
               SAWITH0 D1
     ) D1
where  ( D1.c6 = 1 ) )
select
distinct
     D1.c2 as EXTERNAL_ID,
     D1.c5 as Status,
     D1.c3 as Customer_Account_No,
     to_char(D1.c4,'dd.mm.yyyy hh24:mi:ss') as Set_Date
from
     SAWITH1 D1
order by  c2, c5, c3, 4;`
