### ISSUE TITLE
Backend: Remove alerts and other fields to show in Activity feed

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14213]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Activity feed shows details related to modifications on alerts.

**To Reproduce**
modify the alerts and it sends it on the activity feed

**Additional context**

**Comment by harshach** [comment]
@ayush-shah can you not link collate slack link here and instead post the description of what needs to be done

**Comment by ayush-shah** [comment]
<img width="1020" alt="Screenshot 2023-11-30 at 4 35 52 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/3b6584b4-7622-4761-89de-7c274ec9d503">
The activity feed shows alert secrets

**Comment by mohityadav766** [comment]
Fixed
