### ISSUE TITLE
[CI] - Cancel Github Actions on a new push

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1421]
Whenever we push new code to a PR, old commits still keep running the actions.

We should add an option so that CI pipelines are cancelled on new pushes

**Comment by akash-jain-10** [comment]
This is achieved through Github Actions [Job Concurrency](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency).

Note: Concurrency is currently in beta and subject to change.

I'll prefer to wait till a GA version is up for Public release!
Let me know your thoughs!

**Comment by pmbrull** [comment]
hi @akash-jain-10, I am not seeing the BETA flag on the link you shared though 🤔 

Based on [this](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/) it might seem that concurrency was released in April.

Please let me know if I am missing something!

**Comment by harshach** [comment]
@pmbrull @akash-jain-10 any updates on this

**Comment by pmbrull** [comment]
@akash-jain-10 do you think we could use [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run-1)?
