### ISSUE TITLE
Java coding style plugin in docs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1422]
In the [docs](https://docs.open-metadata.org/open-source-community/developer/coding-style#java) we have a section regarding Java Coding Style.

However, when making a bunch of changes then you spend a lot of time reformatting if there are no helpers around. I've found the following tool https://github.com/google/google-java-format which has an IntelliJ plugin.

It might be a good idea to add in the docs a sentence linking the tool and help devs configure it locally to ease the PR process when validating the style.

Thanks

**Comment by mithmatt** [comment]
I've used this mvn plugin https://github.com/talios/googleformatter-maven-plugin in other projects.

This one auto-formats the code during mvn process-sources phase.

**Comment by pmbrull** [comment]
That would also be great. I think that any automated tool following the standards we want will be great, so that CI passes more easily

**Comment by mithmatt** [comment]
@pmbrull  Can you assign this one to me?
