### ISSUE TITLE
Feat: Foreign keys and visual lineage 

### ISSUE THREAD

**Issue by rparfig** [open-metadata/OpenMetadata#14237]
**Is your feature request related to a problem? Please describe.**
The lineage feature is great but it would be better if it could show the relationship between a data asset and other objects also captured in an ingestion. 

**Describe the solution you'd like**
For instance, the constraints are listed in the schema description of a table, but they are not present in the lineage tab. A visual representation of these relationships as part of the lineage would be an excellent addition so it is easier to identify the several ramifications / relationship that a table, view or any other data asset has

**Describe alternatives you've considered**
I am considering the use of the lineage option through the API but it would be great if this could be done automatically. The feature is present in commercial products, so this implementing this feature in Openmetadata would be a game changer.

**Additional context**

![image](https://github.com/open-metadata/OpenMetadata/assets/95098795/6fefd356-aa0c-4d8b-9368-6f7e8223a439)
![image](https://github.com/open-metadata/OpenMetadata/assets/95098795/9beff229-e6c3-494d-be6e-60dd35275b87)

**Comment by harshach** [comment]
@rparfig lineage is about what columns and tables are derived which upstream tables. We are not going to display schema relations in lineage. This is completely different feature

**Comment by rparfig** [comment]
I understand. Thank you for clarifying.
Would this then be consider as a feature to implement in the future? 
Exposing these dependencies in a graphical fashion allows for the analysis of dependencies between data assets, so it would be useful.
Thank you!

**Comment by harshach** [comment]
ER diagrams feature is shippeed in collate SaaS
