### ISSUE TITLE
While setting up Hive services, I chose MysqlConnection as the Hive Metastore Connection Details. But upon entering the username in the textbox, the selected option was altered.

### ISSUE THREAD

**Issue by sourcecodeguard** [open-metadata/OpenMetadata#14261]
the services was deployed with-docker-compose

While setting up Hive services, I chose MysqlConnection as the Hive Metastore Connection Details. But upon entering the username in the textbox, the selected option was altered.

![1701844269839](https://github.com/open-metadata/OpenMetadata/assets/8141847/015f9b46-12a4-4627-8419-f107aae64c8b)

**Comment by harshach** [comment]
@sourcecodeguard please ask this question in support channel, https://slack.open-metadata.org before opening a github issue.

**Comment by sourcecodeguard** [comment]
okay,thanks

**Comment by Sachin-chaurasiya** [comment]
Hello @sourcecodeguard , thanks for reporting the issue, could you please share the OM version that you are using, as this issue is fixed in `1.2.3`. 

Ref: https://github.com/open-metadata/OpenMetadata/pull/14123

**Comment by Sachin-chaurasiya** [comment]
-
