### ISSUE TITLE
Use DBCS characters in the display name of columns causes display error in versions history

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#14260]
**Affected module**
UI, possibly backend

**Describe the bug**
I use DBCS characters in the display name of columns causes display error in versions history.

**To Reproduce**
   Here is the screenshot. You can see the DBCS display name
![圖片](https://github.com/open-metadata/OpenMetadata/assets/85471195/5ac989bb-eb9a-4712-9079-8495398738b7)

   When Click on Versions history. An error displayed.
![圖片](https://github.com/open-metadata/OpenMetadata/assets/85471195/39886356-9fb8-43dd-9b6c-687682282ce4)

**Expected behavior**
   Normally display the changes among versions.

**Version:**
 
    Python version:
    OpenMetadata version: [1.1]
    OpenMetadata Ingestion package version: []

**Additional context**
N/A

**Comment by harshach** [comment]
@chirag-madlani lets take a look

**Comment by Ashish8689** [comment]
Closing this issue as it is not reproducible in the latest version 1.3.3. 

Character used : 
`
漢字 (Kanji)
ひらがな (Hiragana)
カタカナ (Katakana)
汉字 (Hanzi)
拼音 (Pinyin)
你好 (Nǐ hǎo)
한글 (Hangul)
조선글 (Joseongeul)
안녕하세요 (Annyeonghaseyo)`

<img width="1374" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/b84e2d33-747f-4499-bea7-182d34bf2014">
<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/0859db15-7263-4fa5-9438-e6f0a6dfdb50">
<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/b0c5cc39-11c5-41d9-b812-d844322ef117">

Feel free to re-open this issue with the sample text,  if the issue persists
