### ISSUE TITLE
SearchIndexingApplication running more than one running instance

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#14277]
**Affected module**
SearchIndexingApplication

**Describe the bug**
System is running more than one instance
Possibly related to issue  #14022

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/4106e122-10ed-4b24-8d80-d43e7ade6aa7)

**Expected behavior**
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/ba7d9cd4-509c-48a8-a7bf-a50cfbbf6cce)

**Version:**
 - OpenMetadata version: 1.2.2 AND 1.2.1

**Comment by harshach** [comment]
fixed in 1.3.1
