### ISSUE TITLE
Tags Page UI issues

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#14292]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- Button overflow issue for an in-markdown box of description
- Unwanted API call is triggered on the `Add` and `Edit` cases if we close the modal and data disappears in form while saving the changes
- when hit the delete button in the table, the delete button shows loading.

**To Reproduce**

Screenshots or steps to reproduce

![image (1)](https://github.com/open-metadata/OpenMetadata/assets/66266464/6831e9f8-10bc-4916-ac90-645fd209f9e5)

![image (2)](https://github.com/open-metadata/OpenMetadata/assets/66266464/66a4532d-8b33-409a-9f9f-20be55b0321c)

https://github.com/open-metadata/OpenMetadata/assets/66266464/9a82650c-ab9d-4e49-bd22-fb2e3fa9b4bc

https://github.com/open-metadata/OpenMetadata/assets/66266464/202ea455-2c3a-493c-9e52-afd91bee77c9

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harsh-vador** [comment]
I will take this up
