### ISSUE TITLE
Stale openmetadata-ingestion and docker openmetadata/server

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1429]
I was supporting one of our users and I have noticed that both the python CLI and the docker containers were stale. He installed OM 3 weeks ago and he was following the current documentation to try again.

You can reproduce it:
```sh
# create a new python environment
# simulate an install of 3 weeks ago
pip install 'openmetadata-ingestion==0.4.4'
# it will not upgrade the package
pip install 'openmetadata-ingestion'

# to use the latest version
pip install --upgrade 'openmetadata-ingestion[docker]'
# stop all your containers
# nukes your docker environment!!!
docker system prune -a -f
# simulate an install of 3 weeks ago
docker pull openmetadata/server:0.5.0
docker tag 4c7ef16771b2 openmetadata/server:latest
# start OM
metadata docker --start
```

Latest CLI with an old image.
![image](https://user-images.githubusercontent.com/32617/143724522-165ec2a2-1061-4ca5-9d51-eba9d7fb1904.png)

**Comment by harshach** [comment]
@akash-jain-10 @ayush-shah 
1. Lets make a http call before the start of the docker --start to see if there are any latest images are published
2. If the current image is lower than the latest , print warning message to the user
3. allow user to build based on the new image.
