### ISSUE TITLE
Tags usage

### ISSUE THREAD

**Issue by milinavicute** [open-metadata/OpenMetadata#14303]
**Affected module**
UI

**Describe the bug**

Attaching tags to the "Database Services" or "Schema" level it's not possible to find this objects on the explore panel by tags. Seems like explore panel lack the necessary data assets. 

**To Reproduce**

Setting -> Databases -> Database Services -> Schema -> *choose any service or schema and pin any tag* ->
![image](https://github.com/open-metadata/OpenMetadata/assets/71179466/c5739acc-7ddf-4693-b5e7-77f5938c011c)

 -> click at this tag being on the Classification page* -> 
![image](https://github.com/open-metadata/OpenMetadata/assets/71179466/753221a2-c0ea-4a97-953b-87c2fe8b97aa)

-> no result at the Data assets list
![image](https://github.com/open-metadata/OpenMetadata/assets/71179466/bcd81dcd-723b-4561-95ac-595ffb3f904c)

**Expected behavior**
The ability to find any Data assets which have tags. 

**Version:**
 OS: Microsoft/ Windows 10 Pro
 Python version: Python 3.10.12
OpenMetadata version: 1.2.0
OpenMetadata Ingestion package version: 1.2.0

**Comment by pmbrull** [comment]
hi you can try to go to Application > Search Index > Reindex. Should solve this.

If afterward this is still an issue, please reach out to us in Slack https://slack.open-metadata.org/ so that we can gather more information and understand if this is indeed a bug
