### ISSUE TITLE
Unable to add the term's name in Thai.

### ISSUE THREAD

**Issue by Sakanarmmfec** [open-metadata/OpenMetadata#14311]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
:UI

**Describe the bug**
:Unable to add the term's name in Thai. It appears that there is a validation with the term's name, and it is not working correctly for Thai

**To Reproduce**

Screenshots or steps to reproduce
:
1. Click Glossary
![image](https://github.com/open-metadata/OpenMetadata/assets/153187061/89066472-07e6-4915-8840-4e89f474be83)
2. Click Add Term in a Glossary Domain
![image](https://github.com/open-metadata/OpenMetadata/assets/153187061/9b15fabd-f705-4caf-a755-dd2d4d397615)
3. Input Term name in Thai
eg. "ที่อยู่" , "พยัญชนะ", "ลูกค้า" 
![image](https://github.com/open-metadata/OpenMetadata/assets/153187061/8b3b0616-b1e0-4a9c-9070-2d04a6b91194)
4. You will see the error message
"Name must contain only letters, numbers, underscores, hyphens, periods, parenthesis, and ampersands."

**Expected behavior**
: Able to add the term's name in Thai.

**Version:**
 - OS: [e.g. iOS]: 
 Run Docker on Window 10,  Error Occur when using Open Metadata via window browser eg. chrome
 Docker Compose version v2.23.0-desktop.1
 
 - Python version:  v. 3.9
 - OpenMetadata version: [e.g. 0.8] : 
 V. 1.2.2
 ![image](https://github.com/open-metadata/OpenMetadata/assets/153187061/777d81ea-589c-407f-abcb-e86ad7e856f1)

 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]: 
 V. 1.2.2
 ![image](https://github.com/open-metadata/OpenMetadata/assets/153187061/f50231e5-26f8-4489-a3f8-5c01d1720c0c)
![image](https://github.com/open-metadata/OpenMetadata/assets/153187061/26d7bd5f-ab0e-4a43-b59f-7876347296fe)

**Additional context**
:In case you have any other question, please contact sakan_pu@mfec.co.th
Thank you very much for helping

**Comment by chirag-madlani** [comment]
@sureshms No it should be frontend only for now, If required will ask backend
