### ISSUE TITLE
Clicking on glossary term while adding throws error

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#14317]
**Affected module**
UI

**Describe the bug**
Clicking on glossary term while adding throws error. It is redirecting to tags page instead of glossary.

https://github.com/open-metadata/OpenMetadata/assets/33024356/0c4dc25d-cf9d-4ee9-8385-7bbbcbe68a62

**Comment by harsh-vador** [comment]
I will take this up
