### ISSUE TITLE
CI - Cypress run 

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#14324]
Need following modification for Cypress CI runners 

- [ ] Cypress mysql & postgres should run again main Nightly
- [ ] Cypress should run on PRs after adding `e2e` Label 
- [ ] If we are able to run Runners on non-draft PRs then it will be very helpful 
- [ ] Setup 4 machine for Cypress runs on parallel manner to reducs wait time for results 

cc: @harshach

**Comment by preetsshah** [comment]
I would like to work on this.
