### ISSUE TITLE
Cannot close/accept suggestion for task on Dashboard chart

### ISSUE THREAD

**Issue by locian98** [open-metadata/OpenMetadata#14329]
**Affected module**
I suspect only the backend is involved, as the UI part works.

**Describe the bug**
When a user creates a task on a Dashboard chart, for example a description request, the task is created successfully.
It is possible to comment on it, but it is not possible to close the task (either by closing it or accepting the suggestion).
An error is displayed when trying to close or accept.

**To Reproduce**
Request description on a Dashboard chart:
<img width="857" alt="Screenshot 2023-12-11 at 11 08 09" src="https://github.com/open-metadata/OpenMetadata/assets/147619594/141478f3-82e3-4e28-a36b-747a7a1a78a3">

Click on "Accept suggestion". An error will show up:
<img width="1341" alt="Screenshot 2023-12-11 at 11 08 57" src="https://github.com/open-metadata/OpenMetadata/assets/147619594/7f392a58-a181-4e9d-95bd-2c2530b710b1">

Write a message and click on "Close". The same error will show up:
<img width="1341" alt="Screenshot 2023-12-11 at 11 14 32" src="https://github.com/open-metadata/OpenMetadata/assets/147619594/37ee2c60-8317-46d1-8e12-11c39eeb1b95">

**Expected behavior**
I expect the task to be closed when I click on "Close", and the suggestion to be accepted when I click on "Accept Suggestion".

**Version:**
 - OS: [e.g. iOS] iOS
 - Python version: not relevant
 - OpenMetadata version: [e.g. 0.8] 1.2.3 on Playground (11 dec 2023)
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] not relevant

**Comment by mohityadav766** [comment]
this is fixed #14456
