### ISSUE TITLE
Add S3 Support

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#1433]
Add S3 connector and metadata ingestion for location entity

**Comment by amiorin** [comment]
I'm working on it in steps.

1. Ingestion of location with sample_data connector
2. Ingestion of location with the Glue connector
3. Ingestion of location with a new S3 connector. The requirements here are not defined yet. @mithmatt What do you have in mind?

**Comment by mithmatt** [comment]
Given aws credentials, ingest all S3 buckets (accessible through those credentials) as Locations

```
            for bucket in boto3.resource("s3").buckets.all():
                self.status.scanned(bucket.name)
                yield Location(
                    id=uuid.uuid4(),
                    name=bucket.name,
                    displayName=bucket.name,
                    locationType=LocationType.Bucket,
                    service=EntityReference(id=self.service.id, type="storageService"),
                )
```

**Comment by mithmatt** [comment]
I have a first cut for the related changes while I was making my way to do the policy ingestion (had the changes partially done when I opened this issue).

@amiorin 
I'll create and link the PR here, in case you want to refer to it or commandeer it as you work on this task

**Comment by harshach** [comment]
@mithmatt Thanks for this. But wouldn't this create a lot of noise in metadata , given most companies have lot of s3 buckets.   Does buckets.all() return the top-level buckets or recursively returns nested buckets as well.

**Comment by amiorin** [comment]
Max number of buckets per AWS account is 1000.

From https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html
![image](https://user-images.githubusercontent.com/32617/143782653-d1f359c6-c90d-40eb-b6b4-00d8fd7b64ca.png)

What is a nested bucket in S3?

**Comment by mithmatt** [comment]
> @mithmatt Thanks for this. But wouldn't this create a lot of noise in metadata, given most companies have lot of s3 buckets. Does buckets.all() return the top-level buckets or recursively returns nested buckets as well.

`buckets.all()` returns only the bucket names and does not go into prefixes or folders within the bucket.



There is probably less value if we go down the path of exposing all buckets on the UI -- this does not provide more benefit beyond what AWS console provides.

I think the location we ought to ingest should be connected to a use case and be able to derive insightful information from it.

We should consider ingestion based on the use case such as table:
1. Get all tables from AWS Glue Catalog  --> ingest tables (already part of glue.py ingestion)
2. For each table, get their location --> (need to build this)
3. For location, get policies that apply to this location -->  (need to build this)

With the above approach, we can expose location and policy information alongside the table where applicable. 

#1435 was a quick fix to 2 above to unblock 3.

**Comment by amiorin** [comment]
@mithmatt 
> There is probably less value if we go down the path of exposing all buckets on the UI -- this does not provide more benefit beyond what AWS console provides.

Many companies have one AWS Org and multiple AWS Accounts. I see a benefit in having the technical metadata of all buckets of a company in one place. OM makes it easier to implement ownership, lineage, tiering, metrics, and custom tags like DEV and PROD to enable discovery and workflows for compliance and cost analysis.

**Comment by harshach** [comment]
Thanks @amiorin . I guess if we are not reading objects than this should be fine.
I am more concerned about this
`If you have an object named photos/2017/example.jpg, the console will show you a folder named photos containing the folder 2017. The folder 2017 will contain the object example.jpg. `
so if I understand correctly we are going to photos as the bucket. Not the underneath objects now. Which makes sense but how would be able to associate a table/database to a bucket. Give an external table usually associated with an object/folder like below

`CREATE EXTERNAL TABLE
external_schema.table_name  
(column_name data_type [, …] )
[ PARTITIONED BY (col_name data_type [, … ] )] 
[ { ROW FORMAT DELIMITED row_format |
  ROW FORMAT SERDE 'serde_name' 
  [ WITH SERDEPROPERTIES ( 'property_name' = 'property_value' [, ...] ) ] } ]
STORED AS file_format
LOCATION { 's3://bucket/folder/' | 's3://bucket/manifest_file' }
[ TABLE PROPERTIES ( 'property_name'='property_value' [, ...] ) ] `


In above case are we going to create another location with the fqdn of the location and associate with the said table?
If we did that does the top level buckets still make sense? 

We can move this to discussions thread to get more clarity on the buckets vs their association with the table/database entities

**Comment by amiorin** [comment]
@harshach 
> so if I understand correctly we are going to photos as the bucket. 

Almost, that would be a ```prefix```. A ```bucket``` in OM has the same meaning of S3/GCS/Minio ```bucket```.

A location of a Table has type ```Table``` and a location of a Database has type ```Database```. A location of anything else has type ```Prefix```.

It makes sense to have locations containing locations to enable a data mesh governance based on ownership of prefixes.

**Comment by mithmatt** [comment]
@amiorin 

> I see a benefit in having the technical metadata of all buckets of a company in one place. OM makes it easier to implement ownership, ...

I stand corrected. Yes there is value in having this information if we are going into details of ownership, tiering, etc.


I'm starting a discussion thread on this with some info I gathered since it may be beyond the scope of this task + discussion threads are so much more nicer than comments on issues.

**Comment by amiorin** [comment]
👍

**Comment by mithmatt** [comment]
Discussion thread #1446

**Comment by mithmatt** [comment]
This is completed
