### ISSUE TITLE
Search Index Epic

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14355]
- [x] Search Index: removing / adding the entities throws an error

![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/bc08a70c-9057-4c60-a154-72c42b60fd77)

https://sandbox-beta.open-metadata.org/settings/integrations/apps/SearchIndexingApplication

Similar issue was found in support: https://openmetadata.slack.com/archives/C02B6955S4S/p1702393531771619

![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/26ce74cd-d590-4726-b389-cdfb61aa754c)

- [ ] Search index on indexing doesn't show right numbers
Upon deletion of almost all entities, sandbox is showing 50k+ reindexed things
ref: https://sandbox.open-metadata.org/settings/integrations/apps/SearchIndexingApplication

**Comment by chirag-madlani** [comment]
Update:
After re-installing application it's working fine

**Comment by mohityadav766** [comment]
marking this as fixed m count was due to data insights indexes
