### ISSUE TITLE
Airflow log using UTC even if the server uses local time zone

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#14368]
**Affected module**
UI/Backend

**Describe the bug**
The airflow log shows UTC even if we configure local timezone in the server OS.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
The time zone in airflow server log should be identical with server OS time zone.

**Version:**
Python version:
OpenMetadata version: [1.1]
OpenMetadata Ingestion package version: []

**Additional context**
N/A

**Comment by NiharDoshi99** [comment]
Hi, @AntonioChen0206 
Airflow timezone is configurable, there is option on top-right to change timezone and logs changes as per that timezone.
Timezone set to UTC
<img width="1419" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/51595473/91318171-9167-4162-a5eb-643a8d28c13e">
Timezone set to IST
<img width="1430" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/51595473/e7a0e19b-d118-4dff-8d8f-3247f8dab4ed">

**Comment by ulixius9** [comment]
@AntonioChen0206  let us know if the above solution works for you otherwise you can connect with us on slack support channel for any further discussion!
