### ISSUE TITLE
Custom order in custom properties

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#14369]
**Is your feature request related to a problem? Please describe.**
We add a lot of custom properties and the user might want the list sorted in alphabetical order, Ascending or Descending?

**Describe the solution you'd like**
Design a button beside the title "NAME" to toggle Ascending or Descending?

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by harshach** [comment]
@chirag-madlani can we do this on the UI side?

**Comment by chirag-madlani** [comment]
@harshach Yes we can have it for table column

**Comment by karanh37** [comment]
Fixed with #14537
