### ISSUE TITLE
Hyperlink in Email notice does not work

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#14365]
**Affected module**
UI/backend

**Describe the bug**
The hyperlink generated by the email notice does not work when click it.

**To Reproduce**

   Please see this attach GIF
![Q1-2](https://github.com/open-metadata/OpenMetadata/assets/85471195/59fecff7-970b-4bc1-9863-1c99eb1b998d)
  
   The email setting is here
![Q2-2](https://github.com/open-metadata/OpenMetadata/assets/85471195/bda1d8f8-7b3e-4a68-927f-c1af28fa1d2c)

**Expected behavior**
Click on the hyperlink in the email should jump into the BOT.

**Version:**
- Python version:
- OpenMetadata version: [1.1]
- OpenMetadata Ingestion package version: []

**Additional context**
N/A

**Comment by mohityadav766** [comment]
this is fixed here https://github.com/open-metadata/OpenMetadata/pull/14674 , we need to make sure openmetadataUrl or ENV OPENMETADATA_SERVER_URL points to the proxy or url where UI is hosted, for example if backend is started directly without proxy then http://localhost should be used , else http://localhost:8585 or other port should be used
