### ISSUE TITLE
Version page breaks on adding column display name

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#14363]
**Affected module**
UI

**Describe the bug**
When the display name field of column is populated the version page breaks on UI with following error

![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/dea87891-1e59-44c7-80e0-753b5d9f4569)

![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/518b4cd9-28a3-4bfc-8368-20af65ac45d8)

**Comment by aniketkatkar97** [comment]
@ulixius9 Can you also please add the steps to reproduce the issue with the pipeline version page?
