### ISSUE TITLE
Usernames with period breaks tasks view due to being enclosed in double quotes

### ISSUE THREAD

**Issue by xangxiong** [open-metadata/OpenMetadata#14360]
**Affected module**
This impacts the UI, specifically the settings/members/users view when clicking on a user and then viewing their Tasks.

**Describe the bug**
Viewing users with a period in their username will translate to a URL in the form of `/users/"my.username"`.  When viewing the user and clicking on the `Tasks` menu, the url will be change to `/users/%2522my.username%2522/activity_feed/tasks`.

This will break the UI with an alert `user instance for "%22my.username%22` not found.

**To Reproduce**

1. Create a user with a period in its username.  For my case, we are integrated with Azure SSO and all our users have a period in their username.  Normally in the format of `{first-name}.{last-name}`.
2. Login and access the menu `Settings -> Users`.
3. Click on a username with a period in it to view their profile (e.g. my.username).
4. Under the `Activity` tab, click on `Tasks`.  You will encounter the error.  Sometimes it doesn't happen when clicking on `Tasks`, so you will have to click on `@ Mentions` or other activity menu to trigger the error.

**Expected behavior**
Viewing usernames with period should work and not translate double quotes to %2522 encoding.

**Version:**
 - OS: MacOS Sonoma 14.1.2
 - Python version:
 - OpenMetadata version: 1.2.0
 - OpenMetadata Ingestion package version:  openmetadata-ingestion==1.2.0

**Additional context**
![Screenshot 2023-12-12 at 12 38 56 PM](https://github.com/open-metadata/OpenMetadata/assets/6294649/ea5ae27b-2202-4cab-be65-f6b7e7970eb0)

**Comment by harshach** [comment]
@xangxiong thanks for reporting. Its fixed in Release 1.2.3
