### ISSUE TITLE
Successfully connect to Kafka but cannot fetch topic sample data

### ISSUE THREAD

**Issue by AntonioChen0206** [open-metadata/OpenMetadata#14366]
**Affected module**
Ingestion

**Describe the bug**
We configure a Kafka connect. The connection is ok but can not fetch topic data 

**To Reproduce**

   The execution error:
![Q1-2](https://github.com/open-metadata/OpenMetadata/assets/85471195/5e47b2f2-0bce-4464-9bf3-48a970e44ad3)

   Kafka installed:
![Q1-1](https://github.com/open-metadata/OpenMetadata/assets/85471195/ab529218-1672-4a1f-ba69-563710f4ac19)

**Expected behavior**
Expect to see some sample data from Kafka.

**Version:**
Python version:
OpenMetadata version: [1.1]
OpenMetadata Ingestion package version: []

**Additional context**
N/A

**Comment by harshach** [comment]
@AntonioChen0206 which version of Kafka are you using

**Comment by YMACHEN** [comment]
@harshach we are using 2.7

**Comment by kenyyh** [comment]
This issue occur when Schema Registry is not set.  
If the Schema Registry is set and accessible the Sample Data will be collected even when avro feature is not used in the topic.

**Comment by harshach** [comment]
@kenyyh thanks for the context. We will take a look why thats the case

**Comment by pmbrull** [comment]
can't replicate
