### ISSUE TITLE
Explore filter 'Owner' is inconsistent showing owners/Empty Owner field in Explore view

### ISSUE THREAD

**Issue by omozgovaya** [open-metadata/OpenMetadata#14388]
**Affected module**
UI

**Describe the bug**
Explore view shows tables with no owner whilst owner is set. 

**To Reproduce**
1. Create user or team
2. Set as owner of db and schema
3. Check explore view
4. Change display name of user or run Search Indexing App
5. Field 'Owner' is Explore view is empty

Screenshots or steps to reproduce
![Uploading Sc
<img width="722" alt="Screenshot 2023-12-14 at 15 03 57" src="https://github.com/open-metadata/OpenMetadata/assets/124048632/512cd845-5802-401d-8f61-5d5578c60622">
<img width="786" alt="Screenshot 2023-12-14 at 15 03 50" src="https://github.com/open-metadata/OpenMetadata/assets/124048632/af68564f-8c27-4077-a99b-edf4502b4633">
reenshot 2023-12-14 at 15.04.04.png…]()
<img width="1317" alt="Screenshot 2023-12-14 at 15 04 24" src="https://github.com/open-metadata/OpenMetadata/assets/124048632/25688f43-551b-423d-b375-a0b58b9b0b2b">

**Expected behavior**
Owner field should be filled with owner.

**Version:**
OS: Ubuntu 22.04.2 LTS
Python version: Python 3.10.12
OpenMetadata version: 1.2.2
OpenMetadata Ingestion package version: 1.2.2

**Additional context**

**Comment by harshach** [comment]
@omozgovaya this is fixed in 1.2.3. Please try again.
