### ISSUE TITLE
Add type of Glossary object

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#14389]
**As is:**
I can explain to you the way how my company decided to create our Business Glossary in general.

We use objects that you call "Glossary" as Domains (in other words Business vertical).
Then in each Domain we create a hierarchy of objects that you call "term" with different types (Metric group -> Entity-> Metric )
We created a Classification of tags with Glossary object types because it's impossible to set a type of object in Business Glossary.

**To be:**
Business glossary is an hierarchical structure that is why there is a necessity to have objects with different types.
So when we use classification with tags it is not the optimal decision because when you assign a term to a field in table you also see the related tag.

**Desired solution:**
Please add type of glossary objects as a particular attribute like "Synonyms", "Related terms" and etc. and also as a column to Bulk Import file.

**Comment by KsM00000** [comment]
Hi! Just wondering: will this feature be implemented?
We've made do with tags for terms in the glossary, but if there were types for glossary terms that would be great.

**Comment by harshach** [comment]
You can use custom properties to achieve this. Specially with Enum custom property
