### ISSUE TITLE
UI: lineage sort children by alpha, other...

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#14395]
**Is your feature request related to a problem? Please describe.**
It would be nice if the child nodes in a lineage graph were sortable (alpha, create date, usage count...)

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/73e8434b-76e2-4e42-8389-d9721c6c1473)

**Comment by harshach** [comment]
@karanh37 @07Himank lets see if we can handle this in the release 1.3

**Comment by karanh37** [comment]
In the newer release, we are sorting by alpha.
We are not planning to have other sort fields for now.
