### ISSUE TITLE
Improvements of Glossary Approval Workflow

### ISSUE THREAD

**Issue by LiubovPasechnik** [open-metadata/OpenMetadata#14391]
*The problem**
We have updated OpenMetadata to v1.2 and faced with the following problems:
1. we have already Glossary filled out in v1.1 so when v1.2 was installed we found all our terms in "Approved" status. However it is crucial for our business processes to be able to start Glossary Approval Workflow not only when a new term is created via UI.
2. current behaviour is that Glossary Approval Workflow starts only if Reviewers were added to parent term in UI 

**The desired solution**
So we would like to suggest you to add the following functionality that will boost usability of Glossary:
1. If terms were created via Bulk Import: in csv-file user sets Reviewers, puts term in "Draft" status -> then these terms massively are sent to provided reviewers
2. It will be more convenient to be able to set Reviewers and start Glossary Approval Workflow directly when creating a term regardless if Reviewers were added to parent term or not. 
So the desired flow for the new terms in UI is:
- user creates a new term (but in the parent term there is no specified reviewers)
- user sets a Reviewer in the card of new term
- term is created in the "draft" status and in that moment Glossary Approval Workflow starts
This logic also works for the solution described in the first paragraph. I mean when user wants to create several terms simultaneously he will have to set a Reviewer only for the current term and not for parent.
3. Sometimes there is a necessity to audit terms and resend terms to reviewers again (for instance when formula of metric has charged)
- Can you add maybe "restart Glossary Approval Workflow" button in order to resend term to reviewers again?

**Comment by harshach** [comment]
@pmbrull lets look at this during the workflows execution

**Comment by harshach** [comment]
Fixed in 1.6.0
