### ISSUE TITLE
DB2 Service can't load plugin

### ISSUE THREAD

**Issue by elguero6** [open-metadata/OpenMetadata#14390]
**Affected module**
Db2 Service Connection

**Describe the bug**
Cannot create a DB2 Connection

**To Reproduce**

1.) Create a Db2 Service
2.) Enter all information and Test Connection

**Expected behavior**
Airflow logs show : Can't load plugin: sqlalchemy.dialects:db2.ibm_db

**Version:**
 - OS: Kubernetes / helm chart 
 - Python version: 3.9 
 - OpenMetadata version: 1.2.3

**Additional context**
<img width="1351" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/8837275/bdb2a3fa-bc58-47aa-a9ff-d31174ef0f6d">

**Comment by harshach** [comment]
@ulixius9 can we update the docs for this. Also it would be good with-in the connector check if the lib available if not throw a meaningful exception to install it

**Comment by elguero6** [comment]
This helped create a successful db2 connection,
1.) Exec into the airflow pod
Run: pip install ibm-db-sa,
2.) Setup the DB2 connector on the openmetadata UI settings, make sure to add these properties if SSL is enabled :
SECURITY=SSL
SslServerCertificate=/path/ca-certificate.crt
