### ISSUE TITLE
UI: Explore search not finding tables... and NEEDs alpha sorted search results.

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#14394]
**Is your feature request related to a problem? Please describe.**
The UI is not showing tables that I know are there when filtering to just one schema. If I search for the table directly it will show, but sometimes you don't know exactly what you are looking for and the UI is now showing everything in alphabetical order.

Below are some screenshots documenting my frustration with what I would expect should work.

**Additional context**
Filtered on Schema with no search criteria
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/b8cb375b-a0a6-4d72-83be-7c41237abfd2)

There IS a table named ACCT... Why is it not in the results?
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/b645a1b9-2aba-4e5d-8e5e-a0833fa05eda)

From snowflake
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/c6a44883-9462-430f-a8e9-1c8f9b831d29)

Even the search bar quick results doesn't show it
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/170fd225-d0d2-4a58-ad93-5eacd6c971da)

IF I go by way of settings|Database services... and navigate to the DB then schema it shows ACCT table...
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/6b42e4f4-798d-4ffb-b8d6-79c6237819e9)

I can finally get it to show in the search bar with certain criteria
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/84d73c5b-edff-4cce-949d-fb8619d803dc)

But that ONLY works IF I use the correct case
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/66b5b8c7-d8ff-41fd-b94f-8f6c11fed83c)

Searching for a schema names doesn't return any tables
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/8b7ce380-90ae-463e-aae0-1d4227c1ec00)

**Comment by harshach** [comment]
@karanh37 @07Himank we should in the sort by field to sort by name or displayname

**Comment by karanh37** [comment]
![image](https://github.com/open-metadata/OpenMetadata/assets/33024356/e90f5eb5-35a7-4817-a92c-888555a81e58)

Sort by Name is now added.
