### ISSUE TITLE
UI: Explore - DataAssets tree view based on hierarchy

### ISSUE THREAD

**Issue by kputland** [open-metadata/OpenMetadata#14393]
**Is your feature request related to a problem? Please describe.**
As a user it would be nice if the Data Assets pane of the UI offered a tree view of the search results

![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/687be1a6-924a-454c-b914-47e6f025fa66)

Similar to how this is shown in the snowflake UI
![image](https://github.com/open-metadata/OpenMetadata/assets/1480163/cff8c0c3-017a-4dcf-a643-71e2db011beb)

**Comment by harshach** [comment]
Treeview at the service->db->schema level will not scale. Users already have filters do to this faceted search already

**Comment by sureshms** [comment]
@kputland This tree view is also available if you go to a database service page (which list databases), database page (which lists schemas), schema page (which lists tables)
