### ISSUE TITLE
Response returns empty strings for synonyms under glossary terms

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14428]
The backend on getting glossary terms, sends an empty string, which fails the validation on python. reproducible on sandbox and sandbox beta

{
            "id": "72068262-2c19-4fac-8178-23abc25b48ad",
            "name": "Account",
            "displayName": "",
            "description": "A type of financial property or financial obligation that is held and owned under your name. When you open a financial account—whether it's a checking account, savings account, CD or money market account—you have certain rights and responsibilities as an account holder.",
            "fullyQualifiedName": "Banking.Account",
            "synonyms": [
                ""
            ],

to reproduce:

```
curl -X GET "https://sandbox-beta.open-metadata.org/api/v1/glossaryTerms?glossary=39cd92f7-08bc-4d40-8971-7f8171a4bea7&fields=children%2CrelatedTerms%2Creviewers%2Cowner%2Ctags%2CusageCount%2Cdomain%2Cextension" \
 -H "accept: application/json"\
 -H "authorization: Bearer <TOKEN>" \
```

**Comment by harshach** [comment]
Tested with main 

![Image](https://github.com/open-metadata/OpenMetadata/assets/38649/4a6fd299-ca25-41b2-a99f-c2b702046113)

**Comment by harshach** [comment]
@ayush-shah can't reproduce this with new glossary in sandbox-beta or sandbox. If you can create a new glossary and glossary terms without synonyms and see an empty string, let me know.
