### ISSUE TITLE
Data insights report email related feedback

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#14427]
Here is the Data Insights report email I received:
<img width="470" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/206ccc3f-1c3d-4e93-8c8d-48ef85363881">

Issues:

- [x] The following button is not clickable <img width="240" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/ef7bb0db-d892-4843-9205-c47e3cc4e518">
- [x] Reachout should be Reach out in the following text. Btw, how do they reach out? 
<img width="393" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/a96c9ca3-4c67-47d4-a519-5672a4b819a1">

- [ ] Total Data Assets has different styling compared to other boxes (7 data day change line can have a grey background similar to others) -
<img width="411" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/d88969c3-d401-4b45-92bf-2a2d2dfb91db">

- [x] Let's just say, "In the past week, the Total Data Assets changed by ~a total of~ 30416.67%." (Note the period at the end of the sentence).
<img width="513" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/43a87fc3-7c07-4be5-bb66-2dc440c84bd1">

- [x] Let's round all the percentages to two decimal places. In some cases, it is three decimal places, and in some cases, it is two.
- [x] Both symbol % and the word per cent used redundantly. Let's just use % symbol in these places. 
<img width="346" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/45efbdd1-8c33-42c3-8074-0c196de34af0">
<img width="240" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/29b74180-ceaa-41a9-a1d0-db1162b45d49">
<img width="508" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/143ed99d-0769-425f-9b66-2cf5b3497fb2">

- [x] The second line here should be saying Assigned Ownership instead of Completed Description 
<img width="623" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/a4ed19e8-d265-402b-bf14-4846725144f6">

- [ ] We need to make the table styling (looks like it has no style/default style) consistent with the rest of the email:
<img width="649" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/1417689/5e35c477-e76c-4dc4-a13b-f799c8039f51">

**Comment by mohityadav766** [comment]
@chirag-madlani need someone from UI for styling HTML , I think those 4 boxes are of variable size , can we make them fixed so we have constant styling

**Comment by harshach** [comment]
@mohityadav766 the tier table should be sorted, Tier 1 -> Tier 5 and at the bottom No Tier

**Comment by harshach** [comment]
@chirag-madlani @mohityadav766 this needs to be fixed for 1.3.0

**Comment by mohityadav766** [comment]
majority of the things here are fixed @harshach , styling and table type I am not changing , since we have another format which I need to work on and this is anyway going to be removed
