### ISSUE TITLE
Enhance table details

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#14440]
On the table details page, show if a column already has DQ tests

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/2504d275-1969-41be-83e3-8937dfeb235e)

We could add a new column in the details table with small green,yellow,red circles and a number for people to know if tests exists. Clicking there should redirect us to the DQ tag.

The goal is to help people understand what info we have there on a single glance.

In a similar fashion, would it be possible/beneficial to show if a column has lineage?

**Comment by ShaileshParmar11** [comment]
Blocked on https://github.com/open-metadata/OpenMetadata/issues/15593

**Comment by harshach** [comment]
@ShaileshParmar11 is this still blocked?

**Comment by ShaileshParmar11** [comment]
Yes @harshach
