### ISSUE TITLE
Delete instance, But metadata still exists

### ISSUE THREAD

**Issue by win-shy** [open-metadata/OpenMetadata#14451]
when I add a new service and run the ingestion. The metadata of table will be displayed on the page where is located Tables of Explore. But I delete the Service, the metadata info still exists. The page shows 'table instance for hive2_231.dw.test.tb3 not found' frequently.
![image](https://github.com/open-metadata/OpenMetadata/assets/20906584/fb1a470b-5d58-4d2f-be0f-90f83862e81a)

![image](https://github.com/open-metadata/OpenMetadata/assets/20906584/1305d549-e7ed-4dbb-afa9-57b6cb3577ec)

**Comment by harshach** [comment]
@win-shy please ask in our support before opening github issues. https://slack.open-metadata.org
your ES indexing might have failed, you can re-index to get a up-to-date data in ElasticSearch

**Comment by cglaze11** [comment]
@win-shy Hi, have you solved this problem yet?
