### ISSUE TITLE
Advance Search: The dropdown menu disappears on typing more than 1 character.

### ISSUE THREAD

**Issue by sharmaaanchal27** [open-metadata/OpenMetadata#14450]
**Affected module**
It does impact the UI and Search feature.

**Describe the bug**
The dropdown in Advance Search feature disappears on typing more than 1 character "Sy".

**To Reproduce**
Steps:
1. Click on Advance Search and select a Field example: Database.
2. Select "==" under "Condition".
3. Type "Sy", the dropdown disappears.

<img width="709" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/128101256/c95030dc-9105-414a-973b-ebd9a8aa5f34">

<img width="714" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/128101256/530bdba1-aa3d-4fef-8377-b8f5d4e70185">

<img width="718" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/128101256/419cee4f-a22b-48a2-8bd1-60c8c809291c">

<img width="697" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/128101256/960af20d-6687-47db-bce3-40887c4c8b07">

<img width="711" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/128101256/7fcbf142-3cd4-4513-bd68-06a8e69d79f2">

**Expected behavior**
The dropdown list should narrow down the list matching to the characters typed in the text field.

**Version:**
 - Python version:
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by imperativa-tkp** [comment]
@pmbrull can i pick this up?

**Comment by im-perativa** [comment]
@pmbrull can I pick this up?
