### ISSUE TITLE
Integration with Power BI Dataflows

### ISSUE THREAD

**Issue by tkanagaw** [open-metadata/OpenMetadata#14478]
In order to see the complete lineage of our data, we need to have Power BI Dataflows be added to OpenMetadata.  Currently, we cannot see a full impact analysis since the lineage stops at the Dataflow, then picks up again at the Power BI Dataset.

Column level lineage from the Snowflake tables into the Dataflows, then from the Dataflows to the Power BI Datasets (Symantec layer) would be ideal.

**Comment by LKC-dev** [comment]
Up

**Comment by carloshhelt** [comment]
Up

**Comment by migueldcferreira** [comment]
Hello,
.pbit files are supposed to solve this issue, but it is not working. Please see my issue for more details : https://github.com/open-metadata/OpenMetadata/issues/18600
Up

**Comment by ulixius9** [comment]
should be fixed with pbit 
(ps https://github.com/open-metadata/OpenMetadata/issues/18600 is also closed)

@tkanagaw please reach out to us on slack if you still face this error
