### ISSUE TITLE
DataInsights application fails when KPI for entities with description is exist

### ISSUE THREAD

**Issue by omozgovaya** [open-metadata/OpenMetadata#14475]
**Affected module**
Impacts UI and backend

**Describe the bug**
DataInsights application fails when KPI for entities with description is exist with message:  with "Cannot compute KPI. No results found"
It happens sometimes right after KPI creation, sometimes after several successful runs

**To Reproduce**
- Create KPI with ChartType = 'Percentage of Entities With Description'
- Deploy and run DataInsights.  
- DataInsights Job fails with "Cannot compute KPI. No results found"

<img width="1088" alt="Screenshot 2023-12-21 at 16 24 27" src="https://github.com/open-metadata/OpenMetadata/assets/124048632/e95ba5fa-7eca-4a3c-9346-3dafeee253c9">

**Expected behavior**
DataInsights Job completed successfully

**Version:**
OS: Ubuntu 22.04.2 LTS
Python version: Python 3.10.12
OpenMetadata version: 1.2.2
OpenMetadata Ingestion package version: 1.2.2

**Additional context**

**Comment by harshach** [comment]
@TeddyCr are we able to reproduce this.

**Comment by pmbrull** [comment]
can't reproduce
