### ISSUE TITLE
It is necessary to disallow changing reviewers when creating a term

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#14486]
**Affected module**
backend

**Describe the bug**
Any user can change the reviewers of a term when creating it. Thus, he can appoint himself as a reviewer and add a term without an actual review. If you prohibit changing reviewers for users through policies, then this will affect only terms that have already been created. In the process of creating a term, the user will also have the opportunity to change reviewers.

**To Reproduce**
![term_rewiewers](https://github.com/open-metadata/OpenMetadata/assets/61934044/9714e82b-c5a4-48f2-b1ca-3535ae976673)

**Expected behavior**
When creating a term, the user should not be able to change the reviewers if they are assigned to the dictionary.

**Version:**
 - OpenMetadata version: 1.2.3

**Comment by harshach** [comment]
@chirag-madlani we shouldn't allow the owner / creator of the term to be in reviewers list. Lets fix this in 1.2.4

**Comment by harshach** [comment]
@AlekseevVadim if by "friend" we can argue that the user can also be friends with admin and make lot more changes.
There are use-cases where terms or term group can belong to a team so they may require to change the term reviewers.
All of these are meant to sensible controls. 
One option we can do here is if the parent term has reviewers we add them to the list along with addition of other reviewers by the user who is creating the term
