### ISSUE TITLE
UI: date filter in pipeline execution tab is misaligned on safari browser

### ISSUE THREAD

**Issue by dechoma** [open-metadata/OpenMetadata#14482]
**Affected module**
UI

**Describe the bug**
date filter in the pipeline execution tab is misaligned on safari browser

**To Reproduce**
![Screenshot 2023-12-22 at 09 37 51](https://github.com/open-metadata/OpenMetadata/assets/29060284/07352c17-775a-4527-b65e-4b136ba0efdd)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [master]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani issue still exists, lets fix it in 1.4.0
