### ISSUE TITLE
UI bug？The password box shows what it is in it When I click.

### ISSUE THREAD

**Issue by win-shy** [open-metadata/OpenMetadata#14498]
![462b1f6f47bde67b785d2a176990dca](https://github.com/open-metadata/OpenMetadata/assets/20906584/1563f441-8534-4426-bbcf-13ce51e21d2c)

![df81b06c2a7d3e3394f06889ed14959](https://github.com/open-metadata/OpenMetadata/assets/20906584/94ff1e95-cc33-46ba-aa41-dd6283c1de04)

**Comment by harshach** [comment]
we don't show the passwords for your service. @chirag-madlani lets remove that icon

**Comment by ShailikaS** [comment]
can i pick up this ?

**Comment by chirag-madlani** [comment]
Hi @ShailikaS assigned this to you

**Comment by brueter** [comment]
Is this still up for grabs?

**Comment by chirag-madlani** [comment]
Yes @brueter. You want to work on this?

**Comment by hichem-18** [comment]
Hi, @chirag-madlani  is this still open can I work on it? All do I have to do is remove the icon right?

**Comment by chirag-madlani** [comment]
Hi @hichem-18 
Yes ask here is to change it from Password to Normal input in the form

**Comment by hichem-18** [comment]
Okay can you assign it to me?

**Comment by gabrielrosendo** [comment]
Can I work on this?

**Comment by hichem-18** [comment]
I guess yes because everytime I try to run the project my laptop crushes I don’t know why

**Comment by cortesana** [comment]
Hello, @gabrielrosendo - Have you picked this up or can I take the issue?

**Comment by harshach** [comment]
@chirag-madlani no one making progress here from OSS community.  Lets pick it up and fix it
