### ISSUE TITLE
Assign Owner via UI has bugs

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#14518]
**Affected module**
UI

**Describe the bug**
When typing in Owner field in the UI for specific asset, the letters are in mess and it take like few times to set it right.
(if you type really slow it's working... but typing fast not working)

**To Reproduce**
I wrote 'data' and it catch only the 'ta' 
<img width="363" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/2f87117e-9778-49a7-a9ca-82951b2ec400">

*Also, it might be better to arrange it alphabetically (or by amounts as in the main screen). 

**Expected behavior**
Typing owner fast should work=)

**Version:**
1.3.2

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani this and also in activity feed when you do @ to refer an user/team is not smooth. Lets figure this out and ship it in 1.3.0

**Comment by chirag-madlani** [comment]
This is already fixed [here](https://github.com/open-metadata/OpenMetadata/pull/14495/files#diff-2a59c6eb9ee0e63d6d558d461dd505882c4625808833581fa67254f5cdd8041a) and part of 1.2.4
About '@'  in the feedEditor that will be a separate component so I will raise a different issue for it.
