### ISSUE TITLE
The Metadata versioning is not as expected when the order of the columns in the DDL is different

### ISSUE THREAD

**Issue by YMACHEN** [open-metadata/OpenMetadata#14522]
**Affected module**
Metadata versioning

**Describe the bug**
Dropping the table and then recreating it may lead to column description errors if the order of the columns in the DDL is different between the first and second times.

**To Reproduce**
The first time's DDL
![ddl_v1](https://github.com/open-metadata/OpenMetadata/assets/135201123/183b2b77-fe5f-4061-b40d-b954c41e4073)

Metadata version 0.1
![v1](https://github.com/open-metadata/OpenMetadata/assets/135201123/02b88575-9050-477b-b031-373ef96583ee)

The second time's DDL
![ddl_v2](https://github.com/open-metadata/OpenMetadata/assets/135201123/9075a490-aeb7-4822-9b5d-294fd2866fb0)

Metadata version 0.2
![v2](https://github.com/open-metadata/OpenMetadata/assets/135201123/e6b701ad-5819-4863-87b3-567dc77ccc73)

**Expected behavior**
Expecting version 0.2 not to exist, as the DDL is the same, only the order is different.

**Version:**
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==1.2.3

**Additional context**
Then I used this API to get some details
http://hostname:8585/api/v1/tables/id/versions/0.2
In the 'changeDescription' function, 'oldValue' and 'newValue' are reversed.
![call api](https://github.com/open-metadata/OpenMetadata/assets/135201123/fde279d0-d9f3-489e-ba9c-3da0009ca1f0)

**Comment by harshach** [comment]
@mohityadav766 is this still an issue?
