### ISSUE TITLE
UX improvements based on new mocks

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1453]
Lets start making progress on new UX improvements from @sanketbambulkar

**Comment by harshach** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/38649/143902200-f1bf4fc9-c732-43dd-8dfb-4c1cbb3dcdf0.png">

<img width="263" alt="image" src="https://user-images.githubusercontent.com/38649/143902239-49972078-be0f-4c1a-a607-2d99dd91cba6.png">

**Comment by Sachin-chaurasiya** [comment]
Closing this as we have implemented a new mock for the landing page and explore page.
