### ISSUE TITLE
Use consistent font colours in service connection form 

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#14539]
**Affected module**
UI

**Describe the bug**

The input username and hostport seems like placeholders rather than the actual values, whereas the password fields has a different font color
![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/6852dcb5-1884-442d-8690-6ff4e1b1d076)

**Comment by harsh-vador** [comment]
I will take this up

**Comment by Abhishek332** [comment]
@ulixius9 can you assign it to me.

**Comment by karanh37** [comment]
Fixed with #14551
