### ISSUE TITLE
Issue installing openmetadata-ingestion package

### ISSUE THREAD

**Issue by margot-six** [open-metadata/OpenMetadata#14558]
**Affected module**
Ingestion Framework

**Describe the bug**
We currently use the composer tool (Airflow managed by Google) in version composer-2.5.2-airflow-2.6.3.
When we try to install the openmetadata-ingestion package in version 1.2.3.2 on the pypi library, we have the following error.

We already tried with advices and extra requirements but we have the same issue.

It seemed to be a compatibility problem

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/155529931/7310bb33-fabb-4b08-aa7f-91832e80b75c)

![image](https://github.com/open-metadata/OpenMetadata/assets/155529931/13bdd171-1ec7-4862-b0db-a7bf40fc0fc1)

**Expected behavior**
The package to be installed successfully

**Version:**
 - Python version: 3.8.12
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: 1.2.3.2
 - composer-2.5.2-airflow-2.6.3

**Comment by pmbrull** [comment]
hi, looking into this. I don't see the same error as you posted there, but seeing some other dependency issues that we're trying to fix.

Could you please share the full requirements list you passed to the composer env?

Thanks

**Comment by pmbrull** [comment]
hi @margot-six we're making some changes in the dependencies to make things work with Composer.

We're testing with Composer 2.5.4 and Airflow 2.6.3 (that's the closest we could get to your settings)

We'll see if we can get this fixed for 1.3.

Thanks

**Comment by pmbrull** [comment]
@ulixius9 just to list here the changes we've done:
- Update `collate-sqllineage` to work with `"sqlfluff>=2.1.4,<3"`
- Update `openmetadata-ingestion` to remove the dependency on `typing-extension`

Pending:
- Update `collate-sqllineage` to work with `sqlparse>=0.4.4`

**Comment by pmbrull** [comment]
got it working 
![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/be2c7201-54e6-48a3-9cb5-c5fdaa70e2e1)

**Comment by pmbrull** [comment]
another update: While the environment starts properly, there's a runtime clash between Collate's sqllineage and Composer's sqllineage dependency. We'll need to update a couple of extra things on our end which cannot safely happen before 1.3.

We'll re-test this once again when 1.3.0 is out

**Comment by margot-six** [comment]
Hi, here is our complete configuration if it can help 
![image](https://github.com/open-metadata/OpenMetadata/assets/155529931/ceff2aba-69fa-4105-b963-75546fb54de5)

If necessary, we can try to change the packages version when the fix will be available

**Comment by pmbrull** [comment]
Hi @margot-six  
> If necessary, we can try to change the packages version when the fix will be available
That should be fine. Based on this list, the conflicts we get come from composer itself.

We'll keep working on this and re-test once the 1.3 release is out. Thanks

**Comment by pmbrull** [comment]
![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/d523e6d3-bd71-45d6-8ff3-12552d3d8bfd)

 I just tested it again with the new 1.3.0 release (since we needed to align quite a few dependencies).
Packages are installed properly now and I can extract GCP metadata. You can see the sample here https://sandbox.open-metadata.org/service/pipelineServices/airflow_gcs_composer_260
