### ISSUE TITLE
Tier is not appear on the asset summary on the right

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#14556]
**Is your feature request related to a problem? Please describe.**
When looking on the asset summary in the right, I expect to see the asset 'tier' as part of the summary.

Tier is missing here:

<img width="444" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/65783897-823a-449e-8771-45b84e779453">

**Comment by Sachin-chaurasiya** [comment]
Hello @sapirhi , Thanks for reaching out.

We show the tier info in the card itself, therefore on the summary panel, we do not show the tier, please refer the attached screenshot, thanks!

<img width="1133" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/59080942/1e0edfac-60e1-4f30-8d3f-ee6fa37893df">
