### ISSUE TITLE
Single node deployment in production

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1456]
I was supporting a user who was asking how to deploy OM on a single node in production.
He was following this page of the manual.
https://docs.open-metadata.org/install/run-in-production

I didn't find how to set up MySQL for OM.
```sql
CREATE DATABASE openmetadata_db;
CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
```

And he didn't find how to bootstrap MySQL for OM.
```sh
bootstrap/bootstrap_storage.sh migrate
```

Default passwords are dangerous in production.

**Comment by pmbrull** [comment]
Also, maybe related to documenting & securing the deployment steps, we might need to revisit how to pass the info from `openmetadata.yaml`, as in there we have informed the dbs credentials.

It might be interesting to have together with the single node deployment, a fully AWS deployment taking into consideration that in PROD we should use RDS for MySQL and ElasticSearch separated from the OM instance.

**Comment by pmbrull** [comment]
Actually, a terraform script would be kind of cool and easy to include in any DevOps managed platforms

**Comment by akash-jain-10** [comment]
@pmbrull - We do support configuring OpenMetadata with Helm Charts. Here is the link for docs - https://docs.open-metadata.org/install/run-in-kubernetes

This is our first step towards support for deployments to any cloud platform via kubernetes.
Let me know if this is what you are looking for ?

**Comment by akash-jain-10** [comment]
> I was supporting a user who was asking how to deploy OM on a single node in production. He was following this page of the manual. https://docs.open-metadata.org/install/run-in-production
> 
> I didn't find how to set up MySQL for OM.
> 
> ```sql
> CREATE DATABASE openmetadata_db;
> CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
> GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
> ```
> 
> And he didn't find how to bootstrap MySQL for OM.
> 
> ```shell
> bootstrap/bootstrap_storage.sh migrate
> ```
> 
> Default passwords are dangerous in production.

@amiorin - Is this what you were looking for ? 
https://docs.open-metadata.org/v/open-metadata/install/run-openmetadata#install-on-your-local-machine

**Comment by amiorin** [comment]
@akash-jain-10 
I guess that page would have been helpful to our user.
