### ISSUE TITLE
Container: The breadcrumb is not getting updated

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14560]
The breadcrumb is not getting updated as we navigate through the hierarchy of container service.
@open-metadata/ui  needs to check how we are sending values for creating breadcrumb

steps to reproduce:
Go back and forth different levels of hierarchy in containers and click on breadcrumbs to go back.
https://sandbox-beta.open-metadata.org/container/s3_storage_sample.deep_nested_container_1

https://github.com/open-metadata/OpenMetadata/assets/40225091/3ae9b65b-479c-4180-8553-dcc823bbbd58

**Comment by Abhishek332** [comment]
@chirag-madlani Can I get assign this issue

**Comment by Sachin-chaurasiya** [comment]
> @chirag-madlani Can I get assign this issue

Assiged to you @Abhishek332
