### ISSUE TITLE
Ingestion - missing docs information for airflow

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#14590]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**

In case airflow is not available we should put more information about what can be done as the next step to fix it.
Either doc links or a support link will be much helpful here

**To Reproduce**

Screenshots or steps to reproduce

![image](https://github.com/open-metadata/OpenMetadata/assets/12962843/b6302055-fde8-4982-b87c-aeedb8bbaada)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
https://docs.open-metadata.org/v1.2.x/deployment/ingestion/openmetadata
