### ISSUE TITLE
CustomOIDC auth provider docs does not describe where to put CLIENT_SECRET

### ISSUE THREAD

**Issue by hsnprsd** [open-metadata/OpenMetadata#14602]
**Is some content missing, wrong or not clear?**
CustomOIDC auth provider docs does not describe where to put CLIENT_SECRET

**Describe the solution you'd like**

**Additional context**

**Comment by hsnprsd** [comment]
I think the helm chart does not support it too but I'm not sure.

**Comment by harshach** [comment]
@akash-jain-10 @ayush-shah can you double check this

**Comment by akash-jain-10** [comment]
Hello @hsnprsd . Generally, we do not require a client secret to configure SSO for customOIDC auth provider configuration.
You should be able set up SSO using the following docs section - https://docs.open-metadata.org/v1.2.x/deployment/security/custom-oidc

Closing the ticket! Thanks.
