### ISSUE TITLE
Fine-grained profiling

### ISSUE THREAD

**Issue by hsnprsd** [open-metadata/OpenMetadata#14603]
**Is your feature request related to a problem? Please describe.**
There should be a way to limit the scope of the profiling done (eg. do not collect column statistics, only collect sample data).

**Describe the solution you'd like**
In the ingestion job creation form in the UI there should be checkboxes for different types of profiling where you can disable/enable them as you like.

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
this is shipped 
<img width="950" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/6a732a3c-c5fc-4cfa-8077-4a3ec0ebdadb">
 You can disable profiler and or sampling
