### ISSUE TITLE
IBM Db2 ingestion 

### ISSUE THREAD

**Issue by elguero6** [open-metadata/OpenMetadata#14627]
**Affected module**
Ingestion Framework

**Describe the bug**
When the DB2 Profiler Ingestion runs this error shows in the logs :
String data right truncation. SQLSTATE=22001 SQLCODE=-99999
I believe the columnNames parameter is too long, if I run the query in a Database Client, it will run fine with fewer characters in the parameter

**To Reproduce**

Create a IBM DB2 Connection, run the profiler ingestion.

**Expected behavior**

sqlalchemy.exc.DataError: (ibm_db_dbi.DataError) ibm_db_dbi::DataError: Statement Execute Failed: [IBM][CLI Driver] CLI0109E  String data right truncation. SQLSTATE=22001 SQLCODE=-99999
[SQL: /* {"app": "OpenMetadata", "version": "1.2.3.2"} */
SELECT count(*) AS "rowCount", CAST(? AS BIGINT) AS "columnCount", CAST(? AS VARCHAR) AS "columnNames" 
FROM example_Schema.example_table FETCH FIRST 1 ROWS ONLY]

**Version:**
 - OS: Kubernetes
 - Python version:3.9
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: 1.2.3

**Additional context**

**Comment by ayush-shah** [comment]
Hello @elguero6 will take a look on the issue, you can track the progress here itself.
You can check the project part to see which release it will be a part of

**Comment by TeddyCr** [comment]
@elguero6 how many columns does your table have? The `columnNames` parameter will be replaced by a string of all your column (comma separated). We might need to specify a greater `VARCHAR ` length.

**Comment by elguero6** [comment]
Yea can be numerous, 20-50 column table
