### ISSUE TITLE
Support lineage ingestion for Oracle Stored Procedures

### ISSUE THREAD

**Issue by chuqbach** [open-metadata/OpenMetadata#14630]
**Is your feature request related to a problem? Please describe.**
We're using stored procedures heavily on our Oracle Data Warehouse for our ETL processes. Current Open Metadata version only support ingesting lineage from Oracle's View, so our logic/lineage in the Stored Procedure are not ingested and displayed. Therefore, if Open Metadata can support this feature, it will be really helpful to us (and other user working in Finance, Banking, Insurance industry, where Oracle Stored Procedure are used mainly).

**Describe the solution you'd like**
Open Metadata to ingest Stored Procedures on Oracle database and show a lineage between tables (or even column level) based on the Stored Procedure logic.

**Comment by NiharDoshi99** [comment]
Hi, I am working on this issue.

**Comment by nqvuong1998** [comment]
Hi @NiharDoshi99 , Does Oracle Store Procedures support Table Lineage?

**Comment by ayush-shah** [comment]
Yes @nqvuong1998 it does support table lineage, parsing the stored procedure and creating a lineage out of it.
