### ISSUE TITLE
Incorrect Superset chart link

### ISSUE THREAD

**Issue by artemklevtsov** [open-metadata/OpenMetadata#14647]
**Affected module**
Ingestion Framework

**Describe the bug**
Incorrect chart link: missing **superset** path part.

**To Reproduce**

Go to Dashboards > Superset > Dashboard > Click to chart link.

**Expected behavior**
Now is <http://localhost:8088/explore/?slice_id=1359>.

Should be <http://localhost:8088/superset/explore/?slice_id=1359>

**Version:**
 - OpenMetadata version: 1.2.2
- Superset 2.0.1

**Additional context**
Chart link formed here:
https://github.com/open-metadata/OpenMetadata/blob/1.2.4-release/ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py#L167

Link to dashoboard is correct: https://github.com/open-metadata/OpenMetadata/blob/1.2.4-release/ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py#L112

**Comment by harshach** [comment]
@OnkarVO7 is this still an issue

**Comment by OnkarVO7** [comment]
Hi @artemklevtsov we tried this with our superset instance the formed redirects correctly to the required chart on the superset instance. Can you please share if you are seeing any specific error here?

**Comment by OnkarVO7** [comment]
Closing the issue due to inactivity. Checked with our instance the url gets formed correctly
