### ISSUE TITLE
Dolphin Schedule support

### ISSUE THREAD

**Issue by niyanchun** [open-metadata/OpenMetadata#14648]
As [Apache DolphinScheduler](https://dolphinscheduler.apache.org/) is a famous schedule project, does open metadata has a plan  to support?

**Comment by codegit10001** [comment]
There is a Dolphinscheduler cluster in our production environment, which I hope can be used directly without deploying Airflow. 
so I have a question: When is Dolphinscheduler supported? Or which version supports dolphinscheduler?

**Comment by MRYOG** [comment]
+1

**Comment by juaby** [comment]
+1

**Comment by huxiaolongyin** [comment]
+1

**Comment by shine4net** [comment]
+1

**Comment by ziya05** [comment]
+1

**Comment by JarodLMN** [comment]
+1

**Comment by harshach** [comment]
@JarodLMN @ziya05 if you all have time to contribute please let us know we are happy to assist. Other than that we don't have any plans to add yet another scheduler support.

**Comment by Holoskevych** [comment]
+1

**Comment by xi4ngxin** [comment]
+1

**Comment by darrkz** [comment]
+1
