### ISSUE TITLE
Can you provide a administrator's function to disable site registration?

### ISSUE THREAD

**Issue by wuwuwuuw** [open-metadata/OpenMetadata#14678]
**Is your feature request related to a problem? Please describe.**
Yes, in the actual use scenario, we need this function

**Describe the solution you'd like**
In the administrator setting interface, provide a function disable/opening site registration function

**Describe alternatives you've considered**
Provide a CheckButton option, the manager can manually control the display and hiding of the registration function of the login page

**Additional context**

**Comment by harshach** [comment]
@wuwuwuuw you can control this via config https://github.com/open-metadata/OpenMetadata/blob/99b8e7988db03ecdb37e6f860d842054e0973fd4/conf/openmetadata.yaml#L168

**Comment by wuwuwuuw** [comment]
I get it，thank you for your reply
