### ISSUE TITLE
Set default PR merging to Squash

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1468]
It might be possible to update the repo settings to have the Squash merge for PR by default.

I think that some merges have not been done with that and it breaks the unity of the master commits.

Thanks!

**Comment by akash-jain-10** [comment]
We already have this configuration. Let me know if we are missing anything ?
![image](https://user-images.githubusercontent.com/15995028/144015209-7722a333-19c3-4462-8d33-5be7c6fb53ba.png)

**Comment by pmbrull** [comment]
Oh great, I see it as default now as well. A few days ago we needed to manually fetch the proper option, which could lead to having the wrong merge strategy.

Let's close this then.

Thanks!
