### ISSUE TITLE
Ingestion: Airflow 2.5.1 SourceUrl, throws 404

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14683]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion
**Describe the bug**
Airflow SourceUrl for airflow 2.5.1 is different, throws 404 with current implementation

Actual
https://xxxxxx.airflow.amazonaws.com/home/tree?dag_id=pipeline__analytics__claim_transactions
Expected
https://xxxxxx.airflow.amazonaws.com/dags/pipeline__analytics__claim_transactions/grid

OM version: 1.2.3
https://openmetadata.slack.com/archives/C02B6955S4S/p1704944260291739

**Comment by 17rahulsharma** [comment]
thank you

**Comment by harshach** [comment]
It looks like AWS is doing its own instead of using the OpenSource Airflow URL format.
The issue here is we are using Airflow connector and we are forming the URLs based on their Airflow UI link format

**Comment by 17rahulsharma** [comment]
hi team, I tested with version 1.3.0 (after upgrade) however issue remain same with version 1.3.0

**Comment by aakashg7** [comment]
> hi team, I tested with version 1.3.0 (after upgrade) however issue remain same with version 1.3.0

i am also facing the same
