### ISSUE TITLE
The latest version 1.2.4 The application of docker mirror deployment still has the same problem. may I ask if this is normal?

### ISSUE THREAD

**Issue by wuwuwuuw** [open-metadata/OpenMetadata#14697]
**Affected module**
Ingestion

**Describe the bug**
Minor: Fix casing in MSSQL test connection query #14412
[https://github.com/open-metadata/OpenMetadata/pull/14412/files#diff-4df4b9bbaca3d3a39647692c2fd03a8ae97825a4790726a014bf9ff28ce9c5f9](url)

**Version:**
 1.2.4 docker image

**Comment by pmbrull** [comment]
hi @wuwuwuuw, thanks for reaching out.

The fix was merged and will be there in 1.3. We missed cherry-picking it in 1.3.

Once 1.3 is out, feel free to reopen the original issue if it's still there.

Thanks
