### ISSUE TITLE
Statistics of the percentage of descriptions and tags inserted for each part of the databases

### ISSUE THREAD

**Issue by alitehranim** [open-metadata/OpenMetadata#14706]
Greetings and Regards
Please advise if there is a section through which you can get the statistics of the descriptions and tags entered for each part of the databases. This case has many applications regarding the completion of metadata by different parts of an organization and control It facilitates it.
thanks a lot.

**Comment by harshach** [comment]
@alitehranim please do not open github tickets as bugs. Please join httsp://slack.open-metadata.org and confirm if its indeed an issue.
look at the docs for your question https://docs.open-metadata.org/v1.2.x/how-to-guides/data-insights
