### ISSUE TITLE
alert test case redirects to a non existing web page

### ISSUE THREAD

**Issue by cristianodicrescenzo** [open-metadata/OpenMetadata#14713]
**Affected module**
UI, backend

**Describe the bug**
The alert contains a URL for the test case and the URL redirects to a non-existing webpage

**To Reproduce**

- create a test case
- create an alert for the test case (slack or mail is the same)
- click on the URL inside the alert

**Expected behavior**
the link should redirect to the test case page

**Version:**
 - OS: ubuntu
 - Python version: 3.9
 - OpenMetadata version: 2.4.1
 - OpenMetadata Ingestion package version: Docker installation

**Additional context**

**Comment by mohityadav766** [comment]
Fixed in 1.3.0
