### ISSUE TITLE
DELETE Glossary on UI Didn't delete Related Glossary-Term Documents on Elasticsearch.  

### ISSUE THREAD

**Issue by kenyyh** [open-metadata/OpenMetadata#14719]
**Affected module**
UI, bankend

**Describe the bug**
Delete Glossary on UI will delete the metadata of both Glossary and Glossary-Terms store in PostgreSQL but didn’t delete the related Glossary-Terms store in Elasticsearch.  

When trying to add Glossary on Database Table will find out that some Glossary-Terms Does not exists and pop out error message “glossaryTerm instance for XXXX.XXXX not found” (Which use Elasticsearch to search list but the metadata store in Postgres had already deleted)

If we delete the Glossary-Terms rather than delete Glossary, the behavior will be normal.   

**To Reproduce**
1. Create A Glossary.  
2. Create Glossary-Terms
3. DELETE Glossary
4. Check the document store in elasticsearch. ( glossary_search_index ) The Glossary-Terms which should be deleted will still exists 

**Expected behavior**
Delete Glossary will delete related Glossary-Terms which store in Elasticsearch.

**Version:**
 - OS: Alpine Linux v3.18 (Docker)
 - Python version: Python 3.9.17
 - OpenMetadata version: 1.2.4
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==1.2.4

**Additional context**

**Comment by harshach** [comment]
Fixed in main, will be part of 1.3.0
