### ISSUE TITLE
Glossary description edit bug

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#14729]
**Affected module**
UI

**Describe the bug**
We have a condition that only owner can edit its assets.
The 'edit' button for tables for example is available only for owners.

In glossary term, the edit button available for all, and if 'not an owner' press it, he can edit the description, press save, and then nothing is changed in the UI.

It's very strange behavior for the users. 

**Expected behavior**
Only owner can see the edit sign. 

**Version:**
1.2.3

**Comment by Sachin-chaurasiya** [comment]
Hello @sapirhi, thanks for reporting the issue, this issue has been fixed in `1.2.4`, so please upgrade to `1.2.4`,.
