### ISSUE TITLE
 Ingestion-bot changge jwt,ingestion cann't work normally

### ISSUE THREAD

**Issue by TristingChen** [open-metadata/OpenMetadata#14720]
**Affected module**
UI, backend or Ingestion

**Describe the bug**
  I changed Ingestion-bot's jwt, in Ui, then  ingestion access OpenMetadata -service some api wrong ,like this "GET /api/v1/services/databaseServices/name/test1 HTTP/1.1" 401 54 "-" "python-requests/2.31.0" 9

how to change ingestion‘s jwt 

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
I want to know how to config "ingestion" accessing "OpenMetadata -service" jwt and some useful docs;

**Version:**
 - OS: [e.g. iOS]  docker and windows10
 - Python version: 1.2.3.2
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: OpenMetadata run in windows10;Ingestion  in docker

**Additional context**

**Comment by sureshms** [comment]
For questions and to discuss issues, please use https://slack.open-metadata.org. Create an issue only when it is confirmed.
