### ISSUE TITLE
users don't receive notifications

### ISSUE THREAD

**Issue by cristianodicrescenzo** [open-metadata/OpenMetadata#14730]
**Affected module**
UI, backend

**Describe the bug**
Once a user is tagged in a conversation, there is no notification of such tag

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Ubuntu
 - Python 3.9:
 - OpenMetadata version 2.4.1
 - OpenMetadata Ingestion package version 2.4.1: Docker installation

**Additional context**

**Comment by harshach** [comment]
Fixed in 1.3.1
