### ISSUE TITLE
Table count aggregation

### ISSUE THREAD

**Issue by k3agan** [open-metadata/OpenMetadata#14741]
**Affected module**
Count of database tables

**Describe the bug**
There is a mismatch between the table count in the explore page and the detailed view of a given database. 

(Below is what we see on the search filter in explore page. But the actual database has only around 1150 tables.)

**To Reproduce**
OM version: 1.2.3
Database: SQL Server
DB Version: SQL Server 2019

Slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1705433126404849

![image](https://github.com/open-metadata/OpenMetadata/assets/56366381/09ab1991-8d73-4489-b2bd-244618b55446)
![image](https://github.com/open-metadata/OpenMetadata/assets/56366381/416ef8a1-0e90-4de5-bb89-468fdf1721b4)
![image](https://github.com/open-metadata/OpenMetadata/assets/56366381/863b85e0-a2eb-4d1f-82fc-d412e0cb06fe)

**Expected behavior**
Table counts should be consistent. (explore page maybe doing some double counting)

**Version:**
 - OS: linux docker
 - Python version:
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: 1.2.3

**Additional context**

cc: @harshach

**Comment by harshach** [comment]
Fixed in 1.3.1
