### ISSUE TITLE
SqlFluff does not perform as expected for [tsql]

### ISSUE THREAD

**Issue by jordanjeremy** [open-metadata/OpenMetadata#14744]
**Affected module**
Ingestion

**Describe the bug**
When metadata ingestion is run for AzureSQL/MSSQL database with debug logging enabled, the logs show the message:
```
{parser.py:426} DEBUG - Lineage computed with SqlFluff did not perform as expected for the [tsql] query: [CREATE VIEW [dbo].[client_product]
AS
SELECT [client].[client_name], [product].[product_name]
FROM [dbo].[client]
LEFT JOIN [dbo].[product] ON [client].[id] = [product].[client_id]]
```
Looking at the resulting lineage in the UI shows the tables used in the view but doesn't include any column level lineage.

**To Reproduce**
1. Run the current docker image.
2. Add patch https://github.com/open-metadata/OpenMetadata/commit/d197164125e29b0452cbb8199ea0a609a3c7263a (so AzureSQL uses tsql as the dialect).
3. Run metadata ingestion on any view from AzureSQL db.

**Expected behavior**
Column level lineage is listed as supported in the AzureSQL connector documentation and should be capturable from a simple view.

**Version:**
 - OS: linux docker
 - OpenMetadata version: 1.2.4

**Additional context**
Issue seems to be related to failure to get any column lineage with SqlFluff.
```
from sqllineage.runner import LineageRunner
query = "CREATE VIEW [dbo].[client_product]\nAS\nSELECT [client].[client_name], [product].[product_name]\nFROM [dbo].[client]\nLEFT JOIN [dbo].[product] ON [client].[id] = [product].[client_id]"
lr = LineageRunner(query, dialect="tsql")
lr.get_column_lineage()
```

**Comment by vladm** [comment]
I'm curious why was it marked as completed?
