### ISSUE TITLE
When ingesting metadata from Airflow, execution data is not ingested.

### ISSUE THREAD

**Issue by marcorezende** [open-metadata/OpenMetadata#14742]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Impact the Ingestion Framework

**Describe the bug**

When i try to import metadata from Airflow, i receive this message of error:

![image](https://github.com/open-metadata/OpenMetadata/assets/99234384/ccac8968-2445-4bea-ab08-fc192094399c)

_psycopg2.ProgrammingError: can't adapt type 'AirflowTaskStatus'_

The pipeline is created:

![image](https://github.com/open-metadata/OpenMetadata/assets/99234384/44054e27-691e-4dc4-8486-126e08037a2c)

but without data about execution:

![image](https://github.com/open-metadata/OpenMetadata/assets/99234384/01aa32a7-dcb0-4d77-aba0-1211aaa9bf25)

**To Reproduce**

Screenshots or steps to reproduce
1 - YAML configuration file to ingest metada from Airflow

![image](https://github.com/open-metadata/OpenMetadata/assets/99234384/66516a4f-39ad-4d81-9498-a47057b6efee)

2 - Python script to execute the ingestion

![image](https://github.com/open-metadata/OpenMetadata/assets/99234384/b24fe282-9fcf-47ff-83a8-e01dfcd805d8)

**Expected behavior**
Ingest data from execution.

**Version:**
 - OS:
 - Python version: 3.10
 - OpenMetadata version: [1.2.4]
 - OpenMetadata Ingestion package version: [`openmetadata-ingestion[airflow, databricks, postgres]==1.2.4`]

**Additional context**

**Comment by pmbrull** [comment]
hi @marcorezende , thanks for raising and wanting to contribute. Assigned the issue to you

**Comment by pmbrull** [comment]
hi @marcorezende let us know when you're able to pop a PR :) Looking forward to your first contribution

**Comment by marcorezende** [comment]
Hi @pmbrull, thanks for asking, i going to create the PR today :)

**Comment by marcorezende** [comment]
#14884
