### ISSUE TITLE
Changing the SQL Init Script Makes the Migrations break on existing databases.

### ISSUE THREAD

**Issue by abrisan** [open-metadata/OpenMetadata#1475]
I am trying out the 0.7.0 snapshot of openmetadata, and am getting the following error on an existing database:

```
openmetadata_1         | "migrate" option failed : org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
openmetadata_1         | Migration checksum mismatch for migration version 001
openmetadata_1         | -> Applied to database : 2102739689
openmetadata_1         | -> Resolved locally    : -723630632. Either revert the changes to the migration, or run repair to update the schema history.
openmetadata_1         | Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
```

I believe this is because when migrations are applied to the database, the file has been edited, rather than creating a new migration. Can someone please confirm or point me to a solution?

Thanks

**Comment by harshach** [comment]
@abrisan Yes we haven't yet supported migrations in db schema. we will doing that from next release. For now please do drop-create
