### ISSUE TITLE
Backend FR: Authentication for code flow using Confidential Access Type

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14766]
Currently we authenticate users via UI and auth access type being Public.
In Custom OIDC, if the user has some mandate on using the `Confidential` type, OM doesn't support it as of now, based on the same, this issue is created.

Confidential type needs additional requirement of `client secret` and for some `code-verifier`, this will be handled from the Backend as opposed to UI ( Public access type - current one )

All the communication will be done by the backend.

**Comment by chirag-madlani** [comment]
Supported with 1.3.2
