### ISSUE TITLE
Explore UI is not showing correct count and pagination v/s API results

### ISSUE THREAD

**Issue by rkothariauto** [open-metadata/OpenMetadata#14763]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
During searching for specific table, found that API results return 4 but Explore UI shows 41 as count and multiple pagination. 

**To Reproduce**

Screenshots or steps to reproduce
Attached is screenshot & API calls file
![openmetadata_source_bug](https://github.com/open-metadata/OpenMetadata/assets/104001915/96150a1e-b04e-4671-946e-f85bb2b8638f)
[omd_api_calls.txt](https://github.com/open-metadata/OpenMetadata/files/13963428/omd_api_calls.txt)
 file 

**Expected behavior**
Explore UI count should match with API calls result

**Version:**
 - OS: [e.g. iOS]  Kubernates POD through Helm chart version 1.2.7( https://artifacthub.io/packages/helm/open-metadata/openmetadata/1.2.7)
 - OpenMetadata version: [e.g. 0.8] 1.2.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
we need more details here. What version of OpenSearch or ElasticSearch and are they using multi-node cluster etc..

**Comment by rkothariauto** [comment]
Hi @harshach , We are using elasticsearch:8.7.1 and not using multi node cluster

**Comment by harshach** [comment]
This is fixed in 1.3.0
