### ISSUE TITLE
Profiler - Athena metric computation error with injected projected partitions

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#14765]
**Affected module**
Profiler

Might be based on https://docs.aws.amazon.com/athena/latest/ug/partition-projection-dynamic-id-partitioning.html

**Describe the bug**
```
 Injected projected partition column date_time must have only (and at least one) equality conditions in the WHERE clause!
[SQL: /* {"app": "OpenMetadata", "version": "1.2.2.0"} */
SELECT avg(LENGTH(country)) AS mean, count(country) AS "valuesCount", count(DISTINCT country) AS "distinctCount", MIN(LENGTH(country)) AS min, MAX(LENGTH(country)) AS max, SUM(CAST(CASE WHEN (country IS NULL) THEN %(param_1)s ELSE %(param_2)s END AS BIGINT)) AS "nullCount", STDDEV_POP(LENGTH(country)) AS stddev, SUM(CAST(LENGTH(country) AS BIGINT)) AS sum 
FROM XYZ LIMIT %(param_3)s]
[parameters: {'param_1': 1, 'param_2': 0, 'param_3': 1}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
It looks like we need to add a default partition key for these kind of table -- similar to what we do with BigQuery.

**Comment by pmbrull** [comment]
> It looks like we need to add a default partition key for these kind of table -- similar to what we do with BigQuery.

yup, we might need to pick this info during the ingestion as well which I don't think we're doing now
