### ISSUE TITLE
SELF_SIGNUP setting doesn't work for LDAP authentication provider

### ISSUE THREAD

**Issue by thiagopirex** [open-metadata/OpenMetadata#14802]
**Affected module**
impact the UI

**Describe the bug**
The authenticate page shows the option "Create Account" when using ldap provider. 
For the setting AUTHENTICATION_PROVIDER , when using basic value, this works fine. But if it's ldap, it's doesn't work as expected

**To Reproduce**

1.  change the AUTHENTICATION_PROVIDER config to ldap
2. change the AUTHENTICATION_ENABLE_SELF_SIGNUP to false
3.  open the main page (like image attachment)

**Expected behavior**
When setting the AUTHENTICATION_ENABLE_SELF_SIGNUP to false, it's expect that the user can't sign in creating new user because the account must exist in LDAP provider.

**Version:**
 - OS: AlmaLinux 9.2 using docker image openmetadata/server:1.2.4
 - Python version:
 - OpenMetadata version: 1.2.4
 - OpenMetadata Ingestion package version: not used

![image](https://github.com/open-metadata/OpenMetadata/assets/430234/7b6b4cef-70cb-45ca-8b6b-09a10b80b9fd)

**Comment by metalshanked** [comment]
Thanks same issue!
