### ISSUE TITLE
empty string cant be matched as a null value

### ISSUE THREAD

**Issue by Ianzhii** [open-metadata/OpenMetadata#14812]
**Affected module**
Data Quaalty
**Describe the bug**
on the ui, add a column quality test which test type choose 'column values missing count'. empty string such as '', '      ' cant  be match

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/19724748/274feaa6-dac9-44e4-acda-396632845e52)
![image](https://github.com/open-metadata/OpenMetadata/assets/19724748/fc7bf3cd-4c40-47e6-b78d-21c5db57e351)
![image](https://github.com/open-metadata/OpenMetadata/assets/19724748/8f50cb64-d564-4435-80e8-7ac49fdfe075)

**Expected behavior**
as the description shows 'By default match all null and empty values to be missing. ', '' or '    ' should be matched as empty values
**Version:**
 - OS: [e.g. centos7.9]
 - Python version:3.8.5
 - OpenMetadata version: [e.g. 1.2.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
This is [the test](https://docs.open-metadata.org/v1.3.x/connectors/ingestion/workflows/data-quality/tests#column-values-missing-count-to-be-equal) to check if setting `""` validate empty string
