### ISSUE TITLE
AWS machine credentials not being used during ingestion

### ISSUE THREAD

**Issue by karim-soufi** [open-metadata/OpenMetadata#14831]
**Affected module**
Ingestion Framework

**Describe the bug**
AWS machine credentials are not being used during ingestion.
`Unexpected exception to yield s3 object: Unable to locate credentials`

**To Reproduce**

![image (7)](https://github.com/open-metadata/OpenMetadata/assets/12132020/9ecca47c-0aec-4b0e-a127-4e6441ac14e9)
![image (6)](https://github.com/open-metadata/OpenMetadata/assets/12132020/1b9e4bac-945b-45db-8de3-cfaafb8abd3e)

**Expected behavior**
Ingestion should use the AWS machine credentials (IAM role) when no secret key or id are supplied and profile name remains default.

**Version:**
 - Python version: 3.10
 - OpenMetadata version: 1.2.2
 - OpenMetadata Ingestion package version: 1.2.2

**Comment by ayush-shah** [comment]
ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1705597943687999

**Comment by ayush-shah** [comment]
```
    def get_client(self, service_name: str) -> Any:
        # initialize the client depending on the AWSCredentials passed
        if self.config is not None:
            logger.info(f"Getting AWS client for service [{service_name}]")
            session = self.create_session()
            if self.config.endPointURL is not None:
                return session.client(
                    service_name=service_name, endpoint_url=self.config.endPointURL
                )
            return session.client(service_name=service_name)

        logger.info(f"Getting AWS default client for service [{service_name}]")
        # initialized with the credentials loaded from running machine
        return boto3.client(service_name=service_name)
```

If no configuration is provided (self.config is None), it gets the default client for the specified AWS service using boto3.client(service_name=service_name). This will use the credentials loaded from the running machine, which includes the default profile. but the awsRegion is mandatory, where there are no chances of the config being None.
