### ISSUE TITLE
Update majorVersionChange scope

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1485]
Do you think it would make sense to add the `majorVersionChange` flag as part of the `recordChange` workflow rather than having it as a global var in the `EntityUpdater`?

I am working on having custom minor/major changes in `MlModel` and having `majorVersionChange = true;` in the `entitySpecificUpdate` is giving me some issues, as I think the value gets changed globally in the updater and all tests are retuning `MAJOR` now.

Based on the [Table Repository](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java#L766), I am trying to have something way simpler for the `MlModel`, as there is no need for validation:

```
// This is called in entitySpecificUpdate
private void updateAlgorithm(MlModel origModel, MlModel updatedModel) throws JsonProcessingException {
      majorVersionChange = true;
      recordChange("algorithm", origModel.getAlgorithm(), updatedModel.getAlgorithm());
    }
```

However, now all `PUT` tests are giving version `1.1`. I was wondering about updating the `recordChanges` method to allow the `majorVersionChange` flag as an argument so that the logic flow happens atomically for each update.

Happy to hear your thoughts on this! Sorry I am missing something 🙏 

Thanks!

**Comment by harshach** [comment]
cc @sureshms

**Comment by sureshms** [comment]
@pmbrull, every time updateAlgorithm is called, you are setting `majorVersionChange` to true, irrespective of it has changed.

The following code will ensure only when algorithm is changed, you are setting `majorVersionChange` to true.
```
if (recordChange("algorithm", origModel.getAlgorithm(), updatedModel.getAlgorithm())) {
  majorVersionChange = true;
}
```

Note that major version will change when algorithm goes from null to new value, a value to null, and when the value is changed. See if this is the right behavior.

**Comment by pmbrull** [comment]
Thanks, @sureshms, you are totally right. Even when nothing changes, we are always going to `updateAlgorithm` from the `updater`. Completely missed that, thanks for the info.

I'll change this as you suggested, as it is the right behavior.

As always, many thanks 🙏
