### ISSUE TITLE
Glossary term list default page

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#14872]
**Is your feature request related to a problem? Please describe.**
When I want to review the glossary term, I want to see it fast and easy. And I see all the hierarchy opened in the default.

**Describe the solution you'd like**
In the main screen, I want to see the first hierarchy, and then drill down on my demand. 
Looks like by default it should present 'collapse' and not 'expand' 

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/87426120/cd4b63f6-bdaa-41d7-907b-4fe261843509)
<img width="261" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/dc2c0803-b934-4fc7-b1df-4a1953932680">

**Comment by harshach** [comment]
Fixed in 1.4.0, all terms collpased by default and users can expand as they seem fit
