### ISSUE TITLE
Dag not found in DagModel

### ISSUE THREAD

**Issue by Nemeczek** [open-metadata/OpenMetadata#14883]
**Affected module**
Backend.

**Describe the bug**
The OpenMetadata server sucessfuly deploys new ingestion. 

```
❯ kubectl exec -it airflow-cluster-web-848765c7b6-gckkc -- ls dags
Defaulted container "airflow-web" out of: airflow-web, check-db (init), wait-for-db-migrations (init)
__pycache__                     airflow_metadata_to_es.py
airflow_docker_operator.py      airflow_sample_data.py
airflow_lineage_example.py      airflow_sample_usage.py
airflow_lineage_operator.py     ommm_metadata_IekFMWPA.json
airflow_metadata_extraction.py  ommm_metadata_IekFMWPA.py
```

But on execution:

```
 File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api/common/trigger_dag.py", line 119, in trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found in DagModel")
airflow.exceptions.DagNotFound: Dag id ommm_metadata_IekFMWPA not found in DagModel
```
Also if I go to the Airflow UI - clearly there is no DAG created. But files are there. 

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
DAG run should work and DAG should be present in Airflow and it's DB.

**Version:**
 - Windows 11 with WSL
 - OpenMetadata chart version 1.2.8
 - Airflow chart 8.8.0

**Additional context**
Postgres and Elastic search are hosted in Azure. The k8s is currently on my local machine. We want to go to production on AKS.

**Comment by pmbrull** [comment]
hi @Nemeczek, thanks for reaching out. However, this looks like a configuration issue to me.

Please use the community slack https://slack.open-metadata.org/ to ask these kinds of questions so that we can get more info about your deployment.

Thanks
