### ISSUE TITLE
Deltalake without metastore

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#14885]
we currently use pyspark w/ delta support to connect to an external metastore and extract metadata about the delta tables.

We could expand the support to fetch tables directly from S3. In that case, we could rely on https://pypi.org/project/deltalake/.

Moreover, we should double-check how we are listing & filtering tables in the connector to only fetch delta tables

**Comment by harshach** [comment]
@pmbrull lets assign this to someone in the team
