### ISSUE TITLE
Database Service\Ingestions Pagination Listing Issue.

### ISSUE THREAD

**Issue by tonsumawang** [open-metadata/OpenMetadata#14888]
**Affected module**
In my opinion, it might be a UI layer issue.

**Describe the bug**
Reporting a bug under Database Service\Ingestions, issue on pagination, the page is not refreshing to list all 17 ingestions even if you  change the # of items per page to 25 or 50.

**To Reproduce**
Create more than 10 ingestions in a Database Service
![image](https://github.com/open-metadata/OpenMetadata/assets/134579809/a263de45-d75a-4849-bdde-643ab614414e)

**Expected behavior**
It should list down the ingestions items based on the selected # of items per page.

**Version:**
 - OS: AWS EKS
 - Python version:
 - OpenMetadata version: 1.2.4
 - OpenMetadata Ingestion package version: 1.2.4 in AWS EKS

**Additional context**
Please see the attached screenshot.

**Comment by chirag-madlani** [comment]
Fixed with 1.3.0
