### ISSUE TITLE
Developer-focused quick start guide to developing in OpenMetadata.  

### ISSUE THREAD

**Issue by ksivam** [open-metadata/OpenMetadata#1488]
Convert the below conversation thread into a Developer-focused document.

https://openmetadata.slack.com/archives/C02AZGN0WKY/p1638295939177500

**Comment by shannonbradshaw** [comment]
@ksivam thanks for taking this.

**Comment by amiorin** [comment]
Looking forward to it.

**Comment by ksivam** [comment]
I will get the first draft out for review by Dec3rd.

**Comment by harshach** [comment]
@ksivam That will be great. Thank you

**Comment by ksivam** [comment]
PR here https://github.com/open-metadata/OpenMetadata/pull/1532
