### ISSUE TITLE
The NEXT button or objects/page dropdown is not working at My Data table of user page at OM UI

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#14944]
**Affected module**
Impact at UI

**Describe the bug**
The NEXT button and Objects/PAGE dropdown at My Dara tab of any user profile page is not working or not clickable

**To Reproduce**
Go to Any User profile --> My Data  --> bottom of the page 

or at sandbox please use use https://sandbox.open-metadata.org/users/harsha/mydata

![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/e617e3c4-75b1-4634-9418-cd775b69a4c3)

**Expected behavior**
Next button and dropdown to select number of objects per page should be clickable

**Version:**
 - OpenMetadata version: 1.2.3

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hello @17rahulsharma , thanks for reporting the issue, this has been fixed and will be part of the 1.3 release.


https://github.com/open-metadata/OpenMetadata/assets/59080942/155ac3e5-43b5-4380-93c9-1741996ce58d

**Comment by 17rahulsharma** [comment]
thanks, it is fixed I tested on upgraded version
