### ISSUE TITLE
Filtering and sorting of data quality tests & suites at Data Quality page

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#14941]
**Is your feature request related to a problem? Please describe.**
The data quality module (page) at OM does not allow sorting of filtering of data quality tests, suites
![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/6affe49b-96b2-4037-bff0-1596d9341674)

**Describe the solution you'd like**
Solution should be to have filter to filter out tests and test suites 

1. by **status** i.e. Passed, Aborted or Failed
2. by **resolution** i.e. Ack, New or Resolved
3. by **Last Run value** may be sliding time window
4. by **table name** - search through table names

Also we should have sorting using same columns

**Describe alternatives you've considered**
Alternate way is to scroll through all tests which is not a good experience , specially if you have so many tests or suites

**Additional context**
[Slack Thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1705542770933169)

**Comment by TeddyCr** [comment]
Merging related issue [here](https://github.com/open-metadata/OpenMetadata/issues/15119)

Filters that will be added:
- Latest Status of test case execution
- Resolution state -> will need to add latest state to TestCase (similar to testCaseResult)
- Timestamp
- Table name (i.e. entity link)
- Test type (i.e. OpenMetadata, dbt, GX, or Other)

Note: domain filtering will be tracked in a separate issue https://github.com/open-metadata/OpenMetadata/issues/15594

**Comment by TeddyCr** [comment]
Filters that will be implemented:
- status
- Last run value
- table name
- type [Column, Table]
- ~resolution~ -> This is already available in the incident manager

**Comment by ShaileshParmar11** [comment]
Re-opening as UI changes still left
