### ISSUE TITLE
Creation of admins in the UI

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1495]
A user in slack asked for more flexible management of permissions. In particular, the current implementation allows only to define admin the Dropwizard conf file. He would like to manage the list of admins in UI.

**Comment by harshach** [comment]
@sanketbambulkar @shahsank3t lets come up with a mock for users profile page.
1. User should be able to look at their profile, update etc..
2. Admin should be able to list all the users in the system and page through /search
3. Admin should be able to select a user and make them as admin as well
cc @darth-coder00

**Comment by darth-coder00** [comment]
Related to #709

**Comment by darth-coder00** [comment]
Closing as PR is merged
