### ISSUE TITLE
Support Min/Max Threshold for Custom SQL Tests

### ISSUE THREAD

**Issue by flymemoryRPA** [open-metadata/OpenMetadata#14983]
**Is your feature request related to a problem? Please describe.**
Currently, custom SQL quality tests only supports row count <= threshold. It will be great if we can set max/min value instead of a single threshold.

**Describe the solution you'd like**
Change Threshold to Max Value
Add another filed for Min Value

**Describe alternatives you've considered**
Without this feature, if I hope to set a test which should return at least 10 rows, I can not set the threshold to 10. Insted, I have to write a case when expression to return 0 if it meets the expectation and 1 if it doesn't. 

**Additional context**
N/A

**Comment by pmbrull** [comment]
this is something that should be achievable today just by tuning the returning rows of the custom SQL query. Adding more options that might be too complex for the majority of users
