### ISSUE TITLE
Support for Quality Test for narrow-downed scope

### ISSUE THREAD

**Issue by flymemoryRPA** [open-metadata/OpenMetadata#14984]
**Is your feature request related to a problem? Please describe.**
When I try to run quality test, it's not always that I would like to run it for the entire data table. I usually focus on latest data, for example, create_time is after yesterday. For such cases, I cannot leverage the built-in table/column tests, but have to write custom SQL scripts every time. 

**Describe the solution you'd like**
It will be great if we can customize the scope for quality test, so that we can narrow it down and only focus on latest data.
Maybe we can leverage the profile setting. And restrict that quality test is only done on the profiled scope.

**Describe alternatives you've considered**
Without this feature, I have to write custom SQL scripts.

**Additional context**
N/A

**Comment by TeddyCr** [comment]
@flymemoryRPA, this needs a better documentation on our side, but the table profile setting is applied to DQ as well. https://docs.open-metadata.org/v1.3.x/connectors/ingestion/workflows/profiler#4-updating-profiler-setting-at-the-table-level. 

In your scenario you can add a daily partition only to run the DQ against your fresh batch of data.
