### ISSUE TITLE
1.3.0-Beta version of Docker's launch failed

### ISSUE THREAD

**Issue by wuwuwuuw** [open-metadata/OpenMetadata#14999]
**Describe the bug**

mysql connection Exception in container execute_migrate_all

![docker](https://github.com/open-metadata/OpenMetadata/assets/48746255/548eb98b-d23a-4c09-b33b-eb3303617501)

![docker_all](https://github.com/open-metadata/OpenMetadata/assets/48746255/56f970e4-650f-4c4f-8c4b-4fb0e8910be0)

**Version:**
 - Python version:
 - OpenMetadata version: 1.3.0-beta
 - OpenMetadata Ingestion package version: 1.3.0-beta

**Comment by akash-jain-10** [comment]
Hello @wuwuwuuw . Please download the latest docker compose file from the Github Releases page [here](https://github.com/open-metadata/OpenMetadata/releases/tag/1.3.0-beta-release). This issue was fixed with #14931
