### ISSUE TITLE
UI bug in glossary terms

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#14992]
**Affected module**
UI

**Describe the bug**
When looking on data assets connected to glossary term, there is an option to filter by asset type/ owner etc.
There is '+' button that looks like meant to add more assets, but it's actually a filter button which is very confusing for the user. 

**To Reproduce**
<img width="487" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/ad2fdeb8-6579-41e2-a5d9-bbd48d502b67">

**Expected behavior**
Not sure what is the best UI/UX solution for it, but user feedback was that search feature is missing, they didn't understand it. 

**Version:**
1.2.5

**Comment by Rupchavan** [comment]
@karanh37 can we replace add icon with filter icon here which we are using on activity feed?
<img width="801" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/135013596/270a2588-b03a-49ba-a2f3-b6879c73402a">
