### ISSUE TITLE
In the alerts filter cannot find TestCase FQN 

### ISSUE THREAD

**Issue by flikweert44** [open-metadata/OpenMetadata#15027]
**Affected module**
The notifications module

**Describe the bug**
In the alerts filter cannot find TestCase FQN.

**To Reproduce**
1. Setup a tableCustomSQLQuery testcase and query the api to get the FQN under "fullyQualifiedName": 
![image](https://github.com/open-metadata/OpenMetadata/assets/64777076/75a5e666-2f68-42fb-82d7-3aedb9c24705)

2. Setup an Alert (Filtering for Test Results works fine)
![image](https://github.com/open-metadata/OpenMetadata/assets/64777076/090d6111-f05b-4b8e-a8bb-c1e38ceccec1)

3. Try to find FQN for the testcase in the Alert filter.
![image](https://github.com/open-metadata/OpenMetadata/assets/64777076/bb8b82f5-c35f-4e67-a8b6-eb26d987a270)

**Expected behavior**
I would expect to be able to include/exclude Testcases based on their FQN in a notification channel.

**Version:**
 - OpenMetadata version: 1.2.4

**Comment by TeddyCr** [comment]
@flikweert44 thank you for reporting. I am closing this as this is supported in 1.3.0 (the latest version released).
