### ISSUE TITLE
ui: alternative for global state management for app wide data

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#15022]
**NOTE: THIS IS NOT A BLOCKER FOR ANY RELEASE**

At present, React Context is employed to manage globally utilized data in our application. However, this method presents challenges as we need to maintain separate contexts for different data, which becomes increasingly unmanageable as the application expands. To address this, we will adopt Zustand for handling global state.

[Zustand](https://docs.pmnd.rs/zustand/getting-started/introduction) is a lightweight, swift, and scalable state management solution. Its straightforward API, built on hooks, provides ease of use. While it maintains clarity and flux-like behavior, it avoids excessive boilerplate or imposing specific opinions.

![image](https://github.com/open-metadata/OpenMetadata/assets/59080942/b69d6826-de73-4718-bde8-1392f11cc097)

Majorly we have to replace these contexts with zustand

- [x] AuthContext https://github.com/open-metadata/OpenMetadata/pull/15082
- [x] ApplicationConfig Context https://github.com/open-metadata/OpenMetadata/pull/15082
- [x] GlobalSearchProvider https://github.com/open-metadata/OpenMetadata/pull/15804
- [x] DomainProvider https://github.com/open-metadata/OpenMetadata/pull/15804
- [ ] ApplicationsProvider @karanh37

**Comment by chirag-madlani** [comment]
Let's start using Zustand for globally stored data for the application

**Comment by chirag-madlani** [comment]
Can you list down the places where we need to implement this? I will review it so that we can plan it better

**Comment by Sachin-chaurasiya** [comment]
> Majorly we have to replace these contexts with zustand
> 
> * [ ]  AuthContext
>         
>       
>   
>       Create an issue with the title AuthContext. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  ApplicationConfig Context

Yes @chirag-madlani , I have updated the issue, thanks.

**Comment by Sachin-chaurasiya** [comment]
> Can you list down the places where we need to implement this? I will review it so that we can plan it better

Yes @chirag-madlani , I have updated the description, thanks

**Comment by chirag-madlani** [comment]
It's done already ✅
