### ISSUE TITLE
Add Salesforce Data Cloud connector

### ISSUE THREAD

**Issue by isoctcolo** [open-metadata/OpenMetadata#15035]
**Is your feature request related to a problem? Please describe.**
I would like to ingest metadata from Salesforce Data Cloud.

**Describe the solution you'd like**
Fetch metadata out of the Salesforce Data Cloud

**Describe alternatives you've considered**
No alternatives.

**Additional context**
https://www.salesforce.com/products/data/

**Comment by TeddyCr** [comment]
@isoctcolo thanks for opening this issue. Are you interested in contributing the connector to the community? 😊

**Comment by HareenVenigalla** [comment]
Hi, Is this already assigned to someone ? I would like to take this one up.

**Comment by harshach** [comment]
@HareenVenigalla sure you can take it up
