### ISSUE TITLE
OpenMetadata Data Keyword Search Display more information. 

### ISSUE THREAD

**Issue by kenyyh** [open-metadata/OpenMetadata#15045]
On the Openmetadata UI, the entity search page will show the amount of keyword which is found.   
`Ex: Matches:1 in Description,1 in Columns Name   
`

However, it is hard to find out the matched content when the entity(table) have lots of column or tags.  We need to scroll down to find out which column is matched to confirm which entity is our target.  

![image](https://github.com/open-metadata/OpenMetadata/assets/59424683/1ed2c3c2-b1fb-4838-8ad1-0529277e0bba)

It will be helpful if the info of matched column or tags show directly on the UI.

**Comment by harshach** [comment]
This is resolved as we are now highlighting all the matched parts in preview screen as well 
![Uploading image.png…]()
