### ISSUE TITLE
assert explore exception：search failed due to Elasticsearch exception

### ISSUE THREAD

**Issue by wuwuwuuw** [open-metadata/OpenMetadata#15052]
**Describe the bug**
Abnormalities occur when viewing data assets
![es error](https://github.com/open-metadata/OpenMetadata/assets/48746255/f8fd6eb7-4c61-4cf0-a4a8-de6427d208fa)

**Version:**
 - OpenMetadata version: 1.3.0

use  quickstart packages

**Comment by TeddyCr** [comment]
@wuwuwuuw closing this, as this does not seem OM-related. You should look into your Elasticsearch resources.
