### ISSUE TITLE
Review Tableau DataModel lineage for query datasources 

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#15098]
We might be missing lineage info when ingesting datamodels in tableau generated from SQL Queries.

In that case, it would be interesting to ingest and showcase the actual SQL query too

**Comment by OnkarVO7** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/15197

Also even in case of a custom sql query tableau gives us the table, schema and db names back. So here query does not need to be parsed to extract this info
