### ISSUE TITLE
Strange characters in query usage - Snowflake Ingestion Pipeline

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#15118]
Hi,

I´m Carlos (Hotelbeds),

**Affected module**
Ingestion

**Describe the bug**
In the usage ingestion with snowflake source, we are having some problems in one database, the rest of the snowflake databases are working fine. When analysing the detail of the queries we have seen a common pattern, there are colons (:) in the queries that users use in the comments.

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/87f9ebc9-b356-4f36-9e1e-aee06a903fe7)

but,...the problem could be other simbol (chinesse simbol perhaps,..).

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/50a68333-e0cc-486f-8576-8975c526c7b9)

**To Reproduce**

If we filter like this: **_query_text not like '%:%'_**, we prevent the usage ingest from failing:
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/a9bc3de3-db1d-4192-a8ea-9786aa857945)

But this does not mean that the problem is in the colon symbol, but that filtering by this has prevented it from retrieving the query where the problem really is with another symbol.
[log query usage.txt](https://github.com/open-metadata/OpenMetadata/files/14220040/log.query.usage.txt)

**Expected behavior**
That the error in the ingestion of this type of error is controlled, as users can put any symbol in the comments.

**Version:**
 - Python version:
 - OpenMetadata version: 1.2.2
openmetadata-managed-apis==1.2.2
openmetadata-ingestion[snowflake]==1.2.2
openmetadata-ingestion[airflow]==1.2.2
openmetadata-ingestion[tableau]==1.2.2
openmetadata-ingestion[postgres]==1.2.2

thanks in advance

**Comment by triquinielas** [comment]
Hi Again, we have been able to locate an isolated query that apparently does not seem to have any.

We have filtered ingestion:
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/62bb3c67-890b-4cb5-8f41-537de137a0da)

Log:
[dag_id=HBX_SNOWFLAKE_usage_run_id=manual__2024-05-13T09_10_38+00_00_task_id=usage_task_attempt=1.log](https://github.com/open-metadata/OpenMetadata/files/15292174/dag_id.HBX_SNOWFLAKE_usage_run_id.manual__2024-05-13T09_10_38%2B00_00_task_id.usage_task_attempt.1.log)

thanks,
Carlos

**Comment by triquinielas** [comment]
Hi @ulixius9, We have more queries that fail, in case you need us to create a new ticket.

**Comment by ulixius9** [comment]
Hey @triquinielas, which version of OpenMetadata are you using? have you tried version 1.3.2 and above which contains the fix I've made for this ticket? It should ideally solve all the failing queries

**Comment by triquinielas** [comment]
Hi @ulixius9 , yes we have tested it also in 1.3.3 in stage, in live we are in 1.3.1 and it fails the same. I attach another error from another query, in this case the log says: Too many values to unpack.

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/8e69ffec-4387-4154-b585-68b2ff8ebba6)
[consulta_fallada2.txt](https://github.com/open-metadata/OpenMetadata/files/15305891/consulta_fallada2.txt)

thanks in advance

**Comment by ulixius9** [comment]
this looks similar to https://github.com/open-metadata/OpenMetadata/issues/16185

which seems already fixed, this fix should be out with release 1.4.0rc2 you can test it out and see if it solves the error

**Comment by triquinielas** [comment]
Hi, I have checked the issue #16185 and it seems the same error as the previous issue, that I have communicated to you, can we wait for this release to test again and come to comment this issue, if the same problem still appears. thanks.
