### ISSUE TITLE
Filters in Data Observability module (Data quality, Alerts,...)

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#15119]
Hi, I´m Carlos (Hotelbeds)

**Is your feature request related to a problem? Please describe.**
It is very tedious to search through the tests, users have to scroll through to find their assets.

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/e02a540d-7323-4a59-b97d-4c8312842759)

**Describe the solution you'd like**
Adding different filters would help to better search the information, these filters would help to better organise and search the tests:

**Filter by domain:** Which will work the filter above.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/cc072b69-6cf9-40b8-a083-fb46434b1faf)

**Filter by "source type:"** source type would be a new concept that would help us to discriminate between dbt filters and filters created within open metadata.

**Filter by status**, so we can filter by those who have failed.

When filtering, the totals would be updated by (Total tests) (Success) (Aborted) (failed), could be known by domain and by test origin (dbt vs open metadata).

thanks,

**Comment by ShaileshParmar11** [comment]
@TeddyCr Do we have above mentioned filter support for BE?

**Comment by TeddyCr** [comment]
Closing this and merging with https://github.com/open-metadata/OpenMetadata/issues/14941
