### ISSUE TITLE
Improve sample data view

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#15128]
Hi,

**Is your feature request related to a problem? Please describe.**
When the users see the data, even if they are few (50 rows for example), it is very frustrating because when the table has more than 12 columns you have to scroll down to the bottom of the table to find the horizontal scroll and move it.

**Describe the solution you'd like**

If the column names could be left fixed, even the header of the whole page, it would improve the user experience.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/bd1c1fd0-e226-4efd-8995-d9a80f09a402)

For example in snowflake, the experience for viewing content in the table is quite good.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/d2ba2c18-857b-4e53-911b-e2d122253892)

thanks in advance
Carlos

**Comment by Sachin-chaurasiya** [comment]
Hello @triquinielas , Thanks for filing the issues.

I think you don't have to scroll down to the bottom you can directly scroll to the right using a mouse or touchpad.

For reference, I have attached the video.



https://github.com/open-metadata/OpenMetadata/assets/59080942/b7159e10-64aa-4432-92f9-ada4164568ce

Let me know if you are looking for something else, happy to help.

**Comment by Sachin-chaurasiya** [comment]
Closing this issue, @triquinielas, if you are looking for something else then feel free to re-open.
