### ISSUE TITLE
Test email is always successful even with fake parameters

### ISSUE THREAD

**Issue by Broiler95** [open-metadata/OpenMetadata#15135]
You can enter any data into the SMTP settings and the test will be successful.

I discovered this after I correctly entered my credentials from the smtp server, I saw a message about a successful test when I clicked "Test Email", but the letters never arrived by email.

The screenshot shows an example with random parameters:
![image](https://github.com/open-metadata/OpenMetadata/assets/114237633/2f1bff2b-2364-47fe-9c36-dcf08d85a779)

**Version:**
 - OpenMetadata version: 1.3.0 in docker

**Comment by mohityadav766** [comment]
This is fixed https://github.com/open-metadata/OpenMetadata/pull/15183
