### ISSUE TITLE
some tables randomly dose not show in explorer page, after each database ingestion

### ISSUE THREAD

**Issue by Baft** [open-metadata/OpenMetadata#15174]
**Affected module**
UI : explorer
backend:  elasticsearch indexing or Ingestion Framework

**Describe the bug**
after ingesting database metadata (in my case from oracle) , and each time ingestion pipeline done.

we check tables in explorer page (randomly). this page say table dose not exist but its metadata imported to openmetadata server and accessible by direct url (http://serveraddr/table/db.schema.tableName).
actually some tables dose not indexed by elastic search (also dose not exist in table_search_index indices).

This problem occurs randomly on different tables after each time the ingestion is executed. It is even possible that the table that was indexed at the previous ingestion period, dose not index at current ingestion period and vice versa.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
environment created by docker-ccomposer and postgres as database

 - Python version:
 - OpenMetadata version: 1.2.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ayush-shah** [comment]
Looks like an issue with elasticsearch indexing itself, if it occurs in the latest version, feel free to comment on the same ticket, we can reopen the same. Thanks.
