### ISSUE TITLE
Custom Properties data for tables are only shown limited 

### ISSUE THREAD

**Issue by Nagybstar** [open-metadata/OpenMetadata#15179]
**Affected module**
Affected module: UI

**Describe the bug**
We cannot see on UI all the custom properties of the tables (only five are visible) , clicking an "See all" has no effect
**To Reproduce**

Screenshots of custom properties::
<img width="876" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/149475074/d4c32077-22d1-44c3-bab7-6536359632ef">

**Expected behavior**
Clicking on link "VIew all" should show all Custom Properties of the object. 

**Version:**
 - OpenMetadata 1.3.0

**Comment by Nagybstar** [comment]
As I understand this will be solved with issue #15180

**Comment by Ashish8689** [comment]
Reopening this issue as the PR is not closed yet!

**Comment by harsh-vador** [comment]
I will take this up
