### ISSUE TITLE
Exception when creating a chart via api

### ISSUE THREAD

**Issue by paveltashkinovuc** [open-metadata/OpenMetadata#15190]
Hello everyone. I am trying to create a chart using the following json via API:
{
"chartType": "Line"
,"dataProducts": ["test_prod"]
,"description": "dgd2"
,"displayName": "disp_nm2"
,"domain": "Data_Platform"
,"name": "somename"
,"service": "Superset"
}
It throws an exception: An exception with message [Entity type chart 608b2781-1839-4741-a9f6-604aa465e0e2 does not have expected relationship contains to/from entity type null] was thrown while processing request."
What has gone wrong? What's the entity type null and what's the relationship between the chart and the said type?

![image](https://github.com/open-metadata/OpenMetadata/assets/160125008/7f0a75d3-4134-4e0c-9f05-51a50b941d34)

**Comment by IceS2** [comment]
When creating a Chart through the API with dataProducts and exception is thrown because we are not fetching the dataProduct information in the backend.

When trying to create the Chart Entity, the DataProduct ID is null and 💥

**Comment by mohityadav766** [comment]
this has been fixed [here](https://github.com/open-metadata/OpenMetadata/pull/15439)
