### ISSUE TITLE
lineage graph is not working properlly

### ISSUE THREAD

**Issue by 12sachin95** [open-metadata/OpenMetadata#15221]
lineage graph is not working properly, on drag and drop of nodes multiple edges are creating, this might be due to duplicate index on node or edges. please refer bellow screenshot

![Screenshot 2024-02-16 at 5 31 04 PM](https://github.com/open-metadata/OpenMetadata/assets/85924477/1f511d76-f611-4f85-a11a-f936d721819f)

**Comment by karanh37** [comment]
Hi @12sachin95, lineage graph is generated now using elastic search. Have reindexed the elasticsearch.
Can you check if it's still reproducing ?

**Comment by 12sachin95** [comment]
Now its working fine @karanh37
