### ISSUE TITLE
ci: do not build and coverage CI for md files

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#15220]
Currently, we are running build and coverage CI for md files; however, we should not be running CI for md files as it is only for documentation changes.

Only md file changes in PR https://github.com/open-metadata/OpenMetadata/pull/15219, with build and coverage CIs running.

**Comment by akash-jain-10** [comment]
@Sachin-chaurasiya  - Is this still required ?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya - Is this still required ?

@akash-jain-10 , It's good to have.

**Comment by Sachin-chaurasiya** [comment]
Closing this for now and if needed @open-metadata/devops can improve the CI.
