### ISSUE TITLE
Pydantic v2 and Airflow 2.8

### ISSUE THREAD

**Issue by nickolasrm** [open-metadata/OpenMetadata#15243]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Ingestion framework

**Describe the bug**

Since the launch of Airflow 2.8 they dropped support for Pydantic v1. Because of that, openmetadata ingestion cannot be installed alongside Airflow which is a common scenario considering the installation of the lineage backend.

**To Reproduce**

Screenshots or steps to reproduce

![image](https://github.com/open-metadata/OpenMetadata/assets/26887281/5482231a-699b-4e47-baab-bad7acecc7b2)

_Airflow 2.8 release notes_

![image](https://github.com/open-metadata/OpenMetadata/assets/26887281/603e6ff4-ccd8-47a8-88f9-503f938149ab)

_Openmetadata setup.py_

**Expected behavior**

Make openmetadata ingestion to accept both v1 and v2 versions. Pydantic offers backwards compatibility by using the `pydantic.v1` module, so it will be a matter of using the correct syntax for v1 and v2 through the use of if elses on the `__version__` variable. 

For most models there will be no difference, but for the custom type in the pydantic openmetadata custom types module there may be a big change.

**Version:**
 - OS: [e.g. iOS] Ubuntu 22.04
 - Python version: 3.11.7
 - OpenMetadata version: [e.g. 0.8] 1.2.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.2.5

**Additional context**

I know airflow 2.8 is still incompatible with openmetadata ingestion, but it would be important to migrate or to make it compatible with both v1 and v2 in order to follow project and lib changes. Airflow is just one problem, but projects that use openmetadata may get incompatibility issues due to this outdated dep. 

An example of compatiblity with v1 and v2 at the same time is [bentoml](https://github.com/bentoml/BentoML).

**Comment by colax94** [comment]
Hello,might be unrelated but I am also seeing issues with Airflow 2.8.1, where OpenMetadata auto generated DAGs are not being scheduled by Airflow. The CRON schedule appears correctly in the UI, but the "Next run date" remains None, and the DAG is never scheduled.
The DAGs can still be run manually though.

**Comment by sunchao** [comment]
Also looking forward for this. We have Airflow 2.8.x internally and would like to use OpenMetadata with it.

**Comment by harshach** [comment]
hi @sunchao , we will be prioritizing this for 1.5.0 release. Let us know if you can help us providing with any PRs

**Comment by sureshms** [comment]
@sunchao, how are you? 🤝

**Comment by sunchao** [comment]
Hi @sureshms @harshach how are you doing? long time no see! 

Internally we're just getting started with OpenMetadata. We already have a Airflow 2.8.x setup running and because of the 2.6.x limitation, we had to run a separate Airflow service just for OpenMetadata which is not very desirable, and hence the ask.

Do you guys have a rough timeline for 1.5.0? Also it'd be great if you have some umbrella ticket to track the tasks for unblocking this upgrade. I can't promise I'll have enough time to work on those, but I'll give it a try if I do. 😂

**Comment by DataOps7** [comment]
Hey @harshach !
We are also blocked on this issue :(
You guys can also upgrade pydantic to v2 but still use `from pydantic.v1 import ...` while you're migrating.
Thanks!
