### ISSUE TITLE
dbt ingestion: Incorrect work assignment of owners

### ISSUE THREAD

**Issue by CapitanHeMo** [open-metadata/OpenMetadata#15247]
**Affected module**
Ingestion Framework?

**Describe the bug**
The problem I'm facing affects 3 aspects of working with OpenMetadata:
1. Dbl Ingestion does not find existing users if in <username>(username@yourdomain.com ) there is '.';
2. Users assigned to dbl Ingestion are not displayed on the search page.
3. Users assigned to dbt Ingestion are not displayed in the drop-down filter by owner.

**To Reproduce**
1. A user with a similar name but replacing the '.' sign with '_' is identified without problems.
```
[2024-02-19T13:41:51.468+0000] {metadata.py:171} WARNING - Unable to ingest owner from DBT since no user or team was found with name daniil.kotomtsev
[2024-02-19T13:41:51.616+0000] {metadata.py:171} WARNING - Unable to ingest owner from DBT since no user or team was found with name daniil.kotomtsev
[2024-02-19T13:41:52.070+0000] {metadata.py:171} WARNING - Unable to ingest owner from DBT since no user or team was found with name daniil.kotomtsev
```

2.
![Снимок экрана 2024-02-19 в 16 44 51](https://github.com/open-metadata/OpenMetadata/assets/34104577/bb6f28a2-6f92-4cee-8588-2d3352d3a683)
![Снимок экрана 2024-02-19 в 16 44 29](https://github.com/open-metadata/OpenMetadata/assets/34104577/de5eb5ac-2126-41bf-8216-f47f4f981e84)
3. 
![Снимок экрана 2024-02-19 в 17 10 43](https://github.com/open-metadata/OpenMetadata/assets/34104577/08a9d9a7-c02b-4d3f-80b0-c1e9d97431a5)

Screenshots or steps to reproduce

**Expected behavior**
1. I expect users with '.' in <username>(username@yourdomain.com ) will be detected and linked as owners to the tables, if they are available in the system.
2-3. I expect that users linked to tables using dbt Ingestion will be displayed in the drop-down filter by owner, on the search page in the table(Object) block and on the Profile > "My Data" page.

**Version:**
 - OS: Ubuntu 22.04
 - Python version: - 
 - OpenMetadata version: 1.3.0
 - OpenMetadata Ingestion package version: -

**Additional context**
- I use Docker installation with  default docker-compose file. 
- For load data from dbt artifacts i use UI solution with load files from S3 storage.

**Comment by harshach** [comment]
@OnkarVO7 how are we looking for users?

**Comment by OnkarVO7** [comment]
@harshach we get the user entity ref by using the get_by_name API [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/ometa_api.py#L365) and building the user fqn [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/database/dbt/metadata.py#L155)

Let me try to reproduce this and see if calling ES here fixes it

**Comment by harshach** [comment]
@OnkarVO7 if the name contains "." or any entity contains "." in its name we should escape it for FQN.
@pmbrull is hte ingestion framework does the escape during the construction of FQN?

**Comment by pmbrull** [comment]
@harshach we use antlr as well to build and quote it
