### ISSUE TITLE
AZURE SSO Self-signup not working in the case when username and emails have different formats

### ISSUE THREAD

**Issue by Nagybstar** [open-metadata/OpenMetadata#15241]
**Affected module**
UI Authentication, self-signup

**Describe the bug**
Our company has different formats for username and emails, example.
email: x-le.duy@company.com
username: x-duyl@company.com

When signup  happens the system creates 
the username from the Azure loginname not the email address.
The creation user somehow succeeds but there is an error message already.

<img width="279" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/149475074/bbae9290-169b-46ff-a647-af4cf7d6a642">

The error message is containing the e-mail address of the user. compaining about not finding the user instance.

In the backend database the following data can be seen:

<img width="281" alt="Screenshot 2024-02-16 185416" src="https://github.com/open-metadata/OpenMetadata/assets/149475074/3527d4df-e58b-4b4c-894d-510a1e44aa9e">

We can see that the user's email did not get stored in the database, just the username.

Finally, when the user revisits the OMD site, the login process tries to create again the user 
but it fails with the message "Entity already exists"

Note: if we register the user with the correct email address , they are able to login via SSO,
but in the background database their data appears as below:

name = first part of the e-mail
email = username

**Expected behavior**
I would expect that at self sign-up user data is registered correctly even in the case that usernames and their emails have different naming formats.

**Version:**
 - OpenMetadata version: 1.3.0

**Comment by harshach** [comment]
@Nagybstar please check on slack to confirm if its indeed a bug and not a configuration issue.
https://slack.open-metadata.org
What configuration did you pass to principalUrl?
does the company.com changes or is it the same domain?

**Comment by Nagybstar** [comment]
Hi, 
I have already contacted the support several times on slack, confirmed the settings,
they said 10 days ago that will try to reproduce the issue, but since then I again have only questions to check my configuration again. 
AUTHENTICATION_JWT_PRINCIPAL_CLAIMS is set to default and suggested value: [email,preferred_username,sub]
SSO is working if I start registering users with their email addresses manually (which is not the case)
SSO is not working with self signup , the first login works somehow (with the snapshotted ) but the consecutive login tries again to create the user.

So authentication is working,but the data is not getting through correctly in the case of self signup only with manual registration.

We have the same domain, but a username is not in sync with email address: 
Full name : FirstName LastName 
Email : x-firstname.lastname@domain.com
username: x-lastnameF@domain.com

**Comment by harshach** [comment]
@Nagybstar provide the link to the thread on slack

**Comment by Nagybstar** [comment]
Hi @harshach! 
Thank you for your reply, below is the link:
https://openmetadata.slack.com/archives/C02B6955S4S/p1707394949063649

**Comment by rrigal-lo** [comment]
Apologies to revive an old issue, @Nagybstar were you able to solve your issue ? Would you mind sharing the solution here ? The Slack thread is not accessible without a Pro license. Thank you

**Comment by Nagybstar** [comment]
Hi @rrigal-lo 

Trying to remember as I'm not on the project anymore.
In my agony I simply started to iterate on the settings, instead of the suggested one which was:
AUTHENTICATION_JWT_PRINCIPAL_CLAIMS:-[email,preferred_username,sub]
I tried them in different order and leaving out some of them 
and after some iterations I found a working combination but I don't remember exactly which and I'm not able to check anymore.
