### ISSUE TITLE
OMeta API - Table Mixin Location

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1525]
We need to update the Table Mixin for the OMeta API to add the methods for location handling

**Comment by amiorin** [comment]
I have just committed this.
https://github.com/open-metadata/OpenMetadata/blob/f9436c65f06bde2f51704d4e95483feb6c6ab272/ingestion/src/metadata/ingestion/ometa/mixins/tableMixin.py#L31-L41

**Comment by pmbrull** [comment]
all good then! Closing, thanks!
