### ISSUE TITLE
OpenMetadata java client doesn't work

### ISSUE THREAD

**Issue by alexandredantas** [open-metadata/OpenMetadata#15255]
**Affected module**
openmetadata-java-client

**Describe the bug**
When creating a new `org.openmetadata.client.gateway.OpenMetadata` object I get a `NullPointerException` because the constructor calls `initClient` that expects only `OpenMetadataConnection` object. Inside this method, it's expected that the attribute `apiClient` is already instantiated, what is not.

**To Reproduce**

It's possible to check the issue just checking the call stack until [this](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-clients/openmetadata-java-client/src/main/java/org/openmetadata/client/gateway/OpenMetadata.java#L55) line.

To trigger the issue, just add client dependency in your pom:

<dependency>
    <groupId>org.open-metadata</groupId>
    <artifactId>openmetadata-java-client</artifactId>
    <version>1.3.0</version>
</dependency>
 
In a main class, use the following snippet:

```
OpenMetadataConnection openMetadataConnection = new OpenMetadataConnection();
OpenMetadata openMetadataClient = new OpenMetadata(openMetadataConnection);
```

**Expected behavior**
Creation happens successfully

**Version:**
- openmetadata-java-client version 1.3.0

**Additional context**

**Comment by harshach** [comment]
closing it as duplicate https://github.com/open-metadata/OpenMetadata/issues/15235
