### ISSUE TITLE
Docker-compose.yml: missing 2 instances of 'restart: always'

### ISSUE THREAD

**Issue by sandervanlaar** [open-metadata/OpenMetadata#15266]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
In the docker-compose.yml files (for MySQL and PostgreSQL) the setting 'restart: always' exists in the yml sections 'postgresql' and 'openmetadata-server'.
This setting should be added to the sections 'elasticsearch' and 'ingestion' as well. It does not have to be added to the section 'execute-migrate-all'.)

**To Reproduce**
Run `docker compose -f .\docker-compose.yml up --detach `
Open Docker Desktop and observe only 2 containers started, 2 containers have to be manually started.

**Expected behavior**
Expected: after restart all 4 containers should start.

**Version:**
 - OpenMetadata version: ALL

**Additional context**
Discussion in Slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1708418673065209

**Comment by harshach** [comment]
@tutte is this valid issue? if not can we close it.

**Comment by tutte** [comment]
Closin as the fix was merged
