### ISSUE TITLE
UI: Infinite spining when set a Group as a Domain owner.

### ISSUE THREAD

**Issue by kleysonr** [open-metadata/OpenMetadata#15272]
I'm using OMD 1.3.0 and when I try to set a Group as a domain owner I'm get an infinite spining.

![image](https://github.com/open-metadata/OpenMetadata/assets/1976289/742a106f-47fe-41d2-b91b-1436c128e3ea)

**Comment by chirag-madlani** [comment]
Fixed it [here](https://github.com/open-metadata/OpenMetadata/pull/15293/commits/d53436bcfee1cb98eb66fc2d1a07da9b197e7d75), It will be part of 1.3.1
