### ISSUE TITLE
Mentions in comments on Announcements is not working - always refreshing the page

### ISSUE THREAD

**Issue by nadiapetramont** [open-metadata/OpenMetadata#15271]
**Affected module**
UI

**Describe the bug**
When a Announcement is opened, and someone try to add a comment with a mention on it, the page is refreshing and not allowing to add a comment - only when we try to add a coment with mention

**To Reproduce**
- Create an Announcement
- add a comment with mention (team or user)

![image](https://github.com/open-metadata/OpenMetadata/assets/39867937/7f7fbba9-493d-4e61-91f2-f457869ab9c5)
![image](https://github.com/open-metadata/OpenMetadata/assets/39867937/b1bbfb24-7490-44fb-8eab-a03924c01939)

**Expected behavior**
Allow to add a mention with user or team

**Version:**
 - OpenMetadata version: 1.3.0 - collate sandbox

**Additional context**
Only for add a team or user '@'
# to add an asset is working properly

**Comment by harsh-vador** [comment]
This is handled by this PR #15194

**Comment by chirag-madlani** [comment]
Will ship it with 1.3.1
