### ISSUE TITLE
Remove service as an option from fields query param for data asset entities

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1528]
Should it contain "service" or "database" if they are always included in the data layer answer?
This is for the entity Table but the same question is also Topic and the other data entities.

```java
  static final String FIELDS = "columns,tableConstraints,usageSummary,owner," +
          "database,tags,followers,joins,sampleData,viewDefinition,tableProfile,location,tableQueries";
````

```java
  @Override
  public Table setFields(Table table, Fields fields) throws IOException, ParseException {
    table.setColumns(table.getColumns());
    table.setDatabase(getDatabase(table.getId()));
    table.setService(getService(table));
```

**Comment by sureshms** [comment]
We can delete it now that they are default fields.

**Comment by sureshms** [comment]
Description of the change:
Currently all data entities return the `service` they belong to and the `serviceType`. In GET requests, the `fields` parameter lists `service` as a field that can be passed in the API calls. Remove that field as it is no longer is relevant with `service` becoming a default field.
