### ISSUE TITLE
Backend: User with the enabled `EditReviewers` policy is unable to edit reviewers for glossary and glossary terms

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#15284]
**Affected module**
Backend

**Describe the bug**
A user whit allowed `EditReviewers` Permission is not able to edit the reviewers for glossary and glossary terms.

API: `/api/v1/glossaryTerms/{id}`
METHOD: `PATCH`
RESPONSE: `"Principal: CatalogPrincipal{name='aniketkatkar97'} operations [EditAll] not allowed"`

**To Reproduce**

https://github.com/open-metadata/OpenMetadata/assets/51777795/6d2ae44f-9fe3-45ff-a2db-ffa892d54dbd

**Expected behavior**
A user with `EditReviewers` permission should be able to edit the reviewers

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
resolved. in 1.5.2
