### ISSUE TITLE
Issues with redshift ingestion due to the rowcount

### ISSUE THREAD

**Issue by anddycabrerax** [open-metadata/OpenMetadata#15299]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
attached an image with errors in version 1.3. If rowCount column exists in the database looks like there is a collision of names when the profiler ingestion try to query it but not sure.

Also I got a: Could not run test case response_set_id_unique: division by zero. This error only happens when we have a rowcount column in our tables.

**To Reproduce**

Create a table with rowcount included in redshift and try to do a profiler ingestion for that table. 
For the second error about 0 division, try to create a check of columns to be unique in Profiler & Data Quality.

I can give more information to help to identify the issue. Just ask me.

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 1.3
 - OpenMetadata Ingestion package version: 1.3
**Additional context**

**Comment by anddycabrerax** [comment]
![image](https://github.com/open-metadata/OpenMetadata/assets/89258373/3daeb465-a212-420a-8b25-bc453279ae1c)
![image](https://github.com/open-metadata/OpenMetadata/assets/89258373/7cb513f2-0c1c-4bf4-b067-761c234cd42b)

**Comment by TeddyCr** [comment]
@anddycabrerax thanks for reporting this. Could you share your table schema?

**Comment by anddycabrerax** [comment]
@TeddyCr 
<body>
<body>

</body>
</body>
</html></html>There are 2 errors. the one ZeroDivisionError: division by zero. 
test_case_result.passedRowsPercentage = (passed_rows / row_count) * 100
ZeroDivisionError: division by zero

This is happening in database -> Schemas -> Table -> Profiler & Data Quality -> Data Quality -> Test Cases -> Pipeline

The schema for this one is this:

Field                                   Type
--------------------------------------- -----------------------------------
AppID                                   character varying(36)
TenantID                                character varying(36) [Allows NULL]
ResponseID                              character varying(36)
ResponseSetID                           character varying(36)
QuestionVersionID                       character varying(36)
AnswerID                                character varying(36) [Allows NULL]
IsSelected                              boolean [Allows NULL]
ResponseContent                         character varying(65535) [Allows NULL]
OrderingIndex                           integer [Allows NULL]
UpdateTime                              timestamp without time zone
ContextID                               character varying(36)
SurveyVersionID                         character varying(36)
ResponderID                             character varying(36)
CompleteFlag                            boolean [Allows NULL]
SurveyIdentifier                        character varying(500) [Allows NULL]
SurveyVersionIdentifier                 character varying(500) [Allows NULL]
QuestionIdentifier                      character varying(500)
QuestionVersionIdentifier               character varying(500)
AnswerIdentifierSlug                    character varying(500) [Allows NULL]
ExternalContextID                       character varying(255) [Allows NULL]
ExternalSubcontextID                    character varying(255) [Allows NULL]
AnswerVersionID                         character varying(36) [Allows NULL]
QuestionGroupID                         character varying(36) [Allows NULL]
FactUpdateTime                          timestamp without time zone

2- The second error schema is:

  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/profiler/orm/functions/table_metric_computer.py", line 393, in compute
    if res.rowCount is None:
AttributeError: 'NoneType' object has no attribute 'rowCount'

this is in: Database Services -> Ingestions -> Profiler (ingestion type)
this is the schema for one of the tables with the issue:

Field                         Type
----------------------------- -----------------------------------
RecordID                      character varying(36)
OrganizationID                character varying(36) [Allows NULL]
IsActive                      boolean [Allows NULL]
RecordCreationTime            timestamp without time zone
CreatorID                     character varying(50) [Allows NULL]
RecordUpdateTime              timestamp without time zone
UpdaterID                     character varying(50) [Allows NULL]
ChangeOperationType           character varying(2)
ChangeRecordTime              timestamp without time zone
DataSourceOrigin              character varying(200)

One important thing is that the rowcount only exist in the views so not sure at the point what is the source of the issue.
