### ISSUE TITLE
Can't add tags to glossary terms when I am navigating with a selected Domain

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#15298]
1. On the top-right panel, preselect a Domain `XYZ` other than `All Domains`
2. Go to the glossary view
3. Click on edit glossary term
4. Click on tags -> no tags are coming back from the search API

If instead, we perform this same operation from `All Domains`, we get all the tags back. This can be replicated in the sandbox

We need to double-check the search API call since tags cannot be assigned to specific domains, at least from the UI

UPDATE: On the explore page, once you have a Domain selected, no tags appear as well. I imagine this bug would impact trying to tag any other asset too

**Comment by harshach** [comment]
@karanh37 this is possibly because of passing domain as filter to all the entities. We need to escape tags out of this call and make it a generic call.
