### ISSUE TITLE
Feature Request: Ability to add descriptions to individual column lineage edges in OpenMetadata

### ISSUE THREAD

**Issue by chillerno1** [open-metadata/OpenMetadata#15300]
Please see the following conversation for context and screenshots: [Slack Discussion](https://openmetadata.slack.com/archives/C02B6955S4S/p1708554288761089)

**Is your feature request related to a problem? Please describe.**
Yes, the problem arises when dealing with column lineage within the OpenMetadata API. Currently, when creating an AddLineageEdge request, we can add a description that applies to the entity -> entity edge. However, this description also displays when users click on column lineage edges. There seems to be no functionality available to update or specify descriptions for individual column lineage edges.

**Describe the solution you'd like**
We would like the ability to include a description field for ColumnLineage edges specifically, separate from the entity edge description. This feature would allow for more granular documentation of lineage, enabling users to understand the source and nature of each column lineage. In our specific use case, we'd like to use it to inform users how the column lineage edge was derived when it's created by an external process.

**Describe alternatives you've considered**
N/A

**Additional context**
In the UI, when clicking on a column edge, it displays **Edge Information** including **Source**, **Source Column**, **Target**, **Target Column**, which initially led to the assumption that descriptions were also column edge-specific. Enhancing the UI to allow for descriptions at the column edge level would improve the visibility of lineage documentation in OpenMetadata.

![image_720](https://github.com/open-metadata/OpenMetadata/assets/17304934/851891d3-0d20-4150-a15d-498523400b5b)

**Comment by harshach** [comment]
we will be addressing this in Metadata Actions app, however this is Collate only feature. If someone from OSS wants to take this up and ship this feature, please re-open
