### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting - malformed DAG after some time

### ISSUE THREAD

**Issue by Nemeczek** [open-metadata/OpenMetadata#15321]
**Affected module**
Ingestion Framework

**Describe the bug**
After some time OpenMetadata workflow factory can't parse .json DAG config.

**To Reproduce**
`[2024-02-22T16:23:00.717+0000] {dagbag.py:346} ERROR - Failed to import: /airflow-dags/dags/Data_Platform_UC_metadata_i5ZZdx5s.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/airflow-dags/dags/Data_Platform_UC_metadata_i5ZZdx5s.py", line 7, in <module>
    workflow = workflow_factory.WorkflowFactory.create("/airflow-dags/dags/Data_Platform_UC_metadata_i5ZZdx5s.json")
  File "/home/airflow/.local/lib/python3.10/site-packages/openmetadata_managed_apis/workflows/workflow_factory.py", line 60, in create
    workflow_config_dict = load_config_file(config_file)
  File "/home/airflow/.local/lib/python3.10/site-packages/openmetadata_managed_apis/workflows/config.py", line 29, in load_config_file
    config = json.loads(expanded_config_file)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 3552 (char 3551)`

![image](https://github.com/open-metadata/OpenMetadata/assets/1111404/c4417fef-d091-4b82-b89a-d03b8b1142b9)

And the json is an valid JSON.

Screenshots or steps to reproduce
It happens or regular basis for all the pipelines. Right now we are doing Kafka and Databricks.

**Expected behavior**
DAG is successufly ran and if fails then due to configuration. 

**Version:**
 - OS: AKS 
 - Python version: openmetadata ingestion 1.3
 - OpenMetadata version: 1.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==1.3`]

**Additional context**

**Comment by pmbrull** [comment]
hi @Nemeczek, thanks for details and sharing the files that were raising the exception.

I copied those files on a 1.3.1 container and I am not able to reproduce the error.

The only final difference I can think of is if on your instance you have some environment variables being expanded on the json.

Can you share via DM on Slack the env vars you have on your ingestion container?

Thanks

**Comment by pmbrull** [comment]
Have been in touch with @Nemeczek, looks like the issue might come from some caching on the Azure blob storage that is used to store the files. Waiting for further details

**Comment by Nemeczek** [comment]
99.9% this issue is caused by Azure Blob. I think files are beign cached for certain amount of time - and after that cache expires te pipeline starts to fail. When pipeline is run manually it works. But scheduled runs do not. 

Moreover I edited the DAG workflow .py file. I added printout statements to see if really JSON contains some malformed content. To my surprise the manual run did contain these statements but the scheduled did not... Once I confirm that by changing few settings in our k8s I will close this issue with an comment. Maybe some poor soul will face the same issue

**Comment by pmbrull** [comment]
Thanks for the details @Nemeczek and the debugging.

This will definitely be a great addition to the docs. Also, if there's anything we need to generalize on the airflow plugin to handle these scenarios, we can do so. We'll just need your help on testing the pieces.

Thanks,
Pere

**Comment by Nemeczek** [comment]
In order to use the Airflow we decided to use Azure Blob Storage as PersistentVolume [using this guide - Storage class using blobfuse ](https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret).

Which is a very good solution for teams that are on Azure and using AKS. After every few days our DAGs started to get malformed. After manually editing dag python file (the one from dags/.py) I realised that the Executor pods are actually using the old dag file. And this sort of behaviour was caused by the recommended config by the documentation mentioned:

```
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
```

We managed to fix this by disabling the cache (I think the `--o direct_io` and `--cache-size-mb=0` would do but I actually disabled every possible cache. Why? Because the DAG .py and .json files are small and are not that often used so I think it would generate much costs. 

Without cache:
```
      - --o direct_io
      - --file-cache-timeout-in-seconds=0
      - --use-attr-cache=false
      - --cancel-list-on-mount-seconds=10
      - --o attr_timeout=0
      - --o entry_timeout=0
      - --o negative_timeout=0
      - --log-level=LOG_WARNING
      - --cache-size-mb=0
```

Of course post mortem I was able to find similar issues: 
https://github.com/Azure/azure-storage-fuse/issues/1171
 https://github.com/Azure/azure-storage-fuse/issues/1139

So I am closing the issue because there is nothing wrong with OM - I hope this issue will save someone headache
