### ISSUE TITLE
Entity header icon button need to be change for better UX

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#15324]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- headers icons buttons are hard to see because of white on white background

**To Reproduce**

Screenshots or steps to reproduce

<img width="419" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/70370281-682a-43eb-81bd-42599799f114">

**Expected behavior**

- Need to have better UX Button icons for readability

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
For now good with current UI. Closing this
