### ISSUE TITLE
Backend: Patch using FQN for entities

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#15323]
In order to patch using id, we need to do a get call to list entity/entities, fetch the id of the entity and then pass it to patch.
Rather than making additional calls, we can patch using fqns which would eliminate the need to list entities for their ids in some scenarios.

ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1708654933324039

**Comment by mohityadav766** [comment]
this is done here #16113
