### ISSUE TITLE
greenplum ingestion does not work for GP7

### ISSUE THREAD

**Issue by JackWolverson** [open-metadata/OpenMetadata#15331]
**Affected module**
Ingestion Framework

**Describe the bug**
The query used for getting the tables from greenplum does not work on GP7 due to a view being removed. 
in this query https://github.com/open-metadata/OpenMetadata/blob/bdf27458e52c7997522ebe7e5eec7d889f489c5c/ingestion/src/metadata/ingestion/source/database/greenplum/queries.py#L19 
the view pg_catalog.pg_partition_rule has been removed as per the release note on gp7 here https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-removed-features-objects.html#:~:text=Removed%20Operators-,Removed%20Tables%20and%20Views,-The%20following%20list

**To Reproduce**

connect to a greenplum database that is of version 7 
run the ingestion, no tables will appear due to this warning in the logs 
![image](https://github.com/open-metadata/OpenMetadata/assets/26302103/d8a9e89f-54cc-4da8-993d-fee7b0443a4d)

**Expected behavior**
the tables are ingested 

**Version:**

 - OpenMetadata version: 1.3.0
 

**Additional context**
using the most recent version of the quickstart docker compose

**Comment by TeddyCr** [comment]
Hello @JackWolverson thank you for opening this issue. GP was a community contributed connector, would you like to contribute to solve this issue and add support for GP7?

**Comment by JackWolverson** [comment]
Hi @TeddyCr  i did start looking into this, i am trying to find a query that will work on both 6 & 7 so that any other changes are not required, i will try to continue looking at this issue in my spare time

**Comment by TeddyCr** [comment]
Don't hesitate to join our slack community https://open-metadata.org/?_stg_disable_debug we have a contributor channel

**Comment by gpby** [comment]
@JackWolverson did you try to use native PostgreSQL connector to ingest data from GP7? GP7 metadata came closer to modern Postgresql metadata tables so probably it can be a workaround.
