### ISSUE TITLE
Bug can not add bot to ActivityFeedAlert

### ISSUE THREAD

**Issue by BinhPhamQuang** [open-metadata/OpenMetadata#15358]
**Affected module**
 it impact the UI

**Describe the bug**
I am using version 1.3.0 I I've noticed that filter seems to support excluding users (default exclude is ingestion-bot). When I edit or update something to ActivityFeedAlert . I can not add any new bot I created to that filter. Even if I removed ingestion-bot, I can't add it back again/ Because this drop down list only show end user,  does not include any bot to select.

**To Reproduce**

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/53305948/fb063ce6-20e1-4f5f-82df-c631f1aaa4be)

**Expected behavior**
End user can add bot to list of Updater name

**Version:**
 - Open Metadata Kubernetes v1.3.0

**Additional context**

**Comment by nakaken-churadata** [comment]
Hi team. I'm new here but interested in contributing this project. I thing that the difficulty of this issue looks like just right for me. Can you allow to assign me to this issue?

**Comment by pmbrull** [comment]
hi @nakaken-churadata , assigned, thanks

**Comment by nakaken-churadata** [comment]
Please check PR #15501
