### ISSUE TITLE
Improvement - Exception Raising and Logging on Ingestion Pipeline

### ISSUE THREAD

**Issue by IceS2** [open-metadata/OpenMetadata#15362]
# Description

Today at the end of the Ingestion Pipeline execution we call the `raise_from_status` method to raise any errors and warnings that we have collected from the execution.

At the Source Step we only raise it if the error rate is higher than a constant (`SUCCESS_THRESHOLD_VALUE`). We could do the same for all the steps to avoid marking the pipeline as failure when only a couple of records fail to be processed and instead mark it as `partial_success`.

It'd be great to also allow the user to actually configure the `SUCCESS_THRESHOLD_VALUE` since each case is one case and the hardcoded value might not be a good fit for all the cases.

It'd also be great to improve how we log these Exceptions to let the user know that the pipeline processed all the records but the ones that failed and that it wasn't stopped in the middle. It doesn't seem to be clear

## TL|DR Tasks

- [ ] Use the `SUCCESS_THRESHOLD_VALUE` for all the steps
- [ ] Expose the `SUCCESS_THRESHOLD_VALUE` for the users to configure
- [ ] Improve the logging to guarantee the users understand the pipeline finished and wasn't stopped in the middle due to the exception

## Links

[Call to `raise_from_status` at the end of the Ingestion Pipeline](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/cli/ingest.py#L51)

[`raise_from_status`](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/workflow/workflow_status_mixin.py#L116)

[`raise_from_status_internal` for the Ingestion Pipeline](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/workflow/ingestion.py#L141)

[Related Slack thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1709018835529899)

**Comment by harshach** [comment]
@IceS2 assigned this to you, lets track it for 1.6.0

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/18280
