### ISSUE TITLE
1.2.0 When applying Domain to Glossary, Terms don't displaying as Domain's Assets

### ISSUE THREAD

**Issue by stuchalkin** [open-metadata/OpenMetadata#15374]
**Affected module**
UI

**Describe the bug**
As header says. When i'm set Domain manualy to Term of Glossary, it's appears as Asset of Domain at domain page. But when i'm changing Domain on entire Glossary, Terms dont appears at domain page.

when adding Term to Glossary that already assigned to domain, Term appears as Asset of Domain at domain page.

**To Reproduce**

1. Create glossary, term in glossary and domain
2. Assign domain to glossary
3. Create new domain, and switch glossary to it.
4. At glossary, term will be connected to new domain
5. But at domain page, you will not see term at assets, untill you add it manually.

**Expected behavior**
When Domain set to Glossary, all Terms of Glossari goes to domain's assets

**Version:**
- OMD 1.2.0

**Comment by harshach** [comment]
cc @karanh37

**Comment by harshach** [comment]
@stuchalkin can you upgrade to 1.3.1 and see if the issue persists. Can not reproduce on our side

**Comment by karanh37** [comment]
It is not reproducible now. 
If you feel like this is still happening, then you can reopen this ticket.
