### ISSUE TITLE
Connector for Starrocks

### ISSUE THREAD

**Issue by konovenski** [open-metadata/OpenMetadata#15379]
**Is your feature request related to a problem? Please describe.**
Starrocks is a great alternative for Trino. it would be nice to implement a connector for them. They're following mysql protocol so theoretically it shouldn't be as hard as "from-scratch" integration (But I could be wrong, everything looks easy if you're not working on it haha)

**Comment by agustin-vaca** [comment]
I'd like to work on this, can you please assign it to me?

**Comment by agustin-vaca** [comment]
@pmbrull

**Comment by pmbrull** [comment]
Thanks @agustin-vaca, assigned. You can find the docs on how to build a new connector here https://docs.open-metadata.org/v1.3.x/developers/contribute/developing-a-new-connector

**Comment by JasonChen-ecnu** [comment]
@agustin-vaca  Is the development of this connector completed? In which version is this feature expected to be launched?

**Comment by pmbrull** [comment]
> @agustin-vaca Is the development of this connector completed? In which version is this feature expected to be launched?

@agustin-vaca are you still working on this? Would you need some help? Otherwise. we can unassign the issue. Thanks

**Comment by iamskp11** [comment]
Hey @pmbrull , If this is not being worked upon, I would like to take this task. Please assign. Thanks!

**Comment by fixpng** [comment]
Look forward to the starrocks Connector being developed soon

**Comment by pmbrull** [comment]
hi @iamskp11 sorry missed the message. Hopefully you might have been able to start even if it was not assigned. Thanks

**Comment by harshach** [comment]
@iamskp11 are you able to make any progress. If not we will be closing this as not-planned
