### ISSUE TITLE
Add a default configuration for Lineage's Upstream/Downstream Depth #

### ISSUE THREAD

**Issue by tonsumawang** [open-metadata/OpenMetadata#15408]
**Feature**
Default Configuration of Lineage's Upstream/Downstream Depth # 

**Describe the task**
This is to formally feature tasks to add a default configuration in the UI settings for Lineage's Upstream/Downstream Depth #.

**Business/Technical Use Cases**
1. It allows flexibility for the OMD users to set their preferred default lineage's upstream/downstream depth i.e. 1 or 2 instead of it being hardcoded to 3 by default.
![image](https://github.com/open-metadata/OpenMetadata/assets/134579809/ad40d08d-2dbf-44bb-8480-c935e81a224f)

2. For Lineages that contains hundreds of upstream and downstream nodes and the default is hardcoded and always set to 3, the graph is not loading and producing an error so the user have to manually set the depth to 1 each time.
![image](https://github.com/open-metadata/OpenMetadata/assets/134579809/219d2158-636d-40bf-b508-56578812a3c6)

**Comment by aballiet** [comment]
+ 1000

**Comment by aballiet** [comment]
Outside of the bug / slow UI, it's also overwhelming for business users.
Having adoption issue at my company due to this which is sad considering the quality of the tool and all the features.

I am willing to offer a quick PR which changes the value to 1.

**Comment by harshach** [comment]
Fixed in 1.5.13 and 1.6.1
