### ISSUE TITLE
PostgreSQL Metadata Ingestion Lcoks View/Table which block DDL in Database.  

### ISSUE THREAD

**Issue by kenyyh** [open-metadata/OpenMetadata#15414]
**Is your feature request related to a problem? Please describe.**

When Postgres Metadata Ingestion Collecting information in Postgres.  
It will claim lock on every user defined view and the related table.  

PID 2533941 is Metadata Ingestion Session.  
Which start tansaction at 2024-03-01 13:52:22 and won't commit until the jobs finish.  
![image](https://github.com/open-metadata/OpenMetadata/assets/59424683/6544a964-c305-4b61-ad98-a2bc91253c46)

During the Ingestion Jobs running, we can't do any DDL / truncate on these table.  
(The table doesn't have dependency with view will not be lock. )
![image](https://github.com/open-metadata/OpenMetadata/assets/59424683/1e231034-b0af-40f4-86c4-a564ca488ae5)

When ingesting a large database with lots of table/view, it may cost a long time to do the ingestion job.  
It will become a huge impact for some user that they can't do DDL and truncate for such a long time.  
Is it necessary to claim the table/view lock for such a long time.   
Considering that OpenMetadata is a platform to collect Metadata not the main user, it is not reasonable to block the table change when collecting Metadata.   
Also, the Metadata Ingestion will not lock table when there is no view relate to it, i wonder is it necessary to lock view.

**Describe the solution you'd like**
1. Don't Lock Table/View when Collecting Table.   
2. Don't hold the transaction for such a long time.    

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by TeddyCr** [comment]
My hint here is the join  we are doing on the `pg_class` table which should acquire an AccessShareLock on this table which will conflict with AccessExclusiveLock  that this table will require when you run any kind of DDL statement.

https://www.postgresql.org/docs/current/explicit-locking.html

**Comment by TeddyCr** [comment]
> During the Ingestion Jobs running, we can't do any DDL / truncate on these table.

@kenyyh can you share the type of error you are seeing from the postgres side when you are performing this kind of operation?

**Comment by pmbrull** [comment]
since we cannot reproduce it, not sure we have any direct action on our end to make here. We'll keep it open waiting for further user feedback. Last discussion happened in slack yesterday and moving the ingestion to lower loads it was processing fine

**Comment by TeddyCr** [comment]
@kenyyh do you have any extensions loaded in your postgres instance?

**Comment by TeddyCr** [comment]
Validation scenarios:
- [ ] Create artificial load on a relatively big schema and check the locks create when running ingestion
- [ ] Test older version of postgres
- [ ] (if extensions names shared) try to install extensions and run ingestion
