### ISSUE TITLE
Column lineage is not displayed for Materialized View created from multiple tables

### ISSUE THREAD

**Issue by JahJajaka** [open-metadata/OpenMetadata#15427]
**Affected module**
column lineage graph

**Describe the bug**
There is no column lineage displayed between VIEW and TABLE when VIEW has been created with subquery from multiple tables

**To Reproduce**
```
create materialized view test_schema.sales_current2 as (
    WITH current_or_previous AS (
        SELECT
            MAX(data_release_version) AS data_release_version
        FROM metadata_schema.datamart_run
        WHERE dag_id = 'test_id'
    ) select eventid, listid, salesrow from test_schema.sales where salesrow=(select data_release_version from current_or_previous));
```
<img width="642" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/54989457/77a90137-c843-403b-8199-17a3eab7b1c6">

**Expected behavior**
column lineage displayed between TABLE and VIEW

**Version:**
 - OS: docker.getcollate.io/openmetadata/server:1.2.3
 - Python version:
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/ingestion:1.2.3
**Additional context**
When view create with CREATE VIEW command column lineage displayed correctly

**Comment by ulixius9** [comment]
@JahJajaka can you please also share which source you are referring to? is it snowflake?

**Comment by JahJajaka** [comment]
@ulixius9 sorry forgot to mention it is Redshift

**Comment by ulixius9** [comment]
closing this ticket moving query to #7427
