### ISSUE TITLE
Column lineage is not created for Redshift UNION ALL within subquery

### ISSUE THREAD

**Issue by JahJajaka** [open-metadata/OpenMetadata#15423]
**Affected module**
Column lineage graph

**Describe the bug**
Column lineage is not created for Redshift UNION ALL within subquery
<img width="680" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/54989457/229b81e6-7931-4e86-aa08-67b12e67ccc4">

**To Reproduce**
```
insert into test_schema.union_all_test
with initial_sub as (select eventid, listid, salesrow
from test_schema.sales),
union_sub_test as (
select eventid, listid, salesrow
from initial_sub
where salesrow='Yes'
union all
select eventid, listid, salesrow
from initial_sub
where salesrow='No')
select eventid, listid, salesrow from union_sub_test where listid in(500,501,502);
```

**Expected behavior**
Column lineage displayed between 'sales' and 'union_all_test' tables

**Version:**
 - OS: docker.getcollate.io/openmetadata/server:1.2.3
 - Python version:
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/ingestion:1.2.3

**Comment by ulixius9** [comment]
closing this ticket moving it to https://github.com/open-metadata/OpenMetadata/issues/7427
