### ISSUE TITLE
Azure SSO Issue due to MSAL version

### ISSUE THREAD

**Issue by Nemeczek** [open-metadata/OpenMetadata#15421]
**Affected module**
Does it impact the UI, backend?

**Describe the bug**
Security at work requires us to have "accessTokenAcceptedVersion": 2. Which changes the version of the token to v2. After downgrading the token version to v1 the OpenMetadata SSO Azure Auth works. 

**To Reproduce**

Set accessTokenAcceptedVersion to 2 in the App Registration Manifest and try to login using Azure SSO.

**Expected behavior**
Login should work with the newest tokens from MSFT. 

**Version:**
 - OpenMetadata version: [1.3.0]

**Additional context**
We humbly ask for an upgrade of the frontend dependencies:

`   "@azure/msal-browser": "^2.37.0",
    "@azure/msal-react": "^1.5.11",`

to the latest major releases:

`   "@azure/msal-browser": "^3.10.0",
    "@azure/msal-react": "^2.0.12",`

Also we noticed that SSO works - but the Browser needs to allow PopUps and Redirections in order to work.

**Comment by Sachin-chaurasiya** [comment]
Hello @Nemeczek, We have bumped the versions, and here is the PR https://github.com/open-metadata/OpenMetadata/pull/15509, it would be great if you could help us verify the changes, thanks.
