### ISSUE TITLE
increase the server response rate for endpoint "GET /v1/dataQuality/testCases"

### ISSUE THREAD

**Issue by Alexandr-Nedomets** [open-metadata/OpenMetadata#15426]
**Affected module**
> Module openmetadata-service
> class org.openmetadata.service.security.mask.PIIMasker 
> method getTestCases(...)

**Describe the bug**
The bug affected the performance of the endpoint "GET /v1/dataQuality/testCases".
the same object"Table" is requested in a loop for each object "TestCase"
This causes the response speed from the server to drop
[Method that affects performance](https://github.com/open-metadata/OpenMetadata/blob/4df94ed24db1cd615aac60ecb429334bc843cc7f/openmetadata-service/src/main/java/org/openmetadata/service/security/mask/PIIMasker.java#L145)
**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Faster response from the server for endpoint "GET /v1/dataQuality/testCases".

**Version:**
 - OS: all
 - Python version: all
 - OpenMetadata version: all
 - OpenMetadata Ingestion package version: all

**Additional context**

**Comment by Alexandr-Nedomets** [comment]
I'm ready to do this issue
if all ok, assign to me

**Comment by TeddyCr** [comment]
Hey @Alexandr-Nedomets just assigned it to you. 

> the same object"Table" is requested in a loop for each object "TestCase"
Regarding 👆keep in mind that when requesting test cases there is no guarantees the test cases belong to the same table. Hence, `ResultList<TestCase> testCases` can hold test cases from different tables.

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/15442
