### ISSUE TITLE
Query entity updates & Uniqueness

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#15437]
We are currently storing a lot of change event information about queries. Review:
- how can we ensure query uniqueness -> based on https://github.com/open-metadata/OpenMetadata/pull/13129
- which ops are we doing in the usage workflow that might be causing multiple redundant updates

**Comment by harshach** [comment]
lets use the existing ticket for this https://github.com/open-metadata/OpenMetadata/issues/11868
