### ISSUE TITLE
Hive Profiler ingestion not working

### ISSUE THREAD

**Issue by amitdubey07** [open-metadata/OpenMetadata#15435]
**Affected module**
This issue affects the Profiler Ingestion and Data Quality Framework.

**Describe the bug**
I am utilizing OpenMetadata 1.1.7 and Hive 2.3.0. I have successfully created Hive dataservices in OpenMetadata and ingested the Hive metadata. However, I am encountering an issue while ingesting the Hive profiler. Upon reviewing the Airflow logs, it appears that the queries being generated are not supported by Hive. 
Below are the problematic queries:

`SELECT avg(LEN(`username`)) AS `mean`, count(`username`) AS `valuesCount`, count(DISTINCT `username`) AS `distinctCount`, MIN(LEN(`username`)) AS `min`, min(LEN(`username`)) AS `minLength`, MAX(LEN(`username`)) AS `max`, max(LEN(`username`)) AS `maxLength`, SUM(CAST(CASE WHEN (`username` IS NULL) THEN %(param_1)s ELSE %(param_2)s END AS BIGINT)) AS `nullCount`, STDDEV_POP(LEN(`username`)) AS `stddev`, SUM(CAST(LEN(`username`) AS BIGINT)) AS `sum`
FROM `my_db`.`emp_tbl`
LIMIT 10`

**To Reproduce**
To reproduce this issue, follow the steps below:
1. Create the Hive table in the Hive server.
2. Create and execute the Hive metadata ingestion.
3. Create and execute the Hive profiler ingestion.
4. Review the error logs in the Airflow task.

**Expected behavior**
I have tested the same query in the Hive console, and it produces the same error. I replaced the LEN function with the LENGTH function, and it works correctly.

**Version:**
- OS: Debian GNU/Linux 11
- Python version: 3.8
- OpenMetadata version: 1.1.7
- OpenMetadata Ingestion package version: openmetadata-ingestion[airflow]==1.1.7
 

**Additional context**
The Profiler ingestion generates queries that are not fully supported by Hive. Adjustments may be needed to ensure compatibility.

**Comment by ayush-shah** [comment]
Not an issue in the latest openmetadata version 🙏 closing this. Thanks

**Comment by amitdubey07** [comment]
@ayush-shah @TeddyCr I am upgrading the OpenMetadata version to 1.3.0, and I have attached the log files for OpenMetadata 1.1.7.

**Comment by ayush-shah** [comment]
@amitdubey07 if you reproduce the same issue, feel free to open the issue, and attach the logs for the same 🙏

**Comment by amitdubey07** [comment]
Thanks @ayush-shah @TeddyCr After upgrading the openmetadata to 1.3.0, hive profiler ingestion is working
