### ISSUE TITLE
[Bug] Search Indexing drops whole batch for failure in case of User Entity 

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#15450]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 please add details while issues. Most of the issues do not have any comments or context. Its hard for others to pick up and understand what to do for a given issue.

**Comment by mohityadav766** [comment]
@harshach this is fixed

**Comment by harshach** [comment]
@mohityadav766 did we cherry-pick it into 1.3.2?
