### ISSUE TITLE
Upgraded 1.3.0, did not see knowledge base

### ISSUE THREAD

**Issue by create-co** [open-metadata/OpenMetadata#15456]
![image](https://github.com/open-metadata/OpenMetadata/assets/132736315/68b2af8e-f703-4259-b058-eee278776c5d)
![image](https://github.com/open-metadata/OpenMetadata/assets/132736315/dc4ddc7f-5cad-450e-a1e0-bb9d48e5ec81)

What is the reason why the knowledge base is not displayed?
I read the update log of git. I have updated this feature.

**Comment by KsM00000** [comment]
Isn't Knowledge Center is Collate exclusive?
![image](https://github.com/open-metadata/OpenMetadata/assets/79855848/e02e448f-ce3d-466b-afa6-800aa059c3c3)

**Comment by jsampaiog** [comment]
@create-co, Knowledge base is Collate exclusive

**Comment by create-co** [comment]
I updated from 1.2.2 to 1.3.0. I think UI has been updated, but I don't see the entry to the knowledge base. Do you need any separate processing?
![image](https://github.com/open-metadata/OpenMetadata/assets/132736315/996db0cc-e633-4616-bd43-adf4ad34f35b)
Is this supposed to be the new UI for 1.3.0?

**Comment by KsM00000** [comment]
@create-co dude. You have **OpenMetadata**. OpenMetadata is free opensource project.
Knowledge Center (or knowledge base, whatever) is **Collate** exclusive feature. Collate is paid SAAS project. It is related to OpenMetadata, but it is separate project,
OpenMetadata 1.3 **doesn't have** Knowledge Center.

**Comment by create-co** [comment]
OK，thanks

**Comment by pmbrull** [comment]
hi that's correct. Knowledge Base is a SaaS only feature. You can get more info about Collate's SaaS here https://www.getcollate.io/. Thanks
