### ISSUE TITLE
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:mysql://mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC) for user 'openmetadata_user': Communications link failure

### ISSUE THREAD

**Issue by kingkong2019** [open-metadata/OpenMetadata#15467]
**Affected module**
docker compose up -d ：
service "execute-migrate-all" didn't completed successfully: exit 1

**Describe the bug**
docker compose  logs execute-migrate-all:
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:mysql://mysql:3306/openmetadata_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC) for user 'openmetadata_user': Communications link failure

**To Reproduce**
1、download docker-compose.yml  from 1.3.0 release;
2、execute command：docker compose up -d；get prompt：service "execute-migrate-all" didn't completed successfully: exit 1。
3、docker ps
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS                 PORTS                                            NAMES
0c855885b20c        docker.elastic.co/elasticsearch/elasticsearch:8.10.2   "/bin/tini -- /usr/l…"   2 hours ago         Up 2 hours (healthy)   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   openmetadata_elasticsearch
91db81ed64e2        docker.getcollate.io/openmetadata/db:1.3.1             "/entrypoint.sh --so…"   2 hours ago         Up 2 hours (healthy)   0.0.0.0:3306->3306/tcp, 33060-33061/tcp          openmetadata_mysql
4、docker exec -it 91db81ed64e2 /bin/bash, can login use"mysql -u openmetadata_user -p " successfully.

**Expected behavior**

**Version:**
 - OS: [linux ]
 - Python version: 3.8.5
 - OpenMetadata version: [1.3.0]
 - OpenMetadata Ingestion package version: [1.3.0]

**Additional context**
NA

**Comment by pmbrull** [comment]
hi @kingkong2019, this might be a config error / based on the environment. Please reach out on Slack https://slack.open-metadata.org/ since we most likely will need more info. Thanks
