### ISSUE TITLE
Connector for JunoDB

### ISSUE THREAD

**Issue by mbarki-mohamed** [open-metadata/OpenMetadata#15479]
**Is your feature request related to a problem? Please describe.**
It would be awesome if we can add a JunoDB connector; JunoDB is the core database that powers Paypal and it was open sourced last year (https://github.com/paypal/junodb)

**Comment by pmbrull** [comment]
for anyone that would like to contribute https://docs.open-metadata.org/v1.3.x/developers/contribute/developing-a-new-connector

**Comment by sabareesanravi1** [comment]
I will take up this enhancement to build a connector for junoDB. @mbarki-mohamed . Thanks for the references @pmbrull

**Comment by iamskp11** [comment]
Hey @pmbrull , If this is not being worked upon, I would like to take this task. Please assign. Thanks!

**Comment by harshach** [comment]
@iamskp11 are you planning on contributing. We are closing this as not planned.If you open a PR, you can re-open this issue
