### ISSUE TITLE
Add SSL support for Presto Connector

### ISSUE THREAD

**Issue by hatakag** [open-metadata/OpenMetadata#15477]
**Feature**
SSL support for Presto Connector

**Describe the task**
A new feature allowing users to integrate SSL in the Metadata Ingestion Connector for Presto by adding SSL config under connectionArguments (Similar to _verify_ parameter in Trino)

**Comment by pmbrull** [comment]
covered here https://github.com/open-metadata/OpenMetadata/issues/14113
