### ISSUE TITLE
[Perf] Create Partition for Change_event

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#15474]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
The change_event table grow very fast and the entries can be huge in the table.
We should create partition for that table based on time if the entries are 7 days , 15 days and 30 days cc @harshach  (need accurate information here what timeline partition to create?) 
Then the user can remove this partitions. 
- We can also utilise our application framework to take care of this , where a app can be created to cleanup based on retentionPeriod in app configuration 

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 @Siddhanttimeline Lets build the retention policy app , I think @sushi30 looking into it. 
We should make that as a retention policy and delete the events that older than 3 days by default and allow users to change it.
In future we can provide an option to write to another table as a archival
