### ISSUE TITLE
Backend or Ingestion Framework not working with SSO

### ISSUE THREAD

**Issue by Gowtham029** [open-metadata/OpenMetadata#15489]
**Affected module**
backend or Ingestion Framework

**Describe the bug**
I have integrated Azure SSO with Open-metadata and can access the UI without any issues, but the ingestion is not working with the JWT generated.

I got the below errors:

`Suppressed: com.auth0.jwk.SigningKeyNotFoundException: No key found in https://login.microsoftonline.com/common/discovery/keys with kid **XXXXXXX-9f76-gdjs-a92j-XXXXXXX**`

`Suppressed: com.auth0.jwk.NetworkException: Cannot obtain jwks from url https://open-metadata.example.com/api/v1/system/config/jwks`

I was able to get a response from `/api/v1/system/config/jwks`
```json
{
  "keys": [
    {
      "kty": "RSA",
      "kid": "XXXXXXX-9f76-gdjs-a92j-XXXXXXX",
      "n": "ANl0x260vLmL_kx8Hhg4KkXIgk2SSFNDbmj1EE-N1e6EII9xBabVskXdEOsWY7H-jvM9s1mXdKjUGzJu6iHJhNeUxUzgVBiW6CN28sfi0s4Oq2V6-Y3av_CKj-_zmokQLCw43nwvOQ2_jeyBPh5codW3z_nCDq4fazWcbFybnOpZaGRNM_QiAdJJ4dZi7BcUH1PygYA3S_6SwcKvSpeZ0ur3k4he4KZS7K-tSjlUc8qMlG1e_kz2_pV-HBhI8WjG9DLgqoqGcAf6sWVOnNmYrAYDLtqWsz2U=",
      "e": "AQAB",
      "alg": "RS256",
      "use": "sig"
    }
  ]
}
```

**To Reproduce**
I followed this [document](https://docs.open-metadata.org/v1.2.x/deployment/security/jwt-troubleshooting)

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/23335311/726ea416-7b52-410f-b6ab-ad6f67eec6eb)

**Expected behavior**
The ingestion should work with SSO enabled.

**Version:**
 - OS: Docker
 - Python version:
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]== 1.2.3`]

**Additional context**
```env
AUTHENTICATION_PUBLIC_KEYS=[https://login.microsoftonline.com/common/discovery/keys, https://open-metadata.example.com/api/v1/system/config/jwks]
```

**Comment by harshach** [comment]
@Gowtham029 thiss is a configuration issue on your side. Please use https://slack.open-metadata.org and ask this question in support
