### ISSUE TITLE
OMD 1.3.0 Java client(gateway)'s constructor bug.

### ISSUE THREAD

**Issue by oringnam** [open-metadata/OpenMetadata#15499]
**Affected module**
OMD-client, JAVA SDK

**Describe the bug**
There is an error in the OMD constructor of the Java client regarding the apiClient invocation. The initClient invocation is split into two, and one of them calls the apiClient object without any initialization work.

**To Reproduce**
- [omd 1.3.x omd gateway](https://github.com/open-metadata/OpenMetadata/blob/1.3.1-release/openmetadata-clients/openmetadata-java-client/src/main/java/org/openmetadata/client/gateway/OpenMetadata.java#L42-L70)
```java
  public OpenMetadata(OpenMetadataConnection config) {
    initClient(config);
    validateVersion();
  }

  public OpenMetadata(OpenMetadataConnection config, boolean validateVersion) {
    initClient(config);
    if (validateVersion) validateVersion();
  }

  public void initClient(OpenMetadataConnection config) {
    Feign.Builder builder =
        Feign.builder()
            .encoder(new FormEncoder(new JacksonEncoder(apiClient.getObjectMapper())))
            .decoder(new JacksonDecoder(apiClient.getObjectMapper()))  // <-- the edge point
            .logger(new Slf4jLogger())
            .client(new OkHttpClient());
    initClient(config, builder);
  }

  public void initClient(OpenMetadataConnection config, Feign.Builder builder) {
    apiClient = new ApiClient();
    apiClient.setFeignBuilder(builder);
    AuthenticationProviderFactory factory = new AuthenticationProviderFactory();
    apiClient.addAuthorization("oauth", factory.getAuthProvider(config));
    String basePath = config.getHostPort() + "/";
    apiClient.setBasePath(basePath);
    apiClient.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);
  }
```

**Expected behavior**
The initializing apiClient has move `initClient(OpenMetadataConnection config, Feign.Builder builder)` to `initClient(OpenMetadataConnection config)`
```java
  public void initClient(OpenMetadataConnection config) {
    apiClient = new ApiClient();
    Feign.Builder builder =
        Feign.builder()
            .encoder(new FormEncoder(new JacksonEncoder(apiClient.getObjectMapper())))
            .decoder(new JacksonDecoder(apiClient.getObjectMapper()))
            .logger(new Slf4jLogger())
            .client(new OkHttpClient());
    initClient(config, builder);
  }

  public void initClient(OpenMetadataConnection config, Feign.Builder builder) {
    apiClient.setFeignBuilder(builder);
    AuthenticationProviderFactory factory = new AuthenticationProviderFactory();
    apiClient.addAuthorization("oauth", factory.getAuthProvider(config));
    String basePath = config.getHostPort() + "/";
    apiClient.setBasePath(basePath);
    apiClient.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);
  }
```

**Version:**
 - OS: -
 - Python version: - 
 - OpenMetadata version: [e.g. 0.8] 1.3.x (1.3.0, 1.3.1)
 - OpenMetadata Ingestion package version: -

**Additional context**
- Related Issue: #15065
- Slack Discussion: https://openmetadata.slack.com/archives/C02B6955S4S/p1709779501286299

**Comment by micnori** [comment]
Hi! It seems the bug is still present also in 1.3.2. Could you fix it as soon as possible? In this moment it is impossible to use the java sdk :(

**Comment by oringnam** [comment]
@micnori Hi!
Could I know the problem point?
I will fix it untill this weekend.

**Comment by micnori** [comment]
> @micnori Hi! Could I know the problem point? I will fix it untill this weekend.

It's the same bug explained here: when I try to create a new instance of gateway "new OpenMetadata(config)" I receive the error: "java.lang.NullPointerException: Cannot invoke "org.openmetadata.client.ApiClient.getObjectMapper()" because "this.apiClient" is null".

**Comment by oringnam** [comment]
> > @micnori Hi! Could I know the problem point? I will fix it untill this weekend.
> 
> It's the same bug explained here: when I try to create a new instance of gateway "new OpenMetadata(config)" I receive the error: "java.lang.NullPointerException: Cannot invoke "org.openmetadata.client.ApiClient.getObjectMapper()" because "this.apiClient" is null".

It seems that the commit was not reflected in the 1.3.2 release.
- main:  https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-clients/openmetadata-java-client/src/main/java/org/openmetadata/client/gateway/OpenMetadata.java#L52-L61
- release-1.3.2: https://github.com/open-metadata/OpenMetadata/blob/1.3.2-release/openmetadata-clients/openmetadata-java-client/src/main/java/org/openmetadata/client/gateway/OpenMetadata.java#L52-L60

**Comment by oringnam** [comment]
@harshach Could you please check this?

**Comment by oringnam** [comment]
@micnori it confirmed on 1.4.0.
