### ISSUE TITLE
Links in notification e-mails don't work and end in 404

### ISSUE THREAD

**Issue by Helavater** [open-metadata/OpenMetadata#15492]
**Affected module**
UI+backend

**Describe the bug**
When notification e-mails are received links included in wrong URI.

https://metadata.rara.ee/tag/PII.NonSensitive
https://metadata.rara.ee/glossaryTerm/erb_business_glossary.test

**To Reproduce**
Set up notifications for Glossary changes.

Screenshots or steps to reproduce

**Expected behavior**
Link in the e-mail does not need modification by hand.

**Version:**
 - OS: Ubuntu 22.04
 - Python version: 
 - OpenMetadata version: 1.3.0 (same issue was with 1.2.4)
 - OpenMetadata Ingestion package version: openmetadata-ingestion-docker 1.2.4 (at the moment no active ingestion is running and this component will be updated)

**Comment by IceS2** [comment]
Should be fixed by https://github.com/open-metadata/OpenMetadata/pull/15546

**Comment by mohityadav766** [comment]
This will be fixed in 1.3.2
