### ISSUE TITLE
Webhooks alert do not work

### ISSUE THREAD

**Issue by 969937484** [open-metadata/OpenMetadata#15505]
**Describe the bug**
I created an alert for webhooks,but it not worked,i can not find any message for it.

**Version:**
 - OS: Linux
 - Python version: 2.7.5
 - OpenMetadata version: 1.3.0
 - OpenMetadata Ingestion package version: 

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/69505827/e4b4edce-ca0d-4311-b3da-361194a53642),

**Comment by harshach** [comment]
@969937484 please do not open github issues before confirming this is indeed a bug, use our slack https://slack.open-metadata.org to get in touch with us
