### ISSUE TITLE
Failed to add Data Product Asset to a Glossary term - "Invalid field name tags":

### ISSUE THREAD

**Issue by Yayg** [open-metadata/OpenMetadata#15508]
Hi everyone and thanks for your great work on this product:

**Affected module**
Backend

**Describe the bug**
When trying to add a Data Product Asset to a Glossary term I get an error with "Invalid field name tags":
![image](https://github.com/open-metadata/OpenMetadata/assets/4986194/76b28372-d33b-4329-9b6a-48994945ff1c)

When trying to add the glossary term as an asset of the Data Product after clicking "Save" nothing happens.
The versioning doesn't change and there are no logs neither on the UI or in the pod stdout.

**To Reproduce**
- add a Data Product Asset to a Glossary term
- add the glossary term as an asset of the Data Product

**Expected behavior**
The asset to be added

**Version:**
 - OS: Deployed though Kubernetes helm chart latest version
 - Python version: NA
 - OpenMetadata version: 1.3
 - OpenMetadata Ingestion package version: 1.3

Thanks for any fix or solution! :)

**Comment by harshach** [comment]
@karanh37 data product doesn't have tags / terms as a field. Lets remove data product index from glossary add asset page.
