### ISSUE TITLE
Make Elasticsearch docs page procedural

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#1550]
Let's make this page procedural with step-by-step instructions.
https://docs.open-metadata.org/connectors/elastic-search

In its current form the distinction between the two config files is unclear.

It is also not clear that we should be working from clone of the repo to get the ingestion subdirectory. 

The above seem to be problems across the connectors docs pages.

**Comment by harshach** [comment]
It should be separated from connectors page, as this is internal to the service itself and not necessarily a connector to fetch metadata inside elasticsearch

**Comment by harshach** [comment]
Lets also add some of these details https://docs.google.com/document/d/1-Z7JEhevp3zu780TDXiGPJ6FJsSIScgWGNGL_Pj3Vrk/edit#heading=h.34kftgotq69z on how to access a SSL enable elastic search cluster
