### ISSUE TITLE
UI: Not able to copy query from query code editor

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#15561]
**Affected module**
UI

**Describe the bug**
Not able to copy query from query code editor, checkout the below video 

https://github.com/open-metadata/OpenMetadata/assets/39544459/4d5d111f-ae6c-4861-bf72-b226b8842d92

**Comment by Sachin-chaurasiya** [comment]
@Ashish8689 , let's add the copy button like we have in other places.
