### ISSUE TITLE
Backend: Api end point for test case states count (pass/failed/aborted.)

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#15593]
currently, for showing states for all the columns and table we need to fetch all the test cases of that table and column and show the count for pass failed and aborted,
With the help of a new endpoint, we can avoid heavy calls from the UI side and get only the required information.
API should contains the count details of table and column test cases

**Comment by TeddyCr** [comment]
@ShaileshParmar11 you have an endpoint for that will compute this info from ES.

`/v1/dataQuality/testSuites/executionSummary?testSuiteId={id}`

You need to call this from the DQ page of the entity.

**Comment by ShaileshParmar11** [comment]
> executionSummary

Thanks @TeddyCr for the details, however, the requirement here is to call a single API to fetch all the counts related to the table and its columns, 
example:  if the table has 5 columns then, UI will make only a single call, and BE will provide all the counts for the table and its columns with bifurcated with pass/failed/aborted

**Comment by TeddyCr** [comment]
You mean you want a count broken down by column / table?
e.g.
```
[
{"fqn": "XYZ", passed: 4, failed: 5},
{"fqn": "XYZ.colA", passed: 4, failed: 5}
....
]
```

**Comment by ShaileshParmar11** [comment]
correct @TeddyCr, to show the counts of the column tests in schema tab
https://github.com/open-metadata/OpenMetadata/issues/14440

**Comment by harshach** [comment]
@TeddyCr lets take in entityFQN as the parameter and return all the tests at table or column level back along with their statuses

**Comment by harshach** [comment]
@TeddyCr are you planning to finish this up?

**Comment by TeddyCr** [comment]
Yep that is the plan
