### ISSUE TITLE
4000 character limit for stored procedures MS SQL

### ISSUE THREAD

**Issue by RabochiyYan** [open-metadata/OpenMetadata#15607]
**Affected module**
Ingestion Framework

**Describe the bug**
Query that openmetadata use for getting stored procedure definition cannot get more than 4000 characters in MS SQL connector

**To Reproduce**
Run metadata ingestion in ms sql connector with stored procedures being turned on.
Than open stored procedure which has more than 4000 characters.

**Expected behavior**
Full definition of stored procedures

**Version:**
 - OS: windows
 - Python version: Python 3.10.13
 - OpenMetadata version: 1.3.0
 - OpenMetadata Ingestion package version :openmetadata/ingestion:1.3.0

**Additional context**
![Screenshot_6](https://github.com/open-metadata/OpenMetadata/assets/142233379/93fa1e55-5443-4656-8495-0b4a04184751)
https://stackoverflow.com/questions/48791194/view-definition-in-information-schema-views-is-limited-to-4000-characters

**Comment by pmbrull** [comment]
hi @RabochiyYan, thanks for opening the issue.

I also saw you merged a PR directly to the 1.3.0 release branch https://github.com/RabochiyYan/OpenMetadata/pull/1/files

The correct approach here would be to have it in `main`, so that we can review the changes properly and ensure that future versions have the same patch.

Would you be able to pop the same change in `main` in a new patch?

Thanks

**Comment by RabochiyYan** [comment]
Hi! Donehttps://github.com/RabochiyYan/OpenMetadata/pull/219.04.2024, 08:22, "Pere Miquel Brull" ***@***.***>:
hi @RabochiyYan, thanks for opening the issue.
I also saw you merged a PR directly to the 1.3.0 release branch https://github.com/RabochiyYan/OpenMetadata/pull/1/files
The correct approach here would be to have it in main, so that we can review the changes properly and ensure that future versions have the same patch.
Would you be able to pop the same change in main in a new patch?
Thanks

**Comment by pmbrull** [comment]
Hi @RabochiyYan, thanks! I can see the PR here https://github.com/RabochiyYan/OpenMetadata/pull/2 but it's not against the main OM repo, but directly against your fork.

Maybe you need to change the base branch in the PR so that we can merge it to the main repository :)

Thanks!

**Comment by pmbrull** [comment]
hi @RabochiyYan , works wonders now. Thank you for the help :)

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/16002
