### ISSUE TITLE
Lineage: Add support for pipeline as node

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#15623]
Currently from UI we only support pipeline as an edge between two tables, we should allow pipeline to be added as edge between any two entities, and we should also allow to add pipeline as node not only as an edge.

we need to also decide how to handle such scenarios
![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/732ff6d4-b59e-4a25-af4d-af3e9003cfc5)

**Comment by mohityadav766** [comment]
@karanh37 is this done ?

**Comment by karanh37** [comment]
Nope, support is needed from ES end to make it work.

**Comment by obaltian** [comment]
Hi, is it possible to plan it to the nearest future? This issue rn is a blocker for us to use OM in ~200-member-sized organisation.

**Comment by ulixius9** [comment]
closing by https://github.com/open-metadata/OpenMetadata/pull/17020
