### ISSUE TITLE
[Feature Request] Filter by database name

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#1563]
Hello Guys,

I think would be good on explorer page a way to filter by database, for example in my case we use Glue(Hive) our tables are organized by database.

<img width="1792" alt="Captura de Tela 2021-12-05 às 20 07 15" src="https://user-images.githubusercontent.com/36298331/144767729-fa6f09e0-0df6-4497-91ca-c652f568fbc3.png">

On the middle, would be good to know which database the tables belongs.

Thank you

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya here is the backend change https://github.com/open-metadata/OpenMetadata/pull/1580
