### ISSUE TITLE
Backend: List API throws permission error, when only ViewAll permission is given with conditions

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#15638]
List API throws the error even when the user is the owner of some of the glossary and has viewAll permission

Below are the steps to reproduce:
- Remove the default role and  policy from the organisation team
- Create a new policy with the information provided in the screenshot
- add the newly created policy to the organisation
- Add one glossary and glossary term,
- Create new user, and make him owner of glossary and glossary term
- try accessing glossary list api from newly added users creds
![image (5)](https://github.com/open-metadata/OpenMetadata/assets/71748675/e2a3af29-39d5-4f1d-a2d7-6a71e58b85a7)

**Comment by chirag-madlani** [comment]
Duplicate: #15677
