### ISSUE TITLE
Window environment deployment documentation

### ISSUE THREAD

**Issue by create-co** [open-metadata/OpenMetadata#15642]
1. Whether it is possible to produce a document for deployment in window environment. Now there are many problems in deployment in window environment, and some shell scripts will report errors.
2. Building wsl in window environment requires a high level of computer configuration.
3. Hope to produce a document that can be started and developed in window environment.

**Comment by TeddyCr** [comment]
@create-co do you want to contribute to this? 😊

**Comment by harshach** [comment]
we will not be supporting windows environment except for WSL
