### ISSUE TITLE
Lineage View Issue

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#15641]
**Affected module**
The impact is on the visualisation of the lineage

**Describe the bug**
The impact is on the display of the lineage, when collapsing or expanding a child of the lineage.
It appears in many lineages of different assets, we see that it appears with complex lineages, with simple ones we have not seen the error reproduced.
For example this is a lineage that looks like this when you open it:
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/80c65b5a-93b6-4538-a0de-308325ffaeab)

**To Reproduce**

For example, collapse here.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/b6a6ee39-c8a5-4a19-be18-b1a44399acc4)

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/ff44c550-7a4a-43d6-a82e-e705cb0baa15)

If I continuing to collapse
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/1779c514-5005-4cf9-94de-0261c208ce69)

Some screenshots sent by our users:
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/947c137c-fffe-46a0-8f16-97bbcf814213)
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/a310b2ed-1839-4244-b462-d9fb0e57bfd3)

**Expected behavior**
It always occurs in the same entities, it is easily reproducible.

**Version:**
 - OpenMetadata version: 1.3.1

Thanks,
Carlos Sanz

**Comment by karanh37** [comment]
@triquinielas - hey this happens if the reindexing hasn't happened correctly.
Can you reindex and try reproducing ?

**Comment by TeddyCr** [comment]
@triquinielas we'll close as we have not heard back from you. Please re open it if you are still seeing the issue after proceeding with the steps @karanh37 has defined.
