### ISSUE TITLE
Bug: Test Case Result UI. Graph does not extend to negative values on vertical axis

### ISSUE THREAD

**Issue by tassosgeo** [open-metadata/OpenMetadata#15667]
**Affected module**
It impacts the UI

**Describe the bug**
The Graph in Test Case Result UI does not extend to negative values

**To Reproduce**
Create a test with min column value a negative number. 
Screenshot showing the issue:
![image](https://github.com/open-metadata/OpenMetadata/assets/61195503/3bcbf146-eff3-4a10-b558-1bf7f792eea0)

**Expected behavior**
The vertical axis of the graph should be extended to negative values

**Version:**
 - OS: run on docker on ubuntu 23.04 machine
 - OpenMetadata version: 1.3.1
 - OpenMetadata Ingestion package version: 1.3.1

**Additional context**
It is a visualization only issue

**Comment by ShaileshParmar11** [comment]
This has already been taken care of with #15368, and will be part of 1.3.2
<img width="1680" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/71748675/a6953e1c-6a7f-4294-8438-959fa03db84d">
