### ISSUE TITLE
Adding attributes to rows in a data table in “custom properties”

### ISSUE THREAD

**Issue by k103hub** [open-metadata/OpenMetadata#15717]
The metadata description of each row requires extensive description of business rules, such as the business meaning, etc.

**Comment by Sachin-chaurasiya** [comment]
Hello @k103hub, Thanks for creating the issue, It would be great if you share some examples of what you are looking for.

**Comment by k103hub** [comment]
![image](https://github.com/open-metadata/OpenMetadata/assets/45862662/657c1c94-1dbb-47cb-a5dd-710e8ea86d22)
fyi

**Comment by Sachin-chaurasiya** [comment]
> ![image](https://private-user-images.githubusercontent.com/45862662/317558205-657c1c94-1dbb-47cb-a5dd-710e8ea86d22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDc2MTgsIm5iZiI6MTcxMTYwNzMxOCwicGF0aCI6Ii80NTg2MjY2Mi8zMTc1NTgyMDUtNjU3YzFjOTQtMWRiYi00N2NiLWE1ZGQtNzEwZThlYTg2ZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZmY4MWUzODQxMTJkOGM5YzFhYWI4OTQ2YWRjYjhlMTIyNjk4ZmVjMGZlMTM0MDgxMDBjOTAzYWY4MzJmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UaODH0TCLG-qfhEmElumW_tHMcS-aMT7oCgI0ms9cVQ) fyi

Hello @k103hub , Can you please elaborate more as from image not clear what you want and why?

**Comment by k103hub** [comment]
Business personnel need to understand the column from additional dimensions

**Comment by TeddyCr** [comment]
@k103hub unclear what the ask is here. I'll be closing it. If you have a **detailed explanation** of the request feel free to re open it
