### ISSUE TITLE
lineage default stream 

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#15733]
**Is your feature request related to a problem? Please describe.**
In version 1.3 of OMD, the default behavior when opening lineage is 3 level downstream and 3 upstream. 
It can be very hard to read as a first step. 
Example from sandbox:
<img width="1361" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/37f83fb9-31c4-4146-9359-7ad80c81c46f">

**Describe the solution you'd like**
I think the default behvior should be 1 up and 1 down (as it was in 1.3 version). 

**Describe alternatives you've considered**
Decide on the UI what is your default required behavior. 

**Additional context**

**Comment by harshach** [comment]
duplicate https://github.com/open-metadata/OpenMetadata/issues/15408
