### ISSUE TITLE
Unable to approve a glossary Term

### ISSUE THREAD

**Issue by PedroMiguelFigueiredo** [open-metadata/OpenMetadata#15735]
**Affected module**
UI

**Describe the bug**
After creating a glossary term (don't aprove it yet), change it's name. The task shows one task, but the ui doesn't display it. So we're unable to approve the glossary term

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/6414408/94b68f36-6932-4fb0-a11f-6510a09ba3aa)

![image](https://github.com/open-metadata/OpenMetadata/assets/6414408/37fcac01-b38d-436f-8bcb-955d797060b7)

**Expected behavior**
To be able to approve.

**Version:**
 - OpenMetadata version: 1.3.1

**Additional context**

https://sandbox.open-metadata.org/glossary/Gloss%C3%A1rio%20Comercial.Folha%20de%20Or%C3%A7amento%20de%20Projeto%20(FOP)/activity_feed/tasks

**Comment by harshach** [comment]
@sonika-shah can you check if recent changes addressed this issue?
