### ISSUE TITLE
LDAP no working 1.3.1

### ISSUE THREAD

**Issue by wolfktl** [open-metadata/OpenMetadata#15737]
LDAP no working 1.3.1     
AUTHENTICATION_LDAP_HOST: ${AUTHENTICATION_LDAP_HOST:-"ldap.example.com"}
      AUTHENTICATION_LDAP_PORT: ${AUTHENTICATION_LDAP_PORT:-389}
      AUTHENTICATION_LOOKUP_ADMIN_DN: ${AUTHENTICATION_LOOKUP_ADMIN_DN:-"CN=s-openmetadata-1,OU=Openmetadata,OU=ServiceAccounts,OU=FL,DC=example,DC=com >
      AUTHENTICATION_LOOKUP_ADMIN_PWD: ${AUTHENTICATION_LOOKUP_ADMIN_PWD:-"passwordadmin}
      AUTHENTICATION_USER_LOOKUP_BASEDN: ${AUTHENTICATION_USER_LOOKUP_BASEDN:-"OU=FL,DC=example,DC=com"}
      AUTHENTICATION_LDAP_SSL_ENABLED: ${AUTHENTICATION_LDAP_SSL_ENABLED:-false}
      AUTHENTICATION_USER_MAIL_ATTR: ${AUTHENTICATION_USER_MAIL_ATTR:-"mail"}
AUTH_ROLES_MAPPING: ${AUTH_ROLES_MAPPING:-"CN=openmetadata_admins,OU=Openmetadata,OU=Roles,OU=FL,DC=example,DC=com":["Admin"],"CN=openmetadata_viewers,OU=Openmetadata,OU=Roles,OU=FL,DC=example,DC=com":["DataConsumer"]}
      AUTH_REASSIGN_ROLES: ${AUTH_REASSIGN_ROLES:-["Admin","DataConsumer"]}

User for mail no login

**Comment by TeddyCr** [comment]
@wolfktl does you LDAP object has the `mail` attribute?

**Comment by wolfktl** [comment]
yes

**Comment by wolfktl** [comment]
we use docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
