### ISSUE TITLE
Support for Oracle Stored Packages

### ISSUE THREAD

**Issue by KsM00000** [open-metadata/OpenMetadata#15742]
**Is your feature request related to a problem? Please describe.**
We have a lot of procedures in Oracle. But most of the procedures are in Oracle Packages, so during metadata ingestion they are ignored.

**Describe the solution you'd like**
It would be nice if procedures in packages were added as stored procedures, with a note/type that they were package procedures.

**Additional context**
Stored packages are also used in some other databases: Mariadb, PostgreSQL (Pro enterprise), maybe some other.

**Comment by nqvuong1998** [comment]
Hi @ayush-shah @harshach , I’m experiencing the same issue. In Oracle, stored procedures are primarily organized within packages, making this feature crucial for the lineage capabilities of OpenMetadata.

**Comment by baohan1999** [comment]
My organization has nearly 90% procedures that are managed by package, so that makes it lack most of procedures when showing. Can you please take a look and fix it if possible?

**Comment by ayush-shah** [comment]
@baohan1999 @nqvuong1998 we will take care of this as part of minor releases in 1.6.x or a part of 1.7, we will internally discuss the same and let you know..
It would be great if you folks can contribute around the same if in case it's urgent, we will help you around the code.

**Comment by AlexeySumin** [comment]
@ayush-shah Hi!
Am i right, that this feature will be released in 1.7, not in 1.6.x?
