### ISSUE TITLE
Correct error and typo in config Google SSO docs page

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#1574]
https://docs.open-metadata.org/install/enable-security/google-sso/google-config

For context:
https://openmetadata.slack.com/archives/C02B6955S4S/p1638799990269300

**Comment by ayush-shah** [comment]
also, there is a typo for principalDomain
![image](https://user-images.githubusercontent.com/40225091/144867488-7ab40e4d-4f62-4d23-ae8b-95dcfb497fa0.png)
Both the above images are from https://docs.open-metadata.org/install/enable-security/google-sso/google-config
