### ISSUE TITLE
Allow to disable SignUp page when using SAML Authentication

### ISSUE THREAD

**Issue by nqvuong1998** [open-metadata/OpenMetadata#15755]
**Is your feature request related to a problem? Please describe.**
When I set AUTHENTICATION_PROVIDER to "saml" and login successfully, OM will display the JOIN UI for signup.
![image](https://github.com/open-metadata/OpenMetadata/assets/49333414/673361be-6760-4b62-b3d0-6fdd1c12d23b)

**Describe the solution you'd like**
I expect that OM will offer the option to enable or disable this feature (JOIN UI) because there are occasions when companies prefer to restrict members from editing their information.

**Comment by TeddyCr** [comment]
@nqvuong1998 you have a `enableSelfSignup : ${AUTHENTICATION_ENABLE_SELF_SIGNUP:-true}` in the authentication config section.
