### ISSUE TITLE
EntitiyLink grammar does not handle a column with one character

### ISSUE THREAD

**Issue by sushi30** [open-metadata/OpenMetadata#15754]
**Describe the bug**

**To Reproduce**
Add this code to the test:

https://github.com/open-metadata/OpenMetadata/blob/884029f03120fe68ccdd3c8b9aac77f0e4c9983f/ingestion/tests/unit/metadata/utils/test_entity_link.py#L44-L50

```python
entity_link = "<#E::table::rds.dev.dbt_jaffle.customers::columns::n>"
assert get_table_or_column_fqn(entity_link) == "rds.dev.dbt_jaffle.customers.n"
```

```python
line 1:51 token recognition error at: 'n>'
line 1:53 no viable alternative at input '::'
```

## Screenshots

This also appears to be causing issues on the UI. This error is produced when trying to create a test suite:

![Screenshot 2024-03-28 at 18 17 37](https://github.com/open-metadata/OpenMetadata/assets/26347589/b6d7f38c-e275-4f9d-89e5-009843042521)

**Expected behavior**
Expect the test to pass

**Version:**
 - OS: Macos
 - Python version: 3.11
 - OpenMetadata version: 1.3.2

**Comment by TeddyCr** [comment]
fixed in https://github.com/open-metadata/OpenMetadata/pull/15758
