### ISSUE TITLE
[Feature Request] Profile and Table metadata as a separated things

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#1577]
Hello Everyone,

Please let me know if it make senses.

Here we use Glue as a metastore and Presto/Redshift like our query engines, if I understand right, the metadata collection and profile are very tied. So in our case I think it make sense to get metadata from Glue and get Profile from Presto for example.

Thank you.

**Comment by harshach** [comment]
@rubenssoto You could disable the Glue profiler by passing data_profiler_endabled=false and enable it from Presto.
We can definitely separate this out as another pipeline. But wanted to avoid having another pipeline to be enabled.
But if that's not a big issue we can separate this out.

**Comment by rubenssoto** [comment]
@harshach I will try that... but that way openmetadata will get metadata from both? The idea is to get metadata from glue and profiler from presto

**Comment by harshach** [comment]
@rubenssoto that's true. Let me provide separation here. 
You could however do one thing , In Glue config use the service_name same as presto. That way they are both pointing to same service and updates the same metadata.
This is a workaround but I see your point. We will provide a separation for this.

**Comment by harshach** [comment]
@rubenssoto do let us know if its a blocker, we will try to get in by 0.7 if not we can definitely get this in 0.8

**Comment by rubenssoto** [comment]
It is not a blocker, I'm trying only to anticipate some problems, with monthly release 0.8 is good.

**Comment by pmbrull** [comment]
Handling it as part of https://github.com/open-metadata/OpenMetadata/issues/1311

**Comment by pmbrull** [comment]
Hi @rubenssoto, this has been added as part of the 0.9 release. You can read about the new profiler and data quality in the [docs](https://docs.open-metadata.org/data-quality/data-quality-overview). Let us know if you have any feedback. Thanks 🙏
