### ISSUE TITLE
Drop and recreate MySQL and ES.

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1579]
I'd like to drop and recreate MySQL and ES schema while developing the Python part of OM. I don't have to do it so often in Java because the Java unit test class is doing it for me.

I was trying to use ```bootstrap/bootstrap_storage.sh``` but it complains that the directory ```libs``` doesn't exist.

I was thinking to change the code of the script like this:
```sh
LIBS_DIR="${BOOTSTRAP_DIR}"/../libs/
if [ -d "${LIBS_DIR}" ]; then
  for file in "${LIB_DIR}"*.jar;
  do
      CLASSPATH="$CLASSPATH":"$file"
  done
else
  CLASSPATH=`mvn -pl catalog-rest-service -q exec:exec -Dexec.executable=echo -Dexec.args="%classpath"`
fi
```

WDYT?

**Comment by harshach** [comment]
@amiorin That sounds good to me.
