### ISSUE TITLE
Losing assets after changing glossary terms hierarchy

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#15809]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**

- While changing glossary terms hierarchy which is having assets is not reflected after hierarchy/parent is being changed.
- After doing a re-index we can get it!

**Also Glossary parent renaming leads to all the assets being lost**

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/66266464/556cebbf-c2c5-4b1b-94d1-ac67228a4b83

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
It seems all relationships (not just assets) are getting lost (terms, tags, etc.)

**Comment by DovileKr** [comment]
Please note that Renaming Glossary affects:
- Loses Classification Tags
- Loses Asset Count (tables, columns)
- Loses Related Terms

**Comment by DovileKr** [comment]
Please note 1.4 in SANDBOX still has this bug @mohityadav766

**Comment by DovileKr** [comment]
We have upgraded to 1.4 pre and it still had this bug. Sandbox beta still has the bug, this time ever worse - **if glossary is renamed,** it "looses" all the terms under it.
If change name back - then it reappears.

https://github.com/open-metadata/OpenMetadata/assets/26750060/1a92d622-1b64-47bf-b887-e8cfa98024ad

**Comment by DovileKr** [comment]
@mohityadav766 ticket was closed however it is still a bug. 

Please try renaming GLOSSARY and the underlying glossaryTerms will lose their tags.
