### ISSUE TITLE
 I cannot add existing test to test suite

### ISSUE THREAD

**Issue by YuliyaSavulyak** [open-metadata/OpenMetadata#15810]
![image_720](https://github.com/open-metadata/OpenMetadata/assets/40895969/94b5fb52-982d-49b5-b5b4-2773c98257b8)
![image_720](https://github.com/open-metadata/OpenMetadata/assets/40895969/cf052fa4-4397-4a5c-aa02-36204de6672a)
![image_720](https://github.com/open-metadata/OpenMetadata/assets/40895969/3b72f073-8837-4f87-80cb-2263e2dc83e7)

**Comment by ShaileshParmar11** [comment]
We already have load on scroll feature! can you please confirm if that resolves your issue?

**Comment by harshach** [comment]
@YuliyaSavulyak can you address above comment ^

**Comment by ShaileshParmar11** [comment]
Hello, @YuliyaSavulyak, have you had a chance to try out the "load on scroll" feature? Please let us know if you're still experiencing any issues with it!

**Comment by chirag-madlani** [comment]
Hi @YuliyaSavulyak 
We are listing all the tests with scroll behaviour, Can you please confirm that works for you as well?

**Comment by YuliyaSavulyak** [comment]
Hello. Yes, it was fixed. Thank you!

**Comment by ShaileshParmar11** [comment]
Thanks @YuliyaSavulyak for confirming!
