### ISSUE TITLE
Custom Attribute could not show more than 5 Custom Attributes

### ISSUE THREAD

**Issue by phumdanai12** [open-metadata/OpenMetadata#15817]
I found issue about Custom Attribute could not show more than 5 Custom Attributes. For the detail as below

- select Select 'Glossary Term' or 'Database'
![MicrosoftTeams-image (73)](https://github.com/open-metadata/OpenMetadata/assets/151615349/6d172a4f-78e0-46e9-901d-e65e2595a763)
- click 'Add Property'
![MicrosoftTeams-image (74)](https://github.com/open-metadata/OpenMetadata/assets/151615349/afbf1552-1f5b-4a68-b095-845d17d35e5b)
- Create more than 5 Custom Attributes as below
![MicrosoftTeams-image (75)](https://github.com/open-metadata/OpenMetadata/assets/151615349/5a68d25c-d20c-4b5b-9559-3072e5fc9927)
-In the **Glossary Term Tab Show only maximum 5 Custom Attributes** 
![MicrosoftTeams-image (76)](https://github.com/open-metadata/OpenMetadata/assets/151615349/a13041c9-3673-4b8e-87ed-59f3af32cbba)

Version:

OS: CentOS Linux release 7.9.2009 (Core)
OpenMetadata version: 1.3.0
OpenMetadata Ingestion package version: ingestion:1.3.0

**Comment by Sachin-chaurasiya** [comment]
Hello @phumdanai12, Thanks for filing an issue, this issue has been fixed in 1.3.1, please upgrade to 1.3.1.

You can look here at all the custom properties are shown. https://sandbox.open-metadata.org/glossary/AC%20Domain.DO1/custom_properties
