### ISSUE TITLE
Qlik sense verify_disable off

### ISSUE THREAD

**Issue by dzhabrailovsn** [open-metadata/OpenMetadata#15821]
**Feature**
SSL.None param or verify_certs disable

**Describe the task**
Hello i do integration with qlik sense.
My QS is after WAF, to Qlik sense machine to WSS port i have only route by IP address .
I run openmetadata with docker-compose  and not found where i can make ssl.none or verify_certs = disable .
How can i run ingestion on QS when connecting by IP address of QS server ?
![image](https://github.com/open-metadata/OpenMetadata/assets/17762648/f4287b06-3ba3-4838-b51d-1d795c6a437b)

**Comment by ayush-shah** [comment]
same issue as https://github.com/open-metadata/OpenMetadata/issues/14973
closing it, can be referred/tracked from the above link
