### ISSUE TITLE
Users created via CSV import cannot login, but have to signup and get message 'Entity already exists'

### ISSUE THREAD

**Issue by sandervanlaar** [open-metadata/OpenMetadata#15835]
**Affected module**
UI

**Describe the bug**
Users who were imported via CSV import, cannot login, but are sent to the 'Join OpenMetadata' page. There the get the message 'Entity already exists'.

**To Reproduce**
I executed the following steps:

1. Clicked on: Settings > Team & User Management > Teams
2. Selected a Team from the list
3. Clicked on the 3 vertical dots, next to 'Add User', then 'Import'
4. Uploaded a CSV list of users

Then: 

1. for a user I created a password and sent the email and password to this user to signin on the page <OM address>:8585/signin
2. The user enters mail address and the given password and clicks 'Login'
3. Then the user is asked to 'Join OpenMetadata': 
![image](https://github.com/open-metadata/OpenMetadata/assets/7271324/ef262615-00e3-4615-90ef-16081b4fc11b)

4. The user enters her full name and clicks on 'Create'.

Then the message 'Entity already exists' pops up.

**Expected behavior**
Expected behavior: after login of the user should be redirected to the page http://localhost:8585/my-data.

**Version:**
 - OS: Windows Server 2022 Standard
 - Python version: Python 3.8.10
 - OpenMetadata version: 1.3.1
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==1.3.1

**Comment by harshach** [comment]
@sandervanlaar can you check with us in https://slack.open-metadata.org before opening a github issue.

The reason this might happen is because your login email id might not match the user's email.

**Comment by sandervanlaar** [comment]
The link to the Slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1712643880090489
The user uses her email address to login, which is identical to the email address in the User I created via the CSV import.

**Comment by mohityadav766** [comment]
this is done
