### ISSUE TITLE
improve the Chinese translation of openmetadata

### ISSUE THREAD

**Issue by xuhui1231** [open-metadata/OpenMetadata#15848]
**Is some content missing, wrong or not clear?**
The Chinese translation is incomplete：

**Describe the solution you'd like**
I want to improve the Chinese translation document. At present, I first translate some commonly used data sources and then improve the data quality module。

**Additional context**
![image](https://github.com/open-metadata/OpenMetadata/assets/51685494/4c04dddd-48e9-41cc-9255-87d25c872bc5)

**Comment by harshach** [comment]
@xuhui1231 Thanks for your interest in contributing to OpenMetadata.
Here are the steps https://docs.open-metadata.org/v1.3.x/developers/how-to-add-language-support
@chirag-madlani don't think we enabled translation on the side-bar documentation

**Comment by chirag-madlani** [comment]
@harshach do we support that, @Sachin-chaurasiya can you confirm once?
Also if it's supported let's add docs for the same that how can someone contribute to that

**Comment by Sachin-chaurasiya** [comment]
> @harshach we do support that, @Sachin-chaurasiya can you confirm once? Also if it's supported let's add docs for the same how can someone contribute to that

Hello @harshach @chirag-madlani  we have translation support for the sidebar documentation, currently it's only for `en` and `fr`, I will add the documentation for the same so that contributors can add the translation for other languages.
