### ISSUE TITLE
Y-Axis in custom metrics doesn't behave properly

### ISSUE THREAD

**Issue by fireball147** [open-metadata/OpenMetadata#15845]
**Affected module**
Impacts UI

**Describe the bug**
When I create the custom metrics for the table profile for a bigquery table, the chart's y-axis is not correct based on the value.
- The negative values are moving upwards instead of downwards 
- The vertical gap between two numbers is not consistent. The vertical gap was higher when the number moved by 7th decimal digit, but the vertical shift was lower when the next value was 10000x of previous value.
- When my first value was 0.2119, my second value was 2119, the chart line moved upwards. On third ingestion run, my value was 21.19, but instead of downward movement, the chart is still moving upwards.

**To Reproduce**

Screenshots or steps to reproduce
Negative number moving upwards
<img width="1084" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/19437360/63198366-4135-4e91-8268-465e99864215">

The last two numbers are 381.8, while all the numbers to the left of that are 0.01 to 0.03 (many of them are actually 0.038 with variation in 7th decimal digit. The vertical gap between 0.01 to 0.03 is higher that gap between 0.03 to 381.8
<img width="1074" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/19437360/b6e04bde-f11c-466d-a204-b50d92092119">

On y-axis, 2.1K is lower than 21.2
<img width="992" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/19437360/d36a16fa-df7d-42c6-b9d0-cb0cddb9a825">

**Expected behavior**
Expected behavior is that the y-axis should show negative values moving downwards, the scale or vertical gap between two numbers should be consistent, i.e. gap between 381 vs 0.0381 should be proportional to gap between 0.01 vs 0.0381.
Also, the values on the y-axis should be in increasing order 0.2 < 21.2 < 2119.

**Version:**
 - OS: Official Docker image used on macbook
 - Python version: 3.10.13
 - OpenMetadata version: 1.3.1
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/ingestion:1.3.1

**Additional context**
More details discussed in slack [here](https://openmetadata.slack.com/archives/C02B6955S4S/p1712551097522499)

**Comment by ShaileshParmar11** [comment]
The problem has been resolved in release 1.3.2, thanks to https://github.com/open-metadata/OpenMetadata/pull/15368. Please feel free to reopen the ticket if you encounter the issue again.
