### ISSUE TITLE
Request Access Workflow for assets inside Open Metadata

### ISSUE THREAD

**Issue by dfdf** [open-metadata/OpenMetadata#15855]
**Is your feature request related to a problem? Please describe.**
Today our users can do many things at the OpenMetadata's UI. They can see the available schemas, and tables, see a sample of the data, the queries executed, and so on. However if that user needs to request access (at the database level for example) to that asset, it needs to leave the tool and contact the owner of the data requesting it. And that process most of the time are made manually, the owner will receive the message (in some message tool, or email for example), evaluate the request, if the user can receive the access the owner will need to run the "grant queries" at the database to allow the user to access the data.

**Describe the solution you'd like**
Integrate a workflow inside OpenMetadata, where the user can for example click on the button "request access" and automatically a task and/or a message is sent to the owner, informing them that a new request access was made by some user to some asset. The owner can approve or reject, if approved the OpenMetadata tool can run the grant queries or at least generate an event to be used by an external worker. After that, the user can see it "request access task" completed and the result of it.

**Describe alternatives you've considered**
With the current API, we were able to do it using other trigger events, for example: The user clicks on "favorite" and that event externally triggers a lambda which is responsible for informing (on Slack) the owner and doing all the workflow for that request. But this is not ideal.

**Additional context**
Is very bad for our users to leave the tool just to ask for permission to query the asset. It would be a HUGE improvement in the user experience if we could add this inside the open metadata tool and I have not seen anything like this in any other catalog/governance tool. It does not seem to be something complex, we can start just controlling and informing about this workflow (and not running the grant queries) and later on improve this. 

**We can collaborate on this feature, but we do not know how to add new tabs/pages to the UI. If we could at least create an app at the open metadata marketplace would be awesome, but we did not find any documentation about how to do this, if someone could point us at how to start this, we can greatly contribute to the project**

**Comment by TeddyCr** [comment]
Thank you @dfdf for sharing this. We have this feature on our roadmap but it will be a Collate only feature 😊

**Comment by bramdes** [comment]
hi, where can I see if this feature is now implemented? 
Thanks!
