### ISSUE TITLE
Test case description is removed upon test case display name change

### ISSUE THREAD

**Issue by kevinl1210** [open-metadata/OpenMetadata#15862]
**Affected module**
Impact UI

**Describe the bug**
When I change the test case display name, its test case description are removed automatically.
Illustration as below:
![omd-testcase-description-bug](https://github.com/open-metadata/OpenMetadata/assets/14215103/080ff091-e116-43f0-b1fc-c00200a6bc92)

**Expected behavior**
Test case description should remain the same even when changing the display name.

**Version:**
 - OS: Ubuntu 22.04.3
 - Python version: 3.10.12
 - OpenMetadata version: 1.3.1.0
 - OpenMetadata Ingestion package version: 1.3.1.0

**Comment by ShaileshParmar11** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/15867
