### ISSUE TITLE
Qlik Sense connect with self signed cert trouble

### ISSUE THREAD

**Issue by dzhabrailovsn** [open-metadata/OpenMetadata#15892]
Hello, im trying connect to ws of qlik sense . My QS after Application Firewall (Is it important? ).
But get error  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)
I'm tried add my CA root to omd server and omd ingestion
**(keytool -v -importcert -file /qlik_certs/root.crt -keystore /usr/lib/jvm/java-17-openjdk/lib/security/cacerts -storepass changeit
keytool -v -importcert -file /qlik_certs/root.crt -keystore /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts -storepass changeit)**
 but anyway still get error.
 I run my OMD with docker compose.
 And still:
![image](https://github.com/open-metadata/OpenMetadata/assets/17762648/3e4fa8b7-7b86-4584-92aa-0a530ff069a0)
Now i dont know what should do more, could u give me advise?

**Comment by ulixius9** [comment]
Hey @dzhabrailovsn, let's connect on https://slack.open-metadata.org/ I've prepared a script which may help to solve this error but I'll need your help to test it out, can you please raise a thread on this topic on slack #support channel?
