### ISSUE TITLE
Do not return user email unless you're admin

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#15901]
- currently, any user can go to the teams/users tab and get user mails
- We should limit mails view unless you're an admin
- the API should not even give those results

**Comment by chirag-madlani** [comment]
UI changes pushed here: https://github.com/open-metadata/OpenMetadata/pull/15927
If no email data present it won't shows up

**Comment by pmbrull** [comment]
reopening, backend changes are still required

**Comment by chirag-madlani** [comment]
@pmbrull if you could share an example email that API returns I will push UI changes
