### ISSUE TITLE
Error with mutually exclusive tags when applied to two different columns on the same table

### ISSUE THREAD

**Issue by xiscapericas** [open-metadata/OpenMetadata#15916]
**Affected module**
UI is affected

**Describe the bug**
We have a tag called "status" that we use to tag assets depending on their validation status. The potential values are: unsolved, pending validation and validated. The values are mutually exclusive. 
We were working on Openmetadata 1.0.0, and we were using the tag to label the status of all columns for one specific table. If the description of the column was not done, it was "unsolved", if it was done but not reviewed it was "pending verify" and if it was verified by the table owner, then "verified". 
We upgraded openmetadata to to 1.1.7 and then from 1.1.7 to 1.3.2. Since then, the table is locked and we can't update. Anytime we try to add a description, or remove a tag or any change in the table (even change the owner) we get the following error: 

![Screenshot 2024-04-15 at 11 34 13](https://github.com/open-metadata/OpenMetadata/assets/15002572/7ce1db55-bede-4af0-9dfa-aab300b7b291)

**To Reproduce**

Not sure this will work, but maybe reproducing our scenario: 

- Create a mutually exclusive tag
- Try to add 2 different values to 2 different columns on the same table. 

**Expected behavior**
Be able to add different tag values on each table column. 

**Version:**
 - Python version:
 - OpenMetadata version: 1.3.2
 - OpenMetadata Ingestion package version: image = [docker.getcollate.io/openmetadata/ingestion:1.3.2]

**Additional context**
None

**Comment by harshach** [comment]
You cannot assign a mututally exclusive tag to the same column or table. This was a bug which was fixed. Now you are geting issues because your table has multiple mutually exclusive tags. Remove the mutual exclusivity in the tag category so that you can fix these issues.

**Comment by xiscapericas** [comment]
Hi @harshach , thanks for your contribution. I have tried to remove the "mutual exclusivity" property on the tag category from the UI but there is no way of doing it. Any idea on how to do that without having to recreate the whole tag?
