### ISSUE TITLE
Documentation for dataInsight API

### ISSUE THREAD

**Issue by arturodfj** [open-metadata/OpenMetadata#15936]
**Is some content missing, wrong or not clear?**
Hi!
What I'm missing is some documentation on the dataInsights API CALL https://OM-URL/api/v1/analytics/dataInsights/
I couldn't find anything related with this 😅

**Describe the solution you'd like**
A section in the API page about this calls

![Captura de pantalla 2024-04-16 160113](https://github.com/open-metadata/OpenMetadata/assets/152485642/05b183b0-c348-4cf4-8001-c1738c2f04e8)

**Comment by pmbrull** [comment]
hi, this is an internal API only expected to be used by the automated processes of the server. It's explicetely hidden. Thanks
