### ISSUE TITLE
Can't deploy Ingestion pipeline with Azure Key Vault Secret Manager

### ISSUE THREAD

**Issue by Nemeczek** [open-metadata/OpenMetadata#15933]
**Affected module**
Ingestion Framework

**Describe the bug**
Can't deploy pipeline while using Azure Key Vault secret manager because  "pydantic.error_wrappers.ValidationError: 1 validation error for AzureCredentials"

**To Reproduce**

1. Add managed Key Vault Secret Manager to the OM server
2. Add managed Key Vault Secret Manager to Airflow with DefaultAzureCredentials
3. Try to deploy pipeline to Airflow 

**Expected behavior**
Pipeline should be created

**Version:**
 - OpenMetadata version: 1.3.2
 - OpenMetadata Ingestion package version: 1.3.2

**Additional context**
I tested - the server creates secrets correctly. But when I deploy them the following error pops out in the server:
```
[2024-04-17T12:02:26.064+0000] {deploy.py:72} DEBUG - Traceback (most recent call last):
  File "pydantic/main.py", line 522, in pydantic.main.BaseModel.parse_obj
TypeError: 'NoneType' object is not iterable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/openmetadata_managed_apis/api/routes/deploy.py", line 66, in deploy_dag
    deployer = DagDeployer(ingestion_pipeline)
  File "/home/airflow/.local/lib/python3.10/site-packages/openmetadata_managed_apis/operations/deploy.py", line 61, in __init__
    SecretsManagerFactory(
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/singleton.py", line 28, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/secrets/secrets_manager_factory.py", line 52, in __init__
    self.secrets_manager = self._get_secrets_manager(
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/secrets/secrets_manager_factory.py", line 95, in _get_secrets_manager
    return AzureKVSecretsManager(secrets_manager_loader)
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/singleton.py", line 28, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/secrets/azure_kv_secrets_manager.py", line 108, in __init__
    self.client = AzureClient(self.credentials).create_secret_client()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/clients/azure_client.py", line 31, in __init__
    self.credentials = AzureCredentials.parse_obj(credentials)
  File "pydantic/main.py", line 525, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for AzureCredentials
__root__
  AzureCredentials expected dict not NoneType (type=type_error)
```

which is weird because azure_lv_secrets_manager.py contains guard against "wrong config":
![image](https://github.com/open-metadata/OpenMetadata/assets/1111404/a4dde198-ca63-4469-b3c1-255c627fee36)
But it actually goes further and fails here:
![image](https://github.com/open-metadata/OpenMetadata/assets/1111404/41036c3f-be26-405d-83cb-8fbc5a64babf)

So my guess would be that the metadata.generated.schema.security.credentials.azureCredentials makes Pydantic fail that object.

**Comment by pmbrull** [comment]
hi @Nemeczek thanks for the details. I think it might make sense to follow the conversation on Slack to get more info.

From top of mind, thinking if some creds might be missing in the configuration https://docs.open-metadata.org/v1.3.x/deployment/secrets-manager/supported-implementations/azure-key-vault

```
AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_KEY_VAULT_NAME= <Key Vault Name>
AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_TENANT_ID= <Tenant / Directory ID>
AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_CLIENT_ID= <App Registration ID>
AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_CLIENT_SECRET= <App Registration Secret>
```

If the issue persists and we identify it as a bug, we can reopen this.

thanks

**Comment by Nemeczek** [comment]
> hi @Nemeczek thanks for the details. I think it might make sense to follow the conversation on Slack to get more info.
> 
> From top of mind, thinking if some creds might be missing in the configuration https://docs.open-metadata.org/v1.3.x/deployment/secrets-manager/supported-implementations/azure-key-vault
> 
> ```
> AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_KEY_VAULT_NAME= <Key Vault Name>
> AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_TENANT_ID= <Tenant / Directory ID>
> AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_CLIENT_ID= <App Registration ID>
> AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AZURE_CLIENT_SECRET= <App Registration Secret>
> ```
> 
> If the issue persists and we identify it as a bug, we can reopen this.
> 
> thanks

![image](https://github.com/open-metadata/OpenMetadata/assets/1111404/35c2c63c-64fe-43c6-84b9-57e469efc999)
If I specify all of the creds then it won't be using DefaultAzureCredential
