### ISSUE TITLE
Loss of display name on ingestions when editing

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#15930]
**Describe the bug**
When you use display name to name an ingest it works fine, but when you edit an ingest for example profiler, the display name field is blank.

**To Reproduce**
The ingestion in airflow is named BTB_Community_DBT but it has been named as BIDA_BTB_Community_DBT in the Display name, but when you edit and make a change, if you don't notice you lose the name you gave to the ingestion.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/66bbfb63-e941-4892-9c71-771b4e4b20a0)

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/71a508a4-af81-45a4-94bd-68083823ccba)

**Version:**
 - OpenMetadata version: 1.3.2

**Comment by Sachin-chaurasiya** [comment]
Hello @triquinielas , thanks for filing an issue, this has been fixed with https://github.com/open-metadata/OpenMetadata/pull/15767.
