### ISSUE TITLE
Tasks Created by Incident Manager don't send notifications

### ISSUE THREAD

**Issue by muelleRw** [open-metadata/OpenMetadata#15956]
**Affected module**
Backend

**Describe the bug**
Tasks generated by the Incident Manager do not generate a notification.

**To Reproduce**
1. Set up notifications for Tasks
2. Go to Incident Manager
3. Change Status to Assigned
4. Assign to a User

**Expected behavior**
A notification should be sent if a task is assigned to a user, regardless of where it was assigned from

**Version:**
 - OS: Docker-Postgresql
 - Python version:
 - OpenMetadata version: 1.3.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==1.3.1`]

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 ^
