### ISSUE TITLE
Multiple Owners per Data Asset in OpenMetadata

### ISSUE THREAD

**Issue by tonsumawang** [open-metadata/OpenMetadata#15958]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I wanted to have multiple owners per data asset in OpenMetadata

**Describe alternatives you've considered**
No alternatives at the moment since we are tied up with 1 Owner per data asset.

**Additional context**
Business/Technical Use Case: A data asset table should be own by a Data Analyst for the business logic side + owns by a Data Engineer for the technical side

**Comment by harshach** [comment]
already fixed in 1.5.X
