### ISSUE TITLE
Result of total test case on Data quality tab not correct.

### ISSUE THREAD

**Issue by phumdanai12** [open-metadata/OpenMetadata#15968]
I found about test case not correct when compare between test case vs total test case.
I have try to re-index but result still incorrect.
![image](https://github.com/open-metadata/OpenMetadata/assets/151615349/1c8c0861-f913-4089-a308-8ddefae1d080)

Version:
OS: CentOS Linux release 7.9.2009 (Core)
OpenMetadata version: 1.3.2
OpenMetadata Ingestion package version: ingestion:1.3.2

**Comment by TeddyCr** [comment]
will fix it as part of https://github.com/open-metadata/OpenMetadata/issues/15593
