### ISSUE TITLE
'Tier' filter include results of deleted assets

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#15979]
**Affected module**
UI

**Describe the bug**
When using 'tier' filter, the number shows the results+deleted results, which is confusing for the user

**To Reproduce**
<img width="757" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/6d5e218a-8765-467f-a0fc-a47a2b58650c">

<img width="1141" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/2558f084-65ea-4936-a238-3a02bc26008d">

**Expected behavior**
The filter should count the amount on valid assets only, without deleted ones. 

**Version:**

 - OpenMetadata version: 1.3.2

**Additional context**

**Comment by harshach** [comment]
@karanh37 this should be a UI fix to pass deleted=false cc @sonika-shah
