### ISSUE TITLE
Oracle view metadata only ingested with select privilege

### ISSUE THREAD

**Issue by arubincs** [open-metadata/OpenMetadata#15977]
**Affected module**

Oracle metadata ingestion

**Describe the bug**

When I ingest metadata from an Oracle database, not all views then appear in the catalog. The only views that show up are those that the account OpenMetadata connects to the database with has READ or SELECT privileges to. This Oracle account has the SELECT_CATALOG_ROLE role, and can view all DBA level dictionaries. It does not have SELECT privileges for most objects. Tables and procedures (even those it cannot SELECT from) are populated correctly in OpenMetadata; views are not. It is as if OpenMetadata is using ALL_VIEWS, instead of DBA_VIEWS, during ingestion. But I double checked the version of OpenMetadata (1.3.1) and /home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/oracle/queries.py in Docker (ORACLE_DBA_VIEW_DEFINITIONS queries DBA_VIEWS and DBA_MVIEWS).

**To Reproduce**

- create a view in Oracle
- ensure that the account OpenMetadata uses for connection cannot select from the view (i.e., returns ORA-00942)
- run metadata ingestion from the Oracle database
- verify that the newly-created view does not exist within the data catalog

**Expected behavior**

All views listed in DBA_VIEWS should have their metadata ingested into OpenMetadata.

**Version:**

 - OS: Windows 10 Enterprise
 - Python version: 3.10.9
 - OpenMetadata version: 1.3.1
 - OpenMetadata Ingestion package version: 1.3.1

**Comment by ayush-shah** [comment]
The above is expected behavior.
we are planning to modify the usage with `DBA_` to `ALL_` due to the DBA priviedges issues faced by many. Rather using a `ALL_` would help nullify the problem and the data can be fetched where the user have priviledges

**Comment by arubincs** [comment]
Thank you. I was confused that the [Oracle connector documentation](https://docs.open-metadata.org/v1.3.x/connectors/database/oracle) says
```
-- GRANT SELECT CATALOG ROLE PRIVILEGE TO FETCH METADATA TO ROLE / USER
GRANT SELECT_CATALOG_ROLE TO new_role;
```
and

> With just these permissions, your user should be able to ingest the schemas, but not the tables inside them. 

I thought that SELECT_CATALOG_ROLE is all that's necessary for ingesting Oracle object metadata. And it is consistent with how table and stored procedures are treated in OpenMetadata. Why are views handled differently in 1.3.x?

In future releases, will SELECT privileges (meaning the object is visible in an ALL_ dictionary) be necessary to ingest schemas?
