### ISSUE TITLE
Database & databaseSchema should not be stored in table_entity json

### ISSUE THREAD

**Issue by zjffdu** [open-metadata/OpenMetadata#16005]
**Affected module**
backend

**Describe the bug**
I find database & databaseSchema details in the `table_entity` json, and database details in `database_schema_entity` json.
Although it doesn't affect the user experience in UI, we should remove them, the relationship should be stored in `entity_relationship`.

**To Reproduce**
Import the sample data according the instruction here. https://docs.open-metadata.org/v1.3.x/developers/contribute/build-code-and-run-tests/openmetadata-server

**Expected behavior**
No database and databaseSchema in `table_entity`, no database in `database_schema_entity`

**Version:**
 - OS: Mac
 - Python version: 3.9.7
 - OpenMetadata version: 1.3.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
There is no need to use entity_relationship. as the relation between database -> schema -> table is static. This helps with read side
