### ISSUE TITLE
User search is not handling special chars

### ISSUE THREAD

**Issue by Alexandr-Nedomets** [open-metadata/OpenMetadata#16001]
**Describe the bug**
Incorrect symbols search '+', '&'
Get error for symbols search '[', ']' 

**To Reproduce**
Enter '+', '&', '[', ']' into main search 
or use the user search https://sandbox.open-metadata.org/settings/members/users?user=%5B
![image](https://github.com/open-metadata/OpenMetadata/assets/55582159/ed9cede2-eedf-4ffd-913e-26f90a52daa3)

**Expected behavior**
Correct symbols search '+', '&'
Fix error for symbols search '[', ']' 

**Version:**
 - OpenMetadata version: 1.2.5 and current, maybe in another versions too

**Comment by Alexandr-Nedomets** [comment]
I'm ready to do this issue
if all ok

**Comment by harshach** [comment]
Thanks @Alexandr-Nedomets please provide a PR we will review it.
