### ISSUE TITLE
When the DDL of an existing table is changed, the metadata is run again, but the changed DDL is not collected

### ISSUE THREAD

**Issue by xuhui1231** [open-metadata/OpenMetadata#16013]
**Describe the bug**
I use openmetadata-1.3.0，I added a field to a collected table in the database, and then ran the metadata collection and found that the new field was not collected。
The following is the current field of the table：
![image](https://github.com/open-metadata/OpenMetadata/assets/51685494/f09ab04b-538c-4d4e-9b82-26b58389b6a7)

I click again after running successfully：
![image](https://github.com/open-metadata/OpenMetadata/assets/51685494/cb016164-0d0a-4b08-b719-310614319c5f)
The newly added age field was not collected：
![image](https://github.com/open-metadata/OpenMetadata/assets/51685494/0bab4bcf-34e6-479a-ba39-f186528681f4)

**Comment by ayush-shah** [comment]
@xuhui1231 please update to latest version, and let us know if you face the same issue, will close the ticket, comment if you still can reproduce it. Also, please provide debug logs for the same🙏
