### ISSUE TITLE
Local Installation Tutorial

### ISSUE THREAD

**Issue by smileyboy2019** [open-metadata/OpenMetadata#16012]
Can it be installed locally? If you don't want to use Docker to install the service, please provide the operation process for local installation. Thank you

**Comment by pmbrull** [comment]
hi, there are multiple deployment methods, including Bare Metal if you don't use docker. https://docs.open-metadata.org/v1.3.x/deployment please, follow the docs and keep setup/config questions in [Slack](https://slack.open-metadata.org/) before opening an issue. thanks
