### ISSUE TITLE
show inherited owner in entity details page

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#16018]
- [ ] At present, there's no visual indicator to show that a user is the inherited owner of a specific entity. (we get inherited: true in owner object)
- [ ] Additionally, we need to indicate whether the user is part of the team and if the team is the owner of the entity.

<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/71748675/8dc1836d-3cae-43f8-9ba6-c95cc1b37ebc">

**Comment by harshach** [comment]
we now show inherited users/teams with a icon. @ShaileshParmar11 anything else remaining here?

**Comment by ShaileshParmar11** [comment]
Yes this is done closing it!
