### ISSUE TITLE
DataProduct is not displayed

### ISSUE THREAD

**Issue by Alexandr-Nedomets** [open-metadata/OpenMetadata#16040]
**Affected module**
It impacts the UI

**Describe the bug**
DataProduct is not displayed on services, databases and schema pages

**To Reproduce**

Create domain add assets(services, databases, schemas). I create DataProduct in a domain and add domain assets to DataProduct.
When going to the services, databases and schemas pages
DataProduct is not displayed

**Expected behavior**
DataProduct is displayed on services, databases and schema pages

**Version:**
 - OpenMetadata version: [1.2.5, 1.3.2 maybe another versions]

**Comment by karanh37** [comment]
This has been fixed recently. Reference PR - https://github.com/open-metadata/OpenMetadata/pull/15730
Changes are available on beta now.

Closing this issue, @Alexandr-Nedomets if you can still reproduce on beta, you can reopen this one.
