### ISSUE TITLE
Edge Information Function- not showing in UI

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#16092]
Reference - https://github.com/open-metadata/OpenMetadata/discussions/15793

**Comment by zainabasmah** [comment]
Hello , 
I was looking into the Edge Function attribute and I reached here, I see you guys have this as a bug.
Can you please give an ETA on this.
We are blocked to share our data with the stewards

**Comment by ulixius9** [comment]
@zainabasmah we plan to fix this with 1.5 release, also this should not be a blocker right you should be able to see rest of the lineage information and if getting the function details is a priority for you, then you can also consider it putting in description of the lineage edge while we deliver this fix.

**Comment by aamir5599** [comment]
@karanh37  Can you please confirm, if this is fixed in the latest 1.5 release?
