### ISSUE TITLE
Disable add tag button for non admin users

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#161]
![image](https://user-images.githubusercontent.com/1417689/129455132-1065d51c-dfb2-4255-998c-78fce25c6326.png)

Right now we let the user enter tag category information and only when they complete tag category action, we tell them they can't do it. This is wasted work.

When a non-admin user clicks add categories button, we should show a modal "Only Administrators can add new Tag Categories. Please contact (provide a list of admins) for help." Modal should have an Okay or Dismiss button.

**Comment by sureshms** [comment]
Same goes with Add Tag button for adding a tag to a category.

**Comment by shahsank3t** [comment]
Disabling part will be done in https://github.com/open-metadata/OpenMetadata/issues/173 
For the non-admin part, we'll take care of it in the next release.

**Comment by sureshms** [comment]
This is already fixed in 0.3 release.
