### ISSUE TITLE
Glossary Reviewers can be user or team

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#16107]
**Describe the bug**
Currently we are allowing only users to be reviewers. Glossary reviewers can be team as well.

**Comment by DovileKr** [comment]
Is this bug going to be part of 1.4? It is bad issue as it removed functionality that was available in 1.2.

**Comment by karanh37** [comment]
@harshach - we will require backend support for this. Adding a team as reviewer is currently throwing an error.

**Comment by DovileKr** [comment]
hey please confirm the status for this. still don't see in 1.4.1

**Comment by karanh37** [comment]
Hey, this is currently in development, will let you know once this is merged.

**Comment by karanh37** [comment]
Fixed with #16372
