### ISSUE TITLE
Metabase ingestion support for owner metadata and usage type

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#16101]
### Discussed in https://github.com/open-metadata/OpenMetadata/discussions/16045

<div type='discussions-op-text'>

<sup>Originally posted by **julien-alpaca** April 25, 2024</sup>
@ulixius9 Any chance we can have the owner field populated in the metadata ingestion of Metabase? I believe we could use the creator of the dashboard as the owner.
Also Is there any plan to add a ingestion of type usage for Metabase?

Thank you</div>

**Comment by SumanMaharana** [comment]
I'll be working on this
