### ISSUE TITLE
[Security Deployment] Revisit and update the docs for SSO setup for Implicit Flow and Auth Code Flow

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#16124]
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.

Currently the SSO accounts do not explain Code Flow , that needs to be added , All our docs are for Public type client Type

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

**Comment by harshach** [comment]
@ayush-shah any further updates remaining here?
