### ISSUE TITLE
OKTA SSO Integration

### ISSUE THREAD

**Issue by efrancisor** [open-metadata/OpenMetadata#16141]
**Is some content missing, wrong or not clear?**
We followed the document available for OKTA SSO but it doesn't work.
It just spins eternally.

**Describe the solution you'd like**
Do you have a latest correct documentation? 

**Additional context**

**Comment by sureshms** [comment]
@efrancisor, please don't create an issue until it is confirmed that it is indeed a bug. Please continue the conversation in slack.
