### ISSUE TITLE
Some users can not be mentioned to be tagged in conversations

### ISSUE THREAD

**Issue by franciscapisca** [open-metadata/OpenMetadata#16154]
**Affected module**
UI

**Describe the bug**
 I'm trying to mention a user as part of the conversation on the description of a table and the user is not found in the proposed dropdown, even though i'm sure it exists. The user is "data-enablement". @aniketkatkar97 mentioned that there seems to be an issue with the suggestion popup with names containing `-`in them. 

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/82287469/f75c90af-0bf0-4273-8c61-fa410750c326)

**Expected behavior**
I would expect:
1. User to appear in the popup suggestion
2. The user is properly tagged (I see the name automatically in blue and underlined)

**Version:**
 - Python version:
 - OpenMetadata version: v1.3.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
Seems like the same issue where we have a PR to fix the user search with special chars. @karanh37
