### ISSUE TITLE
Descriptions are not updated in tableau

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#16150]
**Affected module**
Ingestion Framework: Tableau Assets

**Describe the bug**
When we load the assets from tableau, they load the dashboard (workbook) description, but when they are changed in Tableau and the ingest is rerun, it does not update the description.

**To Reproduce**
For example, here I have a list of the assets (workbooks) of tableau, then I identify that a workbook has no description, at this moment it is ok because it is true that it has no description.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/4467f853-b35e-4f0d-a1e5-44970b5c2f40)

I add a new description in the workbook
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/a712858e-5306-4166-ac54-b5c10bf3996c)

Then, I rerun tableau ingestion so that it picks up the changes from the new description and it does not update it.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/b31e66b3-a373-4e07-a65a-5ba6823daae5)

**Version:**
 - OpenMetadata version: 1.3.2

thanks,
Carlos

**Comment by sushi30** [comment]
automatic ingestion currently does not support updating descriptions. this feature is being tracked here: https://github.com/open-metadata/OpenMetadata/issues/15721

closing as duplicate
