### ISSUE TITLE
"edit tier" for tables is missing from policies

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#16155]
**Affected module**
UI

**Describe the bug**
On previous version, there was an option to set permissions for "edit tier". 
Now, it's available for all resources, but not for table resource. 
Meaning there is no option to set permission on this field.

**To Reproduce**

flow 1:
<img width="589" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/f986f053-82dc-4716-b28e-919828617e95">

<img width="574" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/bc6d33e9-57fb-43cb-82bb-2364f5c841f1">

flow 2:

<img width="444" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/fe8d96e4-ea9e-427a-b6f3-4003e4f9d85a">

<img width="426" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/87426120/88ddb9ff-5a1d-48ea-b313-ab75beabbf3c">

**Expected behavior**
I expect the option for setting tier editing permissions will be available for table resource.

**Version:**
1.3.2

**Comment by sapirhi** [comment]
hi @harshach,
Can we prioritize this bug somehow? 
Users are adding this tag though the assets are not in tier 1 standartd.

**Comment by sapirhi** [comment]
hi @harshach,
Can we prioritize this bug somehow? 
Users are adding this tag though the assets are not in tier 1 standard.

**Comment by harshach** [comment]
Fixed in 1.6.1
