### ISSUE TITLE
MySQL field data validation, if a field's enumerated value is not among the set of enumerated values, the data quality task will also not report an error.

### ISSUE THREAD

**Issue by liaoxiaodongabc** [open-metadata/OpenMetadata#16168]
column profile 中 Column Values To Be In Set 字段的值不在设置的数据校验规则范围内，任务也不报错，状态是校验成功

**Version:**
 - OpenMetadata version:1.3.3

**Comment by liaoxiaodongabc** [comment]
比如我的表中某个字段的值只会出现：'优秀' '良好' 这两个值,我在校验规则中设置了 '良好' '及格'，但是任务还是执行成功

**Comment by sushi30** [comment]
addressed by https://github.com/open-metadata/OpenMetadata/issues/16305
