### ISSUE TITLE
Integration with Cube Dev

### ISSUE THREAD

**Issue by ndrluis** [open-metadata/OpenMetadata#16178]
**Describe the solution you'd like**
Integration with [Cube Dev](https://cube.dev/), to enable lineage tracking between the [DBT Models and Cubes](https://cube.dev/docs/guides/dbt), and the [Cubes](https://cube.dev/docs/reference/data-model/cube) and [Views](https://cube.dev/docs/reference/data-model/view), and then between the View or Cube Entity (possibly as a DashboardDataModel) with the Tools (other DashboardDataModel entities, because Cube has a [semantic layer sync](https://cube.dev/docs/product/workspace/semantic-layer-sync)) or other entities like MLModels.

**Comment by TeddyCr** [comment]
Thank you @ndrluis for opening this issue. Would you be interested in contributing this connector?

**Comment by ndrluis** [comment]
@TeddyCr Yes! Is there any documentation about how to implement a connector?

**Comment by TeddyCr** [comment]
@ndrluis yes we have more info [here](https://docs.open-metadata.org/v1.4.x/developers/contribute/developing-a-new-connector). We also have #contributor channel in the Slack community.

**Comment by danielle** [comment]
Why was this closed as not planned? How does it get planned? This would be a fantastic addition to Open Metadata platform to include all the lineage and logic from Cube.dev as well.
