### ISSUE TITLE
[Searchreindex] Create Groups for different entities like observability , quality etc

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#16176]
**Feature**
Add feature issue reference
Currently the list of entities seems cluttered because of the whole list being presented to the user. 
We need to group entities as follows :- 
1. Data Assets  (selecting this will reindex following)
 - Table
 - Chart
 - Dashboard
 - Pipeline
 - SearchService
 - and so on 
 2. Data Insights 
  - WebAnalyticReportData
  - EntityReportData
  - so on
  
 

**Describe the task**

**Comment by harshach** [comment]
@mohityadav766 need more details in the description

**Comment by mohityadav766** [comment]
@harshach we had a discussion around group search index config under sections to allow easier coniguration for users, but tbh this is very low priority
