### ISSUE TITLE
Tag Usage query in Collection DAO is causing a CPU Spike in the Database

### ISSUE THREAD

**Issue by parthasarathy93** [open-metadata/OpenMetadata#16172]
From the version 1.2.4, we find a new tag usage query in the code, which is causing cpu to spike, we have over 19 tags, in which one of them is a column tag, it has 75k columns tagged.  we are not sure whether that is causing it. Need to optimize this query to decrease the cpu spike

https://openmetadata.slack.com/archives/C02B6955S4S/p1714641580918419

**Comment by harshach** [comment]
@parthasarathy93 please provide any details of how to fix it. PRs would be great.
