### ISSUE TITLE
[Notifcations] Filtering logic should allow to create boundary based filters

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#16187]
**Is your feature request related to a problem? Please describe.**
there is no boundary definition for rules It created as (condition1 && condition2 || condition3 || condition4 && condition5)
we cannot create conditions as ((condition1 && condition2) || (condition3 || (condition4 && condition5))) 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 Please update issue description with more details
