### ISSUE TITLE
Review Test Suite Alerts

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#16192]
**Affected module**
Data Observability: ALERTS in TEST SUITE

**Describe the bug**
When we want to create a rule related to the test cases that are in a test suite. The notification never arrives.
To register this issue, we have confirmed that for example if we create the alert with the test case it works.

**To Reproduce**
These are the steps:

1.- I create a dummy table with a test case dummy and make it work.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/7bf9fcba-cf6d-4fc3-844b-2516c598f47a)

2.- I create the test suite and add the test case dummy

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/534a1638-2f1c-4a53-9501-768ba65b4362)
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/1080dfe0-dfa5-4785-acc7-9705ce9743d7)

3.- I create the alert
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/471a468e-cd95-4579-9100-d503521af28f)

4.- I cause the failure in the test case.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/96fc521d-d78f-4376-a801-0a0ab03621a2)
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/cf0505bc-6528-4d23-8c83-5a40c1853f10)

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/a84a8e39-531b-4d84-86ee-de43e8223ee4)

The email will never be received, but if I do the test case if we receive the alert, I comment it to prove that our mail server is working and it is an issue related to the test suite.

**Version:**
 - OpenMetadata version: 1.3.3

**Comment by mohityadav766** [comment]
this has been fixed, please upgrade to latest 1.4.5

**Comment by triquinielas** [comment]
Hello, we are on 1.4.4 and we confirm that it works. thank you so much
