### ISSUE TITLE
Custom Properties for Dashboard Data Models

### ISSUE THREAD

**Issue by brenda-barcelos** [open-metadata/OpenMetadata#16208]
**Is your feature request related to a problem? Please describe.**
Dashboard Data Models are missing the Custom Properties.

**Describe the solution you'd like**
I would like to have the ability to register custom properties for  Dashboard Data Models.

**Describe alternatives you've considered**
Now I'm using the Dashboard  Custom Properties.

**Comment by Sachin-chaurasiya** [comment]
@mohityadav766 @sonika-shah, I verified that the API does not support `extension` in dashboard data models. Therefore, backend changes will be required.

```js
REQ: http://localhost:8585/api/v1/dashboard/datamodels/name/sample_looker.model.orders
fields: owner,tags,followers,votes,domain,dataProducts,extension


RES: 
{
    "code": 400,
    "message": "Invalid field name extension"
}

```

**Comment by Sachin-chaurasiya** [comment]
@mohityadav766 @sonika-shah, I have opened a PR here: [feat(#16208): custom properties for Dashboard Data Models](https://github.com/open-metadata/OpenMetadata/pull/16628#top). Please push the backend changes directly to this PR.
