### ISSUE TITLE
Trino connector username does not accept special characters 

### ISSUE THREAD

**Issue by Larissa-Rocha** [open-metadata/OpenMetadata#16211]
**Affected module**
Ingestion Framework

**Describe the bug**
My Trino users follow the pattern: `context+service_name@company.com` but using that as username in the Trino service connection configuration, I get the error:
![image](https://github.com/open-metadata/OpenMetadata/assets/69212483/ac084084-34d2-487f-9ae4-8ed3fa2d7423)
When I use a username like fistname_lastname@company.com, for example, it works fine.

**To Reproduce**
Create a Trino user with a special character in it and test the connection in the service configuration.

**Expected behavior**
I expect to be able to use special characters in the username and maybe there will be a way to escape them when building the connection string.

**Version:**
 - OS: 
 - Python version:
 - OpenMetadata version: 1.3.1
 - OpenMetadata Ingestion package version: Openmetada UI

**Additional context**

**Comment by harshach** [comment]
@ulixius9 @Sachin-chaurasiya can we check if this is an issue at connector side or UI sending encoded characters

**Comment by Sachin-chaurasiya** [comment]
> @ulixius9 @Sachin-chaurasiya can we check if this is an issue at connector side or UI sending encoded characters

Hello @harshach @ulixius9, I have checked the payload from the UI side and there no encoding from the UI side, UI sending the input as it is.

<img width="1475" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/59080942/c2623828-d8df-49fa-acc6-61174d2d5bd2">

**Comment by harshach** [comment]
Thanks @Sachin-chaurasiya. @ulixius9 can you take a look from Trino side?
