### ISSUE TITLE
lineage.OracleLineageSource  ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by ovjust** [open-metadata/OpenMetadata#16297]
![Snipaste_2024-05-16_16-31-05](https://github.com/open-metadata/OpenMetadata/assets/12697538/221dff90-7865-46b8-9527-ad8d31e65d84)

**Comment by dmarkubex** [comment]
me too,how to solve this?

**Comment by harshsoni2024** [comment]
@ovjust, can you share the full logs for this issue?

**Comment by pmbrull** [comment]
missing info, can't reproduce
