### ISSUE TITLE
Delete TestCase (is not completely eliminated)

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#16322]
**Affected module**
Data Quality

**Describe the bug**
When a test case is created and executed and you decide to delete it, when the test case is created again with the same name, the last status and the history are displayed.

For example, we have defined a nomenclature OM_TABLENAME_CONSISTENCY, and we create a test case and we realize that it is not correct after executing it, when we delete it and when we recreate it with the same name, it keeps the history and execution statuses as if it had never been deleted.

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/fca345bc-45cd-426a-a132-f26e1496bb19)

Keeping the history of the test case created to access the API can be interesting to analyze, deleted test cases and their history but it conflicts with renaming them to the same name.

**To Reproduce**
1.- I create a test

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/fafdc22a-783d-443e-86a7-434c8dc166a5)

2.- I check the last executions
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/63cb961a-5efb-4b9e-a1ec-307a2bcb6eb1)

3.- I remove it
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/fca345bc-45cd-426a-a132-f26e1496bb19)

4.- I create it again with the same name and voila, everything appears again. 

**Expected behavior**
It may not be a good idea to remove it from the database altogether, but to allow a case with the same name to be created over time and to be internally different.

Think for example that today I create a test case called ACCURANCY_TABLE, and I test, and in 1 year I create another test case called ACCURANCY_TABLE, and suddenly the whole history appears, it will be very confusing and surely we will not remember that a test case with the same case was made 1 year ago.

**Version:**
 - OpenMetadata version: 1.3.1

thanks in advance,
Carlos

**Comment by sushi30** [comment]
@TeddyCr I saw this issue when working on integration tests for data quality. I can look into it.
