### ISSUE TITLE
glossaryTerm: description change still goes to Owner and Not Reviewers

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#16326]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
in beta sandbox the workflow for description change still goes to Owner and Not Reviewers:
https://sandbox-beta.open-metadata.org/glossary/%22Bug.Test%22

**To Reproduce**

Screenshots or steps to reproduce

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/e04bbd1c-8437-4b51-8488-15bddff670b1)
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/6e4a7906-60ac-4cd4-97a7-46d989298ac0)

**Expected behavior**
as discussed in https://openmetadata.slack.com/archives/C02B6955S4S/p1712758989579439?thread_ts=1712758609.855309&cid=C02B6955S4S 

if there is a reviewer defined in parent term or glossary, we shouldn't allow users to add new reviewer during the creation process. If we do it , its assigning the review task to the new reviewer which shouldn't be happening

**Version:**
1.4 Sandbox

**Additional context**

**Comment by DovileKr** [comment]
@mohityadav766  @harshach 

@Harsha (getcollate.io) We have upgraded to 1.4 pre and it still had this bug. Sandbox beta still has the bug, this time ever worse - if glossary is renamed, it "looses" all the terms under it.

If change name back - then it reappears. 

Uploading glossaryRenaming.mp4…

**Comment by DovileKr** [comment]
Please provide update on this bug, if possible

**Comment by DovileKr** [comment]
@chirag-madlani  Please provide update on this bug, if possible

**Comment by chirag-madlani** [comment]
Hi @DovileKr 
It is shipped with 1.4.2
cc: @karanh37
