### ISSUE TITLE
Activity feed bugs and improvements

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#16343]
**Affected module**
UI

**Describe the bug**

- [x] Activity tab reloads when commented in the thread resetting the selected thread. Prevent the reload and only update the selected thread

https://github.com/open-metadata/OpenMetadata/assets/51777795/64b29095-8a3a-46dc-a62c-6bee7bad1238

- [ ] persona update feed
 

https://github.com/open-metadata/OpenMetadata/assets/71748675/678ae12b-c5a6-4ed3-855c-81f13fde8760

- [x] plus minus icons should be center aligned.
![image](https://github.com/open-metadata/OpenMetadata/assets/33024356/a2ccf87d-afee-4007-b2b9-28d6e084bc16)

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ayush-shah** [comment]
Incident Manager shows empty but the breadcrumb shows incident manager
Image 1) I see Incident Manager for successful test case
Image 2)  On clicking Incident Manager on the breadcrumbs from Image 1, i get to see empty incident manager
Image 3) I got to Image 1 page from Activity feed shown in this image

<img width="1680" alt="Screenshot 2024-05-23 at 3 51 47 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/6baab4c6-1a48-4215-b15c-c1e7cfb0d606">
<img width="1680" alt="Screenshot 2024-05-23 at 3 52 05 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/fe4a53b1-7bb1-4469-b251-b1b87a9b238e">

![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/194d0984-ac80-42b9-b45e-b6ab6bdb8767)

**Comment by harshach** [comment]
- [ ] dashboard display needs to be shown 
![image](https://github.com/open-metadata/OpenMetadata/assets/38649/df562c1c-e4f3-4339-a2ee-8c17a76b15ba)

- [ ] it looks like activity feed is repeating for a failed test case result? the asset link at the top taking it 
![image](https://github.com/open-metadata/OpenMetadata/assets/38649/0f40f507-e26c-4d3c-aef4-d91db1585f5f)

- [ ] align + icon with description 
![image](https://github.com/open-metadata/OpenMetadata/assets/38649/f8bcba47-63aa-4ad4-8728-bcaa4ce68329)

**Comment by aniketkatkar97** [comment]
- [ ] Long description overflow
![image](https://github.com/open-metadata/OpenMetadata/assets/51777795/3fc86640-1f43-43b7-b761-3e27b1c96686)

**Comment by OnkarVO7** [comment]
Activity Feed does not display the knowledge center article's title 

https://github.com/open-metadata/OpenMetadata/assets/28966081/93bcb44f-6ba0-4de7-81f2-918ede2c147d

**Comment by aniketkatkar97** [comment]
- [ ] Old feed component in the conversation panel on entity page and alignment issue
- [ ] 
<img width="577" alt="Screenshot 2024-05-28 at 12 29 54 PM" src="https://github.com/open-metadata/OpenMetadata/assets/51777795/6b7221f8-c850-4b86-bf36-2b4d75148e87">
<img width="582" alt="Screenshot 2024-05-28 at 12 30 42 PM" src="https://github.com/open-metadata/OpenMetadata/assets/51777795/50ee9489-9e81-4a43-a65c-8b00f079ee85">

**Comment by ayush-shah** [comment]
- [ ] distinguish glossary terms and tags from each other on activity feed
![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/8e0f3631-27be-4379-b346-6b0a3fd48979)
![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/22189c4c-0d7f-4513-bf50-deb175b7848f)
![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/b69ad9d1-9d50-46fe-a4fa-9635261e6618)

**Comment by Ashish8689** [comment]
@mohityadav766 Needed BE support for this.

- [ ] There are some entities with the display name along with it. And we don't have entity info in the Feed. Having the entity reference for the particular entity will help us to display the updated name for the feed. 
![image (7)](https://github.com/open-metadata/OpenMetadata/assets/66266464/be81ff7b-2f5b-4a4f-aa47-fa300b4ee204)
![image (8)](https://github.com/open-metadata/OpenMetadata/assets/66266464/5e62b09d-831d-4925-a6c4-fa6ac02911f5)

- [ ] For any kind of column update in the entity we don't have info about the column in the Feed data. It's hard to state the changes belong to table or column.
<img width="785" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/0c53409c-e0c5-48cb-92bd-3a32445f4f97">
<img width="693" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/ce83c924-48a5-4f17-b900-cd9ab7e5c609">



### Feed not Generating for this change event :

- [ ]  Classification re-naming and description change.
- [ ]  Tag displayName, description, re-naming, style change.
- [ ]  Removing Domain in Glossary
- [ ]  Glossary updating description and re-naming displayName
- [ ]  Glossary Term re-naming / displayName
- [ ]  Team update email, domain, owner, subscription,displayName and description



### Feed generation not needed : 

- [ ] I have updated the widgets in the Persona and it created a feed as entityCreated, I don't think we should we should created any feed for this.


### Need Feed info with cardSyle : 

- [ ] <img width="247" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/1de9614d-a1c9-4a34-825e-64453fc61c87">
- [ ] <img width="275" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/c9d71fb5-7647-4b5e-b50a-241cfeee9387">
- [ ] <img width="389" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/ff6ec946-c205-4915-b3d8-8a6ab3029335">
- [ ] <img width="389" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/398d7f8a-daa1-496b-a605-47d8c40f6feb">
-  [ ] <img width="389" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/3a2ffc0e-28f4-4164-b583-11e66d9d5b1e">
-  [ ] <img width="389" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/1578a5ab-ef0a-44e9-80cb-be7f4de9cb94">

@Rupchavan Need mock for the above feeds!

**Comment by Ashish8689** [comment]
Feed `cardStyle` for tags update in entities will come like: 

- `Tags` : Only for Tags update
- `GlossaryTags`: Only for Glossary update
- `TagsAndGlossary`: Or both the Tags and Glossary update

cc: @mohityadav766

**Comment by Ashish8689** [comment]
- [ ] Activity feed going from one thread to another with the same profile image sticks on another user 

https://github.com/open-metadata/OpenMetadata/assets/66266464/3181e8c6-0b2c-4b97-9ef5-97662e6d020d

**Comment by ShaileshParmar11** [comment]
Breadcrumb for the test case should be Data quality / Test Case

![image (6)](https://github.com/open-metadata/OpenMetadata/assets/71748675/305aac04-f84b-4806-9637-6c26dcb65e0e)

**Comment by aniketkatkar97** [comment]
- [ ] Changing the language to other than English, text `{{entity}}` is added in feed header.
<img width="1038" alt="Screenshot 2024-07-05 at 1 39 31 PM" src="https://github.com/open-metadata/OpenMetadata/assets/51777795/046f553e-9dae-469a-9a5a-b959792fc890">

**Comment by mohityadav766** [comment]
> Feed `cardStyle` for tags update in entities will come like:
> 
> * `Tags` : Only for Tags update
> * `GlossaryTags`: Only for Glossary update
> * `TagsAndGlossary`: Or both the Tags and Glossary update
> 
> cc: @mohityadav766

@Ashish8689 this information is already there
