### ISSUE TITLE
Column-Level Lineage CSV Export

### ISSUE THREAD

**Issue by tonsumawang** [open-metadata/OpenMetadata#16346]
Hi OMD Team - I know that we already have a lineage export to CSV feature in v1.4.0 but it is limited to table-level lineage export only so I am formally requesting to have a "column-level lineage export for both upstream and downstream to a file i.e. if I click a column in the Lineage graph and highlighted the upstream and downstream of the selected column and click export, it will only export the column level lineage

This is very useful if the Lineage graph is congested with hundreds of upstream and downstream lineages which is hard to trace for Impact Analysis/Root Cause Analysis.
Thank you

Slack #support thread reference: https://openmetadata.slack.com/archives/C02B6955S4S/p1716169234503059

**Comment by karanh37** [comment]
Fixed and available in 1.5.12
