### ISSUE TITLE
bug: lineage view issues - thousands of status requests, laggy ui, disappearing/duplicated arrows

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/OpenMetadata#16359]
**Affected module**
UI

**Describe the bug**
When editing the value of 'nodes per layer' in lineage view any change (to lower or greater than default value of 50) causes misbehavior of the view, thousands of status requests to backend, which kills the browser, duplicates edges in the UI and forces user to close the view. The video below depicts the issue:

https://github.com/open-metadata/OpenMetadata/assets/5680655/533c273f-7977-4d93-8aa9-3dabee2bdfa2

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Lineage view is not sending thousands of status requests, view does not contain duplicated edges.

**Version:**
 - Python version: 3.8
 - OpenMetadata version: [e.g. 0.8] 1.3.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.3.3

**Additional context**
Other issues caused by this are:
- duplicated arrows in the view (when moving nodes around)

I've tried reingesting elasticsearch as suggested here https://github.com/open-metadata/OpenMetadata/issues/15221 but this does not solve any of mentioned issues.

**Comment by DovileKr** [comment]
Experienced same: 
In 1.4  I was exploring lineage and noticed that we have some lineage lines that do not have nodes.  I've tried on two browsers, same issue, but maybe different lines. Same issue on 1.3.4. Not sure if it also was on 1.3.
Anyway, not sure if this our hardware resourcing (either tool or my laptop) issue and not enough power to render all the UI elements. The lineage is quite heavy (welcome to the SAP world).

**Comment by karanh37** [comment]
Hi @mgorsk1 - we have fixed multiple status call issue. Ref Issue - https://github.com/open-metadata/OpenMetadata/issues/15303
This will be available with 1.4 release.

**Comment by karanh37** [comment]
This has been fixed and published with 1.4.3 release.
