### ISSUE TITLE
Redeploy all test suite IngestionPipelines from UI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#16380]
<img width="1323" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/35870520/8b1d6d9b-4a01-4835-ad39-8a2d7a6651f9">

post upgrade steps include redeploying Ingestion pipelines (in case we do any payload updates). However, these UI lists do not include test suites

We need to prepare a page for DQ pipelines and allow admins to redeploy them all

When we're done, update the docs accordingly

**Comment by pmbrull** [comment]
hi @tonsumawang , 1.5. I'll update the release here

**Comment by chirag-madlani** [comment]
@pmbrull @harshach Was thinking of placement for the same and I feel we can place it on DQ page itself like below
<img width="1258" alt="Screenshot 2024-06-19 at 6 45 54 PM" src="https://github.com/open-metadata/OpenMetadata/assets/12962843/87c6d353-eb12-4a50-ac64-f94666a77e62">

Let me know in case we want to place this as same as other pipelines under settings page

**Comment by chirag-madlani** [comment]
As discussed with @harshach, We will move this to Settings --> Services --> DQ --> Pipelines --> Re-deploy 
cc: @pmbrull
