### ISSUE TITLE
Add Documentation Section for using `openmetadata-ops.sh` usage

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#16389]
**Is some content missing, wrong or not clear?**
Current documentation does not provide clear usage of `openmetadata-ops.sh`. Need to add a documentation section explaining the CLI usage.

**Comment by harshach** [comment]
@ayush-shah can you delegate this

**Comment by safayavatsal** [comment]
Here's the PR for review -https://github.com/open-metadata/OpenMetadata/pull/19048#issue-2738334019
