### ISSUE TITLE
Search doesn't work on chart

### ISSUE THREAD

**Issue by Uzifly** [open-metadata/OpenMetadata#16390]
**Affected module**
UI, backend.

**Describe the bug**
API and UI doesn't return shart search result (chart_search_index). 

**To Reproduce**
![Search bug](https://github.com/open-metadata/OpenMetadata/assets/111077672/418fc3e9-b7f0-41d1-9a40-eca89ff09527)

**Expected behavior**
Get the corresponding result on request.

**Version:**
 - OS: debian 11
 - Python version: 3.9.2
 - OpenMetadata version: 1.3.4
 - OpenMetadata Ingestion package version: 1.3.4

**Comment by OnkarVO7** [comment]
We'll implement the same approach here as we do for `table->columns`.

When searched for a chart, the related dashboard should be shown in the results for the same.

**Comment by sonika-shah** [comment]
The changes have been successfully merged in [[PR #< 16646 >]](https://github.com/open-metadata/OpenMetadata/pull/16646). This issue has been resolved. 

Closing this issue now.
