### ISSUE TITLE
Classification propagate by lineage

### ISSUE THREAD

**Issue by fjh100456** [open-metadata/OpenMetadata#16400]
**Is your feature request related to a problem? Please describe.**
Classifications like PII were not propagated to its derived tables, it result in a poor user experience.

**Describe the solution you'd like**
It would be much better to allow classifications propagated by lineage.

**Describe alternatives you've considered**
No alternative option.

**Additional context**

**Comment by harshach** [comment]
Supported through our Metadata Automations
