### ISSUE TITLE
Lineage view issues for tables with many columns

### ISSUE THREAD

**Issue by zackcolello** [open-metadata/OpenMetadata#16404]
**Affected module**
UI

**Describe the bug**
The new lineage view in OpenMetadata v1.4.0 opts to have the column-level layer enabled by default -- this means that when looking at a lineage view for tables that include a large amount of columns each (e. g. 20-40 columns), the lineage graph is a bit more difficult to use by default.

When I disable the column layer to get a better sense of what the lineage looks like, the lineage graph seems to disappear, but in reality the graph has been moved "up", and I have to click the zoom-related button to re-focus the graph. I feel this could be confusing for end users, especially since the zoom-related buttons are pretty small.

This is also just an opinion -- but I think defaulting to having all columns enabled when opening up lineage might not be as good of a user experience as having either none of a subset of columns displayed (like in pre-1.4.0), giving how much visual space is taken up by all of the columns. This could be alleviated by providing a configuration setting to change this default behavior. Y'all would know better than me on this though, so just my 2 cents.

**To Reproduce**
Unfortunately I cannot provide screenshots due to company PII concerns, and I'm not able to find an example in sandbox OpenMetadata to point to for this issue. But this should be easily reproducible for any lineage graph that contains several tables with 20-40 columns each.

**Expected behavior**
I would think that when a column layer is enabled or disabled, the graph should refocus itself as needed for a better user experience. Otherwise, I would expect the ability to control whether or not all of the columns get displayed by default.

**Version:**
 - OS: n/a
 - Python version: n/a
 - OpenMetadata version: 1.4.0
 - OpenMetadata Ingestion package version: n/a

**Additional context**

**Comment by DovileKr** [comment]
Relates to https://github.com/open-metadata/OpenMetadata/issues/16359
