### ISSUE TITLE
Data Quality Report Improvements

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#16422]
### Overview section in DQ tab [Collate]
Summary of execution broken down by dimensions:
- Completeness: missing count, not null, etc. test types
- Accuracy/validity: how accurate the data represent the real world (column count, column value to be between, etc.)
- Consistency: how consistent the data are across different entities (e.g. table diff test)
- Uniqueness: 

### Improve Metrics reporting on DQ Page
- Show Total Entities (Supporting DQ tests)
- Show Entities with test (and coverage %)
- Fully healthy entities

### Incident Manager Reporting [Collate]
- Open incidents (non resolved)
- Time to Response (from new to first ack/assign)
- Time to Resolution (from new to resolved)

**Comment by DovileKr** [comment]
Please don't forget DQ checks per glossaryTerm :)

**Comment by TeddyCr** [comment]
> Please don't forget DQ checks per glossaryTerm :)

@DovileKr, thanks for the message. This ☝️ will be covered by the rework we are doing when it comes to the Data Inisght [here](https://github.com/open-metadata/OpenMetadata/issues/10204). This issue is specific to the DQ pages.
