### ISSUE TITLE
Don't build metadata lineage with MSSQL Server when queries contain square brackets.

### ISSUE THREAD

**Issue by Uzifly** [open-metadata/OpenMetadata#16424]
**Affected module**
Ingestion(metadata, lineage)

**Describe the bug**
The view definition contains queries like from [database].[schema].[table] in square brackets. Such requests are not processed by the parser and no connections are built. If we remove the square brackets in the query, then the lineage appear.

**To Reproduce**
This problem occurs when ingesting metadata from MSSQL Server. Specify a [schema] or [table] in the view definition in square brackets and you won't get the lineage.

**Expected behavior**
Perhaps for some reason the method in /ingestion/src/metadata/ingestion/lineage/parser.py insensitive_match does not work

**Version:**
 - OS: debian 11
 - Python version: 3.10
 - OpenMetadata version: 1.3.4
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==1.3.4

**Comment by Uzifly** [comment]
I got debug information:
Method Clean_table.schema.raw_name, r"\[(.*)\]", r"\1" 
returns "db].[schema.table".
You need to fix regexp.

**Comment by SumanMaharana** [comment]
Hello @Uzifly this issue is fixed within the sqlfluff repo with this [PR](https://github.com/sqlfluff/sqlfluff/pull/6001)
Closing this issue. Thanks

**Comment by sqlparser** [comment]
Just a small follow-up for anyone who lands here from search and still sees empty lineage after upgrading — the [sqlfluff PR #6001](https://github.com/sqlfluff/sqlfluff/pull/6001) fix mentioned above genuinely solves the bracket-regex problem @Uzifly isolated (the `r"\[(.*)\]"` → `r"\[(.*?)\]"` non-greedy fix works exactly as predicted). Nice root-cause analysis on the way in.

There's one adjacent case that the regex fix alone doesn't cover, though, which I think explains why a subset of users still report "brackets still break my lineage" post-upgrade: **bracket identifiers inside a T-SQL stored-procedure wrapper**.

Minimal repro:

```sql
CREATE PROCEDURE [dbo].[usp_RefreshOrders]
AS
BEGIN
    INSERT INTO [ReportDB].[dbo].[OrderSummary] (OrderID, Total)
    SELECT [OrderID], [TotalAmount]
    FROM   [SalesDB].[dbo].[Orders]
END
```

The brackets are parsed correctly now (thanks to #6001), but the enclosing `CREATE PROCEDURE ... AS BEGIN ... END` wrapper still defeats the three-parser chain in `collate-sqllineage`, so the whole statement is silently skipped and no lineage edge is produced. That's the symptom cluster tracked in #16737, #17586, and #25299.

For anyone who needs lineage on that combined shape today, we maintain a small non-invasive companion tool, [gsp-openmetadata-sidecar](https://github.com/gudusoftware/gsp-openmetadata-sidecar), that handles both the bracket-identifier resolution *and* the T-SQL procedural wrapper, then pushes lineage through OpenMetadata's public `PUT /api/v1/lineage` API. It doesn't patch core — it complements whatever `collate-sqllineage` produces.

Dry-run on the combined SQL above:

```
SalesDB.dbo.Orders --> ReportDB.dbo.OrderSummary (2 columns)
  OrderID     → OrderID
  TotalAmount → Total
```

```bash
pip install gsp-openmetadata-sidecar
gsp-openmetadata-sidecar --sql-file your_view_or_proc.sql \
                         --db-vendor dbvmssql --dry-run
```

Fuller write-up with three bracket-related failure patterns side-by-side (view definitions, cross-database 3-part names, and procedure-wrapped brackets):

- [Why MSSQL stored-procedure lineage is silently empty in OpenMetadata (and the fix)](https://www.dpriver.com/blog/2026/04/openmetadata-mssql-stored-procedures-why-your-lineage-is-silently-empty-and-how/?utm_source=openmetadata&utm_medium=oss&utm_campaign=issue-16424&utm_content=blog-walkthrough) — narrative deep-dive with side-by-side reproductions
- [OpenMetadata MSSQL sidecar landing page](https://www.sqlparser.com/openmetadata/?utm_source=openmetadata&utm_medium=oss&utm_campaign=issue-16424&utm_content=landing-page) — same patterns shown with install + CLI quickstart

Totally fine to leave this ticket closed — the specific bug @Uzifly reported is genuinely fixed. Just wanted to leave a breadcrumb for the next person who arrives after a 1.4.x+ upgrade wondering why their procedure-wrapped view lineage is still empty.

*(Disclosure: I work at Gudu Software. The sidecar is open and free; backend has an anonymous tier and a self-hosted Docker image for teams that need data to stay in-network.)*
