### ISSUE TITLE
Glossary terms ownership shows "No owner"

### ISSUE THREAD

**Issue by aballiet** [open-metadata/OpenMetadata#16431]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

UI

**Describe the bug**

<img width="914" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/25565600/fd1772a1-73fd-441c-952e-e823828347c7">

Where term has an owner : 

<img width="1351" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/25565600/2a26c9af-d80d-455c-9813-5011fb905b36">

**To Reproduce**

Create a glossary term and add an owner

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aballiet add OpenMetadata version to it. Does the parent has a owner already?
