### ISSUE TITLE
Create a Connector to Pentaho Data Integration

### ISSUE THREAD

**Issue by AlexandreSilvaPereira** [open-metadata/OpenMetadata#16447]
**Feature**
Add Connector to Pentaho Data Integration 

**Describe the task**
Add Connector to Pentaho Data Integration.

**Comment by Marcus1911** [comment]
@AlexandreSilvaPereira please add extra details. 
1) Which kind of connector should be implemented: a.e odbc. 
2) Should we handle Kettle? 
3) Do you have any potential use cases?
