### ISSUE TITLE
role create glossaryTerm doesn't work for the first level

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#16458]
**Affected module**
UI

**Describe the bug**
if a person is given a role that has a policy to create glossaryTerm, they don't have the option to ADD Term immediately in the glossary, but do have an option to create glossaryTerm under the parent term. 

This is a bug

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/52b90168-a994-432b-8ae8-e61c6109a458)

**Expected behavior**
has Add Term

**Version:**
newest 1.4

**Additional context**

**Comment by DovileKr** [comment]
@karanh37 please provide update for this bug

**Comment by harshach** [comment]
@DovileKr we have priorities with other features. We will get to this issue.

**Comment by karanh37** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/16874
