### ISSUE TITLE
API Support for Bulk add and remove Asset in Teams and User

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#16451]
**Feature**
- API Support for `Bulk` add and remove Asset in `Teams and User`

**Describe the task**

UI issue : https://github.com/open-metadata/OpenMetadata/issues/10670

- [ ] Teams : Bulk add and remove asset for Entities for Team, currently in Team we only support bulk add for User.
- [ ] Users : Same bulk add and remove asset for adding user as owner and following for the entities.

**Comment by harshach** [comment]
Since we shipped Metadata Automations we will not add this option.
