### ISSUE TITLE
When creating Athena cross account connector, it requires `default` database to be created. 

### ISSUE THREAD

**Issue by gsumar** [open-metadata/OpenMetadata#16476]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? Ingestion Framework

**Describe the bug**

![image](https://github.com/open-metadata/OpenMetadata/assets/32468623/0acf73d4-e763-444f-98fe-361fddaf16e5)

```
An error occurred (MetadataException) when calling the ListTableMetadata operation: Database default not found. (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 45914404-2fad-4053-997a-7b1a9e28145e; Proxy: null)
```

When creating an Athena Connector cross account is fails testing the connection if a `default` database doesn't exist.

**To Reproduce**

![image](https://github.com/open-metadata/OpenMetadata/assets/32468623/2fa02ef9-9ddc-473f-bbe0-2918e0338e45)

Without a `default` database created in the account that we want to ingest metadata from.

**Expected behavior**
The connectivity test passes with no issues. 

**Version:**
 - OS: [e.g. iOS]   macOS 14.4.1
 - Python version: 3.11
 - OpenMetadata version: [e.g. 0.8] 1.2, 1.3 and 1.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

https://github.com/open-metadata/OpenMetadata/releases/download/1.4.0-release/docker-compose-openmetadata.yml

**Additional context**

**Comment by harshach** [comment]
@ulixius9 can you review this?
