### ISSUE TITLE
Tableau Charts (Worksheets) don't appear in the assets of a glossary term

### ISSUE THREAD

**Issue by asafla** [open-metadata/OpenMetadata#16475]
**Affected module**
UI

**Describe the bug**
If I attach a glossary term to a Tableau Chart (Worksheets), I expect to see the chart on the glossary term's assets, and I don't.

**To Reproduce**

1. Add a glossary term to a Tableau Chart
![image](https://github.com/open-metadata/OpenMetadata/assets/79054184/c9b1583b-969b-4769-b361-64e97dd1b60e)
2. Go to the glossary term's "Assets"
![image](https://github.com/open-metadata/OpenMetadata/assets/79054184/33275391-5114-402a-add1-fa90d7d8da54)
3. Observe the absence of the Tableau chart
![image](https://github.com/open-metadata/OpenMetadata/assets/79054184/856a254c-f745-415a-aa88-1fa203c55e27)

**Expected behavior**
In the "Assets" tab of the glossary term, I expect to see the Tableau charts that are linked with the specific glossary term.

**Version:**
 - OS: Mac Sonoma 14.5
 - Python version: No clue
 - OpenMetadata version: 1.3.4
 - OpenMetadata Ingestion package version: No clue either

**Additional context**
I'm a Wix employee, working with the Wix production environment of the OMD, so maybe it'll give you a hint regarding the Python version and the ingestion package version.

**Comment by Prajwal214** [comment]
@asafla Can you perform re-indexing & let us know if the issue is still persisting.
 
https://docs.open-metadata.org/v1.4.x/how-to-guides/admin-guide/Reindexing-Search

**Comment by asafla** [comment]
Turns out we perform re-index every night.

**Comment by asafla** [comment]
Hey @Prajwal214 , the problem still exists despite re-indexing, any news regarding that issue?

Thanks,
Asaf.

**Comment by Prajwal214** [comment]
@asafla We have an issue opened for this [Issue #16390 on GitHub](https://github.com/open-metadata/OpenMetadata/issues/16390). At present, Charts are not being retrieved through Elastic Search.
