### ISSUE TITLE
[Glossary/Classification] Add tool tip / info note for mutually exclusive saying it cannot be changed later

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#16516]
**Feature**
Add feature issue reference

While creating the glossary/classification we need some information for user to state about not being able to change mutually exclusive later , since it causes some serious issue . Adding a tool tip we'll make it more clear

**Describe the task**

**Comment by TeddyCr** [comment]
@mohityadav766 users should be able to remove it, though.

**Comment by mohityadav766** [comment]
> @mohityadav766 users should be able to remove it, though - there is no constraint there.

@TeddyCr I feel that might be inconsistent/ not uniform behaviour , that we allow only one way update from false to true , but not from true to false, we can definitely handle it but just want to make sure we are not creating more confusion for the users . @harshach wdyt we should do in this case?

**Comment by chirag-madlani** [comment]
As per conversation with @harshach 
We won't be allow any changes for "Mutually Exclusive" flag post creation. However we will caution user for the same that once it's set it can't be changes.
cc: @mohityadav766 @TeddyCr @Ashish8689
