### ISSUE TITLE
Non-discrete values on y-axis in test suite graphs

### ISSUE THREAD

**Issue by sandervanlaar** [open-metadata/OpenMetadata#16535]
**Affected module**
UI

**Describe the bug**
The graphs from the test suite displays unlogical y-axis values.

1. It shows non-discrete values, like 22.5 and 23.5, while the test result is always discrete. It is either number of ROWS or COUNT. See picture below.
2. It shows values of '1K', while the value must/could be 1025 and 1026. See picture below.

**To Reproduce**

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/7271324/b2257861-f1e1-4731-ab5e-206458be39bb)
![image](https://github.com/open-metadata/OpenMetadata/assets/7271324/b5dc4b88-bfb6-4694-911b-c22cf1a272d0)

**Expected behavior**
Y-axis labels should be discrete for tests based on SQL queries, since the result is either ROWS or COUNT.
Y-axis labels should not be abbreviated to 1K, but written as the exact value, like 1025.

**Version:**
 - OS: Windows 11 Server
 - Python version: 3.12
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: n/a

**Comment by ShaileshParmar11** [comment]
We have improved the scaling of the graph; please feel free to try the latest release.
