### ISSUE TITLE
Add a search field in Profiler & Data Quality

### ISSUE THREAD

**Issue by noelaum** [open-metadata/OpenMetadata#16547]
Hi OMD Team/Community,

We're currently on OMD v1.4.0.

Is it possible to add a search field in Profiler & Data Quality?
This would make it easier to search for specific tests, especially when there are many tests created and managing them becomes challenging.
Thank you!
![Screen Shot 2024-06-06 at 9 04 51 AM](https://github.com/open-metadata/OpenMetadata/assets/83212243/30ba2aa8-9f7b-4d6f-9955-efe5146505f6)

**Comment by TeddyCr** [comment]
@ShaileshParmar11 we should switch to the same endpoint we use in the DQ page.
