### ISSUE TITLE
Don't add edge to lineage

### ISSUE THREAD

**Issue by maximutkin** [open-metadata/OpenMetadata#16565]
**Affected module**
There is no way to connect a pipeline between an s3 container and a table. Both using the UI and using the API.

**Describe the bug**
Entity table
Entity of dag pipeline
Entity bucket container s3

Performing an append using the API codec to the following error.

Use API - PUT /v1/lineage

```
{
  "edge": {
    "description": "string",
    "fromEntity": {
      "fullyQualifiedName": "test_click.default.clck.tech_events",
      "id": "20401cc2-e5f2-4eed-b0c8-68e829e2da56",
      "type": "table"
    },
    "lineageDetails": {
      "pipeline": {
        "fullyQualifiedName": "airflow_source.rec_data_collector_pvc",
        "id": "d83bd28a-8bd9-472e-832a-a41f39242e43",
        "type": "pipeline"
      }
    },
    "toEntity": {
      "fullyQualifiedName": "local_s3.rec-data-storage.rec",
      "id": "78e183ef-9d30-4c7c-8253-db63c1d8490b",
      "type": "container"
    }
  }
}
```

RESPONSE

```
{
  "code": 200,
}
```
But the Edge pipeline attribute is missing from the Edge information.

![image](https://github.com/open-metadata/OpenMetadata/assets/79041798/703f1477-37ba-4d33-8079-ff1072eb94c6)

**Expected behavior**
Containers and tables must also be connected by a pipeline.

**Version:**
 - OS: macOS Sonoma 14.3
 - Python version:  3.10.6
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: openmetadata-ingestion[kafka,postgres,airflow, athena]==1.4.1

**Comment by karanh37** [comment]
We currently support pipeline edges between tables and topics. Containers are not yet supported.

**Comment by maximutkin** [comment]
As I understand it, pipeline edges with mlmodel are also not yet supported.

**Comment by karanh37** [comment]
> As I understand it, pipeline edges with mlmodel are also not yet supported?

Yes currently pipeline is supported for tables and topics. We will evaluate this and add this support for all relevant entities.

**Comment by karanh37** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/16960
