### ISSUE TITLE
Bug: Creation of alerts with special characters redirect to empty page

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#16570]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI / Backend

**Describe the bug**

Special Character in the name while creating the alert throws an error

https://github.com/open-metadata/OpenMetadata/assets/40225091/7e17cc63-5783-4c9f-88ac-a71955c6fbdc

**To Reproduce**
Create an alert with the name `Bug.Test` ( special character being `.` )

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by aniketkatkar97** [comment]
Fixed in #18448
