### ISSUE TITLE
Redoc API with parameters doesn't work in secure or non-secure mode

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#166]
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1417689/129458040-126b5cd1-5812-4bf9-999e-55103b49a767.png">
ke

**Comment by Sachin-chaurasiya** [comment]
We tried this API in redoc and API was successful but the response was blank.

http://localhost:8585/api/v1/usage/compute.percentile/table/2021-03-25
