### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by thisisvk45** [open-metadata/OpenMetadata#16645]
Affected module
This issue impacts the Ingestion Framework of OpenMetadata, specifically the Python script attempting to utilize the `metadata.ingestion.api.source` module to import the `Source` class for data ingestion tasks.

Describe the bug
The Python environment throws a `ModuleNotFoundError` indicating that the `Source` class cannot be found in `metadata.ingestion.api.source`. This error suggests either the class does not exist at the specified location, the package is not correctly installed, or the package's internal structure has been changed.

Expected behavior
The expected behavior is for the Python script to successfully import the `Source` class from the specified module, allowing the script to proceed with the data ingestion processes defined in it.

Version:
 - OS: Ubuntu 
 - Python version: 3.8 
 - OpenMetadata Ingestion package version: `openmetadata-ingestion==1.3.2.0`

![Screenshot from 2024-06-13 12-17-32](https://github.com/open-metadata/OpenMetadata/assets/97878275/0342daf5-64fe-45b4-9cdf-cacb0f2d07b8)

**Comment by sushi30** [comment]
is this still occurring in 1.4.3?

**Comment by harshach** [comment]
@thisisvk45 Update to latest release to test out and let us know if you are still facing the issue

**Comment by thisisvk45** [comment]
It is working now
________________________________
