### ISSUE TITLE
Glossary Import/Export not support format ( UTF-8 encoding) 

### ISSUE THREAD

**Issue by halv-123** [open-metadata/OpenMetadata#16657]
**Affected module**
Govern->Glossary->Import
Govern->Glossary->Export
**Describe the bug**
I tried to import a glossary term CSV file containing DBCS Vietnamese characters. The import is successful but all Vietnamese characters become garbage characters.
**To Reproduce**

Export result
![export_csv](https://github.com/open-metadata/OpenMetadata/assets/172566674/d7a6f4a7-d224-49de-a1d0-89501929b95a)

Import result
field data not support format UTF-8  when i import success: 
->>>> háº£o lÆ¡ háº£o lÆ¡

**Expected behavior**

![OM_display_add_term_test](https://github.com/open-metadata/OpenMetadata/assets/172566674/f4aac47a-76d4-4f2d-9193-b0a46fa52ded)

Since we can enter and display Vietnamese characters in OM. Importing/Export should work, too.

**Version:**
 - Python version:
 - OpenMetadata version:  1.4.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
N/A

**Comment by sonika-shah** [comment]
hello @halv-123 , could you confirm if you are still facing the same issue with latest OM version ?
