### ISSUE TITLE
Changing 'results per page' fails: 'Something went wrong'

### ISSUE THREAD

**Issue by sandervanlaar** [open-metadata/OpenMetadata#16655]
**Affected module**
UI

**Describe the bug**
Changing the 'results per page' fails in some cases. 
Produced Error message: 'Something went wrong' and 'Cannot read properties of undefined (reading 'localeCompare')'

**To Reproduce**

1. Click on Observability > Data Quality
2. Select Tab 'By Test Suites'
3. Select a Test Suite
4. Click on 'NAME' to sort ascending
5. Then below click on '15/Page' and change the drop-down value to '50/Page'

Result: error message.

**Expected behavior**
Expected: 50 results per page, sorted ascending on 'NAME'

**Version:**
 - OS: Windows 2022 Server
 - Python version: 3.8.10
 - OpenMetadata version: 1.4.0
 - OpenMetadata Ingestion package version: n/a

**Comment by ShaileshParmar11** [comment]
Hello @sandervanlaar,
Could you please share a screen recording of the error? We followed the provided steps but did not encounter any issues.

https://github.com/open-metadata/OpenMetadata/assets/71748675/bbe03fda-451c-4766-b11a-8540eecf8ac7

**Comment by sandervanlaar** [comment]
You did not select a single Test Suite first, then Click on Name to sort, then select one of the other number of results per page. Then I get the error message. 

You could also try: Data Quality > By Test Cases; sort Name (by clicking on the header); Select '50/Page' or '25/Page' --> error message: Something went wrong
Cannot read properties of undefined (reading 'localeCompare')

**Comment by sandervanlaar** [comment]
I just found out that this issue also occurs in the Collate Sandbox v1.4.7.

1. Click on Observability > Data Qualty
2. Select 'By Test Cases'
3. Click on column name 'NAME' to order on this column name
4. At the bottom of the page, click on 'Next'
5. Result: error message 'Something went wrong'
