### ISSUE TITLE
Kerberos with hive

### ISSUE THREAD

**Issue by luhea** [open-metadata/OpenMetadata#16651]
**Affected module**
Hi,
I'm going to capture a hive data source with kerberos authentication enabled, But the connectionArguments in serviceConnection get an error when written this way.
            connectionArguments={ "auth": "KERBEROS", "kerberos_service_name": "hive", }
What is the premise of writing this way? Or how do I transfer krb5.conf and keytab files.

can i config kerberos with hive

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OS: K8S
 - Python version:
 - OpenMetadata version: [1.4.1]
 - OpenMetadata Ingestion package version: Helm Install

**Additional context**

**Comment by ulixius9** [comment]
Hey @luhea, can you please open a thread on https://slack.open-metadata.org/ support channel, we may need more info here and we maybe able to assist you to configure your hive.

closing this ticket for now, if any improvement or fix required then we can reopen this.
