### ISSUE TITLE
GCS Storage Container support

### ISSUE THREAD

**Issue by MChamberlin** [open-metadata/OpenMetadata#16652]
**FEATURE REQUEST**: Support GCS (Google Cloud Storage) connector for Storage service.

GCS seems like an important integration to have. Currently only S3 is supported out-of-the-box. Can we please add a GCS connector?

Thanks!

**Comment by harshach** [comment]
GCS Supported https://docs.open-metadata.org/v1.4.x/connectors/storage/gcs

**Comment by MChamberlin** [comment]
@harshach 
Hm, I suspect the docs are wrong here. I do not see code for a GCS storage source connector [in any of the latest releases](https://github.com/open-metadata/OpenMetadata/tree/1.4.3-release/ingestion/src/metadata/ingestion/source/storage). The image links in the docs for adding a new source connector are broken. And indeed I see no GCS tile when trying to create a storage service while running the latest release:
![Screenshot 2024-06-25 at 2 55 02 PM](https://github.com/open-metadata/OpenMetadata/assets/4731479/61d03e00-f251-4185-b26a-cf29d52d3fda)
