### ISSUE TITLE
 POSTGRES Test case using columnValuesToMatchRegex in Data quality for a number column.

### ISSUE THREAD

**Issue by mvpkarthik1** [open-metadata/OpenMetadata#16677]
**DATA QUALITY**

I have an issue with Test case pipeline in Data quality.
I have used postgres connection.
Ingested metadata and profiler.
I have created a test case with ID column which is a number column
I have used testDefinition: "columnValuesToMatchRegex"
When I run the pipeline, it fails.
The error is
**ERROR - Failed to execute job 35912 for task test_suite_task (('TestCaseRunner reported errors', Status(source_start_time=1718088994.8943944, records=[], warnings=[], filtered=[], failures=[StackTraceError(name='test case for ID', error='Could not run test case test case for ID: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block\n\n[SQL: /* {"app": "OpenMetadata", "version": "1.2.5.3"} */\nSELECT SUM(CAST(CASE WHEN (id LIKE %(id_1)s) THEN %(param_1)s ELSE %(param_2)s END AS BIGINT)) AS "likeCount" \nFROM public.cdm_work_items \n LIMIT %(param_3)s]\n[parameters: {\'id_1\': \'p*\', \'param_1\': 1, \'param_2\': 0, \'param_3\': 1}]**

**psycopg2.errors.UndefinedFunction: operator does not exist: numeric ~ unknown\nLINE 2: SELECT SUM(CAST(CASE WHEN (id ~ \'p*\') THEN 1 ELSE 0 END AS B...\n                                      ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback
Its not considering the column datatype.**

OM generated query not considering the datatype of the ID column as if it is VARCHAR, instead it is a number column.

OM version is 1.2.5
POSTGRES Version: 
PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
Example test case: 
We are using to check all IDs with 9* for instance.

**Comment by sushi30** [comment]
closing this in favor of the 2 more specific issues
