### ISSUE TITLE
Add tag/tier filter in Profiler Ingestion

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#16679]
Hi,

Being able to generate profilers dynamically would be a great help, since we for example generate profilers for golden assets, if we had a filter that allowed us to filter by tag or by tier, it would allow us to dynamically run the profiler without the need to constantly add tables or remove tables from the profiler.

![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/04d1900e-56d6-4383-9399-038a74799a69)

thanks,

**Comment by TeddyCr** [comment]
Hello @triquinielas closing this as we shipped this functionality in 1.6
