### ISSUE TITLE
UI / Lineage - Mark deleted dashboard

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#16681]
**Is your feature request related to a problem? Please describe.**
When the **Mark Deleted Dashboards** is enabled, it's not possible to identify if the DS is deleted in the lineage view.

**Describe the solution you'd like**
Maybe, change the border color for deleted assets or add an icon.

![Capture d’écran 2024-06-17 à 12 06 45](https://github.com/open-metadata/OpenMetadata/assets/75131226/164fd4fa-e207-4446-9ca6-9cc55dc2ed5e)

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
cc @karanh37
