### ISSUE TITLE
Draft glossaryTerms: link to assets and create child terms

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#16680]
**Is your feature request related to a problem? Please describe.**
At the moments for draft terms we can't
Add child terms
Link assets (use them for tagging)

**Describe the solution you'd like**
Draft terms should have same functionality as approved terms, just have different behavior in search. As in https://github.com/open-metadata/OpenMetadata/issues/16278

**Describe alternatives you've considered**
**Use case**: project team are working together on the number of glossary terms. They are all in Draft until all reviewed and confirmed.

**Additional context**

**Comment by DovileKr** [comment]
We utilize the Glossary terms to represent Data Entity => Data Attribute => Reference Value

For example: Product => Product Type => [Shoes; Dresses; Cars]

So for example a team for a Data Governance project is defining some Data Entities, Attributes and Reference Values. 

In our process - the Data Entity Terms can only be approved IF 
Attributes are available (and attributes have reference value defined)
Lineage (link to assets is documented). 

Meaning Approved glossaryTerm can mean a lot more than just description, synonym, tag, owner.  And now it can't be done.

And until 1.4.1 Admins could do that (at least add childTerms), as my users raised it as something that stopped working.

**Comment by harshach** [comment]
A Glossary Term in draft mode shouldn't be linked to an asset. This will cause confusion that users can essentially use a unapproved / draft glossary term to tag the assests. In such case what is approval process is even there for as any one can use the draft term as they wish

**Comment by DovileKr** [comment]
@harshach ok. We understand your thinking and will adapt our process accordingly.

Maybe only suggestion - ability to change the Glossary Status back (from Approved to Draft) as this also might happen.

**Comment by DovileKr** [comment]
@harshach  suggested improvement https://github.com/open-metadata/OpenMetadata/issues/16913

**Comment by harshach** [comment]
This is fixed in 1.6
