### ISSUE TITLE
[Data Quality] Column is displayed for unsupported columns

### ISSUE THREAD

**Issue by sushi30** [open-metadata/OpenMetadata#16699]
**Affected module**
UI

**Describe the bug**
When defining a column test, I expect only relevant tests to be offered given the column data type.
For example, the `columnValuesToMatchRegex` is only expected to run on `STRING` types yet I am offered to run it on a numeric type in this example:
![image](https://github.com/open-metadata/OpenMetadata/assets/26347589/5d2b0722-ac22-4f47-bb40-47dc8aba1a2d)

**Expected behavior**
For a column test, display only the tests that apply to the column data type.

**Version:**
 - OpenMetadata version: 1.4.3

**Comment by TeddyCr** [comment]
```
{
  "name": "columnValuesToMatchRegex",
  "fullyQualifiedName": "columnValuesToMatchRegex",
  "displayName": "Column Values To Match Regex Pattern",
  "description": "This schema defines the test ColumnValuesToMatchRegex. Test the values in a column to match a given regular expression. ",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata"],
  "supportedDataTypes": ["BYTES", "STRING", "MEDIUMTEXT", "TEXT", "CHAR", "VARCHAR"],
  "parameterDefinition": [
    {
      "name": "regex",
      "displayName": "RegEx Pattern",
      "description": "The regular expression the column entries should match. For database without regex support (i.e. MSSQL, AzureSQL) this test will use `LIKE`.",
      "dataType": "STRING",
      "required": true
    }
  ],
  "supportsRowLevelPassedFailed": true,
  "provider": "system"
}
```

The test definition has the supported dtype, we should check if it is enforced correctly from the ui
