### ISSUE TITLE
Unable to copy link by the share button

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16709]
**Affected module**
UI issue

**Describe the bug**
We cannot copy link by clicking the `share` button

**To Reproduce**

1. go to a table 
2. click share button
3. paste
4. nothing is pasted

**Expected behavior**
url can be pasted after click this button

**Version:**
 - OS: windows
 - Python version: 3.9
 - OpenMetadata version: 1.4.1 bare-metal
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by datapopcorn** [comment]
![IMG_7056](https://github.com/open-metadata/OpenMetadata/assets/142566886/16dbe15d-216c-4dd1-9d10-ec9710732d59)
![IMG_7057](https://github.com/open-metadata/OpenMetadata/assets/142566886/e6983459-6da1-46d5-a841-3ae1f1bada4e)
![IMG_7058](https://github.com/open-metadata/OpenMetadata/assets/142566886/5a17bc5b-94ef-4b7b-94a6-9f745721fd11)

**Comment by Ashish8689** [comment]
@datapopcorn, we couldn't replicate the issue in versions 1.4.1 or 1.4.3 on both macOS and Windows. We're closing this issue for now but can reopen it if the problem recurs in the future.
