### ISSUE TITLE
ingest-dbt: description update does not work

### ISSUE THREAD

**Issue by SabineGl** [open-metadata/OpenMetadata#16704]
**Affected module**
i**ngestion framework:**

- ingest dbt
- ingest postgres

**Describe the bug**
create description in dbt and ingest it to OM works only once. No update is possible. 
If i run ingest postgres without table comments. The descriptions will be updated as expected in OM after I run ingest (dbt descriptions).

The update is visible in dbt ui but not in OM descriptions.
EVEN if I drop the existing database in postgres WITHOUT table comments and I do the metadata ingest prostgres.yaml AFTER wards somehow it REMEMBERS column descriptions for the deleted and new created postgres db. 
It ignores completely changes from dbt description ingests (it works in original DBT ui - there you can see the changes properly.

**To Reproduce**
- create an table without descriptions in postgres
- ingest postgresdata to om
- add descriptions in dbt source.yaml
- dbt run, dbt docs generate
- ingest dbt comments to OM
- descriptions will be updated
- now try to change an existing description in dbt and update it

Screenshots or steps to reproduce

![image](https://github.com/open-metadata/OpenMetadata/assets/130458131/4614bdc7-6508-4ec2-8703-fdae48127c37)
![image](https://github.com/open-metadata/OpenMetadata/assets/130458131/945418c0-2c44-410e-997d-a48afd500816)
![image](https://github.com/open-metadata/OpenMetadata/assets/130458131/108b6dab-08bc-4d15-9486-6efadc5368a5)

**Expected behavior**

- we want to maintain descriptions in dbt. all comments and changes should be updated. 
- when I drop a table in postgres I would like to have the possibility not to reuse existing information or to have at least an overwrite option

**Version:**
 - Python version: 3.10
 - OpenMetadata version: 1.4.3
 - OpenMetadata Ingestion package version: openmetadata-ingestion == 1.4.3.1

**Additional context**

**Comment by harshach** [comment]
@OnkarVO7 can you review to see if its indeed an issue?

**Comment by OnkarVO7** [comment]
Hi @SabineGl can you please check if you have enabled the `dbtUpdateDescriptions` config by following the docs [here](https://docs.open-metadata.org/v1.4.x/connectors/ingestion/workflows/dbt/ingest-dbt-descriptions#overriding-the-existing-table-and-column-descriptions)

Please reach out on slack https://slack.open-metadata.org/ we can discuss there if this indeed is an issue and re-open the ticket
