### ISSUE TITLE
SAML - How to pass in the SP's private key?

### ISSUE THREAD

**Issue by diminishin** [open-metadata/OpenMetadata#16723]
**Is some content missing, wrong or not clear?**
This is the SAML configuration document: https://docs.open-metadata.org/v1.4.x/deployment/security/saml

Within it, it mentions this
Service Provider (SP) Configuration
Openmetadata is the service provider, we just update the localhost to the hosted URI.
EntityId/Authority -> Normally a Url providing info about the provider.
SignOn Url -> Url to be used for signing purpose.
X509 Certificate -> In case the SP expects a signed response from IDP, the IDP can be configured with Signing Certificate given by SP.
**Private Key -> In case SP expects a encrypted response from the IDP , the IDP can be configured with SPs public key for encryption and the Private Key can be used for SP for decrypting.**
SP Metadata XML is available at "http://localhost:8585/api/v1/saml/metadata", localhost needs to be updated with the correct URI.

But from the available configuration provided for SP, there isn't any parameters for private key.

**Describe the solution you'd like**
I would like to know how do i pass in the private key for the SP. Would also be great if the documentation can be updated accordingly.

**Additional context**

**Comment by harshach** [comment]
cc @mohityadav766 @Prajwal214 can we document this clearly

**Comment by Prajwal214** [comment]
@diminishin You can add the Private key in the keystore and configuration the details in the yaml file. We will update the same in the document

https://github.com/open-metadata/OpenMetadata/blob/main/conf/openmetadata.yaml#L219

```
keyStoreFilePath: ${SAML_KEYSTORE_FILE_PATH:-""}
keyStoreAlias: ${SAML_KEYSTORE_ALIAS:-""}
keyStorePassword: ${SAML_KEYSTORE_PASSWORD:-""}
```

**Comment by harshach** [comment]
@Prajwal214 lets update the docs and close it out

**Comment by Prajwal214** [comment]
@diminishin We have updated the documentation on how to include a private key in the SAML configurations. Refer to the [documentation](https://docs.open-metadata.org/v1.3.x/deployment/security/saml#service-provider-sp-configuration).
