### ISSUE TITLE
regarding setting scaling_factor=0.18215 instead of 0.13025 in stage 1 vae training

### ISSUE THREAD

**Issue by MAFLIXD** [open-metadata/OpenMetadata#16726]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@MAFLIXD could you provide more details about the issue? hard to understand from the title.
