### ISSUE TITLE
Database Connector's sources should return `Create` Entities

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1673]
Many implemented sources are returning an `Iterable` of `Entity` models, rather than `CreateEntity`. For example, in the [sql_source](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/sql_source.py#L307).

This forces the unnecessary usage of generating IDs and FQDN, while that information should happen at the server-side during the ingestion.

We should revisit the different sources and make sure we are always using `Create` models. This will be more consistent with the expected logic from the package.

@harshach

**Comment by amiorin** [comment]
👍

**Comment by pmbrull** [comment]
cc @open-metadata/ingestion some sources such as `looker` are using the wrong entity definitions:
```
from metadata.ingestion.models.table_metadata import Chart, Dashboard
```

We should take this chance to clean this up and make sure we are always playing with JSON based entities
