### ISSUE TITLE
[EventResource] Add Pagination to events api

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#16736]
**Feature**
Add feature issue reference
Currently the Eventresource only Supports the timestamp based pagination where event can be fetched after a timestamp.
We need to add a paginated list endpoint which works like other APIs , where offset can be used to paginate over entities, this was asked feature.

**Describe the task**

**Comment by harshach** [comment]
@mohityadav766 can you add more details to the ticket?
