### ISSUE TITLE
DB2 ERROR: Did not recognize type 'BOOLEAN'

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16741]
**Affected module**
Backend

**Describe the bug**
OM can not recognize BOOLEAN data type

**To Reproduce**
Ingest a table which has column with "BOOLEAN" data type
Get the warning message: 
`[2024-06-17T15:45:21.465+0800] {logging_mixin.py:188} WARNING - /opt/airflow/lib64/python3.9/site-packages/ibm_db_sa/reflection.py:292 SAWarning: Did not recognize type 'BOOLEAN' of column 'XXX' `

some discussion are in the slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1712336244151299
**Expected behavior**
can ingest DB2 metadata without this error

**Version:**
 - OS: Redhat8.9
 - Python version: 3.9
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by ulixius9** [comment]
fixed with https://github.com/open-metadata/OpenMetadata/pull/16718
