### ISSUE TITLE
Search Index Error after using quotation marks “” to enclose keywords

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16749]
**Affected module**
backend

**Describe the bug**
using quotation marks “” to enclose keywords in the search bar, and found that it returned no results. However, after removing the quotation marks, the query returned the error shown in the second image.

**To Reproduce**
![index_error(1)](https://github.com/open-metadata/OpenMetadata/assets/142566886/1a66f4d5-2001-4b7b-868c-e80b56b65772)
![index_error(2)](https://github.com/open-metadata/OpenMetadata/assets/142566886/06463e73-3bcc-497c-a555-c94659931bba)

**Expected behavior**
No index error

**Version:**
 - OS: RedHat8.9
 - Python version: 3.9
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version:

**Additional context**

**Comment by harshach** [comment]
why are you using quotation marks and whats the use case we are not supporting?
