### ISSUE TITLE
Deployment: Which concrete permissions are necessary for Elasticsearch?

### ISSUE THREAD

**Issue by notniknot** [open-metadata/OpenMetadata#16746]
**Is some content missing, wrong or not clear?**
We have a managed Elasticsearch cluster where users only get access to specific indexes of the cluster via technical users. In order to configure the necessary permissions for OpenMetadata we would like to know, which one are necessary. This information is missing in the docs.

**Describe the solution you'd like**
A concrete list of permissions a user of an elasticsearch cluster should have to successfully deploy OpenMetadata.

**Comment by harshach** [comment]
ElasticSearch user needs to be able to create/delete/update indexes. We end up creating 30+ indexes
