### ISSUE TITLE
Search failed when typing || in search bar

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16750]
**Affected module**
backend(Elasticsearch)

**Describe the bug**
when I type || in search bar, the error "search_phase_execution_exception, reason=all shards failed" would appear

**To Reproduce**
type || in search bar

**Expected behavior**
No error

**Version:**
 - OS: RedHat8.9
 - Python version: 3.9
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by harshach** [comment]
@datapopcorn please do not open multiple issues and ask these questions in https://slack.open-metadata.org before opening a github issue
