### ISSUE TITLE
DB2 primary key cannot be ingested

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16752]
**Affected module**
Backend

**Describe the bug**
Once ingested DB2 metadata to OM,
some tables cannot be ingested for the error `Failed to ingest CreateTableRequest [xxx] due to api request failure: Invalid column name found in table constraint`.

The DDL we are using is quite normal like 

```
CREATE TABLE SCHEMA.TABLE_NAME
(
   COL1                 INTEGER         NOT NULL,
   COL2                 TIMESTAMP,
)

ALTER TABLE SCHEMA.TABLE_NAME
   ADD CONSTRAINT PK_TABLE_NAME
   PRIMARY KEY (COL1);
```
And other table that can be ingested into OM doesn't show the primary constraint it supposed to have on UI.

**To Reproduce**
Ingest DB2 table with primary key

**Expected behavior**
successfully ingest metadata from DB2 and primary key would show on UI

**Version:**
 - OS: RedHat8.9
 - Python version: 3.9
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: 

**Additional context**
slack discussion thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1718699940377519

**Comment by ulixius9** [comment]
fixed with https://github.com/open-metadata/OpenMetadata/pull/16755
