### ISSUE TITLE
Restrict Sign-In Access to Existing Users in OpenMetadata When Using Keycloak as Authentication Provider

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16763]
**Is your feature request related to a problem? Please describe.**
Yes, this feature request is related to a security and user management problem. Currently, when using Keycloak as the authentication provider, any user in ADFS can sign in to OpenMetadata without the OpenMetadata admin needing to pre-create the account. This can lead to unauthorized access and management challenges, as users who should not have access to OpenMetadata can still log in.

**Describe the solution you'd like**
I would like to have a feature that restricts the ability to sign in to OpenMetadata to only those users who have been explicitly created and approved by the OpenMetadata admin. This means that if a user does not exist in the OpenMetadata user list, they should not be able to log in, even if they are authenticated through Keycloak/ADFS.

**Describe alternatives you've considered**
One alternative considered was assigning the lowest possible permissions (deny all operations) to users who do not exist in OpenMetadata. However, this does not fully resolve the issue as it still allows unauthorized users to log in. Another alternative could be setting up an approval workflow where the admin must approve any new login attempt before the user can access OpenMetadata.

**Additional context**
This feature is crucial for maintaining the security and integrity of the OpenMetadata environment, especially in large organizations where many users have access to the authentication provider but should not have access to OpenMetadata. Adding this feature would greatly enhance control over who can access and manage metadata.

**Comment by harshach** [comment]
@mohityadav766 since you are looking into this, we can use enableSelfSignup to control the SSO based logins

**Comment by mohityadav766** [comment]
This Is fixed

**Comment by datapopcorn** [comment]
Hi, @mohityadav766 
Could you tell me in which version this is fixed.
Is there any config I should modify?

**Comment by datapopcorn** [comment]
I'm using OM 1.5.2
User can still create account on their own without pre create by admin.
Can you reopen this issue
