### ISSUE TITLE
connector for DUNDAS BI Dashboard

### ISSUE THREAD

**Issue by son-mostafa** [open-metadata/OpenMetadata#16776]
Hello to all Amazing community of OMD,

a rich and sophisticated BI dashboard tool is Dundas [https://www.dundas.com/](https://www.dundas.com/) it is a good service for OMD.
i was wondering if OMD community will make it or not.
thanks a lot.

**Comment by sushi30** [comment]
Hi @son-mostafa thank you for raising the issue. Will you be willing to contribute this connector to the community? We have a [dedicated documentation page for building a connector](https://docs.open-metadata.org/v1.4.x/developers/contribute/developing-a-new-connector) on OpenMetadata.
