### ISSUE TITLE
Profiling does not work with partition when using yaml.

### ISSUE THREAD

**Issue by tuanla42710** [open-metadata/OpenMetadata#16779]
- OS: linux
 - Python version: 3.9
 - OpenMetadata version: 1.4
 - 
* Problem: When i run the metadata ingestion from a yaml file with enabling partition (value 1 for column "number") , it still run profiler for whole table.

This is my yaml file:

source:
  type: connection
  serviceName: trino
  sourceConfig:
    config:
      type: Profiler
      generateSampleData: true
      computeMetrics: true
      profileSample: 85
      threadCount: 5
      processPiiSensitive: false
      confidence: 80
      timeoutSeconds: 43200
      databaseFilterPattern:
        includes:
          - database
      schemaFilterPattern:
        includes:
          - schema1
      tableFilterPattern:
        includes:
          - table1
processor:
  type: orm-profiler
  config:   
    tableConfig:
      - fullyQualifiedName: table_fqn

        partitionConfig:
          enablePartitioning: true
          partitionColumnName: number
          partitionIntervalType: COLUMN-VALUE
          partitionValues:
            - 1

sink:
  type: metadata-rest
  config: {}
workflowConfig:
  # loggerLevel: DEBUG  # DEBUG, INFO, WARN or ERROR
  openMetadataServerConfig:
    hostPort: _________
    authProvider: ___________

**Comment by ulixius9** [comment]
@tuanla42710 can you please open a thread on https://slack.open-metadata.org/ support channel, this could be just a misconfiguration, we can reopen this ticket if we found a bug
