### ISSUE TITLE
[UI] user email validation forbids admin user to login

### ISSUE THREAD

**Issue by dechoma** [open-metadata/OpenMetadata#16817]
**Affected module**
UI / Backend 

**Describe the bug**
For OM deployed by docker-compose admin user is unable to login due to email validation , admin@openmetadata.org works

**To Reproduce**

![Screenshot 2024-06-27 at 10 04 29](https://github.com/open-metadata/OpenMetadata/assets/29060284/fc3bfb2a-0285-4771-a067-944069446abf)

**Expected behavior**
admin login is aligned with docs https://docs.open-metadata.org/v1.4.x/quick-start/local-docker-deployment#log-in-to-openmetadata

**Version:**
 - Python version:
 - OpenMetadata version: main branch commit 83678b0047c110bfb34d82ad2a2f5f737c30a874
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
`username` login is deprecated and email will be used for login.
Docs will be available for this changes with release. you can use admin@openmetadata.org to login for now
