### ISSUE TITLE
New custom data asset type

### ISSUE THREAD

**Issue by sapirhi** [open-metadata/OpenMetadata#16852]
**Is your feature request related to a problem? Please describe.**
As a big company with many data assets, we have data assets types that to not exists in OMD.
For examples - KPIs, BI events, Profile fields. Each one contain different features from the data assets metadata configuration - it can be owner, description, custom properties with connection to lineage and sample data.  
Currently these assets does not fit any existing data asset in OMD.

**Describe the solution you'd like**
Allow to create a custom data asset in OMD, with adjustable configuration for the required features.

**Comment by Romioyar** [comment]
I support the request as this is becoming one of the critical points coming from users as they would like to easily create simple data assets like systems this data coming from, there should not be complex data models behind, just description, owner, custom icon, custom properties and the most important is possibility to use in lineage.
