### ISSUE TITLE
OpenMetadata.get_profile_data not returning data related to the time frame passed

### ISSUE THREAD

**Issue by giacomochiarella** [open-metadata/OpenMetadata#16859]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
It looks it is impacting python framework 1.4.3.

**Describe the bug**
By executing the following code

```
from metadata.generated.schema.entity.data.table import TableProfile
from metadata.ingestion.ometa.ometa_api import OpenMetadata
metadata = OpenMetadata(server_config)
start_datetime = int((datetime.datetime.utcnow() - datetime.timedelta(days=20)).timestamp() * 1000)
end_datetime = int((datetime.datetime.utcnow() + datetime.timedelta(days=20)).timestamp() * 1000)
counts = metadata.get_profile_data(fqn, start_datetime, end_datetime, 500, None, TableProfile)
```
counts does not contain all the data related to the time frame passed.
I can see al the data from the UI instead. I can also make the request using RESTclient without any issue

**To Reproduce**

```
from metadata.generated.schema.entity.data.table import TableProfile
from metadata.ingestion.ometa.ometa_api import OpenMetadata
metadata = OpenMetadata(server_config)
start_datetime = int((datetime.datetime.utcnow() - datetime.timedelta(days=20)).timestamp() * 1000)
end_datetime = int((datetime.datetime.utcnow() + datetime.timedelta(days=20)).timestamp() * 1000)
counts = metadata.get_profile_data(fqn, start_datetime, end_datetime, 500, None, TableProfile)
```

Screenshots or steps to reproduce

**Expected behavior**
I expect to have all profiler data related to the time frame I provide in the request

**Version:**
 - OpenMetadata version: 1.4.3 deployed using docker
openmetadata-ingestion==1.4.3
openmetadata-ingestion[postgres]==1.4.3
openmetadata-ingestion[dbt]==1.4.3
openmetadata-ingestion[tableau]==1.4.3
openmetadata-ingestion[superset]==1.4.3
openmetadata-ingestion[data-insight]==1.4.3
openmetadata-ingestion[hive]==1.4.3
openmetadata-ingestion[pyhive]==1.4.3

**Comment by ayush-shah** [comment]
Solved, the data is there based on the time frame passed.

ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1719821590353389
