### ISSUE TITLE
Create/Edit(udpate) Glossary field Description*  allow input only spacebar ? 

### ISSUE THREAD

**Issue by halv-123** [open-metadata/OpenMetadata#16853]
**Affected module**
Create new glossary/ Edit glossary 

![create_description_only_spacebar](https://github.com/open-metadata/OpenMetadata/assets/172566674/d57faa01-74b4-423e-aae3-88cc445b287c)

**Describe the bug**
Create new and edit glossary field Description allow input only spacebar 
**To Reproduce**

![allow_input_spacebar](https://github.com/open-metadata/OpenMetadata/assets/172566674/046ec53c-411d-4346-8cf9-6741ad9913a9)

- Click button add glossary
- Fill data in field
- Input field Description only spacebar 
- Save

**Expected behavior**
Trim description field .
- Not allow input only spacebar

**Version:**
  - OpenMetadata version: 1.4.3
 
**Additional context**
i want custom openmetada in localhost . please support build code and test in local ( clip , guide ..... ) 
thank alot.

**Comment by halv-123** [comment]
same issue with field description when i edit glossary and glossary term 
![image](https://github.com/open-metadata/OpenMetadata/assets/172566674/ae929a33-4dbf-400d-b581-c57fdeb21c33)

**Comment by halv-123** [comment]
Is the editing section already included the edit glossary term? @karanh37 
![image](https://github.com/open-metadata/OpenMetadata/assets/172566674/97fcbcbe-ec9f-4db0-9574-e7272d58b6ac)

**Comment by karanh37** [comment]
Hey, this is fixed for both glossary and glossary term.
It will be available in 1.5 release.

**Comment by halv-123** [comment]
@karanh37  Is it possible for me to see which task is assigned to fix this bug?
