### ISSUE TITLE
Team not found error page, when clicked on owner from entity page

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1687]
![image](https://user-images.githubusercontent.com/38649/145631508-899ebc04-19bc-4abf-9060-4c5f80512725.png)
![image](https://user-images.githubusercontent.com/38649/145631535-eb21c0a5-932b-423a-9785-dd4d069e8dc2.png)

**Comment by ShaileshParmar11** [comment]
Assign to me
