### ISSUE TITLE
Usage information is missing from Search/Explore page

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1688]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/38649/145632381-3790548b-c246-4fe1-84cb-4f20344c71e4.png">

previously

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/38649/145632422-bf8054de-5269-4542-8837-26e2451ea3e2.png">

**Comment by Sachin-chaurasiya** [comment]
Fix has been merged #1743
