### ISSUE TITLE
Local Docker error

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1689]
When trying to run `sh /docker/run_local_docker.sh` or running a GitHub action that requires the Docker Compose to start, we get the following error:
```
alembic.util.exc.CommandError: Migration "upgrade 127d2bf2dfa7 -> cc1e65623dc7, add max tries column to task instance" has left an uncommitted transaction opened; transactional_ddl is False so Alembic is not committing transactions
```
This hangs the process indefinitely. You can check the full logs of a GA execution [here](https://pipelines.actions.githubusercontent.com/wm1HbY4Np5KNBqwlQP33bbCanayfhhI6I5lEzqWO3zbYOjLuDL/_apis/pipelines/1/runs/8071/signedlogcontent/2?urlExpires=2021-12-10T19%3A50%3A46.2765917Z&urlSigningMethod=HMACV1&urlSignature=3P366TumGkuEywCigfjk11KPPgBGVs808TKaU7R9lcM%3D)

**Comment by harshach** [comment]
@pmbrull tried running the /docker/run_local_docker.sh from main branch
```
Creating openmetadata_mysql         ... done
Creating openmetadata_elasticsearch ... done
Creating openmetadata_ingestion     ... done
Creating openmetadata_server        ... done
...............✔ OpenMetadata is up and running
```
Are you doing this from main branch or your branch?

**Comment by pmbrull** [comment]
I created the branch a few h ago from main 🤔  I’ll merge main back to it and give it another go.

if it works for you let’s close this. Thanks!

**Comment by pmbrull** [comment]
Thanks for the check. FYI the issue is coming from adding `mlflow` dependency in the setup. I'll review the requirements so that the final status is compatible with the airflow setup. Thanks!
