### ISSUE TITLE
status automatically goes to approved if added by the Admin

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#16905]
**Affected module**
UI. 1.4.3

**Describe the bug**
status automatically goes to approved if added by the Admin

**To Reproduce**

Be admin - create a term. No glossary approval is created and goes auto to Approved

**Expected behavior**
Workflow approval process should always be activated.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@DovileKr did you have reviewers on that gossary term?

**Comment by harshach** [comment]
I am a admin in Sandbox 
<img width="1544" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/38649/385302e9-809f-4b1a-821d-5a1b1d75d954">
as long as reviewer is enabled we won't create a term in approved status
