### ISSUE TITLE
Pydantic converting None strings to non-empty strings

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1692]
All of our entities and requests are getting generated into pydantic based on JsonSchemas.
In case table descriptions we will try to extract from the source and populate the TableEntity
When we don't have any description we set it to None but during the request conversion into Json it 
turns into an non-empy white space "  ".
On backend we check if table description is set by checking if description is null or its empty. Even though we don't have non-empty descriptions this check never kicks as the white space is not empty

**Comment by sureshms** [comment]
Is this still and issue, @harshach ?

**Comment by harshach** [comment]
This is fixed
