### ISSUE TITLE
Tableau metadata ingestion drops TableauDataModel from Data Product assets

### ISSUE THREAD

**Issue by yelianevich** [open-metadata/OpenMetadata#16927]
**Affected module**
It impacts backend.

**Describe the bug**
Tableau metadata re-ingestion drops Dashboard Data Model from Data Products assets. That asset was added manually between initial ingestion and the next run.

**To Reproduce**
1. Ingest a Dashboard Data Model from Tableau using Airflow standard connector.
2. Go to "Data Products" and select one.
3. Go to the "Asset" option and add a Dashboard Data Model ingested on the first step.
4. Run Tableau metadata ingestion using Airflow standard connector again.
5. No asset is longer present in the selected Data Product.
6. In the model 'Versions History' I can see that `dataProducts has been deleted` by `ingestion-bot` and the time correlates with the airflow DAG execution
<img width="290" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/8944946/b19dbf1c-f799-491a-92ca-2aa007e6fbce">

**Expected behavior**
Dashboard Data Model should be present in Data Product assets after reingestion of the Tableau metadata.

**Version:**
 - OS: debian, apache/airflow:2.6.3-python3.11 Docker image
 - Python version: 3.11
 - OpenMetadata version: 1.3.0
 - OpenMetadata Ingestion package version:
 ```
     openmetadata-ingestion[great-expectations,postgres,tableau]==1.3.0
     openmetadata-managed-apis==1.3.0
```

**Comment by OnkarVO7** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/16866
Will be available in 1.5.0
