### ISSUE TITLE
Sandbox doesn't work

### ISSUE THREAD

**Issue by paoliniluis** [open-metadata/OpenMetadata#16939]
**Affected module**
The sandbox demo doesn't work

**Describe the bug**
If you log in via SSO then you can't log in as it says that the entity already exists

**To Reproduce**

Just log in

**Expected behavior**
I wish I could log in

**Version:**
https://sandbox.open-metadata.org/

**Additional context**
NA

**Comment by ayush-shah** [comment]
Hello @paoliniluis we will take a look and get back, Thanks.

**Comment by halv-123** [comment]
@ayush-shah  I want to test finding bugs. Can you grant my user the permissions to create and edit ... ?
user : hahehom@gmail.com
