### ISSUE TITLE
Airflow connectors should run in a DockerOperator

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1698]
It might be interesting to plan to use `DockerOperator` instead of `PythonOperator`s for the ingestion workflows in Airflow in order to achieve greater independence and isolation in the requirements.

With a growing number of connectors and our current approach in the ingestion's Dockerfile, we can easily find dependency clashes (as it happened https://github.com/open-metadata/OpenMetadata/pull/1677, but luckily we could find a slimmer version for the client execution).

This would mean updating how we package the code (setup.py), docs, example pipelines...

WDYT?

**Comment by harshach** [comment]
@pmbrull This makes complete sense. I am +100 on this approach.

**Comment by pmbrull** [comment]
Great thanks, I'll pick it up
