### ISSUE TITLE
execute_migrate_all failed to start 1.4.4

### ISSUE THREAD

**Issue by liujiangxu** [open-metadata/OpenMetadata#17004]
Migrating the OpenMetadata Schema.
Following Migrations will be performed, with Force Migration : false
+---------+----------------+--------------------+
| Version | ConnectionType | MigrationsFilePath |
+---------+----------------+--------------------+
| No Server Migration To be Run                 |
+---------+----------------+--------------------+

[MigrationWorkflow] WorkFlow Started
+---------+----------------+---------------+---------------+----------------+---------+
| Version | Initialization | SchemaChanges | DataMigration | PostDDLScripts | Context |
+---------+----------------+---------------+---------------+----------------+---------+
| Status Unavailable                                                                  |
+---------+----------------+---------------+---------------+----------------+---------+

[MigrationWorkflow] WorkFlow Completed
Update Search Indexes.
+-------------+---------------------+----------+-----------+-----------+------------+------------+--------------+---------------+---------------+----------------+----------------+-------------------+---------------------+---------------------+----------------------+----------------------+-----------------------+-----------------------+-----------------------+------------+------------------+--------------------+
| installedOn | version             | botCount | teamCount | userCount | tableCount | topicCount | mlModelCount | glossaryCount | pipelineCount | dashboardCount | testSuiteCount | glossaryTermCount | mlModelServiceCount | storageServiceCount | databaseServiceCount | pipelineServiceCount | dashboardServiceCount | messagingServiceCount | storageContainerCount | queryCount | searchIndexCount | searchServiceCount |
+-------------+---------------------+----------+-----------+-----------+------------+------------+--------------+---------------+---------------+----------------+----------------+-------------------+---------------------+---------------------+----------------------+----------------------+-----------------------+-----------------------+-----------------------+------------+------------------+--------------------+
| 1.1.0       | 2024-07-11 11:00:20 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | -          | -                | -                  |
| 1.1.1       | 2024-07-11 11:00:20 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | -          | -                | -                  |
| 1.1.2       | 2024-07-11 11:00:20 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | -          | -                | -                  |
| 1.1.5       | 2024-07-11 11:00:23 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | -          | -                | -                  |
| 1.1.6       | 2024-07-11 11:00:23 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | -          | -                | -                  |
| 1.1.7       | 2024-07-11 11:00:23 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | -          | -                | -                  |
| 1.2.0       | 2024-07-11 11:00:25 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | 0                  |
| 1.2.1       | 2024-07-11 11:00:25 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.2.3       | 2024-07-11 11:00:25 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.2.4       | 2024-07-11 11:00:25 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.3.0       | 2024-07-11 11:00:25 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.3.1       | 2024-07-11 11:00:26 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.3.2       | 2024-07-11 11:00:26 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.3.3       | 2024-07-11 11:00:26 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.4.0       | 2024-07-11 11:00:27 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.4.2       | 2024-07-11 11:00:27 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
| 1.4.4       | 2024-07-11 11:00:27 | 0        | 0         | 0         | 0          | 0          | 0            | 0             | 0             | 0              | 0              | 0                 | 0                   | 0                   | 0                    | 0                  | 0                     | 0                     | 0                     | 0          | 0                | -                  |
+-------------+---------------------+----------+-----------+-----------+------------+------------+--------------+---------------+---------------+----------------+----------------+-------------------+---------------------+---------------------+----------------------+----------------------+-----------------------+-----------------------+-----------------------+------------+------------------+--------------------+

Updating services in case of an update on the JSON schema: [db]
Updating bot users in case of an update on the JSON schema: [db]
Updating ingestion pipelines in case of an update on the JSON schema: [db]
Updating workflows in case of an update on the JSON schema: [db]

**Comment by harshach** [comment]
@liujiangxu ask this question in slack before confirming its a bug https://slack.open-metadata.org
