### ISSUE TITLE
Multi User/Team Ownership

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#17012]
## Ownership of Data Assets

In OpenMetadata, we highly recommend using Team based ownership for any data assets. This is coming from our experience of running data teams small and big. Typical platforms provide an option for users to set ownership to multiple users. Employees tend to leave teams or organizations and the most important part of a data asset is the ownership will become stale 

This is one of the important reasons to assign a team based ownership so that the asset ownership is not reflective of a individual(s) rather than a team.

However, many orgs using OpenMetadata felt this is restrictive and requested for multi-owner relationship to Data Assets.

This feature is to enable the multi-user / single-team ownership. In this feature multi-relationship between data asset to users or a single team.

**Comment by TeddyCr** [comment]
As a user, I want to be able to add any combination of users and team as owners:
e.g:
- 2 teams
- 4 users
- 1 team and 2 users
- 3 teams and 7 users
- etc.

**Comment by nqvuong1998** [comment]
Hi @harshach 
Does this new feature support Multi Teams for a dataset?

**Comment by harshach** [comment]
@nqvuong1998 we decided not to enable multiple team ownership for data assets. Ownership requires taking care of the dataassets, addressing any new requirements and answering to the users of such data asset. Multiple teams means there are many owners without clearly making one team a point of contact.
Can you describe the use-case of multiple team ownership?

**Comment by chuqbach** [comment]
Hi @harshach, in our use case, we have data asset which belongs to multiple domains, and our data governance framework is designed to support ownership at team level, not just specific user. So given the case, we need to have multiple teams ownership for one data asset.

**Comment by baohan1999** [comment]
Hello @harshach, 

Our organization has the same issue, in some schemas, one table can have the responsibility from different teams as the data belongs to different domains. And to find exactly the ones who are responsible, finding by user is hard (ownership is based on the domains) and collecting all the users into one team is not possible too as the domains are different. Please help us consider if multiple team owner is possible, thanks!

**Comment by nqvuong1998** [comment]
Hello @harshach , are you considering adding multi-team ownership?
