### ISSUE TITLE
Clicking a pipeline box in the lineage page returns 400

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1703]
### Problem
The user sees error 400 when clicking a pipelines box in the lineage graph.

### Solution
```service``` should be removed from ```fields```.
![image](https://user-images.githubusercontent.com/32617/145693830-98813a51-1fa7-4604-a7c7-932e2e36d7fe.png)

**Comment by ShaileshParmar11** [comment]
Assign to me
