### ISSUE TITLE
Missing elasticsearch component in docker-compose-postgres.yml

### ISSUE THREAD

**Issue by YungChunLu** [open-metadata/OpenMetadata#17040]
**Is some content missing, wrong or not clear?**
In this [page](https://docs.open-metadata.org/v1.4.x/developers/contribute/build-code-and-run-tests/openmetadata-server), the tutorial said that build the elasticsearch component from the given **docker-compose-postgres.yml**, but there is only opensearch instead of elasticsearch defined in that file.

**Describe the solution you'd like**
Should we update the **docker-compose-postgres.yml** to reflect that? If so, I can help create a PR for that

**Additional context**

**Comment by ayush-shah** [comment]
Hello @YungChunLu can you try:
```docker compose -f docker/development/docker-compose-postgres.yml up postgresql opensearch --build -d```

I will modify the docs for the same, Thanks 🙏

**Comment by YungChunLu** [comment]
Sure :)
