### ISSUE TITLE
Solution Design Docs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1706]
Hi @harshach, @sureshms,

After playing with the backend code and with the lessons learnt from your answers, I tried to do a summary of the Solution Design of the API.

The goal of the docs are two-fold:
- Help newcomers have a clear global vision of how the system works
- Help contributors to understand the different pieces at a lower level.

You can find the docs [here](https://docs.open-metadata.org/open-source-community/developer/solution-design)

I would really appreciate your thoughts and feedback here to make sure the content is correct and there are no important points I missed.

Also @shannonbradshaw, please feel free to have a review and let me know what parts I should improve.

Many thanks to all!

**Comment by sureshms** [comment]
Wow, this is super awesome 👏🏼👏🏼👏🏼. Thank you for this 🙏🏼. I was thinking of doing a write up at some point in time. But couldn't have done as good as this. 🤜🤛.

**Comment by harshach** [comment]
@pmbrull as usual awesome work!! from you :). This is going to be immensely helpful for the community and the users. Thank you

**Comment by amiorin** [comment]
@pmbrull Kudos! 👍

**Comment by pmbrull** [comment]
Thank you all for your words 🙏  Really appreciate it, I am happy this could help!

I'll leave this open to leave room for @shannonbradshaw to jump in. Once we are all happy with the content I'll close this.

Thanks again, do not hesitate to ping me if there's anything you'd like to see improved.

**Comment by mithmatt** [comment]
I was reverse engineering  the architecture on my notepad to learn.. Great to have this documented.
Thanks a lot for your effort @pmbrull 

One table we are probably missing is the FieldRelationship - less used, can be documented later.

**Comment by pmbrull** [comment]
I'll close this now. Do not hesitate to open a new issue for further additions or modifications. Thanks!
