### ISSUE TITLE
Move requirements to setup

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1709]
Instead of using both setup.py and requirements, we should unify this. Move the requirements dev & test inside the setup.py and update the make recipes accordingly

**Comment by harshach** [comment]
@pmbrull I think @amiorin is working on it https://github.com/open-metadata/OpenMetadata/pull/1588 . Can you review the pr and give any feedback you may have

**Comment by amiorin** [comment]
I'm working on it.

**Comment by pmbrull** [comment]
Sorry @amiorin, missed https://github.com/open-metadata/OpenMetadata/issues/1344. Thanks!!
