### ISSUE TITLE
0.7 UI feedback

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1710]
- [x] 1. Alignment issue. It might be better to align the text Owner with the name above BigQuery. Also the first tag with the text owner.
![Pasted Graphic 5](https://user-images.githubusercontent.com/1417689/145724688-680ac64d-b9e5-47b0-97d3-1a51cedd8dcc.png)

- [ ] #1745
![bigquery_gcp » shopify » dim_product](https://user-images.githubusercontent.com/1417689/145724700-2bf43770-a4fc-403b-98be-19e761528165.png)

- [x] 3. Inconsistent styles for summary:
![Pasted Graphic 7](https://user-images.githubusercontent.com/1417689/145724711-175de64a-917e-45b1-bcff-6fc947165ced.png)
![Sachin Chaurasiya](https://user-images.githubusercontent.com/1417689/145724719-2220a1e1-812b-4f3d-bbcf-9efa814a367f.png)

Suggestion, maybe change to: 
Owner name | Tier or No Tier | Medium usage - 55th percentile | 130 queries past week | — columns | — rows

- [x] 4. Tabs in explore page don't seem aligned to anything:
![Pasted Graphic 9](https://user-images.githubusercontent.com/1417689/145724772-7b7ce0d9-7e25-4de3-bbd4-0ad8b2c46975.png)

- [x] 5. Too many icons: We can remove table icon in the result set. Also remove other icons in the result set
![Pasted Graphic 10](https://user-images.githubusercontent.com/1417689/145724789-01c45fc7-a668-4e3a-946d-643998ff5364.png)

- [x] 6. Are there any difference in font weight and choice of grey between these two side panels? If so, can we make them consistent. First one appears to be more readable than the second:
![Service](https://user-images.githubusercontent.com/1417689/145724821-2867dce5-6bae-4aa8-a16e-e0fade1357fa.png)
![Pipelines](https://user-images.githubusercontent.com/1417689/145724831-07c0dea6-e403-47dd-99a2-736683cb7636.png)

- [x] 7. Can we make the font color for BigQuery and the number same? The contrast for number appears to be not that great.
![Pasted Graphic 15](https://user-images.githubusercontent.com/1417689/145724845-f102aed1-ebf6-4614-8a3e-6d0e622dd58c.png)

- [x] 8. The data I am following is not shown in the front page. Here, I am following some datasets, but this is what I see:
![My Data](https://user-images.githubusercontent.com/1417689/145724884-ed316f4a-ed8c-4309-9f00-5aca3347abd2.png)

- [x] 9. Activity filtering by MyData and Following Data does not work.
- [x] 10. Change `Following Data` to `Following` in the activity filter
- [x] 11. User menu has inconsistent fonts and weird layout:
![Signed in as](https://user-images.githubusercontent.com/1417689/145724945-6012fed4-d512-418d-9349-132debd127a7.png)

Do we need a down arrow next to the user icon?
![Pasted Graphic 17](https://user-images.githubusercontent.com/1417689/145724961-4ea34b43-843c-4682-9639-0360dfb26be0.png)

- [x] 12. Can we remove "Hi username!" from this screen, as serves no purpose:
![Hi, suresh!](https://user-images.githubusercontent.com/1417689/145724975-51d2ed1a-2331-46ee-8b12-b1ac0a95ac77.png)

- [x] 13. Can we remove the light purple background here?
![Critical Source of Truth business data assets of an organization](https://user-images.githubusercontent.com/1417689/145724995-6a91a3fb-7f06-4a4a-96b4-49813c334e87.png)

- [x] 14. Can we move the service name and database name to the topline as done table details page here:
![Pasted Graphic 20](https://user-images.githubusercontent.com/1417689/145725019-b0cf9aac-75c7-4dfc-98a0-1e7e3b4d59ea.png)

- [x] 15. Change `Please` to `please and add a period at the end:
![Pasted Graphic 21](https://user-images.githubusercontent.com/1417689/145725037-df49a604-a712-4c80-a888-e1cae069b88b.png)
![Pasted Graphic 22](https://user-images.githubusercontent.com/1417689/145725042-e374fb76-4b2e-4fef-9d51-3c7d90587d9e.png)

- [x] 16. In table details page and for other assets, we can remove the section header Description:
![Pasted Graphic 23](https://user-images.githubusercontent.com/1417689/145725066-ed03927f-6757-4283-be27-3d290708b931.png)

- [x] 17. Different inconsistent ways to show Tags:
![#User Name](https://user-images.githubusercontent.com/1417689/145725089-6781be7f-4145-4469-a2f1-054ccaf0dd67.png)
![#PersonalData Personal](https://user-images.githubusercontent.com/1417689/145725094-a013d7a0-6a27-488c-9591-0a0409b6f2a2.png)
![Pasted Graphic 24](https://user-images.githubusercontent.com/1417689/145725100-bf2b05b3-7eca-41ac-9420-693cf3efc545.png)

- [x] 18. Make column headers bold like Frequently Joined:
![Pasted Graphic 25](https://user-images.githubusercontent.com/1417689/145725132-168cfa21-cb17-48ce-b25d-0e8fec85255e.png)

- [x] 19. Loose white and grey in sample data and also make the header bold:
![Pasted Graphic 26](https://user-images.githubusercontent.com/1417689/145725142-07086469-5714-45fa-8b42-96ff57d81d17.png)

- [x] 20. Follower list looks faded out:
![Unfollow](https://user-images.githubusercontent.com/1417689/145725152-a85b38b8-af93-4552-b945-c1562e97b5d2.png)

- [ ] #1744
![Pasted Graphic 28](https://user-images.githubusercontent.com/1417689/145725162-4d2c49ae-6bba-45d0-be28-8d9764511629.png)
![Pasted Graphic 30](https://user-images.githubusercontent.com/1417689/145725169-49ece3f3-1cd1-441a-897d-8471318ebe4d.png)

- [x] #1722
![alberto miorin updated dim product 0122 PM](https://user-images.githubusercontent.com/1417689/145725182-f2605a4f-8a43-4e87-a30d-bb422bc62bdd.png)

- [x] 23. Some buttons don't have good contrast (example Schema button here):
![Sample Data](https://user-images.githubusercontent.com/1417689/145725222-52a4405a-ba73-4c02-b8a1-6b36875c894b.png)
Maybe use the following style:
![Pasted Graphic 33](https://user-images.githubusercontent.com/1417689/145725233-1669427b-e2df-470e-ae75-f3a21ec579a2.png)

- [x] 24. Three different styles to show entity hierarchy:
![shopifyfact_sale 40](https://user-images.githubusercontent.com/1417689/145725248-9e44c75b-71bd-4d97-949d-0568aa1d8b8a.png)
![bigquery_gcp » shopify » dim_product](https://user-images.githubusercontent.com/1417689/145725254-8b63b79d-e5cb-4027-9018-d90794bb167c.png)
![bigquery_gcp shopify](https://user-images.githubusercontent.com/1417689/145725263-aa992e00-64d4-4aac-a192-221c739df5da.png)

- [x] 25. The recently searched terms section doesn’t look right
![Recently Searched Terms](https://user-images.githubusercontent.com/1417689/145725273-c45a53d1-3f61-4fb5-ae3c-11d27398cf87.png)

- [x] 26. Only exact match is allowed for advanced search?
![column_namesclient](https://user-images.githubusercontent.com/1417689/145725292-64115ff8-c31e-4dba-a9e1-f9379df5d65d.png)

**Comment by harshach** [comment]
@sureshms any attribute search is exact match such column_names
one can do a free-form search that can match client_id

**Comment by harshach** [comment]
@Sachin-chaurasiya @darth-coder00 latest explore page, tabs are wrapping around
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/145895017-5dd22a2b-12c6-483f-88e3-fa23ac3b19c8.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/145895062-f6920fbe-fc1d-4dae-9a3e-e65ff57b178f.png">

**Comment by Sachin-chaurasiya** [comment]
Closing this issue as 24 tasks have been completed. created a separate issue for the remaining 2 tasks.
