### ISSUE TITLE
Cannot connect to https://docker.getcollate.io/v2/ when trying quickstart

### ISSUE THREAD

**Issue by maximillianus** [open-metadata/OpenMetadata#17114]
**Affected module**
backend

**Describe the bug**

Cannot connect to https://docker.getcollate.io/v2/ when trying quickstart

This is the exact error message `Error response from daemon: Get "https://docker.getcollate.io/v2/": dialing docker.getcollate.io:443 with direct connection: connecting to 0.0.0.0:443: dial tcp 0.0.0.0:443: connect: connection refused`

**To Reproduce**

Simply run `docker compose -f docker-compose.yml up --detach` in this link https://docs.open-metadata.org/v1.4.x/quick-start/local-docker-deployment

**Expected behavior**
`docker compose` runs all containers smoothly

**Version:**
 - OS: [e.g. iOS] MacOS Sonoma 14.5
 - Python version: 3.12
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by maximillianus** [comment]
Sorry this could be my DNS issue as I tried in another network and it can download fine..

**Comment by akash-jain-10** [comment]
Thanks! @maximillianus . I'll close this ticket for now! Feel free to open a new one if it persists across networks!
