### ISSUE TITLE
"Please enable the data profiler by following the documentation" - link broken

### ISSUE THREAD

**Issue by jprantza** [open-metadata/OpenMetadata#17120]
**Affected module**
This affects the UI

**Describe the bug**
When you don't have the profiler enabled and you click on the "Profiler & Data Quality" tab, you will get the following message:

"Data Profiler is an optional configuration in Ingestion. Please enable the data profiler by following the documentation"

... followed by a link to the documentation which is incorrect. 

The link points to:
https://docs.open-metadata.org/connectors/ingestion/workflows/profiler

When it should be pointing to here instead:
https://docs.open-metadata.org/v1.4.x/how-to-guides/data-quality-observability/profiler

Because the profiler documentation was moved to the how to section in release 1.4

**To Reproduce**
Assuming you haven't enabled the profiler, click on any table, and then click on the "Profiler & Data Quality" tab for that table. You will see a message like the following:

![image](https://github.com/user-attachments/assets/ef26173b-b230-4158-acef-6be4830cbe62)

Then click on the "here" link in that message and you will get a "Page not found :(" message.

**Expected behavior**
You should see the profiler documentation, and not get a "Page not found :(" message.

**Version:**
 - OS: Windows
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: 1.4.1

**Comment by Prajwal214** [comment]
Looking into it

**Comment by ulixius9** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/17140
