### ISSUE TITLE
Get service_name based on connection's host& port - API

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#1713]
We currently support searching of entities using fqn.

**Comment by harshach** [comment]
As we are collecting lineage information from dashboards, pipelines etc.. its needs to create lineage connections to tables. From these services we get database.table_name this makes it hard to query by FQN as we need service_name. The only option currently is to ask the user to configure a database_service_name this will not work if the dashboard tool is querying multiple services and databases. 
Dashboard service can provide us with connection info of underlying database its using, we can use the host:port information to query the backend to get the service entity reference and use that to form the FQN
