### ISSUE TITLE
Schema description by a human user reported again and again as made by ingestion-bot

### ISSUE THREAD

**Issue by teabbs** [open-metadata/OpenMetadata#17130]
Hello!

**Affected module**
Probably ingestion or OMeta API.

**Describe the bug**
When a schema is created via a metadata ingestion and then edited by a human user having a description added, this change is reported in notifications each time the metadata ingestion runs, but as if description has been added by ingestion-bot.

- When the description is first added, it's reported correctly at once as made by the user.
- Later every time it's reported as **Added** by ingestion bot.
- If the user deletes (clears) this description, it's reported at once as **Added** empty by the user.
- Next time the ingestion job runs, it's reported as **Deleted** byt the ingestion-bot.
- Later it's not reported in any way.

Version history of the entity is correct - the description is stated as added once and deleted both times by the user. Checked both on a schema with tables and an empty one. We have a notification for all changes in all entities to email. We use Oracle as the database source. OpenMetadata is version 1.4.2 both the application and the ingestion/apis packages.

**To Reproduce**

1. Create a notification to email for all changes in all entity types.
2. Run a metadata ingestion that would create a schema.
3. Log in as a human user and add description manually, - you get a notification of added description by the user.
4. Run the ingestion several times, - you should get a notification of a change by ingestion-bot each time.
5. Delete the description manually, - you get a notification as added empty description.
6. Run the ingestion, - you should get a notification as deleted by ingestion-bot only once.

**Expected behavior**
After adding the description, notification only comes once as added by the user, and not by the bot.
After clearing the description, notification only comes once as deleted by the user, and not by the bot.

**Version:**
 - OS: Oracle Linux 8
 - Python version: 3.9
 - OpenMetadata version: 1.4.2
 - OpenMetadata Ingestion package version: 1.4.2.0

**Additional context**
Airflow 2.6.3
'Bare metal' type of installation. Source is Oracle database.

**Comment by mohityadav766** [comment]
hi @teabbs , this has been fixed here https://github.com/open-metadata/OpenMetadata/pull/17087
