### ISSUE TITLE
Proposing LONGTEXT as an Alternative to JSON Type in MySQL for Versions Prior to 8.0.30 to Address Memory Leak Issues

### ISSUE THREAD

**Issue by dntjr8096** [open-metadata/OpenMetadata#17160]
**Is your feature request related to a problem? Please describe.**
There's a known memory leak issue with using the JSON type in MySQL schemas for versions below 8.0.30, as detailed in MySQL Bug #105861. This significantly impacts performance and reliability.

**Describe the solution you'd like**
I propose using LONGTEXT as an alternative to the JSON data type for affected MySQL versions. This change would help avoid the memory leak issues while still allowing for the storage of large text data, which can be manually parsed as JSON.

**Describe alternatives you've considered**
 Explicitly recommend in the documentation the use of MySQL version 8.0.30 or higher to circumvent the memory leak issue associated with earlier versions.

**Additional context**

**Related issues**
- https://bugs.mysql.com/bug.php?id=105861

**Comment by harshach** [comment]
We depend on mysql json functions in many possible. We are not going to support older versions.
