### ISSUE TITLE
Automatic data lineage based on redshift stored procedure

### ISSUE THREAD

**Issue by sound118** [open-metadata/OpenMetadata#17178]
For the latest version of OpenMetaData, can you automatically get the table/column lineage based redshift stored procedure?

**Comment by thisisvk45** [comment]
No, I dont think OpenMetadata currently supports automatic table/column lineage for Redshift stored procedures. It supports automatic lineage for Redshift views but not for stored procedures.

**Comment by pmbrull** [comment]
this is supported. If somethins is not working please share a reproducible example. Thanks!

**Comment by sound118** [comment]
> this is supported. If somethins is not working please share a reproducible example. Thanks!

Is this supported by querying redshift query history system log table to extract sql statements from stored procedures? Then with sql-lineage package, it will parse those extracted sql statements to figure out the source and target destination of tables/columns?
