### ISSUE TITLE
Support Special Characters in Databricks Column Names

### ISSUE THREAD

**Issue by ajsquared** [open-metadata/OpenMetadata#17201]
**Affected module**
Ingestion Framework

**Describe the bug**
OpenMetadata fails to ingest Databricks tables (using the Unity Catalog connector) with special characters in the name.

**To Reproduce**
Create a Databricks table with a column named `"foo:@bar"`, and attempt to ingest it.

**Expected behavior**
OpenMetadata should successfully ingest this table.

**Version:**
 - OS: [e.g. iOS] Linux
 - Python version: 3.10
 - OpenMetadata version: [e.g. 0.8] 1.4.3
 - OpenMetadata Ingestion package version: 1.4.3.2

**Comment by akashverma0786** [comment]
Hi @ajsquared,
I tried reproducing the issue, but I was able to successfully ingest the table with column name "foo:@bar"

USING DATABRICKS CONNECTOR:- 
![Screenshot 2024-11-15 at 1 04 45 PM](https://github.com/user-attachments/assets/f417b50a-2cb7-4fe1-b7d7-2dbbd4c35ce2)


USING UNITY CATALOG CONNECTOR :- 
![Screenshot 2024-11-15 at 1 05 00 PM](https://github.com/user-attachments/assets/0897b123-de56-4e65-b33a-420629159aa4)


SOLUTION :- 
Please upgrade to the latest release and try it out once again. Thanks.

**Comment by ayush-shah** [comment]
Closing this until the user tries with latest version, in case it is reproduced, we can reopen this issue, Thanks.
