### ISSUE TITLE
Cannot grant user permissions to create Business Terms without also allowing them to create a Business Glossary.

### ISSUE THREAD

**Issue by Tranduytien178** [open-metadata/OpenMetadata#17214]
I assigned a role with the policies shown in the image below. On the user screen, after being assigned the role, the button to create a business term does not appear like the image below.
![image](https://github.com/user-attachments/assets/b036d981-9224-4d7f-81ab-cc4d088a0fc0)
![Image 26-07-2024 at 18 04 2](https://github.com/user-attachments/assets/117e38a8-92ab-464b-aad3-c1c8b2a55a6d)
![Image 26-07-2024 at 18 04](https://github.com/user-attachments/assets/4a18f769-758e-4fc0-8062-4a68d8363c0d)
![Image 26-07-2024 at 18 02](https://github.com/user-attachments/assets/1d8dbe54-cae6-418c-b63f-9365cec6b777)

**Comment by karanh37** [comment]
Hi @Tranduytien178 , this is already fixed with https://github.com/open-metadata/OpenMetadata/issues/16458
It will be available in 1.5 release.
