### ISSUE TITLE
Tables are unlinked from dataProducts when updating

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#17249]
**Affected module**
backend

**Describe the bug**
If the table linked to dataProduct is updated and the "dataProducts" attribute is not sent, then this attribute is cleared for the table.
At the same time, the relationship between the table and the dataProduct is preserved and can be viewed from the dataProduct.

**To Reproduce**
![dataProduct_problem](https://github.com/user-attachments/assets/b5cf0b3c-b4c2-4144-ae18-35433c127425)

1) Сhecked the dataProduct link on the table page
2) Checked the presence of a filled "dataProducts" attribute for the table via a get request
3) Updated the table via a put request
4) Checked that the dataProduct link is not displayed on the table page
5) Checked that the link to the table is displayed on the dataProduct page 
6) Checked that the table's relationship with the dataProduct is not displayed via the table's get request

**Expected behavior**
The "dataProducts" attribute of the table should not be cleared when updating the table. 
This should work for other types of objects (dashboards, etc.)

**Version:**
 - OpenMetadata version: 1.4.5

**Comment by harshach** [comment]
@AlekseevVadim you are doing a PUT operation. If you are doing PUT you cannot have partial document updating it, if you do then yes you'll see relations missing like you are showing
if you want to do partial updates to the document, use PATCH

<img width="609" alt="image" src="https://github.com/user-attachments/assets/3552a968-5298-4ded-808a-1f6939ccc694">
