### ISSUE TITLE
Airflow lineage ingestion inadvertently sets incorrect column-level lineage

### ISSUE THREAD

**Issue by ajsquared** [open-metadata/OpenMetadata#17253]
**Affected module**
Ingestion Framework

**Describe the bug**
I have been seen errors like this in an Airflow pipeline ingestion:
```
Failed to ingest table [id: 1c7c1416-6aba-4680-82bc-2b399cc318a2] due to api request failure: Invalid fully qualified column name Service Name.catalog.schema.table.column
```

`Service Name.catalog.schema.table.column` does actually exist.

In investigating this error, I found that the `add_lineage` method modifies the `lineageDetails` field  on an `AddLineageRequest`: https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py#L127

The lineage handling for Airflow uses the same `LineageDetails` object for every `AddLineageRequest`: https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py#L545

This incorrectly leaks column-level lineage details across different requests.

**To Reproduce**
* Ingest tables into OpenMetadata with column-level lineage, such as from the Databricks Unity Catalog
* Ingest an Airflow pipeline that covers the same tables as above, in addition to other tables

**Expected behavior**
The Airflow pipeline ingestion should succeed, and not attempt to add incorrect column-level lineage

**Version:**
 - OS: [e.g. iOS] Linux
 - Python version: 3.10
 - OpenMetadata version: [e.g. 0.8] 1.4.3
 - OpenMetadata Ingestion package version: 1.4.3.2

**Comment by harshach** [comment]
@ulixius9 can you take a look at this.

**Comment by ulixius9** [comment]
I believe this pr should fix this error as well https://github.com/open-metadata/OpenMetadata/pull/17264 hence closing it for now, if this is reproducible after 1.5 we can reopen this ticket
