### ISSUE TITLE
Older comments disappear after adding multiple comment

### ISSUE THREAD

**Issue by chuqbach** [open-metadata/OpenMetadata#17258]
**Affected module**
It impact the UI of OpenMetadata

**Describe the bug**
Older comments disappear after adding multiple comment. There is no scroller to scroll up or down the conversation

**To Reproduce**
Start a new conversation for any topic. Reply to a same conversation for more than 3 times 

Screenshots or steps to reproduce
A conversation start with a comment of "asdf"
![image](https://github.com/user-attachments/assets/984079d0-a250-4b1a-a485-1f51d71024f9)

Adding another comment "123" leading to the "asdf" comment disappears
![image](https://github.com/user-attachments/assets/5bac2eae-d271-46a5-9aeb-d5e25831b881)

Delete of "123" makes the "asdf" comment appears again
![image](https://github.com/user-attachments/assets/d0511eaa-47cd-4ecf-b662-39276d78bf2e)

**Expected behavior**
A scroller should be available to scroll on historical comment

**Version:**
- OpenMetadata version: 1.4.4
- OpenMetadata Ingestion package version: 1.4.4.2

**Comment by nqvuong1998** [comment]
cc @harshach @ayush-shah

**Comment by harshach** [comment]
@nqvuong1998 thanks for sharing. @sonika-shah lets take a look

**Comment by halv-123** [comment]
@chuqbach  so many con vo luôn :)))

**Comment by harshach** [comment]
@chuqbach we are unable to reprodce this in latest release 
<img width="655" alt="image" src="https://github.com/user-attachments/assets/02114187-0698-47f1-80b8-f7b16b5cc996">
if you can reproduce on sandbox.open-metadata.org, re-open the issue.

**Comment by baohan1999** [comment]
Hello @harshach, 

I have the same issue with @chuqbach. 
I think you are on a different view with the view that @chuqbach has this issue on. I tried with your view when creating the conversation and replying in the same thread, it worked as expected that all the replies showed correctly. However, when I closed this tab, then went to 'Activity Feeds & Tasks' tab and opened the conversation that I just created, only 3 replies showed up. You can see the picture below for more details. 
![image](https://github.com/user-attachments/assets/6366d343-2f2b-48ba-b4b8-71bd5922b83d)

Please help us reproduce again and fix it. 
Thanks!

**Comment by chuqbach** [comment]
Hi @harshach, the issue still remains, but it seems like I don't have the permission to reopen it. Please check it again.
