### ISSUE TITLE
Activity feed bugs and improvements

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#17278]
- [x] ~Parse Test Case changes to show case what exactly is updated instead of json payload, in the below image TestCase changes we are not getting any info to  parse and show neatly in the UI~
Note : Not doing this, since we have removed this from Feed generation.
![image (12)](https://github.com/user-attachments/assets/8a05ed18-c295-45fb-a89d-95fe2ee162e9)

- [x]  ~It looks like activity feed is repeating for a failed test case result? the asset link at the top taking it.~
Note : Not doing this, since we have removed this from Feed generation.
![image](https://github.com/user-attachments/assets/db9d1026-80fe-4603-881c-ff07602d72a9)

- [x] ~The test case feed shows the wrong incident data. For the graph to show the correct incident, we need the task data for the respective test case, which is currently not in the feed info object.~
Note : We will not be doing this since we have removed the Test Case result from the Feed

**Actual Data:**
![image (1)](https://github.com/user-attachments/assets/e94f3aae-44d0-4d64-bcf9-6a6d4a4b34c8)

**Feed Data:**
![image](https://github.com/user-attachments/assets/0231b06e-03c8-44b4-a5b3-65225df4a544)

- [ ]  For any kind of column update in the entity we don't have info about the column in the Feed data. It's hard to state the changes belong to table or column.
![image](https://github.com/user-attachments/assets/a569b041-b254-4e4e-9d58-a71e1ffc0706)
![image](https://github.com/user-attachments/assets/967d0664-ba63-4c1a-8c3e-075460b325d3)

- [ ] When we update a glossary in the entity we are getting cardStyle as 'Tags', which we are displaying in the UI Feed which create a miss conception for the user about the change. so the cardStyle for tags update in entities should come like : 
1. `Tags` : Only for Tags update
2. `GlossaryTags`: Only for Glossary update
3. `TagsAndGlossary`: For both the Tags and Glossary update in the feed.

- [ ] Will not show feed for the below change event

1.  Need to remove the Feed when a Persona is Updated
2. Reviewers, Reference, Synonyms, related terms from glossary.

- [ ] Old feed component in the conversation panel on entity page and alignment issue
![image](https://github.com/user-attachments/assets/20d6613a-b74e-4523-952c-4b6ab03f46ee)
![image](https://github.com/user-attachments/assets/b93fbdb0-2635-4e4b-b2ec-fbaf2870ab04)

- [x] After accepting the term it flickers please check the video

https://github.com/user-attachments/assets/be0316b9-6dd8-4e42-b231-5e719257a875

**Comment by aniketkatkar97** [comment]
- [ ] Remove the graph for the test case feed. Just display the test case status and test suite summary
![image](https://github.com/user-attachments/assets/ee177fb1-7503-4db2-a2a9-e0ecc9bf2d0b)

**Comment by ShaileshParmar11** [comment]
- [ ] All feeds is visible for a second after clicking on the task tab,

https://github.com/user-attachments/assets/cb4c90bc-773c-41a0-84fd-ff40a7ba6367
