### ISSUE TITLE
"Schema Definition" does not show correctly 

### ISSUE THREAD

**Issue by baohan1999** [open-metadata/OpenMetadata#17287]
**Affected module**
It impacts Openmetadata UI
**Describe the bug**
In the single pane view of table data asset, the schema definition tab shows correctly the DDL script, however when clicking another tab and back to schema definition tab, the DDL script is shown not correctly anymore. Please see the picture below for more information.

**To Reproduce**
This is when clicking another tab and back to schema definition tab. 
![image (38)](https://github.com/user-attachments/assets/673ffc62-607b-4058-8cd1-a4775b282f03)

**Expected behavior**
I expect the DDL will be shown the same, in a correct way in any cases of change.

**Version:**
OpenMetadata version: 1.4.4
OpenMetadata Ingestion package version: 1.4.4.2

**Comment by baohan1999** [comment]
cc @harshach @ayush-shah

**Comment by KsM00000** [comment]
The same problem with procedure's code (example from sandbox).
![image](https://github.com/user-attachments/assets/b8a2bdc9-e93f-4db9-af75-ec6e7134740c)

**Comment by baohan1999** [comment]
Hello @harshach, can you please help us check this issue and maybe estimate when it can be fixed? Thanks a lot for your support as always!

**Comment by harshach** [comment]
fixed in latest release 
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/2dc6f57e-24a8-415b-b18f-245ffe6b8eb0" />
