### ISSUE TITLE
Connector Trino 

### ISSUE THREAD

**Issue by cdquintas** [open-metadata/OpenMetadata#1729]
it doesn't work like that, with "username":
{
  "source": {
    "type": "trino",
    "config": {
      "service_name": "trino_local",
      "username": "test",
      "host_port": "localhost:8080",
      "catalog": "mysql",
      "schema_name": "teste"
    }
  },

error:
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='testlocalhost', port=8080): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb96ebf730>: Failed to establish a new connection: [Errno -2] Name or service not known'))

the problem is in the connection string " host='testlocalhost' " is missing the @ between user and host.

in the following way it works:
{
  "source": {
    "type": "trino",
    "config": {
      "service_name": "trino_local",
      "host_port": "test@localhost:8080",
      "catalog": "mysql",
      "schema_name": "teste"
    }
  }, 

i put the user in the "host_port" with the "@"

**Comment by amiorin** [comment]
Let me try to reproduce it.

**Comment by amiorin** [comment]
I could reproduce the bug on my computer. It has been fixed in main. Your workaround works. May I ask you to wait for the next release? In two days we will release ```0.7.0``` with a new ```openmetadata-ingestion``` Python package that includes the fix.

**Comment by amiorin** [comment]
I have checked again @ayush-shah and it is broken in ```main``` branch too. I'll fix it and @ayush-shah will publish a new version in Pip in the next hours.

**Comment by cdquintas** [comment]
great support, thank you very much
