### ISSUE TITLE
DBT model description is not correctly parsed

### ISSUE THREAD

**Issue by aballiet** [open-metadata/OpenMetadata#17333]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Ingestion Framework

**Describe the bug**

DBT model description can mismatch the value from YAML, being "shifted" from another column.

See video of the bug: https://www.loom.com/share/86da7cdf491e491c95ac6893b0e21063?sid=9ec1ca14-b5f6-421b-a53c-8b263e3cbffa

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sushi30** [comment]
Thanks for raising the issue. Does this happen with any dbt ingestion or only with this one specifically? Can you share source dbt files which reproduce the issue?

**Comment by aballiet** [comment]
OKOK in fact I did not see the param `dbtUpdateDescriptions`, IMO should be `True` by defaults as it is the expected behavior when ingesting dbt I would say 👍 @sushi30
