### ISSUE TITLE
Option to disable column profiler globally

### ISSUE THREAD

**Issue by sushi30** [open-metadata/OpenMetadata#17339]
**Is your feature request related to a problem? Please describe.**
When I have a significant volume of data assets, I would like to consider disabling the column profiler for a given profiler run so that I can at very least collect the table profiles in a timely manner. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
The current alternative is excluding for each table separately. This is not scalable because:
1. It requires defining for each table.
2. It requires monitoring schema changes to add new columns to the exclusion list.

**Additional context**

From a slack conversion:

> Considering we have thousands of tables, we would like to disable all column profiling once for all. Even if we implement a script using the API, the columns list might be out-of-date very often.
Is there any workaround you suggest to disable column profiling while we wait for the improvement you mentioned?

**Comment by pmbrull** [comment]
delivered 1.6

![image](https://github.com/user-attachments/assets/076fc38e-4a55-4bb5-9df7-82aa695ad6c7)
