### ISSUE TITLE
[UI] cannot remove tag suggestion

### ISSUE THREAD

**Issue by baohan1999** [open-metadata/OpenMetadata#17342]
**Affected module**
It impacts Openmetadata UI

**Describe the bug**
When someone create a task to suggest tag for a specific data object, the assignee of the task cannot remove the suggested tag/ add a new tag. Please see the steps below for this bug.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
- Users suggested classification tag for data
- Assignee choose "Edit & Accept Suggestion", and:
- Do not agree with suggestion -> does not allow to remove the suggestion (suggestion still visible in UI)
![image (39)](https://github.com/user-attachments/assets/aba9e143-57ba-470b-a846-ab117621474c)
- Do not agree with suggestion -> does not allow to remove the suggestion, choose the new classification under same category (like personal data classification as example) -> cannot proceed
![image (40)](https://github.com/user-attachments/assets/90bc4b3b-8cb3-4df4-a2a9-168447baf0da)
- Do not agree with suggestion -> does not allow to remove the suggestion, add new classification under different category -> have to keep the suggestion in order to proceed 
![image (41)](https://github.com/user-attachments/assets/97bb29aa-0d86-4f83-91b6-776f5380f1eb)

**Version:**
OpenMetadata version: 1.4.4
OpenMetadata Ingestion package version: 1.4.4.2

**Comment by baohan1999** [comment]
cc @harshach @ayush-shah

**Comment by Ashish8689** [comment]
@baohan1999 this issue has already been fixed with this PR https://github.com/open-metadata/OpenMetadata/pull/17107 and will be a part of `1.5.0 release`
