### ISSUE TITLE
[BUG] Ingestion: Pyodbc doesn't support couple of datatypes in AzureSQL

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#17377]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
INGESTION

**Describe the bug**
Pyodbc doesn't support datatypes like HIERARCHYID and GEOGRAPHY.
If we try to compute over it, it throws:
pyodbc.ProgrammingError: ('ODBC SQL type -151 is not yet supported.  column-index=x  type=-151', 'HY106')

**To Reproduce**
Create a table with HIERARCHYID and GEOGRAPHY, run ingestion & profiler over it.

**Expected behavior**
It shouldn't fail

**Version:**
 - OS: [e.g. iOS] MacOs
 - Python version: >=3.8
 - OpenMetadata version: [e.g. 0.8] 1.4.x

**Additional context**

**Comment by harshach** [comment]
@ayush-shah are we targeting for 1.5.0

**Comment by ayush-shah** [comment]
Yes @harshach we have a #17378 PR, fixing pytests on the same.
