### ISSUE TITLE
Refactor lineage RBAC rules so lineage information can be edited only by asset owners

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/OpenMetadata#17406]
**Is your feature request related to a problem? Please describe.**
 
I would like regular users to be able to edit lineage information only for assets they are owners of. Consider user A (owner of schema X and hence all tables within this schema), I would like to create policy:

- resources: all, permission: EditLineage, condition: IsOwner()

that would enable this user to only edit lineage information when tables of schema X are downstream (toEntity) in lineage request.

**Describe the solution you'd like**
A change in way ownership information is used in LineageResourceContext.

**Describe alternatives you've considered**

**Additional context**
This requirement would greatly improve self-service aspect of OpenMetadata.

**Comment by harshach** [comment]
we will track it here https://github.com/open-metadata/OpenMetadata/issues/18099
