### ISSUE TITLE
[DBT] Manifest is not parsed correctly on dbt Cloud using "versionless"

### ISSUE THREAD

**Issue by aballiet** [open-metadata/OpenMetadata#17403]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

Library: https://github.com/yu-iskw/dbt-artifacts-parser forbid extra items with current settings

<img width="1211" alt="Capture d’écran 2024-08-12 à 12 56 44" src="https://github.com/user-attachments/assets/44be8b3e-6d4d-465c-bf73-4fd0c462f1ae">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by aballiet** [comment]
Dbt cloud reverted their change it seems. Dbt manifest parser is now working correctly

**Comment by OnkarVO7** [comment]
Re-opening this issue as the error seems to be reproduced again
We'll take a look into applying a workaround mentioned [here](https://github.com/yu-iskw/dbt-artifacts-parser/issues/103#issuecomment-2305565904) and see if that fixes it
