### ISSUE TITLE
UI Bug on Database Level when applied Restricted View on Rules & Policies

### ISSUE THREAD

**Issue by nypnop** [open-metadata/OpenMetadata#17448]
**Affected module**
UI affected, specifically on Database Level page

**Describe the bug**
Compared to the Database Schema, Tables, and Database Service pages, when the Database level page is restricted, it doesn't display a "You don't have access" message. Instead, it shows an infinite loading screen.

**To Reproduce**

Apply rules and policies that prevent users from viewing any data assets that do not belong to them (i.e., where they are not the owner).
![screenshot_2024-08-14_at_14 49 11](https://github.com/user-attachments/assets/e5ed9b56-ba11-46c2-9491-d72b37494c61)

Then try to open the Database Level data asset. It'll show an infinite loading screen, like this.
![screenshot_2024-08-14_at_14 32 02](https://github.com/user-attachments/assets/a1d4e48f-8db3-444c-837a-e59bb2c77cd8)

To be compared, here the screenshot when I'am open other level of data asset.
![screenshot_2024-08-14_at_14 31 25](https://github.com/user-attachments/assets/9c93d4a4-71a6-414d-8e09-7d0f8034a0b6)

**Expected behavior**
The expected, is just like the other, when I'am open the Database Level data asset, it will show an "You don't have access" message

**Version:**
 - OS: macOS 14.0
 - Python version: ?? using the omd dependencies for the airflow
 - OpenMetadata version: 1.4.4
 - OpenMetadata Ingestion package version: 1.4.4 following the omd version

**Additional context**
https://openmetadata.slack.com/archives/C02B6955S4S/p1723620621805789

**Comment by nypnop** [comment]
sorry, I try to test it on my openmetadata but still having the issue, what I need to do on that ?

**Comment by karanh37** [comment]
This will be available with 1.5 release.
