### ISSUE TITLE
Impossible to partially copy a query from the Queries tab in table UI

### ISSUE THREAD

**Issue by sylthiel** [open-metadata/OpenMetadata#17466]
**Affected module**
UI

**Describe the bug**
Attempts to copy any part of a table's query manually (either via right click or ctrl+c) are unsuccessful

**To Reproduce**

Navigate to a table that has a query added to it.
Attempt to copy part of the statement (for example the ```WHERE x = y``` block

**Expected behavior**
The visually selected text is copied

**Actual** 
The visually selected text is not copied

**Version:**
OM 1.4.4

**Comment by harshach** [comment]
I can copy in latest version 
<img width="999" alt="image" src="https://github.com/user-attachments/assets/439ceb2d-254a-4e57-b14f-77f02213e761" />
