### ISSUE TITLE
Profiler best practices link in profile configuration sidebar is dead

### ISSUE THREAD

**Issue by sylthiel** [open-metadata/OpenMetadata#17465]
**Affected module**
UI

**Describe the bug**
https://docs.open-metadata.org/latest/connectors/ingestion/workflows/profiler#profiler-best-practices is a dead link

**To Reproduce**
Click on the link to best practices from the profiler ingestion configuration window. 

**Expected behavior**
The documentation is opened.

**Actual**
Page not found :(

**Version:**
OM 1.4.4

**Comment by TeddyCr** [comment]
Thank you for raising this. This is already solve in the upcoming 1.5 version 😊
