### ISSUE TITLE
Failed to export the file to CSV

### ISSUE THREAD

**Issue by Leefourk** [open-metadata/OpenMetadata#17479]
Hello,I am having problems exporting the team CSV file.
This is my error message in EntityCsv.java:147:
`public static CsvDocumentation getCsvDocumentation(String entityType) {
    LOG.info("Initializing CSV documentation for entity {}", entityType);
    String path = String.format(".*json/data/%s/%sCsvDocumentation.json$", entityType, entityType);
    try {
      List<String> jsonDataFiles = EntityUtil.getJsonDataResources(path);
      String json =
          CommonUtil.getResourceAsStream(
              // Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
              EntityRepository.class.getClassLoader(), jsonDataFiles.get(0));  
      return JsonUtils.readValue(json, CsvDocumentation.class);
    } catch (IOException e) {
      LOG.error(
          "FATAL - Failed to load CSV documentation for entity {} from the path {}",
          entityType,
          path);
    }
    return null;
  }`

This is my teamCsvDocumentation.json
[teamCsvDocumentation.json](https://github.com/user-attachments/files/16655168/teamCsvDocumentation.json)

I hope the question can be answered

**Comment by Leefourk** [comment]
![image](https://github.com/user-attachments/assets/59d93e9f-f9e1-4306-8982-bbb09d4ca02f)

**Comment by harshach** [comment]
@Leefourk please join https://slack.open-metadata.org and ask this question before opening github issue
