### ISSUE TITLE
add dbt not compiled code to UI

### ISSUE THREAD

**Issue by oleg-savko** [open-metadata/OpenMetadata#17470]
It will be very usefull to can see not only compiled dbt code for model, but and raw to like in dbt docs

(example: when columns generate using jinja in dbt, see raw dbt code much more usefull)

**Comment by harshach** [comment]
cc @OnkarVO7

**Comment by OnkarVO7** [comment]
Hi @oleg-savko this is already handled and will be available in 1.5.0 release

**Comment by OnkarVO7** [comment]
@oleg-savko just to confirm here are you expecting to see both compiled and raw code in the UI?

**Comment by oleg-savko** [comment]
> @oleg-savko just to confirm here are you expecting to see both compiled and raw code in the UI?

Yes @OnkarVO7 , very want to see to see both compiled and raw code in the UI.

I already has version 1.5.1 on some servers but cant find raw dbt code anywhere.. ((

**Comment by OnkarVO7** [comment]
@oleg-savko this has not been implemented yet. Current behaviour shows `compiled_code` and if that is not present it will show `raw_code`

**Comment by oleg-savko** [comment]
@OnkarVO7  any plans or ideas when it can be added?

**Comment by oleg-savko** [comment]
dissapointed..
