### ISSUE TITLE
Not correct owner for tables when running dbt ingestion and similar team/user names

### ISSUE THREAD

**Issue by nicor88** [open-metadata/OpenMetadata#17510]
**Affected module**
I believe that this issue is due to the ingestion.

**Describe the bug**
I have few departments:
* data-engineering
* data-analytics

When I run dbt ingestion, the correspondent owner for tables that have dbt owner set to data-engineering is  DataInsightsApplicationBot. I expect that no owner is set, or one of the 2 department is set.

**To Reproduce**
* add owner meta tag to few dbt models containing `data-engineering` for example
* run the dbt-ingestion
* check the owner assigned to those models

**Expected behavior**

**Version:**
 - OS: Debian and MacOs
 - Python version: 3.11
 - OpenMetadata version: 1.4.7
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[dbt]~=1.4.7.0`

**Additional context**
After a chat with Pablo Takara/Sriharsha Chintalapani/Onkar Ravgan looks like that data-engineering cannot be assigned as an owner because it's a departement, which is fine, but no owner should be assigned at all.
Seems like that  the issue is due to [name_search_query_es](https://github.com/open-metadata/OpenMetadata/blob/bee4bda5019ca81bb5c939a3d8e541f8d6075b6e/ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py#L49-L59) where a fuzzy matching it's performed, leading to match DataInsightsApplicationBot (the closest to data-engineering).
I expect that:
* an full equality match it's performed
* bots are excluded from the matching

**Comment by nicor88** [comment]
Here some findings regarding this issue.
In my understanding the issue seems related to the fact that `-` is used on the dbt_owner, therefore when [name_search_query_es](https://github.com/open-metadata/OpenMetadata/blob/bee4bda5019ca81bb5c939a3d8e541f8d6075b6e/ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py#L49-L59) run, it evaluates as `search for data without engineering`, in my understanding the - is evaluated as a operator to tell Opensearch/Elasticsearch that should exclude some terms.

But what is weird, is that if I use data.engineering, therefore a . separator, seems to behave as -, and the bot is returned `datainsightsapplicationbot`

Also, worth to mention, that I tested this beavior in 1.4.7 and 1.5.0 dbt ingestion.

One of the solution that I'm adopting is to use "names" without a separator, because anyhow the Display name of a team can show what I want.
In my case therefore the team name will be `dataengineering` or `dataanalytics`.

**Comment by ulixius9** [comment]
fixed by https://github.com/open-metadata/OpenMetadata/pull/18645
