### ISSUE TITLE
Add Glossary Term API Call Fails

### ISSUE THREAD

**Issue by andkay** [open-metadata/OpenMetadata#17557]
**Affected module**
REST API (glossaryTerms endpoint)

**Describe the bug**
Calling the [Bulk Add Glossary Term to Assets](https://docs.open-metadata.org/swagger.html#operation/bulkAddGlossaryTermToAssets) end point results in a Java null pointer error. We've tested various API calls using cURL (not the SDK) and this is so far the only one that has failed.

```
{"dryRun":false,"status":"failure","numberOfRowsProcessed":1,"numberOfRowsPassed":0,"numberOfRowsFailed":1,
"successRequest":[],"failedRequest":[{"request":{"id":"035e8a10-db1b-404d-bf6e-99649d552acb",
"type":"table","name":"<REDACTED>","fullyQualifiedName":"<REDACTED>","displayName":"<REDACTED>","deleted":false},
"message":"Cannot invoke \"java.util.Collection.toArray()\" because \"c\" is null"}]}
```

**To Reproduce**
```
curl -X PUT "http://localhost:8585/api/v1/glossaryTerms/274b6b41-a865-4549-bc1e-1e3306043a4f/assets/add" \
-H "accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $mytoken" \
-d '{
  "assets": [
    {
      "id": "035e8a10-db1b-404d-bf6e-99649d552acb",
      "type": "table",
      "fullyQualifiedName": "<REDACTED>"
    }
  ],
  "dryRun": false,
  "operation": "AddGlossaryTags"
}'
```

**Expected behavior**
Successful request, resulting in an a tag being added to a table.

**Version:**
 - OS: Red Hat Enterprise Linux
 - OpenMetadata version: 1.4.5

**Comment by harshach** [comment]
@andkay can you please discuss this in https://slack.open-metadata.org to confirm if its indeed a bug, before opening a ticket
