### ISSUE TITLE
0.7 UI improvements

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1761]
- [x] Activity Feed page 
![IMG_7662](https://user-images.githubusercontent.com/38649/146117551-5aae6419-9357-4c83-9b4f-3e6cb159a818.jpeg)
Move left panel and right panels below the activity feed level. Also the text next to the icons is not aligned properly like Tables icon and "Tables" text is below the icon
- [x] Lets remove select all and deselect all per filter 
![image](https://user-images.githubusercontent.com/38649/146118201-f72eefe0-f8eb-43c4-b2be-9f2540355c70.png)
- [x] All Activity Select box should be in purple
![IMG_0014](https://user-images.githubusercontent.com/38649/146117571-a7d411df-3689-4bcf-8ebc-08bcdaa2efa0.jpeg) similar to explore sort by text color 
![image](https://user-images.githubusercontent.com/38649/146118047-285ae503-12f2-437f-8485-2c96ac4812e9.png)
- [x] Tier tag and above row has too much space in between. Could be due to "rows" text is wrapping around
![IMG_3596](https://user-images.githubusercontent.com/38649/146117645-f797f19c-4627-456e-92ee-1eb7fc1f3545.jpeg)
- [x] Rename "users list" to "Users" 
![IMG_8237](https://user-images.githubusercontent.com/38649/146117752-e8f4c94d-4849-45e4-a964-bf10e68f3120.jpeg)
- [x] Explore Tab names can be purple as well 
![IMG_7666](https://user-images.githubusercontent.com/38649/146117863-e13319d9-84fa-4c64-a9e5-868363d6fe1c.jpeg)
- [x] Search bar at the top background could be gray to give little bit of depth and the search magnifying glass can be purple 
![image](https://user-images.githubusercontent.com/38649/146117940-34d85421-a78f-48b4-b455-e7704f99f86b.png)
- [x] Activity Feed date separator text and line can be in purple 
![image](https://user-images.githubusercontent.com/38649/146118002-5677e979-c3e2-4660-93b9-b17bee150ba3.png)
- [x] Team descriptions should be set, cc @ayush-shah in sample-data
![IMG_6473](https://user-images.githubusercontent.com/38649/146117700-89818813-b9b6-4cbc-8f32-adb525429693.jpeg)
- [x] OpenMetadata Icon should have text next to it just like we have it in our logos across our resources github, docs etc..

**Comment by harshach** [comment]
@sanketbambulkar @shahsank3t @darth-coder00 @Sachin-chaurasiya ^

**Comment by ayush-shah** [comment]
Added the Team Description in #1776
