### ISSUE TITLE
Adding a link to the new content on the menu content.

### ISSUE THREAD

**Issue by nakaken-churadata** [open-metadata/OpenMetadata#17640]
**Is some content missing, wrong or not clear?**
I tackled and completed issue #9875 about the secret managers and GCP.
I also created some documents but forgot to create a link to them on the menu content.
This issue corresponds to them.

**Describe the solution you'd like**
Adding a link to the new content on the menu content.

**Comment by harshach** [comment]
@Prajwal214 can you check this
