### ISSUE TITLE
The Quickstart Local Docker Deployment recipes are not working on Mac

### ISSUE THREAD

**Issue by cornelcreanga** [open-metadata/OpenMetadata#17677]
This is related to https://github.com/open-metadata/OpenMetadata/issues/15177. I've tried to follow the steps described here https://docs.open-metadata.org/latest/quick-start/local-docker-deployment but docker compose fails (both Mysql and Postgres based versions).

Command: docker compose -f docker-compose.yml up (for the mysql version)

Mysql output
```
openmetadata_mysql          | 2024-09-02T17:28:06.100438Z 0 [ERROR] [MY-010174] [Server] Can't change data directory owner to mysql
openmetadata_mysql          | 2024-09-02T17:28:06.100483Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
openmetadata_mysql          | 2024-09-02T17:28:06.100689Z 0 [ERROR] [MY-010119] [Server] Aborting
openmetadata_mysql          | 2024-09-02T17:28:06.101038Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
```
Postgres
```
openmetadata_postgresql     | chown: changing ownership of '/var/lib/postgresql/data': Permission denied
openmetadata_postgresql exited with code 0 
```

Mac Os Sonoma 14.6.1 
Open Metadata docker files 1.5.1 - it can be reproduced with lower versions too.

**Comment by harshach** [comment]
@cornelcreanga before opening a github issue, please join https://slack.open-metadata.org and ask this quesiton #support channel. Once reviewed if its indeed a bug not an local environment issue we can open a github issue.
