### ISSUE TITLE
Wrong faceted UI for tableau models: dashboard, chart, data models

### ISSUE THREAD

**Issue by nicor88** [open-metadata/OpenMetadata#17675]
**Affected module**
UI

**Describe the bug**
When searching something in OM, the faceted search in case of tableau models(chart,data-models and  dashboards) shown the ID of the tableau entity, not the name.

**To Reproduce**
* ingest some data from tableau
* enter the name of a dashbord that can match the search, but DO not type enter, let the facet serarch pop up
* see that in the pop up there are ids, not names - that make the faceted search a bit useless for table

<img width="649" alt="Screenshot 2024-09-02 at 19 37 16" src="https://github.com/user-attachments/assets/fa2881a3-fd1b-4383-889d-329de31827e4">

**Expected behavior**
I would like to see the name of the entities, not the ids, to really facilitated the users the usage of faceted.

**Version:**
 - OS: Linux
 - Python version: 3.11
 - OpenMetadata version: 1.5.1

**Additional context**

**Comment by harshach** [comment]
@karanh37 can you handle this, for dashboards, dashboardDataModel, charts we should show displayname, and search API does give you all the details 
<img width="2187" alt="image" src="https://github.com/user-attachments/assets/d62c366b-8068-48fe-ba71-21848b9103b5">

**Comment by nicor88** [comment]
@harshach thanks you for the support here.

Do we have any timeline on when such bug will be addressed? in which release? Thanks again.
