### ISSUE TITLE
Problem with yaml for dbt ingestion

### ISSUE THREAD

**Issue by phil59omd** [open-metadata/OpenMetadata#17672]
Hi,

I'm working with the version 1.3.1.
Despite many attempts, I am unable to write a correct YAML file for dbt ingestion.
I am working on local with Windows, the server is on a docker container.
The file 

source:
  type: dbt
  serviceName: 'Service_name'
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
        dbtConfigType: local
        dbtCatalogFilePath: 'C:\\path\\catalog.json'
        dbtManifestFilePath: 'C:\\path\\manifest.json'
        dbtRunResultsFilePath: 'C:\\path\\run_results.json'      
      dbtUpdateDescriptions: true
      includeTags: true
      dbtClassificationName: 'dbtTags'
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO  # DEBUG, INFO, WARNING or ERROR
  openMetadataServerConfig:
    hostPort: 'https://server_adress/api'
    authProvider: openmetadata
    securityConfig:
      jwtToken: 'token'
    storeServiceConnection: true

Thanks.

**Comment by harshach** [comment]
@phil59omd please join our slack https://slack.open-metadata.org before opening a github issue.
You should use the latest version, 1.3.1 is almost an year old
