### ISSUE TITLE
Error in Users Sign-Up Page

### ISSUE THREAD

**Issue by ktreharrison** [open-metadata/OpenMetadata#17696]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
This is impacting our UI and backend

**Describe the bug**

The sign-up feature. When a new user tries to sign up to our openmetadata instance, they are unable to create their user on both Firefox and Chrome (see image). 

**To Reproduce**
1. New user clicks on our [prod env](https://prod.frogman.ats.amazon.dev/) 
2. Username and email is autopopulated from our authenticator
3. User selects team
4. User clicks create and gets an error.

Screenshots or steps to reproduce
![frogman-signup-error](https://github.com/user-attachments/assets/2305e908-d69b-4393-b97b-9d55affb847f)
![frogman-signup-error-1](https://github.com/user-attachments/assets/6b37dd44-7fac-457f-9190-5ec8a4dbd4dd)

**Expected behavior**
1. User see's signup page
2. User joins a team (External if their team is not listed)
3. User then joins and logins into our instance 

**Version:**
 - OS: [e.g. iOS] Windows
 - Python version: 3.9+
 - OpenMetadata version: [e.g. 0.8] 1.4.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

We also see team duplication when trying to create a user from the admin panel:
![Screenshot 2024-08-30 at 14 54 14](https://github.com/user-attachments/assets/b089d983-267b-4f3f-9340-51fe3de10414)

**Comment by Sachin-chaurasiya** [comment]
Hello @ktreharrison, thanks for filing the issue. This has been fixed in the latest release.

**Comment by ktreharrison** [comment]
Thanks @Sachin-chaurasiya! Can you point me into where this fix is in the repo ?

**Comment by Sachin-chaurasiya** [comment]
> Thanks @Sachin-chaurasiya! Can you point me into where this fix is in the repo ?

@ktreharrison, we recommend you upgrade to the latest version or 1.4.8
