### ISSUE TITLE
Improve Slack Templates

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#17717]
We need to update the way the template looks and feels Slack , for example below doesn't look that great
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/a14a458e-baab-4ad4-bbe0-aa1fcbae2604">

Following can be different Notifications and what we can show with them :- 

- [x] Currently we are using only one format for all the notifications we are sharing, we need to come up with per entity schema to allow us to control building the template for different entity type, and also what kind of information being sent in message for that entity.
This is the schema for that class :- 
public class SlackMessage {
  private String username;
  private String iconEmoji;
  private String channel;
  private String text;
  private String responseType;
  private SlackAttachment[] attachments;
} 

On top of this we need to take into account different entities like Table , Chart etc, to allow us to build TableSlackMessage, ChartSlackMessage, and create mappers to convert that into proper SlackMessage with defined format , for example below looks great for Glossary.
![image](https://github.com/user-attachments/assets/bd166009-0326-492f-97db-8d658062cb54)

- [x] Test Case Result Notification needs enrichemnt as well , we are only showing success and failure . We need to build the whole context for the failure , like which table/ column it failed for, what were the parameter definiation and also show any failure message if available , for example we can have the following details :- 
 Failure Message 
 Table/Column for which it failed
 Result Message
 Test Result Sample/ Query
 Configuration - Test Param Definitions

**Comment by haithem-souala** [comment]
Any Eta, this new template is so needed.
