### ISSUE TITLE
Search bar is showing the ID instead of the display name

### ISSUE THREAD

**Issue by thiagopirex** [open-metadata/OpenMetadata#17739]
**Affected module**
Impact the UI

**Describe the bug**
After ingesting dashboards data, the search bar show id's dashboard instead of it's display name.

**To Reproduce**
Dashboard ID (name): 98290598-1861-4dd3-8d49-a0e7d2144
Dashboard Display Name: abc_dashboard

<img width="343" alt="dashboard" src="https://github.com/user-attachments/assets/d5d2a462-2b2a-45ce-a1ee-a0ce9e45def5">

**Expected behavior**
The search bar should show the display name of the dashboards, like "Qliksense.abc_dashboard"

**Version:**
 - OS: [docker environment](https://hub.docker.com/layers/openmetadata/server/1.5.2)
 - Python version: 3.11
 - OpenMetadata version: 1.5.2
 - OpenMetadata Ingestion package version: 1.5.2.0

**Comment by harshach** [comment]
this is fixed as part of this issue https://github.com/open-metadata/OpenMetadata/issues/17675 will be part of 1.5.3
