### ISSUE TITLE
Bug: Tried to connect Airflow to OpenMetadata

### ISSUE THREAD

**Issue by DigitalTransformation-DataPlatform** [open-metadata/OpenMetadata#17751]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
All of them
**Describe the bug**
My bug is: Field Required.
pydantic_core._pydantic_core.ValidationError: 4 validation errors for AirflowDagDetails
tasks.0.task_id
  Field required [type=missing, input_value={'__var': {'template_fiel...}, '__type': 'operator'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
tasks.1.task_id
  Field required [type=missing, input_value={'__var': {'template_fiel...}, '__type': 'operator'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
tasks.2.task_id
  Field required [type=missing, input_value={'__var': {'template_fiel...}, '__type': 'operator'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
tasks.3.task_id
  Field required [type=missing, input_value={'__var': {'template_fiel...}, '__type': 'operator'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
**To Reproduce**

Screenshots or steps to reproduce
My Logs on OM: ![image](https://github.com/user-attachments/assets/ca2644f0-c66a-405f-92d7-0f063b94e5d6)
My status collected metadata from Airflow on OM sucessuflly: **(No Pipelines)**, although it already has a pipeline on Airflow 
![image](https://github.com/user-attachments/assets/9b5fc877-67dd-4fe1-95d7-76e0c5580b27)
My configuration on OM to connect with Postgresql:
![image](https://github.com/user-attachments/assets/a0f12faf-6fbc-4427-a07d-c87c59af4940)
**Expected behavior**

I would like to connect my airflow db to OM to manage metadata 
**Version:**
 - OS: [e.g. Window 11]
 - Python version: 3.10
 - OpenMetadata version: [e.g. 1.5.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
You can use docker-compose file and run it. You will see my error in OM

[Big_Data_Platform.zip](https://github.com/user-attachments/files/16906412/Big_Data_Platform.zip)

**Comment by DigitalTransformation-DataPlatform** [comment]
I already fixed it, Thanks for OM Community

**Comment by edallastella** [comment]
Hello @DigitalTransformation-DataPlatform! How did you fix this error? I've come across the same thing.
