### ISSUE TITLE
0.8 UI improvements

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1775]
- [x]  Icons needs to be consistent and have better weight
![IMG_2097](https://user-images.githubusercontent.com/38649/146117786-8b92a45e-604f-4696-8be2-62e865acff87.jpeg)
- [ ] Table Entity page, can we add bit of separation and add gray background like we have in rest of the pages 
![image](https://user-images.githubusercontent.com/38649/146118134-542fbf3b-76ed-4700-81f6-0474fa1e1c4e.png)

**Comment by harshach** [comment]
- [ ] on selection of DBT tab we are changing the icon for it 
![image](https://user-images.githubusercontent.com/38649/146233764-34e11b5e-566d-4db2-b2be-9b09e83f07d7.png)
- [ ] Change the "user" in users page dialog box and put "Role: User or Admin" do not use Italics. Also remove "Dismiss as Admin" -> "Revoke Admin Privileges"  
![image](https://user-images.githubusercontent.com/38649/146234051-0676d84f-6902-4997-aeca-7dac3f8635df.png)

**Comment by harshach** [comment]
- [ ] Clear all option is way up there and almost into the tabs rather than closer to filter 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/38649/146296666-3e5c81ec-b4a2-4eda-9b29-8c7d059770a4.png">

**Comment by harshach** [comment]
- [ ] It looks like we are capturing empty space as search term 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/38649/146429165-ba0e8d05-d708-439d-8934-63cead94b7a3.png">

**Comment by shahsank3t** [comment]
@harshach the above `empty space` search term has been fixed in https://github.com/open-metadata/OpenMetadata/commit/3d50f15e974d48f267f23a61f0c0c32a425477ca

**Comment by harshach** [comment]
@shahsank3t @darth-coder00 as we discussed previously, lets lower the right and left sections in landing page
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/146730996-9d98d24f-56bb-452c-9030-824bd9ebc72f.png">
Tables and My Data on left & right panel should be lower. compare to Activity Feed selection
