### ISSUE TITLE
Left column for faceted search on Explore page disappears some times

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1777]
Steps to reproduce:
- From the landing page, search for a data asset entity name that doesn't exist. Say zzzz.
- After getting No results found, clock Explore tab. While List of table are shown, no left side column for faceted search is shown.

cc @harshach

**Comment by harshach** [comment]
Also the page doesn't scroll even when we have results

**Comment by harshach** [comment]
@parthp2107 need a test for this

**Comment by parthp2107** [comment]
> @parthp2107 need a test for this

Will add it in selenium
