### ISSUE TITLE
For Database we are referring to Name instead of DisplayName

### ISSUE THREAD

**Issue by Prajwal214** [open-metadata/OpenMetadata#17786]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? > UI

**Describe the bug**
A clear and concise description of what the bug is.  > Under Explore Tab, For Database we are referring to Name instead of DisplayName.

**To Reproduce**

Screenshots or steps to reproduce
![image](https://github.com/user-attachments/assets/1eaacf88-d1c6-42c8-a92e-78b340a5b038)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] OM v.1.5.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by karanh37** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/17876
