### ISSUE TITLE
bug: Table patch fails when multiple owners are defined

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/OpenMetadata#17840]
**Affected module**
Ingestion / Backend

**Describe the bug**
When I try to patch the table entity and specify two owners in the patch request, the patch will fail with error (backend logs):

```
ERROR [2024-09-14 05:35:49,046] [dw-114 - PATCH /api/v1/tables/2d28de1a-0ea9-4759-b113-3c6a0bab6e72] o.o.s.r.d.TableResource - Got exception: [NullPointerException] / message [Cannot invoke "java.lang.Comparable.compareTo(Object)" because the return value of "java.util.function.Function.apply(Object)" is null] / related resource location: [org.openmetadata.service.resources.databases.TableResource.patch](TableResource.java:420)
```

**To Reproduce**
```
from metadata.generated.schema.entity.data.table import Table
from metadata.generated.schema.type.entityReference import EntityReference
from metadata.generated.schema.type.entityReferenceList import EntityReferenceList
from metadata.generated.schema.entity.teams.user import User

t = c.get_by_name(Table, "register-test-db-2.hive.register-test-db-2-udemy.raw_data_1")
u1 = c.get_by_name(User, "mariusz.gorski")
u2 = c.get_by_name(User, "tony.soprano")

owners2 = EntityReferenceList([EntityReference(id=u1.id.root, type="user"), EntityReference(id=u2.id.root, type="user")])

c.patch_owner(Table, t, owners2, force=True)  # fails
```

**Expected behavior**
Both owners assigned as owners of a table.

**Version:**
 - Python version:
 - OpenMetadata version: 1.5.2
 - OpenMetadata Ingestion package version: 1.5.2

**Additional context**

**Comment by harshach** [comment]
You cannot do patch like that. Its needs a fresh copy from last call. Try doing a get and before the second patch call

**Comment by mgorsk1** [comment]
I agree and I should have been more precise @harshach, to reproduce you should comment out one of these two last lines and run single patch operation. I have amended the original issue not to create confusion. The problem remains and this issue is still valid after updating the code for reproducing. 

I found that adding name property to EntityReference solves it but it might be some bug server side that it's required at all to work.

**Comment by harshach** [comment]
refer to the example here https://github.com/open-metadata/openmetadata-demo/blob/7f32a75a29a8d64b180d117f6e5ea1f78c78bce9/example_apis.py#L259
