### ISSUE TITLE
Default Admin username in documentation

### ISSUE THREAD

**Issue by iouri-forusall** [open-metadata/OpenMetadata#17843]
**Is some content missing, wrong or not clear?**
Default admin username in the documentation is `admin@open-metadata.org` while actual username after docker compose is created as `admin@openmetadata.org`. I am not sure if there are other places in the doc where it should be updated as well.

https://docs.open-metadata.org/latest/quick-start/local-docker-deployment#log-in-to-openmetadata
https://docs.open-metadata.org/v1.6.x-SNAPSHOT/quick-start/local-docker-deployment#log-in-to-openmetadata

**Describe the solution you'd like**
Please update the docs with `admin@openmetadata.org` as default admin username.

**Additional context**
none

**Comment by rchlz** [comment]
This problem also exists in the 1.4.x version of the document
