### ISSUE TITLE
Search API bugs 

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#17851]
**Affected module**
Backend

**Describe the bug**

1. `/aggregate` API does not return all possible suggestions when some text is passed as `value` for `displayName.keyword`. This is especially when there are capital letters present in the display name. 
example request: `/api/v1/search/aggregate?index=database_search_index%2Cdatabase_schema_search_index%2Ctable_search_index%2Cstored_procedure_search_index&field=displayName.keyword&value=.%2ADim.%2A&q=%7B%22query%22%3A%7B%22bool%22%3A%7B%7D%7D%7D`

https://github.com/user-attachments/assets/4bfae430-682a-48eb-bdbe-fdaf074512d2

2. There is a mismatch between the index_count and the list of entities for API collections and API endpoints data assets

https://github.com/user-attachments/assets/54fcff66-ce78-41cc-9208-fa61df9fb334

3. In case the display name is absent for entities fallback to name in ES, same as we do for tables 
![image](https://github.com/user-attachments/assets/df11cfea-2c56-4658-b837-5da4c2135037)

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
2&3 are addressed in this PR https://github.com/open-metadata/OpenMetadata/pull/17871
