### ISSUE TITLE
Search does not highlight the text properly

### ISSUE THREAD

**Issue by NithinKumaraNT** [open-metadata/OpenMetadata#17877]
**Affected module**
UI 

**Describe the bug**
I have noticed that when using the search bar the search results are not considering the special characters and numbers. For example, I used the sandbox collate environment to search for “my_table2” and the screenshot shows that the special characters and numbers are not highlighted. Is this a UI issue or elasticsearch is not configured ?

**To Reproduce**

![image](https://github.com/user-attachments/assets/bb995b40-1b16-46d1-a249-fb9a8c6515ac)
![image](https://github.com/user-attachments/assets/fd7386d2-3b32-4a0e-91cb-c27dd7fcf8f0)

**Expected behavior**
The entire text is highlighted fully instead of partial highlight as this would not mislead the users of the catalog.

**Version:**
 - OpenMetadata version: 1.5.3 (Sandbox - Collate)

**Additional context**

**Comment by harshach** [comment]
<img width="910" alt="image" src="https://github.com/user-attachments/assets/81d63718-9fb0-4b37-986d-7cb022b57f0f" />
Fixed
