### ISSUE TITLE
PowerBI column lineage is not showing end-to-end lineage.

### ISSUE THREAD

**Issue by harshsoni2024** [open-metadata/OpenMetadata#17908]
**Affected module**
Ingestion module

**Describe the bug**
PowerBI column lineage is not showing end-to-end with column of datamodel. Instead it shows lineage with data-model only

**Expected behavior**
Column to column lineage between datamodel columns and db table columns

**Version:**
 - OpenMetadata version: [e.g. 1.5.x]

**Additional context**
<img width="638" alt="Screenshot 2024-09-18 at 5 09 07 PM" src="https://github.com/user-attachments/assets/23f2a589-3e4b-4e88-8279-74924c59f545">
<img width="648" alt="Screenshot 2024-09-18 at 5 09 00 PM" src="https://github.com/user-attachments/assets/a054ad44-d7c7-45f7-845c-93631b6e33b2">

**Comment by ulixius9** [comment]
closing by https://github.com/open-metadata/OpenMetadata/pull/18030
