### ISSUE TITLE
Looker does not support liquid templates or aliased views/models

### ISSUE THREAD

**Issue by sam-mccarty-mavenclinic** [open-metadata/OpenMetadata#17911]
**Affected module**
Ingestion Framework

**Describe the bug**
My team uses templating to adjust our sql table name during development, while leaving the production table as the base condition. 

**To Reproduce**
Ingest LookML with liquid templates in the sql_table_name and observe lineage generation failures

Screenshots or steps to reproduce

**Expected behavior**
I would like the ingestion to try to render the templates with no variables to render the base condition. Likewise, I would like the lineage creation to use the `from_` attribute of a Looker view when it exists or the `view_name` of a model when that exists, regardless of whether there are other joins present in the model (as the current logic requires)

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sam-mccarty-mavenclinic** [comment]
@sushi30 any idea which release this is slated for? i saw it missed 1.5.6, hoping to let my team know when to expect it before i got on leave later this month

**Comment by sushi30** [comment]
It will be in 1.6
