### ISSUE TITLE
Incorrect display of link in user description

### ISSUE THREAD

**Issue by feride-sh** [open-metadata/OpenMetadata#17924]
**Affected module**
UI

**Describe the bug**
In the user profile description I want to indicate a link to the corporate resource profile. Unfortunately, the description is displayed as a nice link only if the user looks at their description through their account (picture 2). If another user looks at the description, the link becomes as in picture 1. 
![image](https://github.com/user-attachments/assets/71860a14-ed7e-4144-8b06-7ddbce27c989)
![image](https://github.com/user-attachments/assets/235264bf-d814-4a41-8f21-7750be0e4422)

**Expected behavior**
The link is displayed beautifully

**Version:**
 - OpenMetadata version: 1.5.4

**Comment by harshach** [comment]
fixed in 1.6.0 
<img width="275" alt="image" src="https://github.com/user-attachments/assets/536a13b2-b16d-4103-8e17-89d02da62e70" />
<img width="275" alt="image" src="https://github.com/user-attachments/assets/012b0402-de9e-4e48-8a26-88aaee4de574" />
