### ISSUE TITLE
metadata docker --start with non standard /tmp dir

### ISSUE THREAD

**Issue by cons0l3** [open-metadata/OpenMetadata#1796]
I currently trying out your work and stumble upon the `metadata docker --start` requiring a /tmp directory.

from ingestion/src/metadata/cmd.py line 200ff:
```
...
                open("/tmp/docker-compose.yml", "wb").write(r.content)
                start_time = time.time()
                subprocess.run(
                    f"docker compose -f /tmp/docker-compose.yml up -d", shell=True
                )
...
```

My systems are a) linux with no /tmp directory at that static location, b) a windows system with its temp folder also not at that location. But the python `tempfile` module finds the correct location thru its magic either way: 
```
import tempfile
tempfile.gettempdir()
```

Please consider to make the code in cmd.py more flexible by not using a static folder location for temp files.

Cheers
Carsten

**Comment by ayush-shah** [comment]
Hey @cons0l3, let me know if you are interested in contributing the effort in any way - code, test, or comment. Thank you for creating this issue.

**Comment by cons0l3** [comment]
I will fork and submit a PR, after work ;-).

**Comment by ayush-shah** [comment]
Yeah, no worries, Thanks🙂
