### ISSUE TITLE
metadata docker --start relies on "wget" being installed and uses bash syntax

### ISSUE THREAD

**Issue by cons0l3** [open-metadata/OpenMetadata#1797]
I am currently trying to get started with `metadata docker --start`. It relies on "wget" being installed. Which it is not in my linux environment (nor is it compatible with a powershell windows environment). Additionally it requires to be run in a unix shell (bash?).

see src/metadata/cmd.py:211ff

I would suggest to use python to do the "wait for it". see e.g. the very approach of the python module (wait-for-it)[https://github.com/clarketm/wait-for-it]. The reduces depenecies on the OS running.

**Comment by cons0l3** [comment]
i can assist with a fork and PR.

**Comment by akash-jain-10** [comment]
Thanks for the suggestion. It would be great to have your contributions for Open Metadata. I'll assign this one to you.
