### ISSUE TITLE
Ingestion pipeline search should only return relevant results.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#18019]
**Affected module**
UI

**Describe the bug**
When searching for ingestion pipelines on the service details page, the results shown, contain ingestion pipelines from other services as well.

https://github.com/user-attachments/assets/cd4d2fb2-d351-4226-9660-5d66682e78ef

**Expected behavior**
The search should only display the pipeline from the respective service.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by datapopcorn** [comment]
Nice,  hope this fix can be included in the next release. THX

**Comment by aniketkatkar97** [comment]
Yes, this will be included in 1.6 release
