### ISSUE TITLE
DBT ingestion errors

### ISSUE THREAD

**Issue by aballiet** [open-metadata/OpenMetadata#18011]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

DBT ingestion

**Describe the bug**

`2024-09-26 12:16:52.750  Expected `ColumnLineage` but got `dict` with value `{'fromColumns': ['bq-gorg...nies_upsert.segment_id'}` - serialized value may not be as expected
`

Errors:
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/02e03af8-0b59-4ca2-a764-1ce88f7cef98">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ulixius9** [comment]
fixed with https://github.com/open-metadata/OpenMetadata/pull/17708

also @aballiet this is just a warning and can be ignored.
