### ISSUE TITLE
Support Dagster as a pipeline connector

### ISSUE THREAD

**Issue by NicolasPA** [open-metadata/OpenMetadata#1801]
[Dagster](https://dagster.io/) is a new generation Python based orchestrator (competing with Prefect) that I think should be part of the pipeline connectors. I think people building new data architectures today are likely to be using one or the other. 

I think it's quite aligned with the metadata mindset considering one of their main features is the ability to easily track data interactions https://docs.dagster.io/concepts/assets/asset-materializations

**Comment by samuelstuetz** [comment]
With the new assets handling that dagster already contains, by simply attaching to dagsters event bus and publishing to it, via graphql and an open metadata sensor,
an integration should be much simpler than with most other systems.

**Comment by harshach** [comment]
@samuelstuetz thanks for the details Would you be interested in contributing. We can work with you to get the dagster integration right

**Comment by harshach** [comment]
@codingwithabhi can we take it up this week?
cc @pmbrull

**Comment by pmbrull** [comment]
I think @ulixius9 might be able to pick it up this week as he also has the Pipeline Topology on his plate
