### ISSUE TITLE
bug: Inconsistent service name in search filters

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/OpenMetadata#18026]
**Affected module**
UI / Search

**Describe the bug**
I have a Trino database service registered with 'DAP IPC Datasources' set as display name. When in explore view, I click on 'Service name' filter to select this service for filtering the results. The name 'DAP IPC Datasources' appears twice with different uppercase/lowercase approach:

![image](https://github.com/user-attachments/assets/5424a07a-051d-4a67-b038-feff9aa633a9)

I checked and the numbers (amount of entities for each service name) reflect amount of tables (first line - lowercase) and schemas (second line - uppercase) ingested in this service respectively. When I filter by first one I only get tables from this service, when I click on second one, only schemas are returned.

**To Reproduce**

Create a database service with uppercase characters in display name, reindex all data.

**Expected behavior**

Same exact value for service name is used regardless whether it's schema or table level.

**Version:**
 - Python version: 3.10
 - OpenMetadata version: [e.g. 0.8] 1.5.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.5.4

**Additional context**

**Comment by mgorsk1** [comment]
cc @dechoma

**Comment by sonika-shah** [comment]
The above issue is resolved in 1.5.9 OM release
