### ISSUE TITLE
Docs are missing for MicroStrategy & Lightdash Connectors

### ISSUE THREAD

**Issue by Prajwal214** [open-metadata/OpenMetadata#18029]
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.
--Docs are missing for MicroStrategy & Lightdash Connectors

**Describe the solution you'd like**
Let us know what could help us improve the docs.
-- Adding docs for MicroStrategy & Lightdash Connectors

**Additional context**

**Comment by pmbrull** [comment]
rel to https://github.com/open-metadata/OpenMetadata/issues/12900
