### ISSUE TITLE
Support for Custom Headers and HTTP Methods for Webhook

### ISSUE THREAD

**Issue by Siddhanttimeline** [open-metadata/OpenMetadata#18066]
Fix https://github.com/open-metadata/OpenMetadata/issues/17879
Backend : https://github.com/open-metadata/OpenMetadata/pull/18056

**UI Changes Required :**

1. Field for providing custom headers for webhook.
2. Toggle button or another appropriate way for selecting between POST (default) and PUT HTTP methods for the webhook.

**Comment by aniketkatkar97** [comment]
Fixed in #18448
