### ISSUE TITLE
Edit Lineage Operation not working with isOwner() condition

### ISSUE THREAD

**Issue by Prajwal214** [open-metadata/OpenMetadata#18099]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? -- Backend

**Describe the bug**

-- Edit Lineage Operation not working with isOwner() condition.

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/user-attachments/assets/df40c1e9-1871-4993-beba-b79aee3cc823

**Expected behavior**

**Version:**
 - OS: [e.g. iOS] Mac OS X
 - Python version:
 - OpenMetadata version: [e.g. 0.8] OM v1.5.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by dechoma** [comment]
may be related 
https://github.com/open-metadata/OpenMetadata/pull/17661
