### ISSUE TITLE
Feature Request - Dictionary

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#1810]
Hi,

It would be a big + for OpenMetada, if you could add this feature:

Dictionary, where DATA consumer, could find the definition of the Metrics and how it's calculated (SQL Query), something like this:

![Capture d’écran 2021-12-16 à 23 22 20](https://user-images.githubusercontent.com/75131226/146457795-5c2a5fdd-a124-474c-85fd-41d5bbb68e44.png)

**Comment by rubenssoto** [comment]
This is a good feature, today we use another system to document the metrics and show the related SQL Querys

**Comment by harshach** [comment]
@haithem-souala @rubenssoto we filed another ticket here https://github.com/open-metadata/OpenMetadata/issues/2517 and this feature will be part of 0.9 release

**Comment by haithem-souala** [comment]
I can't wait to see this feature integrated.

**Comment by harshach** [comment]
@haithem-souala please checkout glossary feature we added in 0.9.0. Let us know if you still need any requirements you mentioned in this ticket
