### ISSUE TITLE
JTW Token Generation not working when using jwtPrincipalClaimsMapping for OIDC auth

### ISSUE THREAD

**Issue by wobu** [open-metadata/OpenMetadata#18138]
**Affected module**
OIDC Authentication Provider

**Describe the bug**
When using OIDC Auth (Custom) and configuring a **jwtPrincipalClaimsMapping** like: 
```yaml
jwtPrincipalClaimsMapping:
  - email:email
  - username:unique_name
```
The authentication for Personal Access Tokens or Bots won't work anymore.
The issue is that the **JWTTokenGenerator** doesn't add the JWT Claims for the  **jwtPrincipalClaimsMapping** as configured and the Authentication Controller checks for them. 

E.g. when starting an ingestion over the UI following error happens:

> 9809ac99-6c0b-4aa3-b38e-b5153cd4b822 Failed to deploy Ingestion Pipeline due to airflow API returned Internal Server Error and response {"error": "Internal error while deploying due to [Failed to generate workflow [9809ac99-6c0b-4aa3-b38e-b5153cd4b822] verify config is correct: Invalid JWT token, 'username' claim is not present] "}

**To Reproduce**

Configure a Custom OIDC authentication with a **jwtPrincipalClaimsMapping** with different claimts than 'sub' and 'email'. Then try to start a ingestion over UI, or user an PAT or configure an external ingestion.

**Expected behavior**
Authentication for Ingestin Bots, or Bots in general and PAT is still working when using OIDC authentication with custom **jwtPrincipalClaimsMapping** configuration.

**Version:**
 - OS: Linux / Docker Container / Kubernetes / Helm
 - Python version:
 - OpenMetadata version: 1.5.6
 - OpenMetadata Ingestion package version: 

**Additional context**
Suggested solution:

Add to the **JWTTokenGenerator** at **getJwtAuthMechanism()**

```java
JWT.create()
    .withIssuer(issuer)
    .withKeyId(kid)
    .withClaim(SUBJECT_CLAIM, userName)
    .withClaim(ROLES_CLAIM, roles.stream().toList())
    .withClaim(EMAIL_CLAIM, email)
    .withClaim(IS_BOT_CLAIM, isBot)
    .withClaim(TOKEN_TYPE, tokenType.value())
    .withIssuedAt(new Date(System.currentTimeMillis()))
    .withExpiresAt(expires)
    .sign(algorithm);
````

the JWT claims configured in **jwtPrincipalClaimsMapping** like:

```java
JWT.create()
    .withIssuer(issuer)
    .withKeyId(kid)
    .withClaim(SUBJECT_CLAIM, userName)
    .withClaim(jwtPrincipalClaimsMapping.get(USERNAME_CLAIM_KEY), userName)
    .withClaim(ROLES_CLAIM, roles.stream().toList())
    .withClaim(EMAIL_CLAIM, email)
    .withClaim(jwtPrincipalClaimsMapping.get(EMAIL_CLAIM_KEY), email)
    .withClaim(IS_BOT_CLAIM, isBot)
    .withClaim(TOKEN_TYPE, tokenType.value())
    .withIssuedAt(new Date(System.currentTimeMillis()))
    .withExpiresAt(expires)
    .sign(algorithm);
````

but only add the claims if they don't exist already.

**Comment by wobu** [comment]
@mohityadav766 friendly reminder i got some strange github error e-mail that the bug / issue labeling didn't work

**Comment by harshach** [comment]
ingestion bot token has nothing to do with your OIDC auth. Make sure configuring publicKeyUrls to have the OM server jwks endpoint like in docs
publicKeys:
    - "{your domain}/api/v1/system/config/jwks" # Update with your Domain and Make sure this "/api/v1/system/config/jwks" is always configured to enable JWT tokens
    - "http://localhost:8080/realms/myrealm/protocol/openid-connect/certs"

**Comment by wobu** [comment]
i am pretty sure the issue still exists. I have checked the code and the changes in the newest 1.5.14 version and i couldn't find any changes fixing this issue.

The cause of this issue is a combination of activated OIDC auth with a custom  jwtPrincipalClaimsMapping configuration. If this is the case, the current JWT Token generation for the Bots will class with the auth mechanism and then won't work anymore. 
Please reproduce this issue before closing it.

**Comment by MHajjem** [comment]
Also have this issue in 1.6.5
