### ISSUE TITLE
Fix py format check error

### ISSUE THREAD

**Issue by kuma0128** [open-metadata/OpenMetadata#18168]
**Affected module**
ingestion

**Describe the bug**
************* Module antlr.split_listener

change method name to snake_case
```
ingestion/src/metadata/antlr/split_listener.py:24:4: C0103: Method name "enterQuotedName" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:27:4: C0103: Method name "enterUnquotedName" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:38:4: C0103: Method name "enterNameOrFQN" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:41:4: C0103: Method name "enterEntityType" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:44:4: C0103: Method name "enterEntityField" doesn't conform to snake_case naming style (invalid-name)
```

**To Reproduce**

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
nothing

**Comment by ayush-shah** [comment]
Running `make py_format_check` from ingestion directory doesn't exclude the auto generated files, running it from root directory excludes it, in turn ignoring the errors.

Closing this as it is expected since it is for the methods that are auto generated by antlr
