### ISSUE TITLE
Hive Connection not working with PostgresSQL Metastore

### ISSUE THREAD

**Issue by Prajwal214** [open-metadata/OpenMetadata#18177]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
-- ingestion

**Describe the bug**
--The automation workflow for the Hive connection fails due to an internal server error from the Airflow API, returning the response: `{"error": "Error running automation workflow due to [Metastore not implemented]"}`. Despite having a PostgreSQL metastore database and successful tests on the Hive server and metastore using scripts, the connection attempts through the OpenMetadata UI or externally are failing.

**To Reproduce**

Screenshots or steps to reproduce
<img width="445" alt="image" src="https://github.com/user-attachments/assets/86b425b0-3704-4c5f-a1b9-c32f5999cdaf">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] OM v1.5.6
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by DigitalTransformation-DataPlatform** [comment]
Good morning @ulixius9 ! It looks like you've already resolved those bugs

**Comment by DigitalTransformation-DataPlatform** [comment]
I used v1.5.7, It seems that there are still errors, such as this one
