### ISSUE TITLE
bug: Ingestion schedule form not properly filled when editing existing ingestion

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/OpenMetadata#18188]
**Affected module**
UI

**Describe the bug**
When I add ingestion process with some schedule (say every Day at 5 AM) I click Submit and the change is persisted. I can see in Airflow

**To Reproduce**

- Register ingestion with Schedule: every day 5 pm
- Submit change
- Go to Edit Ingestion form (schedule tab)
- The form contains Schedule: Every Week, Monday midnight

**Expected behavior**
- The form contains Schedule I have defined previously: every day 5 pm

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] 1.5.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.5.4.0

**Additional context**

**Comment by aniketkatkar97** [comment]
Hey @mgorsk1, can you please provide some screenshots or videos or exact steps to reproduce the issue?

**Comment by mgorsk1** [comment]
here you go: https://github.com/user-attachments/assets/1530be9a-7904-4f4c-adc2-e86608d6cb2b

notice how schedule is daily but in edit form it renders as weekly

**Comment by aniketkatkar97** [comment]
Thanks for the details @mgorsk1 🙇 , This will be fixed in the 1.6 release.
