### ISSUE TITLE
Database and Schema filter on the explore page does not work properly

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#18194]
**Affected module**
UI

**Describe the bug**
When I use Database filter and Schema filter on explore page, it shows wrong table number according to the keyword I search for.

**To Reproduce**
In this case, I only have 125 tables related to keyword `table_1` in OM, but Database and Schema show incorrect result.

https://github.com/user-attachments/assets/d689ade2-c12a-4199-b31d-eafdef737527

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 1.5.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by karanh37** [comment]
Will be available with 1.6 release
