### ISSUE TITLE
Problem with Airflow version check

### ISSUE THREAD

**Issue by DanielTabP11** [open-metadata/OpenMetadata#18238]
I have encountered this problem while trying to configure OpenMetadata with an external Airflow server.
The server is running version 2.10.1. Because the code referenced below fails to detect it correctly, it tries to use an inexistent scheduler and the DAG deployment fails.

https://github.com/open-metadata/OpenMetadata/blob/07b039b8b8c88070145e4adeeb80923409160ca2/openmetadata-airflow-apis/openmetadata_managed_apis/api/utils.py#L113

**Comment by harshach** [comment]
Fixed here https://github.com/open-metadata/OpenMetadata/pull/18352
