### ISSUE TITLE
Is Synapse serverless supported?

### ISSUE THREAD

**Issue by woodyjon** [open-metadata/OpenMetadata#18233]
I see in the roadmap that Azure Synapse support should be integrated in v1.5.
And I see this PR: https://github.com/open-metadata/OpenMetadata/pull/17041

But I do not see any more information on this. And the Synapse connector is not in the docs.

Is the Synapse connector available and working? Does it support Synapse dedicated pool and/or serverless?
We use Synapse serverless, and would love to implement OM, but we would like first to be sure it fully supports Synapse serverless.

Thanks!!

**Comment by harshach** [comment]
Azure Synapse available in Collate SaaS https://docs.getcollate.io/connectors/database/synapse not in our OpenSource

**Comment by woodyjon** [comment]
Ok. Thank you.
