### ISSUE TITLE
image pull failed

### ISSUE THREAD

**Issue by AceCoronnet9034** [open-metadata/OpenMetadata#18241]
I want to experience OpenMetadata,When deploying with Docker according to the documentation, prompt “Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)”
There is no problem with the network here, Google can access it normally, and the ES image can also be pulled. Pulling other specified images has failed.
Please check if the image address is correct. Thanks.

**Comment by harshach** [comment]
we do not control the docker registry, please ask questions in https://slack.open-metadata.org before opening a github issue

**Comment by mullerhai** [comment]
I meet the some issue,because in china,how to resolve it!!! ,please give  a  better mirror download the docker image

**Comment by mullerhai** [comment]
> I want to experience OpenMetadata,When deploying with Docker according to the documentation, prompt “Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)” There is no problem with the network here, Google can access it normally, and the ES image can also be pulled. Pulling other specified images has failed. Please check if the image address is correct. Thanks.

how you resolve it
