### ISSUE TITLE
MySQL Metadata ingestion using documentation returns "extra fields not permitted" error

### ISSUE THREAD

**Issue by juliarvalenti** [open-metadata/OpenMetadata#1826]
Hi there, 

I'm following along with the documentation on this page: 
https://docs.open-metadata.org/connectors/mysql

I've filled out my mysql-ingest.json file with the necessary fields where appropriate.  When I run `metadata ingest -c ./mysql-ingest.json` I receive the following error: 

```
1 validation error for MySQLConfig
filter_pattern
  extra fields not permitted (type=value_error.extra)
```

**Comment by harshach** [comment]
@juliarvalenti thanks for opening the issue. We need to update the docs. You can rename filter_pattern to schema_filter_pattern. This is changed in the latest release. Now we can use schema_filter_pattern to filter out databases and table_filter_pattern to apply to table names

**Comment by juliarvalenti** [comment]
Perfect thanks so much @harshach !!

**Comment by harshach** [comment]
Updated the docs. Please try and confirm if the configs works for you. https://docs.open-metadata.org/connectors/mysql
