### ISSUE TITLE
Access control for Specific Classification

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#18315]
**Is your feature request related to a problem? Please describe.**
Our use case is we need a team to edit 'Tier' Classification, only this Team can modify this classification.
But there is no policy we can choose to restrict this classification to this team only and Other Team can not edit the classification.

**Describe the solution you'd like**
Maybe we can assign owner to Classification and create a policy to deny edit the classification which you are not the owner.

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
This will be addressed https://github.com/open-metadata/OpenMetadata/issues/16279 . There will be ownership and one can apply the ownership only edit
