### ISSUE TITLE
Can not find pipelines in the left menu

### ISSUE THREAD

**Issue by zhouhongyu888** [open-metadata/OpenMetadata#18369]
**Affected module**
dashboards、piplines、apis

**Describe the bug**
I  have created some pipelines for my data quality test case,  but I can not find them in the left menu，other module include apis,dashboards have the same bug。
![img_v3_02fu_dfbcc6d0-1bf1-4734-b3e5-7ce2e8c55b4g](https://github.com/user-attachments/assets/37b05cf9-3b3f-41a6-adf0-dde383931355)

**Expected behavior**
 fix the bug

**Version:**
 -1.5.7 docker deploy

**Comment by harshach** [comment]
run reindex and see if it works

**Comment by harshach** [comment]
data quality testcase pipelines are not the pipelines we display there. Ask these questions in support channel before opening a github issue
