### ISSUE TITLE
Cannot statistics indicators for quality tasks

### ISSUE THREAD

**Issue by zhouhongyu888** [open-metadata/OpenMetadata#18368]
**Affected module**
Data Quality、Test Cases、Pipeline

**Describe the bug**
I have create the test cases and pipeline, and execute my pipeline successfully，but the indicators do not display above
![image](https://github.com/user-attachments/assets/3d803dfe-afd2-4a17-90fa-45a98fa83c1d)

**Expected behavior**
hope fix the bug

**Version:**
 1.5.7 dokcer deploy

**Comment by TeddyCr** [comment]
@zhouhongyu888 could you let us know if this is still an issue in the latest version?
