### ISSUE TITLE
MySQL Test Connection abnormal

### ISSUE THREAD

**Issue by lookingGordo** [open-metadata/OpenMetadata#18362]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
NO

**Describe the bug**

Adding "Connection Arguments" or "Connection Options" parameter serverTimezone=UTC An error occurred

**To Reproduce**
Screenshots or steps to reproduce
![image](https://github.com/user-attachments/assets/2f75ffec-1c5b-4fa4-91ff-303e6b1cace9)

**Expected behavior**
Configure the connection after adding parameters

**Version:**
 - OS: Linux
 - Python version:
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by lookingGordo** [comment]
eg.
127.0.0.1:3306?serverTimezone=UTC&useSSL=false

**Comment by harshach** [comment]
@lookingGordo refer to the docs clearly we do not recommend adding those params . This is not JDBC connection. Ask questions in support channel at https://slack.open-metadata.org
