### ISSUE TITLE
Injection-bot automatically resets asset displayname

### ISSUE THREAD

**Issue by freetime007** [open-metadata/OpenMetadata#18384]
**Affected module**
UI and Ingestion Framework?

**Describe the bug**
The injection-bot automatically deletes the custom display name of an asset that has already been filled in and reverts it back to the default value. After this, the bot generates a new version of the asset. This behavior is causing unexpected changes to the asset's metadata and additional versioning.

**To Reproduce**

![截圖 2024-10-24 上午10 22 49](https://github.com/user-attachments/assets/fdf69fa0-c290-47b4-8ce3-29b44909f1ff)

**Expected behavior**
The bot should preserve the custom display name set by the user, and a new version should not be created unless there is a significant change to the asset.

**Version:**
 - OS: ubuntu 22.04
 - Python version: python3.9
 - OpenMetadata version: v1.4.7
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.4.7.1

**Comment by harshach** [comment]
upgrade to the latest release and try it again

**Comment by freetime007** [comment]
I reviewed the release log, and this issue has not been addressed. How can you ensure that this problem will be resolved in the upcoming update?Thank you!
