### ISSUE TITLE
Pass table type in Glue connector

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1838]
1. For regular tables pass https://github.com/open-metadata/OpenMetadata/blob/ab620e95af1472637366ead91d056ec93f8fcdb6/ingestion/src/metadata/ingestion/source/sql_source.py#L269
2. For external tables, i.e any table with location it should be "external"
3. Similarly view etc..

**Comment by ayush-shah** [comment]
fixed with #2309
