### ISSUE TITLE
Ingest API Metadata -> wsdl, openapi, odata metadata

### ISSUE THREAD

**Issue by fuzolan** [open-metadata/OpenMetadata#18409]
Not everything is stored in a database with access. Although a lot of data is available through api.
Documentation is crucial here. Although there are standards like wsdl, openapi or odata which contains a lot of meta data. 
I wonder there is no adapter for it!

**Comment by sushi30** [comment]
Hi @fuzolan. Can you provide more information? What are trying to ingest from OpenMetadata and where can we find more information about these systems?

**Comment by fuzolan** [comment]
https://swagger.io/specification/
https://www.w3schools.com/xml/xml_wsdl.asp
https://www.odata.org/blog/queryable-odata-metadata/

Metadata from most soap-services you can get with {URI}?wsdl
From odata it is often {URI}{ressource}/$metadata
And from REST-Endpoints you can get often an OPENAPI Spec file in json or yml.

It might also help to have a file ingester for these types. 

---
What i like to ingest are the data models and types and endpoint of that api.
It would also be nice to see the lineage between the database objects and API Endpoints. In most cases there are differences here. So it would be a great benefit for transparency.

**Comment by harshach** [comment]
OpenAPI connector shipped in 1.6.0.
