### ISSUE TITLE
Doris can't fetch the metadata when the table's engine is jdbc 

### ISSUE THREAD

**Issue by sunlc210** [open-metadata/OpenMetadata#18403]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
[bash_doris_metadata_ZHzAVfkj-metadata (1).log](https://github.com/user-attachments/files/17514433/bash_doris_metadata_ZHzAVfkj-metadata.1.log)

**Describe the bug**
When I connected to the doris database today, I found that I could not get the metadata information. After checking the log, I found that tabletype is not in the enum value. My library table has jdbc engin, as shown in the figure, so it cannot be obtained, which will result in all metadata not being obtained.
Similarly, I changed to mysql to connect to doris, and I can partially obtain the metadata information.
I have two requests
1 Increase the enum value of the engine to obtain all metadata
2. Make it the same as mysql, and can obtain part of the table metadata
[Uploading bash_metadata_z9MD9Bp9-metadata.log…]()

![image](https://github.com/user-attachments/assets/feefef74-149e-45db-a252-e7f0834e5af3)

![image](https://github.com/user-attachments/assets/7a4f70d1-5b55-4b7e-ab4f-3b7f72538f8e)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sunlc210** [comment]
any update ？

**Comment by harshach** [comment]
@sunlc210  Please contribute a PR , we don't have plans to address this.
