### ISSUE TITLE
Metadata Ingestion from a Postgres v10 database results in errors

### ISSUE THREAD

**Issue by mohammadalijafri** [open-metadata/OpenMetadata#18417]
**Affected module**

Database Services - Ingestion

**Describe the bug**
Running a metadata ingestion over Postgres database results in 9 errors related to creating lineage as shown in the screenshot. Error log doesn't give a specific message pinpointing a particular schema or table that is problematic and may offer some clue as to where to narrow it down.

![open-metadata-ingestion-error-2](https://github.com/user-attachments/assets/f0fab038-2c67-45a4-9fc4-b825810513ce)

```
Error creating lineage for service [Data Warehouse ALPHA] from table [<default>.pg_type]: Table entity not found: [<default>.pg_type]
Show Logs
Search

0 matches
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/lineage/sql_lineage.py", line 344, in _create_lineage_by_table_name
    raise RuntimeError(f"Table entity not found: [{table_name}]")
RuntimeError: Table entity not found: [<default>.pg_type]

```
----------------------------------------------

**To Reproduce**

Creating a metadata ingestion with the screenshot settings here

![open-metadata-ingestion-error](https://github.com/user-attachments/assets/c0ff66b0-3f3d-4881-b131-a86b4fdf6938)

After this is run, only partial success is observed

**Expected behavior**
Expecting no errors to occur.

**Version:**
 - OS:
Ubuntu 20.04.6 LTS

 - Python version: N/A - run in docker. But some content has been added using a Python SDK using Python 3.8.10 to talk to the API hosted in docker container
 - 
 - OpenMetadata version: 1.5.6

https://github.com/open-metadata/OpenMetadata/releases/download/1.5.6-release/docker-compose.yml
https://github.com/open-metadata/OpenMetadata/releases/download/1.5.6-release/docker-compose-postgres.yml

**Additional context**

**Comment by harshach** [comment]
we do not support postgres 10
