### ISSUE TITLE
Add Delta Lake Connector

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1843]
Build connector to extract metadata from DeltaLake.
This requires to run spark sql to fetch the tables information or we can use the following sqlalchemy driver
https://flynn.gg/blog/databricks-sqlalchemy-dialect/

**Comment by Taurus-Le** [comment]
@harshach Could you please kindly provide the docs of how to use this connector?
I went through the official website below, yet I did not find the related instruction.
https://docs.open-metadata.org/connectors
Thanks.
