### ISSUE TITLE
[IDEA] Don't show backtraces to the users when running metadata CLI

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1847]
### Problem
The user cannot easily translate a Python backtrace in a sequence of steps to solve it when running our CLI ```metadata```.

### Solution
Intercept the Python Exception and print the solution for the users.

### Use cases
- [x] User configures the profiler. Continue but print the command to fulfill the dependencies.
- [ ] User runs the ingestion without the dependencies. Exit and print the commands to fulfill all the dependencies.
- [ ] User runs the ingestion with a nonexisting configuration file. Exit, show the template with comments and the instruction to create the file. Alternatively, if there is TTY, open the default editor with the template of the generic configuration.
- [ ] User runs the ingestion with an incorrect configuration file. Exit and print the error.
- [ ] User runs metadata docker without docker running. To be tested.

Test this idea with #1835

**Comment by harshach** [comment]
+1 for this , but lets keep the stack traces and make them logger.debug . We may need these if we are trying to debug in a user env. we can enable debug logging by running ```metadata --debug``` and it will be helpful to have those stack traces.
