### ISSUE TITLE
Change the text about OpenMetadata in the UI

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#185]
From:
> A central place to discover and collaborate on all your data.

To:
> A single place to Discover, Collaborate, and Get your data right.

**Comment by darth-coder00** [comment]
- A single place to Discover, Collaborate, and Get your data right
- Based on Open metadata standards
- Understand your data and collaborate with your team

**Comment by Sachin-chaurasiya** [comment]
#201
