### ISSUE TITLE
Profiler BigQuery error: 'Schema pattern not allowed'

### ISSUE THREAD

**Issue by Cir02** [open-metadata/OpenMetadata#18503]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Profiler error in BigQuery connection with ADC. 

**Describe the bug**
After launch openmetadata_ingestion for metadata and lineage, both of them are okey. When launching the pipeline for profiler with `Enable Debug Log` enabled and `Schema Filter Pattern` point to only one schema, we get the error: `{'Schema pattern not allowed: Bigquery_dev_3.xxx.business_zone.xxx': 'Schema pattern not allowed'}`. Not getting the right profiler for this schema.
 
**To Reproduce**

Nomal profiler pipeline only include one schema of the database.

![image](https://github.com/user-attachments/assets/6a30e862-3fad-44e4-af2b-bc4cebe8564d)

![image](https://github.com/user-attachments/assets/41b15479-c3b5-489d-ae27-da507ebca163)

**Expected behavior**
get a full profiler of all columns and sample data

**Version:**
 - OS: Docker compose in WSL
 - Python version: 3.10.14
 - OpenMetadata version: 1.5.6
 - OpenMetadata Ingestion package version: 'docker.getcollate.io/openmetadata/ingestion:1.5.6 '

**Additional context**
all roles for bigquery connection in documentation are granted.

**Comment by ulixius9** [comment]
@Cir02 you need to disable the `Use FQN for filtering` flag, once that is done you will be able to run profiler with provided schema.

you can read the description about `Use FQN for filtering` to know more.

**Comment by Cir02** [comment]
thx!
