### ISSUE TITLE
"ALL DOMAINS" option filter in not ADMIN USERS

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#18506]
Hi,

Before version 1.5.X any user could access any domain, but after 1.5.X you have to indicate to each user which domains they can access, which is more restrictive and we can consider it a good option.
The problem comes, when a person, belongs to more than one domain that does not allow him to have a total vision since he does not have the option all domains for not being admin.
In the following example we see a non-admin user, who sees two domains and does not have the ALL DOMAINS option.

![image](https://github.com/user-attachments/assets/8280b4bc-927c-4ce7-b1c5-42f0708e9194)

Now we see how an ADMIN user has this option.
![image](https://github.com/user-attachments/assets/98e1a5e8-8ed2-4bb1-81b4-afe7f500961b)

This option is important, since a user can consult other assets from other domains, but the fact that it does not allow selecting ALL DOMAINS, means that the user has to filter domain by domain to find the asset.

thanks,
Carlos

**Comment by SimonDegeorge** [comment]
Hi,
We have the same issue at #17807

**Comment by triquinielas** [comment]
Hi @SimonDegeorge , thanks for this information.
We´ll follow the thread.
Carlos

**Comment by harshach** [comment]
closing it in favor of https://github.com/open-metadata/OpenMetadata/issues/17807
