### ISSUE TITLE
Can not add API services

### ISSUE THREAD

**Issue by zhouhongyu888** [open-metadata/OpenMetadata#18525]
**Affected module**
Service/Api Services

**Describe the bug**
I cant not click the test connection Tab
![image](https://github.com/user-attachments/assets/0ae77da8-c485-404d-af79-def0660d9d4d)

**Version:**
 1.5.10

**Comment by harshach** [comment]
@zhouhongyu888 there is connector support, use APIs

**Comment by zhouhongyu888** [comment]
> @zhouhongyu888 there is connector support, use APIs

yes , I have used the APIs，the problem still exists
![image](https://github.com/user-attachments/assets/ca1073fe-1ab6-4ea7-98d3-8c0ac6656ff1)
