### ISSUE TITLE
Request to allow bulk import of custom properties

### ISSUE THREAD

**Issue by hameedaseedat** [open-metadata/OpenMetadata#18535]
I am looking for a way to update custom properties in bulk.

Custom properties are created under Settings > Custom Properties > Glossary Term. Currently I have 4 created:
![image](https://github.com/user-attachments/assets/8aba2a08-f6c5-45b8-9c0c-09feede1334c)

These can be populated for each glossary term, either under the Custom Properties tab or in the sidebar on the Overview tab. So far, I haven’t found any way to update these in bulk:
![image](https://github.com/user-attachments/assets/bd429f7e-aacc-48ee-948e-30fe391fcde3)

![image](https://github.com/user-attachments/assets/e47cb6cc-c169-40c0-994b-f111a88c88f1)

An update that allows this would be very helpful.

Thanks

**Comment by harshach** [comment]
supported in 1.5.10
