### ISSUE TITLE
PowerBI with GCC High Environments

### ISSUE THREAD

**Issue by jmtorma** [open-metadata/OpenMetadata#18549]
**Affected module**
Ingestion

**Describe the bug**
Proper Host and Port values are not used when creating a new Power BI connection.

**To Reproduce**
Login to the Openmetadata UI
Settings --> Services --> Dashboards
Create a new service
Input a Client ID, Client Secret, Tenant ID
Auth URI: https://login.microsoftonline.us
Host and Port: https://app.high.powerbigov.us/home/
Scope: https://analysis.usgovcloudapi.net/powerbi/api/.default
Press the Test Connection button.
Connection test is successful.
Written to the logs from the web pod:

Initializing with Entra authority: https://login.microsoftonline.us/<Tenant ID>
PowerBi Access Token generated successfully
WARNING - Error fetching dashboards: 403 Client Error: Forbidden for url: https://api.powerbi.com/v1.0/myorg/admin/dashboards

**Expected behavior**
URL should not be https://api.powerbi.com/v1.0/myorg/admin/dashboards
URL should be https://app.high.powerbigov.us/home/

**Version:**
 - OS: 22.04
 - Python version:
 - OpenMetadata version: 1.5.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Azure AKS
GCC High Environment

**Comment by harshach** [comment]
Please ask this quesiton in support channel in https://slack.open-metadata.org

**Comment by elue-wrd** [comment]
The same thing happens for regular GCC, where the URL should be [https://app.powerbigov.us/home/](https://app.powerbigov.us/home/)

**Comment by harshsoni2024** [comment]
this issue is resolved under this PR: https://github.com/open-metadata/OpenMetadata/pull/24158
