### ISSUE TITLE
[Question] - Does openmetadata use openlineage standard to store lineage 

### ISSUE THREAD

**Issue by TejasRGitHub** [open-metadata/OpenMetadata#18562]
**Is some content missing, wrong or not clear?**
Hi Team, 

Can you please let me know if the lineage which is stored in openmetadata follows the open lineage standard. Is there a way one can migrate lineage data from another open lineage system to open metadata ?

**Comment by harshach** [comment]
no. We have our own standard. CHeck the json schemas
