### ISSUE TITLE
Send Notification when remove tags from table

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#18579]
**Is your feature request related to a problem? Please describe.**
Currently, after add a general metadata events notification for table, if a table was tagged, I would receive a notification, while when I remove it, I wouldn't receive the notification to tell me that a tag was removed. It's not good enough for metadata alert.

**Describe the solution you'd like**
After a tag being removed from table, I can receive notification by setting the notification configuration as below.
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/a55bb978-5fb6-4020-9a9d-a7242b69aa4d">

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
we consolidate events from same user with a session of 10mins, in consolidation we don't send change events
