### ISSUE TITLE
Request to support RS512 JWS Algorithm 

### ISSUE THREAD

**Issue by dspatil** [open-metadata/OpenMetadata#18594]
**Is your feature request related to a problem? Please describe.**
Request to support OIDC client apps who only supports `RS512 `JWS Algorithm while creating token.
Currently, as par this doc [https://docs.open-metadata.org/latest/deployment/security/oidc#preferred-jws-algorithm-preferredjwsalgorithm](https://docs.open-metadata.org/latest/deployment/security/oidc#preferred-jws-algorithm-preferredjwsalgorithm) , OM only supports the `RS256 `JWS Algorithm.
The third party OIDC login works fine when OIDC apps supports and creates tokens with `RS256 `JWS Algorithm, but OM fails to validate tokens of OIDC apps who only supports the `RS512 `algorithm.

**Describe the solution you'd like**
So, requesting you to please support `RS512 `encrypted tokens/OIDC apps as well in OM.

**Describe alternatives you've considered**
Alternative is to only use OIDC apps having `RS256 `algorithm, but in my case, due to security standards, my organization only supports the OIDC apps with `RS512 `algorithm for best security.

**Additional context**
Having this feature will give OM consumers an extra added flexibility with respect to Security standards. So, please consider this.
Thanks.

**Comment by dspatil** [comment]
Any updates team if this will be picked up for implementation?

**Comment by harshach** [comment]
https://github.com/open-metadata/OpenMetadata/pull/19049 fixed here will be part of 1.6.2

**Comment by dspatil** [comment]
That's great news team.... Thanks a lot...
