### ISSUE TITLE
[Lineage] User is not able to disclose relations in lineage 

### ISSUE THREAD

**Issue by a-chumagin** [open-metadata/OpenMetadata#18612]
**Affected module**
UI
**Describe the bug**

**To Reproduce**
Table has lineage . You can add lineage manually 
1. Open lineage page for table 
2. Collapse lineage relations (click on minus)
3. There is not ability to disclose lineage again 
Screenshots or steps to reproduce
![Monosnap screencast 2024-11-12 19-24-13](https://github.com/user-attachments/assets/51273806-592a-4b0d-a216-cae0fd64f0e7)
<img width="503" alt="image" src="https://github.com/user-attachments/assets/4b7931e3-33a9-4abd-aae5-0507d84817f7">

**Expected behavior**
User is able to disclose Lineage relations 

**Version:**
 - OpenMetadata version:  1.5.10 (1.5.7)

**Additional context**
Issue is not reproduced in 1.4.1

**Comment by TeddyCr** [comment]
@a-chumagin  closing this as fixed in 1.5.12
