### ISSUE TITLE
Not clear how to add the client secret for AzureSSO in Docker deployment.

### ISSUE THREAD

**Issue by CSanctus** [open-metadata/OpenMetadata#18680]
**Is some content missing, wrong or not clear?**
https://docs.open-metadata.org/latest/deployment/security/azure/docker

If we choose Web instead of SPA, what is the env variable to paste the Client Secret?

**Describe the solution you'd like**
I would assume that it would be found with the rest of the Azure SSO env.

**Additional context**
I registered the APP in Azure, created my client secret as per the documentation.

**Comment by jgrocha** [comment]
As far as I can see, it should be `OIDC_CLIENT_SECRET`.

For example, in `docker/docker-compose-quickstart/docker-compose.yml` you have this variable:

```yaml
      #For OIDC Authentication, when client is confidential
      ...
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:-""}
      ...
```
