### ISSUE TITLE
Advanced search doesn't take the keyword to populate aggreated Database Schema and database displayname

### ISSUE THREAD

**Issue by kimiiic** [open-metadata/OpenMetadata#18702]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

**To Reproduce**
- Login to latest version 1.5.11 sandbox by searching "fact"
https://sandbox.open-metadata.org/explore/?search=FACT&sort=_score&page=1&size=10
- Explorers shows aggregated counts from the search result perfectly, and all other dropdowns specifying the correct result. For Database and Schema, they are showing a wrong aggregated count number.

Before upgraded to 1.5.x this issue did not appear to be there.

Screenshots or steps to reproduce
![image](https://github.com/user-attachments/assets/e684cbaa-bff9-4f38-ad18-7e77432eb936)
![image](https://github.com/user-attachments/assets/797f84b5-9322-471a-b269-3e698bb7423e)

**Expected behavior**
The aggregated count for Database and Schema need to return the expected count number with the search keywords

**Version:**
 - Python version:
 - OpenMetadata version: 1.5.x
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
Fixed in 1.6
