### ISSUE TITLE
ingestion-core and ingestion can be one module

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1875]
With recent changes we have ingestion-core as another package which publishes our generated code and we have ingestion module that contains the connectors and framework to build the connectors.
It would be great to have ingestion-core and ingestion in a single module and publish different packages this makes the code organization cleaner and all things related ingestion python code base are under a single module and its clear for the community where the code resides

**Comment by harshach** [comment]
@pmbrull @amiorin if you have any ideas on this , please add it here. Not sure how to setup multi package in the same dir

**Comment by harshach** [comment]
This is actually causing an issue today. Users model has now Roles and Policies as additional fields.
However we didn't publish ingestion-core dev package after the server side changes which is breaking the ingestion integration tests as it depends on older ingestion-core package with stale models.
IMO this is unnecessarily complex we shouldn't be needing to publish ingestion-core package in pypi to make a dependency on the ingestion package. Every time we make a change to the models this requires ingestion-core package publish.

@mithmatt if you have any ideas on this please let us know.

**Comment by pmbrull** [comment]
Hi, sorry jumped to other issues and left this in the fridge.

I thought that the core package was only a tool when working through specific commits with hotfixes to help out users. In these cases, where we want to allow a full `pip install` directly from git, then it makes sense to publish the package with the latest version and add it as a dependency ONLY for the testing in a specific branch.

However, I agree that this approach makes things harder for the default development and it is unnecessary to decouple.

**Comment by harshach** [comment]
we have the direct dependency on the ingestion-core package https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/setup.py#L26

IMO ideal behavior
1. Its good to have the generated code published as its own package. It will be useful for other tools like profiler, quality etc..
2. Make this ingestion-core as another module under ingestion
3. when we publish the python package it should do openmetadata-core , openmetadata-ingestion
4. During the development we need to have same or similar experience as before which is 
 4.1 make generate will generate the code based on json schemas under ingestion dir
 4.2 development and installing locally from the source will be similar to before
@akash-jain-10

**Comment by harshach** [comment]
@pmbrull @amiorin added a PR here https://github.com/open-metadata/OpenMetadata/pull/2008
Initial goal of ingestion-core is to package generated code so that users can install using git link. This way if there is a fix we can publish to a branch and let the users test it out and give feedback. However this made dev workflow harder as described in previous comments. With ingestion-core as a separate package we always going to give hot patches against published version. This can be better achieved through the changes I made.
1. core as another plugin package which will package generated and all code into a package
2. users need to install openmetadata-ingestion[core] and hotfix branch connector

This requires 2 installation from user but it will simplify the dev process also
1. Each release will have openmetadata-ingestion[core] package published pypi
2. we can push hotfixes into a branch and ask user to install the openmetadata-ingestion[core] and followed by hot fix branch
3. Dev workflow same as before and we don't need to publish the core package to pypi every time the schema or api changes.

Let me know if there is better way to do this while providing all of the above 3. Otherwise lets merge this in and we can follow-up if we have a better option available

**Comment by amiorin** [comment]
I have never tried this solution and I cannot guarantee that it works. If the effort is not worth it, I'm fine with @harshach PR.

During *development* the CD (continuous delivery) will publish a new PyPI package every time we merge a PR that modifies the JSON files following the convention:
* 0.7.0.dev1
* 0.7.0.dev2
* 0.7.0.dev3
* and so on

The CI (continuous integration) will install `openmetadata-ingestion` and `openmetadata-ingestion-core` from the PR checkout ignoring the PyPI versions.

During *release* and in the release branch the CD will publish a package following the convention:
* 0.7.0
* 0.7.1
* 0.7.2
* and so on

The original problem:
1. If the hot-fix in Python doesn't change a JSON file we still solve the initial problem if the user uses `pip install --pre git+https...`

The new problems:
1. Developer forgets to publish *development* packages is solved by the CD.
2. CI breaks is solved by installing the Python code from the PR checkout.

Local development:
1. I don't think the developer should use `pip install --pre -e OpenMetadata/ingestion` but he should install both packages like the CD does with `pip install -e [LOCAL_DIR]`

WDYT?

**Comment by harshach** [comment]
@amiorin Sounds good to me. Except for local development approach

@akash-jain-10 can you set up the following
1. Any changes to schema and api files should trigger a openmetadata-ingestion-core package in dev release version
2. Refactor Makefile from root folder to generate the sources in ingestion-core
3. Ideally I want the ingestion-core and ingestion in same dir with different setup.py files
4. remove the Makefile from ingestion-core
5. Running make generate should generate new files also install package in local env for dev
6. release publish of packages should publish the ingestion-core package with proper versioning this should be done manually during the release
7.

**Comment by amiorin** [comment]
👍
