### ISSUE TITLE
Support Multi Team Ownership 

### ISSUE THREAD

**Issue by nqvuong1998** [open-metadata/OpenMetadata#18770]
**Is your feature request related to a problem? Please describe.**
In our use case, we have data asset which belongs to multiple domains, and our data governance framework is designed to support ownership at team level, not just specific user. So given the case, we need to have multiple teams ownership for one data asset.

**Describe the solution you'd like**
Same as Multi User Ownership behavior.

**Comment by harshach** [comment]
we support multi usre ownership. When you add multi team then there won't be any real ownership except for finger pointing.
