### ISSUE TITLE
Editing services description does not save

### ISSUE THREAD

**Issue by cphares** [open-metadata/OpenMetadata#1877]
After modifying the description of a service using PUT API and attempting to save, the original value is still displayed.

**Comment by sureshms** [comment]
@parthp2107 and @darth-coder00, is this a UI issue or a backend issue?

**Comment by sureshms** [comment]
@harshach this is because a non-emtpy description is not updated by PUT operation because we don't update description to retain user written descriptions over ingestion. Given services are not ingested, we can simply allow updating description for some of the entities.

**Comment by sureshms** [comment]
@vivekratnavel, we can pass a flag from PipelineUpdater class to the superclass EntityUpdater to allow description update in `updateDescription` method.

**Comment by harshach** [comment]
> @vivekratnavel, we can pass a flag from PipelineUpdater class to the superclass EntityUpdater to allow description update in `updateDescription` method.

@sureshms services can be created from ingestion as well . At least we are not adding description for services but a service can be derived from ingestion config such service_name and connection details and gets created using the put.

**Comment by sureshms** [comment]
@harshach, is there an easy way to distinguish the ingestion user? If that is the case, we have all the information in `EnityUpdater` to only disallow description updates during ingestion. That would be the best and easiest fix.
