### ISSUE TITLE
Possible mismatch between schema entity property and API return type

### ISSUE THREAD

**Issue by roeap** [open-metadata/OpenMetadata#1880]
When developing a client in Rust I noticed a mismatch in the generated model between expected an actual value retrieved from the API. Specifically the `updatedAt` property in the `Database` model is specified at ISO time string, but the return value is unix epoch / i64.

**Comment by sureshms** [comment]
@roeap thank you for reporting this. I have been thinking about changing current dateTime fields to unix epoch. Most tools should be able to take it and convert it to date time as necessary. Date time makes it for easy readability. However Unix epoch makes it easy for people to input the values and use the field for ordering. Cc @mithmatt who had some input on this topic. 

Based on this, we will fix this bug. Thoughts?

**Comment by harshach** [comment]
+1 for unix epoch time. We use the updatedAt field and add it to ES indexing which will enable us to order the landing page feed and sort by "lastUpdated"

**Comment by roeap** [comment]
+1 for unix epoch also from me. I believe having a consistent treatment of time across the api makes it a lot more convenient to use. The legibility factor is in my experience quite short lived since - as was mentioned - conversation is trivial in most environments.

@harshach as for contributing the rust client, I'd be happy to. There is still some work to be done, but making good progress. How would this be done? Is there a place in this org where stuff like that could land?

**Comment by harshach** [comment]
Thanks @roeap . I think we can clients dir under OpenMetadata or we could start another repo with OpenMetadata Clients. We already have a python client and can make it part of the Clients repo.

**Comment by roeap** [comment]
Sounds good, I'll need some time to get things to a state where it can be used somewhat productively, but just let me know what you think, and when that time comes I'll show you the state and we can decide if its worth moving :).

As one probably should, I am using the json schema files to generate data structs - much like in the python API. Here I have a question. While the vast majority of the files is quite consistent, there are some examples which lead to (at leat for my taste) some convoluted class names...

```py
class SetOwnershipForAGivenEntity(BaseModel):
    ...

# called `CatalogVersion` in the API
class CatalogApplicationSoftwareVersion(BaseModel):
    ...
```
Would it be in your interest if I refined some of these smaller things an commit that back to this repo? @sureshms @harshach

**Comment by harshach** [comment]
@roeap sorry didn't see your last comment. Yes please add changes necessary to avoid these kind of naming. We can merge it into main.
