### ISSUE TITLE
Regex pattern with '/' not compatible with Windows platform

### ISSUE THREAD

**Issue by Aicitel** [open-metadata/OpenMetadata#18901]
**Describe the bug**
Files in json.data directory won't be loaded due to pattern compiled with '/' , but for Windows default separator is '\\'
It would be like:
regex pattern:
 `.*json/data/%s/.*\\.json$`
actual path:
` json\data\policy\xxx.json`
They won't match and empty result return from CommonUtil.getResourcesFromDirectory which cause test failure, csv load failure and other further issues.

_Caller:  Many places use the regex, just post a sample https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java#L477_
_Callee: https://github.com/open-metadata/OpenMetadata/blob/main/common/src/main/java/org/openmetadata/common/utils/CommonUtil.java#L104_

**Version:**
 - OS: Windows 11 Enterprise - 23H2
 - OpenMetadata version: 1.5.10

**Additional context**
A fix will be drafted for this issue from my side.
Preview on commit: _https://github.com/open-metadata/OpenMetadata/commit/53212e059eab24dfe1412302177a0a3455170721_

**Comment by harshach** [comment]
we do not support windows for building
