### ISSUE TITLE
Deadlock when using "/" in Team names

### ISSUE THREAD

**Issue by christianneureiter** [open-metadata/OpenMetadata#18910]
**Affected module**
Guess backend

**Describe the bug**
Using a "/" (slash) in the name of the team leads to error and team can not be used anymore.
Issue seems to be with the URL. Example team IT/PM leads to
https://data-governance.xyz.com/settings/members/teams/IT%2FPM
Team can not be used, but can also not be deleted anymore. So, deadlock.

**To Reproduce**
Case 1)
1) Create a team with a slash in the name, eg "IT/PM"
2) Select the team
3) Error "An exception with message [HTTP 404 not found] was thrown while processing request"
![image](https://github.com/user-attachments/assets/b14b035e-ed3b-4d1a-b6f3-44f082d7295f)

Case 2)
If you select the team from somewhere else, like from the feed you do get error "You don't have access, please check with the admin to get permissions", even though it logged in as admin.
![image](https://github.com/user-attachments/assets/ef696e13-ac2c-4840-a771-2fd27fa6a466)

**Expected behavior**
Well, either check on not allowed characters when creating a team or allowing special characters, but make sure it can be used.

**Version:**
No idea, I am the user would be great to get this from the frontend. But, it is running since a view days only and as far as I know in a docker.

**Additional context**

**Comment by harshach** [comment]
@christianneureiter which version of OpenMetadata are you running

**Comment by christianneureiter** [comment]
@harshach we have installed this week only, so I do assume 1.5.12

**Comment by Ashish8689** [comment]
Duplicate issue https://github.com/open-metadata/OpenMetadata/issues/18918
