### ISSUE TITLE
Issue Integrating Dagster with OpenMetadata on Local WSL Environment

### ISSUE THREAD

**Issue by 3angour** [open-metadata/OpenMetadata#18921]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend I believe

**Describe the bug**
A clear and concise description of what the bug is : 
I'm trying to integrate Dagster as a service into OpenMetadata to fetch its metadata. Both OpenMetadata and Dagster are running locally on my WSL Ubuntu environment (on Windows 11). However, I’ve encountered an issue where testing the connection in OpenMetadata consistently fails, and I’m unable to add Dagster successfully.
**To Reproduce**

Screenshots or steps to reproduce :
-installing opnemetadata successfully on an ubuntu wsl
-installing dagster successfully on an ubuntu wsl
-The Problem:
When I test the Dagster connection in OpenMetadata using either http://localhost:3000/ or http://127.0.0.1:3000/ in the url field in openmetadata I always get the following error showed in the image below :
![image](https://github.com/user-attachments/assets/1a2daf60-7b3f-4ad6-9671-b24251ba0ad3)

However, when I run a curl request directly to the Dagster GraphQL API (http://localhost:3000/graphql) like this :

curl -X POST http://localhost:3000/graphql
-H "Content-Type: application/json"
-d '{
"query": "query PipelineRuns { repositoriesOrError { __typename ... on RepositoryConnection { nodes { id name location { id name } pipelines { id name description } } } } }"
}'

I can successfully retrieve the pipeline metadata:
Response from Dagster:

{
"data": {
"repositoriesOrError": {
"__typename": "RepositoryConnection",
"nodes": [
{
"id": "423451fde460f7f3e2271e37b7006a84d40efa4a::2efeefa6393af3b161eec7662556feb5758538a0",
"name": "deploy_docker_repository",
"location": {
"id": "example_user_code",
"name": "example_user_code"
},
"pipelines": [
{ "id": "3ba0abeb52911b8035672174f3f13a35c2b2e69e", "name": "__ASSET_JOB", "description": null },
{ "id": "b4013548ab09ca3536a591ea9cafca9a7776011b", "name": "my_job", "description": null },
{ "id": "a29265b92dfdce506d8a4a9e146a97ff0834ee34", "name": "my_step_isolated_job", "description": null }
]
}
]
}
}
}

**Expected behavior**
openmetadata should test successfully the connection

**Version:**
 - OS: Windows 11
 - Python version: 3.10
 - OpenMetadata version: 1.5.10
 - dagster version : 1.9.2
 - OpenMetadata Ingestion package version: should it be installed in this step ? i'm asking because this a service to integrate and not an ingestion tool to be used instead of airflow, because I already successfully configured bigquery (as a service) and successfully tested the omd-bq connection. (if I should install it where should i do it, within the docker of omd or the docker of dagster)?

**Additional context**

**Comment by harshach** [comment]
try host.docker.internal

**Comment by Prajwal214** [comment]
@3angour Can you confirm if the above comment from @harshach helped in solving the Issue, you can reach out in slack community for more support

**Comment by 3angour** [comment]
@harshach when I tested the connection with host.docker.internal I got the following error : 
test-connection-Dagster-63BX4dOd Failed to trigger workflow due to airflow API returned Bad Request and response {"error": "Request Validation Error parsing payload: 1 validation error for DagsterConnection\nhost\n Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='host.docker.internal', input_type=str]\n For further information visit https://errors.pydantic.dev/2.7/v/url_parsing"}

**Comment by 3angour** [comment]
@Prajwal214 can you reopen the issue please ? it is clearly not solved yet

**Comment by gregory-numenos** [comment]
The solution proposed by @harshach worked for me. 
I was running the dagster locally outside the docker and OpenMetadata using docker compose.
The dagster is queriable at http://127.0.0.1:3000/graphql endpoint locally, but inside the OpenMetadata, the connection is has to be set using `host.docker.internal`

<img width="1283" height="545" alt="Image" src="https://github.com/user-attachments/assets/4a4e99aa-f102-40e5-a9d2-7785b29c04e2" />
