### ISSUE TITLE
Error in Profiler Ingestions（MySQL 5.7）for 1.5.8 and 1.5.13

### ISSUE THREAD

**Issue by rchlz** [open-metadata/OpenMetadata#18939]
**Affected module**
Ingestion Framework

**Describe the bug**
Error log when run profiler （run metadata success）：
[2024-12-06T02:43:54.153+0000] {profiler_interface.py:319} INFO - Skipping metrics for admin_log.id due to (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '() AS row_num\n        FROM \n            manager.admin_log,\n            (SELE' at line 8")
[SQL: /* {"app": "OpenMetadata", "version": "1.5.13.0"} */
SELECT 
    (SELECT
        id
    FROM (
        SELECT
            id, 
            ROW_NUMBER() OVER () AS row_num
        FROM 
            manager.admin_log,
            (SELECT @counter := COUNT(*) FROM manager.admin_log) t_count 
        ORDER BY id
        ) temp
    WHERE temp.row_num = ROUND(0.5 * @counter)
    )
     AS median, 
    (SELECT
        id
    FROM (
        SELECT
            id, 
            ROW_NUMBER() OVER () AS row_num
        FROM 
            manager.admin_log,
            (SELECT @counter := COUNT(*) FROM manager.admin_log) t_count 
        ORDER BY id
        ) temp
    WHERE temp.row_num = ROUND(0.25 * @counter)
    )
     AS `firstQuartile`, 
    (SELECT
        id
    FROM (
        SELECT
            id, 
            ROW_NUMBER() OVER () AS row_num
        FROM 
            manager.admin_log,
            (SELECT @counter := COUNT(*) FROM manager.admin_log) t_count 
        ORDER BY id
        ) temp
    WHERE temp.row_num = ROUND(0.75 * @counter)
    )
     AS `thirdQuartile` 
FROM manager.admin_log 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)

When I copy SQL to Navicat for execution, it also reports an error
![image](https://github.com/user-attachments/assets/ab6f5358-d83e-4bb4-b369-0911b24f7453)

**To Reproduce**

![image](https://github.com/user-attachments/assets/115f3681-a3ca-42de-b56d-2206bfcd4131)

**Expected behavior**
Profiler Ingestions run successfully

**Version:**
 - OS: Ubuntu
 - Python version: Python3.10（docker）
 - OpenMetadata version: 1.5.8 or 1.5.13
 - OpenMetadata Ingestion package version: 1.5.8 or 1.5.13

**Additional context**
application database version is MySQL 5.7

**Comment by rchlz** [comment]
I found the reason: MySQL 5.7 does not have the ROW_NUMBER() function, which was introduced in MySQL 8.0. Can the MySQL in Services be compatible with older versions?

**Comment by harshach** [comment]
we do not support 5.7
