### ISSUE TITLE
Add SonarCloud

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1894]
Use https://sonarcloud.io during CI to prepare and push the analysis.

This tool will give us further information about code quality, bugs, vulnerabilities and history reports.

@amiorin @mithmatt

**Comment by harshach** [comment]
@pmbrull Thanks for this. I created the organization in SonarCloud https://sonarcloud.io/project/configuration?id=open-metadata_OpenMetadata. You should've access too. But post that I need some help on setting this up.

**Comment by pmbrull** [comment]
Yay, I can indeed access it, and the integration with git looks alright!

What we could do as follow-up steps is:
- merge the PR to see the status on the main branch (that should update the main dashboard)
- run the sonar job after the tests (we could even try to set up a project for the backend and another for the ingestion)
- iterate on the `pom` and sonar properties to pass the coverage information

But looks like main ingredients are done, so thanks a lot!

**Comment by pmbrull** [comment]
Re removing the CI sonar pipeline: It is currently working because by default the Sonar + Git integration is configured to run the analysis automatically for us. This can be OK for some time, but we will be missing all coverage related information.

A more generic and complete process would be:

Run mvn build + tests, storing junit.xml and coverage info in the agent
Configure sonar.properties pointing to those paths
Run the sonar analysis directly in the CI, which will have all the project info
Push the results to SonarCloud

**Comment by harshach** [comment]
@pmbrull I think we are running into issues where PRs coming from contributors the build is not running for some reason
let me know which way you prefer and we can add that

**Comment by pmbrull** [comment]
> @pmbrull I think we are running into issues where PRs coming from contributors the build is not running for some reason let me know which way you prefer and we can add that

Hi @harshach, is it regarding https://github.com/open-metadata/OpenMetadata/issues/1908? I can take a look. Having the token in the secrets and passing that should be enough 🤔

**Comment by mithmatt** [comment]
> > @pmbrull I think we are running into issues where PRs coming from contributors the build is not running for some reason let me know which way you prefer and we can add that
> 
> Hi @harshach, is it regarding #1908? I can take a look this afternoon. Having the token in the secrets and passing that should be enough 🤔

Sonar coverage report from mvn was failing due to authorization issues. 
#1908 has the snippet of logs I captured. 

I think the token works for some cases -- I presume it works for collaborators/members of organization but not contributors -- I haven't configured my hypothesis yet. Stopped investigating here to look into other issues earlier today.

**Comment by pmbrull** [comment]
> > > @pmbrull I think we are running into issues where PRs coming from contributors the build is not running for some reason let me know which way you prefer and we can add that
> > 
> > 
> > Hi @harshach, is it regarding #1908? I can take a look this afternoon. Having the token in the secrets and passing that should be enough 🤔
> 
> Sonar coverage report from mvn was failing due to authorization issues. #1908 has the snippet of logs I captured.
> 
> I think the token works for some cases -- I presume it works for collaborators/members of organization but not contributors -- I haven't confirmed my hypothesis yet. Stopped investigating here to look into other issues earlier today.

From my past experience with sonar, the usual security process is to have a "service account" (in this case I assume it is harsha's) creating the Token and storing it. Then, any process should be able to pick it up and run the analysis. As the auth happens with the token, it is as if everyone would be the same service account.

I cannot see the settings of the org, but we could take a look together @harshach
