### ISSUE TITLE
oracle connection query change

### ISSUE THREAD

**Issue by izzyLim** [open-metadata/OpenMetadata#18962]
**Feature**
oracle connection query change

**Describe the task**
Managed a database with multiple account schemas, but the dba_tables privilege has not been granted to many of these accounts. Is it possible to integrate OpenMetadata using a table like all_tables instead of dba_tables?

**Comment by Prajwal214** [comment]
@izzyLim Could you please reach out on the Slack support channel? We can continue discussing this issue there in the thread.
