### ISSUE TITLE
Can the icon of the tab also be changed together?

### ISSUE THREAD

**Issue by sdhzwc** [open-metadata/OpenMetadata#18997]
![image](https://github.com/user-attachments/assets/d7a13cfc-6e88-4e4d-8016-6924943022e1)

**Comment by sdhzwc** [comment]
@sonika-shah cc

**Comment by sonika-shah** [comment]
@sdhzwc can you confirm the Openmetadata version ?

**Comment by sonika-shah** [comment]
In the latest versions, the tab  logo does gets updated , requires a hard fresh in browser once (checked on browser: chrome, version: 1.6.1)

**Comment by sdhzwc** [comment]
> @sdhzwc can you confirm the Openmetadata version and your browser ?

Under the condition of clearing all caches, I tested versions 1.6.1, 1.5.14, and 1.4.8, and they all display the openmetadata icon, with the browser being Edge and Google.

**Comment by sdhzwc** [comment]
> In the latest versions, the tab logo does gets updated , requires a hard fresh in browser once (checked on browser: chrome, version: 1.6.1) <img alt="image" width="1043" src="https://private-user-images.githubusercontent.com/58761340/396375337-8e994cdf-3cd2-4b25-a8e8-b179e6a8d7c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTk1MjYsIm5iZiI6MTczNDQxOTIyNiwicGF0aCI6Ii81ODc2MTM0MC8zOTYzNzUzMzctOGU5OTRjZGYtM2NkMi00YjI1LWE4ZTgtYjE3OWU2YThkN2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZjFhYjk5M2U0YjBmNzk2MzE0NDc2Njc5YjdlMmI5MDI2MzE4MmViZjFiMTc2N2UyNDMzMDlmYmU4NDMwZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uWSl7VUTiqHrqi5ipP0-BkqdMQaL1cba8sMsrVJKcQg">

The use of your connection is displaying normally: https://developer.mozilla.org/favicon.ico

**Comment by sonika-shah** [comment]
favicon should be .ico, or .png , we support these 2 formats. Thanks

**Comment by sdhzwc** [comment]
> favicon should be .ico, or .png , we support these 2 formats. Thanks
PNG seems not to work well
![image](https://github.com/user-attachments/assets/c57e141f-bab3-4ab6-851b-dc5b0f8b6efd)

**Comment by sdhzwc** [comment]
@sonika-shah  @Sachin-chaurasiya  Alright, thank you for answering, my questions have been answered
