### ISSUE TITLE
docker for open metadata is failing

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#191]
"migrate" option failed : org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://localhost/openmetadata_db?useSSL=false&serverTimezone=UTC) for user 'openmetadata_user': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000004014ec3200, pid=36, tid=69
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.12+7) (build 11.0.12+7)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.12+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# J 3 c1 java.lang.Object.<init>()V java.base (1 bytes) @ 0x0000004014ec3200 [0x0000004014ec31c0+0x0000000000000040]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /openmetadata-0.3.0-SNAPSHOT/hs_err_pid36.log
Compiled method (c1)     819    3       3       java.lang.Object::<init> (1 bytes)
 total in heap  [0x0000004014ec3010,0x0000004014ec3328] = 792
 relocation     [0x0000004014ec3188,0x0000004014ec31b0] = 40
 main code      [0x0000004014ec31c0,0x0000004014ec32a0] = 224
 stub code      [0x0000004014ec32a0,0x0000004014ec32d0] = 48
 metadata       [0x0000004014ec32d0,0x0000004014ec32e0] = 16
 scopes data    [0x0000004014ec32e0,0x0000004014ec32f0] = 16
 scopes pcs     [0x0000004014ec32f0,0x0000004014ec3320] = 48
 dependencies   [0x0000004014ec3320,0x0000004014ec3328] = 8
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
qemu: uncaught target signal 6 (Aborted) - core dumped
./openmetadata-start.sh: line 20:    36 Aborted                 ./bin/openmetadata-server-start.sh conf/openmetadata.yaml
Using Configuration file: ./bootstrap/../conf/openmetadata.yaml
url jdbc:mysql://localhost/openmetadata_db?useSSL=false&serverTimezone=UTC, user openmetadata_user, password openmetadata_password, scriptRoot ./bootstrap/sql, validateOnMigrate true00:11:34.428 [main] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:db/callback' ...
00:11:34.437 [main] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Determining location urls for classpath:db/callback using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27 ...
00:11:34.444 [main] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Unable to resolve location classpath:db/callback.
00:11:34.467 [main] DEBUG org.flywaydb.core.internal.util.FeatureDetector - AWS SDK available: false
00:11:34.468 [main] DEBUG org.flywaydb.core.internal.util.FeatureDetector - Google Cloud Storage available: false
00:11:34.468 [main] DEBUG org.flywaydb.core.internal.scanner.filesystem.FileSystemScanner - Scanning for filesystem resources at './bootstrap/sql/mysql'
00:11:34.469 [main] DEBUG org.flywaydb.core.internal.scanner.filesystem.FileSystemScanner - Scanning for resources in path: ./bootstrap/sql/mysql (./bootstrap/sql/mysql)
00:11:34.473 [main] DEBUG org.flywaydb.core.internal.scanner.filesystem.FileSystemScanner - Found filesystem resource: ./bootstrap/sql/mysql/v001__create_db_connection_info.sql
"migrate" option failed : org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://localhost/openmetadata_db?useSSL=false&serverTimezone=UTC) for user 'openmetadata_user': Public Key Retrieval is not allowed
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Public Key Retrieval is not allowed

**Comment by ayush-shah** [comment]
The fix is pushed
Resolved #200
