### ISSUE TITLE
Currently, only MySQL 8.0 and above are supported, and MySQL 5.7. * version is not currently supported

### ISSUE THREAD

**Issue by zhaizhenhua** [open-metadata/OpenMetadata#19182]
Due to historical reasons, the production environment is still using MSYQL 5.7. * version on a large scale, and upgrading to 8. * version carries certain risks. So I hope to support both versions of MySQL. Many enterprises are still using the old version. I hope this compatibility can be supported in versions 1.6.2 and later.

**Comment by harshach** [comment]
@zhaizhenhua we use json functions in mysql and they are not supported in 5.x , we won't be able to support 5.x for these reasons.

**Comment by zhaizhenhua** [comment]
> @zhaizhenhua we use json functions in mysql and they are not supported in 5.x , we won't be able to support 5.x for these reasons.

Thank you for your response. We will consider other options to see how we can resolve this issue at the application level.

**Comment by zhaizhenhua** [comment]
> > @zhaizhenhua we use json functions in mysql and they are not supported in 5.x , we won't be able to support 5.x for these reasons.
> 
> Thank you for your response. We will consider other options to see how we can resolve this issue at the application level.

@harshach
