### ISSUE TITLE
Ingestion is not getting created in UI

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#1933]
`{
"code": 400,
"message": "Cannot deserialize value of type `java.util.ArrayList<java.lang.String>` from Object value (token `JsonToken.START_OBJECT`)\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 90] (through reference chain: org.openmetadata.catalog.api.operations.workflows.CreateIngestion[\"connectorConfig\"]->org.openmetadata.catalog.operations.workflows.ConnectorConfig[\"excludeFilterPattern\"])"
}`

Getting this as the response while creating ingestion.

**Comment by ayush-shah** [comment]
Changes on filter pattern in ingestion side to table filter pattern and schema filter pattern might be the case
cc: @harshach

**Comment by darth-coder00** [comment]
Closing as APIs have changed
