### ISSUE TITLE
Pipeline tasks description is not getting updated.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#1941]
We are using PATCH API to update the pipeline tasks description. on request, we are getting a successful `200` response but on refresh getting the same description as the previous.

**Comment by sureshms** [comment]
What APIs are you using?

**Comment by Sachin-chaurasiya** [comment]
> What APIs are you using?

We are using `Patch` API.

**Comment by harshach** [comment]
Tested this in latest main. Closing this as done.
