### ISSUE TITLE
URL changes not being recorded in change-description for Dashboards and Pipelines

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#1959]
Steps:

1.  Change pipelineUrl or dashboardUrl for Pipeline or Dashboard respectively from the openmetadata_db database.
2.  Now go to details page of that particular Pipeline or Dashboard and check the Network for api response.
3.  Newly set value for pipelineUrl or dashboardUrl is present but there is no corresponding `changeDescription` available.

A `changeDescription` should be recorded for above changes.

**Comment by harshach** [comment]
@darth-coder00 URL changes shouldn't be happening once it created from the source systems itself hence we are not capturing the change.
