### ISSUE TITLE
Add support for entity deletion lifecycle

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1960]
### Entity deletion lifecycle
Entities have a lot of user-generated metadata, such as descriptions, tags, ownership, tiering. Entities also have rich metadata generated by OpenMetadata, such as data profiler, usage data, lineage, test results, and other graph relationships with other entities. When an entity is deleted, all of this rich information is lost, and recreating them is impossible. 

Let's look at requirements related to deletion:

- **User and Teams**: These entities are referenced in Version History, Activity Feeds, and many other user activity metadata. Some of this metadata can remain in the system for a long time. To preserve this, OpenMetadata will only mark the `users` and `teams` as only deleted. **These entities can't be deleted unless they have no relationship to the references mentioned above to allow hard-deleting invalid entities created accidentally.**
- **Services and other Data asset containers**: A service **contains** many data assets. Some data assets, such as Database **contains** tables. Such container entities can't be deleted until all their contained assets are also deleted. Any attempt to delete such entities when they contain other entities will fail with a `400 Bad Request` with failure reason as `<Entity> is not empty`. A new query param is added to `DELETE` operations, called `recursive`, which can be set to `true` to delete an entity and all the children entity it **contains**.
- **Accidental deletion**: If the entity was accidentally deleted (during ingestion or by a user), a user must be able to restore the entities from a soft-deleted state. A PUT operation issued against the entity will restore it back (and recursively for container entities).
- **Entities deleted for a short time but are added back**:  Entities were deleted and but restored on the metadata source side. For example, a table in the data warehouse was deleted for a short period of time and was recreated. In this case, ideally, based on ensuring it is indeed the same table, the metadata from the soft-deleted table should be carried forward to the new table.
- **New entity uses the same name as soft-deleted entity** -  Entities were deleted for the right reason. Now entities with the same names are created and are not the same as the entity that is in a soft-deleted state. In this case, supporting the `hard-deletion` of the entity is necessary to make space for entities that are being created newly.
- **Cleanup of soft-deleted entities** - Entities that are soft-deleted after some configured time are permanently deleted.

### Soft-delete mechansim
1. During the `soft `deletion of an entity, the `deleted` attribute is marked as true. 
2. All the relationships of an entity with other entities are also marked as `deleted`. 
3. These entities are no longer available in search results, and the UI.
4. APIs to get/list entities no longer return deleted entities. Specific query param `include` (see section below) must be passed to get deleted entities.

### API changes
1. DELELTE operations support a new query param `deletionType`. By default the value is `soft`. Other values are `soft-recursive` for recursive deletion and `hard` for hard-deletion of an entity. Note that the option `hard-recursive` is not supported to prevent such accidental deletion resulting in loss of metadata.
2. GET operation to get an entity by ID, entity by name, and list an entity will include a new query param `include` to which values `all`, `deleted`, `not-deleted` (default value) can be passed.
3. PUT operation on the entity will restore the entity back to normal state from soft-deleted stage.
4. PATCH operations to update the soft-deleted entity is rejected with `404 Not Found` response.

### Task breakdown:
- #1961
- #1962 
- #1963 
- #1964 
- #1965 
- #1977 
- #2036 
- #5
- #421
- #921
- #1994 
- #2165 
- #3091

**Comment by harshach** [comment]
@sureshms This looks great. One thing, we should allow retrieval entities through APIs, pass a field as "deleted" we should show the deleted entities or include the deleted entities in listing or via get apis. Otherwise they will be completely missed by any means of access
1. Daemon thread with permanent deletion, IMO we should hold off on this at least for few releases before we introduce it. I feel like any data collected around a entity with same will be applicable in the future if the entity gets restored or created again. At least gives some context

**Comment by sureshms** [comment]
All good ideas. I will update the write up.

**Comment by rubenssoto** [comment]
Its a very good definition, I have only one point related to Teams, for example, I was exploring Openmetadata and I created one team only for test, there is no way to delete this team.

I think, make sense allow delete a team if there isn't relation with other entitys.

**Comment by sureshms** [comment]
> Its a very good definition, I have only one point related to Teams, for example, I was exploring Openmetadata and I created one team only for test, there is no way to delete this team.
> 
> I think, make sense allow to delete a team if there isn't relation with other entitys.

Thank you @rubenssoto. Updated the description above to address this.
