### ISSUE TITLE
Services shifted left to the screen end - UI

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#1972]
![image](https://user-images.githubusercontent.com/40225091/147741376-ce02d67d-69e8-4511-a27a-3217425f24a1.png)
URL: http://localhost:8585/services

**Comment by sureshms** [comment]
@ayush-shah, what is the problem here? Can you describe it a bit more?

**Comment by ayush-shah** [comment]
The box for local-hive service, has shifted to the extreme left, touching the end of the screen.
As Discussed with @darth-coder00 , it was a valid UI bug and a minor change

**Comment by ayush-shah** [comment]
@darth-coder00, is this issue resolved?

**Comment by darth-coder00** [comment]
Resolved in #2011
