### ISSUE TITLE
Ingestion SonarCloud

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1976]
Followup to https://github.com/open-metadata/OpenMetadata/issues/1894

Hi, @harshach, could you please prepare a new project in SonarCloud under OpenMetadata org named `OpenMetadata-Ingestion` (or similar 🤷 ) to set up the Sonar Analysis during the Python CI?

Please, save as well the token in the repo settings and share the key name 🙏 

We can then prepare a make recipe that runs the analysis using Docker (as we do not have any plugin as with mvn) and we'll pick up the coverage and paths in a similar fashion.

Let me know if that would work for you.

Thanks!!

**Comment by harshach** [comment]
@pmbrull it will be the same repository right, given the ingestion is in the same code?

**Comment by harshach** [comment]
@pmbrull added another project and the key name is INGESTION_SONAR_SECRET

**Comment by pmbrull** [comment]
Perfect, thanks @harshach. Yeah, the origin will be the same repo but we'll publish on a different sonar project to handle issues separately. Thanks!

**Comment by pmbrull** [comment]
Parking this until we have a fix for https://github.com/open-metadata/OpenMetadata/issues/1992, as `ometa` integration tests are failing

**Comment by pmbrull** [comment]
Hi @harshach, could you please update the configuration of https://sonarcloud.io/summary/overall?id=openmetadata-ingestion and set `main` as the main branch? it is expecting an analysis to `master` instead. Thanks 🙏

**Comment by pmbrull** [comment]
both catalog and ingestion sc working correctly with PR target
