### ISSUE TITLE
Remove public modifier for test methods in all the JUNIT tests

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1979]
OpenMetadata uses Junit5. Public modifier required for test methods in Junit4 is no longer required as per https://sonarcloud.io/organizations/open-metadata/rules?open=java%3AS5786&rule_key=java%3AS5786.

**Comment by Narcasserun** [comment]
@sureshms  I'd love to take this one if it is good w/ you.

**Comment by sureshms** [comment]
Thank you @Narcasserun for volunteering! Assigned it to you.
