### ISSUE TITLE
Fix errors flagged by sonarcloud - define a constant instead of duplicating string literal

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1982]
See details of such error:
https://sonarcloud.io/project/issues?id=open-metadata_OpenMetadata&resolved=false&rules=java%3AS1192&severities=CRITICAL

**Comment by truemanD** [comment]
Hi,
I'd like to take that.

**Comment by sureshms** [comment]
@truemanD here are other issues, if you want to address - https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1192&id=open-metadata_OpenMetadata
