### ISSUE TITLE
Format specifiers should be used instead of string concatenation.

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1983]
Errors flagged by sonarcloud:
https://sonarcloud.io/project/issues?id=open-metadata_OpenMetadata&resolved=false&rules=java%3AS3457&severities=MAJOR

**Comment by MustaphaGHA** [comment]
Hi 
I would like to take this issue , I believe its a quick win 
Regards

**Comment by sureshms** [comment]
@MustaphaGHA, thank you for volunteering 🙏🏼. Assigned the issue to you.

**Comment by MustaphaGHA** [comment]
@sureshms  Glad to help
