### ISSUE TITLE
Change Thread.sleep based test implementation with Awaitality

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1987]
Here are the tests that have Thread.sleep as reported by sonarcloud:
https://sonarcloud.io/project/issues?id=open-metadata_OpenMetadata&resolved=false&rules=java%3AS2925&severities=MAJOR

Link to awaitality - https://github.com/awaitility/awaitility

**Comment by hendrysuwanda** [comment]
Hi @sureshms can I take this issue?

**Comment by sureshms** [comment]
@hendrysuwanda assigned the issue to you. Thank you!

**Comment by sureshms** [comment]
@ssandy83 assigned the issue to you. Thank you for volunteering.

**Comment by ssandy83** [comment]
@sureshms Created a PR for this
https://github.com/open-metadata/OpenMetadata/pull/8305
