### ISSUE TITLE
409 - Delete + PUT

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1992]
If we create an Entity (PUT), delete and then try to PUT the same Entity, we get back a 409 error `'{"code":409,"message":"Entity already exists"}'`.

Steps to reproduce:

```python
import requests

create_model = {"name": "random", "algorithm": "algo"}

requests.put("http://localhost:8585/api/v1/mlmodels", json=create_model)
requests.delete("http://localhost:8585/api/v1/mlmodels/<ID>")
requests.put("http://localhost:8585/api/v1/mlmodels", json=create_model)
```

We can also reproduce this in the `ometa` integration tests.

Thanks!

@harshach

**Comment by pmbrull** [comment]
It might have something to do with the soft delete flag we just added 🤔

**Comment by pmbrull** [comment]
I would expect that delete + PUT would just remove the delete flag and update the fields as necessary. Taking a look now, please let me know if I am not approaching this as expected!

**Comment by sureshms** [comment]
@pmbrull  and @harshach, we need a bit more discussion on what the right behavior is based on the use cases we want to support. From earlier behavior where entities were permanently deleted, now we support soft-deletes. Post soft-delete, few things may be necessary:
1. **Accidental Deletion** - Entities were deleted in error. In which case we can provide a functionality to **restore** those entities.
2. **Entities deleted for a short time but are added back** - Entities were deleted and but restored on the metadata source side. For example, a table in the data warehouse was deleted for a short period of time and was recreated. In this case, ideally, based on ensuring it is indeed the same table, the metadata from the soft-deleted table should be carried forward to the new table.
3. **New entity uses the same name as old entities** -  Entities were deleted for the right reason. Now entities with the same names are created and are not the same as the entity that is in a soft-deleted state. In this case, supporting the `hard-deletion` of the entity is necessary to make space for entities that are being created newly.
4. **Cleanup of soft-deleted entities** - Entities that are soft-deleted after some configured time are permanently deleted.

Based on my experience,  case 3 should be a rare occurrence. Other cases are going to be more prevalent.

That leaves us with the following options:
1. Support query param based option for DELETE operation - `delete=soft` (current default option), `delete=recursive-soft` and `delete=hard` (recursive delete not supported). When an entity is created on error or as in case 3, when entity needs to be deleted to make space for newer entities with the same name, the option `delete=hard` can be used. User need to exercise the caution if they are using APIs directly to delete entities. OpenMetadata UI can throw appropriate splash screen to confirm permanent deletion.
2. When an entity is in soft-deleted state, we need a way to restore the entity. There are several options here - PUT with delete=false, can recursively restore the entity and it's children. Or we can provide a separate restore API. When restoring, I am not sure if we need to perform major version bump. Let's discuss this a bit more.
3. When an entity is in soft-deleted state, ingestion might find an entity with the same name (see case 2 above). In this case, we can build login in ingestion bot to handle it appropriately. That is it can restore the entity and then update it.

Thoughts?

**Comment by pmbrull** [comment]
@sureshms thanks for jumping into the discussion.

I think that the presented scenarios are really well planned, so big +1 in there. Completely agree that `soft` delete is a great feature and will really help in not losing Entity history.

I do like as well the DELETE params, as we are covering all the scenarios.

In terms of recovery, having it via the usual PUT I believe can be the simplest approach. We do not even need to pass the `delete=false`, both because currently, the API JsonSchemas do not have it as a property and by definition, we are trying to create a new feature. IMO adding the "check if the entity was deleted and recover it" could be part of the usual `PUT` (not `POST`, the same way that `PUT` allows updated and `POST` does not).

I am not seeing now what we could win by having a specific `restore` operation that needs to be handled by bots.

Regarding the version bump, that was a jump into the pool following the thought of "let's notify this". However, we could treat a soft delete as part of the usual Entity lifecycle with a minor instead.

WDYT?

**Comment by sureshms** [comment]
@pmbrull, that makes sense. I am updating the description in #1960. Please take a look at the issue.

**Comment by pmbrull** [comment]
Thanks @sureshms, great summary. I'll go on with the PR then with a couple modifications:
- change to minor version instead of major
- recursively restore children from container entities (HAS)
Please, let me know if there's anything else to consider!
Thanks!
