### ISSUE TITLE
Java line length 100 instead of 120

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2013]
Using a custom line length with google-java-format brings some challenges. It's a feature available only in the mvn plugin and the creators of google-java-format have shared that they [will not accept it](https://github.com/google/google-java-format/pull/57).

That means that the other tools like the official Intellij plugin for google-java-format will never support it.

My advice is to not use this feature in the mvn plugin so that users like me can format the code in Intellij directly. This will require a new PR where we change the line length to 100 and reformat all the Java files with the burden for the open PR to apply the formatter before rebasing.

WDYT?

@sureshms @harshach @mithmatt

**Comment by sureshms** [comment]
@amiorin, we have spent a considerable amount of energy on this already.

Currently, all you need to do is just code without worrying about formatting in your IDE. Run `mvn clean install` to test your code, the code automatically gets formatted and your IDE picks up the new formatted code. This gives a new level of freedom of not having to worry about formatting the code while coding. Formatter formats the code when you build and run tests.

FYI, last time we messed with this behavior, many of us had to do a large number of code merges, for the following reason:
1. I create a PR. Before PR is merged, the pre-commit hook formats the code in PR.
2. Meanwhile, the branch I created PR from, I continue to work and create another PR.
3. The code I have and the code in the main branch have considerably changed and now I need to merge a large number of changes.

I understand that you want to format the code in Intellij directly. But `mvn clean install` does that for you anyway. Can we please just stick to the current process?

**Comment by amiorin** [comment]
We decided to stick to 120.
