### ISSUE TITLE
Use lombok Slf4j annotation to initialize logger

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2037]
In a lot of classes we use LoggerFactory to initialize logger
```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DefaultAuthorizer implements Authorizer {
  private static final Logger LOG = LoggerFactory.getLogger(DefaultAuthorizer.class);
```

This could be simplified to the following, with no need to initialize logger using LoggerFactory
```
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class DefaultAuthorizer implements Authorizer {

   // log.info("hello world")
```

By default the logger object is called `log` 
It is possible to have a custom logger object `LOG`. Check `lombok.log.fieldName`

Reference: https://www.projectlombok.org/features/log

**Comment by Shreshtha13** [comment]
Hi! I would like to work on this issue.

**Comment by sureshms** [comment]
@Shreshtha13, assigned this issue to you. Thank you for volunteering!!! 🙏.
