### ISSUE TITLE
Tags drop-down menu is getting overlapped by another elements.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2044]
Steps to reproduce:
1. Add multiple tags to a table column.
2. Try to select the topmost tag from the drop-down, it will be overlapped by the above elements. 

<img width="321" alt="Screenshot 2022-01-05 at 2 34 24 PM" src="https://user-images.githubusercontent.com/83201188/148191647-09226227-e499-4a10-8019-f6ab2881133f.png">

https://user-images.githubusercontent.com/83201188/148192380-ffbecd43-8cd4-4fc9-80c3-0ae61605b66a.mov

**Comment by parthp2107** [comment]
Found other similar behavior:

https://user-images.githubusercontent.com/83201188/148200856-2a92cbb7-3aa9-4c18-8304-7134f314f339.mov

**Comment by ShaileshParmar11** [comment]
assign to me

**Comment by parthp2107** [comment]
It is not resolved on tags page, reopening the issue
