### ISSUE TITLE
Tags dropdown menu is getting cut out while selecting tags for chart table in Dashboard details page

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#2047]
![Screenshot from 2022-01-05 18-41-19](https://user-images.githubusercontent.com/67048554/148223126-41f7d432-29a7-4670-808b-aa3a7056a15a.png)

**Comment by ShaileshParmar11** [comment]
assign to me

**Comment by Sachin-chaurasiya** [comment]
Duplicate of #2044
