### ISSUE TITLE
Add support to recover soft-deleted children of a container

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2057]
Check `accidental deletion` on https://github.com/open-metadata/OpenMetadata/issues/1960

If the entity was accidentally deleted (during ingestion or by a user), a user must be able to restore the entities from a soft-deleted state. A PUT operation issued against the entity will restore it back (and recursively for container entities).

**Comment by harshach** [comment]
@chirag-madlani this is done right. closing it.
