### ISSUE TITLE
No character display limit for column description

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2067]
There should be a minimum set of characters to display. For the rest of the content, there should be 'show more' or other similar pointers. cc @shahsank3t @harshach 

https://user-images.githubusercontent.com/83201188/148343076-88f465ee-f40f-4881-87b2-d55e75edac16.mov

**Comment by mithmatt** [comment]
Can the row be expanded like an accordion when one clicks show more?

I wonder if this works for showing more details such as the Data Quality results for columns
