### ISSUE TITLE
Not all tag filters are displayed

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2069]
Steps to reproduce:
1. Added different tags to the entity (more than 10)
2. Verify if all the tags are available in the filter
3. In the below screenshot, `User.Politics` and `User.SSN` are not in the tags filter.
<img width="1149" alt="Screenshot 2022-01-06 at 2 36 47 PM" src="https://user-images.githubusercontent.com/83201188/148358151-7283d133-af8a-48a9-a274-b1fb46a8ba4d.png">

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya I can reproduce this and search is returning that tag in aggregations. It looks like we only take 10 tags? also make sure you are sorting the tags in the order of aggregation count and showing the top 10

**Comment by darth-coder00** [comment]
@harshach I tried reproducing it, we have added 12 different tags to `raw_product_catalog`, but only 10 of them are visible in aggregations under Network tab. `User.IPAddress` and `User.MedicalRecords` are missing.

We can show all the tags if we can get it in aggregations.

**Comment by harshach** [comment]
Looks like if we add lot of tags we get a server side error
![image](https://user-images.githubusercontent.com/38649/152418830-1299de4e-62e4-4dc4-b303-3e554ac98c32.png)
