### ISSUE TITLE
Move delete + put tests to EntityResourceTest

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2074]
Iteration on top of https://github.com/open-metadata/OpenMetadata/pull/1993.

This first PR fixed the delete API allowing to PUT back entities. Now we are going to organise the tests better inside `EntityResourceTest`.

**Comment by pmbrull** [comment]
Hi @mithmatt @sureshms, when moving the tests to `EntityResourceTest` I am getting some errors for a few Entities:

```
[ERROR] Failures: 
[ERROR]   WebhookResourceTest>EntityResourceTest.delete_put_Entity_200:800->EntityResourceTest.updateAndCheckEntity:932->EntityResourceTest.updateEntity:878 expected: <200> but was: <201>
[ERROR] Errors: 
[ERROR]   RoleResourceTest>EntityResourceTest.delete_put_Entity_200:800->EntityResourceTest.updateAndCheckEntity:932->EntityResourceTest.updateEntity:878 » HttpResponse
[ERROR]   TeamResourceTest>EntityResourceTest.delete_put_Entity_200:800->EntityResourceTest.updateAndCheckEntity:932->EntityResourceTest.updateEntity:878 » HttpResponse
[ERROR]   UserResourceTest>EntityResourceTest.delete_put_Entity_200:800->EntityResourceTest.updateAndCheckEntity:932->EntityResourceTest.updateEntity:878 » HttpResponse
```

The errors messages:
- Role: `Role attribute deleted can't be modified`,
- Team: `Team attribute deleted can't be modified`
- User: `User attribute deactivated can't be modified`.

Are those something we want to look into and have the same behavior for all Entities?

Thanks

**Comment by sureshms** [comment]
@pmbrull, let's commit this change first and move the code to the common base later.

**Comment by pmbrull** [comment]
> @pmbrull, let's commit this change first and move the code to the common base later.

Yep the PR https://github.com/open-metadata/OpenMetadata/pull/1993 is already merged 🚀
