### ISSUE TITLE
Python code in branch main is always formatted correctly.

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2091]
That is equivalent to saying PRs cannot be merged if the Python code is not formatted correctly.
We have enabled `pre-commit` again and running `pre-commit run --all-files` on main modifies a couple of Python files.
#
![image](https://user-images.githubusercontent.com/32617/148484152-8db6c750-a712-469c-b710-34344b6678f5.png)

**Comment by pmbrull** [comment]
Hi @amiorin, I saw you did a reformat round for this. Are you also working on preparing the CI or shall I pick this up? Thanks!

**Comment by amiorin** [comment]
No plan to work on this, you can pick it up. Let me know if you need a review.
