### ISSUE TITLE
Pipeline entity tasks are not inserted. Only update.

### ISSUE THREAD

**Issue by shaunBucketplace** [open-metadata/OpenMetadata#2092]
There are multiple tasks in the airflow pipeline. However, only the last task is recorded in pipeline_entity.
So, in the task details of the pipeline service, only the last task information display.

It seems to be because it updates the pipeline entity. ([code](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/airflow_provider_openmetadata/lineage/openmetadata.py#L210))

**Comment by harshach** [comment]
@pmbrull this must have been handled already. Please close the issue if it is
