### ISSUE TITLE
No data displayed on Teams page

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#2094]
If there are special characters added to Team name while creating a team, upon selecting user is navigated to a blank page
![Screenshot from 2022-01-07 10-50-32](https://user-images.githubusercontent.com/67048554/148495899-8b864c04-2e07-48f5-a45f-9884f75fa8c2.png)
![Screenshot from 2022-01-07 10-50-58](https://user-images.githubusercontent.com/67048554/148495911-caf43ad1-013f-4952-8455-3336cee53ae4.png)

**Comment by shahsank3t** [comment]
@harshach @sureshms 
Should we allow special characters to be part of name? Not only for teams, but for entities, services, etc.
If we should allow, should we determine which characters are allowed & prohibited?

cc: @darth-coder00 @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
Fixed by #3315
