### ISSUE TITLE
Error 404 response code upon hitting https://sandbox.open-metadata.org/my-data

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#2100]
This is a production issue
Steps to reproduce:
1. Navigate to https://sandbox.open-metadata.org/my-data
2. Open Network tab and hit refresh
3. Check Response code after refresh for myData page
![Screenshot from 2022-01-07 13-31-44](https://user-images.githubusercontent.com/67048554/148511700-853040c5-48ce-452e-8a7f-301e70bf0312.png)
Same issue exists on http://localhost:8585/

**Comment by sureshms** [comment]
Very old issue no longer relevant.
