### ISSUE TITLE
Markdown #[type].[id] syntax and in-editor helper

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2110]
The in-editor Github `#` completion is a time saver and we should have it in OpenMetadata for entity linkage in the markdown content.
#
Example of Github `#` helper where I have typed `host_port`
![image](https://user-images.githubusercontent.com/32617/148627317-ee30735f-bf5b-4cb4-bcf0-d95dfe48d4f6.png)

Tasks

- [ ] Define the syntax for `#`. For example `#table.E0B9C311-4026-40FC-9547-9BD4EE6DE80`
- [ ] Implement the rendering in the markdown textarea of the UI
- [ ] Implement the helper in the UI when the user types `#`

**Comment by vivekratnavel** [comment]
Closing the issue since "#mentions" is already supported in the activity feeds.
