### ISSUE TITLE
Add OMeta tests for services

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2113]
Use as an example any `test_ometa_<entity>_api` to create tests for the Entity Services:
- DatabaseService
- DashboardService
- MessagingService
- PipelineService

**Comment by Beetelbrox** [comment]
Hallo! I'd like to take this one, if it's OK for you. Thanks!

**Comment by pmbrull** [comment]
Sure thing! Thanks @Beetelbrox for the help 🚀

**Comment by pmbrull** [comment]
Hi @Beetelbrox! Hope you are doing ok :) Let me know if there are any questions regarding this, happy to help.

Thanks!

**Comment by Beetelbrox** [comment]
Hai @pmbrull! I'm fine thanks, I hope you're too! I indeed wanted to tackle the services in separate PRs to get faster feedback, shall I address them to this same issue or do we need separate issues as you mentioned? thanks!

**Comment by pmbrull** [comment]
Feel free to start with whichever you want and we can create them on the fly :)

**Comment by pmbrull** [comment]
Thanks for tackling this @Beetelbrox. I just opened other issues to follow on the rest of the testing:
- https://github.com/open-metadata/OpenMetadata/issues/3187
- https://github.com/open-metadata/OpenMetadata/issues/3188
- https://github.com/open-metadata/OpenMetadata/issues/3189

**Comment by pmbrull** [comment]
Closed with https://github.com/open-metadata/OpenMetadata/pull/3185
