### ISSUE TITLE
[BigQuery] Support default service account in BigQuery data ingestion

### ISSUE THREAD

**Issue by lihan** [open-metadata/OpenMetadata#2130]
Username and password does not work for our production environment. It's not practical to use any individual's password and all our accounts have 2FA enabled.

Generally we use service account, in particular, [Application Default Credentials](https://cloud.google.com/bigquery/docs/authentication/getting-started) instead of service account key file.

This application default credential is keyless, there is no file to upload or saved, works in both local and production environment.

See [Introduction to authentication](https://cloud.google.com/bigquery/docs/authentication) for more details.

![image](https://user-images.githubusercontent.com/655051/148735180-5f15e599-8ce1-4fcc-a894-9052d29e3c3e.png)

**Comment by ayush-shah** [comment]
fixed Ingestion with #2160

**Comment by akash-jain-10** [comment]
Closing this Issue.
