### ISSUE TITLE
Reset database filter when service type is selected

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2140]
1. When no filter is selected and explore page is loaded. We show all databases available 
![image](https://user-images.githubusercontent.com/38649/148851193-1e86d84c-a930-41ca-a73f-64bc3f723ca1.png)
2.When user selects lets say "MySQL" service type

![image](https://user-images.githubusercontent.com/38649/148851274-170d0ac8-fb75-471d-938c-24364a1b6b8c.png)

we still show databases of all the service types except that we show entities as zero. However user who wants to look at all the databases inside a service this UX falls little bit short. It would be good if we only show the databases that belongs to the service not all the services.
We had this approach for tags and tiers which makes sense, for example Tier4 is not available in "MySQL" but in "BIGQuery" , in this case we want to show Tier4, as in future there can be Tier4 datasets and users themselves would like to see there are no Tier4 datasets
Where as applying this logic databases is not right as the users don't think a database named "orders" which exists in bigquery will be in "mysql" so ideally they want to look at all databases inside a service via filter selection

**Comment by darth-coder00** [comment]
Closing as this kind of filter behaviour can't be consistent for different filter combinations
