### ISSUE TITLE
Add support for Presto

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#215]
We already have support for Athena. Let's add support for Presto.

**Comment by sureshms** [comment]
Duplicate of #213

**Comment by sureshms** [comment]
@rohanpednekar Added support for presto connector. Please follow the [docs here](https://docs.open-metadata.org/install/metadata-ingestion/connectors/presto). Appreciate it if you can try it out and give us any feedback. Thanks.

**Comment by rohanpednekar** [comment]
Thanks for your contribution. Let me test and get back to you guys with any feedback.
