### ISSUE TITLE
search bar is not taking numbers and special character into consideration.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2152]
https://user-images.githubusercontent.com/83201188/148945394-a0e894a7-29b9-454b-9d37-c712ddfc7ed3.mov

**Comment by parthp2107** [comment]
Also happening with search bar in details page

https://user-images.githubusercontent.com/83201188/148945894-9557440b-9c7a-40a2-a439-dcb64128bfcb.mov

**Comment by darth-coder00** [comment]
In case of top search bar, those are 2 different apis, suggestion and search api, 
Suggestions api is used to provide related results if exact search does not match
