### ISSUE TITLE
Getting empty response for lineage put api

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2156]
https://user-images.githubusercontent.com/59080942/148949715-17440632-41b0-4eb5-9446-a45400707397.mov

**Comment by sureshms** [comment]
@Sachin-chaurasiya, what are you expecting in terms of response. It is the lineage that you pass in the request that gets added.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya, what are you expecting in terms of response. It is the lineage that you pass in the request that gets added.

@sureshms, Earlier we were getting responses like this
```
{
data:'',
statusText:"Ok",
code:200
...
}
```
we were using this response code to validate the response, but now we are getting an empty response.
