### ISSUE TITLE
Documentation - Users get confused on how to start the server in secure mode.

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2159]
Recently, one user faced an issue where he set the openmetadata-security.yaml to start OpenMetadata instance in secure mode, 
the user tried `./bin/openmetadata.sh start` which points to openmetadata.yaml, the instance started in non-secure mode.

**Comment by harshach** [comment]
@shannonbradshaw also it would be good to take a look at security documentation and see what can be improved there. It was fairly untouched from early versions. It works for me but for new users might be confusing.
