### ISSUE TITLE
Add account profile page for logged in user

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2174]
As a logged in user, one should be able to see which teams they are part of and what roles do they have. 

cc: @harshach @sureshms

**Comment by harshach** [comment]
@sanketbambulkar this should be a profile card when the user clicks on their profile pic on top right corner.
@shahsank3t card should be similar to what we have done in the past

**Comment by harshach** [comment]
@Sachin-chaurasiya can we handle this for this release?
@shahsank3t can you show the previous profile work we did in another project
