### ISSUE TITLE
Left panel disappears after clicking 'Clear all' button

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2176]
Steps to reproduce:
1. Search for any keyword
2. Apply any filter with 0 filter count
3. Clear the search
4. Click on the 'clear all' button
5. The left panel will disappear

https://user-images.githubusercontent.com/83201188/149067996-ebbc0173-6392-402d-829b-7011593a0a83.mov

**Comment by ShaileshParmar11** [comment]
Kindly assign to me
