### ISSUE TITLE
The 'matches' when searched for any keyword doesn't show appropriate count.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2178]
Searched for `address`, highlighted are `5` and matches shows `4 in description` 

<img width="1477" alt="Screenshot 2022-01-12 at 11 32 33 AM" src="https://user-images.githubusercontent.com/83201188/149073189-b4d309c4-f2d5-40d8-abb2-c118a78a1b6c.png">

Also for the wild-card search "*", the counts are not matching the actual result.

<img width="1475" alt="Screenshot 2022-01-12 at 11 20 20 AM" src="https://user-images.githubusercontent.com/83201188/149073573-9dca2f7d-c371-42c3-ae5a-dfdb3a6ba78c.png">

**Comment by ShaileshParmar11** [comment]
Kindly assign to me
