### ISSUE TITLE
UI Support for Metadata Operations RBAC

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2181]
Backend work is tracked in #1940 

Initial laundry list of items for UI:

- Ability to associate roles to to a user (User PATCH API with roles field)
- Support viewing configured policies on UI
- Support adding/editing configured policies on UI

**References**
Slide: https://docs.google.com/presentation/d/1S2Ak-CG2i0i2l2IBinuMH9UwuOJv7jPPJTFRPCQe4wU/edit?usp=sharing
Demo: https://youtu.be/y4P_82AJWew

cc: @harshach

**Comment by mithmatt** [comment]
Some guidance

![image](https://user-images.githubusercontent.com/5906984/149708773-ce25678d-e0f6-4d5a-bc82-87a743a3fee1.png)

**Comment by mithmatt** [comment]
When we introduce User profile page - we may also need a way to add a role for that user directly from the profile itself -- something to think about in the future.

**Comment by harshach** [comment]
IMO Data Consumer should be added from the backend itself as the default role and cannot be removed unless the user is deleted.

**Comment by mithmatt** [comment]
#2236 for seed data adding roles DataConsumer and DataSteward and a policy for DataSteward

**Comment by harshach** [comment]
> IMO Data Consumer should be added from the backend itself as the default role and cannot be removed unless the user is deleted.

meant as in, if a new user is signing up or added through APIs we should add a base role of "DataConsumer" to the user
