### ISSUE TITLE
Cannot add more than 10 tags at once

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2188]
`responseMessage: "An exception with message ['[{\"labelType\":\"Manual\",\"state\":\"Confirmed\",\"tagFQN\":\"PersonalData.Personal\"},{\"labelType\":\"Manual\",\"state\":\"Confirmed\",\"tagFQN\":\"PersonalData.SpecialCategory\"}]' contains no element for index 10 and for '10'.] was thrown while processing request."`

**Comment by sureshms** [comment]
@parthp2107 and @aashitk, need details on how to reproduce this issue...

**Comment by parthp2107** [comment]
> @parthp2107 and @aashitk, need details on how to reproduce this issue...

When trying to add 10 or more then 10 tags at once to any entity, getting the below error
`{"responseMessage":"An exception with message ['[{\"labelType\":\"Manual\",\"state\":\"Confirmed\",\"source\":\"Tag\",\"tagFQN\":\"PersonalData.Bot\"},{\"labelType\":\"Manual\",\"state\":\"Confirmed\",\"source\":\"Tag\",\"tagFQN\":\"PersonalData.Data\"}]' contains no element for index 10 and for '10'.] was thrown while processing request."}`

**How to reproduce it:** 

https://user-images.githubusercontent.com/83201188/168967808-a2fcfc3d-7059-401d-854d-19ba85990beb.mov

**Comment by parthp2107** [comment]
@sureshms, The sorting order of path is `0,1,10,2,3,.....` Hence getting `contains no element for index 10 and for '10'.`

```  
  {
    "op": "add",
    "path": "/columns/3/tags/0",
    "value": {
      "labelType": "Manual",
      "state": "Confirmed",
      "source": "Tag",
      "tagFQN": "PersonalData.Personal"
    }
  },
  {
    "op": "add",
    "path": "/columns/3/tags/1",
    "value": {
      "labelType": "Manual",
      "state": "Confirmed",
      "source": "Tag",
      "tagFQN": "PersonalData.SpecialCategory"
    }
  },
  {
    "op": "add",
    "path": "/columns/3/tags/10",
    "value": {
      "labelType": "Manual",
      "state": "Confirmed",
      "source": "Tag",
      "tagFQN": "PersonalData.Bot"
    }
  },
  {
    "op": "add",
    "path": "/columns/3/tags/2",
    "value": {
      "labelType": "Manual",
      "state": "Confirmed",
      "source": "Tag",
      "tagFQN": "PersonalData.Team"
    }
  }
```

**Comment by parthp2107** [comment]
@sureshms @harshach @shahsank3t, can I pick this up?

**Comment by harshach** [comment]
@parthp2107 feel free to pick up cc @mohitdeuex
