### ISSUE TITLE
'Matches' doesn't show up for every search results

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2189]
For the 1st and 2nd result, there is `sales` in the name.

<img width="1469" alt="Screenshot 2022-01-13 at 11 21 37 AM" src="https://user-images.githubusercontent.com/83201188/149273515-2dd15877-b1f9-492a-8eeb-d1dad12e81c3.png">

**Comment by darth-coder00** [comment]
Looks like we are not getting `highlighted text` for these results
CC: @harshach
