### ISSUE TITLE
Support `?fields=*` for GET `{resource}/{id}` requests

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2193]
With current implementation, one has to list out all fields in comma separated form as part of query params.

This issue is to consider a way to support querying all fields without having to list out of all fields in the query param

```
https://sandbox.open-metadata.org/api/v1/tables/{id}?fields=*
```

**Comment by pmbrull** [comment]
nice QOL change here 🚀

**Comment by Shreshtha13** [comment]
Hi. I'd like to work on this issue.

**Comment by mithmatt** [comment]
@Shreshtha13 Assigned to you. 

Thanks for picking this up and making contributions to OpenMetadata.

**Comment by parthp2107** [comment]
@Shreshtha13 Hey, are you still working on this? If not, then I'd like to pick it up.

**Comment by Shreshtha13** [comment]
> @Shreshtha13 Hey, are you still working on this? If not, then I'd like to pick it up.

Hi, yeah I'm not working on this issue anymore, you can pick it up.
