### ISSUE TITLE
Teams with same display name

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2201]
2 teams have the same display name i.e. `Infra`

<img width="325" alt="Screenshot 2022-01-14 at 10 40 56 AM" src="https://user-images.githubusercontent.com/83201188/149455840-3c8c281a-9bd1-4f3a-aed6-796969f2a5e1.png">

**Comment by Sachin-chaurasiya** [comment]
@parthp2107, I think two teams can have the same `displayName` but not the same `name`.
cc: @sureshms @harshach
