### ISSUE TITLE
Make PolicyEvaluator a Singleton with load() or refreshRules() method

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2229]
> any reason to introduce this sleep? assuming this is to kick off the thread to update the policies.

Yes
With current implementation, policies are loaded 5 seconds after application starts, and refreshed every 15 minutes
The 8 seconds here gives enough time for the policies to load.

Sleep time in tests usually turn out to be nasty - ends up sending devs into a rabbit hole of chasing race conditions in tests.

There are a few things that I deferred fixing in this PR (since it was getting larger):

1. Replace scheduled policy update in Authorizer with Change Event based update 
2. Introduce a REST API with GET to return all the policies that are loaded in-memory of Authorizer
3. Replace the sleep here using wait until result of the REST API GET call is as expected (with timeout)

I haven't thought through all the details to make the above 3 work, but I have some idea on what to do.

_Originally posted by @mithmatt in https://github.com/open-metadata/OpenMetadata/pull/2128#discussion_r785400985_

**Comment by harshach** [comment]
@mithmatt thinking about this. Why not make policy evaluator a singleton and whenever there is changes to policies through APIs we can invoke the policyevaluator.load() to reload the new policies? This would be direct and immediate affect of policies rather than waiting for event to come.

**Comment by mithmatt** [comment]
> @mithmatt thinking about this. Why not make policy evaluator a singleton and whenever there is changes to policies through APIs we can invoke the policyevaluator.load() to reload the new policies? This would be direct and immediate affect of policies rather than waiting for event to come.

@harshach As I think about this, your proposal to use Singleton is a better idea than change event based mechanism. 

Initially I wanted to make Authorizer a Singleton (now I recall that this is how I got into exploring Guice and got carried away into Dependency Injection to use @Singleton). 

Will make PolicyEvaluator a singleton to solve this problem as part of this issue, instead of hooking up with change event - would be much simpler and cleaner this way.
