### ISSUE TITLE
Add Role --> Policy relationship

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2253]
Relationship: Role **contains a** Policy

Keep it as a single entity relationship to make things simple - each policy has multiple rules, and hence allows adding more rules.

DataSteward Role contains DataStewardRoleAccessControlPolicy which has N number of rules. 

When creating a role, auto-create an empty policy

Deliverables:
- Establish Role --> Policy relationship during creation of a role
- Create an empty Policy when new roles are created

cc: @harshach

**Comment by harshach** [comment]
> One more challenge to solve on this one.
> 
> When loading roles and policies from resources, the entity-relationship is not created. Need a way to establish this during init/start-up

why not setup the loading data in a way that is associated with the role. 
Example: 
Role can have optional element in its json to have list<policies> you can use this to create a Role entity and add to db?
API can also have the similar capability that way when admin is creating a Role is , he can chose policies add new ones in creation of a role. Instead of 2 step process 1. create role 2. then add policies this can be streamlined.

**Comment by mithmatt** [comment]
> API can also have the similar capability that way when admin is creating a Role is , he can chose policies add new ones in creation of a role. Instead of 2 step process 1. create role 2. then add policies this can be streamlined.

From an API perspective I streamlined it:
- When a new Role is created (POST /roles) - automatically create a Policy and establish Role --> Policy relationship
- When role is deleted (DELETE /roles/:roleId) - automatically delete the Policy associated with it  (using our existing soft delete internal APIs)


For seed data loading, the current implementation loads policy and role seed data separately  and there is a part that establishes relationship (implemented in #2307)   -- I'm not fully satisfied with this approach yet.

Key observation:
Seed data for each of the entities are loaded during CollectionRegistry (init for each resource class). This init may happen in any order (we are using a map that is populated using reflection). 
To avoid getting into order issues,  the implementation in #2307 adds all entities first and at the very last establishes relationships. 

Alternative approach to explore - do something similar to TagCategory and Tag loading (load both together from same file in one initialize call)

**Comment by harshach** [comment]
@mithmatt is there anything remaining on this ticket

**Comment by mithmatt** [comment]
No, the requirement for this issue has been satisfied. 
However, there is scope for improvement (code organization) - will file a new issue if this is critical enough.

Closing this issue.
