### ISSUE TITLE
Add support for data lineage

### ISSUE THREAD

**Issue by csimplestring** [open-metadata/OpenMetadata#226]
Hi, first of all, thanks for this amazing open source project!

Compared with those existing metadata projects: like Apache Atlas, Azure Purview, the data lineage is big selling point. So I am wondering if the. data lineage will be supported in the roadmap?

**Comment by sureshms** [comment]
Data lineage is on our roadmap. We start working on it ASAP and will release it in the next two months (tentatively). Let me know if you are interested in contributing the effort in any way - code, test, or comment. Thank you for creating this issue. Btw I update the title of the issue.

**Comment by shahsank3t** [comment]
Ask from Aaron in `openmetadata-users` Google group:

Does open metadata support column lineage?  In a dataflow for a ETL pipeline or from one system to another, is it possible to mark that a column in one table supplies data for a column in another table?

**Comment by somasays** [comment]
@sureshms Is the lineage support in any way going to be based on or integrate with the open-lineage project (https://github.com/OpenLineage/OpenLineage). 

Also, I would like to find out if I can contribute, where can I find the tickets related to this topic?

**Comment by harshach** [comment]
@somasays Thanks for your interest. We are going to work on the lineage APIs and integrations in 0.5 release slated for next month. Let us know if you are interested in contributing we can share the tickets.

**Comment by somasays** [comment]
Hi @harshach, thank you for asking, just before I commit may I look at the tickets too get a sense of how much time commitment I might have to make?

**Comment by sureshms** [comment]
@csimplestring, @somasays - first implementation of lineage APIs is up. See https://github.com/open-metadata/OpenMetadata/pull/719

**Comment by sureshms** [comment]
Lineage is going to be an ongoing feature. So far we have added Lineage API, Lineage UI, support for lineage for airflow, dbt, and others. We are also adding in release 0.8, manually adding lineage, and lineage for BigQuery, etc. based on query analysis. Closing this issue as the lineage functionality will continue to be built as part of other specific issues.
