### ISSUE TITLE
Ingestion: Roles and Teams apis should only be called when we are ingesting users or policies

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2272]
We are calling bootstrap_entities whenever metadata_rest gets instantiated https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/sink/metadata_rest.py#L103 this will get called even when we are adding tables or other entities which are not related to this data.
Lets make it localized to users/policy ingestion only.
cc @ayush-shah @mithmatt 
@mithmatt do we still need ingestion based policies given we are loading it from resources and also we will have UI?

**Comment by mithmatt** [comment]
> do we still need ingestion based policies given we are loading it from resources and also we will have UI?

I plan to delete the ingestion based policies as part of #2253 (which would possibly land along with the UI)

The boostrapping that happens from resources/json/data/{policy,role} is sufficient for the initial set up

**Comment by harshach** [comment]
@mithmatt closing this as done. If there is anything more to do , we can file another one.
