### ISSUE TITLE
The data access should not throw WebException with HTTP Status code 404.

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2287]
The current implementation works neither for `POST` nor `GET`. `POST` could mean that the validation failed somehow. For example, the user is trying to create a table with an owner that doesn't exist. In the API we declare BAD_REQUEST 400 but we return NOT_FOUND 404. `GET` could mean that the entity has an owner that must exist that it is not found because of an inconsistency in the database. Therefore the Status code should be 500 and not 404.

#
Current version
```java
  default T findEntityById(UUID id, Include include) throws IOException {
    Class<T> clz = getEntityClass();
    String json = findById(getTableName(), id.toString(), toBoolean(include));
    T entity = null;
    if (json != null) {
      entity = JsonUtils.readValue(json, clz);
    }
    if (entity == null) {
      String entityName = Entity.getEntityNameFromClass(clz);
      throw EntityNotFoundException.byMessage(CatalogExceptionMessage.entityNotFound(entityName, id));
    }
    return entity;
  }
```

#
Proposed version. Don't throw WebException from the model layer but delegate it to the control layer.
```java
  default T findEntityByIdOrNull(UUID id, Include include) {
    Class<T> clz = getEntityClass();
    String json = findById(getTableName(), id.toString(), toBoolean(include));
    T entity = null;
    if (json != null) {
      try {
        entity = JsonUtils.readValue(json, clz);
      } catch (IOException e) {
        throw DeserializationException.message(
            String.format("Error in deserializing entity %s in table %s with class %s", id, getTableName(), clz), e);
      }
    }
    return entity;
  }
```

We could use Java `Optional<T>` if we want. The IOException is unrecoverable because it means that the database is again corrupted or the user didn't run the migration before upgrading and there is no point in bubbling up the checked exception. Better to catch it and throw an unchecked exception with Status code 500. We could use a different strategy with `LIST` where we don't want to 500 the request if only one entity is corrupted in the database.

Fixing this and other inconsistencies will make our API consistent with the JSONSchema contract, remove some duplicated code that we have accumulated so far, and make the application more robust to errors.

@sureshms @harshach @pmbrull @mithmatt

**Comment by sureshms** [comment]
> The current implementation works neither for POST nor GET. 
It would be good to describe issues instead of making sweeping statements. Please describe current behavior in APIs that could be improved.

Let's avoid lengthy names that capture implementation and interface details, such as `findEntityByIdOrNull`. Also note that there is a variant of method `findById` which returns you JSON representation of the entity that could be null when not found and that does not throw `Exception`. Where necessary, this could be used to return the appropriate HTTP response code.

**Comment by amiorin** [comment]
I think we could improve the API in this test.
https://github.com/open-metadata/OpenMetadata/blob/89d029355dfff66b556b2a21801f878adf6a5bd0/catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java#L607-L617

Instead of returning 404, we should return 400, or we should change our contract in all Resources.
https://github.com/open-metadata/OpenMetadata/blob/89d029355dfff66b556b2a21801f878adf6a5bd0/catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/databases/TableResource.java#L288-L306

I agree with the answer in [StackOverflow](https://stackoverflow.com/questions/44915255/is-it-ok-return-http-status-404-in-the-post)

`findEntityByIdOrNull` is temporary to avoid clashes with the old method. When/if I completely replace the old method with the new one, I will also rename it to make it shorter.

`findById` makes sense for the validation of the owner. I'll check it out.
