### ISSUE TITLE
Docs: Update Oracle connector docs to install oracle client before running ingestion 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2290]
Oracle connector follows the generic connector template , however Oracle has as strict dependency on their oracle client libraries
We used this document to install the necessary libraries https://help.ubuntu.com/community/Oracle%20Instant%20Client
set
```export LD_LIBRARY_PATH=/usr/lib/oracle/19.13/client64/lib/:$LD_LIBRARY_PATH```

@akash-jain-10 can you work with Shilpa update the docs there. We should've a integration test for testing new connector changes 
cc @shannonbradshaw

**Comment by akash-jain-10** [comment]
@harshach  - I connected with Shilpa on this issue and we already have updated doc for 0.7.0 here - https://docs.open-metadata.org/connectors/oracle#oracle-client-libraries

Let me know if we are good with this ?

**Comment by harshach** [comment]
@akash-jain-10 lets call specifically what environment variables they should setup etc..

**Comment by akash-jain-10** [comment]
> @akash-jain-10 lets call specifically what environment variables they should setup etc..

I will work with Shilpa to get the documentation updated. Thanks @harshach

**Comment by akash-jain-10** [comment]
Hello @shannonbradshaw - We have all the required documentation covered here - https://docs.open-metadata.org/connectors/oracle
