### ISSUE TITLE
Slight snag in installation instructions

### ISSUE THREAD

**Issue by milimetric** [open-metadata/OpenMetadata#2293]
When following the https://docs.open-metadata.org/install/run-openmetadata instructions, I got to step 7:

`metadata docker --start`

This showed a plain text message that I was missing docker-compose, which seemed optional since the process kept running.  The output looked like this:

```
(env) milimetric@data-catalog-evaluation:~/openmetadata-docker$ metadata docker --start
[2022-01-19 20:50:47,420] INFO     {metadata.cmd:200} - Running Latest Release Docker
/bin/sh: 1: docker-compose: not found
[2022-01-19 20:50:47,593] INFO     {metadata.cmd:210} - Time took to get containers running: 0:00:00.006378
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C
Aborted!
```

The slack was very friendly and helpful, I was able to keep going by installing the latest docker-compose.  Someone did mention that maybe in the future OpenMetadata will be using `docker compose` to avoid this issue.  I'm creating this task so I can send a PR to the docs.

**Comment by harshach** [comment]
Thanks @milimetric . 
@akash-jain-10 lets handle the docker compose option in the upcoming release.

**Comment by harshach** [comment]
will keep this issue for docs update as originally intended
