### ISSUE TITLE
Improvements to Developer Docs

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2294]
I am thinking of organizing developer docs in the following sections
1. Pre-requisites  
 -  Java version
 -  Python version
 -  Maven version
 -  Editors
 -  MySQL
 -  ElasticSearch
 -  git hook - pre-requisites
 -  Docker?
2. Configure IntelliJ for Java Development
 - Loading the project 
 - Setting up Runtime configurations to run OpenMetadata Server
 - Debugging, How to run unit tests in debug mode etc.. and server (suggested by @mithmatt)
3.  Configuring PyCharm for Python Development
 - Loading the project
 - Setting up python dependencies for dev
 - Testing end-to-end with OpenMetadata 
 4. UI Development
  - Setting up the project for local development
  - Running a local server and how to quickly dev/test/iterate UI changes

cc @pmbrull @mithmatt @shahsank3t @Sachin-chaurasiya @darth-coder00 @ayush-shah @vivekratnavel @shannonbradshaw Please add any further input here. We can take a look at revamping this post release.

**Comment by pmbrull** [comment]
In the docs and Makefile we randomly switch between `python` and `python3` calls. It would be interesting in the Python Version section to add specific instructions on how to use `pyenv` and/or `virtualenv` to handle the correct Python setup. This way we can properly standardize all calls as `python` and avoid any dependency on specific user aliases

**Comment by mithmatt** [comment]
@harshach 

We can also call the sections, so that it is coherent with what parts of the system we are referring to:
1. Prerequisites
2. Backend (Java)
3. Ingestion (Python)
4. UI (React)

I started the backend directory as part of #2375

**Comment by asdiamond** [comment]
Rather than have a pycharm setup can we add the intellij property files into the repo and have it setup with the python plugin? We could also add settings for the docker plugin etc to make onboarding easier.

**Comment by pmbrull** [comment]
Maybe on a different note, there is the recurrent question of OpenMetadata vs. "Insert tool X".

There is this catalog tool [Castor](https://www.castordoc.com/) that has a feature comparison on a [table](https://notion.castordoc.com/catalog-of-catalogs). IDK if we might want to do something similar to highlight the main unique features

**Comment by mithmatt** [comment]
Adding another link [here](https://www.notion.so/atlanhq/The-Ultimate-Repository-of-Data-Discovery-Solutions-149b0ea2a2ed401d84f2b71681c5a369) that supports @pmbrull comment above

**Comment by harshach** [comment]
@mithmatt assigning this to you as you are driving most of it.
@pmbrull can you help with python side of the things. Thanks

**Comment by harshach** [comment]
@pmbrull we do not have any docs for python building in the Developer section. Can you take this up? Let me know if I can help anywhere.

**Comment by pmbrull** [comment]
@harshach refactored a bit the Build section: https://docs.open-metadata.org/open-source-community/developer/build-code-run-tests We can iterate on top of this. Let me know your thoughts. Thanks!
