### ISSUE TITLE
Login page has same image and texts, also the images are blurry.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2298]
https://user-images.githubusercontent.com/83201188/150278071-24130d9a-3c30-418a-8ad0-3769cc590530.mov

<img width="841" alt="Screenshot 2022-01-20 at 10 46 32 AM" src="https://user-images.githubusercontent.com/83201188/150278167-5fa8752d-6e67-4f2b-885a-7f438787a741.png">

**Comment by darth-coder00** [comment]
Reopening as this will be a higher priority. Need content for carousal.
CC: @shahsank3t, @Sachin-chaurasiya

**Comment by darth-coder00** [comment]
Need content for carousals of different pages.

**Comment by ShilpaVernekar** [comment]
@harshach @sureshms  - Please review
**Landing Page** - Enables End-to-end Metadata Management with Data Discovery, Data Quality, Observability, and People Collaboration
**Explore Page** - Discover your Data and Unlock the Value of Data Assets
**Entity-details Page** - Assess Data Reliability with Data Profiler, Lineage, Sample Data, and more
**Users Page** - Fosters Collaboration among the Producers and Consumers of Data

cc @darth-coder00
