### ISSUE TITLE
Login page enhancements

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2303]
Requested changes are as follows:
- Login page content(logo, login subtitle, and login button) centre alignment
- Equal spacing between the logo, heading, and texts.
- `Log in` should be `Login`
- Change same images and texts,

Login page related issue: #2298

https://user-images.githubusercontent.com/83201188/150278071-24130d9a-3c30-418a-8ad0-3769cc590530.mov

<img width="841" alt="Screenshot 2022-01-20 at 10 46 32 AM" src="https://user-images.githubusercontent.com/83201188/150278167-5fa8752d-6e67-4f2b-885a-7f438787a741.png">

<img width="1625" alt="Screenshot 2022-01-20 at 1 56 36 PM" src="https://user-images.githubusercontent.com/83201188/150301172-b9953648-4779-46f1-8f9f-f4a56ad62b72.png">

**Comment by darth-coder00** [comment]
Point 4 covered in #2298
