### ISSUE TITLE
RBAC UX Test Scenarios 

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2324]
Test the following scenarios through UI to ensure integration works end-to-end with UI + backend changes before 0.8 release

- [x] Backend automatically loads roles + policies on startup - Ensure that they are exposed on roles UI
- [x] Admin should be able to assign Data Steward role to a user John
- [x] Admin should be able to see and adjust policy for roles (add rules, delete, edit, disable existing rules)
- [x] John should be able to Update Description, Tags, Owner for any entity. - test combinations based on rules set up
- [x] Admin revokes access by disabling rules and John cannot do any of the above

- [x] 0.7 --> 0.8 Migration Test - ensure that backend can load roles + policies and UI works after migration
- [x] Ensure RBAC  is not enabled in non secure mode 

Also need to think about UX when DefaultAuthorizer (secure mode) is not enabled. 
Should we put role/policy in read-only mode and indicate to Admin to enable security for accessing this feature?

cc: @harshach @Sachin-chaurasiya @sureshms

**Comment by Sachin-chaurasiya** [comment]
Fixed by #2557
