### ISSUE TITLE
Get APIs for My data page listings and stats

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#233]
Currently it's using search API, need to remove this dependency

**Comment by darth-coder00** [comment]
Assets count here is coming from search api total hits, we should have an API for that
<img width="1064" alt="Screenshot 2021-08-23 at 9 37 14 PM" src="https://user-images.githubusercontent.com/86726556/130482316-cbaa13b2-a685-4944-a60a-0a940c016ec7.png">

Entity list here is coming from Search api for all 3 tabs, i.e. `All` `My Data` `Following`, it should be coming from a RESTful API
<img width="1785" alt="Screenshot 2021-08-23 at 9 37 41 PM" src="https://user-images.githubusercontent.com/86726556/130482559-9255a1ab-3b81-458d-b1fd-5b8179f7f57e.png">

**Comment by harshach** [comment]
we decided to use ES for all the counts
