### ISSUE TITLE
Use a fluent API with the decorator.

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2331]
Code like this is confusing
```java
    report.setService(helper(helper(report).findEntity("service")).toEntityReference());
```

Better to have a fluent API
```
    report.setService(helper(report).findEntity("service").toEntityreference());
```

**Comment by harshach** [comment]
@sureshms keeping this as cleanup of entity helper

**Comment by sureshms** [comment]
Simplified the code after merging EntityHelper into Entity and EntityRepoaitory classe. Closing this.
