### ISSUE TITLE
Policy is allowing to add duplicate rules

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2343]
For `accessControl` policy type I am able to add duplicate rules.

Payload
Here I am passing two same rules but not getting any error for duplicate rules.
```
{
  "name": "DevOpsRoleAccessControlPolicy",
  "policyType": "AccessControl",
   "rules": [
        {
          "name": "DevOpsRoleAccessControlPolicy-UpdateDescription",
          "allow": true,
          "enabled": true,
          "priority": 1000,
          "operation": "UpdateDescription",
          "userRoleAttr": "DevOps"
        },
        {
          "name": "DevOpsRoleAccessControlPolicy-UpdateDescription",
          "allow": true,
          "enabled": false,
          "priority": 1000,
          "operation": "UpdateDescription",
          "userRoleAttr": "DevOps"
        },
      ]
}

```
Response

![image](https://user-images.githubusercontent.com/59080942/150626790-cf67f543-1a3b-42aa-a9df-57309e14b33e.png)

CC: @harshach @mithmatt @sureshms

**Comment by harshach** [comment]
@mithmatt can we add a unique constraint of operation per policy?

**Comment by mithmatt** [comment]
Checking, we should add a unique constraint for this one

**Comment by mithmatt** [comment]
This is a minimal change on the backend (a few lines of code)
Will post PR soon
