### ISSUE TITLE
make bump version setup

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2345]
`make bump-version-dev` should be easier to run with its own requirements. The bot currently only tells devs to run the make recipe but we are not properly talking about the specific dependencies nor where to find this information.

Here we could:
1. Add more info on the bot to make it easier to follow the steps
2. Add further instructions to the make recipe so that it prepares all the requirements in a new venv

**Comment by mithmatt** [comment]
Can we make the make do everything it needs to do ... set up venv, install reqs, bump up, deactivate venv?

**Comment by pmbrull** [comment]
> Can we make the make do everything it needs to do ... set up venv, install reqs, bump up, deactivate venv?

If there are no objections I do think it is the easiest approach as well

**Comment by mithmatt** [comment]
Related task #2342

**Comment by pmbrull** [comment]
Let's do both refactors at the same time!
