### ISSUE TITLE
Check version and publish core at main push

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2363]
The current process of evaluating `ingestion-core` (JSON Schemas standalone) and publishing it to test pypi is the following:
1. When there are schema changes in a PR, a workflow asks the user to bump ingestion-core version and commit that manually
2. When the code reaches `main`, we generate the sources and run the publish.

To ease this process for contributors, let's get rid of the first step and have it happen in one go after the PR is merged:
- Get the latest version directly from pypi releases with a small scraping, add the new version on-the-fly and publish it

**Comment by harshach** [comment]
@pmbrull if you have time, can we handle this quickly

**Comment by harshach** [comment]
@pmbrull closing this
