### ISSUE TITLE
Check entity version return body

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2384]
Some changes have impacted the fields returned by the GET entity version.

We are seeing some errors in the python integration tests for the Ometa wrapper:
```python
Error
Traceback (most recent call last):
  File "/Users/p.brull/projects/OpenMetadata/ingestion/tests/integration/ometa/test_ometa_chart_api.py", line 225, in test_get_entity_version
    res = self.metadata.get_entity_version(
  File "/Users/p.brull/projects/OpenMetadata/ingestion/src/metadata/ingestion/ometa/mixins/version_mixin.py", line 76, in get_entity_version
    return self._get(entity=entity, path=path, fields=fields)
  File "/Users/p.brull/projects/OpenMetadata/ingestion/src/metadata/ingestion/ometa/ometa_api.py", line 380, in _get
    return entity(**resp)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Chart
service
  field required (type=value_error.missing)
```
It is failing when trying to convert the response body to the specific Entity.

Let's take a look and see if it makes sense to keep returning the `service` or if we should update the `OpenMetadata` API wrapper expected behavior.

**Comment by pmbrull** [comment]
Hi @harshach, I was trying to figure out the source from this and it might come from not properly recovering deleted entities in the backend.

The issue we are having is that during the integration tests, we are stressing all operations on the entities with a series of PUT, GET, DELETE, etc. We also test the `versions` endpoint trying to obtain the version `0.1`.

It looks like the combination of `DELETE` + `PUT` + `GET/versions/0.1` does not properly return all the information, as the `service` is missing from the response body. It is a bit weird as the usual `GET` returns the whole info and it is just the `versions` endpoint the one that is having this issue.

You can replicate the issue with
```python
from metadata.generated.schema.api.data.createDashboard import (
    CreateDashboardEntityRequest,
)
from metadata.generated.schema.api.services.createDashboardService import (
    CreateDashboardServiceEntityRequest,
)
from metadata.generated.schema.api.teams.createUser import CreateUserEntityRequest
from metadata.generated.schema.entity.data.dashboard import Dashboard
from metadata.generated.schema.entity.services.dashboardService import (
    DashboardService,
    DashboardServiceType,
)
from metadata.generated.schema.type.entityReference import EntityReference
from metadata.ingestion.ometa.ometa_api import OpenMetadata
from metadata.ingestion.ometa.openmetadata_rest import MetadataServerConfig

import requests


server_config = MetadataServerConfig(api_endpoint="http://localhost:8585/api")
metadata = OpenMetadata(server_config)

# Prepare and create service
service = CreateDashboardServiceEntityRequest(
    name="test-service-dashboard",
    serviceType=DashboardServiceType.Superset,
    dashboardUrl="https://localhost:1000",
)

service_entity = metadata.create_or_update(data=service)

# Prepare and create Dashboard
create = CreateDashboardEntityRequest(
    name="test",
    service=EntityReference(id=service_entity.id, type="dashboardService"),
)

entity = metadata.create_or_update(data=create)

# Delete
metadata.delete(entity=Dashboard, entity_id=entity.id)

# Recreate
metadata.create_or_update(data=create)

requests.get(f"http://localhost:8585/api/v1/dashboards/{str(entity.id.__root__)}/versions/0.1").json()
```

**Comment by pmbrull** [comment]
Looks like at `DELETE` we insert the entity JSON in `entity_extension` already without the `service` information

**Comment by harshach** [comment]
@pmbrull when the entity is deleted we are setting all the relations to be deleted. 
so in our calls after the delete if we want to get the full picture of the entity that is deleted we should pass "include=deleted" as the query param.
cc @amiorin

**Comment by amiorin** [comment]
@pmbrull ping me in Slack if you need help with the debugging.

**Comment by pmbrull** [comment]
Thank you both! ended up being a one-liner, you just needed to know where to add it 😅
