### ISSUE TITLE
Manual Lineage Editor: connecting tables to dashboard is running into errors

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2390]
1. Drop a dashboard widget
2. Search for dashboard, select one of thme
3. Connect a table to dashboard
4. Dashboard card will disappear
5. Lineage on the same component is not refreshed
6. Lineage works on the dashboard->lineage page
7. Drag another dashboard card and try to add the lineage now the card will disappear when selecting a dashboard

**Comment by Sachin-chaurasiya** [comment]
@harshach, I'm not getting any error when connecting table entity with dashboard entity.

https://user-images.githubusercontent.com/59080942/150911773-e0abe585-092d-42cd-a47c-1046a7f3e746.mov
