### ISSUE TITLE
Disable toggle for  'Metadata Extraction' in create service not allowing to go to next step.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2393]
Steps to reproduce:
- Create service
- Go to "ingestion details" section
- Disable the metadata extraction
- Click next, it won't take you to next step.

https://user-images.githubusercontent.com/83201188/150903271-1dbe68b0-12c8-4201-847e-e168c8491a87.mov

**Comment by darth-coder00** [comment]
Fixed
