### ISSUE TITLE
Deleting service and then adding/creating service of same name throws "409, Entity already exists"

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2395]
Steps to reproduce:
- Create a service of same say `test`
- Delete the service `test`
- Try adding a service with name`test`

https://user-images.githubusercontent.com/83201188/150905503-655b3141-f367-416d-819d-6878a2164a8f.mov

**Comment by amiorin** [comment]
I'm also working on this. It could be a bug in the Java code too.

**Comment by amiorin** [comment]
The behaviour is:

1. An entity in deleted state after a PUT request gets restored.
2. PUT is either create or update.
3. POST request will be rejected with 409 if soft-deleted or non-deleted.
4. POST can only be done after hard deleting the entity.
5. We need to add support for hard delete in the next release.

Ping me in Slack if you need support.

**Comment by amiorin** [comment]
@darth-coder00 
Please handle the 409 in the UI.

@sureshms @harshach
UI users cannot list deleted services yet.
#
![image](https://user-images.githubusercontent.com/32617/151039727-4f7276ee-ab18-432a-b6b1-30da983a6b5d.png)

**Comment by darth-coder00** [comment]
> @darth-coder00 Please handle the 409 in the UI.
> 
> @sureshms @harshach UI users cannot list deleted services yet.
> 
> ![image](https://user-images.githubusercontent.com/32617/151039727-4f7276ee-ab18-432a-b6b1-30da983a6b5d.png)

@amiorin  Handled 409 error on UI

CC: @harshach @sureshms
