### ISSUE TITLE
Lineage Docs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2412]
Prepare separate lineage section, adding the config and also documenting if the users have configured the google as security to pass the optional configuration and documenting this example https://github.com/open-metadata/OpenMetadata/blob/0.7.0/ingestion/examples/airflow_lineage/openmetadata_airflow_lineage_example.py

**Comment by harshach** [comment]
We should also document the ways we capture the lineage , Airflow being one of them

**Comment by pmbrull** [comment]
Apart from Airflow, I am aware of:
- manual entries
- API calls / Python Client / ML specific behavior

Do we have any other automatic sources? If so, with some pointers I am happy to add it to https://github.com/open-metadata/OpenMetadata/pull/2618

Thanks!
