### ISSUE TITLE
Pass proper name for entity from suggestion and search API.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2419]
name should be `dim_address_etl` but getting `dim_address etl`.

{
    "name": "dim_address etl",
    "fqdn": "sample_airflow.dim_address_etl",
    "service": "sample_airflow",
    "description": "dim_address etl",
    "display_name": "dim_address ETL pipeline",
   
}

For every entityType, we should get the name as FQN last entry.
For example : 
If FQN is `sample_airflow.dim_address_etl` then name should be `dim_address_etl`

**Comment by Sachin-chaurasiya** [comment]
@harshach , This change is required because we are using the name of the newly added entity in the lineage editor to get its upstream and downstream nodes.

**Comment by harshach** [comment]
@Sachin-chaurasiya is this still required?

**Comment by Sachin-chaurasiya** [comment]
@harshach, not a blocker for now, but we should pass consistent name in search and suggestions API.

**Comment by harshach** [comment]
@Sachin-chaurasiya can you elaborate on this. Let me know the requirements clearly on the response side

**Comment by Sachin-chaurasiya** [comment]
@harshach, For each entity we are getting name and displayName both. we are using displayName in UI. for some use cases we do use the name as well. so on the response side, if fqn is `sample_airflow.dim_address_etl` then we should get a name `dim_address_etl`.

**Comment by harshach** [comment]
For tables name is never going to be changed from source but for dashboards, pipelines etc.. name is not unique and can be changed. What unique is the id of these entities from source (superset, airflow etc..) hence the reason when we are ingesting we map id of a dashboard or pipeline mapped to id of the entity in OM. Similarly when we index this into ElasticSearch we map display name into name of ES index to allow users to search name and displayName.
All of the entities in ES comes with entity_id and fqn so UI or client can use that to lookup more details in OM
