### ISSUE TITLE
Create new roles "Admin" and "Bot" on server startup

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2441]
Register a new role called "Admin" and "Bot" during start up.
Refer https://github.com/open-metadata/OpenMetadata/tree/main/catalog-rest-service/src/main/resources/json/data/role

Admin and Bot roles MUST NOT have any policy associated with it like other roles. 
Any attempts from API calls to associate a policy with Admin or Bot role should return an error.
Refer https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java

**Comment by harshach** [comment]
We should also add bot as role and remove isAdmin and isBot from the User profile.

**Comment by mithmatt** [comment]
Updated description to accommodated Bot

**Comment by asdiamond** [comment]
I think this is something I can pick up. I want to learn more about the RBAC.

**Comment by shahsank3t** [comment]
Assigned to you @asdiamond

**Comment by harshach** [comment]
@mithmatt @asdiamond is this going to be part of 0.9 release?

**Comment by asdiamond** [comment]
No it won't be ready.
