### ISSUE TITLE
Fix case for Role name in rule modal

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2444]
Show role display name as is in the role page.

Currently it is lower cased.

![image](https://user-images.githubusercontent.com/5906984/151120025-23bf3d2d-fa6a-486a-8f93-a8869478ac1e.png)

**Comment by 852hamza** [comment]
yes i solved this issue 
can u send me detail

**Comment by mithmatt** [comment]
https://github.com/open-metadata/OpenMetadata/blob/590a0ab62422ab888d264fbd9fb16f63b5596cb0/openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesPage.component.tsx#L618

**Comment by 852hamza** [comment]
> Show role display name as is in the role page.
> 
> Currently it is lower cased.
> 
> ![image](https://user-images.githubusercontent.com/5906984/151120025-23bf3d2d-fa6a-486a-8f93-a8869478ac1e.png)

In this image where is  the roll page 

is  Add  icon is roll page 
or 
is add new roll button is roll page

**Comment by mithmatt** [comment]
"Data Test" on role page

<img width="568" alt="Screen Shot 2022-01-27 at 1 02 56 AM" src="https://user-images.githubusercontent.com/5906984/151326363-e2a70ab4-6eaa-4a19-868e-f9caa2fb75b7.png">

**Comment by 852hamza** [comment]
can you explain me in detail
what is the problem you faced

**Comment by 852hamza** [comment]
it work accurate
![Screenshot_2022-01-27_04_16_00](https://user-images.githubusercontent.com/86769921/151328768-68f3f929-7833-42f1-8e35-66879c69567d.png)



what do you want

**Comment by 852hamza** [comment]
![Screenshot_2022-01-27_04_17_15](https://user-images.githubusercontent.com/86769921/151328918-3ad7adbf-b511-437a-a3c2-305cd73de261.png)

what is the problem in this pic

are you want in test3 uppercase ?????

**Comment by mithmatt** [comment]
Yes I want the casing for the text in the modal to be exactly the same as what is on the page.

TEST3 in the above example.

**Comment by 852hamza** [comment]
Bro can you tell me how i can run these thing after changing the code

**Comment by mithmatt** [comment]
These may help

https://docs.open-metadata.org/open-source-community/developer/build-code-run-tests
https://docs.open-metadata.org/open-source-community/developer/run-openmetadata-ui-locally

**Comment by mithmatt** [comment]
@852hamza Were you able to run the code locally?

**Comment by 852hamza** [comment]
> @852hamza Were you able to run the code locally?

yes

**Comment by mithmatt** [comment]
@852hamza 

Nice. Let us know if you need any help with fixing this issue.
