### ISSUE TITLE
Support the following functions

### ISSUE THREAD

**Issue by caiyt2001** [open-metadata/OpenMetadata#2446]
- Internationalization support
- Standard terms, dictionary definition, mapping
- Column-Level Lineage   SQL Parsing
- Asset analysis

**Comment by harshach** [comment]
@caiyt2001 Thanks for raising the issue. It would be great if you can add more details such as what you mean by "Asset Analysis"

**Comment by vivekratnavel** [comment]
@caiyt2001 I have created an issue to track support for internationalization via #5496

**Comment by sureshms** [comment]
> * Internationalization support
Tracked in #5496 
> * Standard terms, dictionary definition, mapping
Glossaries and Tags have been added for this purpose
> * Column-Level Lineage   SQL Parsing
Column-level lineage is now supported
> * Asset analysis
Not clear what this is. @caiyt2001 you can open a new issue with details.
