### ISSUE TITLE
API to return what operations user can perform such that UI enable/disable controls

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2455]
UI disables the edit functionality of an entity by checking if the logged-in user 
is a owner of the entity or not. This is breaking Datasteward role as the user may have edit description operation allowed
but UI will show disabled button as the logged-in user is not a owner. 
We should provide an API which returns what operations for a given entity user can perform 
and not use the if the logged-in user is a owner or not

**Comment by mithmatt** [comment]
Example on UI:

Logged in user has Data Steward role, but does not have edit access. 

![image](https://user-images.githubusercontent.com/5906984/151206207-8cce8123-2bd4-4a5c-a9fb-d9f0007c3566.png)

**Comment by mithmatt** [comment]
- [ ] Introduce REST API to get allowable operations 
- [ ] Revamp logic on frontend to use above and disable/enable edit buttons

**Comment by mithmatt** [comment]
Planning to add another method  to the `Authorizer` and expose the results through the `v1/config/authorizer` REST API with fields having user and entity information

```
List<MetadataOperation> listPermissions(User user, EntityReference entityReference);
```

**Comment by mithmatt** [comment]
@Sachin-chaurasiya The backend changes have landed. 

Example API call

![image](https://user-images.githubusercontent.com/5906984/151717450-4c1613a1-ddc3-4c1c-9ca0-89fe4ebd176a.png)
