### ISSUE TITLE
Admin should be able to chose what is the default role a user should belong to

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2460]
We should allow Admins to choose which role is the default role that will get assigned to the users during sign-up

**Comment by mithmatt** [comment]
- [ ] Trace code path for user sign up process
- [ ] Investigate solution to mark a role as default role
- [ ] Implementation

**Comment by mithmatt** [comment]
Signup calls createUser
https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/pages/signup/index.tsx#L63

**Comment by mithmatt** [comment]
Time t0 = 21 users exist within OM
Time t1 = Admin sets the default role as DataConsumer
Time t2 = 1 new user signs up and gets assigned DataConsumer role, the remaining 21 users do not have DataConsumer role.


@harshach What should we do with the users that already exist?
Should there be some support from UI to add a role to a selected set of users in bulk? (could be outside the scope of this issue)

**Comment by harshach** [comment]
@mithmatt In the process of selecting the default role. Admin will be promoted and UI should make a call to apply that role to existing users

**Comment by mithmatt** [comment]
**Proposal**


<img width="857" alt="Screen Shot 2022-02-04 at 2 30 46 AM" src="https://user-images.githubusercontent.com/5906984/152513920-45890407-b35f-4082-8df5-97f4dd373dc3.png">


**Required Changes**

- [ ] Add field isDefault to role entity & query param default=true for GET /roles
- [ ] Amend PATCH /roles/:roleId to 
        - swap existing default role with the new role (set old role isDefault=false, new role isDefault=true)
        - delete all user -- has --> role relationship for old role 
        - create user -- has --> role relationship for new role
- [ ] UI changes

**Comment by mithmatt** [comment]
All backend code changes required for this feature has been landed
