### ISSUE TITLE
Need an API support for join team

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#247]
Currently, we have PATCH API to manipulate teams data with Admin Access only.
If new users come in and want to join the particular team they won't be allowed as there is an admin access check. 
So, we will need a separate `PUT API` to carry out this process.

**Comment by sureshms** [comment]
Let's wait to fix this until we are clear on how users want to manage the teams. Moving this out of 0.4 release.
