### ISSUE TITLE
Organize features into themes on features page

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#2477]

**Comment by harshach** [comment]
@shannonbradshaw ordering like blow probably would be better. Trying to make them as a story of evolution in metadata.
Discovery, updates, owning data, lineage etc..

1. All your data in place
2. Data Discovery
 2.1 Keyword Search
 2.2 Discover data though association
 2.3 Advanced Search
3. Add Descriptive Data
4. Complex Data Types
5. Importance & Owners
 5.1 Filter Assets by Importance
 5.2 Identity Asset Owners
6. Data Lineage
7. Edit Data Lineage Manually
8. DBT Integration
9. Data Reliability
10. Change Activity Feeds
11. Event Notification via Webhooks and Slack Integration
12. Role Based Access Control
