### ISSUE TITLE
Fix height of selected field's number

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2496]
The height of selected field's number is slightly smaller than the non-selected ones.

It is hard to notice. However, if you select and deselect a few times you'll see the line moving up and down.

We should fix the height such that it is same regardless of it being selected or not

![image](https://user-images.githubusercontent.com/5906984/151686275-8b03668f-5226-4223-a561-2c0fe6444019.png)

**Comment by mithmatt** [comment]
@shahsank3t @Sachin-chaurasiya  Could this be a good first issue?

**Comment by shahsank3t** [comment]
Yes @mithmatt it's a good first issue. Added the tag.

**Comment by deweybat** [comment]
Hi, could I take on this issue? Thanks

**Comment by mithmatt** [comment]
Thanks for showing interest in taking this on @deweybat 

Assigned to you

**Comment by Rounak-28** [comment]
Is this issue still open?

**Comment by Sachin-chaurasiya** [comment]
Hello @Rounak-28, it's fixed.
