### ISSUE TITLE
Getting 401 unauthorised error for retrieve permissions API.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2507]
I was trying out a new API endpoint that is  `http://localhost:8585/api/v1/config/permissions` with a header

```
Authorization : Bearer {token}
```

But getting errors like this. 

```
{
    "code": 401,
    "message": "No principal in AuthenticationContext"
}
```
I tried this out with a normal user as well as an admin user.
It is working for other endpoints.

**Comment by harshach** [comment]
@vivekratnavel can you check this
