### ISSUE TITLE
Add coverage for UI component unit tests 

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#2511]
**Is your feature request related to a problem? Please describe.**
Add unit tests for all UI components along with coverage report.
Currently some tests are failing and the passing tests do not have reliable coverage.

**Describe the solution you'd like**
Implementing Unit tests using Jest with React-testing-library to test components from user's perspective.

**UI Design**
Not related

**Additional context**
None required

## Tasks

- #2645 
- #3684 
- #3690

**Comment by harshach** [comment]
@darth-coder00 I am not attaching any mile-stones for this epic. Lets file a follow-up ticket for each milestone on how we are planning on improving it
