### ISSUE TITLE
More nuanced Hive ingestion

### ISSUE THREAD

**Issue by milimetric** [open-metadata/OpenMetadata#2533]
**Is your feature request related to a problem? Please describe.**
I ran through the Hive ingestion tutorial, and found a couple of blockers for implementing it at a production level in our environment.  Kerberos support is there, sort of, but it would be nice if it was better documented.  But being aware of hive partitions and having a robust ingestion query is necessary.

**Describe the solution you'd like**
A documented way to ingest from a hive metastore with support for kerberos authentication and partitioned tables.

**Describe alternatives you've considered**
I've kind of hacked together a config that shows the problem, I'll paste it here and explain a couple of details below:

```
current_user = pwd.getpwuid(os.getuid()).pw_name

config = """
{
  "source": {
    "type": "hive",
    "config": {
      "database": "wmf",
      "host_port": "analytics-test-hive.eqiad.wmnet",
      "service_name": "hive_test_cluster",
      "generate_sample_data": "true",
      "scheme": "hive",
      "query": "select * from {}.{} where year=2022 limit 50",
      "data_profiler_enabled": "false",
      "data_profiler_offset": "0",
      "data_profiler_limit": "50000",
      "connect_args": {
        "auth": "KERBEROS",
        "username": """ + '"' + current_user + '"' + """,
        "kerberos_service_name": "hive"
      }
    }
  },
  "sink": {
    "type": "metadata-rest",
    "config": {}
  },
  "metadata_server": {
    "type": "metadata-server",
    "config": {
      "api_endpoint": "http://localhost:8585/api",
      "auth_provider_type": "no-auth"
    }
  }
}
"""
```

1. Notice the `connect_args` part of the config, I had to kind of look through the code to see that's how I could pass Kerberos information on to sql_alchemy.  It works, just needs some docs and maybe further testing.
2. I had to hard code a partition to get some of our tables to actually import: `"query": "select * from {}.{} where year=2022 limit 50"`.  So for hive ingestion to work, it would have to run something like `show tables`, followed by `describe {table}` for each one, get the metadata from the column and table comments, then use the schema and especially the partition information to build a dynamic query.  I guess it could do `show partitions {table}` to get the partitions and try and find the most recent one, but I'm not exactly sure what the best solution is or how others solve this.  A colleague got LinkedIn's DataHub to work with this same metastore, so maybe take a look at how they do it.

**Comment by harshach** [comment]
@milimetric Thanks for the detailed descriptions. 
1. Partition key is not supported in our schemas yet hence the gap. We are going to prioritize and add this
2. We will update the docs for security for hive, cc @shannonbradshaw  
3. Once we have partition key its easy for us generate the sample only for the latest partition

@milimetric please let us know if we missed anything in this todo's. Thanks

**Comment by harshach** [comment]
@akash-jain-10 assigning this to you as we need a secure hive cluster running

**Comment by harshach** [comment]
resolved the security config docs. We yet to add the partition key as part of this ticket https://github.com/open-metadata/OpenMetadata/issues/2728
