### ISSUE TITLE
Create OpenMetadata Clients and publish artifacts

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2547]
**Is your feature request related to a problem? Please describe.**

OpenMetadata comes with rich APIs and schemas to help any tooling to either consume the rich metadata
collected in OpenMetadata or enhance/ingest metadata through the APIs.
Python based ingestion framework already has a client that allows us to ingest data into the OpenMetadata and also retrieve data from OpenMetadata. 
Ask of this feature request is to build OpenMetadata clients in other languages to start with we can 
separate Python client into its own module and publish into pypi. Similarly we can build one in java and publish
into maven artifact.

There is also a rust client in progress in this discussion https://github.com/open-metadata/OpenMetadata/issues/1880

cc @sureshms @pmbrull @mithmatt @roeap 

**Describe the solution you'd like**
1. Create separate repo to maintain the clients
2. Move all the schemas into core repo
3. Publish these clients into its respective repositories

**Describe alternatives you've considered**

**Additional context**

**Comment by mithmatt** [comment]
There is this Swagger codegen tool which may potentially help us generate the Java client
https://github.com/swagger-api/swagger-codegen#swagger-codegen-3x-300-branch

Haven't used this, but I wonder if we can piggyback on swagger specs and generate required client sdks (similar to what one would do with idls).

**Comment by pmbrull** [comment]
Do we have a javascript client? It might be useful to prioritize that as well

**Comment by mithmatt** [comment]
@pmbrull  

Based on the limited UI dev experience I had with OM, we generate typescript models from the json schema, and have a client for our own UI. The client is within our UI code and not separately managed as an npm package. 
@Sachin-chaurasiya or @shahsank3t  can confirm my understanding.

**Comment by Sachin-chaurasiya** [comment]
Hi @mithmatt , Yes, On the UI side we use `Axios` HTTP client.
