### ISSUE TITLE
UI: Fix failing unit tests and add missing tests

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#2548]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - UI

**Describe the bug**
This is related to failing and missing unit tests for UI components.

**To Reproduce**

Run `yarn test`

**Expected behavior**
0 failing unit tests and all components to have individual tests

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@darth-coder00 is this done?

**Comment by darth-coder00** [comment]
Closing as it's fixed
