### ISSUE TITLE
migrationConfiguration is missing from `conf/openmetadata-security.yaml`

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2551]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? -  backend

**Describe the bug**
While running `conf/openmetadata-security.yaml` script getting 
```
io.dropwizard.configuration.ConfigurationValidationException: conf/openmetadata-security.yaml has an error:
  * migrationConfiguration must not be null
```

**To Reproduce**
Run `./bin/openmetadata-server-start.sh conf/openmetadata-security.yaml`

**Expected behavior**
The server should have started with no errors

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya just add this https://github.com/open-metadata/OpenMetadata/blob/main/conf/openmetadata.yaml#L113 to openmetadata-security.yaml

**Comment by Sachin-chaurasiya** [comment]
@harshach, Sure.
