### ISSUE TITLE
End-to-end integration test support.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#2556]
**Is your feature request related to a problem? Please describe.**
Add integration tests for all happy path and edge cases in selenium.
Currently, some of the tests are failing due to recent changes in UI.

**Describe the solution you'd like**
- Implementing Integration test with all the happy paths covered.
- Covering all the UI/Backend reported and related bugs with extreme edge cases.

**Describe alternatives you've considered**
NA

**Additional context**
NA

## Tasks
- #2558
- #2559
  - Database Service : #2534
  - Dashboard Service :#2559
  - Messaging Service :#2559
  - Pipeline Service :#2559
- #2560
  - Tables Details
  - Topic Details
  - Dashboard Details
  - Pipeline Details
- #2561
- #2563
- #2564
- #2565
- #2566
- #2600 
- #2601
- #2602
- #2614
- #2617

**Comment by harshach** [comment]
@parthp2107 assign the milestones for the sub-tickets in this epic
