### ISSUE TITLE
Allow adding dataset level and column level lineage manually

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#256]
Reference thread created by klish@verizonmedia.com - 
https://groups.google.com/g/openmetadata-users/c/LG3L4p3uEwM/m/Oo2CbQoFAgAJ

**Comment by harshach** [comment]
@sanketbambulkar UX support needed for this.

**Comment by harshach** [comment]
Thanks for the UX mocks for the feature
![Manual Lineage - Edit](https://user-images.githubusercontent.com/38649/148297687-791dec37-74a2-4bd1-9293-80e1c3ac4651.jpg)
![Manual Lineage - View](https://user-images.githubusercontent.com/38649/148297692-ae1c6ac4-9da5-4d61-a43b-d0e9d459bc09.jpg)
