### ISSUE TITLE
Show database/entity_name in Lineage Node Label.

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2568]
**Is your feature request related to a problem? Please describe.**
We are using same names for tables in different schemas in database. There are some difficulties while using Lineage UI

**Describe the solution you'd like**
Show database/schema name in table name in Lineage UI (schema_name.table_name)

**Describe alternatives you've considered**
Rename tables in database - it's not a good solution

**Additional context**
![image](https://user-images.githubusercontent.com/2264016/152138921-60d509ca-af1e-4349-85d9-83b5acf8910e.png)

**Comment by harshach** [comment]
Thanks @igor-kramer for filing this.

**Comment by harshach** [comment]
@Sachin-chaurasiya same thing we are doing during the selection of  a node, lets add database name in there
