### ISSUE TITLE
Ingest column comment to comment description

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2572]
**Is your feature request related to a problem? Please describe.**
Some databases (Postgres, Vertica) has column comments. 

**Describe the solution you'd like**
Ingestion process can use column comment to show in description field for column

**Describe alternatives you've considered**
Manually input column description

**Comment by ulixius9** [comment]
Hi @igor-kramer, for Postgres, column comments are already supported in the ingestion framework. Please let me know if you are facing any issue in this.

(example)
![image (1)](https://user-images.githubusercontent.com/39544459/152362467-d75f961d-5159-45d3-959a-82a5d20e0d12.png)

for Vertica I've raised PR #2596

**Comment by ulixius9** [comment]
PR #2596 merged with main.
