### ISSUE TITLE
Backend is not allowing entity owner to update the lineage

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2590]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
I owned the table entity and from the linage tab if I try to update the lineage i.e adding a new edge. getting an error that you don't have permission to do this action.

PS: Using PUT API to add a new edge.

**To Reproduce**
- Go to any entity page and claim the ownership
- Now Go to the Lineage tab and try to add any new edge.

**Expected behavior**
If I am the owner of the entity then should be allowed to perform all the operations.

**Comment by vivekratnavel** [comment]
I had an offline discussion with @harshach. This is working as expected. We should not allow users (even if they own the table) to update lineage without the "Update Lineage" permission. 

We can use this ticket to track a fix in the UI. The UI should check for "Update Lineage" permission before enabling the edit button on the Lineage page.

**Comment by harshach** [comment]
@Sachin-chaurasiya closing this.

**Comment by Sachin-chaurasiya** [comment]
Reopening this, because UI change is pending.
