### ISSUE TITLE
Store view DDL in metadata

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2591]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Store database view DDL in metadata and show it in UI

**Describe alternatives you've considered**
Use Squitch to handle DDL changes

**Additional context**

**Comment by harshach** [comment]
@igor-kramer we do get the view definition https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/data/table.json#L541
Let us know if its not working for any particular data source , we will double check.

**Comment by igor-kramer** [comment]
@harshach I'm forgot to say magic word - **Vertica**. In sqlalchemy-vertica driver this feature is not realised (i fixed it manually but my code is not so pretty like @ulixius9 )

**Comment by harshach** [comment]
Thanks @igor-kramer . I should know by now :) .
@ulixius9 can we add this change.
