### ISSUE TITLE
Column data length change is not handled and the table entity version does not change

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2593]
**Affected module**
Ingestion Framework

**Describe the bug**
Change column datatype does not generate any metadata changes

**To Reproduce**
Create and modify any table in Vertica

Screenshots or steps to reproduce

```
create table public.tst_tbl
(
    ts       timestamp,
    symbol   varchar(8),
    bid      float default 1.00,
    test_col int   default 20,
    column_5 varchar(2)
);
```
Run ingestion proccess

<img width="1396" alt="Screenshot 2022-02-03 at 16 47 27" src="https://user-images.githubusercontent.com/2264016/152355207-73112a00-cda4-4d83-8c58-1cea14233c2b.png">

```
alter table public.tst_tbl alter column column_5 set data type varchar(20);
```

Run ingestion proccess

<img width="1402" alt="Screenshot 2022-02-03 at 16 49 39" src="https://user-images.githubusercontent.com/2264016/152355569-2f002a58-69e4-453b-97c6-ed3841de28c7.png">

**Expected behavior**
New version of metadata with correct datatype

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@igor-kramer this shouldn't ideally be generating the version of schema change right.
here we are still retaining the original type but the data length is changed.

**Comment by harshach** [comment]
@ayush-shah lets make sure we are getting the dataLength.
@sureshms what you think of the right approach here, same type but the length changes? could be a backward incompatible

**Comment by sureshms** [comment]
@igor-kramer and @harshach, there are couple of choices here:
1. Data length increased - we record this as a backward-compatible change.
2. Data length decreased - we record this as backward-incompatible change given some of the previous applications/jobs that were writing data of certain length can no longer use the table.

What do you guys think?
