### ISSUE TITLE
Missing hive column type during ingestion

### ISSUE THREAD

**Issue by joswlv** [open-metadata/OpenMetadata#2597]
**Affected module**
Ingestion Framework

**Describe the bug**
Hive column type obtained by reflection is omitted when ingestion is started.
There is no syntax to compare types in sqlalchemy_type enum.
- [col type compare source code](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/utils/column_type_parser.py#L149)
- [hive col type source code](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/hive.py#L36)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 0.8
 - OpenMetadata Ingestion package version: 0.8.4

**Additional context**

**Comment by harshach** [comment]
@joswlv thanks a lot for filing the ticket. We have a fix ready. Let us know if you want to give it a try , we can publish dev package into pypi

**Comment by joswlv** [comment]
@harshach After seeing the [PR](https://github.com/open-metadata/OpenMetadata/pull/2598), I made a custom build and tested it. That [PR](https://github.com/open-metadata/OpenMetadata/pull/2598) didn't solve the issue.

**Comment by harshach** [comment]
@joswlv Thanks for the review. Can you please provide some details on what types we are missing.

**Comment by harshach** [comment]
@ayush-shah lets prioritize this in Milestone 2 and get it merged in
