### ISSUE TITLE
Migrate Tag API in BigQuery

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2623]
After fixking https://github.com/open-metadata/OpenMetadata/issues/1526, we need to take a look at the changes from https://github.com/open-metadata/OpenMetadata/pull/2587 and update ometa_api and the bigquery connector to remove the ad-hoc Tag implementations and use the client Tag Mixin

**Comment by codingwithabhi** [comment]
I will work on this.
