### ISSUE TITLE
[BUG] -  Not able to set request body for the creation of Tags

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2624]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI
**Describe the bug**

We can't see param options in Tag for creating a new tag category. Same can be seen in other Post calls under Tag Categories as well.
![image](https://user-images.githubusercontent.com/40225091/152539917-ac14378a-361d-4f0f-a0d6-ecdf46b0fcea.png)

**To Reproduce**

- Go to http://localhost:8585/docs#operation/createCategory
- Click on Try It
- We can't see any param input, and on clicking Send Request we get 500 Internal Server Error

**Expected behavior**
Param / Body input being shown and can be configured in order to create / update Tag Categories.

**Comment by harshach** [comment]
@ayush-shah seems to be the issue is with how we are generating the swagger docs than the UI.

**Comment by mohitdeuex** [comment]
@shahsank3t  let me take a look on this
