### ISSUE TITLE
Log ElasticSearch calls

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2638]
**Is your feature request related to a problem? Please describe.**
If there are issues during ElasticSearch calls, we currently do not see any logs.

**Describe the solution you'd like**
Let's add logging in the backoff https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/events/AbstractEventPublisher.java#L56 for any exceptions that we may encounter
**Describe alternatives you've considered**

**Additional context**

**Comment by deweybat** [comment]
Hi! I'd like to tackle this issue.

**Comment by pmbrull** [comment]
Hi, @deweybat 🚀  Amazing, assigned it to you! Thanks a lot, let us know if you need any help

**Comment by pmbrull** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/2737
