### ISSUE TITLE
Activity Feed, Comments - Mocks 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2645]
![image](https://user-images.githubusercontent.com/38649/152717909-bbd3d637-a937-410f-aa3f-85f599177403.png)

- Activity Feed will be powered by new APIs that will chronologically show the latest activity that is happening through the change events and user comments
- Users can switch based on all activity, my data, following similar to what we have currently
- Users will have a top level text box to refer to any entity or user to start a discussion thread. Any reference to the entity will also push the thread under the entity level feed
- Users can click on the comments to expand the thread or start a new thread
- Users can see the no.of comments per each activity

![image](https://user-images.githubusercontent.com/38649/152719693-abe29b45-2e0c-44a8-af07-5e7d5d4c84a5.png)

- Clicking on any comments will expand the thread and present a text box to reply at the end of the thread.

![image](https://user-images.githubusercontent.com/38649/152718711-fd90e461-b3c8-4b0d-a124-3928a5f212c8.png)

- Similarly in Entity details page, we can have comments for all descriptions
- If there is no comments available or no one started a discussion, we should show "Reply in a thread" like in activity feed above

![image](https://user-images.githubusercontent.com/38649/152719655-af48185b-afb5-474a-ba1b-a5a0b163d655.png)

- Clicking on any of the comments button will expand a section just like versions to show all the replies so far
- At the end of the replies we should show a text area to add new reply
- The beginning of the replies should show the last edit and who edited it etc..

![image](https://user-images.githubusercontent.com/38649/152725055-a01192dc-a0a9-4a8c-8fb7-fbcb768ca447.png)

- Showing activity feed for the entity in another tab in details page
- Taking @mithmatt feedback of enabling pinned threads and allow users to filter by pinned threads. We should make pinned activity as the default filter in table's activity feed tab.

cc @sureshms @vivekratnavel @darth-coder00 @Sachin-chaurasiya @sanketbambulkar

**Comment by mithmatt** [comment]
When there are enough conversations around an entity, important information may become hard to find within a pile of comments.
Should we support ability to pin activities for an entity?

**Comment by harshach** [comment]
> When there are enough conversations around an entity, important information may become hard to find within a pile of comments.
> Should we support ability to pin activities for an entity? (Slack has this feature)

Yes this is good one, couldn't capture it in mocks but yes. We can allow users to see them as knowledge comments/feed etc.. and filter only those that are pinned

**Comment by mithmatt** [comment]
@harshach @vivekratnavel 

> We should make pinned activity as the default filter in table's activity feed tab.

Alternative to drop down based filter:
Pinned conversations could always be on the top, with the rest of the activities under it following chronological order.

Caveat: This works nice from UX point of view only if pinned items are a few (<= 5)

```
---- Pinned ----
Activity 1012 (date 12)
Activity 1028 (date 14)

---------------- (ability to sort by latest or oldest first)
Activity 1 (date 1)
Activity 2 (date 2)
Activity 3 (date 3)
Activity 4 (date 4)
```

**Comment by vivekratnavel** [comment]
I updated the wireframes to reflect the changes we would need to display multiple threads for an entity:
<img width="1007" alt="Screen Shot 2022-02-18 at 12 37 16 AM" src="https://user-images.githubusercontent.com/1051198/154647719-4db58da0-8f08-4829-8a21-bd2120af280a.png">
<img width="994" alt="Screen Shot 2022-02-18 at 12 37 27 AM" src="https://user-images.githubusercontent.com/1051198/154647751-1f3f8525-b2af-4d80-b614-c53ee52d1b9f.png">

**Comment by harshach** [comment]
@Sachin-chaurasiya @vivekratnavel closing this issue as done
