### ISSUE TITLE
[documentation][2/6/2022] local install update with linux instructions

### ISSUE THREAD

**Issue by asdiamond** [open-metadata/OpenMetadata#2646]
**Affected module**
It affects setting up a local dev env on ubuntu 20.04. 

**Describe the bug**
The docs are outdated and need a few linux specific steps. 

**To Reproduce**

Will attach specifc parts that are out of date. 

**Expected behavior**
Following all steps from start to finish allows you to install on ubuntu 20.04 without issue. 

**Version:**
 - OS: ubuntu 20.04
 - OpenMetadata version: [e.g. 0.9]

**Additional context**
n/a

**Comment by asdiamond** [comment]
I'll update these.

**Comment by harshach** [comment]
Thanks @asdiamond
