### ISSUE TITLE
SAML Auth

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2664]
**Is your feature request related to a problem? Please describe.**
Add support for securing OpenMetadata with SAML.

**Describe the solution you'd like**
We are using SAML + Google SSO as an auth method, it'd be great if that was supported as well.

**Describe alternatives you've considered**
The only current alternative is to play without security enabled.

**Comment by harshach** [comment]
some sample code https://github.com/alphagov/verify-dropwizard-saml

**Comment by harshach** [comment]
@mohitdeuex @vivekratnavel we had a brief conversation here on how backend and UI can communicate to get the auth token. Lets finish this up in 0.11.1 for both AWS and Google
