### ISSUE TITLE
Pipeline without tasks breaks ES updates

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2685]
**Affected module**
Elasticsearch

**Describe the bug**
If we create a pipeline without tasks (they are not required in the JSON schema), then the automatic ES events do not run properly. This also breaks the `metadata_to_es.json` workflow.

Cleaning the entity from the database makes everything run normally again.

We saw another issue related to pipelines without tasks in the frontend https://github.com/open-metadata/OpenMetadata/issues/2657. @harshach, should we change the code to check for tasks, or should we update the JSON schema so that tasks are required? In any case, it might be interesting to always validate that the Task list is not empty.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@pmbrull we should fix the metadata ingestion, tasks are optional.

**Comment by pmbrull** [comment]
fixed by https://github.com/open-metadata/OpenMetadata/pull/4454#issuecomment-1108115847
