### ISSUE TITLE
Service Name shouldn't contain "."

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2687]
**Affected module**
all 

**Describe the bug**
We allow users to type "." or configure serivce_name with "." on ingestion configurations. This will cause issues as we are using "." as a separator between entities such as bigquery_gcp.shopify.raw_customer . 
We should add validation just like we do in column names  https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/data/table.json#L106

**To Reproduce**
1. create a service_name with "."
2. Ingest data for that service
3. click on table belonging to that service

**Expected behavior**
Do not allow service_name to contain "." , throw a validation error. 
For this resolution simply adding service_name pattern like we have it in column_names will do it
https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/data/table.json#L106

**Comment by AdamSadek** [comment]
Hello!

To be clear, the issue is when a user types or configure _service_name_ with a "." and you want to implement a method in java that will check if the user configuration **contains** "." that should produce a message telling the user to not include "."?

Many thanks,
**Adam**

**Comment by harshach** [comment]
hi @AdamSadek sorry didn't see your comment. Please do ping us on https://slack.open-metadata.org for quick response.
I was looking at it in JsonSchema to introduce the pattern like this https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/services/databaseService.json#L147 . Looks like its resolved in another PR. Please let us know if you are interested in picking up any other issues.
