### ISSUE TITLE
UI should throw a error back to user when dependent calls fails from backend

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2688]
**Affected module**
UI

**Describe the bug**
When a important call that is necessary to layout the data fails, UI just shows white page without any indication
for the user to do what next.
1. We should throw meaningful error to the users
2. Make this as design choice, i.e lets say on a table page if the main call table is failed we should throw an error. However if profiler call fails we should show meaningful message in the tab instead of throwing an error, "Table profiler data is not available" where as table api 404 , we should throw error "Unable to get details for Table {table_name} due to {error_message}"

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Assign to me
