### ISSUE TITLE
steps for running local unit tests in linux

### ISSUE THREAD

**Issue by asdiamond** [open-metadata/OpenMetadata#2690]
**Affected module**
Docs

**Describe the bug**
Several libraries are needed to run the unit tests locally on linux that are not clearly stated in the docs and difficult to find otherwise. 

**To Reproduce**

run `mvn clean install` on a fresh linux installation. 

**Expected behavior**
The docs should say how to do this.

**Comment by asdiamond** [comment]
libraries needed to run unit tests locally on ubuntu:
```
sudo apt-get install libaio1
sudo apt -y install libssl1.0.0
sudo apt-get install libssl-dev
sudo apt install libncurses5
```

some errors encountered otherwise: 
```
com.wix.mysql.exceptions.CommandFailedException: Command 'CREATE USER 'test'@'%' IDENTIFIED BY '';' on schema 'information_schema' failed with message 'Stream closed'
Caused by: java.io.IOException: Stream closed

java.lang.RuntimeException: 
Command exited with error code: '127' and output: '/home/aleksandr/projects/OpenMetadata/catalog-rest-service/target/mysql-8.0-7e6a4d85-330d-414b-901d-b9462b664cc3/bin/mysqld: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
'
```

**Comment by mithmatt** [comment]
Existing pre-req document: https://github.com/open-metadata/OpenMetadata/blob/main/docs/open-source-community/developer/prerequisites.md
