### ISSUE TITLE
Provide entity count from backend API

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#2697]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to get only the count of a specific entity and UI is making API calls with `limit=100000` to get the total count. 

**Describe the solution you'd like**
Backend should provide a `count` field and UI will use this field to get the count for a specific entity.

**Describe alternatives you've considered**
Alternate option is sending `total` in `paging` object even if before and after are not present

**Comment by Sachin-chaurasiya** [comment]
@harshach , we will need counts for the following entities.
- Services
- Teams
- users

cc: @darth-coder00

**Comment by harshach** [comment]
@Sachin-chaurasiya this is done. Closing.
