### ISSUE TITLE
Support NoSQL databases as metadata sources

### ISSUE THREAD

**Issue by ivbeg** [open-metadata/OpenMetadata#2701]
Please support NoSQL databases like MongoDB, CouchDB, Elasticsearch and others.

**Comment by harshach** [comment]
@ivbeg we are looking into this. If you have any thoughts on how to support, please leave some comments here https://github.com/open-metadata/OpenMetadata/discussions/2629

**Comment by ivbeg** [comment]
@harshach sure, I did it.

**Comment by pmbrull** [comment]
required for https://github.com/open-metadata/OpenMetadata/issues/1076

**Comment by harshach** [comment]
We are targetting mongodb, elasticsearch for 1.0 release

**Comment by harshach** [comment]
mongodb is supported in 1.1 and elastic search will be shipped in 1.2
