### ISSUE TITLE
Tableau ingestion does not work

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2706]
**Affected module**
Ingestion Framework?

**Describe the bug**
Ingestion from tableau fails
1. Can't serialize SecretStr object
2. Fails on non-standart owner fullnames ("igor.kramer", "Jose Maria Ramirez", "Ali Abou Kamal Sallah", etc)

**To Reproduce**

metadata -ingest -c tab.json

**Expected behavior**
Ingestion without errors

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
Thanks @igor-kramer for the fix.
