### ISSUE TITLE
Add SingleStore connector

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2712]
**Is your feature request related to a problem? Please describe.**
It would be great to have single store connector.  SingleStore has 
sqlalchemy support https://docs.singlestore.com/managed-service/en/developer-resources/connect-with-application-development-tools/connect-with-python/connect-with-sqlalchemy.html

**Comment by ulixius9** [comment]
@harshach, SQLAlchemy support for SingleStore is actually mysql SQLAlchemy package, I tried to ingest SingleStore cluster with metadata mysql connector and It works fine

**Comment by harshach** [comment]
@ulixius9 lets copy the mysql code into another file called singlestore and make a separate package for it. Similarly add a doc for it a well
