### ISSUE TITLE
Store additional fields in table metadata

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2728]
**Is your feature request related to a problem? Please describe.**
Sometime we need to know some additional information about tables
- Clickhouse (Engine information, metadata_path, medatata modification date, partition key, order key, etc)
- Vertica (Storage mode, partition expression, etc)

**Describe the solution you'd like**
Some simple key-value schema which allows to store any additional parameters for specific table source

**Describe alternatives you've considered**
Query this information from source

**Additional context**

**Comment by harshach** [comment]
@igor-kramer we have tableExtensions to add custom data. However this seems to be important for general use and applies to other data sources as well. 
Can you add more details in here , we can directly add to table schema itself.

**Comment by harshach** [comment]
Partition key and order key are definitely fields that should be part of tableSchema itself.

**Comment by sureshms** [comment]
Entity extensions have been added to extend the table to include additional information. Closing this.

**Comment by Tonilyn** [comment]
Will this work for other entities? (dashboards, pipelines, topics)

**Comment by sureshms** [comment]
@Tonilyn, given this is a new feature, we just started with `Table`. It will be added for all the entities in the next release.

**Comment by sureshms** [comment]
@Tonilyn you can also contribute this code to the project :). All it requires is adding  a field called `extension` as in `table.json` to other entities. Tests are already taken care of. If you want to work on this, open an issue and we will assign this to you.
