### ISSUE TITLE
Disable deletion for Admin and Bot roles 

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2729]
**Describe the solution you'd like**
Admin and Bot roles are  reserved roles.
Hence we should avoid deleting them.

**Describe alternatives you've considered**
None

**Additional context**
See #2441 where Admin and Bot roles are being added.

**Comment by sureshms** [comment]
With the support of `providerType`, system provided entities such as roles, policies, tags, and glossaries can not longer be deleted.
