### ISSUE TITLE
[HIVE] Update documentation for HIVE kerberos security

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#2740]
- [x] Document Update for `connect_args` attribute 

```
// NOTE - This requires kerberos ticket to be already issued from kinit command....
"source": {
    "type": "hive",
    ......
    "config": {
                "connect_args": {
                        "auth": "KERBEROS",
                        "kerberos_service_name": "hive"
                 }
     }
}
```

- [x] Document update with troubleshooting step

If you come across the below issue, make sure you have all the libraries required to connect to HIVE Cluster via kerberos.

Issue -
```
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found'
```
Solution (Ref - https://stackoverflow.com/questions/30705576/python-cannot-connect-hiveserver2)-
```
// For Ubuntu
sudo apt-get install sasl2-bin libsasl2-2 libsasl2-dev libsasl2-modules libsasl2-modules-gssapi-mit
```

This is in reference to testing from issue #2533

cc - @harshach , @shannonbradshaw , @shahsank3t

**Comment by shannonbradshaw** [comment]
@akash-jain-10 I've addressed the troubleshooting portion of this ticket. Please review here:

**Comment by akash-jain-10** [comment]
LGTM! Thanks @shannonbradshaw
