### ISSUE TITLE
Blank page is displayed while adding or editing descripiton in Roles page

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#2752]
**Affected module**
UI, Backend

**Describe the bug**
If we enter special characters while adding a role in the "Name" field, while adding or editing description a blank page is displayed after saving on the UI.
In the backend, we are getting role not found error

**To Reproduce**
1. Create a role with special characters in Name field
2. Add or Edit the existing description text and click on Save
3. Blank page will be displayed. 
![Screenshot from 2022-02-14 18-47-56](https://user-images.githubusercontent.com/67048554/153871428-601016cf-f665-4ee2-a27a-d4bf2eaba4e5.png)

**Expected behavior**
Updated description should be displayed.

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**
NA

**Comment by mithmatt** [comment]
I took a cursory look at this problem

The Test role I created has special characters
![Screen Shot 2022-02-20 at 1 33 10 PM](https://user-images.githubusercontent.com/5906984/154865245-fc0d38ab-41cf-4212-b16f-c7f9e9bffc47.png)

When the UI makes a GET request with /roles/name the name is incorrectly set up in the request

![Screen Shot 2022-02-20 at 1 32 25 PM](https://user-images.githubusercontent.com/5906984/154865256-273cd21f-8c5b-4c9f-ba50-2123e1ba4df5.png)



We may need to parse the name correctly, perhaps with url encoding before making a request.
I haven't looked into what could potentially go wrong in the backend yet.
