### ISSUE TITLE
Create diagrams for entity relationships for documentation

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2758]
We should add some pictorial representations of relationships in documents, sometime in the future.

_Originally posted by @mithmatt in https://github.com/open-metadata/OpenMetadata/pull/2756#discussion_r806353322_

**Comment by mithmatt** [comment]
Refer https://github.com/open-metadata/OpenMetadata/blob/main/docs/open-source-community/developer/entities/relationship.md

**Comment by sanjeev0210** [comment]
The link throws a 404. Please do update it

**Comment by YashasviChaurasia** [comment]
@mithmatt I would like to work on this issue.
Do kindly update the link to avoid any confusion.
Thank you

**Comment by Suhas2002** [comment]
I would like to work on this issue
Can you assign it to me?

**Comment by harshach** [comment]
@Suhas2002 assigning it to you. @YashasviChaurasia hope you didn't started on this but let us know if you would like to pickup another ticket

**Comment by Suhas2002** [comment]
Hey @harshach 
Can you give more information on the issue
The link above is throwing error 404

**Comment by YashasviChaurasia** [comment]
> @Suhas2002 assigning it to you. @YashasviChaurasia hope you didn't started on this but let us know if you would like to pickup another ticket 

Yes I would like to pickup on another ticket.
Thank you

**Comment by Suhas2002** [comment]
> Hey @harshach Can you give more information on the issue The link above is throwing error 404

@harshach Hey, Help me with this please

**Comment by harshach** [comment]
@pmbrull do you have this doc anywhere?

**Comment by pmbrull** [comment]
hi folks, this is the original doc [file](https://github.com/open-metadata/OpenMetadata/blob/0.9.0/docs/open-source-community/developer/entities/relationship.md).

Please, note that from 0.9 to the current version, some of these relationships might have been updated (specially in terms of users, teams, roles and policies).

You might need to revisit the Entities JSON Schemas and check what `EntityReference`s we have listed in there to prepare the correct and updated doc.

For example, in the case of a [Table](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/data/table.json#L737), that has a reference to a `databaseSchema`. This reference is a relationship between two Entities. In this case that would mean that a Database Schema contains a Table.

**Comment by pmbrull** [comment]
@Suhas2002 we have some diagrams around the docs, e.g. https://docs.open-metadata.org/main-concepts/high-level-design

Anything with similar style (used draw.io) will be good here. Thanks
