### ISSUE TITLE
Doc: Update the Okta integration doc

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#2773]
**Affected module**
Docs

**Describe the bug**
The public key url we recommend [here](https://docs.open-metadata.org/install/enable-security/okta-sso/okta-config) is incorrect

Users will hit the following error:
```
An exception with message [No key found in <hostname>/oauth2/default/v1/keys with kid <kid>] was thrown while processing request.
```

**Fix**
Update the url to 
```
publicKey: "https://{okta_domain}/oauth2/v1/keys"
```

**Comment by harshach** [comment]
@shannonbradshaw please the step 5 and image from this page https://docs.open-metadata.org/install/enable-security/okta-sso/okta-server-creds . Those are wrong configs.
We cover these configs in the next step anyway

**Comment by lihan** [comment]
Any reference to `openmetadata-security.yaml` seems outdated as well, it should be just `openmetadata.yaml`

**Comment by harshach** [comment]
@vivekratnavel @ayush-shah can we take this up post release
