### ISSUE TITLE
Container Security Scanning for public OpenMetadata images

### ISSUE THREAD

**Issue by lihan** [open-metadata/OpenMetadata#2774]
We use the official image from helm chart.

Please consider to add a container security analysis for your public images. For open source projects, they usually free, this makes it more comfortable used in a company. Eg.. https://snyk.io/

**Comment by harshach** [comment]
@akash-jain-10 we are doing this already right?

**Comment by lihan** [comment]
Please publish the security scanning result somewhere, thanks.

**Comment by akash-jain-10** [comment]
Thanks @lihan for bringing this up. At the moment, we do not have a vulnerability scan configured on docker images. We plan to configure it latest by next release.

Meanwhile, we are currently following vulnerability scan reports from [Open Metadata Helm Charts](https://artifacthub.io/packages/helm/open-metadata/openmetadata?modal=security-report) which covers our openmetadata/server docker image.

Let us know if this is a blockage for you. we will surely prioritise this!

**Comment by harshach** [comment]
@lihan does the reports from helm charts work for you?

**Comment by akash-jain-10** [comment]
Hello @harshach , Update on this one - 
We now have Docker Images Container Vulnerability Scanning Available in [Synk](https://app.snyk.io/org/harshach/projects).

Closing this ticket for the same!
