### ISSUE TITLE
Need all icons linear and with same thickness

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#2783]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - UI

**Describe the bug**
Some icons are thicker than others

**To Reproduce**
Look at the Search and other Navbar icons here
<img width="1012" alt="Screenshot 2022-02-16 at 11 46 03 AM" src="https://user-images.githubusercontent.com/86726556/154207330-a50a5f36-8647-40ca-b20e-fbb1f8e8714b.png">

**Expected behavior**
All icons across different pages should have with lines of same thickness, i.e. thinner lines here, and with same color

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
None

**Comment by harshach** [comment]
@sanketbambulkar can you take this up

**Comment by darth-coder00** [comment]
- [ ] Use consistent line-based icons with the same consistent grey color (this is from generate a secret key on webhooks page). We should change the trashcan/delete icons everywhere.
<img width="116" alt="image" src="https://user-images.githubusercontent.com/1417689/156625638-9b01fe61-3832-4f65-b130-feba5ed862ba.png">

**Comment by darth-coder00** [comment]
- [ ] Search
- [ ] Delete
- [ ] My data left panel
- [ ] Settings dropdown arrow
- [ ] Version
- [ ] Edit
- [ ] Regenerate secretKey icon (Webhooks)

**Comment by darth-coder00** [comment]
Closed in #3916
