### ISSUE TITLE
Vertica lineage

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2785]
**Is your feature request related to a problem? Please describe.**
We can ingest lineage from Vertica system tables

**Describe the solution you'd like**
Ingestion process will generate some lineage entities between tables/views in Vertica

**Describe alternatives you've considered**
We can do it manually via UI

**Additional context**

**Comment by igor-kramer** [comment]
@harshach I'll do it by myself in 1-2 weeks

**Comment by harshach** [comment]
@igor-kramer thats great. We are building a lineage parser util that might be helpful for you as well.
cc @ayush-shah please update the ticket when you have the query parser for lineage part available here.

**Comment by igor-kramer** [comment]
@harshach we don't need query parser, Vertica/Postgres has system tables which handle relations between views and tables

**Comment by harshach** [comment]
@igor-kramer if thats the case you can just add the relationship directly using the AddLineage API
@ayush-shah can you paste an example here

**Comment by ayush-shah** [comment]
Hey @igor-kramer, this is how we create a Lineage and yield it to metadata_rest which handles the AddLineage API.
we provide the fqn's for fromEntity(Upstream) and toEntity(DownStreamr)

        def create_lineage(self, from_entity, to_entity):
                lineage = AddLineageRequest(
                    edge=EntitiesEdge(
                        fromEntity=EntityReference(
                            id=from_entity.id.__root__,
                            type="table",
                        ),
                        toEntity=EntityReference(
                            id=to_entity.id.__root__,
                            type="table",
                        ),
                    )
                )
                return lineage

**Comment by harshach** [comment]
@ayush-shah is this done?

**Comment by ayush-shah** [comment]
We have added support for the ingestion of lineages from view definitions for Vertica.

**Comment by ayush-shah** [comment]
Closing this issue.
