### ISSUE TITLE
Auto populate View Lineage to Tables

### ISSUE THREAD

**Issue by kevinbtai** [open-metadata/OpenMetadata#2809]
**Is your feature request related to a problem? Please describe.**
For data warehouses like Snowflake, we have a bunch of views created by other teams using our source data.  It would be helpful if lineage can be automatically populated for views to their source tables so it is easier to track which users/queries rely on certain data.

**Describe the solution you'd like**
Lineage for views is automatically created and attributed to the source tables.

**Comment by igor-kramer** [comment]
Wow! I'll wait your MR and after I can add the same functionality for Postgres/Vertica.

**Comment by harshach** [comment]
@ayush-shah lets run the viewDefinition to lineage runner and we should be able to connect to the upstream tables here. 
Only edgecase here is if the view is in database y and its depends on the database x tables. But if we are processing database y tables/views first we won't be able to link it. But this should resolve in the next run as all the tables are available in the next ingestion cycle
