### ISSUE TITLE
UI: Differentiate between tables and views

### ISSUE THREAD

**Issue by kevinbtai** [open-metadata/OpenMetadata#2810]
**Is your feature request related to a problem? Please describe.**
There is no way in the UI to be able to tell whether a data source is a table or a view.  For connections like Snowflake, there can be views built on top of views and it will be helpful to know how many views are being chained in lineage.  As a data engineer it is helpful to know how many views exist for a certain dataset to help manage how data is being accessed.

**Describe the solution you'd like**
1. Being able to filter for views only
2. Some identifier showing view or table when looking at the metadata of a data source
3. Lineage icon for views

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya is this done?

**Comment by harshach** [comment]
@Sachin-chaurasiya This is P0 we need to fix this in 0.9.1
