### ISSUE TITLE
OMeta API should use a single logger

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2830]
**Feature**
No ref

**Describe the task**
In `ometa_api.py` and its Mixins, we are always using `logger = logging.getLogger(__name__)`.

This will generate a high number of loggers and might make it difficult to track where the trace comes from.

We should create a single logger for the whole Python Client and use it as `logger = logging.getLogger("OMetaAPI")` or a better name for those with more creativity

**Comment by mithmatt** [comment]
From python docs:

```
A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:

logger = logging.getLogger(__name__)
This means that logger names track the package/module hierarchy, and it’s intuitively obvious where events are logged just from the logger name.
```

Isn't it easier to trace with package/module level loggers since the logger itself tells where it is being logged from?

**Comment by pmbrull** [comment]
Hi @mithmatt, I actually had this discussion a few times already and I am not fully convinced myself either.

If we use the `logging.getLogger(__name__)`, we are going to be creating a new logger per each file. If people are not familiar with the project, and considering there are filenames repeated, such as `utils.py`, it might get a bit harder to read for users.

By having a single logger per project vertical, such as profiler or python API, I wanted to ease out the reading process without having to go into project-specific design. For example, it does not really matter if a log gets generated in `ometa_api` or any of its Mixins, as we are still talking about the python client.

If there is an exception, the traceback should be good enough to help us pinpoint the issue anyway.

WDYT?

**Comment by pmbrull** [comment]
That would be a good solution. My only concern here is that workflows are thought to be run mainly in Airflow. If any user configures them inside a DockerOperator, we would lose the file log

**Comment by mithmatt** [comment]
> That would be a good solution. My only concern here is that workflows are thought to be run mainly in Airflow. If any user configures them inside a DockerOperator, we would lose the file log

That is a valid concern.

The only reason why the approach I mentioned above worked is because the file based logs were on the host (non-docker deployment)

Many companies have something like filebeat to ship container logs to a central location - I suppose we cannot make that assumption here. 


Another possible idea: Based on log levels use different formatters (DEBUG has verbose version to show lines)

PS: The complexity I'm proposing to solve this may be an overkill. We should resort to your original proposal and rely on line number for exception stack traces

**Comment by pmbrull** [comment]
Yup, I would stick to a simple first approach to have an easy-to-read trace without a ton of paths. Then, if users face issues, extract the info from the traceback

**Comment by harshach** [comment]
@pmbrull @ayush-shah can we handle this rightaway as its breaking the ingestion logs right now
