### ISSUE TITLE
Ingestion - Multiple Primary Keys in Table Error

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2832]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion
**Describe the bug**
Whenever a Table has multiple primary keys in tables, it throws error
`[2022-02-17 23:19:03,805] ERROR    {metadata.ingestion.sink.metadata_rest:222} - Multiple columns tagged with primary key constraints
`
**To Reproduce**
- Create table with multiple primary key columns
- Ingest the same

**Expected behavior**
It should create TableConstraints and ingest the same

**Comment by harshach** [comment]
@Sachin-chaurasiya are we handling TableConstraint data from table entity in UI.

**Comment by ayush-shah** [comment]
Closing this issue as it was fixed with #2854 
Created a separate ticket #2887 to handle the UI related changes
