### ISSUE TITLE
UI: Sandbox page overflows from the bottom

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2833]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI
**Describe the bug**
The UI overflows from the bottom on Mac M1 
**To Reproduce**
- Go to https://sandbox.open-metadata.org/signin
- Scroll down at the end

**Screenshots or steps to reproduce**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/40225091/154543911-0df8ed6a-f406-421f-ad8d-a293a4ac830a.png">

**Expected behavior**

**Comment by ShaileshParmar11** [comment]
Assign to me
