### ISSUE TITLE
Move core definitions to ingestion-core

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2848]
Tackled as part of:
- https://github.com/open-metadata/OpenMetadata/issues/4698

**Is your feature request related to a problem? Please describe.**
We currently have core definitions such as `Source`, `Sink`, `Workflow`... and general configurations under the `ingestion` module. However, with the addition of the `orm_profiler`, some definitions are also reused there. ~~We might want to skip the dependency from the profiler to the ingestion~~ Actually, we will need all the SQL connectors, so there's a forced dependency in there. It might still make sense to have a clear separation between core concepts and specific implementations

**Describe the solution you'd like**
It might be interesting to reorganise a bit the package to have generic definitions and abstract classes under ingestion-core. This way, we can easily extend them for `ingestion` or `orm_profiler`.

**Describe alternatives you've considered**
Stick to what we currently have

**Additional context**

cc @harshach

**Comment by harshach** [comment]
+1

**Comment by pmbrull** [comment]
Let's also try to tackle this [comment](https://github.com/open-metadata/OpenMetadata/pull/2900#discussion_r811455888) -> When loading sources, processors and sinks, be more generic on where do we pick packages from
