### ISSUE TITLE
Python API Walkthrough Error

### ISSUE THREAD

**Issue by havardnyb** [open-metadata/OpenMetadata#2852]
**Affected module**
Python API(?)

**Describe the bug**
Was going through the walkthrough for python API. Pasted the lines from Walkthrough step 2. Create the DatabaseService, and got a validation error. I added the line (databaseConnection = "") just to try it out, and the code ran without errors. But i found that a little weird because the string is empty.

**To Reproduce**
Walkthrough step 2. create the DatabaseService. Before adding create_service.json().

![Screenshot 2022-02-18 at 15 31 48](https://user-images.githubusercontent.com/62031396/154702498-c4fdf98a-19d4-480c-874a-5bf3f3a004c7.png)

The code ran without bugs after adding databaseConnection = ""
![Screenshot 2022-02-18 at 15 37 02](https://user-images.githubusercontent.com/62031396/154703903-051df794-1da3-4963-8ae6-247cd02518d0.png)

**Expected behavior**
Expected my code to run like it did before adding the lines, because im not doing anything with "create_service" yet, and because im getting the code directly from the walkthrough.

**Version:**
 - OS: IOS
 - Python version: 3.8.2
 - OpenMetadata version: 0.8.7
 - OpenMetadata Ingestion package version: latest from yesterday

**Comment by pmbrull** [comment]
We'll need to update all the Python examples to match the new schema structure
