### ISSUE TITLE
Build profiler sink

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2875]
**Feature**
Based on https://github.com/open-metadata/OpenMetadata/issues/1311

**Describe the task**
Update the OM Python client and build the sink to send the profiler and test results to the OM API.

**Comment by mithmatt** [comment]
I hope the structure of the sink is in such a way that we can extend the implementation in the future to support an external sink such as CloudWatch of OpenTSDB, and make the metrics queryable through Grafana (iframe view embedded in OpenMetadata)

https://grafana.com/docs/grafana/latest/datasources/opentsdb/

**Comment by pmbrull** [comment]
The goal of the sink is to pick up the data structures created during the profiling and push them somewhere. We will start by preparing the OM sink, which will make some API calls to OM itself. We can create other sinks as needed, and they get configured in the JSON, e.g.,

```
"sink": {"type": "metadata-rest", "config": {}},
```
