### ISSUE TITLE
Profiling and testing complex types

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2879]
**Feature**
Based on https://github.com/open-metadata/OpenMetadata/issues/1311

**Describe the task**
We need to figure out and implement how we want to handle complex types. Specifically, arrays, struct, and geo.

**Comment by harshach** [comment]
@pmbrull @TeddyCr lets plan when can we get to this

**Comment by pmbrull** [comment]
IMO we can handle this in 0.12

**Comment by TeddyCr** [comment]
Closing this one as we'll be tracking in by connector.
