### ISSUE TITLE
Add data-catalog tag to OpenMetadata github project

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2880]
Add data-catalog tag to OpenMetadata github project to make the project more discoverable

<img width="308" alt="image" src="https://user-images.githubusercontent.com/5906984/154862235-0cdd1cca-eb1a-491e-82ea-1758587446e9.png">

cc: @harshach  @sureshms  - only project owners may be able to do this

**Comment by harshach** [comment]
we are already at max 20 tags for the project. Cannot add new ones

**Comment by mithmatt** [comment]
We could potentially trade metadata-extraction for data-catalog, based on my understanding of the relevance. 

Projects in https://github.com/topics/metadata-extraction do not seem to be in the same league as OpenMetadata

**Comment by harshach** [comment]
@mithmatt done

**Comment by mithmatt** [comment]
Much better 

https://github.com/topics/data-catalog?o=desc&s=stars
