### ISSUE TITLE
Reconcile relationship functions in EntityRepository and EntityRelationshipRepository

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2886]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Simplify the backend codebase

There is overlap between EntityRepository.java and EntityRelationshipRepository.java , such as addRelationship function.

**Describe alternatives you've considered**
None

**Additional context**
None

cc: @sureshms

**Comment by sureshms** [comment]
`EntityRepository` is a base class for all Entities. `EntityRelationshipRepository` is a repository class for `entity_relationship` table following the convention that there a repository class per table.

**Comment by sureshms** [comment]
Btw I saw the code `EntityRelationshipRepository` just now. Not sure why we need to initialize seed data etc... @mithmatt, let's talk about this.

**Comment by sureshms** [comment]
This is no longer relevant
