### ISSUE TITLE
Add information on how to use env variables and airflow variables for workflows

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2904]
Add docs on how to configure safe retrieval of sensitive information of the workflows, such as passwords.

Add info on env vars and airflow vars

**Comment by harshach** [comment]
@pmbrull what are we planning to do here?

**Comment by pmbrull** [comment]
hi sorry been pushing this out. I'll prep a quick example

**Comment by pmbrull** [comment]
ok forgot we had that https://docs.open-metadata.org/v1.0.0/connectors/credentials#using-airflow-connections
