### ISSUE TITLE
SingleStore icon is missing

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2921]
I'm using OpenMetata up to commit 647712c39772f54c43f5f0b0d8ae5a37c14ac837 and SingleStore doesn't have an icon.
#
<img width="732" alt="image" src="https://user-images.githubusercontent.com/32617/155152913-bfb97831-6e49-4adb-aa44-1a3b97cb8b5b.png">

**Comment by Sachin-chaurasiya** [comment]
@sanketbambulkar Please provide an icon for new services.
cc: @darth-coder00
