### ISSUE TITLE
Add a User through Users page

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2932]
**Affected module**
UI, Ingestion
**Describe the bug**
Helm chart based cluster doesn't ingest any users data. This means there are no users 
and there is no way to create ingestion without an active user

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Assign this to me.
