### ISSUE TITLE
Vertica Timestamp column fix

### ISSUE THREAD

**Issue by codingwithabhi** [open-metadata/OpenMetadata#2945]
**Describe the bug**
Ingestion fails in Vertica with Timestamp Column.

**Comment by harshach** [comment]
@ayush-shah moving this to 0.10

**Comment by ayush-shah** [comment]
Couldn't reproduce the same, should we close the issue for now and reopen if reproduced in the future?
cc: @harshach

**Comment by harshach** [comment]
closing this. Please re-open if you see this issue again
