### ISSUE TITLE
Add usage for Kafka service

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#295]
Currently, we have usage for database services only and not for Messaging services (for eg. Kafka ). 
need to add usage for messaging services as well.

**Comment by sureshms** [comment]
This won't be done for 0.4 release. Moving it out. @Sachin-chaurasiya UI should handle this for Tables, Topics, Dashboards

**Comment by Sachin-chaurasiya** [comment]
> This won't be done for 0.4 release. Moving it out. @Sachin-chaurasiya UI should handle this for Tables, Topics, Dashboards

@sureshms Yes, we are handling this on the UI side.
