### ISSUE TITLE
Add or remove users from teams permission

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#2950]
Hello,

Here at my company we want to give the permission to add or remove users from teams to the data managers, but Openmetadata doesn't has this possibility yet. It would be very could to add this permission to a role.

 A second step, but I think it is a more complicated one, it is the possibility to give permission to a person to manage only specific or a list of teams.

thank you

**Comment by mithmatt** [comment]
@rubenssoto  

Possible related question:
At your company, do you sync users from a system like LDAP or directly create users from OpenMetadata UI?

**Comment by harshach** [comment]
@mithmatt they are using SSO to login and it will prompt the sign up page.
@rubenssoto 
1. When the user signups they will get a prompt to chose a team 
2. Right now it will list all the teams available , which means users can be part of all teams or any team. Do you want to restrict this?
3. If So we can provide a config option to disable this behavior so when user sign ups they won't be assigned to any team
4. Next admin can create a role and designate user to manage team or teams . Now that person needs to add or remove users from teams

**Comment by mithmatt** [comment]
For 4, we can add a new permission called UpdateTeam which can be assigned to a role. And ensure that this is enforced at team API level

**Comment by mithmatt** [comment]
See mocks in #3057

**Comment by mithmatt** [comment]
For 0.9 release let's attempt a smaller scope: " give the permission to add or remove users from teams to the data managers" to get a preview of the feature out

**Comment by mithmatt** [comment]
We have implemented the part where one can create a role and provide the role permissions to update users in all teams.

**Comment by mithmatt** [comment]
Tasks:

- [ ] #3056 
- [ ] #3152
