### ISSUE TITLE
Assign roles to teams not only to users

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#2951]
hello,

It would be good if openmetadata offers the possibility to assign roles to teams too, not only to users.

Thank you

**Comment by pmbrull** [comment]
Thanks, @rubenssoto, for reaching out.

@mithmatt, is this related to https://github.com/open-metadata/OpenMetadata/issues/2883?

Thanks!

**Comment by mithmatt** [comment]
Thanks for bringing this to my attentoin @pmbrull 

@rubenssoto  Can you check #2762 and see if it satisfies this use case?
If yes, let's close this issue as duplicate.

**Comment by rubenssoto** [comment]
@pmbrull @mithmatt yeah, I think it is the same thing

Thank you!!!

**Comment by mithmatt** [comment]
Thanks for confirming, closing this so we can track everything in #2762
