### ISSUE TITLE
Adding custom tags and tag categories with code

### ISSUE THREAD

**Issue by havardnyb** [open-metadata/OpenMetadata#2952]
Hi.
I have followed the walkthrough for the python API and its working really good so far. I have the idea is to use keywords from datasets that my program reads as tags. I have done some digging in the documentation and here on github, but i cant find a way to submit new tags or tag categories like you do in settings, with code. Is this possible to do at the moment? it would have been really nice to be able to fetch a list or something with the current tag categories and their children, and to be able to add custom categories and tags with the code.

**Comment by havardnyb** [comment]
I will check it out. Thank you!

**Comment by pmbrull** [comment]
Also, if you want more information about the API definition you can check the docs on the [sandbox](https://sandbox.open-metadata.org/docs). You'll need to sign in and click on the link again.

Note that the Python API is just a wrapper on top of the backend API. If you find something on the API missing on the Python side, feel free to let us know

**Comment by harshach** [comment]
@havardnyb Please let us know if you have any feedback on the API
