### ISSUE TITLE
Can you please support connector for Qlik view and Qlik Sense

### ISSUE THREAD

**Issue by tufanrakshit** [open-metadata/OpenMetadata#2957]
**Is your feature request related to a problem? Please describe.**
looking for connector from Qlik View and Qlik sense

**Describe the solution you'd like**
looking for connector from Qlik View and Qlik sense

**Describe alternatives you've considered**
Collibra

**Additional context**

**Comment by pmbrull** [comment]
for this we can use https://pypi.org/project/qlik-sdk/#description
