### ISSUE TITLE
Ingestion from UI should throw better error when Airflow is not configured with OpenMetadata Instance

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#2964]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI bug when using Open Metadata Helm Charts and spinning up instance.

**Describe the bug**
Below are the steps I performed -
 - Install open metadata from helm charts
 - Add a service (example redshift)
 - Add ingestion without airflow configuration
 - UI Lets you add Ingestion for the first time
 - UI does not display appropriate error if ingestion fails

Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/15995028/155466967-5ce81059-7eed-47c7-b152-6ef44b0e73f5.png)

https://user-images.githubusercontent.com/15995028/155470405-d73f15aa-344e-4c6c-8c05-591ca31ac52d.mov

**Expected behavior**
UI should not let you add ingestions if no Airflow configuration is setup

**Version:**
 - OS: Linux
 - OpenMetadata version: 0.8.4

**Comment by harshach** [comment]
@pmbrull it would be good to support /status on the airflow APIs side. OpenMetadata can make this call and see if the Airflow that the user configured has our APIs, if not throw an appropriate error response.
