### ISSUE TITLE
Extract lineage from AWS Managed Airflow

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2978]
**Is your feature request related to a problem? Please describe.**
It would be great if we can support extracting lineage from managed Airflow

**Describe the solution you'd like**
Airflow lineage extraction requires one to add the LineageBackend code that we provide.
However there are many users who will be using managed airflow to run their dags. 
Managed Airflow requires one to upload their Python DAGs to S3.
One way we could do this is to ask users to configure their s3, download the dags and load them into
Airflow dagbag and parse the inlets, outlets.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by harshach** [comment]
@pmbrull can we close this?

**Comment by pmbrull** [comment]
I'll close this as a duplicate, but we still need to get the environment running @vijaypm
