### ISSUE TITLE
ImportError - Numpy - Ingestion

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2980]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
Numpy Dependency added in histogram.py(orm profiler) causes the sample_data ingestion to fail.

**To Reproduce**
Create new env
Install dependencies and generate new models
Ingest Sample Data

If numpy is not being used anywhere, we can remove the dependency.
if it's being used somewhere, we can add it in base requirements or create a new plugin
cc: @pmbrull @harshach

**Comment by pmbrull** [comment]
Thanks @ayush-shah , added it already in the PR I am working on
