### ISSUE TITLE
Table is not formatted correctly when a new Tag Category is added

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2985]
**Affected module**
UI

**Describe the bug**
Table is not formatted correctly when a new Tag Category is added
The column widths are not consistent, with existing tag category table

**To Reproduce**

![image](https://user-images.githubusercontent.com/5906984/155667627-84a140cc-9853-43de-959b-c654746a8710.png)
![image](https://user-images.githubusercontent.com/5906984/155667714-be40c32f-7a77-49a2-9bc2-b63e5f5e62f7.png)

**Expected behavior**
Table column widths remain the same

**Version:**
 - Python version:
 - OpenMetadata version:  0.8 sandbox deployment
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
None

**Comment by Sachin-chaurasiya** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/59080942/162903396-c2d652fe-adbb-4b46-9bf6-cadef4d65f5b.png">
Closing This.
