### ISSUE TITLE
Support to provide team deletion and team member removal functions in the UI

### ISSUE THREAD

**Issue by joswlv** [open-metadata/OpenMetadata#3001]
It would be nice to be able to control the team deletion and team deletion functions, which are currently only available as an API, from the UI.

The feature supported by the admin UI are summarized as follows.

- Delete team
- Remove team members

**Comment by Sachin-chaurasiya** [comment]
cc: @darth-coder00

**Comment by darth-coder00** [comment]
Removing of users from team is already supported for Admins and Users with UpdateTeam permissions
