### ISSUE TITLE
Delete Tags and Tag Categories

### ISSUE THREAD

**Issue by havardnyb** [open-metadata/OpenMetadata#3013]
Hi!

I have figured out how to add new tags and categories to use custom tags. But I would also like to have the opportunity to remove the tags and categories, so that I can clean up the space. I saw that you did not have the opportunity  to remove them in the localhost server, but do you have any functions that I can use, or ideas to make this work?

**Comment by havardnyb** [comment]
Would also be nice to be able to remove a database or a database service with code

**Comment by Sachin-chaurasiya** [comment]
cc: @darth-coder00

**Comment by harshach** [comment]
@Sachin-chaurasiya @darth-coder00 delete APIs for tags are now supported. Let's add support for it in UI.
cc @vivekratnavel
