### ISSUE TITLE
Support policy authoring through UI (outside of role page)

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3031]
**Feature**
#2907

**Describe the task**

With permissions granted to a specific team (which may not necessarily have its own role), we need to think about supporting policy authoring through UI (outside of role page)

**Comment by sureshms** [comment]
@Sachin-chaurasiya this is UI-only work. The backend already supports this.

**Comment by Sachin-chaurasiya** [comment]
Completed with #6863
