### ISSUE TITLE
Update datamodel-codegen version

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3044]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
`datamodel-codegen` has released some minor versions since we started using it. The interesting point is that it now supports black 22, so we should take a spin at this and try to play with the upgrade of both libs.

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
@pmbrull lets do this in 0.10 release?

**Comment by pmbrull** [comment]
done
