### ISSUE TITLE
User friendly messages in landing page

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3053]
**Feature**
Can we make this messages sound better
<img width="350" alt="image" src="https://user-images.githubusercontent.com/38649/156229340-8b37feea-ae34-46b3-92c0-3fd81d30487f.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/38649/156229363-c155c2f2-3faa-468e-9ded-c019bdc365c1.png">

cc @ShilpaVernekar

**Comment by ShilpaVernekar** [comment]
@harshach - Please review.
**My Data**
No data to display.

**Following**
No data found. Start following.

**Recent Views**
No recent views.

**Recent Search Terms**
No recent searches.
