### ISSUE TITLE
Sonar coverage information is missing

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3054]
**Affected module**
Backend

**Describe the bug**
Backend PRs - Sonar coverage info is missing 

**To Reproduce**

No coverage reported on main branch and on PRs

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/5906984/156235060-5b2e3147-36b7-4ee8-aec5-8b7a36296547.png">
**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
Yeah ingestion sonar has something misconfigured. I have a ticket about this too somewhere. Ill pick this up after 0.9
