### ISSUE TITLE
Mocks for new access control related features

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3057]
**Feature**
#2460 #2762 #2950

**Describe the task**
Mocks for new access control related features

**Comment by mithmatt** [comment]
**Ideas for different pages/components:**

Role 
- Add a checkbox at the top for set as default

Role -> Policy:
- Move Add new rule button inside the Policy tab view - this ensures that this button is self-descriptive on what it does. 

Role -> Teams:
- Introduce a new teams tab
- Add a new button "Add team" - this enables assigning a role to a team 

Role -> Users:
- Inside User tab, support bulk adding/removing users for the role using multi-select checkbox (this same semantic needs to be supported in Teams -> Users tab)

Settings -> Teams
- Make Teams visible in dropdown if user has UpdateTeam permission


cc: @harshach  @vivekratnavel

**Comment by mithmatt** [comment]
https://doejo.com/blog/solutions-for-implementing-user-friendly-multi-select/

**Comment by mithmatt** [comment]
**For 1**
![Screen Shot 2022-03-01 at 3 26 19 PM](https://user-images.githubusercontent.com/5906984/156266452-6b499ef5-054e-420b-82ed-2a5a21a26c21.png)

**For 2**
This needs to be done for all the pages which have similar tabs. The tab specific button should be moved within the tab.
![Screen Shot 2022-03-01 at 3 26 03 PM](https://user-images.githubusercontent.com/5906984/156266526-25c7de3e-f0ed-4ab3-80ff-2ed663bb9d7c.png)

**For 3**
![Screen Shot 2022-03-01 at 3 26 11 PM](https://user-images.githubusercontent.com/5906984/156266651-e95b9534-bd10-44df-9c30-03c30b3d99ee.png)


**For 4 and 5**
![Screen Shot 2022-03-01 at 3 26 55 PM](https://user-images.githubusercontent.com/5906984/156266504-516f8f7d-d9f0-4c24-a229-ebb97fc20fbb.png)

**Comment by mithmatt** [comment]
To help with prioritization order based on end-to-end features:

Highest to lowest 
1, 4, 3+5

**Comment by harshach** [comment]
@Sachin-chaurasiya please check these mocks. work with @mithmatt to get them in this release. Thanks
