### ISSUE TITLE
Sort users within teams page

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3058]
**Affected module**
UI 

**Describe the bug**
The list of users in the teams page is not sorted. 
To make it easily readable, we should sort it in lexicographical order

**To Reproduce**

Navigate to teams page and check Users tab
![image](https://user-images.githubusercontent.com/5906984/156255766-bcaf9bf7-1af8-4222-9f93-aad2aab0aabe.png)

**Expected behavior**
Users are sorted

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
We may need to do this for all entities which are displayed on tabs within an entity page.

Eg:
- Users for a Team (this issue)
- Assets for a Team
- Roles for a Team

This could be possibly fixed from the backend by returning all entity reference lists as sorted lists.

cc: @harshach  @sureshms @vivekratnavel

**Comment by ShaileshParmar11** [comment]
Kindly assign this to me.
