### ISSUE TITLE
Improve multi-select UI experience for updating users within the team

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3060]
**Is your feature request related to a problem? Please describe.**
Improve multi-select UI experience for updating users within the team such that it can support both add and remove of users from the team. 

With more features that rely on multi-select for adding/removing relationships between entities, we'll need to have a better user experience for facilitating these changes easily through the UI.

Possible examples:
- Selecting users in a team
- Selecting teams that should have a role set as default role
- Selecting users who should have a role
- Setting tags to a set of assets in bulk (similar to adding labels to multiple github issues)?

**Describe the solution you'd like**
![Screen Shot 2022-03-01 at 4 10 51 PM](https://user-images.githubusercontent.com/5906984/156270110-a65f5869-e93e-4c75-a871-b6f13be40a47.png)
![Screen Shot 2022-03-01 at 4 10 58 PM](https://user-images.githubusercontent.com/5906984/156270126-c55b9aae-a059-49db-91a2-3a43540d0751.png)

Key areas of change:

1. 'Select' instead of 'Add' supporting both bulk add and remove of users from the same page
2. Display selected count so that the customer knows how many users are selected as part of the team
3. Sort the users list with all selected users first, then lexicographically sorted - so that it is easy for customer to scroll through and find the user with visual binary search if needed 
4. Display the unselected users after the selected users. Click on checkbox of unselected user will automatically move the unselected user to the top (sort on any select/deselect action - this shouldn't take much time for 1000 users on the UI with an appropriate sorting algorithm)
5. Scroll bar extends across both sections as indicated in 3 and 4. Scrolling down means selected users go out of frame from the top first, before unselected users start going out of frame.
6. When search bar with "User2" is selected, show only selected users that match the criteria (starts with "User2"), sorting remains same as 3
7. When search bar with "User2" is selected, show only unselected users that match the criteria (starts with "User2"), sorting remains same as 4

**Describe alternatives you've considered**
Reference: https://doejo.com/blog/solutions-for-implementing-user-friendly-multi-select/

**Additional context**
None

cc: @vivekratnavel @harshach @Sachin-chaurasiya @shahsank3t

**Comment by vivekratnavel** [comment]
I like this approach. It will definitely improve the UX on multi-select.  

For the implementation, when it comes to multi-select or select, my favorite go-to component is [Creatable](https://react-select.com/creatable). It can be customized to our liking with tons of options to configure.

**Comment by mithmatt** [comment]
Thanks for the pointer @vivekratnavel 

This one is pretty awesome. We should definitely explore on improving the UX on multi-select somehow.
We have the functionality working but have a lot to improve on UX from where we are today. 

<img width="551" alt="image" src="https://user-images.githubusercontent.com/5906984/156473905-6aafba1d-4c74-41c6-acb0-8a70a88f17d9.png">
