### ISSUE TITLE
Tour redirects to blank page

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3062]
**Affected module**
UI

**Describe the bug**
Clicking on the tour guide gives a blank page.

**To Reproduce**
Click on the tour guide button.

https://user-images.githubusercontent.com/83201188/156301312-b08ce36b-181b-4de3-97e0-c874c6f48ed9.mov

**Expected behavior**
Successful tour

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment]
Fixed with #3184

**Comment by parthp2107** [comment]
404 is fixed, getting this now #3196
