### ISSUE TITLE
Getting "Invalid field name tags"

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3063]
**Affected module**
UI

**Describe the bug**
Clicking on any service gives "Invalid field name tags". Also happening on database details page
**To Reproduce**

https://user-images.githubusercontent.com/83201188/156302088-583f2b17-fb04-44c5-bbd3-395a2e12b08a.mov

**Expected behavior**
Should not get such error on clicking services

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by harshach** [comment]
@darth-coder00 we removed unnecessary fields so might affect other areas too
