### ISSUE TITLE
After following any entity, the same is not reflected on my-data page. Need to refresh it.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3065]
**Affected module**
UI

**Describe the bug**
After following, the same is not reflected on the my-data page under "Following". Need to refresh it.

**To Reproduce**
- Follow any entity
- Check on the my-data page. It won't reflect without refreshing.

**Expected behavior**
After following any entity, the same should reflect on my-data page without refreshing.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by harshach** [comment]
Thought this was the backend bug . But we are indexing
<img width="547" alt="image" src="https://user-images.githubusercontent.com/38649/156303936-6c674296-a394-464e-856c-a1bc47746c20.png">
<img width="312" alt="image" src="https://user-images.githubusercontent.com/38649/156303951-4ef624f4-3b0d-4b3f-b63c-9a5d66be8ce8.png">
