### ISSUE TITLE
Getting <span> tag in threads after updating description

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3078]
**Affected module**
UI

**Describe the bug**
Getting <span> tag in threads after updating description

**To Reproduce**

<img width="661" alt="Screenshot 2022-03-02 at 5 43 00 PM" src="https://user-images.githubusercontent.com/83201188/156359632-ac151a03-fad0-4dbb-8b4e-2d3643504d47.png">

**Expected behavior**
Tags should not be visible on UI.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment]
@parthp2107, Diff is coming from the backend so you can assign this issue to @vivekratnavel .
