### ISSUE TITLE
Activity Feed: Blank feed on my-data page for updating user's role or team

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3080]
**Affected module**
UI

**Describe the bug**
Blank feed on my-data page for updating users. Also getting versions.

**To Reproduce**

<img width="867" alt="Screenshot 2022-03-02 at 6 18 57 PM" src="https://user-images.githubusercontent.com/83201188/156365365-73f31944-9ec1-4198-b1b7-597d300f5c3d.png">

**Expected behavior**
Not sure if an empty feed is intentional.
Not sure where to check the versioning for users.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment]
@parthp2107, can paste the Feed API response?

**Comment by parthp2107** [comment]
> @parthp2107, can you paste the Feed API response? Also, how are you updating users?

@Sachin-chaurasiya I am updating user's role. 

Here is the API response: 
`{"data":[{"id":"1687bf73-05db-439c-a79f-bb635eb78e21","href":"http://localhost:8585/api/v1/feed/1687bf73-05db-439c-a79f-bb635eb78e21","threadTs":1646225409463,"about":"<#E/user/aaron_johnson0/isAdmin>","createdBy":"anonymous","updatedAt":1646225409463,"updatedBy":"anonymous","resolved":false,"message":" <br/><br/> **Change Type:** *MINOR (0.4 -> 0.5)*","postsCount":0,"posts":[]},{"id":"b5753e5f-5e77-48fc-9167-2f98650a8241","href":"http://localhost:8585/api/v1/feed/b5753e5f-5e77-48fc-9167-2f98650a8241","threadTs":1646225320239,"about":"<#E/user/aaron_johnson0/isAdmin>","createdBy":"anonymous","updatedAt":1646225320239,"updatedBy":"anonymous","resolved":false,"message":" <br/><br/> **Change Type:** *MINOR (0.3 -> 0.4)*","postsCount":0,"posts":[]},{"id":"2b7ea604-0489-4a18-bc3d-0f8239a89079","href":"http://localhost:8585/api/v1/feed/2b7ea604-0489-4a18-bc3d-0f8239a89079","threadTs":1646225139312,"about":"<#E/user/aaron_johnson0/isAdmin>","createdBy":"anonymous","updatedAt":1646225139312,"updatedBy":"anonymous","resolved":false,"message":" <br/><br/> **Change Type:** *MINOR (0.2 -> 0.3)*","postsCount":0,"posts":[]},{"id":"37bcf971-24c6-48f3-b437-66fed12089e1","href":"http://localhost:8585/api/v1/feed/37bcf971-24c6-48f3-b437-66fed12089e1","threadTs":1646225033384,"about":"<#E/user/aaron_johnson0/isAdmin>","createdBy":"anonymous","updatedAt":1646225033384,"updatedBy":"anonymous","resolved":false,"message":" <br/><br/> **Change Type:** *MINOR (0.1 -> 0.2)*","postsCount":0,"posts":[]}]}`

**Comment by Sachin-chaurasiya** [comment]
> <br/><br/> **Change Type:** *MINOR (0.4 -> 0.5)*

Hey @vivekratnavel, can you look into this?
