### ISSUE TITLE
Ability to test connectivity for a database service while providing connection config

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3089]
**Is your feature request related to a problem? Please describe.**
Ability to test connectivity for a database service while providing connection config.
It is useful for users to fill in the connection details and try out if the connection works

**Describe the solution you'd like**

Perhaps a test connection button somewhere here:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/5906984/156481775-8ab21ea2-c028-41fc-b3b0-a1e5d02e6026.png">

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mithmatt** [comment]
cc: @harshach @vivekratnavel

**Comment by harshach** [comment]
@pmbrull we should think about how to do this via Airflow REST APIs. May be another one-time trigger pipeline i.e there is only one pipeline that will take any connection of any service and check if its able to connect or not
