### ISSUE TITLE
OpenMetadata Ingestion Docker Improvements

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#3094]
Optimizing and creating a better efficient OpenMetadata Ingestion Docker.
For better user experience and making it more configurable.

Tasks
- Using volumes for airflow.cfg

**Comment by harshach** [comment]
@akash-jain-10 lets keep track of it and make sure we follow up on what we need to do here. cc @ayush-shah

**Comment by ayush-shah** [comment]
Allowing users to upload service account json files for bigquery, sso auth for google (secret_key path) on the volumes.

The flow that user will follow would be - 
Edit airflow.cfg and openmetadata.yaml to have all the auth related stuff.
They specify paths for the service account files, but it can be difficult for users to execute / send files in an container.
Instead an easy option would be to allow them to upload the same using volumes.

Same for Bigquery, one of the connection options are credentials_path which points to a service account file.

cc: @akash-jain-10 @harshach

**Comment by harshach** [comment]
@akash-jain-10 can we add the sidecar facility to ingestion docker image

**Comment by pmbrull** [comment]
Another thing we should consider improving is that I believe that currently, the image is built by copying the `generated` sources from the laptop. This forces us to run a `make generate` before building the image.

It should be cleaner and less error-prone to install dev dependencies and generate in the Dockerfile.

If we cannot tackle it here, we can open a separated issue for that

**Comment by pmbrull** [comment]
@akash-jain-10 @vijaypm could you please add a volume by default to the docker images? This way users will know how to pass config files needed for ingestion. Thanks!

**Comment by akash-jain-10** [comment]
@Vj-L  :)
