### ISSUE TITLE
Webhook description is not reflecting updated value

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3099]
**Affected module**
UI

**Describe the bug**
Webhook description is not reflecting updated value

**To Reproduce**

https://user-images.githubusercontent.com/83201188/156551706-dac7209d-39ca-4684-83e4-d3fe814dc751.mov

**Expected behavior**
Should reflect updated value of description

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
`{"id":"1de64199-51e5-467d-a728-02c74aa37767","name":"Testing","description":"Description","endpoint":"www.example.com","eventFilters":[{"eventType":"entityCreated","entities":["topic"]},{"eventType":"entityUpdated","entities":["table"]},{"eventType":"entityDeleted","entities":["table"]},{"eventType":"entitySoftDeleted","entities":["table"]}],"batchSize":10,"timeout":10,"enabled":true,"secretKey":"","version":0.1,"updatedAt":1646304950485,"updatedBy":"anonymous","status":"active","href":"http://localhost:8585/api/v1/webhook/1de64199-51e5-467d-a728-02c74aa37767","changeDescription":{"fieldsAdded":[],"fieldsUpdated":[],"fieldsDeleted":[],"previousVersion":0.1},"deleted":false}`

**Comment by darth-coder00** [comment]
Closing as it's related to #2731
