### ISSUE TITLE
Adding Azure SQL and Databricks config support in Ingestion - UI

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#3102]
Adding configs related to Azure SQL and Databricks support from backend.
These 2 connectors are using sqlalchemy packages and need additional parameters.

- Azure SQL
  - `"driver": "{ODBC Driver 17 for SQL Server}"`

- Databricks
  - `"token": "<databricks token>"`

cc: @harshach @darth-coder00

**Comment by TeraInferno** [comment]
It might be a good idea to hide the visibility of the Databricks Access Token in the UI. That token could be used for a lot more than just ingesting into Open Metadata, and exposing it in plain text could be a security risk. Perhaps cover it up with dots like a lot of password fields are handled.

**Comment by harshach** [comment]
@ayush-shah ^
@ShaileshParmar11 
@vivekratnavel 
Lets encode this in password in JsonSchema and UI shouldn't be revealing any password in plaintext

**Comment by ayush-shah** [comment]
Fixed. The changes are inside main.
