### ISSUE TITLE
Review implementation of ColumnValuesToMatchRegex

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3105]
**Feature**
Based on https://github.com/open-metadata/OpenMetadata/issues/1311

**Describe the task**
Two things to check here:
- Regex strategy to follow: @harshach are we talking about python-level regex or aiming towards SQL-supported 'LIKE' syntax? I am assuming the second, but just to confirm.
- We'll need to review how we want to create tests based on metrics with specific parameters requirements that can change from col to col.

**Comment by harshach** [comment]
@pmbrull lets use SQL Like and second thing is email regex that we should see if we can pass down to sql instead of doing in python
