### ISSUE TITLE
Activity Feed: mention user/team link 404

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3110]
If there is a mention 
![image](https://user-images.githubusercontent.com/35870520/156607382-77456b26-3c87-41a8-8055-b3235bbb8bcb.png)

when clicking on top of the `@name`, we get a 404 `GET https://sandbox-beta.open-metadata.org/user/pmbrull 404 (Not Found)`

cc @vivekratnavel @Sachin-chaurasiya

**Comment by parthp2107** [comment]
@Sachin-chaurasiya the same is happening with teams as well.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya the same is happening with teams as well.

@parthp2107 , for the team, patch is included in this PR #3074
