### ISSUE TITLE
[Documentation] Typo in script name when starting OpenMetadata

### ISSUE THREAD

**Issue by jamiegeddes-tp** [open-metadata/OpenMetadata#3111]
**Affected module**
Documentation

**Describe the bug**
Documentation here: https://docs.open-metadata.org/install/run-in-production#4.-start-openmetadata to start OpenMetadata has a typo in the script name, openmetadata is missing a letter "a". Copying and pasting from this field results in an error as the script name is invalid.

**To Reproduce**

Follow steps in https://docs.open-metadata.org/install/run-in-production until 4. Start OpenMetadata

**Expected behavior**
Correct shell script name is used.

**Version:**
 - Latest docs

**Additional context**
Script name in markdown file here: https://github.com/open-metadata/OpenMetadata/blob/b0beac243b6531ba48f34bb25621d8ed167f8104/docs/install/run-in-production.md?plain=1#L82 needs to be corrected.

**Comment by harshach** [comment]
Fixed in 0.8 and main
