### ISSUE TITLE
Ingestion - Allowing Multiple Databases 

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#3118]
Allowing multiple database support from a connector instead of providing one.
- Overriding get_inspectors
For instance, snowflake connector doesn't work if we don't pass database to it.
we will need to override get_inspectors, run the query to show databases and loop through it.

**Comment by ayush-shah** [comment]
Reopening this issue - to be taken up in 0.9.2 release.

**Comment by pmbrull** [comment]
This should be handled already by the addition of the db schema entity
