### ISSUE TITLE
Document new profiler and data quality configuration and deployment

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#3119]
Document configuration and deployment for the profiler and data quality using a manner similar to what we do now for metadata ingestion.

Docs for: https://github.com/open-metadata/OpenMetadata/issues/2845

**Comment by shannonbradshaw** [comment]
@pmbrull can you provide a high level list of steps a user needs to walk through to manually configure and deploy the new profiler.

**Comment by pmbrull** [comment]
@shannonbradshaw , it is on gitbook https://app.gitbook.com/o/-MehiNqHP1pI0oSe7bvF/s/JUz6NmjOXjrY5pVqDjw7/data-quality/data-quality-overview
