### ISSUE TITLE
Adding user to a team adds with its previous roles.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3146]
**Affected module**
UI

**Describe the bug**
Adding users to a team are added with their previous roles.

**To Reproduce**
1. Make a user an admin
2. Remove the above user
3. Add the same user again to the team
4. The user will be added as an admin

https://user-images.githubusercontent.com/83201188/156760865-7c7af249-58dd-4062-bce2-107f3f16aa3c.mov

**Expected behavior**
The user should not be added as an admin directly.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
@parthp2107  This is expected right. you have changed the user permission.

**Comment by harshach** [comment]
@parthp2107 permissions and user being added to a team or removing a team is not related. Not sure what is the expectation is
