### ISSUE TITLE
Investigate go-client code gen

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#3167]
https://github.com/atombender/go-jsonschema
can only do one file at a time

https://github.com/sourcegraph/go-jsonschema
https://github.com/a-h/generate
can do multiple files, but has issues with recursive references

https://github.com/idubinskiy/schematyper
can do multiple files, but has type issues 
```
gojsonschema: Failed: error parsing from file ./entity/policies/policy.json: json: cannot unmarshal bool into Go struct field unmarshalerSchema.additionalProperties of type schemas.Type
```

**Comment by sureshms** [comment]
Resolving this as won't fix.
