### ISSUE TITLE
Add OMeta tests for DashboardService

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3187]
Follow the implementation example of `ingestion/tests/integration/ometa/test_ometa_database_service_api.py` to implement the testing of the Python client for DashboardService.

**Comment by pmbrull** [comment]
Please make sure that you name your entities in the tests with a unique name (not clashing with other instances created in different tests). Otherwise this might have an impact in the CI

**Comment by Supzz2** [comment]
HI, I'm interested in, can you assign it for me? Thanks.

**Comment by pmbrull** [comment]
Assigned, thanks!
