### ISSUE TITLE
Add OMeta tests for MessagingService

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3188]
Follow the implementation example of `ingestion/tests/integration/ometa/test_ometa_database_service_api.py` to implement the testing of the Python client for MessagingService.

**Comment by pmbrull** [comment]
Please make sure that you name your entities in the tests with a unique name (not clashing with other instances created in different tests). Otherwise this might have an impact in the CI

**Comment by YaqiXue2** [comment]
Hi, I am interested in this issue, can you please assign it to me?

**Comment by pmbrull** [comment]
Assigned, thanks!
