### ISSUE TITLE
Add OMeta tests for PipelineService

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3189]
Follow the implementation example of `ingestion/tests/integration/ometa/test_ometa_database_service_api.py` to implement the testing of the Python client for PipelineService.

**Comment by pmbrull** [comment]
Please make sure that you name your entities in the tests with a unique name (not clashing with other instances created in different tests). Otherwise this might have an impact in the CI

**Comment by akhil-ghatiki** [comment]
I can sign up for this

**Comment by ziwei-la** [comment]
Hi, I'm interested in working on this issue. Can you please assign it to me?

**Comment by pmbrull** [comment]
Assigned, thanks!

**Comment by ziwei-la** [comment]
Hi pmbrull, I opened a PR for the issue [https://github.com/open-metadata/OpenMetadata/pull/8298] and had a failure about custom property for dashboard Entities. However, I think my code has nothing to do with the dashboard entities, could you please   tell me how to revise code about this failure?

**Comment by pmbrull** [comment]
Thanks @ziwei-la , left a comment in the PR!
