### ISSUE TITLE
[DOCUMENTATION] Mismatch between Database Service docs & JSON schema

### ISSUE THREAD

**Issue by Beetelbrox** [open-metadata/OpenMetadata#3190]
**Affected module**
Documentation

**Describe the bug**
The properties described in the [Database Service documentation ](https://docs.open-metadata.org/openmetadata/schemas/entities/databaseservice) don't match the ones listed in the [JSON schema](https://open-metadata.org/schema/entity/services/databaseService.json).

**To Reproduce**

N/A

**Expected behavior**
Properties listed in the docs should match the ones in the JSON Scema

**Version:**
 - OS: N/A
 - Python version: N/A
 - OpenMetadata version: 0.8
 - OpenMetadata Ingestion package version: N/A

**Additional context**
N/A

**Comment by Beetelbrox** [comment]
@pmbrull FYI

**Comment by pmbrull** [comment]
@shannonbradshaw I am now not quite sure how we usually generate all the API and Schemas data in the docs, but we should try to update them with the latest JSON Schemas. Thanks!

**Comment by pmbrull** [comment]
Hi @Beetelbrox, I can see that the docs now present the updated version of the `DatabaseService`. I see the `databaseConnection` field instead of the old `jdbc`. I'll close this. Please, let us know if you need anything else. Thanks!
