### ISSUE TITLE
Unable to get entity reference for DatabaseService with python API

### ISSUE THREAD

**Issue by Beetelbrox** [open-metadata/OpenMetadata#3191]
**Affected module**
Python API

**Describe the bug**
The current implementation of [get_entity_reference](https://github.com/open-metadata/OpenMetadata/blob/a9290bf1a04fe0c2800efe7f33db6a574b178553/ingestion/src/metadata/ingestion/ometa/ometa_api.py#L447-L465) depends on the entity's `fullyQualifiedName` field. DatabaseService Entities don't have such field and therefore trying to retrieve a ref for a DB Service entity crashes.

**To Reproduce**

Try to retrieve a reference to an existing DatabaseService entity using the python API:
```
server_config = MetadataServerConfig(api_endpoint="http://localhost:8585/api")
metadata = OpenMetadata(server_config)
metadata.get_entity_reference(
    entity=DatabaseService, fqdn=<my_db_service_name>,
)
```

**Expected behavior**
Reference to the existing databaseService is returned instead of crashing.

**Version:**
 - OS: iOS
 - Python version: 3.8.12
 - OpenMetadata version: 0.8.0
 - OpenMetadata Ingestion package version: 0.8.0

**Additional context**
N/A

**Comment by Beetelbrox** [comment]
@pmbrull FYI

**Comment by harshach** [comment]
@pmbrull is this still an issue? If so lets reopen
