### ISSUE TITLE
Data Quality - Missing values

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3199]
**Affected module**
UI

**Describe the bug**
We are missing the values that should be extracted from testCase.config

<img width="481" alt="image" src="https://user-images.githubusercontent.com/35870520/156989183-d8d904be-f68d-4fe2-9ec8-097575016c26.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/35870520/156989195-192f5515-7079-4830-9f1a-39262e81def1.png">

**To Reproduce**

Check sample data in `dim_staff`

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Can you assign this to me? @Sachin-chaurasiya @pmbrull
