### ISSUE TITLE
Suggestion api shows deleted entities.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3203]
**Affected module**
Backend

**Describe the bug**
Suggestion api shows deleted entities

**To Reproduce**

https://user-images.githubusercontent.com/83201188/156990256-80bf147e-2253-4564-9755-20e7327bb690.mov

https://user-images.githubusercontent.com/83201188/156990264-77d7ff7f-5f54-43ad-a376-081bbc3a39e4.mov

**Expected behavior**
Suggestion API should not show deleted entity

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
cc @darth-coder00

**Comment by harshach** [comment]
this is fixed
