### ISSUE TITLE
Data Quality - Add Test Button

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3223]
Highlight a bit more the Add Test button

![image](https://user-images.githubusercontent.com/35870520/157052659-d8e36d21-d530-4e1f-931d-07b2c684ec2b.png)

Should have the same style as the webhook 

![image](https://user-images.githubusercontent.com/35870520/157052707-7df406a4-5d57-4b46-9d96-7e672bd6d35c.png)

Let's see if we can make it pop a bit more when we have other tests configured

![image](https://user-images.githubusercontent.com/35870520/157052891-2953bdd1-83c1-41b8-9917-2bbdc2503a94.png)

**Comment by pmbrull** [comment]
cc @Sachin-chaurasiya @ShaileshParmar11

**Comment by pmbrull** [comment]
Hi @Sachin-chaurasiya, great work on all the improvements. The "Add Test" now looks better when we have other tests, but I still would highlight a bit more the button when the tab is empty:
![image](https://user-images.githubusercontent.com/35870520/157246319-d0ab485c-2a3c-426b-b7d9-5fbc7e535103.png)
I believe we can close this after this change.

Thanks!

**Comment by ShaileshParmar11** [comment]
Hey this changes will reflect once my PR merge. @pmbrull

**Comment by pmbrull** [comment]
> Hey this changes will reflect once my PR merge. @pmbrull

Amazing thanks 🙏
