### ISSUE TITLE
Data Quality - Check UI test generation

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3226]
In this https://github.com/open-metadata/OpenMetadata/pull/3220 we updated some names and configs from the JSON Schemas of the Tests.

Now, when creating a `tableColumnCountToEqual` from the UI, the test gets generated as `testCase: {config: {value: 100}, tableTestType: "tableColumnCountToEqual"}`. This is the old config, it should use `columnCount`. This is not only aesthetic, but makes the ingestion process not pick up the correct test definition.

Thanks

**Comment by pmbrull** [comment]
Same happens with `columnValueLengthsToBeBetween`. Note the payload generated by the UI: `testCase: {config: {maxValue: 100, minValue: 4}, columnTestType: "columnValueLengthsToBeBetween"}`.

We should make sure we are using `minLength` and `maxLength` as per the changes in #3220. Thanks!

**Comment by ShaileshParmar11** [comment]
Yes sure i will make required change for it @pmbrull
