### ISSUE TITLE
Doc: 4GB memory requirement for docker is insufficient

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3231]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Docs

To try out Open Metadata in Docker, we recommend users allocate at least 4GB of memory to Docker, which is insufficient. I tried running my docker with 4GB RAM and the elastic search container kept exiting. I would suggest updating the recommendation to at least 8GB of memory.

https://docs.open-metadata.org/v/main/try-openmetadata/run-openmetadata

<img width="753" alt="Screen Shot 2022-03-07 at 11 52 41 AM" src="https://user-images.githubusercontent.com/1051198/157108085-e9734754-7c2c-40db-b5d0-c83d10cecb32.png">

cc @harshach

**Comment by ayush-shah** [comment]
Hey @vivekratnavel, I am trying out the same with 5 GB, it works without giving me exit code 137.
Can you test it out if it works for you?

**Comment by harshach** [comment]
@ayush-shah this used to work with 4GB right, any idea what changed?

**Comment by vivekratnavel** [comment]
@ayush-shah I am trying out with 5GB memory and the elastic search container did not exit yet. So, I think 5GB might be sufficient for now. I will update this thread if I find any more issues related to memory.
