### ISSUE TITLE
Search in the glossary is not filtering searched keyword

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3249]
**Affected module**
UI

**Describe the bug**
Search in the glossary is not filtering searched keyword

**To Reproduce**

https://user-images.githubusercontent.com/83201188/157179295-ccea7996-fedc-444e-be85-40352463c20d.mov

**Expected behavior**
Search should give filtered results

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by darth-coder00** [comment]
Already fixed
