### ISSUE TITLE
Breadcrumb in the glossary shows deleted term.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3252]
**Affected module**
UI

**Describe the bug**
Breadcrumb in the glossary shows deleted term.

**To Reproduce**

https://user-images.githubusercontent.com/83201188/157179925-beafd3f7-e62b-43fd-805f-1271bea378d6.mov

**Expected behavior**
The breadcrumb and terms should be in sync

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by darth-coder00** [comment]
After deletion of parent term, child terms still has parent term's name in it's `fullyQualifiedName`
CC: @sureshms @harshach
