### ISSUE TITLE
Getting blank in activity feed to adding reviewers/synonyms/reference in glossary terms.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3258]
**Affected module**
backend

**Describe the bug**
Getting blank in activity feed to adding reviewers/synonyms/reference in glossary terms.

**To Reproduce**

<img width="848" alt="Screenshot 2022-03-08 at 12 54 13 PM" src="https://user-images.githubusercontent.com/83201188/157187490-55dba1bc-fda8-4b5f-ab82-470589208fc5.png">

**Expected behavior**
Should not give blank values.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by kshinde2512** [comment]
@darth-coder00 @Sachin-chaurasiya @ShaileshParmar11 
Screenshot for synonyms and references
![Screenshot from 2022-03-08 12-56-12](https://user-images.githubusercontent.com/67048554/157188096-c56d6573-f698-4b85-b311-e0a052d09001.png)
