### ISSUE TITLE
Data Quality - Column Profile cleaning & improvements

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3265]
Not mandatory for 0.9, but might be interesting to tackle it afterward:
- Remove `validCount` from `columnProfile`. It makes sense in a test, but it is not a self-contained metric.
- Align naming: we have both `valuesPercentage` vs. `nullProportion`. Let's stick to one wording.
- IDK if the `variance` is a bit redundant having `stddev`. It is easy to compute, so we might want to keep it.

**Comment by pmbrull** [comment]
cc @harshach IDK if there's anything else you had in mind that we could improve here

**Comment by pmbrull** [comment]
Note that we should tackle this after migrating the testing data into a separate table as per the discussion on https://github.com/open-metadata/OpenMetadata/pull/3292#issuecomment-1062544638. Otherwise, we might break the migrations

**Comment by harshach** [comment]
@pmbrull lets see if we are going to ship this in this release or move it out to 0.11

**Comment by pmbrull** [comment]
Let's move DQ stuff to 0.11 if not mandatory

**Comment by harshach** [comment]
@pmbrull can we close it out?
