### ISSUE TITLE
Data Quality - Filter tests by type

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3277]
We currently allow all tests for numeric and string types. There is one difference though between the two.

These are the tests to exclude for each supported type (i.e., not array or struct):

# Numeric
- excluded `columnValuesLengthsToBeBetween` 
# String
- excluded `columnValuesToBeBetween`
# Boolean
- excluded `columnValuesToBeNotInSet`
- excluded `columnValuesLengthsToBeBetween`
- excluded `columnValuesToBeBetween`
# Dates
- excluded `columnValuesToBeNotInSet`
- excluded `columnValuesLengthsToBeBetween`

**Comment by pmbrull** [comment]
cc @Sachin-chaurasiya @ShaileshParmar11

**Comment by ShaileshParmar11** [comment]
Assign it to me
