### ISSUE TITLE
Feedback on Glossaries feature/UI

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#3285]
- [x] Remove delete option until hard delete is supported. If someone deleted a glossary, the glossary of the same name can't be created.
- [x] Adding a Glossary term as a label doesn't show the corresponding Table in Assets.
- [x] When adding a tag or glossary term as a label, tag terms show up faster and glossary terms show up slower. In some cases, typing a few characters does not suggest glossary terms.
- [x] Search while adding Related Terms does not work. Type `Risk` and the glossary term `Risk Assessment` does not show up. Also the search box says `Search for a User`.
<img width="747" alt="image" src="https://user-images.githubusercontent.com/1417689/157324525-d7d50292-054f-4e86-b164-2e66df730a20.png">

- [x] Need better use of spacing. Adding more space after arrows would be better.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/1417689/157324666-62c95dd2-4cc5-4e85-9dfb-fb31f368d155.png">

- [x] Make Related Terms clickable
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1417689/157324748-95ee0fed-ff57-4638-9589-e0039ef8e59b.png">

- [ ] Long glossary term name/highly nested terms are cut off 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/1417689/157324910-5d4fdb83-28dd-4f29-a0cc-8e89bc1018ce.png">

- [x] Make parent terms clickable. In the below examples, make Domain and Sales clickable. 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1417689/157327547-579b4824-2363-45e2-9f86-a33981593171.png">

- [x] Searching for users to set Reviewers is very slow
- [x] When hovering over terms in the tree hierarchy, give feedback by highlighting the term hovering over
- [x] Remove tags column for assets and just include name, description, and owner. The look and feel could be similar to Explore page results.
- [x] When search does not find a glossary term, there is no indication - 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1417689/157328977-8e278927-c792-4122-8738-c65547ae13f0.png">

- [x] Partial searches don't work. For example, using the first-word Annual finds a Glossary Term. But typing revenue does not find matching terms.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/1417689/157329357-e2597bdf-b691-4d03-99ed-aa9d1c64dfcb.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1417689/157329423-114fffe9-0200-4a10-ae8a-835e6718458f.png">

- [x] Change the tab name to `Reviewers` for Glossary similar to the Glossary Term page.
- [x] URL does not change as you click through different terms. It just stays as Glossary.
- [x] We should only show leaf glossary term instead of the entire hierarchy in all the places.

**Comment by harshach** [comment]
- [ ] add a hover over on search tags to display full text of a tag or glossary term 
<img width="373" alt="image" src="https://user-images.githubusercontent.com/38649/157329360-bf374dd8-1b04-4011-b547-e5cbdbec5d6a.png">

**Comment by sureshms** [comment]
@aashitk and @harshach, can we fix this as a blocker.

- [ ] GlossaryTerm details page has different ways of showing data is not available. Can we use a consistent way as shown for Assets tab?
<img width="944" alt="image" src="https://user-images.githubusercontent.com/1417689/157558469-2959dff7-7bc3-454d-9e73-57bb200e29ef.png">
<img width="819" alt="image" src="https://user-images.githubusercontent.com/1417689/157558508-6d64b780-7b08-41b9-bab9-9b7c0e6895c6.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/1417689/157558546-e10fbbd8-0627-429f-a2f6-9592fbefd078.png">
