### ISSUE TITLE
Glossary UI: Updating a reference doesn't work

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3286]
**Affected module**
UI

**Describe the bug**
Updating reference of a glossary term does not trigger any API request but shows the updated value in the UI until the refresh of the page.

**To Reproduce**

Update reference of any term.

**Expected behavior**
UI makes an API call to the backend to update the reference.

**Comment by darth-coder00** [comment]
Already fixed
