### ISSUE TITLE
Snowflake Connector | Precision & Scale for a couple datatypes aren't propagated accurately

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#3289]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework
**Describe the bug**
* `NUMBER`/`DECIMAL` Data types with varying allowed precision/scale are always set to `DECIMAL(1)`.
*  `VARIANT ` seems to be mapped to `VARBINARY`

Not sure, if the below should even display with `(1)` which looks like precision and might be misleading.
* `BOOLEAN`
*  `DATE`
* `FLOAT`
* `TIMESTAMP`
* `OBJECT`
* `BINARY`

**To Reproduce**
create and ingest a table with any/all of the above data types and try to ingest the same onto OM.

Screenshots or steps to reproduce

**Expected behavior**
Data types need to be mapped to appropriate equals. Also, Data types without a possible precision/scale should not end up with `(1)` precision.

**Version:**
 - OS: [e.g. iOS]: Mac OS 11.6.2 (20G314)
 - Python version: Python 3.8.10
 - OpenMetadata version: [e.g. 0.8]: 0.8.6
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
Breaking down these into tasks:

- #4334 
- @harshach, please add tasks for ingestion and UI
