### ISSUE TITLE
Data Quality - Missing Test Description UI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3301]
**Affected module**
UI

**Describe the bug**
In the Data Quality tab we are not showing the description of tests. Let's discuss if we want to add it and how, as the table is pretty packed already with the results. Let's tackle in the next release.

**To Reproduce**

![image](https://user-images.githubusercontent.com/35870520/157384966-83bc378c-31af-44b9-82f5-9659a96f909a.png)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Kindly assign it to me

**Comment by ShaileshParmar11** [comment]
We can close this as its handled in #3404
