### ISSUE TITLE
Need add user button in roles page.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3307]
**Is your feature request related to a problem? Please describe.**
Currently, to assign roles to users, we need to assign if from the user page individually.
No provision to select multiple users.
Need add user button in roles page. Like for teams

**Describe the solution you'd like**
Add the add user button so multiple selections can be made.

<img width="1498" alt="Screenshot 2022-03-09 at 2 07 14 PM" src="https://user-images.githubusercontent.com/83201188/157404344-fade0b8b-0f56-4c7a-93e0-6d8ecb3e35c7.png">

<img width="1449" alt="Screenshot 2022-03-09 at 2 07 23 PM" src="https://user-images.githubusercontent.com/83201188/157404397-fca9e80c-df54-4624-9034-267dd7f5947b.png">

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by harshach** [comment]
@Sachin-chaurasiya lets fix this

**Comment by Sachin-chaurasiya** [comment]
Closing this we have new a whole new UI.
