### ISSUE TITLE
Lineage : Number is displayed in side drawer instead of dashboard name and superset url

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#3308]
**Affected module**
UI

**Describe the bug**
Number is displayed in side drawer instead of dashboard name and superset url

**To Reproduce**

![image](https://user-images.githubusercontent.com/67048554/157404454-3790f319-61ca-4805-b07b-34a32830fb3f.png)
![image](https://user-images.githubusercontent.com/67048554/157404599-2e1b005a-e7b6-4d00-80e5-0bad9605e927.png)

**Expected behavior**
Dashboard name should be displayed

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**

**Comment by kshinde2512** [comment]
@Sachin-chaurasiya @darth-coder00

**Comment by parthp2107** [comment]
Same is happening on activity feed

https://user-images.githubusercontent.com/83201188/157458264-3b564d45-73f4-4794-858b-329b8aa01348.mov
