### ISSUE TITLE
Team roles are not reflected in user profile.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3317]
**Affected module**
UI/backend

**Describe the bug**
When assigned any role to a team. The same is not reflected for the users in the user profile of that team.

**To Reproduce**

- Add user to any team
- Assign team any role
- Check the user profile of that team member, the role is not reflected.

**Expected behavior**
The role should reflect for the team members

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by harshach** [comment]
@sureshms adding this to keep track of it.
/api/v1/users/{id|name}/roles should give us the user roles and their inherited roles based on system level default and team they belong to

**Comment by sureshms** [comment]
@parthp2107 @harshach is this still and issue?

**Comment by parthp2107** [comment]
> @parthp2107 @harshach is this still an issue? Can we try this in the latest main branch?

@sureshms I am able to reproduce this issue on the main branch.
