### ISSUE TITLE
Ingestion - Redshift varbyte & time

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3332]
**Affected module**
Ingestion

**Describe the bug**
```
/Users/pmbrull/venv/lib/python3.9/site-packages/metadata/ingestion/source/redshift.py:120: SAWarning: Did not recognize type 'binary varying' of column 'my_varbyte'
  column_info = super(RedshiftDialectMixin, self)._get_column_info(
```

When ingesting redshift data of type `varbinary` we get the error above and the column gets mapped wrongly to varchar.

Also, although there is no error in the logs, the `TIME` type gets ingested as `varchar` as well.

**To Reproduce**

Reproduce this by running the ingestion against our DEV redshift and check the table `public.type_test`.

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@ayush-shah can we fix this and if needed the varbyte into types on the server side
