### ISSUE TITLE
Data Quality - Check tests being supported in Date but not Timestamp

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3333]
**Affected module**
UI

**Describe the bug**
We are supporting tests for DATE but not TIMESTAMP. Both types should go hand in hand to just support Unique, notnull and missing count.

![image](https://user-images.githubusercontent.com/35870520/157476150-cee0bc2f-66fc-48d2-b798-d1c37cc1ea43.png)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Assign it to me

**Comment by ShaileshParmar11** [comment]
Hi @pmbrull I checked in UI, we are supporting creation of test case for both `TIMESTAMP` and `DATE`, and backend also allowing to create test.

**Comment by pmbrull** [comment]
Hi @ShaileshParmar11, I checked the following info in the sandbox, table `event`:
![image](https://user-images.githubusercontent.com/35870520/158138376-1b152766-3414-45a2-941a-73b1482a7a60.png)

Sorry if I am missing something here, but why are we showing this `Not supported` label? From where does this info come from?

**Comment by ShaileshParmar11** [comment]
Thanks @pmbrull I i'll check and update the code.
