### ISSUE TITLE
[UI] Add Ingestion Modal are missing Snowflake Warehouse and account input fields

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#3338]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI.

**Describe the bug**
Adding a service panel contains Warehouse and Account field for Snowflake Ingestion. But the same is missing from Services >> Ingestion Tab >> Add Ingestion Modal.
This is related to #3319 

**Expected behavior**
Adding Snowflake ingestion should have warehouse and account field consistently across OpenMetadata.

cc - @ayush-shah , @ShaileshParmar11

**Comment by ShaileshParmar11** [comment]
Assign to me
