### ISSUE TITLE
Activity Thread updates push mechanism

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3342]
**Is your feature request related to a problem? Please describe.**
It would be great to have ActivityThreads push mechanism and update the comments in live.
This can be done through web sockets. Also have an option to integrate with notifications that can send new message updates to the user directly

**Describe the solution you'd like**
Use web sockets to push the new comments and replies to the browser

**Describe alternatives you've considered**

**Additional context**

**Comment by vivekratnavel** [comment]
This would be awesome! I will work on the design.

**Comment by harshach** [comment]
@mohitdeuex @vivekratnavel any remaining items should be completed including showing proper notifications via browser and showing a list of notifications. Once the user clicks the notifications marking them as read cc @chirag-madlani
