### ISSUE TITLE
Feedback on clickability in UI

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#3343]
We have many small targets for clicking and inconsistent UI on what can be clicked. @pmbrull, @vivekratnavel, and @harshach, please continue to provide feedback here:

- [x] In Glossaries there are two types of click allowed. One for clicking the term to see the details and another to expand the children under a term by clicking the arrow. Let's combine them to make the click target bigger. When clicking a term or an arrow, let's expand the children and show the term details both. 
- [x] Instead of just making the checkbox a click target, let's also allow clicking the entire line:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1417689/157558962-f6db33a9-eb5c-49e2-9e98-42183a25691a.png">

- [x] Some clickable text changes colors to purple with an underline when hovering over and others don't do this. Some examples are - Sorting with `Last Updated`, `Owner` field in the data asset details page. @parthp2107, can you please do a thorough review of this?

- [x] No hover over response for `What's New`, `Tour`, `Help`, and `Profile` button like Explore and settings
- [x] Inconsistent hover-over for follow and version count in data asset details page.

https://user-images.githubusercontent.com/83201188/157595786-6fefaf45-17f4-4b58-ac9e-fbafa5880f99.mov

- [x] The count presentation should be consistent for activity feed.
<img width="472" alt="Screenshot 2022-03-10 at 11 27 26 AM" src="https://user-images.githubusercontent.com/83201188/157599075-20bb8529-d800-42f7-a316-25a7103b22cc.png">

**Comment by harshach** [comment]
- [ ] adding glossary terms as a tag is really hard to do .

https://user-images.githubusercontent.com/38649/157581268-dc2d7056-926d-4b28-9e7c-d42e76958165.mov

**Comment by parthp2107** [comment]
The hover-over tooltip gives the same text as a checkbox innerHTML

https://user-images.githubusercontent.com/83201188/157592545-812098c7-74bd-4910-8c35-0c376c7e3a17.mov

**Comment by pmbrull** [comment]
The icon shown for a user changes depending on if we show the username or the name 
![image](https://user-images.githubusercontent.com/35870520/157607041-0098dfd8-0d8f-4950-8e2e-0bf78f74879b.png)

**Comment by kshinde2512** [comment]
Tag details UI changes after adding a new tag category 
![image](https://user-images.githubusercontent.com/67048554/157644486-7ad2ea15-1890-4c72-bfcf-16f662f5e7b8.png)

**Comment by parthp2107** [comment]
Misaligned icon:

<img width="280" alt="Screenshot 2022-03-15 at 5 21 30 PM" src="https://user-images.githubusercontent.com/83201188/158372350-2b2ee652-9dee-42a7-a7fd-fc6f54ff7a05.png">

**Comment by vivekratnavel** [comment]
The icon is not aligned with the left margin in service pages.

<img width="442" alt="Screen Shot 2022-03-15 at 10 57 23 PM" src="https://user-images.githubusercontent.com/1051198/158525994-a1162321-da5b-4832-a212-5d7373188da5.png">

**Comment by Sachin-chaurasiya** [comment]
> The hover-over tooltip gives the same text as a checkbox innerHTML
> 
>  Screen.Recording.2022-03-10.at.10.24.41.AM.mov

@parthp2107 That is expected behaviour.

**Comment by Sachin-chaurasiya** [comment]
Closing this and moving out alignment related issues to #3115
