### ISSUE TITLE
Usage run fails in Redshift and Snowflake from UI

### ISSUE THREAD

**Issue by codingwithabhi** [open-metadata/OpenMetadata#3360]
**Affected module**
Ingestion Framework

**Describe the bug**

`Failed to deploy pipeline [test_redshift_queryUsage2] due to [Unrecognized field "includeViews" (class org.openmetadata.catalog.operations.pipelines.DatabaseServiceQueryUsagePipeline), not marked as ignorable (2 known properties: "queryLogDuration", "stageFileLocation"]) at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openmetadata.catalog.operations.pipelines.DatabaseServiceQueryUsagePipeline["includeViews"])].`

**To Reproduce**
Run the usage from UI
**Screenshot**
<img width="423" alt="Screenshot 2022-03-10 at 8 27 49 PM" src="https://user-images.githubusercontent.com/63392662/157709365-aa33a911-8ea7-4db9-9e1a-291f12c68387.png">

**Comment by ayush-shah** [comment]
This issue reproduces if the UI (Server instance) and Ingestion Instance are on different versions.
Current bug was reproduced when the server was 0.8.4 and ingestion was 0.9.1.
Closing this issue as it was a version mismatch.
