### ISSUE TITLE
Data Quality - Support skipping columns in profiler

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3372]
**Feature**
Based on https://github.com/open-metadata/OpenMetadata/issues/3326

**Describe the task**
There are columns whose profiling adds 0 values, such as IDs. Support excluding columns.

To do this:
- Update the profiler config with an array of columns

**Comment by pmbrull** [comment]
Let's work on this after having the `profilerConfig` property in the Table entity

**Comment by harshach** [comment]
@pmbrull @TeddyCr lets handle this in 0.11.1 release?

**Comment by pmbrull** [comment]
yep let's handle this
