### ISSUE TITLE
AWS SSO and Google SAML support

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#3376]
**Is your feature request related to a problem? Please describe.**
As an admin, I'd like to integrate OpenMetadata with LDAP for authentication.

**Describe the solution you'd like**
I'd like to have some environment variables to specify the usual parameters to connect OpenMetadata to the company LDAP.

**Comment by sfirke** [comment]
Agree this feature would be very valuable.  I see on the Roadmap for 0.9.2, `Support for AWS SSO and LDAP`.  Would that support LDAP beyond AWS too?  I am working with Microsoft's Azure Active Directory LDAP service.

**Comment by irbian** [comment]
Hi!

I don´t see this feature on https://github.com/open-metadata/OpenMetadata/releases/tag/0.11.1-release , will be then realeased on 0.12?

Regards

**Comment by harshach** [comment]
@irbian if you are in need of this we can do 0.11.2 with this feature available. Let us know

**Comment by konnectr** [comment]
When you plan to add the ability to authorize via local LDAP ?

**Comment by Gunnnn** [comment]
Please, add ldap, it is very needed!

**Comment by AntonArgon** [comment]
Support. Please add local LDAP!!! It's very relevant. Thanks.

**Comment by harshach** [comment]
@konnectr @Gunnnn @AntonArgon we will look into it. cc @mohitdeuex @vivekratnavel

**Comment by konnectr** [comment]
@harshach 
How long to wait in release ?
