### ISSUE TITLE
UI: Add unit test coverage for Activity Feed and conversation threads

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3379]
- [x] Activity Feed on the homepage
- [x] Conversation threads on the sidebar drawer
- [x] Activity Feed tab in the entities page
- [x] Chat icon shown next to entity fields
- [x] Request description icon in entity pages

**Comment by vivekratnavel** [comment]
Current coverage in main branch just for status check:
```
=============================== Coverage summary ===============================
Statements   : 40.34% ( 7335/18183 )
Branches     : 18.3% ( 2790/15242 )
Functions    : 21.75% ( 814/3743 )
Lines        : 37.98% ( 5963/15700 )
================================================================================
```

**Comment by Sachin-chaurasiya** [comment]
Test Coverage for Activity Feed Components

                                                                      | Statements | Branches | Functions | Lines |

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/59080942/161566500-a0a5229b-edae-4ae1-b844-59dad3798807.png">

cc: @vivekratnavel
