### ISSUE TITLE
UI: Error handling

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3380]
- [x] UI should handle errors gracefully and show useful toast messages for the user to understand what went wrong.
- [x] All the unit tests should include negative cases such as 500 response from the server
- [x] When UI comes up first and the server is still starting up, the first API call to `/api/v1/config/auth` fails and the error message is not helpful
- [x] UI should never throw a blank page. This happens when UI doesn't handle an exception that is thrown. Ex: A Promise without a catch

**Comment by ShaileshParmar11** [comment]
Hi , Please also assign the task to me!
