### ISSUE TITLE
Clearly show if the logged-in user is the owner of the Entity

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3385]
**Feature**
Entity can have teams as the owner but it doesn't clearly show if a logged-in user indeed is the owner.

**Describe the task**
Check if the logged-in user belongs to the team which is the owner of the entity, if they are show them as the owner

**Comment by harshach** [comment]
cc @Sachin-chaurasiya

**Comment by aniketkatkar97** [comment]
Edit functionality for owner is not available once owner is selected.
<img width="771" alt="Screenshot 2022-08-25 at 11 32 52 AM" src="https://user-images.githubusercontent.com/51777795/186587325-b1270605-eb96-4e34-88e9-fe819cb40d5b.png">

**Comment by Sachin-chaurasiya** [comment]
completed with #6904
