### ISSUE TITLE
Add support for schema name in database.table hierarchy

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3386]
**Feature**
In some datasources, example snowflake a schema can be different than the database.
When we are initially designing this hierarchy we decided to keep database.table with database and schema name being the same name but in certain data sources this can be different i.e database and schema name can be differ and users would like to have that hierarchy can be maintained.
**Describe the task**
This requires FQN handling update on the backend, UI and ingestion

**Comment by sureshms** [comment]
This issue is already addressed by #3602
