### ISSUE TITLE
Getting test added message on UI for editing tests

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3406]
**Affected module**
UI

**Describe the bug**
Getting test added message on UI for editing tests

**To Reproduce**
- Add a column/table test from data quality tab.
- Edit the added test and click save.
- UI gives`Test columnValuesToBeUnique for last_order_date has been added.` message

https://user-images.githubusercontent.com/83201188/158174233-671b2e08-0e59-42cd-8da3-08c26d64b4c6.mov

**Expected behavior**
Should show proper message as per the actions

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by ShaileshParmar11** [comment]
Hi, can you assign this to me?

**Comment by parthp2107** [comment]
> @parthp2107 Can you please explain the issue in detail?

@vivekratnavel , so when I am trying to edit the test, I get a toast notification saying the `test has been added` instead of saying `edited`. For adding or editing, we get the same notification saying `the test has been added`
