### ISSUE TITLE
Deleting column test shows blank under tests in data-profiler for that column 

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3407]
**Affected module**
UI

**Describe the bug**
Deleting column test shows blank under tests in data-profiler for that column 

**To Reproduce**
- Delete a column test
- Go to profiler
- Check under `tests` for the deleted column test.
- Shows blank instead of showing `No tests available`

**Expected behavior**
Should show `No tests available` when no tests are present

<img width="1423" alt="Screenshot 2022-03-14 at 6 13 49 PM" src="https://user-images.githubusercontent.com/83201188/158175312-42794e0c-d07d-41c4-81bb-b05a564f4161.png">

<img width="1453" alt="Screenshot 2022-03-14 at 6 18 56 PM" src="https://user-images.githubusercontent.com/83201188/158175288-fa5e35f9-0543-4259-ab74-254aa1efc82f.png">

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by ShaileshParmar11** [comment]
Hi, can you assign this to me?
