### ISSUE TITLE
Looker connector | Add in "usage" & "access" metadata for Dashboards & Looks (Charts)

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#3412]
**Feature**
Add `view_count` & `last_viewed_at` for Looker Dashboards & Looks (charts) onto OM Dashboard/Chart entities.

**Describe the task**
We currently do not fetch and expose usage & access data for Looker Dashboards/Looks (Charts). Adding this metadata onto OM would help with many use cases

* sort by most used assets
* Understand usage statistics across assets.

**Comment by harshach** [comment]
@ayush-shah we have usageSummary in dashboard entities https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/data/dashboard.json#L86 . Lets capture the view_count similar to the way we are getting the table usage

**Comment by harshach** [comment]
cc @pmbrull

**Comment by pmbrull** [comment]
I'll be adding the usage together with the lineage information. I'll open another issue for the `last_viewed_at` that we can take together the other schema changes we want to discuss for dashboards and charts
