### ISSUE TITLE
Looker | Issues with attribute mapping on Looker Dashboard/Look (Charts) onto OM

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#3413]
**Affected module**
Ingestion Framework

**Describe the bug**
* `description` currently is hardcoded to `temp`. We need to map it to description (an existing value from GET Dashboard response).
* `dashboardUrl` currently seems to be mapped to `looker_host` (a static value across all dashboard  assets). We need to update this to `“{looker_host}/dashboards/{id}”`.
* `charts` (looks) under a Dashboard are not being pulled onto OM `charts` entity.

**Expected behavior**
Mentioned above

**Version:**
 - Python version: `Python 3.8.10`
 - OpenMetadata version: [e.g. 0.8] `0.9.1`
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]: `openmetadata-ingestion[looker]`

**Comment by ayush-shah** [comment]
This issue is resolved in #3441
