### ISSUE TITLE
Cluster Overview port 8085 and 8586 are unauthenticated

### ISSUE THREAD

**Issue by zipponnova** [open-metadata/OpenMetadata#3415]
**Affected module**
Backend

**Describe the bug**
Asset which is vulnerable is 136.243.150.188. There is an open port 8085 which is http://136.243.150.188:8085/ui/#. Redirects to presto cluster overview. Also another port is open 8586 which lets me see internal CPU performance, virtual network distributions using cpu contention, internal network I/O metrics and kernel metrics. http://136.243.150.188:8586/ 

**To Reproduce**
1. Prestor cluster overview can be visited at http://136.243.150.188:8085/ui/#
2. No password is required. Provide username admin, and you can also bruteforce the users to see other clusters. 
3. CPU metrics can be see at http://136.243.150.188:8586/ 
4. Just traverse different options to view different data. 

**Expected behavior**
Both the ports should either be available for internal usage or should have authorization implemented.

Let me know if this is eligible for bug bounty.

**Comment by zipponnova** [comment]
Also port 9200/Elasticsearch is open 

curl -X GET "136.243.150.188:9200/_cluster/allocation/explain" 

Response:
`{"index":"read-me-hacked-by-nightlionsecurity-ure4zd","shard":0,"primary":false,"current_state":"unassigned","unassigned_info":{"reason":"INDEX_CREATED","at":"2022-03-03T03:42:23.865Z","last_allocation_status":"no_attempt"},"can_allocate":"no","allocate_explanation":"cannot allocate because allocation is not permitted to any of the nodes","node_allocation_decisions":[{"node_id":"OijEb8tCSWOqANrE3zE-4A","node_name":"elasticsearch","transport_address":"172.19.0.2:9300","node_attributes":{"ml.machine_memory":"1073741824","xpack.installed":"true","transform.node":"true","ml.max_open_jobs":"20"},"node_decision":"no","weight_ranking":1,"deciders":[{"decider":"same_shard","decision":"NO","explanation":"a copy of this shard is already allocated to this node [[read-me-hacked-by-nightlionsecurity-ure4zd][0], node[OijEb8tCSWOqANrE3zE-4A], [P], s[STARTED], a[id=pisk608MRoOVSl0kZpgWow]]"}]}]}%   `

**Comment by zipponnova** [comment]
Also this kafka stream is unauthenticated at 192.53.165.139:9092

This command: kafka-topics --bootstrap-server 192.53.165.139:9092 --list --exclude-internal


Sample response:
RAY-APIs
_confluent-command
_confluent-controlcenter-6-1-0-1-AlertHistoryStore-changelog
_confluent-controlcenter-6-1-0-1-AlertHistoryStore-repartition
_confluent-controlcenter-6-1-0-1-Group-ONE_MINUTE-changelog
_confluent-controlcenter-6-1-0-1-Group-ONE_MINUTE-repartition
_confluent-controlcenter-6-1-0-1-Group-THREE_HOURS-changelog
_confluent-controlcenter-6-1-0-1-Group-THREE_HOURS-repartition
_confluent-controlcenter-6-1-0-1-KSTREAM-OUTEROTHER-0000000106-store-changelog
_confluent-controlcenter-6-1-0-1-KSTREAM-OUTEROTHER-0000000106-store-repartition
_confluent-controlcenter-6-1-0-1-KSTREAM-OUTERTHIS-0000000105-store-changelog
_confluent-controlcenter-6-1-0-1-KSTREAM-OUTERTHIS-0000000105-store-repartition
_confluent-controlcenter-6-1-0-1-MetricsAggregateStore-changelog
_confluent-controlcenter-6-1-0-1-MetricsAggregateStore-repartition
_confluent-controlcenter-6-1-0-1-MonitoringMessageAggregatorWindows-ONE_MINUTE-changelog
_confluent-controlcenter-6-1-0-1-MonitoringMessageAggregatorWindows-ONE_MINUTE-repartition
_confluent-controlcenter-6-1-0-1-MonitoringMessageAggregatorWindows-THREE_HOURS-changelog
_confluent-controlcenter-6-1-0-1-MonitoringMessageAggregatorWindows-THREE_HOURS-repartition
_confluent-controlcenter-6-1-0-1-MonitoringStream-ONE_MINUTE-changelog
_confluent-controlcenter-6-1-0-1-MonitoringStream-ONE_MINUTE-repartition
_confluent-controlcenter-6-1-0-1-MonitoringStream-THREE_HOURS-changelog
_confluent-controlcenter-6-1-0-1-MonitoringStream-THREE_HOURS-repartition
_confluent-controlcenter-6-1-0-1-MonitoringTriggerStore-changelog
_confluent-controlcenter-6-1-0-1-MonitoringTriggerStore-repartition
_confluent-controlcenter-6-1-0-1-MonitoringVerifierStore-changelog
_confluent-controlcenter-6-1-0-1-MonitoringVerifierStore-repartition
_confluent-controlcenter-6-1-0-1-TriggerActionsStore-changelog
_confluent-controlcenter-6-1-0-1-TriggerActionsStore-repartition
_confluent-controlcenter-6-1-0-1-TriggerEventsStore-changelog
_confluent-controlcenter-6-1-0-1-TriggerEventsStore-repartition
_confluent-controlcenter-6-1-0-1-actual-group-consumption-rekey
_confluent-controlcenter-6-1-0-1-aggregate-topic-partition-store-changelog
_confluent-controlcenter-6-1-0-1-aggregate-topic-partition-store-repartition
_confluent-controlcenter-6-1-0-1-aggregatedTopicPartitionTableWindows-ONE_MINUTE-changelog
_confluent-controlcenter-6-1-0-1-aggregatedTopicPartitionTableWindows-ONE_MINUTE-repartition
_confluent-controlcenter-6-1-0-1-aggregatedTopicPartitionTableWindows-THREE_HOURS-changelog
_confluent-controlcenter-6-1-0-1-aggregatedTopicPartitionTableWindows-THREE_HOURS-repartition
_confluent-controlcenter-6-1-0-1-cluster-rekey
_confluent-controlcenter-6-1-0-1-expected-group-consumption-rekey
_confluent-controlcenter-6-1-0-1-group-aggregate-store-ONE_MINUTE-changelog
_confluent-controlcenter-6-1-0-1-group-aggregate-store-ONE_MINUTE-repartition
_confluent-controlcenter-6-1-0-1-group-aggregate-store-THREE_HOURS-changelog
_confluent-controlcenter-6-1-0-1-group-aggregate-store-THREE_HOURS-repartition
_confluent-controlcenter-6-1-0-1-group-stream-extension-rekey
_confluent-controlcenter-6-1-0-1-metrics-trigger-measurement-rekey
_confluent-controlcenter-6-1-0-1-monitoring-aggregate-rekey-store-changelog
_confluent-controlcenter-6-1-0-1-monitoring-aggregate-rekey-store-repartition
_confluent-controlcenter-6-1-0-1-monitoring-message-rekey-store
_confluent-controlcenter-6-1-0-1-monitoring-trigger-event-rekey
_confluent-ksql-default__command_topic
_confluent-license
_confluent-metrics
_confluent-monitoring
_confluent-telemetry-metrics
_confluent_balancer_api_state
_confluent_balancer_broker_samples
_confluent_balancer_partition_samples
_schemas
com.getray.tribenaija
connect-configs
connect-offsets
connect-statuses
default_ksql_processing_log

**Comment by harshach** [comment]
@zipponnova we do know these clusters are insecure, they are there for testing only. We are not going to put extra effort mark them secure at this point.
