### ISSUE TITLE
New attributes on Dashboard/Chart entities

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#3416]
**Is your feature request related to a problem? Please describe.**
I would like to source and expose more metadata especially regarding Looker. But I think this might also benefit other Dashboard services too. I would love to see what the community thinks about this
* `folder` --> Folder name of where the Dashboard/Charts live in.
* `refresh_interval` --> time interval on how frequently a scheduled Dashboard/Chart will be refreshed.
* `last_refreshed_at` --> time when a Dashboard/Chart was last refreshed.
* `last_viewed_at` --> Time when a dashboard/chart was last accessed
* `created_by` --> user who created Dashboard/Chart. (having this could cause any confusion with `owner` attribute)

**Describe the solution you'd like**
Ideally I would want the above entity attributes supports on Dashboard/Chart entity on OM

**Comment by pmbrull** [comment]
- folder already done (by project)
- We'll add some common attributes from here https://github.com/open-metadata/OpenMetadata/issues/11967
