### ISSUE TITLE
Docker - Allow OpenMetadata service to reach services in host machine

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3421]
**Feature**
If users want to test the OpenMetadata webhook and if they have a service running in host machine we won't be able to reach that service at all
**Describe the task**

**Comment by akash-jain-10** [comment]
Hello @harshach , As per documentation for Docker, this can be achieved by using `host.docker.internal` or `gateway.docker.internal` as hostname.
Reference - https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds
