### ISSUE TITLE
Snowflake Usage Connector | Exclude Query_Type's that aren't needed for Usage connector

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#3423]
**Is your feature request related to a problem? Please describe.**
Currently the Snowflake Usage connector fetches all query_type's from `information_schema.query_history`. With the `RESULT_LIMIT` we imposed currently `RESULT_LIMIT => 1000`, it would be better to only explicitly fetch Query_Type that are needed for the connector.

Also, the Snowflake information_schema.query_history can fetch up-to `RESULT_LIMIT => 10000`. It would be good to bump this up as well from `1000`.

**Describe the solution you'd like**
We need to only fetch QUERY_TYPES that we might need for usage connections `SELECT`, `CREATE_TABLE_AS_SELECT`, `INSERT`, `MERGE` etc.

OR maybe exclude the below list of QUERY_TYPES's:
`ROLLBACK`, `UNLOAD`, `USE`, `DELETE`, `DROP`, `TRUNCATE_TABLE`, `ALTER_SESSION`, `COPY`, `UPDATE`, `COMMIT`, `SHOW`, `ALTER`, `CREATE_TABLE`, `DESCRIBE`, `PUT_FILES`, `CREATE` etc..

**Comment by ayush-shah** [comment]
Hey @sidhreddy, about the result_limit,it is configurable by user, by default we have kept it at 1000.
They can add the same in json config as per their requirements.

**Comment by sidhreddy** [comment]
@ayush-shah Would be great if we could expose this and have it configurable on the json config. Is it already available to be configured?

**Comment by ayush-shah** [comment]
Yes, it is available to be configured. 


      {
        "source": {
          "type": "snowflake-usage",
          "config": {
            "host_port": "account.region.service.snowflakecomputing.com",
            "username": "username",
            "password": "strong_password",
            "database": "SNOWFLAKE_SAMPLE_DATA",
            "account": "account_name",
            "warehouse": "COMPUTE_WH",
            "service_name": "snowflake",
            "result_limit": 1000,
            "duration": 2
          }
        },

**Comment by sidhreddy** [comment]
@ayush-shah Great. Thanks!
