### ISSUE TITLE
Data Quality - Missing config minValue

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3427]
**Affected module**
UI

**Describe the bug**
If we have a test with minValue 0, the Config in the UI does not show the value for the minValue. Let's review the truthy check to allow for 0 as well.

**To Reproduce**

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/35870520/158347156-a20c40e2-5b3e-4d27-bbb3-4be6e13fde90.png">

Real config `ColumnValuesToBeBetween(minValue=0, maxValue=99)`

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Hi, Can you please assign this to me?

**Comment by pmbrull** [comment]
done! thanks @ShaileshParmar11. IDK why but until you do not comment, I cannot see you on the assignee list 🤔

**Comment by ShaileshParmar11** [comment]
I am not added as maintainer yet, thats why 😅

**Comment by pmbrull** [comment]
> I am not added as maintainer yet, thats why 😅

ooh I see. Maybe @harshach could add you to the team https://github.com/orgs/open-metadata/people
