### ISSUE TITLE
Not filtering deleted entities

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3432]
**Affected module**
UI/backend

**Describe the bug**
Not showing deleted entities

**To Reproduce**
- Delete entity
- Click on show deleted on explore page

https://user-images.githubusercontent.com/83201188/158367097-6ddd709c-36e2-41ce-9581-d6dc77da8509.mov

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
@parthp2107 , can you provide the API response for the `show deleted` API call?

**Comment by parthp2107** [comment]
> @parthp2107 , can you provide the API response for the `show deleted` API call?

@Sachin-chaurasiya
<img width="756" alt="Screenshot 2022-03-15 at 5 03 54 PM" src="https://user-images.githubusercontent.com/83201188/158369225-19166992-d9d1-40e6-8ee5-1ceca0efc4e1.png">

**Comment by harshach** [comment]
@parthp2107 how are you testing this. I am not able to reproduce. Check the recording here 

https://user-images.githubusercontent.com/38649/158472801-061a450e-0ea0-4731-8039-7a97a93639ba.mov
