### ISSUE TITLE
Able to add comment/reply in deleted entity

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#3457]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend & UI

**Describe the bug**
I can able to replay on deleted entity thread. is it expected behaviour? as backend also not throwing any exception. 

**To Reproduce**
1. Delete any entity, it will create change event.
2. go to activity feed tab in deleted entity and reply on the conversation.

Screenshots or steps to reproduce
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71748675/158572811-50365eaa-7b9e-407e-8d8b-a636e02e2674.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
@Sachin-chaurasiya @vivekratnavel

**Comment by vivekratnavel** [comment]
This is interesting. I think we should allow conversations and replies on deleted entities especially since we are showing in the UI as deleted entities. 

This is the use case I am thinking of - An admin deletes an entity by mistake. If we allow conversations to happen, it will give someone an opportunity to fix the mistake. It will also give everyone an opportunity to ask the admins why an entity was deleted and so on.

@harshach @ShaileshParmar11 Let me know your thoughts.

**Comment by Sachin-chaurasiya** [comment]
> This is interesting. I think we should allow conversations and replies on deleted entities especially since we are showing in the UI as deleted entities.
> 
> This is the use case I am thinking of - An admin deletes an entity by mistake. If we allow conversations to happen, it will give someone an opportunity to fix the mistake. It will also give everyone an opportunity to ask the admins why an entity was deleted and so on.
> 
> @harshach @ShaileshParmar11 Let me know your thoughts.

@vivekratnavel, Yeah, we should allow conversations on deleted entities like github does for closed PRs and Issues.
So if the admin deleted an entity by mistake then anyone from the Organization can communicate and ask to fix the mistakes.

**Comment by ShaileshParmar11** [comment]
> This is interesting. I think we should allow conversations and replies on deleted entities especially since we are showing in the UI as deleted entities.
> 
> This is the use case I am thinking of - An admin deletes an entity by mistake. If we allow conversations to happen, it will give someone an opportunity to fix the mistake. It will also give everyone an opportunity to ask the admins why an entity was deleted and so on.
> 
> @harshach @ShaileshParmar11 Let me know your thoughts.

Agreed with your thought.

**Comment by harshach** [comment]
@vivekratnavel @Sachin-chaurasiya  github allows one to re-open the thread with a comment. We should support that just like an entity can be restored, a thread can be restored as well. So if someone deleted a thread one can re-open with a comment.
In next versions we should support locked threads where no-one can comment or restore only admin can
