### ISSUE TITLE
Data Quality - Custom SQL Tests

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3463]
**Feature**
Based on https://github.com/open-metadata/OpenMetadata/issues/3326

**Describe the task**
Support custom metrics definition. We need to allow users to give us an SQL query that we can associate to a specific column and link to a test.

We should also prepare the abstraction to support custom python code to be executed.

Also, these custom tests might not be directly related to a metric, so let's update the test framework to allow this easily -> execution vs report-only

**Comment by mariotaddeucci** [comment]
Hey, one question about ir?
With this feature, will we be able do push tests from a simple interface?
Like, there’re some tools that we use, such soda, dbt test and custom tests using spark with GE.
If we have a simple interface, we could easily push this results and centralize everything into one page.

**Comment by harshach** [comment]
@mariotaddeucci yes thats the plan. We are already support pushing tests and test results from GreatExpectations.
With this ticket our goal is to allow creating custom tests through UI & Api and let the clients push results of those tests onto OpenMetadata

**Comment by mariotaddeucci** [comment]
Awesome
