### ISSUE TITLE
Glossary is displayed in owned data tab on User profile page

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#3473]
**Affected module**
UI

**Describe the bug**
Glossary is displayed in owned data tab on User profile page

**To Reproduce**
- Navigate to Glossary page from Settings 
- Create a new glossary and add glossary term
- Navigate to Profile page from Mydata page
- Created glossary is displayed in Owner data tab

![Screenshot from 2022-03-16 22-28-49](https://user-images.githubusercontent.com/67048554/158646953-60e2f69a-f025-43ab-8bf8-537cadf5e823.png)

**Expected behavior**
Glossary should not be displayed in Owned data tab

**Version:**
 - OpenMetadata version: 0.9.1

**Additional context**
NA

**Comment by kshinde2512** [comment]
@ShaileshParmar11

**Comment by ShaileshParmar11** [comment]
Hi kindly assign this to me!
