### ISSUE TITLE
Add support for Localization

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3474]
**Is your feature request related to a problem? Please describe.**
It would be great to have support for Localization to consume Open Metadata in other languages.

**Describe the solution you'd like**
I would like Open Metadata to use https://react.i18next.com/ to support localization

**Acceptance Criteria**

- [x] Every label or message should support translation
- [x] An option to switch between languages
- [x] Doc on how to contribute to other languages

**Comment by mohoval** [comment]
Does it mean to be able to customize for language support?
I wanted to try it myself. When will this feature be added?

**Comment by sureshms** [comment]
This issue has been addressed.

**Comment by chirag-madlani** [comment]
Completed in Release 1.0
