### ISSUE TITLE
Add tier support for topics

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#348]
currently, we have a tier for tables, need to add tier support for topics as well.

**Comment by harshach** [comment]
@Sachin-chaurasiya @darth-coder00  aren't you using tags to update the topic and table tiers? why this needs to be handled differently

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya @darth-coder00 aren't you using tags to update the topic and table tiers? why this needs to be handled differently

@harshach yes we do use tags for tables, we will do the same for topics as well.

**Comment by Sachin-chaurasiya** [comment]
Closing this issue as we will handle tiers via tags.
