### ISSUE TITLE
[UI] Default Value for User's not Assigned to any Teams on User's Listing Page

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#3480]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Let's add a default value when user is not assigned to any Team. Ex. `None`.
![image](https://user-images.githubusercontent.com/15995028/158744990-2ad46386-9888-44e5-870c-c56862cccb45.png)

**Version:**
 - OpenMetadata version: 0.9.0

cc - @darth-coder00, @harshach

**Comment by darth-coder00** [comment]
@ShaileshParmar11 can you look into this with add user thing?

**Comment by ShaileshParmar11** [comment]
Yes, Sure ill look in to it.

**Comment by ShaileshParmar11** [comment]
Can you assign this to me?
