### ISSUE TITLE
OAUTH authentication - support multiple principal fields

### ISSUE THREAD

**Issue by mosiac1** [open-metadata/OpenMetadata#3511]
This is a follow-up to this commit https://github.com/open-metadata/OpenMetadata/commit/9a8d29b8cadef3a45393f8ff6771efdfad9635e5, which added the option to configure the email claim field. 

**Is your feature request related to a problem? Please describe.**
Some proprietary OAuth systems don't have a single JWT field used to provide the email or name of the user. (e.g: when logging in through the UI, an `email` field may be provided, but for bot accounts used for ingestion `email` is not a valid property so `user` or `sub` is provided.)

**Describe the solution you'd like**
Instead of a single filed `jwtEmail` allow the configuration of `principalClaims` (or any other suitable name) as a set of fields. The default could be `[email, preferred_username, sub]` to keep current functionality the same.

**Additional context**
I can work on this issue if the community approves!

**Comment by harshach** [comment]
Thanks @mosiac1 for filing this. Assigned the issue to you.
