### ISSUE TITLE
Snowflake doing multiple logins per ingestion session

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3521]
**Affected module**
Ingesiton

**Describe the bug**
Snowflake connector does multiple logins. For metadata extractions, we are seeing 2 logins and if we use profiler it asks for one more.

**Expected behavior**
We should build one connection use it where we needed. 
For profiler, if it is invoked via metadata extraction we should pass the connection to profiler to use from metadata extraction.
Thanks for reporting @kevinbtai

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@ayush-shah as we are refactoring the snowflake and SQL, let's double-check if we cover this. 
shouldn't be creating more than 1 connection.

**Comment by OnkarVO7** [comment]
I'll be working on the issue
