### ISSUE TITLE
Ingestion: View's Lineage generation is not working in Postgres or Snowflake

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3526]
**Affected module**
Ingestion

**Describe the bug**
Views table lineage is not working for Postgres or Snowflake

**To Reproduce**

<img width="445" alt="image" src="https://user-images.githubusercontent.com/38649/159100023-93b059a2-12a7-48bf-bd00-eff5d593a9e0.png">
<img width="882" alt="image" src="https://user-images.githubusercontent.com/38649/159100030-bdca4231-238e-45b4-8227-731ff89bafa7.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by codingwithabhi** [comment]
Hi @harshach `get_view_definition()` returns the `select * from table` as per above example,Lineage will not be created because `sqllineage` requires the `create` query to generate source and target tables.
cc @ayush-shah

**Comment by sfirke** [comment]
This also does not work for MSSQL, it would be an excellent feature if it did.  Should I open a separate issue?

**Comment by ayush-shah** [comment]
Hey @sfirke, we have already started working on the same.
you can refer this PR #3643.

**Comment by ayush-shah** [comment]
Hey @sfirke, yes, it would be easier to track the same. Thanks.
We will test the same out and let you know on the progress for the same.

**Comment by codingwithabhi** [comment]
Postgres Lineage is fixed with #4196

**Comment by ayush-shah** [comment]
Closing this ticket as Snowflake as well as Postgres - both are fixed in the latest main.
