### ISSUE TITLE
Ingestion: Profiler is not working on views

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3529]
**Affected module**
Ingestion

**Describe the bug**
Profiler is not working on  Snowflake views. We should check other datasources as well.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
We'll also need to tackle further changes on this. After https://github.com/open-metadata/OpenMetadata/pull/3464, the profiler is not working as expected as we cannot obtain the database name when creating the ORM object

**Comment by pmbrull** [comment]
Hi @harshach in order to test this we might need to first handle the hierarchy `service name > db name > schema name> table name`, otherwise the profiler cannot obtain the real schema name when building the queries. Let's sync on how to tackle this, as currently the snowflake profiler fails

**Comment by pmbrull** [comment]
As discussed, I'll proceed with a snowflake-specific workaround to get things patched up for 0.9.2. Let's sync later on for a more cohesive solution. Thanks 🙏

**Comment by pmbrull** [comment]
Prepared a workaround on the snowflake db naming issue and tested ingestion + profiling on a fresh view. Everything is working on my end out of the box.

**Comment by sfirke** [comment]
Running 0.9.0 the profiler does not work on MSSQL Views either.  Will this closed issue have fixed that for 0.9.1 or should I open a separate issue?

**Comment by pmbrull** [comment]
Hi @sfirke, running the profiler workflow, it computes the metrics for views as well. I'll open an issue though to check the profiler being directly enabled in the metadata ingestion pipelines. Thanks
