### ISSUE TITLE
S3 connector to read parquet, csv and other format files and generate metadata based on that

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3538]
**Is your feature request related to a problem? Please describe.**
Currently, users need to use the Glue connector to read the tables with external storage set to S3. This might not meet the requirements for several users as Glue APIs can be expensive and also many orgs might not want to use Glue.

**Describe the solution you'd like**
Build S3 DataLake connector to read the files from the S3 bucket and parse the files to generate the schema and store it in OpenMetadata

**Describe alternatives you've considered**

**Additional context**

**Comment by ayush-shah** [comment]
Creating an issue for gcs as well to support file formats

**Comment by OnkarVO7** [comment]
Closed in https://github.com/open-metadata/OpenMetadata/pull/5343
