### ISSUE TITLE
UI: Add unit tests for Glossary

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#3539]
**Feature**
Glossary unit tests

**Describe the task**
Add unit tests to support functionality of Glossary page

- [x] Glossary Page tests
- [x] Glossary Details tests
- [x] Glossary Term Details tests
- [x] Add Glossary tests
- [x] Add Glossary term tests

**Comment by vivekratnavel** [comment]
Current coverage in main branch just for status check:
```
=============================== Coverage summary ===============================
Statements   : 40.34% ( 7335/18183 )
Branches     : 18.3% ( 2790/15242 )
Functions    : 21.75% ( 814/3743 )
Lines        : 37.98% ( 5963/15700 )
================================================================================
```
