### ISSUE TITLE
Activity Feed: Soft deletion is reported as Update event instead of delete

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3541]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
When a table gets deleted, its "deleted" column gets updated to support soft delete.
<img width="838" alt="Screen Shot 2022-03-20 at 10 38 33 PM" src="https://user-images.githubusercontent.com/1051198/159210222-77875997-3cc1-4813-a94f-4136a7353f52.png">

**To Reproduce**
Delete a table 

**Expected behavior**
The feed shows the event as table deleted

**Comment by mohityadav766** [comment]
Fixed
