### ISSUE TITLE
Able to create roles with the same name.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3552]
**Affected module**
UI

**Describe the bug**
Able to create roles with the same name.

**To Reproduce** 

<img width="320" alt="Screenshot 2022-03-21 at 4 22 11 PM" src="https://user-images.githubusercontent.com/83201188/159247718-47ce3aed-6886-44c4-bd83-c447d2b006da.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment]
@parthp2107, are we getting any errors from the backend?

**Comment by parthp2107** [comment]
@Sachin-chaurasiya, the backend is not throwing any error.

**Comment by Sachin-chaurasiya** [comment]
@parthp2107, on UI we show displayName and we can create roles with the same display name but not with the same name.
This is already handled so closing this issue.
