### ISSUE TITLE
Href links don't work in description dropdown

### ISSUE THREAD

**Issue by havardnyb** [open-metadata/OpenMetadata#3554]
**Affected module**
UI

**Describe the bug**
I have tried to place html href in the description of a table, and the link worked out fine. But when you have longer descriptions that get dropdowns to show more, the links dont work when you show the whole description, but works when you show less of the description.

**To Reproduce**
![Screenshot 2022-03-21 at 12 31 09](https://user-images.githubusercontent.com/62031396/159252899-c0d3b634-2b56-482c-8610-ffc914976552.png)
The links works here

![Screenshot 2022-03-21 at 12 31 24](https://user-images.githubusercontent.com/62031396/159252920-649c41e4-fb53-4c6b-a734-f362528e1206.png)
The links dont work here

Kode:
![Screenshot 2022-03-21 at 12 34 58](https://user-images.githubusercontent.com/62031396/159253320-0e979cd4-e719-4fc0-87a3-56f1ddb55cdf.png)

**Expected behavior**
I expected the links to work in both "Show less" and "Show more"

**Version:**
 - IOS
 - Python version: 3.9.10
 - OpenMetadata version: 0.9.1

**Comment by ShaileshParmar11** [comment]
Kindly assign to me
