### ISSUE TITLE
Invalid Field Status - UI

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#3557]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI
**Describe the bug**
Invalid field name status

**To Reproduce**
Go into Service Details page
- Ingesting Sample Data
- http://localhost:8585/service/databaseServices/bigquery_gcp

Screenshots or steps to reproduce
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40225091/159261926-9effecc4-29b6-4c8e-8648-ba262fb5eb82.png">

**Comment by ShaileshParmar11** [comment]
Hi, Kindly assign this to me!

**Comment by ShaileshParmar11** [comment]
Block by #3581 
Even after removing `status` field from API call, we are not getting status from API for more details please refer above issue.
