### ISSUE TITLE
Not getting 'pipelineStatuses' from Airflow Pipelines API

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#3581]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
1. Not getting `pipelineStatuses` field from Airflow Pipelines API
2. if we pass `fields=status` it throws error with status code 400
3. if we pass `fields=pipelineStatuses`, API does't throw any error but also not getting `pipelineStatuses` field in response

**To Reproduce**

Screenshots or steps to reproduce
`http://localhost:8585/api/operations/v1/airflowPipeline?fields=owner&service=bigquery_test`

Response:
```
{
  "data": [
    {
      "id": "227c95b0-9b3b-4902-8c2d-256de9276254",
      "name": "bigquery_test_metadata",
      "displayName": "bigquery_test_metadata",
      "pipelineType": "metadata",
      "owner": {
        "id": "bcf6da47-0689-4fde-8302-b4cdfb5f309b",
        "type": "user",
        "name": "aaron_johnson0",
        "displayName": "Aaron Johnson",
        "deleted": false,
        "href": "http://localhost:8585/api/v1/users/bcf6da47-0689-4fde-8302-b4cdfb5f309b"
      },
      "fullyQualifiedName": "bigquery_test.bigquery_test_metadata",
      "pipelineConfig": {
        "config": {
          "includeViews": true,
          "enableDataProfiler": false,
          "generateSampleData": false
        },
        "schema": "databaseServiceMetadataPipeline"
      },
      "forceDeploy": true,
      "pausePipeline": false,
      "concurrency": 1,
      "startDate": "2022-03-22",
      "endDate": "",
      "pipelineTimezone": "UTC",
      "retries": 1,
      "retryDelay": 300,
      "pipelineCatchup": false,
      "scheduleInterval": "5 * * * *",
      "pipelineTimeout": 60,
      "service": {
        "id": "5359f1cd-ed44-466c-9b9b-622fd1d31ed5",
        "type": "databaseService",
        "name": "bigquery_test",
        "description": "",
        "deleted": false,
        "href": "http://localhost:8585/api/v1/services/databaseServices/5359f1cd-ed44-466c-9b9b-622fd1d31ed5"
      },
      "href": "http://localhost:8585/api/operations/v1/airflowPipeline/227c95b0-9b3b-4902-8c2d-256de9276254",
      "version": 0.1,
      "updatedAt": 1647931665369,
      "updatedBy": "anonymous",
      "deleted": false
    }
  ],
  "paging": {
    "total": 1
  }
}
```

**Expected behavior**
API should send `pipelineStatuses` in response.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

cc @ayush-shah

**Comment by harshach** [comment]
@ShaileshParmar11 you need to pass "status" in fields to get this. Can you try this call http://localhost:8585/api/operations/v1/airflowPipeline?fields=owner,status&service=bigquery_test

**Comment by harshach** [comment]
@ShaileshParmar11 do you have the airflow container running?
