### ISSUE TITLE
Optimize py-tests CI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3589]
**Affected module**
py tests CI

**Describe the bug**
They take too long to run, let's analyze what parts can be improved. IMO we might not need to always install all the plugins as building the ingestion image takes a lot of time!

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@pmbrull lets set a deadline for this and release

**Comment by harshach** [comment]
@pmbrull lets assign this and get it done for 0.13.1
