### ISSUE TITLE
Provide option to get counts for entities using list APIs  by setting limit=0

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#3596]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI. 

**Describe the bug**
Services count shown is 13 whereas count for all the services is 30. Looks like ElasticSearch is aggregating a wrong value from the query.

**To Reproduce**

Ingest lot of services and then check for count on HomePage of OpenMetadata UI.
Also, tried to run metadata_to_es.json ingestion which reindexes Elastic Search. Post that, the count did not change (Ideally this should not be required with the change event handler).

![image](https://user-images.githubusercontent.com/15995028/159535285-46f67831-ff70-472c-baf2-eb33641ff343.png)
![image](https://user-images.githubusercontent.com/15995028/159535478-863f0081-3b1c-418e-ad8c-1c0f83163ca0.png)
![image](https://user-images.githubusercontent.com/15995028/159535733-ce471178-a091-4012-bc03-563cd6a54097.png)

**Expected behavior**
UI HomePage should show count of all the services ingested in open metadata.

**Version:**
 - OS: Ubuntu

cc - @harshach , @sureshms

**Comment by harshach** [comment]
currently, UI is getting counts from the pagination APIs and in some cases using elasticsearch to get the counts. In case of services we are not using ElasticSearch instead we are calling list API with default limit
<img width="829" alt="image" src="https://user-images.githubusercontent.com/38649/159574363-b6ab5749-784a-4acd-86cb-8e98e0df01cd.png">
which means we are listing all of these unnecessary resources even when we needed is count.

I am fixing this by adding pagination for all resources to accept limit=0 which won't query the tables for entities and only gets the count for tables
```http://localhost:8585/api/v1/tables?limit=0``` will get the following response
```
{
data: [ ],
paging: {
total: 17
}
}
```

This will work for all resource classes. @darth-coder00 @Sachin-chaurasiya let's use this API whenever we need a count for a given entity

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya APIs are merged in. Assigning it back to you to make changes on the UI side.
