### ISSUE TITLE
Adding support for database schema name

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#3602]
**Is your feature request related to a problem? Please describe.**
Adding support for schema name. 
One of the examples was Snowflake
Currently Hierarchy of Snowflake data looks like
Database Name -> Schema Name -> Table Name.

OM supports
Service Name -> Database Name -> Table Name.

**Describe the solution you'd like**
Adding support for schema names.

**Comment by harshach** [comment]
@ayush-shah can you paste the snowflake listing page that you were showing for reference here

**Comment by ayush-shah** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40225091/159623873-90210dc4-5abe-4e8e-aa1f-8ff338aaf49a.png">
<img width="321" alt="image" src="https://user-images.githubusercontent.com/40225091/159623912-f398bf79-01e7-4a95-ac68-ba57367184c1.png">
<img width="753" alt="image" src="https://user-images.githubusercontent.com/40225091/159623998-cecda52d-4781-4cb9-80c0-aa4aa13240ec.png">
<img width="677" alt="image" src="https://user-images.githubusercontent.com/40225091/159624019-68e12d5b-b5a5-45b0-9ec0-6a968be949d2.png">
cc: @harshach
