### ISSUE TITLE
Indexes not created properly while running the instance. Index not properly created causes error in updating tags and updating of descriptions

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#3648]
**Affected module**
Local Docker, UI

**Describe the bug**
Indexes not created properly while running the instance. Index not properly created causes error in updating tags and updating of descriptions

Steps to reproduce:
- Run run_local_docker.sh
- Start server
- Explore
- Go to one of the tables
- Change description
- Go to Explore

Expected Output:
Description Changes according to latest change

Actual Output:
Description doesn't change and stays the same whereas we see the activity feed having latest changes

**Comment by pmbrull** [comment]
@harshach I believe this was fixed already, right?
