### ISSUE TITLE
Consistent timezone between OM and Airflow REST

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3655]
**Affected module**
OM & Airflow REST

**Describe the bug**
To summarize this thread
- was using OpenMetadata UI to deploy pipelines
- Athena pipeline didn't started immediately due to the UTC time used in Airflow and OpenMetadata server wasn't using the same UTC
- hence Airflow that the workflow needs to be backfilled it created multiple runs
- In the end, all these workflows ran using the UI and able to get the Metadata
- Few fixes, getting consistent time zone and making sure we have same timezone protocol from OM -> Airflow.
- Edge cases where the ingestion workflow deployed but not show in the UI 

Let's check if we can add catchup=False, as it does not make sense to run the same workflow multiple times for backfilling as the pipeline will always pick the same data.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ayush-shah** [comment]
@pmbrull 
can we try sending the start_date in utc time zone instead of the OpenMetadata server's timezone?
cc: @harshach

**Comment by pmbrull** [comment]
yep, I'll validate the datetime management to make sure we are converting everything to UTC

**Comment by pmbrull** [comment]
@harshach we're already sending UTC from the backend right?

**Comment by harshach** [comment]
@pmbrull I am passing what UI is passing to me. So I guess its not UTC. @ShaileshParmar11 can you pass the UTC time from the UI.

**Comment by ShaileshParmar11** [comment]
@harshach @pmbrull, We are sending UTC time formate from UI i.e `2022-04-20`

**Comment by pmbrull** [comment]
thanks both. I see we are also specifying in the UI that the dates are in UTC. Closing this
