### ISSUE TITLE
Show database + schema together as database name

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#3666]
Possibly related to #3602 and #3386.

**Is your feature request related to a problem? Please describe.**
I ingest from two MSSQL databases, one is test ("A2_Data_UAT") and one production ("A2_Data_Prod").  Both use the `dbo` schema.  Currently in OpenMetadata, tables from both get stored under a single database name, `dbo`.  I'd like the tables to appear as belonging to two different databases.  That info is available in the name that the database object has in its url: `database/a2_data_prod.dbo`.

Right now my test has 237 tables, my prod has 40, but here's what I see on the Explore view - 277 tables in a single database:
![image](https://user-images.githubusercontent.com/7569808/160126549-3fa86507-c41a-4cf4-b85a-6ddb341c6548.png)

**Describe the solution you'd like**
Have the database name show up as two different databases, `A2_Data_UAT.dbo` and `A2_Data_Prod.dbo`, so that I can more quickly see what tables are in test vs. prod.

**Comment by harshach** [comment]
Fixed and changes are in main. Will be part of the upcoming 0.10.0 release
cc @sfirke

**Comment by sfirke** [comment]
Awesome, thank you!
