### ISSUE TITLE
Test: Handle all E2E test cases for apis integrated on UI

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#3680]
Need to add use cases to test out all branches of positive as well as negative cases for API integrations on UI

For instance, E2E tests should cover all the branches from below code snippet
```js
api.then((response) => {
  // if response has data
  // else if it has no data
}).catch((error) => // some error from api)
```

**Comment by harshach** [comment]
@shahsank3t @vivekratnavel lets make this as cypress end-to-end tests
