### ISSUE TITLE
Usage queries tab UI issues

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#3727]
**Affected module**
UI

**Describe the bug**
In Queries tab the duration and date fields are optional, also some queries overlap with the copy icon

![image (1)](https://user-images.githubusercontent.com/39544459/160540346-8b5d2f3f-2527-4bee-8da8-83af3a9a00eb.png)

Also the copied to clipboard text overlaps with the query 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/39544459/160545722-c283b4de-4aae-4029-bbc5-f320d22a7759.png">

**To Reproduce**
Ingest any usage connector

**Comment by harshach** [comment]
@ulixius9 @ayush-shah as part of sample data can we add bigger queries that goes multiple lines instead of single query
