### ISSUE TITLE
Delete team name is displayed on the users profile

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#3733]
**Affected module**
Backend

**Describe the bug**
Delete team name is displayed on the users profile. Upon deleting a team, the team is not removed from the users list array

**To Reproduce**

- Navigate to teams from the settings tab
- Delete a team (eg : Cloud Infra)
- Refresh the page
- Check Users profile
- Deleted team name is displayed

**Before deleting the team - API response**

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya we talked about skipping entity references with deleted status not to show on user profiler

**Comment by Sachin-chaurasiya** [comment]
Yes @harshach , this is fixed so closing this.
