### ISSUE TITLE
Add 'Services' to search/suggest

### ISSUE THREAD

**Issue by dvecerdea** [open-metadata/OpenMetadata#3739]
**Is your feature request related to a problem? Please describe.**
Ability to search for database services (by name). 

**Describe the solution you'd like**
Index database services in Elasticsearch: https://github.com/open-metadata/OpenMetadata/blob/4d09c165d730810c8bb0ec7546c5bdddbae7e48f/catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/search/SearchResource.java#L143

**Describe alternatives you've considered**
Include service name in the fields considered when searching for tables: https://github.com/open-metadata/OpenMetadata/blob/4d09c165d730810c8bb0ec7546c5bdddbae7e48f/catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/search/SearchResource.java#L229

**Additional context**
In our case, we have a big number of trino services, each corresponding to a catalog.  Searching for a service would correspond to searching for a catalog, which is desirable with a large number of services of same type

**Comment by harshach** [comment]
one can do so today using service:service_name in search box. 
We will be adding a advanced search UI that will make it easier to search for specific attributes in a entity

**Comment by harshach** [comment]
@dvecerdea ^
