### ISSUE TITLE
Ingestion Sonar print_ext()

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3751]
**Affected module**
Ingestion sonar

**Describe the bug**
Sonar raises some bugs from `logger.debug(traceback.print_exc())`. https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=3748&id=open-metadata-ingestion&open=AX_ZkymFRV7RtJ8NIzoF

Let's see how we can improve this

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
A colleague of mine shared the following solution (Thanks Miquel, I cannot tag you here as you did not comment :) ).

Instead of `traceback.print_ext()`, use `format_exc()` which returns a string. Test it out with:

```python
import traceback

try:
    a = 1 / 0
except:
    tb_text_1 = traceback.format_exc()
    #content in multiple lines, we can
    formatted_lines = traceback.format_exc().splitlines()
    print(formatted_lines[0])
    print(tb_text_1)
```

cc @ayush-shah Let's start using this for new code

**Comment by ayush-shah** [comment]
Yes, I will modify the same all over our code

**Comment by pmbrull** [comment]
THanks @ayush-shah , not a priority to change it now everywhere. I'm adding that for 0.11
