### ISSUE TITLE
Custom connector in a private pypi repo

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#3753]
## Intro
As a developer of OpenMetadata, I'd like to develop a custom connector that I will publish to a private pypi repo.

## Workflow
```json
{
  "source": {
    "type": "custom_connector"
   ...
}
```

## Private repo of the company
```
/company_repo/src/metadata/ingestion/source/custom_connector.py
/company_repo/setup.py
...
```

## Installation process

$ pip install openmetadata-ingestion **customer_connector**

## References
* https://github.com/pypa/sample-namespace-packages
* https://packaging.python.org/en/latest/guides/packaging-namespace-packages/
* https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-namespace-packages

## Option 1
Rename all sources from `src/metadata/ingestion/source/mysql.py` to `src/metadata/ingestion/source/mysql/__init__.py`. It's a global namespace and clashes of names can happen.

## Option 2
Modify the source loader so that it accepts classes defined with the full package in the type.
```json
{
  "source": {
    "type": "company.package.CustomSource"
   ...
}
```

**Comment by pmbrull** [comment]
Let's go with option 2. We also have https://github.com/open-metadata/OpenMetadata/issues/2848 to move some of the stuff into ingestion-core. We can tackle this together
