### ISSUE TITLE
Parse and Expand Arrays of Structs

### ISSUE THREAD

**Issue by TeraInferno** [open-metadata/OpenMetadata#3763]
One of the best features of Open Metadata is its ability to parse and expand struct types so that you can document and tag the underlying fields individually. This feature should be expanded to support arrays of struct types. Arrays of structs are a pretty common format in schemas and even more so when the tables are more denormalized. If Open Metadata could parse and expand this structure, it would allow users to document and tag particular fields of the structs that make up the array.

I have attached an example array of structs in a json format. It would be useful for users to be able to tag the name field in this array as potentially PII while leaving the lastUpdated field alone as not marked as PII. It could also be useful to add a description to the lastUpdated field to explain how it is updated.

Example JSON with an array of structs:
```json
[
    {
        "name": "John Doe",
        "lastUpdated": "2022-03-04T14:27:48-0700"
    },
    {
        "name": "Bob Smith",
        "lastUpdated": "2022-03-06T14:27:48-0700"
    }

]
```

I don't think we need to parse and expand arrays of data types other than structs. For example, expanding an array of strings or numbers does not make a ton of sense in my view.

I think we can display the parsed arrays of structs in the UI schema page just like we do structs. They can be expanded using the same tree view structure. From the UI Perspective, we would treat them almost the same as structs are treated today. 

This feature would be very helpful and make Open Metadata a much better product.

**Comment by sureshms** [comment]
@TeraInferno, this feature is already supported. Please reopen or open a new issue if the existing functionality does not address this requirement.
