### ISSUE TITLE
Ingestions tests are throwing warnings

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3773]
**Affected module**
Ingestion
**Describe the bug**
======================================================================= warnings summary =======================================================================
ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:35
  /Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:35: PytestCollectionWarning: cannot collect test class 'TestCaseResult' because it has a __init__ constructor (from: tests/unit/profiler/test_session_validations.py)
    class TestCaseResult(BaseModel):

ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:23
  /Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:23: PytestCollectionWarning: cannot collect test class 'TestCaseStatus' because it has a __new__ constructor (from: tests/unit/profiler/test_session_validations.py)
    class TestCaseStatus(Enum):

ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:35
  /Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:35: PytestCollectionWarning: cannot collect test class 'TestCaseResult' because it has a __init__ constructor (from: tests/unit/profiler/test_validations.py)
    class TestCaseResult(BaseModel):

ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:23
  /Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/generated/schema/tests/basic.py:23: PytestCollectionWarning: cannot collect test class 'TestCaseStatus' because it has a __new__ constructor (from: tests/unit/profiler/test_validations.py)
    class TestCaseStatus(Enum):

ingestion/env/lib/python3.9/site-packages/metadata/orm_profiler/validations/models.py:23
  /Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/orm_profiler/validations/models.py:23: PytestCollectionWarning: cannot collect test class 'TestDef' because it has a __init__ constructor (from: tests/unit/profiler/test_workflow.py)
    class TestDef(ConfigModel):

ingestion/env/lib/python3.9/site-packages/metadata/orm_profiler/validations/models.py:44
  /Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/orm_profiler/validations/models.py:44: PytestCollectionWarning: cannot collect test class 'TestSuite' because it has a __init__ constructor (from: tests/unit/profiler/test_workflow.py)
    class TestSuite(ConfigModel):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
---------------------------------- generated xml file: /Users/harsha/Code/OpenMetadata/ingestion/junit/test-results-unit.xml -----------------------------------
=============================================================== 80 passed, 6 warnings in 45.62s ================================================================

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@ayush-shah @pmbrull is this still an issue or can we close it

**Comment by pmbrull** [comment]
pytests is trying to import test cases from false test classes just by name. Not a big issue, but we should clean it up

**Comment by harshach** [comment]
@pmbrull closing this, if we attempt doing it lets re-open when we have PR ready
