### ISSUE TITLE
Option to hide specific column contents in the sample data option of data-ingestion

### ISSUE THREAD

**Issue by joswlv** [open-metadata/OpenMetadata#3776]
**Is your feature request related to a problem? Please describe.**
In data-ingestion, I would like a function to hide the data of a specific column in the sample data option.
Due to privacy issues, the option to hide the data of a specific column in the sample data is required.

**Describe the solution you'd like**

<sample data>

| col1 | col2 | col3            |
|------|------|-----------------|
| a    | b    | ##hidden_data## |
| c    | d    | ##hidden_data## |
| e    | f    | ##hidden_data## |

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
@joswlv how about we hide any column that has PII tag ? and only users who will have PII policy can look into that

**Comment by sureshms** [comment]
With policies rework done in #4199 this requirement is addressed. One can write a condition to say any table with certain sensitive tags is not visible to all the users with certain exceptions (team members can see, people with certain roles can see, etc.). 

While this is different from the solution described in this issue, it does provide a way to hide sensitive data. @joswlv, let us know if this takes care of your needs. For now, resolving this issue.
