### ISSUE TITLE
Manual Lineage Editor: UX Improvements

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#3793]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
- We allow edge connection only if we drop edge on node circle, this takes much effort because we have to do connection on that small circle.
- Currently, the Manual lineage editor only supports edge deletion and when we delete the edge it also deletes the node, which leads to a bad user experience.

**Expected behaviour**

- [x] Allow edges to be connected even if the user drops it on the box and not only circle
- [x] Allow users to delete edge and node separately

cc: @harshach @shahsank3t @darth-coder00 @sureshms @vivekratnavel

**Comment by shahsank3t** [comment]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/6761317/167783658-ff536f88-2548-4a23-8406-b6e1eb809244.png">
