### ISSUE TITLE
Replace sqlalchemy-trino with trino[sqlalchemy]

### ISSUE THREAD

**Issue by dvecerdea** [open-metadata/OpenMetadata#3799]
**Affected module**
Ingestion: trino client is out of date

** Context **
trino client (https://github.com/trinodb/trino-python-client) is now (and since v0.307.0) releasing with built-in SQLAlchemy driver

See sqlalchemy-trino v0.4.1 release: https://github.com/dungdm93/sqlalchemy-trino/releases/tag/v0.4.1

**Describe the bug**
sqlalchemy-trino is now locked on an older version (v0.306.0) of trino client (which is missing some needed fields, eg. http_session).
trino[sqlalchemy] should be used instead of sqlalchemy-trino

**Expected behavior**
replace sqlalchemy-trino with trino[sqlalchemy]: https://github.com/open-metadata/OpenMetadata/blob/3b7b65d46cdeff62c478a9ea4ac3734a8b4da365/ingestion/setup.py#L105

**Version:**
 - OpenMetadata version: 0.9.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[trino]==0.9.0`]

**Comment by dvecerdea** [comment]
May I be assigned to this? Thanks

**Comment by ulixius9** [comment]
Closing this issue as PR #3800 is merged.
