### ISSUE TITLE
Python Client for Roles and Policies

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3809]
Let's prepare a mixin for interacting with Roles and Policies with the Python client, in case users want to use the API directly.

Do not only have the list, get etc, but also utility methods, such as updating a default role. It should wrap the following logic:

```python
import requests
import json

# Get the ID
data_consumer = requests.get("http://localhost:8585/api/v1/roles/name/DataConsumer").json()
data_consumer

# Prepare the patch
patch = [{"op": "replace", "path": "/defaultRole", "value": "true"}]

res = requests.patch(
    "http://localhost:8585/api/v1/roles/b3296549-5e9c-42c6-b51d-94eee9c8c675",
    data=json.dumps(patch),
    headers={"Content-Type": "application/json-patch+json"}
)
res.json()
```

**Comment by pmbrull** [comment]
You can check the implementation of similar Mixins, such as the `TableMixin` class, and prepare the methods on a new role_mixin.py file.

**Comment by YashasviChaurasia** [comment]
@pmbrull I would like to work on this issue.
Thank you

**Comment by pmbrull** [comment]
Hi @YashasviChaurasia assigned the issue, thanks for contributing. You can reach out to us in Slack if you have any questions. I'd recommend reviewing the API docs (https://docs.open-metadata.org/swagger.html) and the ometa_api implementation for some examples. Thanks

**Comment by schlameel** [comment]
I will work on this

**Comment by ulixius9** [comment]
closing by #10531
