### ISSUE TITLE
Deleting the default role disables using another one as default

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3812]
**Affected module**
Backend / UI

**Describe the bug**
If we have a role X assigned as the default, it is possible to delete it. However, after doing so, we are unable to PATCH another role assigning the default as it tries to update the delete role as well.

**To Reproduce**
- assign default to `Data Consumer`
- Delete it
- Try to patch `Data Steward` to be the default.

**Expected behavior**
Either protect the deletion of the default role to force users to reassign it beforehand, or allow to assign a default role if there is no current default role.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
cc @harshach @vivekratnavel

Thread on slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1649064791566639

**Comment by harshach** [comment]
@sureshms assigning this to you to block the deletion of default org roles

**Comment by sureshms** [comment]
@harshach, disallowing system policies and roles to handle this.
