### ISSUE TITLE
Table Deprecation Plan

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#3833]
**Is your feature request related to a problem? Please describe.**
Requesting to add a feature to support custom communications to downstream customers related to table events, in the instance of deprecation / migration / data quality issue etc.

**Describe the solution you'd like**
As a table owner, I need the ability to send a communication to downstream customers in the scenario of deprecating a table.
I shall be able to write a custom message with guidance on what is happening and by when a particular action needs to be completed.

Example

> "Hello downstream customer, we are depreating table XYZ because of reason 123. You should migrate to table ABC by ETA. etc.."

As a table owner, I need the ability to choose between different notification types: 
1. raising a ticket in internal ticketing system (most important)
2. Slack notification
3. Outlook email

I should be able to configure automatic followup reminders if a particular action hasn't been actioned or a ticket has not been resolved.

The feature should be able to detect relevant audience / downstream customers for the notification (e.g. based on "follower").

**Comment by harshach** [comment]
@vivekratnavel lets finish this in 0.11.1

**Comment by vivekratnavel** [comment]
We have completed the [announcements feature](https://github.com/open-metadata/OpenMetadata/issues/5685) that will ship in the 0.12 release. That covers most of the requirements listed in this issue. We will continue to work on email integration for notifications

**Comment by sureshms** [comment]
@vivekratnavel can you close this issue if the work is done and open a separate issue for email integration?

**Comment by vivekratnavel** [comment]
Currently, we don't mark the table as deprecated. But, that is a good idea as well. I have created #6937 and #6939 to track these improvements.
