### ISSUE TITLE
Service Connection & Schema Name - Revisit DBT

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3863]
test that the DBT integration works with the schema change

**Comment by OnkarVO7** [comment]
I'll be working on testing the DBT

**Comment by pmbrull** [comment]
Hi, @OnkarVO7, is there anything else we need to do here?

**Comment by OnkarVO7** [comment]
DBT has been handled in the #3736 and it works with the new schema changes. This issue can be closed @pmbrull

**Comment by ayush-shah** [comment]
Closing this issue - fixed in #3736
