### ISSUE TITLE
UI support for new Service and Ingestion APIs

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#3871]
- [x] Schema updation of generated typescripts and integration on UI
- [x] #3954
- - [x] Database services
- - [x] Messaging services
- - [x] Dashboard services
- - [x] Pipeline services
- [x] #3924
- - [x] List APIs
- - [x] Get APIs
- - [x] Create APIs
- - [x] Update APIs
- - [x] Delete APIs
- [x] #3925
- [x] #3926
- [ ] #4019
- [ ] #4020
- [x] #4057 
- [x] #4116 
- [x] #4143
- [x] #4119

**Comment by darth-coder00** [comment]
[link](http://example.com)

**Comment by devyani-kaushik** [comment]
[Ingestion UI.zip](https://github.com/open-metadata/OpenMetadata/files/8448739/Ingestion.UI.zip)

**Comment by harshach** [comment]
@devyani-kaushik just upload the images directly

**Comment by darth-coder00** [comment]
Closing for 0.10.0
