### ISSUE TITLE
Check asyncio

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3906]
Analyse and see if it makes sense to implement asyncio to run the connectors with multiple tables at a time.

We can also leverage AsyncEngine from SQLalchemy 1.4

**Comment by harshach** [comment]
@pmbrull something to look into for 0.11.1

**Comment by pmbrull** [comment]
moving to 0.12, we'll have more room for this

**Comment by harshach** [comment]
@pmbrull lets look at this as part of our perf improvements plan, if its not going to be useful lets close it out

**Comment by pmbrull** [comment]
I believe a first good bet would be on updating the queries getting the source metadata instead of relying directly on the dialect. For example, here https://github.com/open-metadata/OpenMetadata/pull/9588/files#diff-9d908935d07272dc6d417aeb3902afd90a7d90020e549822b6c3be8d27b6fd7fR79 we are now using a custom redshift query to get all the tables instead of relying on the default dialect, which first gets ALL schemas and then iterates on top of the results to filter things out.

If after playing with custom queries + batching table comments we still have performance requirements, we can look into concurrency elements, but for now it might not be needed as there are simpler wins.
