### ISSUE TITLE
Add custom service type for internal business systems

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#3912]
**Is your feature request related to a problem? Please describe.**
Often, there are company's internal custom systems, that either cannot be ingested, but still need to be described, or connectors from existing service types doesn't work for ingestion from such internal systems. We have to create these systems using wrong type from the available list. Once this is done, data consumers get confused, because system is assigned to a wrong type (like, MySQL when in fact the system is not MySQL). 

**Describe the solution you'd like**
As per image attached, it would be great to have a custom type of service for non-conventional services. Often, there are internal custom systems, that either cannot be ingested, but still need to be described, or connectors from existing service types doesn't work for ingestion from such internal systems. 
Once the system is added, it should be visible in the list of available systems, that this exact system is "custom" (not Athena or MySQL etc.).

**Describe alternatives you've considered**
As for now, we have to create fake systems with wrong system type. It doesn't make sense for company users (data consumers and data engineers).

**Additional context**

![Screenshot_4](https://user-images.githubusercontent.com/60112387/162200260-d5f22996-0157-43ac-9156-6ef88a6cebfd.png)

**Comment by harshach** [comment]
This is getting shipped in 0.12.1
