### ISSUE TITLE
Service Connection & Schema Name - Improve Tableau

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3921]
Tableau site_name and site_url both are same - we need to make one of these optional and use the same in the process of creating an connection.

From the thread https://openmetadata.slack.com/archives/C02B6955S4S/p1649328082484669

**Comment by ayush-shah** [comment]
Yes, removing one of them and reusing the other one will be better

**Comment by ayush-shah** [comment]
Resolved this in #3946
