### ISSUE TITLE
Analyse SparkSession in SourceConfig JSON Schema

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3922]
based on the set_spark discussion on https://github.com/open-metadata/OpenMetadata/pull/3710

Check if it would make sense to add a SparkSessionURL property in the sourceConfig JSON Schema as a property to allow users pass their own custom spark cluster session URL.

This property can be added somewhere else, no need to be that specific class, but the important part is that is should be source related, not workflow related.

Thanks

**Comment by ayush-shah** [comment]
As discussed, shifting this to 0.11.0.
cc: @pmbrull @harshach

**Comment by harshach** [comment]
@ulixius9 @ayush-shah @pmbrull anything remaining here?
