### ISSUE TITLE
ConnectionOptions and ConnectionArguments not working

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#3965]
**Affected module**
Ingestion

**Describe the bug**
ConnectionOptions and ConnectionArguments in the config shows empty even when options are passed into it.

**To Reproduce**

Screenshots or steps to reproduce
<img width="499" alt="image" src="https://user-images.githubusercontent.com/28966081/162482413-759c2e82-fc4b-4689-b9c0-839b4c7f2131.png">

**Comment by ayush-shah** [comment]
Snowflake's Private key support is dependent on this PR - will be fixed once the above issue's PR is merged.
Same goes for Bigquery.

**Comment by pmbrull** [comment]
https://github.com/open-metadata/OpenMetadata/pull/4023/files#diff-aa8fe9edb29fb4c233310c068ddb8f95be0082a0c3548dcfe6d81bdb8eb5edd0L16 here we are also updating these JSONs to allow for key-value dicts in connectionArgs and connectionOptions. Having the http_path in there was making other services fail

**Comment by ayush-shah** [comment]
This has been resolved - passing additionalProperties as true with a key value format.
