### ISSUE TITLE
Dashboard entity FQN is not in a proper way.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#397]
Here we are getting the dashboard name "Sales Dashboard",
![ss2](https://user-images.githubusercontent.com/59080942/132013911-dbe2f828-d0b1-4844-9bbb-4c974517a905.png)

and when we go to the details page we get something like this "sample_superset.31" instead of "sample_superset.Sales Dashboard" 

![ss3](https://user-images.githubusercontent.com/59080942/132014091-ce917899-95df-4237-8d0a-613b546b8cb3.png)

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya for dashboards and charts name is not going to be unique like we have in tables and topics. Instead I've used dashboardid and chartid into the name and added displayName. So we should use the displayName to show in dataset page and fqdn will be like that for now

**Comment by Sachin-chaurasiya** [comment]
> @darth-coder00 @Sachin-chaurasiya for dashboards and charts name is not going to be unique like we have in tables and topics. Instead I've used dashboardid and chartid into the name and added displayName. So we should use the displayName to show in dataset page and fqdn will be like that for now

@harshach sure, I have changed the name to displayName.
