### ISSUE TITLE
Random strings in Recently searched terms in OpenMetadata fresh install

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#3997]
**Affected module**
Does it impact the UI, backend, or Ingestion Framework?
UI

**Describe the bug**
When OpenMetadata is installed first, the Recently searched terms are seeded with random strings.
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1417689/162626155-5c73fb86-52a4-4a1c-a63a-88b407060e58.png">

**To Reproduce**
Fresh install of OpenMetadata and log in.

**Expected behavior**
Remove these random strings. Instead, it is okay to show nothing under Recently searched terms.

cc @harshach

**Comment by harshach** [comment]
@ShaileshParmar11 can we add version to the cookie name so that we are not retrieving or parsing names that does't belong to the cookie
