### ISSUE TITLE
Highlight the matching texts in the search results

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#40]

**Comment by darth-coder00** [comment]
Need to change the way of passing the highlighted text for name and description as now we have markdown in table description. 
Sending highlighted text in `<b>` tag won't be enough.
Might need to send it inside a `<span>` with some `class` attribute

**Comment by darth-coder00** [comment]
Can we send highlighted text inside `span` like `<span class="text-highlighter">Searched text</span>`
