### ISSUE TITLE
Service Connection - Hive required

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4001]
Check how to properly use oneOf or anyOf to use different required fields in the Hive connection

**Comment by pmbrull** [comment]
Based on https://github.com/koxudaxi/datamodel-code-generator/issues/495 it seems a bit too complex for what we’re trying to achieve. Lets update the descriptions accordingly for simplicity

**Comment by harshach** [comment]
@pmbrull what needs to be done here

**Comment by pmbrull** [comment]
hive connection LGTM. closing this
