### ISSUE TITLE
EntityReference update ingestion

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4012]
EntityReference will have name, displayName, fullyQualifiedName in main, previously name used to point to fullyQualifiedName

so either ingestion or UI is sending name=FQN this needs to change to fullyQualifiedName=FQN and similarly how you reading the entityReferences will change as well

**Comment by ayush-shah** [comment]
Moving this in next release

**Comment by harshach** [comment]
@ayush-shah anything remaining here

**Comment by pmbrull** [comment]
Let's review how we are working with Entity References throughout the ingestion code and make sure we are properly passing name/fqn in the valid fields
