### ISSUE TITLE
OM's health check and K8s unnecessary restarts

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#4038]
OM's health check executes an SQL statement. K8s ReplicaSet depends on OM's health check.
The current behavior is that if MySQL is unhealthy, K8s will mark OM unhealthy too, leading to unnecessary restarts of OM.
I don't think this is the expected behavior by ops guys. We could create a health check that doesn't depend on MySQL, maybe the default one of Dropwizard.

WDYT @akash-jain-10 ?

**Comment by akash-jain-10** [comment]
What should be the expected behaviour of OpenMetadata Server in this case? Will it also shut down or should be working and through response that it's not able to connect to Application Database ?
