### ISSUE TITLE
Airflow APIs - Trigger and test connection

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4039]
- https://github.com/open-metadata/OpenMetadata/issues/3089

**Comment by harshach** [comment]
@pmbrull for this we should just add another api to the airflow_plugin_apis and use sqlalchemy to test it inline and provide the response back to openMetadata server

**Comment by pmbrull** [comment]
yep, this will be helpful during the tests as well, so I'll prioritise the connection test
