### ISSUE TITLE
Add service icon for sample database service and also have default icons for new services

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4046]
**Feature**
<img width="855" alt="image" src="https://user-images.githubusercontent.com/38649/162860522-48c71dea-543c-4abd-b422-066ca26b2440.png">
If there is no service icon matching a service we just show blank icon. 
1. We added new service called SampleData to indicate the sample data that we ingest. We need an icon for this
2. If there is a new service added in Databases, Dashboards, Pipelines etc.. that we don't have an icon for we should show a default icon

cc @vivekratnavel

**Comment by darth-coder00** [comment]
@harshach we have default icons for all 4 service types, looks like `SampleData` service is not present in any of the enums, if it is present in json-schema then all we need to do is generate typescript interfaces and it should work.

CC: @ShaileshParmar11 @vivekratnavel
