### ISSUE TITLE
Docs: Update Auth0 SSO doc

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4061]
Auth0 setup documentation suggests users configure application as "Regular Web Application" which is incorrect. It should be configured as "Single Page Application"

**Comment by ShilpaVernekar** [comment]
@akash-jain-10 @vivekratnavel - Is it just the image that needs a change or are there any further steps that change based on selecting "Single Page Web Apps"

**Comment by vivekratnavel** [comment]
@ShilpaVernekar Just the image needs to be replaced.

**Comment by ShilpaVernekar** [comment]
@vivekratnavel @akash-jain-10 - Created a PR for the same - https://github.com/open-metadata/OpenMetadata/pull/7293

Thanks @parthp2107 for helping with this
