### ISSUE TITLE
ES not updating during ingestion

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4069]
From the following thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1649083295305679

---

ES indexes not always updating during a metadata ingestion workflow on 0.9. No errors on the logs appear.

**Comment by pmbrull** [comment]
@harshach other users faced this as well. IDK if we are missing some logging on the backend side that might make this fail silently 🤔 

cc @ayush-shah, thanks for resurfacing this

**Comment by harshach** [comment]
@pmbrull @ayush-shah I think this is fixed. If its resurfaced let me know. I am going to close it for now
