### ISSUE TITLE
Enable search functionality on tags

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#4080]
**Is your feature request related to a problem?**
Today, search / browse functionality only works on table name / description, but not on tags.
So I'm unable to search for a given tag, but can only select it on left-hand filter menu.

**Describe the solution you'd like**
Enable Search functionality based on tags so I can search for all tables that have a given tag.

**Comment by harshach** [comment]
@trillhaa It already works you need to tags:tag_name

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/38649/163045142-6845b00d-a057-45eb-918b-3c62eac1fc8e.png">

**Comment by trillhaa** [comment]
Got it, thanks. Resolving.

**Comment by trillhaa** [comment]
@harshach - is it possible to search based on table name or column name? Can you please provide any documentation if available

**Comment by harshach** [comment]
@trillhaa we are working on adding all of these in the current PR https://github.com/open-metadata/OpenMetadata/issues/5330
you could however do right now by following
name:orders AND column_names:user_id in the search box itself
