### ISSUE TITLE
UI fails to parse table name with apostrophe

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#4102]
**Affected module**
UI

**Describe the bug**
On clicking the `test's_table4` table UI parses the FQN `gold.default.test_schema.test's_table4` as `gold.default.test_schema.test` hence getting table not found error.

<img width="1507" alt="image (11)" src="https://user-images.githubusercontent.com/39544459/163191206-f9ad4759-35fa-48dd-ab05-69b8243c0c01.png">

<img width="1512" alt="image (12)" src="https://user-images.githubusercontent.com/39544459/163191141-0c763480-e0bf-4891-a04a-a901aa9fdf83.png">

**Comment by harshach** [comment]
@Sachin-chaurasiya table names can contain special characters. We should be able to handle it on UI side cc @vivekratnavel
