### ISSUE TITLE
Rework Roles and Policies - Part 1

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4113]
Currently, Roles and Policies have several issues:
> A Role has only one policy. That policy gets created automatically instead of over `CreateRole` request. 

This will be changed to **A Role has one or more policies. A Role without a policy is not allowed.** APIs will change to reflect this.

Implementation changes:
> Current implementation compiles all the rules from all the policies and uses them to check the permission. To do this, a rule needs to know role information to match relevant rules by role.

Implementation will be changed where Users role decides the policies that apply to the subject. A role has an ordered set of policies. Permission check will be done per policy in the order it is defined. **Policy evaluation will not know about the Role.** Rules only get entityType and entity tags, and Operation information. **Rules will no longer have Role information.**

> Currently, the `Role` **contains** Policies

It is changed to `Role` **has** Policies. This relationship is less strict. When a `Role` is deleted, the `Policies` it refers to are not deleted.

**Comment by sureshms** [comment]
@harshach this is a backward incompatible change. `createRole` request now must now non-null array field `policies` with 1 or more policies.

**Comment by Sachin-chaurasiya** [comment]
@sureshms, Will it need changes on the UI side as well?

**Comment by sureshms** [comment]
> @sureshms, Will it need changes on the UI side as well?

Yes. @harshach will provide details
