### ISSUE TITLE
UI : Remove Save and Discard button from manage tab

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#4124]
**Feature**
Support individual save actions for owner and tier.

**Describe the task**
Today we update the owner and tier with the click of the save button in the manage tab. this change should include separate micro-interaction for both operations.

**Comment by harshach** [comment]
@Sachin-chaurasiya For tier when the user selects one we can show adjacent to that label a button to save. That way we don't keep adding and changing the tier tag every time user clicks on a label

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya For tier when the user selects one we can show adjacent to that label a button to save. That way we don't keep adding and changing the tier tag every time user clicks on a label

@harshach , Yeah We are planning the same.
