### ISSUE TITLE
UI: Support list of policies instead of one policy in role

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#4130]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? UI

**Describe the bug**
Role schema now have list of `policies` instead of single `policy`, need to handle this change on UI

**Comment by sureshms** [comment]
For details related to Rules and Policies changes, see https://github.com/open-metadata/OpenMetadata/issues/4199.

@harshach and @darth-coder00:
1. Creating a role requires at least one policy.
2. Remove the enabled flag for rules. It is only at the policy level.
