### ISSUE TITLE
The UI should show the displayName instead of the name for entities.

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#4137]
**Affected module**
UI

**Describe the bug**
When trying to change the display name for an entity (database, for instance) `'displayName'` is not be visible in UI. Instead, it shows `'name'` in UI.

**To Reproduce**
![Screenshot_3](https://user-images.githubusercontent.com/60112387/163358831-cd850f0f-5dd6-404d-97be-3fc06e109fc5.png)
![Screenshot_4](https://user-images.githubusercontent.com/60112387/163358834-9e6758cf-c28a-4fb9-a6a7-5b32014ff293.png)

Screenshots or steps to reproduce

**Expected behavior**
`displayName` should be visible instead of `name`. 

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**

**Comment by pmbrull** [comment]
cc @darth-coder00
