### ISSUE TITLE
Add searching by database name and teams.

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#4138]
**Is your feature request related to a problem? Please describe.**
It would be more convenient to work with huge amounts of data if there would have been added searching by different entities, not only tables. Usually, you remember database name. It's easier because databases can contain thousands of tables. 

**Describe the solution you'd like**
I would like to be able to search databases and teams as well (in addition to tables, pipelines, topics and dashboards).

**Describe alternatives you've considered**
-

**Additional context**
![photo_2022-04-14_12-52-27](https://user-images.githubusercontent.com/60112387/163360943-2eeffda3-d3dc-4ba3-b76c-8231be67b075.jpg)

**Comment by pmbrull** [comment]
cc @darth-coder00

**Comment by harshach** [comment]
@Tonilyn you can pass owner:(team or user name) database:database name all of these already in index. We allow complex ES queries example owner: Finance AND database: orders

**Comment by Tonilyn** [comment]
@harshach just checked, it works, thank you! However, it would be nice to have this as a part of interface for business users. Business users rarely use queries. That would create a very complex CJM leading to low satisfaction rate among catalogue readers.

**Comment by Tonilyn** [comment]
@harshach Hi! It seems ES queries now doesn't work as they used to in previous OMD versions

1. Can't use "owner: Finance AND database: orders" kind of queries, result is empty 
2. owner/team also returns empty result
3. Now you can't search schemas using query, only databases. Schemas (former database type asset) are more interesting for users in terms of daily usage

Screenshots 
<img width="1378" alt="Screenshot 2022-06-17 at 12 55 18" src="https://user-images.githubusercontent.com/60112387/174285364-4af1ce41-1311-466b-b832-6e9e3ce4c513.png">
<img width="1380" alt="Screenshot 2022-06-17 at 12 56 46" src="https://user-images.githubusercontent.com/60112387/174285376-1604755d-e148-47d8-91d1-a962765b72ed.png">
<img width="1380" alt="Screenshot 2022-06-17 at 12 57 38" src="https://user-images.githubusercontent.com/60112387/174285381-1d63bad5-61df-4070-9af6-42110206bc82.png">

**Comment by Sachin-chaurasiya** [comment]
Hey @Tonilyn, as part of this PR we have landed an Advanced search feature  https://github.com/open-metadata/OpenMetadata/pull/5427.
Now you can use this advanced search feature to get more specific results.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/59080942/173058098-ab88ed85-bc17-4392-aae0-c1eb0b811215.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/173058156-4cb9150e-c26a-4c72-bf58-98882d8500d5.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/173058197-dabcb3f3-c280-4ece-8d64-2ef924d58735.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/173058280-4064fe7f-e937-447f-b35f-f663557c862a.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/59080942/173058340-79fd7dc4-1ee9-4718-ad36-adc0d9f47d59.png">



https://user-images.githubusercontent.com/59080942/173323862-9fd1312d-da53-4503-ab51-b65a173da896.mov

**Comment by Tonilyn** [comment]
@Sachin-chaurasiya that looks fantastic! Can't wait to test!
