### ISSUE TITLE
Activity feed not updating on adding description or tags

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#4154]
**Affected module**
Backend

**Describe the bug**
Activity feed not updating on adding description or tags

**To Reproduce**
- Navigate to any Entity details page
- Update description or Tags and Click on Save
- Navigate to OpenMetadata homepage
- Activity feed is not updated.

https://user-images.githubusercontent.com/67048554/163465460-9f2a3073-5ed1-4e4b-956d-9edbbc318ded.mp4

**Expected behavior**
Activity feed should be updated.

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**

**Comment by kshinde2512** [comment]
@vivekratnavel

**Comment by vivekratnavel** [comment]
This should be fixed with #4152 which fixes #4052

**Comment by vivekratnavel** [comment]
@kshinde2512 Can you please check if it is reproducible in latest main and close this?

**Comment by kshinde2512** [comment]
@vivekratnavel @Sachin-chaurasiya Checked this with the latest main. We can close this issue
