### ISSUE TITLE
Allow automated updates of table/column descriptions using ingestion workflow(s)

### ISSUE THREAD

**Issue by abcabhishek** [open-metadata/OpenMetadata#4179]
**Is your feature request related to a problem? Please describe.**
The use-case here is a situation where the details of a table X are only updated from a backend process and NEVER by any user because it is a system owned table. Based on current behavior, if there is an update to the description of table X using the workflow, it won’t get updated by the ingestion workflow as the subsequent PUT request with description will be rejected.

**Describe the solution you'd like**
As mentioned by Harsha, what we can do:
- Introduce a config option to override descriptions. This will apply to all the entities and user generated content can be overwritten if there is new content on the ingestion side (this config option would allow control whether the request goes through as a put request or as a patch request?)
- Introduce System Tables(entities) where the description updates will preferred from the ingestion side. This can be more nuanced and entities can be tagged or provided type to enable this behavior

**Describe alternatives you've considered**
Current temporary workaround:
- To model the changes to the description programmatically,  create a new sink similar to metadata_rest and use the patch endpoint of the metadata client instead of the put endpoint. 
- 
- This does not mitigate the problem statement in entirety as this will always overwrite the user-made updates made to the table and replace it with the metadata from the workflow process

**Additional context**
NA

**Comment by abcabhishek** [comment]
@harshach for visibility

**Comment by harshach** [comment]
@sureshms FYI ^

**Comment by harshach** [comment]
This is fixed by allowing any user entity to update the description but behave the same way where if there is description they cannot override the existing description. 
Please re-open if this is not sufficient for your use cases
