### ISSUE TITLE
DBT Python SDK example

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4198]
Based on https://openmetadata.slack.com/archives/C02B6955S4S/p1650294072819929?thread_ts=1649981347.920599&cid=C02B6955S4S

**Comment by OnkarVO7** [comment]
Yes I'll add the example

**Comment by OnkarVO7** [comment]
The documentation is updated [here](https://docs.open-metadata.org/v/0.10.1-1/data-lineage/dbt-integration/dbt-python-sdk)
