### ISSUE TITLE
Rework Roles and Policies

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4199]
This is an umbrella issue to track all the changes to Roles and Policies. The following diagram shows the entities related to access control functionality.
![Blank diagram - Page 10](https://user-images.githubusercontent.com/1417689/163835234-36697c35-2806-497f-beeb-db4452557a9a.png)

Roles and Policies for Access Control are described in this [blog](https://blog.open-metadata.org/building-access-control-for-openmetadata-5b842a2abd90). Few changes are being made from the previous version.

API and Modeling changes:
1. A `Role` now has one or more `Policies` with a 1:N relationship instead of a 1:1 relationship. `CreateRole` now requires at least one policy to be attached to a role. A policy is not automatically created during the creation of a role. 
2. Policies that the system comes with have been renamed. `DataConsumerAccessControlPolicy` is now `DataConsumerPolicy` and `DataStewardAccessControlPolicy` is just `DataStewardPolicy`.
3. A policy has rules. Both the policy and the rule had an `enabled` flag. Now the `enabled` flag per rule is removed.

For more details and implementation changes, see the description of the following tasks:
- #3031
- #3776
- #4113 
- #4120 
- #4166 
- #4170 
- #5509 
- #5558
- #2907 
- #3032
- #4079 
- #4580
- #3553
- #4677
- #6172 
- #6336 
- #6365 
- #6368 
- #6391 
- #6518 
- #6631
- #6676
- #6719 
- #6723
- #6728 
- #6860
- #6886
- #7072 
- #7145 
- #7181
- #7322 
- #7643

**Comment by harshach** [comment]
![image](https://user-images.githubusercontent.com/38649/171482867-6e36b662-3dac-4ea8-97cd-82b9e14a26e7.png)
![image](https://user-images.githubusercontent.com/38649/171482921-38471905-c15d-4d92-b664-ded33af66290.png)

**Comment by harshach** [comment]
![image](https://user-images.githubusercontent.com/38649/171484215-aec5331f-ac0b-4a8b-b332-38882098d8af.png)
![image](https://user-images.githubusercontent.com/38649/171484252-db9012bc-1914-42f1-bf41-824d27f07327.png)


1. We need to build APIs for a role with multiple policies to retrieve the allowed operations by going through all the policies. That will help summarize what operations an admin is giving to a policy while creating
2. Another API for a logged In user, based on the roles they got assigned to what policies they have, and finally what operations they can perform. UI can make this request to see what tabs they need to show and if they should make an API call such as a sample data call should they make this one or not and also hide components such as edit description if they do not have edit description or suggest description option
