### ISSUE TITLE
Document Updation - Ingestion

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#420]
Updating the Ingestion documentation with changes
- New Connectors
- Command to install the python package for the connectors
- Openmetadata-ingestion Pypi package
- Ingestion Docker

**Comment by harshach** [comment]
@ayush-shah lets remove this line from 
```python -m spacy download en_core_web_sm```
we don't need it anymore

**Comment by harshach** [comment]
redshift page is empty https://docs.open-metadata.org/install/metadata-ingestion/connectors/database-services/redshift
