### ISSUE TITLE
Feedback on 0.10 release UI

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4241]
- [x] In activity feed in the following, the line can be made thinner and subtler
<img width="855" alt="image" src="https://user-images.githubusercontent.com/1417689/164046306-b645198b-e075-4384-8c45-6cd1c0f49680.png">

- [x] In explore page, we can change the name to hierarchical name instead of providing service name, database name, schema name, etc. Similar to how we do in dataset details page. 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/1417689/164046602-f5d712c6-445e-4e1e-b3d5-1505fb6a4bb7.png"> 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/1417689/164046653-45ae799c-4e82-486a-9d0f-84f3c7afbce0.png">

- [x] If there are not enough searches, let's not show not empty line with table icon. If no data not found, we just say no recent searches. 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/1417689/164047296-49e6e0c0-2486-4ca5-b56f-49fe4e355438.png">

- [x] In all DELETE actions (not just team), we should say - "Are you sure you want to delete "XYZ". This action can't be undone once the deletion is complete. Please enter DELETE in the text box below". Only enabling the delete button after the user enters the text.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/1417689/164048068-92720650-eb36-4cc3-a437-0dfe3639c81f.png">

Review still in progress.

**Comment by vivekratnavel** [comment]
- [ ] With initial sample data ingestion, there is a single dot displayed near the number of rows as shown. This dot lacks context and looks hanging in the middle of the page unless the user hovers over it. 

<img width="1002" alt="Screen Shot 2022-04-19 at 3 50 14 PM" src="https://user-images.githubusercontent.com/1051198/164114109-e0270d50-6f2e-4855-ba57-5f17a3db2f7f.png">

https://user-images.githubusercontent.com/1051198/164114122-8cae3d55-be0c-4e6e-83f7-33f2489b0aab.mov

cc @devyani-kaushik

**Comment by harshach** [comment]
cc @vivekratnavel @devyani-kaushik

**Comment by devyani-kaushik** [comment]
That dot is basically a graphical representation for one day's data, so our solution here is to hide the graph in this scenario

**Comment by devyani-kaushik** [comment]
- [ ] Need to update these Icons
![Dashboard](https://user-images.githubusercontent.com/103238069/164167933-d3ab9fb6-f19d-48f9-b20b-d493e81857fe.svg)
![Ingestion](https://user-images.githubusercontent.com/103238069/164167938-d10e864e-cd9f-4f40-900a-423773b65b97.svg)
![Pipeline](https://user-images.githubusercontent.com/103238069/164167941-d807dafa-8a4e-4220-937d-1e4fc49066af.svg)
![Team](https://user-images.githubusercontent.com/103238069/164167942-5158e34b-54c0-4a46-b72e-d40bd86dc92d.svg)

- [ ] Can we move the last word to second line completely instead of breaking the word ?
<img width="318" alt="Screenshot 2022-04-20 at 12 12 21 PM" src="https://user-images.githubusercontent.com/103238069/164168169-c2549294-f65a-4947-86b5-355144134d3b.png">

**Comment by vivekratnavel** [comment]
- [ ] After the loading icon, the default graphic is shown for a second before populating users and teams

https://user-images.githubusercontent.com/1051198/164350606-2e6fb6fb-c21e-44d4-b0ae-8f0f5d6fa12c.mov

- [ ] Admin user does not see "Join Team" button
- [ ] "Admin" role is not displayed anywhere when an admin logs in
- [ ] Clicking on the user card should redirect to the user page
- [ ] Should we have a page for bot users as well (ex: there is no page for ingestion-bot)

**Comment by Sachin-chaurasiya** [comment]
- [ ] Remove tooltip from entity feed card header
<img width="501" alt="image" src="https://user-images.githubusercontent.com/59080942/164380966-ba068df6-1e72-4df0-90fb-d63fc3bb2344.png">

**Comment by vivekratnavel** [comment]
- [ ] When no teams are available, the admin should have an option to create new team. Also, there should be a greyed out text "No Teams" under Teams
<img width="1422" alt="Screen Shot 2022-04-21 at 12 09 51 PM" src="https://user-images.githubusercontent.com/1051198/164536297-76f56b06-eac3-48f9-a6fb-faf962ff666a.png">

**Comment by harshach** [comment]
- [ ] Description not shown as required but the backend api throws an error as required
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/164539185-15b7f5a4-344d-4df9-a0a1-46576cf56c51.png">
the red dot is not there for description as it is for name

**Comment by devyani-kaushik** [comment]
<img width="556" alt="Screenshot 2022-04-21 at 1 23 50 PM" src="https://user-images.githubusercontent.com/103238069/164716402-5575b1c9-d16d-478a-967f-69536c2ff659.png">

- [ ]  Need to fix alignment of the service type grid. it's width should match the width of the drop down 
like in the image below
<img width="758" alt="Screenshot 2022-04-22 at 6 14 02 PM" src="https://user-images.githubusercontent.com/103238069/164716887-fd22886c-b871-4517-8618-c7565a9e0c20.png">

**Comment by darth-coder00** [comment]
- [ ] Need to handle loader for ingestion tab on service details page

https://user-images.githubusercontent.com/86726556/164735816-92b60290-4d21-4854-ab8e-842f8bf0ca7e.mov

**Comment by sureshms** [comment]
- [ ] User page follows an entirely different layout. We should reduce the conversation/activity feed width to the same width as the landing page with a three-column layout. Instead of Owned and following data being a separate tab, it could be shown similar to the landing page as well in the right-most column. @harshach 
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/1417689/164985092-d93f30cc-850d-426a-8630-dc968507aa83.png">

- [ ] Add real use profile picture on the user page in the left-most column.

**Comment by harshach** [comment]
- [ ] User profile link is not consistent. It looks like Admin roles doesn't have a profile link? 
<img width="493" alt="image" src="https://user-images.githubusercontent.com/38649/164985989-c487aeb7-43b6-41dd-8135-6077ad2f8d3d.png">
<img width="433" alt="image" src="https://user-images.githubusercontent.com/38649/164985995-972a4ad9-0b4e-4034-a231-d2c37072957a.png">

- [ ] Remove the Add Reviewer tab for this release. As its out of alignment. We will add Reviewer to be similar in UI/UX as adding a Owner 
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/38649/164986053-27ae83c7-e08a-44c7-b4a4-6b3bfa3019cf.png">
- [ ] can we add profile picture in user profile page and as well as sign in panel in header navigation cc @vivekratnavel 
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/38649/164986109-3a03676f-8b6c-470c-b3f6-535fdf28f44d.png">

**Comment by harshach** [comment]
- [ ] when the user selects a term on the left side panel and clicks Add Term to add a child term underneath it. After creation we select the newly added term 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/164988887-dc30b845-b952-4719-a67e-a22048937413.png">
The issue with that is user intends to select customers and keep adding new terms underneath it. But as soon as they add one child term its selected and if they click add term again with the intention of adding one under customers it will add underneath the newly created term.

**Comment by harshach** [comment]
- [ ] "write your description" should be grayed out . Currently it looks like there is already text and I can create a term without adding anything
<img width="900" alt="image" src="https://user-images.githubusercontent.com/38649/164989074-a431cb31-b484-4daa-a138-263456f61c6a.png">

**Comment by harshach** [comment]
- [ ] Adding a Glossary Term is not showing up in Activity Feed
