### ISSUE TITLE
Refactor Databricks and Redshift JSON Schema

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4247]
- Databricks add http_path
- Redshift add SSL options
- Snowflake private key
+ prepare engine

**Comment by pmbrull** [comment]
cc @open-metadata/ingestion

**Comment by ayush-shah** [comment]
Adding private key as a field for snowflake as well

**Comment by pmbrull** [comment]
@open-metadata/ingestion any takers on this? Would be good to have it cleaned in the next couple of days
