### ISSUE TITLE
Ingestion button redirects to airflow

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4251]
Prepare a button with a link towards Airflow tree view of an ingestion DAG:

```
http://localhost:8080/tree?dag_id=sample_data&root=
```
The DAG is named after the IngestionPipeline `name`, so we should just prepare a URL towards the airflow host + dag_id=name

**Comment by pmbrull** [comment]
cc @open-metadata/ui

**Comment by darth-coder00** [comment]
@pmbrull do we have an api to get `Airflow Host`? If not, UI will need one to get configured airflow host.
