### ISSUE TITLE
UI : Activity Feed Editor and Entity Description Editor Feedback

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#4306]
This ticket will track all the feedback for the Activity feed editor and Entity Description Editor.

1. Activity Feed Editor
<img width="858" alt="image" src="https://user-images.githubusercontent.com/59080942/164378531-bcb9a04c-4f38-4122-bb00-a1f3f657c9bd.png">

2. Entity Description Editor
<img width="970" alt="image" src="https://user-images.githubusercontent.com/59080942/164378712-f858f93d-2fda-434b-973e-7b0262bd46d8.png">

@open-metadata/ui @harshach @sureshms

**Comment by Sachin-chaurasiya** [comment]
- [ ] markdown editor toolbox icons are bigger compare to write and preview. Doesn't look clean and consistent
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/38649/164292406-54128d92-195e-41c1-843b-decf779f7e5e.png">

**Comment by darth-coder00** [comment]
Closing this for 0.10
