### ISSUE TITLE
Show Manage Tab only if User has access to perform any action underneath 

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#4318]
Right now we show Manage tab for all the users even if they do not have access to perform any actions under that tab

To avoid confusion, instead of blocking user, we should not show Manage tab if user does not have any permission to perform the actions there

**Comment by darth-coder00** [comment]
CC: @harshach @vivekratnavel @devyani-kaushik

**Comment by Sachin-chaurasiya** [comment]
Closing this as we have removed the manage tab.
