### ISSUE TITLE
IngestionPipeline update deployed for airflowDeploymentUrl

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4333]
Update the JSON Schema of IngestionPipeline, changing from `deployed` to `airflowDeploymentUrl` directly. This will build the link where the DAG lives.

cc @ShaileshParmar11 I'll ping when this is done to align UI changes. Thanks!

**Comment by harshach** [comment]
@pmbrull anything needs to be done here?

**Comment by pmbrull** [comment]
I don't think this is relevant anymore
