### ISSUE TITLE
Service and service types not available for entity detail APIs

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#434]
Service and Service-type is not available for api/v1/tables api

Service-type is not available in api/v1/topics and api/v1/dashboards apis

P.S. Here Service-type means `BigQuery`, `Kafka`, `Looker`, etc.

**Comment by sureshms** [comment]
@darth-coder00 table points back to database. database points back to service. All of this information is available in the UI when we show breadcrumbs in the table details page.

This is similar for topics and dashboards.

What use case are you looking at these for? Can you describe the use case?

**Comment by sureshms** [comment]
This has already been fixed
