### ISSUE TITLE
UI: Manage tab UX improvements in Entity Pages

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4353]
This ticket is to track the UX improvements to the "Manage" tab in the entity pages

**Comment by darth-coder00** [comment]
Mocks:

Entity - 
![Delete Entity_1a](https://user-images.githubusercontent.com/86726556/164626869-fafcf324-5e0f-4896-a52d-c99e0e0e1083.png)
![Delete Entity_1b](https://user-images.githubusercontent.com/86726556/164626885-34ead846-92a4-4245-ae5d-b2dad0653263.png)
![Delete Entity_1c](https://user-images.githubusercontent.com/86726556/164626890-c4edbb23-2476-4dac-b46f-8754481a8563.png)

Teams -
![Admin team view_1](https://user-images.githubusercontent.com/86726556/164626969-72e172fe-7271-4c45-ab08-1a5be2bda45b.png)

**Comment by darth-coder00** [comment]
## Tasks

- [ ] Update Soft/Hard Delete design
- [ ] Update Owners design
- [ ] Update Tiers design
