### ISSUE TITLE
Test Connection button fails the first time

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4359]
If we fill the form quickly and click on Test Connection, the first time it will fail as we send an empty payload.

When clicking Test Connection, we should make sure we are dumping all the values before sending the request

**Comment by pmbrull** [comment]
cc @vivekratnavel IDK if you encountered this on your end or not. I'll let you folks decide if this can/should be part of 0.10.1

**Comment by vivekratnavel** [comment]
@darth-coder00 Can you try to reproduce this and close if not reproducible?

@pmbrull Can you also verify if you are able to reproduce in the latest main?

**Comment by pmbrull** [comment]
hi @vivekratnavel @darth-coder00 , still happening. I tested a (failing) connection and got the following:

![image](https://user-images.githubusercontent.com/35870520/165680860-2a48db3c-33b3-4b16-b2d7-469fe424a908.png)

the error on the top is about a malformation of the JSON that cannot be parsed to JSON Schema class, while the one in the bottom, the parsing was OK and the connection just fails.

So it looks like the first error is because we are not passing all the info

**Comment by vivekratnavel** [comment]
@pmbrull Thank you! 

@darth-coder00 Can you try to reproduce this and fix it?
