### ISSUE TITLE
Define Histogram SQA compilation

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4368]
Different dialects have different needs when setting up the histogram queries. For example:

- Athena: if we don't specify a `select_from` in `hist`, we get `(pyathena.error.OperationalError) SYNTAX_ERROR: line 1:114: Column 'ranges.bin_floor' cannot be resolved`.
- MSSQL: If we add the `select_from` `sqlalchemy.exc.OperationalError: (pytds.tds_base.OperationalError) Each GROUP BY expression must contain at least one column that is not an outer reference.`.

Therefore, there are a couple of options here:
- Either we find a generic approach to build a single query to rule them all,
- We try to define the Histogram as a compiled SQA class where we can play differently in specific dialects. We are already doing this with Functions, but we might need fully-fledged queries as well

**Comment by harshach** [comment]
@TeddyCr @pmbrull marking it as P0 for 0.13. If its already one lets close it.

**Comment by pmbrull** [comment]
We need to do this on ingestion + UI side

**Comment by harshach** [comment]
@pmbrull @TeddyCr keeping it for 0.13.1 , move it 1.0 if we can't get it done
