### ISSUE TITLE
Docs: Google SSO under specific domain

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4369]
Based on https://openmetadata.slack.com/archives/C02B6955S4S/p1650628447627769

**Comment by akash-jain-10** [comment]
Closing this as we have already incorporated docs update under [Google SSO](https://docs.open-metadata.org/deploy/secure-openmetadata/google-sso/create-server-credentials#step-3-how-to-configure-oauth-consent).
