### ISSUE TITLE
Deleting rule for selected roles also deletes rule for roles having same policy 

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#4378]
**Affected module**
Backend

**Describe the bug**
Deleting rule for selected roles also deletes rules for roles having the same policy 

**To Reproduce**
- Navigate to the roles page
- Add new role with "Data Consumer Policy"
- Delete a rule from the newly created Role
- Deleted rule also gets deleted from Roles having policy "Data Consumer Policy"

https://user-images.githubusercontent.com/67048554/164761399-99164938-3a1b-45c3-a870-571ff1c8a04c.mov

**Expected behavior**
Rules should not be deleted

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment]
Closing this as we changed the structure of the roles and policies...
