### ISSUE TITLE
Encryption error when deployed in Kubernetese with multiple replicas

### ISSUE THREAD

**Issue by mosiac1** [open-metadata/OpenMetadata#4379]
**Affected module**
All

**Describe the bug**
When deploying Openmetadata in an environment like Kubernetese (where there are multiple replicas and the instance that will handle a particular request is chosen at random) encryption provided by [CypherText](https://github.com/open-metadata/OpenMetadata/blob/6057a37015f54a3cc42d60d045995cfda5657a49/common/src/main/java/org/openmetadata/common/utils/CipherText.java#L36) is not synced across the multiple instances. This causes 500 responses to queries that should normally go through. 

A VERY common case is pagination - a client may hit multiple different pods when getting large data. The `before` or `after` pointers are encrypted using each pod's openmetadata's private key, so they cannot be shared. [This causes a 500.](https://gist.github.com/mosiac1/353849672b7858535e7b0791475f529e)

**To Reproduce**

I observed this issue in production, but here is a quick description of the environment.

1. Get a Kube cluster (e.g: minikube)
2. Create a deployment with multiple replicas of Openmetadata (assuming database and Elasticsearch are already running)
3. Ingest tables
4. On the UI scroll through the tables from `service/databaseServices`
4. OR run ingestion into Elasticsearch (this will get all the tables programmatically)

**Expected behavior**
Replicas of Openmetadata should behave the same - they should be stateless.

**Version:**
 - OS: linux - rhel
 - OpenMetadata version: 0.9.0
 
**Additional context**
While I don't really see the point of encrypting `before` and `after`, this can be fixed by allowing the user to provide the private key as a config.

❗  What I think is more important is to keep in mind that MANY users will want to deploy Openmetadata in Kubernetese or other managed environments and they will assume it is a stateless application. Bugs caused by minor differences between replicas can be very hard to track. ❗

**Comment by harshach** [comment]
@mosiac1 which version are you running. We fixed it in main

**Comment by mosiac1** [comment]
I'm running 0.9.0. 
I checked the main branch for the class - so it's still there but it's not used. Issue resolved then
