### ISSUE TITLE
UI: Firefox does not load user profile picture 

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4385]
**Affected module**
UI

**Describe the bug**
In firefox, only the alt text is displayed in place of profile picture
 
<img width="264" alt="Screen Shot 2022-04-22 at 6 12 02 PM" src="https://user-images.githubusercontent.com/1051198/164847011-1e2938bf-7a0f-4ebe-8b35-a67410cadfd7.png">

**To Reproduce**

Login to OM in Firefox with any SSO

**Comment by Sachin-chaurasiya** [comment]
Closing this as it's fixed.
![image](https://user-images.githubusercontent.com/59080942/177262371-41ddc466-ea13-41b8-812f-d09b6d93395a.png)
