### ISSUE TITLE
User Profile Roles are missing Admin option in dropdown

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#4414]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?- UI

**Describe the bug**
User Profile Roles are missing Admin option in dropdown

**To Reproduce**

<img width="1792" alt="Screenshot 2022-04-23 at 10 37 25 PM" src="https://user-images.githubusercontent.com/86726556/164916343-0bd0f58d-aac4-4ae1-8be2-9510bbdd8321.png">

**Expected behavior**
Roles dropdown should have the option to make user an Admin

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Admin users can see `Admin` in the assigned role

**Comment by harshach** [comment]
@Sachin-chaurasiya We should show all the available roles not just admin
