### ISSUE TITLE
Assigning Users or Teams as owners or reviewers should be same component and same experience on all pages

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4444]
**Affected module**
UI
**Describe the bug**
Currently we are using multiple ways of assigning a owner or reviewer . We should use a single
module to add a user/team for owner , reviewer or in future in any other place.
We should be using the ES apis to achieve the experience of adding users or teams or list users or teams.
cc @vivekratnavel 
As part of this ticket remove any calls to users or teams via apis to bulkload that list on the UI side

**Comment by Sachin-chaurasiya** [comment]
Completed!
