### ISSUE TITLE
BigQuery fails in TestConnection

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4457]
ValueError('Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.').

Review how we are sending the privateKey data

**Comment by ayush-shah** [comment]
Hey Pere - this might be related to this https://github.com/open-metadata/OpenMetadata/issues/4280 ticket

**Comment by pmbrull** [comment]
yeah, thanks for sharing. We must be formatting something wrong. Looking into it!
