### ISSUE TITLE
DBT configs search from prefix

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4466]
Based on the discussion on https://github.com/open-metadata/OpenMetadata/pull/4462#pullrequestreview-951528821
Do not search all the buckets (this will not work with some more constrained security requirements).
We should allow a prefix to be passed there too and search from that key.

**Comment by pmbrull** [comment]
cc @OnkarVO7

**Comment by pmbrull** [comment]
let's see if we can fix it for 0.10.1

**Comment by OnkarVO7** [comment]
Yes I'll take a look

**Comment by pmbrull** [comment]
Thanks for the update @OnkarVO7. As part of this, we will also add the bucket name to not have any permission issues when listing all buckets.
