### ISSUE TITLE
Usage ingestion from UI update description

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4468]
![image](https://user-images.githubusercontent.com/35870520/165059989-022cf4fa-e14a-47d0-b3d3-dfbf2bee4e55.png)

We are showing the same description as for the metadata ingestion. Check with @ayush-shah what should we add there

**Comment by pmbrull** [comment]
cc @open-metadata/ui

**Comment by darth-coder00** [comment]
Resolved in #4501
