### ISSUE TITLE
Update usage workflow source

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4469]
The IngestionPipeline payload sent for a usage pipeline should have the Source Type as `usage`, not just the source.

**Comment by pmbrull** [comment]
@harshach depending on the PipelineType, the source.type should be `service` or `service-usage` accordingly.

We need to sync this change to also remove a patch done in the REST apis.

**Comment by harshach** [comment]
@pmbrull is this still an issue
