### ISSUE TITLE
Ingestion: Clicking "Run" should update the status as pending or queued so that user knows something is in progress

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4487]
**Feature**
Clicking "run" doesn't give any visual update to the user and it doesn't show the status of the newly scheduled run
cc @pmbrull 

**Describe the task**

**Comment by pmbrull** [comment]
sounds good. We could try to get the pipelineStatus right away. I hope Airflow is fast enough updating the db. Otherwise we can add a pending 🤔

**Comment by vivekratnavel** [comment]
@ShaileshParmar11 Can you post a video of the micro-interaction we show while clicking the run button?

**Comment by ShaileshParmar11** [comment]
https://user-images.githubusercontent.com/71748675/165704367-8eb7fc41-645c-416d-8d08-03e532c4d776.mov

**Comment by harshach** [comment]
@ShaileshParmar11  @vivekratnavel this doesn't happen when we first deploy the pipeline we don't show anything in the recent run
