### ISSUE TITLE
Python FQN Builder

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4496]
The FQN uniquely identifies an Entity. We need a centric piece of logic to handle how we create it depending on the Entity Type. For example:
- A Table FQN is built as `service.db.schema.name`
- A Pipeline FQN is built as `service.name`

Using antlr we will also be able to parse FQN strings into their specific pieces. This will become an important stepping stone that will help us not rely entirely on FQN searches for user input data, but to parse the incoming FQN and be more flexible by querying Elasticsearch and use the Entity ID (e.g., https://github.com/open-metadata/OpenMetadata/issues/4648)

Task breakdown:
- https://github.com/open-metadata/OpenMetadata/issues/4688
- https://github.com/open-metadata/OpenMetadata/issues/4689

**Comment by ayush-shah** [comment]
Once this is merged, we can take up https://github.com/open-metadata/OpenMetadata/issues/4909
