### ISSUE TITLE
SampleData is filtered from service list

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4511]
UPDATE: We should filter out the SampleData service from the DatabaseService list on the UI

**Comment by pmbrull** [comment]
@harshach @vivekratnavel would it make sense to just remove the `SampleData` from the DB services list?

**Comment by pmbrull** [comment]
As discussed, we'll filter this out from frontend side.

**Comment by vivekratnavel** [comment]
@darth-coder00 Let's not remove or filter sample data, but hide the test connection button for Sample Data.
