### ISSUE TITLE
Auth docs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4526]
We should document the different providers that we support.

We already have part of the info but not everything from the JSON Schemas is being reflected.

We should show how to configure the environment when working from:
- Docker
- bare metal
- k8s

with all the providers

**Comment by akash-jain-10** [comment]
Closing this as we updated the docs on Secure OpenMetadata [here](https://docs.open-metadata.org/deploy/secure-openmetadata).
