### ISSUE TITLE
Tables with a slash (/) in their name aren't appearing 

### ISSUE THREAD

**Issue by mesmith027** [open-metadata/OpenMetadata#4542]
**Affected module**
It affects the UI.

**Describe the bug**
the data table(s) with a `/` in their name(s) do not seem to be there. The table data is actually there and if you replace the `/` in the URL query parameter with `%2f` the table will display as expected. 

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
When you load the new 0.10 version of OM and connect a glue database service (possibly any db service, the example we saw was with glue) you should see the tables in the left sidebar. 

<img width="710" alt="Screen Shot 2022-04-27 at 2 48 18 PM" src="https://user-images.githubusercontent.com/66020208/165599876-24e8b1a7-95ba-4e86-aadd-ca0dac064373.png">

**Version:**
 - OS: amazone ec2 linux instance 
 - Python version: 3.8
 - OpenMetadata version: 0.10
 - OpenMetadata Ingestion package version: ~unsure on this one 

**Additional context**
This comes from our debugging session with a community member in the Slack support channel, [link to the conversation here](https://openmetadata.slack.com/archives/C02B6955S4S/p1651073750535999)

**Comment by harshach** [comment]
@vivekratnavel easier fix here is to encode the entity names in the fqn part. once we did the url encode it worked.
Good idea from @ayush-shah
