### ISSUE TITLE
Redshift test connection fails if we do not pass database

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4545]
**Affected module**
Ingestion

**Describe the bug**
Redshift test connection fails if the user doesn't pass the database

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/38649/165635813-99474ef4-4ba1-467d-a151-9adf0d5363ff.png">

**To Reproduce**

**Expected behavior** 
database is optional in redshift and test connection should work

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
Not sure if this is a bug or user doesn't have privileges
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/38649/165640777-4533b708-1b7c-4bb0-8fae-6ff881a93a37.png">

**Comment by pmbrull** [comment]
The Database should be marked as requirement: https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-build-connection-url.html we might also need to rename it to schema following official AWS docs

**Comment by pmbrull** [comment]
@harshach the Glue one looks like a permissions issue, as we're doing `connection.client.list_workflows()`. cc @ulixius9

**Comment by pmbrull** [comment]
Let's divide it into two steps:
If the current code does not support multiple dbs, then let's add the database as required to be consistent
Then, we can work on providing support to have a single service with all the dbs
