### ISSUE TITLE
[Snowflake Connector] | Optimize Snowflake metadata extraction

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4546]
**Is your feature request related to a problem? Please describe.**
* Fetch all snowflake metadata from `information_schema` tables instead of running `SHOW /* sqlalchemy:_get_table_comment */ TABLES LIKE 'table' IN SCHEMA schema`  
* Fetch Snowflake row count from `information_schema` rather than run a `SELECT count(*) FROM table`

**Describe the solution you'd like**
Same as above

**Describe alternatives you've considered**
Current ingestion which runs a query for each table for metadata and `count(*)` for each table

**Additional context**

**Comment by harshach** [comment]
@sidhreddy I think it makes sense if we can do a more performative way. The generic sqlalchemy approach is fetch_tables and fetch_views except that rest of code can be reusable.
@ayush-shah we should override those methods and re-implement them in snowflake.py

**Comment by harshach** [comment]
@pmbrull ^

**Comment by pmbrull** [comment]
Hi @sidhreddy, that's a great suggestion. Currently, we are computing everything with SQA but we should be able to reuse parts of the information from the database stats directly. Opened https://github.com/open-metadata/OpenMetadata/issues/4565 to track this. Thanks!
