### ISSUE TITLE
[Snowflake] | Ability to set a query tag for snowflake connections

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4549]
**Is your feature request related to a problem? Please describe.**
Ability to set a query tag for snowflake connections

**Describe the solution you'd like**
Ability to set a query tag for snowflake connections. This would provide more information for us in terms of monitoring usage and also to aggregate access history to provide for data governance.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ayush-shah** [comment]
Partially fixed in #4653.
Remaining - Views and columns
