### ISSUE TITLE
UI: Add support to get JWT token for bot users

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4559]
**Feature**
Add a tab to bot user profile page for Admin users to click on a button to generate JWT tokens to be used for ingestion

**Comment by devyani-kaushik** [comment]
![Bot listing](https://user-images.githubusercontent.com/103238069/166496871-fa3cd8ce-2c59-4e16-ace6-cad23143877c.png)

![Bot Detail](https://user-images.githubusercontent.com/103238069/166496852-662c1985-244d-4969-b48b-681178ddd5d9.png)
