### ISSUE TITLE
UI: Consistent UX everywhere for choosing Users & Teams

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4561]
The UX should be consistent across all the places we let the user choose Users & Teams including Glossary Reviewers, Entity pages, etc.

**Comment by harshach** [comment]
@vivekratnavel these two are related right https://github.com/open-metadata/OpenMetadata/issues/4537

**Comment by vivekratnavel** [comment]
Yes, they are both related
