### ISSUE TITLE
Pull metrics from table metric from system tables

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4565]
**Context**
Currently, the profiler runs directly metrics on top of the tables. However, there are system tables in each database which might already contain pieces of information we can reuse instead of compute it.

For example, in snowflake, use the row count informed in information_schema.

**Comment by harshach** [comment]
@pmbrull 
@TeddyCr lets plan this for 1.0

**Comment by TeddyCr** [comment]
When sampling is enable, we'll ignore it for table metrics (unless prevent full scan is on). Strategy we'll use:
1. pull table metrics from system table when available 
2. compute the metrics against the entire table
