### ISSUE TITLE
Trino data profiler is using a function Trino doesn't support - LEN

### ISSUE THREAD

**Issue by mosiac1** [open-metadata/OpenMetadata#4569]
**Affected module**
Ingestion

**Describe the bug**
When ingestion from trino with the data profiler enabled no data about the columns is ingested because of errors like these:

`Error trying to compute column profile for datalabel - TrinoUserError(type=USER_ERROR, name=FUNCTION_NOT_FOUND, message="line 2:7: Function 'len' not registered", query_id=20220428_103239_84305_3g8jx)`

This is the request to Trino:

```sql
SELECT
  avg(LEN(datalabel)) mean
, count(datalabel) "valuesCount"
, count(DISTINCT datalabel) "distinctCount"
, null anon_1
, min(LEN(datalabel)) "minLength"
, null anon__1
, max(LEN(datalabel)) "maxLength"
, sum((CASE WHEN (datalabel IS NULL) THEN ? ELSE ? END)) "nullCount"
, null anon__2
, null anon__3
FROM
  innotap_iceberg.innotap_price
LIMIT ?
```

**To Reproduce**

Run Trino ingestion with the data profiler enabled

**Version:**
 - Python version: 3.10
 - OpenMetadata version: 0.10.0
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[trino]==0.10.0.1`

**Comment by pmbrull** [comment]
Thanks for reporting. Will handle it now

**Comment by pmbrull** [comment]
will be part of 0.10.1 release next week

**Comment by mosiac1** [comment]
Thank you!
