### ISSUE TITLE
Ability to track User adoption on OM

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4578]
**Is your feature request related to a problem? Please describe.**
It would be great to have visibility in how users are adopting OM.

**Describe the solution you'd like**
Ability to track User adoption on OM:
* User Invites Sent
* User(s) who have logged in
* DAU/MAU
* Engagement on entities

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by harshach** [comment]
@sidhreddy this in our roadmap. We will try to get to it in 0.11 if not next release.

**Comment by harshach** [comment]
@TeddyCr lets see if we need to cover any other metrics as part of this ticket if not lets close it out.
Not sure if we can derive MAUs (aggregated number) with existing metrics
