### ISSUE TITLE
RBAC for Data Quality

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4580]
**Is your feature request related to a problem? Please describe.**
Currently Data Quality isn't behind RBAC

**Describe the solution you'd like**
Ability to allow Data Quality for entities based on RBAC

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sureshms** [comment]
As part of work in #4199, granular access control has been added to every entity. This includes ability to control access to data profiler, usage, queries, tests, etc. as shown below:
```
  {
    "name" : "table",
    "operations" : [
      "Create",
      "Delete",
      "ViewAll",
      "ViewUsage",
      "ViewTests",
      "ViewQueries",
      "ViewDataProfile",
      "ViewSampleData",
      "EditAll",
      "EditDescription",
      "EditDisplayName",
      "EditTags",
      "EditOwner",
      "EditTier",
      "EditCustomFields",
      "EditTests",
      "EditQueries",
      "EditDataProfile",
      "EditSampleData",
      "EditLineage"
    ]
  }
```

This addresses this feature. @sidhreddy comment if this does not address the needs completely.
