### ISSUE TITLE
[Looker] | Ingestion UI | Remove Unnecessary config on service connection setup flow

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4581]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI Ingestion Framework

**Describe the bug**
Current Service connection setup for Looker asks for `Include Views`, `Enable Data Profiler` & `Ingest Sample Data` which might not make sense for the service.

**To Reproduce**
Screenshots or steps to reproduce
* Setup a Looker Connection via UI
<img width="687" alt="Screen Shot 2022-04-28 at 10 55 30 PM" src="https://user-images.githubusercontent.com/49429859/165883398-a00d5186-0a1d-4197-8307-ce5bb570da18.png">

**Expected behavior**
Remove unnecessary connection config for Looker Service

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]
`openmetadata-ingestion==0.10.0`
`openmetadata-ingestion-core==0.10.0`

**Additional context**
NA

**Comment by harshach** [comment]
@darth-coder00 @shahsank3t looks like we are showing this form everywhere? it should only applied to databaseServices
