### ISSUE TITLE
UI: Move Database service connection form

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4583]
**Feature**
Move Database service connection form to a different page for better UX.

<img width="1045" alt="Screen Shot 2022-04-28 at 9 43 34 PM" src="https://user-images.githubusercontent.com/1051198/165886691-932b44cc-baa8-43e1-be80-48b7cd95126e.png">

**Comment by devyani-kaushik** [comment]
![connections tab](https://user-images.githubusercontent.com/103238069/166407280-b886f932-ee2b-432c-a11e-5b4ddc98106c.png)

**Comment by shahsank3t** [comment]
The plan is to have Connection details in view mode, as displayed in the above-attached screenshot with the `Edit Connection` button. We will navigate the user to a separate page to edit connection details by clicking it.
