### ISSUE TITLE
Check DBT model parsing

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4585]
**Affected module**
Ingestion

**Describe the bug**
DBT parsed modules do not appear in the UI after ingesting.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] 0.9
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
might be related to dots in the table names. Double-check that in `main` the models can be properly parsed.

**Comment by OnkarVO7** [comment]
Yes I'll check

**Comment by pmbrull** [comment]
Working on 0.10
