### ISSUE TITLE
Superset link update does not reflect in chart link

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4587]
**Affected module**
Ingestion, UI

**Describe the bug**
When changing the Connection Config with a new URL, the chart does not get updated.

Same happens with the Pipeline Entity

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
this is also happening with Airflow tasks

**Comment by pmbrull** [comment]
Hi @ayush-shah @harshach @vivekratnavel this issue happens at Task and Chart level because the `taskUrl` and `chartUrl` get informed when loading the metadata and are left static.

If for some reason the service URL was not properly ingested (e.g., we are using a wrong URL) and users change it via the UI, the chart and task URL are not automatically updated. I believe that if we give the option to update service URL via the UI, the changes should get reflected to the children metadata.

A possible solution here would be to update the connectors to not add the whole URL during the ingestion and just put the suffix. Then, in the UI we could build the links based on:
```
serviceURL/childrenURL
```
WDYT?

**Comment by pmbrull** [comment]
Will move this to 0.11 to properly align with UI team on these changes. Thanks!

**Comment by vivekratnavel** [comment]
I think this needs more discussion and effort on the UI side. I would prefer to move this to 0.11. Thanks, @pmbrull!

**Comment by harshach** [comment]
@pmbrull @vivekratnavel moving this to 0.12

**Comment by pmbrull** [comment]
this should be done already @harshach was part of the epic https://github.com/open-metadata/OpenMetadata/issues/4695

we can close it
