### ISSUE TITLE
Allow for selecting multiple databases per service

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#4594]
Maybe related to #3118 - this box allows either one database name or it scans them all:
![image](https://user-images.githubusercontent.com/7569808/165964274-790a4e83-2274-4855-bd9e-d2b592d1fe04.png)

I want to ingest _two_ databases from the same server.  It would be nice to have them on a single service.  Ideally I could list them here, separated by a comma.

**Comment by harshach** [comment]
@ayush-shah @ulixius9 we should database include, exclude filters and users who want to scan more than one database can leave this option empty and just add database -> include -> database1, database2, etc..

**Comment by sfirke** [comment]
@harshach what you describe would be a nice improvement!

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/4736
