### ISSUE TITLE
UI improvements in 0.10.1 release

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4600]
This epic captures improvements OpenMetadata UI and UX to functionality  functionality related to User profile. The User profile improvements are tracked in the epic #4599.

The task breakdown is as follows:
- #4558
- #4559 
- #4560 
- #4561 
- #4583 
- #4595
- #4556 
- #4555 
- #4542 
- #4455 
- #4359 
- #4155 
- #3793 
- #3508

**Comment by shahsank3t** [comment]
@harshach @sureshms We have agreed on moving Manual Lineage Editor related changes/improvements to 0.11.0 Release.
We'll track it here in case we have the bandwidth to cover in 0.10.1 but just a heads up.
