### ISSUE TITLE
Add support for Postgres as OpenMetadata store

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4601]
OpenMetadata currently only supports MySQL as the database service for metadata storage. Many organizations standardize on using Postgres as the database service of choice. Many users have requested adding support for Postgres.

Tasks and PRs related to this epic:
- #3952 
- #4541 
- #4551 
- #4573 
- #4508

**Comment by suparna-bhattacharya** [comment]
Cool. Does this also include lineage/usage connector for postgres?

**Comment by harshach** [comment]
Thanks @ulixius9 for putting the docs together https://docs.open-metadata.org/data-lineage/usage-workflow-through-query-logs @suparna-bhattacharya please refer to that to run the Postgres or any other database usage/lineage parsing
