### ISSUE TITLE
UI: Users and Teams page shows placeholder for "No Teams" when there are multiple teams available

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4632]
**Affected module**
UI

**Describe the bug**
When landing on the Users & Teams page, the following placeholder is shown

<img width="1718" alt="Screen Shot 2022-05-02 at 10 10 44 AM" src="https://user-images.githubusercontent.com/1051198/166293284-9243c784-5136-476e-8d4f-9f9ef1260b4d.png">

**To Reproduce**
Click on "Teams & Users" link from Settings on the Top Nav bar

**Expected behavior**
The first team is selected

**Comment by shahsank3t** [comment]
This has been recently fixed, closing it.
