### ISSUE TITLE
Airflow lineage with ES instead of FQN

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4648]
**Is your feature request related to a problem? Please describe.**
Requiring to add the FQN can be a bit hard when informing inlets and outlets

**Describe the solution you'd like**
Use ES as a middle-step to:
1. Use antlr to parse the inlet/outlet and fetch the possible entity ID
2. Use the entity ID to build the lineage

**Describe alternatives you've considered**
Stick to FQN to have no room for operational errors or inconsistencies

**Additional context**

**Related issues**
- ...

**Comment by harshach** [comment]
@pmbrull anything remaining here or can we close it

**Comment by pmbrull** [comment]
We still need to pick it up. Should be a quick improvements in 0.13. Thanks

**Comment by harshach** [comment]
@nahuelverdugo pick up for 0.13.1 or 1.0?

**Comment by nahuelverdugo** [comment]
I will take this for `0.13.1`.
