### ISSUE TITLE
Data Profiler Dashboard Mock

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4656]
**Feature**
- https://github.com/open-metadata/OpenMetadata/issues/4652

**Describe the task**
Prepare the mock for the Data Profiler dashboard. We should be able to see the evolution of metrics, metrics of higher dimensions such as the Histogram, and also the evolution of the quality tests results 

Some previous work:

![image](https://user-images.githubusercontent.com/35870520/166443117-e6e13805-0129-467d-8883-4cbf57221975.png)

**Comment by TeddyCr** [comment]
Hey @pmbrull @harshach below are the Mocks regarding the drill down functionality for the profiler and data quality

### Profiler
The idea would be to have an accordion view in the profiler column. Clicking on the profiler column would expand that view and reveal more details about that column. From there the user should be able:
1. select the metric they want to view
2. select the time range they want to look at

Hovering over a data point in the graph should give the value and the date

![image](https://user-images.githubusercontent.com/13626425/177590757-08a19dfb-42f0-47d0-9ff8-6b7b9d31b5af.png)

One specificity in the profile metric drill down would be the distribution. The layout would be slightly different and I feel like having a date range filter does not make sense -- instead the latest distribution should be shown.

![image](https://user-images.githubusercontent.com/13626425/177592413-4732398c-0bd8-4ecf-b67b-85025a357207.png)

### Data Quality
Regarding data quality, we are suggesting a similar approach, with an accordion. it has 3 basic elements:
- the date range filter
- summary of tests run status
- graph of test runs -- not all graphs will necessarily have a `min` `max` box, but if a quality config has it, it should display the acceptable range in the graph for quick insight. The color are used to display the state of a test run.

![image](https://user-images.githubusercontent.com/13626425/177592835-1ba27d2e-93fd-4906-89a8-a8e8eb668f97.png)

Let me know what you think and what the next steps are here. 🙂

**Comment by TeddyCr** [comment]
@devyani-kaushik here is the library used 👉 https://recharts.org/en-US/

**Comment by TeddyCr** [comment]
@devyani-kaushik thank you very much for the mocks. Are you able to give me access to the mocks in Figma. 🙂

**Comment by TeddyCr** [comment]
@devyani-kaushik could we close this issue?
