### ISSUE TITLE
Remove references to openmetadata-security.yaml ?

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#4662]
Looking into setting up Azure SSO I was reading this https://docs.open-metadata.org/deploy/secure-openmetadata/azure-sso/configure-openmetadata/configure-openmetadata-server and it says:

> Update conf/openmetadata-security.yaml

But I couldn't find that file in the docker container.  Based on this [GitHub comment](https://github.com/open-metadata/OpenMetadata/issues/2773#issuecomment-1041063312) I'm thinking maybe that file doesn't exist anymore and it should be just openmetadata.yaml?  Which I do see.

**Comment by akash-jain-10** [comment]
Thanks @sfirke . We have updated all the docs to reflect the changes for `openmetadata.yaml` instead of `openmetadata-security.yaml`.
