### ISSUE TITLE
Documentation: how to deploy with docker and specify config variables

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#4663]
**Is your feature request related to a problem? Please describe.**
As a beginner with Docker, I could use more guidance on configuration and deployment.

**Describe the solution you'd like**
In general, the more support + instructions possible for deploying with Docker Compose, the better.  For instance, I have it up and running on port 8585 and would like my users to access it on the default https port - I was told in Slack to check out Azure Load Balancer (thanks!) but would love other tips like that.

My specific request prompting this issue is, could we get instructions + a workflow for deploying with docker compose and a config file?  That way I could specify things like my Azure SSO config in a config file that would be portable and editable.  Anything that right now says I should edit the .yaml file, which I have to do in the docker container (?), I'd think would go in a config file?

I believe Apache Superset has this process in place of deploying with compose + a config file.

**Describe alternatives you've considered**
I tried running on bare metal which makes all the files accessible - but then I used docker and it was much easier!

**Additional context**
Posting here at @sureshms suggestion after a conversation in Slack, feel free to edit + reshape this issue to suit the project's needs.

**Comment by harshach** [comment]
handled in latest docs
