### ISSUE TITLE
Feature request: email notifications

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#4674]
**Is your feature request related to a problem? Please describe.**
My company would like to receive notifications when a data quality test fails (or for other events).  Right now when a test fails, I don't see it unless I browse to that table and check.

**Describe the solution you'd like**
To be able to configure a mail service and then have alerts send upon an event.  E.g., a data quality test fails, it emails me immediately.

**Describe alternatives you've considered**
I started to read about webhooks but don't think I can get that working to send emails, no one at my company has experience with webhooks.  Slack integration doesn't work for us  - we use Microsoft Teams, but email would be better than chat anyway.

**Comment by harshach** [comment]
@sfirke what email service do you use? does configuring a SMTP gateway a possibility ?

**Comment by sfirke** [comment]
We use Microsoft Outlook.  I'm not an expert (would be getting help from our infrastructure team) but I'd think Outlook should support anything SMTP-related.

**Comment by sfirke** [comment]
Update: I am successfully using an unauthenticated SMTP server to send alerts from Apache Superset.  If OpenMetadata could send alerts similarly, that would be great.  Often the people who will be responsible for fixing a case of bad data and who should thus receive the alert will not be logging in to OpenMetadata regularly, so having an ability to send them alerts via email will be very useful.
