### ISSUE TITLE
Add all operations through the UI and APIs as metadata operations

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4677]
**Feature**
We support a few UI operations such as editing descriptions, adding tags, etc..
As part of this task, we are going to instrument all the operations in JsonSchema such as adding a test, view data profiler, view schema, etc..
This will allow admins to create policies by grouping operations and associating this policy with a role.

**Comment by sureshms** [comment]
This has been addressed by work so far done in #4199
