### ISSUE TITLE
Ingestion Pipeline Logs from UI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4693]
**Feature**
- https://github.com/open-metadata/OpenMetadata/issues/4691

**Describe the task**
Prepare the methods to load the airflow logs directly in the UI. This might be a bit tricky because the log files will be in different containers.

You can pick up the endpoint as `/v1/services/ingestionPipelines/logs/{ingestion pipeline ID}/last`

**Comment by Sachin-chaurasiya** [comment]
Blocked by https://github.com/open-metadata/OpenMetadata/issues/6143
