### ISSUE TITLE
Custom Service Schema and APIs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4699]
**Feature**
- https://github.com/open-metadata/OpenMetadata/issues/4698

**Describe the task**
From the backend perspective, we need to define the custom service types and prepare the APIs.

One question here would be if we need a custom service type for each service type (Database, Dashboard, Pipeline), or if it makes more sense to abstract yet another layer. Here I am imagining users having maybe lineage information, roles, or any other metadata that does not directly conform to a Table or any product of the above services.

For those cases, having a separated category might make things more clear.

**Comment by harshach** [comment]
@pmbrull can we call this done?

**Comment by pmbrull** [comment]
oh that's correct. Closing!
