### ISSUE TITLE
UI Custom Service form and flow

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4700]
**Feature**
- https://github.com/open-metadata/OpenMetadata/issues/4698

**Describe the task**
The UI will need to support the handling of the custom services and connectors properties.

Let's wait until the resolution of https://github.com/open-metadata/OpenMetadata/issues/4699 to see how the new services need to be structured.

**Comment by harshach** [comment]
@nahuelverdugo can you verify if we need anything else to do to support custom service through the UI, if not lets close this

**Comment by nahuelverdugo** [comment]
@harshach this one is still open https://github.com/open-metadata/OpenMetadata/issues/7480
