### ISSUE TITLE
UI: Feedback from 0.10

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4709]
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/38649/166720702-0a43f28d-2333-4410-a52f-c58e13aa6f2d.png">
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/38649/166720874-16a86714-a407-4ded-bcdc-2a774df04246.png">

**Comment by shahsank3t** [comment]
All points have been fixed, closing this ticket.
