### ISSUE TITLE
0.10.0 - Snowflake Ingestion Issues

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4711]
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/38649/166721347-84fa9613-e6a0-4a42-b473-93881bcae07e.png">

**Comment by harshach** [comment]
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/38649/166721535-913ac89e-d609-4869-aff4-18c9c3ec9c16.png">

**Comment by harshach** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/166721638-e7a676a5-31c9-4aee-a9af-84ba74d9b598.png">
@Sachin-chaurasiya manual lineage bugs

**Comment by pmbrull** [comment]
@ayush-shah let's validate these issues during the snowflake testing
