### ISSUE TITLE
Snowflake Usage | Unintended behavior when queries don't explicitly specify `DATABASE` & `SCHEMA` on source tables

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4713]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework

**Describe the bug**
Currently it looks like the Query Parser only extracts source table information from the `QUERY_TEXT` , but there could be cases where `database` & `schema` might not be explicitly specified for a source tables on the `QUERY_TEXT` when there has been a `USE DB` and/or `USE SCHEMA` commands run in the session before the actual `QUERY` . For this case I see the below potential issues:

* Lineage tracked incorrectly when we have the same `TABLE_NAME` across `DATABASE` and/or `SCHEMA` .
* Lineage not tracked at all if the source table look on OM for Lineage requires full FQN from the `QUERY_TEXT`

**To Reproduce**
Run Snowflake Usage connector with Queries that don't explicitly specify DATABASE and/or SCHEMA but would have run `USE DB` and/or `USE SCHEMA`

Screenshots or steps to reproduce
NA

**Expected behavior**
To resolve this, I think we could use DATABASE_NAME & SCHEMA_NAME fields from QUERY_HISTORY table which would have context on what DATABASE and SCHEMA the QUERY_TEXT was intended for the above :point_up::skin-tone-2: scenario.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]
`openmetadata-ingestion==0.10.0.1`
`openmetadata-ingestion-core==0.10.0`

**Additional context**
NA

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/5190
