### ISSUE TITLE
Backend : Add support for bots search API

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#4714]
Today, we have a search API for teams and users that we use on the user&teams page to get results based on the user search query.
We will need a search API for bots users to add search functionality on the bot listing page.

**Comment by harshach** [comment]
@Sachin-chaurasiya do we need this . Given the no.of bots going to be in 10s if not 100s. Can't we just get all the bots and do the search through the UI?

**Comment by Sachin-chaurasiya** [comment]
@harshach , I will check the current UI implementation and update it here.

**Comment by harshach** [comment]
@Sachin-chaurasiya fyi, we are not going to assign any assets to bots, so having search for bots doesn't make sense to me unless there is any usecase where we need this

**Comment by Sachin-chaurasiya** [comment]
@harshach, On the UI side we will fetch the bots with limit=100 and filter them on the UI side.
