### ISSUE TITLE
Topics Follow button doesn't work

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#473]
it looks like UI is making a request to a api method that doesn't exists
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/38649/133024242-cdb77147-d543-49ab-8126-25d389ba2b65.png">

**Comment by Sachin-chaurasiya** [comment]
@harshach Can you provide Error Details from the preview tab?

I have tested all these APIs and it is working perfectly for me.

**Comment by Sachin-chaurasiya** [comment]
Closing this as we have tested out on safari browser as well and it is working fine.
