### ISSUE TITLE
Snowflake Usage | connecter fails to extract query logs with multiple DB support on 0.10

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4741]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework

**Describe the bug**
With multiple DB support for Snowflake in `0.10`, the usage connector is failing to extract `QUERY_HISTORY` due to the fact that the extract query doesn't specifying which `DATABASE` it needs to extract query logs from.

**To Reproduce**
Run Usage Connector against a Snowflake instance with multiple `DATABASES`.

**Expected behavior**
Run `SHOW DATABASE` & `USE DATABASE` and extract the query logs from each `DATABASE` at a time.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]
`openmetadata-ingestion==0.10.0.1.dev2`
`openmetadata-ingestion-core==0.10.0`

**Additional context**
NA

**Comment by harshach** [comment]
@sidhreddy isn't this the same as this https://github.com/open-metadata/OpenMetadata/issues/4713

**Comment by sidhreddy** [comment]
@harshach This is to address the issue that the Usage connector fails to extract any query logs at all logs due to the support for multiple DBs.

#4713 is meant to accurately link lineage from `QUERY_TEXT` when `DATABASE` & `SCHEMA` aren't specified on the query itself. Sorry - My wording might be misleading.

**Comment by harshach** [comment]
Thanks for the clarification @sidhreddy

**Comment by ayush-shah** [comment]
Fixed in #4653
