### ISSUE TITLE
UI: For scrolling the content in the middle column, the cursor needs to be in the middle column 

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4745]
**Affected module**
UI

**Describe the bug**
The user is left with no clue on how to scroll through the content in the middle column without any scrollbars. We should improve the UX here.

Examples: Add new service form,  Activity Feed in the homepage, etc.

**Comment by ShaileshParmar11** [comment]
I will be looking into this issue as I am working on a similar component!
