### ISSUE TITLE
Make setting owner and tier tag more intuitive by eliminating Manage tab

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4753]
**Is your feature request related to a problem? Please describe.**
`Manage` tab for setting owner and tier tag is not very intuitive. Users may not know setting these fields requires going to a separate tab. cc @harshach 

**Describe the solution you'd like**
We should make the summary line below the data asset editable and eliminate the `Manage` tag altogether.

**Comment by harshach** [comment]
@vivekratnavel @Sachin-chaurasiya are we going to handle this in this release. If not lets move it to 0.12

**Comment by Sachin-chaurasiya** [comment]
@harshach , It will require to touch almost all the pages where we have manage tab, so we should move this to 0.12
