### ISSUE TITLE
Get Embedded and Published Datasource information with the Tableau connector

### ISSUE THREAD

**Issue by djrmarques** [open-metadata/OpenMetadata#4762]
**Is your feature request related to a problem? Please describe.**
No datasources are shown when using the Tableau connector.

**Describe the solution you'd like**
I would like to see the following information on the UI when using the Tableau connector:

1. Datasource Lineage: Which dashboards, charts and other datasources are connected to a given datasource. Also what are the external services (Redshift, Athena, a file, etc..) that are connected to the Datasource. This information should show on the Lineage graph on the UI, assuming all the relevante metadata was ingested. For example, if I ingested a table on Redshift and there is a datasource on Tableau connected to this table, this connection should be apparent on  the UI.
2. Metadata related to the datasource such as which user owns the datasource, when it was created, etc..
3. Fields on datasources (particularly published datasources) should be searchable. This would allow analysts to reuse existing datasources. 

**Describe alternatives you've considered**
None so far

**Additional context**

**Comment by ulixius9** [comment]
Hey @djrmarques, an update regarding this

1. Datasource lineage in tableau connector has been fixed with PR #5315
2. The metadata extraction for datasource like owner, tags and description has been handles as part of PR #5341
3. Will test this out once and update in this thread 

cc: @harshach @pmbrull

**Comment by ulixius9** [comment]
Hey @djrmarques 

> Fields on datasources (particularly published datasources) should be searchable. This would allow analysts to reuse existing datasources.

what I understand from this is you want to search based on column names of table linked to the dashboard, if yes then this feature is already supported in OMD and we can close this issue. 

if no then can you please elaborate on the same.

**Comment by djrmarques** [comment]
Hello! Sorry for the late response. Yeah,  it seems that this issue can be closed. Thank you :)!
