### ISSUE TITLE
Revamp Ingestion Backend

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4765]
While the value provided in OpenMetadata comes from many different fronts (from foundational aspects just as the standard language to the UX navigating the tool), the typical user flow is:
1. Discover the tool
2. Install
3. Ingest

Without correctly bringing the metadata, we cannot provide the rest of the value layers. Therefore, we need to make as many efforts as necessary to make sure that the foundations behind the Ingestion Framework are as solid as possible. We have been focusing on bringing as many features and connectors as possible, but now it's time to double down on quality and stability.

In this epic, we are going to track all the improvements that can be done in core elements of the Ingestion Framework.

- https://github.com/open-metadata/OpenMetadata/issues/1673 - We are adding complexity because of this
- https://github.com/open-metadata/OpenMetadata/issues/2848 - Also a requirement for https://github.com/open-metadata/OpenMetadata/issues/4698. Reorganizing the core definitions and properly setting the package dependencies between `ingestion` and `ingestion-core` will help us evolve faster and improve release flows.
- https://github.com/open-metadata/OpenMetadata/issues/3394 - We've been delaying this for too long! Pylint is a great source of improvements and knowledge, and the longer it takes for us to get this fixed, the more work we'll need to do. Afterward, we'll be able to update the CI workflows to check the linting results and ensure that the codebase does not deteriorate.
- https://github.com/open-metadata/OpenMetadata/issues/3054 - While sonar helps us to avoid bugs and issues during PRs, we are missing important inputs from coverage. This is a requirement to help us see where we need to improve.
- https://github.com/open-metadata/OpenMetadata/issues/4766 - After fixing sonar and pylint, let's add mypy to the mix to ensure that we are properly typing and sending the expected data.
- https://github.com/open-metadata/OpenMetadata/issues/3940 - `SQLSource` is the major pillar of the ingestion framework, and it is not in its best shape. Properly refactor it into more manageable and better tested methods.
- https://github.com/open-metadata/OpenMetadata/issues/4894 - Tags cleanup
- https://github.com/open-metadata/OpenMetadata/issues/4767 - We need proper Lineage & Usage modules that centralize the logic. It will be easier to test and evolve.
- https://github.com/open-metadata/OpenMetadata/issues/4880 - Standardise JSON schema types
- https://github.com/open-metadata/OpenMetadata/issues/5014 - Fix ingestion-core publish and usage
- https://github.com/open-metadata/OpenMetadata/issues/5093 - DBT refactor

**Comment by harshach** [comment]
Lets clean this up in 0.13

**Comment by pmbrull** [comment]
we'll close linting on 0.13. Moving the rest for 0.14

**Comment by harshach** [comment]
@pmbrull anything to consider for 0.13.1 if not lets move it to 1.0

**Comment by pmbrull** [comment]
let's call it 1.0

**Comment by pmbrull** [comment]
we're only missing mypy. Will close this issue
