### ISSUE TITLE
Add Mypy to ingestion tests

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4766]
**Feature**
- https://github.com/open-metadata/OpenMetadata/issues/4765

**Describe the task**
Add http://mypy-lang.org/ to the CI process and fix the codebase. Let's break this down into multiple issues depending on the amount of work.

**Comment by harshach** [comment]
@pmbrull handle it in 0.13 or move it out?

**Comment by pmbrull** [comment]
we can do 0.14 here and focus on linting for 0.13
