### ISSUE TITLE
Broken Ingestion Link

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4776]
**Affected module**
UI

**Describe the bug**
docker-compose deployment locally. The link to the ingestion should redirect to airflow, but its saying `http://ingestion:8080/tree?dag_id=test_metadata` instead of `localhost`. 

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
cc @vivekratnavel

**Comment by vivekratnavel** [comment]
cc @harshach This is because of the endpoint exposed via airflow config API. This issue should be fixed once we remove the airflow config API.
