### ISSUE TITLE
remove newKey, newValue text from MessagingService connection form

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4786]
**Affected module**
UI

**Describe the bug**
<img width="875" alt="image" src="https://user-images.githubusercontent.com/38649/167283868-3a0855c1-d50b-42d0-b907-65cd4998eca2.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by darth-coder00** [comment]
We already have fixed the filtering default values from payload.

**Comment by darth-coder00** [comment]
Library has an issue posted for seeing invalid property not matching the schema
https://github.com/rjsf-team/react-jsonschema-form/issues/2672

Ours is the similar case

CC: @harshach @vivekratnavel

**Comment by harshach** [comment]
@Sachin-chaurasiya @chirag-madlani lets figure this out and fix it for 0.13.1

**Comment by Sachin-chaurasiya** [comment]
The configs are objects and to create the object it will require some placeholder values, that is why that newKey and newValue are shown by default from the library itself.

From our side, we have added logic to remove those default values while submitting the data, so closing this issue
