### ISSUE TITLE
Backend - Tables get overwritten if of same name but different case

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#4797]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

This is the tables page after ingestion
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/40225091/167377122-f7dc6164-440f-4299-9fa4-7fcc08169f1d.png">

Ingestion shows successfully ingested
<img width="616" alt="image" src="https://user-images.githubusercontent.com/40225091/167377850-9d8ba173-58b4-4591-b380-7c5b6170a55c.png">

Expected:
1st Table Name: PERSONS
2nd Table Name: persons
Both Ingesting successfully and show up on UI as well as in DB

Actual
1st Table Name: PERSONS
2nd Table Name: persons
Ingestion shows up as successful for both but UI and DB shows 1 table. The Latter table overwrites the former.

Note: Snowflake takes in same names with different cases - only difference is that it takes quotes in order to differentiate those.

**Comment by sureshms** [comment]
@harshach, this was taken care of by you, right?
