### ISSUE TITLE
Add metadata collection for delta tables.

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [open-metadata/OpenMetadata#481]
Support the delta table metadata collection.

**Comment by allenhaozi** [comment]
https://github.com/delta-io/delta/issues/1097
I also created a related issue that we can discuss here

**Comment by allenhaozi** [comment]
If I use S3 to store delta Lake tables

There are two ways to obtain metadata
1. Asynchronous 
> bucket polling based on the rules I used to build tables in S3 to find out which tables are in Delta Lake, and then get their schema information and synchronize it

2. Synchronous
>  such as Delta Lake, supports a configuration that listens to create/ ALTER tables and triggers synchronous metadata

Isn't it ? Welcome to discuss

**Comment by harshach** [comment]
@codingwithabhi this is fixed right, can we close it?
cc @pmbrull

**Comment by pmbrull** [comment]
This is implemented. There are two approaches here:
1. Ingest delta tables from a given metastore using the deltalake connector
2. Ingest directly the parquet files using the datalake connector
