### ISSUE TITLE
Support pluggable iceberg catalog so iceberg metadata can be correctly collected

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [open-metadata/OpenMetadata#482]
ICeberg support many different caalogs and users could choose any implementation, for collecting the metadata for iceberg tables it makes more sense to let users configure what catalog implementation they would like to use to collect all metadata vs relying on underlying engines like presto and spark.

**Comment by JensRoland** [comment]
If implementing Iceberg support, please consider Nessie as well.

**Comment by canopenerda** [comment]
We have a lakehouse solution built upon iceberg and nessie catalog. When I experiment metadata profiling for iceberg in Open Metadata, I found generic catalog support for iceberg is missing.
