### ISSUE TITLE
Fields for creating service used by Tableau and Redash - UI

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#484]
Fields required for Tableau and Redash

Tableau:
 username: str
 password: str
 server: str
 api_version: str
 env: Optional[str] = 'tableau_prod'  /*(default)*/
 site_name: str
 site_url: str
 service_name: str
 

Redash:
 uri: str = "http://localhost:5000"
 api_key: str

**Comment by shahsank3t** [comment]
Tableau integration has been done, Redash is moved to 0.5.0.

**Comment by shahsank3t** [comment]
Created https://github.com/open-metadata/OpenMetadata/issues/523 to track Redash, closing this issue.
