### ISSUE TITLE
Update Open Metadata to handle python 3.7 version logic to support AWS managed airflow

### ISSUE THREAD

**Issue by issaq84mohd** [open-metadata/OpenMetadata#4849]
**Feature**
Open Metadata currently support python 3.8 or above due to this version constraints we cannot use the Open Metadata capabilities on AWS Managed Airflow since it's build on python 3.7.

**Describe the task**
Update the Open Metadata libraries to handle python 3.7 version

**Comment by harshach** [comment]
Can we make the OM Lineage backend to use python 3.7?

**Comment by issaq84mohd** [comment]
@harshach - Are you planning to add this fix for the release 0.11 ? Is there a possibility we can get this done sooner?

**Comment by harshach** [comment]
@issaq84mohd we are working on a few other options. 
1. is directly reading from airflow DB to extract metadata. This way you don't even need to configure the lineage backend in airflow configuration. Instead, you can just configure a connector and provide the airflow DB access details.
2. If the above option doesn't work we need to see how we can downgrade to the 3.7 
Let us know if option 1 works for you.

cc @pmbrull

**Comment by harshach** [comment]
@issaq84mohd as a first step we are going to support 3.6 https://github.com/open-metadata/OpenMetadata/pull/5003
