### ISSUE TITLE
Clicking on an ingestion doesn't route you to airflow

### ISSUE THREAD

**Issue by mesmith027** [open-metadata/OpenMetadata#4853]
**Affected module**
I think it's Ingestion Framework? @harshach correct me on this if I am wrong 

**Describe the bug**
When you are looking at a service on the "ingestion" tab, and you click the hyperlinked "Name" to view the service in airflow, it _should_ open a new tab in airflow and show you the running service. Instead, it picks up the wrong URL and you get an error page (this site can't be reached)

**To Reproduce**
- Go to a service connection and click on "ingestions" 
- Click the "name" of the ingestion you want to view in airflow
<img width="1428" alt="Screen Shot 2022-05-10 at 3 14 11 PM" src="https://user-images.githubusercontent.com/66020208/167705831-2ad88b79-4599-4359-9c6a-377a2bf5349b.png">
- this opens a new tab
- new tab URL is wrong and brings you to an error page 
<img width="1628" alt="Screen Shot 2022-05-10 at 3 14 23 PM" src="https://user-images.githubusercontent.com/66020208/167706185-716e84d4-c31f-4fba-a6b7-1c3c9166cebb.png">

**Expected behaviour**
- when you click on the "name" of the ingestion, it should redirect you to `localhost:8080/path/to/airflow` and not `http://ingestion:8080/path/to/airflow`
<img width="1697" alt="Screen Shot 2022-05-10 at 3 26 20 PM" src="https://user-images.githubusercontent.com/66020208/167707559-452e57e5-3e9f-4525-ac6b-6c46c571791e.png">

**Version:**
 - OS: any
 - Python version: any
 - OpenMetadata version:  10.0
 - OpenMetadata Ingestion package version: N/A

**Comment by harshach** [comment]
closing this in favor of https://github.com/open-metadata/OpenMetadata/issues/4776
