### ISSUE TITLE
Changing the default schedule on an new connector ingestion does not run

### ISSUE THREAD

**Issue by mesmith027** [open-metadata/OpenMetadata#4854]
**Affected module**
pretty sure the Ingestion Framework

**Describe the bug**
Using the OM UI, if you create a brand new service connection and then change the preset defaults of the ingestion, then the service ingestion does not run right away.

**To Reproduce**
- create any new service through the UI, on the last step choose to "add Ingestion" button
<img width="1317" alt="Screen Shot 2022-05-10 at 3 41 53 PM" src="https://user-images.githubusercontent.com/66020208/167710430-62fa8802-7531-4efb-b79f-8a869d3e98be.png">

- configure ingestion connection (you can leave the defaults to reproduce)
- change the schedule interval to something other than defaults and hit deploy

<img width="1327" alt="Screen Shot 2022-05-10 at 3 42 35 PM" src="https://user-images.githubusercontent.com/66020208/167710791-36c3d9a0-650f-4d35-b030-91127981dc14.png">

- go to the service (view service)
- go to Ingestions, the service appears but it is not running (recent runs column is empty)

<img width="1772" alt="Screen Shot 2022-05-10 at 3 44 40 PM" src="https://user-images.githubusercontent.com/66020208/167711282-49492e3f-a3f6-4f8c-8cbd-2eeefb70452e.png">

**Expected behaviour**
You expect that the ingestion will run once right now, even though you set all future ingestions to a specific schedule. 
<img width="1764" alt="Screen Shot 2022-05-10 at 3 46 40 PM" src="https://user-images.githubusercontent.com/66020208/167711595-487088cd-0098-4408-8a41-905f77aaab97.png">

**Version:**
 - OS: N/A
 - Python version: N/A
 - OpenMetadata version: 10.0
 - OpenMetadata Ingestion package version: N/A

**Comment by pmbrull** [comment]
hi @mesmith027 would that behavior be correct? IMO scheduled workflows should run when the time is met. If some users need the workflow to be triggered externally right away, they can already do so from the UI 🤔
