### ISSUE TITLE
Ingestion UI | Updating an existing Snowflake Usage Ingestion pipeline via UI is not working

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4864]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI & Ingestion

**Describe the bug**
Currently, when an existing ingestion pipeline on the UI is updated, the changes aren't reflected on the equivalent `.json` under `/airflow/dag_generated_configs/*.json`.

**To Reproduce**
* Create a Snowflake Usage pipeline via UI
* Update the existing pipeline and check for changes on the `/airflow/dag_generated_configs/*.json`.

Screenshots or steps to reproduce
NA

**Expected behavior**
Reflect any changes on the Ingestion pipelines on the UI

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]
`metadata, version metadata 0.10.1.0.dev1 from /usr/local/lib/python3.9 (python 3.9)`

**Additional context**
NA

**Comment by pmbrull** [comment]
after decoupling the IngestionPipeline create/update & deploy, I think we missed adding the deploy after editing a pipeline. We only update the IngestionPipeline entity without passing the request to the Airflow REST.

@vivekratnavel @darth-coder00 

![image](https://user-images.githubusercontent.com/35870520/167823031-531b3f7a-ac70-4106-9980-0a1ef2eb9edd.png)
