### ISSUE TITLE
Snowflake | Optimize Snowflake tag_references for Snowflake Ingestion

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#4866]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework

**Describe the bug**
Snowflake Ingestion pipeline seem to be running the query for `tag_references` multiple times for a specific `table`.

**To Reproduce**
* Run ingestion for Snowflake on `0.10.1.dev.0` with `tag_references`
* Notice the same query for extracting `tag_references` running multiple times

Screenshots or steps to reproduce
NA

**Expected behavior**
Extract `tag_references` from only 1 metadata query per table.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]
`metadata, version metadata 0.10.1.0.dev1 from /usr/local/lib/python3.9 (python 3.9)`

**Additional context**
NA

**Comment by sidhreddy** [comment]
@harshach @ayush-shah Would we be able to get this on 0.11? 🙇

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/5376

**Comment by pmbrull** [comment]
@sidhreddy this will be part of 0.11. Thanks for reporting!
