### ISSUE TITLE
Support Azure blob for metadata backup dump

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4868]
based on https://openmetadata.slack.com/archives/C02B6955S4S/p1652248191418669?thread_ts=1652243987.478259&cid=C02B6955S4S

Support Azure blob for the CLI metadata dump as well. We currently only support AWS S3.

**Comment by amymareemc** [comment]
Hi, I’d like to be assigned to this.

**Comment by pmbrull** [comment]
Hi @amymareemc, thanks. Assigned!

You can take a look at this implementation https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/cli/backup.py#L52 and add the required logic for Azure blob storage

**Comment by shivamshrey** [comment]
Hey @pmbrull, is this being worked on?

**Comment by pmbrull** [comment]
hi @shivamshrey no, we have not picked it up yet

**Comment by amymareemc** [comment]
Currently working on this issue. I looked at the [current implementation](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/cli/backup.py#L52)  for AWS S3. It seems like `get_output()` and `run_backup()` would stay relatively consistent. Is the idea to add an additional `upload_azure_backup()` specifically for azure within `backup.py`? (or adapt the existing `upload_backup()` with a flag for either Azure or AWS?)

**Comment by harshach** [comment]
Lets handle this for 0.13.1

**Comment by pmbrull** [comment]
hi @NiharDoshi99 the development here should be done. Pending topics are:
- test if anything's missing
- docs

Thanks

**Comment by harshach** [comment]
@NiharDoshi99 any update?
