### ISSUE TITLE
NotImplementedType is thrown while trying to  add Superset as a dashboard services 

### ISSUE THREAD

**Issue by DataScientistSamChan** [open-metadata/OpenMetadata#4885]
**Affected module**
Dashboard Service Module

**Describe the bug**
I install openmetadata using the official docker-compose.yml. Everything is fine until i tried to add superset as a dashboard service.
I tried to add superset in the dashboard services with the below input, and I press test connection and the error arises as below.

![image](https://user-images.githubusercontent.com/18599494/167846620-f49613b2-556e-457b-8834-79147ca15500.png)

**To Reproduce**

![image](https://user-images.githubusercontent.com/18599494/167846620-f49613b2-556e-457b-8834-79147ca15500.png)

**Expected behavior**
I should be able to test connection

**Version:**
 - OS: Linux
 - Python version: 3.9.12
 - OpenMetadata version: 0.10 stable
 - OpenMetadata Ingestion package version: 
 openmetadata-ingestion                   0.10.0.1
openmetadata-ingestion-core              0.10.0

**Comment by ayush-shah** [comment]
Hey @DataScientistSamChan - the above issue is fixed in 0.10.1 - upcoming release - bits to be published next week.

If you want to try out preview images for the same,
Python
openmetadata-ingestion-core==0.10.1.dev0
openmetadata-ingestion==0.10.1.0.dev1
openmetadata-airflow-managed-apis==0.10.1.0.dev1
Docker
[openmetadata/server:0.10.1.dev.0](https://hub.docker.com/r/openmetadata/server/tags?page=1&name=0.10.1)
[openmetadata/ingestion:0.10.1.dev.0](https://hub.docker.com/r/openmetadata/ingestion/tags?page=1&name=0.10.1.dev.0)
[openmetadata/db:0.10.1.dev.0](https://hub.docker.com/r/openmetadata/db/tags?page=1&name=0.10.1.dev.0)
[openmetadata/airflow:0.10.1.dev.0](https://hub.docker.com/r/openmetadata/airflow/tags?page=1&name=0.10.1)


To answer your question on `Database Service Name`
Database Service Name refers to the datasource superset is fetching data from in order to create a lineage between the dashboard and the table it is created from.
In order to have the database service name working, you need to first ingest the data from the relevant sources(db sources) and then ingest superset with the service name for the db service you created first.

**Comment by DataScientistSamChan** [comment]
Wow, you guys are amazing. Now `NotImplementedType` error is gone, but a new error arises as below. 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/18599494/167870443-52f4092d-2a5f-42cb-8619-de6aad04aa4d.png">

FYI, my superset version is 1.0. And the entity returned is as below. It looks like the json structure of this entity may not collide wth the platform's orm suggest.
```
{
    "result": [
        {
            "childs": [
                "-",
                {
                    "icon": "fa-lock",
                    "label": "Row Level Security",
                    "name": "Row Level Security",
                    "url": "/rowlevelsecurityfiltersmodelview/list/"
                },
                {
                    "icon": "fa-table",
                    "label": "Access requests",
                    "name": "Access requests",
                    "url": "/accessrequestsmodelview/list/"
                }
            ],
            "icon": "fa-cogs",
            "label": "Security",
            "name": "Security"
        },
        {
            "childs": [
                {
                    "icon": "fa-comment",
                    "label": "Annotation Layers",
                    "name": "Annotation Layers",
                    "url": "/annotationlayermodelview/list/"
                },
                {
                    "icon": "fa-css3",
                    "label": "CSS Templates",
                    "name": "CSS Templates",
                    "url": "/csstemplatemodelview/list/"
                },
                {
                    "icon": "fa-cloud-upload",
                    "label": "Import Dashboards",
                    "name": "Import Dashboards",
                    "url": "/superset/import_dashboards/"
                },
                {
                    "icon": "fa-exclamation-triangle",
                    "label": "Alerts & Reports",
                    "name": "Alerts & Report",
                    "url": "/alert/list/"
                }
            ],
            "icon": "",
            "label": "Manage",
            "name": "Manage"
        },
        {
            "icon": "fa-dashboard",
            "label": "Dashboards",
            "name": "Dashboards",
            "url": "/dashboard/list/"
        },
        {
            "icon": "fa-bar-chart",
            "label": "Charts",
            "name": "Charts",
            "url": "/chart/list/"
        },
        {
            "childs": [
                {
                    "icon": "fa-flask",
                    "label": "SQL Editor",
                    "name": "SQL Editor",
                    "url": "/superset/sqllab/"
                },
                {
                    "icon": "fa-save",
                    "label": "Saved Queries",
                    "name": "Saved Queries",
                    "url": "/savedqueryview/list/"
                },
                {
                    "icon": "fa-search",
                    "label": "Query History",
                    "name": "Query Search",
                    "url": "/superset/sqllab/history/"
                }
            ],
            "icon": "fa-flask",
            "label": "SQL Lab",
            "name": "SQL Lab"
        },
        {
            "childs": [
                {
                    "icon": "fa-database",
                    "label": "Databases",
                    "name": "Databases",
                    "url": "/databaseview/list/"
                },
                {
                    "icon": "fa-table",
                    "label": "Datasets",
                    "name": "Datasets",
                    "url": "/tablemodelview/list/"
                },
                "-",
                {
                    "icon": "fa-upload",
                    "label": "Upload a Columnar File",
                    "name": "Upload a Columnar file",
                    "url": "/columnartodatabaseview/form"
                },
                {
                    "icon": "fa-upload",
                    "label": "Upload Excel",
                    "name": "Upload Excel",
                    "url": "/exceltodatabaseview/form"
                }
            ],
            "icon": "fa-database",
            "label": "Data",
            "name": "Data"
        }
    ]
}

```

**Comment by DataScientistSamChan** [comment]
To throw in some info, I did not see the `openmetadata/airflow` image in `docker-compose.yml`, but I did change the other 3 images.

**Comment by ayush-shah** [comment]
Yes - the openmetadata/airflow isn't a part of the docker-compose.yml

**Comment by ayush-shah** [comment]
We will test out the superset issue that you are facing, try to reproduce the issue and fix it.

**Comment by harshach** [comment]
@ayush-shah any updates!

**Comment by ayush-shah** [comment]
It's a work in progress, will take this up in this milestone.

**Comment by harshach** [comment]
@ayush-shah @ulixius9 lets prioritize this one for 0.13

**Comment by pmbrull** [comment]
hi @DataScientistSamChan are you still facing this issue? We are having some trouble spinning up superset 1.0. If you could help us get a dev environment, that would be great. Thanks

**Comment by pmbrull** [comment]
Closing this for now. @DataScientistSamChan feel free to ping us here if you still need help with that. It would be good to sync and work together on delivering and testing the fix. Thanks
