### ISSUE TITLE
Optimize + Cleanup - Fetching tags

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#4894]
We have a standardized method in order to fetch tags.
this can be used for table level entities as well as column level entities.

- [x] Cleanup - Bigquery Policy Tags code can be moved to standardized method.

- [x] #5375

**Comment by harshach** [comment]
lets see what are all the databases support this and we should add integration to all of them

**Comment by pmbrull** [comment]
opened trino and postgres separatedly
