### ISSUE TITLE
List of aliases for columns of different origins but that are the same

### ISSUE THREAD

**Issue by mesmith027** [open-metadata/OpenMetadata#4896]
**Is your feature request related to a problem? Please describe.**
The user requested mapping such that any references in the metadata will be mapped to a common name. 

For example:  
if you have different data sources, all of them with a reference to Client ID, but with different names for each scheme, for example, ClientID, ClientID, Client_ID; and what I would like is to create a client identification metadata that have aliases or synonyms (Like a list of aliases for an specific column name).

Say 3 tables have the same column of data, but with all slightly different names, say user_ID, ClientID and User-ID. Having a list that shows these different column names as a list so you can easily identify that those columns are actually the same data.

**Additional context**
Created from Slack support channel: https://openmetadata.slack.com/archives/C02B6955S4S/p1652207575754789

**Comment by pmbrull** [comment]
cc @harshach
