### ISSUE TITLE
UI: Check `status` api to verify if airflow is setup

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#4899]
Check status api to notify user about airflow setup before allowing them to create ingestion pipelines

**Comment by harshach** [comment]
@darth-coder00 status API check should be a silent check. if there is any error i.e status other than 200 we should show the helpful message to the users similar to Explore page when the ElasticSearch server is not available.
cc @vivekratnavel @shahsank3t

**Comment by darth-coder00** [comment]
@harshach, Yes we will not throw any toast notification for any errors in status api, provide some message on UI that is highlighted to grab user's attention.
