### ISSUE TITLE
Dashboard Datasource Lineage - not being generated

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#4909]
Lineage is not being generated for datasources.
Datasource text we receive - schema.table

- [x] #5260
- [x] #5261
- [x] #5262
- [x] #5317

we will have to use ES in order to create lineage

**Comment by pmbrull** [comment]
Let's fix this after https://github.com/open-metadata/OpenMetadata/issues/4496

**Comment by pmbrull** [comment]
@ulixius9 We should take this in consideration during the lineage revamp
