### ISSUE TITLE
Entity extension mechanism - support adding custom properties to an entity

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#4920]
OpenMetadata follows a schema-first approach using JSON schema to model the strongly-typed entities. This is very important for building open standards for metadata and making metadata sharable. This is in contrast with other systems that loosely model the metadata with **key-value** as the basis for building schema. The second approach makes extending schema easy but at the cost of standardization. Every organization looks different in terms of metadata they store making sharing metadata hard. Every tool has to be customized or purpose-built for an organization.

OpenMetadata defines a comprehensive set of entities using well-defined types required for a centralized metadata store. However, an organization may want to add additional attributes to an entity to serve some specific needs of the organization. This feature addresses the need to extend the entities with custom attributes.

Task breakdown:
- #4921
- #4977 
- #5010 
- #5345 
- #5344

**Comment by zlgonzalez** [comment]
In general, what I was hoping to see is the ability to create:

1. Class definition
2. Association definition
3. Property definitions - this would look more like the custom attributes

I think being able to create a Type definition would be interesting as well, though it seems like the struct, list and scalar should suffice for columns.

A Class definition would have a 1:n to an Association definition. Both class definition and association definition can have a 1:n to a property definition. By creating this kind of object model, this allows users to create their own metadata type, and create instances of this class definition.

Would be great to hear the team's thoughts on this...
