### ISSUE TITLE
Separator lines are overlapping in profile page if edit description box is open

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#4934]
**Affected module**
UI

**Describe the bug**
Separator lines are overlapping on the profile page if the edit description box is open

**To Reproduce**

- Navigate to User Profile page
- Click on edit description button below user name
- The separator lines are overlapping on the description box
<img width="1422" alt="Screenshot 2022-05-13 at 4 19 23 PM" src="https://user-images.githubusercontent.com/67048554/168275168-36c741a2-f23b-4dc8-a29f-61c682c8ef4b.png">

**Expected behavior**
Separator lines should not overlap

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Fixed by #4938
