### ISSUE TITLE
Views are not getting ingested in `mysql`

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#4942]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - Ingestion

**Describe the bug**
Views are not getting ingested in `mysql` through ingestionPipeline API as well as CLI

**To Reproduce**

1. Create View in MySQL DB
2. Configure ingestion pipeline to include views
3. Run ingestion and check the ingested data

Created view is not available in ingested data.

**Expected behavior**
View should be available in ingested data.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by pmbrull** [comment]
hi @darth-coder00 tried from `main`

![image](https://user-images.githubusercontent.com/35870520/168326339-cde413e8-2c28-486a-98ec-6df41496cf20.png)

**Comment by darth-coder00** [comment]
Closing this issue as it is not replicable
