### ISSUE TITLE
UI: Json to typescript should be a part of the build

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4953]
We should generate typescript files from  JSON schema on the fly during every build similar to the connection schemas and remove all the generated typescript files from the source code repository.

**Comment by darth-coder00** [comment]
- [ ] Fix Invalid Json-schemas
- [ ] Remove references of generated typescripts, who's Json-schema is deleted
- [ ] Make `json2ts` as part of build
