### ISSUE TITLE
E2E Testing with Cypress

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#4972]
- [x] #5018
- [x] #5034
- [x] #5035
- [x] #5139
- [ ] #5140
- [x] #5200
- [x] #5201
- [x] #5202

**Comment by Sachin-chaurasiya** [comment]
Closing this as only one page is pending and we have separate ticket for the same https://github.com/open-metadata/OpenMetadata/issues/5140
