### ISSUE TITLE
Sample data not ingested in deltalake connector

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#4973]
**Affected module**
Ingestion Framework

**Describe the bug**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39544459/168577604-e25db443-448a-40f4-835e-bcae160437a8.png">

**To Reproduce**
Ingest Deltalake Connector

**Comment by pmbrull** [comment]
WE need to figure out how (and if) to run the profiler on non-SQA sources cc @TeddyCr

**Comment by pmbrull** [comment]
to be validated after https://github.com/open-metadata/OpenMetadata/issues/7449

**Comment by harshach** [comment]
@TeddyCr whats plan around non SQA sources?

**Comment by TeddyCr** [comment]
We started the work progressively. We added support for:
- data lake
- Mongo
- BigTable

The plan is to keep addressing the issue based on community feedback and keep it open as "Good first issue" for community contributor 😊
