### ISSUE TITLE
Support alternative orchestrators for metadata ingestion

### ISSUE THREAD

**Issue by blarghmatey** [open-metadata/OpenMetadata#4986]
**Is your feature request related to a problem? Please describe.**
It would be nice to abstract the dependency on Airflow to support a pluggable interface for orchestrators to manage the metadata ingestion workflow. 

**Describe the solution you'd like**
being able to hook into Dagster, Prefect, Flyte, etc. if they are already part of the infrastructure would be very useful. It should be possible to (if not already present) build importable functions that perform the necessary actions which can then be easily wrapped by whichever orchestration engine is being used.

**Describe alternatives you've considered**
The default alternative is to use the system as it stands today, which is acceptable but not necessarily optimal or preferred.

**Additional context**
N/A

**Comment by Trymzet** [comment]
They even have a tutorial for Prefect but I couldn't find this `prefect_ingestion` function in the library https://docs.open-metadata.org/overview/run-openmetadata-with-prefect

**Comment by harshach** [comment]
@pmbrull can we publish a example for prefect and call it done?

**Comment by pmbrull** [comment]
We now have an interface https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/java/org/openmetadata/sdk/PipelineServiceClient.java that can be extended to bring support to any other orchestrator. You can follow the implementation we have for Airflow https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java as a starting point
