### ISSUE TITLE
Multiple Language Definition Support.

### ISSUE THREAD

**Issue by EminUZUN** [open-metadata/OpenMetadata#5001]
It would be great to have multiple language definitions and glossary management as mentioned in 
slack threat https://openmetadata.slack.com/archives/C02DZK3QH8Q/p1652781221405869

 @harshach

**Comment by harshach** [comment]
@chirag-madlani what is the progress so far?

**Comment by chirag-madlani** [comment]
Will be tracking it here: #3474
