### ISSUE TITLE
[BACKEND] Moving common files to OpenMetadata-core

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#5025]
**Is your feature request related to a problem? Please describe.**
The JSON schema and a lot of common files are currently present in catalog-rest-service which need to be refactored to OpenMetadata-core and used as a dependency for rest-service.

**Describe the solution you'd like**
1. openmetadata-core submodule needs to be created with the following files:-
   - Exceptions used in rest-service should be moved this.
   - JsonSchema used by different modules needs to come from this core as a dependency.
   - Interface for entity needs to be added, concrete definition can be part of rest service.
   - Common utilities needed by the EntityRepository need to be refactored.
 Following structure needs to be followed : 
openmetadata-core 
 - src
   - main
      - java
         - org.openmetadata.core
            - entity -> contains interface and classes for entity specific classes
            - exception -> exceptions used by the rest services
            - jdbi3 -> top level files which are used in rest-service 
            - util -> Utils available in rest-service for common functionalities
 
2. catalog-rest-service will be renamed as openmetadata-api
3. common needs to be removed from the repositories
4. modules using common need to be updated to use OpenMetadata-core

**Proposed module structure**

   1. openmetadata-core , contains JsonSchema and common dependencies such as Error and Entity classes and also ingestion-core module will be part of openmetadata-core
   2. openmetadata-apis, contains all the dropwizard resources / server / tests
   3. openmetadata-clients, contains the clients for Java and Python etc..
   4. ingestion , contains all things related to ingestion
   5. openmetadata-app, contains the UI code 

cc @sureshms @vivekratnavel @pmbrull @ayush-shah @Sachin-chaurasiya @ShaileshParmar11

**Comment by harshach** [comment]
@mohitdeuex can you describe the layout of these modules 
1. openmetadata-core contains json schema files and classes etc..
2. openmetadata-api etc..

**Comment by mohitdeuex** [comment]
updated

**Comment by mohityadav766** [comment]
done already by @harshach
