### ISSUE TITLE
Automate Release deployments

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5031]
We should have a set of GitHub actions that take care of automatically deploying python and docker images both when a release is crated and under demand (in case we need any dev deployment or bugfix)

- https://github.com/open-metadata/OpenMetadata/issues/5014 (might be a copy of https://github.com/open-metadata/OpenMetadata/issues/2363)
- https://github.com/open-metadata/OpenMetadata/issues/5027
- https://github.com/open-metadata/OpenMetadata/issues/5029
- https://github.com/open-metadata/OpenMetadata/issues/5426
- https://github.com/open-metadata/OpenMetadata/issues/5030

For all these processes, they should be documented in Notion to help anyone in the team handle it if necessary and not silo the knowledge in a single person

**Comment by harshach** [comment]
@akash-jain-10 are we going to finish the helm charts auto release process?

**Comment by akash-jain-10** [comment]
Since Helm Charts are not part of OpenMetadata Repo, it would have it's own CI Actions! We have documentation ready on what needs to be updated for the release here! Helm Charts Auto Release process is in place!

**Comment by harshach** [comment]
@akash-jain-10 part of this ticket make sure we add all of our tests to minor releases as well. It should be automated

**Comment by akash-jain-10** [comment]
Hello @harshach and @pmbrull - Will close this issue for the last comment since we have already added an issue ticket to track Enabling Github CI for Release branches [here](https://github.com/open-metadata/OpenMetadata/issues/7434)
