### ISSUE TITLE
[JWT Token Generation] Unable to generate a token with Expiration value of Unlimited Days

### ISSUE THREAD

**Issue by abcabhishek** [open-metadata/OpenMetadata#5070]
**Affected module**
Backend + Ingestion Framework

**Describe the bug**

**To Reproduce**
1. Generated the private and public keys using the following: `
```
openssl genrsa -out private_key.pem 2048   
openssl pkcs8 -topk8 -inform PEM -outform DER -in private_key.pem -out private_key.der -nocrypt
openssl rsa -in private_key.pem -pubout -outform DER -out public_key.der 
```
2. Add the full path to the public_key.der and private_key.der to the envrionment variables 
3. Ran OpenMetadata using IntelliJ
4. Go to Bots -> Selected Ingestion Bot -> Generate JWT token -> Select Expiration as "Unlimited Days" -> Click on Generate
5. The process fails at this step and the screen shows a message (Oops! An unexpected error occurred)

**Expected behavior**
JWT token should be generated which has unlimited validity, similar to the JWT tokens being issued for 7, 30, 60 and 90 days

**Version:**
 - OS: MacOS X Catalina 10.15.7
 - Python version: 
 - OpenMetadata version: [e.g. 0.10.1]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Logs from Mac:
```
[0:0:0:0:0:0:0:1] - - [20/May/2022:12:28:16 +0000] "PUT /api/v1/users/generateToken/<redacting because it looks to be a common endpoint for all tokens being generated for me> HTTP/1.1" 400 241 "http://localhost:8585/bots/ingestion-bot" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" 7
```

Screenshot:
![image](https://user-images.githubusercontent.com/16971608/169529769-e64ce45f-7750-4873-bf9e-62406c2423b1.png)

**Comment by harshach** [comment]
ok let me check
