### ISSUE TITLE
Make "Data Quality" column on Table schema page optional to hide

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#5091]
We don't have any use for "Data Quality" column on table schema page (for now). We might also have actual DQ issues which we are (for the time being) communicating through other channels and hence don't want to set expectation that OM is source of truth. In order to not confuse our customers, we only want to show them relevant information.

Requesting to make DQ column optional to hide.

**Comment by sidhreddy** [comment]
+1

**Comment by harshach** [comment]
@Sachin-chaurasiya can you do a test on this? If the user doesn't have view permission on data quality the tab shouldn't be visible and we shouldn't be making an API call
