### ISSUE TITLE
Glossary export/import

### ISSUE THREAD

**Issue by filip-xmargin** [open-metadata/OpenMetadata#5098]
**Problem**

As metadata manager, I need to export Glossary content only, process it outside of my OMD and then import again (without erasing all database).

**Minimal solution**

Ability to import (with overwrite) Glossary data from file format like xml/json.

**Ideal solution**

Ability to selectively import & export any essential kind of metadata, including 

* metadata limited to selected services or tables
* Glossary content
* user-generated content like custom tags / descriptions.
* lineage data only

**Alternatives**

There is an option of full database backup and restore. However this will overwrite _all_ database, including all the ingested metadata,custom tags and profiling data -  which might be costly to recover.

**Comment by harshach** [comment]
we will be doing import only for 0.13.1 release
