### ISSUE TITLE
UI shows incorrect table number

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5135]
**Affected module**
UI

from https://openmetadata.slack.com/archives/C02B6955S4S/p1653461804389539

**Describe the bug**
![image](https://user-images.githubusercontent.com/35870520/170210175-671914ed-1f08-40aa-8e2c-516366bdc0b2.png)

I see that the UI OMD incorrectly shows the number of tables if this value exceeds 10000. If you check the Oracle box in the screenshot, then the UI shows the correct value for a particle of a second, and then 10,000 tables again. v0.10.0 Released on 26 Apr 2022.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by shahsank3t** [comment]
@harshach is there a limitation on elastic search that limits to 10,000 counts, coz UI is just displaying whatever elastic search API is providing in response?

**Comment by harshach** [comment]
@shahsank3t I think its a bug on the UI side. One should always look at the "hits"field to show the number of docs

**Comment by harshach** [comment]
@shahsank3t never mind its a bug on backend side. Fixing it

**Comment by harshach** [comment]
@Sachin-chaurasiya @shahsank3t 
1. ElasticSearch made improvements to provide approximate number and I am adding a parameter to get accurate count
2. However we should use this carefully , i.e only upon explore page click when we show counts on the tabs pass the track_total_hits=true, by default this will be set to false . 
3. ES will show up to 10000 matches when that is set to false. Important UX here is

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/38649/170926145-35a4438b-1193-4acc-9b70-a0570e7f7e41.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/38649/170926174-b5363323-5de8-4c7c-8299-f11d2dc96201.png">
incase of search we show "4 results" but when a user selects a filter we don't show that. 
we should in both cases and if we get 10000 results we should show "About 10000 results"
