### ISSUE TITLE
 add new constraints: distributon and sort key

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#5153]
**Is your feature request related to a problem? Please describe.**
Unable to add `DISTKEY` and `SORKEY` as table constraints.

**Describe the solution you'd like**
Add `DISTKEY` and `SORKEY` as table constraints.
https://github.com/open-metadata/OpenMetadata/blob/9a3fa2e532ecbdf0c83d0ebce30788ce511fe965/openmetadata-core/src/main/resources/json/schema/entity/data/table.json#L103

**Comment by sureshms** [comment]
@trillhaa these are specific to Redshift, right?

**Comment by trillhaa** [comment]
Was this released with 0.11.1?

**Comment by trillhaa** [comment]
@harshach - do you think you could support this in the next releases, is it a bigger lift? Some users in our org have requested for it.
