### ISSUE TITLE
Column type mapping as JSON Data

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5156]
Define the column mappings of the databases instead of having that as Python code.

It can be a way to easily document our approach

**Comment by harshach** [comment]
@pmbrull what needs to be done here?

**Comment by pmbrull** [comment]
this was a request from @sureshms to define centrally how we map incoming types from different sources to OM types. We currently have some Python dictionaries that we could analyze and see how to extract as JSON data

**Comment by pmbrull** [comment]
lets reopen if we want this in the future
