### ISSUE TITLE
Updating tests in workflow should show in the UI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5171]
From https://openmetadata.slack.com/archives/C02B6955S4S/p1653562294488499

1. configure test
2. run test
3. change test definition in workflow
4. run workflow
5. mismatching information on the UI

![image](https://user-images.githubusercontent.com/35870520/170488703-44da0012-cb62-41f7-99e3-072e1a5ecac8.png)

Let's tackle this after the backend APIs changes

**Comment by pmbrull** [comment]
should be covered by https://github.com/open-metadata/OpenMetadata/pull/6416 Let's just double check once the new UI is done

**Comment by TeddyCr** [comment]
This is solved by #6416. Validation steps:
1. configured a testCase
2. ran a testCase
3. Updated testCase conf
4. Re-ran testCase
5. Confirmed new configs is taken into account
