### ISSUE TITLE
OpenLineage Support

### ISSUE THREAD

**Issue by pixie79** [open-metadata/OpenMetadata#5179]
Hi 

I know this has been asked before
https://github.com/open-metadata/OpenMetadata/issues/1267

But I was wondering if it was time to consider aligning the two products, especially as a lot of the data feeding into OpenMetadata comes from sources like Airflow which is supporting Open Lineage directly (with Astronomer now directly backing both). It would be great to see one standard going forward where Open Metadata can build on top of other open standards.

Mark

**Comment by sureshms** [comment]
OpenMetadata has a comprehensive spec for not only lineage but a much wider landscape of metadata. Marking this as won't fix. Reopen if you still feel this is necessary.
