### ISSUE TITLE
Whats new dialog box should open for the first time when the user logs in

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#518]
We are not opening what's new dialog box when the user logs in. This should happen only once for the first time user logs -in
Also, we show another dialog box to welcome the user (first-time signup). We should be able to do both

**Comment by darth-coder00** [comment]
@harshach, it's working on local server.

Please refer this screen recordings 
1. New/First-time user: https://app.replay.io/recording/6456c407-9da4-404d-ae0e-a6f873f1c1ce
2. Returning user(first time after release): https://app.replay.io/recording/debbc3fe-c5aa-4ef5-9da5-fb02fa3fa740
