### ISSUE TITLE
Explore page is not getting data if name contains special character

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#5182]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
not getting search results if we have "-" in the search term.

**To Reproduce**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71748675/170652562-6118ad1e-094f-4919-a2a7-647c7c45b713.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71748675/170652577-451bea7e-7b13-44af-a8fd-ae5c7483e267.png">

https://user-images.githubusercontent.com/71748675/170752019-ed43f480-a334-4126-a08d-8d4ef05ff316.mov

**Expected behavior**
it should search for data even if it contains a special character

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/208154192-fa63a4e1-eead-42bd-bb37-5f49f2f077bf.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/208154224-8cea3979-343e-4f63-881b-b7a8774ac9bf.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/208154273-dc1c2d05-264b-4a83-9253-8ce4cf5e3ecb.png">

Works now
