### ISSUE TITLE
Add profilerDataQuery into ProfilerWorkflow config

### ISSUE THREAD

**Issue by Curiosady** [open-metadata/OpenMetadata#5188]
**Is your feature request related to a problem? Please describe.**
We have really big tables in our Hive and we want to make profiling and data quality tests not on whole tables, but on some sample of data. Some of the tables so huge that almost infinite time needed for profiling them.

**Describe the solution you'd like**
We'd like to see "profilerDataQuery" in ProfilerWorkflow configuration analogous to "sampleDataQuery" in regular Workflow. Where we can define how to select data from table for subsequent profiling and data quality testing.

**Comment by harshach** [comment]
@pmbrull @TeddyCr ^
