### ISSUE TITLE
ES indexing issue for deleted tags

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#5199]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Even after deleting a tag or category, it appears in ES search results
**To Reproduce**

Screenshots or steps to reproduce

https://user-images.githubusercontent.com/71748675/170742058-68245d08-eb3e-4dd0-b9f8-a37ee83bfe70.mov

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@sureshms should we allow deletion of tags when they are associated with entities. This going to be tricky to resolve on ES side as we need to update all the indexes on one change event to remove any associated deleted tags
