### ISSUE TITLE
UI - wrong asset instance in Teams redirection

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#5208]
**Affected module**
UI

**Describe the bug**
When you go to the Team Assets, there are tables, schemas and database listed there. For some reason, open metadata redirects all schemas and databases that belong to a Team to non existent tables, i.e., by default all assets are considered tables instances and when you click on a schema/database instance, you get error because open metadata can't find such table. 

**To Reproduce**

Screenshots or steps to reproduce

Go to Teams -> Assets -> choose schema and click on it -> "Table instance is not found" for a schema instance. 
When you click on the schema instance from **Team assets** window, open metadata is trying to redirect you to the table type. But it's a schema, so we get an error:

![bug2_1](https://user-images.githubusercontent.com/60112387/170885661-55d2e2cd-4169-483c-9016-71a9a5ba61d4.png)
![bug2_2](https://user-images.githubusercontent.com/60112387/170885665-9b225a61-0a40-41ed-938b-ac2308189546.png)
![bug2_3](https://user-images.githubusercontent.com/60112387/170885841-e2b8aa40-3bc9-4891-9bd0-300edfbf139d.png)

**Expected behavior**
When you click on schema instance, you should go to that schema instance instead of non-existent table. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
This has been taken care of in #5043
