### ISSUE TITLE
Review database field for connectors

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5210]
The `database` field is quite confusing. There are two types of database sources:

- Sources whose structure is database.schema.table, e.g., Redshift, or MSSQL.
- Flat sources with schema.table , e.g., Athena, MySQL.

The first group, we are handling fine. Our Table hierarchy matches that structure so we know what to do.

However, in the second group we are complicating things unnecessarily. For example, let's review the connections for MySQL and Athena:
- [MySQL](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/services/connections/database/mysqlConnection.json#L51)
- [Athena](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/services/connections/database/athenaConnection.json#L44)

Two things not going well here:

1. We are asking for something that does not make sense (the concept of database does not exist)
1. We are describing the field in a way that users get confused: If we say that adding the field database will filter stuff in MySQL, then users will expect that database will be applied as a SchemaFilterPattern, as that is the only possible explanation for the info they see.

What ends up happening is that no matter what we put in the field database, it is just a complicated way to pass a custom name, which is not even necessary.

In this ticket, we should review the `database` field for all connectors and remove it for those which it does not need to exist. Also, test the ingestion with and without database to validate that all the data is being picked up correctly.

**Comment by pmbrull** [comment]
cc @MilanBariya

**Comment by MilanBariya** [comment]
I will do this.
