### ISSUE TITLE
Superset Service Crops a character from port

### ISSUE THREAD

**Issue by EminUZUN** [open-metadata/OpenMetadata#5227]
**Affected module**
Superset Service

**Describe the bug**
Superset service removes a character from port
normally it should be: http://xxx:8088/superset/dashboard/world_health/
but it crops to: http://xxx:808/superset/dashboard/world_health/

Probably same in sandbox environment: https://sandbox.open-metadata.org/dashboard/sample_superset.eta_predictions_performance

As mentioned in slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1653923207126059

**Comment by pmbrull** [comment]
We'll take care of this as part of this epic https://github.com/open-metadata/OpenMetadata/issues/4695. Thanks for reporting
