### ISSUE TITLE
Error when indexing Glossary Term with ampersand (&) in Elasticseaarch

### ISSUE THREAD

**Issue by filip-xmargin** [open-metadata/OpenMetadata#5231]
Steps to reproduce (version 0.10.1):
* create any entry in Glossary with ampersand in name (`Rules & Policies` in my example)
* observe following ES error in the app:

> An exception with message [Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]] was thrown while processing request.

The behavior was confirmed on two different deployments (docker compose on mysql db and  and k8s on postgres db). so most likely it is a real bug. 

Most likely, special chars need to be quoted before feeding to ES. 

![OMD-ampersand-bug](https://user-images.githubusercontent.com/95128697/171154147-e4e7c394-de7e-4c5a-a897-52c69cd57520.png)

**Comment by harshach** [comment]
@filip-xmargin indexing is working fine 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/172062836-83b24e9e-a4e6-42fd-bf23-d2200ae3e85e.png">

Searching through apis
http://localhost:8585/api/v1/search/query?q=Rules%20&%20Policies&from=0&size=10&index=glossary_search_index
<img width="942" alt="image" src="https://user-images.githubusercontent.com/38649/172062879-c63faa88-722c-4185-9671-0132d01d6d06.png">


<img width="1067" alt="image" src="https://user-images.githubusercontent.com/38649/172062888-ce09f5e8-94e4-41e0-9c04-29de0da52b31.png">


<img width="999" alt="image" src="https://user-images.githubusercontent.com/38649/172062904-5b98a02c-6617-4160-a708-00a3e3d6465c.png">

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/38649/172062921-2fd2a587-39e7-4b09-9b4d-07348d0755b7.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/38649/172062939-72f05251-763c-4c94-8f38-d163c3d3d1e8.png">
