### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'workflowConfig'

### ISSUE THREAD

**Issue by SomniVertix** [open-metadata/OpenMetadata#5239]
**Affected module**
Ingestion Framework - elasticsearch 

**Describe the bug**
Getting error when trying to install elasticsearch integration

**To Reproduce**
- stand up openmetadata on kubernetes cluster
- forward port 8585 locally
- pip3 install --upgrade pip setuptools
- pip3 install 'openmetadata-ingestion[elasticsearch]'
- Use following elasticsearch.yml:
```json
{
  "source": {
    "type": "metadata_elasticsearch",
    "serviceName": "openMetadata",
    "serviceConnection": {
      "config":{
        "type":"MetadataES",
        "includeTables": "true",
        "includeUsers": "true",
        "includeTopics": "true",
        "includeDashboards": "true",
        "limitRecords": 10
      } 
    },
    "sourceConfig":{"config":{}},
    "config":{
        "host_port": "localhost:9200",
        "username": "elastic",
        "password": "<redacted>"
    }
  },
  "sink": {
    "type": "elasticsearch",
    "config": {
      "index_tables": "true",
      "index_topics": "true",
      "index_dashboards": "true",
      "es_host": "localhost",
      "es_port": 9200
    }
  },
  "workflowConfig": {
    "openMetadataServerConfig": {
      "hostPort": "http://localhost:858/api",
      "authProvider": "no-auth"
    }
  }
}
```
- metadata ingest -c ./elasticsearch.json
![image](https://user-images.githubusercontent.com/35609960/171214718-1cdaba13-239a-45bc-9c02-a7ac588a3614.png)

**Expected behavior**
Integration should register to openmetadata

**Version:**
 - OS: Linux - exec'ed into the python docker image
 - Python version: 3.10.4
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version: pip3 install 'openmetadata-ingestion[elasticsearch]'

**Additional context**
--

**Comment by harshach** [comment]
@codingwithabhi can we throw a better error here. Looks like the json config issue.

**Comment by pmbrull** [comment]
Add this case into `parse_workflow_config_gracefully` function
