### ISSUE TITLE
Display database name and table name in activity feed. 

### ISSUE THREAD

**Issue by ha5463** [open-metadata/OpenMetadata#5240]
**Is your feature request related to a problem? Please describe.**
When a user logs into the OpenMetadata portal, the first thing they see is the All Activity feed. Each entry in the feed tells me what has happened. For e.g. Person X has updated table description. But it does not tell me for which table? In my opinion, to make meaning out of each feed, it's crucial to know atleast which table's metadata has been updated.

**Describe the solution you'd like**
Each entry in the activity feed should display the concerned table name and database name. This would help the user to make meaning out of the activity feed. Right now, id someone updates a column description, I don't get to know which table does this column belong to. Similarly for most of the updates. 

**Describe alternatives you've considered**
Haven't considered anything at the moment. But I envision this feature would really give meaning to the activity feed and delight our customers.

**Comment by trillhaa** [comment]
@vivekratnavel 

> do you want the full FQN of the table to be displayed in each feed?
Example: `sample_data.ecommerce_db.shopify.fact_line_item`

Yes.
