### ISSUE TITLE
Role policies and access control bug

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#5246]
**Affected module**
Backend

**Describe the bug**
1. When a user becomes data steward/data consumer, they are permitted to edit all assets in the catalogue. Naturally, they get policies to update all instances they find, even those belonging to another team. For example, data steward from team1 has permission to change team2's assets.
2. If we create a new role based on existing default policies (Data Steward, Data Consumer) and then change something in this new role, the existing policy is updated as well for the old role.
You change one role -> both roles are updated instantly. 

**To Reproduce**
Screenshots or steps to reproduce
![bug_report_policies](https://user-images.githubusercontent.com/60112387/171343458-7397d70a-ae33-4cc5-b651-538de6217e38.gif)

**Expected behaviour**

1. Role policies should be limited to teams and their corresponding assets. Data steward or consumer from team1 shouldn't be able to edit/update team2's assets etc. 
2. Newly created roles shouldn't be in codependency with the existing roles even if they're based on the same policy. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya can you test this out and close it.

**Comment by Sachin-chaurasiya** [comment]
This is fixed with new roles and policy structures.
