### ISSUE TITLE
Add "stop" button in ingestion (UI)

### ISSUE THREAD

**Issue by jlanka8** [open-metadata/OpenMetadata#5251]
Hi,
It would be great to add a stop button to ingestion, now there is only a run button and if, for example, you delete a working ingestion, then the pod in k8s will stay running, this causes a problem when there are a lot of deleted ingestion, there are also a lot of pods, and new dags get in queue

<img width="694" alt="image" src="https://user-images.githubusercontent.com/106686946/171438449-9b4f1433-43f7-4de2-be0f-d4a2c7b99996.png">

**Comment by vivekratnavel** [comment]
Moving this to 0.11.1 to give it some more time to design this.

**Comment by harshach** [comment]
@vivekratnavel Its just adding a button next a ingestion.
