### ISSUE TITLE
Service descriptions lost after editing

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#5269]
**Affected module**
UI

**Describe the bug**
When you add a description for a service and then add owner for it, the description disappears.

**To Reproduce**

Screenshots or steps to reproduce

![Screen Recording 2022-06-02 at 14 55 38](https://user-images.githubusercontent.com/60112387/171624204-f125a5c4-d249-4c42-8aa0-ecca61e9b21e.gif)

**Expected behavior**
Descriptions shouldn't disappear after we change an owner or update an entity. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Tonilyn** [comment]
Same for Data Quality, it seems. After we re-started DAG for a test, test's description disappeared. 
![image](https://user-images.githubusercontent.com/60112387/171639208-46364abd-b8f2-46f1-8799-a61df0b792d0.png)

**Comment by harshach** [comment]
Thanks @Tonilyn for filing.
@Sachin-chaurasiya @ShaileshParmar11 can you check if you are passing descriptions as empty strings to the backend when sending other fields through PATCH API. we should have a cypress coverage around this. We have seen in other cases where we are passing them as empty strings.
cc @vivekratnavel

**Comment by Sachin-chaurasiya** [comment]
> Same for Data Quality, it seems. After we re-started DAG for a test, test's description disappeared. ![image](https://user-images.githubusercontent.com/60112387/171639208-46364abd-b8f2-46f1-8799-a61df0b792d0.png)

Hey @pmbrull, Can you once verify this?

**Comment by Tonilyn** [comment]
@pmbrull @Sachin-chaurasiya another one for dq tests 
if you click edit test to add description and save changes, test results disappear.

**Comment by pmbrull** [comment]
> > Same for Data Quality, it seems. After we re-started DAG for a test, test's description disappeared. ![image](https://user-images.githubusercontent.com/60112387/171639208-46364abd-b8f2-46f1-8799-a61df0b792d0.png)
> 
> Hey @pmbrull, Can you once verify this?

Hi folks, I am not able to replicate this on my end 

![image](https://user-images.githubusercontent.com/35870520/171816946-3f14fcca-9b5c-4cf7-8521-8daeac735305.png)

Ran the profiler pipeline a bunch of times

**Comment by pmbrull** [comment]
> @pmbrull @Sachin-chaurasiya another one for dq tests if you click edit test to add description and save changes, test results disappear.

Thanks for reporting this as well @Tonilyn! We are working on decoupling a couple of endpoints on the backend side which should take care of this! Changes will roll out on 0.11

**Comment by pmbrull** [comment]
In any case, opened a specific issue for the test cases so that we can validate that everything is working as expected https://github.com/open-metadata/OpenMetadata/issues/5285. Thanks!
