### ISSUE TITLE
Docs: Update security section links to correct pages

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5296]
**Issue**
The security sections are not pointing to the correct pages in our docs.

https://user-images.githubusercontent.com/1051198/171961388-71ec7ed6-9258-42df-96a7-460442403fdf.mov

**Comment by ShilpaVernekar** [comment]
Thanks for bringing this to my attention @vivekratnavel 
All the links in the SSO docs have been corrected.
