### ISSUE TITLE
Add Mode connector

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#5309]
**Is your feature request related to a problem? Please describe.**
Mode is one of the popular dashboard/analytics tool. More and more users are using it and requesting OpenMetadata to add that connector. 

**Describe the solution you'd like**
Add Mode connector to OpenMetadata.
Mode has good REST API with docs here https://mode.com/developer/api-reference/introduction/

**Describe alternatives you've considered**
None

**Comment by pmbrull** [comment]
Test the full stack -> DBT + BigQuery (adding more data to the sources) + Mode dashboards + airflow lineage
