### ISSUE TITLE
UI: Show entity card in popover on hover of entity links in activity feed

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5399]
We can show a nice popover with more information about an entity instead of just showing FQN on hover in the activity feed.

<img width="1045" alt="Screen Shot 2022-06-09 at 10 30 00 AM" src="https://user-images.githubusercontent.com/1051198/172913320-4d5ff67f-0b84-4c77-94ac-6e24a74b88e7.png">

In this screen-shot, hovering over "product_events" should display a popover with entity fqn, description, owner, tags, etc. in a card format.

For reference, this is how Github does it.
<img width="608" alt="Screen Shot 2022-06-09 at 10 58 52 AM" src="https://user-images.githubusercontent.com/1051198/172913661-3846bc6a-de6e-400b-9fa3-2ce3919820ab.png">

**Comment by vivekratnavel** [comment]
@Sachin-chaurasiya Can this be closed?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Can this be closed?

No, @vivekratnavel , This is not done yet.
