### ISSUE TITLE
Broader Dashboards structure

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#5406]
**Is your feature request related to a problem? Please describe.**
Dashboards are usually more complexly nested that single page. In case of **Superset** and **Qlik Sense**, dashboards consist of pages and each page consist of charts (aka visualisations of the data), metrics and dimensions.  Currently, we can't reflect this in the Open Metadata. 
Also, some BI instruments allows users to separate their dashboards using so-called Streams (very database like).  Each team might have up to 4 streams to publish their dashboards to. 
Thus we get a hierarchical structure with several levels. 

**Describe the solution you'd like**
A more complex dashboards structure to be reflected in the Open Metadata: 

> Dashboard Service -> (opt.Stream) -> Dashboard -> Page -> Chart/Metric.

**Describe alternatives you've considered**

**Additional context**
![superset page 1](https://user-images.githubusercontent.com/60112387/173017259-1a11561c-c7d8-4ae5-a815-4735676fc45b.png)
![superset page 2](https://user-images.githubusercontent.com/60112387/173017274-c5bf2e7c-be33-475f-8652-ff2888d17148.png)

**Comment by pmbrull** [comment]
thanks for filling this issue @Tonilyn! Appreciate the effort!

We have been getting this input from the community about adding folder/page layer on the dashboards. Definitely, we will look into it.

cc @harshach

**Comment by harshach** [comment]
@pmbrull lets look into this for 0.13

**Comment by pmbrull** [comment]
let's add the page as a property for now. We will update the FQN for service.page.dashboard later on

**Comment by pmbrull** [comment]
- project is already part of the dashboards and ingested
- we'll add further details to all entities in here https://github.com/open-metadata/OpenMetadata/issues/11967
