### ISSUE TITLE
Create Generic Iceberg Source Connector

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#5448]
### Context
Ingestion of iceberg table is currently supported through the Glue source. As Iceberg tables requires the use of a metastore giving the ability to the user to define in the connector configuration which metastore they are using will allow us to support all implementation of Iceberg tables

### Solution
Leveraging the [Python API](https://py.iceberg.apache.org/) for Iceberg we would be able to leverage existing logic to fetch table metadata based.

### A.C.
- Iceberg source is available as a connector in OM

**Comment by canopenerda** [comment]
Can we expedite this feature as this is critical to our data discovery solution for iceberg based lakehouse?

**Comment by pmbrull** [comment]
hi @canopenerda, you can follow this guide https://www.youtube.com/watch?v=ZvA4wuvINFA&ab_channel=OpenMetadata to implement the connector if needed.

We have no exact ETA on when this will land. Currently any external catalogue (glue, hive) containing iceberg tables can be used for the metadata ingestion.

**Comment by pmbrull** [comment]
we can implement it via https://py.iceberg.apache.org/

**Comment by pmbrull** [comment]
let's do docs in 1.3 + implementation in 1.4

**Comment by harshach** [comment]
@IceS2 @pmbrull are we shipping this for 1.3.0?

**Comment by pmbrull** [comment]
> @IceS2 @pmbrull are we shipping this for 1.3.0?

We'll merge today
