### ISSUE TITLE
Table description overlaps with Frequently joined tables

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#5454]
**Affected module**
UI

**Describe the bug**
For long table descriptions, the description overlaps with "frequently joined tables" section.

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/173667945-75f96cb9-a781-448a-a0d4-634cd033a3a5.png)

**Expected behavior**
Description would have line break.

**Version:**
 - Chrome

**Comment by harshach** [comment]
cc @vivekratnavel

**Comment by Sachin-chaurasiya** [comment]
Hey @trillhaa, we are not able to reproduce it.
cc : @harshach 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/173740749-d5504254-8cb1-493a-b6bc-9cd381c959a0.png">

**Comment by Sachin-chaurasiya** [comment]
It is reproducible with the long link, we will fix it.

**Comment by trillhaa** [comment]
Did this already get pushed? I can still see the error?

**Comment by trillhaa** [comment]
![image](https://user-images.githubusercontent.com/102999683/173774140-52bf8d6c-cc1d-49bd-88f7-047b99c122a1.png)

**Comment by Sachin-chaurasiya** [comment]
@trillhaa, Can you take the latest pull and try?

**Comment by abcabhishek** [comment]
Hi @Sachin-chaurasiya 
Looks like this is still persisting

PFA Image
![image](https://user-images.githubusercontent.com/16971608/174057632-65bff4a2-a9a0-47a4-abe6-793e519215f3.png)

**Comment by Sachin-chaurasiya** [comment]
Hey @abcabhishek, I'm not able to reproduce it.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/174073456-05e091e2-ea9c-47d6-9651-5d521b924871.png">

**Comment by vivekratnavel** [comment]
Hi @abcabhishek, can you please state which OS and browser are you trying out?

**Comment by abcabhishek** [comment]
Hi Vivek,
I'm using Chrome 102.0.5005.115 and MacOS Monterey (12.3.1)
