### ISSUE TITLE
"Entity already exists" error while adding new user.

### ISSUE THREAD

**Issue by MilanBariya** [open-metadata/OpenMetadata#5464]
**Affected module**
Backend 

**Describe the bug**
From Ui I try to create a new user and it's giving an Entity already exists error.

**To Reproduce**
First, create a new user, and after that delete that user.
Now try to create a user with the same email which was used for a deleted.

**Expected behavior**
If we delete a user and create a new user using that deleted user's email that time it should not give an Entity already exists error.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@MilanBariya deleting the user might be a soft delete. So the user entity does existing db. @Sachin-chaurasiya @ShaileshParmar11 to confirm. We need to make sure delete and soft delete are clearly called out
cc @vivekratnavel this should be a ticket to do soft delete and hard delete we already have a mock for that

**Comment by vivekratnavel** [comment]
Just created #5474 to track it.
