### ISSUE TITLE
Creating a tag with an illegal character prevents utilizing the tagging system until manually removed

### ISSUE THREAD

**Issue by NathanM-RA** [open-metadata/OpenMetadata#5471]
**Affected module**
UI

**Describe the bug**
For reference, OpenMetadata's ElasticSearch, MySQL, and server containers are all being hosted in a Docker environment. When creating a tag in the Tag Categories section of the OpenMetadata UI, you are unable to post a tag such as "TagTest.Delimiter.|" or "TagTest.Delimiter.\". An error pops up, which is good. However, it appears that the tag is still created and added to the OpenMetadata SQL database, as the entire tagging system falls apart: You are unable to open the Tag Categories menu (displays that tagging is not currently available) and when you try to tag tables or columns, the list of available tags does not populate, meaning no tags can be applied. In the attached image, you will see the exact error that was found by pulling from the tag API. As the image states, the reason for the tagging system falling apart ends up being because a backslash in the tags was attempted to be created. And despite displaying an error, that attempted tag was still pushed to the SQL database. The bug was able to be reversed by manually entering into the CLI for the OpenMetadata MySQL Docker container and deleting the row that contains the tag containing the backslash.

**To Reproduce**

On the OpenMetadata UI, enter into the Tag Categories section under Settings (see attached image). Select to create a new tag and end the tag name with a backslash (such as "TagTest.Delimiter.\"). Upon refreshing later, the tagging system will no longer work. If you query the tags via the API, you will see that your new tag is causing the error in the SQL database.

**Expected behavior**
When an error pops up that the tag is invalid, it is expected that it is not added to the SQL tag database because it is invalid. However, it appears that it was added to the database regardless of being invalid. Both my examples with the pipe character and backslash character were present in the "tag" SQL table in the SQL container (viewed via the CLI).

**Version:**
 - OS: Windows, but containers are hosted in a Linux environment
 - Python version:
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version: I don't have this information currently; let me know if it is important for this issue.

**Additional context**
Performed using official OpenMetadata docker containers.
![OMTagBug](https://user-images.githubusercontent.com/82049463/173833555-c838487f-fff5-4315-8662-ef7186b0216c.png)
![OMTagBug2](https://user-images.githubusercontent.com/82049463/173833557-9eae86a9-afc2-476b-a7c6-f0425bd807f0.png)

**Comment by harshach** [comment]
Thanks @NathanM-RA for reporting the bug. 
cc @Sachin-chaurasiya @vivekratnavel
