### ISSUE TITLE
Can MLModel, Report, Table, Location support an extra field ?

### ISSUE THREAD

**Issue by allenhaozi** [open-metadata/OpenMetadata#5481]
In our actual scenario
We store a model on OSS
In addition to the model itself, we'll have a custom description of the model
At present, this information is difficult to express through the current MLmodel schema
So we really want to have an extra field, so that we can attach customized information through this field

**Comment by harshach** [comment]
@allenhaozi since we added custom properties support for all entities. You can define a custom property at entity level and use that to update it.
