### ISSUE TITLE
Use Column FQN when handling table joins

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5486]
We are currently sending info such as:

```
{"startDate": "2022-06-14", "dayCount": 1, "columnJoins": 
  [{"columnName": "id", "joinedWith": 
      [{"fullyQualifiedName": "test_mssql.master.dbo.orders.user_id", "joinCount": 1}, {"fullyQualifiedName": "test_mssql.master.dbo.users_view.id", "joinCount": 1}]}]}
```

And this is the information used in the python client, backend, and UI.

We should:
1. send the column FQN from the client
2. in TableRepository:getJoins, handle the col FQN instead of `String columnName = FullyQualifiedName.getColumnName(innerList.get(0));`
3. in the UI, expect the column FQN, otherwise the join info does not appear in the column description

This should fix a use case when, joining two tables by the same column name, duplicates information:

```
select
  users.id,
  users.name,
  uv.fullname
from users
join users_view uv
  on users.id = uv.id
  ;
```

**Comment by harshach** [comment]
@pmbrull do we need to handle this on backend or ingestion?

**Comment by pmbrull** [comment]
@harshach I'd say both & UI. This is the issue we saw about tables being marked as joined with themselves if we had the same column name, but that broke the UI and the info was not available there.

It might be better to move that to 0.12 and align the 3 teams

**Comment by pmbrull** [comment]
@harshach would it make sense to use EntityLink here as when handling columns in the tests?

**Comment by Sachin-chaurasiya** [comment]
Hello @pmbrull @harshach, is this issue still relevant or can we close this?
