### ISSUE TITLE
[Elastic Search] Indexes are not updating automatically

### ISSUE THREAD

**Issue by mohitdeuex** [open-metadata/OpenMetadata#5488]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend Elastic Search

**Describe the bug**
The issue is that when we perform hard delete (let's say for a table) the index for that are not updated and we can still see entry for that when we try to search and that table is also there under list of tables

**To Reproduce**
Delete any table from list of tables and try to search that table , we still see the result for that table

Screenshots or steps to reproduce

**Expected behavior**
Once we have deleted the table the indexes for that table should be automatically updated

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by abcabhishek** [comment]
Just to add onto "Describe the bug"

This also affects all subsequent tables that are being ingested into the OM Server. The tables actually get ingested and stored in MySQL but they stop getting indexed in ES
