### ISSUE TITLE
can not retrieve column description in trino

### ISSUE THREAD

**Issue by quguangyu0321** [open-metadata/OpenMetadata#5492]
**Affected module**
 Ingestion Framework

**Describe the bug**
hi team. i tried ingest metadata from trino. i found that column description does not work.

**To Reproduce**
![image](https://user-images.githubusercontent.com/61673226/174091501-b8016436-a491-48b1-a5c8-5784f8ea94bd.png)

**Expected behavior**
retrieve column description from trino

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Comment by caldeirav** [comment]
@erikerlandson it seems improving the connector as suggested here should be the right way for us to manage field level metadata as going through an additional pipeline after ingestion has a number of shortcomings (i.e. creates new version of the schema, not able to detect changes automatically, etc...). Could we consider having someone in Red Hat team improve the Trino connector based on our use-case and contribute this?

**Comment by harshach** [comment]
@erikerlandson @caldeirav let us know if anyone from your team interested in picking this up.
