### ISSUE TITLE
Support Internationalization

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5496]
**Feature**
Add support for internationalization in OpenMetada UI. We should move all the standard text displayed in Open Metadata UI to a language constants file to support multiple languages.

**Comment by Arturo-Penas-Rial** [comment]
I can help translating to Spanish language!

**Comment by mohoval** [comment]
Thanks for your efforts. 
When this feature can be added (which release)?
And does this support RTL languages?
@vivekratnavel 
@harshach

**Comment by harshach** [comment]
@mohoval we are shooting for 0.13 release slated for Oct 19th 2022

**Comment by Sachin-chaurasiya** [comment]
Duplicate of #3474
