### ISSUE TITLE
UI: Side bar doesn't show all filters in Explore tab

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#5503]
**Affected module**
UI

**Describe the bug**
Chrome, Open metadata "Explore" tab: you can't see the whole list of filters in the side bar when scaled to 100%. To see all filters you need to scale down page to 50%.

 After that, when you set tab zoom to 100% back, you can see all filters as expected. 

Macbook pro 13 inch, 2560 × 1600
Google Chrome ver.98.0.4758.102

**To Reproduce**
Screenshots or steps to reproduce

_**When scaled down to 50%:**_
<img width="233" alt="Screenshot 2022-06-17 at 13 02 11" src="https://user-images.githubusercontent.com/60112387/174277402-d03febb7-e412-4192-a075-240745b86ff0.png">

**Expected behavior**
There should be at leat a scroll bar in the side bar with filters if display resolution is too small to show all available filters.

**Version:**
 - Python version:
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hello @Tonilyn, Thanks for filing the bug.
This issue has been fixed in 0.11
