### ISSUE TITLE
UI: Show a global settings page for Admins to view/update the settings for different services such as  Slack Event Publisher, etc.

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5519]

**Comment by devyani-kaushik** [comment]
![Open Matadata Settings_1](https://user-images.githubusercontent.com/103238069/179679395-2e8af5eb-d4d3-4ee2-98fe-ed8e9eb67e4f.png)
![Open Matadat Settings_4](https://user-images.githubusercontent.com/103238069/179679402-ea494ffd-8ce9-49da-99a8-a50e7f548888.png)
![Open Matadat Settings_2](https://user-images.githubusercontent.com/103238069/179679408-602cd5d4-1648-4ba2-a41a-22e68e4e421d.png)
![Open Matadat Settings_3](https://user-images.githubusercontent.com/103238069/179679410-78cc4884-6e4a-4ab4-ad7a-5ae49cee058b.png)

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/6677
