### ISSUE TITLE
Profiler Timeout Logic is Not Working

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#5522]
**Affected module**
Profiler

**Describe the bug**
Current implementation of the timeout does not work properly when executing queries with SQL Alchemy

**To Reproduce**
Run a profiler query lasting more than 10 minutes

**Expected behavior**
By default the timeout is set at 10 minutes. The query should timeout and the session be closed once this timeout value is reached

**Additional context**
We need to investigate what is preventing SQL Alchemy from picking up the timeout logic and implement a fix

**Comment by Beetelbrox** [comment]
Hai I can work on this one!

**Comment by TeddyCr** [comment]
Thanks @Beetelbrox

**Comment by Beetelbrox** [comment]
Hai @TeddyCr finally got some time to look at the issue, opened a PR with the fix.

A couple of observations I have on the implementation:
 * The [decorator docstring & name](https://github.com/open-metadata/OpenMetadata/blob/82de3a4cc65e869d50597979fefc7b119886f6d9/ingestion/src/metadata/utils/timeout.py#L59-L65) of `cls_timeout` refer to "Decorating a class" but you're [passing an instance](https://github.com/open-metadata/OpenMetadata/blob/aae4410c93a03263c5a6ee755630a7982d4457c5/ingestion/src/metadata/orm_profiler/interfaces/sqa_profiler_interface.py#L138-L143) of the class instead and therefore only modifying the attributes of that particular object. Is the goal to decorate the class itself or its instances?
 * Why do you need to go the decorator approach to add the timeouts? IMO modifying objects at runtime makes the code more difficult to reason about especially when there is composition/inheritance & multiple files involved. It seems that the `QueryRunner` is tightly coupled to a `SQLALchemy` session too, if the decorator approach becomes too unwieldly maybe it makes sense to set timeouts on the engine/session itself via [connect_args](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.connect_args). The exact argument to pass depends on the underlying DBAPI implementation (eg which db are we pointing to) so it's a bit more work to implement the specific connectors but could result in a cleaner API. Just throwing ideas on the board.

Thanks!

**Comment by TeddyCr** [comment]
Hey @Beetelbrox, thank you for looking into this. 🙂 I have answer the questions below
- Yes it should definitely be called on the method of the instance. I think it should not modify the actual instance of the object.
- `SQAProfilerInterface` is meant to be a protocol, though, protocols are not supported in 3.7 it is instead an ABC. We are also actively working on removing association between the `ProfilerProcessor` object, the `Profiler` object and SQA. To me the association between the `QueryRunner` object and the `SQAInterface` object make sense. The `QueryRunner` object should only be associated with the `SQAInterface`. You can see that it is today somewhat associated with the `Profiler` though it should be removed soon. 
As far as the way to set timeout, we should probably look at stopping the function (vs setting the timeout on the SQA connection if it is dialect dependent). We also introduced `multithreading` recently to compute metrics -- we might look at killing the thread and raising a timeout error. https://github.com/open-metadata/OpenMetadata/blob/6fb888437a1a8304394b75a300038e5c82edfee2/ingestion/src/metadata/orm_profiler/interfaces/sqa_profiler_interface.py

**Comment by harshach** [comment]
@TeddyCr can we close this out for 0.13.1?
