### ISSUE TITLE
UI improvements 

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#5528]
Home page
- [x] reduce card bottom padding
- [x] add padding between profile thumbnails on "view older replies"
<img width="855" alt="Screenshot 2022-06-20 at 12 27 48 PM" src="https://user-images.githubusercontent.com/103238069/174556841-aadf9c3a-844b-4576-91c8-1653bfbb4b8c.png">

Explore Page 
<img width="522" alt="Screenshot 2022-06-15 at 7 39 18 PM" src="https://user-images.githubusercontent.com/103238069/174548802-e775f379-df1e-4671-9723-14dc0e1cab19.png">
- [x] bottom padding in filters is more than tab menu
- [ ] Left Column Height should have a minimum fixed height with bottom margin that is = to top margin

Manage page 
<img width="824" alt="Screenshot 2022-06-07 at 1 39 55 PM" src="https://user-images.githubusercontent.com/103238069/174548901-6718be8a-4d92-4710-9238-3e7f85a94167.png">
- [x] all text should be white

Glossary
<img width="1440" alt="Screenshot 2022-06-20 at 4 09 48 PM" src="https://user-images.githubusercontent.com/103238069/174590486-f0c67c57-ad94-4af8-943a-1a73cad7d563.png">
- [x] Left Column Height should have a minimum fixed height with bottom margin that is = to top margin
- [x] Left Margin is more than right margin
- [x] Breadcrumb font size should be 14px (currently it's 16px)
- [x] Top right buttons should be aligned with right column
- [x] Tab line should not touch the left column and should be aligned with description box
<img width="196" alt="Screenshot 2022-06-20 at 4 52 29 PM" src="https://user-images.githubusercontent.com/103238069/174591105-a59d3d58-f70a-4468-b8c5-113b79ea1a1d.png">

- [x]  Selection highlight should be edge to edge
<img width="244" alt="Screenshot 2022-06-20 at 4 55 45 PM" src="https://user-images.githubusercontent.com/103238069/174591680-6fe633ae-6620-436b-a84b-1972f3c49b29.png">

Queries Tab
<img width="1518" alt="image (5)" src="https://user-images.githubusercontent.com/103238069/174709886-8d2441ad-df38-47c6-a603-974e48ae03c7.png">
- [x] Need to fix alignments 

- [x] Reduce overall Shadow

**Comment by devyani-kaushik** [comment]
- [ ] UI is breaking on 1280 resolution
<img width="1093" alt="Screenshot 2022-06-23 at 1 15 49 PM" src="https://user-images.githubusercontent.com/103238069/175244764-428d666b-e8a1-45c0-b9c0-569b0c7541de.png">

**Comment by devyani-kaushik** [comment]
- [ ] This page shouldn't have this white background
<img width="1430" alt="Screenshot 2022-06-23 at 1 21 17 PM" src="https://user-images.githubusercontent.com/103238069/175245808-a5e809d5-9b29-49cc-9dcf-c4bdc1ee85cf.png">

- [ ] Should not have the white background
- [ ] "Delete Category" button should be in secondary button styling
- [ ] Update icon sizes to 16px (icons are too small)
<img width="1440" alt="Screenshot 2022-06-23 at 1 42 24 PM" src="https://user-images.githubusercontent.com/103238069/175250274-c11d0fbb-2bc3-42e4-a44f-36a6cf7dc7d3.png">

- [ ] Tab alignment is broken
- [ ] Remove white background
- [ ] Need to fix the alignment of left column
<img width="1440" alt="Screenshot 2022-06-23 at 1 22 46 PM" src="https://user-images.githubusercontent.com/103238069/175246207-b2d942bb-627f-4b50-96c8-d61d54133790.png">

**Comment by vivekratnavel** [comment]
- Fix the alignment of sort icon
<img width="500" alt="Screen Shot 2022-06-23 at 2 01 22 PM" src="https://user-images.githubusercontent.com/1051198/175399187-abd9f228-f976-43ef-8c2d-806331f56b28.png">
