### ISSUE TITLE
LineageRunner to handle tables with dots

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5530]
If we have a query such as: 

```
SELECT
  snow_t1.C_NAME 
FROM "PU.BLIC".SNOW_T1
;
```

LineageRunner will tell us that the table name is `pu.blic.snow_t1`, which we will interpret as db.schema.table.

We should take a look at the libs source code and fix this

**Comment by pmbrull** [comment]
before jumping into this, while we support the dot notation in the FQN we should consider if the effort is worth it based on impact. Adding you folks for visibility, but not top priority

**Comment by harshach** [comment]
closing this , lets re-open if its a common issue
