### ISSUE TITLE
Simplify BigQuery Service onboarding

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#5534]
**Is your feature request related to a problem? Please describe.**
Creating a new bigquery service is not user friendly.

**Describe the solution you'd like**
A lot of fields (project id, private key, client email ..etc) could be extracted from a GCP Service Account Key JSON file.

**Describe alternatives you've considered**
N/A
**Additional context**
![Capture d’écran 2022-06-20 à 17 27 34](https://user-images.githubusercontent.com/75131226/174635049-18c8ada7-148e-489f-ae8e-fb8688dec264.png)

**Comment by ulixius9** [comment]
Hey @haithem-souala, The bigquery service there are two ways you can pass the credentials, one is through passing the direct values like project id, private key, client email etc or one is through passing the file path of GCP Service Account Key JSON file.

select the `GCS Credentials Configuration` value as `GCS Credentials Path` to input the Service Account Key JSON file path.
![image](https://user-images.githubusercontent.com/39544459/174636671-63350e2b-55bc-405b-adef-e3d942221a24.png)

You can select

**Comment by haithem-souala** [comment]
Thanks for your quick reply.
GCS Credentials Path, that mean i should download the Key from GCP console, then upload it somewhere, and use the SA key json file URL to configure the BQ Service, i mean, i think that too much.
What about just a field where we can put the content of the SA key file or upload the key.

**Comment by ulixius9** [comment]
ok So in the `GCS Credentials Path` we are expecting a local file path so if you have downloaded in your `Downloads` folder then you can provide value as `<Path of Downloads Dir>/<Filename>.json`, I think we can improve the description here to make sure this confusion does not happen.

Also the `DATABASE` and `USERNAME` field has been removed, this will be reflected from `0.11.0` release.

**Comment by harshach** [comment]
@ulixius9 did we handle adding clear description?
