### ISSUE TITLE
Enhance Dashboard Entity

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5577]
# Context

We have been getting different inputs from the community about adding more properties and enhancing the Service hierarchy. A few examples are:
- https://github.com/open-metadata/OpenMetadata/issues/5406
- https://github.com/open-metadata/OpenMetadata/issues/3416
- https://github.com/open-metadata/OpenMetadata/issues/3412

The goal of this EPIC is to scope and track what additions can be done that are consistent among the different services

# Tasks
TBD

**Comment by harshach** [comment]
@pmbrull closing this
