### ISSUE TITLE
Ingest Databricks jobs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5592]
Review the information we can retrieve from databricks jobs and ingest them as pipeline entities

**Comment by pmbrull** [comment]
This basically means having Databricks as a Pipeline Connector as well

**Comment by harshach** [comment]
@pmbrull there is a request about adding the queries from databricks sql

**Comment by pmbrull** [comment]
hi @harshach I see, thanks. For query history we could use something like https://docs.databricks.com/sql/api/query-history.html# and manage it as a usage and lineage connector. I will open a separated issue for that and keep this one for the Pipeline Entities.

**Comment by pmbrull** [comment]
https://github.com/open-metadata/OpenMetadata/issues/7376

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/9554
