### ISSUE TITLE
Optimize filter pattern

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5602]
In the ingestion process, we can filter out entities based on their properties (e.g., name, schema, database,...).

The current approach is:
1. read all the entries to process (tables, dashboards, whatever)
2. iterate over them
3. filter what is not required based on filter patterns

This means we are retrieving data from the source that won't always be processed or useful. We should instead:
1. read entities based on filters
2. process everything coming out from the query / API call.

UPDATE: This has already been improved in the Dashboard sources

**Comment by sureshms** [comment]
@pmbrull is this for ingestion? Adding more details to the description will help. Still relevant?

**Comment by pmbrull** [comment]
Added further details in the description 🙏

**Comment by ayush-shah** [comment]
currently the approach is:
- fqn.build builds the fqn
    - which calls es
- we check filter_by_xxxx
    - conditions being:
        - if self.config.sourceConfig.config.useFqnForFiltering
            - we use fqn
        - else if self.config.sourceConfig.config.databaseFilterPattern,
            - we use the data fetched from source
instead i was suggesting:
- if self.config.sourceConfig.config.databaseFilterPattern
    - we use the data fetched from source, filter it out
- if self.config.sourceConfig.config.useFqnForFiltering
    - fqn.build -> call to es
    - filter using fqn
    
using this way, we might be able to reduce many API calls to server.

**Comment by sureshms** [comment]
@pmbrull, is this still an issue? If not, can you close this?

**Comment by pmbrull** [comment]
> @pmbrull, is this still an issue? If not, can you close this?

we still need to handle it. It requires some thought
