### ISSUE TITLE
Possibility of duplicates in Glossary terms

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#5622]
**Affected module**
UI + backend

**Describe the bug**
It is possible to create duplicate terms in Glossaries on both levels (glossary and sub-glossary). I'm honestly not sure if this is a bug, though it causes certain business ambiguity when it comes to using Business Glossary. 

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

If a term (eg, imei or client) already exists, then you shouldn't be able to create its duplicate (both in name and displayName). System must warn that such term was added before. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.10
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Tonilyn this is fixed now
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/38649/225453770-421b8bb9-f7ee-4352-aa2e-2716979f30d2.png">
