### ISSUE TITLE
UI Improvements - 0.11.0 release

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#5645]
- [x] #5648
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/38649/175782531-bef342af-5064-4b7e-9aee-843ddb075118.png">

- [x] #5649

https://user-images.githubusercontent.com/38649/175785139-2e4b43d6-8ccf-4be2-9303-a30609227abe.mov

<img width="756" alt="image" src="https://user-images.githubusercontent.com/38649/175785225-28ffd6c0-e9a6-43d0-93a5-a5c93e7f5c35.png">

- [x] Hover on the emoji and the reply should stay longer and cover the entire panel, each reply in a thread should have the entire panel and can hover to get the emoji reply button. The highlighter in the above image should be expanded its cutting over the text.
- [x] #5650

https://user-images.githubusercontent.com/38649/175794239-bf6598ba-e46d-4546-be68-8cfe6b902546.mov

- [x] Hover over any emoji it will pop up the reply , emoji shortcuts as the emoji hover action is lost . Just like Slack we should show both , keep the tooling for reply , emoji buttons available and show the emoji's users as well.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/38649/175826438-08193746-2778-465d-8ab6-016aec8302d8.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/38649/175826474-d10cd34f-27ab-4d92-8758-a67b483d3bc4.png">

- [x] #5651
<img width="853" alt="image" src="https://user-images.githubusercontent.com/38649/175826586-bf55931d-0104-4071-9fc6-77ea773ccde4.png">

**Comment by harshach** [comment]
- [ ] adding a reply misaligns the Task header 
<img width="872" alt="image" src="https://user-images.githubusercontent.com/38649/175840000-59ed097d-13fc-45ad-b2c3-5f79c79b1da4.png">

**Comment by ShaileshParmar11** [comment]
- [ ] Fix service details page for non-admin user 
- [ ] hide connection tab and manage tab for the same
@ShaileshParmar11 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71748675/175863928-3b8d1749-4f5b-4abb-99e9-362b37e81686.png">

**Comment by sureshms** [comment]
- [ ] We can change the text from "Starting following table" to "Followed table" and "Stopped following table" to "Unfollowed table" <img width="395" alt="image" src="https://user-images.githubusercontent.com/1417689/175980024-9fbdadee-ed01-49cf-81a8-66a8efcd9465.png">

**Comment by harsh-vador** [comment]
Facing alignment issues here:

<img width="347" alt="Screenshot 2022-06-29 at 12 43 28 PM" src="https://user-images.githubusercontent.com/58542468/176374821-b4268f80-6215-47b3-b53a-63c25464d0ec.png">
