### ISSUE TITLE
UI : Use Tags suggestion API to get the tags

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#5646]
Today, we use REST APIs to get the tags and show them as options while adding tags to entity and entity fields.

As part of this PR https://github.com/open-metadata/OpenMetadata/pull/5573, the backend has added support for tags suggestion API, so on UI we should replace REST API calls with this suggestion API.

**Comment by Sachin-chaurasiya** [comment]
@harshach , Regarding this issue, we can have the frontend changes, but there is one issue that tags and index get created simultaneously and some cypress tests will fail.
I have made the changes to this PR https://github.com/open-metadata/OpenMetadata/pull/5912 but closed it as cypress tests were failing and lost track of it.

**Comment by harshach** [comment]
@Sachin-chaurasiya can we close this out. For tests you can create a new tag and tag categories and test it with that? or invoke the elasticsearch re-index all
