### ISSUE TITLE
UI: fix hover over for entity cards

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#5649]
- Hover on the emoji and the reply should stay longer and cover the entire panel, each reply in a thread should have the entire panel and can hover to get the emoji reply button. The highlighter in the above image should be expanded its cutting over the text.

https://user-images.githubusercontent.com/38649/175785139-2e4b43d6-8ccf-4be2-9303-a30609227abe.mov

<img width="756" alt="image" src="https://user-images.githubusercontent.com/38649/175785225-28ffd6c0-e9a6-43d0-93a5-a5c93e7f5c35.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Increase the Size of the hover box and icons inside it.
<img width="245" alt="image" src="https://user-images.githubusercontent.com/59080942/175895372-2b9e818a-d9ef-4f98-adeb-23b27eba6efe.png">

- [ ] Increase the Size of the emoji's
<img width="181" alt="image" src="https://user-images.githubusercontent.com/59080942/175895435-16f9735a-b809-4757-b9e9-ca8bd578a11e.png">
