### ISSUE TITLE
Service level navigation shows there are no databases even when there are databases 

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#57]
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/1417689/128422859-71574692-7fc4-46e0-8c29-b1ea8c1581f8.png">

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/1417689/128422898-7edfc426-ca8d-41d5-afc3-0f75b036a6d1.png">

@sanketbambulkar we need to come up with standard pages when there is no data to show and fonts etc..

**Comment by Sachin-chaurasiya** [comment]
This is fixed with #235
