### ISSUE TITLE
Support multiple ingestion jobs for databases in one database service

### ISSUE THREAD

**Issue by TheDragonWarrior** [open-metadata/OpenMetadata#5719]
**Is your feature request related to a problem? Please describe.**
Currently for one database service, only one ingestion job could be created for each type of the ingestion (metadata, profiler). However in practice, we might need to create different metadata ingestion jobs for different databases in one database service. The jobs might be different in schedules, etc. 

**Describe the solution you'd like**
On the UI, when user create the metadata ingestion job, it is better to have an filed to specify the database info, (one or multiple databases.) Then this additional information is saved in the ingestion pipeline entity in database.

**Describe alternatives you've considered**
currently the workaround is to create sperate database service for each database.

**Additional context**

**Comment by harshach** [comment]
linking the same issue here https://github.com/open-metadata/OpenMetadata/issues/6725

**Comment by harshach** [comment]
@Sachin-chaurasiya I think we are only restricting this from the UI. Lets remove this and show the "Add Metadata Ingestion" from dropdown.

**Comment by MichaelTiemannOSC** [comment]
We have the same problem.  For our case, we ask people to write data pipelines to ingest data into Trino.  In the very near future we will also federate data using Trino.  Our hierarchy is:

- Trino Catalog (a large heavyweight thing, one per cluster that serves all users of that cluster, all schema, and all tables)
- Trino Schemas (developers prototype in shared or personal sandboxes, and for production, each data pipeline lives in its own schema, which may contain multiple tables).
- Trino Tables (the columns and rows of ingested data)

We are using DBT to create table-level and column-level metadata.  We have built about a dozen ingestion pipelines, each of which has its own source data, dependencies on other tables and federation, and metadata.  We want to provide a means for data pipeline developers to make metadata production and ingestion part of the data pipeline.

It would be most convenient if we could hand catalogs and manifests on a per-pipeline basis to OM and let OM aggregate the tasks to create a totality of metadata information across all pipelines (so a user can see the universe of pipelines feeding our database service from a single perspective).

A clunky alternative would be to manually collect that manifest and catalog files, merge all the json dictionaries, thereby manually performing the aggregation ourselves (before handing to OM).

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya I think we are only restricting this from the UI. Lets remove this and show the "Add Metadata Ingestion" from dropdown.

Sure @harshach.

**Comment by pmbrull** [comment]
Here we'll need to handle how we mark tables as deleted on the Ingestion side, using the necessary filtering mechanisms to not flag tables not incoming from the source due to input parameters
