### ISSUE TITLE
UI Feedbacks 0.11.0 for glossary

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#5732]
- [x] We can change the text from "Starting following table" to "Followed table" and "Stopped following table" to "Unfollowed table" <img width="395" alt="image" src="https://user-images.githubusercontent.com/1417689/175980024-9fbdadee-ed01-49cf-81a8-66a8efcd9465.png">

- [x] Edit button has inconsistent styling in Glossary page. In the following, do we need Pencil to be in purple color or can we use the same styling as the dataset details page? Also, do we need the text `Edit`?  PR #5706
<img width="105" alt="image" src="https://user-images.githubusercontent.com/1417689/175980949-bf405e84-f9fd-4258-bf07-d90ec5f33c5f.png">

- [ ] Glossary terms details page has too many boxes. Can we make this consistent with the data asset details page where the description is stated right below the asset details without a separate `Description` header etc? Also, we can lose many of these boxes and merge it. <img width="1224" alt="image" src="https://user-images.githubusercontent.com/1417689/175986865-959a2606-2585-4359-91a0-8c998bbae8b1.png">
- [ ] Why include Add Related Term button etc. and not just use Pencil for editing?
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1417689/175987157-1189c8d8-8d52-43f0-b568-ab85f33d8d8e.png">

- [x] Color for the last term seems to be off compared to higher-level terms  
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1417689/175987629-b92dd932-7487-4c68-ab00-df890b6b0612.png"> 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1417689/175987783-1558912a-6d45-449c-b6a7-15ac731270f5.png">

- [ ] Tags and Glossaries are not consistent with each other 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/1417689/175988223-ddd5bd46-e4ad-478e-ac4a-c4c2681bc256.png"> 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/1417689/175988303-9c7b4a0b-8ac1-425c-afb3-d5d244a28646.png">

_Originally posted by @sureshms in https://github.com/open-metadata/OpenMetadata/issues/5645#issuecomment-1167516060_

**Comment by ShaileshParmar11** [comment]
some of the above issues are already fixed but the rest of the other issues will be taken care of in 0.11.1
cc @harshach @vivekratnavel @sureshms

**Comment by chirag-madlani** [comment]
Closed as `0.11.0` is shipped and we are working on `0.12.0`
UI tracking for 0.12.0 is #6701
