### ISSUE TITLE
Activity feed bug for tables with similar name

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#5739]
**Affected module**
Backend 

**Describe the bug** 
I've two identical tables in glue `cloudfront_logs` and `cloudfront_logs2` When I update the comment in `cloudfront_logs2`, Activity feed for `cloudfront_logs` also gets updated

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39544459/176415773-72b0c7ea-6650-4336-bdc1-b1177176e285.png">

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/39544459/176415810-11dd8ffa-bae6-47ef-a307-9fc3723bd183.png">

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/39544459/176415878-619b015e-2cee-4e9c-9853-056c7739eae8.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/39544459/176416169-9561aedc-de59-4078-9314-0844e4ca3562.png">

**Comment by vivekratnavel** [comment]
This is a good catch. Thank you for reporting this bug @ulixius9!
