### ISSUE TITLE
Frequently Joined Tables and Column level lineage not working for Redshift connecter.

### ISSUE THREAD

**Issue by MilanBariya** [open-metadata/OpenMetadata#5745]
**Affected module**
 Ingestion Framework

**Describe the bug**
If we use any join queries that time Frequently Joined Tables should appear. also column-level lineage.

**To Reproduce**
Query example for join tables: " select listing.listid, sales.salesid, sales.sellerid, sales.commission
from sales join listing
on sales.listid=listing.listid and sales.eventid=listing.eventid
where listing.listid between 1 and 5;"
for more join query : https://docs.aws.amazon.com/redshift/latest/dg/r_Join_examples.html

**Expected behavior**
Frequently Joined Tables and Column level lineage should appear.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
joins work well on my end after https://github.com/open-metadata/OpenMetadata/pull/5749. The lineage we'll need to double-check

**Comment by MilanBariya** [comment]
Column level lineage  and  Frequently Joined Tables both working
<img width="1440" alt="Screenshot 2022-06-30 at 12 21 22 PM" src="https://user-images.githubusercontent.com/52292922/176620583-907ff69e-3790-4282-859b-9bb3acdba7c6.png">

<img width="1440" alt="Screenshot 2022-06-30 at 12 19 52 PM" src="https://user-images.githubusercontent.com/52292922/176620623-2a9f2023-bf2d-4297-8662-fdbde686bec0.png">
.
