### ISSUE TITLE
Query for Postgres 9.6.7

### ISSUE THREAD

**Issue by jlanka8** [open-metadata/OpenMetadata#5794]
**Affected module**
Ingestion Framework

**Describe the bug**
While scanning the Postgresql source (OMD v0.10.1), I see some errors
`[2022-06-29 14:53:48] ERROR    {OMetaAPI:sql_source:362} - current transaction is aborted, commands ignored until end of transaction block`. Finally in OMD, I can't see all the schemas and tables that are seen in the Dbeaver client.

[slack thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1656509729372469)
**To Reproduce**
<img width="193" alt="image" src="https://user-images.githubusercontent.com/106686946/176650698-f03e7ad9-3483-436b-9f03-71f64b3092e8.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/106686946/176650841-fdc962da-5354-4d30-8749-4e682ed91f80.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/106686946/176650884-25dc33d7-5fc8-4aeb-9f5f-8925a0d17d26.png">

**Expected behavior**
successful scan for all objects

**Version:**
 - Postgres 9.6.7
 - OpenMetadata version: 0.10.1

**Comment by pmbrull** [comment]
hi @jlanka8, after reviewing this issue, we noticed that the postgres version you are sharing is not supported anymore (https://www.postgresql.org/support/versioning/). Therefore, we are not going to add compatibility here, sorry about that.

Thanks
