### ISSUE TITLE
Joining open team gives permission error to normal user

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#5823]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Joining open team gives permission error to normal user

**To Reproduce**

Screenshots or steps to reproduce

https://user-images.githubusercontent.com/71748675/176916118-d02d6b44-6cee-4a44-9a13-cff89106ee79.mov

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
@open-metadata/backend

**Comment by sureshms** [comment]
@ShaileshParmar11 is this still a problem?

**Comment by ShaileshParmar11** [comment]
I'll check and update the status

**Comment by ShaileshParmar11** [comment]
@sureshms I have tried with sandbox beta but I ran into a bunch of errors, it might be due to a new policy thing! It is still a working progress from the UI side! ill test it out once the implementation of the policy is done!

**Comment by harshach** [comment]
@ShaileshParmar11 please check and close it out cc @Sachin-chaurasiya

**Comment by harshach** [comment]
@ShaileshParmar11 closing this as fixe
