### ISSUE TITLE
Improve Iceberg Data Types mapping to OM

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#5830]
## Context
Some iceberg timestamp are not fully mapped to types in OM. For example timestamp with and without timezone are currently not distinguished.

## A.C.
- Iceberg types are fully mapped to OM types

**Comment by TeddyCr** [comment]
We are currently supporting Iceberg tables through AWS Glue Catalog. Glue does not have a specification for timestamp with or without time zone -- onlye `timestamp`. Timestamp values will be displayed in UTC unless time zone is specified [here](https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg.html).

From what I see, as we are reading types directly from Glue, for now, there is no information allowing us to distinguish timestamp that could carry time zone information

**Comment by pmbrull** [comment]
not getting any response from the community user as of now. We'll close it due to lack of details. We can reopen it when needed

**Comment by TheFu527** [comment]
Iceberg's schemas are explained here: https://iceberg.apache.org/docs/latest/schemas/
We can see that it has two kinds of timestamps. When I'm using Iceberg there is no registration on OM via AWS Glue Catalog. Instead, I directly call the OM's RESTFul API for Table registration. At this time, it is necessary to distinguish between these two timestamps.

**Comment by TeddyCr** [comment]
@TheFu527 should be a simple fix -- adding timestampz type in the `dataType`. We'll try to ship it in 0.12.0
