### ISSUE TITLE
Test Suite Tab in Tables

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5833]
Based on https://github.com/open-metadata/OpenMetadata/issues/4652

- After https://github.com/open-metadata/OpenMetadata/issues/5832

Prepare a new Tab in the Table view to handle Tests Suites for that table and a new global page view from settings

![image](https://user-images.githubusercontent.com/35870520/177187961-166eb95d-4810-4a37-a283-1fa0d5878163.png)

**Comment by Sachin-chaurasiya** [comment]
@pmbrull , is this relevant anymore? or we can close it?

**Comment by pmbrull** [comment]
let's kill this one, all new mocks are already in place. Thanks for flagging
