### ISSUE TITLE
Fix migrate script

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5841]
We need to fix the `migrate.py` script (when doing the search on table, `get(name)` instead of `get(table)`) for both main and 0.10.4.

After fixing on 0.10.4, let's release a new patch package with the fix

**Comment by pmbrull** [comment]
@ulixius9 merged the PR to 0.10.4, I think we are missing the fix on main

**Comment by ulixius9** [comment]
@pmbrull pere on [main](https://github.com/open-metadata/OpenMetadata/blob/421eca4f3169765d9c0b6f526b6b8c20942b5362/ingestion/src/metadata/ingestion/bulksink/migrate.py#L180) we are already pointing to `name` instead of `table`
