### ISSUE TITLE
Deleting the Tier tag category causes UI errors

### ISSUE THREAD

**Issue by mosiac1** [open-metadata/OpenMetadata#5849]
**Affected module**

UI, maybe backend.

**Describe the bug**

After deleting the default "Tier" tag category, an error with the text "tagCategory instance for Tier not found" will keep poping up (as a notification in the top left corner) for various pages where Tier tags would normally appear: `/explore`, `/table/<fqn>/manage`. 
On the `/explore` page, on the left pane, the Tier filter still appears even if the Tier category has been deleted.

**To Reproduce**

Run the docker image and sample data ingestion. Delete the "Tier" tag category.

**Expected behavior**

Tier being pushed as a "critical" tag is not ideal - users should be able to decide what tags are important in their organization.
This can be a good opportunity to rethink Tiers and how other tag categories can be given more or less importance.

**Version:**
 - OS: WSL2 on Windows10 running Ubuntu 18 - Docker on Windows
 - OpenMetadata version: 0.11.0

**Comment by chirag-madlani** [comment]
@harshach Need to discuss this

**Comment by harshach** [comment]
@chirag-madlani @ShaileshParmar11 deleting system tags will not be allowed, Users can edit and change the display name of it. 
cc @sureshms

**Comment by ShaileshParmar11** [comment]
UI changes are pushed in PR #8703

**Comment by sureshms** [comment]
Tier tags are system tags. Whether an organization uses it or not, many of OpenMetadata feature uses tiering information in various features. Given system tags can't be deleted, this issue should not occur. Marking as closed.
