### ISSUE TITLE
UI: Show open tasks and conversations count always

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5868]
**Feature**
Currently, the tasks count is shown only on hover on any column. This should be shown always for the user to know which columns have open tasks or conversations

**Comment by chirag-madlani** [comment]
As discussed with @harshach @vivekratnavel @Sachin-chaurasiya @devyani-kaushik 
We will not modify existing behaviour for count and revisit only if user found some difficulty with UX.
