### ISSUE TITLE
Docker compose file for Postgres deployment

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5872]
**Feature**
Currently, we only publish a docker-compose.yml file with mysql and getting a postgres deployment is not straightforward. It would be great to have separate docker compose for mysql and Postgres deployments.

**Describe the task**

- [x] Create a new docker compose file with Postgres as the database for OM server.
- [x] Add the database env variables for OM server 
```
      DB_DRIVER_CLASS: ${DB_DRIVER_CLASS:-org.postgresql.Driver}
      DB_SCHEME: ${DB_SCHEME:-postgresql}
      DB_USE_SSL: ${DB_USE_SSL:-false}
      MYSQL_USER: ${MYSQL_USER:-postgres}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD:-""}
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_PORT: ${MYSQL_PORT:-5432}
```
- [ ] Change the variables to generic instead of MYSQL in both docker compose and openmetadata.yaml file

**Comment by akash-jain-10** [comment]
Adding another task here - 
- [ ] Ingestion Container Database connection string to be updated to use postgres

**Comment by vivekratnavel** [comment]
cc @akash-jain-10 @harshach

**Comment by haithem-souala** [comment]
Hey,

I don't think maintaining 2 separate docker composes files is a good idea, the best scenario, 1 docker compose file where Postgres is the default option.

**Comment by haithem-souala** [comment]
Same for helm chart.
