### ISSUE TITLE
Cannot create Location by Java Client

### ISSUE THREAD

**Issue by TheFu527** [open-metadata/OpenMetadata#5875]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend.
**Describe the bug**
When I use the Java Client:
```Java
        <dependency>
            <groupId>org.open-metadata</groupId>
            <artifactId>openmetadata-java-client</artifactId>
            <version>0.11.1</version>
        </dependency>
```
to create location, it responsed 400:
```Json
{
	"code": 400,
	"message": "Unrecognized field \"extension\" (class org.openmetadata.catalog.api.data.CreateLocation), not marked as ignorable (8 known properties: \"owner\", \"path\", \"tags\", \"name\", \"description\", \"displayName\", \"locationType\", \"service\"])\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 56] (through reference chain: org.openmetadata.catalog.api.data.CreateLocation[\"extension\"])"
}
```

**To Reproduce**

Screenshots or steps to reproduce
```Java
CreateLocation createLocation = new CreateLocation();
Location location = locationsApi.createLocation(createLocation);
```

**Expected behavior**

Response 200, and get the location I created.

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohitdeuex** [comment]
@TheFu527  Closing this , need to use OpenMetadata or we can add apiClient.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL); in case we want to build the client manually do it manually
