### ISSUE TITLE
Improve Profiler Metrics Display

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#5882]
With the addition of the median as a metric to the column profile we need to scroll within the cell to see all the metrics. Additionally, thousands separator (e.g. `1,000`) should be used to display large number.

![Screenshot 2022-07-06 at 10 54 59 AM](https://user-images.githubusercontent.com/13626425/177511640-0645c5ca-7f2d-4a01-b11b-f824428e6d31.png)

**Comment by Sachin-chaurasiya** [comment]
Closing this as we will be having a whole new UI.
