### ISSUE TITLE
UI: Add options to reactivate or permanently delete a soft deleted user or team

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5893]
**Feature**
Add options to reactivate or permanently delete a soft deleted user or team

**Describe the task**

https://user-images.githubusercontent.com/1051198/177607761-c5c9c628-5689-4761-8c21-4c2d51900da4.mov

There is no option to manage a soft-deleted user or team.

**Comment by ShaileshParmar11** [comment]
Need backend support, re-active teams, for user we already support reactivation via put api

**Comment by ShaileshParmar11** [comment]
We need to give try to `PUT` API for reactivating teams @Ashish8689
