### ISSUE TITLE
Extend API to include the ability to only pull metadata that contains a specific tag

### ISSUE THREAD

**Issue by NathanM-RA** [open-metadata/OpenMetadata#5895]
**Is your feature request related to a problem? Please describe.**
One of the most beneficial parts of OpenMetadata I have found is the ability to tag metadata and retrieve metadata via the API. However, unless I missed a specific API option, retrieving only metadata containing a specific tag requires some programmatic work. My current approach to get JSON/a dictionary of metadata with a specific tag requires me to first call the /api/v1/databases endpoint and then pass each qualified name of each database as a parameter to the /api/v1/tables endpoint with the "tags" fields parameter enabled. For each table returned, I then have to programmatically check the "tags" section of each table in the JSON to confirm if the metadata column contains the tag or not. Doing so is a tedious and time consuming process, especially considering I have about 6 databases with multiple tables in each.

**Describe the solution you'd like**
If the OpenMetadata API was extended to include an additional "tags" endpoint that returns JSON of **only** metadata containing a specific tag across all tables/databases or even just across a single table, then that would be a great improvement from a programmatic approach.

**Describe alternatives you've considered**
Alternatives were detailed in the initial problem explanation. Also, I checked all the GET endpoints for databases, tables, and tags in the API. 

**Additional context**
If you have any questions about what exactly or why exactly I am making this request, I am happy to answer! Thank you!

**Comment by sureshms** [comment]
This can be done using search APIs. @harshach can provide more details on the OpenMetadata #support slack channel. Closing this for now.
