### ISSUE TITLE
Allow tag names to be 64 chars in length

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#5902]
**Feature**
Add feature issue reference

**Describe the task**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/38649/177682824-a59f1df7-3585-4ea3-9a78-4250dc85ac09.png">

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/6367
