### ISSUE TITLE
Define base elements

### ISSUE THREAD

**Issue by Arturo-Penas-Rial** [open-metadata/OpenMetadata#5935]
Define base elements (abstract definition independent of their instance in databases). These elements are special because they allow you to define policies in an abstract dictionary as a priority or secure source of data and from where the changes are taken as valid. For example, we could use the glossary to define these terms or base elements, and then link them to instances of different data sources where they are represented.

**Comment by pmbrull** [comment]
Hi @Arturo-Penas-Rial , as discussed, this process of defining and applying data validation can be achieved via Glossaries and Data Quality Tests
