### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by Arturo-Penas-Rial** [open-metadata/OpenMetadata#5936]
It is necessary to be able to define aliases to the data that is ingested, since in different contexts the same base elements (see 1) can have different names and descriptions. It is essential to be able to map synonymous (semantically analogous) fields, without having to change the database schemas to unify those references. In short, the idea is to have a mapping mechanism from one field to one or multiple aliases. For example, we could have in different data sources different fields that mean the same, so it is convenient to be able to define what the base data is and what the aliases are, or derived references.

**Comment by pmbrull** [comment]
Hi @Arturo-Penas-Rial, as discussed, defining glossaries and terms can achieve what you are looking for here. Applying those terms as tags can help align data that relates to the same elements
