### ISSUE TITLE
Define value domains / format masks

### ISSUE THREAD

**Issue by Arturo-Penas-Rial** [open-metadata/OpenMetadata#5937]
In the management of metadata, the need to define domains is frequent (abstract types), not only for basic data types but for range or list of values, for example, the data "sex" can be represented as a number, but not always the range of values and their significance are consistently modeled in different databases. Therefore, it is convenient to be able to model which data set is valid and even format masks at the level of each field.

**Comment by pmbrull** [comment]
Hi @Arturo-Penas-Rial , adding Data Quality Tests can help you validate that the fields are following the structure that you expect
