### ISSUE TITLE
Allow "login" without having to integrate with an external active directory.

### ISSUE THREAD

**Issue by Arturo-Penas-Rial** [open-metadata/OpenMetadata#5938]

**Comment by pmbrull** [comment]
this will be solved in https://github.com/open-metadata/OpenMetadata/issues/6894

**Comment by sureshms** [comment]
@harshach is this resolved with 0.12?

**Comment by harshach** [comment]
only backend, UI will be landing in 0.12.1. We have a duplicate ticket https://github.com/open-metadata/OpenMetadata/issues/6894 . Closing this. @Arturo-Penas-Rial please follow the updates in #6894
