### ISSUE TITLE
Reindex ES directly from UI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5952]
From some conversations with users, plus having to ask usually to reindex data, it would be interesting to have a quick way to get this done via the UI.

We could prepare an endpoint that runs the DAG from Airflow REST by passing which elements to clean, and if we need to recreate the indexes or not.

**Comment by harshach** [comment]
@pmbrull planning on doing it directly from backend.

**Comment by harshach** [comment]
@mohitdeuex it would be good to have this with in the backend instead of a pipeline deployment. We have all the logic in the backend we can reuse and list each entity to index them. 
We should use bulk api of ES to do this.
