### ISSUE TITLE
Not all teams are displayed

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#5976]
**Affected module**
UI

**Describe the bug**
We have 35 teams on our OM verison. When manually creating a user or when a user tries to register for the first time, not all of our teams are displayed but just the first 10. It's still possible to search for the other 25 teams and add the user to these, but they don't show up in the drill down.

**To Reproduce**
![image (6)](https://user-images.githubusercontent.com/102999683/178065319-5cfd548c-3adc-49e7-a6db-538dd88e3dba.png)

**Expected behavior**
All teams are displayed

**Version:**
 - OS: Microsoft, Chrome
 - OpenMetadata version: 0.11.0

**Comment by harshach** [comment]
@chirag-madlani is this the same issue that we noticed?

**Comment by chirag-madlani** [comment]
@harshach No it's slightly different. It's mostly due to pagination. We can discuss this and fix it.

**Comment by chirag-madlani** [comment]
Fixed with: https://github.com/open-metadata/OpenMetadata/pull/6156

**Comment by chirag-madlani** [comment]
@trillhaa We won't be pulling all the options instead we will show first 10 and allow user to search over teams. Same instructions added to the field: Fix added in `0.11.3`

**Comment by trillhaa** [comment]
Why would you only show top 10? Can we at least add remaining on subsequent pages? Some users might not know how we named their team and then they won't find it.

**Comment by harshach** [comment]
@trillhaa can you give us more details here. What you mean show only 10? we are showing limited results and with the option of user searching. If they do not know what to search how would they pick? as you are saying they don't know what the team is
if you have 100 teams displaying all of them in a select box is bad UX one needs to search anyway to filter out. What you mean by adding subsequent pages?

**Comment by harshach** [comment]
@chirag-madlani 
![](https://miro.medium.com/max/1400/1*j80PcvZzQFwuyH0RSdMgrw.gif)

**Comment by trillhaa** [comment]
A `View All` option at the end would be great.

**Comment by chirag-madlani** [comment]
@trillhaa We will work on "Show all" option available.

CC: @harshach

**Comment by chirag-madlani** [comment]
We are showing all the teams as options in `0.11.4` hence closing this issue.
