### ISSUE TITLE
Search Filters should be configurable

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#5979]
**Is your feature request related to a problem? Please describe.**
Some categories in search filters are not relevant and don't add value (e.g. there is a single attribute for that category). 

![image](https://user-images.githubusercontent.com/102999683/178068510-a53e933b-a490-4e4d-8af8-70a4221be9ef.png)

**Describe the solution you'd like**
Admins should be able to configure which search filters should be displayed and which search filters should not be displayed.

**Additional context**
Discussed with Harsha on 7/7

**Comment by sureshms** [comment]
With 1.1, the search filter has been reworked.  Closing as this is no longer relevant.
