### ISSUE TITLE
Ingest TBLPROPERTIES and DDL

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5996]
While researching on fetching tags from Trino https://github.com/open-metadata/OpenMetadata/issues/5374, one train of thought was that although Trino did not have Tags per se (at least not the same concept as BQ or Snowflake tags), some connectors supported specific PROPERTIES.

However, these properties are usually more related to the generic TBLPROPERTIES options (such as format, serde...) that services such as Hive support.

Then, we'll close out the Trino Tags issue, but open this follow-up issue in case we would want to get TBLPROPERTIES and DDL information about the tables.

Another source with added information that we can ingest is Databricks: 
![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/0aa17b91-0cb6-4c7b-96ac-a9422b743095)

**Comment by harshach** [comment]
@pmbrull lets check if we want to do anything here for 0.13 release

**Comment by pmbrull** [comment]
marking it as a P2. It might be interesting to see how the table was created in a separated tab
