### ISSUE TITLE
Pass clean 'name' to Airflow ingestion pipeline

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#6012]
**Is your feature request related to a problem? Please describe.**
While OMD supports more than alphanumeric in OM names, Airflow is more limited. Thus, when you create a database service entity using special characters for `name` value, ingestion fails with the following error: `The key (some service and special characters there) has to be made of alphanumeric characters, dashes, dots and underscores exclusively.`

**Describe the solution you'd like**
A patch on OM end to clean the service name when creating the DAG, so that Airflow gets it without restricted characters.

**Describe alternatives you've considered**
Try to patch it directly through database records which may eventually lead to data loss and broken entity relationships. 

**Additional context**
Initial thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1657539503309069

**Comment by pmbrull** [comment]
@harshach I am wondering if we could do a cleaning directly on Airflow REST as well when deploying the pipeline

**Comment by harshach** [comment]
@pmbrull we are allowing white spaces in service names from ingestion framework. Need to be consistent everywhere.
