### ISSUE TITLE
Rename Elasticsearch environment variable to avoid period character

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#6013]
Azure won't allow an environment variable with a period which means that `discovery.type=single-node` in `docker-compose.yml` causes a failure.

Someone reported it here https://github.com/elastic/elasticsearch/issues/74036 and a fix is merged at https://github.com/elastic/elasticsearch/pull/76192.  The merged PR says it's been backported to 7.x.

The fix appears to be use `ES_SETTING_DISCOVERY_TYPE=single-node` to replace `discovery.type=single-node`, it does the same thing but complies with Azure naming rules.

**Comment by sfirke** [comment]
Ah I see where it lists 7.15, 7.16 etc.  Okay, maybe not an option then.

I've given up on the Azure Container Instances workflow where this was a problem, so it no longer personally affects me.  I'll be deploying OpenMetadata next month via `docker compose` on a VM.

**Comment by pmbrull** [comment]
Thank you both 🙏 

@akash-jain-10 we might want to document this limitation. We can close this afterwards

**Comment by akash-jain-10** [comment]
Yes! I will add a documentation note on docker section regarding elasticsearch and azure and link to this Issue ticket for reference!

**Comment by harshach** [comment]
@akash-jain-10 any update on this?
