### ISSUE TITLE
Make Activity Feed Configurable

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#6014]
**Is your feature request related to a problem? Please describe.**
The activity feed is very noisy. Not every notification is worth posting on the activity feed. 
For example, not every user needs to know that some other user has followed a table. The feed becomes very cluttered (see below)

**Describe the solution you'd like**
Classify all activities and let admins configure which notifications should appear on the feed.

- Activity Classification: Description Update, Follow, Mentions,...
- Which ones to see? Options: All, my teams, only my own

![image](https://user-images.githubusercontent.com/102999683/178366246-63df5f45-6862-45ad-b5dd-d18f07b69424.png)

**Comment by harshach** [comment]
@vivekratnavel, we should make this a generic filter that can be applied to the activity feed, slack, and webhook filtering.
![image](https://user-images.githubusercontent.com/38649/178811459-2337261b-4b7a-4f12-82f7-c73d3e12909b.png)

**Comment by trillhaa** [comment]
Will this be part of 0.12 release?

**Comment by harshach** [comment]
@trillhaa yes

**Comment by mohitdeuex** [comment]
Added for 0.12
