### ISSUE TITLE
Unable to search for users

### ISSUE THREAD

**Issue by jlanka8** [open-metadata/OpenMetadata#6051]
**Affected module**
backend

**Describe the bug**
I can't search for users, though they are in OpenMetadata and I can see them.

**To Reproduce**

more details in the beeline channel

**Expected behavior**
Successful search

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
Fixed in `0.11.1`
