### ISSUE TITLE
[AWS][Websocket] Unable to connect to Server sand open a WebSocket connection

### ISSUE THREAD

**Issue by mohitdeuex** [open-metadata/OpenMetadata#6056]
**Affected module**
AWS ALB configuration

**Describe the bug**
Currently the WebSocket connection is not opened due to request routed through ALB

**To Reproduce**
On homepage we try to connect to Server with WebSocket for sandbox beta , we get 400 and the connection fails

**Expected behavior**
We need to be able to open WebSocket connection

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohitdeuex** [comment]
done

**Comment by Vj-L** [comment]
We have setup the ALB for both the Environments
