### ISSUE TITLE
Unable to add pipeline as edge for topic, dashboard and mlModel

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#6065]
Context issue: UI - Handle Pipeline Lineage as an Edge Transformation [#5653](https://github.com/open-metadata/OpenMetadata/issues/5653)

WIP PR:- https://github.com/open-metadata/OpenMetadata/pull/5891

for re-produce please checkout the above branch!

Payload:- 
```
{
    "description": "string",
    "edge": {
        "description": "string",
        "fromEntity": {
            "id": "c9f6a2f3-e2e1-4758-b240-575d16f0b042",
            "type": "table"
        },
        "lineageDetails": {
            "pipeline": {
                "id": "f416c39d-48bd-4b6b-9f0b-8835b1ed7b2e",
                "type": "pipeline"
            },
            "sqlQuery": "string"
        },
        "toEntity": {
            "id": "ddf205d7-b7c4-447d-9011-b65dddaf3da3",
            "type": "dashboard"
        }
    }
}
```

Response:- 
```
{"code":400,"message":"Column level lineage is only allowed between two tables."}
```

expected:-
This error should be thrown only when there is `columnLineage` field/data is pass

**Comment by harshach** [comment]
pipelines are only between table -> table. However we may have pipeline object coming in for topic in future.
For now we can just say in the UI pipeline can only added between table -> table

**Comment by sureshms** [comment]
@harshach I am going to close this for now. As newer entities with columns come in (for example Topic as you said), we can create a new issue.
