### ISSUE TITLE
UI: Explore page tables total count on tab is wrong

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#607]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/38649/135173077-71bcc17c-894c-45d2-b987-6563a108b363.png">

There are around 45k tables in total
<img width="848" alt="image" src="https://user-images.githubusercontent.com/38649/135173132-0d5f7c65-5aff-4a6b-a457-9f29ca46eb59.png">

Similarly on the Explore card
<img width="848" alt="image" src="https://user-images.githubusercontent.com/38649/135173164-15a95ddb-2021-427e-8d1a-85aeac59cdd3.png">

it looks like we are making search calls with limit set to 10000, hence we are not getting total count?

**Comment by harshach** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/38649/135173262-fd968279-8755-4a29-bf54-1f7ef09e83a0.png">

**Comment by harshach** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/38649/135173298-f5fc5eb9-c821-4a96-9485-b9adb0228db1.png">

**Comment by Sachin-chaurasiya** [comment]
@harshach  we are making calls like this.

http://localhost:3000/api/v1/search/query?q=*&from=0&size=0&sort_field=last_updated_timestamp&sort_order=desc&index=table_search_index

Same thing for other indexes as well.

can you share the response you are getting?
