### ISSUE TITLE
Service ingestion workflows should be configurable as scheduled or on-demand

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6071]
**Feature**
Currently, service ingestion workflows are deployed, and we ask users to input their desired schedule.
This is great for ingestion workflows as they need to be executed at desired schedule intervals. However, few system-level ingestion workflows may need to be executed on-demand.
Example:
1. Backup workflow
2. Search Index workflow

It would be great to have an option to select on-demand and provide "Run Now" options that can be manually triggered.

**Comment by pmbrull** [comment]
hi @harshach, gave this a go and on the ingestion side I don't think we'll need to do any updates. Airflow already supports having a `scheduleInterval` as `null`, which will only allow DAGs to be triggered externally.

The `run` API is also present, so we can trigger pipelines on demand.

Let me know if that would work or if you were thinking on a specific endpoint.

Thanks!

**Comment by pmbrull** [comment]
Only UI support missing here
