### ISSUE TITLE
Tag creation should apply the validation from JsonSchema

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6097]
**Affected module**
UI

**Describe the bug**
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/38649/179047423-3b3802cf-42ae-473a-8b75-527b178add1a.png">
https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/resources/json/schema/entity/tags/tagCategory.json#L14

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
- [ ] tags if one of the categories fails we don't display any of them and throw an error


![Image](https://user-images.githubusercontent.com/71748675/179241832-ed5ec532-cb1e-4bb1-9db9-de387aca2224.png)
