### ISSUE TITLE
Links to the Python API are broken.

### ISSUE THREAD

**Issue by vecorro** [open-metadata/OpenMetadata#6104]
**Is some content missing, wrong or not clear?**
I'm trying to understand how to use OpenMetadata for ML model dev use cases. Two publications about the subject:
[https://blog.open-metadata.org/ml-is-not-just-about-ml-c08eab242e84](url)
[https://docs.open-metadata.org/developer/architecture/entities/ml-model-entity](url)

point readers to the Python API documentation, however, those links are broken.

**Describe the solution you'd like**
Can you verify that the Python API docs are placed at the right location? it probably has been moved and is no longer at the link where other documents expect it to be.

**Comment by pmbrull** [comment]
Thanks for raising @vecorro. The blog has been updated accordingly.
