### ISSUE TITLE
Not getting Entity details which is connected via pipeline as edge

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#6108]
- [x] This pipeline is connected as an edge in multiple table entities but still, we are not getting data of table entities here!
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71748675/179169266-3233c0eb-43c8-4c75-94cc-7c297939e4e6.png">

- [x] We should not get pipeline as an entity in the lineage API call
- [ ] backend should restrict creating lineage for any entity to pipeline entity (after pipeline as edge we no longer need an entity to the pipeline)

**Comment by harshach** [comment]
@nahuelverdugo can you take this up, right now when a pipeline entity reference comes in we add it as edge only. Solution is to add both as edge and a pipeline. In case of Table lineage view Ui will show the pipeline as edge and incase of Pipeline view it will shown as edge.

**Comment by ShaileshParmar11** [comment]
Hi @harshach 1st and 2nd point is done, but 3rd point is still left, we can be able to connect the pipeline with the table as a node, and after that, the pipeline shown as a node, in the table view
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/71748675/231371127-c6b3d719-393c-4028-b078-fda969aa04c5.png">
