### ISSUE TITLE
Ingestion error in using sample pipelines

### ISSUE THREAD

**Issue by yelim-0** [open-metadata/OpenMetadata#611]
I referred to the document.
→ https://docs.open-metadata.org/install/metadata-ingestion/ingest-sample-data#ingest-using-sample-pipelines-consisting-of

I've done installation. Then, I command "metadata ingest -c ./examples/workflows/sample_data.json".
But there isn't 'sample_data.json.' So, I searched it and found the same-titled file on the following path.
→ /OpenMetadata/ingestion/pipelines/
**Q1) Is it this file that I'm looking for?**

I thought it was the proper file and proceeded. I ran "metadata ingest -c sample_data.json" command again. Then the error occurred, "FileNotFoundError: [Errno 2] No such file or directory: './examples/sample_data/datasets/service.json'". 

To solve the above error, I copied 'sample_data.json' to the parent folder, 'ingestion', and executed the "ingestion -c sample_data.json" command again. 
--> Then, another error occurred "requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8585/api/v1/services/messagingServices?name=sample_kafka" 

![image](https://user-images.githubusercontent.com/59372607/135276588-0da3d898-1347-4889-bccc-2c84f158643c.png)

**Q2) How can I solve this problem?**

**Comment by harshach** [comment]
hi @yelim-0 thanks for filing the ticket.
I assume you checked out the main branch from git if so
can you check under ingestion dir
<img width="613" alt="image" src="https://user-images.githubusercontent.com/38649/135298379-9e7559c1-75ca-4e57-9914-625653f60c6b.png">

in metadata command "-c" is the config file not the data file
so you need to run
```
metadata ingest -c pipelines/sample_data.json
```

**Comment by harshach** [comment]
@yelim-0 it was bug in our docs. I updated it 
please give it a try again
https://docs.open-metadata.org/install/metadata-ingestion/ingest-sample-data#ingest-using-sample-pipelines-consisting-of

**Comment by darkknight100** [comment]
I tried it and it gave some validation errors.
`[2021-09-29 17:39:53,084] INFO     {metadata.cmd:68} - Using config: {'source': {'type': 'sample-data', 'config': {'sample_data_folder': './examples/sample_data'}}, 'sink': {'type': 'metadata-rest', 'config': {}}, 'metadata_server': {'type': 'metadata-server', 'config': {'api_endpoint': 'http://localhost:8585/api', 'auth_provider_type': 'no-auth'}}, 'cron': {'minute': '*/12', 'hour': None, 'day': None, 'month': None, 'day_of_week': None}}
Traceback (most recent call last):
  File "/usr/local/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/metadata/cmd.py", line 76, in ingest
    workflow.execute()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 128, in execute
    for record in self.source.next_record():
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/sample_data.py", line 295, in next_record
    yield from self.ingest_tables()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/sample_data.py", line 308, in ingest_tables
    table_metadata = Table(**table)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 12 validation errors for Table
columns -> 0 -> columnDataType
  field required (type=value_error.missing)
columns -> 1 -> columnDataType
  field required (type=value_error.missing)
columns -> 2 -> columnDataType
  field required (type=value_error.missing)
columns -> 3 -> columnDataType
  field required (type=value_error.missing)
columns -> 4 -> columnDataType
  field required (type=value_error.missing)
columns -> 5 -> columnDataType
  field required (type=value_error.missing)
columns -> 6 -> columnDataType
  field required (type=value_error.missing)
columns -> 7 -> columnDataType
  field required (type=value_error.missing)
columns -> 8 -> columnDataType
  field required (type=value_error.missing)
columns -> 9 -> columnDataType
  field required (type=value_error.missing)
columns -> 10 -> columnDataType
  field required (type=value_error.missing)
columns -> 11 -> columnDataType
  field required (type=value_error.missing)
`

**Comment by harshach** [comment]
@darkknight100 you might be using the main. Try the 0.4 branch if not. Can you try the following command and restart the server
build the openMetadata from main https://docs.open-metadata.org/open-source-community/developer/build-code-run-tests
once you have the binary built ru
```./bootstrap/bootstrap-storage.sh drop-create```
and re-run the ingestion

Issue here is you are using new sample data with old openMetadata server. We have made changes in main hence causing this issue.
Feel free jump in slack we can resolve it quicker http://slack.open-metadata.org

**Comment by harshach** [comment]
Hi @yelim-0 @darkknight100 checking to see if you got a chance to test out new docs to ingest sample data. Thanks

**Comment by sureshms** [comment]
Closing this as it is quite old. If the issue still happens, reopen this issue or create a new issue.
