### ISSUE TITLE
Sampledata page breaks if there is no sample data for a table

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#612]
Sample data is an optional field for a table. We may not have this data for all tables or tables itself doesn't have any data. 
Right now sample data breaks if there is no data
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/38649/135299587-5ca6004b-de8f-4407-97f4-a6a7bf0ed8f5.png">
@Sachin-chaurasiya lets make sure we are defensive about these things and show there is no sample data message

**Comment by Sachin-chaurasiya** [comment]
@harshach can you share the console error ? 
It would be easy to debug.

**Comment by Sachin-chaurasiya** [comment]
Closing this as fixed has been merged #630
