### ISSUE TITLE
UI - Show aggregate tests count at the top level

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#6127]
**Affected module**
UI

**Describe the bug**
Number of tests seen in UI is less than actual number (see screenshot). Perhaps, only column tests count here but need to confirm.

**To Reproduce**

Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/60112387/179244284-6b2e9274-d3d1-461c-877e-9aeddc3fe2b9.png)

**Expected behavior**
Correct number of created tests should be displayed. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
[Thread here ](https://openmetadata.slack.com/archives/C02B6955S4S/p1657722994390779?thread_ts=1657722962.371559&cid=C02B6955S4S)🧵

**Comment by Tonilyn** [comment]
@Sachin-chaurasiya Got it, now I see, thanks! 

Numbers are a bit confusing and that's why users asked us a lot about reasons behind this count display. Perhaps it would be more clear to see the sum in one place in the future.  Just a thought based on feedback.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Got it, now I see, thanks!
> 
> Numbers are a bit confusing and that's why users asked us a lot about reasons behind this count display. Perhaps it would be more clear to see the sum in one place in the future. Just a thought based on feedback.

Thanks, @Tonilyn, We will look into that.

**Comment by harshach** [comment]
we should aggregate counts at the top. @devyani-kaushik please add these changes to the mocks as well

**Comment by ShaileshParmar11** [comment]
With the new implementation, we have a profiler tab which takes care of this


![Image](https://user-images.githubusercontent.com/71748675/186824185-e8a9a708-3099-4227-ba0d-71bded4adaf5.png)
