### ISSUE TITLE
Docs reference "Messaging Service" in places where "Dashboard Service" or "Pipeline Service" are more appropriate

### ISSUE THREAD

**Issue by juliarvalenti** [open-metadata/OpenMetadata#613]
There are a few places in the documentation where Messaging Service is referenced when it should be Dashboard or Pipeline.  I assume this is due to a copy-paste.

![Screen Shot 2021-09-29 at 12 54 29 PM](https://user-images.githubusercontent.com/42276144/135314394-47990a20-c30c-430a-8b55-a6a6883875ca.png)

https://docs.open-metadata.org/openmetadata-apis/schemas/entities/dashboardservice

**Comment by harshach** [comment]
Thank you for the contribution. Can you please open a PR we will merge it in https://github.com/open-metadata/OpenMetadata/pulls
