### ISSUE TITLE
Add support for team hiearchy

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#6133]
Currently, the only people hierarchy supported in OpenMetadata is `teams` and each team is a group of `users`. This issue adds support for a more comprehensive team hierarchy.

# Why?
1. In OpenMetadata, an admin is an admin for the entire organization. There is no delegated admin model where an admin can be scoped to a specific team or parts of the organization.
2. When authoring policies, having a team hierarchy can help in authoring hierarchical policies. For example, a policy at an organizational level applies to everyone. A policy at a business unit level or department level applies to the users and resources belonging to that team.
3. In the future, we can use this hierarchy to help users set the scope of OpenMetadata UI to a business unit, division, or department to limit their focus on the part of the organization they are interested in instead of the entire metadata of an organization.

# How?
- We are adding `teamType` that can be `Organization`, `Business Unit`, `Division`, and `Department` (default team type).
- `Organization` is the root team in the hierarchy. It can't have a parent. It can have children of type `Business Unit`, `Division`, or `Department` along with `Users` directly as children (who are without teams).
- `BusinessUnit` is the next level of the team in the hierarchy. It can have `Business Unit`, `Division`, and `Department` as children. It can only have ** one parent ** either of type `Organization`, or `Business Unit`.
- `Division` is the next level of the team in the hierarchy below `Business Unit`. It can have `Division`, and `Department` as children. It can only have ** one parent ** of type `Organization`, `Business Unit`, or `Division`.
- `Department` is the next level of the team in the hierarchy below `Division`. It can have `Department` as children. It can have all the types of teams as parents. ** It can have multiple parents **.

# How does this affect existing OpenMetadata deployments
1. No change is necessary to existing deployments. All the teams start with a flat hierarchy and are directly the children of `Organization`. A default `Organization` is created during OpenMetadata startup and the existing teams are made children of the org.
2. New teams can be added to this hierarchy based on the needs of an organization. A large organization can choose the entire hierarchy - Org -> Business Unit -> Division -> Department. A small organization can just choose Org -> Department -> Department to model a simpler flat organization.

**Comment by mkayl** [comment]
This proposal makes sense to me aside from the following point:
1. A `BusinessUnit` can have `Organization` or `Business Unit` as a parent. This would allow limitless levels of hierarchy.
2. Same for `Division`
3. Same for `Department`

What is the reasoning behind this proposal?
Also, the naming `Team` instead of `Department` would feel a bit more intuitive to me.

**Comment by sureshms** [comment]
> This proposal makes sense to me aside from the following point:
> 
> 1. A `BusinessUnit` can have `Business Unit` as a parent. This would allow limitless levels of hierarchy.
> 2. Same for `Division`
> 3. Same for `Department`
> 
> What is the reasoning behind this proposal? Also, the naming `Team` instead of `Department` would feel a bit more intuitive to me.

Large companies can have a depth of levels of more than 5. These organizations can also have matrix reporting. The current proposal handles these requirements. 

Btw all these are Team entities of different types. We are thinking of naming the leaf node as `Group`. Just a group of people that can only have users under it. Wdyt?
