### ISSUE TITLE
UI: Show Reactivate option for soft-deleted entities

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6137]
**Affected module**
UI

We should show an option to re-activate a soft deleted entity along with an option to hard delete.

**Comment by chirag-madlani** [comment]
@harshach We need backend support for reactivating Entities.

**Comment by harshach** [comment]
@chirag-madlani currently, a client needs to make a GET call and use the entire response as a PUT call if the entity is soft deleted, it will restore it.
Adding a specific API will go against HTTP semantics.
Discussion https://stackoverflow.com/questions/8621671/restful-undelete
