### ISSUE TITLE
Use a comment to tag all OM-related queries

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6140]
We should be able to run all our queries with an added comment, something like:

```sql
select 
/* Query generated from OpenMetadata */
...
```

The idea will then be filtering out all these data from the usage to not try to compute noise and give a way to users to track what we are doing and how

**Comment by Beetelbrox** [comment]
dbt uses a header like the one below to inject metadata on all its queries, could be used as inspiration:
`/* {"app": "dbt", "dbt_version": "1.1.1", "profile_name": "<profile>", "target_name": "<target>", "node_id": "<node.fqn>"} */`

**Comment by pmbrull** [comment]
that's a pretty great suggestion, thanks for the info!

**Comment by pmbrull** [comment]
really like the idea of the version TBH

**Comment by pmbrull** [comment]
Let's also add also the filtering in the usage to exclude OM queries

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/6293
