### ISSUE TITLE
Notification for service owner when ingestion pipeline fails

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6145]
Whenever an IngestionPipeline fails, the service owner should receive a notification. Otherwise, it is hard to keep track of the different services and requires manual validation

**Comment by pmbrull** [comment]
Let's handle this one after we finish https://github.com/open-metadata/OpenMetadata/issues/6141, it will be easier

**Comment by harshach** [comment]
This can be built on top of alerts we have now cc @mohityadav766
