### ISSUE TITLE
Invalid field name policyUrl Error

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#6152]
**Affected module**
- UI

**Describe the bug**

**To Reproduce**
- Go to "Roles" page

Screenshots or steps to reproduce
![Capture d’écran 2022-07-18 à 14 26 09](https://user-images.githubusercontent.com/75131226/179510802-eb12a74f-2b41-4b2a-8962-7bfd52494bf7.png)
![Capture d’écran 2022-07-18 à 14 27 08](https://user-images.githubusercontent.com/75131226/179511110-3a3f6261-e8d7-43b7-8eb8-5d664d43d6eb.png)

**Expected behavior**

**Version:**
 - OpenMetadata version: 1.11.1

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hey @haithem-souala, Thanks for reporting this.
This is fixed by https://github.com/open-metadata/OpenMetadata/pull/6124
