### ISSUE TITLE
Optimize Redshift usage query

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6162]
Now it takes way too long and we end up having to cancel the run. Reported a few times

**Comment by TeddyCr** [comment]
Thanks @Beetelbrox for the great insight and findings on this 🙏. 

Regarding 2) the best would be to skip the excluded tables -- we can connect on the actual implementation if needed/if interested -- @pmbrull any opinion this?

Feel free to open a PR with the query predicate you think would be best to optimize the query. 🙂

**Comment by Beetelbrox** [comment]
Moar finding, this time on the ingestion process performance. We can broadly split it into 4 stages that can be tackled more or less separately at this stage. Here are the performance findings for them:
 1. **Fetching list of queries & associated tables from RS**: Runs relatively fast (~1 min) for tens of thousands of queries
 2. **Query parsing**: The parser sqllineage uses under the hood ([sqlparse](https://github.com/andialbrecht/sqlparse)) It's not particularly fast and experiments run on my company's workload show an average parsing time per query of ~30 ms ~= 33 queries/s ~= 118800 queries/hour. Depending on the volumes we're targeting this might not be acceptable
 3.  **Table entity fetching from ES**: This stage is slow as it relies on HTTP requests and has massive amounts of redundancy: Most queries target a subset of all the table and we are currently naively requesting the same tables over and over. We could improve this by keeping a cache of tables.
 4.  **SQL lineage + TableQuery registration**: Same as the step above, this step is HTTP-intensive and doesn't scale well for large volumes. There seem to be some degree of redundancy here too that we could try to eliminate, we could also explore more efficient ways to do load the data into OMeta (Async, bulk load endpoint) to avoid doing large amounts of requests sequentially

As a reference, I truncated the ingestion to 20k records and it took 29:18 mins to run, with a significant amount of time spent on waiting:
![image](https://user-images.githubusercontent.com/9376816/180146039-c885665e-a147-4bef-88b4-de6b6571a867.png)

**Comment by TeddyCr** [comment]
Thanks for the additional findings @Beetelbrox. Very interesting insight. 3) seems well identified and a quick win. Do you see this as adding good value for your use case, if so would you be interested in tackling it?

**Comment by Beetelbrox** [comment]
Hey @TeddyCr thanks for your answer. Yes indeed, I'm already on it. Thanks!

**Comment by TeddyCr** [comment]
Awesome, let's open a new issue (if this not already done)

**Comment by pmbrull** [comment]
Hi @Beetelbrox, @TeddyCr , as this task is related to the Redshift query, is there anything else we need to handle here? Or can we consider this done. I understand that further tuning can be done in the usage workflow, but we can open other issues if needed.

Thanks

**Comment by Beetelbrox** [comment]
Hai I think we're done here, most of the optimization I can think of it's on the workflow itself as you mentioned so I reckon we can close this.

**Comment by pmbrull** [comment]
thanks, closed!
