### ISSUE TITLE
Parallelise Profiler Workflow

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6163]
We run sequentially, both in terms of queries (metrics) as well as tables. This takes a bunch of time and has a high cost output for Snowflake.

### Ingestion
- https://github.com/open-metadata/OpenMetadata/issues/6325
- https://github.com/open-metadata/OpenMetadata/issues/6326

**Comment by TeddyCr** [comment]
https://github.com/open-metadata/OpenMetadata/issues/5661 will need to be tackled first.

**Comment by harshach** [comment]
@pmbrull @TeddyCr moving some of this to 0.13.
