### ISSUE TITLE
Datamodel codegen does not apply defaults for $ref

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6173]
From https://github.com/open-metadata/OpenMetadata/pull/6134

There is a new definition in `team.json`

```
"definitions": {
    "teamType" : {
      "description" : "Organization is the highest level entity. An Organization has one of more Business Units, Division, or Departments. A Business Unit has one or more Divisions, or Departments. A Division has one or more Divisions or Departments. A Department has one or more Departments or users.",
      "type" : "string",
      "enum": [
        "Department",
        "Division",
        "BusinessUnit",
        "Organization"
      ],
      "default": "Department"
    }
  },
```

Picked up in

```
"teamType": {
      "description": "Team type",
      "$ref": "#/definitions/teamType"
    },
```

However, the pydantic model generating from here does not properly use the `default` in `teamType`. This is working correctly in Java.

Let's see if we can play with some parameters on the CLI https://koxudaxi.github.io/datamodel-code-generator/, find a better alternative, or open a PR

**Comment by pmbrull** [comment]
Reached out at https://github.com/koxudaxi/datamodel-code-generator/issues/812

**Comment by pmbrull** [comment]
This has been fixed on the source in https://github.com/koxudaxi/datamodel-code-generator/pull/832. Let's wait until the next release which should have this in and upgrade our deps

**Comment by pmbrull** [comment]
This ticket is now to just update the dependency

**Comment by koxudaxi** [comment]
@pmbrull 
I'm sorry for the late release of the fixed.
version `0.13.2` has been released.
Could you please try it?

https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.13.2

**Comment by pmbrull** [comment]
hi @koxudaxi no issues at all, thanks for the fix, appreciate the time on getting this done!

Actually, I was trying to replicate an issue we are currently having with `0.13.2`:

- We have the [ingestionPipeline.json](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/ingestionPipelines/ingestionPipeline.json#L169) using a `$ref` to another JSON Schema.
- The references JSON Schema has some [defaults](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/metadataIngestion/workflow.json#L137) in an enum.

What is happening is that the `import` is not properly handled. In the `IngestionPipeline` pydantic model we end up having an import error:

```
from ....metadataIngestion import workflow

[...]
    loggerLevel: Optional[workflow.LogLevels] = Field(
        LogLevels.INFO, description='Set the logging level for the workflow.'
    )
[...]
```

As you can see, within the `Optional` we have `workflow.LogLevels`, while this import is not being used when setting the default.

Trying to get some minified example on this that would be easier for you to reproduce.

Thanks!

**Comment by koxudaxi** [comment]
Thank you for testing the lastest version quickly.

> but foo.py gets created without passing the ref and just using the str thinking
Do you expect the default value?
```python
class Foo(BaseModel):
    loggerLevel: Optional[bar.LogLevels] = bar.LogLevels.INFO
```

The CLI is the option for the behavior

```
  --set-default-enum-member
                        Set enum members as default values for enum field
```

I have tried the option.
But, I met the bug for the case :sweat:  

```
class Foo(BaseModel):
    loggerLevel: Optional[bar.LogLevels] = LogLevels.INFO
````

I will fix it.

**Comment by pmbrull** [comment]
oh missed that flag you're right! Thanks for checking and for the fast response. We'll wait to upgrade to the following version. Thanks!

**Comment by koxudaxi** [comment]
@pmbrull 
I have released the fixed version.
Could you please try it?
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.13.3

**Comment by pmbrull** [comment]
Hi @koxudaxi, thanks for the ping.

From our JSON Schema

```json
"logLevels": {
      "description": "Supported logging levels",
      "javaType": "org.openmetadata.schema.metadataIngestion.LogLevels",
      "type": "string",
      "enum": ["DEBUG", "INFO", "WARN", "ERROR"],
      "default": "INFO"
    },
```

Now the model gets generated as 

```python
loggerLevel: Optional[workflow.LogLevels] = Field(
        workflow.LogLevels, description='Set the logging level for the workflow.'
    )
```

I am not sure this si correct. I would expect `workflow.LogLevels.INFO`. Are we missing anything here?

I believe this is the expected behavior you set in the test cases though https://github.com/koxudaxi/datamodel-code-generator/pull/876/files#diff-c3b08450ac392a35ce5120ee7381936f1c1ecedc3a60ae020d6b9d3ddb55b790R15

Thanks again! Happy to discuss 🙏

**Comment by koxudaxi** [comment]
@pmbrull 
Thank you for checking the version.
I'm sorry, I made mistake :cry: 

https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.13.4
I fixed and released it as `0.13.4` :bow: 

https://github.com/koxudaxi/datamodel-code-generator/pull/888/files#diff-c3b08450ac392a35ce5120ee7381936f1c1ecedc3a60ae020d6b9d3ddb55b790R16-R17

**Comment by pmbrull** [comment]
Awesome thanks! no issues at all, let me test and get back here, appreciate the help 🙏

**Comment by pmbrull** [comment]
Looks like it is working perfect now! Many thanks

```python
loggerLevel: Optional[workflow.LogLevels] = Field(
        workflow.LogLevels.INFO, description='Set the logging level for the workflow.'
    )
```

Will be updating the version on our repo. If we see anything weird we'll let you know, but looks perfect.

Thanks!

**Comment by pmbrull** [comment]
closed with https://github.com/open-metadata/OpenMetadata/pull/8492

**Comment by koxudaxi** [comment]
I'm happy to hear the result.
Thank you very much for sponsoring me :)
