### ISSUE TITLE
Edge not getting generated when multiple  tasks in pipeline

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#6179]
**Affected module**
UI

**Describe the bug**
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/39544459/179687341-19dfe867-d254-4dc9-a864-1bcb40f2f892.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/39544459/179687443-6f04387a-ddb6-482d-b2d4-9d1a1f75ea0c.png">

**Comment by Sachin-chaurasiya** [comment]
The issue is we were only checking if the task is a downstream task or not, we were missing the check for if the task has a downstream task.
Will push the fix for the same.
