### ISSUE TITLE
Query parser fails on Redshift COPY statements

### ISSUE THREAD

**Issue by Beetelbrox** [open-metadata/OpenMetadata#6203]
**Affected module**
Ingestion framework

**Describe the bug**
When we try to parse a [COPY](https://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html) statement from Redshift the `source_tables` list on the parsed query object contains a `sqllineage.core.models.Path` instance with the S3 key of the copied file. Downstream code [expects this instance to be a table](https://github.com/open-metadata/OpenMetadata/blob/9308fe6df31d83895ba16e934ef6e69adba25881/ingestion/src/metadata/ingestion/processor/query_parser.py#L78-L85) and tries to access a non-existing `alias` field, crashing the parsing of the query with the error `AttributeError: 'Path' object has no attribute 'alias'`

**To Reproduce**
The error can be reproduced running the following code:
```python

from sqllineage.runner import LineageRunner
from metadata.ingestion.processor.query_parser import get_involved_tables_from_parser, get_parser_table_aliases

query = "COPY my_schema.my_table FROM 's3://bucket/path/object.csv';"

tables = get_involved_tables_from_parser(LineageRunner(query))
get_parser_table_aliases(tables)
```

**Expected behavior**
The query parser doesn't raise an error and the reference to the object is stored in some kind of entity. Not sure if we have some way of supporting this right now or if we should just filter out copy queries for now.

**Version:**
 - OS: iOS
 - Python version: 3.9.19
 - OpenMetadata version: 0.11.0
 - OpenMetadata Ingestion package version: 0.11.0

**Additional context**
This is part of the greater effort for optimizing redshift usage ingestion on #6162.

**Comment by TeddyCr** [comment]
Thanks @Beetelbrox for the findings, this is very great feedback. I would say `COPY` statement could be skipped as they are primarly data manipulation statement and I feel like they provide little value for users (they could also poluate usage statistic in a sense). 

As a user, do you see any value in keeping `COPY` statements in usage?

**Comment by harshach** [comment]
@nahuelverdugo shall we skip the erroring out just like MERGE INTO queries and close this out?

**Comment by nahuelverdugo** [comment]
I would use the same approach we have for `MERGE INTO` and address this for `0.13.1`.
