### ISSUE TITLE
UI: Soft deleted team shows up in Manage -> Add Owner

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6208]
**Affected module**
UI

**Describe the bug**
Deleted users / teams show up in "Add owner" dropdown

**To Reproduce**
 - Soft delete a team
 - Go to any entity page's Manage tab and click on "Add owner" and search for deleted team

**Expected behavior**
Only active users or teams are shown in the dropdown to assume ownership of entities

**Comment by chirag-madlani** [comment]
@harshach Need filter support on suggest team API

**Comment by harshach** [comment]
@chirag-madlani this fixed. Can you double check and close it out

**Comment by chirag-madlani** [comment]
Fixed in `0.12.1` Verified on sandbox
