### ISSUE TITLE
Support MySQL 5.7

### ISSUE THREAD

**Issue by TheFu527** [open-metadata/OpenMetadata#6223]
**Is your feature request related to a problem? Please describe.**

The current OpenMetadata cannot connect to MySQL 5.7, because the version of flyway is too high to support MySQL 5.7. But MySQL 5.7 is still an indispensable release in many production environments.

**Describe the solution you'd like**

Downgrade Flyway to support MySQL 5.7.

**Describe alternatives you've considered**

**Additional context**

**Comment by pmbrull** [comment]
MySQL 5.7 is reaching EOL in 2023. Moreover, there is a known limitation on Flyway where MySQL 5.7 is not supported on the free version.

Going backwards won't help the majority of the community.

Thanks
