### ISSUE TITLE
Show dataset information

### ISSUE THREAD

**Issue by anshu-sam** [open-metadata/OpenMetadata#6235]
**Is your feature request related to a problem? Please describe.**
This feature of adding dataset level information while searching makes it easier for users to search for datasets if required. The feature which I can see from the sandbox is that we cannot search for datasets individually, but rather it is just tables, pipelines, dashboards etc.

**Describe the solution you'd like**
The solution we can come up with is, to show the datasets as well, while searching for them in data catalog and along with the required definition tags, the tables present in the dataset etc. If this feature is already present but not in sandbox, please add in sandbox as well. 

**Describe alternatives you've considered**
Also add this feature in the search bar. And if possible if there is any visualization tool (eg-tableau,powerbi) we can connect to attached to the queries or table for reports, it would be great.

**Comment by harshach** [comment]
@anshu-sam we do show the tables based on database, databseSchema. Can you elaborate more on what you mean by dataset in this context

**Comment by harshach** [comment]
@anshu-sam can you please add more details and some examples here. Thanks

**Comment by sureshms** [comment]
@anshu-sam marking this as closed. Reopen with additional information if necessary.
