### ISSUE TITLE
ES index DAG to be always deployed with our instances

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6249]
to make sure we can run this daily and have updates ES in case of any hiccups

**Comment by harshach** [comment]
@pmbrull 
IMO this should be on demand deployment. 
ex: 
1. If  user installs in non-secure mode the deployment will not contain any security configs on the es workflow side
2. if they later configures security, this workflow needs to be updated.

This should be a separate settings from the UI and run like rest of the ingestion workflows
