### ISSUE TITLE
[Redshift] Usage Workflow not updating percentile 

### ISSUE THREAD

**Issue by nileshkhatri9** [open-metadata/OpenMetadata#6253]
**Affected module**
[Ingestion Framework]
Redshift Usage Workflow

**Describe the bug**
When we run usage workflow and profiler workflow both, we can see the profilers data but usage is always 0th pctile and also Queries list is not generated.

**To Reproduce**
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/42669843/180263255-b24b6ea3-22fe-4ad0-8c90-b3f5e2d11f9d.png">
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/42669843/180263434-468954a0-c30e-4d90-a0ae-6b2af0663f52.png">

**Expected behavior**

We should get usage percentile for a particular 
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/42669843/180263547-d47a0076-405c-491e-96dc-a9b9232967c6.png">
[Note: Image taken from tutorials just for explanatory purpose]

**Version:**
 - OS:  iOS
 - Python version: 3.9.7
 - OpenMetadata version: [0.11.0]
 - OpenMetadata Ingestion package version: openmetadata-ingestion 0.11.0.0

**Comment by pmbrull** [comment]
not replicable, working on 0.11.X and 0.12
