### ISSUE TITLE
sandbox-beta logging in as non-admin user throws an error

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6285]
**Affected module**
UI

**Describe the bug**
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/38649/180486681-82f0ba13-04e6-4ce9-b1cb-208fde490322.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Verified on sandbox beta and it's working fine.
