### ISSUE TITLE
Setting up a database service with underscores fails and gives no UI acknlowledgment

### ISSUE THREAD

**Issue by juliarvalenti** [open-metadata/OpenMetadata#629]
https://user-images.githubusercontent.com/42276144/135534441-263b4fce-0a2f-4645-aa09-d1efde3de70d.mov

As detailed in the above video, I can fill out the form and click Save.  The modal closes, but no Database Service is created because the API request returned 400 with the following error.  There is no modal or error popup detailing what went wrong with the request, it just fails silently.

```
Cannot deserialize value of type `java.net.URI` from String "my_sql_user:mysql_pass@localhost:3306/test": not a valid textual representation, problem: Illegal character in scheme name at index 2: my_sql_user:mysql_pass@localhost:3306/test
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 185] (through reference chain: org.openmetadata.catalog.api.services.CreateDatabaseService["jdbc"]->org.openmetadata.catalog.type.JdbcInfo["connectionUrl"])
```

**Comment by harshach** [comment]
Thanks for reporting the issue @juliarvalenti .
@darth-coder00 can you take a look at the UI part and I'll check the backend exception.

**Comment by darth-coder00** [comment]
> Thanks for reporting the issue @juliarvalenti . @darth-coder00 can you take a look at the UI part and I'll check the backend exception.

Sure, will take a look
