### ISSUE TITLE
Profiler should collect last updated timestamp of a table

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6294]
**Feature**
We should look at the start and endgame of table load and provide timestamps back to OM table entity.
1. Tables that are partitioned would be easy to collect if the table has any timestamp column look at the latest row and earliest row to get the timestamps. If we collect enough of this data we can provide the ETL time loads to users and drive freshness metric
2. In cases of where tables are not partitioned we need to apply heuristic to collect the start and end date and collect the times over a period of time
3. We also need to consider if the warehouses provide this information instead of looking at the data.

**Comment by TeddyCr** [comment]
@harshach I am going to close this as this will be supported by the freshness metric implementation
