### ISSUE TITLE
Datalake connector performance

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6295]
We need to analyze if we need to load the whole files when parsing the schemas, or we can pick up a few lines.

In the case of parquet, we might be able to read the first rowGroup or directly the metadata headers.

We need to be able to properly ingest the metadata from multiple GB sized files without needed to load everything in the RAM

**Comment by pmbrull** [comment]
cc @Beetelbrox

**Comment by Beetelbrox** [comment]
For parquet it seems we can read the schema & metadata on the parquet file footer quite easily with the tooling provided by pyarrow:
```python
from pyarrow.parquet import ParquetFile
from pyarrow import fs

s3 = fs.S3FileSystem(region='eu-west-1')
pf = ParquetFile(s3.open_input_file(S3_KEY))
print(pf.schema)
```
This returns the file's schema without reading the file:
```
required group field_id=-1 schema {
  optional double field_id=-1 X;
  optional double field_id=-1 Y;
  optional double field_id=-1 Z;
  optional double field_id=-1 X_noise;
  optional double field_id=-1 Y_noise;
  optional double field_id=-1 Z_noise;
  optional double field_id=-1 R;
  optional double field_id=-1 G;
  optional double field_id=-1 B;
  optional double field_id=-1 time;
  optional double field_id=-1 eol;
  optional double field_id=-1 label;
}
```

Tried it in a 2GB parquet file, it read it instantly without any memory usage at all. We also have available the metadata exposed in `ParquetFile.metadata`:
```
  created_by: parquet-cpp version 1.5.1-SNAPSHOT
  num_columns: 12
  num_rows: 46234315
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 2778
```

**Comment by Beetelbrox** [comment]
I have questions on the expected & desired usage of this ingestion tho. From what I can read in the code we assume as "tables" all files under `s3://<bucket>/prefix/`, which we then extract the schema from. Unless I'm understanding something quite wrong, if the intention is to allow users to define some prefix in S3 and then ingest everything in them as "tables" we might have several challenges & required changes:
 * The amount of files to process can be massive. When users read "Datalake ingestion" they might try to use it to ingest their entire datalake storage layer.
 * If someone points to eg a prefix pointing to a hive table we will create a table entity for each file in the Hive table, and this can be a lot of entities which don't necessarily mean anything as individuals as they're part of the bigger Hive table.
 * [The current implementation](https://github.com/open-metadata/OpenMetadata/blob/14b9439b982b9a5f4faeb12d70ba91448e9f3cb9/ingestion/src/metadata/ingestion/source/database/datalake.py#L193) for S3 will only return 1k files, [list_objects](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects) is paginated and we're not handling the pagination from what I can see.

Maybe I missed something important in the code and I got the above completely wrong, but if I read it right we might have a rough time making this scalable and preventing it from polluting the catalog as users will most definitely "misuse" it. Happy to discuss more on this tho!

**Comment by pmbrull** [comment]
Hi @Beetelbrox,

Thanks for your thoughts:

- IMO we should use the datalake connector for specific buckets/prefixes/paths that are not registered in a given metastore. We could better document the connector and explain the different approaches to listing data from a Datalake, as different connectors might overlap (the clearest being ingesting tables from Glue and Athena, for example).
- Agree on the file formats. We are now required to follow tabular data, but we'll add support for NoSQL to handle more general and schemaless data.
- Connecting this to the Datalake ingestion, updating the ingested entities from Table to Location (which is currently supported but a bit underused, might need some further tuning to get it right), might be a cleaner approach.
- We already have the requirement to not follow a sequential approach for the ingestion in the roadmap, although we would still need to keep sending HTTP requests to the backend. Processing only created/updated files would be interesting, but we'd then need to think about how to handle if a file has been deleted or not. Might not be a significant change.

Also, thanks for noticing that we are missing the pagination. That is a good point that we'll need to address. Thanks for analyzing the parquet read. I wonder if something similar can be done for JSON/CSV/TSV files to not rely on the whole data. Maybe we could just read a % of the file and infer the schema based on that.

**Comment by pmbrull** [comment]
closing this one in favour of https://github.com/open-metadata/OpenMetadata/issues/6479
