### ISSUE TITLE
Data Lake option to ingest at least basic file information for unsupported filetypes

### ISSUE THREAD

**Issue by cmedinasoriano** [open-metadata/OpenMetadata#6299]
**Is your feature request related to a problem? Please describe.**
It would be great to allow ingestion of any file type on a Data Lake instead of only ingesting the fully supported ones and discarding the unsupported ones.

**Describe the solution you'd like**
- Add a configuration recipe option to also allow ingesting not fully supported files with at least the known information of the file, like filename, owner.
- If the ingested s3 bucket already has a directory structure, why not ingest also the directories retaining the structure and allow adding metadata to the directories as well and not just the files.

**Describe alternatives you've considered**
I was able to ingest PNGs, JPEGs with Datahub (alternative framework) and was able to add metadata after ingestion, even though the file type was not fully supported IAW their documentation and the only available information of the file after ingestion was the name and owner.

**Additional context**
- A file that is not fully supported probably doesn't have to be fully processed to avoid affecting performance due to unknown large files.

**Comment by harshach** [comment]
@pmbrull given this is handled through storage services I am closing it as done

**Comment by eckarta** [comment]
@harshach If i'm not mistaken, storage services does not support the tagging of assets contained within a container, and only enables tagging the container itself. Supporting basic ingestion of 'unsupported files', even if they are not structured/parse-able could enable expanded usage of the framework, allowing for management of data files of any format, even if they do not conform to a supported structure.
