### ISSUE TITLE
PATCH API is fails to update for column description for table entity.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#632]
REQUEST: http://localhost:3000/api/v1/tables/8eeec9dd-017c-4fe8-9c6d-7513ad782c57

PAYLOAD : [
    {
        "op": "replace",
        "path": "/columns/0/description",
        "value": "location description updated."
    }
]

RESPONSE : 
```
 {      name: "location_id",
        constraint: "PRIMARY_KEY"
        dataType: "NUMERIC"
        dataTypeDisplay: "numeric"
        description: "location description."
....
}
```

EXPECTED RESPONSE : 

```
 {      name: "location_id",
        constraint: "PRIMARY_KEY"
        dataType: "NUMERIC"
        dataTypeDisplay: "numeric"
        description: "location description updated."
....
}
```

**Comment by sureshms** [comment]
@Sachin-chaurasiya, are you making multiple changes here to the table? Can you describe how to reproduce this? There are unit tests that test this functionality already.

**Comment by Sachin-chaurasiya** [comment]
@sureshms I was just updating the description.
To reproduce this issue, go to any table entity details page and try to update description of any column.
