### ISSUE TITLE
UI : Add custom properties support for all entities

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#6328]
Today, we have custom property support for the table entity only, as the backend has added support for all the entities UI should also add custom properties for the following entities.

- [ ] Topic
- [ ] Pipeline
- [ ] Dashboard
- [ ] Ml Models

**Comment by harshach** [comment]
@Sachin-chaurasiya can we add a cypress test for this

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya can we add a cypress test for this

Sure @harshach , I will add that.
