### ISSUE TITLE
Implement Median support for MySQL

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#6340]
There is no straightfroward support for median computation with MySQL currently. Solutions often involve few subqueries. Currently we are returning `NULL` for MySQL; we need to implement the correct computation to support this metric.

```
@compiles(MedianFn, Dialects.MySQL)
def _(elemenst, compiler, **kwargs):
    """Median computation for MySQL currently not supported
    Needs to be tackled in https://github.com/open-metadata/OpenMetadata/issues/6340
    """
    return "NULL"
```

**Comment by deweybat** [comment]
Hi, I'm interested in this issue

**Comment by harshach** [comment]
hi @deweybat assigning it to you. If you have any questions reach out to us at slack https://slack.open-metadata.org

**Comment by pmbrull** [comment]
hi @deweybat, any updates on this? Let us know if you need any help. Thanks

**Comment by deweybat** [comment]
Hi!
I took an initial look at this, and I have some questions; Im away from my
computer at the moment, and I should be back Sunday

**Comment by pmbrull** [comment]
Thanks for the update. Please feel free to reach out on slack https://slack.open-metadata.org/, we'll be able to give you some guidance in there. Thanks

**Comment by schlameel** [comment]
This looks stalled. Would you assign this to me?
