### ISSUE TITLE
Service connection credential parameters marked as passwords are not masked

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#6345]
**Affected module**
UI

**Describe the bug**
Service credential connection parameters marked as passwords are visible in the connection tab of the service.

This is happening for Datalake connector but probably it also happens in other connectors which require credentials.

**To Reproduce**

![image](https://user-images.githubusercontent.com/11074908/180966949-edbab31d-3830-4ee0-9a14-bca4af520c0a.png)

**Expected behavior**

Those values should be masked.

**Version:**
 - OS: macOS
 - Python version: 3.9
 - OpenMetadata version: 0.11.2

**Comment by Sachin-chaurasiya** [comment]
Completed with #6880
