### ISSUE TITLE
Blank tier description is displayed

### ISSUE THREAD

**Issue by harsh-vador** [open-metadata/OpenMetadata#6353]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
A blank component is displayed when hovering over tier description tag.

**To Reproduce**
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/58542468/181011788-826ff839-be71-4240-a73a-4a493e9c3927.png">

**Expected behavior**
A component showing tier description should be displayed on hover.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Completed.
