### ISSUE TITLE
Airflow 2.3.3 None schedule validation

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6360]
Updating a scheduled DAG to `none` schedule gives us a broken dag on 2.3.3:

```
Broken DAG: [/ingestion/examples/airflow/dags/mysql_metadata.py] Invalid timetable expression: Exactly 5 or 6 columns has to be specified for iterator expression.
```

**Comment by stepanof** [comment]
[Try this](https://stackoverflow.com/questions/51520767/airflow-webserver-gives-cron-error-for-dags-with-none-as-schedule-interval#:~:text=19-,Try%20this%3A,-Set%20your%20schedule_interval)

**Comment by pmbrull** [comment]
Thanks @stepanof for the hint. I believe that the UI should not be passing any `schedule_interval` so the DAG is created with that value as `None`. We'll double-check based on the thread you shared. Thanks!

**Comment by stepanof** [comment]
@pmbrull As I can understand there is no opportunity to set empty `schedule_interval ` for new dag by openmetadata, am I right? 
![image](https://user-images.githubusercontent.com/68236577/183889773-ac189a95-c531-4d0f-9c8a-dab4f8a4fe8e.png)

If user change `schedule_interval ` in created by openmetadata DAG so he have to be responsible for occuring errors?
Please correct me if I don't understand something.

**Comment by nahuelverdugo** [comment]
Hi @stepanof after closing [this](https://github.com/open-metadata/OpenMetadata/issues/6071) issue we are able to configure `None` as `schedule_interval`.

![image](https://user-images.githubusercontent.com/11074908/183941091-02e87853-e818-459a-a8c9-87bc5af50ced.png)

**Comment by stepanof** [comment]
@nahuelverdugo Oh, I see. Thanks for explanation :)
