### ISSUE TITLE
[UI][Notification] Issue in tab for task Notifications

### ISSUE THREAD

**Issue by mohitdeuex** [open-metadata/OpenMetadata#6371]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Notifications tab should be on top of everything

**To Reproduce**
![image](https://user-images.githubusercontent.com/105265192/181171773-91f616c6-e73c-4002-bfd7-0c2e1670f3b7.png)

**Expected behavior**
Notification tab should be on top

**Version:**
 - OpenMetadata version: main

**Additional context**

**Comment by chirag-madlani** [comment]
#6395
