### ISSUE TITLE
Categorical column details on Profiler page

### ISSUE THREAD

**Issue by kkwan-vh** [open-metadata/OpenMetadata#6390]
Would like to see additional details about categorical data on Profiler page such as:
- Top (n) values
- Distribution of categorical values

References: 
- https://www.tableau.com/products/prep
- https://pandas-profiling.ydata.ai/examples/master/census/census_report.html

**Comment by jayasekharreddy-telluri** [comment]
Hey, I'd like to start taking a look at this issue, could you please assign it to me?

**Comment by TeddyCr** [comment]
@jayasekharreddy-telluri I see you already asked to contribute to this one https://github.com/open-metadata/OpenMetadata/issues/12198. Which one would you want to take?

**Comment by sureshms** [comment]
@TeddyCr is this still relevant?
