### ISSUE TITLE
Make Comments Editable

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#6394]
**Is your feature request related to a problem? Please describe.**
If I make a typo on a comment for a task, I'm unable to edit the comment and correct the typo, I can only delete the entire comment.

**Describe the solution you'd like**
Comment should be editable.

**Describe alternatives you've considered**
Copy the Comment, Delete the old Comment, Paste the new Comment with correction.

![image](https://user-images.githubusercontent.com/102999683/181394841-b0bb322b-41da-4216-9ae1-c52fbc605f1a.png)

**Comment by vivekratnavel** [comment]
@Sachin-chaurasiya Backend already supports [PATCH](https://docs.open-metadata.org/swagger.html#operation/patchPostOfThread) for posts in a thread. We need to add support in the UI.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Backend already supports [PATCH](https://docs.open-metadata.org/swagger.html#operation/patchPostOfThread) for posts in a thread. We need to add support in the UI.

Sure @vivekratnavel , I will add that.
