### ISSUE TITLE
Oracle database error because it cannot locate client library

### ISSUE THREAD

**Issue by Dennis8** [open-metadata/OpenMetadata#6404]
**Affected module**
It impacts the ingestion framework, which I attempted to start through the Web UI as described in the manual: https://docs.open-metadata.org/openmetadata/connectors/database/oracle.

**Describe the bug**
I'm trying to start the data ingestion from an Oracle database through the Web UI running on the latest docker-compose.yml
But I receive the error:
(cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: \"libclntsh.so: cannot open shared object file: No such file or directory\". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help\n(Background on this error at: https://sqlalche.me/e/14/4xp6)."}

**To Reproduce**
- Run the latest docker-compose.yml stack
- Open the Web UI and try to add an Oracle database ingestion through the Services page.
- Enter your credentials
- Test the connection
- Receive the error

**Expected behavior**
It will return that it has logged in or the credentials that are entered are incorrect.

**Version:**
 - OS: [e.g. iOS] Windows 10 Enterprise Version10.0.19042 Build 19042
 - Docker version: Desktop 4.10.1, Engine 20.10.17, Compose 2.6.1
 - Python version: In the docker image the Python version is 3.9.13
 - OpenMetadata version: [e.g. 0.8] 0.11.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] openmetadata/ingestion:0.11.3

**Additional context**
It might be worthwhile to further investigate the option to use the latest python-oracledb, which has an option to use a thin client and therefore does not depend on external Oracle client binaries.

**Comment by harshach** [comment]
@akash-jain-10 @ulixius9 is this resolved?

**Comment by ulixius9** [comment]
@harshach yes this issue is resolved as we have moved to [python-oracledb](https://oracle.github.io/python-oracledb/) library which doesn't require configuring oracle client libraries!
