### ISSUE TITLE
Add time series extension to store test results, profile, pipeline status etc..

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6414]
**Feature**
Currently we are adding test results as one big payload similar to how we store profile and pipeline status. This however is harder to showcase few results and paginate based on user selection.
 As part of this feature, we will be adding entity_extension_time_series and provide methods to list based on the start_ts and end_ts to results.

**Comment by TeddyCr** [comment]
@harshach is this fixed by #6416?
