### ISSUE TITLE
Ingestion, Profiler and Support Bot (JWT)

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6420]
We should have:
- Ingestion Bot
- Profiler Bot
- Support Bot -> 1h expiry for users to give us access and debug on their instance

Then, each workflow will have to point to the required bot, and automatically pick up the credentials from SM.

This way we will have different "service accounts" for different applications. It will also allow us to control better and grow the number of bots/applications, e.g., for data insights.

**Comment by pmbrull** [comment]
We will need to update how we pass the info to each workflow, just giving the bot name and then dynamically picking up the creds

**Comment by pmbrull** [comment]
After dicussing with @nahuelverdugo , a possible idea here as we now support the creation of bots with custom permissions, would be to update the UI to allow assign a specific bot when creating a workflow

cc @harshach

**Comment by pmbrull** [comment]
Ingestion, Profiler, Test... will be system-level bots. When creating different pipelines we will look for their names as constants. We will not allow high customization of pipelines' bots from users. We will handle all this process internally.

**Comment by harshach** [comment]
@nahuelverdugo can we add the remaining bots and assign to a workflow type?

**Comment by nahuelverdugo** [comment]
@harshach yes, for adding extra "system" bots, we just have to edit [this](https://github.com/open-metadata/OpenMetadata/blob/593ca3a4a0c73e28d5f821659f37e46f2fdf0726/openmetadata-spec/src/main/resources/json/schema/entity/bot.json#L14) Enum. Which workflows would require a different bot?

**Comment by nahuelverdugo** [comment]
@harshach I have added `test` and `profiler` bot. I think people with service accounts configured for the `ingestion-bot` will need to create two additional service accounts for these bots. Is it what we want?

**Comment by nahuelverdugo** [comment]
On hold until 0.14

**Comment by pmbrull** [comment]
I'll add a supportBot and keep the ingestion bot as is
