### ISSUE TITLE
Add LDAP Authorization

### ISSUE THREAD

**Issue by konnectr** [open-metadata/OpenMetadata#6428]
**Is your feature request related to a problem? Please describe.**
Can't use in production environment without authorization

**Describe the solution you'd like**

Add LDAP Authorization Capability

**Comment by konnectr** [comment]
Duplicate https://github.com/open-metadata/OpenMetadata/issues/3376

**Comment by mohityadav766** [comment]
hi @konnectr , i have recently raised a PR with support for LDAP 
It would really help if you give it a try, please let me know , i can help you in setting things up

**Comment by stepanof** [comment]
@mohityadav766 Hello! 
If you want I can test it, but I need instrustion how to switch my docker images to images with yours changes and also I need help with settings :)
