### ISSUE TITLE
UI - global search should show some default or initial results on launch

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#6445]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Currently Global search didn't bring any results.

**To Reproduce**
Enter Command + k

Screenshots or steps to reproduce
<img width="1631" alt="Screenshot 2022-07-30 at 1 58 46 AM" src="https://user-images.githubusercontent.com/12962843/181838489-10da485e-fe0e-4d3b-b52b-bd146c5c8294.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani it should show the searchbox itself. Later we can add saved searches etc
<img width="686" alt="image" src="https://user-images.githubusercontent.com/38649/182010710-03c4de22-7bf0-43c6-9a3a-7210587ce159.png">

**Comment by aniketkatkar97** [comment]
@chirag-madlani

**Comment by aniketkatkar97** [comment]
#6482
