### ISSUE TITLE
Can't deploy OpenMetadata on standard google kubernetes engine 

### ISSUE THREAD

**Issue by nabilm** [open-metadata/OpenMetadata#6452]
**Affected module**
Ingestion, airflow 

**Describe the bug**
Currently following https://docs.open-metadata.org/deployment/kubernetes is not working on standard GKE due to the fact that airflow requires a persistent disk with ReadWriteMany access mode.

the workaround is described here https://github.com/nabilm/openmetadata-gke

**To Reproduce**
Follow https://docs.open-metadata.org/deployment/kubernetes

**Expected behavior**
Airflow gets successfully on standard google Kubernetes engine cluster 

**Version:**
all versions 

**Additional context**
An automated fix using terraform, Kubernetes manifest need to be present

**Comment by akash-jain-10** [comment]
Closing this issue as we [documented](https://docs.open-metadata.org/deployment/kubernetes/gke) the steps to configure OpenMetadata Helm Charts on GKE. 

Thank you @nabilm for amazing contribution.
