### ISSUE TITLE
Java SDK throws IllegalArgumentException

### ISSUE THREAD

**Issue by Taurus-Le** [open-metadata/OpenMetadata#6455]
**Affected module**
Java SDK

**Describe the bug**
Trying to add lineage with java sdk. But got an illegal argument exception like this while following the steps in [doc](https://docs.open-metadata.org/sdk/java).
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid Version Given :0.11.1
	at org.openmetadata.core.util.VersionUtils.getVersionFromString(VersionUtils.java:37)
	at org.openmetadata.client.gateway.OpenMetadata.getClientVersion(OpenMetadata.java:111)
	at org.openmetadata.client.gateway.OpenMetadata.validateVersion(OpenMetadata.java:94)
	at org.openmetadata.client.gateway.OpenMetadata.<init>(OpenMetadata.java:62)
	at com.changle.openmetadatasdk.SDKTest.main(SDKTest.java:19)
```

**To Reproduce**

1、Create a maven project and add java SDK dependency.
2、Find a table using TablesApi as below:
```
OpenMetadataServerConnection connection = new OpenMetadataServerConnection();
connection.setHostPort("http://192.168.32.133:8585/api");
connection.setApiVersion("v1");
connection.setAuthProvider(OpenMetadataServerConnection.AuthProvider.NO_AUTH);
OpenMetadata openMetadata = new OpenMetadata(connection);
TablesApi tablesApi = openMetadata.buildClient(TablesApi.class);
Table table = tablesApi.getTableByFQN("FQN", "", "");
System.out.println(table.toString());
```

**Expected behavior**
Information of table should be printed in console.

**Version:**
 - OS: Windows 11
 - OpenMetadata version: 0.11.1
 - Java version: 11.0.15
 - Java SDK version: 0.11.1

**Additional context**
According to the source of `org/openmetadata/client/gateway/OpenMetadata.java` , version of catalog client was read from `/catalog/VERSION`  which is generated by buildnumber-maven-plugin. And below is the content of generated file:
```
#Created by build system. Do not modify
#Tue Jul 05 18:17:35 IST 2022
name=openmetadata-java-client
revision=418a5a47243eb3cc037113ae44343f4db3232071
timestamp=1657025255956
version=0.11.1
```
According to VersionUtils  in openmetadata-core-0.11.1, the illegalArgumentException  will be thrown if version dose not contain a "-" .
```
public static String getVersionFromString(String input) {
    if (input.contains("-")) {
        return input.split(Pattern.quote("-"))[0];
    } else {
        throw new IllegalArgumentException("Invalid Version Given :" + input);
    }
}
```

**Comment by mohitdeuex** [comment]
Fixed
