### ISSUE TITLE
Dag Home folder pointing to examples folder

### ISSUE THREAD

**Issue by allegoricalJest** [open-metadata/OpenMetadata#6523]
**Affected module**
Ingestion Framework

**Describe the bug**
Docker Default Dag folder points to /ingestion/examples/airflow/dags rather than /airflow/dags

**To Reproduce**

Deploy any version of docker OM

**Expected behavior**
Dags should be stored in /airflow/dags and airflow should be reading them from that location as well

**Version:**
 - OS: Ubuntu 22.04 LTS
 - Python version:  3.10.4
 - OpenMetadata version: 0.11.3 and up
 - OpenMetadata Ingestion package version: 0.11.3 and up
 
**Additional context**

**Comment by harshach** [comment]
@akash-jain-10 @vijaypm we need to have dags folder configurable. In this case, @allegoricalJest mounted volumes to the docker and export AIRFLOW_HOME didn't changed the dags folder location. We had to copy airflow.cfg to the mounted volume and adjust the config to point to the right location

**Comment by Vj-L** [comment]
This is done [](https://github.com/open-metadata/OpenMetadata/pull/6759)
