### ISSUE TITLE
Profiler always requires sending columnProfile when we just need table level data

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6529]
From https://openmetadata.slack.com/archives/C02B6955S4S/p1656658286663549

If we want just to send table-level data, we still need to pass `columnProfile: []`:

```
//This succeeds
"tableProfile": [
  {
    "profileDate": "2021-10-18",
    "rowCount": 1909,
    "columnProfile": []
  }
],

//This fails with NPE on Backend
"tableProfile": [
  {
    "profileDate": "2021-10-18",
    "rowCount": 1909,
  }
],
```

We could mark the columnProfile as optional

**Comment by TeddyCr** [comment]
@pmbrull this will be fixed by https://github.com/open-metadata/OpenMetadata/pull/6416 🙂

**Comment by pmbrull** [comment]
oooh thank you @TeddyCr (L)
