### ISSUE TITLE
Use python-oracledb instead of cx-oracle

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#6530]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Container Image

**Describe the bug**
Currently, Ingestion Container does not support Oracle Connector due to missing instant client libraries.
A potential fix to try out is swap usage of cx-oracle python library with python-oracledb.

**Comment by pmbrull** [comment]
https://oracle.github.io/python-oracledb/
