### ISSUE TITLE
Documentation or Tutorial Requests！！

### ISSUE THREAD

**Issue by zhangtt9537** [open-metadata/OpenMetadata#6539]
Dear developers, first of all I am very interested in this project, but I have some problems when I perform local deployment, I will be very grateful if the developers can reply to me.The tutorial of the reference documentation of this open source project is behind the code. If possible, the documentation can be updated in time. At present, I can start the service locally, but the ingestion module cannot connect to airflow through rest-api. The ingestion module uses the official image provided. Thank you very much.

**Comment by sureshms** [comment]
@zhangtt9537 we are continuously improving the documentation. We encourage community participation in doing the same. Please do bring up specific issues as a lot of docs have already been updated.
