### ISSUE TITLE
Install openmetadata in a subpath

### ISSUE THREAD

**Issue by irbian** [open-metadata/OpenMetadata#6541]
**Is your feature request related to a problem? Please describe.**
I´m not sure if it´s a feature request or simply that I don´t know how but I would like to know how to install openmetadata under a subpath

**Describe alternatives you've considered**
We have considered using subdomains or ports, but that is not an option because how we handle our certificates and main page structure

**Comment by irbian** [comment]
any info on this?

**Comment by harshach** [comment]
@irbian please join our slack to ask such questions https://slack.open-metadata.org. Github issues are there to track actual bugs or features
