### ISSUE TITLE
Ingest more metadata from DBT

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#6548]
DBT allows to add much more metadata to its assets than only column names and descriptions and lineage.

In particular it allows to specify data owners, additional key-value metadata pairs and so on:

- https://docs.getdbt.com/reference/resource-configs/meta

In fact with the recent upgrade around exposures:
- https://github.com/gouline/dbt-metabase
- https://docs.getdbt.com/docs/building-a-dbt-project/exposures

several BI visualization tools started to integrate around these features (metabase, mode, looker, superset) 

- https://github.com/slidoapp/dbt-superset-lineage
- https://mode.com/get-dbt/
- https://www.getdbt.com/blog/how-to-integrate-dbt-and-looker-with-user-attributes/

It would be great if open-metadata could ingest these additional attributes as well.

**Comment by geoHeil** [comment]
https://openmetadata.slack.com/archives/C02B6955S4S/p1659539501092759?thread_ts=1659537963.701169&cid=C02B6955S4S  DBT`s `schema.yaml` which is defining documentation around column metadata does not seem to be imported as well. I think this would be most important to get these semantics imported.

**Comment by geoHeil** [comment]
One more great missing integration is `dbt test`. Ideally, one does not need to define additional tests in OpneMetadata - rather the ones from DBT can be integrated.

**Comment by pmbrull** [comment]
DBT tests will be added in https://github.com/open-metadata/OpenMetadata/issues/6135

**Comment by pmbrull** [comment]
Created https://github.com/open-metadata/OpenMetadata/issues/6801 to follow up on column descriptions as well as owner.

we will use this issue to discuss on custom properties from the ingestion

**Comment by OnkarVO7** [comment]
Hi @geoHeil
We are adding below features in our DBT integration as a part of `0.12.1` release

- Ingesting DBT Tests and test results information
- Assigning owner to a model/table in OpenMetadata from DBT. [Docs Link](https://docs.open-metadata.org/openmetadata/ingestion/workflows/metadata/dbt/ingest-dbt-owner)
- Adding table level and column level tags from DBT to OpenMetadata
- Adding a control on whether table and column descriptions from DBT should overwrite the already present descriptions

We will be taking into consideration the other features listed in this issue for our `0.13` release.
Thank you for your contribution and let us know if you have any doubts/queries.

**Comment by harshach** [comment]
@OnkarVO7 what is remaining to close this ticket?

**Comment by OnkarVO7** [comment]
@harshach let me make an aggregate list of the things remaining and will update here

**Comment by mingfang** [comment]
ingesting exposure and metrics would be amazing. thanks

**Comment by harshach** [comment]
@OnkarVO7 please provide an update here

**Comment by pmbrull** [comment]
hi @OnkarVO7 if you could please confirm, owner and tags from `meta` fields are already being ingested. The only missing point from this issue is around `exposures`. Is that correct?

**Comment by OnkarVO7** [comment]
@pmbrull yes owner and tags have been implemented

**Comment by pmbrull** [comment]
Thanks, then I'll be closing this issue and listing down `exposures` in the EPIC https://github.com/open-metadata/OpenMetadata/issues/8486
