### ISSUE TITLE
Build fails on X86 with java 17

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#655]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.779 s <<< FAILURE! - in org.openmetadata.catalog.resources.usage.UsageResourceTest
[ERROR] org.openmetadata.catalog.resources.usage.UsageResourceTest  Time elapsed: 8.779 s  <<< ERROR!
java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class org.skife.jdbi.cglib.proxy.Enhancer
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.skife.jdbi.cglib.proxy.Enhancer

**Comment by harshach** [comment]
Thanks for reporting this @juliarvalenti @pmbrull

**Comment by sureshms** [comment]
Looks like cglib uses non-public Java methods which are disallowed by default in Java 16 and 17. See the discussions here - https://github.com/cglib/cglib/issues/191. 

Currently, there is no decent workaround. Let's document we don't support Java  16 and 17.

**Comment by sureshms** [comment]
@harshach, is this still an issue?
