### ISSUE TITLE
Add support for PostGIS geometry type

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#6550]
When ingestion a PostGIS table with a column of type Geometry OpenMetadata emits a warning:

```
/source/database/sql_column_handler.py:174: SAWarning: Did not recognize type 'geometry' of column 'geom'
  columns = inspector.get_columns(table_name, schema_name, db_name=db_name)
```

Instead of using the correct type geometry  the metadata of VarChar is stored

**Comment by geoHeil** [comment]
Ideally, you could parse the CRS attribute from it as well.

**Comment by NiharDoshi99** [comment]
Hello , I will work on this issue.
