### ISSUE TITLE
Support for AWS-delegated credentials for Elasticsearch

### ISSUE THREAD

**Issue by abcabhishek** [open-metadata/OpenMetadata#6559]
**Is your feature request related to a problem? Please describe.**
Currently, Elasticsearch configuration has an optional field to input `username` and `password` credentials for the Elasticsearch instance. For AWS-managed instances, not all customers create a master user and password. 

This Feature Request is to delegate the credentials handoff using boto3 for python clients. There could be a flag when setting up the config `useAWSCredentials: bool` which would use credentials from the container (code sample below) and AuthN to the Elasticsearch instance.

**Describe the solution you'd like**
An alternate methodology to authN to the ES Instance from a service would be using the `boto3 Session` credentials stored by default in every container. The role delegated to the container determines if the credentials being used can access the service instead of using an explicit username and password. 

Using this solution `AWS4Auth` library would enable customers to do hands-off delegation of credentials.

**Describe alternatives you've considered**
NA

**Additional context**
Relevant code context:
```
        from elasticsearch import Elasticsearch, RequestsHttpConnection

        credentials = boto3.Session().get_credentials()

        http_auth = AWS4Auth(region='us-east-1', service='es', refreshable_credentials=credentials)

        self.elasticsearch_client = Elasticsearch(
            [
                {"host": self.config.es_host, "port": self.config.es_port},
            ],
            http_auth=http_auth,
            scheme=self.config.scheme,
            use_ssl=self.config.use_ssl,
            verify_certs=self.config.verify_certs,
            ssl_context=ssl_context,
            ca_certs=self.config.ca_certs,
            connection_class=RequestsHttpConnection //Required for compatibility with AWS4Auth delegated creds
        )
```

**Comment by pmbrull** [comment]
Thanks for opening this, we'll be bringing that on 0.12. Thanks
