### ISSUE TITLE
Allow consumers of Openmetadata-ingestion to define custom connectors in their own package with same namespace

### ISSUE THREAD

**Issue by abcabhishek** [open-metadata/OpenMetadata#6560]
**Is your feature request related to a problem? Please describe.**
As a consumer of Openmetadata-ingestion package,  I want to add my custom connectors within the same namespace but in a different package repository.

Consider a situation below:

```
├─my_code_repository_package
  ├── src
      ├── my_other_relevant_code_package
      ├── metadata
      │   └── ingestion
      │       └── source
      │        └── database
      │         └── my_awesome_connector.py
      └── setup.py
├── openmetadata_ingestion
  ├── src
      ├── metadata
      │   └── ingestion
      │       └── source
      │        └── database
      │         └── existingSource1
      |         └── existingSource2
      |         └── ....
      └── setup.py

```
I want `my_awesome_connector.py` to build as a source and run as a part of workflows defined in `openmetadata_ingestion`

**Describe the solution you'd like**
Clear set of steps to achieve this and also how to index the same on IDE

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by pmbrull** [comment]
Thanks for the details @abcabhishek.

This will be a growing need for the community, so we'll test it out and land it in the docs
