### ISSUE TITLE
MSSQL Lineage query

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6564]
From the MSSQL Query:

```
      SELECT
        db.NAME database_name,
        t.text query_text,
        s.last_execution_time start_time,
        DATEADD(ms, s.total_elapsed_time, s.last_execution_time) end_time,
        NULL schema_name,
        NULL query_type,
        NULL user_name,
        NULL aborted
      FROM sys.dm_exec_cached_plans AS p
      INNER JOIN sys.dm_exec_query_stats AS s
        ON p.plan_handle = s.plan_handle
      CROSS APPLY sys.Dm_exec_sql_text(p.plan_handle) AS t
      INNER JOIN sys.databases db
        ON db.database_id = t.dbid
      WHERE s.last_execution_time between '{start_time}' and '{end_time}'
          AND t.text NOT LIKE '/* {{"app": "OpenMetadata", %%}} */%%'
          AND t.text NOT LIKE '/* {{"app": "dbt", %%}} */%%'
          AND s.Prepared != 'Prepared'
      ORDER BY s.last_execution_time DESC
```

I am not able to find `CREATE` or `INSERT` queries. Looks like MSSQL might be breaking those down into multiple internal calls (you will see them if you comment out `s.Prepared != 'Prepared'`).

Let's validate if MSSQL offers raw query execution somehow and update the query if needed

**Comment by sfirke** [comment]
I don't have any lineage displayed for my MSSQL views except for the view itself.  Does this issue mean that lineage ingestion is currently missing for MSSQL?  I just created a lineage ingestion and ran it successfully several times.

**Comment by pmbrull** [comment]
hi @sfirke the python connector is there but I am not sure it is bringing in the right information. Last time I checked the query we are using I was not seeing the queries properly (body of the ticket). So even if you run that you might be missing lineage results as there's no ingredients to properly parse.

This issue is about finding a better query candidate

**Comment by ulixius9** [comment]
closing this issue as the query fetches insert & create queries also the lineage from the same is generated
