### ISSUE TITLE
Backend: Add isActive flag to announcements response

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6583]
**Feature**
It will be good to have the `isActive` flag in the announcements list API

**Comment by harshach** [comment]
shouldn't this be drive from start and end date?

**Comment by vivekratnavel** [comment]
@harshach Yes, I think that will be much easier on the client side. 

@Sachin-chaurasiya If you can compare the current UTC time with the announcement start and end time, you can determine `isActive`.  What do you think?

**Comment by Sachin-chaurasiya** [comment]
> @harshach Yes, I think that will be much easier on the client side.
> 
> @Sachin-chaurasiya If you can compare the current UTC time with the announcement start and end time, you can determine `isActive`. What do you think?

@vivekratnavel, I think both ways will work, I can compare the start and end date with the current UTC to drive the `isActive`.
