### ISSUE TITLE
deploy error 

### ISSUE THREAD

**Issue by zhangtt9537** [open-metadata/OpenMetadata#6600]
When I execute the interface http://localhost:8080/rest_api/api?api=deploy_dag, I will get the following error.

{"error": "Internal error deploying None - metadata.generated.schema.entity.services.ingestionPipelines.ingestionPipeline.IngestionPipeline() argument after ** must be a mapping, not NoneType - Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/openmetadata/api/rest_api.py\", line 178, in deploy_dag\n    ingestion_pipeline = IngestionPipeline(**json_request)\nTypeError: metadata.generated.schema.entity.services.ingestionPipelines.ingestionPipeline.IngestionPipeline() argument after ** must be a mapping, not NoneType\n"}
And the airflow page will also have corresponding error prompts

![image](https://user-images.githubusercontent.com/64458688/183034544-ca10d097-f378-4726-af06-a6a1daa9b65b.png)

**Comment by sureshms** [comment]
@zhangtt9537, please use [Slack support channel ](https://slack.open-metadata.org)to get help on this. Creating an issue for this can be done if a bug is identified. Closing this issue for now.
