### ISSUE TITLE
User cannot authenticate after upgrading OM to 0.11.4

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#6602]
**Affected module**
UI 

**Describe the bug**
After upgrading to 0.11.4, i cannot login to OM using Google SSO.

**To Reproduce**

1 - Go to OM
2 - Click on **Sign in with Google**
3 - 
![Capture d’écran 2022-08-05 à 11 24 43](https://user-images.githubusercontent.com/75131226/183047241-386a4446-7a85-4cf7-82e0-a8fd215ba3f7.png)

**Expected behavior**
Redirect to the main page.

**Version:**
 - OpenMetadata version: 0.11.4

**Additional context**

**Comment by haithem-souala** [comment]
No errors in logs or in the browser console.

**Comment by chirag-madlani** [comment]
Fixed and available on `0.11.4` with latest commit: https://github.com/open-metadata/OpenMetadata/pull/6599

**Comment by haithem-souala** [comment]
> Fixed and available on `0.11.4` with latest commit: #6599

i've the issue on 0.11.4.

**Comment by haithem-souala** [comment]
Working again, thx!
