### ISSUE TITLE
UI: Show User timezone for announcements

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6621]
One major UX improvement would be to convert the timezone automatically. While creating the announcement, if we can display the user timezone and get input for start time and end time in the user time zone, that will be great. The server will accept and respond only in UTC. So, while rendering the Schedule for announcement anywhere in the UI (Activity Feed, Right Side Drawer, etc.), we can convert the UTC time to the user timezone and display it. This way the users will never have to think about UTC.

**Comment by Sachin-chaurasiya** [comment]
@vivekratnavel , Currently For StartTime and EndTime we are using `datetime-local`, which will be date and time without any timezone and finally we convert it into UTC date time.
It will be great If you could provide some examples of what we are precisely expecting here.

**Comment by vivekratnavel** [comment]
With [moment timezone](https://momentjs.com/timezone/), we can convert timestamps that we get from the server response (UTC) to the user's local timezone for displaying the schedule of each announcement. In the same way, while making a new announcement, we can get the input for start time and end time in the local timezone and convert it to UTC before sending the request to the server. This way user does not have to schedule announcements in UTC.

**Comment by chirag-madlani** [comment]
Please follow mm/dd/yyyy format for all the dates
