### ISSUE TITLE
High Level Design documentation starting paragraph has a typo

### ISSUE THREAD

**Issue by rameeshm** [open-metadata/OpenMetadata#6623]
High Level Design documentation starting paragraph has a typo
While reading the high level design documentation found a  typo.  It is starting with "Thi" instead of "This" i suppose.  A
https://docs.open-metadata.org/main-concepts/high-level-design
lso would like to contribute to Open Metadata project. Thanks.

**Comment by sureshms** [comment]
@rameeshm this issue looks like has been fixed. Feel free to reopen the issue, if it still exists.
