### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by ankumar** [open-metadata/OpenMetadata#6630]
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.

https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/api/data/createmlmodel

think it's ML & not MI

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

**Comment by sureshms** [comment]
In the code per the naming convention, we are using mlModel etc. Thre is one instance Ml that is incorrect while the other instances rightly use ML in the documentation.

**Comment by sureshms** [comment]
Closing this issue.
