### ISSUE TITLE
Backend: Team FQN should have its hierarchy reflected

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6636]
**Feature**
Today, the team FQN has only the name of the team. If the FQN reflects team hierarchy such as `org_name.bu_name.division_name.dept_name.group_name`, then the UI can pick it up and display Team name as `org_name > bu_name > division_name > dept_name > group_name` in the dropdowns.

**Comment by harshach** [comment]
@vivekratnavel a team belong to multiple organizations as parent, hence the reason we are not doing the FQN.
@sureshms not sure if we can assume a team has only one parent. In the UI we are not supporting adding a team to multiple parents

**Comment by vivekratnavel** [comment]
@harshach We can close this issue since we now support team hierarchy API and will not need this FQN support
