### ISSUE TITLE
REST APIs should throw error in same format

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#664]
For instance, we are getting error for api `/api/v1/services/{service-name}/{id}` as below
```
{
    message: "{some error message}"
}
```
which is readable on client-side, but for api `/api/v1/services/{service-type}` it gives whole Java exception as error
```
Error: Request failed with status code 400
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:17)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:62)
```
which is not readable on client-side

Expected: All APIs should give errors in same format that is readable on client-side, either `JSON` or `String`

**Comment by sureshms** [comment]
@darth-coder00, this is no longer relevant, right? Can we close this?
