### ISSUE TITLE
Check MSSQL with windows authentication

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#6645]
**Affected module**
Ingestion Framework

**Describe the bug**
Check MSSQL with windows authentication
slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1659447513402549

**Comment by NiharDoshi99** [comment]
I will take this issue.

**Comment by pmbrull** [comment]
hi @NiharDoshi99 do you have any updates on this? Would you need any help? It would be great to ship this for 0.12 as some users are relying on this change.

Thanks!

**Comment by NiharDoshi99** [comment]
Hi @pmbrull , working on https://github.com/open-metadata/OpenMetadata/issues/6563 it will be completed by today. Will take the above issue after that.

**Comment by pmbrull** [comment]
perfect thanks
