### ISSUE TITLE
UI: Add useful hint for Sample Data

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6656]
Instead of showing simply "No Sample Data available", we should show some useful hints on how to get the sample data populated. Something like "To see Sample Data, run the Profiler Ingestion. To schedule Profiler Ingestion, refer to these docs."

<img width="1705" alt="Screen Shot 2022-08-08 at 3 06 53 PM" src="https://user-images.githubusercontent.com/1051198/183523233-4b3c93b1-2426-4aa6-9026-4a1f2eff5b51.png">
 
 
cc @ShilpaVernekar to help with the text

**Comment by ShilpaVernekar** [comment]
Sorry, I missed noticing this...
Here's the edited text
To view Sample Data, run the Profiler Ingestion. Please refer to this doc to schedule the [Profiler Ingestion](https://docs.open-metadata.org/openmetadata/ingestion/workflows/profiler)
