### ISSUE TITLE
Feature Request - Data Quality - Moove.io

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#6662]
Sample Data and Quality test results to be downloaded in csv/excel format.

**Comment by lailapatel** [comment]
Please share the status for this feature.

**Comment by lailapatel** [comment]
Hi @TeddyCr @pmbrull @harshach

**Comment by TeddyCr** [comment]
@lailapatel I believe you are referring to a different issue. Could share the type for your column `date` as it appears in OpenMetadata and confirm the version as well?

**Comment by lailapatel** [comment]
@TeddyCr 
yes the date test suite case is for ticket 6704

**Comment by lailapatel** [comment]
Hi @TeddyCr 

Thanks for the update that row level test results are in roadmap.

@harshach @sureshms 

Would like to request if we can prioritize this feature.

**Comment by TeddyCr** [comment]
This feature will be part of Collate offering
