### ISSUE TITLE
Feature Request- Integration with QuickSight and Google Sheet- Moove.io

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#6663]
Integration with QuickSight Dashboard.

Integration with GoogleSheet.

**Comment by pmbrull** [comment]
Hi @lailapatel , quicksight has already been implemented in 0.13

**Comment by lailapatel** [comment]
Hi @pmbrull ,

Can you please recheck the QuickSight part? As upon creating the connection, none of the technical fields are being asked for building of the connection.

![image](https://user-images.githubusercontent.com/110607559/205843575-ca44ac62-7cd6-4d10-ace6-11f95b044d85.png)
![image](https://user-images.githubusercontent.com/110607559/205844209-77fe157c-ae74-4186-a8a7-6c3d5bfd326e.png)

**Comment by lailapatel** [comment]
Kindly consider this fixing for 13.1.

**Comment by pmbrull** [comment]
hi @lailapatel, please pull again the 0.13.0 server image. We did an in place release with the fixes 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/35870520/205911349-95d7cf4e-2a1b-4eba-a70a-02f74181803a.png">

Thanks

**Comment by lailapatel** [comment]
Hi @pmbrull

**Comment by lailapatel** [comment]
Hi @pmbrull  @ayush-shah @ShaileshParmar11 

facing the below error upon adding QuickSight. Parameters which are passed are access key, secret key, region and AWS account id.

Kindly resolve this urgently.

![image](https://user-images.githubusercontent.com/110607559/211295198-3275a01c-15af-4812-bb1b-e00304986f9d.png)

**Comment by pmbrull** [comment]
hi @lailapatel this issue has been fixed and will be part of the next release. Thanks

**Comment by lailapatel** [comment]
@ayush-shah @pmbrull we would be needing an urgent fix.

@ayush-shah please share the dev environment fix, as discussed yesterday

**Comment by pmbrull** [comment]
@lailapatel pinged on Slack. We can continue the discussion there

**Comment by lailapatel** [comment]
@pmbrull thank you for your support.

**Comment by lailapatel** [comment]
@pmbrull since we are setting our production instance, therefore we would be relying on upcoming release (13.2) for QuickSight fix.

**Comment by pmbrull** [comment]
we're doing some last validations and improvements. Everything should be in good shape for 0.13.2. Thansk

**Comment by ayush-shah** [comment]
creating a child ticket to tackle quicksight related issues

**Comment by ayush-shah** [comment]
here is the sub ticket to keep track of quicksight https://github.com/open-metadata/OpenMetadata/issues/9755
