### ISSUE TITLE
Backend : Add support for policy evaluation API

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#6681]
On Add role page we are allowing users to select multiple policies and on UI we want to show the evaluation of selected policies like this.
![image](https://user-images.githubusercontent.com/59080942/183881915-04b7f5b5-d4ef-45d2-af99-bac5d1261eb3.png)
To achieve this UI will need API support where UI will pass the list of policies and in response backend will be sending evaluation for passed policies.

**Comment by harshach** [comment]
@sureshms are we taking this up for this release?

**Comment by sureshms** [comment]
@harshach ack. Will get it done for the release 0.13.
