### ISSUE TITLE
Assets Certification Workflow

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#6684]
**Is your feature request related to a problem? Please describe.**
Add possibility to certify tables, dashboards or term, that will be useful  to identify quickly read-to-use assets.

**Comment by haithem-souala** [comment]
UNCERTIFIED (for every new assets) -------> IN REVIEW --------------------> CERTIFIED

**Comment by harshach** [comment]
hi @haithem-souala wouldn't you be able to use Tags or Glossary to achieve the same. Could you elaborate on what workflow you are looking if not for tagging

**Comment by haithem-souala** [comment]
I agree, create a new tag category would achieve to same.
Thank you @harshach
