### ISSUE TITLE
Make Glossary names editable

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#6694]
**Is your feature request related to a problem? Please describe.**
Once a glossary has been created, it's impossible to rename it. This is frustratring as the entire glossary has to be deleted, will all it's sub-terms

**Describe the solution you'd like**
Make glossary terms editable.

**Comment by ShaileshParmar11** [comment]
With OM version 0.12 we are supporting the edit feature for glossary and glossary terms based on permissions!
