### ISSUE TITLE
Implement Authorization Code Flow for custom OIDC

### ISSUE THREAD

**Issue by k-popov** [open-metadata/OpenMetadata#6699]
**Is your feature request related to a problem? Please describe.**
Currently OpenMetadata only supports implicit grant flow for custom OIDC authentication variant.
Many sources recommend to switch to authorization code flow, e.g. https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#prefer-the-auth-code-flow or https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead#the-oauth-authorization-code-flow-is-better
Besides that some OIDC providers do not support implicit grant flow, e.g. Gitlab: https://docs.gitlab.com/ee/api/oauth2.html#implicit-grant-flow-removed

**Describe the solution you'd like**
Authorization Code Flow is supported by OpenMetadata for custom OIDC authentication option.

**Comment by chirag-madlani** [comment]
Duplicate #13773
