### ISSUE TITLE
Unable to add multiple new user in teams page

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#670]
On the team's page, I am not able to add multiple new users it gives a 500 Internal Server Error, but on other hand, I am able to add a single new user. I have explain the scenario to @darth-coder00

**Comment by ShaileshParmar11** [comment]
**single-user API call**

![image](https://user-images.githubusercontent.com/71748675/136321490-52470d8d-b43b-4c3a-b9cc-24e0aa89b5dc.png)

![image](https://user-images.githubusercontent.com/71748675/136321527-0b76456d-cba0-4aae-805d-241796230e28.png)


**Multi-user API call**

![image](https://user-images.githubusercontent.com/71748675/136322695-936cb7ac-39e8-4f70-9b22-34329a006f50.png)

![image](https://user-images.githubusercontent.com/71748675/136322730-beb47949-9d96-4378-b23d-9404a96dfbc0.png)

![image](https://user-images.githubusercontent.com/71748675/136322766-18558028-9839-4b7e-830e-e5b392834a05.png)

![image](https://user-images.githubusercontent.com/71748675/136322873-47162a94-f38d-4eec-86bb-9e9567a370a9.png)

```{"responseMessage":"An exception with message ['[{\"id\":\"2808eb23-a209-4847-b2d9-035b580c0fd6\",\"type\":\"user\",\"name\":\"amanda_phillips7\",\"description\":\"Amanda Phillips\"},{\"id\":\"95a3c28f-67f2-4237-9f16-8e24349b8de6\",\"type\":\"user\",\"name\":\"aaron_mcgee8\",\"description\":\"Aaron Mcgee\"}]' contains no element for index 3 and for '3'.] was thrown while processing request."}```

**Comment by vivekratnavel** [comment]
I think it is because of the reverse sorting done in the [applyPatch](https://github.com/open-metadata/OpenMetadata/blob/8ccb8624e48a627f8bd1234ae0bfc1b7e61403d2/catalog-rest-service/src/main/java/org/openmetadata/catalog/util/JsonUtils.java#L120). I am happy to take this up and provide a PR soon.

**Comment by vivekratnavel** [comment]
I am unable to assign it to myself. Can someone please assign this issue to me?
