### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#6701]
Settings Page

- [x] Left panel styling (stroke and shadow) (Update it as per the styling on other pages)
- [x] Add more margin b/w left panel and content 
- [x] Manage button width to be in 1:1 ratio
<img width="34" alt="Screenshot 2022-08-12 at 8 04 13 AM" src="https://user-images.githubusercontent.com/103238069/184274448-c2d462f6-f2f8-4f66-8806-21bb8ce6d2d7.png">

- [x] Change icon colour of selected section colour to primary colour and font weight semi-bold
- [x] Move “Teams, User and Admins” to new category 
- [x] Reduce delete button switch size
<img width="155" alt="Screenshot 2022-08-12 at 8 22 50 AM" src="https://user-images.githubusercontent.com/103238069/184276242-2e0c563d-cc43-41bc-9130-3c722ceea0e2.png">

- [x] Maintain top margin
<img width="406" alt="Screenshot 2022-08-12 at 8 01 50 AM" src="https://user-images.githubusercontent.com/103238069/184274213-02c8a3b1-df55-4ad3-a4cd-1801a0ba422f.png">

- [ ] #6791
- [x]  Reduce table column height

- [x] update edit icon 
![Edit](https://user-images.githubusercontent.com/103238069/184277747-f4dabee9-53a4-46ae-8eab-33a79761b269.svg)

- [x]  need to fix the read more button here
<img width="866" alt="Screenshot 2022-08-12 at 8 26 03 AM" src="https://user-images.githubusercontent.com/103238069/184276576-89606970-aa35-4d6d-9d8d-7e30b67238c2.png">

- [ ] Left column Position and width should be consistent, currently it's different on explore page, settings page and glossary page (Should be consistent as on home page)

- [x] Update filter styling on Webhook as on home page

- [x] Search bar needs fixing on Webhook

**Comment by Sachin-chaurasiya** [comment]
- [ ] The search box is getting shrink
![image](https://user-images.githubusercontent.com/59080942/184805664-b8611126-ccd6-4e48-80c3-1a7eb4d5a210.png)

**Comment by Sachin-chaurasiya** [comment]
- [ ] Order should be Explore, Glossary, Tags and Settings
![image](https://user-images.githubusercontent.com/59080942/184807302-e85d75b8-f3c8-461c-a23b-abf9b9c39a13.png)

**Comment by devyani-kaushik** [comment]
- [ ]  Bot creation form tyling should be consistent with "Add Service" Styling
<img width="817" alt="Screenshot 2022-08-17 at 9 47 03 AM" src="https://user-images.githubusercontent.com/103238069/185033585-c3513c05-864e-4f1d-aab1-302c9dd2541c.png">

- [ ] Add "webhook" and "slack" form styling needs to be fixed, it has a white background
<img width="1439" alt="Screenshot 2022-08-17 at 9 52 16 AM" src="https://user-images.githubusercontent.com/103238069/185034130-8053615e-c54d-4a80-b791-dc74caf8c9a9.png">

- [ ]  User cards are not aligned properly when you add new user to a team
<img width="772" alt="Screenshot 2022-08-17 at 9 54 31 AM" src="https://user-images.githubusercontent.com/103238069/185034337-982ed535-966a-4000-835e-cf4c79e40943.png">

- [ ]  Add new user form styling isn't consistent to other forms.

- [ ] Need to have consistent switch button styling (different icon is being used on settings pages, please use the one in forms like on add user form)
<img width="50" alt="Screenshot 2022-08-17 at 9 57 23 AM" src="https://user-images.githubusercontent.com/103238069/185034623-3e19f917-03ca-4fe4-936a-b8bcd4fb637f.png">

- [ ] nothing is happening on the click of "Add Policy" 
<img width="1156" alt="Screenshot 2022-08-17 at 10 07 27 AM" src="https://user-images.githubusercontent.com/103238069/185035849-94d40792-f1a3-41d6-bb3f-8f66a2551a1d.png">

- [ ]  Need to work on the UI and UX of the forms, it isn't consistent.
<img width="1437" alt="Screenshot 2022-08-17 at 10 09 03 AM" src="https://user-images.githubusercontent.com/103238069/185036020-99ca2392-b86b-43b1-8463-fdd467243a5a.png">

- [ ] Assignee should be clickable here
<img width="233" alt="Screenshot 2022-08-17 at 10 14 30 AM" src="https://user-images.githubusercontent.com/103238069/185036594-0ab6fe63-88ef-4f25-aac5-001abb5eec15.png">

- [ ] Spacing not right on user page
<img width="288" alt="Screenshot 2022-08-17 at 10 18 44 AM" src="https://user-images.githubusercontent.com/103238069/185037034-059d48ac-af1e-471a-acd9-f3c764cfdf73.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Add down and up key support for suggestion dropdown
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/59080942/185038752-db965155-2013-487d-8402-0e977be0779c.png">

**Comment by ulixius9** [comment]
- [ ] progress bar missing on ingestion deployment 

https://user-images.githubusercontent.com/39544459/185592476-193f1a0e-1e91-4b5e-9602-4c7aea7e0b5d.mov

**Comment by chirag-madlani** [comment]
#6210

**Comment by Sachin-chaurasiya** [comment]
Glossary page left panel issue.
https://github.com/open-metadata/OpenMetadata/issues/6834#issuecomment-1223577243

**Comment by Sachin-chaurasiya** [comment]
Pending issues are tracked, individual.
#6854 
#6791

**Comment by devyani-kaushik** [comment]
- [ ]  Manage button styling on team detail page is not consistent 
<img width="80" alt="Screenshot 2022-08-24 at 8 49 44 AM" src="https://user-images.githubusercontent.com/103238069/186315437-3eae7ec6-6c69-4014-b67a-36703367a0ca.png">

- [ ] Replace Delete Icon with Remove icon 
![Remove](https://user-images.githubusercontent.com/103238069/186317616-2a58abe8-0ff1-41a3-a36b-8d3246a0b038.svg)
<img width="110" alt="Screenshot 2022-08-24 at 8 51 39 AM" src="https://user-images.githubusercontent.com/103238069/186316694-4a589dc0-940a-4f33-901e-15bb8a5717a4.png">

- [ ] Owner's link on teams page not working, either not re-directing or giving a 404 error
- [ ] Add a breadcrumb link to the main user listing page on create user form
<img width="147" alt="Screenshot 2022-08-24 at 8 55 55 AM" src="https://user-images.githubusercontent.com/103238069/186319734-e931bcb5-1649-4bf9-a639-24b6f900d18c.png">
 

- [ ] Can we keep the styiling in image 1 same as it is in image 2
Image 1
<img width="1431" alt="Screenshot 2022-08-24 at 8 59 53 AM" src="https://user-images.githubusercontent.com/103238069/186322013-c5d6444e-5340-4f6e-9792-87c9002fbdef.png">
Image 2
<img width="1381" alt="Screenshot 2022-08-24 at 9 01 13 AM" src="https://user-images.githubusercontent.com/103238069/186322564-3190660c-639e-4d1e-b133-c10d89ab90c5.png">

- [ ] "Database Service" click is redirecting to the old Service page
<img width="252" alt="Screenshot 2022-08-24 at 9 01 57 AM" src="https://user-images.githubusercontent.com/103238069/186322641-2bd1b2cb-bac0-4d8c-82f1-0c13c884da85.png">

- [ ] mlflow logo is stretched over here
<img width="740" alt="Screenshot 2022-08-24 at 9 04 19 AM" src="https://user-images.githubusercontent.com/103238069/186322885-6552f635-789d-48e3-bdee-4ee8db14287b.png">

- [ ] Service type (Breadcrumb) click on add service form is redirecting to the old Service page

- [ ] Can we list these chips in 1 line below the filter option instead of filtering it inside on "Webhook" and "Slack" page
<img width="273" alt="Screenshot 2022-08-24 at 9 09 28 AM" src="https://user-images.githubusercontent.com/103238069/186323420-33a8d938-b98f-4109-b61c-68f302142c16.png">

**Comment by harshach** [comment]
@devyani-kaushik lets open a new ticket for this
