### ISSUE TITLE
Redirection on docs page for Connectors from profiler tab is not proper.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#6702]
**Affected module**
UI

**Describe the bug**
When clicked on "here" in profiler tab for entity details page, we get 404 as we redirect to /connectors.

**To Reproduce**
<img width="896" alt="Screenshot 2022-08-12 at 10 00 17 AM" src="https://user-images.githubusercontent.com/51777795/184285971-079d9783-973e-40f8-b3ad-bb5f7b988abd.png">
<img width="958" alt="Screenshot 2022-08-12 at 10 00 33 AM" src="https://user-images.githubusercontent.com/51777795/184285989-0974a7db-0a0c-4f69-a649-da77bac5cca1.png">

**Expected behavior**
It should redirect to /openmetadata/connectors
<img width="622" alt="Screenshot 2022-08-12 at 10 00 50 AM" src="https://user-images.githubusercontent.com/51777795/184286133-ba1fbcfe-4f85-437a-ba36-e426d30d8449.png">

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShaileshParmar11** [comment]
Hey @aniketkatkar97 kindly make changes to the newly implemented profiler component! let me know if you need any help around here!
