### ISSUE TITLE
The PUT {{baseUrl}}/v1/tables endpoint is not supporting the addition of column level tests

### ISSUE THREAD

**Issue by learn-learn4** [open-metadata/OpenMetadata#6706]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Yes

**Describe the bug**

I got a usecase of adding column level test cases for profiled data.
So, i tried this endpoint PUT {{baseUrl}}/v1/tables.

here i provided the columnTest in the paylaod shown below. The api response was 200 and in the response payload, i received 
the Column Test i send in the request payload but it was not stored int Database and when we try to get the table using GET table/:id endpoint i dont receive the column test cases i have provided.

**To Reproduce**

Screenshots or steps to reproduce

1. Execute the PUT {{baseUrl}}/v1/tables endpoint with column level test cases . an example payload

`{
    "name": "sample_table",
    "description": "",
    "displayName": "sample_table",
    "tableType": "Iceberg",
    "columns": [
        {
            "name": "order_amount",
            "dataType": "BIGINT",
            "dataTypeDisplay": "bigint",
            "fullyQualifiedName": "sampleservice.sample_schema.sample_table.sample_table.order_amount",
            "columnTests": [
                {
                    "name": "order_amount_column",
                    "columnName": "order_amount",
                    "testCase": {
                        "columnTestType": "columnValuesToBeBetween",
                        "config": {
                            "minValue": 100,
                            "maxValue": 200
                        }
                    },
                    "results": [
                        {
                            "executionTime": 1660213350,
                            "result": "89",
                            "testCaseStatus": "Failed"
                        },
                        {
                            "executionTime": 1660223350,
                            "result": "101",
                            "testCaseStatus": "Success"
                        }
                    ]
                }
            ]
        }
    ],
    "databaseSchema": {
        "id": "21992fd0-3f92-45af-9f46-824a799921ed",
        "type": "databaseSchema",
        "name": "sample_table",
        "fullyQualifiedName": "sampleservice.sample_schema.sample_table",
        "description": "",
        "deleted": false,
        "href": "http://localhost:8585/api/v1/databaseSchemas/21992fd0-3f92-45af-9f46-824a799921ed"
    }
}`

2. Now check with GET {{baseUrl}}/v1/tables/name/:fqn endpoint  the column test cases are not added.

**Expected behavior**

The PUT {{baseUrl}}/v1/tables should also be able to add the column level test cases for a column in a table.

**Version:**
 - OS: [e.g. iOS] macOS
 - Python version: 3.9
 - OpenMetadata version: 0.11.3
 - OpenMetadata Ingestion package version: NA as i ma using the API endpoints only 

**Additional context**

**Comment by harshach** [comment]
Fixed in 0.12
