### ISSUE TITLE
Service's description disappears when the ingestion task runs

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#6712]
**Affected module**
UI and Ingestion

**Describe the bug**
When a created ingestion for a Database service runs, it deletes the service's description. 

**To Reproduce**

1. Create a DB service - e.g., MySQL
2. Create a metadata ingestion
3. Run the ingestion task
4. The description disappears

**Expected behavior**
The description should not be updated by the ingestion.

**Version:**
 - OpenMetadata version: 0.11.4

**Comment by pmbrull** [comment]
This scenario is already covered on 0.12
