### ISSUE TITLE
Allow dbt description to overwrite descriptions from the UI

### ISSUE THREAD

**Issue by psg2** [open-metadata/OpenMetadata#6714]
**Is your feature request related to a problem? Please describe.**
At Clicampo we prefer to maintain our tables' descriptions up to date in our source code instead of the OpenMetadata UI, for us it should only show the latest description from the dbt manifest/catalog files.

**Describe the solution you'd like**
To have an option the DBT Source config where we can specify if we prefer to overwrite the descriptions or not

**Describe alternatives you've considered**
None so far

**Additional context**
Slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1660227141692939

**Comment by pmbrull** [comment]
https://github.com/open-metadata/OpenMetadata/issues/6767

**Comment by pmbrull** [comment]
@OnkarVO7 Let's add a parameter in the DBT ingestion config to specify if we want descriptions to be updated from DBT or not (False by default).

Then we can use the `patch_mixin` from the ometa_api to handle this behavior directly

**Comment by pmbrull** [comment]
depends on https://github.com/open-metadata/OpenMetadata/issues/6844

**Comment by harshach** [comment]
@pmbrull did we handle this?

**Comment by pmbrull** [comment]
will be part of 0.12.1

**Comment by pmbrull** [comment]
closed in https://github.com/open-metadata/OpenMetadata/pull/7653
