### ISSUE TITLE
Parse user from query log and surface in UI

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#6727]
https://openmetadata.slack.com/archives/C02DZK3QH8Q/p1660305758715529

Identify users with knowledge of a particular dataset from the query usage logs and surface the UI

**Comment by pmbrull** [comment]
@ulixius9 to confirm, are we already picking up this information from the ingestion side?

**Comment by pmbrull** [comment]
The ingestion is picking up users and this information appears in the query card as `Used by` 
<img width="396" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/35870520/e0b4b008-c7a5-4f2b-884e-eb61a6330389">
