### ISSUE TITLE
UI - use antlr parser for fqn and entityLink

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#6741]
We will have Entitylink antlr grammar implemented and have Javascript variants for Parser, Lexer available in src/generated/antlr under ui directory.
We can use that to parse the entityLink and Fqn to match patterns to create Fqn

- [ ] For activity feeds
- [ ] Test cases

PR: #6673
ref: https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md

**Comment by Sachin-chaurasiya** [comment]
Closing this as we are already using Antlr for parsing the FQNs.

**Comment by Sachin-chaurasiya** [comment]
Reopening as it's pending for entity links.
