### ISSUE TITLE
Knowledge Center - Add support for Articles and QuickLinks

### ISSUE THREAD

**Issue by noel** [open-metadata/OpenMetadata#6751]
**Is your feature request related to a problem? Please describe.**
There are cases when companies want to add context to technical metadata.  This can be because they want to describe a Data Science experiment, the team involved, the data used, links to code repo, etc. Since many catalogs dont support unstructured document creation, other tools are used (Confluence, Notion, etc). 

**Describe the solution you'd like**
If users could create "Pages" like a wiki they can write documentation at a higher level and link to other catalog items (users, tables, other pages, etc)

**Describe alternatives you've considered**
Users can continue to use external tools, but the UX isnt great and you would not be able to @ mention other catalog items if the page is in another tool. 

**Additional context**
Alation has this feature 

![image](https://user-images.githubusercontent.com/19945/184991077-12e1a90a-6b99-427a-a627-fe03f0406eeb.png)

Slack Thread:
https://openmetadata.slack.com/archives/C02AZGN0WKY/p1660683996939719

**Comment by harshach** [comment]
Turning this into our Knowledge Center Implementation Epic.

1. Similar to usageResource, we will create KnowledgeCenterResources
2. KnowledgeCenterResource can accept any entityType except for User/Bot/TestCase but for everything else to create an Article or Link
3. We will store these in entity_extension for any of the above entities
4. Users can create rich text like a wiki for any articles. We will support versions for the Article, ownership, votes
5. All Entity pages will have a tab called Knowledge Center to show a list of articles and links. Each piece will have a full page to display the article and a versions tab
6. A single article can be linked to multiple entities, thus preventing duplication of content that might be suitable at domain/team etc.
7. We will provide the ability to search articles in 1.3
