### ISSUE TITLE
Pick up popular users from usage

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6754]
Search users from the queries and see if we can find them as signed up in OM. If that's the case, push the info.

We'll need to:
- search for user in ES
- PUT the user in the table

**Comment by pmbrull** [comment]
duplicate of https://github.com/open-metadata/OpenMetadata/issues/6727

**Comment by harshach** [comment]
@pmbrull are we taking this up for 0.13?

**Comment by pmbrull** [comment]
yes! @ulixius9 will be handling it after the IngestionPipeline improvements

**Comment by pmbrull** [comment]
based on slack convos:

- Update https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/type/tableQuery.json to have userName as an EntityReference
- Add a description field to allow users to add context

We'll need to validate if updating the user to an EntityRef can cause any issues to existing usage data. Worst case scenario, let's prep a migration to remove user from the stored json
