### ISSUE TITLE
Improve ColumnValuestoMatchRegex test to support REGEXP

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#6760]
We should change `LIKE` to `REGEXP` for database engine supporting it.

**Comment by Daniel53245** [comment]
Hi,

I am interested in contributing to this issue. Could you provide some further detail about this issue?

Regards,
Dai

**Comment by TeddyCr** [comment]
Hey @Daniel53245 thank you for your voluntarism.

In [column_values_to_match_regex.py](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/test_suite/validations/column/column_values_to_match_regex.py) and [column_values_to_not_match_regex.py](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/test_suite/validations/column/column_values_to_not_match_regex.py) we use `Metrics.NOT_LIKE_COUNT` (line 55 and 59 respectively). We need to create a new metric in [this ](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/orm_profiler/metrics/static/like_count.py) submodule (you can check the other metric example that wil instead use regex. Implementation logic will most likely vary from database engine to database engine we will need to do something similar to what we are doing with the lenght metric [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/orm_profiler/orm/functions/length.py) and [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/orm_profiler/metrics/static/min_length.py). 

The engine we need to check the implementation syntax are (feel free to check their doc):
- redshift
- Snowflake
- Bigquery

**Comment by Daniel53245** [comment]
Yes, that sounds good. I will probably start working on It this monday.

**Comment by TeddyCr** [comment]
Thanks @Daniel53245 🙏 don't hesitate to reach out if you have any questions

**Comment by hendrix04** [comment]
Ugh, this is why I have been beating my head on my desk for an hour? Fields really shouldn't be labeled as "regex" if they are actually just "like" statements.

**Comment by TeddyCr** [comment]
Hey @hendrix04 yes this will be fixed in 0.13.0

**Comment by Daniel53245** [comment]
Hi, sorry to say it but could I get unassigned to the issue? I feel that I am not able to fix it. @TeddyCr

**Comment by harshach** [comment]
@TeddyCr lets handle it ourselves? cc @ayush-shah
