### ISSUE TITLE
Db2 LUW zOS service cannot be added. Test Connection fails due to possibly SQLAlchemy package issue

### ISSUE THREAD

**Issue by upenbendre** [open-metadata/OpenMetadata#6762]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? Ingestion Framework

**Describe the bug**
The "Test Connection" feature on the "Database Services" screen throws an error, when we try to add a DB2 service. The source is a DB2 LUW database, which we are trying to connect using SQLAlchemy.

**To Reproduce**
In the opemetadata-ingestion docker container:
docker exec -it openmetadata_ingestion bash
apt-get update
apt-get install libxml2
pip install "ibm-db==3.1.3"
pip install "ibm-db-sa==0.3.8"

On the OM UI
Services -> "Add a New Service" -> Choose DB2 -> db2+ibm_db is the only connection scheme available. Enter the user, password, host:port and schema name. 

Screenshots or steps to reproduce
Error message:
**Failed to test connection due to {"error": "Connection error from Engine(db2+ibm_db://dt224374:***@db2databaseurl:50000/TPJ) - Unknown error connecting with Engine(db2+ibm_db://dt224374:***@db2databaseurl:50000/TPJ) - (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/AIX64] SQL0104N An unexpected token \"END-OF-STATEMENT\" was found following \"1.3.1\"} */ SELECT 42\". Expected tokens may include: \"<table_expr>\". SQLSTATE=42601 SQLCODE=-104\n[SQL: /* {\"app\": \"OpenMetadata\", \"version\": \"0.11.3.1\"} */\nSELECT 42]\n(Background on this error at: https://sqlalche.me/e/14/f405)."}**

It seems as though the generated query 'SELECT 42' here is wrong. DB2 expects that query to be 'SELECT 42 FROM SYSIBM.SYSDUMMY1;'
Relevant code: ./lib/python3.9/**site-packages/metadata/orm_profiler/orm/functions/conn_test.py**

**Expected behavior**
The test connection should succeed and the DB2 service should be created, instead of the error above. 

**Version:**
 - OS: [e.g. iOS] (Host is CentOS 7, but the issue is inside the open-metadata-ingestion docker container.
 - Python version: 3.9 inside the docker container
 - OpenMetadata version: [e.g. 0.8] openmetadata/server:0.11.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] openmetadata/ingestion:0.11.3
openmetadata/db:0.11.3
docker.elastic.co/elasticsearch/elasticsearch:7.10.2

**Additional context**
This may be more of an SQLAlchemy issue than an open-metadata issue, but open-metadata could circumvent by possibly :
1) Using a different driver internally, or a different or older version of ibm_db_sa which does not have this problem?
2) Supporting another toolkit/ORM apart from SQLAlchemy, which can extract from DB2 LUW and z/OS
3) Some custom connection scheme instead of the db2+ibm_db option which can extract schema successfully.

**Comment by nahuelverdugo** [comment]
Thank you, @upenbendre, for asking in the SQLAlchemy community. 

**Note:** DB2 is not supported directly by SQLAlchemy.

![image](https://user-images.githubusercontent.com/11074908/185168941-60af2c37-15cf-4c3a-ba82-a620d4916aec.png)

**Comment by Vj-L** [comment]
@nahuelverdugo 
Can I mark this as close?
