### ISSUE TITLE
Tableau ingestion failing due to secrets manager issue

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#6764]
**Affected module**
Ingestion

**Describe the bug**
Tableau ingestion is failing due to airflow not able to connect to secrets manager
ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1660313254390619

**To Reproduce**

Ingestion tableau via airflow

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Comment by pmbrull** [comment]
confirmed by all users that this is working
