### ISSUE TITLE
Tables dissapper from UI after containers reboot

### ISSUE THREAD

**Issue by stepanof** [open-metadata/OpenMetadata#6770]
**Affected module**
UI

**Describe the bug**
After restarting OM containers I can't see tables in UI
![tables_dissappear](https://user-images.githubusercontent.com/68236577/185170605-2e90c48d-4c96-402e-93e0-77b9769d9990.png)

**To Reproduce**

I have changed standard docker-compose.yaml in some places:
1) Add volume for mysql container
    volumes:
      - ./db_data:/var/lib/mysql

2) Im using 
image: elasticsearch:7.17.5
instead of 
image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2 
for elasticsearch container

3) Changed some ports becuase some of them are alredy locked by other application:
 - 9201:9200 for elactic
 - 8095:8585 for openmetadata-server
 - 8096:8080 for airflow

**Expected behavior**
After restarting containers to see the same what was before

**Version:**
 - OS: ubuntu 21.04
 - Python version: 3.8
 - OpenMetadata version: 11.4

**Comment by pmbrull** [comment]
hi @stepanof , you might need to reindex the data on ElasticSearch with https://github.com/open-metadata/OpenMetadata/discussions/5300 after a reboot, as the volume is only on MySQL

**Comment by pmbrull** [comment]
@akash-jain-10 @vijaypm lets add the volumes by default here

**Comment by stepanof** [comment]
Thankx @pmbrull !!! I'll try it later. Hope this will help. You can close the issue if needed.

**Comment by pmbrull** [comment]
thanks, do let us know if you need anything else. We'll keep this issue open for us to track that we are adding the volume behavior as default. Thank you for reporting

**Comment by harshach** [comment]
@Vj-L any update on this to support volumes by default

**Comment by harshach** [comment]
@akash-jain-10 @Vj-L update please

**Comment by Vj-L** [comment]
@harshach 
We will take this on priority for this week and try to close this up

**Comment by pmbrull** [comment]
@Vj-L we need to add the JWT env vars in the docker compose files as well 🙏
