### ISSUE TITLE
Docs updates from support channel

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6772]
After reviewing the support channel since July, there are a few topics we might need to handle better in the documentation:

- [x] How to change Airflow port in Docker Compose? https://openmetadata.slack.com/archives/C02B6955S4S/p1656584925523139
- [x] AWS profile troubleshooting @pmbrull 
- [x] Lineage backend SSO config @pmbrull 
- [x] MLflow & Mode connectors @MilanBariya 
- [x] Python requirement on quickstart installation @pmbrull 
- [x] Lineage example with Python client @pmbrull 
- [x] Fix DBT cli link https://docs.open-metadata.org/openmetadata/ingestion/workflows/metadata/dbt/ingest-dbt-cli @pmbrull 
- [ ] Apache Nifi docs @OnkarVO7 
- [ ] SQLite docs @TeddyCr 
- [x] Atlas docs @ulixius9 
- [ ] How to use the ingested metadata further? Use the API https://openmetadata.slack.com/archives/C02B6955S4S/p1656586291437489
- [x] EC2 instance size for deployment https://openmetadata.slack.com/archives/C02B6955S4S/p1656607855615849 @akash-jain-10 
- [ ] DBT configurations and how it works. A lot of questions around this. Examples on how to pick things up from ALL sources (HTTP from github might be interesting) @OnkarVO7 
- [x] “compose” is not a docker command https://openmetadata.slack.com/archives/C02B6955S4S/p1656644869250529
- [x] MYSQL needs permissions to INFORMATION_SCHEMA table
- [x] metadata docker CLI @pmbrull 
- [x] kubernetes expects secrets on the same namespace  https://openmetadata.slack.com/archives/C02B6955S4S/p1657138857272699 @akash-jain-10 
- [x] AWS machine access https://openmetadata.slack.com/archives/C02B6955S4S/p1657301042008309 @akash-jain-10 
- [x] Redshift ca-verify docs https://openmetadata.slack.com/archives/C02B6955S4S/p1657546064582539 @ulixius9 
- [x] explain lineage deep @pmbrull 
- [x] python SDK review that we are using the latest namings https://openmetadata.slack.com/archives/C02B6955S4S/p1657679706198999 @ulixius9 
- [x] Mysql 5.7 https://openmetadata.slack.com/archives/C02B6955S4S/p1658307805553539
- [x] JWT for k8s https://openmetadata.slack.com/archives/C02B6955S4S/p1658428692139929
- [x] #8709
- [ ] Expand on the Workflow structure: source, processor, sink, stage, bulksink https://openmetadata.slack.com/archives/C02B6955S4S/p1659438955830229 @pmbrull 
- [x] Custom properties via API @Sachin-chaurasiya 
- [x] ES and OS versions @akash-jain-10 
- [x] AWS OpenSearch  @akash-jain-10 
- [x] AWS EKS for deployment @akash-jain-10 https://github.com/open-metadata/OpenMetadata/pull/7205
- [x] DeltaLake metastore explanation @pmbrull 
- [ ] Hive connection settings @ulixius9 (based on https://github.com/open-metadata/OpenMetadata/issues/6913)
- [x] Connectors show `loggerLevel` config @pmbrull 
- [x] IMPORTANT for 0.12 the openmetadata.yaml parameters changed. We'll need to update the deployment info @akash-jain-10. We still do not have a fancy way to support multiple versions in the docs (WIP), so please just create use one section in the page for 0.11 and one for 0.12 until we can migrate this properly
- [x] Redshift ingestion permissions. Redshift docs SVV_TABLE_INFO is visible only to superusers. For more information, see [Visibility of data in system tables and views](https://docs.aws.amazon.com/redshift/latest/dg/c_visibility-of-data.html). To permit a user to query the view, grant SELECT permission on SVV_TABLE_INFO to the user. @ulixius9 
- [ ] more docs and examples on the mark deleted tables new functionality for filtering @ulixius9 
- [x] RedPanda docs @nahuelverdugo https://github.com/open-metadata/OpenMetadata/pull/7205

**Comment by pmbrull** [comment]
still there are tasks to handle

**Comment by harshach** [comment]
@OnkarVO7 @ulixius9 @akash-jain-10 @pmbrull lets close this ticket for 0.12.1
