### ISSUE TITLE
Openmetadata secure Active Directory

### ISSUE THREAD

**Issue by AntonArgon** [open-metadata/OpenMetadata#6775]
**Is your feature request related to a problem? Please describe.**
Good time! Our company uses the corporate local Active Directory for authentication. The link https://docs.open-metadata.org/deployment/security did not find such an authentication method. Cloud solutions are not suitable for security requirements. 

**Describe the solution you'd like**
Are there any plans to add authentication to openmetadata via AD (ldap) config?
This issue https://github.com/open-metadata/OpenMetadata/issues/3376 does not answer.

**Comment by mohityadav766** [comment]
hi @AntonArgon  , i have recently raised a PR with support for LDAP 
Can you try this out and give us any feedback if it works for you?
Let me know i can help you with setting it up
