### ISSUE TITLE
Table UI cannot render child columns when child columns do not specify `dataTypeToDisplay`

### ISSUE THREAD

**Issue by cvlendistry** [open-metadata/OpenMetadata#6780]
**Affected module**
UI, Backend

**Describe the bug**
Table UI cannot render child columns when child columns do not specify `dataTypeToDisplay`. On clicking the arrow button next to the parent column, the UI renders a "something went wrong" page.
The error is `TypeError: Cannot read properties of undefined (reading 'length')`
**To Reproduce**
Create a table using the API that has columns with child columns but do not specify the `dataTypeToDisplay`
```
children = [Column(name="col1_1", dataType=DataType.INT), Column(name="col1_2", dataType=DataType.INT)]
    create_table = CreateTableRequest(
        name="test",
        databaseSchema=schema_reference,
        columns=[Column(name="id", dataType=DataType.BIGINT), Column(name="col1", dataType=DataType.STRUCT, dataTypeDisplay='struct<col1_1:int,col1_2:int>', children=children)],
    )
    table_entity = metadata.create_or_update(create_table)
```

**Expected behavior**
Either the API call should have failed, or the UI should have a fallback mechanism when the display string is not available.

**Version:**
 - OS: n/a
 - Python version: 3.9
 - OpenMetadata version: 0.11.0
 - OpenMetadata Ingestion package version: n/a

https://user-images.githubusercontent.com/84750525/185265390-cc623cae-c168-4712-944b-89a788122634.mov

**Comment by pmbrull** [comment]
Let's see if we can tackle this
