### ISSUE TITLE
Separate TableProfile and ColumnProfile api calls

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6782]
**Feature**
Current APIs give the entire response of TableProfile, which includes column profile details as well. With the new UI we are building per column dashboard, to get this data UI has to make a call for all the columns, which is unnecessary and can cause performance issues when the table has a lot of columns.

**Describe the task**
In this issue, we add a createTableProfile request such that the client can send a bulk of table and column profiles in a single request. During the update, we separate them out into their own extensions.
clients can use FQN of table or column to fetch the relevant profiles. This also affects the Pipeline statuses and TestCase statuses all of them needs to use FQN of Pipeline or Testcase, respectively, to get the pipeline results and test case results
cc @pmbrull (may require changes on any pipeline connectors that are inputting the pipeline status) /api/v1/pipeline/{fqn}/status (PUT, DELETE, LIST)
@TeddyCr for testcase results /api/v1/testCase/{fqn}/status (PUT, DELETE, LIST)

@ShaileshParmar11 this requires address pipeline status UI as well.

**Comment by pmbrull** [comment]
got it, thanks for change, makes a lot of sense. I'll add the statuses changes on the same PR
