### ISSUE TITLE
Improvement(UI): No service icons available for Datalake, Mode and PinoDB

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#6806]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

UI

**Describe the bug**
There are default icons available for Datalake, Mode and PinoDB while adding the service connection.

**To Reproduce**
<img width="166" alt="Screenshot 2022-08-18 at 8 28 57 PM" src="https://user-images.githubusercontent.com/51777795/185427957-5fc02ce6-e2f1-4d43-a3e3-37c9a84bbfa9.png">
<img width="162" alt="Screenshot 2022-08-18 at 8 29 00 PM" src="https://user-images.githubusercontent.com/51777795/185427968-362c736a-7fd6-48a0-9812-10514a41d200.png">
<img width="164" alt="Screenshot 2022-08-18 at 8 29 10 PM" src="https://user-images.githubusercontent.com/51777795/185427975-446d53ee-0c57-4939-aa7b-a5de23198e3e.png">

**Expected behavior**

Add service specific icons.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ulixius9** [comment]
@aniketkatkar97 while adding this can you also please add the icons for Dagster & Fivetran 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/39544459/185603263-77cc55fd-6f50-44d8-9b50-529bdcad706b.png">
