### ISSUE TITLE
Exact search with quotes does not work

### ISSUE THREAD

**Issue by cvlendistry** [open-metadata/OpenMetadata#6811]
**Affected module**
UI
**Describe the bug**
Use the top search bar to search for any keyword or phrase with quotes:
```
"this is nonsense"
```
for example. It will return all tables in the database.

**To Reproduce**

see description
**Expected behavior**
Results should match exact phrase.

**Version:**
 - OS: [e.g. iOS]: n/a
 - Python version: n/a
 - OpenMetadata version: 0.11.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
API supports it but we need to escape the double quotes
http://localhost:8585/api/v1/search/query?q=\"raw_customer\"&index=table_search_index
We should only do it if the user passed string has those double quotes
