### ISSUE TITLE
Review auto query comment in Hive & Athena

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6816]
From https://openmetadata.slack.com/archives/C02B6955S4S/p1660852909848949

In all our connections we send a comment in the queries, something like

```
/* {\"app\": \"OpenMetadata\", \"version\": \"0.11.3.1\"} */ SELECT 42
```

And it is possible that these comments are giving issues.

We need to validate that the queries can properly run on Hive and, if not, we will need to update when we are adding them when creating the Engine

**Comment by pmbrull** [comment]
Same thing is happening in Athena:

```
metadata.utils.connections.SourceConnectionException: Unknown error connecting with Engine(awsathena+rest://...:***@athena.us-east-2.amazonaws.com:443?s3_staging_dir=s3%3A%2F%2Fathena-postgres%2Foutput%2F&work_group=primary) - (pyathena.error.DatabaseError) An error occurred (UnrecognizedClientException) when calling the StartQueryExecution operation: The security token included in the request is invalid.
[SQL: /* {"app": "OpenMetadata", "version": "0.12.0.dev0"} */
SELECT 42]
(Background on this error at: https://sqlalche.me/e/14/4xp6).
```

**Comment by pmbrull** [comment]
IMO we can add a new property to all JSON Schemas for databases named `supportsQueryComment` with default value to true. Then, if this value is True, we configure the Engine in SQLAlchemy to send the comment. If it is false, we disable that.

Let's validate that this works for Testing the connection as well

**Comment by MilanBariya** [comment]
> metadata.utils.connections.SourceConnectionException: Unknown error connecting with Engine(awsathena+rest://...:***@athena.us-east-2.amazonaws.com:443?s3_staging_dir=s3%3A%2F%2Fathena-postgres%2Foutput%2F&work_group=primary) - (pyathena.error.DatabaseError) An error occurred (UnrecognizedClientException) when calling the StartQueryExecution operation: The security token included in the request is invalid.
> [SQL: /* {"app": "OpenMetadata", "version": "0.12.0.dev0"} */
> SELECT 42]
> (Background on this error at: https://sqlalche.me/e/14/4xp6).

Okay, @pmbrull let me try that way.
