### ISSUE TITLE
Update profiler workflow based on #6782

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#6822]
## Context
We are currently passing the profiler metrics into a `TableProfile` in `core.py`. This include both column and table profile. 
https://github.com/open-metadata/OpenMetadata/blob/78b5f8c8e28ee78807e16dc0a5a2f3235e788c89/ingestion/src/metadata/orm_profiler/profiler/core.py#L423-L430
which are then passed into a `ProfilerResponse` object in the`profile` attribute.
https://github.com/open-metadata/OpenMetadata/blob/78b5f8c8e28ee78807e16dc0a5a2f3235e788c89/ingestion/src/metadata/orm_profiler/profiler/core.py#L381-L385
This `ProfilerResponse` object is then used in the sink to write data to the `tableProfile` attribute of the `Table` object.
https://github.com/open-metadata/OpenMetadata/blob/78b5f8c8e28ee78807e16dc0a5a2f3235e788c89/ingestion/src/metadata/orm_profiler/sink/metadata_rest.py#L70-L72
The sink uses `ingest_table_profile_data` method to add the data to the `Table` object
https://github.com/open-metadata/OpenMetadata/blob/78b5f8c8e28ee78807e16dc0a5a2f3235e788c89/ingestion/src/metadata/ingestion/ometa/mixins/table_mixin.py#L99-L113

With #6782 column profile and table are now split. table profile will be at the root of a table entity while column profile will be linked to table entities via the column entity (now accessible via `Table -> columns[Column -> profile]`.

## Solution
We need to integrate this new logic to the new logic of the profiler workflow.

**Comment by ayush-shah** [comment]
This is fixed in #6827
