### ISSUE TITLE
UI: Glossary details page improvements

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#6834]
Glossary terms details page has too many boxes. Can we make this consistent with the data asset details page where the description is stated right below the asset details without a separate `Description` header etc? Also, we can lose many of these boxes and merge it.

**Comment by Sachin-chaurasiya** [comment]
- [ ] Left column Position and width should be consistent, currently it's different on explore page, settings page and glossary page (Should be consistent as on home page)
