### ISSUE TITLE
Tags and Glossaries are not consistent with each other

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#6835]
![image](https://user-images.githubusercontent.com/12962843/185863916-0c5b7a0d-8403-426d-ba59-5bed28941864.png)
![image](https://user-images.githubusercontent.com/12962843/185863936-9a1bd523-fda2-43c7-9325-b2b7cc76f6d9.png)

**Comment by devyani-kaushik** [comment]
we need to update the styling as per glossary which mean no separator and full height of the left column
