### ISSUE TITLE
Automated PII tagging for common PII data

### ISSUE THREAD

**Issue by fikrifikar** [open-metadata/OpenMetadata#6838]
**Is your feature request related to a problem? Please describe.**
In large-scale data managed by the company, it will definitely require a big effort if a data person adds tagging one by one for common PII data such as name, address, id card, amount of money and etc. It would be better if OpenMetadata provided this feature to organize PII data automatically or can categorize data into PII via script

**Describe the solution you'd like**
It would be better if OpenMetadata provided this feature to organize PII data automatically or can categorize data into PII via script

**Describe alternatives you've considered**

**Additional context**

**Comment by TeddyCr** [comment]
This will come onto the road map once we start tackling automation

**Comment by TeddyCr** [comment]
closing as already covered here https://github.com/open-metadata/OpenMetadata/issues/3803
