### ISSUE TITLE
Backend : Roles patch API is not working for `policies` 

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#6851]
Roles patch API is not working for `policies` 

When we try to patch the roles by updating `policies` attribute, with payload.

```
[
    {
        "op": "remove",
        "path": "/policies/3"
    }
]
```
In response we are getting updated attributes but when we refresh we get all the policies.
cc : @sureshms

**Comment by Sachin-chaurasiya** [comment]
@sureshms , Will this be the same as this?
https://github.com/open-metadata/OpenMetadata/issues/6852#issuecomment-1224312870

**Comment by sureshms** [comment]
@Sachin-chaurasiya this is the right place to make changes. Patch a role to add/remove policies in it.
