### ISSUE TITLE
Backend : Policy patch API is not working for 'roles`

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#6852]
Policy patch API is not working for 'roles`

Request : http://localhost:3000/api/v1/policies/c89152a3-e3c9-40a8-b187-262b58d98be3
Payload : 
```js
[
    {
        "op": "remove",
        "path": "/roles/0"
    }
]
```
Response : 
```js
{
    "responseMessage": "An exception with message ['{\"id\":\"c89152a3-e3c9-40a8-b187-262b58d98be3\",\"name\":\"TestPolicy\",\"fullyQualifiedName\":\"TestPolicy\",\"description\":\"Description\",\"policyType\":\"AccessControl\",\"enabled\":true,\"version\":0.1,\"updatedAt\":1661171748017,\"updatedBy\":\"anonymous\",\"rules\":[{\"name\":\"TestRule\",\"effect\":\"allow\",\"resources\":[\"all\"],\"operations\":[\"All\"],\"description\":\"Description\"}],\"deleted\":false}' contains no value for name 'roles'] was thrown while processing request."
}
```

**Comment by sureshms** [comment]
@Sachin-chaurasiya this is incorrect use of API. You add or delete policies in `Roles` endpoint. You should not be able to add/delete roles from `Policies` endpoint. The policies has list of roles where a policy is referenced.

**Comment by sureshms** [comment]
I am closing this issue as `won't fix`

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya this is the incorrect use of API. You add or delete policies in the `Roles` endpoint. You should not be able to add/delete roles from the `Policies` endpoint. The policy just has a list of roles where a policy is referenced.

Thanks, @sureshms, I will try that out.
Same way if we want to remove the policy from roles then we will have to use the policy API right not the roles API?
