### ISSUE TITLE
Inconsistent API Schema Class for create op

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#686]
In https://github.com/open-metadata/OpenMetadata/pull/679 we noticed an issue where for the `POST` operation to create an Entity, we were not passing the correct `Create` class as the API schema.

We had `schema = @Schema(implementation = Model.class)` instead of `schema = @Schema(implementation = CreateModel.class)`.

Taking a look at other `EntityResource` files, we have similar inconsistencies, such as in `TopicResource.java:216` and `DashboardResource.java:218`.

We should review the different Entities and make sure we are requesting the proper schema for creation.

Thanks

**Comment by harshach** [comment]
Thanks for filing this @pmbrull . All of the POST/PUT should use CreateEntity schemas. If you are planning on sending a PR let me know otherwise I can fix it.

**Comment by pmbrull** [comment]
Hi @harshach, I am happy to take this 🤗  Thanks

**Comment by pmbrull** [comment]
Fix with https://github.com/open-metadata/OpenMetadata/pull/704
