### ISSUE TITLE
Passing on field descriptions of referenced tables

### ISSUE THREAD

**Issue by bmy-ashampoo** [open-metadata/OpenMetadata#6873]
**Is your feature request related to a problem? Please describe.**
Currently, each field within a lineage must be documented/described individually even if it is the exact same field represented in a different table.

**Describe the solution you'd like**
I would like the UI to suggest to adopt the existing description of a referenced column (if that description already exists). This would save a lot of time and effort.

**Describe alternatives you've considered**
Another approach might be to edit multiple column descriptions at the same time or apply the same description to multiple columns of different tables.

**Additional context**
Ideal scenario: Let's say I have a table "revenue" that is referencing a table "product" which has a field "product_name". I add a description to "product_name" in the "products" table. Later when I want to document  "product_name" in my "revenue" table, the UI gives me the option to simply adopt the description from "products" that I wrote before.

**Comment by oleg-savko** [comment]
up vote, will be very useful feature


or add posibility to apply description for all empty upstream/downstream column lineage
