### ISSUE TITLE
Tableau Lineage parsing issue

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6884]
this line `datasource.split("(")[1].split(")")[0].split(".")` can be conflictive.

Aside from the service connection exception error, we are seeing a "list index out of bound" error in https://openmetadata.slack.com/archives/C02B6955S4S/p1661260687998279

Let's double-check the logic here and add better logging to catch why the datasource splitting might be failing

**Comment by pmbrull** [comment]
0.12.1

**Comment by pmbrull** [comment]
@OnkarVO7 let's use this ticket to fix the actual Lineage problem, as we are not picking the information from the right place. We'll need to rely on the graphql API to extract what is needed

**Comment by OnkarVO7** [comment]
Yes @pmbrull. Taking the graphql approach itself here
