### ISSUE TITLE
Explore data profiling for datalake connector

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#6892]
Explore data profiling for datalake connector

Support conversation link: https://openmetadata.slack.com/archives/C02B6955S4S/p1661257220174859

**Comment by TeddyCr** [comment]
@ulixius9 would that the same as https://github.com/open-metadata/OpenMetadata/issues/7449?

**Comment by TeddyCr** [comment]
duplicate with #7449
