### ISSUE TITLE
UI Improvements_2

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#6893]
- [x]  Manage button styling on team detail page is not consistent 
<img width="80" alt="Screenshot 2022-08-24 at 8 49 44 AM" src="https://user-images.githubusercontent.com/103238069/186315437-3eae7ec6-6c69-4014-b67a-36703367a0ca.png">

- [x] Replace Delete Icon with Remove icon 
![Remove](https://user-images.githubusercontent.com/103238069/186317616-2a58abe8-0ff1-41a3-a36b-8d3246a0b038.svg)
<img width="110" alt="Screenshot 2022-08-24 at 8 51 39 AM" src="https://user-images.githubusercontent.com/103238069/186316694-4a589dc0-940a-4f33-901e-15bb8a5717a4.png">

- [x] Owner's link on teams page not working, either not re-directing or giving a 404 error
- [x] Add a breadcrumb link to the main user listing page on create user form
<img width="147" alt="Screenshot 2022-08-24 at 8 55 55 AM" src="https://user-images.githubusercontent.com/103238069/186319734-e931bcb5-1649-4bf9-a639-24b6f900d18c.png">
 

- [x] Can we keep the styiling in image 1 same as it is in image 2
Image 1
<img width="1431" alt="Screenshot 2022-08-24 at 8 59 53 AM" src="https://user-images.githubusercontent.com/103238069/186322013-c5d6444e-5340-4f6e-9792-87c9002fbdef.png">
Image 2
<img width="1381" alt="Screenshot 2022-08-24 at 9 01 13 AM" src="https://user-images.githubusercontent.com/103238069/186322564-3190660c-639e-4d1e-b133-c10d89ab90c5.png">

- [x] "Database Service" click is redirecting to the old Service page
<img width="252" alt="Screenshot 2022-08-24 at 9 01 57 AM" src="https://user-images.githubusercontent.com/103238069/186322641-2bd1b2cb-bac0-4d8c-82f1-0c13c884da85.png">

- [x] mlflow logo is stretched over here
<img width="740" alt="Screenshot 2022-08-24 at 9 04 19 AM" src="https://user-images.githubusercontent.com/103238069/186322885-6552f635-789d-48e3-bdee-4ee8db14287b.png">

- [x] Service type (Breadcrumb) click on add service form is redirecting to the old Service page

- [x] Can we list these chips in 1 line below the filter option instead of filtering it inside on "Webhook" and "Slack" page
<img width="273" alt="Screenshot 2022-08-24 at 9 09 28 AM" src="https://user-images.githubusercontent.com/103238069/186323420-33a8d938-b98f-4109-b61c-68f302142c16.png">

- [x]  Explore Page Left column isn't using full height on applying filter
<img width="275" alt="Screenshot 2022-08-24 at 9 29 34 AM" src="https://user-images.githubusercontent.com/103238069/186327617-42d42fe9-9bc7-4115-a87a-ee2ddeee9658.png">

- [x] Reduce table column height on user page and admins page

- [x] Edit owner dropdown position should be below the icon
<img width="507" alt="Screenshot 2022-08-25 at 6 11 21 PM" src="https://user-images.githubusercontent.com/51777795/186668028-6a28d56f-5e2c-44df-91d8-6d5d12d22a19.png">

- [x] Manage button styling on glossary page is not consistent with other pages
<img width="221" alt="Screenshot 2022-08-25 at 6 36 25 PM" src="https://user-images.githubusercontent.com/51777795/186673026-fcfc2bad-44b5-4395-bc7e-4d777ad70f24.png">

**Comment by ShilpaVernekar** [comment]
**1)** In the OM search bar, need a space between Dashboards,Pipelines. 
![image](https://user-images.githubusercontent.com/94032785/186718195-9f084db1-0061-4206-b48e-c53d4e49d646.png)

Please edit the text as follows:
Search for Tables, Topics, Dashboards, Pipelines and ML Models

**2)** If we have a single task, better if it reads as "1 Pending Task". Only if it's more that one, it should read as "n Pending Tasks"
![image](https://user-images.githubusercontent.com/94032785/186718468-6e7ad2f3-f31b-401d-a459-29dc2110d8f5.png)

cc @harshach

**Comment by ShilpaVernekar** [comment]
Here are some more changes required
queries should be "**Q**ueries"
columns should be "**C**olumns"
Activity Feed & Tasks should be "Activity Feed**s** & Tasks"
![image](https://user-images.githubusercontent.com/94032785/186902792-7dbb109c-2ea6-4778-9bb1-b12e527bbc01.png)

**Comment by chirag-madlani** [comment]
All issues are fixed.
