### ISSUE TITLE
UI - support basic auth via Email only

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#6894]
**Feature**
Add feature issue reference

Support Login / Signup via Email

1. Login flow
  - Username, Password 
  - Forgot Password - Email
  - Provision to reset password via reset link. Fields - Password, Confirm Password

2. SingUp through Admin
  - FirstName, LastName, Email

Questions:

- SingUp link expiry? - 24 hours
- Reset password link expiry? - 24 hours
- Email should be unique?
- 

**Describe the task**

**Comment by Sachin-chaurasiya** [comment]
Fixed with #7558
