### ISSUE TITLE
Tableau Custom SQL for Lineage

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#6905]
**Is your feature request related to a problem? Please describe.**
Tableau Metadata API provides the custom SQL which can be used to create lineage information
Look for ways to check if it can be used with OM

**Comment by kkwan-vh** [comment]
Tableau API Model - https://help.tableau.com/current/api/metadata_api/en-us/docs/meta_api_model.html

GraphiQL query example
```{
customSQLTables
  {
  id
  name
  description
  query
  connectionType
  tables 
    {
    id
    name
    schema
    fullName
    description
    database {
      name
    }
  }
  downstreamWorkbooks{
    name
  }
}
}```

**Comment by pmbrull** [comment]
@OnkarVO7 could you please check if this is already done? Thanks

**Comment by OnkarVO7** [comment]
Support for Tableau Custom SQL Lineage has been implemented with the Tableau Data Models
