### ISSUE TITLE
Domo Connector

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#6907]
it has full features: pipelines, dashboards, models...

**Comment by harshach** [comment]
@pmbrull lets pick this up post 0.12.1 release

**Comment by NiharDoshi99** [comment]
Opened sub-issues
- #8011 
- #8012 
- #8013

**Comment by pmbrull** [comment]
as only the ML is pending, I'll clean up this ticket. ML has not that high priority. Thanks
