### ISSUE TITLE
Automatically tag assets with respective glossary term

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#6908]
**Is your feature request related to a problem? Please describe.**
An asset (column) needs to be manually associate with a glossary

**Describe the solution you'd like**
We should automatically associate a column with a glossary in case there is an exact match on the two strings (column name and glossary term). If there are concerns, you can make an option to opt-in the term for auto-assignment.

**Describe alternatives you've considered**
Manually or programatically on our end

**Additional context**
This will help us drive education on the different data set we have by allowing customers to learn about our datasets through glossaries.

**Comment by trillhaa** [comment]
I don't think this is needed any longer for us, we found workarounds for this for the time being. The point was on auto-tagging columns if the column name happened to match a glossary term (e.g. column name `customer_id` would be tagged with a glossary section called `customer_id`.)

**Comment by pmbrull** [comment]
Thanks for the clarification @trillhaa. @harshach any thoughts on this?
