### ISSUE TITLE
Problems to tag databases and schemas

### ISSUE THREAD

**Issue by leobiscassi** [open-metadata/OpenMetadata#6910]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Impacts the UI.

**Describe the bug**
I'm not able to tag database and schemas, just tables. I'm running open metadata 0.11.0 on docker through the metadata cli.

**To Reproduce**

Just include a new database service, and go to the database and/or schemas and see that there is no option to include the tags at this level. Below a screenshot at the schema level:

![image](https://user-images.githubusercontent.com/1977418/186515989-6a754d47-421b-4006-93e3-261eace9713a.png)

**Expected behavior**

As far I talked with Harsha in the `#support` slack channel it is expected for the tag option to be there.

**Version:**
 - OS: [e.g. iOS] Ubuntu 22.04
 - Python version: 3.9.9
 - OpenMetadata version: [e.g. 0.8] 0.11.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] openmetadata-ingestion[docker]==0.11.5.0

**Additional context**

**Comment by mohityadav766** [comment]
this is done
