### ISSUE TITLE
Hive connection fails if there is no auth is being passed in connectionArguments

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#6913]
**Affected module**
Ingestion

**Describe the bug**
Run hive without any security mechanism and go to settings-> service -> hive
fill up required fields and click on test connection 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/38649/186549133-c92464cf-9d8f-4c68-a45f-dd821a352525.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/186549155-941f9db0-952c-465d-b848-930c53b71d71.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ulixius9** [comment]
Hi @harshach, closing this issue as it has been already fixed with #6824, will update the documents as part of issue #6772
