### ISSUE TITLE
UI : Modify the logs modal markdown content styling

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#6916]
Logs are coming as a markdown and there are some headings like (h1,h2,h3).
We will have to modify the styling for this log modal.
![image](https://user-images.githubusercontent.com/59080942/186585803-817ed749-b5e5-4b5d-9975-fa3a2a143178.png)

**Comment by chirag-madlani** [comment]
We will switch to lib to show logs in a pretty manner. Progress can be tracked here: #7477
