### ISSUE TITLE
startTs & endTs filters providing paginated data

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#6917]
## Backend

`http://localhost:3000/api/v1/testCase/sample_data.ecommerce_db.shopify.dim_address.shop_id.column_value_max_to_be_between/testCaseResult?startTs=1660197342&endTs=1661406942`

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/71748675/186586680-058835db-1aaf-4bd5-aadb-6866e0bdd68c.png">

### Below are the some of end point where we are using startTs & endTs
- http://localhost:8585/api/v1/testCase
- http://localhost:8585/api/v1/testCase/{fqn}/testCaseResult
- http://localhost:8585/api/v1/tables/{fqn}/columnProfile
- http://localhost:8585/api/v1/tables/{fqn}/tableProfile

## UI
- Replace the max limit for API calls once this is fixed from API

**Comment by harshach** [comment]
@TeddyCr adding some of the backend tasks to you, Let me know if you have any questions

**Comment by harshach** [comment]
@ShaileshParmar11 here is the PR https://github.com/open-metadata/OpenMetadata/pull/7617 . 
all of the apis will have fqn, startTs,endTs all of them are mandatory fields that one must pass.
Please push your changes into this PR and we can merge all of them together.
