### ISSUE TITLE
Search results are not showing the table description properly

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#692]
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/38649/136260818-71b368b3-d435-4302-a545-0ba18b622f22.png">
above result showing partial description
below we have all the description in table

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/38649/136260878-76d2dec8-3365-4616-8a8e-af04ba2835c0.png">

**Comment by Sachin-chaurasiya** [comment]
@harshach from search API we are getting the description.
{
    ....
    "highlight": {
        "description": [
            "Although this table is good for generating order lists and joining with the dim_customer, use the <span class=\"text-highlighter\">sales</span>"
        ]
    }
},
