### ISSUE TITLE
UI - to accommodate backend changes from #6014

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#6921]
**Is your feature request related to a problem? Please describe.**

UI changes required for #6014 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/12962843/186622719-adfe0344-81e6-416d-99ef-c972d1f2086c.png)

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/6990
