### ISSUE TITLE
UI | Full Table name is not displayed on the Table Home Page

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#6932]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Full Table name is not displayed on the Table Home Page

**To Reproduce**
* Have table with a long name

Screenshots or steps to reproduce
<img width="651" alt="Screen_Shot_2022-08-25_at_12_15_53_PM" src="https://user-images.githubusercontent.com/49429859/186729308-88f35fcb-5fbd-44bd-bfdf-277f5209eb01.png">

**Expected behavior**
Display the full Table name, at-least upon Hover

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]: 0.11.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
+1 for showing the full table name upon hover. @sidhreddy thank you for reporting this and welcome back. It's been a long time!
