### ISSUE TITLE
Announcement: Add support for email notifications

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6937]
**Feature**
When an announcement is created, there should be an option for the admins and the creator of the announcement to trigger email notifications to all the followers of the entity on which the announcement is being made.

**Describe the task**
 - There should be an option to configure the frequency of emails (for example: at the time of the announcement, on the day of deprecation, etc.)

**Comment by harshach** [comment]
@mohityadav766 are we taking care of this in the new notifications part

**Comment by harshach** [comment]
duplicate ticket
