### ISSUE TITLE
UI | Enable 2-finger scroll zoom-in/zoom-out on the Lineage tab

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#6942]
**Is your feature request related to a problem? Please describe.**
Enable 2-finger scroll zoom-in/zoom-out on the Lineage tab like Google-Maps

**Describe the solution you'd like**
Enable 2-finger scroll zoom-in/zoom-out on the Lineage tab like Google-Maps

**Describe alternatives you've considered**
Pinch-to-zoom

**Additional context**

**Comment by ShaileshParmar11** [comment]
Hello @sidhreddy We already support 2 finger zoom in zoom out for lineage

https://user-images.githubusercontent.com/71748675/194851947-06a109f0-e7d0-49d4-b0a8-125eb5a921d8.mov
