### ISSUE TITLE
UI | Superscript service.db.schema and show table name more prominently

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#6946]
**Is your feature request related to a problem? Please describe.**
The current Lineage graph lists the entire Table FQN's which could be long sometimes. Having only listing the table name could be simpler

**Describe the solution you'd like**
Show only the table name on the Lineage graph and maybe the FQN upon clicking on the node.

**Describe alternatives you've considered**
Use the Current Lineage graph with FQN

**Additional context**

**Comment by harshach** [comment]
superscript service.db_name.db_schem and show the table_name more prominently similar to explore cards

**Comment by ShaileshParmar11** [comment]
@Ashish8689 Please take help from @devyani-kaushik showing linage name
![image](https://user-images.githubusercontent.com/71748675/211987851-8cd0c82c-2d97-498d-929f-fcdfa396e699.png)
