### ISSUE TITLE
UI | Table Detail pane on the Lineage tab doesn't show the column count

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#6947]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Table Detail pane on the Lineage tab doesn't show the column count

**To Reproduce**
* Click on node in the Lineage tab
* Check for column count on the Table Detail pane on the right

Screenshots or steps to reproduce
<img width="629" alt="Screen_Shot_2022-08-25_at_11_03_39_PM" src="https://user-images.githubusercontent.com/49429859/186818130-0deb4c25-7397-4f67-a234-e6b2f15c65e9.png">

**Expected behavior**
Correctly show the column count

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]: `0.11.5`
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sidhreddy** [comment]
FYI - I did not enable Profiler yet on this specific table, so I guess row count being not available is OK.

**Comment by harshach** [comment]
@sidhreddy both row count and column count are picked up by profiler

**Comment by sidhreddy** [comment]
@harshach isn't the columns here mean the column count? Isn't that part of metadata extraction?

**Comment by harshach** [comment]
we can add it from column count, but the idea was to display the metrics from profiling. But yes we can use column count from the metadata

**Comment by sidhreddy** [comment]
Got it. Would be able to make it consistent with the Table Home page? And also add the Schema name?
<img width="728" alt="Screen_Shot_2022-08-25_at_4_48_20_PM" src="https://user-images.githubusercontent.com/49429859/186825523-3451f262-1331-424e-b7e9-95097ae8896e.png">
