### ISSUE TITLE
[INGESTION][METADATA][DOCKER][CLI] ability to run docker-compose of postgresql for 0.12.0 Release

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#6959]
**Is your feature request related to a problem? Please describe.**
Currently, `metadata docker --start` by default brings up Docker Compose file from Main Branch `docker/metadata/docker-compose.yaml`.
Need to add Feature to support postgresql docker-compose as well!

`metadata docker --start`  - By Default should bring Docker Compose of MYSQL Main Branch.
`metadata docker --start --db=postgresql` - Should provide the ability to run docker compose for PostgreSQL from Main branch.
`--db` should only take either `postgresql` or `mysql`.
Also if we can, Docker Compose file should be picked up from Latest Release instead of main branch!

**Comment by pmbrull** [comment]
@akash-jain-10 will get it from `main` for now. Please open a separated ticket for that. Also to handle this from the release we need to add the asset from 0.12 onwards (0.11.5 is missing the postgres compose)
