### ISSUE TITLE
UI | cmd + click does not work as expected on the Explore page

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#6976]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
`cmd + click` does not work as expected on the Explore page, where as it works fine on other pages on OM

**To Reproduce**
* Open Explore page
* Try `cmd + click` on any entity and see the current tab open the entity page as well a new tab instead of opening the entity just on a new tab

Screenshots or steps to reproduce

**Expected behavior**
Only opening the entity home page just on a new tab upon `cmd + click`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]: `0.11.5`
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya @chirag-madlani lets handle this in 0.12
