### ISSUE TITLE
UI | Longer entity names are not shown on Explore All Activity Page

### ISSUE THREAD

**Issue by sidhreddy** [open-metadata/OpenMetadata#6977]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Longer entity names are not shown on Explore All Activity Page but instead show up as `...` and a hover revels the entity name

**To Reproduce**
* Have an entity with a really long name
* Update entity metadata (maybe add a new column)
* Run OM metadata ingestion and check for the Entity Activity on the `Explore` `All Activity` Page

Screenshots or steps to reproduce
<img width="985" alt="Screen_Shot_2022-08-26_at_12_18_12_PM" src="https://user-images.githubusercontent.com/49429859/186958754-97e4bf11-4ed2-4f67-a5c9-fc287672ff83.png">

**Expected behavior**
Display the table name instead of `...`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]: `0.11.5`
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
Fixed in [0.12.0](https://github.com/open-metadata/OpenMetadata/releases/tag/0.12.0-release) 
![image](https://user-images.githubusercontent.com/12962843/191172487-cd9c75ea-bbee-4188-8406-fb533c9068e5.png)
