### ISSUE TITLE
UI: Re-design pages and components to make them modular

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#699]
Basically Pages should have control of API calls and data, and no concerns with business logic
Whereas Components should be data-dumb but rich with business logic, they should accept data from pages and use handlers for RESTful operations

A step towards making modular and reliable components

Page to be refactored:

- [x] Dataset Details
- [x] Topic Details
- [x] Dashboard Details
- [x] Pipeline Details
- [ ] Database Details
- [ ] Service Details
- [ ] Services Page
- [ ] Teams Page
- [ ] Tags Page
- [x] Explore Page
- [x] Landing Page

**Comment by harshach** [comment]
@vivekratnavel lets add what we discussed in this ticket.

**Comment by sureshms** [comment]
@vivekratnavel, is this issue still relevant?
