### ISSUE TITLE
Add ability to create requests from entities in Python SDK

### ISSUE THREAD

**Issue by alogvinov-forter** [open-metadata/OpenMetadata#6994]
Let's take the `Table` entity as an example.

Python SDK provides a `CreateTableRequest` that can be used to create OR update a table. Currently, there is no way to use the `Table` entity to construct this request, so it has to be done manually:

```python
table_def = metadata.get_by_name(fqn=table_fqn, entity=Table)
​
table_request = CreateTableRequest(
    name = getattr(table_def, "name", None),
    displayName = getattr(table_def, "displayName", None),
    description = "New description",
    tableType = getattr(table_def, "tableType", None),
    columns = getattr(table_def, "columns", None),
    tableConstraints = getattr(table_def, "tableConstraints", None),
    tablePartition = getattr(table_def, "tablePartition", None),
    owner = getattr(table_def, "owner", None),
    databaseSchema = getattr(table_def, "databaseSchema", None),
    tags = getattr(table_def, "tags", None),
    viewDefinition = getattr(table_def, "viewDefinition", None),
    extension = getattr(table_def, "extension", None)
)
​
metadata.create_or_update(data=table_request)
```

`CreateTableRequest` expects that developer will list **all the fields**, and if some field is missing, it will be removed from the entity when the request is executed. However, fields may (and will - https://github.com/open-metadata/OpenMetadata/pull/6416) change, which will cause problems for people who use this API - they will have to check and update their code whenever they upgrade their OM instance to a new version.

It would be great if we could do something like this:

```python
table_def = metadata.get_by_name(fqn=table_fqn, entity=Table)
...
# modify the table here
...
request = CreateTableRequest(table_def)
```

In this case, SDK should take care of the fields, and no data should be lost during the request execution.

**Comment by harshach** [comment]
@pmbrull what are your thoughts here? Users need to use CreateTableRequest and use appropriate method to update the table such as PUT in this case it needs to have all the available fields if not use PATCH.
not sure if this is a valid request here if not lets close this out

**Comment by pmbrull** [comment]
this will also help in a couple of calls in the code as well to update profiler specific props. Just need the time to add the syntactic sugar for the PUT

**Comment by sureshms** [comment]
Table entity has a lot more information than what is allowed when a table is created using CreateTableRequest. As an example, followers, tests, queries, usage summaries all are available in the Table entity when you GET a table. However, the creation of all this information is done in separate APIs and not during table creation. Marking this as won't fix.
