### ISSUE TITLE
Logging level gets overridden when calling `set_loggers_level` method multiple times

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7006]
**Affected module**
Ingestion Framework

**Describe the bug**
We call the `set_loggers_level` method multiple times from different places, which overrides the logging level. This could take a user to stop seeing the expected logs.

**To Reproduce**
Run any ingestion with `DEBUG` as debug level and a workflow with `ERROR` as debug level. When the workflow starts, the initial debug level is overridden by the one from the workflow.

**Expected behavior**
We should be able to see `DEBUG` logs.

**Version:**
  - OpenMetadata version: 0.11.5

**Comment by pmbrull** [comment]
we might be able to clean this up by creating a WorkflowRunner

**Comment by harshach** [comment]
@pmbrull is this still a bug?

**Comment by pmbrull** [comment]
we can can close this. Handled with the centralized workflow management
