### ISSUE TITLE
Tableau View links don't generate properly

### ISSUE THREAD

**Issue by allegoricalJest** [open-metadata/OpenMetadata#7009]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Fontend?

**Describe the bug**
When clicking the link to a view in an ingested dashboard the url that opens is incorrect

**To Reproduce**

Screenshots or steps to reproduce
Click the link for any view of an ingested dashboard

**Expected behavior**
URL should open to the correct view

**Version:**
 - OS: Ubuntu
 - Python version: 3.9
 - OpenMetadata version: 0.11.5 (and previous versions I believe)
 - OpenMetadata Ingestion package version: 0.11.5 on GKE

**Additional context**
The link when opening a view for an ingested dashboard is incorrect. It generates with an extra slash after the server url and generates with spaces in the dashboard name.

https://server-url//#/site/SITE-name/views/Dashboard%20Name/ViewName (invalid url)
vs
https://server-url/#/site/SITE-name/views/DashboardName/ViewName (valid url)

**Comment by allegoricalJest** [comment]
It also looks like some of the dashboard links don't generate properly either generating as 

https://server-url/http://tableau-one/#/site/site-name/workbooks/### (incorrect) 

vs

https://server-url/#/site/site-name/workbooks/### (correct)

**Comment by pmbrull** [comment]
hi @allegoricalJest, we're trying to replicate the issue but haven't been able to reproduce it with Tableau Cloud.

We are picking up the URL from the `webpageUrl` property that the Tableau API gives us.

Could you please give us some more details on your Tableau deployment?

**Comment by OnkarVO7** [comment]
Hi @allegoricalJest 
This has been fixed as a part of `0.12.0` release
