### ISSUE TITLE
mssqlConnection.json miss 'supportsDatabase' property

### ISSUE THREAD

**Issue by Damon-Zeng** [open-metadata/OpenMetadata#7010]
**Affected module**
Ingestion Framework

**Describe the bug**
The "supportsDatabase" property is missing in mssqlConnection.json

**To Reproduce**
Run profiler ingest for mssql. It cannot run into the correct logic because it cannot pass the following conditional statement in ProfilerWorkflow.
` if hasattr( self.config.source.serviceConnection.__root__.config, "supportsDatabase",):`

Screenshots or steps to reproduce

**Expected behavior**
MSSQL support the database concept in its hierarchy, so we need to add 'supportsDatabase' property in its connection model.

**Version:**
 - OpenMetadata Ingestion: 0.11.5

**Comment by harshach** [comment]
Fixed.
