### ISSUE TITLE
Backend : Roles and policies is not effective on search/suggest API's

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7012]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

As we have roles and policies that are effective for other REST APIs we should have the same for the search/suggest APIs.

Example: My current logged-in user does not have viewAll permission but is still able to see all the results.

**Comment by harshach** [comment]
search apis integration is not implemented might go in 0.12.1 or 0.13

**Comment by harshach** [comment]
close it as duplicate
