### ISSUE TITLE
Backend : Policy rule description is not getting updated

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7013]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
The policy rule description is not getting updated

I'm using Policy patch API to update the policy rule description but it's not storing the updated description in the database.
For reference please watch the video.

https://user-images.githubusercontent.com/59080942/187184684-874130e4-aec0-4c2a-b8e4-fab83e692d4a.mov

**Comment by sureshms** [comment]
@Sachin-chaurasiya we test this functionality quite thoroughly. Need to see what is going on. Need requests/responses.

**Comment by harshach** [comment]
Reproducibel on sandbox-beta
<img width="671" alt="image" src="https://user-images.githubusercontent.com/38649/187315009-1f7cfe58-c328-49f1-be8f-90fb0879f3da.png">

request
<img width="723" alt="image" src="https://user-images.githubusercontent.com/38649/187315056-9fb45e81-5deb-4e1c-a071-aafed5c77c5b.png">

response
```
{"id":"0bdbd317-5e55-40f9-ac1a-5f14590d57e1","name":"Data Consumer Policy-1","fullyQualifiedName":"Data Consumer Policy-1","description":"data","href":"http://sandbox-beta.open-metadata.org/api/v1/policies/0bdbd317-5e55-40f9-ac1a-5f14590d57e1","policyType":"AccessControl","enabled":true,"version":0.1,"updatedAt":1661814970413,"updatedBy":"harsha","changeDescription":{"fieldsAdded":[],"fieldsUpdated":[],"fieldsDeleted":[],"previousVersion":0.1},"rules":[{"name":"Rule1","description":"test","effect":"allow","resources":["all"],"operations":["ViewAll","EditAll"]}],"deleted":false}
```

**Comment by sureshms** [comment]
@harshach okay, I thought it was the Policy description that is not getting updated. This is actually a rule in a policy and updating that description.
