### ISSUE TITLE
Clicking the notification should open the OpenMetadata page in the browser

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7026]
**Affected module**
UI

**Describe the bug**
When another user opens a task and assigns it to you, we get a browser notification.
But clicking on it will not take us to the open metadata UI and task details.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
#7068
