### ISSUE TITLE
DBT - Do not force to have both manifest and catalog

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7038]
We should be a bit more flexible and allow either of them.

The issue happens in two places:
1. For example for Local DBT config, if we don't pass both files, the pydantic model is not properly parsed and thinks we are talking about S3 config
2. We will need to revisit the loading functions and how we use the info later to make sure that if either is missing, there are no exceptions

**Comment by harshach** [comment]
@OnkarVO7 will it be handled in DBT refactoring

**Comment by OnkarVO7** [comment]
Yes @harshach
