### ISSUE TITLE
Handle databse filter in ingestion pipeline when connection specifies a database 

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7044]
When creating a new service and adding a database, database filter in the ingestion workflow will be ignore -- though nothing indicates this.

**Suggested solution**
Grey out (or remove) database filter when connection has a database value

**Comment by harshach** [comment]
@NiharDoshi99 any update on this?

**Comment by ShaileshParmar11** [comment]
Re-opening as only UI side changes are done!

**Comment by NiharDoshi99** [comment]
From Ingestion side it is already handled.
