### ISSUE TITLE
Automatic lineage from ML Model to data source

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#7056]
**Is your feature request related to a problem? Please describe.**
When we create ml models entities, we point out to the tables and features (table fields) used as data source. We get direct link to these tables as data sources from ml model entity, but lineages are not created at the same time automatically. Instead, users should add lineages from UI again manually. It would be logical if these lineages were created automatically based on data source uid added to model features. 

**Describe the solution you'd like**
When model feature gets data source added, system should add data lineages to data sources tables and fields. Because we already point out to these entities in open metadata when we create models. 
<img width="1372" alt="Screenshot 2022-08-30 at 15 56 19" src="https://user-images.githubusercontent.com/60112387/187443018-451981dd-1ead-4931-9f1a-12378329c8d5.png">
<img width="1417" alt="Screenshot 2022-08-30 at 15 58 16" src="https://user-images.githubusercontent.com/60112387/187443032-8c6c69d6-8315-46c4-a478-c7f397c7ccd3.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by pmbrull** [comment]
Thanks for opening this. We'll be handling that on 0.13.

Currently we have all the necessary ingredients and have a utility method to manage lineage on the Python client, but we should move this behavior to the backend itself so that it happens automatically
