### ISSUE TITLE
Feedback on 0.12 UI

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7071]
- [x] #7149
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1417689/187520583-e225df69-9cb2-4280-805d-45d3b2991e48.png"> 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/1417689/187520648-697a116d-bc46-46ad-abec-4c2868266217.png">

- [x] #7153
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/1417689/187521093-1cef9c14-d8c9-4ee3-91aa-1670da0ed1c4.png"> 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/1417689/187521158-eee7cd50-dade-4483-90eb-67c3374b5a5e.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/1417689/187522025-338db25e-0e37-4d57-ae84-14568e0c9ac8.png">

- [x] #7128
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1417689/187521750-4a0e89e9-39fe-461c-8e4f-9765a3308879.png"> 
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/1417689/187521798-3e5f69a7-9bed-401b-926c-c56a720c0a65.png">

- [x] Is there a reason to show a user's email address in the user listing? Instead, we could show roles or other information. Same comment for admin listing
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1417689/187523133-31db31d0-872e-4c7f-a65f-0aa2794339eb.png">

- [x] The name Organization should use `displayName` instead of `name` everywhere. One example - 
<img width="310" alt="image" src="https://user-images.githubusercontent.com/1417689/187523432-e24bed37-158b-4a3b-9440-db3008866053.png">

- [x] Join Group does not look right. Sometimes we have a switch on the right side, and here it is on the left.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1417689/187524021-1bab4fda-6026-41f0-8149-2790a3f38a08.png"> 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/1417689/187524163-3e661b45-7efe-4bb3-b0d4-113f107bcb88.png">

- [x] Team that has Open Group switch turned off. Still the Join Team button is enabled 
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1417689/187524393-70ebdcb4-0a28-40bd-9c7f-62e35e1beef0.png">

- [x] #7150
<img width="310" alt="image" src="https://user-images.githubusercontent.com/1417689/187526189-ecdd526d-0115-4d7d-91bb-8c8325a1f30f.png">
<img width="292" alt="image" src="https://user-images.githubusercontent.com/1417689/187526451-7173108a-8625-4b41-8ac7-b56f2a46dd4f.png"> 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/1417689/187526561-197646cd-ea1f-4a59-af26-2bb109d813bc.png">

- [x] #7151

- [x] #7152 @Ashish8689 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/1417689/187526866-5c46c4cc-a87e-489c-a1e8-89919195b338.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1417689/187526893-fcac885b-1707-45d3-b940-427cb2a14f90.png">
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/1417689/187526943-fb461d32-2ef1-4aa6-b585-83de0ae45b7e.png">

- [x] User name not clickable in dataset details page and in explore page (though hand appears sometimes): @aniketkatkar97 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1417689/187527109-bff47098-b964-41e6-be2d-3486b71412dc.png">
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1417689/187527201-242b096e-c1fa-4925-bcf3-9423e9c5e904.png">

**Comment by vivekratnavel** [comment]
- [ ] Multiple scrollbars (horizontal) in the Settings page
<img width="1728" alt="Screen Shot 2022-08-31 at 2 22 46 PM" src="https://user-images.githubusercontent.com/1051198/187787660-88c970c5-78de-423d-ab98-6767226add82.png">

**Comment by ulixius9** [comment]
- [ ] alignment issue for service not found page 

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/39544459/187933686-8c4619d5-f4ac-404c-b9b6-da843543da54.png">

**Comment by vivekratnavel** [comment]
- [ ] On the Explore page, the left menu bar styling is not right while scrolling for more content.

https://user-images.githubusercontent.com/1051198/187981575-1b6369a3-2983-4886-8e97-0dd4ed75dfda.mov

 cc @chirag-madlani

**Comment by devyani-kaushik** [comment]
- [ ] All icons seem to be of a different size
<img width="301" alt="Screenshot 2022-09-01 at 11 15 51 PM" src="https://user-images.githubusercontent.com/103238069/187979183-829ff028-a13a-4ff1-a112-8c507c4f16f7.png">

- [ ] Padding and alignment is a bit off here
<img width="282" alt="Screenshot 2022-09-01 at 11 19 11 PM" src="https://user-images.githubusercontent.com/103238069/187979736-1a0ecde7-466b-4aa9-82a9-9bdd0e4b8c12.png">

- [ ] Styling doesn't match the mocks @chirag-madlani 
<img width="1431" alt="Screenshot 2022-09-01 at 11 25 27 PM" src="https://user-images.githubusercontent.com/103238069/187980754-dcf0df57-4133-46dd-9513-411388055838.png">

- [ ] We can move the icons a little closer
<img width="203" alt="Screenshot 2022-09-01 at 11 33 45 PM" src="https://user-images.githubusercontent.com/103238069/187982646-bd0f19be-a596-43a7-a6e4-1cc65acbfa3f.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Slack webhook listing layout is not proper.
![image](https://user-images.githubusercontent.com/59080942/187986222-d0dcf16e-5f0b-445b-9e64-ceded4661e8b.png)

**Comment by Sachin-chaurasiya** [comment]
- [ ] Saving slack webhook redirects to webhook page.

https://user-images.githubusercontent.com/59080942/187992562-0ad655a4-57b1-426f-8d0e-d3dc5e32726c.mov

**Comment by sureshms** [comment]
- [ ] Change All Test to All Tests
<img width="190" alt="image" src="https://user-images.githubusercontent.com/1417689/188024889-72e5b2c6-6ac6-403c-968e-7a7812d6415f.png">

**Comment by harshach** [comment]
- [ ] data quality permissions, showing no permission to edit but allows me to delete 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/38649/188033116-79ae697d-4905-4800-a03d-756e9b64d5ec.png">

**Comment by devyani-kaushik** [comment]
- [ ] Update the catagory text color to #76746F
<img width="157" alt="Screenshot 2022-09-02 at 11 18 09 AM" src="https://user-images.githubusercontent.com/103238069/188067440-ff74e454-131b-4bfa-a9c0-1db808adabe6.png">

- [ ] Settings page left panel width and padding is not consistent with other pages

**Comment by harshach** [comment]
- [ ] Opening rule sections makes the arrow misalign 
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/38649/188210093-724cc443-a0a9-4c5b-9aab-fe80755123b0.png">

**Comment by vivekratnavel** [comment]
- [ ] Teams breadcrumb navigation doesn't look right to me.

https://user-images.githubusercontent.com/1051198/188248554-6b4ced4a-1fef-4701-acef-6e5835724338.mov

cc @devyani-kaushik

**Comment by ShaileshParmar11** [comment]
- [ ] Tags page:-  add new tag and delete category button size is not same

![image](https://user-images.githubusercontent.com/71748675/188257743-28befdac-131f-4919-a6de-118f002714c7.png)

**Comment by devyani-kaushik** [comment]
- [ ] Icons are not aligned 
<img width="310" alt="Screenshot 2022-09-03 at 11 56 21 AM" src="https://user-images.githubusercontent.com/103238069/188258736-5e85e389-6661-4bd3-b523-b4a52cd7f8a2.png">

- [ ] Remove the shadow here
<img width="746" alt="Screenshot 2022-09-03 at 11 57 55 AM" src="https://user-images.githubusercontent.com/103238069/188258798-d8830cf6-5d68-4c69-a95d-822c8d115622.png">

- [ ] Tier popup corner is edgy.
<img width="257" alt="Screenshot 2022-09-03 at 12 03 39 PM" src="https://user-images.githubusercontent.com/103238069/188258964-e59f852b-07df-4e28-b5bd-6870ce0ad12d.png">
<img width="196" alt="Screenshot 2022-09-03 at 11 58 49 AM" src="https://user-images.githubusercontent.com/103238069/188258823-d920696d-1e79-4679-9712-ddca9db8bafb.png">

- [ ] update all the tab stylings as per the mock
<img width="226" alt="Screenshot 2022-09-03 at 12 12 46 PM" src="https://user-images.githubusercontent.com/103238069/188259183-4b6cb1a9-f09b-4a84-bd2c-2c15aed9be07.png">

>> Mock
<img width="401" alt="Screenshot 2022-09-03 at 12 15 03 PM" src="https://user-images.githubusercontent.com/103238069/188259240-c1c09a8c-676b-4cd6-ad9f-86180aee1d12.png">

**Comment by vivekratnavel** [comment]
- [ ] Team of type "Group" cannot have sub-teams. We should not show "Add Team" button for these team pages
<img width="1724" alt="Screen Shot 2022-09-03 at 2 20 38 PM" src="https://user-images.githubusercontent.com/1051198/188288070-817f5c58-48a9-4558-8b29-be13bd420d39.png">

**Comment by chirag-madlani** [comment]
- [ ] make default table pageSize to 15 instead of 10.  @aniketkatkar97

**Comment by chirag-madlani** [comment]
- [ ] Update announcement layout as below image 2nd variant
 
<img width="641" alt="Screenshot 2022-09-01 at 4 53 07 PM" src="https://user-images.githubusercontent.com/12962843/188544247-5cb35b83-b609-4902-aa9c-6cd9cbbb7cff.png">

**Comment by ShaileshParmar11** [comment]
Closing as all the tasks are completed from this ticket
