### ISSUE TITLE
Asset Name on Glossary pages should include schema

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#7075]
**Is your feature request related to a problem? Please describe.**
It's a bit confusing to show multiple assets tagged to the same gloassry that are part of different schemas.
Example
 - schema_X.table_A
 - schema_Y.table_A

**Describe the solution you'd like**
Show {Schema}.{Table}

![image](https://user-images.githubusercontent.com/102999683/187595424-ee967b03-9ca9-48ff-a3ed-0a4a9b0f55aa.png)

**Comment by Ashish8689** [comment]
This is already fix in 0.12 


![Image](https://user-images.githubusercontent.com/66266464/194482285-5c644618-f4f5-4237-8142-c951458750ab.png)

**Comment by Ashish8689** [comment]
Re-opening this issue as currently we are showing the Database name and table name. We will be working on adding the schema name as well.

**Comment by Sachin-chaurasiya** [comment]
Closing this as it's already done and we do show schema in glossary asset.
![image](https://user-images.githubusercontent.com/59080942/199084411-2c24e9a9-ee5c-4802-bae7-b890c379d742.png)
