### ISSUE TITLE
UI bug when expanding glossary section

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#7077]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
The white frame around the glossary section is not expanding as glossary terms are open

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/187596260-320d4636-b012-4666-8ca8-b5d4a369002d.png)

**Expected behavior**
White frame is expanding with glossary tree

**Version:**
 - OS: Windows, Chrome

**Comment by ShaileshParmar11** [comment]
This issue has been fixed in OM 0.12


https://user-images.githubusercontent.com/71748675/189683781-7d104359-cc94-4216-a04e-596b289a18ef.mov
