### ISSUE TITLE
Profiler & Data Quality UI feedback & improvement

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7090]
- [x]  When landing on the profiler tab we should be able to add either profiler workflow or test suite workflow (with testCases). Right now to be able to view/add testSuite with testCases we need to first run the profiler -- cc @devyani-kaushik 
#7114
![image](https://user-images.githubusercontent.com/13626425/187712342-dd6a94cf-ef29-4a73-9e18-b1e800f0775c.png)

- [x] parameter definition for the custom SQL test is not displayed in an editor but as plain text
#7114
![Screenshot 2022-08-31 at 4 08 04 PM (2)](https://user-images.githubusercontent.com/13626425/187711956-a91e1817-d0d5-4965-9010-1e950ec5e90a.png)

- [x] the test is available for all column types regardless of type (should replicate the behaviour of 0.11 and filter out certain tests based on column type) it is tracked in #7105

![Screenshot 2022-08-31 at 5 07 42 PM](https://user-images.githubusercontent.com/13626425/187713023-514e26b1-4ecd-4600-9737-a3bf9c669370.png)

**Comment by ShaileshParmar11** [comment]
- [ ] Selecting some column-level tests breaks the UI

**Comment by pmbrull** [comment]
Error building the UI:
```
ℹ ｢wdm｣: Compiled successfully.
ERROR in src/interface/dataQuality.interface.ts:22:3
TS2305: Module '"../generated/tests/tableTest"' has no exported member 'TestCaseExecutionFrequency'.
    20 |   EntityReference,
    21 |   TableTestType,
  > 22 |   TestCaseExecutionFrequency,
       |   ^^^^^^^^^^^^^^^^^^^^^^^^^^
    23 |   TestCaseResult,
    24 | } from '../generated/tests/tableTest';
    25 |

ℹ ｢wdm｣: Compiling...
```

**Comment by ShaileshParmar11** [comment]
https://github.com/open-metadata/OpenMetadata/issues/7082

**Comment by TeddyCr** [comment]
- [ ] clicking on cancel or the table name in breadcrum when creating testcase/testsuite should bring user back to profiler view
https://user-images.githubusercontent.com/13626425/187727735-e83e7d36-d708-4611-a42e-82f2678994a7.mov
https://user-images.githubusercontent.com/13626425/187727741-c5b263f2-de12-46da-a1b8-897400307eaa.mov

- [ ] editing custom SQL tests does not display editor box correctly
![Screenshot 2022-08-31 at 5 33 34 PM](https://user-images.githubusercontent.com/13626425/187728041-b30460d3-1eee-4443-b41e-3b284a4e1de9.png)

**Comment by pmbrull** [comment]
When updating a test parameter, the boundary line of the past tests gets updated too. Then, it's strange to understand why a past test failed

![image](https://user-images.githubusercontent.com/35870520/187831237-d6b5de9c-ee24-4f13-b414-b7236104112e.png)

To replicate:
- add a parameter condition that will trigger test failure
- change the condition to an OK one
- rerun the test

**Comment by TeddyCr** [comment]
> - [ ] When updating a test parameter, the boundary line of the past tests gets updated too. Then, it's strange to understand why a past test failed
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35870520/187831237-d6b5de9c-ee24-4f13-b414-b7236104112e.png)
> 
> 
> 
> To replicate:
> 
> - add a parameter condition that will trigger test failure
> 
> - change the condition to an OK one
> 
> - rerun the test
> 
> 
> 
> Here I had the param originally at 10, but lowered at 6 to make the test pass

@pmbrull The line you are seeing here is not the boundary but the actual value returned by the test (I.e. you have 6 columns in your table).

**Comment by ShaileshParmar11** [comment]
> 

Even I am not sure about the same, Need to think about it because changing boundary line based on value with a dynamic chart seems very complex 🧐

**Comment by ShaileshParmar11** [comment]
- [ ] display all the tests at table level and provide filter option for the same
- [ ] add one column which contains redirection linked to the test suite and table
- [ ] Currently, we hiding profiler tab details if there is no profiler data, but instead, we should show the profiler tab dashboard so we have options to add data-quality tests and show some messages to enable profiler

**Comment by ShaileshParmar11** [comment]
- [ ] update the right panel guide as per the below test
Select/Create Test Suite
A Test Suite is a container consisting of multiple but related test cases. With a Test Suite, you can easily deploy a pipeline to execute the Test Cases.
Start by selecting an existing test suite or create a new test suite to create a table or column level test for an entity.

**Comment by TeddyCr** [comment]
@ShaileshParmar11 

- [ ] `columnValuesToBeNotNull` and `columnValuesToBeUnique` tests are not working on the UI side 

https://user-images.githubusercontent.com/13626425/187849800-eebc44fe-dfd3-451b-bbd2-dccc3ffa8c27.mov

**Comment by pmbrull** [comment]
@ShaileshParmar11 

- [ ] Clicking on a table from the lineage view to obtain more details throws an error and does not show further info on the table

![image](https://user-images.githubusercontent.com/35870520/187849963-07e7ff66-73c1-44c9-ab70-77cdf41f6377.png)

**Comment by TeddyCr** [comment]
- [ ] Setting should be available on schema tab otherwise we'll need to run the profiler first to then configure the profiler at the table level -- cc @pmbrull @harshach 
![Screenshot 2022-09-01 at 10 39 22 AM](https://user-images.githubusercontent.com/13626425/187871303-d601b394-51d7-41ca-834b-034db07e1b5e.png)
![Screenshot 2022-09-01 at 10 40 49 AM](https://user-images.githubusercontent.com/13626425/187871360-2b89f557-e742-453a-b59d-ef16ac707cc2.png)

**Comment by TeddyCr** [comment]
- [ ] When clicking on a struct we get an error saying the column could not be found
https://user-images.githubusercontent.com/13626425/187881750-2e5197ab-afae-4290-9d4e-6dcf3092f269.mov

**Comment by pmbrull** [comment]
- [ ] Getting 404 page after creating a test suite

1. Add test
2. Create test suite
3. Instead of "Add Ingestion" click on View Test Suite
4. You get 404

**Comment by ShaileshParmar11** [comment]
> * [ ]  Getting 404 page after creating a test suite
> 
> 1. Add test
> 2. Create test suite
> 3. Instead of "Add Ingestion" click on View Test Suite
> 4. You get 404

Hey, @pmbrull Have you tried the latest main? changes for the same is already pushed!

**Comment by pmbrull** [comment]
@TeddyCr Running the test suite workflow:

- [ ] Not finding test definition for ColumnValuesToBeInSet from an Integer. Should this be shown as ABORTED? It keeps the UI empty

```
[2022-09-01 13:32:35,936] {core.py:33} INFO - Executing test case Table Entity Deleted for entity mysql.default.openmetadata_db.table_entity
[2022-09-01 13:32:35,936] {sqa_interface.py:361} WARNING - Test definition ColumnValuesToBeInSet not registered in OpenMetadata TestDefintion registry. Skipping test case Table Entity
```

**Comment by ShaileshParmar11** [comment]
> @TeddyCr Running the test suite workflow:
> 
> * [ ]  Not finding test definition for ColumnValuesToBeInSet from an Integer. Should this be shown as ABORTED? It keeps the UI empty
> 
> ```
> [2022-09-01 13:32:35,936] {core.py:33} INFO - Executing test case Table Entity Deleted for entity mysql.default.openmetadata_db.table_entity
> [2022-09-01 13:32:35,936] {sqa_interface.py:361} WARNING - Test definition ColumnValuesToBeInSet not registered in OpenMetadata TestDefintion registry. Skipping test case Table Entity
> ```
> 
> ![image](https://user-images.githubusercontent.com/35870520/187927044-69fedd7e-88fa-4187-bbf0-955b99e6e13c.png)

Status is based on API response can you check and confirm if API is sending any status? also steps to reproduce would be appreciated

**Comment by pmbrull** [comment]
> > @TeddyCr Running the test suite workflow:
> > 
> > * [ ]   Not finding test definition for ColumnValuesToBeInSet from an Integer. Should this be shown as ABORTED? It keeps the UI empty
> > 
> > ```
> > [2022-09-01 13:32:35,936] {core.py:33} INFO - Executing test case Table Entity Deleted for entity mysql.default.openmetadata_db.table_entity
> > [2022-09-01 13:32:35,936] {sqa_interface.py:361} WARNING - Test definition ColumnValuesToBeInSet not registered in OpenMetadata TestDefintion registry. Skipping test case Table Entity
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/35870520/187927044-69fedd7e-88fa-4187-bbf0-955b99e6e13c.png)
> 
> Status is based on API response can you check and confirm if API is sending any status? also steps to reproduce would be appreciated

@ShaileshParmar11 updated the comment. Error is on the profiler. Thanks!

**Comment by chirag-madlani** [comment]
- [ ] Test case count should be visible on Profiler tab upfront besides test status

**Comment by chirag-madlani** [comment]
- [ ] Rename Profiler to "Profiler & Data Quality"

**Comment by chirag-madlani** [comment]
- [ ] update Add Test button with icon button @devyani-kaushik

**Comment by ShaileshParmar11** [comment]
- [ ] generate test name dynamically based on test type and entity type
