### ISSUE TITLE
Need to filter column test based on dataType

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#7105]
the test is available for all column types regardless of type (should replicate the behaviour of 0.11 and filter out certain tests based on column type)

![image](https://user-images.githubusercontent.com/71748675/187836672-a14ede9e-234e-4509-9db2-2d9200d725d3.png)

## Backend
- need filter from the backend to get a filter test type

## UI
- Consume API provided by backend in UI

**Comment by harshach** [comment]
@TeddyCr let me know if you can take this up as well
