### ISSUE TITLE
Look up, push, edit metadata using Integration with Microsoft Teams / JIRA / ServiceNow

### ISSUE THREAD

**Issue by upenbendre** [open-metadata/OpenMetadata#7108]
The users of Open MetaData in a large organisation would include several business users, techno-functional users, operational users, who may use Microsoft Teams and JIRA for collaboration. When a decision about defining classification rules, relationships between business terms etc is made collaboratively, it is likely that such discussions would happen on MS Teams, or in the comments section of JIRA / ServiceNow. If openmetadata had integration with these tools, it would allow the users to look up, push or edit metadata directly from the chat, and also publish notifications / alerts through the same channel.

Various scenarios possible:
1. Business users on an MS Teams channel / or a JIRA story, decide to publish new data quality rules for a Postgres database e.g, as soon as they arrive at a final version in a meeting, they tag OpenMetaData (or a pop-up for open-meta-data / plugin) shows them the existing ingestion or profiler details for that source. They add the data quality rules on this pop-up from Teams itself.
2. Data Quality rules as JIRA test cases -> A data quality test plan created in JIRA, could be pushed as Data quality rules to openmetadata. So the business / acceptance testing teams can continue working in JIRA as they always do.

Homegrown scripts / extensions using APIs provided by openmetadata, JIRA etc are possible, but the best option is integration through UI.

metadata tools with enterprise offerings seem to be building this. But they are not covering all the chat / collaboration tools that are commonly used.

**Comment by pmbrull** [comment]
cc @harshach
