### ISSUE TITLE
DB2 primary key and foreign key constraints metadata does not show up after ingestion

### ISSUE THREAD

**Issue by upenbendre** [open-metadata/OpenMetadata#7109]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
in the DB2 ingestion, is metadata for primary and foreign key constraints supposed to be ingested? I don’t see that ingested.
source:
  type: db2
  serviceName: test_db2DPS
  serviceConnection:
    config:
      type: Db2
      username: user
      password: password
      hostPort: db2host:50028/db0001
      # databaseSchema: schema
  sourceConfig:
    config:
      markDeletedTables: true
      includeTables: true
      includeViews: true
      # includeTags: true
      databaseFilterPattern:
        includes:
         - db0001
      #   excludes:
      #     - database3
      schemaFilterPattern:
        includes:
          - DPS
      #     - schema2
      #   excludes:
      #     - schema3
      #     - schema4
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: http://openmeta2.cloud:8585/api
    authProvider: no-auth

Expected:
Primary and Foreign key metadata should load.

**Version:**
 - OS: CentOS server
 - Python version: 3.9
 - OpenMetadata version: 0.11.5
 - OpenMetadata Ingestion package version:0.11.5

**Comment by TeddyCr** [comment]
cc @pmbrull

**Comment by nahuelverdugo** [comment]
This will be fixed by #9322 
/cc @pmbrull @TeddyCr

**Comment by pmbrull** [comment]
thanks @nahuelverdugo.

Closed by https://github.com/open-metadata/OpenMetadata/pull/9322
