### ISSUE TITLE
Kafka Ingestion for Schema Registry connection does not work when credentials are given as config basic.auth.user.info

### ISSUE THREAD

**Issue by upenbendre** [open-metadata/OpenMetadata#7112]
**Affected module**
Ingestion framework + UI

**Describe the bug**

**To Reproduce**
On the Kafka UI ingestion screen, the Schema Registry URL is given as https://someurl.com and the credentials are provided in the Schema Registry config:
basic.auth.user.info set as username:password

The error messages:
====================
Failed to test connection due to {"error": "Internal error testing connection Unrecognized configuration properties: dict_keys(['basic.auth.user.info']) - Traceback (most recent call last):\n File \"/usr/local/lib/python3.9/site-packages/openmetadata/api/rest_api.py\", line 209, in test_connection\n response = test_source_connection(test_service_connection)\n File \"/usr/local/lib/python3.9/site-packages/openmetadata/operations/test_connection.py\", line 36, in test_source_connection\n connection = get_connection(test_service_connection.connection.config)\n File \"/usr/local/lib/python3.9/functools.py\", line 888, in wrapper\n return dispatch(args[0].__class__)(*args, **kw)\n File \"/usr/local/lib/python3.9/site-packages/metadata/utils/connections.py\", line 342, in _\n consumer_client = AvroConsumer(consumer_config)\n File \"/usr/local/lib/python3.9/site-packages/confluent_kafka/avro/__init__.py\", line 141, in __init__\n schema_registry = CachedSchemaRegistryClient(sr_conf)\n File \"/usr/local/lib/python3.9/site-packages/confluent_kafka/avro/cached_schema_registry_client.py\", line 116, in __init__\n raise ValueError(\"Unrecognized configuration properties: {}\".format(conf.keys()))\nValueError: Unrecognized configuration properties: dict_keys(['basic.auth.user.info'])\n"}

====================

**Expected behavior**
The data source connection should get tested successfully since basic.auth.user.info is mentioned in Confluent docs. The only way the connection tests successful is when there is no Schema Registry config given. Instead the credentials are given within the URL. i.e. https://user:pass@someurl.com

**Version:**
 - OS: Server: CentOS 7, Client MacOS Monterey - Intel
 - Python version: 3.9
 - OpenMetadata version: 0.11.5
 - OpenMetadata Ingestion package version: 0.11.5

**Additional context**
I have also tried using the basic.auth.credentials.source property in addition to basic.auth.user.info but still get the same error.

**Comment by harshach** [comment]
@nahuelverdugo since you are testing Kafka, can we cover this in this process. I've tested and it worked

**Comment by harshach** [comment]
@upenbendre not sure why are you passing the credentials in the url form. No client supports that

**Comment by nahuelverdugo** [comment]
> @nahuelverdugo since you are testing Kafka, can we cover this in this process. I've tested and it worked want to double check

I will double check 👍

**Comment by nahuelverdugo** [comment]
@upenbendre, thank you for submitting this bug, I was able to reproduce it locally, and there is already a PR with the fix, which will probably be part of the 0.12 version.

cc: @harshach
