### ISSUE TITLE
Not able to connect to External Hive Metastore which is deployed in mysql

### ISSUE THREAD

**Issue by mukheshnarra** [open-metadata/OpenMetadata#7121]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework

**Describe the bug**
Trying to connect the external hive metastore deployed in Mysql using delta lake connector. Unable to Connect because of bug in deltalake connector which is confirmed by OpenMetadata Support Team.

Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/55047128/187899027-15e27e66-1064-49ee-900d-0103ce8da8c3.png)

**Comment by harshach** [comment]
@mukheshnarra for Hive connector we are not using hivemetastore, why not use hive connector directly to fetch the data? also for hive we need hiverserver 2 connection

**Comment by pmbrull** [comment]
Reference: https://openmetadata.slack.com/archives/C02B6955S4S/p1662025121552689

@harshach to give some more context here, we are configuring the Deltalake ingestion setting `hive.metastore.uris` to the Spark Session to reach the metastore. Looks like @mukheshnarra is able to use instead `spark.hadoop.javax.jdo.option.ConnectionURL` and directly pass the MySQL instance and not the Hive service
