### ISSUE TITLE
UI - improve design for pipeline status

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#7127]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

**To Reproduce**

<img width="1472" alt="Screenshot 2022-09-01 at 7 09 57 PM" src="https://user-images.githubusercontent.com/12962843/187928451-89f20c1d-ec14-4b8e-828f-e90ca16117f0.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
@ShaileshParmar11 Add filter for timeseries to get status

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=14437%3A23135
