### ISSUE TITLE
UI: @Mention filter doesn't work in Entity page activity feeds tab

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7137]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
@Mention filter doesn't work in Entity page activity feeds tab

**To Reproduce**
Change the filter to @Mention 

**Expected behavior**
It filters only the mentioned conversations

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
The payload does not include user id to filter by @Mentions.

**Comment by Sachin-chaurasiya** [comment]
Hey @vivekratnavel , I think there is some backend issue as well for the mention filter with entity link.

Uploading Screen Recording 2022-09-02 at 12.49.28 AM.mov…

**Comment by vivekratnavel** [comment]
@Sachin-chaurasiya I have updated PR #7143 with backend fixes.
