### ISSUE TITLE
Backend : Slack Webhook is not working as expected

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7138]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend.

**Describe the bug**
Slack Webhook is not working as expected,  I have opted for topics, dashboards, pipelines and models but I'm getting notifications for tables too.

![image](https://user-images.githubusercontent.com/59080942/187992034-201efe33-6379-4573-a7f2-347b49761389.png)

**To Reproduce**

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/59080942/187992105-4f8789f5-b3ca-4733-9ce5-acbe8cb03c46.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by mohitdeuex** [comment]
@Sachin-chaurasiya the request for webhook is wrong .

There are so many entities for which we have not provided any filter to the user , we just listed 4-5 of them, and we wanted those entities to be allowed to pass through the filter. So there is a wildcard filter 'all' underneath which handles such scenario.

Now for the entities we don't want to any updates at all, we should have entry in the filter list , but no filters selected (which means the user doesn't want to get any updates for that entity).
If we remove the entity entry completely it is as if that the user has not added any filters for that entity (that will be qualified with wildcard filter). This is the reason we are getting the updates for the table.

**Comment by mohitdeuex** [comment]
This was already explained ... it should be working fine since request are created properly now
