### ISSUE TITLE
Let's use consistent styling (I prefer the third one)

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#7150]
<img width="310" alt="187526189-ecdd526d-0115-4d7d-91bb-8c8325a1f30f" src="https://user-images.githubusercontent.com/51777795/188502699-50a168b9-36f1-40ce-b6f0-dbba7c27db86.png">
<img width="292" alt="187526451-7173108a-8625-4b41-8ac7-b56f2a46dd4f" src="https://user-images.githubusercontent.com/51777795/188502707-f8abc26a-3d42-414e-bd97-3ddedf41a45d.png">
<img width="165" alt="187526561-197646cd-ea1f-4a59-af26-2bb109d813bc" src="https://user-images.githubusercontent.com/51777795/188502709-9ade62d7-b4de-401c-afeb-f74667cb94c8.png">

**Comment by harshach** [comment]
@aniketkatkar97 please file clear description on whats this ticket about

**Comment by ShaileshParmar11** [comment]
Placeholders are updated and PR are merged to main
