### ISSUE TITLE
`Mark Deleted Topics` in messaging service connectors

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7157]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have an option `Mark Deleted Topics` in the messaging service connectors as we have `Mark Deleted Tables` in the database services ones. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pmbrull** [comment]
fixed by https://github.com/open-metadata/OpenMetadata/pull/10695/files#diff-eb847a74de8bb8209673bc048d828bee119171b932a36914311da64b47c4a7b4
