### ISSUE TITLE
Backend: List teams API throwing 404 for soft deleted team even with include=all

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#7172]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
List teams API throwing 404 for soft deleted team even with include=all param

**To Reproduce**

Screenshots or steps to reproduce
Soft delete a team and then hit teams list API with filter parent team as the deleted team name and include=all param
<img width="1440" alt="Screenshot 2022-09-02 at 9 30 58 PM" src="https://user-images.githubusercontent.com/51777795/188194060-2788330d-1019-4728-b1c1-0398cfc0c272.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97 why are we making calls with included=all in the teams listing page. By default any soft deleted entities shouldn't be shown cc @chirag-madlani
