### ISSUE TITLE
add description lags

### ISSUE THREAD

**Issue by WalonDreamer** [open-metadata/OpenMetadata#7184]
https://user-images.githubusercontent.com/12093397/188253919-d068551a-4bb6-4794-bc1a-0dc9ce878be0.mp4

**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
when i add any description，from click the save button to  display finally，it lasts more than 10 seconds，is it normally？ step1 click save ----wait nearly 10 seconds-------> step2 display finally

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya lets double check if we need to update the comments and conversations thread count on description update. 
Secondly if its needed lets wait on updating description. Perceived latency vs actual latency is always a problem in UI. We need optimize for perceived latency in all UI interactions.

**Comment by Sachin-chaurasiya** [comment]
@harshach @WalonDreamer,  description update and comments and conversations thread count update API calls are independent.

**Comment by harshach** [comment]
@Sachin-chaurasiya based on the video above it looks like browser is waiting on the entityLink responses to update the description. Are we updating the description immediately after the patch response?

**Comment by Sachin-chaurasiya** [comment]
Yes @harshach .

**Comment by harshach** [comment]
so @Sachin-chaurasiya my point is that. Lets not wait for those entityLinks to return the response. We should just update the description. User is updating the description and their expectation is UI update the description immediately while we are waiting for other information. We should update the description and update the entityLink updates as they come

**Comment by Sachin-chaurasiya** [comment]
@harshach , We are updating the description immediately after we get the response, we are not waiting for `entityLinks` to return the response.
