### ISSUE TITLE
Backend: Patching teams API for team type is not working properly

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#7187]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Hitting the teams API with PATCH for team type updation, returns success status, but the updated value is not reflecting in team details.

**To Reproduce**

Screenshots or steps to reproduce

https://user-images.githubusercontent.com/51777795/188261742-d9e493b8-d444-4244-b6d3-b90fa4c16c8d.mov

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97 can you paste the request/response api calls

**Comment by aniketkatkar97** [comment]
Patch request :
- URL -` /api/v1/teams/:id`
- Payload - `[{op: "replace", path: "/teamType", value: "Division"}]`
- Response - `{
    "id": "...",
    "teamType": "Division",
    "name": "Customer_Support",
    "fullyQualifiedName": "Customer_Support",
    "displayName": "Customer_Support",
    "description": "This is Customer_Support description.",
   ...
}`
