### ISSUE TITLE
UI: Improve UX on API calls from a modal dialog

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7198]
When API calls are made from a modal dialog for example in an edit description of an entity flow,  when the user clicks on the "Save" button, the dialog box closes immediately regardless of the response status.

This will be bad UX if the API call fails for some reason since the user has to type in the lengthy description again and try to save again. 

Expected Behavior:

- Disable the "Save" button, and show a loading indicator when the API call is being made.
- If the response is success, change the loading indicator to a green check mark and then close the modal dialog 
- If the response if failure, show the error message in the modal dialog itself and enable the "Save" button for the user to retry

https://user-images.githubusercontent.com/1051198/188285481-ed9cb088-9cc8-44d2-8003-6082c9d63c02.mov

**Comment by Sachin-chaurasiya** [comment]
- [ ] Delete Entity Modal
- [ ] Create/Edit Announcement Modal
- [ ] Profiler Settings Modal
- [ ] Entity Description Modal

- Teams Page
- [ ] Add team modal
- [ ] Add role modal
- [ ] Add policy modal

- Glossary Page
- [ ] Add Reviewers Modal

- Tags Page
- [ ] Delete Tag Modal
- [ ] Add Tag Modal
- [ ] Delete Tag Category Modal
