### ISSUE TITLE
Query parser not able to recognise table with special char during usage

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#7216]
**Affected module**
Ingestion Framework

**Describe the bug**
While running the usage for snowflake query parser is not able to detect queries for tables with special characters like `$`

for example `TEST$JIRA_TABLE`

**Comment by pmbrull** [comment]
Let's validate first the impact of this. We can ask the user how many tables are impacted and tune the priority accordingly

**Comment by harshach** [comment]
@ulixius9 @nahuelverdugo what are we blocked on?

**Comment by pmbrull** [comment]
@harshach some of the changes need to be done on the `sqllineage` repo. We are waiting to have the big first patch in to start building the evolutions directly there
