### ISSUE TITLE
`unhashable type: 'list'` when using list of boolean in `in_()`

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7225]
This is due to some errors in `python-bigquery-sqlalchemy`. Ticket raised here -> more info https://github.com/googleapis/python-bigquery-sqlalchemy/issues/489

**Comment by harshach** [comment]
@TeddyCr are you planning on providing a patch to the google lib ?

**Comment by TeddyCr** [comment]
@harshach FYI looks like it might be a bigger issue than a simple commit to the repo https://github.com/googleapis/python-bigquery-sqlalchemy/issues/489#issuecomment-1253731826
