### ISSUE TITLE
Create test suite ingestion pipelines with underscores instead of spaces

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7279]
**Affected module**
UI

**Describe the bug**
When an ingestion pipeline for a test suite with spaces on the name is created, the UI tries to get the status for a DAG name that does not exist.

**To Reproduce**
- Create a Test Suite for any table with a space, e.g., `Test Suite`:
![image](https://user-images.githubusercontent.com/11074908/188724689-4f50f3e4-9cbf-4137-adfb-0f52c627f6a1.png)
- In the `pipeline` tab of the test suite, we see this:
![image](https://user-images.githubusercontent.com/11074908/188725396-1988f923-0c95-4ae0-8013-8c11d88eeddc.png)
but in Airflow, we have:
![image](https://user-images.githubusercontent.com/11074908/188725339-0a06151f-6973-48cd-a226-1b5f39141bb5.png)

This cause running it to be impossible.

**Expected behavior**
The UI should get the status for the same DAG name created in Airflow and also allow the user to run the DAG.

**Version:**
 - OpenMetadata version: 0.12
 
 ** Additional issue **
 The link to the ingestion points to the wrong URL.

cc: @TeddyCr

**Comment by Sachin-chaurasiya** [comment]
@nahuelverdugo, Can you share the API response for this?

**Comment by nahuelverdugo** [comment]
@Sachin-chaurasiya, this is the request sent from UI:
```bash
curl 'http://localhost:8585/api/v1/testSuite' \
  --data-raw '{"name":"test with space","description":"test","owner":{"id":"2aa243fe-8837-4c7f-8058-c4c0c87fc2cc","type":"user"}}' 
```
Then we sent:
```bash
curl 'http://localhost:8585/api/v1/testCase' \
  --data-raw '{"name":"bot_entity_TableColumnCountToBeBetween","description":"","entityLink":"<#E::table::local_mysql.default.openmetadata_db.bot_entity>","parameterValues":[{"name":"minColValue","value":0},{"name":"maxColValue","value":1}],"owner":{"id":"2aa243fe-8837-4c7f-8058-c4c0c87fc2cc","type":"user"},"testDefinition":{"id":"aae4f7a8-e8a3-4216-897c-21a1396165ad","type":"testDefinition"},"testSuite":{"id":"b40707ae-1874-4e2d-87e6-903ebbf673eb","type":"testSuite"}}' \
  ```
  And after clicking `Submit` for creating the ingestion:
  ```bash
  curl 'http://localhost:8585/api/v1/services/ingestionPipelines' \
  --data-raw '{"airflowConfig":{},"name":"test with space_TestSuite","pipelineType":"TestSuite","service":{"id":"b40707ae-1874-4e2d-87e6-903ebbf673eb","type":"testSuite"},"sourceConfig":{"config":{"type":"TestSuite"}}}' 
  ```
  When adding a test suite with spaces in the name, you can check the same calls in the `Developers Tools` of `Chrome`.
