### ISSUE TITLE
Org : Add Domain Verification for OpenMetadata Org

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7290]
By verifying the domains controlled by our organization on GitHub, we can give more confidence to people visiting our GitHub page that they are actually viewing our organization’s GitHub page.

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization

https://github.blog/changelog/2018-08-07-domain-verification/

**Comment by harshach** [comment]
@Sachin-chaurasiya this is done. Please re-open if necessary
