### ISSUE TITLE
Custom test definition can be selected from the UI

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7309]
When creating custom test definitions we can select them from the UI. We should filter for OM only test definition as by definition we do not know how to process custom test definition -- cc @harshach let me know if i am missing something here.

![Screenshot 2022-09-07 at 3 06 33 PM](https://user-images.githubusercontent.com/13626425/188885688-a1fb01d9-5c15-457e-84c0-d1a2c3cfcb27.png)

**Comment by harshach** [comment]
@TeddyCr there is providers option for every test definition , we should only pickup test definitions if the provider is "openmetadata" cc @ShaileshParmar11

**Comment by TeddyCr** [comment]
@harshach we don't have a way to filter by `testPlatforms` -- if i am not mistaking. I can work on adding that on the backend if that works with you.

**Comment by harshach** [comment]
@TeddyCr if you have time, please go ahead and add it. Similar work needs to happen to list the test cases by column type
