### ISSUE TITLE
Table tests and Column show up in table data summary + count disapear

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7310]
When clicking on the "Data Quality" tab in the top row we list both table and column tests summary, is that expected? I was under the impression only table tests would be listed here.

Also, when going from "Data Quality"/"Profiler" tab to the "Summary" tab the count disapear.

https://user-images.githubusercontent.com/13626425/188887047-1a4ec7d8-bb7e-4c77-8169-d56352997e09.mov

**Comment by ShaileshParmar11** [comment]
Hello, @TeddyCr Yes showing all the tests in the data quality test is intentional and also we have provided a filter for the same to filter out the table and column test!
Another one seems like a bug, I'll have a look! Thanks

**Comment by harshach** [comment]
@ShaileshParmar11 the counts should be linked and redirected to appropriate page

**Comment by ShaileshParmar11** [comment]
Fixed with #7325
