### ISSUE TITLE
Glossary Management Screen UI behaviour. 

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#7312]
**Affected module**
Glossary Management UI

**Describe the bug**
When the number of Terms increases the tree overflows at  the bottom. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/112470575/188899045-ab94d2d7-6f63-4391-aeb4-61c337952157.png)

**Expected behavior**
A vertical scroll bar should appear to avoid overflow. I suggest also adding a lateral slider, so tree width can be resized. Dealing with special characters in terms name or descriptions when creating terms should be desirable too.

**Version:**
 - OS: RHEL 7.9
 - Python version: 3.8.13
 - OpenMetadata version: 0.11.2
 - Browser: Google Chrome 102.0.5005.63
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
It’s fixed in 0.12.0 release
