### ISSUE TITLE
Feedback 0.12 release

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#7334]
@ShaileshParmar11  will take care of all these issues

- [ ] Table Styling different on custom properties tab on entity page.
UI Comment:-
This will be taken care in 0.12.1 as we are going to replace all the existing table with ANTD table
<img width="1381" alt="Screenshot 2022-09-06 at 1 05 38 PM" src="https://user-images.githubusercontent.com/103238069/188574694-a74e3a14-9bde-44b1-997d-ac450cbd7d99.png">

- [ ] Add an empty table for Model Store as well when there's no data
UI Comment:-
As the field of model store will be dynamic, due to which we can not show it in empty table
<img width="1433" alt="Screenshot 2022-09-06 at 2 39 26 PM" src="https://user-images.githubusercontent.com/103238069/188595578-de1b56f3-52a2-4a30-b479-b95ca93d26c0.png">

_Originally posted by @devyani-kaushik in https://github.com/open-metadata/OpenMetadata/issues/7248#issuecomment-1237832285_

**Comment by harshach** [comment]
- [ ] When there is no status lets not show any status 
![image](https://user-images.githubusercontent.com/38649/189238214-5a18a1b8-1d9f-48aa-9932-8aa2c285e754.png)
