### ISSUE TITLE
Backend: Search API returns no results for query with space

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#7338]
**Affected module**
Backend

**Describe the bug**
Hitting the search API with query containing space returns no results even if the entity exists.
 URL - `http://localhost:3000/api/v1/search/query?q=*%20AND%20(service.name:local+mysql)&from=0&size=10&sort_field=updatedAt&sort_order=desc&index=table_search_index`

Payload - `q: * AND (service.name:local mysql)
from: 0
size: 10
sort_field: updatedAt
sort_order: desc
index: table_search_index`

Response - 
<img width="739" alt="Screenshot 2022-09-08 at 5 03 33 PM" src="https://user-images.githubusercontent.com/51777795/189112036-08e778d8-2cc9-4ec6-8539-de1a3f53fcdc.png">

**To Reproduce**

https://user-images.githubusercontent.com/51777795/189111331-3a074eeb-62b6-4a27-ac97-fb0c55af43f6.mov

**Expected behavior**
It should return relevant results.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
For anything with space we need to add double quotes
