### ISSUE TITLE
Error fetching sample data from MSSQL v. 12.0.6329

### ISSUE THREAD

**Issue by Zarah-hh** [open-metadata/OpenMetadata#7357]
**Affected module**
Ingestion Framework

**Describe the bug**
Error fetching sample data from MSSQL v. 12.0.6329
I've done Profiler Ingestion completely but there is no data in 'Sample Data' tab.
Also, got warning in log 
`[2022-09-09 08:04:36,842] {core.py:389} WARNING - Error fetching sample data: (pymssql._pymssql.ProgrammingError) (102, b"Incorrect syntax near '100'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")`

**To Reproduce**

Screenshots in Thread of reply https://openmetadata.slack.com/archives/C02B6955S4S/p1662716909253669

**Expected behavior**

**Version:**
 - OS: Ubuntu
 - Python version:
 - OpenMetadata version: 0.12.0
 - OpenMetadata Ingestion package version: 0.11.5.3

**Additional context**
ref. slack thread https://openmetadata.slack.com/archives/C02B6955S4S/p1662716909253669
![image](https://user-images.githubusercontent.com/113189216/189365045-30b35956-c415-4a2b-8122-de690c852305.png)
![image](https://user-images.githubusercontent.com/113189216/189365084-f5554f99-8ed7-4d81-97fc-8b79bab33501.png)
![image](https://user-images.githubusercontent.com/113189216/189365164-8eb98b9d-bf0c-4d08-b692-83df2561dd96.png)

**Comment by TeddyCr** [comment]
@Zarah-hh the error might come from a version discrepancy between what we are testing it with and what you are using. We have used 15.x.x to test this connector while your version is 12.x.x. We are working on replicating this error in MSSQL 12.x.x on our end to ship a fix. 

If you are able to do so, upgrading to MSSQL 15.x.x should fix this error.

**Comment by pmbrull** [comment]
@akash-jain-10 to give an EC2 instance by 14/09

**Comment by pmbrull** [comment]
Version 12 of MSSQL is no longer supported. We will not be adding backwards compatibility for databases after their EOL
