### ISSUE TITLE
Dagster integration must work with its API and enable dagster cloud 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7362]
**Is your feature request related to a problem? Please describe.**
Currently, Dagster integration only works with MySQL and its bypassing the API from dagster 
This requires us to build an integration to all the DBs that Dagster supports and it will be harder to configure and maintain.
Let’s use the API and only enable data that comes from those APIs

**Comment by NiharDoshi99** [comment]
Hi , I will work on this task.
