### ISSUE TITLE
UI : Remove the dependency of rc-tree, react-table from code

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7367]
Remove the dependency of rc-tree, and react-table from the code

**Comment by Ashish8689** [comment]
https://github.com/open-metadata/OpenMetadata/pull/8019
https://github.com/open-metadata/OpenMetadata/pull/8025
https://github.com/open-metadata/OpenMetadata/pull/8049
https://github.com/open-metadata/OpenMetadata/pull/8001
