### ISSUE TITLE
Reading secret values from existing keys

### ISSUE THREAD

**Issue by nataliezeller1** [open-metadata/OpenMetadata#7369]
Currently, when working with secret manager, OpenMetadata is in charge of creating keys in SSM/AWS Secret Manager. 
We would like to have the option to use existing keys, created with the Organization's standard format.

The suggested solution is to allow entering parameter key instead of plain text values for any sensitive information (user, password...).

**Comment by nahuelverdugo** [comment]
This has been fixed by https://github.com/open-metadata/OpenMetadata/pull/8617. We can use secret ids on the password fields following the convention `secret:{secret_id}`. The documentation is pending to be merged here https://github.com/open-metadata/OpenMetadata/pull/8771
