### ISSUE TITLE
Azure Data Lake gen2 Connector

### ISSUE THREAD

**Issue by mukheshnarra** [open-metadata/OpenMetadata#7379]
**Is your feature request related to a problem? Please describe.**
Azure Data lake gen2 connector helps connect to container deployed and manage the entities which are deployed

**Describe the solution you'd like**
Have Connector just like AWS S3, GCS

**Comment by hardiktalati** [comment]
@NiharDoshi99  and @pmbrull  Kindly update on when this feature would be available.

**Comment by knoerregaard** [comment]
Looking for connector that connects to Azure Data Lake Storage Gen2. An easy way to connect to files and Delta Lake with hierarchical namespace feature of gen2.

**Comment by pmbrull** [comment]
Hi folks, we'll implement this for 0.13.1. Thanks
