### ISSUE TITLE
Getting error while deploying any database service

### ISSUE THREAD

**Issue by abhijeet0801** [open-metadata/OpenMetadata#7383]
**Affected module**
ingestion Framework

**Describe the bug**
 When I try to deploy MySQL or Clickhouse database services, using openmetadata provided ingestion  docker service (airflow). I get error of "[Failed to generate workflow [workflow_name] verify config is correct: Could not get service from type databaseService] "}. I am using 0.12 version with docker deployment and using custom MySQL RDS connection

**To Reproduce**

Screenshots or steps to reproduce. 
Provide database credentials in add database service option, click on ingestion and click on Deploy
<img width="329" alt="OM-issue" src="https://user-images.githubusercontent.com/113355276/189652796-6c613430-7593-4623-adc8-4f9fe1dd34b1.PNG">

**Expected behavior**
A DAG of ingesting metadata should be created in Airflow and metadata should be extracted from source

**Version:**
 - OS: [e.g. Linux]
 - Python version: 3.9
 - OpenMetadata version:  0.12
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by miguel-chacon** [comment]
I had the same issue. If you have some kind of SSO enabled, review the ingestion bot set up.

**Comment by hertznsk** [comment]
I encountered this error in version 0.13.0. I use SSO (Keycloak). Ingestion-bot settings are correct.  It works correctly on version 0.12.3.

**Comment by harshach** [comment]
@hertznsk can you come and join https://slack.open-metadata.org so that we can take a look closely. we can't reproduce
