### ISSUE TITLE
Allow Profile Sample to be set using at the decimal point

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7392]
In the 2 location where we can set profile sample we should be able to set a decimal sample

![Screenshot 2022-09-12 at 5 57 27 PM](https://user-images.githubusercontent.com/13626425/189700897-efedcd88-3e8a-45eb-a38b-422c01f64e3e.png)
![Screenshot 2022-09-12 at 5 58 48 PM](https://user-images.githubusercontent.com/13626425/189700940-878ac6f0-7087-4964-8e36-bf9e9d776c80.png)

**Comment by ShaileshParmar11** [comment]
completed with https://github.com/open-metadata/OpenMetadata/pull/7485
