### ISSUE TITLE
If the airflow service not available we throw IP exception

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7409]
**Affected module**
Backend

**Describe the bug**
When the airflow is not available we still make the call to get the IP address of the container and backend will throw an error
<img width="536" alt="image" src="https://user-images.githubusercontent.com/38649/189838647-c61eed6c-92b2-48b5-86f7-8f2bafbbcf8c.png">

**Expected behavior**
UI should make the status call first and only if it succeeds we should make a call to get the IP address
Backend should never throw an exception in this case. As getting these details are informative not necessarily an issue to throw exception back

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
@Sachin-chaurasiya could you please update the UI code to validate that the Airflow REST is available before querying for the IP?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya could you please update the UI code to validate that the Airflow REST is available before querying for the IP?

Sure, @pmbrull.
