### ISSUE TITLE
Ingest Athena tags from CLI Automatically

### ISSUE THREAD

**Issue by jsuarez-ravenpack** [open-metadata/OpenMetadata#7414]
- We would like to have the ability to assign specific tags to a dataset upon ingestion so we do not have to this manually as part of an ingestion workflow.

**Comment by pmbrull** [comment]
Hi @jsuarez-ravenpack, you should be able to use the following methods https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/tests/integration/ometa/test_ometa_patch.py#L195 as in this test file to get this automation done.

Thanks!

**Comment by jsuarez-ravenpack** [comment]
Great thanks for the update
