### ISSUE TITLE
ES indexing does not work in Linux Mint distribution

### ISSUE THREAD

**Issue by jsuarez-ravenpack** [open-metadata/OpenMetadata#7415]
After many attempts and with the help of [Nahuel Verdugo Revigliono] we were not able to install OM in my local PC.

**Comment by nahuelverdugo** [comment]
The current issue is related to Elasticsearch, which is not indexing any table in the searches.
- ES is up and running
- We can query ES from the local machine and openmetadata-server service
- We tried solution proposed [here](https://github.com/open-metadata/OpenMetadata/discussions/5300)

**Comment by Lapeth** [comment]
Issue appears when running OM in containers (on Mint).

Reindexing ElasticSearch (with Recreate Indexes = Yes) fixes the issue, but it reappears if containers are stopped with `docker-compose down`. Restarting containers with `docker-compose restart` does not trigger the issue.
