### ISSUE TITLE
0.12 Bots are not getting created in k8s.

### ISSUE THREAD

**Issue by EminUZUN** [open-metadata/OpenMetadata#7424]
0.12 Bots are not getting created in k8s.
Deployment of ingestion are slow, it may have any relation with that.

**Comment by EminUZUN** [comment]
Ingestion bot does not seem to exist. But it is doing some stuff :) 
![image](https://user-images.githubusercontent.com/8695124/189929785-b6cbd78c-0da3-46d7-b9c6-ba884d169dad.png)

**Comment by harshach** [comment]
@nahuelverdugo @chirag-madlani
1. UI need to disable creating bots flag in user creation step
2. @nahuelverdugo once we have the backend support for creating the bots through bot entity and @chirag-madlani we need UI support for that

**Comment by Sachin-chaurasiya** [comment]
@harshach, First Part is handled with [this](https://github.com/open-metadata/OpenMetadata/pull/7476) Patch.
