### ISSUE TITLE
[Docker Deployments] Bootstrapped Ingestion Bot does not appear on UI

### ISSUE THREAD

**Issue by abcabhishek** [open-metadata/OpenMetadata#7426]
**Affected module**
Server/UI

**Describe the bug**
Ingestion Bot (`ingestion-bot`) created during bootstrap step is not showing up on the UI on 0.12.0

**Expected behavior**
Ingestion Bot created during bootstrap step should appear on the UI

**Version:**
 - OpenMetadata version: 0.12.0

**Comment by Sachin-chaurasiya** [comment]
@nahuelverdugo , Can we close this issue?
As we have merged this PR https://github.com/open-metadata/OpenMetadata/pull/7559?

**Comment by nahuelverdugo** [comment]
You are right @Sachin-chaurasiya this has been fixed by https://github.com/open-metadata/OpenMetadata/pull/7559
