### ISSUE TITLE
Add support for sorting data assets by popularity

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7433]
**Feature**
#7430 

**Describe the task**
Add support for sorting data assets by popularity that includes the number of followers and thumbs up as signals

**Comment by harshach** [comment]
@07Himank lets add voting value as another sort value in the UI 
cc @karanh37

**Comment by karanh37** [comment]
Fields added by backend
`sort_field=votes.upVotes` || `sort_field=votes.downVotes`

Reference Url 
`http://localhost:8585/api/v1/search/query?q=&index=table_search_index&from=0&size=10&deleted=false&query_filter=%7B%22query%22%3A%7B%22bool%22%3A%7B%7D%7D%7D&sort_field=votes.upVotes&sort_order=desc`
