### ISSUE TITLE
Github Actions: Run Cypress Integration Tests with PostgreSQL backed OpenMetadata Instance

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#7435]
**Is your feature request related to a problem? Please describe.**
Run Cypress Integration Tests with PostgreSQL backed OpenMetadata Instance.

**Comment by akash-jain-10** [comment]
Use Github Actions Matrix Strategy in order to run Cypress Tests. The Matrix will depend upon 2 values that is passed to `run_local_docker.sh` script - `mysql` and `postgresql`.

**Comment by akash-jain-10** [comment]
Hello @harshach , Do we want to run cypress integration tests for PostgreSQL as part of every commit or just a once a day ?
cc- @vivekratnavel

**Comment by harshach** [comment]
once per day is good enough
