### ISSUE TITLE
UI: Profile picture is different in the user menu

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7441]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Notice the color of profile picture background being different in the User menu in the top right corner.
<img width="1728" alt="Screen Shot 2022-09-13 at 12 19 58 PM" src="https://user-images.githubusercontent.com/1051198/189990963-a1d84a3b-5e2c-4c16-8c14-9d1f585c83cd.png">

**Expected behavior**
Profile picture is the same everywhere

**Comment by Sachin-chaurasiya** [comment]
Completed with #7451
