### ISSUE TITLE
Backend : Search API pagination is not working as expected.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7445]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend.

**Describe the bug**
I am making search queries with `size=10` but getting all the responses.

https://sandbox-beta.open-metadata.org/api/v1/search/query?q=%2A&index=table_search_index&size=10

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Should return the paginated response.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.12]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani update the ticket with the details since you were testing this.

**Comment by chirag-madlani** [comment]
@harshach We tested it in local and it's reproducible in local as well with elasticsearch
Sharing screenshot for more context

Request:

![image](https://user-images.githubusercontent.com/12962843/190970298-f6b69a53-5727-49f3-8b15-8e3634a21eb8.png)

Response:

![image](https://user-images.githubusercontent.com/12962843/190970336-1278dd3a-444c-4210-bdcd-16fa5cd36656.png)
