### ISSUE TITLE
Add Freshness Metrics for the profiler

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7447]
For a select number of DBAPI (at minimum snowflake, redshift and bigquery) we should show the timeline of table insertion update (datetime). We should rely on the syslog of the DBAPI to do so

**Comment by pmbrull** [comment]
Hi @TeddyCr, thanks for the writeup. Just a minor comment (as always, open for discussion):

- What is the goal of having properties such as `isInsert`, `isUpdate`...? Could we handle the query type in an enum? (INSERT, UPDATE, DELETE).

The rest looks great, looking forward to it

**Comment by TeddyCr** [comment]
Makes a lot of sense. I like it better actually.
