### ISSUE TITLE
Base sqlalchemy requirement cannot be installed on GCS Composer 2.2.5

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7453]
We initially tested the GCS ingestion from 2.1.4 and that was working perf.

GCS Composer 2.2.5  has some backward versioning incompatibilities on requirements for sqlalchemy that impact our side. Been trying to align version installation without any luck.

A couple of possible scenarios here would be:
- have a different package `openmetadata-ingestion-composer` without the profiler base requirements. That would require a different workflow but does not impact the majority of the current cases.
- move the profiler requirements as a plugin, which might force some users to manually install it on their current setups.

**Comment by pmbrull** [comment]
I might be leaning more and more towards setting this up as a plugin

**Comment by pmbrull** [comment]
We might want to think about this in the context of https://github.com/open-metadata/OpenMetadata/issues/2848 and https://github.com/open-metadata/OpenMetadata/issues/5014. Modularising into a plugin might be a good idea.

**Comment by pmbrull** [comment]
We can take it up from https://github.com/open-metadata/OpenMetadata/pull/7211/files

**Comment by harshach** [comment]
@pmbrull @TeddyCr are we targeting for 0.12.1?

**Comment by pmbrull** [comment]
Check with GCS folks

**Comment by pmbrull** [comment]
will aim to solve this with https://github.com/open-metadata/OpenMetadata/pull/8065

**Comment by nahuelverdugo** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/8065
