### ISSUE TITLE
UI throws fetch entity count error when there is no data in ElasticSearch

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7466]
**Affected module**
UI

**Describe the bug**
When user installs OpenMetadata and no data is ingested , navigating to Explore page throws the fetch entity count error
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/38649/190205600-805a8b9e-2408-42ba-97d2-ecff84b645f5.png">

**Expected behavior**
It is clear from the UI steps there is no data in ElasticSearch so do not throw a error

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
This is still happening, double check and close it if it fixed.

**Comment by chirag-madlani** [comment]
@harshach Yes it's happing we have this issue on the sandbox should be fixed in 0.12.1
