### ISSUE TITLE
KafkaConnection secrets viewable in UI

### ISSUE THREAD

**Issue by ehausig** [open-metadata/OpenMetadata#7468]
**Is your feature request related to a problem? Please describe.**

In order to setup a connection to a secured Kafka cluster (e.g. Confluent Cloud), custom config values must be added to the "Consumer Config" of the KafkaConnection:

`security.protocol`
`sasl.mechanism`
`sasl.username`
`sasl.password`

Similarly, to connect to a secured Schema Registry the following config value must be added to the "Schema Registry Config":

`basic.auth.user.info`

Both the `sasl.password` and `basic.auth.user.info` config values are secrets, however they are not masked can can be viewed as clear text in the UI. This is problematic from a security perspective.

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/16280871/190233356-5b9575af-3ae7-45fa-bb5c-ca64af475c9b.png">

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16280871/190233382-4f995e37-eb32-41de-8361-35c58e9b0aac.png">

**Describe the solution you'd like**
I don't think that secrets should be viewable by default on a web form, they should be masked. (Ideally, they should also be encrypted when persisted to storage.)

There are probably a number of different ways to address the issue of it appearing on the UI. One way may be to simply mask config values for keys known to contain secrets (e.g. `sasl.password`, `basic.auth.user.info`.) Another way may be to provide a tailored UI for the user, similar to how the PostgreSQL connection is laid out.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by nahuelverdugo** [comment]
@harshach, do we want to encrypt these parameters in the backend using Fernet?

**Comment by harshach** [comment]
@nahuelverdugo yes, lets do that

**Comment by Sachin-chaurasiya** [comment]
@nahuelverdugo , Are we gonna handle this in `0.13.0`?

**Comment by harshach** [comment]
@nahuelverdugo since you are going to look at secrets can we handle this? if not lets move it out

**Comment by nahuelverdugo** [comment]
@harshach I am going to start to work on this soon so I will update this ticket depending on the approach.

**Comment by chethan-bs** [comment]
@nahuelverdugo - also we need to look on ingestions logs which is printing as clear text.  connections can be avoid to view only for admins but ingestions logs is viewing for everyone.

**Comment by harshach** [comment]
@nahuelverdugo can we handle this for 0.13.1?

**Comment by harshach** [comment]
@nahuelverdugo any update on this?

**Comment by nahuelverdugo** [comment]
We decided to move it to 1.0 at the end as we have to address some other topics related to security like [this](https://github.com/open-metadata/OpenMetadata/issues/8648).

**Comment by nahuelverdugo** [comment]
This will be covered by #8981
