### ISSUE TITLE
UI: Don't show Glossary Terms in "Draft" status for "Add Tag"

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7471]
If a Glossary Term has its status as "Draft", it should not be shown in "Add tag" dropdown or any other dropdown until the term is reviewed by the assigned reviewers and approved.

**Comment by harshach** [comment]
@vivekratnavel you need to finish the approval process only then we can enable this.

**Comment by vivekratnavel** [comment]
Blocked on #3090

**Comment by ShaileshParmar11** [comment]
Currently, all the glossary term has the `draft` status! so if we implement this feature, we won't able to see any glossary term while adding tags
