### ISSUE TITLE
UI: Display glossary term status if status is "Draft"

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7472]
A glossary term's status should be displayed on the Term page if it is in draft mode.

**Comment by vivekratnavel** [comment]
Blocked on #3090

**Comment by ShaileshParmar11** [comment]
Currently, we are getting `status: draft` for all the glossary terms, seems like it is hardcoded at the backend side!
Should we go ahead and show the status in UI? @harshach

**Comment by chirag-madlani** [comment]
@harshach @sureshms  Are we planning to have approval workflow for glossary for this release?
