### ISSUE TITLE
Sandbox - Database Service Update Owner shows only limited users

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#7475]
**Affected module**
UI
![image](https://user-images.githubusercontent.com/15995028/190312058-27857624-207b-4878-b36f-9133d41fc089.png)

**Describe the bug**
It seems the UI is not showing all the teams and users when you want to update owners in Database Service Page!

**To Reproduce**

- Login to sandbox.open-metadata.org
- Navigate to Settings >> Database Services
- Click on Owners to update

**Expected behavior**
THe UI should show all the teams and users at the first glance.

**Version:**
 - OpenMetadata version: 0.12.0

**Additional context**
Need to check if this issue persists on other services update owner functionality.

**Comment by harshach** [comment]
@Sachin-chaurasiya @chirag-madlani api listing works fine, any reason we are only displaying partial resutl
cc @vivekratnavel

**Comment by harshach** [comment]
@chirag-madlani @Sachin-chaurasiya here is the call output from sandbox
<img width="484" alt="image" src="https://user-images.githubusercontent.com/38649/191098577-9f3c7ef3-e2ff-45b4-899e-dd313f697dff.png">

You have a total count, and the limit is set to 10. You need to display the total count in the users(11) -> users(1747). Use a bigger limit like 50 and add More.. at the end for users to add more users to the list.

This should've been caught by a test
