### ISSUE TITLE
Add logic to fetch log use react-lazylog

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7477]
Large logs cause the browser to crash. We should use https://www.npmjs.com/package/react-lazylog to parse the logs

**Comment by pmbrull** [comment]
we will need to update the get_last_logs endpoint to support pagination. Work on the Airflow REST APIs and AirflowRESTClient backend apis

**Comment by pmbrull** [comment]
compression will no longer be needed as well
