### ISSUE TITLE
UI: New service names overflow the box displayed while creating new services

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7480]
**Issue**
After the changes in this [issue](https://github.com/open-metadata/OpenMetadata/issues/7407), some service names overflow the box displayed while creating new services. As is shown below:

![image](https://user-images.githubusercontent.com/11074908/190358929-2cbf7913-04b2-4628-9864-07876d9d36c3.png)

This is happening for all the custom services created:
- `CustomPipeline`
- `CustomDatabase`
- `CustomDashboard`
- `CustomMessaging`
- `CustoMlModel`

**Comment by pmbrull** [comment]
@devyani-kaushik @Sachin-chaurasiya I was thinking about maybe having a separated button to add a custom service instead of having this special case in the "usual" service list. Feel free to explore that idea (or toss it away).

Thanks!
