### ISSUE TITLE
UI bag dashboards tab

### ISSUE THREAD

**Issue by AntonArgon** [open-metadata/OpenMetadata#7482]
**Affected module**
UI

**Describe the bug**
Navigation in the dashboards tab is not working correctly

**To Reproduce**
1) Go to https://sandbox.open-metadata.org/explore/dashboards/.
We see 12 dashboards, the top one "dim-address"
![image](https://user-images.githubusercontent.com/108890829/190358610-02526b67-b901-4999-9b71-598b4132010d.png)

2) Mouse click on "dim-address"
![image](https://user-images.githubusercontent.com/108890829/190359457-136b9c66-2b40-443f-9be5-86644378f851.png)

3) Go back to the list dashboards by pressing the button in the browser go back
![image](https://user-images.githubusercontent.com/108890829/190360110-9fc969f1-b7ba-4bd5-9daf-81701d881fc8.png)

As you can see in the figure, the topmost report is now [ETA Predictions Performance](https://sandbox.open-metadata.org/dashboard/sample_superset.eta_predictions_performance) 

**Version:**
  - OpenMetadata version: [0.12.0.0]
 -  Browser Firefox or Google Chrom

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Thanks, @AntonArgon for filing a ticket, this issue is tracked with [UI : Explore page data loading issue](https://github.com/open-metadata/OpenMetadata/issues/7403)
