### ISSUE TITLE
java.lang.ClassNotFoundException: org.openmetadata.service.security.NoopAuthorizer in OpenMetadata Server

### ISSUE THREAD

**Issue by HolgerMeyer** [open-metadata/OpenMetadata#7486]
**Affected module**
The UI will not start.

**Describe the bug**
Error code in command line: "container for service "openmetadata-server" is unhealthy" when trying to start OpenMetadata using `metadata docker --start`

**To Reproduce**
1. Activate Env
2. Run `metadata docker --start`

**Expected behavior**
Usually the CLI will display that the server has been started successfully on port 8585. 

However Error code is displayed in CLI.
When inspecting logs of openmetadata_server container, error: `java.lang.ClassNotFoundException: org.openmetadata.service.security.NoopAuthorizer` is shown.

**Version:**
 - OS: macOS Monterey 12.5.1
 - Python version: Python 3.9.13
 - OpenMetadata version: 0.12
 - OpenMetadata Ingestion package version: 0.12.0.0

**Additional context**
I have attached the logs of the metadata_server container as well as the CLI logs.
<img width="517" alt="CLI" src="https://user-images.githubusercontent.com/113591088/190398700-9dc5b9df-f358-490d-82aa-4af77b7f83b0.png">
<img width="769" alt="Openmetadata-Server" src="https://user-images.githubusercontent.com/113591088/190398877-25f5c6fa-4640-4cb8-a634-052e11385de2.png">

**Comment by clark94** [comment]
I am facing the same issue, Could Someone Help me?

**Comment by pmbrull** [comment]
please, check the docs on the PR. It will help you update your quickstart deployment. running `metadata docker --clean` will clean up your test local environment and use the new release compose file. More info on the docs. Thanks
