### ISSUE TITLE
Show table size

### ISSUE THREAD

**Issue by ChrisWB** [open-metadata/OpenMetadata#7488]
Today I need to check the size (in MB) of a table and of certain segments of a table via SQL statements.

Showing the size of a table and the average size of certain segments of a table in OM would be a real benefit. 
Example to get the size [MB] of a table in Oracle called "BWA":
SELECT DS.TABLESPACE_NAME, SEGMENT_NAME, ROUND(SUM(DS.BYTES) / (1024 * 1024)) AS MB
  FROM DBA_SEGMENTS DS
  WHERE SEGMENT_NAME IN (SELECT TABLE_NAME FROM DBA_TABLES) AND TABLESPACE_NAME = 'TAB_ALL' AND SEGMENT_NAME = 'BWA'
 GROUP BY DS.TABLESPACE_NAME, SEGMENT_NAME;

Moreover it would be very helpful to get the average size for a certain group of rows inside a table.
Example: In the table "BWA" we have n companies, identified via a company number. I would like to see the average size in MB for a company. So we would need to count the number of distinct companies in the column "companies" and divide the size of the table in MB through the number of companies.
Perhaps it would be possible to define certain columns to put a COUNT DISTINCT on it and divide it by the size of the table.

**Comment by TeddyCr** [comment]
@ChrisWB regarding the table size, we'll be implementing it [here](https://github.com/open-metadata/OpenMetadata/issues/4565). As far as the size of data in a specific column feel free to open a PR if you would like to contriute. We'll be more than happy to help. 🙂
