### ISSUE TITLE
Nested column collapse issue frontend

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#7491]
**Affected module**
UI

**Describe the bug**
while expanding or collapsing one nested column other columns also get expanded or collapsed 

https://user-images.githubusercontent.com/39544459/190417869-b7b63a2e-3e7c-413d-b607-886cc9de6b90.mov

**Comment by ShaileshParmar11** [comment]
Providing key to data will resolve this issue
