### ISSUE TITLE
Airflow console doesn't come up when the ingestion container is restarted

### ISSUE THREAD

**Issue by gaurav-ravi** [open-metadata/OpenMetadata#7493]
**Affected module**
- UI: Airflow console is not starting up
- Backend: Missing managed Airflow APIs when viewing ingestion for services.

**Describe the bug**
- The Airflow console on (http://localhost:8080) is not reachable. The error message (**Safari can't open the page "localist:8080" because the server unexpectedly dropped the connection. This sometimes occur when the server is busy. Wait for a few minutes and then try again**) 
<img width="613" alt="Screenshot 2022-09-15 at 13 35 39" src="https://user-images.githubusercontent.com/104371569/190431484-ff4edeea-1d66-490c-9e76-ad2e1224725d.png">

- The ingestions configured for a service will not be visible anymore. Instead we see an error message (**Failed to find OpenMetadata - managed Airflow APIs**) 
<img width="1213" alt="Screenshot 2022-09-15 at 13 35 54" src="https://user-images.githubusercontent.com/104371569/190431291-25f478b2-9fec-4e4d-a717-1f6ffe97f687.png">

**To Reproduce**
1. Download [docker-compose-postgres.yml](https://github.com/open-metadata/OpenMetadata/releases/download/0.12.0-release/docker-compose-postgres.yml) to a local directory.
2. Run `docker-compose up` to create the containers
3. Verify that you can open the Airflow console (http://localhost:8080)
4. Stop all the containers with command `docker-compose stop`
5. Restart all containers with command `docker-compose start`
6. After the containers are started and are healthy, try opening the Airflow console (http://localhost:8080) - the console will not be available

**Expected behavior**
- When all the containers are restarted (using docker-compose), the expectation is to have the Airflow and OpenMetadata console to be accessible.
- The managed Airflow APIs should be available to the ingestion services through the OpenMetadata console

**Version:**
 - OS: macOS Monterey (Version 12.5.1)
 - Python version: 3.10.6
 - OpenMetadata version: [0.12.0-Release](https://github.com/open-metadata/OpenMetadata/releases/tag/0.12.0-release)
 - OpenMetadata Ingestion package version: 0.12.0.0

**Additional context**
- The problem can be reproduced on both podman and docker container engines.
- I am not using the metadata cli to build and start the containers. I primarily use podman as the container engine and we dont have the cli support for podman (as of yet)
- The ingestion container log is attached for reference. This is extracted soon after the container is restarted - 
[ingestion_container_log.log](https://github.com/open-metadata/OpenMetadata/files/9576170/ingestion_container_log.log)

**Comment by akash-jain-10** [comment]
Hello @gaurav-ravi  - I'm able to reproduce the issue provided the above steps. However, Can you help us understand what is the reason to stop the containers for your use case ?

I did some research around the commands available with `docker compose` and here is something that I found you can give it a try - 

[Docker Compose Pause](https://docs.docker.com/engine/reference/commandline/compose_pause/)
`docker compose --file docker-compose-postgresql.yml pause` to pause the process running by docker containers.

[Docker Compose Unpause](https://docs.docker.com/engine/reference/commandline/compose_unpause/)
`docker compose --file docker-compose-postgresql.yaml unpause` to unpause or resume the process running by docker containers.

### When to use docker stop and docker pause?
**docker stop:** When you wish to clear up memory or delete all of the processes' -cached- data. Simply put, you no longer care about the processes in the container and are comfortable with killing them.

**docker pause:** When you only want to suspend the processes in the container; you do not want them to lose data or state.

If you are using `metadata docker CLI`, we do have the CLI commands to pause and unpause the containers using `metadata docker pause` and `metadata docker unpause`.

Also, if you are using [podman-compose](https://github.com/containers/podman-compose), it provides pause and unpause operations on the services running.

Let us know if this helps!

I've verified pausing and unpausing the OpenMetadata cocker compose services works as expected!

cc - @vivekratnavel @harshach

**Comment by akash-jain-10** [comment]
Hello @gaurav-ravi . Apologies it took some more time to test! With `0.12.1` we are revamping and centralising Docker Image for ingestion and I tested the same scenario mentioned in the original issue request. I can confirm that stopping and starting ingestion containers with docker compose works as expected.

We are going to release `0.12.1` in the next week. Please try the same at your end and verify the same!

Reference PR - https://github.com/open-metadata/OpenMetadata/pull/7456

Thanks.

**Comment by gaurav-ravi** [comment]
No worries @akash-jain-10. I will try out the new patch-set when its out. Thanks for your support once again.
