### ISSUE TITLE
Metadata Ingestion Workflow with SSL enabled in OpenMetadata server

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#7495]
**Is some content missing, wrong or not clear?**

After enabling SSL 2 steps are neccessary to run a successful metadata ingestion command via CLI:

1. Update the workflow section of YAML config file to the new https endpoint. 
https://docs.open-metadata.org/openmetadata/connectors/database/hive/cli#metadata-ingestion

workflowConfig:
  openMetadataServerConfig:
    hostPort: **https:**//localhost:8585/api

2. Specify an environment variable with the path to the certificate used for SSL (pam format):

export REQUESTS_CA_BUNDLE="/path/to/cacert.pem"
metadata ingest -c <path-to-yaml>

**Describe the solution you'd like**
Enable a "certificate path" parameter in metadata command and/or document required steps in SSL configuration section:
https://docs.open-metadata.org/openmetadata/connectors/database/hive/cli

**Comment by pmbrull** [comment]
let's use this ticket for documenting the solution from the PR

**Comment by nahuelverdugo** [comment]
This ticket was closed by: https://github.com/open-metadata/OpenMetadata/pull/10053 and https://github.com/open-metadata/OpenMetadata/pull/7502.
