### ISSUE TITLE
Test Connection Result Appears to be cached

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7497]
**Problem**
When creating a service with an invalid connection and testing it the result appears to be cached
1) Modifying the credentials to valid ones (before having pressed save) will still result in the same error message. e.g. create a BQ service with a credential file path that is fake and test the connection. Then update the credential type to credential values enter the correct values and test the connection again -> you should see the same error message as when testing the connection with the credentials file path

**Comment by TeddyCr** [comment]
Putting in ingestion but we need to investigate the root cause

**Comment by harshach** [comment]
@OnkarVO7 does your PR fixes this issue?

**Comment by OnkarVO7** [comment]
@harshach this [PR](https://github.com/open-metadata/OpenMetadata/pull/7823) fixes issues where the connections details where getting cached for e.g in case of tableau which the user was facing.

This particular issue is specifically related to bigquery which has a different problem. Trying to figure out this issue.

**Comment by TeddyCr** [comment]
@OnkarVO7 can we close this?
