### ISSUE TITLE
UI permission denied to edit lineage on Topics

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7510]
**Affected module**
UI

**Describe the bug**
After ingesting topic data, we cannot edit the lineage in the UI from the topic entity. We can, however, edit lineage from any other entity and link the topic.

**To Reproduce**

Ingest topic data (you can follow https://github.com/open-metadata/openmetadata-demo/tree/main/redpanda) and try to edit lineage on the topic

![image](https://user-images.githubusercontent.com/35870520/190604200-60b03d61-2b69-41c0-ba3d-72cc76f6dbe5.png)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
@pmbrull , Can you check what permission you have for the topic resource?

**Comment by Sachin-chaurasiya** [comment]
Hello @pmbrull , Need your input on this 🙏 .

**Comment by pmbrull** [comment]
hi @Sachin-chaurasiya , this was with the default deployment, no security, no changes whatsoever just ingesting the data

**Comment by pmbrull** [comment]
and sorry for the delay, missed the first ping

**Comment by Sachin-chaurasiya** [comment]
@pmbrull, Can you try again and check if this still exists?

**Comment by pmbrull** [comment]
@Sachin-chaurasiya yes, still happening. You can replicate it with a fresh installation and test on the sample data

**Comment by Sachin-chaurasiya** [comment]
Thanks, @pmbrull , I will check that out.
