### ISSUE TITLE
Track new primary keys in table

### ISSUE THREAD

**Issue by stepanof** [open-metadata/OpenMetadata#7513]
**Is your feature request related to a problem? Please describe.**
I can't understand when primary keys were added to the table.

**Describe the solution you'd like**
OM now track the only existing primary keys. 
![image](https://user-images.githubusercontent.com/68236577/190640675-5bd1b00d-1a65-4e7a-b017-e30736021516.png)
(existing primary key was deleted)

If new primary key is added to the table it will be visible in the UI but the fact of appearing the new key won't be shown in "All Activity" page.
![image](https://user-images.githubusercontent.com/68236577/190640608-fb0b693f-a624-4b8b-89d8-a3daf67f9c14.png)

It would be very helpful to see when new primary keys were added.

**Comment by harshach** [comment]
@stepanof thanks for the feedback. We will handle it in 0.13

**Comment by harshach** [comment]
@mohityadav766 this should be happening now can you try to reproduce this , if we are versioning the constraint addition or not.
