### ISSUE TITLE
UI - Transparent expand button allows to accidentally click on external links in descriptions

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#7514]
**Affected module**
UI

**Describe the bug**
Expanding button in descriptions doesn't cover enough text. If you have an external link in description field which happens to be just in line with the expand button, you will accidentally click on this link instead of expanding the field. For more details, please see screenshots attached.

**To Reproduce**
1. Mis-clicked somewhere near the dropdown button
![image (1)](https://user-images.githubusercontent.com/60112387/190670952-bf58cb1d-feef-4e1c-a385-4f8116b70529.png)
2. Got email service opened instead
![image (2)](https://user-images.githubusercontent.com/60112387/190670977-2569fdcf-c75c-4b8b-91e6-959107f9fb9b.png)
3. Expanded the field and saw that I have an email mentioned here
![image](https://user-images.githubusercontent.com/60112387/190671494-2ba5b635-4b75-487e-9549-c2cd141db837.png)

**Expected behavior**
Perhaps, a more dense transparency would make do. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya @devyani-kaushik I thought we changed this control to "Read More" link?

**Comment by Sachin-chaurasiya** [comment]
@harshach @Tonilyn, This has been fixed in `0.12.0`.

https://user-images.githubusercontent.com/59080942/190949001-f80de5c9-e0cb-4ebb-96c6-1d58d44d646b.mov
