### ISSUE TITLE
Add nightly tests for Helm charts deployment.

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7518]

**Comment by harshach** [comment]
Currently cypress tests runs on docker based deployment. However we ran to several issues in 0.12.0 release which would've been caught had we run cypress tests on helm charts as well. So the goal of this ticket is to bring up nightly a fresh helm charts based deployment and kick off cypress tests. cc @akash-jain-10

**Comment by akash-jain-10** [comment]
Once we have the preview release, we will do a manual testing of cypress integration tests along with @ShaileshParmar11 here and provide a conclusion to this issue.

**Comment by harshach** [comment]
@akash-jain-10 lets prioritize this and close it out
