### ISSUE TITLE
camelCase package names cause compilation failure

### ISSUE THREAD

**Issue by dr3s** [open-metadata/OpenMetadata#7521]
**Affected module**
backend

**Describe the bug**
This is probably not technically a bug but when compiling with Azul zulu 11 openjdk, the camelCase packages get compiled to all lower case, which fails the class compilation of dependent classes.

for example `package org.openmetadata.schema.services.connections.mlModel;` gets compiled to `org.openmetadata.schema.services.connections.mlmodel`

**To Reproduce**

Run `mvn install` on the parent project

result:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/145115/190716667-fef416f3-79a5-4a03-8a45-93f663e6cac5.png">

**Expected behavior**
package conventions are all lower case and this seems to be a requirement of some JVMs.  I'm using zulu 11 because I'm on an M1 mac

**Version:**
 - OS: MacOS 12.6
 - Python version: 3.9
 - OpenMetadata version: 0.12
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-spec[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@dr3s curious why not use openjdk?

**Comment by dr3s** [comment]
technically zulu is openjdk.  But to answer your question, adoptopenjdk and oracl openjdk didn't have M1 ARM builds.  It appears that adoptopenjdk now does so I'll give that a try.

**Comment by dr3s** [comment]
I get the same error with `adoptopenjdk-11.0.16+101` as I did with `zulu-11.54.25`.  I checked the generated sources and they are camelCase.  I checked the classes and they are lower case package names.  Compile error:
<img width="2008" alt="image" src="https://user-images.githubusercontent.com/145115/190838522-57e1fb4e-d30d-4284-b958-11a1b0b8b3cf.png">

**Comment by harshach** [comment]
@dr3s I just did a build OpenJDK 11.0.16.1

<img width="949" alt="image" src="https://user-images.githubusercontent.com/38649/190838742-f7b734ab-d646-425a-85e2-fdde866fb9ce.png">
it works for me on a M2 Mac 
I am not aware of java being case insensitive about the package names
can you check if your file system is being case insensitive?

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/38649/190838828-30d8b993-da97-4a67-a99a-f7d50e5b5149.png">

**Comment by harshach** [comment]
@dr3s we just pushed a fix for it, can you pull in latest main and try it again. Thanks

**Comment by dr3s** [comment]
looks ok, not sure why I had so much trouble with this change
