### ISSUE TITLE
UI is not listing any teams during the edit of ownership

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7527]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by vivekratnavel** [comment]
@harshach It looks like the teamType filter is not working in this ES API call - `https://sandbox.open-metadata.org/api/v1/search/query?q=*%20AND%20teamType:Group&from=0&size=10&index=team_search_index`

TeamType is not present in the response as well.
