### ISSUE TITLE
Test Connection Result Appears to be cached

### ISSUE THREAD

**Issue by sivaarumalla** [open-metadata/OpenMetadata#7528]
Problem
When creating a service with an invalid connection and testing it the result appears to be cached

Modifying the credentials to valid ones (before having pressed save) will still result in the same error message. e.g. create a BQ service with a credential file path that is fake and test the connection. Then update the credential type to credential values enter the correct values and test the connection again -> you should see the same error message as when testing the connection with the credentials file path

**Comment by harshach** [comment]
another ticket https://github.com/open-metadata/OpenMetadata/issues/7497

**Comment by harshach** [comment]
@ulixius9 @OnkarVO7 can we close these tickets?

**Comment by OnkarVO7** [comment]
@harshach will test it once before closing

**Comment by harshach** [comment]
@OnkarVO7 @ulixius9 any updates here?

**Comment by ulixius9** [comment]
Fixed with #9352
