### ISSUE TITLE
Backend : Webhook description update is not working

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7537]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
When we try to edit the description of a generic webhook, it's not getting updated. for slack and MS Team it's working as expected.

Please watch the screen recording.

https://user-images.githubusercontent.com/59080942/190956040-2cfba53f-1f1d-4db9-a982-39c729be8614.mov

**Expected behavior**
The update description should work.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.12]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
@mohitdeuex, assigning this to you
