### ISSUE TITLE
Profiler metrics are not formatted correctly

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7552]
![Screenshot 2022-09-19 at 2 32 17 PM](https://user-images.githubusercontent.com/13626425/191018336-67ec67b1-83a1-45c4-bb40-109495b4a9ff.png)
- [ ] Large numbers are not formmatted correctly with the coma speration

![Screenshot 2022-09-19 at 2 32 49 PM](https://user-images.githubusercontent.com/13626425/191018333-f6adaabb-83dd-43f2-b3f7-203c603b8f69.png)
- [ ] decimal numbers are not turned into percentage in the column detail view

![Screenshot 2022-09-19 at 2 35 38 PM](https://user-images.githubusercontent.com/13626425/191018698-fb8a15ba-4c82-4323-903e-1e7cbcd05137.png)
![Screenshot 2022-09-19 at 2 35 26 PM](https://user-images.githubusercontent.com/13626425/191018703-c68abc17-cff8-403b-be24-17f28dd57778.png)
- [ ] column value count metric is not coma seperated
- [ ] On graph hover metrics are not coma seperated

**Comment by ShaileshParmar11** [comment]
-  column value count metric is not coma separated
earlier we have added coma separated value but with [this](https://github.com/open-metadata/OpenMetadata/issues/7082) issue we have change the value

can you confirm what is the expected behaviour here?
cc @pmbrull

**Comment by TeddyCr** [comment]
@ShaileshParmar11  we are expecting thousands to be coma separated (e.g 1,500,000). In the screenshots you can see the thousands separation is not correct. It is 1,50,000 instead of being 150,000.
