### ISSUE TITLE
UI: Explore page initial filters reset when tabs change.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#7554]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Initial filters are reset when tabs change.

**To Reproduce**

https://user-images.githubusercontent.com/51777795/191020377-b5b4eff7-1bfa-46c0-855e-0c9e9dd1cea8.mov

**Expected behavior**
Filters should not reset on tab change.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
This is intentional
