### ISSUE TITLE
Openmetadata cannot get key from Keycloak

### ISSUE THREAD

**Issue by cuongthh** [open-metadata/OpenMetadata#7567]
**Describe the bug**
When I enable sercurity by Keycloak SSO following docs: https://docs.open-metadata.org/deployment/security/keycloak
Affer login with Keycloak user account, the openmetadata throw an exception as:
"An exception with message [No key found in with kid xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] was thrown while processing request."

My configuration:
      AUTHORIZER_CLASS_NAME: ${AUTHORIZER_CLASS_NAME:-org.openmetadata.catalog.security.DefaultAuthorizer}
      AUTHORIZER_REQUEST_FILTER: ${AUTHORIZER_REQUEST_FILTER:-org.openmetadata.catalog.security.JwtFilter}
      AUTHORIZER_ADMIN_PRINCIPALS: ${AUTHORIZER_ADMIN_PRINCIPALS:-[admin]}
      AUTHORIZER_INGESTION_PRINCIPALS: ${AUTHORIZER_INGESTION_PRINCIPALS:-[ingestion-bot, service-account-open-metadata]}
      AUTHORIZER_PRINCIPAL_DOMAIN: ${AUTHORIZER_PRINCIPAL_DOMAIN:-"open-metadata.org"}
      AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN: ${AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN:-false}
      AUTHORIZER_ENABLE_SECURE_SOCKET: ${AUTHORIZER_ENABLE_SECURE_SOCKET:-false}
      AUTHENTICATION_PROVIDER: ${AUTHENTICATION_PROVIDER:-custom-oidc}
      CUSTOM_OIDC_AUTHENTICATION_PROVIDER_NAME: ${CUSTOM_OIDC_AUTHENTICATION_PROVIDER_NAME:-"KeyCloak"}
      AUTHENTICATION_PUBLIC_KEYS: ${AUTHENTICATION_PUBLIC_KEYS:-[http://localhost:8080/realms/mfrealm/protocol/openid-connect/certs]}
      AUTHENTICATION_AUTHORITY: ${AUTHENTICATION_AUTHORITY:-http://localhost:8080/realms/mfrealm}
      AUTHENTICATION_CLIENT_ID: ${AUTHENTICATION_CLIENT_ID:-"open-metadata"}

My keycloak setting:
![image](https://user-images.githubusercontent.com/108664799/191151428-cd7b89de-8360-4825-9614-6eeedb768a49.png)

**Expected behavior**
Login successfully

**Version:**
 - OS: Amazon linux 2
 - Keycloak version: 19.0.1
 - OpenMetadata version docker: 0.12.0

**Comment by vivekratnavel** [comment]
Hi @cuongthh, can you check if you are able to access this url from within the openmetadata server container?  http://localhost:8080/realms/mfrealm/protocol/openid-connect/certs

**Comment by cuongthh** [comment]
Hi @vivekratnavel , yes, I can access the both url 
http://localhost:8080/realms/mfrealm/protocol/openid-connect/certs

the result is
{"keys":[{"kid":"okSamNVdm_ZJPQUfnFPsnaTOIGLLYSUtwwGHc3Ayobc","kty":"RSA","alg":"RSA-OAEP","use":"enc","n":"rVffAR0k_uZ8E7viqcOCI16Su7QN-vAjBDEpfyw6yIZSgJKAV9vChc0ryjJ0nxMtJCccXkoC-QE60yCJZtm5sRJQm6IJlp4tOZivByRkcpdEFCI_If1zUiLjBPgrqWBm_e2pricBrRTJhZHTxbKi0nN4rOhHxLM6fLGDB9RMAo10dR7BX-xTBUrw-m5KrW1SE_kWFa6m3r4WhaBszBxWqDZUU_Mre5G7S2T88Jb2e7hdoMhPKBBnBNfvdeSfImqt0ev8lTKgfqjkckSzpFtB9LFLCRfCQ6-AYEkRi110H5aQdTF4mI0xJsceROdWS-4DgFIvQxpiN-caO73RMonamQ","e":"AQAB","x5c":["MIICnTCCAYUCBgGDWNS+izANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdtZnJlYWxtMB4XDTIyMDkyMDAyNTYyMFoXDTMyMDkyMDAyNTgwMFowEjEQMA4GA1UEAwwHbWZyZWFsbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK1X3wEdJP7mfBO74qnDgiNekru0DfrwIwQxKX8sOsiGUoCSgFfbwoXNK8oydJ8TLSQnHF5KAvkBOtMgiWbZubESUJuiCZaeLTmYrwckZHKXRBQiPyH9c1Ii4wT4K6lgZv3tqa4nAa0UyYWR08WyotJzeKzoR8SzOnyxgwfUTAKNdHUewV/sUwVK8PpuSq1tUhP5FhWupt6+FoWgbMwcVqg2VFPzK3uRu0tk/PCW9nu4XaDITygQZwTX73XknyJqrdHr/JUyoH6o5HJEs6RbQfSxSwkXwkOvgGBJEYtddB+WkHUxeJiNMSbHHkTnVkvuA4BSL0MaYjfnGju90TKJ2pkCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAXnifuRHA/d2obThHdQIChj1Ruq9juLcLJucJC8cgggUzJuFTeoZ8azgxDt/UkMr+COb4tySVZZd+liGGvhnFvQaZ7BGFTea9M49QIHct5rXDZPDtKlYEfIErZNCRMcGaIUH3Fr5w5/e1EKOtUhKqmzSFyl8lWjh3V/4OYMODG4tYsDKXt6vXCrwVydhlO6RSltYgj299mrYiiqV7KLgqCf1pwhYCaHCV20rk5JzgW3nDkxko9Mse/vMj8362FSpB30sjxgqvdriV+FxJhaiJMvyINpAu0aEmjysUyYxmM1cCPmcqO17OIUpHfMj6ATrgVznyYdn+9MmuLZOgs/aeiQ=="],"x5t":"myGoN7mlKI7CH9lJGKLllULwKLs","x5t#S256":"SqB50xGjj3cgcuCJW9VABqqB7X8-h9uCzE_bvHl3-Cc"},{"kid":"ZV942z1chyi1_6RHFPI1oneDld4U--2_WHywm3O-fG4","kty":"RSA","alg":"RS256","use":"sig","n":"0H5HsRw_v9dKc9ZaFzQPuAaHPQdtyFWOJV-A8p_29cTqHZZYHjNPazRNBaPIyZugKo7Lo9Vv0rsiuN_OypPQrMeAAVHNkIG082g4GkW09Q0y6rnuoVeX2xYrPIOG80IAY3oA2qKsoFFdR8DXMIfxulfzcNaeJSCIxm2I_l7d_SUBMhIkbVGiEk8B31EuXnkLIhkINJk2IT3B2BpJNG6mBBw5YgghE_Y_g6UDUbylXrh3X1LjAVBxB-1CotGqeN9g1sDT6oXtB8QFjUR-OGVagCI2dEDLyMnihjXtPGbY9pCINssyV4M_y6Jwt0waswblVcP7e1kQMnBrQVVCQ60C4w","e":"AQAB","x5c":["MIICnTCCAYUCBgGDWNS9zDANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdtZnJlYWxtMB4XDTIyMDkyMDAyNTYyMFoXDTMyMDkyMDAyNTgwMFowEjEQMA4GA1UEAwwHbWZyZWFsbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANB+R7EcP7/XSnPWWhc0D7gGhz0HbchVjiVfgPKf9vXE6h2WWB4zT2s0TQWjyMmboCqOy6PVb9K7IrjfzsqT0KzHgAFRzZCBtPNoOBpFtPUNMuq57qFXl9sWKzyDhvNCAGN6ANqirKBRXUfA1zCH8bpX83DWniUgiMZtiP5e3f0lATISJG1RohJPAd9RLl55CyIZCDSZNiE9wdgaSTRupgQcOWIIIRP2P4OlA1G8pV64d19S4wFQcQftQqLRqnjfYNbA0+qF7QfEBY1EfjhlWoAiNnRAy8jJ4oY17Txm2PaQiDbLMleDP8uicLdMGrMG5VXD+3tZEDJwa0FVQkOtAuMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAGLasIadglA8x+IwqaJn2rijc7azGPkkqRKV7Oj/h8xkw5DZrQC/WpqZaGdZhHjUjdkW0yk/MOrSLaBccwzm1VP1iSKshFARyQXdV2/MjOHyCtHduqtk4ufexQ9scbzDTEIKtzhLOL0rYTk59x3UuHU97fgoEh51VtGXEThT5Xq6RzSHlTzXGFqG8WE9YIhaCBQAQE2gdBWigMByGQuXhZoWCaBm2wqIgQn3yR7ykvz2TwEb7M5ZFA+eGxxyT5Z66dbfPfVAFYVsG1IlfiTqmcMcnFedQIr6yUrqnPTbL5kBNYvMPNNX9TE5shXiu2XGUGhGNya+MW/XIpYWzEH+4gA=="],"x5t":"nIQW7itg53qIG73W8BUOpMSrQT0","x5t#S256":"pe6viDrdZaKC7BNMkOfcW6VYv-hqmuRzFBoPEjliqRw"}]}

**Comment by vivekratnavel** [comment]
Hi @cuongthh, can you please verify if `jwks_uri` in the well known configuration points to the correct certs URL?
```
http://localhost:8080/realms/mfrealm/.well-known/openid-configuration
```

**Comment by cuongthh** [comment]
Hi @vivekratnavel 
The result for http://localhost:8080/realms/mfrealm/.well-known/openid-configuration:

{"issuer":"http://localhost:8080/realms/mfrealm","authorization_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/auth","token_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/token","introspection_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/token/introspect","userinfo_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/userinfo","end_session_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/logout","frontchannel_logout_session_supported":true,"frontchannel_logout_supported":true,"jwks_uri":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/certs","check_session_iframe":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"acr_values_supported":["0","1"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"id_token_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"userinfo_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"userinfo_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"request_object_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"response_modes_supported":["query","fragment","form_post","query.jwt","fragment.jwt","form_post.jwt","jwt"],"registration_endpoint":"http://localhost:8080/realms/mfrealm/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"introspection_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"introspection_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"authorization_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"authorization_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"authorization_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"],"claim_types_supported":["normal"],"claims_parameter_supported":true,"scopes_supported":["openid","phone","roles","profile","email","microprofile-jwt","web-origins","address","acr","offline_access"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"require_request_uri_registration":true,"code_challenge_methods_supported":["plain","S256"],"tls_client_certificate_bound_access_tokens":true,"revocation_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/revoke","revocation_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"revocation_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"device_authorization_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/auth/device","backchannel_token_delivery_modes_supported":["poll","ping"],"backchannel_authentication_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/ext/ciba/auth","backchannel_authentication_request_signing_alg_values_supported":["PS384","ES384","RS384","ES256","RS256","ES512","PS256","PS512","RS512"],"require_pushed_authorization_requests":false,"pushed_authorization_request_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/ext/par/request","mtls_endpoint_aliases":{"token_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/token","revocation_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/revoke","introspection_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/token/introspect","device_authorization_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/auth/device","registration_endpoint":"http://localhost:8080/realms/mfrealm/clients-registrations/openid-connect","userinfo_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/userinfo","pushed_authorization_request_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/ext/par/request","backchannel_authentication_endpoint":"http://localhost:8080/realms/mfrealm/protocol/openid-connect/ext/ciba/auth"}}

**Comment by harshach** [comment]
@cuongthh can you join our slack here https://slack.open-metadata.org easier to help there

**Comment by vivekratnavel** [comment]
Hi @cuongthh, I am not able to reproduce this issue. As @harshach mentioned, please join the community slack and ping me. I should be able to quickly help you unblock there.

**Comment by cuongthh** [comment]
This issue has been sovled by changing:
AUTHENTICATION_PUBLIC_KEYS: ${AUTHENTICATION_PUBLIC_KEYS:-[http://localhost:8080/realms/mfrealm/protocol/openid-connect/certs]}
to
AUTHENTICATION_PUBLIC_KEYS: ${AUTHENTICATION_PUBLIC_KEYS:-[http://host.docker.internal:8080/realms/mfrealm/protocol/openid-connect/certs]}
