### ISSUE TITLE
Support specifying projectId when user auth using ADC

### ISSUE THREAD

**Issue by nathancCG** [open-metadata/OpenMetadata#7572]
**Is your feature request related to a problem? Please describe.**

Current it is unable to specify the projectId with ADC. For our bigquery environment. Our ADC is authenticated with Project A. But it needs to access the tables that belong to Project B, there is no permission as it’s been setup. As long as it access the table using a project prefix on the table name, it will work.

**Describe the solution you'd like**
Able to specify the `projectId` in `gcsConfig`.

**Comment by harshach** [comment]
@ayush-shah assigning it to you as you have the context
