### ISSUE TITLE
Secondary Tags exist in API but UI does not have it.

### ISSUE THREAD

**Issue by EminUZUN** [open-metadata/OpenMetadata#7581]
OpenMetadata Version: 0.12

It is possible to define secondary tags from API. But it is not possible to add from UI. And not possible to differentiate them.

![image](https://user-images.githubusercontent.com/8695124/191225201-88fb1ba1-9bac-47a4-b87b-97dec389608c.png)
![image](https://user-images.githubusercontent.com/8695124/191225798-7c4dddbc-dd65-4cc0-b7b1-62f47b2fec60.png)

**Comment by harshach** [comment]
@Sachin-chaurasiya can you take a look whats missing here

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya can you take a look whats missing here

@harshach , We used to show the associated tags, but as mentioned [here](https://github.com/open-metadata/OpenMetadata/issues/4216) we have removed it from the UI.
 
For reference :  [Pull Request](https://github.com/open-metadata/OpenMetadata/pull/4308)
