### ISSUE TITLE
Updating Tag Name is not possible.

### ISSUE THREAD

**Issue by EminUZUN** [open-metadata/OpenMetadata#7582]
Version: 0.12
It is not possible to edit name for tags. And when I try to update with API, it adds new tag.

**Comment by sureshms** [comment]
@EminUZUN, the APIs are currently confusing and do not conform with the rest of OM APIs. This will be addressed with new APIs in #9259. Closing this for now. Reopen if the new APIs don't work (it should, given the functionality is well tested).
