### ISSUE TITLE
Add an empty table for Model Store as well when there's no data

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#7589]
UI Comments :-  As the field of model store will be dynamic, due to which we can not show it in empty table 

<img width="829" alt="image" src="https://user-images.githubusercontent.com/66266464/191233422-af5cf17f-3f7b-432f-a718-516ffef241dc.png">

**Comment by chirag-madlani** [comment]
Use common empty placeholder at both place @Ashish8689
