### ISSUE TITLE
Existing ingestion bot JWT tokens should be preserved

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7610]
**Feature**
Since we are adding Bot in BotEntity tables, we need to ensure during the initialization phase if there is an existing ingestion-bot user and attach it to the BotEntity IngestionBot.
If the ingestion bot already has a JWT token we should preserve that.

**Describe the task**

**Comment by nahuelverdugo** [comment]
This has been covered in https://github.com/open-metadata/OpenMetadata/pull/7637 I will keep close this one once we close the PR.

**Comment by nahuelverdugo** [comment]
This one has been already done as part of #7637.
