### ISSUE TITLE
All docker/helm chart any other deployment must come up with JWT token configuration

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7611]
**Feature**
Since we are making username/password the default auth mechanism. We need to bootstrap the ingestion-bot account and create a JWT token. The user experience should be the following.
1. If they are installing via docker, helm charts. SSL certs are generated, and JWT token configuration is set - @akash-jain-10 
2. Ingestion Bot is created along with JWT token - we should probably do this during the DefaultAuthorizer; if there is an existing one, we only link but don't generate a new token - cc @nahuelverdugo 
3. Ingestion deployment doesn't require any other setups on the airflow configuration etc..
4. We are deprecating the Airflow auth mechanism. From the server side, if there is an existing airflow auth mechanism, we shouldn't throw any errors during the config parsing - cc @nahuelverdugo 

**Describe the task**

**Comment by harshach** [comment]
@nahuelverdugo shall we start removing the auth mechanisms from the Airflow section

**Comment by nahuelverdugo** [comment]
@harshach opened https://github.com/open-metadata/OpenMetadata/pull/8896 to deprecate the use of the configuration of the bot auth mechanism in the YAML configuration of the OM server. It will not force the user to remove it. So points 2 and 4 should be covered.
