### ISSUE TITLE
Connection OM -> Airflow using Google SSO

### ISSUE THREAD

**Issue by ndrluis** [open-metadata/OpenMetadata#7613]
**Is your feature request related to a problem? Please describe.**
I'm using Google SSO on my own Airflow cluster and I want to use my Airflow cluster to orchestrate the OM Ingestions.

**Describe the solution you'd like**
Use service account instead of basic auth to communicate.

**Additional context**

https://openmetadata.slack.com/archives/C02B6955S4S/p1663702507068489

**Comment by harshach** [comment]
we won't be able to support this.
