### ISSUE TITLE
Documentation feedback from support channel

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7614]
**Is some content missing, wrong or not clear?**

- [x] Documentation based on OM version. We have always the latest changes and this could confuse users. For example, the changes done in `openmetadata-service` has affected the documentation of the SSO. Instead of `org.openmetadata.catalog.security.DefaultAuthorizer` we had `org.openmetadata.service.security.DefaultAuthorizer`.
- [ ] The functionality of `enableSecureSocketConnection` and `enforcePrincipalDomain` are not explained.
- [ ] https://docs.open-metadata.org/features/users is empty.
- [ ] No explanation about how new users are handled after activating the SSO. For example, the users which have access must be restricted, otherwise, anyone can access the application.
![image](https://user-images.githubusercontent.com/11074908/191356117-5606d9fb-5666-4ec1-82de-5424745db674.png)
- [ ] Redeploy ingestion pipelines after configuring an SSO.

 cc @harshach

**Comment by akash-jain-10** [comment]
Linking another Issue here so that we can cover it as part of avoiding more support queries.

- [ ] https://github.com/open-metadata/OpenMetadata/issues/7574

**Comment by harshach** [comment]
@aniketkatkar97 can you work adding versions for each of the docs, so that users can choose a version to go to a release.
example 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/38649/192172734-e04243ce-9b1a-4272-96b3-1566c218c7ff.png">
