### ISSUE TITLE
UI: Teams hierarchy is not working as expected in Signup and Add User pages

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7619]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
The dropdown box to select teams does not show team hierarchy as expected in the Signup and Add User pages.

The UI component uses the following Elastic search API to build the team hierarchy tree:
```
http://localhost:8585/api/v1/search/query?index=team_search_index&q=*&from=0&size=100&sort_field=name.keyword&sort_order=asc
```

The response of this API call is missing the "parents" field and hence the UI is unable to build the hierarchy.

**To Reproduce**
Create a bunch of teams with hierarchy (Business Unit -> Division -> Department -> Group). Go to "Add User" page as an admin user. Select the teams from the dropdown box.

**Expected behavior**
A hierarchy of teams is displayed.

**Comment by harshach** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/38649/191411548-8fe9aa5c-f38f-4eec-85cb-e57e3c195d73.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/38649/191411634-760c3974-2ec7-4f4f-b71f-3dfc03520e30.png">
