### ISSUE TITLE
[UI] Issue with scrolling and Reaction 

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#7622]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
The Activity feed has scrolling issues + the reaction doesn't disappear when mouse is taken away

**To Reproduce**
[](url)
Screenshots or steps to reproduce

**Expected behavior**
 

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

*

https://user-images.githubusercontent.com/105265192/191435453-22f3d588-5952-4f28-949b-4b5257556324.mov

*Additional context**

**Comment by pgregor** [comment]
Hi mohityadav766, I'm keen to look into this bug. Could you please assign me to this issue?

**Comment by pgregor** [comment]
Hi @Sachin-chaurasiya I would like to look into this bug. Could you please assign me to this issue?

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya I would like to look into this bug. Could you please assign me to this issue?

Assigned to you @pgregor .
