### ISSUE TITLE
Quality tests can not be created if the column names have spaces or special characters

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#7623]
**Affected module**
UI issue: Profiler and Quality test tab

**Describe the bug**
issue 1: Quality test cannot be created for the column names with spaces 
issue 2 : For columns with special characters in name, upon clicking the add test button the web page for adding test does not load.

payload for issue 1:

{name: "gross bookings_columnValueMaxToBeBetween", description: "",…}
description
:
""
entityLink
:
"<#E::table::[rs-dwh.dev](http://rs-dwh.dev/).public.vw_wbr_metrics_by_city_lw_wow::columns::gross bookings>"
name
:
"gross bookings_columnValueMaxToBeBetween"
owner
:
{id: "9ff2f38c-fa2e-4384-8f4b-92012fad6881", type: "user"}
parameterValues
:
[{name: "minValueForMaxInCol", value: 0}, {name: "maxValueForMaxInCol", value: 100}]
testDefinition
:
{id: "7d954464-ae39-4636-98e5-98c36b7822f5", type: "testDefinition"}
testSuite
:
{id: "b3679cae-5650-4db7-99cd-e531275e49c8", type: "testSuite"}

issue 2 

![image (1)](https://user-images.githubusercontent.com/110607559/191440455-55e30b89-1f6c-455a-8cf1-8fc8612a63f9.png)

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/7658

**Comment by Sachin-chaurasiya** [comment]
Reopening as backend changes are pending.

**Comment by TeddyCr** [comment]
@ShaileshParmar11 just opened a PR https://github.com/open-metadata/OpenMetadata/pull/7670. I am thinking we should encode the column name in the entityLink when sending a request to create the `testCase`.We would be expecting spaces to be encoded with the `+` sign i.e. `first name` -> `first+name`.

BTW, unsure if it is expected but #7659 does not seem to fix the spacing issue -- see screen recording below.

https://user-images.githubusercontent.com/13626425/191826898-8d61126e-daee-466a-9fa1-3a42a5d1b81a.mov

**Comment by ShaileshParmar11** [comment]
Hello @TeddyCr , We were having 2 issues here, so for spacing we needed backend changes 1st, and in 2nd issue, it is related to redirection, which is fixed in [#7658](https://github.com/open-metadata/OpenMetadata/pull/7658)

**Comment by ShaileshParmar11** [comment]
Reopening as frontend task is left
