### ISSUE TITLE
Generated Looker url  is wrong in Lineage tab

### ISSUE THREAD

**Issue by larspettermadsstuen** [open-metadata/OpenMetadata#7629]
**Affected module**
UI

**Describe the bug**
The generated Looker URL (indicated in attached picture) seems wrong. The base part of the URL seems to be that of the OpenMetadata url (in my case, localhost), instead of the Looker instance host.

**To Reproduce**
<img width="756" alt="image" src="https://user-images.githubusercontent.com/100695195/191503939-531c0cac-2985-46fb-bea3-d6637b29599e.png">

**Expected behavior**
The base part of the url should point towards the Looker instance.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@nahuelverdugo might be related to the service connection

**Comment by nahuelverdugo** [comment]
@harshach from what I see in the JSON schema of Looker Connection, it seems that we are correctly exposing the `hostPort` of the configuration.

Can someone from @open-metadata/ui confirm how that URL is created?

**Comment by nahuelverdugo** [comment]
Hi @larspettermadsstuen, could you confirm if it is still happening in the latest version of OM?

**Comment by harshach** [comment]
@pmbrull since you are looking at looker, can you confirm?

**Comment by pmbrull** [comment]
The issue is still valid. The URL that is shown in the UI at the dashboard level points to the right looker instance, but from the lineage view instead of parsing `<hostPort>/<dashboardUrl>` it goes to `<localhost:8585>/<dashboardUrl>`

**Comment by pmbrull** [comment]
hi, validated this with the latest release. If we check the example in the sandbox, URLs look good to me after we modified a couple of behaviors in the ingestion and UI. Thanks

example: https://sandbox.open-metadata.org/dashboard/sample_looker.orders/lineage
