### ISSUE TITLE
UI: Non-admin user should not be allowed to add a bot

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7646]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
When a non-admin user tries to add a bot, the first request to create a user succeeds, but the second request to create a bot fails with a 409 status code.

**To Reproduce**

https://user-images.githubusercontent.com/1051198/191618954-34c015a7-83b2-4e7d-af9c-711d3b5be073.mov

**Expected behavior**
"Add Bot" button should be disabled. 

cc @nahuelverdugo

**Comment by Sachin-chaurasiya** [comment]
@vivekratnavel , Can you check the permission response?
Here everything is based on permission, so if the user has permission he can create the bot.

**Comment by Sachin-chaurasiya** [comment]
@harshach , we had a discussion around this and on the UI side, we have made these changes https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/utils/PermissionsUtils.ts#L91.
Also, we discussed that we will be removing the admin context and everything will be based on permissions.
cc : @chirag-madlani

**Comment by harshach** [comment]
@Sachin-chaurasiya admin context is not removed yet. But we should still check for the permissions here. If the user has bot  create permission we should allow it , if not they should be blocked except if the user is admin
