### ISSUE TITLE
404 links in documentation

### ISSUE THREAD

**Issue by larspettermadsstuen** [open-metadata/OpenMetadata#7661]
**Is some content missing, wrong or not clear?**
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas

<img width="863" alt="image" src="https://user-images.githubusercontent.com/100695195/191746282-7ebf9713-4fe6-48c9-99c5-dba929753d9c.png">

The links indicated in pictured give a 404.

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

**Comment by sfirke** [comment]
This is also broken on https://docs.open-metadata.org/deployment/upgrade/docker:

![image](https://user-images.githubusercontent.com/7569808/191798173-65e7c439-420a-46c7-8f9e-6d0ecdfe3e71.png)
