### ISSUE TITLE
Newly added roles and policies are not reflecting in the Teams (Roles and Policies )tab

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#7663]
**Affected module**
Team, Roles and Policies
**Describe the bug**
Newly added roles and policies are not reflecting in the Teams (Roles and Policies )tab.

![image (4)](https://user-images.githubusercontent.com/110607559/191755381-72e63cee-91da-45a2-8488-84e9dde70855.png)
![image (5)](https://user-images.githubusercontent.com/110607559/191755400-b43c9a20-4dd1-4602-8ad1-2ed33f72a531.png)

**Comment by Sachin-chaurasiya** [comment]
This issue has been fixed with https://github.com/open-metadata/OpenMetadata/pull/7660.

https://user-images.githubusercontent.com/59080942/191758543-fcea5e69-8773-46be-a8bd-923abebad24f.mov
