### ISSUE TITLE
Permanent delete option after soft deleting the team is not available.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#7664]
**Affected module**
Team

**Describe the bug**
![image](https://user-images.githubusercontent.com/110607559/191755822-ac239b25-9321-4c8d-ac1f-8aab997559a4.png)

**Comment by Sachin-chaurasiya** [comment]
@aniketkatkar97, Reverify the issue and if it is fixed close this ticket.

**Comment by chirag-madlani** [comment]
@aniketkatkar97 Add Cypress tests for the same
