### ISSUE TITLE
Screenshots in documentation not loaded

### ISSUE THREAD

**Issue by fifionachow** [open-metadata/OpenMetadata#7674]
**Is some content missing, wrong or not clear?**
Screenshot images on these page aren't loaded.
https://docs.open-metadata.org/openmetadata/connectors/database/postgres
https://docs.open-metadata.org/openmetadata/connectors/pipeline/glue

**Comment by harshach** [comment]
https://docs.open-metadata.org/connectors/pipeline/glue-pipeline
https://docs.open-metadata.org/connectors/database/postgres
Taken care in new docs
