### ISSUE TITLE
Column name max length is too low

### ISSUE THREAD

**Issue by fredriv** [open-metadata/OpenMetadata#7680]
**Affected module**
Ingestion Framework

**Describe the bug**
While ingesting tables from Snowflake, we got a lot of warnings saying that the column name was too long. The maximum in Open Metadata seems to be 128 characters, but Snowflake column names [can be up to 255 characters long](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#identifier-requirements).

Example error message (long column name replaced with `xyz`):
```
[2022-09-22 11:06:52] WARNING  {Ingestion:sql_column_handler:246} - Unexpected exception processing column [{'name': 'xyz', 'type': DECIMAL(precision=38, scale=0), 'nullable': True, 'default': None, 'autoincrement': False, 'comment': None, 'primary_key': False}]: 1 validation error for Column
name -> __root__
  ensure this value has at most 128 characters (type=value_error.any_str.max_length; limit_value=128)
```

**To Reproduce**
Ingest a Snowflake table with a column name longer than 128 characters.

**Expected behavior**
I expect Open Metadata to be able to ingest tables with long column names.

**Version:**
 - OS: MacOS
 - Python version: 3.9.9
 - OpenMetadata version: 0.12
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[snowflake]==0.12.0.2`

**Additional context**

**Comment by FabrizioCafolla** [comment]
+1

**Comment by charliemenke** [comment]
+1 also an issue when yielding a Table Name
