### ISSUE TITLE
Allow Admin to set one-time password while adding

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7702]
**Affected module**
UI, Backend

**Describe the bug**
Currently, there is no way to add a password while adding a User by an admin.
This forces the deployment must have SMTP. Our goal is to simplify deploying as much as possible, not add additional configs users must do.
This option should only be available if the authentication is basic.

Users should be able to reset their password when logged in. We need to check the current password and allow them to set the new password
<img width="813" alt="image" src="https://user-images.githubusercontent.com/38649/192066238-2e802def-554c-4d40-a47e-84b53eded706.png">

Old Password should match the existing password to set the new password.
cc @mohitdeuex 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/38649/192066280-3364d0e9-ff15-4994-b44c-b76d8ef460a4.png">

add a link below the description "Change Password" This will only be displayed if the logged-in user looking at their own profile.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
@chirag-madlani 
1. Admin should create User with Password for Basic Auth
2. Provide Users to change their password for Basic Auth
