### ISSUE TITLE
Dependencies conflict with airflow official constrains 

### ISSUE THREAD

**Issue by nathancCG** [open-metadata/OpenMetadata#7709]
**Affected module**
This affects building the airflow image with official airflow 2.3.4 constrains.txt file if I want to have openmetadata client library installed.

**Describe the bug**
Conflict between openmetadata library and airflow official constrain file. Investigation on whether openmetadata can loosen the dependencies requirement would be much appreciated.

**To Reproduce**
in docker file, when pip install requirements add `-c constraints.txt` where the constrains.txt file can be found [here](https://github.com/apache/airflow/blob/constraints-main/constraints-3.9.txt)
Docker build error log:
`openmetadata-ingestion 0.12.0.3 depends on boto3~=1.19.12
The user requested (constraint) boto3==1.24.58
openmetadata-ingestion 0.12.0.3 depends on botocore==1.22.12
The user requested (constraint) botocore==1.27.58
openmetadata-ingestion[elasticsearch] 0.12.0.3 depends on elasticsearch==7.13.1; extra == "elasticsearch"
The user requested (constraint) elasticsearch==7.13.4
boto3 1.19.12 depends on s3transfer<0.6.0 and >=0.5.0
The user requested (constraint) s3transfer==0.6.0
`

**Version:**
 - OpenMetadata version: 0.12
 - OpenMetadata Ingestion package version: 0.12.0.3

**Comment by pmbrull** [comment]
will prep some docs around this

**Comment by pmbrull** [comment]
hi @nathancCG, please find the docs here https://docs.open-metadata.org/connectors/ingestion/run-connectors-in-airflow on how to run the connectors from a custom Airflow using a Docker Operator. This way you won't need to install any requirements on the Airflow host.

Same thing applies for MWAA https://docs.open-metadata.org/connectors/ingestion/run-connectors-from-mwaa.

Thanks

**Comment by pmbrull** [comment]
Airflow is just one of the possible ways of running the connectors, so we don't want to restrict ourselves to their constraints
