### ISSUE TITLE
Dead links on SDK documentation

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#7710]
[SDK docs](https://docs.open-metadata.org/sdk/python) has couple of dead links

**Comment by katebmckay** [comment]
Hi, I'm a student and am new to the project, could this issue be assigned to me? I've read the documentation and relevant conversation. 
Thanks.

**Comment by harshach** [comment]
hi @katebmckay thanks for your interest. Assigning it to you

**Comment by harshach** [comment]
@katebmckay all the docs are in here https://github.com/open-metadata/OpenMetadata/tree/main/openmetadata-docs . We use markdown syntax and sdk docs are here https://github.com/open-metadata/OpenMetadata/tree/main/openmetadata-docs/content/sdk
