### ISSUE TITLE
deltalake service unable to configure hadoop configuration

### ISSUE THREAD

**Issue by cometta** [open-metadata/OpenMetadata#7716]
affected Openmetadata 0.12.0

according to source code at https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/utils/connections.py#L301  and https://github.com/open-metadata/OpenMetadata/blob/2df214a381e617b05407ed5d66ee7063b862fa61/ingestion/src/metadata/utils/connections.py#L345, 

there is no option to configurate hadoop for parameters like below
```
spark._jsc.hadoopConfiguration().set(“fs.s3a.path.style.access”, “true”)
spark._jsc.hadoopConfiguration().set(“fs.s3a.connection.ssl.enabled”, “true”)
spark._jsc.hadoopConfiguration().set(“fs.s3a.aws.credentials.provider”, “org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider”)
spark._jsc.hadoopConfiguration().set(“fs.s3a.access.key”, access_key)
spark._jsc.hadoopConfiguration().set(“fs.s3a.secret.key”, secret_key)
spark._jsc.hadoopConfiguration().set(“fs.s3a.endpoint”, “https://my_on_prem_s3_server/”)
```

This issue is confirmed by @MilanBariya 

aside from this error, i can see other error as well, not sure related  WARN Executor: Issue communicating with driver in heartbeater ,  it tells executors cant communicate with driver. in case you look into this issue, remember to test on kubernetes

**Comment by pmbrull** [comment]
Thanks for the details. Could you please share some more info on how you deployed OM (version etc) and how you configured the delta connector? We'll try to replicate.

Thanks

**Comment by harshach** [comment]
@pmbrull lets see if we can address this in release 1.3 otherwise lets close it
