### ISSUE TITLE
Number of passed/failed rows should be captured

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7729]
- [x] Add ingestion logic to capture the number of failed rows
- [ ] Display number of failed rows on the UI

**Comment by Kulkarniyash7** [comment]
Can you provide further details Please .

**Comment by TeddyCr** [comment]
Hey @Kulkarniyash7 we have validations that runs against databases [here](https://github.com/open-metadata/OpenMetadata/tree/main/ingestion/src/metadata/test_suite/validations). These validations will return a `TestCaseResults` object defined [here](https://github.com/open-metadata/OpenMetadata/blob/8427a0d280f781cea0a054a80612eef27075d331/openmetadata-spec/src/main/resources/json/schema/tests/basic.json#L22-L62) which does not include the number of rows that met and did not met the condition defined in the validation (example [here](https://github.com/open-metadata/OpenMetadata/blob/8427a0d280f781cea0a054a80612eef27075d331/ingestion/src/metadata/test_suite/validations/column/column_value_max_to_be_between.py#L103-L108)).

What we need is to capture these data and pass it to the `TestCaseResults` object

**Comment by techrajdeep** [comment]
Hey @TeddyCr  Is someone working on this ?

**Comment by harshach** [comment]
@techrajdeep do you want to work on it? we can assign it to you

**Comment by techrajdeep** [comment]
Thanks @harshach  . Yes , I want to work on this. Since this is my first contribution , need some guidance.

**Comment by techrajdeep** [comment]
Hey @harshach , Could you please assign this to me?

**Comment by harshach** [comment]
@techrajdeep done. Please join https://slack.open-metadata.org for any questions you may have. Reach out to @TeddyCr

**Comment by amymareemc** [comment]
Hi, I'd like to work on this as well. If possible could I get assigned to this?

**Comment by pmbrull** [comment]
hi @techrajdeep, any updates on this? Let us know if you need any help. Thanks

**Comment by harshach** [comment]
@amymareemc let us know if you still interested in working on it. We are looking to ship this in our next minor release
cc @TeddyCr @ayush-shah 
cc @devyani-kaushik @ShaileshParmar11 for the UI

**Comment by TeddyCr** [comment]
cc @ShaileshParmar11

**Comment by harshach** [comment]
@ShaileshParmar11 can you paste the screenshot how are we going to show this on the UI?

**Comment by ShaileshParmar11** [comment]
@harshach 
<img width="828" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/71748675/a6c58eb6-7e2c-490a-a373-a2b6f7c35c98">
