### ISSUE TITLE
Kafka topic ingestion fails if topic contains zero messages

### ISSUE THREAD

**Issue by ehausig** [open-metadata/OpenMetadata#7730]
**Affected module**
Ingestion Framework

**Describe the bug**
A Kafka ingestion pipeline that has "Ingest Sample Data" enabled appears to fail with `exit 1` if it tries to sample one or more topics that contains 0 messages.

Topics that do not contain messages will be listed in the `failures[]` array of the `MessageSourceStatus()` object. For example:
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/16280871/192325216-711599ca-1198-444f-bc4b-14575659df04.png">
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/16280871/192325289-5a546dd6-91da-4821-afe4-448cbd9f74e6.png">

**To Reproduce**

1. Create an Avro topic in Kafka with a corresponding Avro schema, but do not insert any messages in the topic
2. Create an ingestion pipeline and select the "Ingest Sample Data" option
3. Run the ingestion pipeline
4. Check the logs of the pipeline and inspect the `failures[]` array of the `MessageSourceStatus()` object outputted to the log

**Expected behavior**
Topics that contain zero messages should be categorized as "warnings" instead of "failures"--An empty topic should not cause the pipeline to fail.

**Version:**
 - OS: Kubernetes
 - Python version:
 - OpenMetadata version: 0.12.0
 - OpenMetadata Ingestion package version:

**Comment by harshach** [comment]
@ehausig did you enable the sample data to be ingested?

**Comment by harshach** [comment]
@ehausig are you seeing the pipeline failure or its reporting failures on no.of topics it was able to extract

**Comment by ehausig** [comment]
@harshach I am seeing a pipeline failure:
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/16280871/192331059-dbafd5c7-507c-4aa8-af61-fcbeb22bf578.png">
I now think it has nothing to do with the number of messages in a topic....maybe I should update the report?

**Comment by ehausig** [comment]
Issue misdiagnosed. This looks to be more of an issue with the ingestion pipeline not being able call `SchemaRegistryClient.get_by_id()`.

**Comment by harshach** [comment]
Thanks for the report @ehausig . Trying to reproduce. Can you please share the ingestion framework version
```metadata --version ```

**Comment by ehausig** [comment]
@harshach sure, where I can I find the ingestion framework version? I know that the container image that is being spun-up for the pipeline is:
```
openmetadata/airflow:0.12.0
```
