### ISSUE TITLE
Differentiate tags for tables and columns

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#7732]
**Is your feature request related to a problem? Please describe.**
When creating Tags/Tags Categories, it would be nice to define whether they apply to tables, columns, or both types of objects. For better management in scenarios with a large number of labels

**Describe the solution you'd like**

![](https://files.slack.com/files-pri/T02BVTLN3G8-F04406AQMV2/image.png)

**Comment by jromandv** [comment]
About our previous conversation about tags, An issue related. In the attached image, highlighted Tags are assigned to columns, it does not make sense for them to appear in the summary of a table when clicking "Explore" link at home page! (edited) 
![image](https://user-images.githubusercontent.com/112470575/193051427-e32705ad-f4e1-4def-a33d-c018e07a00de.png)

**Comment by harshach** [comment]
@Sachin-chaurasiya what is this ticket about is we are merging tags from columns into table tags so that we can match them better and in summary what we are showing is looks like tags that apply across the tables and columns.
is this happening from the UI? i.e are you merging tags from table.tags and table.column.tags as well?

**Comment by Sachin-chaurasiya** [comment]
Hello @harshach, I checked we are getting aggregated tags from the search API itself.

**Comment by sureshms** [comment]
@harshach assigning this to you given this is search API related.

**Comment by harshach** [comment]
@sureshms we are putting tags and glossary terms in to same field as tags. So it will be the same from the dataset page and search . Unless we want to split this separately?
