### ISSUE TITLE
UI - Bring all the asset listing to same styling as glossary page

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#7737]
**Is your feature request related to a problem? Please describe.**

**Update styling for listing to same for all**

**Describe the solution you'd like**
- Inconsistency in UI for listings assets

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/12962843/192433367-49e6afed-e5b7-4267-aa43-2db670ee86b5.png)

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=14646%3A23089
