### ISSUE TITLE
FAQ / Knowledge Center / Onboarding Guide

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#7738]
**Is your feature request related to a problem? Please describe.**
Business Intelligence Engineers (BIEs) need a proper Onboarding guide to explore the tables and data concepts we have. Neither table metadata nor glossaries can address this.

**Describe the solution you'd like**
1. FAQ Section
- Create several "domains" and within each domain have a Q&A style.
- It should provide markdown support for SQL queries.
- It should link to tables (assets)
- This should be read-only and maintained by some owner

2. Onboarding Guide
- Create tutorial content in form of chapters that users have to click through to learn about data concepts.
- It should link to tables and glossaries
- This should be read-only and mainted by some owner.
- Should be able to show picture / diagram (p1)

**Describe alternatives you've considered**
Repurpose glossaries.

**Additional context**
Discussed with Harsha on 9/26.

**Comment by harshach** [comment]
closing this infavor of this ticket https://github.com/open-metadata/OpenMetadata/issues/6751
