### ISSUE TITLE
DBT - Add support for test_suite_name meta defined in model schemal.yaml file

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7743]
Currently test suite integration with dbt are supported when defined inside the dbt_project.yaml file. We should add support for the `schema.yaml` file

**Comment by pmbrull** [comment]
@TeddyCr could you please add some more details here? Is this from DBT?

**Comment by TeddyCr** [comment]
@pmbrull my bad, I missed that message. Basically, right if I well remember we support integrating test suites defined in `dbt_project.yaml` but could not in `schema.yaml` file.

**Comment by pmbrull** [comment]
@TeddyCr should we handle this when migrating to the new test suite logic? This has been open for a while. If we cannot/want to add this change we can close this out. Thanks!

**Comment by TeddyCr** [comment]
@pmbrull yes, this is planned. We should not even need it anymore as we'll be linking testCases to tables.

**Comment by TeddyCr** [comment]
closing as won't be relevant after https://github.com/open-metadata/OpenMetadata/issues/11592
