### ISSUE TITLE
Using openmetada to configure and deploy dagster for ingestion

### ISSUE THREAD

**Issue by slamer59** [open-metadata/OpenMetadata#7762]
**Is your feature request related to a problem? Please describe.**
For now, only Airflow can be setup through the UI. 

![image](https://user-images.githubusercontent.com/25283272/192606586-8ac97f06-d066-46dc-95c8-8990a56b5895.png)

Support alternative orchestrators for metadata ingestion #4986 

**Describe the solution you'd like**
I want to be able to deploy dagster and select it in OpenMetadata UI.
- [ ] [Helm chart should be able to deploy it](https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm)
- [ ] Openmetadata should be able to run Ingestion with dagster

We might want to integrate [as a service extending the interface. ]([OpenMetadata/AirflowRESTClient.java at main · open-metadata/OpenMetadata](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/airflow/AirflowRESTClient.java))

**Mapping API** 
This is the dagster [API](https://docs.dagster.io/concepts/dagit/graphql#graphql-api)

_deployPipeline_ : I don't think there is something similar in dagster. What is the purpose of it ? Usually we create a pipeline and [create a Docker image.](https://docs.dagster.io/deployment/guides/docker) A daemon is connected through gRPC. We add this pipeline in a configfile ConfigMap. 

_deletePipeline_ : we remove it from the ConfigMap

_runPipeline_ : correspond to [LaunchRunMutation](https://docs.dagster.io/concepts/dagit/graphql#launch-a-run )

_toggleIngestion_ : What is the purpose of this ? We can activate  [schedulers](https://docs.dagster.io/concepts/partitions-schedules-sensors/schedules) with Graphql API 

_getPipelineStatus_ :  One way [RunsQuery](https://docs.dagster.io/concepts/dagit/graphql#example-queries) you have all runs but we can filter for OpenMetadata secific run. _FilteredRunsQuery_

_getServiceStatus_ and _testConnection_ : health check of daemon and pipeline is possible. 

_killIngestion_ : [TerminateRun mutation](https://docs.dagster.io/concepts/dagit/graphql#terminate-an-in-progress-run)

_requestGetHostIP_ : What is it for ? 

_getLastIngestionLogs_ : What is it for ? We can requests metadata asociated to a pipeline.

**Describe alternatives you've considered**
Today one way is to do something similar [to this](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/examples/airflow/dags/airflow_metadata_extraction.py#L41)
Not installing Airflow will through error in the UI. 

**Additional context**
This follows this discussion
https://openmetadata.slack.com/archives/C02AZGN0WKY/p1664297118682629

**Comment by geoHeil** [comment]
Will this be part of 0.13 @pmbrull ?

**Comment by pmbrull** [comment]
hi @geoHeil we are not going to work on this in the near future. We prepared some docs around the architecture https://docs.open-metadata.org/connectors/ingestion/deployment so that the community has more vision on preparing these changes. No ETA for now. We can give support if anyone wants to pick it up

**Comment by geoHeil** [comment]
I might pick something up here in the coming days/weeks. Once it is completed I will show/share it with you and discuss how this could potentially be integrated.

**Comment by pmbrull** [comment]
hi @geoHeil we are currently working on getting this done for Argo here: https://github.com/open-metadata/OpenMetadata/pull/8595

This implementation should be something similar
