### ISSUE TITLE
Revisit PowerBI lineage

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7767]
so far, we have created lineage against the database. Take another look at the PBI API and document our findings. We need to end up with a doc explaining what we looked at and what we found. Let's also make sure that we create different datasets, from SQL or DAX and see if we can extract further information in these cases.

**Comment by ayush-shah** [comment]
conversation link: [link](https://openmetadata.slack.com/archives/C02B6955S4S/p1664372309911489?thread_ts=1664309054.139629&cid=C02B6955S4S)

**Comment by ayush-shah** [comment]
ref: 
https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-data-lineage
https://learn.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.data/?view=powerbi-ps
