### ISSUE TITLE
UI: Add password validation to Register New Account page

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#7779]
**Affected module**
UI

**Describe the bug**

- [ ] There is no password validation in the UI on the Register New Account page. It allows me to create an account with a password less than 8 characters.

- [ ] The form should not be cleared until a success response from the API. 

<img width="1728" alt="Screen Shot 2022-09-28 at 9 51 59 AM" src="https://user-images.githubusercontent.com/1051198/192842898-e9744d74-7140-453d-9aca-20a9b37df49d.png">

**Comment by harshach** [comment]
are we doing validation around password == confirm Password?

**Comment by vivekratnavel** [comment]
Yes, that validation is present.
