### ISSUE TITLE
Differentiate Tags & Glossary Terms

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#7802]
**Is your feature request related to a problem? Please describe.**
When browsing table summary/detail cannot differentiate Tags from Glossary Terms

**Describe the solution you'd like**
- Use a different prefix than '#', color, ..... to differentiate both  objects
- Set also a predefined/fixed visual order  by default (terms first always, tags next)

**Describe alternatives you've considered**
-  Review frequently inventory of T&t to identify type

**Additional context**

**Comment by sureshms** [comment]
@harshach how about using # as a prefix for tags and nothing for glossary terms? +1 on showing glossary terms first and tags after that. This is a UI-only change.

**Comment by harshach** [comment]
@sureshms thats a good idea.
