### ISSUE TITLE
UI: Show error toast for 500 server response while fetching glossary terms

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#7804]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
A user was facing issue, initially all glossary terms were not displaying in the list but displayed after search. Server response was 500 while fetching glossary terms but no error toast was displayed.

**To Reproduce**

![image (1)](https://user-images.githubusercontent.com/51777795/193189636-4102f91a-fac8-4de2-99bf-94dafcd78143.png)
![image](https://user-images.githubusercontent.com/51777795/193189641-77a343c2-8c0a-4875-bede-dc87d7dbd7ea.png)

**Expected behavior**
Error toast should be shown for failed API response to the user.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97 I assume this is fixed? cc @chirag-madlani

**Comment by aniketkatkar97** [comment]
@harshach As the whole glossary was revamped, this should not be an issue now.
