### ISSUE TITLE
Improve `min` `max` DQ to allow passing only `min` or `max`

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#7810]
## Context
Currently DQ testing a value is between `min` and `max` require users to pass both values. We should allow users to only also test if a value is less than or greater than by passing respectively only `max` or `min`.

**Comment by demi365** [comment]
Could you be a bit more specific?
There are multiple column types in DQ tests on which min and max is allowed, and I can see most of them accept either min or max and do not have any validation of enforcing min and max? The tooltip of few columns do not mention it.

**Comment by TeddyCr** [comment]
@demi365 thanks for looking into this. All the validation [here](https://github.com/open-metadata/OpenMetadata/tree/main/ingestion/src/metadata/test_suite/validations/column) assume both values are passed -- as we do not weather `max` or `min` is `None`. If it is `None` the validation will throw an error.

I am thinking we might want to set `min` or `max` to respectively either `float("-inf")` or float("inf") when no value is present.

**Comment by demi365** [comment]
Great, thanks for the information. Can I try taking this issue if it's available?

**Comment by TeddyCr** [comment]
Sounds good. I'll assign it to you. Thank you 🙏

**Comment by demi365** [comment]
PR is raised for this change [8235](https://github.com/open-metadata/OpenMetadata/pull/8235)
