### ISSUE TITLE
Button in UI for adding a table

### ISSUE THREAD

**Issue by AntonArgon** [open-metadata/OpenMetadata#7819]
**Is your feature request related to a problem? Please describe.**
Data analysts need to periodically describe artificial entities that are not metadata of any source and build a lineage with them. These artificial entities can be described via json along the path databases service - database - schema - table. But doing this via json is inconvenient, since data analysts must have rights to manage databases service

**Describe the solution you'd like**
To solve this problem, it would be convenient to have a button in UI for adding a table

With respect!

**Comment by harshach** [comment]
@AntonArgon we won't be able to add this , as this is outside feature set we are considering for OM currenlty
