### ISSUE TITLE
Docker Compose add ENV for Server Port and Admin Port

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#7820]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Docker Compose

**Describe the bug**
Docker Compose add ENV for Server Port and Admin Port menitoned in conf/openmetadata.yaml

Ref - https://openmetadata.slack.com/archives/C02B6955S4S/p1664533973513679

**Comment by Vj-L** [comment]
@akash-jain-10  We need to provide port forwarding section in the document

**Comment by harshach** [comment]
@akash-jain-10 @Vj-L please handle this for 0.12.1

**Comment by Vj-L** [comment]
Closing this since we already have the port forwarding section in the document as changing the port [Link](https://docs.open-metadata.org/deployment/docker)
