### ISSUE TITLE
Data Profiling for CSV and JSON

### ISSUE THREAD

**Issue by upenbendre** [open-metadata/OpenMetadata#7821]
Several organisations, esp. Financial Services receive CSV and JSON files from partners and clients in large numbers. Very often their schemas and formats are agreed upon, but their data needs to be profiled, as that may unearth potential issues or business opportunities

**Describe the solution you'd like**
While it is hard to query a CSV directly, and profiling queries may impact performance, a few options could be looked at - S3 SQL, or copying a sample those files into an in-memory DB and running the profiler.
An initial solution could be a profiler that profiles a sample rather than the whole file/dataset. And the user be allowed to select a sampling strategy

**Comment by TeddyCr** [comment]
closing as duplicate. @upenbendre you can follow the progress here 👉 https://github.com/open-metadata/OpenMetadata/issues/7449
