### ISSUE TITLE
ctrl + k is not working as expected

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#7824]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- In ubuntu + chrome Ctrl + K get focused to addressed bar along with Global search window

**To Reproduce**

1. Run chrome in non-Mac system
2. Login to OpenMetadata
3. Hit `Ctrl + K` to launch Global search
4. Along with Global search focused has shifted to browsers address bar 

Screenshots or steps to reproduce

**Expected behavior**

- Browser should not take the focus and Global search should work

**Version:**
 - OS: [e.g. iOS]: Ubuntu, Chrome
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Aashish1221** [comment]
@chirag-madlani  more details regarding this issue.
Version:
OS: [e.g. iOS]: -Ubuntu, Chrome/Firefox
Python version:
OpenMetadata version: 0.12.0
OpenMetadata Ingestion package version: [e.g. openmetadata-ingestion[docker]==XYZ]

Thanks
