### ISSUE TITLE
Provide Pagination Controls to Visualise Table and Column lists

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#7839]
**Is your feature request related to a problem? Please describe.**
In database schemas with a high number of tables, and tables with a great number or columns I have to scroll down my screen continuously

https://files.slack.com/files-pri/T02BVTLN3G8-F043XRN9550/image.png

https://files.slack.com/files-pri/T02BVTLN3G8-F043XMZPZCK/image.png

**Describe the solution you'd like**
To enable pagination controls, to view the list of tables sequentially. For tables with a high number of columns this functionality is also desirable

https://files.slack.com/files-pri/T02BVTLN3G8-F04400CD16G/image.png

https://files.slack.com/files-pri/T02BVTLN3G8-F044A5TQRND/image.png

**Describe alternatives you've considered**

**Additional context**

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=19271%3A22329&t=dsKa2WXtNm8G7FzY-1
@chirag-madlani
