### ISSUE TITLE
Add private constructor to utility classes to hide the implicit public one

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7844]
See the issues flagged by sonar cloud
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1118&severities=MAJOR&id=open-metadata_OpenMetadata

**Comment by ozanuslan** [comment]
I can work on this issue.

**Comment by harshach** [comment]
Thanks @ozanuslan assigning it to you
