### ISSUE TITLE
Merge if statements with the enclosing one

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7847]
Sonar cloud flagged issues - https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1066&severities=MAJOR&id=open-metadata_OpenMetadata

**Comment by andrefpoliveira** [comment]
Hey! Can I work on this?

**Comment by harshach** [comment]
hi @andrefpoliveira Yes please take it over

**Comment by Pranav-yadav** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/7851
