### ISSUE TITLE
Make final fields static

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7849]
Make final fields static https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1170&severities=MINOR&id=open-metadata_OpenMetadata

**Comment by shivam-Purohit** [comment]
Hey can I work on this issue , it will be a worthy project to start my open source journey!

**Comment by harshach** [comment]
Thanks @shivam-Purohit . Assigning it to you. If you need any help join our https://slack.open-metadata.org

**Comment by amymareemc** [comment]
Hi, I'd like to work on this as well. If possible could I get assigned to this?

**Comment by sahil3471** [comment]
I fixed this one
