### ISSUE TITLE
Prep ingestion Makefile

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7858]
Instead of putting all ingestion related work in the root project Makefile

We can then import the ingestion specific make commands into the project Makefile

**Comment by fMurugi** [comment]
Hi i would like to work on this.

**Comment by RahulSurwade08** [comment]
Hey @harshach , I would love to work on this issue. How can I get started?

**Comment by pmbrull** [comment]
hi @RahulSurwade08, assigned the issue to you. Thanks for pinging!

We have a few recipes in the Makefile that can be moved out from the root project and brought within the `ingestion/` directory:
- env38
- clean_env37
- install
- devinstall
- install_apis
- install_tests
- install_dev
- install_all
- precommit_install
- lint
- py_format
- py_format_check
- generate
- devgenerate
- run_ometa_integration_tests
- unit_ingestion
- run_python_tests
- coverage

**Comment by pmbrull** [comment]
@rahulsurwade any updates here? Let us know if you need any help
