### ISSUE TITLE
UI : Update OpenMetadata UI Readme with getting started steps 

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#7859]
Update the OpenMetadata UI Readme with getting started steps.
https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/README.md.

**Comment by MUCCHU** [comment]
I am interested in taking up the issue. I would like to know further details.

**Comment by Sachin-chaurasiya** [comment]
@MUCCHU , Assigned to you @MUCCHU

**Comment by Sachin-chaurasiya** [comment]
@MUCCHU , You have to update the https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/README.md. with the steps to run OpenMetadata UI locally.
