### ISSUE TITLE
add permalink to entity->schema/details, sample data, lineage

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#786]
Users would like to share the schema or lineage or sample data , profilet etc.. links with others
https://sandbox-beta.open-metadata.org/pipeline/sample_airflow.dim_product_etl we are not showing which tab they are on in the URL. we should add /schema, /profile, /lineage at the end such they are sharable and bookmarkable.

**Comment by ShaileshParmar11** [comment]
assign this to me

**Comment by Sachin-chaurasiya** [comment]
@ShaileshParmar11 assigned to you.
