### ISSUE TITLE
Rename this variable to not match a restricted identifier.

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7861]
Issues flagged by sonar cloud - https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS6213&severities=MAJOR&id=open-metadata_OpenMetadata

Instead of using the restricted identifier name `record`, we could change it to `extensionRecord`

**Comment by harshach** [comment]
Thanks @TheGor1lla assigned it to you
