### ISSUE TITLE
Use the primitive boolean expression 

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#7863]
See Sonar flagged issues https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5411&severities=MINOR&id=open-metadata_OpenMetadata

**Comment by semnim** [comment]
Hi, please assign me to this issue

**Comment by harshach** [comment]
Thanks @semnim assigned it to you.

**Comment by semnim** [comment]
Just to clarify, I cant find the path annotated in sonarcloud (catalog-rest-service/src/main/java/org/openmetadata/catalog/fernet/Fernet.java). Did I miss any info? There is no catalog-rest-service folder.
