### ISSUE TITLE
Pagination for table columns in the UI

### ISSUE THREAD

**Issue by cristiancalugaru** [open-metadata/OpenMetadata#7880]
**Is your feature request related to a problem? Please describe.**
Scrolling through the columns of a table when the total columns is large (2k+) is slow and not user-friendly

**Describe the solution you'd like**
Pagination for the columns would improve user interaction and decrease load time.

**Comment by nahuelverdugo** [comment]
@vivekratnavel I think this one is related to https://github.com/open-metadata/OpenMetadata/issues/7839

**Comment by chirag-madlani** [comment]
Hi @cristiancalugaru we will be tracking it in #7839 and tentatively aiming it for `1.0.0`
