### ISSUE TITLE
[DOCS] Add Upgrade Kubernetes Docs for mysql persistence volume error

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#7886]
**Is some content missing, wrong or not clear?**
Content Missing.

**Describe the solution you'd like**
While running `helm upgrade --install openmetadata-dependencies . --values values.yaml`

Error: UPGRADE FAILED: cannot patch "mysql" with kind StatefulSet: StatefulSet.apps "mysql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

This is because with 0.12.1, we will now be defaulting the mysql persistence volume to 50Gi (previously 8Gi). Statefulsets cannot be upgraded with that change. So you need to patch PVCs resource request used by mysql statefulset object manually.

Steps -

Run the below commands

`kubectl patch pvc data-mysql-0 -p '{"spec":{"resources":{"requests":{"storage":"50Gi"}}}}'`

Then, proceed with helm upgrade section.

**Additional context**
Add the above in documentation section under upgrade openmetadata.

**Comment by mazen-r** [comment]
The file that contains these docs is [this](https://github.com/open-metadata/OpenMetadata/blob/a4ed9a4184d717a8bf40522c132bb739b099c64c/openmetadata-docs/content/deployment/upgrade/kubernetes.md) right ? 
Should I add these docs under Troubleshooting for 0.12 Release or create a new Troubleshooting for 0.12.1 Release Section ?

**Comment by harshach** [comment]
@akash-jain-10 updates please?

**Comment by akash-jain-10** [comment]
Hello @harshach . These are included [here](https://docs.open-metadata.org/deployment/upgrade/kubernetes#step-2-troubleshooting). Closing this issue here.
