### ISSUE TITLE
Add lineage between terms and entities

### ISSUE THREAD

**Issue by AntonArgon** [open-metadata/OpenMetadata#7887]
**Is your feature request related to a problem? Please describe.**
Typical data analysis chain:
a) by name or characteristics, a business indicator is searched;
b) the chain of formation of a business indicator in the pipeline is analyzed;
с) data sources are analyzed.

A business indicator is essentially a glossary term. In version 0.12.0, it is not possible to bind a glossary term to a pipeline task, such as airflow. Thus, there is a break in the typical chain of data analysis.

**Describe the solution you'd like**
Proposed to add lineage between terms and other entity types (Tables, pipelines, dashboards ....)

**Comment by sureshms** [comment]
@AntonArgon few questions. I am unable to understand the description very clearly. Is the main ask ability to add tags to Pipelines and Tasks in the pipelines? Not sure what you mean by `Add lineage between terms and entities` in the title.

**Comment by AntonArgon** [comment]
@sureshms, I'll try to explain with an example. For example, we have a dashboard "USA Births Names" (https://sandbox.open-metadata.org/dashboard/sample_superset.45/details) with the indicator Sales.Contact Details.Name (https://sandbox.open-metadata.org/glossary/Sales.Contact%20Details.Name).
1) The indicator Sales.Contact Details.Name measure is entered in the business glossary with description.
2) In OpenMetadata, we scan the "USA Births Names" dashboard, create a lineage with database tables.
3) Using tags, the indicator Sales.Contact Details.Name in the business glossary is linked to the "USA Births Names" dashboard.

That is, there is a bunch of tags, but they are not visually displayed on the Lineage tab.
![image](https://user-images.githubusercontent.com/108890829/199690255-ac30e68a-3280-48fc-bc46-609d24b9477f.png)

I propose to add the terms of the business glossary as a separate type of element in the lineage and in the business glossary add the visualization of the lineage as a separate tab as Assets.
