### ISSUE TITLE
Move all resources loading such as tags/testDefinition etc.. to bootstrap instead of loading it on server start

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7912]
**Affected module**
We load of a lot of resources data example https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/resources/json/data/tags/piiTags.json as a first server start. Similarly, Test Definitions etc.. this takes a longer time for server restarts and also if someone deleted their tag category it will reload on restart. 
We should avoid loading these files during the server start instead doing it as part bootstrap-storage.sh

This might be bit involved for hacktoberfest. if you are interested in picking it up please ping us on  slack https://slack.open-metadata.org

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ssandy83** [comment]
Hey @harshach 
Can you pls assign this to me?

**Comment by harshach** [comment]
Thanks @ssandy83 assigned it to you. If you have any questions join our slack at https://slack.open-metadata.org

**Comment by ssandy83** [comment]
@harshach The idea is to move all the static data loading to the [bootstrap](https://github.com/open-metadata/OpenMetadata/blob/main/bootstrap/bootstrap_storage.sh#L56) script, right?

**Comment by harshach** [comment]
HI @ssandy83, Yes, thats right.

**Comment by ssandy83** [comment]
Hey @harshach I guess I have to look at all resources that are loaded [here](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java#L182). How do I get the list of these resources?

When I run the server locally, and in the bootstrap script, I see this error. Is the user created in the docker image, or I am missing a pre-req step?

 Access denied for user 'openmetadata_user'@'localhost' (using password: YES)

**Comment by ssandy83** [comment]
Hi @harshach 
Need some pointers here. How do I get the list of resources being loaded during restart and how do I test my changes?
