### ISSUE TITLE
profiler is inconsistent

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#7932]
profiler is inconsistent: does not honor serviceName and forces to specify the password of source DB

https://openmetadata.slack.com/archives/C02B6955S4S/p1664877683642579

**Comment by pmbrull** [comment]
hi @TeddyCr this is the behavior we have on the ingestion atm. Let's see what we are missing and if we can centralise the behavior

**Comment by TeddyCr** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/10335
