### ISSUE TITLE
Settings -> "Elastic Search" should be one single word 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7946]
**Affected module**
UI Shows in settings "Elastic Seearch" instead of "Elasticsearch"

**Describe the bug**
Rename "Elastic Seearch" -> "Elasticsearch"

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/38649/193916527-5524704a-02e1-481b-b94e-44e1e837471f.png">

**Comment by con-mark** [comment]
I can take this if you like

**Comment by harshach** [comment]
yes please @con-mark assigned it to you

**Comment by con-mark** [comment]
Thanks is there only one instance of the issue or multiple?

**Comment by ShubhraSuman** [comment]
Can you assign this to me?

**Comment by harshach** [comment]
HI, @ShubhraSuman it's taken and resolved already. Do you want to work any other issues

**Comment by Sachin-chaurasiya** [comment]
Fixed with #7949
