### ISSUE TITLE
Settings -> ElasticSearch refresh re-loads the entire panel

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7948]
**Affected module**
UI

**Describe the bug**
Once we start the elasticsearch indexing and the admin hits the refresh button, it reloads the entire panel. All we need to reload just the values instead of the entire panel.

https://user-images.githubusercontent.com/38649/193919779-935cd180-2ec4-4eab-ad7c-837a1820e893.mov

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by YuexinChen96** [comment]
Hi harshach, I am interested in this issue and want to try on this. Can you please assign this issue to me?

**Comment by alexbassa** [comment]
Hi harshach, keen to jump on this issue too if its possible?

**Comment by ayush-shah** [comment]
Assigning the issue to both, @YuexinChen96 and @alexbassa

**Comment by YuexinChen96** [comment]
> Assigning the issue to both, @YuexinChen96 and @alexbassa

Sorry about that. I have worked on this issue, but I miss-clicked the unassign-me. Could you please add me to the assignee again? Thanks.

**Comment by ayush-shah** [comment]
Assigning it to you @YuexinChen96.

**Comment by OneGuitars** [comment]
Hi，I am a student，I would like to analyse this problem and try to solve it to contribute to this project.  Could you please give me some instructions and point me in the direction of where to find the classes (or folders) concerned with the problem？

**Comment by alexbassa** [comment]
> Hi，I am a student，I would like to analyse this problem and try to solve it to contribute to this project. Could you please give me some instructions and point me in the direction of where to find the classes (or folders) concerned with the problem？

Hey! OneGuitars is a fellow group member of mine so would love for him to also jump on the issue and if you can help with direction that would be fantastic :-)

**Comment by alexbassa** [comment]
Hey @harshach, I wa having a bit of trouble finding the correct repos to work on, is there anyway you can try pointing me in the right direction? Really new to controbuting so would appreciate any help you can give! :)

**Comment by ayush-shah** [comment]
cc: @open-metadata/ui ^

**Comment by Sachin-chaurasiya** [comment]
Hello @YuexinChen96 @OneGuitars @alexbassa, Here is the file where you have to make the changes.
https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/elastic-search-index.page.tsx

**Comment by YuexinChen96** [comment]
> Hello @YuexinChen96 @OneGuitars @alexbassa, Here is the file where you have to make the changes. https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/elastic-search-index.page.tsx
> 
> Doc reference: https://docs.open-metadata.org/developers/contribute/build-code-and-run-tests

Hi Sachin, I have reviewed this issue. I notice that the onClick function for reload button is fetchBatchReIndexedData & fetchBatchReIndexedData. However, I think the main problem with this issue is not about the coding but the React framework. For these two functions, I do not find any UI refresh for this part. They only have the data updated. As for assigning new states in React, React framework will call rerender function automatically and will compare the old framework with the new one. Therefore, I think one potential solution will be changing the dependency for this panel. Typically, this page uses **Card** component to display, I think breaking this component into two may fix this problem (but I am not sure whether this way will match the original design for this component). I am not sure if my direction is correct or not. Any suggestions will be appreciated.

**Comment by Sachin-chaurasiya** [comment]
> > Hello @YuexinChen96 @OneGuitars @alexbassa, Here is the file where you have to make the changes. https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/elastic-search-index.page.tsx
> > Doc reference: https://docs.open-metadata.org/developers/contribute/build-code-and-run-tests
> 
> Hi Sachin, I have reviewed this issue. I notice that the onClick function for reload button is fetchBatchReIndexedData & fetchBatchReIndexedData. However, I think the main problem with this issue is not about the coding but the React framework. For these two functions, I do not find any UI refresh for this part. They only have the data updated. As for assigning new states in React, React framework will call rerender function automatically and will compare the old framework with the new one. Therefore, I think one potential solution will be changing the dependency for this panel. Typically, this page uses **Card** component to display, I think breaking this component into two may fix this problem (but I am not sure whether this way will match the original design for this component). I am not sure if my direction is correct or not. Any suggestions will be appreciated.

@YuexinChen96 , I would suggest we should show the loader while data is being fetched.

**Comment by alexbassa** [comment]
@Sachin-chaurasiya, as far as I can see, all the code for showing grey bars as a way of signifying that the page is loading (such as what occurs in the screenshot below) already exists for the upper panel, but, for whatever reason, is not showing. I am unable at this time to figure out why that might be, but once again appreciate any guidance :)
![Screen Shot 2022-10-18 at 3 08 58 pm (2)](https://user-images.githubusercontent.com/110961469/196333510-b21c5d1b-2457-4486-b582-8cc0e8022bf0.png)

**Comment by Sachin-chaurasiya** [comment]
@alexbassa , Can we do something like this?
When data is loading just reduce the content opacity and show the loader on top of that.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/59080942/196347485-491f4244-93b6-4c23-aa58-4f568877e7c1.png">
