### ISSUE TITLE
DBT integration deep dive docs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7954]
based on this thread https://openmetadata.slack.com/archives/C02B6955S4S/p1664900751679459 there are a few questions and considerations that we should document on how we are extracting the data etc.

**Comment by OnkarVO7** [comment]
The dbt documentation is updated and there is explanation for each feature we are supporting on how the data gets extracted
https://docs.open-metadata.org/connectors/ingestion/workflows/dbt

Also added the troubleshooting docs https://docs.open-metadata.org/connectors/ingestion/workflows/dbt/dbt-troubleshooting
