### ISSUE TITLE
Tooltip hidding issue on Modal

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#7990]
**Affected module**
UI

**Describe the bug**
Tooltip on text of any Modal is hidden behind it.

**To Reproduce**

<img width="422" alt="image" src="https://user-images.githubusercontent.com/66266464/194344170-35da9999-4c11-44b8-89f3-fd6795fe40ba.png">

**Expected behavior**
It should on top of modal and should be visible

**Comment by subashpaul** [comment]
assign me on this sir

**Comment by ayush-shah** [comment]
Hello @Chaitanya-087 @subashpaul i have tagged you both in this issue.

**Comment by manu-vaillant-afk** [comment]
Hello, is this issue resolved ? I'm a student and I would like to make my first contribution on this issue

**Comment by AKalakota23** [comment]
I would like to work on this!

**Comment by chirag-madlani** [comment]
It's already been fixed, hence closing it.
@AKalakota23 Can you check some other issue I will assign them to you
