### ISSUE TITLE
Add Elasticsearch Environment Variables Configurations with docker compose yaml files

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#7993]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Docker and OpenMetadata UI.

**Describe the bug**
Docker Compose yaml files are missing the Elastic Search configurations such as ELASTICSEARCH_PORT, ELASTICSEARCH_SCHEME, ELASTICSEARCH_USER, ELASTICSEARCH_PASSWORD.

As part of this issue, we need to update  the below docker-compose.yml files adding these environment variables under openmetadata-server docker service.
- https://github.com/open-metadata/OpenMetadata/blob/main/docker/local-metadata/docker-compose-postgres.yml
- https://github.com/open-metadata/OpenMetadata/blob/main/docker/local-metadata/docker-compose.yml
- https://github.com/open-metadata/OpenMetadata/blob/main/docker/metadata/docker-compose-postgres.yml
- https://github.com/open-metadata/OpenMetadata/blob/main/docker/metadata/docker-compose.yml

The default values for each will be -
- ELASTICSEARCH_PORT: 9200
- ELASTICSEARCH_SCHEME: http
- ELASTICSEARCH_USER: ""
- ELASTICSEARCH_PASSWORD: ""

The above change will enable `docker compose up` command to be used custom enviroment variables when connecting with external ElasticSearch cluster.

**Comment by kmalki** [comment]
Hi can I take this one ?

**Comment by harshach** [comment]
@kmalki can you try now

**Comment by kmalki** [comment]
Merged can be closed
