### ISSUE TITLE
Allow row limit for Profiler instead of just %

### ISSUE THREAD

**Issue by hendrix04** [open-metadata/OpenMetadata#7995]
When tables are VERY large, having a percentage based profiler limiter isn't ideal.

For example, 1% of 16 billion rows (real example) is still 160 thousand rows. I wouldn't necessarily want to profile that many rows every run.

**Comment by TeddyCr** [comment]
Thanks for opening this issue. While we are working on implementing this, you are able to use a decimal point sample percentage in 0.12.1 -- see screenshot below.
![Screenshot 2022-10-07 at 10 00 53 AM](https://user-images.githubusercontent.com/13626425/194503500-8f4bb2ac-cdce-40c8-838e-a42620795683.png)

**Comment by harshach** [comment]
@ShaileshParmar11 we need to fix the UI here ^

**Comment by ayush-shah** [comment]
@hendrix04 is this still an issue? if not, let me know if can close this issue
cc: @TeddyCr @harshach

**Comment by harshach** [comment]
@ShaileshParmar11 @ayush-shah we need to add an option to allow users to create a % of rows or select just a no.of rows. Lets fix this for 0.13.1

**Comment by pmbrull** [comment]
let's add 2 types from the schema so that we safely know if we are getting an int or a %
