### ISSUE TITLE
RDBMS ingestion - Filter to switch ingestion of foreign keys or other DB objects apart from the table and primary key

### ISSUE THREAD

**Issue by upenbendre** [open-metadata/OpenMetadata#8006]
Foreign key metadata is useful, but not always needed. Some legacy databases with tables of 100s of columns have loads of foreign keys. The ingestion takes a long time to get all that data, and is not critical. So it will be good to have a filter in the ingestion yml (and something similar on OM UI), to opt out of ingesting foreign keys. 
In fact the ibm_db_sa i.e. IBM's SQLAlchemy has several get methods in its reflections.py. It would be nice to have filters based on each of these methods. But foreign keys would be a good place to start

**Comment by pmbrull** [comment]
Hi @upenbendre, I have some mixed feelings on adding too many config options related to the metadata ingestion. IMO it makes sense to separate configurations if they required elevated permissions (e.g., ingesting tags for some dbs), or we only want to stick to tables (e.g., toggle views). However, keys and constraints are all essential parts of the metadata.

For now, I'd advocate for keeping this behavior. If some tables are not critical, then we could even filter them out from the metadata ingestion if having them on the catalog is not adding value.

If we get more inputs on this subject, we can pivot and add it. Thanks

cc @harshach
