### ISSUE TITLE
Clickhouse type column AggregateFunction

### ISSUE THREAD

**Issue by konnectr** [open-metadata/OpenMetadata#8007]
**Affected module**
Ingestion

**Describe the bug**
Clickhouse have column type AggregateFunction(avg, Float64) , OpenMetaData convertion type to varchar.
DBT have desription column type AggregateFunction(avg, Float64), OpenMetaData not show desription.

Airflow logs:
```
[2022-10-07, 08:56:10 UTC] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/clickhouse.py:100 SAWarning: Did not recognize type 'AggregateFunction(avg, Float64)' of column 'test_agg'
```

**To Reproduce**

1. Create table for Clickhouse 
```
CREATE TABLE test
(
test_agg AggregateFunction(avg, Float64)
)
engine = Memory()
```
2. ADD Desription columns to DBT
3. Integration metadata Clickhouse
4. Integration metadata DBT of Clickhouse

**Expected behavior**
Correcly data type and description in DBT

**Version:**
 - Python version: 3.9
 - OpenMetadata version: 0.12.1
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==0.12.1

**Additional context**

Clickhouse have to data Type 
1. https://clickhouse.com/docs/en/sql-reference/data-types/aggregatefunction
2. https://clickhouse.com/docs/en/sql-reference/data-types/simpleaggregatefunction

**Comment by harshach** [comment]
@ulixius9 lets close this out
