### ISSUE TITLE
Safer default Mark Deleted Tables

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8010]
currently if we enable that with filtered stuff, we mark everything filtered as deleted by default. The current behavior forces us to also toggle the Mark Deleted Tables from Filter Only to keep the metadata safe. We should change this behavior around. The default marking deleted behavior should be the "safe" one, only considering filter entities, and then force users to toggle a "Mark All Deleted Tables" or something if they really want to remove all the filtered data

**Comment by harshach** [comment]
@pmbrull who is this going to be assigned?
