### ISSUE TITLE
Adding hyperlinks to FK Columns for related entity.

### ISSUE THREAD

**Issue by EminUZUN** [open-metadata/OpenMetadata#8027]
Adding hyperlink to FK Column names which is addressing to related entity, would be great. Related entities would be found so easily.
FK's are already in response json. It could be a quick win.

**Comment by Sachin-chaurasiya** [comment]
We already show the hyperlinks for Fk columns.


![Image](https://user-images.githubusercontent.com/59080942/204980112-387a2514-3825-4fa1-ba79-8f140d1109ef.png)
