### ISSUE TITLE
Centralise Workflow Status handling

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8038]
Right now we have copy-paste implementation of the source/sink/stage/bulkink/processor/sink statuses. This should be a base class properly extended instead of duplicating code.

**Comment by alexbassa** [comment]
Hey pmbrull, was wondering where in the repo this is refering too?

**Comment by pmbrull** [comment]
hi @alexbassa sorry I am not doing a good job keeping an eye on the comments.

For example, we have a base [status](https://github.com/open-metadata/OpenMetadata/blob/35a87ac09c993be9529d73bc6270b877836c5e32/ingestion/src/metadata/ingestion/api/status.py#L18) class with basic implementation, but then each step (e.g., [sink](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/api/sink.py#L28) or [source](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/api/source.py#L35)), defines a similar-but-not-quite class.

It might make sense to review how this is being used and try to centralise all the calls and implementations. We usually just want to keep track of processed records, failed, warnings and filters, and that might be general for all steps.

Thanks

**Comment by pmbrull** [comment]
+ join together which entities failed with their exception
