### ISSUE TITLE
SELECT based on json fields from db

### ISSUE THREAD

**Issue by TheFu527** [open-metadata/OpenMetadata#8057]
**Is your feature request related to a problem? Please describe.**

When I use OM, I found that there are many dependencies on ES. The "List" API with `key EQ value` also depends on ES, such as List all Tables whose tableType is Iceberg. Now I could only use `query?q=tableType:Iceberg`. Is it possible to modify the list api to get rid of the search api that relies on ES?

**Describe the solution you'd like**

SELECT based on json fields from db.

**Describe alternatives you've considered**

**Additional context**

**Comment by sureshms** [comment]
@TheFu527 even if such a query can be made based on MySQL/Postgres, ElasticSearch/OpenSearch is required to search, suggest, and for counting entities based on many combinations of search queries. So I am not sure if just moving some of the existing ES queries to list API is the answer.
