### ISSUE TITLE
Ingest Athena complex type

### ISSUE THREAD

**Issue by a-cid** [open-metadata/OpenMetadata#8070]
**Is your feature request related to a problem? Please describe.**
Currently on release 0.12.1, tables containing complex data types (or at least arrays in my experience) fail to ingest.

**Describe the solution you'd like**
Athena tables containing array, map and struct columns be successfully ingested. 

Probably something similar to [this PR for Trino](https://github.com/open-metadata/OpenMetadata/pull/5931).

**Describe alternatives you've considered**
A general improvement to ingestion would be to ingest the table either excluding any columns with undefined types or marking them as such in the UI.

**Comment by flaviomax** [comment]
I can confirm the problem also happens for `structs`, not just `arrays`.

**Comment by jsuarez-ravenpack** [comment]
As further examples these tables are not being ingested. The types does not include structs, or arrays. They do not get ingested either. There may be an issue with partitioned tables making fail the ingestion!!

![image](https://user-images.githubusercontent.com/113429058/197151359-d8f52d3b-7d26-4757-961a-8e27b1a8a608.png)

**Comment by harshach** [comment]
@OnkarVO7 lets take this up for 0.13.1

**Comment by OnkarVO7** [comment]
I'll pick it up @harshach

**Comment by OnkarVO7** [comment]
Closing the issue as this has been fixed by https://github.com/open-metadata/OpenMetadata/pull/8453

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/28966081/234624549-d14209cb-6aec-4952-8496-736c59d3e4c9.png">
