### ISSUE TITLE
Create Data Insight Endpoints

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8075]
## Context
To allow admins to track the health of their data platform, the team is working on developing a setup of endpoints to allow 1) the collection of data on the platform health and 2) serving this data to display reports and allow admins to set up KPIs.

## Solution
To collect and process the data we are choosing the below approach.

1. Collect endpoint: A collect endpoint will be developed to collect data regarding users activity (sessions, page views, etc.). Regarding entity activity (description, ownership, etc.) data will be collected directly from the existing endpoints
2. Reports endpoint: Reports endpoints will be used to 1) compute raw snapshot data and write this data to MySQL and index it in ES (we decided to use the ingestion framework to schedule aggregation) and 2) retrieve aggregated data -- we'll be using elastic search for the aggregation
3. KPI endpoint: this endpoint allows teams to define KPIs for specific metrics. These KPIs will be time-bound (e.g. 80% description by xyz).

![image](https://user-images.githubusercontent.com/13626425/195020472-b1522bce-d37c-450b-b46d-2f3d57067a24.png)

## Backend
- [x] #8121 
- [x]  #8353 
- [x] #8154 
- [x]  #8472
- [x] #8633

## Ingestion
- [x] #8206 
- [x] #8473
- [x] #8470

## Frontend
- [x] #8159
- [x] #8160
- [x] #8161
- [x] #8258
    - [x] #8396 
- [x] #8413
- [x] #8540 
- [x] #8608
- [x] #8639
- [x] #8664
- [x]  #8754

**Comment by sureshms** [comment]
@TeddyCr awesome description and organization of the epic 👏 👏 👏

**Comment by Sachin-chaurasiya** [comment]
All things have been taken care of on this ticket, so closing it.
