### ISSUE TITLE
Inconvenient search in lineage

### ISSUE THREAD

**Issue by konnectr** [open-metadata/OpenMetadata#8077]
**Affected module**
UI

**Describe the bug**
not clear search

**To Reproduce**
I have airflow pipeline elt_huawei_ads_marketing.
I want to add pipeline in lineage for table.
I start search `etl` no results,
I start search `airflow etl` : i have results

Discussion on Slack about my problem
https://openmetadata.slack.com/archives/C02B6955S4S/p1665469703774989

**Expected behavior**
I want an answer to `etl`

**Version:**
 - OpenMetadata version: 0.12.1

**Comment by harshach** [comment]
@ShaileshParmar11 lets change the lineage behavior to hit search apis instead of suggestions . we can pass *etl* to find the pipelines or any object.

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 lets change the lineage behavior to hit search apis instead of suggestions . we can pass _etl_ to find the pipelines or any object.

Sure @harshach Thanks
