### ISSUE TITLE
BigQuery + dbt lineage for models from same dbt project and different Google Cloud projects.

### ISSUE THREAD

**Issue by zxy-zxy** [open-metadata/OpenMetadata#8086]
**Is your feature request related to a problem? Please describe.**
With the current implementation (as of 0.12.1) for BigQuery and dbt OpenMetadata ingestion pipeline ingests data only for the project which is specified in the BigQuery database service connection and Database filters are not working. 
The lineage from the dbt can be built only for the models under the same project. 
 
**Describe the solution you'd like**
I would like to have the option to have dbt models from different BigQuery projects can be connected in one lineage chart. 
To specify multiple GCP projects in one Database Service or Ingestion pipeline, enable database filter for GCP project id.

**Describe alternatives you've considered**
I have tried to set up different Database Service connections with different GCP projects and the same pair of dbt artifacts, but in this case, in the lineage, only models are visible from the same project as in the Database Service. 

**Additional context**
My dbt models are split between multiple Google Cloud projects in the same dbt repository (different projects for ingesting, staging, and serving layers). 
`dbt docs generate` command generates one pair of manifest.json and catalog.json files which contains all projects and models.  
Different projects for different needs are configured with `dbt_project.yml` - [https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-databases#configuring-database-overrides-in-dbt_projectyml
](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-databases#configuring-database-overrides-in-dbt_projectyml
)

**Comment by ayush-shah** [comment]
ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1665470925061989

**Comment by pmbrull** [comment]
Thanks for reporting @zxy-zxy, this should be fixed with https://github.com/open-metadata/OpenMetadata/issues/8462. It will be part of 0.13.
Thanks!
