### ISSUE TITLE
Split connections into get_connection and test_connection files

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8088]
The [connections](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/utils/connections.py) module has grown too big and it's hard to pinpoint what we are doing where.

Let's split the logic into two files, one with get_connection and another with test_connections.

Also, instead of having a module `utils`, let's move that to a module `connections`.

**Comment by vaibhavmishra4g** [comment]
hey can you assign me the issue under hacktoberfest label?

**Comment by pmbrull** [comment]
Assigned, thanks!

**Comment by u7398973** [comment]
Hi, I would also like to work on this if possible. Could you please assign me the issue as well?

**Comment by pmbrull** [comment]
hi @u7398973, apologies but looks like @vaibhavmishra4g is working on this already.

@vaibhavmishra4g, let us know if you're OK tackling this or if someone else can pick it up.

Thanks

**Comment by vaibhavmishra4g** [comment]
Really sorry but I got busy with my exams ,sorry I didn't inform it here

**Comment by vaibhavmishra4g** [comment]
Yeah you can pass on this issue to somebody else,again apologies from my side

**Comment by pmbrull** [comment]
sure no worries @vaibhavmishra4g.

@u7398973 assigned it to you, thanks for offering

**Comment by databugs** [comment]
Hi, what is the update on this? Is @vaibhavmishra4g working on it?

**Comment by vaibhavmishra4g** [comment]
Really sorry to not inform you upon this , I got pretty busy in my exams so I left open source contributions for a bit, you can give the issue to someone else. Again sorry for not informing you.

**Comment by pmbrull** [comment]
Assigned it to @u7398973, any updates?

**Comment by u7398973** [comment]
Apologies from my end as well - I will no longer be able to complete this issue at this point. Please feel free to pass it on.

**Comment by pmbrull** [comment]
hi @databugs, looks like this is free for you to pick up if you'd like. Thanks

**Comment by databugs** [comment]
@pmbrull, Thanks. Please assign it to me.

**Comment by pmbrull** [comment]
thanks @databugs , done

**Comment by databugs** [comment]
Thanks

**Comment by pmbrull** [comment]
hi @databugs any updates here?
