### ISSUE TITLE
Upon Restrictions Give the Option to make Visible Name of the Tables.

### ISSUE THREAD

**Issue by jsuarez-ravenpack** [open-metadata/OpenMetadata#8089]
**Is your feature request related to a problem? Please describe.**
Currently restrictions on view allows users to see the name of the tables

**Describe the solution you'd like**
Ideally there will be the option to see or not to see the table at all in the explore tab if the users wish to do so. 

**Additional context**
For our use case when we exclude users we don't want them to see that anything for that table is visible. But option to see the table and not fields may also be useful.

**Comment by ShaileshParmar11** [comment]
based on slack conversation https://openmetadata.slack.com/archives/C02B6955S4S/p1665488139089689

**Comment by harshach** [comment]
already tracked here https://github.com/open-metadata/OpenMetadata/issues/7012
