### ISSUE TITLE
Improve Table Queries UI

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#8096]
Improve UI
https://sandbox.open-metadata.org/table/sample_data.ecommerce_db.shopify.raw_customer/table_queries

**Comment by harshach** [comment]
@devyani-kaushik we need to work on this for 0.13.1. a query can be 100s of lines long and the way we are showing doesn't look right

**Comment by Sachin-chaurasiya** [comment]
For inspiration

https://uploads-ssl.webflow.com/6087db3cbaa248cd720ccdc5/6228c32bfe5d98946ea96c47_Leverage%20work%20done%20by%20your%20peers.png

**Comment by ShaileshParmar11** [comment]
Blocked on design cc @devyani-kaushik

**Comment by Sachin-chaurasiya** [comment]
@devyani-kaushik, We are getting these attributes for one query.

```
{
    "query": "CREATE TABLE production.products (\n\tproduct_id INT IDENTITY (1, 1) PRIMARY KEY,\n\tproduct_name VARCHAR (255) NOT NULL,\n\tbrand_id INT NOT NULL,\n\tcategory_id INT NOT NULL,\n\tmodel_year SMALLINT NOT NULL,\n\tlist_price DECIMAL (10, 2) NOT NULL,\n);",
    "users": [
        {
            "id": "afe645d6-2937-4af6-8725-cb706fa53f5e",
            "type": "user",
            "name": "TESTOPENMETADATA",
            "fullyQualifiedName": "TESTOPENMETADATA",
            "displayName": "yest",
            "deleted": false,
            "href": "http://openmetadata-server:8585/api/v1/users/afe645d6-2937-4af6-8725-cb706fa53f5e"
        }
    ],
    "vote": 1,
    "checksum": "6d995b330fc8ba3a75a242123266bc89",
    "queryDate": "2022-12-02"
}
```

**Comment by TeddyCr** [comment]
https://openmetadata.slack.com/archives/C02B6955S4S/p1671458205411699?thread_ts=1671453520.037669&cid=C02B6955S4S 👉 an example of a use case from a community member were these improvement could be used.

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=18562%3A21981&t=DTWzedNptYlKOrGU-1

@ShaileshParmar11
