### ISSUE TITLE
Change the name Test Suite to Test Suites in UI

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#8097]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/1417689/195249424-d2f42ecf-507b-421a-8483-2c87958f1ba4.png">

CC @Sachin-chaurasiya and @ShaileshParmar11. This could be a beginner issue

**Comment by u7283219** [comment]
Hey, I am a student and a new contributor to the project, can I be assigned this issue? I have read the project documentation and contribution statements. Could you please give me some instructions and point me in the direction of where to find the classes (or folders) concerned with the problem
Thanks.

**Comment by Sachin-chaurasiya** [comment]
> Hey, I am a student and a new contributor to the project, can I be assigned this issue? I have read the project documentation and contribution statements. Could you please give me some instructions and point me in the direction of where to find the classes (or folders) concerned with the problem Thanks.

Hello @u7283219, Welcome to the community, I have assigned the issue to you.

**Comment by Sachin-chaurasiya** [comment]
@u7283219 , Here is the file https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/components/MyAssetStats/MyAssetStats.component.tsx#L74 where you have to make the changes, let us know if you need any help.

**Comment by Suhas2002** [comment]
Hey, Can you assign this to me? I am new to open source and want to start contributing

**Comment by ayushanand308** [comment]
HI! I want to contribute to this issue as a first time contributor. Can you assign it to me?

**Comment by sureshms** [comment]
@u7283219 let us know if you need help. @Suhas2002 and @ayushanand308, looks like this is already assigned. Let me know if you want to work on something else.

**Comment by u7283219** [comment]
Yep, all good I have nearly completed the fix and will submit a pull request shortly.

**Comment by u7283219** [comment]
This issue can be closed, the changes have been successfully merged.
