### ISSUE TITLE
Previous value and new value is not displayed correctly for space separated data

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#8099]
- [x] Names should be one block - Clemens Rau changed to Ramendra Bahadur:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1417689/195251386-26015118-44db-4646-a66b-d71fa65858c8.png">

- [x] PersonalData.Personal changed to PII.None

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1417689/195251535-c507f735-60d6-45ac-b1ee-e5a8b45b4fb1.png">

- [x] The following should be added tags to column first_name instead of firstname.tags:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/1417689/195251668-99a2457c-2b2d-4c3c-b5ef-0e05023c9e6e.png">

- [ ] Following should just be Unfollowed table table dev.fivetran_airflow_public.ab_user_w_new_constraints instead of posted on followed by details of unfollowed a table:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1417689/195251858-cac5a074-0fc9-417c-9eaf-e035cb7bd9fc.png">

cc @harshach

**Comment by Sachin-chaurasiya** [comment]
Hello @harshach @sureshms, These diffs are getting generated from the backend, so assigning this to the backend team.

**Comment by sureshms** [comment]
@Sachin-chaurasiya this should not be coming from the backend. Can you double check the api response. Cc @vivekratnavel

**Comment by Sachin-chaurasiya** [comment]
@sureshms , I have checked it we are getting it from the backend in the `message` attribute.

```
"message": "Added **first_name.tags**: `PII.NonSensitive`",
```

```js
{
    "id": "34ec35a9-fabb-4490-ad80-262f2c1fad73",
    "type": "Conversation",
    "href": "http://sandbox-beta.open-metadata.org/api/v1/feed/34ec35a9-fabb-4490-ad80-262f2c1fad73",
    "threadTs": 1665514177915,
    "about": "<#E::table::sample_data.ecommerce_db.shopify.dim_address_clean::columns::first_name::tags>",
    "entityId": "4f58a1f5-61c5-449b-a0c7-66ccc3c8b701",
    "createdBy": "harsha",
    "updatedAt": 1665514177915,
    "updatedBy": "harsha",
    "resolved": false,
    "message": "Added **first_name.tags**: `PII.NonSensitive`",
    "postsCount": 0,
    "posts": [],
    "reactions": []
}
```

**Comment by harshach** [comment]
@sureshms @Sachin-chaurasiya  activities are formed from the backend but styling is applied on the UI right
"message": "Added **tags**: `Tier.Tier1`",

**Comment by Sachin-chaurasiya** [comment]
> @sureshms @Sachin-chaurasiya activities are formed from the backend but styling is applied on the UI right "message": "Added **tags**: `Tier.Tier1`",

Yes @harshach , That is markdown and we are parsing the markdown on the UI side.

**Comment by harshach** [comment]
@vivekratnavel will take care of it once he is back. We need to do a better diff for strings . Looks like we are applying same diff that we do for description in here.

**Comment by 07Himank** [comment]
Can I pick it up

**Comment by pmbrull** [comment]
hi @07Himank any updates here? Let us know if you need any help
