### ISSUE TITLE
The low version of mysql does not support the 5.xx I use

### ISSUE THREAD

**Issue by wangguobin425425** [open-metadata/OpenMetadata#8105]
I use docker-compose install for 0.12.1  but  my  source mysql version is 5.xx 

 12.0 version can still be used, 12.0 will not work

**Comment by sureshms** [comment]
@wangguobin425425 OpenMetadata does not support 5.x.x. Sorry, we don't have plans for supporting it given it is approaching EOL. Closing this issue.
