### ISSUE TITLE
Tableau metadata API enabled docs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8125]
- Update the docs explaining the required steps and how we use this dependency
- Update the code to explain what is missing too if we reach the exception due to missing permissions on the metadata API

**Comment by pmbrull** [comment]
@OnkarVO7 have we added these docs already?

**Comment by OnkarVO7** [comment]
@pmbrull yes this is done [here](https://docs.open-metadata.org/connectors/dashboard/tableau/cli#requirements) and [here](https://docs.open-metadata.org/connectors/dashboard/tableau/cli#example-source-configurations-for-default-and-non-default-tableau-sites)

**Comment by pmbrull** [comment]
thanks, closing
