### ISSUE TITLE
Allow Profiler to run based on a partition 

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8135]
## Context
The profiler can currently run against sample data, though in some circumstances users may want to run a against specific partition range

## Solution
On the metadata ingestion side we pick up the partitionning of table which is then passed to the table entity. We need to 
1. add logic in the profiler workflow + UI to enable profiler to run by partition (will require to also specify the partition range)
2. if the database does not support partitionning natively, allow users to define a partition field directly from the platform

**Comment by jromandv** [comment]
Allow user to set by configuration YAML/UI:
- Only the most recient (latest in time) partition -> fresh data
- A range of partitions
- No partitions (full partition scan)
