### ISSUE TITLE
table list Default sorting mode

### ISSUE THREAD

**Issue by allenhaozi** [open-metadata/OpenMetadata#8157]
**Affected module**

table list api  Get `/v1/tables`

**Describe the bug**
As we discussed https://openmetadata.slack.com/archives/C02B6955S4S/p1665664452567599?thread_ts=1665662303.423189&cid=C02B6955S4S

`We order the table by fullyQualifiedName`

That means that I get the first page of the table list, maybe it’s not the most recently created table

This is not consistent with the way we normally use pagination, and it's confusing to our users,

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

order by update time

**Comment by sureshms** [comment]
API will only support listing by alphabetical names. The explore page supports various sorting orders for the end users - last updated time, relevance, and usage. Please use the search APIs instead of table resource (see how UI does this) instead.
