### ISSUE TITLE
Integrate with Lightdash

### ISSUE THREAD

**Issue by mingfang** [open-metadata/OpenMetadata#8166]
Lightdash is an open source dashboard tool that's tightly integrated with dbt.
https://www.lightdash.com

**Comment by TeddyCr** [comment]
@mingfang (or anyone else from the community) if you are interested in implementing this we have a nice video explaining how to implement a connector https://www.youtube.com/watch?v=ZvA4wuvINFA

**Comment by TeddyCr** [comment]
@mingfang (or anyone else from the community) if you are interested in implementing this we have a nice video explaining how to implement a connector https://www.youtube.com/watch?v=ZvA4wuvINFA

**Comment by yu-iskw** [comment]
I created an issue on the lightdash side as well.
https://github.com/lightdash/lightdash/issues/5010

**Comment by abhin-dynamify** [comment]
can i take this up?

**Comment by abhin-dynamify** [comment]
Thanks i ll have a look

**Comment by abhin-dynamify** [comment]
Hey for issue i went throught the lighdash dashboard , as per the issue we need to pull data from lightdash? correct me if i am wrong

**Comment by mudgil09** [comment]
hello sir I am really excited to solve this up...looking forward that u assign this to me

**Comment by pmbrull** [comment]
this has already been implemented
