### ISSUE TITLE
CreateTableProfileRequest requires `columnProfile` to be instantiated even though it is an Optional Field

### ISSUE THREAD

**Issue by abcabhishek** [open-metadata/OpenMetadata#8171]
**Affected module**
Ingestion Framework

**Describe the bug**

`CreateTableProfileRequest` has the following attributes:

```
class CreateTableProfileRequest(BaseModel):
    class Config:
        extra = Extra.forbid

    tableProfile: table.TableProfile = Field(..., description='Table Profile.')
    columnProfile: Optional[List[table.ColumnProfile]] = Field(
        None, description='List of local column profiles of the table.'
    )
```
If columnProfile is passed as null, the ingestion task fails with a 500 Internal Server Error.
Paste: https://pasteio.com/xQRDzEIkKu9B

**Expected behavior**
Passing `null` columnProfile should not cause Ingestion to fail

**Version:**
 - Python version: 3.8
 - OpenMetadata version: 0.12.1

**Comment by harshach** [comment]
@abcabhishek are you actively passing columnProfile as None or not passing the field? Given its optional field, you don't need to pass that. Which case are you getting NPE?

**Comment by harshach** [comment]
This works in my tests
<img width="931" alt="image" src="https://user-images.githubusercontent.com/38649/204364846-dac2a767-0d1c-43ab-83a9-6c3c17282b69.png">
Added a unit test here https://github.com/open-metadata/OpenMetadata/pull/9038
