### ISSUE TITLE
Athena Connection are not ingesting Views

### ISSUE THREAD

**Issue by jsuarez-ravenpack** [open-metadata/OpenMetadata#8180]
**Affected module**
Ingestion
**Describe the bug**
Ingestions does not bring the views.
**To Reproduce**
when I run the ingestion with a view it does not bring anything not tables or views.
If I run the ingestion with only tables it then brings the tables.
Screenshots or steps to reproduce
![image](https://user-images.githubusercontent.com/113429058/196155685-980e6926-bcdb-44ea-b69b-d32a26f64e49.png)

**Expected behavior**
Upon selection the option for view I expect to have both tables and views displayed in Athena

**Version:**

 - OpenMetadata version: 0.12.1

**Comment by jsuarez-ravenpack** [comment]
Just to clarify it looks like the issue is that the ingestion cannot be reused. If I add an new Database and Ingestion it works.
So what it may need to be looked at is the way to be able to reuse then ingestion with new parameters i.e ticking or not the view. to bring different tables.

**Comment by MilanBariya** [comment]
I test out and found that Athena Connection is ingesting Views. confirm with @jsuarez-ravenpack  also on slack.

**Comment by harshach** [comment]
@MilanBariya can we close this ?

**Comment by MilanBariya** [comment]
> @MilanBariya can we close this ?

Yes @harshach we can close.
