### ISSUE TITLE
PowerBI Admin API's Required to Fetch Metadata

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#8187]
**Is your feature request related to a problem? Please describe.**
Current PowerBI connector requires a readonly **admin user** to fetch dashboard metadata via PowerBI Admin APi's. This type of user has global visibility of all PowerBI instances in case of shared tenants. The scope & object visibility of admin user is very wide and due to policies, security and information isolation, they are not provided or permited (my use case).

**Describe the solution you'd like**
Retrieve PowerBI metadata with provided user credentials, using non admistrative API's:
- https://learn.microsoft.com/en-us/rest/api/power-bi/dashboards
- https://learn.microsoft.com/en-us/rest/api/power-bi/datasets
- https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-datasources
- ...

A implementation aligned with other connectors, not requiring admin privileges (even readonly), and metadata retrieval based in provided regular user credentials.

**Describe alternatives you've considered**

**Additional context**

**Comment by jromandv** [comment]
Hi,
I would like to know if any work in progress about this Issue or will be or not considered in future releases. Thanks.

**Comment by pauloventurab** [comment]
Hello team, any update on that? The use of Power Bi is massive.

**Comment by pmbrull** [comment]
hi @jromandv, @pauloventurab, we'll work on this for 1.0. Thanks

**Comment by jromandv** [comment]
Hi @pmbrull, that's cool.

**Comment by jromandv** [comment]
If you need some time from my side to check connector let me know. Thanks again¡
