### ISSUE TITLE
Docker Hub images via trusted account

### ISSUE THREAD

**Issue by Stan-Tastic** [open-metadata/OpenMetadata#8191]
Hi,
I noticed that OpenMetadata is a "community user" on Docker Hub, would it be possible for it to become a trusted user? (like "Sponsored OSS" or "Verified Publisher").

**Comment by pmbrull** [comment]
Hi @Stan-Tastic, thanks for opening the issue. We had a chat with Docker folks, and we might not be pushing this for now.

I'd still recommend building the images locally and push them in your internal org's registry. Everything that we publish is available in the repo.

Let us know if you have any questions.

Thanks
