### ISSUE TITLE
Remove the create-ingestion-bot and update-ingestion-bot from bootstrap_storage.sh

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#8196]
**Describe the task**
Need to remove the two options from bootstrap_storage.sh
 - create-ingestion-bot
 - update-ingestion-bot

Will need to update the file TablesInitializer.java

**Comment by finn-mcclusky** [comment]
Hi, could this issue be assigned to me please?

**Comment by mohityadav766** [comment]
> Hi, could this issue be assigned to me please?

Done
