### ISSUE TITLE
OpenMetadata server supports Postgres 15

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8208]
Let's take a look at the init script we currently have, as it is throwing an error when trying to create the Flyway tables with a permission error on schema `public`.

**Comment by pmbrull** [comment]
as a workaround, we downgraded postgres to v14 in https://github.com/open-metadata/OpenMetadata/pull/8207

**Comment by harshach** [comment]
Reopenig to update the docker dependencies

**Comment by akash-jain-10** [comment]
@pmbrull @harshach Can we close this one ? The PR #12370 Takes care of the PostgreSQL 15 Support from Application end.
