### ISSUE TITLE
Split `connection.py` to resolve `too-many-lines` lint error 

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#8215]
split connection.py into multiple files to avoid  [too-many-lines](https://github.com/open-metadata/OpenMetadata/blob/9cc90e42fc1d5554a664fad9f983f187acb89fe7/ingestion/src/metadata/utils/connections.py#L1) lint error

**Comment by katebmckay** [comment]
Hello, I am interested in doing this issue. Are there any guidelines for how you would like this file split up? Any additional assistance would be appreciated.

**Comment by pmbrull** [comment]
hi @katebmckay sorry this issue is actually a duplicate of https://github.com/open-metadata/OpenMetadata/issues/8088

**Comment by pmbrull** [comment]
I'll be closing this issue now. You can take a look at what other issues we have labelled as good first issues or for hacktoberfest. Thanks
