### ISSUE TITLE
Wrong path on docker volume configuration example of postgres 

### ISSUE THREAD

**Issue by alancmag** [open-metadata/OpenMetadata#8231]
On [this ](https://docs.open-metadata.org/deployment/docker/volumes) page of the docs, on the volume configuration of postgres, the path of postgres has an extra **S** on the path.
On the docs say `- /opt/openmetadata/db:/var/lib/postgressql`
but it's not the right path of postgres. Just remove the extra **S**
it should be  `- /opt/openmetadata/db:/var/lib/postgresql`

**Comment by Shzn7** [comment]
Hey, I would love to fix this issue can I be assigned to it

**Comment by u7283219** [comment]
Hey, I would love to fix this issue can I be assigned to it

**Comment by harshach** [comment]
@u7283219 done

**Comment by u7283219** [comment]
This issue can be closed, the changes have been successfully merged.
