### ISSUE TITLE
[Github Actions] Add a better name for pytest runs

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#8244]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Github Actions CI Checks

Update the filename [.github/workflows/cd.yml](https://github.com/open-metadata/OpenMetadata/blob/2647843cd329a134493d26c90346f24fa984e7cf/.github/workflows/cd.yml) to `python-pytests.yml`.

Also update the Github Actions Workflow name to `Pytests CI` from `cd`. Ref - https://github.com/open-metadata/OpenMetadata/blob/2647843cd329a134493d26c90346f24fa984e7cf/.github/workflows/cd.yml#L1

cc - @pmbrull

**Comment by hamzabohra** [comment]
can i work on this one?

**Comment by akash-jain-10** [comment]
Yes. Thanks!

**Comment by hamzabohra** [comment]
bro why there is no file named cd.yml when i search it?

**Comment by akash-jain-10** [comment]
Hello @hamzabohra. It seems this is already taken care of! Thanks will be closing this issue for now.
