### ISSUE TITLE
UI : Handle Loading States In a Better Way

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#8261]
On some pages, UI shows an empty placeholder or some kind of placeholder before the data completely loads, something like this.

https://user-images.githubusercontent.com/59080942/196706268-87574682-0c5d-4391-807f-e51119241da8.mov

UI should handle this thing gracefully if there is a slight delay in the API response, it should show the loader until data gets fetched.

**Comment by finn-mcclusky** [comment]
Hi, could this issue be assigned to me please?
