### ISSUE TITLE
Doc: Multiple Taxonomy Project ID for bigquery

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#8264]
Add Documentation around taxonomy project id - bigquery

**Comment by harshach** [comment]
@NiharDoshi99 can we finish the documentation?

**Comment by ayush-shah** [comment]
@harshach multiple project id is taken care of, but this ticket for taxonomy is yet to be started on..
I will discuss the same with @NiharDoshi99 tomorrow.
This is related to policy tags that the user needs to fetch from different project ids, and in order to do that, they need to pass in the taxonomyProjectID.

**Comment by pmbrull** [comment]
@ayush-shah let's finish this please
