### ISSUE TITLE
Ability to push Open Metadata tags to Apache Ranger

### ISSUE THREAD

**Issue by mahajpuneet** [open-metadata/OpenMetadata#8271]
**Is your feature request related to a problem? Please describe.**
We currently do not have tag propagation from OM to Ranger. 

**Describe the solution you'd like**
As Apache ranger offers RBAC control on hive and other data assets within data orgs, we need to find a way to propagate setup up of metadata tags(data access related metadata) from OM-> Ranger.

**Describe alternatives you've considered**
Could also go through Privacera but thats a commercial solution for Ranger

**Additional context**
None

**Comment by darshanik** [comment]
Is this been added to release? or any update on this Issue. We are also trying to do the same. 

Currently I'm developing a standalone Python based "Tag synchronizer" (similar to Tag sync of Ranger, but simpler and more tailored to Open metadata as source).

It pulls entity data from open metadata API, transforms extracted payload to ranger compatible one and use Ranger Endpoints to import service tags "/service/public/v2/api/service/:serviceName/tags" (or) "/service/tags/tagdefs?updateIfExists=true" to map resource (such as hive table entity) with tags
