### ISSUE TITLE
Tableau SSL certificate verification issue

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#8284]
**Is your feature request related to a problem? Please describe.**
Tableau Connection fails by default if SSL certificate is not configured properly
By default we are verifying SSL for tableau

**Describe the solution you'd like**
Add a option to the config to add and configure the SSL certificate for tableau
ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1666236144227559

**Describe alternatives you've considered**

**Additional context**
https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/openMetadataConnection.json#L46

https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/security/ssl/validateSSLClientConfig.json

https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/ometa_api.py

**Comment by vdl-vciriza** [comment]
Same issue here. We use self-signed certificates in our on-prem Tableau Servers. The certificate validation phase fails 

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

We have encountered the same issue when calling Tableau APIs using the Python Client (TSC). We simply got through by adding in the http_options of the server instation the certificate path (path to a local copy of the certificate chain):
server.add_http_options({"verify": "/my/certpath"})

Similar to: [(https://community.tableau.com/s/question/0D58b00009ZKFlWCAX/access-https-tableau-server)]

Can you add an option to support this?

**Comment by harshach** [comment]
@OnkarVO7 are we going to handle it in 0.13.1

**Comment by OnkarVO7** [comment]
@harshach let me check if it is a quick fix we can target for `0.13.1`

**Comment by pmbrull** [comment]
Doing some changes on Tableau. Picking this up
