### ISSUE TITLE
UI - redirect links for team (Mentions) are not correct

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#8293]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

Redirect links are not working as expected
1. Mention someone in thread
2. hove over or try to navigate to that team
3. It's not redirecting

**To Reproduce**

Screenshots or steps to reproduce

![image](https://user-images.githubusercontent.com/12962843/196974891-55261920-21de-435e-b574-7740497441e8.png)

**Expected behavior**

It should redirect to teams page

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

Check for users as well

**Comment by Aashish1221** [comment]
Adding on above issue more env. details where this is replicable.
Version:

OS: Linux/Mac
Python version:
OpenMetadata version: 0.12.1
