### ISSUE TITLE
UI: Confusing data about query on table details page.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#8303]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
On table details page, the 'Queries Usage Count' is shown as ' {number of usage} Queries' but we show only unique queries in the 'Queries' tab which is confusing for user. Need to update the message to state clearly what the count is about.

**To Reproduce**

Screenshots or steps to reproduce
<img width="1356" alt="Screenshot 2022-10-21 at 5 31 06 PM" src="https://user-images.githubusercontent.com/51777795/197191866-59d06f7e-cb4c-4c33-a23b-cda861839c40.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
@harshach , Are we going to handle this in 0.13.1? If yes then will need more info like how we can handle this on the UI side.

**Comment by harshach** [comment]
moving it ,lets handle as part of query refactor

**Comment by chirag-madlani** [comment]
@harshach Currently we don't have query data coming from details API. Need support for the same
Attaching response for current API with supported fields
<img width="1800" alt="Screenshot 2023-04-04 at 4 52 01 PM" src="https://user-images.githubusercontent.com/12962843/229776573-2b7085c7-b0df-488c-9572-8807d89024be.png">
