### ISSUE TITLE
Doc: Fill in docs for Lineage Workflow

### ISSUE THREAD

**Issue by flaviomax** [open-metadata/OpenMetadata#8310]
**Is some content missing, wrong or not clear?**
Lineage Workflows were released in version 0.12.0, [but the docs are empty](https://docs.open-metadata.org/connectors/ingestion/workflows/lineage).

**Describe the solution you'd like**
The docs for the Lineage Workflow to be filled in, specially regarding how to run the workflow using a yaml file and query logs (as was done with [Usage Workflow Through Query Logs](docs.open-metadata.org/connectors/ingestion/workflows/usage/usage-workflow-query-logs#usage-workflow-through-query-logs) ) for databases that do not support it directly thorugh the connector.

**Additional context**
That Usage Workflow Through Query Logs doc is also out-of-date, but I'll create another Issue for that :)

**Comment by yayayi60** [comment]
Hey, I'd like to start taking a look at this issue, could you please assign it to me?

**Comment by sureshms** [comment]
There has been a lot of improvement in docs since this issue was created. Reopen with specific comments if there are still pending issues.
