### ISSUE TITLE
Replace null and empty checks with a util method

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#8319]
Many of the code that does the following check (from `TableRepository.java`):
```
addedColumn.getDescription() == null || addedColumn.getDescription().isEmpty()
```
Can be replaced with `CommonUtil.java` method:
```
nullOrEmpty(addedColumn.getDescription())
```

There are 11 instances in the code:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/1417689/197350806-bb9830c1-5960-45e4-bdae-c9063b8cc9dc.png">

**Comment by MaheshGPai** [comment]
I can pick this. You can please assign this to me.

**Comment by sureshms** [comment]
@MaheshGPai assigned it to you 😊
