### ISSUE TITLE
Remove botName from createUser request

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#8321]
A bot can't be created without a user. We already have `createBot` which takes user reference. Let's avoid adding another way to create a bot during user creation. Let's stick to the existing mechanism:
1. A user is created for a bot.
2. That user is used in createBot to build an association between the user and the bot.

**Comment by sureshms** [comment]
@nahuelverdugo, assigned this issue to you.

**Comment by harshach** [comment]
duplicate #8984
