### ISSUE TITLE
SQL query missing when a data quality test is edited

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#8341]
**Affected module**
UI

**Describe the bug**
I created a test and then needed to edit it.  When I click edit, the SQL Query field is blank.  Currently I have to copy the query before clicking edit, then paste it in and edit it.

Here's a screenshot of the SQL Query field being blank:

![image](https://user-images.githubusercontent.com/7569808/197607903-f6111e45-aa64-47fc-a317-3cc67524cf36.png)

**Expected behavior**
Just like the Description text populates in an editable field, the SQL Query should do the same -- appear as text to edit, not a blank field.

**Version:**
 - OpenMetadata version: 0.12.2

**Comment by harshach** [comment]
@ShaileshParmar11 lets add tests for these
