### ISSUE TITLE
Display Custom properties in Entity details page

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#8345]
**Is your feature request related to a problem? Please describe.**
Custom Properties are hard to find in a separate table. Folks using OpenMetadata might not even find it.

**Describe the solution you'd like**
Custom properties should have configuration to be displayed at the table summary section.

If you want to take it one step further, any property in table summary should be configurable. E.g. not everyone might care about having "Tier" at the top.

**Comment by harshach** [comment]
@chirag-madlani custom properties need to be turned into a knowledge panel that can be added to the right side bar on entity page
