### ISSUE TITLE
Column name only display 20 characters and is cut off after that

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#8346]
**Affected module**
UI

**Describe the bug**
Full column name is not displayed but cut off after 20 characters

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/197687806-5bbe29c5-84bf-48b3-b2f2-be1ee5ec1706.png)

**Expected behavior**
Display full column name

**Version:**
 - OS: Windows, Chrome
 - OpenMetadata version: 0.12.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Comment by trillhaa** [comment]
Same for data type for "timestamp without time zone" (27). there is a lot of space for "Description", I think you can take some away there 
![image](https://user-images.githubusercontent.com/102999683/197689024-8a807e30-ccaf-4485-89e6-51efd4b73a08.png)

**Comment by trillhaa** [comment]
This is still not handled very well. I can still see cutoffs after 27 characters. I really don't understand why we give so much real estate to description but no enough to column name. Not seeing full column name is a very poor customer experience

![image](https://user-images.githubusercontent.com/102999683/213267314-f616eb44-28e6-470b-9e0d-7455fdcb6e1b.png)

**Comment by harshach** [comment]
@Ashish8689 @chirag-madlani can you take a look. Doesn't look like fix is working cc @trillhaa

**Comment by trillhaa** [comment]
The new screenshot is on version 0.13.1 by the way.

**Comment by Ashish8689** [comment]
Fix PR for this issue. : https://github.com/open-metadata/OpenMetadata/pull/9807

**Comment by trillhaa** [comment]
It also looks wrong in "Profile & Data Quality" section
![image](https://user-images.githubusercontent.com/102999683/213539246-3b0a7a70-b906-48d3-8ce4-f4ee4e40952c.png)
