### ISSUE TITLE
Allow control of which tests get sent via which webhooks

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#8357]
**Is your feature request related to a problem? Please describe.**
I have a webhook connector to an MS Teams channel that sends _all_ test case results to the channel.  But I have different audiences who are in different teams and channels.  There's currently no way to pick which test suites get sent via a webhook, it's all or none.

**Describe the solution you'd like**
I want to set up multiple webhooks and have each connected to a different channel, reporting a different set of test results in each channel.  The first part is currently possible (multiple webhooks) but it would send all the test results from every suite to each channel.

**Additional context**
From Slack @sureshms suggested I file this issue 😄

**Comment by harshach** [comment]
Addressed in new alerts overhaul. Will be part of 0.13.1
