### ISSUE TITLE
Column name with % and ) causes error in profiler

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#8358]
**Affected module**
Ingestion

**Describe the bug**
I have a table with a column called `Ozone gas concentration (%03)`.  This throws an error in the Profiler logs:
> {'Ozone gas concentration (%03)': {'Static Metrics': {"unsupported format character ')' (0x29) at index 46"}}}

**Version:**
 - OpenMetadata version: 0.12.2

**Comment by harshach** [comment]
@ayush-shah lets handle this in 0.13.1

**Comment by TeddyCr** [comment]
@harshach I believed we said we won't fix this has it requires some very intricate logic for an edge case
