### ISSUE TITLE
Add CI support for Python 3.10

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8359]
3.7 EOL is planned for Juner 2023. We should start the moving towards adding support for 3.10 and 3.11:
- add CI test for python 3.10 and 3.11

**Comment by ayush-shah** [comment]
@TeddyCr should we have a weekly CI to test out python support for plugins / connectors?

**Comment by pmbrull** [comment]
added 3.10, CI looks fine on `main`

**Comment by pmbrull** [comment]
we'll add 3.11 here https://github.com/open-metadata/OpenMetadata/issues/12082
