### ISSUE TITLE
Wrap `sqllineage` usage into a class

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#8364]
**Issue**
We should have the same behavior when calling the `LineageRunner` parser from different workflows and connectors.

For example:
We have calls directly to `LineageRunner` in [this](https://github.com/open-metadata/OpenMetadata/blob/a6822aa0942c841a6b8a811f29aea44388d220e0/ingestion/src/metadata/ingestion/source/dashboard/mode.py#L143) line and also [here](https://github.com/open-metadata/OpenMetadata/blob/a6822aa0942c841a6b8a811f29aea44388d220e0/ingestion/src/metadata/ingestion/source/dashboard/redash.py#L129). And probably in other places.

**Solution**
Wrap the usage of `sqllineage` in a class where we can align how we want to call it without coupling the use of this library to different parts of the code. 

An idea for this issue could be to create a util class:
```python
class LineageParser:
  
  @classmethod
  def create(sql_query: str) -> LineageRunner:
     return LineageRunner(clean_raw_query(query.get("raw_query")))
```
And replace calls like:
```python
table_list = LineageRunner(clean_raw_query(query.get("raw_query")))
``` 
with:
 ```python
parser = LineageParser.create(query.get("raw_query"))
```

**Comment by ssandy83** [comment]
@nahuelverdugo 
Is this issue still open? Can I work on this?

**Comment by nahuelverdugo** [comment]
Hi @ssandy83, thank you for your interest 🚀 ! Yes, it is still open. I will assign it to you, let me know if you have any doubts here on our [slack](https://slack.open-metadata.org/) channel.

**Comment by pmbrull** [comment]
hi @ssandy83 any updates here? Thanks

**Comment by ssandy83** [comment]
Hey @pmbrull 
I couldn't get to this yet. I shall be able to have an update by next week

**Comment by nahuelverdugo** [comment]
Sorry @ssandy83, I hope you have not started to work on this issue, but it has been closed as part of another [issue](https://github.com/open-metadata/OpenMetadata/pull/9073) we were fixing. Feel free to reach out to us on Slack if you want to collaborate on another task :)
