### ISSUE TITLE
Deprecate EntitiesEdge

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8379]
in the entityLineage.json https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/type/entityLineage.json#L75 we have both `edge` and `EntitiesEdge`.

We need to deprecate EntitiesEdge in favor of edge.

- [ ] update ingestion
- [ ] check backend
- [ ] check frontend
- [ ] update docs

**Comment by sureshms** [comment]
`entitiesEdge` is used for accepting lineage details using `entityReferences` as nodes (so it can be any entity and hence entityReference includes id and type) in the `addLineage` request. The type `edge` is used to provide entity lineage information as `entityLineage` where nodes in the graph are already covered in the `nodes` field and edges are just based on `uuid`.
