### ISSUE TITLE
Link tags on Column datalog to Glossary

### ISSUE THREAD

**Issue by silviodvjr** [open-metadata/OpenMetadata#8395]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i need watch the glossary descripton when im browsing data column and this data column reference glossary through <tag>, its amazing if when i click on <tag> be redirect to glossary descriptions.

![image](https://user-images.githubusercontent.com/38475199/198326123-e955567c-6999-4867-9655-4ece4f0cca22.png)

**Comment by harshach** [comment]
This issue is already fixed @silviodvjr please check the latest release
