### ISSUE TITLE
Advance search not allowing values for `==`, `!=`,`Not In`, `Any In`, 

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8397]
https://user-images.githubusercontent.com/13626425/198330489-c4a4e283-e80f-4e45-bc76-95356d2d29d4.mov

**Comment by Ashish8689** [comment]
@chirag-madlani  In `Not In` case only a single input value is working perfectly. While multiple values give incorrect entities.

**Comment by chirag-madlani** [comment]
All the operators are working fine.
Only one issue is when we try to send multiple values for an operator like `Not In` it's not giving us desired results
Note: for single values it's working fine
cc: @harshach

**Comment by harshach** [comment]
@chirag-madlani this working as expected now, closing it out
