### ISSUE TITLE
Ability to add relationships between entities manually 

### ISSUE THREAD

**Issue by n00j** [open-metadata/OpenMetadata#8400]
**Is your feature request related to a problem? Please describe.**
Hard to figure out relationships between different datasets / tables in openmetadata.  For data that is manually generated, there is no where to ingest table constraints and thus no way to create relationship between entities.

**Describe the solution you'd like**
It would be great to have the ability to add relationships / table constrains between tables manually via the UI. Data imported from different data sources could be related in some way, so automated methods to determine relationships is not always possible. 

From these relationships, it would be great to be able to view an ER diagram based on the relationships, similar to how Lineage is visualized. 

**Describe alternatives you've considered**
N/A

**Additional context**
Found this other issue for the ER diagram: https://github.com/open-metadata/OpenMetadata/issues/8028

**Comment by karanh37** [comment]
Hey this feature is now available in the latest version of OM.
For ER diagrams, you can track this [ticket](https://github.com/open-metadata/OpenMetadata/issues/8028).
