### ISSUE TITLE
New tables, new columns, changed tables don't appear in my feed

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#8405]
I'm using MSSQL.

**Affected module**
Ingestion/UI

**Describe the bug**
New tables are ingested overnight.  They appear at the top of the `/explore/tables` list so I know they are being ingested and recognized as new.  But they, and adding a new column to a table, do not appear as notifications / posts in my home feed.  Prior to ingestion I made sure all boxes were checked at `/settings/collaboration/activityFeed`.

**To Reproduce**

Ingest new tables, see if it appears in home feed.  Can't think of anything else on my config / steps that could cause this.

**Expected behavior**
New tables and new columns appear in the home feed.

**Version:**
 - OpenMetadata version: 0.12.2

**Comment by sfirke** [comment]
I now think this could be caused by a failure to track versions of my data tables.  I updated a View two days ago but it still shows as a single version, though there should be a version 0.2.
![image](https://user-images.githubusercontent.com/7569808/199276955-566cb826-5278-4da4-ae87-749976f2389e.png)

If the ingestion is not creating a second version of any database, could that bug be causing me not to see any new tables/added column activity?  I will re-title this issue accordingly.

**Comment by sfirke** [comment]
Here's what versions look like for a new table I just added to the DB and then scanned with ingestion:
![image](https://user-images.githubusercontent.com/7569808/199308285-2042f900-9512-40f7-b52e-7f776a535503.png)

That new table addition doesn't show up in my feed either.

**Comment by sureshms** [comment]
@sfirke, is this issue still relevant?

**Comment by sfirke** [comment]
Hi @sureshms - I'll confirm with a test tomorrow but I think so, in v1.1.

**Comment by sfirke** [comment]
Enabling posts to the ActivityFeed by the ingestion-bot solved this, now I'm seeing the creation of new columns post to the feed when I log in.  I'm not sure entirely new tables are showing up, but that's not a concern for now.  I will close this issue as I believe it was solved by letting the ingestion-bot post to the feed.
