### ISSUE TITLE
[Sonar] Use try with resources and closing Ldap connection

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#8406]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
see the sonar for reference
https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=8403&id=open-metadata_OpenMetadata&open=AYQa96av7Bk8kfmsZ_IB

**To Reproduce**

Screenshots or steps to reproduce
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/105265192/198495928-199979b4-0493-4fcb-a871-49b4edb9c4ac.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ShajithaMohammed** [comment]
I'm interested to contribute here!

**Comment by mohityadav766** [comment]
> I'm interested to contribute here!

hi @ShajithaMohammed  , thank you for your contribution
