### ISSUE TITLE
Bulk Edit Entity Metadata

### ISSUE THREAD

**Issue by jromandv** [open-metadata/OpenMetadata#8415]
**Is your feature request related to a problem? Please describe.**

**_Managing metadata individually click by click consumes a lot of time and resources, not feasible in almost all scenarios._**
To ease work and productivity of data owners/users with certain privileges, it would be nice to **_manage attributes of multiple entities simultaneously on the UI._**

**Describe the solution you'd like**

In the UI, allow users to search entities by multiple criteria (owner, tag, name, glosary tag, tier, ...) and logical conditions. Once the list of matching entities appears on the screen, **allow to select all or those on you want to make a massive and simultaneous change in their custom metadata**.

- In a next step/screen, new attributes (owner, tags, terms, ...) could be selected/added and will be common to all the selected entities, or some of the attributes that are currently common to all of them will be deleted/modified.

- A complementary operation consists to **_allow entities to be exported to an excel or csv file, which the user would download to their desktop to work unattended, modifying the metadata of the entities at discretion_**. Once modified, the user would upload the entity file to OM through the UI.

- Metadata changes will be done at the entity and/or attribute level, perhaps the user should indicate by UI the scope.

 This operation will consider core OM aspects to garantee repositry integrity related to the user that requests: rights, role, owner, 	... over the involved entities.

In both cases (UI/File) and as process summary, **_a log is generated and viewed on screen, with the success or error of the operations, to guarantee entities have been updated correctly_**, or determinate errors on those not.

**Describe alternatives you've considered**
A custom development application with OM API integration.

**Additional context**
 Owners are responsible for managing tens, hundreds or thousands of tables. Usually it's necessary to make multiple and simultaneous changes to entity custom metadata, even temporarily (owner, tags, tier, glossary terms, etc.).

**Comment by aBoMBaYa** [comment]
+1. We found the same problem. It has been here for almost a year. Could you help prioritize this?

**Comment by maiake** [comment]
+1, we are facing this problem at the moment as we have a service that do bulk column description suggestions to table owners, resulting to hundreds and thousands tasks to review at once. The owners feedback that it is very painful with the current UX/UI. Would be great to prioritize this issue.

**Comment by harshach** [comment]
@aBoMBaYa @maiake we will shipping it in 1.3
