### ISSUE TITLE
False Usage Query Count

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#8422]
**Affected module**
Ingestion Framework

**Describe the bug**
The count of queries during usage keeps getting increased after running the usage pipeline even though no queries have been executed.

![image](https://user-images.githubusercontent.com/39544459/198612690-2fcaa542-fde6-41af-85c0-1161e12f0742.png)

**To Reproduce**
run the usage pipeline multiple times and see the count getting increased even though no queries have been actually executed in DB.

**Comment by harshach** [comment]
@ulixius9 is this done?

**Comment by pmbrull** [comment]
we need to start with this yet
