### ISSUE TITLE
SQLServer Profiler throw overflow error

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8430]
The sum function will use the field dtype as the dtype of the returned value. If this value is bigger than the value field can hold an overflow error will be thrown. 

### Solution
Similar to what we implemented for BigQuery, we'll need to force the field dtype to bigint in the sum function
https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/orm_profiler/orm/functions/sum.py

**Comment by sfirke** [comment]
I could implement this as an exception for MSSQL in the style of the BigQuery exception.  But I see Postgres and MySQL have the same limits on int (2^31) and bigint (2^63) so will be hit with the same error.  Could the generic command simply be changed to `return f"SUM(CAST({proc} AS BIGINT))"` or are there any SQL dialects that would cause problems for / other issues?

**Comment by TeddyCr** [comment]
@sfirke, I'd say to keep the general case general. If redshift will have the same issue let's fix it similar to BigQuery.

If those 3 Dialects have the exact same syntax you can below line 38 a decoractor similar to what we did with Bigquery. Something like that

```
@compiles(SumFn, Dialects.BigQuery)
@compiles(ConcatFn, Dialects.Redshift)
@compiles(StdDevFn, Dialects.MSSQL)
def _(element, compiler, **kw):
    """Handle case where column type is INTEGER but SUM returns a NUMBER"""
    proc = compiler.process(element.clauses, **kw)
    return f"SUM(CAST({proc} AS BIGINT))"
```

☝️ this assumes all 3 will use the same logic. Otherwise you'll need to create specific function with the appropriate decorator.
