### ISSUE TITLE
Glossary / Tag / Team names should be editable

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#8438]
**Is your feature request related to a problem? Please describe.**
When I change the "Display" name of a glossary term (or tag, team), the true name remains unedited. 
As a result, I have to redo the entire glossary hierarchy if I want to not carry over mistakes.

![image](https://user-images.githubusercontent.com/102999683/198858181-57354998-d138-430d-ac57-d4abbea50f25.png)

**Describe the solution you'd like**
Names should be editable at any point in time in a hierarchy.

**Comment by sureshms** [comment]
Task breakdown:

- [ ] 8438

**Comment by harshach** [comment]
@chirag-madlani can we check if all of the above is supported from the UI side?

**Comment by harshach** [comment]
Shipped in 1.0
