### ISSUE TITLE
Ingesting the metadata of bigquery tables of different projects 

### ISSUE THREAD

**Issue by Deepakparashar14** [open-metadata/OpenMetadata#8462]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hello team ,
I am looking to ingest the metadata of various gcp projects from the bigquery tables but as of now there is no way I can define the complete fully qualified name of the tables from various projects in big query connection config
Like projectname.datasetid.tablename
Can you please consider this as feature request as  the OM would be running on gcp Vm and it will have permission to various other projects

**Comment by harshach** [comment]
@ayush-shah you looked into this before right

**Comment by ayush-shah** [comment]
@harshach we currently have multiple taxonomies policy tags from different project ids.
we will be able to ingest multiple project ids into one service using similar approach

**Comment by Deepakparashar14** [comment]
Thanks a lot Ayush

**Comment by Deepakparashar14** [comment]
Please let me know in which version this feature can be included

**Comment by ayush-shah** [comment]
we should have this feature in the upcoming releases post 0.13,
Also, let us know if you want to contribute, i can assign this issue to you.
