### ISSUE TITLE
Add Authentication Support for Dagster Pipeline Ingest

### ISSUE THREAD

**Issue by slopp** [open-metadata/OpenMetadata#8465]
Thank you @NiharDoshi99  for adding Dagster support through the GraphQL endpoint! 

This issue is a follow on for auth support, which is being driven by a mutual prospect. 

**Is your feature request related to a problem? Please describe.**
The current dagster ingest only accepts a HostPort which is insufficient for accessing the GraphQL endpoint in Dagster Cloud which requires an API token. 

Code: https://github.com/open-metadata/OpenMetadata/blob/cbcb910f06541876e3964e0aa59b73e19f89b27c/ingestion/src/metadata/utils/connections.py#L952-L967

FWIW the Dagster integration docs suggest this idea was considered but not implemented, as they refer to an API token.

https://github.com/open-metadata/OpenMetadata/blob/3d3dcff910301bd3a4a6eea50dcc510f2f75103f/openmetadata-docs/content/connectors/pipeline/dagster/index.md?plain=1#L138-L139

**Describe the solution you'd like**
Adding an optional parameter for an API key then using it as:

```
client = DagsterGraphQLClient(url, transport=RequestsHTTPTransport(url=url+"/graphql", headers={"Dagster-Cloud-Api-Token": token}))

```

Ref: https://github.com/dagster-io/dagster/discussions/7772

**Describe alternatives you've considered**
We could add a Dagster Cloud specific connector, but this adds a lot of duplication in what could be an optional parameter.

**Comment by NiharDoshi99** [comment]
Hi @slopp , already working on integrating dagster with cloud and local just by changing `dagster.yaml` file .
Please find the issue for the same #7934

**Comment by slopp** [comment]
Awesome @NiharDoshi99  thanks!

**Comment by geoHeil** [comment]
this is already working / the issue can be closed
