### ISSUE TITLE
Inherited ownership for children in schema entities

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#8479]
**Is your feature request related to a problem? Please describe.**
Currently, entity children (tables in schemas, for instance) don’t inherit owners. If a new table was added to some schema with an owner, you have to manually assign the same owner to this individual table. Given that there are 100 new tables in the schema, the task of manually doing the job is burdensome for users. 

**Describe the solution you'd like**

Assign automatically owners to the child-entities. For example, if schema has an owner assigned, then newly added tables in this schema should inherit the owner automatically.

**Describe alternatives you've considered**

**Additional context**

**Comment by sureshms** [comment]
Related tasks:
- [ ] #8821
- [ ] #8823
