### ISSUE TITLE
UI: Add search field in system/database/schema interfaces

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#8480]
**Is your feature request related to a problem? Please describe.**

It's inconvenient to search for schemas in databases using next button. If you have hundreds of schemas in a database or tables in a schema, searching becomes tedious. 

**Describe the solution you'd like**

Adding searching field to system/database/schema interfaces level would greatly enhance user experience. Mock-up is attached.

**Describe alternatives you've considered**

**Additional context**
<img width="1361" alt="A2646419-83E5-48C8-91F5-75F597A8FDFA" src="https://user-images.githubusercontent.com/60112387/199257961-a83dfbce-d11f-4696-8ffb-35648bdf4044.png">

**Comment by harshach** [comment]
@chirag-madlani one option is to use the export styling here and use ES for listing and searches. Will be faster to add.

**Comment by chirag-madlani** [comment]
@harshach Let me verify and update you on this

**Comment by ShaileshParmar11** [comment]
To give search support for schema and database we need to add schema and database index in ES.
cc @harshach
