### ISSUE TITLE
More visually organised team’s assets page

### ISSUE THREAD

**Issue by Tonilyn** [open-metadata/OpenMetadata#8481]
**Is your feature request related to a problem? Please describe.**

Currently, team's assets page is disorganised: users see all kinds of entities chaotically let it be tables or schemas etc. It would be much more convenient to see some sort of structure to navigate through all the information. As for now, it’s nearly impossible to look up data in Assets page. 

**Describe the solution you'd like**

More visually organised Assets would be great based on feedback. For example, in file systems you can sort your files by their types. It would be great to see all these team’s assets sorted like this by type (systems, databases, schemas, tables, dashboards, ml models etc). Or any other structure you might deem appropriate. 

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani we discussed this previously that all the asset pages should have same structure as what we are doing for Glossary assets page.

@Tonilyn thanks for raising the issue. What you think of applying the styling of Explore listing to Asset pages everywhere?
