### ISSUE TITLE
Update Table styling

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#8497]
Update the table styling to the styling in image below
<img width="1022" alt="Screenshot 2022-11-02 at 4 27 55 PM" src="https://user-images.githubusercontent.com/103238069/199472673-b1c8704f-50e7-4f8f-98f1-eeb68d36db94.png">

**Comment by sureshms** [comment]
@devyani-kaushik what is the styling change here? Can you please add details?
