### ISSUE TITLE
Build tag and glossary term cache and use it instead of database lookups in list operations

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#8506]
Currently, while listing entities, to get the details of tag labels that entities have we do the following joins:
```
    @ConnectionAwareSqlQuery(
        value =
            "SELECT tu.source, tu.tagFQN, tu.labelType, tu.state, "
                + "t.json ->> '$.description' AS description1, "
                + "g.json ->> '$.description' AS description2 "
                + "FROM tag_usage tu "
                + "LEFT JOIN tag t ON tu.tagFQN = t.fullyQualifiedName AND tu.source = 0 "
                + "LEFT JOIN glossary_term_entity g ON tu.tagFQN = g.fullyQualifiedName AND tu.source = 1 "
                + "WHERE tu.targetFQN = :targetFQN ORDER BY tu.tagFQN",
        connectionType = MYSQL)
    @ConnectionAwareSqlQuery(
        value =
            "SELECT tu.source, tu.tagFQN, tu.labelType, tu.state, "
                + "t.json ->> 'description' AS description1, "
                + "g.json ->> 'description' AS description2 "
                + "FROM tag_usage tu "
                + "LEFT JOIN tag t ON tu.tagFQN = t.fullyQualifiedName AND tu.source = 0 "
                + "LEFT JOIN glossary_term_entity g ON tu.tagFQN = g.fullyQualifiedName AND tu.source = 1 "
                + "WHERE tu.targetFQN = :targetFQN ORDER BY tu.tagFQN",
        connectionType = POSTGRES)
    List<TagLabel> getTags(@Bind("targetFQN") String targetFQN);
```

`tag_usage` table from `openmetadata-service/src/test/resources/db/sql/com.mysql.cj.jdbc.Driver/v001__create_db_connection_info.sql`
```
CREATE TABLE IF NOT EXISTS tag_usage (
    source TINYINT NOT NULL,            -- Source of the tag label
    tagFQN VARCHAR(256) NOT NULL,       -- Fully qualified name of the tag
    targetFQN VARCHAR(256) NOT NULL,    -- Fully qualified name of the entity instance or corresponding field
    labelType TINYINT NOT NULL,         -- Type of tagging: manual, automated, propagated, derived
    state TINYINT NOT NULL,             -- State of tagging: suggested or confirmed
    UNIQUE (source, tagFQN, targetFQN)
);
```

When we list 1000s of entities, these joins make the list operations slow.

We are doing these joins for the following reason:
- Given an entity's FQN (for a table for example.- `databaseService.database.databaseSchema.table`), we look up all the tag label information `source` (tag label is from Glossary or Tag), `tagFqn` (fully qualified name of the tag/glossary), `labelType` and `state` from the `tag_usage` table.
- Just to get the description of tag or glossary to tagLabel we are doing left join.

To optimize this:
- Build a cache of tags and labels similar to `https://github.com/open-metadata/OpenMetadata/blob/aab3b89165dd7359168e0721340a408cd1c05de7/openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectCache.java`
- Use that information to populate this information in listing results

**Comment by sisir-umich** [comment]
Hi @sureshms , can you assign this issue to me? Thanks!

**Comment by sureshms** [comment]
@sisir-umich done

**Comment by show981111** [comment]
Hi @sureshms , I and sisir want to work this together. Can you assign it to me with sisir?

**Comment by sureshms** [comment]
@sisir-umich and @show981111, how is it going? Do you guys need any help?

**Comment by sisir-umich** [comment]
Hi @sureshms , sorry for the late response. We actually selected a different project to work on for the course, so you can unassign us from this - thanks!

**Comment by trillhaa** [comment]
We are actually seeing a lot of lag for pages to be opened and users have asked us what is going on. Do you guys have an ETA for addressing this bug?

**Comment by sureshms** [comment]
@sisir-umich and @show981111, thank you for letting us know in a timely manner.
