### ISSUE TITLE
UI Improvements 0.13

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#8513]
- [x]  change "Delete Catagory" button styling to secondary
<img width="325" alt="Screenshot 2022-11-03 at 11 15 53 AM" src="https://user-images.githubusercontent.com/103238069/199654883-5f2c527b-70d5-4158-bed5-223d41eb13d3.png">

- [x]  Left and right padding is not consistent on all pages
<img width="136" alt="Screenshot 2022-11-03 at 11 17 47 AM" src="https://user-images.githubusercontent.com/103238069/199655077-909bae0c-dd8a-44fe-b227-65cb0f0f0495.png">
<img width="154" alt="Screenshot 2022-11-03 at 11 17 59 AM" src="https://user-images.githubusercontent.com/103238069/199655097-ffe44218-93a3-475a-8a0e-cff34a526eb6.png">
<img width="128" alt="Screenshot 2022-11-03 at 11 18 12 AM" src="https://user-images.githubusercontent.com/103238069/199655118-edc6074f-7513-4145-ae7f-fe67c36a493e.png">
<img width="107" alt="Screenshot 2022-11-03 at 11 18 38 AM" src="https://user-images.githubusercontent.com/103238069/199655162-50ac371c-1d62-4add-8070-82452cabe988.png">

- [x] Left Column needs to have fixed height
<img width="1440" alt="Screenshot 2022-11-03 at 11 19 28 AM" src="https://user-images.githubusercontent.com/103238069/199655255-a9c1e336-10bc-494d-90e4-33582f7f9551.png">

- [x] Can we add an empty table when no data is available ?
<img width="1440" alt="Screenshot 2022-11-03 at 11 26 45 AM" src="https://user-images.githubusercontent.com/103238069/199655928-b208e3e0-2168-4328-bdd9-8a10f54423b1.png">

- [x] Delete icon getting cropped in user list
<img width="1140" alt="Screenshot 2022-11-03 at 11 44 30 AM" src="https://user-images.githubusercontent.com/103238069/199657854-2f833d28-a018-4975-8572-3c917d088b20.png">

- [x] Table styling not consistent 
<img width="1396" alt="Screenshot 2022-11-03 at 11 46 48 AM" src="https://user-images.githubusercontent.com/103238069/199658013-5b967db1-fc93-46de-ba78-5f4b435c742e.png">

- [x] need to update the right documentation link
<img width="887" alt="Screenshot 2022-11-03 at 11 51 48 AM" src="https://user-images.githubusercontent.com/103238069/199658656-343cfcc0-2802-4736-b0a8-90a2c0e9b1aa.png">

**Comment by devyani-kaushik** [comment]
- [ ] Need to fix spacing after you add a tag to the table
<img width="1369" alt="Screenshot 2022-11-08 at 8 47 50 AM" src="https://user-images.githubusercontent.com/103238069/200466934-07fe1e4b-077d-404b-8996-9c5af728a6e4.png">

- [ ] need to fix spacing here (top & bottom padding)
<img width="1289" alt="Screenshot 2022-11-08 at 8 52 55 AM" src="https://user-images.githubusercontent.com/103238069/200467602-eec07d10-26fb-4276-ac6d-5f501d11d968.png">

- [ ] table styling not consistent on this page
<img width="1440" alt="Screenshot 2022-11-08 at 8 54 05 AM" src="https://user-images.githubusercontent.com/103238069/200467746-f2e0fa74-f65b-45b5-b947-5c322a6fa095.png">

- [ ] Left column spacing and width not consistent
<img width="320" alt="Screenshot 2022-11-08 at 9 04 42 AM" src="https://user-images.githubusercontent.com/103238069/200469116-a47379fe-e62b-422f-a9eb-4a8d43eb2d6a.png">
<img width="292" alt="Screenshot 2022-11-08 at 9 04 25 AM" src="https://user-images.githubusercontent.com/103238069/200469066-e7d85a78-1ceb-406c-b325-159937b26fe9.png">

**Comment by chirag-madlani** [comment]
[ ] Glossary tree icons are missaligned
<img width="493" alt="Screenshot 2022-11-09 at 8 02 09 PM" src="https://user-images.githubusercontent.com/12962843/200857452-5306097f-ebfc-43f7-b7b5-a2c865186a0c.png">

**Comment by Sachin-chaurasiya** [comment]
Icons are not aligned.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/59080942/201581278-c24bfa12-19a3-4144-9d65-8cf109a75daf.png">

**Comment by Sachin-chaurasiya** [comment]
The dropdown icon is not aligned properly.


![Image](https://user-images.githubusercontent.com/59080942/201659739-8a56a5d4-94ca-455d-8d53-c21d0d081cf4.png)

**Comment by pmbrull** [comment]
Services > Openmetadata Service

- [ ] Display name should be `OpenMetadata Service`, not `Openmetadata`
- [ ] JWT Token should be masked
- [ ] I'd disable the `Test Connection` in the `Connection` tab, at least for now

![image](https://user-images.githubusercontent.com/35870520/201676235-c72c48ce-bfe2-45b7-b5b7-c2a5a2d811ca.png)

**Comment by mohityadav766** [comment]
> Services > Openmetadata Service
> 
> - [ ] Display name should be `OpenMetadata Service`, not `Openmetadata` -> I guess we'll need to change this in the backend @mohityadav766. Ping us when you do this change as we'll need to update ingestion code
> - [ ] JWT Token should be masked
> - [ ] I'd disable the `Test Connection` in the `Connection` tab, at least for now. There is no implementation behind that
> 
> ![image](https://user-images.githubusercontent.com/35870520/201676235-c72c48ce-bfe2-45b7-b5b7-c2a5a2d811ca.png)
> 

@pmbrull , corrected the first one should take changes on the ui

**Comment by Ashish8689** [comment]
- [ ]  Search bar get small while redirecting to any 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66266464/201848202-4dfb4c8f-ab1c-4998-aea5-12f6509590e1.png">

- [ ] Horizontal scrollbar is visible on every page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66266464/201848645-dec5e324-f6c6-4a0e-95ae-6e02678f2d58.png">

**Comment by devyani-kaushik** [comment]
Change matadata Icon on settings page to svg shared below
![metadata](https://user-images.githubusercontent.com/103238069/202143613-cf2a2329-b09e-4582-8747-39e5c2864d96.svg)
![image](https://user-images.githubusercontent.com/103238069/202143710-9ef65277-ab60-46b8-95d7-7e1e060a8bb6.png)

**Comment by Sachin-chaurasiya** [comment]
- [ ] On UI replace `entity` with `data asset` and `entities` with `data assests`

**Comment by devyani-kaushik** [comment]
- [ ] bottom padding of the filters can be reduced a little and should we fix the position ?

<img width="1440" alt="Screenshot 2022-11-17 at 10 59 14 AM" src="https://user-images.githubusercontent.com/103238069/202363965-fd890bea-3796-48fc-8f48-bd3ba12f5ca4.png">

**Comment by ulixius9** [comment]
- [ ] parentheses missing even though available in api response in `dataTypeDisplay`

![image](https://user-images.githubusercontent.com/39544459/202433803-af29ff3d-50b0-4aef-8b98-75cc06bbb632.png)

**Comment by Sachin-chaurasiya** [comment]
The dropdown icon is not aligned.
![image](https://user-images.githubusercontent.com/59080942/202622234-b3476407-a7fd-4a8a-a45c-ab2fe34524de.png)

**Comment by Sachin-chaurasiya** [comment]
@Ashish8689 Disable the test connection button for `matadata service` on the edit connection page.
![image](https://user-images.githubusercontent.com/59080942/202623265-e7360f7e-e8de-4b36-b61d-5f5265df09a6.png)

**Comment by Sachin-chaurasiya** [comment]
@aniketkatkar97 , Replace this icon with the below one
![image](https://user-images.githubusercontent.com/59080942/202627753-55aac1d5-0290-4599-987a-0c4ea4cb4135.png)

![image](https://user-images.githubusercontent.com/59080942/202627576-1b0190cb-5d80-4d4d-9970-a66f13c1ba69.png)

**Comment by harshach** [comment]
- [ ] font sizes and arrows look out of place compare to others we use 
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/38649/202643547-129a856f-0113-4dfd-a660-7cef3800aba5.png">
- [ ] @chirag-madlani we shouldn't be showing the list view and DAG view in the same page. It should be switchable button that can switch from list to DAG view. Default should be switch view
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/38649/202643638-d7ee22f5-dd3a-47b6-9f44-0224340fd1a7.png">

**Comment by harshach** [comment]
- [ ] profiler metrics looks too big cc @devyani-kaushik 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/38649/202643908-e06636a4-1c7e-46bb-9283-f9414c13561d.png">

**Comment by aniketkatkar97** [comment]
- [ ] Fix time for the Firefox browser
<img width="859" alt="Screenshot 2022-11-18 at 3 59 18 PM" src="https://user-images.githubusercontent.com/51777795/202681330-e927886b-71c4-42dd-a94c-2abad786be6c.png">

**Comment by devyani-kaushik** [comment]
- [ ] Update the label styling to >> color: #6B7280 and font-weight: 500
<img width="1380" alt="Screenshot 2022-11-22 at 11 58 09 AM" src="https://user-images.githubusercontent.com/103238069/203240815-0ac4821d-5450-4856-9a7b-d374ae7a8ee6.png">

- [ ] Use the announcement icon in list for both the places.
<img width="286" alt="Screenshot 2022-11-22 at 11 56 49 AM" src="https://user-images.githubusercontent.com/103238069/203241542-0083cf95-e2d9-461a-9ac6-f0cb1c73dc81.png">

**Comment by ShaileshParmar11** [comment]
the description is miss aligned  -> @ShaileshParmar11 
![image](https://user-images.githubusercontent.com/71748675/203302203-db6bc345-0010-4af3-a6bf-a9b374131e1c.png)
