### ISSUE TITLE
URL breaks within collapsing description

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#8549]
**Affected module**
UI

**Describe the bug**
There is a character limit on the description. If there is a URL that subject to that charater limit, clicking on the URL will result in an error as it looks up the URL up to the point of the charater limit. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/102999683/200074641-14127c8e-8171-4be8-bf13-ea5937a370a3.png)

![image](https://user-images.githubusercontent.com/102999683/200074683-92138611-f941-4267-8e45-33f6b7a7a154.png)

Actual description
![image](https://user-images.githubusercontent.com/102999683/200074923-72cec2fb-61f1-4893-8c9f-f9dbfc972a7c.png)

**Expected behavior**
Despite only showing a certain number of characters, clicking on the URL should direct me without issues.

**Version:**
 - OS: Windows, Chrome
 - OpenMetadata version: 12.3

**Comment by trillhaa** [comment]
This is still broken on Table Summary page!

**Comment by trillhaa** [comment]
I'm on version 0.13.1 and still have this issue with anything markdown related

![image](https://user-images.githubusercontent.com/102999683/214132535-d7edcbbd-17bf-4845-b3ae-927b6ea60e41.png)

**Comment by harshach** [comment]
@trillhaa can you give more details on this.  URL breaking issue is fixed. But in the example above we are cutting markdown is that the issue?

**Comment by trillhaa** [comment]
yes

**Comment by Sachin-chaurasiya** [comment]
Hello @trillhaa , thanks for filing the issue,it has been fixed in `1.0.0`.

https://github.com/open-metadata/OpenMetadata/assets/59080942/a88480fc-88fb-4ffe-8532-6c9a3436b5d9
