### ISSUE TITLE
Metadata ingestion filter descriptions in UI

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8551]
based on https://openmetadata.slack.com/archives/C02B6955S4S/p1667789613202249

Let's add some more information and examples about filter patterns

**Comment by Sachin-chaurasiya** [comment]
Related to #6981

**Comment by pmbrull** [comment]
Now that you ping this, the doc might be useful https://docs.open-metadata.org/connectors/ingestion/workflows/metadata/filter-patterns/database, we have a bunch of examples we can add. Thanks
