### ISSUE TITLE
Using DBT's catalog.json and manifest.json from GCS location results in TypeError

### ISSUE THREAD

**Issue by bmy-ashampoo** [open-metadata/OpenMetadata#8559]
**Affected module**
Ingestion Framework

**Describe the bug**
When trying to create a lineage ingestion from DBT files stored in Google Cloud Storage the following error occurs:
![image](https://user-images.githubusercontent.com/92018608/200304353-3ef913b2-c040-4c5d-b59a-3ae488dc16c9.png)

The files are found successfully but there seems to be a problem when initializing `dbt_owner`

**To Reproduce**

Upload manifest and catalog.json to GCS. Use a service account that has the proper credentials and give the respective path to the files in the ingestion setup.

**Expected behavior**
Lineage and DBT view works as expected when using local manifest.json and catalog.json

**Version:**
 - OS: Windows 11
 - Python version: 3.9
 - OpenMetadata version: 12.1
 - OpenMetadata Ingestion package version: 12.1

**Additional context**
-

**Comment by OnkarVO7** [comment]
**Update on the issue:**
This error is occuring due to missing `analysis` nodes in the catalog files.

**Solution:**
The analysis node can be filtered out from since it is not relevant and only used for testing purpose.
https://docs.getdbt.com/docs/build/analyses
