### ISSUE TITLE
Parsing failure of strange database schema names

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#8561]
See https://openmetadata.slack.com/archives/C02B6955S4S/p1667822489808209 for reference with more details.

I am having a strange problem with DBT which is causing downstream issues with OM:

1. the upstream DBT issue is described here https://getdbt.slack.com/archives/C2JRRQDTL/p1667567610232459 and TLDR is: 1) I want to have DBT automatically generate a schema like: specific_user.schema_name.table_name as the DBT user does not have create schema permission 2) DBT with create schema permission is creating the very strange schema of:

```
-- non privileged normal user
    specific_user
```

Yes, including the spaces and newline.

Upstream DBT details:

generate schema name

```
{% macro generate_schema_name(custom_schema_name, node) -%}
  {%- set default_schema = target.schema -%}
  {%- if target.schema == 'mwf' -%}
  -- scheduled production run
    {%- if custom_schema_name is none -%}

            {{ default_schema }}

        {%- else -%}

            {{ custom_schema_name | trim }}

        {%- endif -%}

  {%- else -%}
  -- non privileged normal user
    {%- if custom_schema_name is none -%}

            {{ target.schema }}

        {%- else -%}

            {{ target.schema }}

        {%- endif -%}
  {%- endif -%}
{%- endmacro %}

```

**Comment by pmbrull** [comment]
Hi @geoHeil I see that the thread was solved in the `dbt` community by cleaning up the jinja templates.

Is this still relevant on the OM side?

**Comment by geoHeil** [comment]
solved
