### ISSUE TITLE
Gather IngestionPipeline metrics to CloudWatch

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8573]
- https://github.com/open-metadata/OpenMetadata/issues/8571
- https://github.com/open-metadata/OpenMetadata/issues/8572

**Comment by ssandy83** [comment]
Hi @pmbrull 
I would be interested in contributing to this. Let me know if I can do so.

**Comment by pmbrull** [comment]
Hi apologies @ssandy83 missed the message. We're already on it.

There are a few issues we opened for the community that are marked as `hacktoberfest` or `good-first-issue`. You can find them here https://github.com/open-metadata/OpenMetadata/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue%2Chacktoberfest

Thanks
