### ISSUE TITLE
Document JWT validation & GKE setup troubleshooting

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8602]
based on the convo on https://openmetadata.slack.com/archives/C02B6955S4S/p1667902805246339

**Comment by harshach** [comment]
@MilanBariya @Vj-L any update on the docs?

**Comment by pmbrull** [comment]
there's an open PR that was just reviewed https://github.com/open-metadata/OpenMetadata/pull/8678 we'll close it tomorrow
