### ISSUE TITLE
Description and Tags are non editable on Charts and Tasks table

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#864]
When trying to add/edit description and tags for particular tasks or charts, then it gives 403 
These actions are allowed for Pipelines and Dashboards

If add/edit of descriptions and tags is not allowed on task and chart level, it should be read only fields

**Comment by harshach** [comment]
@darth-coder00 I am able to add and edit the description , tags for charts. Closing this as resolved.
