### ISSUE TITLE
Backend : Getting different case for entity type in data assets charts and web charts

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#8650]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**

In the data insight report, we are getting a different case for entity type in the data assets chart and web charts.
For Example In data assets, we are getting `DatabaseSchema` as an entity type but in web analytics `Databaseschema` is an entity type.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

Entity Type should be the same in all the charts.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@TeddyCr can we make these consistent?

**Comment by TeddyCr** [comment]
Fixed in #9239
