### ISSUE TITLE
Test case finished with success but the dag contains error

### ISSUE THREAD

**Issue by marcelotsarmento** [open-metadata/OpenMetadata#8675]
**Affected module**
Test case ingestion

**Describe the bug**
I have a column test case using test type columnValueLengthsToBetween. i didn't fill the min value. I ran this test case and pipeline finished with success. But in the Airlofw dag log, there is an error.

**To Reproduce**
Create test case using test type columnValueLengthsToBetween and don't fill min value.

Screenshots or steps to reproduce
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/108694447/201347256-fa08de7d-b7fe-4378-8e64-7ea4385efc1d.png">

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/108694447/201347323-ac164c87-87cf-42f0-9d6d-d59802e0ea4a.png">

**Expected behavior**
Test case finished with aborted.
Created some handling when min or max value missing.
Change this text info is is not possible leave min or max empty
![image](https://user-images.githubusercontent.com/108694447/201348620-480f7777-d252-48a0-8116-dfeb37123679.png)

**Version:**
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: 0.12.2

**Comment by harshach** [comment]
@TeddyCr @ayush-shah can you look into this?

**Comment by ayush-shah** [comment]
I will handle this in my upcoming PR for test suites
