### ISSUE TITLE
Lineage feature request: Add the ability to collapse sub-graphs

### ISSUE THREAD

**Issue by stevenspadotto** [open-metadata/OpenMetadata#8680]
**Is your feature request related to a problem? Please describe.**

Once a node in the Lineage graph is expanded to show it's sub-graph, there is no way to collapse that sub-graph after.

Below it a screenshot of what it looks like to expand a node. There is currently no ability to collapse it once expanded.

![image](https://user-images.githubusercontent.com/97744515/201380927-1e7e9251-0fe6-41c0-bd2b-ef22c871b5f0.png)

**Describe the solution you'd like**

Add the ability to collapse the sub-graphs of expanded nodes in the Lineage graph.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by harshach** [comment]
@ShaileshParmar11 can we handle this for 0.13?

**Comment by harshach** [comment]
@karanh37 lets add a way to shrink the expanded node
