### ISSUE TITLE
A feature to filter the Lineage graph by tags assigned to assets would be helpful, especially when the Lineage graph displays hundreds or thousands of nodes.

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#8705]
A feature to filter the Lineage graph by tags assigned to assets would be helpful, especially when the Lineage graph displays hundreds or thousands of nodes.

_Originally posted by @stevenspadotto in https://github.com/open-metadata/OpenMetadata/issues/8521#issuecomment-1307691648_

**Comment by sureshms** [comment]
Duplicate of #8685
