### ISSUE TITLE
Custom workflow solution instead of airflow

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#8717]
**Is your feature request related to a problem? Please describe.**
When a user is having a custom workflow solution instead of airflow, the user should be able to create the ingestion pipeline without airflow config also user should be able to view ingestion pipelines from UI instead of fail message when airflow is not available.

![image](https://user-images.githubusercontent.com/39544459/201671965-81c13d21-72b0-4b56-aad0-b43c72ecd0e7.png)

**Comment by harshach** [comment]
@chirag-madlani @ulixius9 any updates?

**Comment by pmbrull** [comment]
we can push this to 0.13.1

**Comment by harshach** [comment]
@chirag-madlani @ulixius9 @pmbrull planing for 0.13.1? or move to 1.0

**Comment by pmbrull** [comment]
moving it out, might take a bit of thinking
