### ISSUE TITLE
Enable KpiResourceTest , 

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#8721]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend 

**Describe the bug**
Currently the KpiResourceTest are disable as they need handling one to one mapping

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 any update on this one?

**Comment by mohityadav766** [comment]
Complete
