### ISSUE TITLE
[UI] Add support for renaming tags

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#8732]
**Feature**
#8438 

**Describe the task**
Add support for renaming tags. See related backend issue #8730 

@harshach we should do this in 0.13.1

**Comment by ShaileshParmar11** [comment]
Renaming tag category is done by #9154

**Comment by ShaileshParmar11** [comment]
blocked by #9168

**Comment by Ashish8689** [comment]
@devyani-kaushik  New design is needed to show the edit functionality for the tags name.
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/66266464/227148544-e4214cc3-032a-4559-8a86-04d727191be9.png">
@harshach @chirag-madlani  Do we also need to have a separate display name input for the user to enter?

**Comment by devyani-kaushik** [comment]
Edit should work like how it works for "Add new tag"
cc: @Ashish8689 @chirag-madlani 
<img width="852" alt="Screenshot 2023-03-23 at 2 35 44 PM" src="https://user-images.githubusercontent.com/103238069/227154610-ac9679e6-5d04-4b8d-a90e-332c4e9cc169.png">
