### ISSUE TITLE
No auto-generated password when the "Automatic Generate" option is selected by default

### ISSUE THREAD

**Issue by stevenspadotto** [open-metadata/OpenMetadata#8736]
**Affected module**

UI

**Describe the bug**

The `/create-user` page does not auto-generate a password when the "Automatic Generate" option is selected by default. Also, it may need to be renamed to "Automatically Generate". In order to see an auto-generated password, I need to click the refresh arrows icon at least once.

**To Reproduce**

<img width="697" alt="Screenshot 2022-11-14 at 4 17 54 PM" src="https://user-images.githubusercontent.com/97744515/201767443-b5524911-626c-4c9a-bebe-9746631a5f55.png">

<img width="700" alt="Screenshot 2022-11-14 at 4 14 56 PM" src="https://user-images.githubusercontent.com/97744515/201767444-d1bc1ef6-8546-44ee-84b1-3cc3adbd7ef6.png">

**Expected behavior**

When the "Automatically Generate" option is selected, or when it is active by default, such as when the create user form first loads, show an auto-generated password in the text box instead of an empty text box.

**Version:**
 - OS: OS X
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani this UX is confusing as the user expects the password to appear. Instead, the user needs to click on the refresh button next to it. 

Lets generate the password by default here.

**Comment by chirag-madlani** [comment]
@Ashish8689 please update this as mentioned
