### ISSUE TITLE
Mouse clicks on the dark overlay outside of a Modal does not automatically close the Modal

### ISSUE THREAD

**Issue by stevenspadotto** [open-metadata/OpenMetadata#8737]
**Affected module**

UI

**Describe the bug**

Clicking with the mouse on the dark overlay outside of a Modal does not automatically close the Modal. This type of behavior is quite common on front-ends and users may expect it, however it does not work. The user must explicitly click on the "Cancel" button. 

**To Reproduce**

<img width="1346" alt="Screenshot 2022-11-14 at 4 11 10 PM" src="https://user-images.githubusercontent.com/97744515/201769482-74814474-6098-4db3-b91a-2e2732f2dfa9.png">

**Expected behavior**

Clicking with the mouse on the dark overlay outside of a Modal automatically closes the Modal.

**Version:**
 - OS: OS X
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@chirag-madlani need to handle this for 0.13.1

**Comment by chirag-madlani** [comment]
@aniketkatkar97 Please check this

**Comment by aniketkatkar97** [comment]
Checking
