### ISSUE TITLE
Teams link from the main page links to the wrong page

### ISSUE THREAD

**Issue by stevenspadotto** [open-metadata/OpenMetadata#8741]
**Affected module**

UI

**Describe the bug**

On the main page, Teams count is `1` but then when I click on Teams, it takes me to a page where the count is `0`.

It seems that the Teams link from the main page links to `/settings/members/teams/Organization` instead of linking to
`/settings/members/teams`.

**To Reproduce**

<img width="401" alt="Screenshot 2022-11-14 at 5 30 32 PM" src="https://user-images.githubusercontent.com/97744515/201785559-8acf074f-b529-4804-b083-981acd149465.png">

<img width="756" alt="Screenshot 2022-11-14 at 5 30 39 PM" src="https://user-images.githubusercontent.com/97744515/201785569-bb4f97d2-865d-42da-b7fa-799422832ab1.png">

**Expected behavior**

Teams link from the main page should link to `/settings/members/teams`.

**Version:**
 - OS: OS X
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
Hi, @stevenspadotto Thanks for reporting.
We will be having `/settings/members/teams/Organization` as our home path for the Teams page as all teams must fall under Organization
I did remove the older path and UI in this [PR](https://github.com/open-metadata/OpenMetadata/pull/8767).
Should be fixed with 0.13.0

cc: @harshach

**Comment by stevenspadotto** [comment]
@chirag-madlani I see. Ok, thanks. However, on the main page, I see Teams count as `1`, but when I click on the Teams link from there, it takes me to the Organization page where I see Teams count as `0`. This discrepancy with the count can appear to be confusing.

**Comment by harshach** [comment]
@chirag-madlani it looks like we are not showing the total count of all teams but instead showing the count at the top level example
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/38649/201979988-101d34f8-2b68-467d-8f54-d4196313f4d6.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/38649/201980022-16ed0ef4-2788-4dbf-baaa-185acc7fec45.png">

**Comment by chirag-madlani** [comment]
> @chirag-madlani I see. Ok, thanks. However, on the main page, I see Teams count as `1`, but when I click on the Teams link from there, it takes me to the Organization page where I see Teams count as `0`. This discrepancy with the count can appear to be confusing.

Yes, there's a mismatch. Will fix it in 0.13.0
Thanks for pointing it out @stevenspadotto @harshach

**Comment by chirag-madlani** [comment]
Need to fix count issue

**Comment by chirag-madlani** [comment]
Fixed in 13.0
