### ISSUE TITLE
Search Suggest API endpoint does not return user. Returns ElasticSearch search_phase_execution_exception

### ISSUE THREAD

**Issue by stevenspadotto** [open-metadata/OpenMetadata#8742]
**Affected module**

API, UI

**Describe the bug**

When I try to conduct a suggest search via the API using `/api/v1/search/suggest?q=admin&index=user_search_index`, I am getting:

```
{
	"responseMessage": "An exception with message [Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]] was thrown while processing request."
}
```

If I add `team_search_index` to the request `/api/v1/search/suggest?q=admin&index=user_search_index,team_search_index`, then I get:

```
{
	"suggest": {
		"metadata-suggest": [
			{
				"text": "admin",
				"offset": 0,
				"length": 5,
				"options": [
				]
			}
		]
	}
}
```

There are no results. I would expect there to be 1 result for the admin user that I see in the UI.

**To Reproduce**

Try an API call to `/api/v1/search/suggest?q=admin&index=user_search_index`

Try an API call to `/api/v1/search/suggest?q=admin&index=user_search_index,team_search_index`

**Expected behavior**

Admin user is returned by the API call.

**Version:**
 - OS: OS X
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
Issue is fixed in 0.13.0 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/38649/204958584-ad476138-d594-4af0-b512-41c5c7e08941.png">
