### ISSUE TITLE
Allow EmailNotification Configuration from global settings

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#8753]
**Is your feature request related to a problem? Please describe.**
#4674 : Currently the backend support email notifcations for Test case result and Task Assignment.

**Describe the solution you'd like**
Add a settings page in the Global settings from where the notifications can be enabled or disabled

**Describe alternatives you've considered**

**Additional context**

**Comment by chirag-madlani** [comment]
Implemented in 0.13.1
