### ISSUE TITLE
UI : Data Insight report improvements

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#8754]
Ticket to track feedback for data insight report page.

**Comment by TeddyCr** [comment]
- [ ] The value we get from completedDescriptionFraction  are fraction and not percentage (we need to convert them to percentage e.g. completedDescriptionFraction * 100). The percentage for table is also not showing for some reasons
^ same thing for the KPI value
- [ ] Regarding the "Latest" value for percentage you cannot sum completedDescriptionFraction  value. Here you'll need to sum all completedDescription  from the latest timestamp and divide it by the sum of entityCount  from the latest timestamp
- [ ] Regarding the KPI, I think we should drop the time
- [ ] number of days left (vs the target date) should be displayed for KPI

![Screenshot 2022-11-15 at 9 18 52 AM](https://user-images.githubusercontent.com/13626425/201868601-37ba6745-6ae2-4cf8-a496-36420c5f4bf0.png)
![Screenshot 2022-11-15 at 8 58 43 AM](https://user-images.githubusercontent.com/13626425/201868604-76908014-d65d-4321-818b-af49f4210647.png)
![Screenshot 2022-11-15 at 8 58 15 AM](https://user-images.githubusercontent.com/13626425/201868606-f3768a99-8668-4b73-8a69-42458cd9c27c.png)

**Comment by TeddyCr** [comment]
- [ ] UI has a horizontal scroll bar
- [ ] data insight vertical scroll bar does not match the page height

Uploading Screen Recording 2022-11-16 at 9.00.23 AM.mov…

**Comment by TeddyCr** [comment]
- [ ] When we set the KPI, we have 2 ->  PERCENTAGE and NUMBER

If it is PERCENTAGE the value in the targetDefinition  should be a decimal number (i.e. 0.76) -- ONLY for percentage. Right now we send a whole number

**Comment by mohityadav766** [comment]
![image](https://user-images.githubusercontent.com/105265192/202174316-7d0f1a02-a43f-4c7a-baa3-f5f3eed2ecf8.png)
The table percentage is not showing

**Comment by mohityadav766** [comment]
@TeddyCr I might be missing something over here , but we do take into account the column description as per the discussion we had in the call, but as you can see in the image the fraction for table = 0.611 is 11/18 (entityWithDescription/TotalTableEntity) although in actual majority of the table in my case had table level as well as column level desciption
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/105265192/202174886-82835135-2603-48ef-bf9b-ff324c797200.png">

**Comment by TeddyCr** [comment]
> @TeddyCr I might be missing something over here , but we do take into account the column description as per the discussion we had in the call, but as you can see in the image the fraction for table = 0.611 is 11/18 (entityWithDescription/TotalTableEntity) although in actual majority of the table in my case had table level as well as column level desciption
> <img alt="image" width="1310" src="https://user-images.githubusercontent.com/105265192/202174886-82835135-2603-48ef-bf9b-ff324c797200.png">

@mohityadav766 are you able to confirm if the numbers match you see in the UI (i.e. 11 and 18)?
