### ISSUE TITLE
"Unable to parse response body" is displayed in UI upon elasticsearch re-indexing

### ISSUE THREAD

**Issue by k-popov** [open-metadata/OpenMetadata#8772]
**Affected module**
backend

**Describe the bug**
Running Elasticsearch re-Index from UI https://<openmetadata-host>/settings/eventPublishers/elasticsearch causes error `Batch Failed Completely. Reason : Unable to parse response body for Response`  with `java.lang.NullPointerException` later in trace. Nevertheless re-indexing goes fine on Elasticsearch side

Elasticsearch version 8.3.2 shows:
```
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
```
While OpenMetadata is using 7.13.4: https://github.com/open-metadata/OpenMetadata/blob/7b9fecc369e50c2d0b9c5e14de3d70b6b6b1efa2/pom.xml#L110 so probably a dependency version update would solve the issue.

**To Reproduce**

- set up OpenMetadata 0.12.2
- configure Elasticsearch version 8.3.2
- attempt to run re-index from UI: https://<openmetadata-host>/settings/eventPublishers/elasticsearch

**Expected behavior**
Re-indexing completes fine and success is reported in UI

**Version:**
 - OS: Alpine Linux 3.15 (official OpenMetadata Docker image: `openmetadata/server:0.12.2`)
 - Python version: None
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: None

**Additional context**

**Comment by harshach** [comment]
@k-popov we do not support 7.17 version and beyond due to the elasticsearch library breaking the compatibility. We need to work on this to move onto OpenSearch client

**Comment by harshach** [comment]
Have other duplicated tickets , closing this one out
