### ISSUE TITLE
Support Iceberg Partition

### ISSUE THREAD

**Issue by TheFu527** [open-metadata/OpenMetadata#8798]
**Is your feature request related to a problem? Please describe.**

I would like to ask how the tablePartition in OM supports Iceberg's Partition? For Iceberg, there is no case where an interval corresponds to multiple columns. On the contrary, a table corresponds to multiple intervals, such as hour, day and identity, etc.

**Describe the solution you'd like**

Support Iceberg Partition. Maybe like this:

```json
{
  "tablePartitions": [
    {
      "column": "",
      "interval": "",
      "invervalType": ""
    },
    {
      "column": "",
      "interval": "",
      "invervalType": ""
    }
  ]
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by TeddyCr** [comment]
hey @TheFu527 thank you for opening an issue. Could you elaborate on what you are looking for regarding this? Thank you.
