### ISSUE TITLE
datalake metadata connector: parsing CSV

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#8854]
**Is your feature request related to a problem? Please describe.**
Can't capture CSV file schema

**Describe the solution you'd like**
I would like to be able to load csv files from via datalake metadata connector and provider delimiter information so they can be parsed, and I would have the correct schema. However, should be per file name pattern, so I don't have thousands of schemas for the same information.

**Describe alternatives you've considered**
Loading CSV to table and then loading the metadata

**Additional context**
![image](https://user-images.githubusercontent.com/26750060/202496338-c736c675-1d15-4824-a7ca-c21a87102624.png)

**Comment by harshach** [comment]
@ulixius9 lets add manifest file for datalake connector as wel

**Comment by pmbrull** [comment]
Storage Services and manifest allow to pass the required delimiter for CSV and specify the directory where we can pick up the files
