### ISSUE TITLE
Get more metadata from looker

### ISSUE THREAD

**Issue by pjain-branch** [open-metadata/OpenMetadata#8858]
**Is your feature request related to a problem? Please describe.**
I successfully integrated with looker today. I could see that openmetadata ingests the dashboard names and charts. But not a lot of metadata is ingested. We will have to manually add a lot of the metdata like descriptions, tags, etc. With 245 dashboards and charts it is quite a manual task. 

**Describe the solution you'd like**
If there are descriptions, tags, etc added to dashboards in looker, then it would be helpful if openmetadata extracts that information from looker and displays it on openmetadata.

**Describe alternatives you've considered**
The only other alternative is to add the descriptions manually on openmetadata which is quite a big task. 

**Additional context**

**Comment by pmbrull** [comment]
from https://openmetadata.slack.com/archives/C02B6955S4S/p1668715434924659

**Comment by harshach** [comment]
@pmbrull can you take this up? and prioritize for this week

**Comment by pmbrull** [comment]
thanks @pjain-branch for the discussion. We'll handle:
- ingesting text tiles as descriptions if the Dashboard Details > Description is not informed. As describing dashboards in text tiles might not be a conventional use, we'll prioritize the actual details. In any case, ingesting that information should help on the dashboard discoverability.
- For the lineage ingestion we'll add more flexibility around the code to help match the `sql_table_name` from looker with the OM name of the assets.
- Re the links in OM pointing to Looker, the port added in the hostPort is what is giving us issues. AFAIK other looker users don't need to pass the port for the ingestion to work (although your tests without the port failed). we can further discuss the root of this
Thanks
