### ISSUE TITLE
Ingestion : Data Insight pipeline is not running at scheduled time

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#8859]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
I have created and deployed the data insight pipeline and scheduled it to run at `10:35` every day, but time passed and still pipeline is in a `queued` state.
![image](https://user-images.githubusercontent.com/59080942/202624176-b9ca1938-03e7-4259-bd6d-4517f911b2ed.png)

**To Reproduce**

- Go to metadata service 
- Create and deploy the data insight pipeline
- Now wait for the scheduled time

**Expected behavior**
The pipeline should be in a running state once the time is met.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by pmbrull** [comment]
was this related to the UTC timestamp being used? Can we close this?

**Comment by Sachin-chaurasiya** [comment]
Yes, closing this.
