### ISSUE TITLE
datamodel codegen creates different names

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8866]
for models that are defined +1 depending if the classes are generated on macos or linux.

- [x] Prepare a reproducible example
- [x] Check with datamodel devs
- [x] Fix
- [ ] Update dependency

**Comment by pmbrull** [comment]
Created an issue for the datamodel codegen https://github.com/koxudaxi/datamodel-code-generator/issues/961

**Comment by pmbrull** [comment]
PR has been merged with the fix at https://github.com/koxudaxi/datamodel-code-generator/pull/973

**Comment by pmbrull** [comment]
As always, thanks @koxudaxi for the fixes

**Comment by pmbrull** [comment]
hi @koxudaxi :D

Testing out the changes noticed the following changes when upgrading from `0.13.4` to `0.15.0`:

- We have the following JSON Schema definition of [connectionOptions](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/connectionBasicType.json#L7). It is a wrapper class to add arbitrary properties.
- On `0.13.4`, the conversion returned

```python
class ConnectionOptions(BaseModel):
    pass

    class Config:
        extra = Extra.allow
```

- On `0.15.0` we get:

```python
class ConnectionOptions(BaseModel):
    __root__: Optional[Dict[str, str]] = None
```

Just wanted to double-check with you if this change was expected and that will be the behavior going forward for `additionalProperties`. If so, I'll apply the necessary changes in the codebase. We already had to validate that the property existed so it won't be a big change on our end.

Thanks 🙏

**Comment by koxudaxi** [comment]
@pmbrull 
Yes, I expect the behavior.
This change comes from the issue.
https://github.com/koxudaxi/datamodel-code-generator/issues/696
The change affect only `type: "object"`
If `additionalProperties` is `true` then
```python
 class Config:
        extra = Extra.allow
```

when `additionalProperties` has a specific type.
```python
    __root__: Optional[Dict[str, `specific type`]] = None
```
The behavior had applied to other object types such a `oneOf` before `0.15.0`. 

I think the change is an improvement of `additionalProperties` detection. 
So, I don't add any CLI option for the changes.

But, I don't want to create any blockers and pain points for existing users.
What do you think about it?

**Comment by pmbrull** [comment]
thanks for explaining @koxudaxi, IMO it makes sense. In the end, it feels a bit healthier to have `prop.__root__.get("key")` than `prop.getattr("key")`, which ends up being a bit more hacky.

Just wanted to confirm before applying the changes. We'll start the migration then.

Thanks!
