### ISSUE TITLE
Quick switch between two filter on search/explore page shows incorrect data

### ISSUE THREAD

**Issue by dion-gdn** [open-metadata/OpenMetadata#8873]
**Affected module**
Bug found in the frontend/UI

**Describe the bug**
On the explore/search page there's a bunch of filters on the left side. This filter works great but when I try to quickly switch between two filters something weird happened. Somehow the data shown in the search result is not the currently selected filter, but rather it shows the data from the previously selected filter.

**To Reproduce**
1. Visit explore page
2. Click on any filter
3. Quickly unselect the filter and click on another
4. Check the results

Here's my screen recording of me doing the steps:
https://drive.google.com/file/d/17cAgZxeB4NyNwyBphLMgwtvxKqsTHT3K/view?usp=share_link

**Expected behavior**
The search result should be show data filtered by the currently selected filter.

**Version:**
 - OS: Windows
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version:

**Additional context**
The video I recorded was me testing this bug in the OpenMetadata sandbox site.

**Comment by sureshms** [comment]
@dion-gdn, the filtering mechanism is overhauled with release 1.1. If you still see this issue in 1.1, please reopen the issue.
