### ISSUE TITLE
Misleading WARNING on logs with 404 errors

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#8885]
**Issue**
Every time the `ometa_client` fails to do a call to the OM server, it logs a `WARNING` for any 404 error on the logs, regardless of whether it can be expected. These logs add misleading ideas about what could happen internally in the code. 
**Solution**
We have to log these errors depending on if they are expected.

**Comment by pmbrull** [comment]
@nahuelverdugo how would you differentiate between "expected" vs. "not expected" returns?

**Comment by nahuelverdugo** [comment]
@pmbrull, I would add an extra parameter to not raise an exception or mute the logging when doing the call to the method.
