### ISSUE TITLE
User with "DenyAll" policy is able to see tables in search results

### ISSUE THREAD

**Issue by k-popov** [open-metadata/OpenMetadata#8892]
**Affected module**
UI/backend

**Describe the bug**
A user (set up with Custom OIDC) is only the member or Organization team. This organization team has the only role "EverybodyRole" assigned. The mentioned role has only one policy attached consisting of two rules:
![image](https://user-images.githubusercontent.com/1763358/202760501-62fa35ac-4918-46a6-aec6-3e2c369ddd95.png)
The rules (if my understanding is correct) forbid everything except viewing own teams membership.

I expect this user to not be able to get any information from OpenMetadata but in fact the user is able to see the list of tables in `https://<open-metadata-host>/explore/tables/` (see screenshot). Thus no detailed information on table may be seen. To the list of tables and list of services is also sensitive information.
![image](https://user-images.githubusercontent.com/1763358/202761381-f71f16cf-5407-4a4e-bceb-fd820ec4616e.png)

**To Reproduce**

See description above.
The same effect is seen when attaching policy directly to team, not through role.

**Expected behavior**
The user only belonging to organization with policies set up like described and can see no information until added to some team.

**Version:**
 - OS: Linux, official OpenMetadata docker image
 - Python version: None
 - OpenMetadata version: 12.1
 - OpenMetadata Ingestion package version: None

**Additional context**
The database has its ownership set up to a group that the described user does not belong to.

**Comment by k-popov** [comment]
@harshach thank you for quick reply! Do I understand that right that **for now** this is expected behavior: show **list** of tables in "explore" view regardless of role permission? You mentioned search but I didn't use search when reproducing the situation.

**Comment by sureshms** [comment]
@k-popov the explore page shows data assets powered by search. Are you able to click the data asset shown during explore and view them?

**Comment by k-popov** [comment]
@sureshms As expected upon clicking on table name I see "You do not have the necessary permissions to view this data" for the user with no permissions. So the only issue I see is this "list" of tables which may potentially disclose some sensitive information.

**Comment by sureshms** [comment]
@k-popov building a search filter is quite tricky from the policies. Something that we are working on. Would you be okay to provide in addition to access control, a search filter in a rule to filter the results out?

**Comment by k-popov** [comment]
Not sure I understand the proposal. Include search filter into rules set for policies? Would it be whitelist or blacklist? The original issue was with "show all" search query.

**Comment by brucewu** [comment]
i have the save problem，and i don't kown how to fix it

**Comment by moravcik94** [comment]
still open ? when will be this released ?

**Comment by jan-pieter** [comment]
Ran into this as well. For us it would work to have Search or Explore as a Resource so we can deny this entirely. Some background: we have configured SSO with Azure and over 1M people with an account and we only want to provide access to a subset of users. Current setup is to deny everything until we have added them to a team.

**Comment by harshach** [comment]
resolved in 1.6.0
