### ISSUE TITLE
UI: Ability to select user as a type for custom attributes

### ISSUE THREAD

**Issue by NithinKumaraNT** [open-metadata/OpenMetadata#8898]
**Is your feature request related to a problem? Please describe.**
As a source of contact for an entity, an owner is necessary but not sufficient. Sometimes it is necessary to add multiple users as contacts.

**Describe the solution you'd like**
Currently the custom attributes accept the types - Integer, String and Markdown. It would be nice to have a **User** type (OM users). This feature provides the flexibility to model different contact points for an asset.

**Describe alternatives you've considered**

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
This will require backend changes to support `user` entity metadata types.

**Comment by mhornst** [comment]
+1 on this request

And linked to my related request [[#11287](https://github.com/open-metadata/OpenMetadata/issues/11287)], would there be a possibility to include an additional `date` type for custom properites.
