### ISSUE TITLE
Configure Slack notification / Webhooks at team level

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#8935]
**Is your feature request related to a problem? Please describe.**
Today, slack notifications / webhooks cannot be configured based on the table's ownership. All notifications are sent to a single endpoint URL, irrespective of the table's owner. This means we cannot notify the right owners of any tasks (but only everyone, and then nobody  would read it because they are not targeted).

**Describe the solution you'd like**
Configure Slack notification / webhooks at the team level. Essentially, provide an option on the configuration page for Integrations for which team this configuration should apply to. Then I can create a webhook for team X to their respective slack channel X and another one for team Y to their respective slack channel Y. Notifications for tables owned by team X will only be seen by team X, etc..

**Describe alternatives you've considered**
none

**Comment by mohityadav766** [comment]
hi @trillhaa , this can be achieved using the new alert mechanism, in the filters you can select matchAnyOwner (can be team or a user), and the alerts will be delivered on ChangeEvents to those selected users or members of team only .
Marking this as complete , please let us know if something is needed

**Comment by trillhaa** [comment]
Thanks, we‘ll check it out as we are importing 0.13.1 in out Prod instance now.

Regards,
Martin
