### ISSUE TITLE
Admin can create bot user with existing user names 

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8941]
How to reproduce it?
Create a bot with the same username as an existing user.

**Comment by pmbrull** [comment]
This also becomes an error if an existing email gets used. Users will essentially get logged out of their real account without the chance to get this fixed

**Comment by pmbrull** [comment]
checked in 1.0, we cannot create the bots anymore. LGTM

![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/e5a7be6b-365c-4467-916a-1a8853078b70)
