### ISSUE TITLE
table API return data with an important lag

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8951]
### Context
When querying the OM database, data are returned quite fast (~0.03 seconds) (about 5K rows in the table entity table), though when sending requests through the API we observe important lag (data are returned in about 10 seconds). 

After initial investigation the team suspects the lag to be from the following lines https://github.com/open-metadata/OpenMetadata/blob/5a163c739c573198a4a87e5c85d4edd1f1f18b5d/openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java#L343-L346

**Comment by nahuelverdugo** [comment]
This is the distribution of queries when calling the endpoint `/api/v1/tables?limit=1000&fields=name`:

![image](https://user-images.githubusercontent.com/11074908/203359094-1ec88dbf-5bf5-43cc-9b76-d4aec1c608ce.png)

The total amount of time is *8219* ms. I hope it helps to clarify the issue.

**Comment by sureshms** [comment]
@nahuelverdugo what are columns 0, 1, 2, etc? And you are only asking for fields=name?

**Comment by sureshms** [comment]
@nahuelverdugo, can you please create an index for toId and toEntity and see if some of these times change?

**Comment by nahuelverdugo** [comment]
> what are columns 0, 1, 2, etc? And you are only asking for fields=name?

They are the time in ms that the query takes, and each value in the row is the number of queries. For example, for the call to `DatabaseDAO.findById` from 2002 queries, 1812 took 1 ms. I did it only with the name field because it is the most straightforward call. 

> can you please create an index for toId and toEntity and see if some of these times change?

Sure, I will update once I do the test.

**Comment by nahuelverdugo** [comment]
@sureshms I have tested it.
The index `to_index` is used instead of the new one.
![image](https://user-images.githubusercontent.com/11074908/203580745-f960e9c7-73c5-4220-8203-e67eeab1eab4.png)
Anyway, after deleting it and tried with:
```
ALTER TABLE entity_relationship ADD INDEX to_entity_index (toId, toEntity);
```
The request time is the same.

**Comment by TeddyCr** [comment]
Seems like
- https://github.com/open-metadata/OpenMetadata/pull/9041
- https://github.com/open-metadata/OpenMetadata/pull/9043/files
may have fixed the issue. Able to return `https://sandbox-beta.open-metadata.org/api/v1/tables?limit=1000` this request in 10 seconds, and this `https://sandbox-beta.open-metadata.org/api/v1/tables?limit=2000` in 20 seconds (seems like response time grows linearly to the number of tables returned).

@mohityadav766, @nahuelverdugo are you able to confirm on your end.

---
cc @harshach

**Comment by sureshms** [comment]
This issue was reported long back since we have not heard of this issue in the recent releases, closing this. We can open another issue if this happens again.
