### ISSUE TITLE
Non scheduled runs appear as Queued

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8955]
Deploy an Ingestion Pipeline without a schedule (schedule None) and the state will appear as Queued by default

**Comment by ulixius9** [comment]
@chirag-madlani this was fixed right?

**Comment by chirag-madlani** [comment]
It's fixed

**Comment by ulixius9** [comment]
okay, but on latest main I still see queued status 

![image](https://user-images.githubusercontent.com/39544459/203483350-2e575883-319d-45c8-ae0f-097bce3e68d9.png)

can your please double check?
