### ISSUE TITLE
Backend: Error thrown while deleting the created Amundsen service.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#8970]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
While trying to delete a created Amundsen service, an error is thrown 
`An exception with message [HTTP 404 Not Found] was thrown while processing request.`

Request URL: `/api/v1/metadataServices/{id}?hardDelete=true&recursive=true`
Response: `An exception with message [HTTP 404 Not Found] was thrown while processing request.`

**To Reproduce**

Screenshots or steps to reproduce
<img width="1440" alt="Screenshot 2022-11-23 at 3 26 09 PM" src="https://user-images.githubusercontent.com/51777795/203519535-97b73e79-f57a-4e99-8749-988f7b6f0e10.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97, you are sending an API request to http://localhost:8585/api/v1/metadataServices/d7c26a76-47de-4e56-ac65-984ef0844de4?hardDelete=true&recursive=true
it should be 
http://localhost:8585/**api/v1/services/metadataServices**/d7c26a76-47de-4e56-ac65-984ef0844de4?hardDelete=true&recursive=true

**Comment by harshach** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/38649/204372746-226bf360-2b96-4dd4-9712-e4f4ffb9a441.png">
API works fine

**Comment by harshach** [comment]
why are we highlighting these as required 
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/38649/204372918-c46a7c77-6c62-45da-8373-3123f3436d0b.png">
when there are default values already cc @chirag-madlani 

added required fields here @ulixius9 , do we need model class required?
https://github.com/open-metadata/OpenMetadata/pull/9039

**Comment by ulixius9** [comment]
@harshach I believe we are not using the modelClass, I'll remove it and push changes to your pr after testing 🙏
