### ISSUE TITLE
Explore Superset auth SSO

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#8973]
**Is your feature request related to a problem? Please describe.**
Explore Superset auth SSO

support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1669110816450539

**Comment by pmbrull** [comment]
@ulixius9 did you reach out to Superset slack asking about this? If it's not supported by the API we might need to keep it blocked until they bring support or any suggested workaround from their community.

Thanks

**Comment by harshach** [comment]
@ulixius9 can you please give an update on this?

**Comment by ulixius9** [comment]
@harshach @pmbrull I've asked this question in superset community but didn't got any response I've the question once again will see if I get any response now!

**Comment by harshach** [comment]
@ulixius9 can you paste the support conversation in here as they expire
