### ISSUE TITLE
Lineage for Dashboard Service

### ISSUE THREAD

**Issue by pjain-branch** [open-metadata/OpenMetadata#8988]
**Affected module**
Ingestion framework for Dashboards ( Looker and Tableau ) - specially lineage

**Describe the bug**
I am ingesting only one dashboard in these logs to make it easier to go through logs. Logs are attached in this slack thread https://openmetadata.slack.com/archives/C02B6955S4S/p1668715434924659. Config used 
```source:
  type: looker
  serviceName: test_looker
  serviceConnection:
    config:
      type: Looker
      username: 
      password: 
      hostPort: http://hostport/
  sourceConfig:
    config:
      type: DashboardMetadata
      dbServiceName: hive
      dashboardFilterPattern:
        includes:
          - 785
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: "http://{{OPENMETADATA_HOST}}/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: ""
```

**To Reproduce**

<img width="1640" alt="Screen Shot 2022-11-18 at 4 16 32 PM" src="https://user-images.githubusercontent.com/56648967/203638444-9e4d2e5e-acb8-4336-9360-01dd1e0ab81f.png">

**Expected behavior**
According to @pmbrull ```How those tables appear in OM should not matter as long as they are present in the service configured during the metadata ingest```
I have the hive database service in OM and have the source tables that feed the looker and tableau dashboards but I do not see the lineage getting created. 

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.4
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[tableau,looker]==0.11.4.0`

**Additional context**

**Comment by pmbrull** [comment]
Thanks for validating the lineage changes @pjain-branch. Closing this as part of https://github.com/open-metadata/OpenMetadata/pull/9124
