### ISSUE TITLE
Index fully qualified table name for search

### ISSUE THREAD

**Issue by hansencc** [open-metadata/OpenMetadata#8991]
**Is your feature request related to a problem? Please describe.**
I often want to search for tables based on a combination of database and table name, but doing so yields no results since they are indexed separately.

**Describe the solution you'd like**
Index the fully qualified table name.

**Describe alternatives you've considered**
An alternative is to tell people to search for the table only and scroll through results, but that seems suboptimal.

**Additional context**
We use BigQuery, where tables take on the form `projectId.datasetId.tableId`. It's not uncommon for a table ID to exist in multiple datasets and projects.

**Comment by harshach** [comment]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/38649/203663877-a46e5214-d121-4667-bf5a-6e46e9e397ff.png">
It works today but need to include service_name as part of FQN

**Comment by hansencc** [comment]
Great! Eventually it would be preference to not have to include the service name, since that can be very long to type.
