### ISSUE TITLE
UI: Improve the App Analytics and Data Assets tab

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#8996]
**Affected module**
UI

**Describe the bug**
The tab here is almost non-visible to new users. I usually scroll around without even noticing that page is there.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/38649/203703633-de380f57-b5c1-40b6-b4de-a910786ee288.png">

@devyani-kaushik we should create a left-hand menu and add Reports underneath that we should have 
<img width="215" alt="image" src="https://user-images.githubusercontent.com/38649/203703759-c504f81d-e8e8-443a-962b-2caa84c94091.png">

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
- [ ] Add check boxes for multiselect dropdown for better UX
- [ ] 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/59080942/204014031-7d8f2665-5f77-4d04-bfea-bcb08d2290db.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Tier chart should have another bar showing how many entities are non-tiered i.e no tier associated with them
![image](https://user-images.githubusercontent.com/59080942/204742672-cec80ae3-bcda-47c8-a705-2fa9c3b602ac.png)

- [ ] Here we should how many are owned vs non-owned
![image](https://user-images.githubusercontent.com/59080942/204742779-223432a7-352e-4548-84d7-20a3cbf7337b.png)

- [ ] For the Tier chart we should % instead of count like others

- [ ] Here we should add the links to entities similar to the search card style
![image](https://user-images.githubusercontent.com/59080942/204742882-aca6c2bc-1349-413c-aedc-020982d670eb.png)

- [ ] It should be the Organization display name Data Health Summary. If the user changes team the Organization display name should be changed to Team Name Data health summary
![image](https://user-images.githubusercontent.com/59080942/204742982-ec0da497-a353-4db8-9726-83e08410a7a8.png)

**Comment by harshach** [comment]
- [ ] Once the KPI is defined, there is now way to edit it . It needs a edit button in actions
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/38649/204881421-a91320b2-8838-4e6f-9ac7-be323153f626.png"> 

- [ ] We are asking users enter name and display name. This is redudant and confusing for the users. We should just ask for displayName and generate a unique name out of it 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/38649/204881616-ccc9098b-7327-4705-9e94-cb2655ee244b.png"> 

- [ ] Do we need Name to be unique here, I think the chart they are creating against should be the unique anyway. ie. you cannot create two KPIs for the same metric, description target can only one KPI. If so just take the Name as display name
- [ ] Calendar we show to select start and end date doesn't look right to me .  We do not need hour , mins, secs granularity for KPIs. Usually KPIs start and end on a day we can alway default start hours:mins as 00:00 and end hours:mins as 24:00 cc @TeddyCr @mohityadav766 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/38649/204882014-6b85de45-f747-47ae-b063-d9f27474e99e.png">

**Comment by harshach** [comment]
- [ ] Please use the camelcase where appropriate for labels. @devyani-kaushik need a guidance and consistency in creation of labels 
<img width="782" alt="image" src="https://user-images.githubusercontent.com/38649/204882355-6babeeaf-e581-469b-a91b-78936d7fffcc.png">

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=16580%3A21713&t=B3Gs7LE3LYlKtTut-1
@Sachin-chaurasiya

**Comment by TeddyCr** [comment]
![Screenshot 2022-12-01 at 11 24 18 AM](https://user-images.githubusercontent.com/13626425/205028753-b9cfe991-a1b0-4030-824c-5e762123bc19.png)
- [ ] Users should only be able to create 1 data insight pipeline

![Screenshot 2022-12-01 at 11 23 39 AM](https://user-images.githubusercontent.com/13626425/205028758-c4880e7f-aed5-474c-a2c2-6f49f346810c.png)
- [ ] clicking on the legend of a specific entity should filter out only for the selected (i.e. clicked) entity

![Screenshot 2022-12-01 at 11 26 26 AM](https://user-images.githubusercontent.com/13626425/205029071-4806405e-cfa4-477a-960b-31cf1517ecc5.png)
- [ ] y-axis label should be removed for stacked percentage graphs

**Comment by TeddyCr** [comment]
- [ ] logs cannot be retrieve (hangigng)
<img width="1492" alt="Screenshot 2022-12-01 at 6 52 59 PM" src="https://user-images.githubusercontent.com/13626425/205125205-25ae5112-82c9-4ab1-ada6-992490776c44.png">

**Comment by TeddyCr** [comment]
- [ ] stacked bar charts should be converted to line graphs 

![Screenshot 2022-12-07 at 7 51 45 AM](https://user-images.githubusercontent.com/13626425/206108969-187a1112-4095-42ab-9e11-daf9fffc7629.png)

**Comment by TeddyCr** [comment]
- [ ] Relative comparison needs to be added for "Total Data Assets", "Percentage of Data Assets with Description",  "Percentage of Data Assets with Owners", "Total Data Assets by Tier", "Page views by data assets", and "Daily active users on the platform" -- We need to take the total of the max timestamp and the total of the min timestamp and do a relative comparison calcul -> `(max - min)/min`
- [ ] "Daily active users on the platform" needs to have a "Latest" similar to other graphs
- [ ] Remove the grid pattern in the back
