### ISSUE TITLE
DBT parser support macro-bsed DBT projects for column-level lineage

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9011]
https://openmetadata.slack.com/archives/C02B6955S4S/p1669367705377959?thread_ts=1669221137.283589&cid=C02B6955S4S

Neither compiled_sql or compiled_code is present only macro_sql

**Comment by harshach** [comment]
@geoHeil what version of DBT are you using?

**Comment by geoHeil** [comment]
1.3.1

**Comment by pmbrull** [comment]
done in https://github.com/reata/sqllineage/pull/397
