### ISSUE TITLE
Support parsing of postgres type daterange

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9019]
The basic metadata import of a postgres database imports `daterange` type as `varchar(1)`

**Comment by harshach** [comment]
@NiharDoshi99 any update on this?

**Comment by OnkarVO7** [comment]
Yes looking into this

**Comment by OnkarVO7** [comment]
Hi @geoHeil closing this issue as it is fixed with the `1.0` release

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/28966081/234579369-71eb1ab3-5dd3-4e6b-bb91-53eab6b0d366.png">
