### ISSUE TITLE
UI: Settings sidebar should always visiable

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#9020]
**Affected module**
Settings side bar only available on the landing when the user clicks add or browse through to another page this side navigation disappears

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by sureshms** [comment]
No longer relevant form release 1.1.
