### ISSUE TITLE
Configure server with TLS when deploying on Kubernetes 

### ISSUE THREAD

**Issue by revit13** [open-metadata/OpenMetadata#9022]
I would like to enable OM server with SSL. To do that I need to configure [conf/openmetadata.yaml](https://docs.open-metadata.org/deployment/security/enable-ssl/openmetadata-server#configure-openmetadatayaml) following the instructions [in the site](http://docs.open-metadata.org/deployment/security/enable-ssl/openmetadata-server#enable-ssl-at-the-openmetadata-server). My server is deployed in Kubernetes so I wonder if there is a way to set `applicationConnectors` values using helm chart values.yaml upon the deployment of the server? if not, what is the proper way of setting  applicationConnectors  in the OM server deployed in Kubernetes? 
Also, it might be easier if there would be a possibility to save TLS certificates in a Kubernetes secret which will be mounted to OM deployment container similar to what is done in [vault server](https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L191)

**Comment by harshach** [comment]
@akash-jain-10 lets prioritize this one for 0.13.1 release

**Comment by akash-jain-10** [comment]
Hello @harshach . This is a feature request primarily on helm charts end. We have prioritize as well as tasked out the feature request into 2 parts will be tracking the same [here](https://github.com/open-metadata/openmetadata-helm-charts/issues/96). Closing this issue here as duplicate.
