### ISSUE TITLE
Unable to set AWS Config for kinesis connector

### ISSUE THREAD

**Issue by dfdf** [open-metadata/OpenMetadata#9029]
**Affected module**
Ingestion Framework

**Describe the bug**
We are unable to create an AWS Connection when trying to create a new kinesis service.
There is no available option at the Connection Details screen, which causes an error when trying to deploy the ingestion job to airflow.

**To Reproduce**
Following the process to create a connection for kinesis:

Settings -> Messaging -> Add New Service -> Kinesis -> Next (Configure Service) -> Connection Details.

On the connection details page, there is no available configuration.

Message: "No Connection Configs available."

![image](https://user-images.githubusercontent.com/4792360/204294884-c7608a8e-0cc5-4a93-963a-9dfecd5b968a.png)

![image](https://user-images.githubusercontent.com/4792360/204295881-7aa81a41-23dd-4ca2-8678-a6a36e7e76a9.png)

**Expected behavior**
At Connection details, should have a form to configure AWS connection details.

**Version:**
 - OS: [e.g. iOS]. MacOS
 - Python version: Default version from openmetadata docker
 - OpenMetadata version: [e.g. 0.8] 0.13
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] openmetadata-ingestion==0.13.0.1

**Additional context**

**Comment by dN0Mad** [comment]
Same issue applies for ML Model services (e.g. Sagemaker) and Dashboard services (e.g. Quicksight):

![image](https://user-images.githubusercontent.com/87071419/204300596-5f9515a0-3683-4f5e-9e59-20ce57570c7c.png)

**Version**:
- OS: [e.g. iOS]. Ubuntu 22.04.1 LTS
- Python version: Default version from openmetadata docker
-OpenMetadata version: [e.g. 0.8] 0.13
- OpenMetadata Ingestion package version: openmetadata-ingestion==0.13.0.1

**Comment by harshach** [comment]
@chirag-madlani @pmbrull these should be supported in the latest release right

**Comment by pmbrull** [comment]
Hi folks, please pull the openmetadata/server:0.13.0 image again.

We did an in place release with the fixes 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/35870520/205911571-54dd41e9-96d3-4a24-a472-3848a521a317.png">

Thanks
