### ISSUE TITLE
sync tier from DBT to OM

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9031]
https://openmetadata.slack.com/archives/C02B6955S4S/p1669581800070729

```
meta:

      model_maturity: bronze/silver/gold
```

Please add support to sync model_maturity to the OM terms of maturity. Perhaps bronze/silver/gold is okay. But I think OM has finer-grained terms. Perhaps these could also be fine.

**Comment by pmbrull** [comment]
Hi @geoHeil , these settings `model_maturity: bronze/silver/gold` are something custom on your end or is it standard in dbt?

**Comment by geoHeil** [comment]
the bronze/silver/gold thing is more the Databricks way of identifying their tables - and not DBT specific.
But it would be great if arbitrary tags would sync over

**Comment by pmbrull** [comment]
I think that we already support bringing tags from dbt based on the `tags` field https://docs.open-metadata.org/v1.0.0/connectors/ingestion/workflows/dbt/ingest-dbt-tags

Would that work?

**Comment by geoHeil** [comment]
Would these also be applicable for the OM tiers somehow? (and not land in the tags field)

**Comment by pmbrull** [comment]
Not sure this would work with tiering atm, since these tags fall inside a dbt-specific category. If `model_maturity` is not something directly related to dbt, we could come up with our own spec to handle tiering

**Comment by geoHeil** [comment]
At least in the link you sent it looks like if tags are pre-created in OM they should not be prefixed with DBTTAGS.* so it might work?

But I think it would be nice if DBT could map to all OM basic fields including tier.

**Comment by pmbrull** [comment]
cc @OnkarVO7 any thoughts on this?

**Comment by geoHeil** [comment]
@OnkarVO7 do you have any update here on how to sync DBT to OMs native tier field?

**Comment by OnkarVO7** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/15833
