### ISSUE TITLE
Code styling, rename Kpi -> KPI everywhere. 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#9037]
**Affected module**
backend, UI

**Describe the bug**
For abbreviations such as KPI or SMTP we should use the capital letters not do CamelCase.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Sachin-chaurasiya @mohityadav766 please take care of it

**Comment by Sachin-chaurasiya** [comment]
This is taken care of on the UI side.

**Comment by harshach** [comment]
@mohityadav766 can you complete this?

**Comment by mohityadav766** [comment]
> @mohityadav766 can you complete this?

Raise PR for the same
