### ISSUE TITLE
Arithmetic overflow error while running profiler for MSSQL

### ISSUE THREAD

**Issue by eeshan-deshpande** [open-metadata/OpenMetadata#9058]
**Affected module**
/OpenMetadata/tree/main/ingestion/src/metadata/utils)/sql_queries.py

**Describe the bug**
We are getting Error "Arithmetic overflow error converting expression to data type int." for MSSQL profiling.
In statement MSSQL_SQL_STATEMENT  "DATEADD(MS, s.total_elapsed_time, s.last_execution_time) end_time," is the line of code for this cause. This happening in case the s.total_elapsed_time is bigint/very large.

**To Reproduce**
1: Run the MSSQL_SQL_STATEMENT  statement on database where s.total_elapsed_time is very large.

**Expected behavior**
The statement should not error out.

**Version:**
 Docker deploy - pip3 install --upgrade "openmetadata-ingestion[docker]"

**Additional context**
This can be solved by using minute by dividing s.total_elapsed_time by 60000

**Comment by eeshan-deshpande** [comment]
@TeddyCr , I am running on latest version available on pypi  When we have long running queries which take a day or two,  "s.total_elapsed_time" is a very high number,ideally bigInt where as DATEADD function requires its second parameter to be int which causes this issue. For now I have changed to code to below and it is working -  
DATEADD(minute, s.total_elapsed_time/60000, s.last_execution_time) end_time,

**Comment by TeddyCr** [comment]
@eeshan-deshpande where did you change this `DATEADD(minute, s.total_elapsed_time/60000, s.last_execution_time) end_time,`?

**Comment by eeshan-deshpande** [comment]
@TeddyCr I have changed in file /OpenMetadata/tree/main/ingestion/src/metadata/utils)/sql_queries.py under section "MSSQL_SQL_STATEMENT " in my local repository to test whether this solves the issue.

**Comment by TeddyCr** [comment]
I see, this query is not used in the profiler. It is related to the usage. cc @ulixius9

**Comment by eeshan-deshpande** [comment]
Also , any idea which all queries are used in Lineage, I was facing same issue while running lineage on MSSQL.

**Comment by ulixius9** [comment]
Yes @eeshan-deshpande, we run [this](https://github.com/open-metadata/OpenMetadata/blob/d193df352add14a94c8d335d57b0bd018ddd3a32/ingestion/src/metadata/utils/sql_queries.py#L351) query for both usage & lineage which might be causing the issue 

> dividing s.total_elapsed_time by 60000

@eeshan-deshpande we can try out this solution, Thanks 🙇‍♂️

**Comment by eeshan-deshpande** [comment]
@ulixius9 Will it be possible to add below statements to MSSQL part just above select to ensure no other breakages?
SET ARITHABORT OFF
SET ANSI_WARNINGS OFF

Since this is select statement and these params are only set for that particular query instance , we should be good.

**Comment by ulixius9** [comment]
@eeshan-deshpande can you please confirm if dividing s.total_elapsed_time by 1000 works for you? 

In my case it threw an arithmetic error when total_elapsed_time was more than 15 days and if I divide it by 1000 and do addition in sec then it works for total_elapsed_time upto 5 years (i.e 157788000000 milisec approx)which I believe should be more than enough
