### ISSUE TITLE
Prep Ingestion Pipeline JSON update tool

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9060]
to handle the breaking changes we added in 0.13.0.

E.g.,

```
Broken DAG: [/airflow-dags/dags/Snowflake-analytics_usage.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/workflow_factory.py", line 66, in create
    airflow_pipeline = IngestionPipeline(**workflow_config_dict)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for IngestionPipeline
openMetadataServerConnection -> supportsMetadataExtraction
  extra fields not permitted (type=value_error.extra)
```

If any other change comes for 0.13.1, add that as well and update the docs.

**Comment by TeddyCr** [comment]
@pmbrull with the redeploy button on the UI side, do we still need this?

**Comment by pmbrull** [comment]
oh that's a good point 🤔 Depending on how many pipelines users have this could still be useful. If it's not hard to update I'd get it done and document both approaches and let people choose what they prefer. This could also help us on SaaS

**Comment by pmbrull** [comment]
@TeddyCr actually what we can do for 1.0 is to have an endpoint on the backend side to `Redeploy All`. That should give us the same outcome
