### ISSUE TITLE
Storage Service connector

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9064]
Thanks to everyone participating in the discussion https://github.com/open-metadata/OpenMetadata/discussions/8124.

Let's start writing down the initial ideas. Note that this is a WIP, and we'll keep curating the points as the design discussions happen.

## Context

What is happening today:

- Ingesting individual files as separated `Table`s. This does not properly represent partitioned data. We are not applying any difference between "structured" files (representing a table) vs. unstructured files (any unorganized bucket/path).
- The path is used as the `Table` name, which can sometimes be longer than the current `name` limitations https://github.com/open-metadata/OpenMetadata/issues/6889
- We are not surfacing `Location` entities. Currently, only the Glue connector uses `Location` data as the EXTERNAL TABLE path information. 

## Initial Goals & Thoughts

- We ingest Buckets as `Location` entities and add the Paths inside them. EXTERNAL TABLEs are then linked to a Path within a Bucket.
- We do not ingest all tables' files as separate Entities. While configuring an input sample size, we check if the files within a directory all follow the same schema. If so, the full directory will be represented as a single `Table`.
    - We will build a set of examples of supported inputs/outputs: what happens if all files follow the same schema, if all files minus one have the same schema, etc.
- Figure out how to scope the ingestion of structured and unstructured prefixes. Should we allow a list of paths?
- For data without implicit schema (JSON, CSV, TSV), define rules for either fetching the schema file or requiring an input field for pointing to the schema location.
- Develop a "Structured Datalake" connector that will group and analyze schemas to ingest Tables + a `StorageService` connector that will ingest each individual file as files.

### Figuring out the JSON Schema

The first solution was to have a top-level entity `Bucket` or `Folder` containing the internal paths as the second Entity. The issue here is how to easy the discovery at each different level (`level1/level2/level3`). Also, this gives special treatment to buckets, which might be useful for some scenarios, but what happens if we have a generic `datalake` bucket and the important pieces we want to explore are the layers (e.g., RAW, L1, L2,..., or `DEV`, `SIT`, `PROD`,...)?

The second (and final) approach has been to prepare a more generic structure with a single `Container` Entity, that can have other Containers as children. This allows to give the same importance regardless of the level of the path. You can find the definition of the JSON Schema [here](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/data/container.json).

- NOTE: Why the name `Container`? Because `Bucket` can seem cloud-specific and only refer to the top-level asset. We need a term that can refer to a real AWS Bucket, an internal blob in there, and even a Dropbox path when/if we include that in the future.

### Structured vs. Unstructured

The second difficulty is figuring out how to handle structured paths i.e., those that uniquely identify to a real "table", with a specific schema, format, etc. vs. the unstructured paths, where we just have free format files such as mp4, jpg, pkl,...

To handle this, our JSON Schema has an optional property `dataModel`, where the schema will be informed in the cases where it applies.

### Building the Connector -> Crawling solution

Once the APIs are in place and the JSON Schema is defined, the difficulty comes when automating the metadata discovery. Every request has an associated cost and we cannot easily know what to expect when ingesting a bucket. Is the data going to be structured? How many files should we sample for us to flag a directory as structured or not? How many paths should we try to discover? Are all of them going to be important for the user? And many more.

Given the complexity and the cost of false positives during the crawling, or just by the fact of ingesting metadata that might not even be useful, we've made the decision to direct the ingestion based on a `manifest.json` file to be loaded when configuring the service.

### Manifest JSON

In the manifest, we'll specify in which paths we have the data we want to surface, if it's partitioned or not, and the format. This will help the ingestion workflow go directly where the bread and butter is.

By default, we'll try to ingest all the buckets (top-level containers), and keep high-level information about them:
- number of objects
- size of the bucket
But we're not going to jump into its contents to avoid any errors and edge cases.

---

## Roadmap

We'll be taking this in two steps:
1. Prepare the Object Storage APIs, Connector and UI
2. Deprecate the current Storage Service for the new Object Storage. We'll keep the name `Service Storage`. We will also deprecate the current `Location` Entity. Instead, we'll add a `type` to the properties of the containers which will specify if it's an `object`, `path`, etc. depending on the source.

**Comment by harshach** [comment]
- We should have an implementation that is data lake as it currently does by treating all files as Tables and another implementation of StorageServices that treats them as files
