### ISSUE TITLE
Query as a separate entity and adding snapshot of metrics at table level

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#9068]
**Feature**

### Separation of Query as another entity

Currently we are using entity_extension table to store all of the queries. Also we are storing the queries as one big payload.
One of the reasons to do this is, while adding new query against a table we check if the same query added before. The way we are doing it is , taking a checksum of the query and storing it in the one big payload when a new query comes in we load all of the queries into a hash map and lookup based on the checksum of the query.  This is approach is ok with few 100s of queries but in big orgs with lot no.of queries running this approach causing lot of penalty.

Given entity_extension is made for having more of limited content in the extension table , example usage summary, sample data( we limit at 50 rows) etc.. storing queries in entity_extension is not suitable unless we start adding columns that provides a unique column out of extension into the extension table. In case of query we can use checksum as the unique column and scan entity_extension based on that. 

However, Instead of trying to make query to fit into entity_extension model we can add query as another entity in the data model , similar to how the location is associated with a table, we can add query as another sub entity that can be associated with multiple tables. Provide pagination and all the options that comes with it. 
This will also help us build query page better with description, tags, users etc..

### Add snapshot of all the metrics for a given table

In UI we display summary of metrics at the top of panel such as row count, column count etc.. this requires backend to serve the latest result from the profile at table and column level and also query count which is now extremely expensive without the above changes.
Instead of making frequent calls to time series data of profile and getting query count we can attach at each entity "latestMetrics" field which will contain the profile , query count in case of tables. These will be updated during the new profile data being added or new query being added.

**Describe the task**

**Comment by pmbrull** [comment]
agree on the query. Will the checksum still be the name? In any case, this will also solve https://github.com/open-metadata/OpenMetadata/issues/8422. Also, should we then use EntityRef for the queries we ingest as part of views DDL and DBT models?

**Comment by ayush-shah** [comment]
Having an index similar to key lookup on the checksum and not on queries, would that work?
Unique checksum for queries
if we can have checksum on the backend side, we can directly search for that checksum first, no checksum available means no similar queries.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/40225091/204716526-88f5f111-f14e-4ec9-930a-76afeb65374a.png">

**Comment by ayush-shah** [comment]
storing queries separately in other table (ex. query_table)
having table entity reference here
We can quickly take a look at which checksums to be checked for which table


<img width="1247" alt="image" src="https://user-images.githubusercontent.com/40225091/204717413-34450323-4d54-4ef6-9410-dc0f0444d358.png">

**Comment by harshach** [comment]
@pmbrull to your question of checksums, Yes it will be the same we are already using this method to de-dup queries
