### ISSUE TITLE
Usernames are generated from email not provided username from OIDC

### ISSUE THREAD

**Issue by widders** [open-metadata/OpenMetadata#9078]
**Affected module**
UI - Login/User Creation

**Describe the bug**
When using OIDC authentication, during the user creation and login the username is extracted from the email address not the preferred_username field, even if this is specified first in the JWT claims.
If a users username and email address don't match, they see the user signup page, OMD creates a user with the wrong username from their email address, then are unable to access any table data and will be unable to login again as their username does not match the created user.

**To Reproduce**
OMD running with custom oidc authentication.
principalJWTclaim set to ["preferred_username", "email", "sub"].
New user whose's email address is not <username>@<domain>
Login with user to create a new OMD account.

e.g.
Username: jwiddicombe
Email: jon@example.com
OMD will create a user with username "jon" which will not match to "jwiddicombe" provided by OIDC.

**Expected behavior**
All elements should respect the principal JWT claim setting when determining username and not assume the email address is <username>@<domain>.

**Version:**
 - OS: docker packaged
 - Python version: docker packaged
 - OpenMetadata version: 0.12.2 - 0.13.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
I've not tested it but I'm guessing a user with no email address from oidc would cause bigger problems during the signup process. Since the JWT principal is meant to be a list of likely immutable fields suitable to identify a user, potentially email may not even be included for some setups.

**Comment by harshach** [comment]
@mohityadav766 @chirag-madlani any update on this?

**Comment by chirag-madlani** [comment]
It's fixed in 0.13.1
