### ISSUE TITLE
ElasticSearch login credentials visible in OpenMetadata Service connection infos

### ISSUE THREAD

**Issue by bmy-ashampoo** [open-metadata/OpenMetadata#9085]
**Affected module**
UI

**Describe the bug**
When viewing the OpenMetadata Service connection infos the login credentials are visible in clear text

**To Reproduce**
Settings > Services > Metadata > OpenMetadataService > Connection

**Expected behavior**
The credentials should be blurred or hidden

**Version:**
 - OpenMetadata version: 0.13

**Additional context**

**Comment by harshach** [comment]
@mohityadav766 @Sachin-chaurasiya lets not return any of the credentials back

**Comment by harshach** [comment]
Fixed in 1.0
