### ISSUE TITLE
Activity Feed Display Wrong "Day"

### ISSUE THREAD

**Issue by cbeauch** [open-metadata/OpenMetadata#9089]
**Affected module**
UI

**Describe the bug**

- User does something, somewhere 
- Activity feed says they did said thing "Yesterday" when it should say "Today" 

![Screen Shot 2022-11-30 at 4 52 38 PM](https://user-images.githubusercontent.com/46851320/204932851-3bdbd035-c09f-4033-8a7d-5058909302c6.png)

In the above screenshot, the user made the comment today at 09:41AM. 

If a day does pass, it will look like this: 

![Screen Shot 2022-11-30 at 4 49 36 PM](https://user-images.githubusercontent.com/46851320/204932542-998ad189-18ac-4424-85c3-cca027c37f28.png)

Shouldn't that be just "Tuesday" ? 

**To Reproduce**

Pull latest release docker-compose.yml
Docker compose up with default values 
Do something on the UI
View the activity feed

**Expected behavior**
Should say "Today", not "Yesterday" 

**Version:**
- image: openmetadata/server:0.13.0

**Additional context**

https://openmetadata.slack.com/archives/C02B6955S4S/p1669846780558639

**Comment by harshach** [comment]
![image](https://user-images.githubusercontent.com/38649/204934888-d3eb5764-8bf7-4953-bdcc-2b47a8e03d29.png)

threadTs to human readable

![image](https://user-images.githubusercontent.com/38649/204934929-3dddd973-8417-4801-8553-48e62e5c9e02.png)

@chirag-madlani @Sachin-chaurasiya lets add cypress tests for this.
