### ISSUE TITLE
regression in search filters

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#9108]
**Affected module**
UI

**Describe the bug**
In our previous versions, search aggregations/filters on left side are used to filter the content , each filter selection allows users to further drill down the documents.
However with 0.13.0 release we changed the filters to be post_filter which means it won't apply on the search aggregations.
Example
1. User selects snowflake as service 
![image](https://user-images.githubusercontent.com/38649/205103767-c25afb5c-976e-4132-b47d-b23153f46e22.png)
2. User still sees there are documents that are available in Tier and Tags. But they do not have any matching docs with snowflake as service 
![image](https://user-images.githubusercontent.com/38649/205103890-a43beb8e-1e3b-4678-a53b-004c79e93906.png)

We should pass this as query_filter instead of post_filter

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
- [ ] Relation between two Facet filters will be -- `AND`
- [ ] Should we persist filters across Tabs? 
- [ ] Should we override Facet Filter over Advance search & vice-versa?

**Comment by harshach** [comment]
1. yes
2. No, filters are specific to each entity , there might be some overlap, Tags, Tier but the rest will be different. An example service snowflake is a database service. They won't be any service like that in the rest of the entities
3. I don't understand. Can you explain a bit more

**Comment by Sachin-chaurasiya** [comment]
Fixed with https://github.com/open-metadata/OpenMetadata/pull/9214
