### ISSUE TITLE
Implemented tags

### ISSUE THREAD

**Issue by silviodvjr** [open-metadata/OpenMetadata#9110]
![image](https://user-images.githubusercontent.com/38475199/205056155-0cc53143-c42e-472a-9c20-ef5aa24ae118.png)

Hello,
to assign a tag to calumn is necessary to do i through the application, is there any API in OMD that i can use for this functionality?

**Comment by harshach** [comment]
@silviodvjr everything in OpenMetadata is through our REST APIs. Please look at the API documentation for more details https://sandbox.open-metadata.org/docs
