### ISSUE TITLE
Add freshness + rows inserted graphs on the UI side

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#9117]
### Context
In 0.13.1 we'll be introducing freshness metrics. This metrics will represent a timestamp and a list of operation performed with their respective timestamp and numbers of rows affected. For more details on the implementation refer to the following ticket https://github.com/open-metadata/OpenMetadata/issues/7447#issuecomment-1325408233

### Implementation
We'll need to add 3 table profile graphs:
- one graph showing the timestamp at which the operation was performed (no y-axis label)
- one graph showing the number of rows affected by the operation
- one graphe showing the number of rows over time
See wire frames below for more details.

![image](https://user-images.githubusercontent.com/13626425/205262005-a68c5a37-b2d5-40d1-8200-a1919da3cbc1.png)

**Comment by TeddyCr** [comment]
@devyani-kaushik the initial idea would be to add a "Table Profile table" on the "Profiler and Data Quality" tab. Wdyt?

**Comment by harshach** [comment]
@pmbrull @TeddyCr shall we follow the same styling that we are going to use for data insights with side bar to list the reports instead of tabs.

**Comment by harshach** [comment]
leaving this here for reference 
![image](https://user-images.githubusercontent.com/38649/205336384-d605abd2-bffb-47e3-881d-cbfdb2cc2ccb.png)
cc @sureshms

**Comment by TeddyCr** [comment]
@harshach I'll defer to @devyani-kaushik here as she will probably have a more informed opinion.

**Comment by ShaileshParmar11** [comment]
Blocked on design  cc @devyani-kaushik
