### ISSUE TITLE
The system-level flag for the system-generated tag Tier comes as user

### ISSUE THREAD

**Issue by Ashish8689** [open-metadata/OpenMetadata#9127]
**Affected module**
backend

**Describe the bug**
The system-level flag for the system-generated tag `Tier` comes as `user` 

**To Reproduce**

<img width="738" alt="image" src="https://user-images.githubusercontent.com/66266464/205306490-09a33e7f-e03f-49dd-846d-9cc3ac834dd8.png">

**Expected behavior**
For system generated tags, flag should be `system`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@Ashish8689 this cannot be reproducible with the latest main. Make sure you re-created your DB or migrated it
http://localhost:8585/api/v1/tags/Tier?fields=usageCount
<img width="744" alt="image" src="https://user-images.githubusercontent.com/38649/205749181-0b62d3da-426b-4f20-b5c6-1d9b54c29c6c.png">
