### ISSUE TITLE
UI: Delete button not visible for connection options and connection arguments

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#9137]
**Affected module**
UI

![image](https://user-images.githubusercontent.com/39544459/205544246-95047b5e-afc8-4b21-85eb-b302e7a34874.png)

Delete button is not visible for connection options and connection arguments, it's there if we click on it but just not visible

**Comment by harshach** [comment]
@chirag-madlani lets get rid off this newKey / newValue

**Comment by chirag-madlani** [comment]
> @chirag-madlani lets get rid off this newKey / newValue

@harshach We are following up with the community [here](https://github.com/rjsf-team/react-jsonschema-form/issues/2672) and our internal issue is tracked [here](https://github.com/open-metadata/OpenMetadata/issues/4786)
However I have invested sometime before to see if I could remove it via some hack but no luck so far, I am awaiting from the community response now
