### ISSUE TITLE
[GITHUB ACTIONS] Fix and update warnings for workflow files to use the latest stable versions of Actions Steps

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#9141]
Currently Github Actions Worflow uses actions steps which were built from nodejs12. As per Github, 

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the actions to use Node.js 16.

Update all the actions to use newer versions that are built on nodejs16 in the .github/worflows/*.yml files.

**Comment by dhruvinmaniar123** [comment]
I would like to take this task and work upon.

**Comment by akash-jain-10** [comment]
Thanks @dhruvinmaniar123 . Assigned this issue to you.
