### ISSUE TITLE
Postgres Foreign Table 

### ISSUE THREAD

**Issue by megumiie** [open-metadata/OpenMetadata#9149]
**Is your feature request related to a problem? Please describe.**

I use Postgres Foreign Table to refer to multiple Postgres and MySQL data from one Postgres.  
But I used OpenMetadata's Postgres Connector to fetch my Postgres data, but all Foreign Tables were ignored and not fetched.

**Describe the solution you'd like**

OpenMetadata ingestion treats Foreign Table information like any other table entity.   
Also, the foreign table's information is used to generate Lineage information to another DS table that the foreign table references.  

OpenMetadata will ingestion foreign tables info from Postgres.  
Also, type of extracted table will 'Foreign'.

```
sample=# select relname, relnamespace, relkind, relispartition from pg_class WHERE relkind in ('f');
        relname      | relnamespace | relkind | relispartition 
---------------------+--------------+---------+----------------
person_ft_postgres1  |         2200 | f       | f
(1 rows)
```
![2022-12-05 214242](https://user-images.githubusercontent.com/8586013/205642185-b55d210d-68ed-4983-9065-03cfdb8f0fff.png)

See Postgres Foreign Tables here.  https://www.postgresql.org/docs/current/postgres-fdw.html

**Describe alternatives you've considered**

**Additional context**

**Comment by pmbrull** [comment]
We'll be basing the tests and setup around https://hub.docker.com/r/toleg/postgres_mysql_fdw

**Comment by pmbrull** [comment]
ok I can replicate this on my end. The query we're using to retrieve postgres tables does not include `relkind = 'f'` condition, so foreign tables are not being ingested.

We'll take the chance of working on this to:
1. Not use default SQLAlchemy (inspector) queries, but rather build our own on all sources
2. currently, the sources are just sending the table name and we only differentiate between `Regular` and `Views`. Other sources need to re-implement the logic to pass custom types (e.g., `External` in Athena or Glue). We'll update the information that the `get_table_names` function returns to include `table_name` and `table_type`, based on the `TableType` definition in the JSON Schema.
3. This means that each source can then easily handle which table is what. For foreign tables, we'll be returning `(table_name, Foreign)`.
4. This will also allow us to re-centralise some logic we needed to patch in other sources.

Will be handling this for 0.13.2 as it requires some further refactors.

Thank you

**Comment by sureshms** [comment]
- [ ] We should also add support for manually setting a foreign-key(s) for a table.
