### ISSUE TITLE
Custom database services are not listing in my-data page 

### ISSUE THREAD

**Issue by parthasarathy93** [open-metadata/OpenMetadata#9156]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Yes
**Describe the bug**

I tried to create a dummy custom database service, so that i can extend it to support new databases by pushing data externally, I created the custom db service successfully. but the number of services is still showing as zero. 
**To Reproduce**
I followed this documentation,
link:  https://docs.open-metadata.org/connectors/custom-connectors  and the same connectors in Openmetadata-v13, where i create a new image with the base image as openmetadata-0-13.0 ingestion. 

Screenshots or steps to reproduce

**Expected behavior**
It should show in the my-data page

**Version:**
 - OS: Mac OS
 - Python version: 3.9
<img width="1028" alt="Screen Shot 2565-12-04 at 17 13 36" src="https://user-images.githubusercontent.com/14884964/205706994-be72e5aa-cda2-4ec8-af3f-055edefb849a.png">

<img width="285" alt="Screen Shot 2565-12-04 at 17 13 43" src="https://user-images.githubusercontent.com/14884964/205706985-2d38cac2-e423-482c-8ec7-c156017dafca.png">

<img width="1680" alt="Screen Shot 2565-12-04 at 23 47 22" src="https://user-images.githubusercontent.com/14884964/205706965-1231b215-46b7-4729-b393-95364e8a7390.png">

 - OpenMetadata version: 0.13.0
 - OpenMetadata Ingestion package version: Base 0.13.0+installed dependencies 

**Additional context**

**Comment by parthasarathy93** [comment]
Please ignore the elasticsearch screenshot

**Comment by parthasarathy93** [comment]
CC: @harshach

**Comment by parthasarathy93** [comment]
Hi @harshach  can you go to <omserver>/my-data page and share the screenshot of  the services count listed 
<img width="454" alt="Screen Shot 2565-12-06 at 01 08 50" src="https://user-images.githubusercontent.com/14884964/205710482-c3ac1a2c-51a2-48b4-89fe-5aa696fe5ff1.png">

**Comment by parthasarathy93** [comment]
Hi @harshach  where you able to reproduce the issue?

**Comment by harshach** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/38649/205716994-13a7e7e8-16f7-460b-bdf9-13479791f0d2.png">
I've 10 services in my database services page and it does show 10 in home page
