### ISSUE TITLE
Add support to provide tags via API and client for database services

### ISSUE THREAD

**Issue by harph** [open-metadata/OpenMetadata#9162]
**Is your feature request related to a problem? Please describe.**
The database service API response when creating, updating, or fetching a database service includes `tags`, however, there isn't a way to set the tags via API or client.

**Describe the solution you'd like**
Add support to the API and client to take tags as part of the payload.

**Describe alternatives you've considered**
Add a generic tag-entity endpoint that can be used to tag anything in the system.

**Comment by sureshms** [comment]
This issue has been fixed by https://github.com/open-metadata/OpenMetadata/pull/9330
