### ISSUE TITLE
OpenMetadata Config - SLACK_CHAT_SLACK_URL should have default value

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#9167]
Under [conf/openmetadata.yaml](https://github.com/open-metadata/OpenMetadata/blob/main/conf/openmetadata.yaml#L263) file should have SLACK_CHAT_SLACK_URL defaulting to https://openmetadata.slack.com/ which is our open community Slack URL.

**Comment by talalio** [comment]
Hi, can i work on this ?

**Comment by akash-jain-10** [comment]
Yes!. Thanks @talalio
