### ISSUE TITLE
Backend: tags rename is not supported in new backend change

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#9168]
With the new backend change, tag category is supported for renaming but for renaming tags it is creating new tag with patch API

**Comment by sureshms** [comment]
@ShaileshParmar11, this functionality is well-tested in the backend. Can you attach the API request and response?

**Comment by ShaileshParmar11** [comment]
Hi @sureshms This issue was created before implementing the new API structure! with the new API its working fine!
