### ISSUE TITLE
[GITHUB ACTION] Prepare GH Action Job for Docker Publish of openmetadata/server to build the application and update release

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#9172]
Add a new Job in .github/workflow/docker-openmetadata-server.yml which will -
- build the application package in CI
- upload/update artifact on Github Release mapped to image tag (example - 0.13.0 image tag corresponds to Github Release tag 0.13.0-release)
- then run the current job which will build the docker image using the instruction in docker/metadata/Dockerfile (this will fetch the binary from Github Release pages which got updated by previous job step)

**Comment by dhruvinmaniar123** [comment]
I would like work on this issue.
