### ISSUE TITLE
0.13 UI feedback - Part 2

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#9184]
- [x] Not clear what the difference between Column Count and Columns is in the preview. Also when the profiler is not enabled, we should just show profiler is not enabled. ✅ 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1417689/206067444-21ffe0f8-be3c-4c1a-a61e-090b5cdb1c0e.png">
- Instead of multiple rows, this  -- @devyani-kaushik will sync with @sureshms & @harshach around this
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1417689/206067527-3d28797b-d085-47b7-b5b1-e1ffcb53bdcb.png">
might be better shown compactly as on dataset details page - 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/1417689/206067581-652fc559-d391-442a-8cd0-cb9560e17a64.png">

- [x] Font sizes and font weights are all over the place. Can we make sure we use this consistently like dataset details page?  ✅ 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1417689/206067776-fea27e62-3b5c-4310-b338-1070ea4d0dec.png">

- Include information such as primary key, not null etc. as in dataset details page in the preview. -- @aniketkatkar97  -->  [UI: Added more information for table columns in summary panel.](https://github.com/open-metadata/OpenMetadata/pull/9420)

- No need to repeat the Tier prefix and just use Tier1, Tier2...  -- @ShaileshParmar11 -> https://github.com/open-metadata/OpenMetadata/pull/9417 ✅ 
<img width="249" alt="image" src="https://user-images.githubusercontent.com/1417689/206068118-9191d64f-9308-4ba7-a963-cf65f87277c7.png">
- Not sure what 1 is in this - ✅ 
<img width="47" alt="image" src="https://user-images.githubusercontent.com/1417689/206068342-7d403a42-eddf-49ac-90f6-a6f5e60d492e.png">
- Add a column filter (example sale_id) in the search and hit clear all. The search results remain the same and the filter is not cleared. If you choose again column to filter the previous filter value is not shown. -- @aniketkatkar97 ✅ 
- The user profile has all kinds of fonts and weights. We probably can make this wider to make it look better ✅  - 
<img width="177" alt="image" src="https://user-images.githubusercontent.com/1417689/206069166-94164f54-d7e2-4b53-8b6b-af4701267d84.png">

- [ ] #9414 -> feed is generated from backend assigned to @mohityadav766 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1417689/206069554-83d3d812-b11f-431b-9044-2f3bccd35f66.png">

**Comment by sureshms** [comment]
- [ ] Can we lose the pink background for announcements?
<img width="882" alt="image" src="https://user-images.githubusercontent.com/1417689/206070239-686d2df4-b9c1-456d-92c3-d69aa19f5900.png">

**Comment by sureshms** [comment]
- [ ] Inconsistent section headers font styling as shown below. The first one feels more pleasing to my eyes at least.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1417689/206071571-d4b03ba5-3938-4968-9d18-d790aa4fe77f.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1417689/206071673-8342ddac-d94c-4d14-9dd4-1188f748dfd8.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/1417689/206071785-df71c486-082a-4d82-b691-bc2ea5a25503.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/1417689/206071886-aabefe2c-787a-40a6-9734-3a0668aa0714.png">

**Comment by sureshms** [comment]
- [ ] Can we have one consistent styling for this either '-' or ':' as separator
<img width="258" alt="image" src="https://user-images.githubusercontent.com/1417689/206072858-0ca96e83-e65c-4909-9b8b-88009f3956f9.png">

**Comment by nahuelverdugo** [comment]
- [ ] This is how the service configuration looks on my screen (2560 × 1440):
![image](https://user-images.githubusercontent.com/11074908/208149996-e8bf4127-bc89-4ec2-be06-71d89347737c.png)
but in `0.13.0` it looks like this:
![image](https://user-images.githubusercontent.com/11074908/208150085-746f9106-b3cc-4cb6-9944-92dae8a93fed.png)

- [ ] Maybe this one is not urgent, but when the description is empty there is a lot of empty space:
![image](https://user-images.githubusercontent.com/11074908/208150697-f3a0eb1f-8a03-45a8-9c9a-e3b4adf84b2c.png)
but in `0.13.0` it looks like this:
![image](https://user-images.githubusercontent.com/11074908/208150775-0da02a16-bb6d-40a3-8450-79e900efb41e.png)

**Comment by harshach** [comment]
@chirag-madlani please follow up on this ticket and close it out

**Comment by TeddyCr** [comment]
- [ ] Move "row count" graph for the profiler at the top

**Comment by ShaileshParmar11** [comment]
all the above task is completed except 3
1. https://github.com/open-metadata/OpenMetadata/issues/9431 which is moved to 1.0
2. https://github.com/open-metadata/OpenMetadata/issues/9414 -> assigned to @mohityadav766 
3. https://github.com/open-metadata/OpenMetadata/issues/9433 -> @devyani-kaushik will connect with @harshach & @sureshms
