### ISSUE TITLE
Elasticsearch index for table is not updated when we delete a tag associated with it.

### ISSUE THREAD

**Issue by learn-learn4** [open-metadata/OpenMetadata#9194]
**Affected module**
UI and Backend

**Describe the bug**
The table index on elasticsearch is not refreshed when an already added tag is deleted from tags listing.

**To Reproduce**

step 1. create a tag under any category.
step 2. attach this created tag to any table.
step 3. Go to, explore section to find out the tag attached is showing correctly against the table.
step 4. Now, permanently delete the tag from tags listing by going inside tag category section.
step 5. Go to, explore section and  search for the table name and check the tag is still not removed from the table.

**Expected behavior**
The results in explore section are getting populated from elasticsearch and as said, the table index still contains the tags array in the response.

**Version:**
- OM 0.12.0

**Additional context**
After going through code it looks like only the direct entity referenced in a request , gets their index updated on elasticsearch. the cross entity reference is not updated.

**Comment by mohityadav766** [comment]
This is fixed
