### ISSUE TITLE
Delete service internal error

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#921]
If we create a database based on a service, and then delete the service while the database is still present, the whole endpoint gets compromised, as we cannot even list the entities:

```
GET http://localhost:8585/api/v1/databases
An exception with message [null] was thrown while processing request
```

We should add a validation step in the backend that does not allow us to delete any Entity that is currently being used as an EntityReference. I am assuming that this issue can easily be replicated with any ref, such as owners.

Thanks

**Comment by sureshms** [comment]
This is no longer an issue with all the cases addressed as part of #1960
