### ISSUE TITLE
Problems creating an S3 database service on OM 0.13.0

### ISSUE THREAD

**Issue by cdoron** [open-metadata/OpenMetadata#9217]
**Affected module**
Backend

**Describe the bug**
Unable to connect to a non-AWS S3 service on OM 0.13.0. This problem did not exist in previous versions of OM.
I get the following error: https://files.slack.com/files-pri/T02BVTLN3G8-F04E8HQCEFP/image.png
This error suggests that OM ignores the value entered into Endpoint URL.

According to @TeddyCr , OpenMetadata never passes the endpoint URL when creating the client: https://github.com/open-metadata/OpenMetadata/blob/601b9cd38ae24088e68f0217f582f96f58b737d5/ingestion/src/metadata/clients/aws_client.py#L49-L69

**To Reproduce**
Try to create any `Datalake` database service pointing to an non-AWS S3 service.

**Version:**
 - OpenMetadata version: 0.13.0

**Comment by pmbrull** [comment]
Thanks for the details. This is the same issue reported at #7841 & #6682.

As this one has some more details, I'll keep this open and close the duplicates.

Thanks
