### ISSUE TITLE
 Business glossary search problem

### ISSUE THREAD

**Issue by AnnaShevchuk23** [open-metadata/OpenMetadata#9218]
**Affected module**
Yes, it impact the UI.

**Describe the bug**
Hey all. I would be happy if you help me. We have version 12 of Open Metadata installed and having trouble searching for business terms. The problem is that when you create 2 identical business terms in different glossaries and then delete one of them, the search does not return results, although one of the terms is still in the Glossary, but the search does not find it. Reindexing ElasticSearch didn't help.

**To Reproduce**
Screenshots or steps to reproduce:
I created 2 business glossaries and added 2 term crowns to them (screenshot #1). I then deleted the business glossary called Business Term 2 and searched for the term Restruct. As a result, OMD gives an error (screenshot #2).
I guess you can now try to search for the term Restruct in the search and see this problem in sandbox v13.0.
![1](https://user-images.githubusercontent.com/120117425/206486047-b525228d-bf1a-4e42-be25-dfa90e626178.png)
![2](https://user-images.githubusercontent.com/120117425/206486053-e2e3c912-54dd-46f3-94d5-ca2091d4bd5c.png)

**Expected behavior**
I expected the search to work correctly and return the desired business term.

**Version:**
 - OS: [e.g. Windows 10]
 - OpenMetadata version: [e.g. 12.0 и 13.0]

**Additional context**
-

**Comment by TeddyCr** [comment]
support link https://openmetadata.slack.com/archives/C02B6955S4S/p1670498595714649

**Comment by AnnaShevchuk23** [comment]
@harshach, 
Record video for you with error protection. I hope it helps

https://user-images.githubusercontent.com/120117425/206653529-3acb9e4d-24fe-48e9-a515-fa3aebf7621a.mp4

**Comment by harshach** [comment]
Thanks @AnnaShevchuk23 fixed the issue

https://user-images.githubusercontent.com/38649/206757470-e89464a7-008b-426f-a965-db281b23494d.mov
