### ISSUE TITLE
UI: Test Suite Bug

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#9232]
UI:
- Payload's entity link is being sent encoded while creating a test suite for table named `"test.json"` ( including the quotes ) ( Datalake connector )
![image](https://user-images.githubusercontent.com/40225091/206850457-c7d72264-46f3-4ed9-be0a-b51cdd37e7d7.png)
![image](https://user-images.githubusercontent.com/40225091/206850469-3a4c3a4c-97e9-4cc8-be5a-f938c79080a7.png)

- Table name changes to undefined when we go to `profiler & data quality tab`, click on DQ, Add Tests.
   - It also fails to fetch profile data
  
https://user-images.githubusercontent.com/40225091/206850920-b08ee7dc-a4a2-4d34-8abf-090aa1c087c0.mov

- Name in test suite's page under test cases shows half name for tables under datalake connector with quotes
<img width="975" alt="image" src="https://user-images.githubusercontent.com/40225091/206851014-7e2045a6-c0d9-4e29-9302-318716e80d02.png">
<img width="185" alt="image" src="https://user-images.githubusercontent.com/40225091/206850978-c33a96ce-458d-4b53-b08e-33ba12b663df.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/40225091/206850989-77585628-2db2-4f0a-81a0-43c6a5f9c332.png">

**Comment by harshach** [comment]
@ShaileshParmar11 can we handle this for 0.13.1? cc @chirag-madlani

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 can we handle this for 0.13.1? cc @chirag-madlani

sure @Ashish8689 Please have a look here

**Comment by ayush-shah** [comment]
@ShaileshParmar11 I have resolved the payload part (1st one)
