### ISSUE TITLE
UI Improvements for 13.1

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#9242]
- [x] "day" batch shouldn't go over the divider --> #9434 
<img width="1440" alt="Screenshot 2022-12-10 at 7 49 16 PM" src="https://user-images.githubusercontent.com/103238069/206859898-d94d2deb-422f-49d7-842a-e4a2d6221546.png">

- [x] <img width="1440" alt="Screenshot 2022-12-10 at 9 10 49 PM" src="https://user-images.githubusercontent.com/103238069/206863279-d7187f78-461b-405c-a327-be511b0ac757.png"> 
--> #9434 

- [x] #9477
--> issue from the backend @harshach @mohityadav766, is there a ticket open for this?

- [x] <img width="1440" alt="Screenshot 2022-12-10 at 11 27 20 PM" src="https://user-images.githubusercontent.com/103238069/206868832-4cc7582e-aad6-4124-a031-e6f44bab5bf7.png">
--> #9434 

- [x] <img width="657" alt="Screenshot 2022-12-11 at 2 14 21 PM" src="https://user-images.githubusercontent.com/103238069/206894712-f45183d6-3b94-41d2-8cf8-15f6026e38cd.png">

- [x] By default right panel should be open for top entity 
- [x] Selected entity should be highlighted with blue border
<img width="1440" alt="Screenshot 2022-12-11 at 10 27 59 PM" src="https://user-images.githubusercontent.com/103238069/206917461-18ea214f-291d-4b00-ba38-972be02ca66f.png">

- [x] Only one link button at a time, Either "View More" or "View Less"
<img width="283" alt="Screenshot 2022-12-11 at 11 08 45 PM" src="https://user-images.githubusercontent.com/103238069/206919528-50e5c284-0896-4914-b132-16fad8a32821.png">

- [x] Add top padding in left panel -> https://github.com/open-metadata/OpenMetadata/pull/9403
- [x] KPI button should be aligned to page title -> https://github.com/open-metadata/OpenMetadata/pull/9403
<img width="1440" alt="Screenshot 2022-12-12 at 12 00 23 AM" src="https://user-images.githubusercontent.com/103238069/206921917-7292e599-1517-4c8d-9c4a-69de7461272b.png">

- [x] Icon colors and selection colors are not right -> https://github.com/open-metadata/OpenMetadata/pull/9403
<img width="304" alt="Screenshot 2022-12-12 at 12 03 38 AM" src="https://user-images.githubusercontent.com/103238069/206922075-4af1abb5-eb93-4cac-abc7-f5cf063b6f8a.png">

**Comment by harshach** [comment]
@devyani-kaushik on many pages we have lot space left but we are using same pagination size, looks odd. Lets cover that in these improvements cc @TeddyCr

**Comment by harshach** [comment]
- [ ] slack chat icon overlaps the tag buttons 
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/38649/207982954-c937a07d-7350-4e62-809c-f08d3219eeb3.png">

**Comment by Sachin-chaurasiya** [comment]
Closing this as all improvements are done.
