### ISSUE TITLE
add Licensing tab inside settings page

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#9254]
**Feature**
Add feature issue reference
Create pricing plan page in OMD

**Describe the task**

Create a page where users can easily navigate to the pricing plan for OMD. Something similar to what shown in below image

![image](https://user-images.githubusercontent.com/12962843/207054693-e0bb400f-c6bf-43da-bd12-ed0d6ca24203.png)

**Comment by sureshms** [comment]
This is Collate SaaS related issue not related to OpenMetadata.
