### ISSUE TITLE
Issue while creating Glossary

### ISSUE THREAD

**Issue by eeshan-deshpande** [open-metadata/OpenMetadata#9272]
Affected module - Glossary

Description-
When we try to create 3rd level Glossary term, it is giving error "An exception with message [null] was thrown while processing request."
Example- A->B->C, when we try to create C it is giving above error

Expected behaviour- We should be able to created nested or hierarchical Glossary terms.

Version - Latest version 0.13.0
Attached is error log as well as network details of html page.
Error in backend log file - 
"[13/Dec/2022:11:08:45 +0000] "GET /api/v1/config/jwks HTTP/1.1" 200 454 "-" "Java/11.0.17" 1
INFO [2022-12-13 11:08:45,533] [dw-7762 - POST /api/v1/glossaryTerms] o.o.s.e.CatalogGenericExceptionMapper - exception
java.lang.NullPointerException: null
ERROR [2022-12-13 11:08:45,533] [dw-7762 - POST /api/v1/glossaryTerms] o.o.s.e.CatalogGenericExceptionMapper - Got exception: [NullPointerException] / message [null]
java.lang.NullPointerException: null"

Network details from HTML page-
General->
Request URL: HOST:8585/api/v1/glossaryTerms
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 10.242.64.123:8585
Referrer Policy: strict-origin-when-cross-origin

Response Header->
Content-Length: 91
Content-Type: application/json
Date: Tue, 13 Dec 2022 11:05:07 GMT

Request Headers->
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzQm90IjpmYWxzZSwiaXNzIjoib3Blbi1tZXRhZGF0YS5vcmciLCJleHAiOjE2NzA5MzMwNDAsImlhdCI6MTY3MDkyOTQ0MCwiZW1haWwiOiJhZG1pbkBvcGVubWV0YWRhdGEub3JnIn0.M83XrS045fl4fadKsgMT4yM7lMKMMH8JvUWSHJ484j-01Oq_jHa6h8WwrzVF_bVCbz2xx2ABasOs_ZBZLyZl_1VsWN5jwWWyU9UzBFm48QTtEfW9YuRZCxy451N84oDorbg0BoJc4ZEXLp6sXSvAiYorL_QcGu00VZKj6YFtZURgIBNCZ7yCnvDmxjARBfAnNjxVLp7pmPqLcUFH4g8s_skzboRXze_F4yrCEuSTeTesXYAA6KIHId2eCx3uAacRHnq7gOTC9O9thQdaEktQ4FWH20O7FzaUCRxX7wAkeq79ScWcYaXlMXFciqgq7jBJ-prava0WzfGzzIY67-AfkQ
Connection: keep-alive
Content-Length: 282
Content-Type: application/json
Cookie: VERSION_0_13_0=true; __session=%7B%22id%22%3A%22101ecd26-b791-4f7d-a4e5-67e2425b35e9%22%2C%22created%22%3A1670929439396%2C%22createdAt%22%3A%222022-12-13T11%3A03%3A59.396Z%22%2C%22expires%22%3A1670931259385%2C%22expiresAt%22%3A%222022-12-13T11%3A34%3A19.385Z%22%2C%22modified%22%3A1670929459385%2C%22modifiedAt%22%3A%222022-12-13T11%3A04%3A19.385Z%22%7D
DNT: 1
Host: HOST:8585
Origin: HOST:8585
Referer: HOST:8585/glossary/Entity/term/Entity.Cash%20Flow/add-term
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

Have replaced actual server with HOST.

**Comment by harshach** [comment]
@eeshan-deshpande this has been fixed in 0.13.2
