### ISSUE TITLE
CORS resolve

### ISSUE THREAD

**Issue by Jaytimbadia7** [open-metadata/OpenMetadata#9278]
What we are trying to do is that we have deployed OM using docker on our org-server. Now we have our angular application which needs to access this API's.
We are getting CORS error when we are trying to use Open-Metadata API for our internal angular application. Is there any restriction from backend? How can I resolve this? Where to add allow all origins?

Can you please help us enable this?

**Comment by Jaytimbadia7** [comment]
Hi @chirag-madlani 

We have org-angular application which needs to access this APIs for dev & production. 
We do have OM server running.

What kind of proxy are you talking about for development? We can try that.  

 Jay

**Comment by chirag-madlani** [comment]
Hi @Jaytimbadia7 

I meant to proxy like something mentioned here: https://betterprogramming.pub/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d

**Comment by Jaytimbadia7** [comment]
Yes. we have tried this with Nginx. It's still showing the CORS error. 

Let us know for any other solution of you might have else if possible you can let us know what changes to make on which side to resolve the same!

**Comment by chirag-madlani** [comment]
Can you attach the error screenshot as well, So that it will be easy to find the solution, Also what you will get when you tried above with Nginx, It was same or different?

**Comment by sureshms** [comment]
It is better to take this issue on OpenMetadata slack support channel. Please only open an issue when it is confirmed as a bug. In a lot of cases, there are deployment issues and setup issues that can cause this.
