### ISSUE TITLE
Add lineage details for other entities

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9281]
Currently, we are using lineage details to pass col-level lineage. Let's update the implementation on the UI (and possibly backend/ingestion) to handle:
- task-level lineage for Pipelines [maybe not, since pipelines are edge now]
- chart-level lineage for dashboards 
- feature-level lineage for ML Models
- field-level lineage for topics
- dashboard datamodel

**Comment by pmbrull** [comment]
Re Pipelines & tasks: https://openmetadata.slack.com/archives/C02B6955S4S/p1684146703741239

```
 i am suggesting like this :- Tasks <> Table  instead of Pipeline <> Table (which is the case currently ) .
Though this might be very specific usecase. but it helps as when different tasks are working with different tables inside same pipeline.
```

**Comment by VarshaNagpal** [comment]
Hi Open Metadata team, 

Could you please enable the column level lineage for Power BI dashboards to Snowflake columns ? And please let us know the ETA for the same.

Regards,
Varsha
