### ISSUE TITLE
Airflow CI failing - Operational error

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#9286]
Airflow Apis Test workflow fails with this

       if len(data) < num_bytes:
                  self._force_close()
      >           raise err.OperationalError(
                      CR.CR_SERVER_LOST, "Lost connection to MySQL server during query"
                  )
      E           sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
      E           (Background on this error at: https://sqlalche.me/e/14/e3q8)
      
      env/lib/python3.9/site-packages/pymysql/connections.py:748: OperationalError

ref: https://github.com/open-metadata/OpenMetadata/actions/runs/3692216655/jobs/6250888697#step:14:644

**Comment by harshach** [comment]
this I've seen with Airflow. Our Airflow container loses connection periodically to the mysql. Let's look at the default values connection settings on Airflow. Our DB container can get busy during the ingestion as we are writing lot of data. So we can increase the timeout values on the airflow side

**Comment by caupetit-itf** [comment]
Hello ! is this issue still a thing ? we are having this error when deploying an ingestion with bigquery and dbt from gcp buckets, did you manage to get rid of it ? (we are using your helm chart)

**Comment by pmbrull** [comment]
Hi @caupetit-itf thanks for reaching out. We're looking into this. We'll update the issue with our findings. Thanks!

**Comment by pmbrull** [comment]
Looks like setting `SET GLOBAL net_read_timeout = 600;` in MySQL got it working for some users. We're validating the approach as well and will change the db image if needed.

Thanks
