### ISSUE TITLE
Backend: markdown text issue in activity feed

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#9414]
The text here should "Test case xyz is failed" and "Test Case xyz is passed" 
original comment -> https://github.com/open-metadata/OpenMetadata/issues/9184#issue-1480682939

<img width="633" alt="image" src="https://user-images.githubusercontent.com/1417689/206069554-83d3d812-b11f-431b-9044-2f3bccd35f66.png">

**Comment by mohityadav766** [comment]
this is don't
