### ISSUE TITLE
UI: Inconsistency in left panel

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#9431]
- [ ] Inconsistent section headers font styling as shown below. The first one feels more pleasing to my eyes at least.
**As discussed with @harshach we will hold this one for 0.13.1 and do it on 0.13.2**
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1417689/206071571-d4b03ba5-3938-4968-9d18-d790aa4fe77f.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1417689/206071673-8342ddac-d94c-4d14-9dd4-1188f748dfd8.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/1417689/206071785-df71c486-082a-4d82-b691-bc2ea5a25503.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/1417689/206071886-aabefe2c-787a-40a6-9734-3a0668aa0714.png">

_Originally posted by @sureshms in https://github.com/open-metadata/OpenMetadata/issues/9184#issuecomment-1340283456_

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=17264%3A20846&t=lXpXA2t6pSj0qTNR-1
