### ISSUE TITLE
UI: Improve the Markdown editor toolbar

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#9432]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
When used in a modal, the markdown editor toolbar does not show the `more` button for better visibility of options resulting in an overflow of options

**To Reproduce**

Screenshots or steps to reproduce
<img width="743" alt="Screenshot 2022-12-20 at 7 29 48 PM" src="https://user-images.githubusercontent.com/51777795/208685145-bc7c4cd8-4a88-41b4-a8e6-6d24727fe5a9.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Fixed in #9486
