### ISSUE TITLE
UI: asset preview improvement

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#9433]
- Instead of multiple rows, this  -- @devyani-kaushik will sync with @sureshms & @harshach around this
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1417689/206067527-3d28797b-d085-47b7-b5b1-e1ffcb53bdcb.png">
might be better shown compactly as on dataset details page - 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/1417689/206067581-652fc559-d391-442a-8cd0-cb9560e17a64.png">

original:- https://github.com/open-metadata/OpenMetadata/issues/9184

**Comment by chirag-madlani** [comment]
Update:

We will show details that are not present in Explore cards
- For lineage, we might show additional details hence vertical layout will be applicable 
- While for explore will go for what we have on Entity Details page

**Comment by chirag-madlani** [comment]
We don't need any update on this for now hence closing it
cc: @harshach @sureshms
