### ISSUE TITLE
Service count mismatch issue.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#9477]
![image](https://user-images.githubusercontent.com/59080942/209060440-900c7da0-d974-43fd-a851-72791f016174.png)

**Comment by harshach** [comment]
@Sachin-chaurasiya ??

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya ??

@harshach , I have updated the title and attached the screenshots.

**Comment by harshach** [comment]
already fixed

**Comment by Sachin-chaurasiya** [comment]
> already fixed

Thanks for verifying @harshach.
