### ISSUE TITLE
Data Factory metadata Ingestion

### ISSUE THREAD

**Issue by pauloventurab** [open-metadata/OpenMetadata#9491]
**Is your feature request related to a problem? Please describe.**
Well, not a problem, but something it would be really great.

**Describe the solution you'd like**
Data Factory metadata (Azure) ingestion

**Comment by Ossy81** [comment]
any plans to have this in? Or someone who could see how we could add this via API

**Comment by tanakpad** [comment]
Any plan on ADF integration?

**Comment by aemnathanclinton** [comment]
I work with several state agencies across the country using ADF and Synapse Pipelines.  I would love to see support for this and more Azure products.
