### ISSUE TITLE
UI: check node minimum version

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#9495]
These arises because one of the user faces the minimum requirement for node
`error @rjsf/antd@5.0.0-beta.12: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.9"`

ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1671709954829909?thread_ts=1671537690.646529&cid=C02B6955S4S

**Comment by chirag-madlani** [comment]
Docs updated with latest node version
