### ISSUE TITLE
Do not list bot users in the users' list or remove the delete option for the system's users

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#9497]
**Affected module**
UI/Backend

**Describe the bug**
We are listing bots in the users' list, which can be deleted.  We should:
1. List them but remove the possibility of removing them from UI.
2. Stop listing them.

Before deleting a bot user, we should check if it is associated with a bot.

**To Reproduce**
Search `ingestion-bot` in the list of users.

**Expected behavior**
It should:
1. Gray out the delete button
2. Stop listing them

In any case, do not allow delete a user if it is associated with a bot.

**Version:**
 - OpenMetadata version: 0.13.0

**Additional context**

**Comment by nahuelverdugo** [comment]
Moving this to 1.0 since the change affects the elasticsearch user_index_mapping and we will require some more time.

**Comment by harshach** [comment]
@Ashish8689 is this coming in suggest ?

**Comment by harshach** [comment]
@Ashish8689, please pass the following flag
http://localhost:8585/api/v1/search/query?q=*+AND+isBot:false&from=0&size=10&index=user_search_index
cc @chirag-madlani

**Comment by harshach** [comment]
also lets make sure we add a test for this.

**Comment by Ashish8689** [comment]
@harshach  yes, will be adding that.

**Comment by harshach** [comment]
@Ashish8689 opened a PR with a fix https://github.com/open-metadata/OpenMetadata/pull/10558
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/38649/224798022-03b44cc4-9cb8-4259-95b8-60fc4b59928e.png">
