### ISSUE TITLE
Deleting a role could cause side effect of a logged user

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#9504]
**Affected module**
Backend

**Describe the bug**
When deleting a role in OM, the role is removed from the `RoleCache`. However, the `SubjectCache` used heavily to perform the permissions checks to different actions and resources has a `UserCache` where the user stored there could have a reference to the deleted `Role`. This will lead us to an entity not found error when requesting permissions to any resource.

**To Reproduce**

1. Create a user
2. Create a role
3. Login with the user and delete the role
4. Try to access to any part of the app
5. A entity not found error will appear

**Expected behavior**
Created User does not see any error and stops having the deleted role.

**Version:**
 - OpenMetadata version: 0.13.0

**Additional context**
Once we delete a role from the app, we should update the `UserCache` of `SubjectCache` by invalidating all the users that has the deleted role. The same should happen when deleting a team with the `TeamCache` of `SubjectCache`.

**Comment by sureshms** [comment]
@nahuelverdugo a lot of code has changed related to this. Can you see if this error still happens?

**Comment by nahuelverdugo** [comment]
@sureshms, this is still happening. As soon as I delete the role, the user who is assigned to the role gets this error:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/11074908/229448653-5977ddbc-5fd3-4bc0-9886-8249f401aeac.png">

I followed the steps described in the issue to reproduce the error.

**Comment by harshach** [comment]
This is fixed
