### ISSUE TITLE
Addition _patch methods added to Python SDK

### ISSUE THREAD

**Issue by gf-atebbe** [open-metadata/OpenMetadata#9509]
There are some very helpful methods in the Python SDK to update data, such as patch_description and patch_tag.  It would be helpful to have similar methods to patch an owner, and possibly even displayName and name and/or fullyQualifiedName.  This is particularly useful for tables ingested from a DataLake service, where these properties are not set as part of the ingestion pipeline.  Currently, when a table is imported from a json file on s3, the fullQualifiedName is s3path/filename.json, which is not very user-friendly.  It would be great to be able to update this name easily to a more human-readable name.  The owner and displayName of the table can be set with the code below, but the name and fullyQualifiedName cannot because they are object types that do not serialize to json.  It would be very helpful to add additional patch_ methods to the Python SDK to make these updates easier.

metadata.client.patch(
    f"{metadata.get_suffix(Table)}/{table_uuid}",
    json.dumps(
        [
            {
                "op": "replace", # or add
                "path": "/owner",
                "value": {
                    "type": "user",
                    "id": f"{user_id}"
                }
            }
        ]
    )
)

**Comment by pmbrull** [comment]
hi @gf-atebbe, name and FQN (fullyQualifiedName) are internal unique identifiers and cannot be modified.

Regarding S3 sources, we'll be revamping the Datalake process. More details here https://github.com/open-metadata/OpenMetadata/discussions/8124.

For now we don't have plans to add these patch methods you mention. The current ones are defined here https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py. Feel free to open a PR with these additions.

Thanks
