### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#9535]
- [x] All the search results are being highlighted with a blue border. Only the selected one should be highlighted  -> @Ashish8689 
<img width="1440" alt="Screenshot 2022-12-28 at 12 31 12 PM" src="https://user-images.githubusercontent.com/103238069/209772312-b4862be2-e719-4ec9-a39e-3e6d67f994e2.png">

- [x] MlModel is repeated in Data Insights page. cc @harshach 
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1417689/210023056-a4e29ee6-be69-478b-b095-520d56a67999.png">

- [x] NaN% in Data Insights page (see Tier 5 below) -> @Ashish8689 
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1417689/210023128-29edfffa-4b67-443c-9db8-f8b90506e405.png">

- [x] GlossaryTerm being viewed is less emphasized than its parents (reverse of what we do for data assets)
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1417689/210023233-75cc817e-2b2a-4d18-91c5-4f57ed839e4c.png">

- [x] Add a profile picture for the ingestion bot (and other bots) -> We already having  image for bots in Bots Page 
- [x] Make Group as the default type instead of Department  -> @Ashish8689 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1417689/211165576-bf7e2577-10f2-463c-81e0-04356812b5eb.png">

- [x] Clicking the markdown guide in teams page results team being created. This could be true for other pages as well -> @Ashish8689 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1417689/211165663-08a4f63d-c95f-4597-8bc9-579a6caec333.png">

- [x] Ownership search is not working correctly. Search for Data and only team Data appears and Data_Platform is not provided as a choice.  - cc @chirag-madlani and @harshach    -> @Ashish8689 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1417689/211406943-e24baee5-0958-4edc-82cc-416ced4db751.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/1417689/211407045-727097df-8c0c-4383-b1cf-b4f1937ba7cd.png">

**Comment by Ashish8689** [comment]
- [ ] Convert add service select to antd one -> @Ashish8689 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66266464/211996753-4f9e4d11-44ea-4241-aeb0-01bcad3de76e.png">

- [ ] Convert add ingestion select to antd one -> @Ashish8689 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66266464/211996894-d3dfd972-5440-4989-9ac4-20255655869e.png">

**Comment by chirag-madlani** [comment]
- [ ] Tags count is missing int the UI -- @chirag-madlani 

<img width="909" alt="Screenshot 2023-01-16 at 11 20 50 AM" src="https://user-images.githubusercontent.com/12962843/212607443-b51670dd-09c1-4c75-ad8c-f9d84742e718.png">

**Comment by aniketkatkar97** [comment]
- [ ] Highlighted characters' cases are not proper in options for 'Search Dropdowns'. --> @aniketkatkar97 

<img width="252" alt="Screenshot 2023-01-16 at 7 50 04 PM" src="https://user-images.githubusercontent.com/51777795/212700322-355f103f-2d70-4464-b8a1-fc914bc7af2b.png">
<img width="239" alt="Screenshot 2023-01-16 at 7 50 20 PM" src="https://user-images.githubusercontent.com/51777795/212700333-251c5f7a-48ae-4cb3-a898-bb1f156b65f5.png">

in the above case options should show the original displayName as 'Aaron Johnson' and not 'aaron Johnson' or 'AAron Johnson'

**Comment by Ashish8689** [comment]
Pending UI changes will be going to be a part of 1.0.

**Comment by Ashish8689** [comment]
Antd select is the duplicate issue from https://github.com/open-metadata/OpenMetadata/issues/10052, will be covering it in that issue.
