### ISSUE TITLE
SQL lineage does not handle column lineage for CTEs, wildcard and line comments

### ISSUE THREAD

**Issue by martsec** [open-metadata/OpenMetadata#9536]
**Affected module**Ingestion

**Describe the bug**
The query parser does not correctly handle Common table expressions, Line comments and Wild cards. Those are common things to find in SQL files for DBT so IMO it should handle it well

**To Reproduce**
Have some models in dbt with the following equivalent query:

```sql
        SELECT
            ID,
            -- A comment here
            NAME
        FROM TESTDB.PUBLIC.USERS
        ;
```

```sql
         WITH cte_table AS (
           SELECT
             USERS.ID,
             USERS.NAME
           FROM TESTDB.PUBLIC.USERS
        ),
        cte_table2 AS (
           SELECT
              ID,
              NAME
           FROM cte_table
        )        
        SELECT 
          ID,
          NAME
        FROM cte_table2
        ;
```
```sql
SELECT * FROM TESTDB.PUBLIC.USERS
```

**Expected behavior**
We should obtain a correct column lineage, from source to target

**Version:**
 - OS: Ubuntu
 - Python version: 3.10
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: 0.13.1

**Additional context**
I'll open a PR with the changes I have done

**Comment by pmbrull** [comment]
While this issue was addressed in https://github.com/open-metadata/OpenMetadata/pull/9537, we might need to validate the behavior with the new sqllineage

**Comment by ulixius9** [comment]
Closing this ticket as this is already handled.
