### ISSUE TITLE
Addition PATCH method to update Owners in SDK

### ISSUE THREAD

**Issue by jsuarez-ravenpack** [open-metadata/OpenMetadata#9544]
Currently we are not able to update via SDK  the owners of the Tables, Schemas, DBs

**Describe the solution you'd like**
Ideally we can have a method in python to updates them. 
This  will help with the fully automation of features of OM objects in python. without it it means that we have to assign owners manually.

**Comment by jsuarez-ravenpack** [comment]
Slack conversation https://openmetadata.slack.com/archives/C02B6955S4S/p1672320541294059?thread_ts=1672317548.812169&cid=C02B6955S4S

**Comment by pmbrull** [comment]
The implementation can follow any example of https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
