### ISSUE TITLE
Fix sonar cloud flagged issues

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#9546]
Some issues to get started - Variable naming issues https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS6213&severities=MAJOR&id=open-metadata_OpenMetadata and https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS115&severities=CRITICAL&id=open-metadata_OpenMetadata

Other issues are here if someone wants to work on it - https://sonarcloud.io/project/issues?resolved=false&id=open-metadata_OpenMetadata

**Comment by PennVanan** [comment]
Please assign me to this issue @sureshms

**Comment by sureshms** [comment]
@PennVanan assigned the issue to you.

**Comment by lap1597** [comment]
I would like to work on this!

**Comment by PennVanan** [comment]
I’m working on this

**Comment by mgg143** [comment]
Hi, @PennVanan . There appear to be over 650 issues across the three links that @sureshms shared.

Could you please specify which of them you are working on? That way, other individuals interested in addressing some of the other issues can make progress on those without worrying about doing potentially redundant work.

Thanks in advance :)

**Comment by PennVanan** [comment]
I'm working on the Critical & Major issues: https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS6213&severities=MAJOR&id=open-metadata_OpenMetadata and https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS115&severities=CRITICAL&id=open-metadata_OpenMetadata

**Comment by ItsBaiShiXi** [comment]
Hi, @PennVanan, thank you for your reply! We will work on some of the issues in this link: https://sonarcloud.io/project/issues?resolved=false&id=open-metadata_OpenMetadata

**Comment by w4ft** [comment]
@sureshms I'd like to take up this issue, especially the last link posted: https://sonarcloud.io/project/issues?resolved=false&id=open-metadata_OpenMetadata. Could I be assigned to this?

**Comment by PennVanan** [comment]
Sure

**Comment by sureshms** [comment]
@w4ft assigned the issue to you

**Comment by sureshms** [comment]
Many sonar issues have gotten fixed. Marking this as closed.
