### ISSUE TITLE
View lineage in Snowflake fails when persist_docs for columns is true in dbt

### ISSUE THREAD

**Issue by fredriv** [open-metadata/OpenMetadata#9548]
**Affected module**
Ingestion Framework

**Describe the bug**
Lineage ingestion fails for views in Snowflake when [persist_docs](https://docs.getdbt.com/reference/resource-configs/persist_docs) config is set to `true` for columns in dbt.

This is due to an issue in the underlying sqllineage library which is unable to find the source tables in this case. I have opened a bug report: https://github.com/reata/sqllineage/issues/322

**To Reproduce**
Create a view in Snowflake in dbt with `persist_docs` config set to `true` for columns. Ingest the dbt models and see that lineage information is not present for the view.

**Expected behavior**
I expect Open Metadata to be able to ingest lineage for views in Snowflake/dbt.

**Version:**
 - OS: Mac OS
 - Python version: 3.9.9
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[snowflake]==0.13.1`

**Comment by OnkarVO7** [comment]
@fredriv are you running the dbt workflow here?
Also are you able to see the view ingested in OM?

**Comment by OnkarVO7** [comment]
@fredriv the view lineage might not be getting creating here because the query parser is not able to parse the query that is used to create the view
We are currently improving our query parser to handle complex queries
If possible could you please share the query that is used to create the view.

**Comment by fredriv** [comment]
Hi @OnkarVO7! 

There is an example query in the `sqllineage` bug report I linked to above. In essence, `sqllineage` doesn't handle a view query has both an explicit column list as well as the select expression inside parenthesis, e.g.

```
create view a.my_view (column_name) as (select some_column from b.my_table)
```

**Comment by OnkarVO7** [comment]
@fredriv parsing this query should be handled in the latest version of OM. Can you please upgrade to the latest OpenMetadata version and try it out again

> Hi @OnkarVO7!
> 
> There is an example query in the `sqllineage` bug report I linked to above. In essence, `sqllineage` doesn't handle a view query which has both an explicit column list as well as the select expression inside parenthesis, e.g.
> 
> ```
> create view a.my_view (column_name) as (select some_column from b.my_table)
> ```

**Comment by fredriv** [comment]
Is that the 1.0 alpha release @OnkarVO7? I can give it a try! 🙂
