### ISSUE TITLE
In-context documentation for Tiers would be helpful

### ISSUE THREAD

**Issue by shannonbradshaw** [open-metadata/OpenMetadata#958]
At the moment, to see the definitions for different Tiers, it is necessary to visit the Settings menu. This is a little hard to find. 

Displaying the documentation for each Tier on hover from the search/filter UI and from the tags from an asset would be a nice addition. Likewise for any tag -- hover shows you a description. Even better if the hover modal included a link for visiting more detailed documentation for that tag.

**Comment by ShaileshParmar11** [comment]
Assign to me
