### ISSUE TITLE
Column description getting deleted when dataLenght/dataType updated.

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#9582]
**Affected module**
Backend

**Describe the bug**
Column description getting deleted when dataLenght/dataType updated.

![image](https://user-images.githubusercontent.com/39544459/210367855-d7a1adca-3590-401e-a1a8-7cd56850ef5b.png)

![image](https://user-images.githubusercontent.com/39544459/210368107-eb49f5b0-3e85-47f9-b65d-14c0f7f1d0f7.png)

support Thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1672724584375769

**Expected behavior**
Ideally changing column dataLenght/dataType should not delete description

**Comment by mohityadav766** [comment]
Fixed
