### ISSUE TITLE
Quick Start Installation Guide on Mac missing dependency

### ISSUE THREAD

**Issue by DaveMurrells** [open-metadata/OpenMetadata#9589]
**Is some content missing, wrong or not clear?**
XCode installation (or a smaller gcc) is a mandatory dependency when executing pip3 install --upgrade "openmetadata-ingestion[docker]" on Mac OS.  Without it the command will fail (see below).  So as a very minor change (I was setting up a new Mac Book) it would be worth adding this to the installation guide

**Describe the solution you'd like**
The docs note python as a dependency and include the command to execute a version check on this.  It would be good to also note that Xcode must be installed (the non developer python that comes by default on Mac is insufficient)

**Additional context**
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -DNPY_NO_DEPRECATED_API=0 -I./pandas/_libs -Ipandas/_libs/src/klib -I/private/var/folders/_1/j2z71w2d0tx8rgfnrqmhb3cm0000gp/T/pip-build-env-5rii9v0y/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/dmurrells/openmetadata-docker/env/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -c pandas/_libs/algos.c -o build/temp.macosx-10.9-universal2-cpython-39/pandas/_libs/algos.o -Wno-error=unreachable-code
      pandas/_libs/algos.c:45:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

**Comment by sureshms** [comment]
@gauthk6 as you go through quick installation can you please update this documentation? cc @TeddyCr
