### ISSUE TITLE
Support for IBM DB Python Libs with arm64 architecture in Ingestion Docker Image

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#9593]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
Ref - https://github.com/ibmdb/python-ibmdb/issues/688
As per the official documentation, 
> Important: The driver for IBM DB2 is not compatible with Apple Silicon and will have to run in emulated mode. Please support [this request for an Apple Silicon version of the driver](https://ibm-data-and-ai.ideas.ibm.com/ideas/DB2CON-I-92) to show IBM that you are interested in a native solution.

Will have to wait for the package owners to provide the support.

**Version:**
 - OS: Mac OS with M1 Library and other OS with arm64 Architecture
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[ibm]`

**Comment by akash-jain-10** [comment]
Hello @pmbrull . Thanks for checking this in. Looks like this will not be possible with our current way of building the Docker Images. Inclusion of `ibm-db-sa~=0.3` just for one architecture is currently not possible. This would require breaking the Dockerfile per architecture basis and then update our whole CI around the same and for the future maintaining multiple docker files per architecture basis.

**Comment by pmbrull** [comment]
@akash-jain-10 opened a draft PR https://github.com/open-metadata/OpenMetadata/pull/11798/files#diff-9b8d4ba36354537e4c53b40ed95233815a556a9eec0a9b58ddf205d0ee93c4ffR84, any reason why that should not work?

**Comment by akash-jain-10** [comment]
Hello @pmbrull . Yes the PR should handle the case of not including the library for `arm64` platform builds.
