### ISSUE TITLE
Allow apostrophe in entity names

### ISSUE THREAD

**Issue by sevdegueldre** [open-metadata/OpenMetadata#9618]
It is currently not possible to use apostrophes in a glossary term's name (term is then invalid).
Lots of expressions in French use d' or l' and it is difficult not to use it in something that should reflect the business language.
Many thanks

**Comment by pmbrull** [comment]
adding @sureshms to the convo hear. Not sure if this should be something that can be achieved via a Display Name. In any case, I think there might be an issue on how the query gets run

```
An exception with message [java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.')) WHERE fullyQualifiedName LIKE 'Balan GLOSS TEST.Demo term 2.another name.%'' at line 1 [statement:"/* GlossaryTermDAO.updateFqnInternal */ UPDATE glossary_term_entity SET json = JSON_REPLACE(json, '$.fullyQualifiedName', REGEXP_REPLACE(fullyQualifiedName, '^Balan GLOSS TEST.Demo term 2.another name\.', 'Balan GLOSS TEST.Demo term 2.hello'world.')) WHERE fullyQualifiedName LIKE 'Balan GLOSS TEST.Demo term 2.another name.%'", arguments:{positional:{}, named:{}, finder:[]}]] was thrown while processing request.
```

**Comment by sureshms** [comment]
@chirag-madlani and @ShaileshParmar11, I have removed `'` from the regex that validates the name. However, we still should not allow `'` for the `Type` name and `Extension` names. In fact, the regex pattern for the names there is "`^[a-z][a-zA-Z0-9]+$` as defined in the JSON schema. Can you please make this change in the validation only for them?

**Comment by ShaileshParmar11** [comment]
> @chirag-madlani and @ShaileshParmar11, I have removed `'` from the regex that validates the name. Please review that change in this patch. However, we still should not allow `'` for the `Type` name and `Extension` names. In fact, the regex pattern for the names there is "`^[a-z][a-zA-Z0-9]+$` as defined in the JSON schema. Can you please make this change in the validation only for them?

Hi @sureshms, as I understood we should not allow `'` for custom property `name` and `type` and we should validate the same with `^[a-z][a-zA-Z0-9]+$` this Regex pattern!

**Comment by sureshms** [comment]
> Hi @sureshms, as I understood we should not allow ' for custom property name and type and we should validate the same with ^[a-z][a-zA-Z0-9]+$ this Regex pattern!
@ShaileshParmar11 that is correct.
