### ISSUE TITLE
CI optimisations 

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#9638]
#### Issue

- Currently CI is taking more than 1 hour to finish all the checks

#### Suggestions

- Reduce time taken by tests runners
- Caching of mvn or yarn will help us in reducing time

**Comment by akash-jain-10** [comment]
- [ ] We also need to figure out a way to reduce Docker Image Build time of Ingestion and Ingestion-Base. Currently it takes around 1 hour 50 minutes to build and publish docker images (cc - @pmbrull, @ayush-shah )
