### ISSUE TITLE
Feature Request: Import of Atlas data by tags

### ISSUE THREAD

**Issue by ryandawsonuk** [open-metadata/OpenMetadata#9647]
I'd like to import existing Atlas data into openmetadata. But if I follow the steps from the [website](https://docs.open-metadata.org/connectors/metadata/atlas#1-visit-the-services-page) to configure ingestion via the UI then I hit this error:

400 Client Error: Bad Request for url: https://<ATLAS_URL>/api/atlas/entities?type=Table

This makes sense as I don't have an entity called 'Table'. But I also don't really want to create one. I have existing entities and I want to import them.

Tables and Topics are core openmetadata concepts so anything imported to openmetadata has to fit into them. This makes sense. But I'm not sure that the ingestion code needs to [hardcode these entity names](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/metadata/atlas/metadata.py#L66) as it currently does.

I'm thinking it could look for entities that have a 'Table' tag on them based on an Atlas glossary. Possibly the user might have to stipulate which glossary or perhaps it would work for the connector to find any entity that has any tag with the name 'Table'. Then it could import the contents of these entities as 'Tables'.

**Comment by harshach** [comment]
@OnkarVO7 lets add a mapping options to map Table -> to a custom type in Atlas
