### ISSUE TITLE
limit tags shown on explore page cards

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#9649]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
- It's showing all the tags upfront on the UI which UI bit difficult, Let's limit it to max 10 and show other on a popover just like we do on Details page

**To Reproduce**

Screenshots or steps to reproduce

<img width="1800" alt="Screenshot 2023-01-09 at 2 35 43 PM" src="https://user-images.githubusercontent.com/12962843/211272771-aa02432e-35ea-4584-87d5-b96fd6c990b4.png">

**Expected behavior**

- We should truncate it to at max 10 tags on explore page

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by vsapucaia** [comment]
Hey @chirag-madlani, thank you so much for creating this ticket. To add to that, in my case here, not only is showing all tags but they are duplicated many times also. My table has 43 columns, 9 of them are tagged with 3 distinct tags. However, the UI displays 40 tags:
![Screenshot 2023-01-09 at 10 24 21](https://user-images.githubusercontent.com/15616773/211276320-6fa109c3-c366-4f41-a297-73136f19c967.png)

**Comment by chirag-madlani** [comment]
@harshach Can we add a filter to exclude column-level tags data from the ES response? 

<img width="1800" alt="Screenshot 2023-01-12 at 11 15 04 AM" src="https://user-images.githubusercontent.com/12962843/211987178-e75ff616-9110-4779-9d78-fbd968589181.png">
