### ISSUE TITLE
IBM DB2 Failure to connect

### ISSUE THREAD

**Issue by vdl-vciriza** [open-metadata/OpenMetadata#9657]
**Affected module**
Affects Ingestion of DB2 databases

**Describe the bug**
Whenever launching a connection test or an ingestion to an IBM DB2 db we get a failure to connect:

Failed to test connection due to {"error": "Connection error from [Engine(db2+ibm_db://usrread:***@10.0.21.16:50000/pttttt)]: Unknown error connecting with Engine(db2+ibm_db://zzzuser:***@XX.XX.XX.XX:50000/YYYY): (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/NT64] SQL0104N An unexpected token \"END-OF-STATEMENT\" was found following \"2.1.2\"} */ SELECT 42\". Expected tokens may include: \"<table_expr>\". SQLSTATE=42601 SQLCODE=-104\n[SQL: /* {\"app\": \"OpenMetadata\", \"version\": \"0.12.1.2\"} */\nSELECT 42]\n(Background on this error at: https://sqlalche.me/e/14/f405)."}

**To Reproduce**

Configure a DB2 connection and Test Connect

**Expected behavior**
Ingestion of metadata from DB2

**Version:**
 - OS: IBM DB2 running on Windows
 - Python version: 3.9 on openmetadata ingestion server (docker)
 - OpenMetadata version: 0.12.1
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[docker]==0.12.1 on which https://pypi.org/project/ibm-db-sa/ was installed manually on airflow python local environment

**Additional context**
Python IBM DB2 support for SQL alchemy installed manually

**Comment by TeddyCr** [comment]
@vdl-vciriza can you upgrade to the latest version. This was fixed here https://github.com/open-metadata/OpenMetadata/pull/6928.

Closing this issue as fixed
