### ISSUE TITLE
[feature-request] Improve lineage icon

### ISSUE THREAD

**Issue by FelipeArruda** [open-metadata/OpenMetadata#9685]
**Is your feature request related to a problem? Please describe.**
Add icons of the technologies that are in the lineage. 
Example: Show Oracle icon, Mysql icon and others in lineage.

**Describe the solution you'd like**
Add technologies icon to lineage and their types (table, view, pipelines, dashboards, all suported by OM), something like the image.

**Describe alternatives you've considered**
First add text to show which kind of technology and object type (table, view and more).
Second add the icon to show what technology are being used.

**Additional context**
![image](https://user-images.githubusercontent.com/5818475/211818930-1f61d3cb-c2b7-4548-96d1-fe19bd0d1b5c.png)

**Comment by pmbrull** [comment]
cc @chirag-madlani @harshach

**Comment by harshach** [comment]
will be fixed as part of this ticket https://github.com/open-metadata/OpenMetadata/issues/12613
