### ISSUE TITLE
Tags show up multiple times on search page

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#9692]
**Affected module**
UI

**Describe the bug**
On Search page, tags are shown as often as they appear on the table. For tags linked to mulitple columns in the table, they are showed for every appearance.

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/211975056-5af8a8ee-49ff-4881-8bc5-6b36772fcc5d.png)

**Expected behavior**
Show tags only once.

**Version:**
 - OS: Chrome
 - OpenMetadata version: 0.13.1

**Comment by chirag-madlani** [comment]
#9649
