### ISSUE TITLE
unrelated tags containting tier show up under Tier search refinement category

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#9693]
**Affected module**
UI

**Describe the bug**
Tags that contain the string "Tier" (e.g. Business Tier) show up under "Tier" search refinement category, even thought they are part of different tag category.

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/211975170-db2b635e-2837-4ae9-9c89-c9cecac72a21.png)

**Expected behavior**
Only Tier1-5 show up under "Tier" tag category.

**Version:**
 - OS: Chrome
 - OpenMetadata version: 0.13.1

**Comment by chirag-madlani** [comment]
@harshach we need to fix it from the Elasticsearch end, We are getting it from the API response
![image](https://user-images.githubusercontent.com/12962843/212036840-f50e2390-487a-4806-a71d-5aef714272fe.png)
