### ISSUE TITLE
Teams show up in lower case

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#9695]
**Affected module**
UI

**Describe the bug**
Owner names are all lower case in advanced search.

**To Reproduce**

![image](https://user-images.githubusercontent.com/102999683/211977349-73df2743-618e-4b12-bc78-d5e70a61cff3.png)

**Expected behavior**
Owner names show up in correct format ("Team", not "team")

**Version:**
 - OS: 0.13.1
 - OpenMetadata version: 0.13.1

**Comment by aniketkatkar97** [comment]
@harshach as we are using aggregate API for initial suggestions, the options shown here are names and not display names.
```
aggregations: {
  "sterms#owner.name": {
    "doc_count_error_upper_bound": 0,
    "sum_other_doc_count": 0,
    "buckets": [
      {
        "key": "aaron_johnson0",
        "doc_count": 1
      },
      {
        "key": "team name",
        "doc_count": 1
      }
    ]
  }
}
```
This issue will be resolved if the 'label' field is sent in the buckets containing the display name. The changes for UI are already present, we just need backend support for this.

**Comment by harshach** [comment]
@chirag-madlani right now we are doing aggregate table's owner.name however if there are no owners assigned to any table this will be empty. 
The other option is to set the owner filed behavior similar to how we show the entity owners with users and teams available in tabs
http://localhost:8585/api/v1/search/aggregate?index=user_search_index&field=displayName
http://localhost:8585/api/v1/search/aggregate?index=team_search_index&field=displayName
