### ISSUE TITLE
Profiler Ingestion is failing for Postgres v11.16

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#9702]
@TeddyCr 
- Profiler Ingestion is failing for Postgres v11.16

Logs are attached.

OM version : 13.1
[profiler ingestion failure -postgress.txt](https://github.com/open-metadata/OpenMetadata/files/10399756/profiler.ingestion.failure.-postgress.txt)

**Comment by TeddyCr** [comment]
closing as fixed with https://github.com/open-metadata/OpenMetadata/pull/9705
