### ISSUE TITLE
oracle TNS inline connection

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9704]
Allow to specify an direct inline oracle TNS entry for connection https://openmetadata.slack.com/archives/C02B6955S4S/p1673516230302759?thread_ts=1673514186.158309&cid=C02B6955S4S

(DESCRIPTION=
  (ADDRESS_LIST=
    (ADDRESS=(PROTOCOL=tcp)(HOST=sales1-server)(PORT=1521))
    (ADDRESS=(PROTOCOL=tcp)(HOST=sales2-server)(PORT=1521)))
  (CONNECT_DATA=
    (SERVICE_NAME=sales.us.example.com)))

support to specify such connections inline directly in the connection details in the yaml

**Comment by pmbrull** [comment]
Hi @geoHeil, is currently any other way to pass these parameters? Or not having this option blocks the ingestion?

**Comment by geoHeil** [comment]
no not blocking. We have to install the TNS configuration inside the dockerfile
