### ISSUE TITLE
support thick mode for oracle connection

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9707]
https://openmetadata.slack.com/archives/C02B6955S4S/p1673526768531769
Please allow to enable thick mode for Oracle https://stackoverflow.com/questions/72385500/error-dpy-3010-when-connecting-python-oracledb-to-oracle-db-11-2 in the oracle connector

**Comment by pmbrull** [comment]
Hi @geoHeil thanks for sharing that, we'll take care of this. Just a followup question on this (not an oracle expert here). Is this thick mode something we can enable globally without impacting other oracle connections, or is this a specific requirement that should be treated separately?

**Comment by geoHeil** [comment]
Yes it should work for all. 

But think mode requires the installation of separate oracle binaries. 


Thick mode: Some advanced Oracle Database functionality is currently only available via Oracle Client libraries. You can install these libraries using the free Oracle Instant Client packages. Python-oracledb works with Oracle Client libraries 11.2 through 21c. See Enabling python-oracledb Thick mode

https://oracle.github.io/python-oracledb/

**Comment by pmbrull** [comment]
- To install the oracle client https://yum.oracle.com/oracle-instant-client.html
- Client 18 should be enough for the majority of [versions](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installation:~:text=Oracle%20Client%2019%2C%2018%20and%2012.2%20can%20connect%20to%20Oracle%20Database%2011.2%20or%20later)

**Comment by geoHeil** [comment]
Indeed. Please use the 18/19 client - only that one is downward compatible with 11 or any other older version.
