### ISSUE TITLE
[BUG] Quality tab - markdown not rendered in suite description 

### ISSUE THREAD

**Issue by itaise** [open-metadata/OpenMetadata#9709]
**Affected module**
UI

**Describe the bug**
I am creating a test suite with a description in markdown format (it has a link).
for example, a suite with this description: [Link to doc](http://www.url.com)
In the main “Quality” tab, the markdown is not rendered as markdown, 
but, when clicking a specific suite, the markdown is rendered properly (a link is shown). 

**To Reproduce**
1. create a new suite in the UI (or via API) with description as markdown (e.g. with a link).
2. the markdown will not render in the quality tab.

Can you please check? 
thank you!

**Version:**
  - OpenMetadata version: 0.13.1

**Comment by sureshms** [comment]
The related tasks are closed. Marking this as done.
