### ISSUE TITLE
Validate snowflake private key connection

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9717]
We had this error on 0.13.1 https://github.com/open-metadata/OpenMetadata/blob/0.13.1/ingestion/src/metadata/utils/connections.py#L339 where we're casting connectionArguments to a dict.

Then, this decorator fails here https://github.com/open-metadata/OpenMetadata/blob/0.13.1/ingestion/src/metadata/utils/source_connections.py#L110 as we are already working with a dictionary.

This issue should be fixed in main with the upgrade of datamodel-codegen as we updated the property. Let's validate that there are no issues coming from this

**Comment by ulixius9** [comment]
closing this as already handled in main!
