### ISSUE TITLE
Glossary search problem

### ISSUE THREAD

**Issue by AnnaShevchuk23** [open-metadata/OpenMetadata#9724]
**Affected module**
Yes, it impact the UI.

**Describe the bug**
Found the following problem with the search in the glossary, which appeared in version 13.1, there was no such problem before. Do I understand correctly that now the search has become case sensitive? For example, 3 terms have been added to the glossary that have the word restructuring in their titles. 2 of them are written in uppercase and 1 in lowercase. When you enter the Rest value in the search, the search finds two values: Restructuring flg and Restruct, as well as some additional values that are in the Credit Agreement category along with Restruct. When you enter the rest value in the search, the search finds only 1 Flag restruct value. Also, when searching in the glossary, OMD gives the following errors: Error while fetching glossary term! and Error while fetching glossary! Previously, case-insensitive search returned all 3 required results without padding. 

**To Reproduce**
If you enter the words "**Rest**" and "**rest**" in the glossary search in the sandbox, you can clearly see the problem
Search result in upper case "**Rest**":
[
![12](https://user-images.githubusercontent.com/120117425/212311484-a682a60e-db80-4b15-8c9e-af59248ddb9b.png)
](url)
Search result in lower case "**rest**":
[
![21](https://user-images.githubusercontent.com/120117425/212311645-8058defa-6944-4e2e-b17b-691fed2c616e.png)
](url)

**Expected behavior**
There are 3 terms in the Glossary that deal with restructuring, I expected that regardless of case, when asked in a search, the search would return all 3 results

**Version:**
-OS: [e.g. Windows 10]
-OpenMetadata version: [e.g. 13.1]

**Additional context**
I recorded a video of the problem in your sandbox, where this problem is clearly visible.
![2023-01-11-14-25-40](https://user-images.githubusercontent.com/120117425/212312668-19d98e30-9909-4ccd-b64f-3034f25c650c.gif)

I would also like to add that reindexing the elastic search did not help.

**Comment by harshach** [comment]
This is fixed in latest release
