### ISSUE TITLE
Fix the ingestion Docker image vulnerabilities for ingestion base image

### ISSUE THREAD

**Issue by Vj-L** [open-metadata/OpenMetadata#9738]
- [ ] libksba/libksba8 - integer Overflow or Wraparound
- [ ] curl/libcurl3-gnutls - Exposure of Resource to the Wrong Sphere
- [ ] libtasn1-6/libtasn1-6-dev - Out-of-bounds Read

**Comment by tutte** [comment]
Options:
- Patch the packages
- Do a custom airflow docker image to use as base
