### ISSUE TITLE
Table isn't found to be added in the lineage

### ISSUE THREAD

**Issue by fredericocotrim** [open-metadata/OpenMetadata#9746]
**Affected module**
It impacts the UI

**Describe the bug**
The table "cleaned_station_status" isn't found to be added in the lineage.

**To Reproduce**

In the sandbox: 
- Edit the lineage of the table [redshift_prod.dev.dbt_jaffle.raw_customers](https://sandbox.open-metadata.org/table/redshift_prod.dev.dbt_jaffle.raw_customers/lineage);
- Add a table and in its search field input "[cleaned_station_status](https://sandbox.open-metadata.org/table/dbt_stefan.default.bike_dlt.cleaned_station_status)"

![image](https://user-images.githubusercontent.com/42280776/212723016-694cbfc8-0a3d-4dfd-a4e7-74b649cba829.png)

![image](https://user-images.githubusercontent.com/42280776/212723048-dc0fc015-d878-47a9-b09e-5b520d576d49.png)

**Expected behavior**
The table "cleaned_station_status" be found the be added in the lineage.

**Version:**
 - OpenMetadata version: 0.13.1

**Additional context**
Slack: [https://openmetadata.slack.com/archives/C02B6955S4S/p1673554889165519](https://openmetadata.slack.com/archives/C02B6955S4S/p1673554889165519)

**Comment by harshach** [comment]
@ShaileshParmar11 please remove the * and * from wrapping the search keyword 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/212786199-d1d3f441-1aea-48ca-9706-5ffc628e4b2e.png">
I think we should be able to use suggest as well here
