### ISSUE TITLE
Can't Add  Atlas Service

### ISSUE THREAD

**Issue by bigdata-spec** [open-metadata/OpenMetadata#9754]
Hi，
    I want to add **Atlas Service** 
    We have atlas Server and I can login **http://10.1x.x.x:21021 by admin/admin**
    when I test connect  
![image](https://user-images.githubusercontent.com/23710717/212795186-0e131187-a792-4437-80de-5540a136d5d0.png)
    Can you help me? Thank you very much.

**Comment by harshach** [comment]
@bigdata-spec did you added "http://" infront of hostandport?

**Comment by bigdata-spec** [comment]
> @bigdata-spec did you added "http://" infront of hostandport?

@harshach Thank you very much, **Apache Atlas work well**
![image](https://user-images.githubusercontent.com/23710717/212795599-4f6b9da2-cc04-4db6-ad9d-e8296738054a.png)

when I don't added "http://"
![image](https://user-images.githubusercontent.com/23710717/212795823-e0d536bf-1e35-4b90-aa4d-6f3ba4882fb0.png)

when I  added "http://"
![image](https://user-images.githubusercontent.com/23710717/212795912-2a278ab7-d05f-49be-ba51-7de557e491a4.png)

**Comment by harshach** [comment]
@NiharDoshi99 please add clear description to the configs with an example.
cc @pmbrull

**Comment by bigdata-spec** [comment]
@harshach @NiharDoshi99 Thank you very much, But I still can't run **test atlas  connection**,
I follower steps:
1.pip3 install --upgrade "openmetadata-ingestion[docker]"
2.metadata docker --start

![image](https://user-images.githubusercontent.com/23710717/215250043-9be40aa3-96bc-43ea-ac32-5a9f31ac4123.png)

**Comment by harshach** [comment]
@bigdata-spec are you using 0.13.2 beta release?

**Comment by bigdata-spec** [comment]
> @bigdata-spec are you using 0.13.2 beta release?

@harshach Hi,I just try **quick-start**  [](https://docs.open-metadata.org/quick-start/local-deployment)
![image](https://user-images.githubusercontent.com/23710717/215299088-5ec50484-61cf-4af9-ba70-6067fb8d6229.png)
