### ISSUE TITLE
Ingestion: QuickSight Dashboard

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#9755]
To Track Progress on quicksight dashboard.
This ticket will take care of dashboards and their embed urls, analyses/visuals (charts), lineage around quicksight and other services.

**Comment by ayush-shah** [comment]
sub ticket for #6663

**Comment by lailapatel** [comment]
Thank you for monitoring this ticket.

**Comment by lailapatel** [comment]
Waiting for the next release for the resolution. 
Thanks and Regards
