### ISSUE TITLE
split helm db user permissions

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9765]
https://openmetadata.slack.com/archives/C02B6955S4S/p1673953595835469

split the permissions of the user that sets up the env vs. the user that will be interacting with the DB during the API calls,

**Comment by pmbrull** [comment]
cc @harshach if you have any thoughts here

**Comment by pmbrull** [comment]
based on the slack conversation: Adding this feature might complicate the usual setup for the majority of users.

A possible workaround for now is to work with 2 different YAMLs pointing to the db with different users, one used for bootstrapping and the other for spinning up the server.

For now, we won't work on this to keep things simple.

Thanks
