### ISSUE TITLE
UI: Error thrown when showing summary panel for deleted data asset.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#9768]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
An error is thrown when we click on soft deleted data asset card on explore page.

**To Reproduce**

Screenshots or steps to reproduce
<img width="1440" alt="Screenshot 2023-01-17 at 7 46 13 PM" src="https://user-images.githubusercontent.com/51777795/212922520-532ee31f-0e27-4597-860a-ec09ebe665ca.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@aniketkatkar97 lets fix it in 0.13.2. Looks like you might not be passing deleted=true flag to the APIs

**Comment by aniketkatkar97** [comment]
@harshach actually this error is thrown because of tableProfiler API. For that, we don't have deleted flag. I'll just avoid making that call for deleted tables.

**Comment by harshach** [comment]
@aniketkatkar97 Yep. lets disable profiler calls
