### ISSUE TITLE
UI: Add cypress tests.

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#9776]
- [x] Cypress for advanced search quick dropdowns -> #9856 
- [ ] Cypress for entity summary panel
- [x] Test to cover all the scenarios for adding tags for all data assets- addition, removal, mutually exclusive tags addition check,etc.

**Comment by chirag-madlani** [comment]
@aniketkatkar97 what's the update on this issue? Is it still pending

**Comment by aniketkatkar97** [comment]
@chirag-madlani  Yes, I will take this up after some priority bugs are taken care of.

**Comment by chirag-madlani** [comment]
Will track Cypress here: https://github.com/open-metadata/OpenMetadata/issues/12016
