### ISSUE TITLE
Configuration to increase session timeout for the web-app

### ISSUE THREAD

**Issue by bmy-ashampoo** [open-metadata/OpenMetadata#9781]
It would be good to be able to increase the existing session timeout. With the current timeout there were a few occasions where I got logged out during documentation. This resulted in the written text being deleted.

**Comment by chirag-madlani** [comment]
Hi @bmy-ashampoo 
Are you being timeout while working or in the ideal condition?
Also can you add more details here like: OMD version, Which SSO, How did you deployed OM currently

**Comment by bmy-ashampoo** [comment]
@chirag-madlani 
It happened after I came back to the OM browser-tab, maybe after 60 minutes. After thinking about it, the problem might not be the timeout itself but that I was logged out **after** I clicked the save button for the documentation. If I was logged out when returning back to the browser-tab, there would be no problem.
OM version is 0.13.0 and we use basic authentication with mail and password. We deployed it in a AWS environment with ECS, RDS and OpenSearch.

**Comment by chirag-madlani** [comment]
Hi @bmy-ashampoo 
With 0.13.2 we have added some improvements.

When you come back to use OMD application we will verify the token and if it's not valid anymore we will ask user to signin again. Let me know if this feature is helping you any way

**Comment by chirag-madlani** [comment]
> Hi @chirag-madlani,
> that sounds good! The remaining question would be what happens to the already written text when I am promted to sign in again? Will I at least be able to copy it to my clipboard?

Can you share the page where you are editing?
I will see the option to retain it

**Comment by bmy-ashampoo** [comment]
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/92018608/216028577-7bc0fd78-7f41-41f9-a1a8-809745a5582f.png">

This would be an example. If I return to the OMD application it would be good to somehow copy this to my clipboard before I will get the promt to sign in again.

**Comment by chirag-madlani** [comment]
@harshach @mohityadav766 Can we Provide and option to configure longer session for Basic auth at least?

**Comment by mohityadav766** [comment]
@chirag-madlani it's already there in config  , or you mean from the UI?

**Comment by chirag-madlani** [comment]
Hi @bmy-ashampoo 
Can you check if this variable will work for you? https://github.com/open-metadata/OpenMetadata/blob/7eba3e6b4a047ed167a0b602d081caca7e6c68f7/conf/openmetadata.yaml#L313

**Comment by chirag-madlani** [comment]
Closing this. Let us know if you have any doubts here
