### ISSUE TITLE
Custom attributes descriptions are not updated

### ISSUE THREAD

**Issue by NithinKumaraNT** [open-metadata/OpenMetadata#9783]
**Affected module**

It affects the UI and the backend.

**Describe the bug**

I stumbled upon a bug with updating the descriptions of the custom attributes (Tables). On saving the update, the UI displays the change but after a refresh of the page, the description is no longer updated.

**To Reproduce**

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/42895864/213134238-c65b295a-c73b-435d-a831-b0347b950b7d.png">

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/42895864/213134324-84040eb7-808f-4e34-a578-6e025086df59.png">

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/42895864/213134381-ca82b6eb-33af-47ce-ac05-2fc3a9ea101b.png">

**Expected behavior**
The description must be updated inplace.

**Version:**
 - Was tested on sandbox environment
 - OpenMetadata version: 0.13.1

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
For more info

Here we are using the `PATCH` API to update the description of the type custom property.

https://sandbox-beta.open-metadata.org/api/v1/metadata/types/3fa9c0e9-7011-4ef3-8284-a8ff4cfe6c53

Payload :

**Comment by sureshms** [comment]
@Sachin-chaurasiya this functionality works and is well-tested in the backend and I can't reproduce this. Can you copy the request and response?
