### ISSUE TITLE
Make max history days configurable in Profile and QA results

### ISSUE THREAD

**Issue by JahJajaka** [open-metadata/OpenMetadata#9794]
**Is your feature request related to a problem? Please describe.**
Currently user can see Profiles and QA results only for interval: 3, 7, 14, 30 or 60 days. This doesn't give enough context for the data updated monthly, quarterly or even yearly.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/54989457/213188396-d47e6aa5-0969-4c58-ab00-d59ccf47178e.png">

**Describe the solution you'd like**
There are two ideas coming to mind:

- Make intervals and max history days configurable. For example filter with options: 30, 60, 90, 120 means INTERVAL=30 days and MAX_HISTORY_DAYS=120. If also make definition configurable (MINUTES, DAYS, YEARS), then user can setup this according to data updating intervals. Then profiling and QA results will become more valuable
- Instead of date/time intervals, display certain number or latest runs in dropdown selection: 100, 200, 300, 400. Approach can be the same like with dates: INTERVAL=100 results, MAX_NUMBER_OF_RESULTS=400.

**Comment by ShaileshParmar11** [comment]
Similar issue https://github.com/orgs/open-metadata/projects/18/views/5?filterQuery=is%3Aopen++assignee%3AShaileshParmar11&pane=issue&itemId=20196867

**Comment by TeddyCr** [comment]
@JahJajaka will be closing this issue as we already have one open 👉 https://github.com/open-metadata/OpenMetadata/issues/10187
