### ISSUE TITLE
Feature Request : Non-tabular data structures and data files repositories

### ISSUE THREAD

**Issue by vchalmel** [open-metadata/OpenMetadata#9799]
Problem :
Open MetaData is strongly oriented towards SGBD databases / schemas and tabular relations and needs to expand its definitions to allow for nested data structures to be able to represent most NoSQL data (ex : elasticsearch, mongodb, or even json and xml files)
Additionnaly The enum for storage services should be expanded to allow for classic files storages (ex : local/lan storage (nfs, dfs, etc.), FTP and HTTP file servers, RSS feeds, etc.) and underlying data structures should be able to represent path-like directories structures and data models.

Solution :
- Expand the storage services enum to allow for a generic/custom storage, and or, a few specific (file system, ftp server, http server, etc.)
- Ability to ingest various industry standards schema definitions (.xsd files, json schemas, csv headers, etc.) and to parse sample files to extract metadata to document various formats for the content of a storage container (xml files or rss feed, json files, csv or parquet files, etc.)
- Allow to define documents, as an alternative to tables a hierarchy mirroring the database / schema / tables could be container / structure / document, We should be able to nest documents definitions with json-schema referencing

**Comment by vchalmel** [comment]
c.f. https://openmetadata.slack.com/archives/C02B6955S4S/p1673875713923919

**Comment by harshach** [comment]
we support elastic, mongodb and other NoSQL sources
