### ISSUE TITLE
<title> in HTML heading should reflect the page you're on

### ISSUE THREAD

**Issue by agger-magenta** [open-metadata/OpenMetadata#9809]
It would be nice if the document title varied with the kind of page you're on in the UI - that would make it easier to make sense of the browser history.

As it is, all the browser's "Back" button tells the user is "Open Metadata", so it's hard to figure out how to get back to the desired page.

![image](https://user-images.githubusercontent.com/4435559/213396795-6d3d0480-53ed-48aa-8307-20da08c3712c.png)

If the title were to reflect that you're on the Explore page, viewing a Table, or what kind of page it is in the specific case, this browser history would be much easier to understand.

**Comment by Sachin-chaurasiya** [comment]
Completed with #10342
