### ISSUE TITLE
Ability to configure the prefixes and suffixes for Elasticsearch Indexes 

### ISSUE THREAD

**Issue by parthasarathy93** [open-metadata/OpenMetadata#9815]
If there are prefixes and suffixes for elasticsearch Indexes, it will be easier for the org to calculate the storage cost ,also do versioning based on datadate.

**Comment by harshach** [comment]
shipped in 1.3.0

**Comment by dispensable** [comment]
@harshach hi i can't find any docs of prefix/suffix config. Could you show me how to config index prefix/suffix ? thank you
