### ISSUE TITLE
add tags from python fails with policies other than default

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#9842]
For me a:

```
metadata.patch_tag(Table,table_entity.id,'Tier.Tier3')
[2023-01-20 14:18:24] WARNING  {OMetaAPI:patch_mixin:78} - Cannot find an instance of 'ModelMetaclass' with id [__root__=UUID('4f300348-5c37-47c7-884a-8b0cc7bb4a82')].
```

is the result of using another ingestion bot with non-default policies.

1. How can I get working policies which allow me to write  the tag
2. Can the error message be made clearer to understand what is going wrong

**Comment by NiharDoshi99** [comment]
Hello @geoHeil , can you please provide what are the rules you have defined while trying to `patch_tag` or can you try adding `Tag` in resource with operation of `editAll`.
I have test it out using same configuration it works.

**Comment by geoHeil** [comment]
unfortunately, I will not easily be able to provide the rules

**Comment by NiharDoshi99** [comment]
Ok. Can you try adding `Tag` and `Mlmodel`  in resource with operation of `editAll`?
If you have any questions let us know.
