### ISSUE TITLE
Add option to redeploy all workflows in a single place

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#9847]
**Is your feature request related to a problem? Please describe.**
After updating the ingestion-bot credentials we have to redeploy all the workflows.

**Describe the solution you'd like**
Option to redeploy all the workflows from UI or using the CLI.

**Describe alternatives you've considered**
Manually do it.

**Additional context**
N/A

**Comment by pmbrull** [comment]
we can add this after migrations

**Comment by pmbrull** [comment]
this is also needed for argo upgrades
