### ISSUE TITLE
Support Google Secret Manager

### ISSUE THREAD

**Issue by yu-iskw** [open-metadata/OpenMetadata#9875]
**Is your feature request related to a problem? Please describe.**
We would like to store sensitive information in Google Secret Manager, as OpenMetadata already supports AWS Secrets Manager.

- https://docs.open-metadata.org/deployment/secrets-manager
- https://cloud.google.com/secret-manager/docs

**Describe the solution you'd like**
We implement features for Google Secret Manager in OpenMetadata.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pmbrull** [comment]
Thanks for pinging this. We don't have an expected ETA to add these new connections, as usually we push after it becomes valuable for multiple community members.

In case you'd like to contribute to this, we have some docs here https://docs.open-metadata.org/deployment/secrets-manager/how-to-add-a-new-implementation

Thanks

cc @nahuelverdugo

**Comment by TeodorLungu** [comment]
Could I be assigned to this issue? @nahuelverdugo some help in understanding the structure of how GSM should be implemented would be greately appreciated!

**Comment by nahuelverdugo** [comment]
Hi @TeodorLungu, I have assigned it to you. In the [documentation](https://docs.open-metadata.org/deployment/secrets-manager), you have more information about how to add a new implementation of Secrets Manager.

**Comment by jayampathiadhikari** [comment]
Hi @nahuelverdugo, is this still ongoing or I can take this task if no progression is made yet.

**Comment by harshach** [comment]
@jayampathiadhikari If you are interested I can assign the task to you. Let me know

**Comment by jayampathiadhikari** [comment]
@harshach yes please. Thank you

**Comment by sameeraappana** [comment]
Hi, can i work on this issue?

**Comment by pmbrull** [comment]
hi @sameeraappana, assigned. Thanks!

**Comment by nakaken-churadata** [comment]
Hi. It looks like that the current assignee is too busy to tackle this issue. Can I try to implement this issue in parallel?

**Comment by nakaken-churadata** [comment]
I did to implements storing value to the GCP Secret Manager and getting value from it. It will take a few days to create PR. Wait a moment.

**Comment by nakaken-churadata** [comment]
Long time no see, I finished implementing and testing my code.
So I'll try to create PR for this issue but I have some questions.
Do I have to create documents? If so, Where is the source I have to modify?
Thanks.

**Comment by harshach** [comment]
@nakaken-churadata any update on your PR. Thanks

**Comment by pmbrull** [comment]
closed by https://github.com/open-metadata/OpenMetadata/pull/16505
