### ISSUE TITLE
backend: suggest API for 'ML models' not working properly for 'service_suggest' field

### ISSUE THREAD

**Issue by aniketkatkar97** [open-metadata/OpenMetadata#9876]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
The `suggest` API for 'ML model' assets in not working properly for the `service_suggest` field.

**To Reproduce**

Screenshots or steps to reproduce

https://user-images.githubusercontent.com/51777795/214213850-66126f04-85f1-4fa4-a10c-a0b84ffb3356.mov

**Request URL:** `/api/v1/search/suggest?index=mlmodel_search_index&field=service_suggest&q=mlflow`
**Response object:** 
```
{
    "suggest": {
        "metadata-suggest": [
            {
                "text": "ml",
                "offset": 0,
                "length": 2,
                "options": []
            }
        ]
    }
}
```

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
As discussed on Slack, suggest is not the right way to search with in aggregations.
