### ISSUE TITLE
13.2 improvements

### ISSUE THREAD

**Issue by devyani-kaushik** [open-metadata/OpenMetadata#9879]
- [x] Make the font styling consistent to other categories titles
<img width="238" alt="Screenshot 2023-01-23 at 3 04 19 PM" src="https://user-images.githubusercontent.com/103238069/214217087-112d311b-b0c6-4068-baf2-be49ed3b9c1f.png">

- [x] Add 8px top margin
- [x] Update the font size of title to H1 (font-size: 18px, font-weight: 700)
<img width="1440" alt="Screenshot 2023-01-24 at 10 48 54 AM" src="https://user-images.githubusercontent.com/103238069/214217482-7cfc995e-d9d9-4948-858b-4ac7873c6a1f.png">

- [x] Give a consistent height to trigger, filters and Destination
<img width="1137" alt="Screenshot 2023-01-24 at 10 53 49 AM" src="https://user-images.githubusercontent.com/103238069/214218113-38fd95f8-d537-4910-973a-e8c16bb8f95d.png">

- [x] Activity Feed page is inconsistent to other pages, need to add page title with description and remove the link text
<img width="1440" alt="Screenshot 2023-01-24 at 10 55 56 AM" src="https://user-images.githubusercontent.com/103238069/214218349-6b9b8907-1f19-4382-847b-7878f0d0963b.png">

- [x] Inconsistent top padding
<img width="1440" alt="Screenshot 2023-01-24 at 10 59 50 AM" src="https://user-images.githubusercontent.com/103238069/214218812-506beeee-5d80-4dc2-ab8d-4467874decba.png">

- [ ] Lineage is too zoomed out
<img width="1438" alt="Screenshot 2023-01-24 at 11 02 21 AM" src="https://user-images.githubusercontent.com/103238069/214219147-2ff6e07b-9201-4cbd-887e-496556947341.png">

- [x] Inconsistent Button and font styling (Use the styling from Classifications page)
<img width="335" alt="Screenshot 2023-01-24 at 11 03 33 AM" src="https://user-images.githubusercontent.com/103238069/214219337-ab597cbc-a3e8-48bb-8178-a6a73ff79f8f.png">
<img width="288" alt="Screenshot 2023-01-24 at 11 03 22 AM" src="https://user-images.githubusercontent.com/103238069/214219300-35351a33-3f57-49e3-9e09-c60899992ffa.png">

**Comment by chirag-madlani** [comment]
@devyani-kaushik 
> Lineage is too zoomed out 

This is know implementation so won't be changing it now
