### ISSUE TITLE
Layout shift on table page as new buttons are inserted into the nav

### ISSUE THREAD

**Issue by korompaiistvan** [open-metadata/OpenMetadata#9885]
**Affected module**
UI

**Describe the bug**
When navigating to the table page for a given table in the OM UI, the nav in the header (`#tabs`) receives new items after the first render. This results in a layout shift, which is annoying when the use attempts to navigate before loading has finished.

E.g. when I want to open up a table and see its lineage, I would:
1. Open the page for the table
2. See this UI
![Screenshot 2023-01-24 at 9 33 17](https://user-images.githubusercontent.com/36007115/214247506-147d9ea6-baf3-4990-ada4-72634366c9b8.png)
3. Attempt to click the button labelled Lineage
4. Layout shifts to:
![Screenshot 2023-01-24 at 9 37 00](https://user-images.githubusercontent.com/36007115/214247628-e95fc09e-1a33-47b3-96c8-f6610337a964.png)
5. I end up clicking the Sample Data tab and navigate to that page

**Expected behavior**
Buttons' order should not change after the initial render and without user input. Either of the following options would achieve this. I've listed them in the order of my personal preference:
- The nav should only be displayed once fully loaded
- All buttons/tabs should be available on first render in a deactivated state and activated as appropriate
- New buttons should be inserted at the end of the nav, and not the middle

**Version:**
 - OS: macOS Ventura 13.1 with Chrome 109.0.5414.87
 - Python version: docker image openmetadata/ingestion:0.13.1
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: docker image openmetadata/ingestion:0.13.1

**Comment by aniketkatkar97** [comment]
Fixed in #9957
