### ISSUE TITLE
Rename `gcsCredentials` to `gcpCredentials`

### ISSUE THREAD

**Issue by yu-iskw** [open-metadata/OpenMetadata#9886]
**Is your feature request related to a problem? Please describe.**
That doesn't cause any problem. But, we use the credentials schema to authenticate Google Cloud Platform, not Google Cloud Storage. Something like `gcpCredentials` sounds more natural. For instance, when I created a BigQuery connector, I was a bit upset to fill out information of credentials by `GCS Credentials`. 

![image](https://user-images.githubusercontent.com/1523515/214249973-59aec18f-f877-462b-8628-57dfb2f03814.png)

**Describe the solution you'd like**
We can rename `gcsCredentials.json` to `gcpCredentials.json` and its contents.

- https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/security/credentials/gcsCredentials.json

**Describe alternatives you've considered**
N/A

**Additional context**
- https://openmetadata.slack.com/archives/C02DZK3QH8Q/p1674517036236469

**Comment by pmbrull** [comment]
@MilanBariya when working on this let's review the UI page on the dbt ingestion and see if anything is required from the UI team. I believe that page we build manually not from JSON Schema

**Comment by yu-iskw** [comment]
@MilanBariya I would like to sophisticate `gcsConfig` at the same time of rename, because specifically selecting multiple projects is a bit to optimized to Google Cloud Storage. 

Take an a bit complicated example of BigQuery, for instance. We assume if we would like to ingest metadata of BigQuery in project X and project Y on the right side. Technically, we create a service account in project A. However, we grant no IAMs to it in project B. Instead, we grant `roles/bigquery.jobUser` in project B and `roles/bigquery.dataViewer` in project X and Y respectively. To do that, the service account is authorized in project A. The project ID of a BigQuery client must be project B. 

![image](https://user-images.githubusercontent.com/1523515/221089622-d466486b-1084-43aa-a90b-ad5a305fb117.png)

My proposal is to extract only authorization parts from `gcsConfig`. We reuse the extracted parts to BigQuery , Spanner ans so on . Moreover, we implement a new schema specialized Google Cloud Storage.  What do you think?

**Comment by pmbrull** [comment]
hi @yu-iskw could you please open a separate feature request for this proposal? The goal of this ticket is to align the naming for GCS vs. GCP. We can fine-tune the configuration later on.

Thanks

cc @MilanBariya
