### ISSUE TITLE
create Policies that contains only edit access to table 

### ISSUE THREAD

**Issue by raja-mudhireddy** [open-metadata/OpenMetadata#9891]
**Feature**
I have seen some roles predefined in UI. I want to give the minimum privileges to users, can have access only to edit descriptions, tags  and view sample data in the tables. 

In Data consumer role  users can run or kill the ingestion pipeline. how can I stop/ disable those services to users.

I have created a Policies like below. Still user can view pipelines and run and kill them. please advice. 

![image](https://user-images.githubusercontent.com/73642915/214274744-2ecaf0c1-655a-46c9-a55e-5dbf0d8219b5.png)

**Describe the task**
I am looking for role, where user is not allowed to linage, usage, database service. Only allowed to edit the description of the columns in the table and view sample data

**Comment by chirag-madlani** [comment]
Permissions are not working correctly for Ingestion service actions like: Kill, Run, Stop

**Comment by chirag-madlani** [comment]
@harshach is it done from the Backend?

**Comment by chirag-madlani** [comment]
It's fixed from UI side.

<img width="1512" alt="Screenshot 2023-05-25 at 12 02 59 PM" src="https://github.com/open-metadata/OpenMetadata/assets/12962843/b5196260-3722-4212-8d16-305b134f48ef">
