### ISSUE TITLE
Airflow services (webserver and scheduler) on separate filesystems - disappearing OM dags in Airflow

### ISSUE THREAD

**Issue by jhettler** [open-metadata/OpenMetadata#9904]
**Is your feature request related to a problem? Please describe.**
Hi everyone, 
I have encountered an unexpected behaviour in the ingestion dag deployment from OM to Airflow.

Imagine the situation where all parts (Webserver, Scheduler, Triggerer) of Airflow run separately (in different containers, differents machines, AWS ECS tasks, etc.), in our case this means those Airflow parts have separate filesystem and here comes the issue.

Current implementation of dag deployment from OM to Airflow works via airflow-managed-apis, but this api runs on Airflow webserver, OM sends the request to Airflow webserver (responsible for serving REST API) with DAG describing json and this json is saved in dag_generated_configs folder on Airflow webserver. Unfortunately if Airflow webserver has separated filesystem from Airflow scheduler, dag appears in Airflow for a while and then it disappears. I assume that reason why it disappears is pretty simple, because Airflow scheduler periodically scans Airflow dags folder (by default /opt/airflow/dags/) and tries to catch changes in dags and propagate them in the Airflow database, but as there is no dag on Airflow scheduler filesystem (because it is located on Airflow webserver) it deletes the dag and it dissapears from Airflow.

This works correctly in docker-compose examples because Airflow scheduler and webserver (openmetadata-ingestion) runs in the same container. 

https://github.com/open-metadata/OpenMetadata/blob/339abc5bf33aa3f6b56166145d58fdca0119ed92/ingestion/ingestion_dependency.sh#L45-L46 

**Describe the solution you'd like**
Distribute DAG json file from OM to Airflow scheduler instances (all of instances), not to the webserver. I know it sounds easy, but I have no idea how to distribute and if there is a way.

**Describe alternatives you've considered**
Create shared filesystem under at least Airflow webserver and scheduler.

**Comment by pmbrull** [comment]
Hi, I believe this question might be better aimed to the Airflow community. In any case, if you are using separated instances for the components, the volumes/filesystems need to be shared. Otherwise, the DAGs won't be able to run.

This is the same as with the k8s deployment. You need a shared RWX volume so that when the scheduler discovers DAGs, the workers can also access those files.

Please unify the filesystems and give it another go.

Closing this as it's not related to OM.
