### ISSUE TITLE
Document team of type "group" can own the entities

### ISSUE THREAD

**Issue by focagrande** [open-metadata/OpenMetadata#9913]
**Is some content missing, wrong or not clear?**

You may point out that only teams with type "group" may be assigned as object owners.

**Describe the solution you'd like**

When describing types of teams you may state that only "Groups" can own the objects.

**Comment by stephanesol** [comment]
☝️  Adding to this. It would be helpful if the docs also indicated that once an object is made into a `group` it can't be changed into anything else.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/6843613/224355070-d183eafc-009b-44ec-9b61-56670849490f.png">

**Comment by harshach** [comment]
@ShilpaVernekar lets cover this in Teams & Users section of the docs

**Comment by ShilpaVernekar** [comment]
@harshach Noted 👍

**Comment by sureshms** [comment]
@ShilpaVernekar if this is done, can you please close the issue?

**Comment by ShilpaVernekar** [comment]
Sure @sureshms 
Mentioned in the [Team Structure](https://docs.open-metadata.org/v1.1.x/how-to-guides/quick-start-guide-for-admins/teams-and-users/team-structure-openmetadata) doc as a Note

Also mentioned in the [Team Ownership](https://docs.open-metadata.org/v1.1.x/how-to-guides/user-guide-for-data-stewards/overview-data-assets/data-ownership) section
