### ISSUE TITLE
Cleanup postgres lineage and usage

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9919]
The postgres/lineage.py file is not following the same approach as the rest of lineage sources ([example](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/database/postgres/lineage.py#L49)).

The [process_table_query](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/database/postgres/query_parser.py#L137) is not returning the same object that it says it does.

We should try to align as much as possible this logic here taking Snowflake as an example

**Comment by TonyTumba08** [comment]
I'd like to start taking a look at this issue, could you please assign it to me? @pmbrull

**Comment by pmbrull** [comment]
done, thanks!

**Comment by TonyTumba08** [comment]
I saw on the readme that you guys have a slack where I can potentially ask for help on getting started, however that slack doesn't seem to work anymore. Is there a new up to date link or do you guys not use slack anymore?

**Comment by pmbrull** [comment]
Hi @TonyTumba08, which link are you following? Just checked and https://slack.open-metadata.org/ is redirecting me properly 🤔

**Comment by TonyTumba08** [comment]
Sorry for the late reply, I've been quite busy the past few weeks. You're right though the link does seem to be working now, slack might've been done when I was trying to open it before.

**Comment by BarOffn** [comment]
Hey @harshach,
Is this still relevant? I'd like to take a look at this issue
If so, could you assign it to me?

**Comment by pmbrull** [comment]
hi @BarOffn, thanks for the ping. Assigned it to you

**Comment by TomBushell** [comment]
I would like to work on this issue. Could I get assigned?
