### ISSUE TITLE
Add support for Task deletion

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#992]
Currently in pipelines, the PUT requests merge the previous tasks in a pipeline with the new one from the request. This additive functionality can't handle deletion of tasks. Please update the test `PipelineResourceTest#put_AddRemovePipelineTasksUpdate_200` to enable testing task deletion.

**Comment by harshach** [comment]
@pmbrull we handled it in the latest lineage backend right?

**Comment by pmbrull** [comment]
Yes, now the client is the one who holds the truth. So if we make a put with a set of tasks, those are the ones that are going to be saved in the backend, managing adds/updates/deletes
