### ISSUE TITLE
Simplify lineage and usage inheritance

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9936]
So here we actually have some nasty inheritance working that we might want to simplify in the future because tbh, now that you said it, it has me a bit lost.

Our classes at play are:
- `VerticaLineageSource(VerticaQueryParserSource, LineageSource)`
- `VerticaQueryParserSource(QueryParserSource, ABC)` -> implements `get_table_query` and calls `super().get_table_query()`
- `LineageSource(QueryParserSource, ABC)` -> implements `get_table_query`

So when we run `VerticaLineageSource` it runs the `VerticaQueryParserSource.get_table_query` that then runs `LineageSource.get_table_query`

This works because of the inheritance order of the classes set in `VerticaLineageSource(VerticaQueryParserSource, LineageSource)`. Changing the order does not follow the right calls.

We can find a better to handle this for all lineage/usage sources

Another thing that we need to think about regarding the implementation is that it works right now since we have the specific mro. If a class only subclasses the class calling super().... we could have hard to debug issues.

**Comment by harshach** [comment]
Can we Merge Lineage and Usage into one workflow? The no.of workflows users need to deploy has become too many, and given both of these workflows are reads the same data.

**Comment by pmbrull** [comment]
we wanted to keep it separated to make it easier to debug lineage information, since that would only parse a small subset of queries (and thus making things faster)
