### ISSUE TITLE
Merge Utils with EntityUtil

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#994]
Merge catalog-rest-service/src/main/java/org/openmetadata/catalog/util/Utils.java

into

catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java

**Comment by dec0deit** [comment]
hey @sureshms, I would like to work on this issue please assign to me

**Comment by sureshms** [comment]
Done

**Comment by dec0deit** [comment]
hey @sureshms, I just need to merge the functions and member of the util class into the Entity Util Class and verify the test cases right?

**Comment by sureshms** [comment]
That is correct

**Comment by dec0deit** [comment]
Please review the PR @sureshms 
PR : #1010

**Comment by sureshms** [comment]
@dec0deit, closing this issue. Thank you for your contribution.
