### ISSUE TITLE
Can not ingest redash dashboards

### ISSUE THREAD

**Issue by avignd** [open-metadata/OpenMetadata#995]
Played with open-meta-data and tried to connect Redash locally but I am getting a 404 Client Error: NOT FOUND for the '/api/dashboards/'.

The issue seems to be here:
https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/redash.py#L128

The dashboard slug should be sent instead of the dashboard id, as Redash's API states:
https://redash.io/help/user-guide/integrations-and-api/api

and as done in example here:
https://github.com/getredash/redash-toolbelt/blob/master/redash_toolbelt/examples/clone_dashboard_and_queries.py#L12

If it is ok I will open a PR for the fix.
Also I was wondering if the widgets will be supported too (now they are ignored)

**Comment by harshach** [comment]
Thanks for finding the bug @avignd . Please open a PR if you are interested in taking it up. Assigning the task to you.

**Comment by avignd** [comment]
@harshach no problem.

Opened a fix [here](https://github.com/open-metadata/OpenMetadata/pull/996) 
LMK if adding support of widgets makes sense

**Comment by harshach** [comment]
@avignd adding support to widgets would be great. Can you open a new issue for that
