### ISSUE TITLE
Fix PyLint

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#997]
We need to have a deep look at the `pylint` issues and get the code at 10/10.

Once this is fixed, we'll be able to have the linting as a quality gate for approving new PRs, which will help us in maintaining new code.

**Comment by pmbrull** [comment]
Thanks @TeddyCr for picking this up 🙏 🚀 ❤️

**Comment by harshach** [comment]
@pmbrull is there any thing else need to be done in this ticket, if not lets close it out

**Comment by pmbrull** [comment]
We're still at 8.52/10, but I'll break this down into smaller issues otherwise it is hard to tackle. Thanks!
