### ISSUE TITLE
Ease Business Glossary Accessibility and Enhance Searchability

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#9971]
**Is your feature request related to a problem? Please describe.**
Feature Request: Promote Business Glossary Terms to Exploration search and Enable Search Filters.
Currently Business Glossary is not part of Explore Menu as it only focuses on Tables, Pipelines and so on.  Current search from Business Glossary is hidden away and limited. However, to promote the use and value of Business Glossary, I believe it should be a part of exploration tab. Also, the search needs to be enhanced to help navigation.

**Describe the solution you'd like**

- Business Glossary searchable from Explore tab
- Business Glossary item count visible next to tables count
- Also supports search filters:  able to filer Business Glossary search by "where term's Glossary is XYZ; where term is with a tag XYZ; where term parent term is XYZ;"

![explore](https://user-images.githubusercontent.com/26750060/215160436-68ee9276-bf6e-4456-8d42-e35f6f30b3b6.PNG)

![OMD BG](https://user-images.githubusercontent.com/26750060/215160316-da7278d9-0a7b-4965-91d9-732be7a4fabb.jpg)

**Comment by chirag-madlani** [comment]
Add Glossary & Glossary Term count here. @pmbrull has provided API support here
