### ISSUE TITLE
Add Badge with color or icon for Tags,GlossaryTerm, Domain and DataProducts

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#9972]
**Is your feature request related to a problem? Please describe.**
My task is categorize Business Glossary terms as they are not equal. Some might be just terms, some might represent business data entities, somes data attributes, some reference values, some kpis and so on, However current BG would only allow what via tags. Unfortunately tags are ok if one is searching, but not exploring. Also tags aren't visual and one has to go into the term to see the tag.

**Describe the solution you'd like**
Ability to assign a category to a Business terms and those categories could have different colour or an icon. 
This would make it easier to "explore" and "scan" the glossary for humans :) 

**Describe alternatives you've considered**
I have considered tags, however they don't have an effect that I am looking for.

**Additional context**
I am structuring business glossary as per conceptual data modeling

**Comment by ShaileshParmar11** [comment]
as discussed 
- we will need backend support to store the selected color
- UI will provide color pallet option to select color
- Only glossary will have this feature

**Comment by ShaileshParmar11** [comment]
re-opening the issue as still pending from the frontend side

**Comment by harshach** [comment]
@ShaileshParmar11 can we make async call to load them lazily and cache it on client side?

**Comment by harshach** [comment]
@ShaileshParmar11 also are you getting this as part of TagLabel?
