### ISSUE TITLE
Support @ handle for referencing other items like tables or business terms (rather than URLs)

### ISSUE THREAD

**Issue by DovileKr** [open-metadata/OpenMetadata#9973]
**Is your feature request related to a problem? Please describe.**
We are struggling to get business and data users to share their know-how in a effective manners. For example not duplicating explanations. We want that users reference already documented items rather than re-typing.

**Describe the solution you'd like**
Enable to reference other items like tables or business terms in the Rich Text Description with something like @handle. 
This handle could also become an automatic tag.
For example: I am describing a Profit Term. It would be super convenient to do "Profit is @Revenues - @Costs. " . So it references other business terms. Even better if it could auto become a related term or tag.

**Describe alternatives you've considered**
Using URLs, however it slows down the description and usually means that person won't link it. As one has to go and find url, copy it paste it, save it. We want to make it for our data users writing the descriptions more enjoyable. And people like @handle :)

**Comment by harshach** [comment]
@DovileKr this is already supported @ is for users/teams # is for entities. If this doesn't solve your requirements please re-open
