### ISSUE TITLE
About Add Atlas Service

### ISSUE THREAD

**Issue by bigdata-spec** [open-metadata/OpenMetadata#9984]
Hi, Because OpenMetadata doesn't support Hive lineage，So I try atlas service，But I can't see hive lineage,
my OpenMetadata version is **0.13.2** 
![image](https://user-images.githubusercontent.com/23710717/215311184-2f1f3b74-d23a-426f-ab3f-aa6b32bf53ad.png)
so I try cli 
![image](https://user-images.githubusercontent.com/23710717/215311305-a412510f-f6a0-47b4-a5bc-36cd713f4651.png)
info **Cannot find service for hivedemo - type DatabaseService** 
![image](https://user-images.githubusercontent.com/23710717/215311327-11e4a1eb-53c1-4be3-9add-f43866ae966d.png)

**Comment by NiharDoshi99** [comment]
Hey @bigdata-spec , have you tried passing value for `authProvider`.

**Comment by pmbrull** [comment]
Hi @bigdata-spec could you please check?

**Comment by bigdata-spec** [comment]
> Hi @bigdata-spec could you please check?

@pmbrull @NiharDoshi99  Thank you for your help.  
I'm sorry, but we won't go into that for now
